### ISSUE TITLE
Backpressure

### ISSUE THREAD

**Issue by benjchristensen** [ReactiveX/RxJava#1000]
Thus far Rx has left backpressure solutions "an exercise for the user". It can be done via manual feedback loops and operators like `throttle`, `sample`, `window`, etc.

The drawback of this is that it requires someone understanding the implication of every operator and when it might be async (buffer/queue) and requires the effort to create a feedback loop and hook it up correctly. Some use cases will probably always require this type of manual effort, but it's worth exploring whether we can solve the general use cases within Rx.

Most Rx operators are synchronous in nature meaning the producing thread does not return until the work is completed. The `map` operator is a good example. It does computation work to transform from `T -> R` and nothing else. 

There are some operators though that are async in nature and involve unbounded buffers. These include `observeOn`, `zip` and `merge` (as of 0.17.1 which means `flatMap` is affected). It also happens if an `Observer` is writing the data out to non-blocking IO (such as a Netty channel).

In all of these example, if the producer is fast, such as an in-memory Iterable, loading a file, or a firehose of events over a network, buffer-bloat (and eventually OutOfMemory) can easily occur.

After some experimentation and talking with various individuals, teams and companies about this topic, a possible solution is the use of co-routines from the producing `Observable` that a `Subscriber` can request data from in batches.
#### Prototype Code

A prototype of this is being experimented with at https://github.com/benjchristensen/RxBackpressure though it is not yet complete (as of this writing).

The general idea is that an `Observable.OnSubscribe` implementation could register a producer co-routine with the `Subscriber` and then only push data down when the `Subscriber` has said how much it can receive. It becomes a conditional push-model. The co-routine can then be "parked" by the producer by finishing work and returning (releasing the thread) and then "unparked" or resumed by the `Subscriber` when it wants more. In this way no threads are blocked and only the amount of data the `Subscriber` can handle is sent. The same model can work across threads or across the network.

If the `Observable` chain has no async operators then it will be executed with an "infinite" request and behave exactly as it does today without any parking. 

If an async operator is in the chain then it will "request" a batch size equaling it's internal buffer (say 128, 512, 1024 etc).

A simple producer of an `Iterable` would look like [this](https://github.com/benjchristensen/RxBackpressure/blob/master/rx-bp-prototype/src/main/java/rx/operators/OnSubscribeFromIterable.java) (ignoring debates over naming and API):

``` java
public final class OnSubscribeFromIterable<T> implements OnSubscribe<T> {

    final Iterable<? extends T> is;

    public OnSubscribeFromIterable(Iterable<? extends T> iterable) {
        this.is = iterable;
    }

    @Override
    public void call(final Subscriber<? super T> o) {
        // state is outside the co-routine below
        final Iterator<? extends T> iter = is.iterator();
        // define the co-routine
        Action1<Request> func = new Action1<Request>() {
            @Override
            public void call(final Request r) {
                if (!r.countDown()) {
                    return;
                }

                while (iter.hasNext()) {
                    final T value = iter.next();
                    o.onNext(value);

                    if (!r.countDown()) {
                        // we have delivered all that was requested
                        // so "park" be returning and releasing this thread
                        return;
                    }
                }
                o.onCompleted();
            }

        };

        // register co-routine with Subscriber
        o.setProducer(func);
    }
}
```

The `observeOn` operator is async and thus will request batches as needed. The relevant code looks like [this](https://github.com/benjchristensen/RxBackpressure/blob/master/rx-bp-prototype/src/main/java/rx/operators/OperatorObserveOn.java):

``` java
private void pollQueue() {
    do {
        Object v = queue.poll();
        if (v != null) {
            if (v instanceof Sentinel) {
                if (v == NULL_SENTINEL) {
                    observer.onNext(null);
                } else if (v == COMPLETE_SENTINEL) {
                    observer.onCompleted();
                } else if (v instanceof ErrorSentinel) {
                    observer.onError(((ErrorSentinel) v).e);
                }
            } else {
                observer.onNext((T) v);
            }
        }
        requested--;
    } while (counter.decrementAndGet() > 0 && !observer.isUnsubscribed());
    if (requested == 0) {
        requested += SIZE;
        // request more (starting the co-routine up again)
        request(SIZE);
    }
})
```

The `subscribeOn` operator [decorates the co-routine](https://github.com/benjchristensen/RxBackpressure/blob/master/rx-bp-prototype/src/main/java/rx/operators/OperatorSubscribeOn.java#L79) so scheduling is retained and is started on the desired thread each time rather than the consuming thread doing the work.

``` java
public void setProducer(final Action1<rx.Subscriber.Request> producer) {
    subscriber.setProducer(new Action1<Request>() {

        @Override
        public void call(final rx.Subscriber.Request r) {
            inner.schedule(new Action1<Inner>() {

                @Override
                public void call(Inner inner) {
                    producer.call(r);
                }

            });

        }

    });

}
```

The `take` and `skip` operators compose the batch sizes to adjust accordingly to what is being taken or skipped:
- https://github.com/benjchristensen/RxBackpressure/blob/master/rx-bp-prototype/src/main/java/rx/operators/OperatorTake.java#L93
- https://github.com/benjchristensen/RxBackpressure/blob/master/rx-bp-prototype/src/main/java/rx/operators/OperatorSkip.java#L51

The `Subscriber` manages the life-cycle of when the co-routine is run: https://github.com/benjchristensen/RxBackpressure/blob/master/rx-bp-prototype/src/main/java/rx/Subscriber.java#L97

For example, if the final `Subscriber` in the chain is hit and no async operator was involved it immediately invokes the co-routine with "-1" request size so it is infinite.
#### Example Use Cases

Use case are being written here: https://github.com/benjchristensen/RxBackpressure/tree/master/rx-bp-examples/src/test/java/rx/examples
#### Handling Observables Without Co-routines

Implementing an `Observable` that supports backpressure is more complicated and not all will support it. In those cases the async operators will `onError` stating that an `Observable` is not respecting the backpressure and suggest resolutions (linking to documentation probably).

The two routes at that time are: 1) fix the `Observable` to support backpressure, or 2) use one of several backpressure operators that will be added such as:
- `whileParkedDrop`
- `whileParkedBuffer`
- `whileParkedBufferThenDrop(int maxCount)`
- `whileParkedBlock` (when blocking is okay, such as on Quasar fibers, IO threads, etc)
- `whileParkedUnsubscribe` (such as on a hot stream like mouse events)
#### Outstanding Work

An earlier prototype (not public) had `zip` functioning but the current code does not. We know how it is done and this model works with it but have not yet spent the time to re-implement it. We need to.

The biggest outstanding item is making `merge` work (and thus `flatMap`). This is the major hurdle of any backpressure solution working. 

We (myself, @abersnaze, @headinthebox and others) have whiteboarded it and believe we have a solution but my schedule has not allowed me to code it. I have held off on writing this post as I wanted to code it up first, but since I still haven't had time I wanted to get this information public instead of holding it up.

The planned design for `merge` is that each `Observable` being merged would have it's own buffer (of say 128 items) and then the consumer would request _n_ items which would come in round-robin fashion from all of the merged buffers. Each individual `Observable` would exert it's own backpressure upstream. Slow `Observables` may never fill their buffer while fast ones will. 

We will not attempt to limit the horizontal growth (number of `Observables` being merged) but will limit the vertical growth (size of buffer for each `Observable`).

The challenge with this is making sure performance and fairness are balanced. 
#### Next Steps

1) Finish prototype implementatation of `merge` and `zip`
2) Finish examples across threads and netwwork.
3) Bikeshed and debate APIs and naming conventions
4) Prove or disprove performance/functionality tradeoff.
5) Test long enough to convince ourselves we're not going to cause deadlocks/livelocks/hangs somewhere (co-routines not running).

I look forward to your help making this happen.

**Comment by VesaKarvonen** [comment]
Hello!  In the past couple of months I've put some time into developing a library for reactive/responsive programming based on a pull model called *choice streams*.  I believe that you might find it interesting.

Here is a little bit of prose on the idea:

  https://github.com/Hopac/Hopac/blob/master/Docs/Inverting.md

I must apologise that the above document is somewhat out of date with respect to my improved understanding of Rx and contains a couple of incorrect assertions.

And here is the current reference documentation on choice streams:

  http://hopac.github.io/Hopac/Hopac.html#def:type%20Hopac.Stream.Stream

Summary: It turns out that it is quite possible to do responsive and reactive programming with a pull model.  All you need is lightweight threads, lazy futures/promises and non-deterministic choice.  Even operators like `groupBy` and operations like `delay` (I call it `shift`) can be implemented for choice streams.  Many operations appear to be significantly simpler to implement on pull -based streams than on push -based streams.  The main feature lacking from choice streams is the subscription protocol, which means that operations like `Using` cannot be implemented with comparable semantics.

Please note that choice streams are still work-in-progress and, compared to Rx, there are a few combinators missing that I haven't yet had the time to implement, although I'm confident there will be no problems.  I'm already using choice streams in an actual application for reactive/responsive programming and they have worked without problems.

**Comment by benjchristensen** [comment]
Hi @VesaKarvonen The Reactive Streams and Rx model supports both push and pull to achieve the backpressure. Adopting a completely pull model defeats the point of Rx as that would eliminate all of the data sources that are "hot" that fire events without regard for when we pull from them. A pull-based stream is an Iterable, even if it is an AsyncIterable. 

RxJava has created push/pull implementations of `publish`/`groupBy`/`merge`/etc that all change from push to pull when the downstream can not keep up with push. This may be of interest to you based on your comments in the Inverting document about groupBy and merge. This has all occurred since Erik mentioned the "don't know how to do groupBy" comment. Indeed `groupBy` was tricky to get right with backpressure, but it works with push and pull and moves between them as necessary.

Your document also references closing over locks ... that does not happen in RxJava. It did in very early versions, and it may still do so in Rx.Net, but a lock is never held while emitting in RxJava.

The Reactive Streams Spec is a good document with over a year of collaboration amongst several companies that is applicable to this topic: https://github.com/reactive-streams/reactive-streams#goals-design-and-scope

**Comment by VesaKarvonen** [comment]
Hi @benjchristensen,

> Hi @VesaKarvonen The Reactive Streams and Rx model supports both push and pull
> to achieve the backpressure.

I assume the "Reactive Streams" model refers to the specification in

  https://github.com/reactive-streams/reactive-streams

What do you mean by the "Rx" model?

If, by Rx, you refer essentially to the interfaces [IObservable](https://msdn.microsoft.com/en-us/library/dd782981%28v=vs.110%29.aspx) and [IObserver](https://msdn.microsoft.com/en-us/library/dd783449%28v=vs.110%29.aspx) of .Net, then I don't see how they could support the same push-pull model as Reactive Streams.

Note: My point here is just to distinguish between the different models.  In the rest of this reply, I will use "Reactive Streams" to refer to the referenced specification and "Rx" to refer to the .Net interfaces.

> Adopting a completely pull model defeats the point of Rx as that would
> eliminate all of the data sources that are "hot" that fire events without
> regard for when we pull from them.  A pull-based stream is an Iterable, even
> if it is an AsyncIterable.

Here the definition of "completely pull model" is significant.  Choice streams do support generating a stream based on push events.  You probably understand this already, but let me elaborate on this.

An ordinary singly linked list could be implemented using a pair of types that roughly looks like

```java
class List<X> {
  volatile Cons<X> list;
}

class Cons<X> {
  X       head;
  List<X> tail;
}
```

in a Java style syntax.  Suppose one has a method `OnClick` that is called in response to external events (or is "pushed to") such as button clicks.  One could then generate a list `clicks`

```java
List<Button> clicks = new List<X>(); // clicks.list == null
```

in that method by writing

```java
void OnClick(Button theButton) {
  List<Button> newClicks = new List<Button>();
  Cons<Button> newCons = new Cons<Button>();

  newCons.head = theButton;
  newCons.tail = newClicks;
  
  clicks.list = newClicks;
}
```

One can then observe the list being generated from another thread by following the `list` references:

```java
List<X> cursor = clicks;

while (true) {
  while ( cursor.list == null ) { /* wait */ }
  System.out.println( cursor.list.head.toString() );
  cursor = cursor.list.tail;
}
```

Of course, the above sketch is an absolutely silly way to do things, but I hope that this example is simple enough to be understood.

Now, the choice stream type is only a small change from the above `List<X>` type and would look roughly like

```java
class Stream<X> inherit Promise<Cons<X>> { } // Read: inherit = typedef

class Cons<X> {
  X         head;
  Stream<X> tail;
}
```

in a Java style syntax.  The `Promise<X>` type supports a number of operations, including the ability to create an empty "unfulfilled" promise and an operation to "fulfill" such a promise:

```java
class Promise<X> {
  Promise();  // Create a new unfulfilled promise
  // ...
  void fulfill(X value);
  // ...
}
```

Using these types, you can similarly generate a stream:

```java
Stream<Button> clicks = new Stream<Button>();

void OnClick(Button theButton) {
  Stream<Button> newClicks = new Stream<Button>();
  Cons<Button> newCons = new Cons<Button>();

  newCons.head = theButton;
  newCons.tail = newClicks;

  clicks.fulfill(newCons);
  clicks = newClicks;
}
```

I hope this *helps* to understand the very simple model underlying choice streams and one way to generate such streams.

Basically, choice streams are just linked lists of promises.  A promise can be defined in a variety of ways (most of which I haven't talked about here), including as the result of a non-deterministic choice of two or more promises.

What is interesting, IMO, is that such a simple model, measurably one to two orders of magnitude simpler (roughly 500 lines in choice streams vs 30k lines in RxJava or 50k lines in .Net Rx), is able to support very similar styles of programming as Rx.  In my opinion, the comment in

  https://github.com/ReactiveX/RxJava/blob/1.x/src/main/java/rx/internal/operators/OperatorMerge.java#L75

is quite telling.  By comparison, many of the basic operations on choice streams are next to trivial to define.  Here is `merge`

```fsharp
let rec mergeSwap ls rs =
  ls >>= function Nil -> rs
                | Cons (l, ls) -> cons l (merge rs ls)
and merge ls rs = mergeSwap ls rs <|>* mergeSwap rs ls
```

Also, compared to Rx, in particular, choice streams allow forms of composition that simply are not available in Rx.  For example, the `map` operation (or `Select`) can be defined via `unfold` (`Job` = lightweight thread/async monad):

```fsharp
let mapJob f xs =
  unfoldJob
   (fun xs ->
      xs >>= function Nil -> Job.result None
                    | Cons (x, xs) ->
                      f x |>> fun y -> Some (y, xs))
   xs
```

Note that the above is also an asynchronous version of `map` as opposed to the synchronous version of `Select` in .Net Rx.  It does not seem possible to implement `Select` in Rx in the above style in the original .Net Rx model.  I believe the comment made by @headinthebox above about "fewer operators" is a realization of this property in conjuction with the Reactive Streams model.

I believe the Reactive Streams model supports similar forms of composition as choice streams, but at a huge increase in complexity.

> RxJava has created push/pull implementations of publish/groupBy/merge/etc that
> all change from push to pull when the downstream can not keep up with push.
> This may be of interest to you [...]

Indeed!  That is an interesting ability.  In the choice stream model, as in the Rx model, there is no built-in mechanism for switching between push and pull models.  The Rx model is fundamentally push and the choice stream model is fundamentally pull.

> [...] based on your comments in the Inverting document about groupBy and
> merge.  This has all occurred since Erik mentioned the "don't know how to do
> groupBy" comment.  Indeed groupBy was tricky to get right with backpressure,
> but it works with push and pull and moves between them as necessary.

That is nice!

> Your document also references closing over locks ... that does not happen in
> RxJava.  It did in very early versions, and it may still do so in Rx.Net, but
> a lock is never held while emitting in RxJava.

That is also a cool feature.  There is, however, a fundamental difference here between Rx/Reactive Streams and choice streams.  In Rx/Reactive Streams the `OnNext` calls are synchronous and a subscriber must return quickly from `OnNext` or there will be trouble.  In choice streams the act of producing a new element is fully asynchronous.  Any number of consumers of a choice stream can be immediately dispatched when a new element is produced and, from the point of view of the stream producer and other consumers, it doesn't matter if some consumer is slower than others or even fails catastrophically (raising an exception).

At any rate, thanks for the reply, I believe this discussion helped me to better understand some further differences between the different models.

**Comment by benjchristensen** [comment]
> If, by Rx, you refer essentially to the interfaces IObservable and IObserver of .Net, then I don't see how they could support the same push-pull model as Reactive Streams.

RxJava has advanced beyond Rx.Net and supports the Reactive Stream style backpressure.

**Comment by benjchristensen** [comment]
> Basically, choice streams are just linked lists of promises.

I have played with approaches like this and found the object allocation overhead to be far too restrictive on the JVM. Perhaps with value types it would be more viable, but right now I don't see how this would be done without measurable impact on throughput. 

How do you address that?

How does your model differ from CSP or Actors? The fact that every stream is a queue (linked list) suggests that it is very similar.

**Comment by VesaKarvonen** [comment]
> I have played with approaches like this and found the object allocation
> overhead to be far too restrictive on the JVM.  Perhaps with value types it
> would be more viable, but right now I don't see how this would be done without
> measurable impact on throughput.

> How do you address that?

At the present, choice streams are a library built on top of a concurrent programming library and there are only some minimal manual optimizations done on the choice stream implementation.  The concurrent programming library, Hopac, on which choice streams are written in is, however, aggressively optimized.

I haven't yet done comprehensive benchmarking or performance testing (and subsequent optimization) on choice streams.  A couple of very simple tests suggested that choice streams are competitive with .Net Rx in terms of performance, but I really wouldn't draw any conclusions from those yet.  More comprehensive benchmarks and performance tests are needed.

Theoretically, it should be possible to implement choice streams so that they are nearly as efficient as regular singly linked lazy lists: single allocation to add an element to a choice stream, zero or one allocations to request an element from a stream.  This requires either a very good optimizing compiler (e.g. MLton) or manual specialization of the stream representation, ultimately fusing the `Cons` and `Promise` types together.

> How does your model differ from CSP or Actors?  The fact that every stream is
> a queue (linked list) suggests that it is very similar.

The design of the Hopac library is heavily influenced by Concurrent ML.  CML can be seen as being based on pi-calculus with non-deterministic choice.  More recent languages/libraries like Go and Clojure core.async said to be based on CSP can basically be seen as providing a subset of CML&mdash;they lack the built-in notion of first-class events (called alternatives in Hopac) and negative acknowledgments.

A choice stream can basically be seen as a kind of multicast communication mechanism allowing one-to-many and many-to-many messaging, with the property that all receivers (Rx subscribers, choice stream consumers) get all the messages (after the point they start receiving).  In Reppy's Concurrent ML book there is an implementation of multicast channels that can be seen as a particular use case of choice streams.

It should be straighforward to encode choice streams in terms of pi-calculus, CSP or join-calculus, possibly even with more limited actor models.  However, I don't really think of them as being related.  Choice streams are about broadcasting messages with ordering and delivery guarantees to any number of processes, which is not a basic mode of communication for those process calculi.

**Comment by benjchristensen** [comment]
Thanks for the further information. I'll think about what you've shared.

**Comment by exceptionplayer** [comment]
excellent
