### ISSUE TITLE
Additional error handling

### ISSUE THREAD

**Issue by christopherperry** [ReactiveX/RxJava#1002]
I would like an error handling operator that behaves like a mix between `onErrorResumeNext()` and `onErrorReturn()`. 

What I'd like it to do is let me replace the emission that caused the error (like `onErrorReturn()`), but put that replacement value in place of the emitted item in the original set of emissions and keep moving along as if nothing happened (like `onErrorResumeNext()`)

**Comment by dominicthomas** [comment]
Related question, can you add a .doOnError to the chain to say log the error and a .retry after that to attempt to try again? Will that work?

**Comment by benjchristensen** [comment]
Yes you can compose doOnError and retry.
