### ISSUE TITLE
Add Observable.endWith?

### ISSUE THREAD

**Issue by davidmoten** [ReactiveX/RxJava#1176]
I'm using `Observable.startWith` but would also like to use a new method `Observable.endWith` say (I suppose `concat` is not available because of static method with same signature after erasure). 

The driver for me is that my code (in java) is heaps uglier without it. 

Suppose I have source1, source2 and I want to do some stuff to source1 and then append source2:

I have three options:

Use static `concat`:

``` java
Observable.concat(source1.take(20).buffer(2,1).filter(myFilter), source2);
```

Use `startWith`:

``` java
source2.startWith(source1.take(20).buffer(2,1).filter(myFilter));
```

or use a new `endWith` method:

``` java
source1.take(20).buffer(2,1).filter(myFilter).endWith(source2);
```

The last one is much clearer. Am I overlooking something or can we can add this method to the api?

Perhaps a method like ``append` is better because it might seem strange to see multiple concatenated endWiths:

``` java
source1.endWith(source2).endWith(source3);
```

or 

``` java
source1.append(source2).append(source3);
```

**Comment by charlesr1971** [comment]
I have created an RxJs5 [5.0.0-rc.1]  'endWith' version, if anyone needs it?
It was quite interesting comparing the official source code between 'startWith' & 'endWith'. Very similar except for the order in which the source is added...

**Comment by akarnokd** [comment]
@charlesr1971 You probably commented on the wrong project; did you mean https://github.com/ReactiveX/rxjs#rxjs-6-stable ?

**Comment by dkuteynikov** [comment]
Actually, it would be great to also have `concatWithItem`, because we already have both `startWith` and `startWithItem`, while `concatWith` doesn't have a similar shortcut to omit writing `Observable.just`.
