### ISSUE TITLE
Operator ObserveOn without queue?

### ISSUE THREAD

**Issue by akarnokd** [ReactiveX/RxJava#1207]
Now that the CPU/IO Scheduler.Worker is guaranteed to be run on the same thread, do we need serialization and queueing in ObserveOn? Since the worker already does the MPSC behavior, there is no need to do it before that. On the other hand, if a worker is stalled, ObserveOn batches up the work and we may avoid some overhead elsewhere.

Thoughts?

**Comment by akarnokd** [comment]
While I was working on #2603 I've tried this and the perf was like 3x lower because the increased GC pressure of the individual schedules instead of the self-tuning batching currently happens.

**Comment by benjchristensen** [comment]
I suggest closing this out. If this type of behavior is wanted we can use `onBackpressureBlock().observeOn()`.

**Comment by benjchristensen** [comment]
Oh, you closed it already :-)
