### ISSUE TITLE
"Another strategy was already registered" even when using default

### ISSUE THREAD

**Issue by dlew** [ReactiveX/RxJava#1213]
I've been experimenting with rxjava-debug. One problem I've run into is that I _must_ set the observable execution hook before _anything_ else or else I get "Another strategy was already registered" exception.

The exception seems off when RxJavaObservableExecutionHook is the hook being used; in that case it feels like you should still be able to register a new hook if the default is just being used to cover.

**Comment by amitai-hoze** [comment]
@dlew, on my Android app I'm trying to use this code
```java
RxJavaPlugins.getInstance().registerObservableExecutionHook(new DebugHook(new DebugNotificationListener() {
    public Object onNext(DebugNotification n) {
        Log.v(TAG,"onNext on "+n);
        return super.onNext(n);
    }


    public Object start(DebugNotification n) {
        Log.v(TAG,"start on "+n);
        return super.start(n);
    }


    public void complete(Object context) {
        super.complete(context);
        Log.v(TAG,"onNext on "+context);
    }

    public void error(Object context, Throwable e) {
        super.error(context, e);
        Log.e(TAG,"error on "+context);
    }
}));
```
and I'm getting the "Another strategy was already registered" error. You said I should put it before anything else, where is that? I tried putting it in my activity's constructor but still got the error message.

**Comment by dlew** [comment]
That means it's still being registered sometime before your Activity's constructor. Try putting it into  `Application.onCreate()`; that will run before anything else on Android (except for any `static` initialization blocks).

**Comment by amitai-hoze** [comment]
Thanks :smile:, it worked.
