### ISSUE TITLE
New ExecutorScheduler Implementation

### ISSUE THREAD

**Issue by benjchristensen** [ReactiveX/RxJava#1219]
It turns out a lot of people used `ExecutorScheduler` despite its problems (#711 & #713). We need to bring it back, but in a way that is compliant with the contract.

This will mean that each `Worker` from the `ExecutorScheduler` will need to maintain it's own queue outside of the `Executor` (similar to `observeOn`) and then recurse on the `Executor`. Only a single task per `Worker` can be scheduled/enqueued on an `Executor`, and when it completes then it should recurse pulling items from the `Worker` queue. When the queue is empty it can stop processing. When a new task is enqueued on the `Worker` then it can schedule against for execution on the `Executor`.

We will be working against the default behavior of the `Executor` but need to do that to maintain the single-threaded contract of a `Scheduler.Worker`.

**Comment by cq321** [comment]
-keep class rx.internal.util.** { *; }
 add it in proguard to resolve few problems
