### ISSUE TITLE
Make operator parameter names consistent across operators.

### ISSUE THREAD

**Issue by DavidMGross** [ReactiveX/RxJava#1353]
I recommend that some of the parameter names used in Observable operators be changed so that similar parameters have similar names from operator to operator.

Specifically:

#### Collections of Observables

An iterable, list, or array of Observables is called "`sources`" in `amb()` and `combineLatest()`; "`sequences`" in `merge()`, and "`ws`" in `zip()`.

I recommend standardizing on "`observables`" as the parameter name for these.

#### Observables that emit Observables

An Observable that emits Observables is called "`observables`" in `concat()`, "`source`" in `merge()` and `mergeDelayError()`; "`sequenceOfSequences`" in `switchOnNext()`; and "`ws`" in `zip()`.

I recommend standardizing on "`observables`" as the parameter name for these

#### Ordinary Observable

Some operators take an ordinary Observable as a parameter.

The `zip()` operator calls the Observable that you pass as a parameter to zip with the source Observable "`other`"; the `groupJoin()` and `join()` operators use the parameter name "`right`" to describe a similar thing.

(The new operators `ambWith()`, `concatWith()`, and `mergeWith()` use "`t1`" for this sort of parameter; `zipWith()` uses "`other`".)

I recommend standardizing on "`other`" for this.

#### Multiple Observables

Some operators take two or more Observables as parameters.
* `amb()`, `combineLatest()`, and `zip()` call these "`o1`," "`o2`," "`o3`," etc.
* `concat()`, `merge()`, and `mergeDelayError()` call these "`t1`," "`t2`," "`t3`," etc.
* `sequenceEqual()` calls these "`first`" and "`second`"

My recommendation: for at least the operators in the first two bullet points, choose a single naming scheme and standardize over it for all of those operators.

#### Special-Function Observables

Some operators are passed Observables that emit indicators that instruct the operators to do certain things at certain times.  The naming schemes for these could be improved.

Currently:
**`buffer()`**
* opening indicator: `bufferOpenings`
* closing indicator: `bufferClosingSelector`
* boundary indicator: `boundary`

**`window()`**
* opening indicator: `windowOpenings`
* closing indicator: `closingSelector`
* boundary indicator: `boundary`

My recommendation for both:
* opening indicator: `openingIndicator`
* closing indicator: `closingIndicator`
* boundary indicator: `boundaryIndicator`

I also recommend changing the names of the following parameters so that they conform to a similar naming scheme:
* "`durationSelector`", "`leftDuration`", "`rightDuration`" (`groupByUntil()`)
* "`leftDurationSelector`", "`rightDurationSelector`" (`join()`)
* "`other`" (`skipUntil()` and `takeUntil()`)
* "`firstTimeoutSelector`" and "`timeoutSelector`" (`timeout()`)
* "`debounceSelector`" (`debounce()`)
* "`sampler`" (`sample()`)

(There are also parameter names for functions that _generate_ Observables that emit indicators: 
"`subscriptionDelay`" and "`itemDelay`" from `delay()`, "`closingSelector`" from `window()`, and "`notificationHandler`" from `repeatWhen()` and `retryWhen()`).

#### Observables that act as back-up sequences

Observables that are meant to supply items in case of failure in a primary Observable are called "`resumeSequence`" in `onError/ExceptionrResumeNext()`, and "`other`" in `timeout()`.

I recommend standardizing on a single parameter name for these.

#### Number of repetitions

`repeat()` uses "`count`" to indicate how many times the items should be repeated; `retry()` uses "`retryCount`" to indicate how many times to attempt to retry.

Recommendation: either use "`count`" for both, or change the first one to "`repeatCount`"

#### Numbers of items to skip, emit, or observe

You can instruct some operators to ignore a certain number of items emitted by an observable. You indicate this number with "`skip`" (`buffer()` and `window()`), "`num`" (`skip()`), or "`count`" (`skipLast()`). I recommend standardizing on "`skip`" for all three.

You can also instruct some operators to attend to or to emit a particular number of items emitted by an observable. You indicate this number with "`num`" (`limit()` and `take()`), "`count`" (`buffer()`, `range()`, `takeLast()`, `takeLastBuffer()`, and `window()`), or "`capacity`" (`cache()`). I recommend standardizing on one or the other for all of these operators.

#### Durations

Several operators have parameters that indicate durations of time. There are currently at least eight parameter names for parameters indicating duration. I recommend this be reduced, not necessarily to one, but to fewer. Here are the current ones:

* "`timespan`" (`buffer()`, `window()`)
* "`timeout`" (`debounce()`, `from()`, `throttleWithTimeout()`, `timeout()`)
* "`interval`" (`interval()`)
* "`time`" (`replay()`, `skip()`, `skipLast()`, `take()`, `takeLast()`, `takeLastBuffer()`)
* "`period`" (`sample()`, `timer()`)
* "`windowDuration`" and "`skipDuration`" (`throttleFirst()`)
* "`intervalDuration`" (`throttleLast()`)

There are also several operators that have parameters related to shifting things forward in time or delaying things in time. There are three names for these parameters now: one or maybe two are probably sufficient:

* "`timeshift`" (`buffer()`, `window()`)
* "`delay`" (`delay()`, `delaySubscription()`)
* "`initialDelay`" (`timer()`)

There is a single inconsistency in the parameter for indicating the time unit. This is called "`unit`" everywhere except in `timeout()` where it is called "`timeUnit`" -- I recommend changing it to "`unit`" there as well.

#### Items emitted by Observables

There are many names used for the parameters that describe an item emitted, or to be emitted, by an Observable: for instance "`element`" (`contains()`) and "`value`" (`just()`); also "`t1`" (`startWith()`) and "`initialValue`" (`publish()`, `reduce()`, `BlockingObservable.mostRecent()`) for an item to emit as the first emission; and "`defaultValue`" (many operators) for an item to emit if there were no emitted items from the source or none that met a predicate.

I've been using "item" in the wiki & javadocs to describe things emitted from Observables, rather than "value," "element," or "object." This is because Observables can emit lots of sorts of things (e.g. objects, elementals, additional Observables), and usually in the documentation, the important thing about these emissions is _that_ they're emissions, rather than that they're a particular sort of thing. "Item" is a less-misleading vague specifier for such emissions.

For this reason, I recommend that the parameter names also standardize on the "item" terminology, so:

* "`element`" and "`value`" become **"`item`"**
* "`t1`" and "`initialValue`" become **"`initialItem`"**
* "`defaultValue`" becomes **"`defaultItem`"**

There are also a few different names for parameters describing _arrays_ of items:

* "`t1`" (`from()`)
* "`items`" (`from()`)
* "`values`" (`startWith()`)

I recommend consolidating these into "`items`".

#### Collectors and accumulators

Are collectors and accumulators two different sorts of things or pretty much the same sort of thing?  `collect()` calls its function a "`collector`" while `reduce()` and `scan()` call theirs an "`accumulator`".  I'm not certain whether these are distinct enough things to necessitate distinct terminology.

#### Functions that transform items emitted by Observables

The following are used as parameter names for passing functions that are meant to transform items emitted by Observables:

* "`valueSelector`" (`groupByUntil()`, `toMap()`, `toMultiMap()`)
* "`elementSelector`" (`groupBy()`)
* "`func`" (`map()`)
* "`selector`" (`multicast()`, `publish()`, `publishLast()`, `replay()`)

I recommend standardizing on a single name, and considering something other than "selector", since these functions aren't really "selecting" items so much as _changing_ them.

#### Functions that combine multiple items emitted by Observables to create single items

The following parameter names describe functions that take items emitted by multiple Observables and operate on them to generate a single new item to be emitted:

* "`combineFunction`" (`combineLatest()`)
* "`resultSelector`" (`groupByUntil()`, `join()`, `mergeMap()`, `mergeMapIterable()`)
* "`zipFunction`" (`zip()`, `zipWith()`)

I recommend standardizing on a single name for all of these, and again I'm not sold on the "selector" terminology...

#### Functions that generate Observables

There are a number of parameters that describe functions that generate Observables:

* "`func`" (`concatMap()`, `flatMap()`, `mergeMap()`, `switchMap()`)
* "`collectionSelector`" (`mergeMap()`)
* "`observableFactory`" (`defer()`, `using()`)
* "`resumeFunction`" (`onErrorFlatMap()`, `onErrorResumeNext()`)

My recommendation: change "`func`" to something more descriptive, and see if you can consolidate some of these others as well.

#### On[State] actions/functions

`doOnCompleted()` and `mergeMap()` have "`onCompleted`" parameters; `forEach()` and `subscribe()` call their parameters "`onComplete`". Recommendation: change `forEach()` and `subscribe()` to use "`onCompleted`" so as to better match the name of the Observer method.

`finallyDo()` takes a parameter called "`action`"; most other operators of this sort take parameters of the form "onSomething" (e.g. "`onTerminate`", "`onNotification`", "`onNext`").  Recommendation: change the name of this parameter to use an "onSomething" form.

#### Iterables

`from()` calls its Iterable parameter "`iterable`"; `zip()` calls it "`other`". Recommendation, change `zip()` to match `from()` in this respect.

**Comment by DavidMGross** [comment]
Giving this a bump in the hopes of getting it on the radar of folks who are working on the 2.0 versions...

**Comment by DavidMGross** [comment]
@artem-zinnatullin - as long as you're doing code clean-up stuff... care to tackle this one?

**Comment by artem-zinnatullin** [comment]
I am afraid, that versioning scheme won't allow us to do it, several JVM langs such as Kotlin, Groovy,  Scala supports ["Named Arguments"](http://kotlinlang.org/docs/reference/functions.html#named-arguments) and we can break compilation of someone's code. Though I think that in terms of Java we are not breaking anything and this is RxJava, not RxKotlin or RxScala… 

@benjchristensen I can do this in 1.x if you don't mind, or it's time to start 2.x and move on.

**Comment by akarnokd** [comment]
This will be tackled in 2.x before RC 1. Let's rename parameters based on @DavidMGross suggestions then.

**Comment by DavidMGross** [comment]
bump

**Comment by akarnokd** [comment]
I'm doing some minor cleanups for 2.0 RC1 now and will try to unify the field names as well.

**Comment by akarnokd** [comment]
The names were mostly unified. If anything left out, we can do that post 2.0 for perhaps a few months; it may take some time other language adapters, who actually rely on parameter naming, pick 2.0 up.
