### ISSUE TITLE
Why BehaviorSubject requires default value?

### ISSUE THREAD

**Issue by lexer** [ReactiveX/RxJava#1364]
I often need BehaviorSubject that don't have default value and should not spawn values until first value is supplied. 

Currently as a workaround I initialize it with null and provide access to it after filter that ignores null value. Which looks ugly.

``` java
private BehaviorSubject<Location> locationUpdateSubject = BehaviorSubject.create((Location) null);

    public Observable<Location> getLocationUpdates() {
        return locationUpdateSubject.filter(new Func1<Location, Boolean>() {
            @Override
            public Boolean call(Location location) {
                return location != null;
            }
        });
    }
```

**Comment by Viktor-Bredihin** [comment]
what does it mean? how can I create Behavior subject without init value?

**Comment by artem-zinnatullin** [comment]
Just call `BehaviorSubject.create()`

**Comment by Viktor-Bredihin** [comment]
I did, it creates anonymous subject

**Comment by artem-zinnatullin** [comment]
What do you mean by anonymous subject?

**Comment by Viktor-Bredihin** [comment]
I mean 'AnonymousSubject'. Have you seen the result of BehaviorSubject.create() ?

**Comment by akarnokd** [comment]
@Viktor-Bredihin I don't understand what you are talking about either. From the [javadoc](http://reactivex.io/RxJava/1.x/javadoc/rx/subjects/BehaviorSubject.html):

![image](https://user-images.githubusercontent.com/1269832/26869127-93057872-4b6b-11e7-97de-506ce5214dbf.png)

`BehaviorSubject.create()` returns `BehaviorSubject<T>` where `T` is the type parameter inferred from the usage or has to be specified like `BehaviorSubject.<Integer>create()` in some other cases.

**Comment by Viktor-Bredihin** [comment]
it says that it creates behavior subject - yes, but when I create it and do console.log() it says 'AnonymousSubject'

**Comment by akarnokd** [comment]
What is your environment? A quick google search indicates `AnonymousSubject` is in RxJS, a JavaScript library. RxJava is a Java language library and as far as I remember there was never such `AnonymousSubject`.

**Comment by Viktor-Bredihin** [comment]
here is my env https://github.com/AngularClass/angular-starter

**Comment by Viktor-Bredihin** [comment]
new BehaviorSubject() returns as expected, but BehaviorSubject.create() returns AnonymousSubject

**Comment by akarnokd** [comment]
You have the wrong repository then. I suggest asking question on [their](https://github.com/ReactiveX/rxjs) site or StackOverflow about this.

**Comment by Aks659** [comment]
@lexer , I know it was
 long ago, but where you able to get rid of filter ? I have the exact same problem.
![subjectdilemma](https://user-images.githubusercontent.com/31528799/30416114-8c0f2678-9948-11e7-9314-9ff07da14809.png)
