### ISSUE TITLE
SerializedObserverTest.testNoficationDelay not deterministic

### ISSUE THREAD

**Issue by davidmoten** [ReactiveX/RxJava#1389]
This [test](https://github.com/Netflix/RxJava/blob/0.19.1/rxjava-core/src/test/java/rx/observers/SerializedObserverTest.java#L274-284) is failing 50% of the time on my old laptop and if I bump up ```n``` to 10000 on a modern desktop it fails all the time.

My laptop runs ubuntu 12.04, i5 4 virtual processors, java 8 runtime, and failed 5 out of 10 tests with n=10.
My desktop runs ubuntu 12.04, xeon 12 virtual processors, java 8 runtime, and fails every time after i gets between 1000 and 3000

The line failing is line 330
```assertSame(t1, t2);```

**Comment by akarnokd** [comment]
Potential fix posted: #3753

**Comment by akarnokd** [comment]
Closing via #3753.
