### ISSUE TITLE
Backpressure: cache

### ISSUE THREAD

**Issue by benjchristensen** [ReactiveX/RxJava#1483]
The `cache` operator should support downstream backpressure. It should `request(Long.MAX_VALUE)` up but be capable of correctly responding to downstream (similar to `from(Iterable)`).

This will mean we either have to stop using `ReplaySubject` or be able to handle it with `ReplaySubject` in the mix.

The idea here is that once data is cached, it should behave as an `Iterable`. Therefore, the cache really should behave like `onBackpressureBuffer`.

**Comment by akarnokd** [comment]
See #2969

**Comment by akarnokd** [comment]
Cache officially supports backpressure from relelase 1.0.14.
