### ISSUE TITLE
Unable to substitute a default scheduler with a wrapped Executor

### ISSUE THREAD

**Issue by pparlev** [ReactiveX/RxJava#1506]
Hello,

I'm trying to substitute the default IO scheduler following these guidelines: https://github.com/Netflix/RxJava/wiki/Plugins#rxjavadefaultschedulers

The substitute is a cached thread pool wrapped using Schedulers.from(Executor executor).
However, the attempt to set the default scheduler fails because it is already set when the call to Schedulers.from causes the single Schedulers instance to be initialized.

This is the related part of the stack trace:

```
java.lang.IllegalStateException: Another strategy was already registered: rx.plugins.RxJavaDefaultSchedulersDefault@ebb013f
    at rx.plugins.RxJavaPlugins.registerDefaultSchedulers(RxJavaPlugins.java:207)
```

Do you have any ideas on how to approach this? 

PS: The reason to do this is a separate problem - I need to limit the number of threads spawned by the IO scheduler. I saw this mentioned in several closed issues but it doesn't seem to be on the track for implementation.

**Comment by myion8you** [comment]
I am getting this same error trying to accomplish a similar task.  I know for a fact that there is no way the default scheduler is getting set before I try and register.
