### ISSUE TITLE
Missing javadoc comments in exceptions/Exceptions.java

### ISSUE THREAD

**Issue by DavidMGross** [ReactiveX/RxJava#1508]
The Exceptions class itself needs a javadoc description, as does its propagate() method and that method's "t" parameter.

I've flagged areas that need help in the javadocs with "@warn" tags. That tag is not part of the javadoc standard, so it triggers a javadoc compilation warning. Please remove those tags from any areas that you fix.

**Comment by zsxwing** [comment]
Closing per  #3683
