### ISSUE TITLE
Missing javadoc comments in Notification.java

### ISSUE THREAD

**Issue by DavidMGross** [ReactiveX/RxJava#1509]
The "type" parameter to Notification.createOnCompleted() is not documented in the javadocs and needs some sort of explanation (particularly as it doesn't seem to have any purpose).

I've flagged areas that need help in the javadocs with "@warn" tags. That tag is not part of the javadoc standard, so it triggers a javadoc compilation warning. Please remove those tags from any areas that you fix.

**Comment by akarnokd** [comment]
Seems to be fixed now.
