### ISSUE TITLE
Missing javadoc comments for Subscriber.setProducer()

### ISSUE THREAD

**Issue by DavidMGross** [ReactiveX/RxJava#1512]
The Subscriber.setProducer() method needs a javadoc description, and its "producer" parameter needs a description as well.

I've flagged areas that need help in the javadocs with "@warn" tags. That tag is not part of the javadoc standard, so it triggers a javadoc compilation warning. Please remove those tags from any areas that you fix.

**Comment by akarnokd** [comment]
Subscriber.setProducer() has now a proper javadoc.
