### ISSUE TITLE
Add OSGi manifest headers

### ISSUE THREAD

**Issue by mattbishop** [ReactiveX/RxJava#154]
Those of us on OSGi environments (like eclipse, netbeans, glassfish) cannot use rxjava-core or the other adapters without OSGi headers being added to the manifest.

This is pretty easy to do using the Maven Bundle plugin from apache Felix.

**Comment by SimonScholz** [comment]
Hi in case you're interested I am usually using a gradle plugin to convert normal jars to osgi bundles.
See https://github.com/SimonScholz/rxjava-osgi/

I've also written a tutorial how to do that: http://www.vogella.com/tutorials/EclipseJarToPlugin/article.html#convert-jar-files-to-osgi-bundles-with-gradle
