### ISSUE TITLE
Backpressure Docs

### ISSUE THREAD

**Issue by benjchristensen** [ReactiveX/RxJava#1541]
An issue to track discussion of docs for backpressure, started at https://github.com/Netflix/RxJava/issues/1000#issuecomment-49087519 but done here so it doesn't hijack #1000.

Current draft is at: https://github.com/Netflix/RxJava/wiki/Backpressure

**Comment by DavidMGross** [comment]
With
- https://github.com/ReactiveX/RxJava/wiki/Backpressure

and
- http://reactivex.io/documentation/operators/backpressure.html

I think we can close this issue.
