### ISSUE TITLE
Event Bus Documentation

### ISSUE THREAD

**Issue by benjchristensen** [ReactiveX/RxJava#1543]
A common question I see is how to do simple event bus use cases. 

Let's add docs and exames to the wiki.

**Comment by akarnokd** [comment]
This is a very old issue. I personally don't want to put too much emphasis on thinking in an shared event bus instead of dedicated sequences. In addition, people have blogged about it extensively since the opening of this issue. Thoughts?

**Comment by akarnokd** [comment]
The problem with EventBus with RxJava that it funnels all sorts of source emissions into a single serialized pipeline instead of having as many flows (individually multicasted if necessary) as there are types.
