### ISSUE TITLE
Error Handling Documentation

### ISSUE THREAD

**Issue by benjchristensen** [ReactiveX/RxJava#1544]
Common questions are related to error handling such as retry, exponential back off, checked exceptions, user functions throwing, and handling different errors differently. 

Let's add a section to the docs with code examples for these things and explaining the Rx contract with idiomatic solutions. 

It should show how to convert from imperative try/catch thinking.

**Comment by Kavignon** [comment]
I would be happy to contribute to the documentation. What's currently missing or what's partially complete that would need better support ?

**Comment by DavidMGross** [comment]
Here is what we have currently:
https://github.com/ReactiveX/RxJava/wiki/Error-Handling
It could use some fleshing-out with concrete examples.

**Comment by DavidMGross** [comment]
There are also the operator pages for the onError...() operators, retry(), and such, which are now at the reactivex.io site:
https://github.com/ReactiveX/RxJava/wiki/Error-Handling-Operators

**Comment by koral--** [comment]
Those 2 wiki pages have both `Error Handling` label on a sidebar. It seems that the latter should be `Error Handling Operators`.

**Comment by akarnokd** [comment]
Thanks, @koral-- updated the wiki.

**Comment by akarnokd** [comment]
Closing as it will be handled via #6001
