### ISSUE TITLE
rx.Future/Task/Async/Single

### ISSUE THREAD

**Issue by benjchristensen** [ReactiveX/RxJava#1594]
Explore whether an `rx.Future` makes sense to allow better representation of Scalar responses.

-----------

Comment below explaining reasoning: https://github.com/ReactiveX/RxJava/issues/1594#issuecomment-101300655

**Comment by akarnokd** [comment]
Can someone explain what this Future/Task should do, or more specifically, what is the underlying issue we want to solve that ```Observable``` or ```Async``` can't do (efficiency?)?

**Comment by benjchristensen** [comment]
Represent request/response of a single value. It is purely a design thing, not functional. Many, many people would prefer to represent scalar values such as IO request/response (think HTTP, REST, RPC) as a Future/Task but be able to merge them into Observable streams. It is one of the most common questions I get.

Rx.Net has it because .Net already has `Task` that works nicely with `Observable` since they were built for each other. The Java `Future` is unusable in this sense and `CompletableFuture` in Java 8 can be made to work but it's entire API design is incredibly different and they are always "hot".

**Comment by benjchristensen** [comment]
FYI, I plan on tackling this myself as we want to use it at Netflix for something.

**Comment by mttkay** [comment]
I would also be curious to see what value this adds other than introducing a concept that developers familiar with other frameworks or languages are used to. So just to play devil's advocate: if `Observable` is semantically a superset of `Task` as it's capable of producing N results rather than just 1 (and N can be 1), does this justify introducing a new type? I am worried that this really only adds cognitive overhead and redundancy, as we're essentially dealing with the same thing, but one is a specialization of the other? Will people start asking when to use a Task and when to use an Observable?

I should add that we use almost always scalar Observables in our app, and I never thought that it feels awkward. An `Observable.just(list)` seems no more or less confusing to me than a `Future.value(list)` (to draw the comparison again to Twitter's composable Futures.)

That said, is the actual problem we're trying to solve one of naming and expectation, because people are looking at Observable and expecting a Scalar, because that's what Futures do? So is the problem more discoverability of the API rather than a gap in functionality?

I do need to say here that if I had to pick one design aspect of RxJava that I think really stands out, then it's its universal applicability, and that's partially because of a healthy lack of assumptions--emitting a single result is an assumption--and I find this to be a powerful combination in library design.

**Comment by mttkay** [comment]
I think I meant to respond on the PR, as the discussion seemed to have moved there. Sorry.

**Comment by ylemoigne** [comment]
I think it's confusing, because the http://reactivex.io/intro.html first array tells that for single item, the concept to use is a Future.

**Comment by JakeWharton** [comment]
That is what this would be aiming to replace. Future is a really bad abstraction.

**Comment by mark9white** [comment]
Would obs.toSeq, obs.single return Task? Certainly I'd like to see that but we'd need to make sure that doesn't interfere with people who don't want to use Task ...

**Comment by sdeleuze** [comment]
As said in the PR comments, I fully agree with the need to have a scalar observable type, especially when exposing such type in application public API.

The main thing that confuses me in the implementation proposal is the embedded `Task.Promise` type. I understand this is done differently in .NET since `Task` already exists, but on other platforms I would just expect a single type that I would expose in my API instead of `Observable` for scalar result.

**Comment by benjchristensen** [comment]
I'm still interested in pursuing this. The only thing holding us up right now is a final decision on what we should call it. 

It seems `Single` is the name we are converging on: https://github.com/ReactiveX/RxJava/pull/2641#issuecomment-100985990

Any reason not to merge an `@Experimental` version of `rx.Single`?

**Comment by headinthebox** [comment]
Let's go for it!

**Comment by akarnokd** [comment]
```Single``` sounds odd to me. Here are my candidates: Scalar(Task, Observable, Future), Single(Task, Future), Async(Task, Scalar, Future), ObservableScalar; however, I suspect most combinations are already taken by some other library.

**Comment by headinthebox** [comment]
http://en.wikipedia.org/wiki/Scalar: "Variable (computing), or scalar, an atomic quantity that can hold only one value at a time". Why use a complex term like "scalar" when you just mean "single"?

**Comment by akarnokd** [comment]
@benjchristensen I meant potential postixes, i.e., ScalarTask, ScalarObservable or ScalarFuture, etc.

Since we will use the experimental annotation, let's proceed with ```Single``` and come back to the name in a few months once enough use experience has been accumulated.

**Comment by schrepfler** [comment]
I like Single but just to throw more alternatives, Observable1 or OneObservable can be considered to avoid mixing up with other class names/libraries.

**Comment by benjchristensen** [comment]
Here are examples of using `Single`:

```java
import java.util.concurrent.TimeUnit;

import rx.Observable;
import rx.Single;
import rx.Single.Promise;
import rx.schedulers.Schedulers;

public class SingleExperiment {

    public static void main(String... args) {
        Observable<String> a_merge_b = getDataA().mergeWith(getDataB());

        Single<String> a_and_b = getDataA().flatMap(t -> {
            return getDataB().map(r -> t + r);
        });

        Single<String> a_transformed = getDataA().map(a -> a + "_response");

        Observable<String> a_concat_b = getDataA().concatWith(getDataB());

        /**
         * This shows flatMapping a Single with an Observable
         */
        Observable<String> a_with_c = getDataA().flatMapObservable(a -> {
            return getDataC().map(c -> a + "-" + c);
        });

        Single<String> aWithTimeout = getDataA().timeout(100, TimeUnit.MILLISECONDS);

        Single<String> aWithTimeoutAndSimpleDefaultValue = aWithTimeout.onErrorReturn(t -> "DefaultValue");

        /**
         * We can use toObservable() for a Single to interact with an Observable.
         * Or we can add the various overloads to Observable.merge/concat/zip/mergeWith/concatWith/zipWith/etc
         * Adding the overloads though does result in a lot of API clutter.
         */
        getDataC().mergeWith(getDataA().toObservable());

    }

    public static Single<String> getDataA() {
        return Single.<String> create(o -> {
            o.onSuccess("DataA");
        }).subscribeOn(Schedulers.io());
    }

    public static Single<String> getDataB() {
        return Single.just("DataB")
                .subscribeOn(Schedulers.io());
    }

    public static Observable<String> getDataC() {
        return Observable.interval(10, TimeUnit.MILLISECONDS).map(i -> "c" + i);
    }

    /**
     * Example of Single.Promise
     */
    public static Single<String> getDataD() {
        Promise<String> p = Single.Promise.create();
        new Thread(() -> {
            p.onSuccess("data-d-from-thread");
        });
        return p.getSingle();
    }
}
```

**Comment by sdeleuze** [comment]
@benjchristensen I like this new proposal but could you explain why there is a need for this embedded `Promise` type?

**Comment by benjchristensen** [comment]
Reposting a modified version of https://github.com/ReactiveX/RxJava/pull/2641#issuecomment-73593232 to provide reasoning for this proposal:

--------------

The evolution of thinking after using RxJava for a couple years is that libraries that expose public APIs can benefit from being able to communicate if something is scalar or vector – despite the "functional" argument that a scalar is just a "list of one". We are able to choose to use `T` or `List<T>` when creating a synchronous API, so why not for async as well? In other words, why should the use of RxJava exclude communicating when we do know something is a scalar, which is a very common use case, and results in a simpler mental model? 

When composition occurs that results in multiple values then the type changes to an `Observable`. Not all composition and transformation requires this though – `zip`, `amb`, `map`, `flatMap` all can return `Single`. Others like `merge` will return an `Observable`. 

Another consideration is that APIs that expose data access are generally separate from the consuming code that composes them, and it is these data access APIs where the scalar `Single` is most effective at providing communicating via a static type such as:

```java
Single<T> getData()
```

versus

```java
Observable<T> getData()
```

> does this actually simplify anything?

There is one thing I think it simplifies that is more than just making it easier due to familiarity. It communicates when a user does NOT need to think about multiple values, and that does indeed simplify code. 

A `Single` will always behave in one of 3 ways:

1) respond with an error
2) never respond
3) respond with a success

An `Observable` on the other hand may:

1) response with an error
2) never respond
3) respond successfully with no data and terminate
4) respond successfully with a single value and terminate
5) respond successfully with multiple values and terminate
7) respond successfully with one or more values and never terminate (waiting for more data)

The mental model for these extra possibilities do definitely increase the complexity and are a big part of the pushback for using RxJava that I have seen for request/response models. 

These more complex models do still end up happening as soon as composition occurs, but now that composition is declared by the consumer, and the consumer knows the contract of the producer to be simpler if it is a `Single`.

For example, in "service layer" type code we could have getters like this:

```java
Single<T> getDataA(arg);
Single<R> getDataB(arg);
Observable<R> getDataC(arg);
```

This is now simpler to understand because the types narrow the scope for `A` and `B` so we know we don't need to consider multi-value or infinite cases (which generally need to be explained in the javadoc). The `C` type in contrast clearly indicates that it wants to support multiple values otherwise it would have just been a `Single`.


> familiarity can always be learned, but complexity is harder to avoid

My thinking has evolved to think that trying to force everything to be a vector results in increased complexity of a different kind that can be addressed by a slight increase in complexity of the RxJava APIs (2 types instead of 1). Static types communicate common information that simplifies the mental model and constrains available states and operations that can be applied. This seems worth the increase in API surface area.

**Comment by benjchristensen** [comment]
> could you explain why there is a need for this embedded Promise type

@sdeleuze it is not required and I should probably remove it. I added it to prove a common programming model.

Below are two ways of achieving the same thing. The first eliminates nesting but does involve an extra type. However, Promises are "hot" whereas the `Single.create` approach supports hot and cold execution. 

```java
    public static Single<String> getDataD() {
        Promise<String> p = Single.Promise.create();
        doStuffWithCallback(d -> p.onSuccess(d + "-from-thread"));
        return p.getSingle();
    }

    public static Single<String> getDataE() {
        return Single.create(o -> {
            doStuffWithCallback(d -> {
                o.onSuccess(d + "-from-thread");
            });
        });
    }
```

**Comment by benjchristensen** [comment]
An `@Experimental` version was merged in https://github.com/ReactiveX/RxJava/pull/3012
