### ISSUE TITLE
rx.Future with CompletableFuture Support

### ISSUE THREAD

**Issue by benjchristensen** [ReactiveX/RxJava#1595]
Explore whether an io.reactivex.Future makes sense to allow better representation of Scalar responses.

Related to https://github.com/Netflix/RxJava/issues/1594 in 1.x but targeting 2.x as it can support interop with Java 8 `CompletableFuture`.

**Comment by akarnokd** [comment]
Do we want to duplicate Java 8's functionality or all those other ListenableFuture, etc. implementations? Is there a use-case?

**Comment by benjchristensen** [comment]
This is only applicable to 2.x discussions. https://github.com/ReactiveX/RxJava/issues/1594 is more applicable for right now.

**Comment by akarnokd** [comment]
Done.

  - [fromFuture()](https://github.com/ReactiveX/RxJava/blob/2.x/src/main/java/io/reactivex/Observable.java#L330)
  - [toBlocking().toFuture()](https://github.com/ReactiveX/RxJava/blob/2.x/src/main/java/io/reactivex/observables/BlockingObservable.java#L215)

**Comment by akarnokd** [comment]
2.x was decided to be Java 6 compatible as well. This has to go to an external library.
