### ISSUE TITLE
Java8 Stream Support

### ISSUE THREAD

**Issue by benjchristensen** [ReactiveX/RxJava#1596]
Support Java 8 Streams

**Comment by akarnokd** [comment]
Done.

  - [fromStream](https://github.com/ReactiveX/RxJava/blob/2.x/src/main/java/io/reactivex/Observable.java#L384)
  - [toBlocking().stream()](https://github.com/ReactiveX/RxJava/blob/2.x/src/main/java/io/reactivex/observables/BlockingObservable.java#L137)
