### ISSUE TITLE
Need inclusive predicate variant of takeUntil/takeWhile

### ISSUE THREAD

**Issue by samueltardieu** [ReactiveX/RxJava#1649]
It has been two times I've been missing a `takeUntil(filter)` operator on observables. The last time was in cgeo while implementing a low-power mode: I want to receive location updates through an observable and stop as soon as a location arrives with a precision of 20m or less, but I want this location to be returned. Using `takeWhile(!filter)` would drop the matching item.

Of course, this can be worked around, but I was surprised not to get this operator which is the dual of `takeWhile`. Would you consider a contribution adding it?

**Comment by benjchristensen** [comment]
I hit another use case today where I'd really like to have this.

**Comment by akarnokd** [comment]
An experimental ```takeUntil()``` is now available in 1.0.5.

**Comment by headinthebox** [comment]
One way to distinguish the two versions would be `takeUntil` (forwards, then checks) versus `untilTake` (checks, the forwards). Like `do-while` and `while`.

**Comment by mxklabs** [comment]
I second the idea of needing this operator. 

I'd argue this is a basic primitive stream operation that ought not to be composed. Not including it is like Java designers arguing that you don't need a <= operator on integers because you already have < and == operators.

**Comment by akarnokd** [comment]
@mxklabs how urgently do you need this operator?

**Comment by mxklabs** [comment]
@akarnokd I need it now but can probably work around it. I just wanted to agree with the sentiment that it makes sense to have this operator.

**Comment by mxklabs** [comment]
@akarnokd Also, take until (from what I understand from [here](http://reactivex.io/documentation/operators/takeuntil.html)) is not exactly what's requested. It takes two observables and terminates as soon as the second observable emits an item as opposed to an observable and a condition and keep emitting upto and including the first emit where the condition holds.

(Not sure if I am looking at the right documentation, sorry)
