### ISSUE TITLE
Backpressure: SerializedSubscriber

### ISSUE THREAD

**Issue by benjchristensen** [ReactiveX/RxJava#1671]
Can we make `SerializedSubscriber` correctly be implemented with a bounded buffer and support reactive pull backpressure?

This should also ensure that `Observable.serialize()` works correctly with backpressure, both bounding its internal queue and chaining through the `Producer.request` calls.

**Comment by akarnokd** [comment]
I don't believe we should add backpressure support to ```SerializedSubscriber```: it is a write-through from the perspective of backpressure: if downstream requests 5, ```SerializedSubscriber``` will request 5. It is not meant to run with backpressure-ignoring upstream and the```onBackpressureXXX``` are there to handle it after.

I vote on closing this issue.

**Comment by akarnokd** [comment]
We use it mainly to serialize out `onNext` vs `onError` | `onCompleted`, for example in `takeUntil`, and not for serializing concurrent `onNext` calls (as far as I can remember).
