### ISSUE TITLE
Remove Parallel Operator

### ISSUE THREAD

**Issue by benjchristensen** [ReactiveX/RxJava#1673]
Almost every time I see the 'parallel' operator used it is being used incorrectly and misunderstood. This leads me to believe we should remove it and instead educate on how to use merge and flatMap correctly which is generally what is trying to be achieved in uses of parallel. 

Anyone have good reason not to eliminate it?

/cc @headinthebox

**Comment by rishi-anand** [comment]
Hi, @benjchristensen , @davidmoten , @jbripley , I agree with using flatMap(). I have 1 question, flatMap will do the operation and merge it back to main thread and onNext() will be called. What if one Observable ends with Observable.error() in that case Observable.error() will be called in main thread? If yes, then main thread will shut down and what will happen to other Observables running in parallel? If no, then result from other Observable will be triggered in onNext?

Correct me If I am wrong as I have just started with RxJava.

**Comment by akarnokd** [comment]
@rishi-anand please post your question on StackOverflow with details on what you have already implemented.
