### ISSUE TITLE
Backpressure: Publish

### ISSUE THREAD

**Issue by benjchristensen** [ReactiveX/RxJava#1732]
Is it possible in limited cases to support reactive pull backpressure on multicast use cases such as `.publish()`?

In the general case of a `ConnectableObservable` it wouldn't be, as those are "hot". I'm interested in exploring if there are cases when it will work, such as when using `refCount` to address use cases such as discussed in https://github.com/ReactiveX/RxJava/issues/1649#issuecomment-58058704

As per the example from @headinthebox 

``` scala
import rx.lang.scala._

object MainScala {
  def main(args: Array[String]): Unit = {
  val xs = Observable.items(0, 1, 2, 3, 4)
  val zs = xs.publish[Int]((xs: Observable[Int]) => xs.takeUntil(xs.dropWhile(x => x < 3).tail))
  zs.subscribe(z => println(z)) // 0,1,2,3
  readLine()
}
```

**Comment by JakeWharton** [comment]
Is there a non-trivial or non-contrived use case for this code to help me understand its applicability? I'm having a hard time conceptualizing what it would be used for when the example can be rewritten as `.takeWhile(Predicates.not(x => x > 3))` (or, of course, simply `.takeWhile(x => x <= 3)`).
