### ISSUE TITLE
Expose Live Observables for Debugging (Similar to Thread Dump)

### ISSUE THREAD

**Issue by benjchristensen** [ReactiveX/RxJava#1822]
I'd like to explore exposing an API for capturing an "observable dump" similar to a thread dump of all Observables currently live in the system. 

This would permit analysis and debugging of slow, latent, old, leaking Observables. This is particularly important when running in event loops systems where the threads don't reveal what's going on. 

This capability should in turn be combined with the ability to inspect an Observable chain to get a graph of all operators and flow of data as per work started in https://github.com/ReactiveX/RxJavaDebug

**Comment by akarnokd** [comment]
Project Reactor does this and it has to go very deep. This could be handled by an external library by hooking into flows with `RxJavaPlugins'' and some additional interfaces that allow discovering the connection graph. Maybe in 3.x.

**Comment by akarnokd** [comment]
I decided this is out of scope for this repository. The `RxJavaPlugins` hooks are available for doing such tracking if needed. If more introspection is required later on, those can be added via PRs on a case-by-case basis.
