### ISSUE TITLE
Native Java Agent for "Async Call Stacks"

### ISSUE THREAD

**Issue by benjchristensen** [ReactiveX/RxJava#1823]
Speaking with Tal Weiss at QConSF (@takipi https://www.takipi.com) it sounds like there may be some efficient approaches to capturing the callstack as longs (using C in native code) at each async invocation point in an `Observable` sequence so that in event of `onError` we could rebuild the stacktrace (paying the cost only then) and end up with more useful error information that normal stack traces offer in async and composed systems like Rx. 

This could enhance what we can do with https://github.com/ReactiveX/RxJavaDebug but also allow an "RxException" that contains the graph and callstack at each method invocation point along the way. It won't necessarily be a simple stack since an Observable can split and merge, but we should be able to either capture the full graph or the path to the error.

**Comment by akarnokd** [comment]
PR is welcome, although it might be better to have such tool in a separate project - not sure how we'd build and release a separate agent jar with the current infrastructure.

**Comment by iNoles** [comment]
Android does have NDK (C and C++) with JNI access too.

**Comment by akarnokd** [comment]
Closing as very old and being a complicated topic. Other async solutions also struggle with this and I haven't seen any solution for the either despite the support from their major IDE vendor.
