### ISSUE TITLE
Backpressure: Window by Size

### ISSUE THREAD

**Issue by benjchristensen** [ReactiveX/RxJava#1828]
The `window` operators that use time or Observable boundaries do not participate in backpressure ... they act as "temporal" operators for flow control and not reactive pull. The `window(int size)` variant however seems like it should work with reactive pull backpressure and behave similarly to `groupBy`. 

In other words, it can be applied to a cold observable and correctly compose backpressure to emit windows and items within each window at a controlled rate. 

Any thoughts or opinions on this?

**Comment by akarnokd** [comment]
Is this in the works? @zsxwing PR #1862 was closed do you want to revive it?

**Comment by zsxwing** [comment]
I'm busy with other work and may not go back to work on this one soon. If someone is interested in the issue, please go head.

**Comment by akarnokd** [comment]
Window supports backpressure on the outer Observable as of 1.0.14 and there is a PR that adds backpressure support to the inner observable: #3150.

**Comment by akarnokd** [comment]
Backpressure support added + there is a subsequent fix to this, #3678

**Comment by akarnokd** [comment]
Closing via #3678.
