### ISSUE TITLE
Improve "How to Use RxJava" page (EDGE-1829)

### ISSUE THREAD

**Issue by DavidMGross** [ReactiveX/RxJava#1869]
feedback from @danlew42:

The "how to use" page is confusing to start with. Theoretically that's the second page you view but it's just got a random mish-mash of information that goes way over a beginner's head; it mixes different languages and concepts at a rapid speed.

What I think would be much more effective would be an overview of key concepts. Something like the Observable page combined with a few key operators. As a beginnger RxJava user, there are a lot of Operators to look at - it's hard to tell which ones are core and which ones are just conveniences. For example, flatMap() is core while takeFirst() is just a convenience.
I think a lot more focus could be on how flatMap() works. Then one could explain how other common operators could be implemented through flatMap(). Instead, right now flatMap() is somewhat hidden in "Transforming observables".

The one example that I never saw - that would've helped me understand a lot more - is one where flatMap() is used to fork possible observables. In pseudo:

Observable.create(booleanFunc)
.flatMap(
if true then Observable A
if false return Observable B
)

Alternatively, you could present something like the idea of takeFirst() then implement it using flatMap().

**Comment by gboersma** [comment]
Agreed. I would also like to see Java code that uses Java 8 closures to show better equivalence to other languages. For example, this is the equivalent Java 8 implementation:

```
public static void hello(String... names) {
    Observable.from(names).subscribe(s -> System.out.println("Hello " + s + "!"));
}    
```

**Comment by akarnokd** [comment]
Closing as the Wiki will be reworked anyway and there is a [Getting started](https://github.com/ReactiveX/RxJava#getting-started) on the main page covering most typical beginner StackOverflow questions.
