### ISSUE TITLE
Create a complex problem-solving tutorial walk-through on the wiki (EDGE-1830)

### ISSUE THREAD

**Issue by DavidMGross** [ReactiveX/RxJava#1870]
feedback from @danlew42:

I wish there was a complex tutorial showing common problems that one solves. It's great that there are samples for almost every operator, but it'd be nice to see code one step above the sample.

**Comment by TarasMazepa** [comment]
This could serve as a nice example https://yarikx.github.io/NotRxJava/ , the link is taken from here http://reactivex.io/tutorials.html . Actually, this is my favorite RxJava tutorial which I'm sending to anyone who wants to learn RxJava and so far everyone is happy with it.

**Comment by akarnokd** [comment]
I'd rather stick to answering StackOverflow questions.
