### ISSUE TITLE
Add to backpressure documentation (EDGE-1449)

### ISSUE THREAD

**Issue by DavidMGross** [ReactiveX/RxJava#1874]
Things that are still missing from the docs:
- the Producer interface (and its request method)
- other new method in Subscriber:
  -- setProducer(p)
- how and when to support producers in custom observables & operators
  -- integration with the "how to make a custom operator" page; maybe also from create operator doc

https://github.com/ReactiveX/RxJava/wiki/Backpressure

**Comment by akarnokd** [comment]
Updated the wiki to point to https://github.com/ReactiveX/RxJava/wiki/Implementing-custom-operators-(draft)

**Comment by akarnokd** [comment]
Closing as 1.x is EOL.
