### ISSUE TITLE
Move RxJava docs to ReactiveX, integrate with other ReactiveX docs (EDGE-2004)

### ISSUE THREAD

**Issue by DavidMGross** [ReactiveX/RxJava#1875]
This will also involve changing the sample code so that it's in Java 8.

Move generic ReactiveX information to generic ReactiveX docs (e.g. list of operators).

Take Groovy code samples and move them to RxGroovy docs where appropriate.

**Comment by akarnokd** [comment]
Closing as this is very old and the workflow of getting things changed on the ReactiveX site is convoluted. We'll update our own wiki first.
