### ISSUE TITLE
Possible Thread Safety Issue in Merge

### ISSUE THREAD

**Issue by benjchristensen** [ReactiveX/RxJava#1885]
As per discussion in https://github.com/ReactiveX/RxJava/pull/1866#issuecomment-62782835 there may be a thread-safety issue in `merge`:

> I don't fully understand the OperatorMerge, but it contains a lot of mutable variables and synchronized blocks and I'm not sure but I found some anomalies in:

> https://github.com/ReactiveX/RxJava/blob/1.x/src/main/java/rx/internal/operators/OperatorMerge.java#L505

> It synchronizes on the MergeProducer's this but reads the MergeSubscriber's wip field which generally is accessed through the MergeSubscriber's this. Same seems to be true for the scalarValueQueue.

**Comment by akarnokd** [comment]
I think this issue has been fixed.
