### ISSUE TITLE
Possible Enhancement BlockingObservable with Timeout

### ISSUE THREAD

**Issue by daschl** [ReactiveX/RxJava#1921]
Hey folks,

while working on #1919 I was looking at the code a bit more and I get why `timeout` has a quite complex architecture. Now a common scenario if you use blocking code is:

`.timeout(...).toBlocking().single()`

Now what do you think about in the future providing overloads for the toBlocking methods that take a timeout? We can just operate on the latch that is used in there anyways. Right now we just call `.await()` on the latch there, but if we enhance it to supply a timeout we could provide a much simpler solution that has no additional GC overhead (since timeout puts stuff onto a scheduler and so forth).

Like 

`.toBlocking().single(5, TimeUnit.SECONDS)` and then pass this down to the latch and raise a TimeoutException.

What do you think? (If we agree this is a good thing, I'd love to take a stab at this)

**Comment by benjchristensen** [comment]
Closing out due to age. If this is still something worth discussing, please comment here for us to re-open.

**Comment by rishi-anand** [comment]
@benjchristensen Is this enhancement merged?

**Comment by akarnokd** [comment]
@rishi-anand No, blocking operations don't have timeout. You should apply `timeout` before a `blockingX` operator.
