### ISSUE TITLE
merge of synchronous observables = concat?

### ISSUE THREAD

**Issue by davidmoten** [ReactiveX/RxJava#1925]
Using 1.0.2 when I call try to merge two ```range``` observables (which are synchronous sources) I end up with ```concat``` behaviour. The [merge wiki entry](https://github.com/ReactiveX/RxJava/wiki/Combining-Observables#merge) suggests that I should see a mix of the two. Do we have a merge problem or a documentation problem?  
 
```java
Observable.range(1, 1000).mergeWith(Observable.range(1001, 1000))
				.subscribe(new Action1<Integer>() {
					@Override
					public void call(Integer n) {
						System.out.println(n);
					}
				});
```

**Comment by akarnokd** [comment]
Were the changes applied to the documentation? If so, could you close this issue?
