### ISSUE TITLE
ReplaySubject race condition: subscribers not always triggered?

### ISSUE THREAD

**Issue by marshallpierce** [ReactiveX/RxJava#1940]
*Assumptions*
Based on my casual look at the ReplaySubject source (namely, the obvious traces of thread safety in the implementations of the two fields in ReplaySubject) and the existence of tests like https://github.com/ReactiveX/RxJava/blob/1.x/src/test/java/rx/subjects/ReplaySubjectConcurrencyTest.java, it looks like ReplaySubject is designed to be thread safe.

*What I'm doing*
Concurrently adding a subscription to a `ReplaySubject` and supplying a value to it with `onNext` when `subscribeOn(schedulerThatUsesAnotherThread)` is in effect. See the two test methods in repro test case at https://bitbucket.org/marshallpierce/rxjava-replaysubject-race for cases with and without `subscribeOn`.

*Expected behavior*
The provided `Action0` should always have `onNext` invoked regardless of how it was scheduled. Even if the scheduling ends up happening after the subject's `onNext` is called, my understanding of `ReplaySubject` is that the point is that it should always replay everything regardless of when the subscription happens.

*Observed behavior*
Every once in a while (a few times out of thousands), the subscriber does *not* get called.

Am I not using the API correctly, or is ReplaySubject always supposed to replay everything to all subscribers regardless of concurrency when subscribing / providing values?

**Comment by akarnokd** [comment]
Hello. The fix for this bug should be in 1.0.4. Can you confirm it works for you?

**Comment by marshallpierce** [comment]
Yep, my tests pass now. Thanks!
