### ISSUE TITLE
Global Contract Tests via Unit Tests

### ISSUE THREAD

**Issue by benjchristensen** [ReactiveX/RxJava#1962]
I'm wondering if there is a way for us to create an `AbstractTest` class that we could implement for each operator that would have a series of specification tests, similar to a TCK that assert core behavior as opposed to the operator functionality. 

For example:

- subscribe and unsubscribe
- request(Long.MAX_VALUE)
- request(0)
- request(n < 0)
- request(n > 0)
- scalar
- vector
- infinite
- async and sync variants of each
- concurrency (where applicable, such as unsubscribe and request)

It would require the implementation classes providing an Observable impl with each operator configured correctly for the various cases, but then the abstract portions could do the pounding and prove the basics for all operators. 

This would be a great addition for someone looking to contribute. If someone has the time to tackle this I'd be happy to review the approach, specifications and tests while getting started. We should prove it on a few operators first before making the effort for all of them. For example `map`, `take`, `merge`, `groupBy`.

**Comment by davidmoten** [comment]
I've had a play with this one. It's not fully unit tested but appears to be working so far and I'm already finding this very useful for testing custom ```Operator```s. This may not be what people are envisaging but might nethertheless be useful for pushing discussion.

The page below demos a sync test for ```count``` and an async test for ```merge```.

https://github.com/davidmoten/rxjava-extras

**Comment by benjchristensen** [comment]
Closing in favor of https://github.com/ReactiveX/RxJava/issues/2783 for 2.0.
