### ISSUE TITLE
Worker schedulePeriodically behavior probably wrong

### ISSUE THREAD

**Issue by lexer** [ReactiveX/RxJava#1970]
schedulePeriodically remembers timestamp when it was started.

https://github.com/ReactiveX/RxJava/blob/1.x/src/main/java/rx/Scheduler.java#L112

So all repeat intervals are pre calculated.

If execution of one action was significantly delayed it potentially creates a risk of immediate sequential execution of next actions.

Example: schedulePeriodically is used to poll server every 5 second. due to bad network connectivity one request was delayed by minute. In this case 11 (60/5) requests will fire without delay right after that.

**Comment by frko** [comment]
Agreed this is a bug. This shouldn't qualify as acceptable behaviour as it isn't intuitive to assume such an implementation. Clients will expect the interval to be idle time and with a task consuming more time then interval will trigger all subsequent invocations to be instant.

**Comment by samueltardieu** [comment]
@frko I don't agree that this is a bug.

People used to real-time systems expect the current behavior. If you schedule a task once a day and each invocation takes around two hours, you don't expect it to run only 28 times a months with 31 days. You don't want to have one day between invocation, you want one invocation a day. And of course, invocations must not take more than one day to execute or you will always be executing one.

Why not just reschedule the action if you want to wait some time after the action has ended? All bases would be covered then.

**Comment by akarnokd** [comment]
For this reason, ```ScheduledExecutorService``` features two methods: ```scheduleAtFixedRate``` and ```scheduleWithFixedDelay```. We chose the former as the basis for periodic scheduling because the latter is much simpler to implement with recursive scheduling.

**Comment by frko** [comment]
Above arguments seem acceptable indeed. However one thing that still is a bit flakey is the fact that the jdk schedulers have different behaviour using the same nouns and verbs in their method names. My confusion was due to the fact I assumed you used the same conventions as the jdk which isnt quite the case. Perhaps indicating that explicitly in the javadoc would suffice.

Regards and thanks for the feedback guys !
