### ISSUE TITLE
Non-deterministic test failure: ReplaySubjectConcurrencyTest.testReplaySubjectEmissionSubscriptionRace

### ISSUE THREAD

**Issue by benjchristensen** [ReactiveX/RxJava#1972]
This test randomly failed on my local machine. This was just recently added: https://github.com/ReactiveX/RxJava/pull/1947/files#diff-fe6df6db9fa6e69287f256960599708bR338

/cc @akarnokd

**Comment by akarnokd** [comment]
Should be fixed now.
