### ISSUE TITLE
Observable.cache() creates indefinite number of Threads with Schedulers.io()

### ISSUE THREAD

**Issue by michelbetancourt** [ReactiveX/RxJava#2191]
Hi,

It would appear to me that there's an issue with using when using Observable.cache() and Schedulers.io().  The issue is that an indefinite amount of threads are created as opposed to having thread re-use.  

This can eventually lead the following fatal scenario: "java.lang.OutOfMemoryError: Unable to create new native thread".

I did notice that when using Observable.cache() and Schedulers.from(Executors.newCachedThreadPool()) Rx is able to re-use threads.  

Other than thread-caching configuration, it's not clear to me why these 2 implementations produce wildly different thread caching results and behavior.  I can only assume that this behavior is not intended.  It would be great to hear whether that's the case.

Here's a sample program I've put together that demonstrates the 2 different results.  It's a very simple example that creates multiple observables and ensures that they are subscribed to and that result is read.  I'm using SettableFuture to mock a lag between calls.

Result with Schedulers.from(Executors.newCachedThreadPool()) (last few items displayed, notice the re-use in threads):
Thread[pool-1-thread-18,5,main]
Thread[pool-1-thread-15,5,main]
Thread[pool-1-thread-20,5,main]
Thread[pool-1-thread-7,5,main]
Thread[pool-1-thread-6,5,main]
Thread[pool-1-thread-11,5,main]
Thread[pool-1-thread-17,5,main]
Thread[pool-1-thread-4,5,main]
Thread[pool-1-thread-21,5,main]
Thread[pool-1-thread-1,5,main]
Thread[pool-1-thread-18,5,main]
Thread[pool-1-thread-10,5,main]
Thread[pool-1-thread-7,5,main]
Thread[pool-1-thread-11,5,main]
Thread[pool-1-thread-20,5,main]

Result with Schedulers.io() (last few items displayed, notice that the number is incremental, no re-use):
Thread[RxCachedThreadScheduler-187,5,main]
Thread[RxCachedThreadScheduler-196,5,main]
Thread[RxCachedThreadScheduler-189,5,main]
Thread[RxCachedThreadScheduler-198,5,main]
Thread[RxCachedThreadScheduler-191,5,main]
Thread[RxCachedThreadScheduler-200,5,main]
Thread[RxCachedThreadScheduler-193,5,main]
Thread[RxCachedThreadScheduler-195,5,main]
Thread[RxCachedThreadScheduler-197,5,main]
Thread[RxCachedThreadScheduler-199,5,main]

public class RxIndefiniateThreads {

    static final Scheduler scheduler = Schedulers.from(Executors.newCachedThreadPool());

    // static final Scheduler scheduler = Schedulers.io();
    public static void main(String[] args) throws Exception {
        
        int i = 0;
        final AtomicInteger counter = new AtomicInteger(0);
        while (true) {
            final SettableFuture<Object> first = SettableFuture.create();
            final SettableFuture<Object> second = SettableFuture.create();
            Observable<Object> observe = Async.fromCallable(new Callable<Object>() {

                @Override
                public Object call() throws Exception {
                    System.out.println(Thread.currentThread());
                    return first.get();
                }

            }, scheduler).observeOn(scheduler).flatMap(new Func1<Object, Observable<Object>>() {

                @Override
                public Observable<Object> call(Object t1) {
                    System.out.println(Thread.currentThread());
                    try {
                        return Observable.just((Object) (t1.toString() + " :: " + second.get()));
                    } catch (Exception e) {
                        throw new IllegalStateException("Mock exception for second");
                    }
                }
            }).cache();

            final Future<Object> future = observe.toBlocking().toFuture();
            // Thread.sleep(2);
            i++;
            new Thread(new Runnable(){

                @Override
                public void run() {
                    int count = counter.incrementAndGet();
                    try {
                        Thread.sleep(1);
                    } catch (InterruptedException e) {
                        e.printStackTrace();
                    }
                    first.set("done");
                    try {
                        Thread.sleep(1);
                    } catch (InterruptedException e) {
                        e.printStackTrace();
                    }
                    second.set("done");
                    try {
                        future.get();
                    } catch (Exception e) {
                        e.printStackTrace();
                    }
                    // System.out.println("doneWith=" + count);
                }
                
            }).start();
            if (i == 100) {
                break;
            }
        }
        System.out.println("done");
    }
    
}

dependencies:
<dependency>
  		<groupId>com.google.guava</groupId>
  		<artifactId>guava</artifactId>
  		<version>18.0</version>
  	</dependency>
  	<dependency>
            <groupId>io.reactivex</groupId>
            <artifactId>rxjava</artifactId>
            <version>1.0.3</version>
        </dependency>
        <dependency>
            <groupId>io.reactivex</groupId>
            <artifactId>rxjava-async-util</artifactId>
            <version>0.21.0</version>
            <exclusions>
                <exclusion>
                    <groupId>io.reactivex</groupId>
                    <artifactId>rxjava</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

**Comment by michelbetancourt** [comment]
Hi @zsxwing , is the fix ready for testing?

**Comment by zsxwing** [comment]
@michelbetancourt sure, you can test pr #2238 by yourself. I think it will be fixed in the next release once @benjchristensen merges it.

**Comment by duncani** [comment]
I've been looking at this problem as well - I found it in both OnSubscribeCache and OperatorMulticast so far.  I fixed it by adding unsubscribe logic to the Subscribers.from/create factories, and using .from on the Subject in OperatorMulticast instead of the anonymous inner class (which then corrects the OnSubscribeCache case as well).

**Comment by zsxwing** [comment]
@duncani To fix `OperatorMulticast`, you can simply change the line https://github.com/ReactiveX/RxJava/blob/3cecb9037aaf11c131451fef962d749487420798/src/main/java/rx/internal/operators/OperatorMulticast.java#L146 to `source.unsafeSubscribe(subscription);`

Could you also write a test and send a PR?

**Comment by michelbetancourt** [comment]
@zsxwing, I have confirmed that your fix address the original issue -- use of cache operator with Schedulers.io leaking threads.

**Comment by duncani** [comment]
@zsxwing, fair enough, I've submitted PR: https://github.com/ReactiveX/RxJava/pull/2455
