### ISSUE TITLE
window time+size emits only 1 window

### ISSUE THREAD

**Issue by benjchristensen** [ReactiveX/RxJava#2290]
This code only emits 1 window. 

```java
        Observable.range(0, 10000).window(1, TimeUnit.SECONDS, 20).flatMap(o -> {
            System.out.println("window");
           return o.count(); 
        }).toBlocking().forEach(System.out::println);
```

There are 2 issues I have with it:

1) Why are there 21 instead of 20 elements in it?
2) Why does this only emit 1 window? Why does this not just behave like `window(20)` since the time never triggers?

**Comment by akarnokd** [comment]
Fixed.
