### ISSUE TITLE
Make RxJavaPlugins.reset() public

### ISSUE THREAD

**Issue by TomRK1089** [ReactiveX/RxJava#2297]
Let me preface this by saying the RxJava library has made my life easier in just the short time I've been using it. However, there's one jagged edge that bit me today.

I'm attempting to use the `RxJavaPlugins` class to override the default schedulers via `registerSchedulersHook`. However, I want to only override the defaults for a single JUnit test. Ideally, I would call `RxJavaPlugins.getInstance().reset()` in my `@After` method...but I can't, because it is package private.

I could get at it via reflection, but it'd be easier if it was public -- unless there is a) a very good reason it is not or b) there is an obvious alternative I am missing (always a possibility!)

**Comment by akarnokd** [comment]
Why don't you use operators which let you parametrize the scheduler and not rely on the defaults?

For the other hooks, you could set up a level of indirection, i.e., you register your own hook which then does allow setting/removing further hooks at will. You can even create it such a way that multiple hooks can work at the same time, but you have to implement a separate Observable-Observer and make careful decisions when these hooks return some value instead of just consuming.

**Comment by Axxiss** [comment]
As a work around for this what I have done by now is defining a RxJavaTestPlugins class on src/test/java/rx/plugins

    public class RxJavaTestPlugins extends RxJavaPlugins {
        RxJavaTestPlugins() {
            super();
        }

        public static void resetPlugins(){
            getInstance().reset();
        }
    }

And then invoke `resetPlugins()`  on the tear down of my units test.

**Comment by JakeWharton** [comment]
I very much would like something like this, too.

I do something similar to what you have but as a JUnit rule so it can be used as:
```java
@Rule public final RxJavaPluginsResetRule pluginsReset = new RxJavaPluginsResetRule();
```
and it calls `.reset()` both before and after each test.

**Comment by JakeWharton** [comment]
FYI RxAndroid shipped with a `@Beta` `reset()` method public on its `RxAndroidPlugins` class.

**Comment by pakerfeldt** [comment]
@JakeWharton Is there really a point of doing .reset() in your Rule? To me it doesn't seem to have the expected effect. Any subsequent call to Schedulers.* will still return the same original Scheduler even after calling .reset(). Since the hooks are only called once when the Schedulers instance is created.

I can't seem to find a valid use case for using RxJavaPlugins to register test schedulers in unit tests really. Maybe it was never intended for that anyway.

**Comment by pakerfeldt** [comment]
Here's an example of how you can accidently misuse TestScheduler to break unrelated tests.

**Comment by pakerfeldt** [comment]
Actually, using a singleton TestScheduler wrapper we can more easily identify when we accidently initialize Schedulers before our hook is called (instead of just getting weird behavior in the test):
https://gist.github.com/pakerfeldt/db297764918e7d464884

However, that would require all unit tests that happen to execute any code that would initialize Schedulers to first initialize our TestSchedulerProxy (which registers the hook).

**Comment by mikebaum** [comment]
I ran into this exact problem and it was frustrating. I ended up creating the following TestWatcher, which is specific to verifying that there are no leaking subscriptions, but I suppose could be used more generally. 

```
/**
 * This Verifier will assert that any subscriptions created during a test are unsubscribed after the
 * test has finished.<br>
 * 
 * NOTE: It is very important that the call {@link #initialize()} is done before any
 * {@link Observable} is created. Failing to do so, means that the {@link SusbcriptionCollector}
 * would fail to collect any subscriptions.
 */
public class RxTestCaseSubscriptionsVerifier extends TestWatcher
{
    @Override
    protected void starting( Description description )
    {
        SusbcriptionCollector subSusbcriptionCollector = SusbcriptionCollector.getInstance();
        
        checkState( ! subSusbcriptionCollector.isCollecting(),
                    "Cannot start collecting subscriptions while another SusbcriptionCollector is " +
                    "already collecting." );
        
        subSusbcriptionCollector.startCollecting();
    }
    
    @Override
    protected void succeeded( Description description )
    {
        SusbcriptionCollector subSusbcriptionCollector = SusbcriptionCollector.getInstance();
        
        checkState( subSusbcriptionCollector.isCollecting(), 
                    "Cannot assert all subscriptions are unsubscribed if the SusbcriptionCollector " +
                    "was not collecting subscriptions" );
        
        subSusbcriptionCollector.assertAllSubscriptionsAreUnsubscribed();
    }
    
    @Override
    protected void finished( Description description )
    {
        SusbcriptionCollector subSusbcriptionCollector = SusbcriptionCollector.getInstance();
        
        subSusbcriptionCollector.reset();
        
        checkState( ! subSusbcriptionCollector.isCollecting(), 
                    "The SusbcriptionCollector should not be collecting once reset" );
    }
    
    /**
     * See NOTE in the class documentation.
     */
    public static void initialize()
    {
        SusbcriptionCollector.getInstance();
    }
    
    private static class SusbcriptionCollector
    {
        private static SusbcriptionCollector INSTANCE = null;
        
        private final Map<Subscription, String> mSubscriptions =  Collections.synchronizedMap( Maps.newHashMap() );
        private volatile boolean mShouldCollect = false;
        
        private SusbcriptionCollector()
        {
            RxJavaPlugins.getInstance().registerObservableExecutionHook( createSubscriptionCollector() );
        }
        
        static synchronized SusbcriptionCollector getInstance()
        {
            if ( INSTANCE == null )
                INSTANCE = new SusbcriptionCollector();
            
            return INSTANCE;
        }
        
        void startCollecting()
        {
            mShouldCollect = true;
        }

        public void assertAllSubscriptionsAreUnsubscribed()
        {
            synchronized( mSubscriptions )
            {
                for ( Map.Entry<Subscription, String> entry : mSubscriptions.entrySet() )
                {
                    if ( ! entry.getKey().isUnsubscribed() )
                    {
                        fail( "There was an non-unsubscribed subscription detected " +
                              "which was created at the following place:\n" +
                              "<-------------------- start unsubscribed stack -------------------->\n" + 
                              entry.getValue() +
                              "<--------------------- end unsubscribed stack --------------------->" );
                    }
                }
            }
        }

        private void reset()
        {
            synchronized( mSubscriptions )
            {                
                mSubscriptions.clear();
                mShouldCollect = false;
            }
        }
        
        private boolean isCollecting()
        {
            return mShouldCollect;
        }
        
        private RxJavaObservableExecutionHook createSubscriptionCollector()
        {
            return new RxJavaObservableExecutionHook()
            {
                @Override
                public <T extends Object> Subscription onSubscribeReturn( Subscription subscription )
                {
                    if ( ! mShouldCollect )
                        return subscription;
                    
                    String stackTrace = Debug.getStackTrace( new Exception( "Subscription not unsubscribed." ) );
                    mSubscriptions.put( subscription, stackTrace );
                    return subscription;
                };
            };
        }
    }
}
```
then in the test you need to add the following:
```
@Rule public final TestRule mSubscriptionsVerifier = new RxTestCaseSubscriptionsVerifier();
```
or in a Test Suite class you could do this if you want  to use the rule on all tests.
```
    @BeforeClass
    public static void initializeRxVerifier()
    {
        RxTestCaseSubscriptionsVerifier.initialize();
    }
```

**Comment by ivacf** [comment]
I also think making `reset()` public would be very useful for unit testing. At the moment, there isn't a way of calling `registerSchedulersHook` during local unit tests that doesn't end up throwing `java.lang.IllegalStateException: Another strategy was already registered` 

The closes I got was from the constructor of a custom test Runner but this only works for the first test case, the rest would throw the exception above. So the two options I have are: 1) catch the `IllegalStateException` so once my hook is registered it will live for the rest of the tests or 2) call `reset()` via reflection. I'm not happy with any of these options.

**Comment by mikebaum** [comment]
@ivacf Not sure if you are referring to my previous comment, but it's very important that you add:
```
    @BeforeClass
    public static void initializeRxVerifier()
    {
        RxTestCaseSubscriptionsVerifier.initialize();
    }
```

to whatever class groups all you're tests. If you don't have a suite that groups tests, then it's possible this might have to be done before each test. Anyway, this was tricky and frustrating for the reasons you already mentioned.

**Comment by ricamgar** [comment]
As a workaround I am registering the SchedulerHook on the `@BeforeClass` method. 
```java
    @BeforeClass
    public static void setUpHooks() throws Exception {
        RxJavaPlugins.getInstance().registerSchedulersHook(new RxJavaSchedulersHook() {
            @Override
            public Scheduler getIOScheduler() {
                return Schedulers.immediate();
            }
        });
    }
```
Do you guys see any potential issue?

**Comment by shivangshah** [comment]
:+1: 
I was trying to contribute back to `spring-cloud-sleuth` to have distributed tracing capabilities across RxJava threadpools as well (https://github.com/spring-cloud/spring-cloud-sleuth/issues/235). I am following their current `Hystrix` implementation strategy : https://github.com/spring-cloud/spring-cloud-sleuth/blob/master/spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/hystrix/SleuthHystrixConcurrencyStrategy.java#L66
You could reset HystrixPlugins but the same cannot be done right now with RxjavaPlugins. I have to create a wrapper (as mentioned above) in the same `rx.plugins` folder as a workaround (testing as we speak if it's working or not). 
It'd be good to not have to do this workaround.

**Comment by marcingrzejszczak** [comment]
Hi! @benjchristensen @akarnokd @mattrjacobs @abersnaze  - any news on this? It doesn't seem like a big change and would certainly be helpful in Spring Cloud Sleuth's intergration with RxJava.

**Comment by akarnokd** [comment]
I don't use the plugin API so can't tell if its worth it or what consequences it holds. PR welcome.

**Comment by akarnokd** [comment]
Closing via #3820

**Comment by Alisunov** [comment]
I'm getting problem when I use:
`@ClassRule public static final RxJavaPluginsResetRule pluginsReset = new RxJavaPluginsResetRule();`
instead of:
`@Rule public final RxJavaPluginsResetRule pluginsReset = new RxJavaPluginsResetRule();`

`@ClassRule` causes `(singleExecutionHook.get() == null)` to be `true` in `RxJavaPlugins.getSingleExecutionHook()` which leads to default hook for `RxJavaPlugins`.

How can it be possible?
Thanks!

**Comment by afjoseph** [comment]
Not sure if its related to this issue, but just wanted to say that RxJava2 changed a few things about how to override schedulers. I found another way outlined here: http://stackoverflow.com/a/43320828/3870025
