### ISSUE TITLE
Schedulers.from(Executor) creates Scheduler.Worker that may not be single threaded

### ISSUE THREAD

**Issue by allenxwang** [ReactiveX/RxJava#2448]
According to a conversation with @benjchristensen, `Schedulers.from(Executor)` should create a Scheduler.Worker that is single threaded even if Executor is backed by multiple threads. 

Otherwise, there will be threading issue in `Observable.interval(long, TimeUnit, Scheduler)` if a scheduler is from a multi-threaded Executor, as the following example shows. 

```java
ExecutorService executor = Executors.newFixedThreadPool(2);
        Observable.interval(100, TimeUnit.MILLISECONDS, Schedulers.from(executor))
                .take(10)
                .toBlocking()
                .forEach(new Action1<Long>() {
                    @Override
                    public void call(Long aLong) {
                        System.out.println(Thread.currentThread().getName());
                    }
                });

pool-1-thread-1
pool-1-thread-2
pool-1-thread-1
pool-1-thread-2
pool-1-thread-1
pool-1-thread-2
pool-1-thread-1
pool-1-thread-2
pool-1-thread-1
pool-1-thread-2
```

Since the sequence is emitted from two threads, it creates safe publishing issue for the counter in `OnSubscribeTimerPeriodically`:

```java
    @Override
    public void call(final Subscriber<? super Long> child) {
        final Worker worker = scheduler.createWorker();
        child.add(worker);
        worker.schedulePeriodically(new Action0() {
            long counter;
            @Override
            public void call() {
                try {
                    child.onNext(counter++);
                } catch (Throwable e) {
                    try {
                        child.onError(e);
                    } finally {
                        worker.unsubscribe();
                    }
                }
            }
            
        }, initialDelay, period, unit);
    }
```

**Comment by zsxwing** [comment]
I think it's safe because `Worker.schedulePeriodically` will submit the next action after the previous action. 
```Java
        public Subscription schedulePeriodically(final Action0 action, long initialDelay, long period, TimeUnit unit) {
            final long periodInNanos = unit.toNanos(period);
            final long startInNanos = TimeUnit.MILLISECONDS.toNanos(now()) + unit.toNanos(initialDelay);

            final MultipleAssignmentSubscription mas = new MultipleAssignmentSubscription();
            final Action0 recursiveAction = new Action0() {
                long count = 0;
                @Override
                public void call() {
                    if (!mas.isUnsubscribed()) {
                        action.call();
                        long nextTick = startInNanos + (++count * periodInNanos);
                        mas.set(schedule(this, nextTick - TimeUnit.MILLISECONDS.toNanos(now()), TimeUnit.NANOSECONDS));
                    }
                }
            };
            mas.set(schedule(recursiveAction, initialDelay, unit));
            return mas;
        }
```
Since the codes before `executor.execute` happend-before the submitted Runnable, the previous action should happend-before  the next action.

**Comment by allenxwang** [comment]
Does that mean ```Schedulers.from(Executor)``` is meant to create multi-threaded Worker? And I can expect ```Observable.observeOn(Scheduler)``` to split the work among multiple threads?

**Comment by zsxwing** [comment]
> Does that mean Schedulers.from(Executor) is meant to create multi-threaded Worker?

Yes if `Executor` is a multi-threaded executor.

> And I can expect Observable.observeOn(Scheduler) to split the work among multiple threads?

No. There is only one of `onNext`, `onCompleted`, `onError` running at the same time. RxJava guarantees calling `onNext`, `onCompleted`, `onError` in sequence. It means non-overlapping. However, these methods may run in different threads. So don't assume they will run in the same thread and use `ThreadLocal`.

**Comment by benjchristensen** [comment]
They can not run concurrently. Different threads can be used each time (generally not a good idea but a scheduler can choose to do so) but it must not add out-of-order execution or concurrent emission.

**Comment by akarnokd** [comment]
The Scheduler created from an Executor is weaker than the other Schedulers in respect of unavoidable thread hopping, but nonetheless it still ensures no concurrent onXXX is called even if the Executor is multi-threaded. The regular schedulers use one threadpool per worker since RxJava controls the creation and use of those threadpools.

**Comment by allenxwang** [comment]
Sounds reasonable. Thanks for the explanation.
