### ISSUE TITLE
ConcurrentModificationException from ViewObservable.clicks()

### ISSUE THREAD

**Issue by TomRK1089** [ReactiveX/RxJava#2449]
If the observer of a `ViewObservable.clicks(view)` causes itself to unsubscribe as a result of the click, a `ConcurrentModificationException` is thrown.

For example, I have a Fragment which binds to a button in `onViewCreated` and adds the returned subscription to a `CompositeSubscription`. In `onDestroyView` I unsubscribe the `CompositeSubscription`. Since the observer of the button causes me to switch fragments, it leads to the fragment's view being destroyed -- and since the `CompositeOnClickListener` does not use a thread-safe list, it throws an exception.

Simplest fix is probably to use a `CopyOnWriteArrayList`, but I question if there's a better approach in general to this approach.

**Comment by zsxwing** [comment]
It's an issue of RxAndroid. Could you move this issue to https://github.com/ReactiveX/RxAndroid ?

**Comment by TomRK1089** [comment]
My mistake, the wiki link here led me to believe it was one repo.
