### ISSUE TITLE
Wiki: Typo in url on https://github.com/ReactiveX/RxJava/wiki/Scheduler

### ISSUE THREAD

**Issue by willemsst** [ReactiveX/RxJava#2451]
The url on the page is referring to

http://reactivex.io/documentations/scheduler.html

while this should be 

http://reactivex.io/documentation/scheduler.html

**Comment by DavidMGross** [comment]
Thanks. I've made the correction.

On Tue, Jan 13, 2015 at 1:12 PM, Steven Willems <notifications@github.com>
wrote:

> The url on the page is referring to
>
> http://reactivex.io/documentations/scheduler.html
>
> while this should be
>
> http://reactivex.io/documentation/scheduler.html
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ReactiveX/RxJava/issues/2451>.
>



-- 
David M. Gross
PLP Consulting
