### ISSUE TITLE
Per version Javadoc seems to be not updated.

### ISSUE THREAD

**Issue by alkemist** [ReactiveX/RxJava#2457]
http://reactivex.io/RxJava/javadoc/1.0.4/ - 404
http://reactivex.io/RxJava/javadoc/1.0.0/ - 200

**Comment by samuelgruetter** [comment]
Those who can write to https://github.com/ReactiveX/reactivex.github.io, @GeorgiKhomeriki, @DavidMGross

**Comment by GeorgiKhomeriki** [comment]
I might be missing something, but afaik the RxJava javadoc isn't hosted in the  https://github.com/ReactiveX/reactivex.github.io repo.

**Comment by benjchristensen** [comment]
The javadocs are hosted in the RxJava projects, not reactivex.github.io, and they are still manually done by me which means they often go along time without updates. I'll update now and open an issue for automating.

**Comment by benjchristensen** [comment]
Check out issue #2631. I'd be happy for someone to provide a proper solution to generating the Javadocs and committing them back to Github on each build.

**Comment by benjchristensen** [comment]
1.0.5 was pushed. Automating each version will be left to #2631 to do.
