### ISSUE TITLE
Lifting into a Subject

### ISSUE THREAD

**Issue by abersnaze** [ReactiveX/RxJava#2458]
Mildly interesting idea to see if there would be any interest.

```
public class Subject<T, R> extends Observable<R> implements Observer<T> {
    ...
    public <X> Subject<X, R> liftHead(final Operator<? extends T, ? super X> op) { ... }
    public <X> Subject<T, X> liftTail(final Operator<? extends X, ? super R> op) { ... }

    @Override
    public <X> Subject<T, X> lift(final Operator<? extends X, ? super R> op) { return liftTail(op); }
}
```

**Comment by akarnokd** [comment]
What do you want to achieve with this change?

**Comment by abersnaze** [comment]
Up till now all the APIs that want to delegate part of the observable change chain to another piece of code has had to pass in the head as an argument.  With these methods the delegate could return a subject the represents the some segment of the chain without any arguments.

For example `retryWhen()` takes a notification handler `Func1<Observable<Exception>, Observable<?>>`.  With this it would have been possible for `retryWhen` to take a notification handler `Func0<Subject<Exception, ?>`

**Comment by akarnokd** [comment]
If I understand correctly, a chain of Subject<Integer, String> -> Subject<String, Date> -> Subject<Date, Long>, I can hand out each to different parties and observe them at any point?

**Comment by abersnaze** [comment]
Yes.  The `Subject` returned could be reused to `subscribe()` different source observables.  The `Subject` would just be an capsulation of some computation without defining where the data comes from or where it is going to.

**Comment by benjchristensen** [comment]
The encapsulation of computation sounds like the Transformer with Observable.compose.

**Comment by akarnokd** [comment]
Do you still want to pursue this?

**Comment by benjchristensen** [comment]
Punting to 2.0 for bikeshedding.

**Comment by akarnokd** [comment]
See #3975.

**Comment by akarnokd** [comment]
I'm closing this as the PR implementing the proposed feature was not really endorsed by the OP after all. If you have further input on the issue, don't hesitate to reopen this issue or post a new one.
