### ISSUE TITLE
Out of requests in merge

### ISSUE THREAD

**Issue by grzechum** [ReactiveX/RxJava#2466]
Below test, when run, quickly goes out of requests, merge operator is quite complex and it is difficult to say what exactly causes the problem but it looks like race condition, because each run gives different results.

This may be related to #1941 but scenario is different.

```java
	private final class OnSubscribeImpl implements OnSubscribe<String> {
		private final int id;
		private final Semaphore requested = new Semaphore(0); // back pressure control

		public OnSubscribeImpl(int id) {
			this.id = id;
		}

		@Override
		public void call(Subscriber<? super String> s) {
			s.setProducer(new Producer() {
				@Override
				public void request(long n) {
					System.out.println(id + " - REQUESTED: " + n);
					requested.release((int) n);
				}
			});

			try {
				long counter = 0;
				while (true) {
					requested.acquire();
					System.out.println(id + " - REMAININIG: " + requested.availablePermits());

					s.onNext(id + " - " + (counter++));
				}
			} catch (InterruptedException ex) {
				ex.printStackTrace();
			}
		}
	}

	@Test
	public void testX() throws InterruptedException {

		Observable<String> obs0 = Observable.create(new OnSubscribeImpl(0)).subscribeOn(Schedulers.io());
		Observable<String> obs1 = Observable.create(new OnSubscribeImpl(1)).subscribeOn(Schedulers.io());

		Observable.merge(obs0, obs1).observeOn(Schedulers.computation()).forEach(s -> System.out.println(s));

		Thread.sleep(Long.MAX_VALUE);
	}
```

**Comment by benjchristensen** [comment]
This will require some time to dig into.

**Comment by grzechum** [comment]
Thanks,

I found a workaround for this, which solves the problem for low and medium load.
- remove backpressure control from producer
- add onBackpressureBlock() after subscribeOn()

```java
	private final class OnSubscribeImpl implements OnSubscribe<String> {
		private final int id;

		public OnSubscribeImpl(int id) {
			this.id = id;
		}

		@Override
		public void call(Subscriber<? super String> s) {
			try {
				long counter = 0;
				while (true) {
					s.onNext(id + " - " + (counter++));
				}
			} catch (Exception ex) {
				ex.printStackTrace();
			}
		}
	}

	@Test
	public void testX() throws InterruptedException {

		Observable<?> obs0 = Observable.create(new OnSubscribeImpl(0)).subscribeOn(Schedulers.io())
				.onBackpressureBlock();
		Observable<?> obs1 = Observable.create(new OnSubscribeImpl(1)).subscribeOn(Schedulers.io())
				.onBackpressureBlock();

		Observable.merge(obs0, obs1).observeOn(Schedulers.computation()).forEach(s -> System.out.println(s));

		Thread.sleep(Long.MAX_VALUE);
	}
``` 

but still under heavy load when consumers are slow I see increasing number of events buffered somewhere inside merge() and/or onBackpressureBuffer() - I will expect buffering around hundreds of messages (ring buffers) but I observe tens of thousands of messages being buffered  - but this is just a quick observation and I need to dig more to understand where the events are buffered.

**Comment by akarnokd** [comment]
Hi, I'm looking at this issue right now (great test btw, fails all the time as required by debugging :).

**Comment by akarnokd** [comment]
It seems some downstream requests don't get executed on the SubscribeOn's worker because the same worker is blocked on an acquire. onBackpressureBlock works because it disregards the upstream's backpressure capability. So blocking and backpressure awareness doesn't work well on the same subscribeOn worker.

**Comment by grzechum** [comment]
I'believe downstream request must be pushed from consuming thread(s) when buffers slots become available. SubscribeOn thread must block to slow down producer ?

**Comment by akarnokd** [comment]
SubscribeOn schedules a request onto the same thread as the emission took place. The reason is to be consistent with pre-backpressure behavior where all of the values would be emitted from this single thread.

**Comment by grzechum** [comment]
Thanks, that explains the problem - quick test shows that as you pointed, the same thread is scheduled for request.

But, I do not see elegant workaround/solution for this yet...
    - e.g. when to release subscribeOn thread having the guarantee that request will be called from downstream (when requests == 0?)

**Comment by akarnokd** [comment]
The whole backpressure logic is based on continuations so you don't need to block/unblock a thread (and avoid a same-pool deadlock). You could rewriter your Observable with the help of AbstractOnSubscribe which takes care of the backpressure or use onBackpressureBlock.

**Comment by grzechum** [comment]
Thanks, that works well:

```java
	Observable<String> create(int id, long limit) {
		AtomicLong counter = new AtomicLong();
		return AbstractOnSubscribe.<String, Void> create(s -> {
			if (counter.get() < limit) {
				s.onNext(id + " - " + counter.incrementAndGet());
			} else {
				s.onCompleted();
			}
		}).toObservable();
	}

	@Test
	public void testX() throws InterruptedException {
		Semaphore end = new Semaphore(0);

		Observable<String> obs0 = create(0, 100000).subscribeOn(Schedulers.io());
		Observable<String> obs1 = create(1, 100000).subscribeOn(Schedulers.io());

		Observable.merge(obs0, obs1).observeOn(Schedulers.computation())
				.subscribe(System.out::println, System.out::println, () -> end.release());

		end.acquire();
	}
```
