### ISSUE TITLE
How to stop observable execution

### ISSUE THREAD

**Issue by pradhakrishnan** [ReactiveX/RxJava#2525]
Hi,

I have some set of observable which I am executing in parallel. I need to get the value of observable who is completing first. If the return value meets my requirement then i need to stop the execution of other observables. I couldn't find the example for that. 

I could do this scenario through Callable interface and CompletionService interface from concurrent package.

sample code using concurrent package
```
@Autowired
private CompletionService<Result> cService;

List<Future<Result>> statusList = new ArrayList<Future<Result>>();
try{
for(String str: strLst){
		statusList.add(cService.submit(new GetItemOnCallable(msg)));
	}

	for(int i =0; i < statusList.size(); i++){
		Result status = cService.take().get();
		if(null != status){
		 if(staus.equals(Result.SUCCESS))
		 break;
	}
}finally{
for(Future<Result> statusFuture: statusList){
	statusFuture.cancel(true);
}
}
```

Is there any way to achieve this using observable?
Can someone please help on this.

Regards
Pranesh

**Comment by akarnokd** [comment]
We have the ```amb``` operator which streams the first responding source observable. You could filter your sources then amb them to get the first matching value:

```java
amb(source1.filter(predicate), source2.filter(predicate))
```

**Comment by pradhakrishnan** [comment]
Thanks Akarnokd.

**Comment by pradhakrishnan** [comment]
It works fine. Thanks Akarnokd. 
I have one question on this. What will happen if none of my source observable meets my filter.

**Comment by akarnokd** [comment]
You get an empty sequence which just calls onCompleted.

**Comment by pradhakrishnan** [comment]
Got it!!! Thanks Akarnokd.

**Comment by akarnokd** [comment]
You are welcome.
