### ISSUE TITLE
Subscriber.request add ignore for negative requests

### ISSUE THREAD

**Issue by davidmoten** [ReactiveX/RxJava#2545]
So that negative requests don't need to be checked by every ```Operator``` that supports backpressure why don't we add a check at the start of ```Subscriber.request```:

```java
protected final void request(long n) {
        // ignore zero or negative requests
        if (n <=0) return;
        Producer shouldRequest = null;
        synchronized (this) {
            if (p != null) {
                shouldRequest = p;
            } else {
                requested = n;
            }
        }
        // after releasing lock
        if (shouldRequest != null) {
            shouldRequest.request(n);
        }
    }
```

Happy to submit PR if has support.

**Comment by zsxwing** [comment]
Looks a good place to add it. Just a bit comment: Ignore zero but IAE for negative numbers, as per #1956

**Comment by davidmoten** [comment]
I did wonder about that, and makes sense. I'll make a PR.

**Comment by davidmoten** [comment]
Looks to me that n = 0 should be allowed through because it may override a default of Long.MAX_VALUE sometimes (asking an upstream producer to produce nothing as opposed to whatever a default might be). I'll make a PR with the n < 0 check only.
