### ISSUE TITLE
What is the policy regarding breaking TestObserver/TestSubscriber/TestScheduler 

### ISSUE THREAD

**Issue by zsxwing** [ReactiveX/RxJava#2549]
TestObserver/TestSubscriber/TestScheduler should only be used in the test codes. Should we have same policy as the other public APIs?

**Comment by zsxwing** [comment]
@benjchristensen as your comment in https://github.com/ReactiveX/RxJava/issues/2555#issuecomment-72726415
I think you agree that we can break these Test APIs if necessary?

**Comment by benjchristensen** [comment]
Those are part of the public API and will break a project build if we change them. We can't break public APIs.

**Comment by benjchristensen** [comment]
What did my comment have to do with breaking changes?

**Comment by zsxwing** [comment]
I had comments in #2555 but you didn't reply:
> I hope we can have some conclusion for #2549 before releasing 1.0.5, because I think awaitTerminalEvent(long timeout, TimeUnit unit) has been broken in #2332: before that it's quiet if timeout, but now it will throw a RuntimeException.

> I think the current behavior is more reasonable. I just wonder the policy about changing the behavior of a method in TestObserver/TestSubscriber/TestScheduler. For the changing of awaitTerminalEvent(long timeout, TimeUnit unit), should it be classified as a bug fix or a breaking change?

**Comment by zsxwing** [comment]
Here is the breaking change: https://github.com/ReactiveX/RxJava/pull/2332/files#diff-fbed6a16f49022fd2b10f45fd6dd015bR230

**Comment by benjchristensen** [comment]
That's in the gray area as it is a semantic change, not an API change. So whether that's acceptable or not depends on if it is fixing a bug or not. If it's not and it is changing behavior then that's something we should not do.

It seems to me it was not a bug, and the javadoc clearly states what it was doing (wait until timeout or completion). So, I think that change should be reverted.

**Comment by benjchristensen** [comment]
I reverted the change in https://github.com/ReactiveX/RxJava/pull/2594

If we need this new behavior then we need to discuss it more and determine if it really is a bug and should have always been throwing an exception, or if there are times when returning without an error on timeout is legit behavior and thus we need two different methods. Go ahead and open a new issue to discuss this.
