### ISSUE TITLE
Connectable observable won't publish errors to all subscribers

### ISSUE THREAD

**Issue by amitai-hoze** [ReactiveX/RxJava#2556]
Hi, I'm using a connectable observable and I want all the subscribers to get errors, but they don't.
I'm using RxJava 1.0.4, and developing on Android.

This is an example of this behavior:
```java
Observable<String> o = Observable.defer(() -> {
    if (start)
    {
        start = false;
        return Observable.error(new Exception("Some exception"));
    }
    else {
        return Observable.just("Value 1", "Value 2", "Value 3");
    }
});

Observable<String> published = o.publish().refCount();

published
        .doOnError(t -> {System.out.println("subscriber 1 error: " + t.getMessage());})
        .retry()
        .subscribe(s -> {System.out.println("subscriber 1: " + s);});

published
        .doOnError(t -> {System.out.println("subscriber 2 error: " + t.getMessage());})
        .retry()
        .subscribe(s -> {System.out.println("subscriber 2: " + s);});
```

This is the output
```
subscriber 1 error: Some exception
subscriber 1: Value 1
subscriber 1: Value 2
subscriber 1: Value 3
subscriber 2: Value 1
subscriber 2: Value 2
subscriber 2: Value 3
```

Is this expected? How can other subscribers know about errors and handle them then?

**Comment by benjchristensen** [comment]
That is all synchronous so will execute the origin Observable 3 times and thus only emit the error for the first one. It subscribes, increments count to 1, completes, decrements to 0, then repeats. Each time it goes from 0 to 1 it runs the Observable you defined inside defer. 

RefCount is only useful if you have concurrent subscribers to an async stream. 

If there were multiple subscribers when the error was emitted then they would all receive the error.

**Comment by amitai-hoze** [comment]
OK, that makes sense, thanks
