### ISSUE TITLE
Copyright 2014 Netflix, Inc. -> 2015?

### ISSUE THREAD

**Issue by akarnokd** [ReactiveX/RxJava#2562]
Just a few considerations:

  - README.md still lists 2013
  - Update headers to year 2015
  - Do we keep naming Netflix as the copyright owner since we moved to io.reactivex?

**Comment by benjchristensen** [comment]
I don't know how important it is to update the date unless the file is actually changed. 

As for Netflix, the desire is to move from that but we haven't yet made ReactiveX Org an official legal entity. I've been holding off on sweeping changes until I figure that out with lawyers (started the conversation, I need to go finish it). =

**Comment by benjchristensen** [comment]
Closing as it doesn't really matter.
