### ISSUE TITLE
Patent status of the library

### ISSUE THREAD

**Issue by kostix123** [ReactiveX/RxJava#2570]
It seems that Microsoft patented many aspects of reactive extensions. See, for example, https://www.google.com/patents/US20110107392 and other patents with the same authors. What's the legal status of the library? Did Microsoft granted the license for patent to Netflix, or it was derived from Rx for .NET library somehow.

**Comment by kostix123** [comment]
It seems that @headinthebox is one of the authors of the patent. May be he can comment on this.

**Comment by benjchristensen** [comment]
I can't comment on Microsoft patents. Closing this issue since I am not a lawyer and can not provide answers to your questions.
