### ISSUE TITLE
Non-deterministic test: OperatorMergeMaxConcurrentTest

### ISSUE THREAD

**Issue by davidmoten** [ReactiveX/RxJava#2571]
The following tests timed out after 10s when running full suite in Eclipse on fast machine.

testSimpleAsyncLoop
testSimpleOneLessAsyncLoop

**Comment by akarnokd** [comment]
Strange. Both test have an internal 1s timeout in case the merge hangs. Both test repeat the main part a 1000 times. I get 1.6s and 0.9s on my i7 920. Could you remove the timeout, let it run and do a threaddump when it hangs?

**Comment by akarnokd** [comment]
Is this still a problem?

**Comment by benjchristensen** [comment]
Closing due to age.
