### ISSUE TITLE
Unused method

### ISSUE THREAD

**Issue by jakudlaty** [ReactiveX/RxJava#2577]
Hi
I think that `shutdown()` method of `rx.internal.util.ObjectPool` is never used. The result is that every ObjectPool schedules an instance of `Action0` in constructor and NEVER unsubscribes the `schedulerWorker`.

Is that intentional?

I know why all object pools are static :), but this is some kind of leak - 5 workers working forever :)

**Comment by akarnokd** [comment]
The current Scheduler behavior is not container-friendly (i.e., Tomcat will complain about RxJava threads). These pools were introduced to increase performance and are never explicitly terminated (they stop on JVM exit). There was some movement to make schedulers shutdownable but the discussion stopped after a while and certain decisions were not made. This leak is at least minimal.

**Comment by jakudlaty** [comment]
Thanks for quick answer :)

**Comment by jakudlaty** [comment]
Should I close the issue?
