### ISSUE TITLE
Can we get Travis to deploy SNAPSHOTs to Sonatype?

### ISSUE THREAD

**Issue by davidmoten** [ReactiveX/RxJava#2586]
I frequently find myself wanting to use the latest SNAPSHOT version of RxJava in open source projects on github. It's usually a temporary thing till the next release comes along but I'd like CI on those open source projects to pass while I'm waiting and my work partners to just pull and build without having to build and install SNAPSHOT deps manually.

Any chance of incorporating this into the Travis CI  of rxjava? (I'm assuming this doesn't happen already).

One how-to is http://benlimmer.com/2014/01/04/automatically-publish-to-sonatype-with-gradle-and-travis-ci/

**Comment by JakeWharton** [comment]
:+1: Wanted to bring this up for RxAndroid as well.

**Comment by JakeWharton** [comment]
Also happy to help. Recently rolled this out to 30+ repos of both Maven and
Gradle.

**Comment by akarnokd** [comment]
This would be great; our release cycle is too long and I have to manually build and update all my projects using RxJava to get rid of bugs.

**Comment by davidmoten** [comment]
@JakeWharton so for example https://github.com/JakeWharton/butterknife/commit/bac2342500971a3c6664629c3a63ca74d6e4819c ?

**Comment by davidmoten** [comment]
@JakeWharton  can you contribute a PR on this one?

**Comment by JakeWharton** [comment]
I can do the work, but I need the secrets for this repo.

The way that I did this was:
 1. Create a new user on Sonatype dedicated to snapshot deployments.
 2. Ask for snapshot-only access permissions to the `groupId` (see [OSSRH-12860](https://issues.sonatype.org/browse/OSSRH-12860)).
 3. Use the [`travis` gem](http://docs.travis-ci.com/user/encryption-keys/#Usage) to create the secrets (these are per-repo) from the username and password of the Sonatype account.

**Comment by benjchristensen** [comment]
I can post encrypted secrets in the `.travis.yml` file. 

I think we've already got all the snapshot stuff in place, we just don't use it. 

@rspieldenner does the Nebula build already have stuff in place for this?

**Comment by benjchristensen** [comment]
I got releases to Bintray working tonight via Travis: https://github.com/ReactiveX/RxJava/issues/1810

It shouldn't be much more effort to make snapshots happen now. The Nebula plugin has a `snapshot` task:

```
./gradlew snapshot
```

Running that tries to upload to Sonatype and fails with missing credentials (as I didn't pass them in). I can add those to the .travis.yml file.

**Comment by benjchristensen** [comment]
@rspieldenner I can't find the docs for how to define the credentials for the snapshot job. I'm looking here: https://github.com/nebula-plugins/nebula-release-plugin

**Comment by rspieldenner** [comment]
Take a look at https://github.com/nebula-plugins/nebula-bintray-plugin

**Comment by benjchristensen** [comment]
Do snapshots go via the bintray plugin as well? What is the nebula-ojo-publishing thing that references snapshots? 

If it happens via Bintray, then those credentials already exist, so all I need to do is add "snapshot" to the normal build arguments right? --> https://github.com/ReactiveX/RxJava/blob/1.x/gradle/buildViaTravis.sh#L6

**Comment by benjchristensen** [comment]
I got it to build and deploy a snapshot but it has issues.

1) Wrong filename
2) Build failed with a git issue
3) No idea where to find the snapshot.

@rspieldenner What config do I need to use to get the name of the file done correctly? For example, it shouldn't have jumped to 1.1.0-SNAPSHOT. And it's having an issue with HEAD ... why does it care about that and fail?

Log at https://travis-ci.org/ReactiveX/RxJava/builds/49498308#L3289

Here is the config: https://github.com/ReactiveX/RxJava/blob/1.x/gradle/buildViaTravis.sh#L9

**Comment by rspieldenner** [comment]
So with how we're setup SNAPSHOT builds will be deployed to oss.jfrog.org

To resolve them in gradle:

    repositories {
      maven {
        url 'http://oss.jfrog.org/artifactory/libs-snapshot'
      }
    }

To resolve them in maven:

    <repository>
      <snapshots />
      <id>snapshots</id>
      <name>libs-snapshot</name>
      <url>http://oss.jfrog.org/artifactory/libs-snapshot</url>
    </repository>

**Comment by rspieldenner** [comment]
To have snapshots default to bumping the patch number add the following to gradle.properties

    release.scope=patch

**Comment by rspieldenner** [comment]
And not sure why it cares about the git repo for snapshot releases as they don't create tags. Checking now.

**Comment by rspieldenner** [comment]
Options on the release git issue.

1) Make sure travisci checks out to a branch that has upstream set to a branch it can push to
2) Remove the push logic in the gradle-rxjava-project-plugin for snapshot builds. It's possible that with reactivex's general workflow you'll never need the plugin to tag so in the project-plugin we could always remove the default behavior

    if (condition) {
      project.tasks.release.deleteAllActions()
    }

**Comment by benjchristensen** [comment]
> 1) Make sure travisci checks out to a branch that has upstream set to a branch it can push to

I don't know how to do that.

> It's possible that with reactivex's general workflow you'll never need the plugin to tag

Never is difficult to ensure, particularly since most still use the CloudBees build and release model right now.

It would be great if it was a property I could set so when building/releasing via Travis is never tries to touch the tags.

**Comment by rspieldenner** [comment]
nebula-plugins/gradle-rxjava-project-plugin#13

**Comment by benjchristensen** [comment]
Can I use the `deleteAllActions` approach for now until that issue is resolved? Or do I need to just disable the snapshot releases for the build to work?

**Comment by rspieldenner** [comment]
you can use the deleteAllActions now, I'll probably release a fix tonight
or tomorrow

**Comment by rspieldenner** [comment]
New Version of gradle-rxjava-project-plugin released. You should be able to add `-Prelease.travisci=true` to get the behavior

**Comment by benjchristensen** [comment]
This did not work: 

```
./gradlew -Prelease.travisci=true -PbintrayUser="${bintrayUser}" -PbintrayKey="${bintrayKey}" snapshot --stacktrace
```

https://travis-ci.org/ReactiveX/RxJava/builds/49704199

**Comment by rspieldenner** [comment]
Well prepare failed and I didn't check there. Looking how to get around
that one.

**Comment by rspieldenner** [comment]
I think I have it this time. Please give it another shot. 2.2.4 of the gradle-rxjava-project-plugin is released.

**Comment by benjchristensen** [comment]
The build worked and snapshot was deployed:

```
:artifactoryPublish
Deploying artifact: https://oss.jfrog.org/oss-snapshot-local/io/reactivex/rxjava/1.1.0-SNAPSHOT/rxjava-1.1.0-SNAPSHOT.jar
Deploying artifact: https://oss.jfrog.org/oss-snapshot-local/io/reactivex/rxjava/1.1.0-SNAPSHOT/rxjava-1.1.0-SNAPSHOT-javadoc.jar
Deploying artifact: https://oss.jfrog.org/oss-snapshot-local/io/reactivex/rxjava/1.1.0-SNAPSHOT/rxjava-1.1.0-SNAPSHOT.pom
Deploying artifact: https://oss.jfrog.org/oss-snapshot-local/io/reactivex/rxjava/1.1.0-SNAPSHOT/rxjava-1.1.0-SNAPSHOT-sources.jar
Deploying artifact: https://oss.jfrog.org/oss-snapshot-local/io/reactivex/rxjava/1.1.0-SNAPSHOT/rxjava-1.1.0-SNAPSHOT-benchmarks.jar
Deploying build info to: https://oss.jfrog.org/api/build
Build successfully deployed. Browse it in Artifactory under https://oss.jfrog.org/webapp/builds/rxjava/1423256083376/2015-02-06T20:54:37.458+0000/
:verifyReleaseStatus UP-TO-DATE
:bintrayUpload SKIPPED
:release
```

Just the version number now needs to be fixed. Just set that property and building again ...

**Comment by benjchristensen** [comment]
Here is a link to the snapshot artifacts: https://oss.jfrog.org/webapp/search/artifact/?1-2.ILinkListener-searchTabs-panel-searchBorder-results-topToolbars-toolbars-2500-headers-5-header-orderByLink&q=rxjava

Is this the naming convention that is normal?

For example, is it normal to need to put `rxjava-1.1.0-20150206.061850-5` as the artifact name for snapshots?

**Comment by benjchristensen** [comment]
@rspieldenner It fails when telling it to use `patch` for version increments.

https://travis-ci.org/ReactiveX/RxJava/builds/49795313#L387

**Comment by benjchristensen** [comment]
Here is where that is configured: https://github.com/ReactiveX/RxJava/blob/1.x/build.gradle#L26

**Comment by rspieldenner** [comment]
You can add a gradle.properties file. Like eureka https://github.com/Netflix/eureka/blob/master/gradle.properties

Or in build.gradle

project.setProperty('release.scope', 'patch')

**Comment by rspieldenner** [comment]
As to the rxjava-1.1.0-20150206.061850-5 version. That is the actual timestamped version but can be referenced via rxjava-1.1.0-SNAPSHOT.

**Comment by benjchristensen** [comment]
Setting that property did not work: https://travis-ci.org/ReactiveX/RxJava/builds/49800810#L376

**Comment by rspieldenner** [comment]
Maybe `project.ext.set('release.scope', 'patch')`

**Comment by rspieldenner** [comment]
I would tend to favor putting it in gradle.properties so that it could be overridden via command line.

**Comment by benjchristensen** [comment]
Should any of these other configs/properties go into grade.properties then? -> https://github.com/ReactiveX/RxJava/blob/1.x/build.gradle#L20

**Comment by rspieldenner** [comment]
the nebulaRelease config needs to be in a build.gradle since its doing something programatic not just settings a property

description can go in either. I doubt you'd ever want to override that from the command line so safe in build.gradle

**Comment by benjchristensen** [comment]
Looks like that worked: https://travis-ci.org/ReactiveX/RxJava/builds/49812918#L3296

It is a 1.0.6-SNAPSHOT that got built and released.

Can others confirm whether this is now working as desired?

@rspieldenner Is there anything in my config that you would change or cleanup (considering the trial and error approach I took)? Getting build systems working is such whack-a-mole! :-)

**Comment by akarnokd** [comment]
Did this finally work, can this issue be closed?

**Comment by benjchristensen** [comment]
This is working.
