### ISSUE TITLE
Code style guide

### ISSUE THREAD

**Issue by jakudlaty** [ReactiveX/RxJava#2602]
Hi
I have question about code style. Where can I read code style guidelines?
I thik some of the conventions used in source code are making code less readable than it could be.
I couldnt find any information why this:
```
if (cond) {
   return x;
} else if(cond2) {
   return y;
} else {
   return z;
}
``` 
is considered as  more readable than this:

```
if (cond) {
   return x;
}
if (cond2) {
   return y;
}
return z;
```
Is there any performance difference or simply matter of taste?

Another problem is a lack of consequence.
In one place i can see multiple return statements:
```
   public int add(E e) {
        int i = getIndexForAdd();
        if (i < SIZE) {
            // fast-path when we are in the first section
            elements.array.set(i, e);
            return i;
        } else {
            int sectionIndex = i % SIZE;
            getElementSection(i).array.set(sectionIndex, e);
            return i;
        }
    }
```
In the same file - "single return statement" code style:
```
    public E remove(int index) {
        E e;
        if (index < SIZE) {
            // fast-path when we are in the first section
            e = elements.array.getAndSet(index, null);
        } else {
            int sectionIndex = index % SIZE;
            e = getElementSection(index).array.getAndSet(sectionIndex, null);
        }
        pushRemovedIndex(index);
        return e;
    }
```

**Comment by akarnokd** [comment]
There isn't any coding style guide, only the requirement of using 4 spaces and LF-only line endings. The code style is matter of taste and we mostly tolerant; we wouldn't complain about any of your examples.

I'd say, on one hand, as long as there aren't any bugs in the code, I certainly won't change the style of the code. On the other hand, if a bug is presumed, I usually format things around to have the style I'm most confortable with to help spot the issue.

**Comment by benjchristensen** [comment]
To backup what @akarnokd said, I have consciously not been strict about styles. I generally dislike most of the artificial and subjective decisions style guides make and wanted to make RxJava as easy to contribute to as possible. 

It is all covered in this line from https://github.com/ReactiveX/RxJava/blob/1.x/CONTRIBUTING.md:

> When submitting code, please make every effort to follow existing conventions and style in order to keep the code as readable as possible.

Beyond that it is left to good judgement and intelligent individuals trying to cooperate together.

A related topic is whether all pull requests must be single-commit or not. This is another where I have chosen to not be strict. If a pull request is a mess of many incremental developer commits I sometimes ask for it to be rebased, but if there are a handful of logical commits with decent commit messages I'm fine with there being more than one. 

Almost all developers self-police on having clean code and clean commits and matching the style of the project. Occasionally we need to provide guidance on improving something, but that's rare compared with how most developers do the right thing without being explicitly told what to do.

All of this aligns with the "freedom and responsibility" culture at Netflix where this project originated: http://www.slideshare.net/reed2001/culture-1798664
