### ISSUE TITLE
`BehaviorSubject.create()` is overloaded and can cause problems.

### ISSUE THREAD

**Issue by runningcode** [ReactiveX/RxJava#2652]
The static method `BehaviorSubject.create()` is overloaded from the static method `Observable.create()` and can cause problems.

Let's say I wanted to seed my `BehaviorSubject` with a null value. At first pass, one would think the code for this would be
```
BehaviorSubject.create(null);
```
Unfortunately, this does not seed a BehaviorSubject with a null value, it actually creates an Observable with a null `OnSubscribe` by calling this method "inherited" from the `Observable` class.
```
Observable<T> create(OnSubscribe<T> f)
```

I'm left with no way of seeding my BehaviorSubject with a null value so my workaround is 
```
BehaviorSubject<Void> subject = BehaviorSubject.create();
subject.onNext(null);
```

**Comment by akarnokd** [comment]
You need to cast the initial value to the target type:
```java
BehaviorSubject<Void> subject = BehaviorSubject.create((Void)null);
System.out.println(subject.hasValue());
```

**Comment by runningcode** [comment]
Thanks, that works.
I would prefer to not have an API that required casting to use properly. Feel free to close this issue.
