### ISSUE TITLE
sharing a switchMap which produces its result via merge, will stop producing after 128 events

### ISSUE THREAD

**Issue by angrycamel** [ReactiveX/RxJava#2654]
The first example uses switchMap and fails with the exception below after 128 events, whereas the second example uses flatMap and does not fail. The third example shows that switchMap does not fail if the nested observable is not a product of of the merge operator. 

However the other variable is the share() on the mainObservable. *Without this, Example 1 works* (I have called this case Example 4). So you might wonder if it has anything to do with switchMap at all - maybe just sharing a merged observable will also fail (Example 5) - however, this case works fine.

So we're left with "sharing a switchMap which produces its result via merge, will stop producing after 128 events". But why?

_(using rxjava 1.0.4, rxscala 0.23.1, scala 2.11.4)_

<pre>
rx.exceptions.MissingBackpressureException: null
	at rx.internal.util.RxRingBuffer.onNext(RxRingBuffer.java:338) ~[rxjava-1.0.4.jar:1.0.4]
	at rx.internal.operators.OperatorMerge$InnerSubscriber.enqueue(OperatorMerge.java:680) [rxjava-1.0.4.jar:1.0.4]
	at rx.internal.operators.OperatorMerge$InnerSubscriber.emit(OperatorMerge.java:657) [rxjava-1.0.4.jar:1.0.4]
	at rx.internal.operators.OperatorMerge$InnerSubscriber.onNext(OperatorMerge.java:545) [rxjava-1.0.4.jar:1.0.4]
	at rx.internal.operators.OperatorMap$1.onNext(OperatorMap.java:55) [rxjava-1.0.4.jar:1.0.4]
</pre>
*Example 1 : This Fails After 128 events*
```scala
def main(args:Array[String]) = {
    val oneItemOnly = (Observable.just("Hello").merge(Observable.never))
    val mainObservable = oneItemOnly.switchMap {
      v => 
        val a = Observable.just(v)
        val b = Observable.interval(20 milliseconds).map(i => s"$v $i")
        a.merge(b)
    }
    .share

    val sub = mainObservable.subscribe( 
      (v) => LOG.info(s"Value: $v"),
      (e) => LOG.info(s"Error",e),
      () => LOG.info(s"Done")
    )
    Observable.never.toBlocking.first
}
```
*Example 2 : This Works Fine*
Note this is precisely the same code as Example 1, except I've changed  switchMap to flatMap
```scala
def main(args:Array[String]) = {
    val oneItemOnly = (Observable.just("Hello").merge(Observable.never))
    val mainObservable = oneItemOnly.flatMap {
      v => 
        val a = Observable.just(v)
        val b = Observable.interval(20 milliseconds).map(i => s"$v $i")
        a.merge(b)
    }
    .share

    val sub = mainObservable.subscribe( 
      (v) => LOG.info(s"Value: $v"),
      (e) => LOG.info(s"Error",e),
      () => LOG.info(s"Done")
    )
    Observable.never.toBlocking.first
}
```
*Example 3 : This also works fine*
Changing example 1 again but this time not using merge within the switchMap.
```scala
def main(args:Array[String]) = {
    val oneItemOnly = (Observable.just("Hello").merge(Observable.never))
    val mainObservable = oneItemOnly.switchMap {
      v => 
        Observable.interval(20 milliseconds).map(i => s"$v $i")
    }
    .share

    val sub = mainObservable.subscribe( 
      (v) => LOG.info(s"Value: $v"),
      (e) => LOG.info(s"Error",e),
      () => LOG.info(s"Done")
    )
    Observable.never.toBlocking.first
}
```
*Example 4 : This also works fine*
Changing example 1 again but this time not share()ing the mainObservable
```scala
def main(args:Array[String]) = {
    val oneItemOnly = (Observable.just("Hello").merge(Observable.never))
    val mainObservable = oneItemOnly.switchMap {
      v => 
        val a = Observable.just(v)
        val b = Observable.interval(20 milliseconds).map(i => s"$v $i")
        a.merge(b)
    }

    val sub = mainObservable.subscribe( 
      (v) => LOG.info(s"Value: $v"),
      (e) => LOG.info(s"Error",e),
      () => LOG.info(s"Done")
    )
    Observable.never.toBlocking.first
}
```
*Example 5 : This also works fine*
Experiment to find out if the problem is simply sharing a merged observable.... seems not
```scala
def main(args:Array[String]) = {
    val mainObservable = Observable.just(1).merge(Observable.interval(20 milliseconds))
        .share
    val sub = mainObservable.subscribe( 
      (v) => LOG.info(s"Value: $v"),
      (e) => LOG.info(s"Error",e),
      () => LOG.info(s"Done")
    )
    Observable.never.toBlocking.first
}
```

**Comment by akarnokd** [comment]
Could you check these with RxJava 1.0.6? We've fixed a bunch of share- and merge-related bugs since 1.0.4.

**Comment by angrycamel** [comment]
Done, no change

<pre>
18:22:07.723 [RxComputationThreadPool-2] INFO  MinimalRepro - Value: Hello 125
18:22:07.744 [RxComputationThreadPool-2] INFO  MinimalRepro - Value: Hello 126
18:22:10.343 [RxComputationThreadPool-2] INFO  MinimalRepro - Error
rx.exceptions.MissingBackpressureException: null
	at rx.internal.util.RxRingBuffer.onNext(RxRingBuffer.java:349) ~[rxjava-1.0.6.jar:1.0.6]
	at rx.internal.operators.OperatorMerge$InnerSubscriber.enqueue(OperatorMerge.java:721) [rxjava-1.0.6.jar:1.0.6]
	at rx.internal.operators.OperatorMerge$InnerSubscriber.emit(OperatorMerge.java:698) [rxjava-1.0.6.jar:1.0.6]
	at rx.internal.operators.OperatorMerge$InnerSubscriber.onNext(OperatorMerge.java:586) [rxjava-1.0.6.jar:1.0.6]
	at rx.internal.operators.OperatorMap$1.onNext(OperatorMap.java:55) [rxjava-1.0.6.jar:1.0.6]
</pre>
_(rxjava 1.0.6, rxscala 0.23.1, scala 2.11.4)_

**Comment by akarnokd** [comment]
It's a bug in switch. Could you check if #2655 works for you?

**Comment by angrycamel** [comment]
Yes - it works for me. Nice work!
