### ISSUE TITLE
just(T) : RxJavaObservableExecutionHook not called

### ISSUE THREAD

**Issue by ronanM** [ReactiveX/RxJava#2656]
When using rx.Observable.just(T) the RxJavaObservableExecutionHook is not call.

This is not like other just(T,...) that call rx.Observable.from(Iterable<? extends T>).

**Comment by benjchristensen** [comment]
Thanks for the report.

**Comment by benjchristensen** [comment]
@abersnaze Since this probably affects work you're doing as well, can you take a look at what we need to fix here? It will be anything using the internal ScalarSynchronousObservable optimization I think.

**Comment by abersnaze** [comment]
sure.

**Comment by akarnokd** [comment]
What is the status of this issue? I've lost track of the proposed changes to `ScalarSynchronousObservable`.

**Comment by akarnokd** [comment]
See #3958.

**Comment by zsxwing** [comment]
Closing via #3958
