### ISSUE TITLE
Adding a no-op action

### ISSUE THREAD

**Issue by mttkay** [ReactiveX/RxJava#276]
I'm honestly not convinced this is even the Rx way of doing things, but I ended up adding a pre-defined no-op action to our codebase that I found myself using quite a bit. It's basically the counterpart to Observable.empty() and allows you to register an "empty" `Observer` by supplying a no-op onNext Action.

I guess the problem is that once you adopt Rx throughout the codebase, you will want to use it to schedule work that you may not actually want to observe, i.e. "fire and forget". As far as I know there is no way to subscribe a no-op to an Observable yet, so similarly to the `Functions` class, would it be useful to have an `Actions` class with predefined reusable action objects such as `Actions.empty()`?

Sample use

```
serviceObject.createThing().subscribe(Actions.empty())
```

Depending on what Thing is, I might not actually be interested in the result, so an empty callback is what I want.

**Comment by schwiz** [comment]
Still would be useful in terms of an action. For example
Observable.using(myResource, myFactory, Action.empty());
