### ISSUE TITLE
add new operator onBackpressureDrop(Action1 onDrop)

### ISSUE THREAD

**Issue by stevenzwu** [ReactiveX/RxJava#2764]
When Observable drops msg on backpressure, it should call the onDrop method. This can be useful for incrementing some counter or just simply log something.

**Comment by stevenzwu** [comment]
@akarnokd I updated the PR with recommended enhancement. can we merge it and close this issue?

**Comment by benjchristensen** [comment]
This was merged in https://github.com/ReactiveX/RxJava/pull/2776
