### ISSUE TITLE
ConnectableObservable.connect() returns a null subscription if already connected

### ISSUE THREAD

**Issue by lopespm** [ReactiveX/RxJava#2774]
Any posterior `connect()` calls to an already connected `ConnectableObservable` return `null`, but I believe the expected behaviour would be for it to return the subscription created for the first connection

**Comment by davidmoten** [comment]
I suspect that this is a documentation issue on the method because the source code seems to be quite deliberate in its treatment of this case (can code be deliberate?). No doubt an API expert will comment soon.

**Comment by akarnokd** [comment]
I think it should return a subscription every time, but all places where ```connect(Action1)``` is implemented, the action is only called on the first subscription: see ```OperatorMulticast``` and ```OperatorPublish```.

**Comment by davidmoten** [comment]
I can have a look at making this happen if someone isn't working on it already.

**Comment by akarnokd** [comment]
@davidmoten I'm working on something else so you can go ahead.

**Comment by benjchristensen** [comment]
Was merged in https://github.com/ReactiveX/RxJava/pull/2779

**Comment by davidmoten** [comment]
```OperatorPublish``` has not been done yet, I'll open up a new issue.
