### ISSUE TITLE
Observable.interval vs Observable.timer

### ISSUE THREAD

**Issue by baoti** [ReactiveX/RxJava#2778]
In the document http://reactivex.io/documentation/operators/interval.html#collapseRxJava:

![interval](http://reactivex.io/documentation/operators/images/interval.c.png)

 and http://reactivex.io/documentation/operators/timer.html#collapseRxJava:

![timer](http://reactivex.io/documentation/operators/images/timer.p.png)

Does it mean `interval(long,TimeUnit,Scheduler)` is equivalent to `timer(0,long,TimeUnit,Scheduler)`?

But in the code:

    public final static Observable<Long> interval(long interval, TimeUnit unit, Scheduler scheduler) {
        return create(new OnSubscribeTimerPeriodically(interval, interval, unit, scheduler));
    }

    public final static Observable<Long> timer(long initialDelay, long period, TimeUnit unit, Scheduler scheduler) {
        return create(new OnSubscribeTimerPeriodically(initialDelay, period, unit, scheduler));
    }

What's wrong, document or code?

**Comment by zsxwing** [comment]
The docs is wrong. `interval(interval, unit)` should be equivalent to `timer(interval, interval, unit)`.

**Comment by DavidMGross** [comment]
Documentation fixed.

**Comment by baoti** [comment]
:+1:

**Comment by Lars6** [comment]
This should be fixed in the javadoc as well:
http://reactivex.io/RxJava/javadoc/rx/Observable.html#interval%28long,%20java.util.concurrent.TimeUnit%29

**Comment by DavidMGross** [comment]
Good catch. I forgot to copy those files over. I fixed it this morning in 9999d358.
