### ISSUE TITLE
2.0 Design: ReactiveX Design Guidelines and Contract

### ISSUE THREAD

**Issue by benjchristensen** [ReactiveX/RxJava#2781]
The [Rx Design Guidelines](http://go.microsoft.com/fwlink/?LinkID=205219) posted by Microsoft is out of date and does not correctly represent RxJava. We need to update or rewrite it to match the evolution over the past couple years, such as the addition of backpressure. 

Related: https://github.com/ReactiveX/RxJava/issues/981 and https://github.com/ReactiveX/reactivex.github.io/issues/14

cc @headinthebox @mattpodwysocki @jhusain as we would preferably do this across RxJS, Rx.Net, etc. However, if we can't reach consensus, RxJava will stick closer to [Reactive Streams](https://github.com/reactive-streams/reactive-streams-jvm/blob/master/README.md#specification) and [j.u.c.Flow](http://gee.cs.oswego.edu/dl/jsr166/dist/docs/java/util/concurrent/Flow.html) which is targeting Java 9 and [based on Reactive Streams](http://cs.oswego.edu/pipermail/concurrency-interest/2015-January/013641.html). This is because interop within the JVM ecosystem is more important than between languages. This is similar to how ES7 is evolving an "Observable" that has the necessary semantics but differs significantly from .Net and Java.

**Comment by benjchristensen** [comment]
This is required to achieve https://github.com/ReactiveX/RxJava/issues/2450

**Comment by akarnokd** [comment]
There is a design document here: https://github.com/ReactiveX/RxJava/blob/2.x/DESIGN.md with mostly up-to-date descriptions.
