### ISSUE TITLE
Combining merge and mergeMaxConcurrent

### ISSUE THREAD

**Issue by akarnokd** [ReactiveX/RxJava#2789]
I'm writing a combined merge for 2.0 and have some questions:

  - In the 1.0 ```merge```, the scalar queue is bounded and may throw ```MissingBackpressureException``` if more than ```RxRingBuffer.SIZE``` scalars are merged without downstream requests. Do we want to keep this behavior switch to an unbounded queue?
  - In the current ```mergeMaxConcurrent```, upstream's backpressure-support is loosely handled: ```mergeMaxConcurrent``` requests ```maxConcurrent``` but queues ```Observable```s that arrive after the limit. Do we wan't to keep this behavior or throw ```MissingBackpressureException```?

**Comment by benjchristensen** [comment]
> switch to an unbounded queue

Why would we want an unbounded queue? That would break backpressure and allow buffer bloat.

> queues Observables that arrive after the limit

That sounds like a problem in our current implementation. It should use `request(n)` backpressure semantics to request only enough to fill the `maxConcurrent`. We should definitely not queue `Observable`s in an unbounded buffer.

**Comment by akarnokd** [comment]
> Why would we want an unbounded queue? That would break backpressure and allow buffer bloat.

Current 1.x merge requests ```Long.MAX_VALUE``` from upstream. If all of those are ```ScalarSynchronousObservable```s, the merge will throw a ```MissingBackpressureException```. So are we essentially saying: you can merge any number of non-scalar Observables but you can only merge RxRingBuffer.SIZE scalar observables at the same time?
