### ISSUE TITLE
2.0 Design: OnErrorNotImplementedException

### ISSUE THREAD

**Issue by akarnokd** [ReactiveX/RxJava#2790]
The Reactive-Streams specification prohibits throwing anything but ```NullPointerException``` from ```onError```, but many 1.0 tests expects ```OnErrorNotImplementedException```.

We should decide how to handle this case, for example, forwarding the incoming exception to the plugin error handler and/or the current thread's uncaught exception handler.

**Comment by benjchristensen** [comment]
> OnErrorNotImplementedException

Rx also prohibits throwing errors. `OnErrorNotImplementedException` is the Rx equivalent saying that the contract is broken.

**Comment by benjchristensen** [comment]
> Rx Design Guideline 6.5. Subscribe implementations should not throw

**Comment by akarnokd** [comment]
So do we still want to propagate fatal exceptions upward to the highest onSubscribe/lift call site while it travels through RxJava's call chain? In that case, when taking someone else's Publisher, we need extra safeguards to enforce RS contract: we can't let OnErrorNotImplemented escape, (and most probably we need to serialize access to the Subscription of such external Publisher because RS doesn't require thread-safety there, but implementing RxJava's Subscriptions as thread-safe proven to be quite convenient so far).

**Comment by akarnokd** [comment]
OnErrorNotImplementedException has been removed and undeliverable exceptions are now forwarded to `RxJavaPlugins.onError`.
