### ISSUE TITLE
GroupBy throws exception when calling onNext from multiple threads.

### ISSUE THREAD

**Issue by elrodro83** [ReactiveX/RxJava#2791]
I'm getting the exception thrown in line 308 of OperatorGroupBy when calling onNext from multiple threads. The comment line 307 suggest i shouldn't be doing that, but the usage of concurrent classes and the overall design of the class (and other rx operators i've used without problem) suggest that shouldn't be a problem and be treated as a bug.

From the code, when running for the first time (discovering the groups) the condition of line 217 can be true for more than one thread, and that would trigger 2 creations of the same group and the exception I'm getting.

**Comment by zsxwing** [comment]
> I'm getting the exception thrown in line 308 of OperatorGroupBy when calling onNext from multiple threads.

Do you mean your Observable will call `onNext` in multiple threads? If so, you should call `Observable.serialize()` to make the Observable obey the Rx contract. See: http://reactivex.io/documentation/operators/serialize.html

**Comment by elrodro83** [comment]
Ok, sounds fair.

Do you happen to know why does OperatorGroupBy use a ConcurrentHashMap internally instead of a regular HashMap to keep the groups? If access is serialized that shouldn't be needed...

**Comment by zsxwing** [comment]
`unsubscribe` can be accessed in any thread. That's why it needs a `ConcurrentHashMap` to put and remove groups.

**Comment by elrodro83** [comment]
Got it. Thanks!
