### ISSUE TITLE
2.0 Design: Pluggable Type Annotations

### ISSUE THREAD

**Issue by abersnaze** [ReactiveX/RxJava#2795]
I think it would wonderfull if 2.0 could add additional compile type validation of the Rx code with pluggable types.  The problems at runtime that I think could potentially be caught at compile time:

* not subscribing to an observable.
* subscribing more than once.
* validating back pressure support.
* validating sub types.  like a no argument instance method `merge()` is only called on an observable of observables.

There are a many predefined annotations and lots of documentation or writing custom checkers
http://types.cs.washington.edu/checker-framework/current/checker-framework-manual.html#writing-a-checker

**Comment by akarnokd** [comment]
This is a very old issue. We have `@BackpressureSupport` annotation on all `Flowable` operators. I believe such checkes should live outside the RxJava project.
