### ISSUE TITLE
AbstractOnSubscribe fast path?

### ISSUE THREAD

**Issue by davidmoten** [ReactiveX/RxJava#2796]
I'm a huge fan of ```AbstractOnSubscribe``` because has made implementing backpressure so much easier.  In the case that I have a fast path I'd like to specify it to ```AbstractOnSubscribe``` so that one ```OnSubscribe``` handles both cases. Any thoughts? (@akarnokd)

**Comment by benjchristensen** [comment]
What do you mean by fast path?

**Comment by davidmoten** [comment]
By fast path I mean non-backpressure supporting code that is run when  ```Long.MAX_VALUE``` is requested.  For my custom operator it's significantly faster than the backpressure supporting ```AbstractOnSubscribe```.

**Comment by akarnokd** [comment]
At first glance, the drawback for it is that you need to specify two separate logic for emitting values: one would be based on phases the other on free-form onXXX calls.

**Comment by davidmoten** [comment]
Yeah it's a drawback but in my cases the challenge in writing the ```OnSubscribe```s has been mostly  handled by ```AbstractOnSubscribe```. The non-backpressure OnSubscribe is a cinch so not a lot of overhead for big performance gains.  Perhaps a decent performance improvement would be achieved with @benjchristensen 's batching suggestion in #2801.

**Comment by akarnokd** [comment]
I'll work this out tomorrow along with #2801 since they are somewhat related.

**Comment by akarnokd** [comment]
See #3118.
