### ISSUE TITLE
add backpressure support to operator: buffer(long timespan, TimeUnit unit, int count)

### ISSUE THREAD

**Issue by stevenzwu** [ReactiveX/RxJava#2797]
Ben mentioned that this operator should be upgraded to support backpressure

**Comment by akarnokd** [comment]
Operators with time parameters are unlikely to work with backpressure beause if the downstream doesn't request the next value, the clock is till ticking and values may get lost unexpectedly.

(I'm too much into RxJava 2.0 now and maybe there is a way to work this out.)

**Comment by benjchristensen** [comment]
This one could possibly be made to work since it has size, but if the timer ticks and there is no requested demand it would then have to emit an error. That probably isn't appropriate for this existing operator because emitting an error is not expected.

Is there a way we could have an overload with count/time and a strategy of what to do if time ticks but no requested demand exists? For example ... drop or emit an error? What could the signature be to make that happen?

**Comment by akarnokd** [comment]
Allow me to think out loud:

##### Requesting 1 at a time

The operator requests ```count``` elements and starts the timer. If the count is reached, the timer is cancelled and the buffer is emitted to downstream. If the timer fires first, the buffer is emitted, but any excess upstream value needs to be buffered. Such excess values will be the first in a buffer for new request, and only ```count - len``` is requested from upstream.

The coordination of emitting at count vs. emitting at timer will be challenging.

##### Requesting N 

The operator requests ```count * N``` values and start the timer. If ```count``` elements are received, the timer is cancelled and the buffer is emitted. If the downstream request > 0 after, a new timer is started and the upstream can continue producing. If the timer fires, it takes the available buffer contents and emits it to downstream. If the downstream request > 0 after this emission from the timer thread, a new timer is started. If the downstream requests N and no further requests are made, the final segment will have the same things to consider as in the request-1 case above.

##### Buffer with timespan, timeshift and size

I don't even try to imagine this scenario yet.

-----

I'll try to prototype such an operator.

**Comment by akarnokd** [comment]
I have reimplemented the operator in #2806. Could you check if it works for you?

**Comment by akarnokd** [comment]
We have discussed that making timed operations backpressure aware requires starting and stopping the timed part, it adds the latency of the requesting operation and skews the timing of the buffers in respect to a wall-clock.
