### ISSUE TITLE
Move AbstractOnSubscribe into Observable

### ISSUE THREAD

**Issue by benjchristensen** [ReactiveX/RxJava#2800]
I like what `AbstractOnSubscribe` gives us, but I'm not a fan of the class or location in the API. I would like to explore moving the functionality into factory methods of `Observable`. For example, can `Observable.generate` with various overloads give us this ability? Or `Observable.create` overload so it is discoverable?

**Comment by akarnokd** [comment]
`AbstractOnSubscribe` is going to be deprecated and eventually removed in favor for #3118.
