### ISSUE TITLE
AbstractOnSubscribe Batching

### ISSUE THREAD

**Issue by benjchristensen** [ReactiveX/RxJava#2801]
How does one performed batched requests when `AbstractOnSubscribe` invokes `onNext` every time?

We should be able to generate a backpressure aware `Observable` that handles function invocation but doesn't prohibit batch performance.

**Comment by davidmoten** [comment]
Yep, that would be nice.

**Comment by akarnokd** [comment]
I'll think about it.

**Comment by akarnokd** [comment]
See #3118 which is likely to replace `AbstractOnSubscribe`.
