### ISSUE TITLE
Installing rxjava locally uses version 0.20.1-SNAPSHOT

### ISSUE THREAD

**Issue by davidmoten** [ReactiveX/RxJava#2802]
Running
```./gradlew install```
 on latest creates the rxjava artifact locally with version 0.20.1-SNAPSHOT. I was expecting 1.0.8-SNAPSHOT.

Can this be fixed please?

**Comment by zsxwing** [comment]
Please use `./gradlew publishToMavenLocal` instead.

**Comment by davidmoten** [comment]
That has the same effect:

```
$ ./gradlew publishToMavenLocal
Inferred version: 0.20.1-SNAPSHOT
...

**Comment by zsxwing** [comment]
Could you check the git tags using `git tag -l`? Is `v1.0.7` in the list?

**Comment by davidmoten** [comment]
Ah gotcha, that's how it works. Thanks @zsxwing. So I just did
```
git fetch upstream --tags
```
and the build worked (producing 1.0.8-SNAPSHOT)

**Comment by zsxwing** [comment]
Ah, both `install` and `publishToMavenLocal` work. Your issue is just because tags were absent.

**Comment by davidmoten** [comment]
Yep, thanks. Closing.
