### ISSUE TITLE
Documentation issue: 404 for groovy examples

### ISSUE THREAD

**Issue by javazquez** [ReactiveX/RxJava#2808]
On the [*How to use rxJava page*](https://github.com/ReactiveX/RxJava/wiki/How-To-Use-RxJava), the link to [rxGroovy Examples](https://github.com/ReactiveX/RxGroovy/tree/0.x/src/examples/groovy/rx/lang/groovy/examples) appears to be invalid.

**Comment by javazquez** [comment]
appears that a change in the rxGroovy Examples url  of 0.x to 1.x resolves the problem

**Comment by abersnaze** [comment]
thanks for the report. I've changed the link on the page.
