### ISSUE TITLE
Observable.compose() generics fail pre-JDK 8

### ISSUE THREAD

**Issue by dlew** [ReactiveX/RxJava#2815]
The following code works just fine on JDK 8, but fails to compile on 7 or below:

```java
import rx.Observable;

public class Fetcher {
  
    public Observable<String> fetch() {
        return Observable.just("1").compose(composer());
    }

    private <T> Observable.Transformer<T, T> composer() {
        return new Observable.Transformer<T, T>() {
            @Override
            public Observable<T> call(Observable<T> o) {
                return o;
            }
        };
    }
}
```

Pre-8 you get this error message:

```
Fetcher.java:6: error: incompatible types
      return Observable.just("1").compose(composer());
                                         ^
  required: Observable<String>
  found:    Observable<Object>
1 error
```

I see there were other discussions about `compose()` and generics but I couldn't find anything related to JDK version from before.

**Comment by akarnokd** [comment]
This is the limit of Java 7's type inference, not related to RxJava, but a common shortcoming. The inference can't propagate the compose's parameter type to the return type of composer. You need to specify the type on composer directly, or pull out the results of composer into a local variable.

```java
Observable.just("1").compose(this.<String>composer());

Transformer<String, String> comp = composer();
Observable.just("1").compose(comp);
```

**Comment by dlew** [comment]
Ah, okay, thanks for the explanation!

**Comment by zsiegel** [comment]
Running into the same problem. Would love to know why this happens.

**Comment by iNoles** [comment]
According to http://docs.oracle.com/javase/tutorial/java/generics/genTypeInference.html, Java 8 fixed this issue.
