### ISSUE TITLE
Combining create & defer?

### ISSUE THREAD

**Issue by daschl** [ReactiveX/RxJava#2819]
Hi folks,

is it possible to combine create & defer?

We have the following use case which is related to releasing netty byte buffers. We have a hot observable and need to do two things to avoid accidental leaking:

- Make it cold
- If someone unsubscribed before the data could be loaded release the buffers.

The current version would be something like:

```java
        return Buffers.wrapColdWithAutoRelease(Observable.defer(new Func0<Observable<R>>() {
            @Override
            public Observable<R> call() {
                return sendHot(request);
            }
        }));
```

which would make it cold and the auto release then is:

```java
    public static <T> Observable<T> wrapColdWithAutoRelease(final Observable<T> source) {
        return Observable.create(new Observable.OnSubscribe<T>() {
            @Override
            public void call(final Subscriber<? super T> subscriber) {
                source.subscribe(new Subscriber<T>() {
                    @Override
                    public void onCompleted() {
                        if (!subscriber.isUnsubscribed()) {
                            subscriber.onCompleted();
                        }
                    }

                    @Override
                    public void onError(Throwable e) {
                        if(!subscriber.isUnsubscribed()) {
                            subscriber.onError(e);
                        }
                    }

                    @Override
                    public void onNext(T t) {
                        if (!subscriber.isUnsubscribed()) {
                            subscriber.onNext(t);
                        } else {
                            ReferenceCountUtil.release(t);
                        }
                    }
                });
            }
        });
    }
```

It works, but it also creates more observables/garbage than needed. Any idea how we could combine the defer into the create so we only need to create 1 wrapper?

Maybe @akarnokd or @benjchristensen have an idea? ;)

**Comment by akarnokd** [comment]
You could lift in the resource tracking Subscriber instead of creating an entire observable.

**Comment by daschl** [comment]
@akarnokd so you mean like so?

```java
    public static <T> Observable<T> wrapColdWithAutoRelease(final Observable<T> source) {
        return source.lift(new Observable.Operator<T, T>() {
            @Override
            public Subscriber<? super T> call(final Subscriber<? super T> o) {
                return new Subscriber<T>() {
                    @Override
                    public void onCompleted() {
                        o.onCompleted();
                    }

                    @Override
                    public void onError(Throwable e) {
                        o.onError(e);
                    }

                    @Override
                    public void onNext(T t) {
                        if (!o.isUnsubscribed()) {
                            o.onNext(t);
                        } else {
                            ReferenceCountUtil.release(t);
                        }
                    }
                };
            }
        });
    }
```

**Comment by akarnokd** [comment]
There is no need to check for unsubscription in those methods. However, your Subscriber is disconnected from downstream and won't really participate in backpressure or unsubscription: you may not deliver values to it but you'll still receive them from upstream until a terminal event comes along.
Note also that if you have any asynchronous delivery downstream (such as observeOn), there is a time gap between ```isUnsubscribed``` and ```o.onNext``` which could still leak your values.

**Comment by daschl** [comment]
>> There is no need to check for unsubscription in those methods. However, your Subscriber is 
>> disconnected from downstream and won't really participate in backpressure or unsubscription: you 
>> may not deliver values to it but you'll still receive them from upstream until a terminal event comes along.

Actually I think that's what I want, because the upstream one is cold so it has been requested once (in fact they are all AsyncSubjects), so even if someone unsubsribes downstream I want to consume the rest and release it.

Your second point could hold true since in general this is not the case but it _could_ be in the future. What is the proper way to handle this without loosing too much performance?

**Comment by akarnokd** [comment]
The most reliable way is to use a serialization principle such as queue-drain or emitter loops; but these come at a (latency) cost. It is hard to give more concrete tips as I'd need more details on the problem, perhaps in a form of a simple runnable example or test case.

**Comment by daschl** [comment]
Hmm thanks so far, I think I'll leave it as is with that. The chance that someone is doing that is very small, and I don't want everyone to pay the cost. If someone runs into that he needs to make sure he stays on our computation pool (where the stuff is emitted originally).

Thanks much!
