### ISSUE TITLE
Zip and CombineLatest result class

### ISSUE THREAD

**Issue by artem-zinnatullin** [ReactiveX/RxJava#2822]
`Zip` and `CombineLatest` are pretty popular operators, but there is problem with representing result combination of multiple items of different types.

Example below is similar to one of @benjchristensen slides about RxJava:

```java
class UserWithFavoriteMovies {
  final User user;
  final List<Movie> favoriteMovies;

 UserWithFavoriteMovies(User user, List<Movie> favoriteMovies) {
    this.user = user;
    this.favoriteMovies = Collections.unmodifiableList(favoriteMovies);
  }
}

Observable.zip(getUserInfo(userId), getFavoriteMovies(userId), new Func2<UserInfo, List<Movie>,        UserWithFavoriteMovies>() {
  @Override public UserWithFavoriteMovies call(User user, List<Movie> favoriteMovies) {
    return new UserWithFavoriteMovies(user, favoriteMovies);
  }
});

// same with lambda
Observable.zip(getUserInfo(userId), getFavoriteMovies(userId), (user, favoriteMovies) -> return new UserWithFavoriteMovies(user, favoriteMovies));
```

As you can see, we have to add class `UserWithFavoriteMovies` just to Zip two objects of different types together.

What if we will add classes, similar to `Func2`, `Func3`, `Func4`... which will store final references to objects of Generic types, also will be great if `Combination` class will implement `equals()`, `hashCode()`, `toString()`

Something like this:

```java
class Combination2<T1, T2> {
  public final T1 item1;
  public final T2 item2;

  Combination2(T1 item1, T2 item2) {
    this.item1 = item1;
    this.item2 = item2;
  }

  // equals(), hashCode(), toString()
}
```

And similar classes `Combination3`, `Combination4`, etc.

It will reduce boilerplate classes from many applications, I hope.

```java
Observable.zip(getUserInfo(userId), getFavoriteMovies(userId), new Func2<User, List<Movie>, Combination2<User, List<Movie>>() {
    @Override public Combination2<User, List<Movie>> call(User user, List<Movie> favoriteMovies) {
      return new Combination2(user, Collections.unmodifiableList(favoriteMovies)));
    }
});

// same with lambda
Observable.zip(getUserInfo(userId), getFavoriteMovies(userId), (user, favoriteMovies) -> return new Combination2(user, Collections.unmodifiableList(favoriteMovies)));
```

So, what do you think about classes `Combination2`, `Combination3`, `Combination4`..?

Issue can be marked as `question`.

**Comment by akarnokd** [comment]
You are talking about tuples and pairs that don't have a standard representation in Java. Many libraries define their own so RxJava doesn't do this on its own. Since RxJava itself doesn't need tuples, it is left to the developer to implement/use what he/she finds the best for his/her needs.

**Comment by artem-zinnatullin** [comment]
Yep, it's tuples, I just thought that it might be useful "feature" of `RxJava` and one of the standard way for Java developers who use `RxJava`.

Thanks for quick reply!

Just found http://www.javatuples.org library
