### ISSUE TITLE
Is there a way to provide a hook after the onNext() of a subscriber is complete.

### ISSUE THREAD

**Issue by ashish-tyagi** [ReactiveX/RxJava#2824]
For example, in the example below:

``` java
public class Main {
    public static void main(String[] args) {
        Observable.just(10).flatMap(new Func1<Integer, Observable<? extends Integer>>() {
            @Override
            public Observable<? extends Integer> call(Integer t1) {
                return Observable.just(t1 * t1);
            }
        }).subscribe(new Action1<Integer>() {
            @Override
            public void call(Integer t1) {
                System.out.println(t1);
            }
        });
    }
}
```

I want to get a notification that the item '100' has been consumed and I want to receive the item '10' also as arguments i.e some method like below:

``` java
void afterOnNext(int i){
// Do cleanup here. For example free memory etc.
} 
```

I want to do it for every item produced by the source observable. Thanks for your help.

**Comment by davidmoten** [comment]
Yes you can but your notification will only work for as far as the item is synchronously processed. One way is to use a custom Operator:

```java
import rx.Observable.Operator;
import rx.Subscriber;
import rx.functions.Action1;

public class OperatorDoAfterOnNext<T> implements Operator<T,T> {

    private final Action1<T> action;

    public OperatorDoAfterOnNext(Action1<T> action) {
        this.action = action;
    }
    
    @Override
    public Subscriber<? super T> call(final Subscriber<? super T> child) {
        return new Subscriber<T>(child) {

            @Override
            public void onCompleted() {
                child.onCompleted();
            }

            @Override
            public void onError(Throwable e) {
                child.onError(e);
            }

            @Override
            public void onNext(T t) {
                child.onNext(t);
                action.call(t);
            }
            
        };
    }
   
}
```

You can use it like this:

```java
Observable.just(1,2,3)
    .lift(new OperatorDoAfterOnNext(x -> doSomething(x)))
    .flatMap(etc)
    .subscribe();
```

You might also find ```Observable.using```  useful.

**Comment by ashish-tyagi** [comment]
Thanks, it helped.

**Comment by Doctoror** [comment]
> One way is to use a custom Operator

This way the action will not be called after subscriber onNext() if observeOn() is set after lift.

**Comment by mzorilla** [comment]
Hello @davidmoten! I can't find an equivalent version of that code using RxJava2... what's the best solution for that?

**Comment by akarnokd** [comment]
http://reactivex.io/RxJava/2.x/javadoc/io/reactivex/Observable.html#doAfterNext-io.reactivex.functions.Consumer-

**Comment by mzorilla** [comment]
Thanks @akarnokd! But, if for example, I do an animation (ViewPropertyAnimator) on Android I don't have a Subscriber to wait for the animation to finish and then move to the next one.

**Comment by artem-zinnatullin** [comment]
Animations are async, you can emit a signal on animation completion and react to that instead of dealing with hooks
