### ISSUE TITLE
Javadoc + Marble diagram of replay(Func1<Observable<T>, Observable<R>>, ...) family

### ISSUE THREAD

**Issue by ronanM** [ReactiveX/RxJava#2843]
The javadoc and the marble diagram for the family of operators ```rx.Observable.replay(Func1<? super Observable<T>, ? extends Observable<R>>)``` seems to be outdated. 

The description show a ```Func1<? super T, ? extends R>``` but it's in reality a ```Func1<? super Observable<T>, ? extends Observable<R>>```.

**Comment by DavidMGross** [comment]
How does this look to you? (you may have to clear your browser cache): http://reactivex.io/RxJava/javadoc/rx/Observable.html#replay(rx.functions.Func1)

**Comment by ronanM** [comment]
Great ! Thank you.
