### ISSUE TITLE
ConcatMap combined with Delay causes a hang

### ISSUE THREAD

**Issue by DaGenix** [ReactiveX/RxJava#2844]
The following code:

```java
public class Test {
	public static void main(final String[] arg) throws Exception {
		Observable.just(1)
				.repeat()
				.concatMap(x -> {
					System.out.println(x);
					return Observable.empty()
							.delay(1, TimeUnit.SECONDS);
				})
				.subscribe();
		
		Thread.sleep(Long.MAX_VALUE);
	}
}
```

Prints out two "1"s quickly, and then another "1" every second afterward.

If you change that code just slightly two use the two argument form of `just()` as in:

```java
public class Test {
	public static void main(final String[] arg) throws Exception {
		Observable.just(1, 2)
				.repeat()
				.concatMap(x -> {
					System.out.println(x);
					return Observable.empty()
							.delay(1, TimeUnit.SECONDS);
				})
				.subscribe();
		
		Thread.sleep(Long.MAX_VALUE);
	}
}
```

Then, it prints "1", then "2", and then hangs and doesn't do anything afterward.

I have no idea whats going on, but, I don't think that the 2nd piece of code should hang if the first one doesn't.

I tested with 1.0.8 and didn't find any similar looking issue with a quick look.

**Comment by akarnokd** [comment]
Thanks. This is a bug with ```repeat()``` and the fix is in #2845.
