### ISSUE TITLE
Backpressure and onComplete from an empty observable

### ISSUE THREAD

**Issue by davidmoten** [ReactiveX/RxJava#2884]
What is the *preferred* behaviour for an observable that supports backpressure but emits nothing when it has been subscribed to with an initial request of 0? Should it report completion as soon as it knows it is empty or wait for a positive request? 
 
I notice that reactive-streams-jvm 2.9 says

>A Subscriber MUST be prepared to receive an onComplete signal with or without a preceding Subscription.request(long n) call.

This allows us to go either way when developing an ```Operator``` for instance but perhaps RxJava wants to proffer a preferred or mandated direction for it's internal operators? @benjchristensen 

FYI @viktorklang

**Comment by akarnokd** [comment]
```from``` and ```range``` already emit ```onCompleted``` if they are essentially empty or just after the last item so I think that should stay as the behavior.

**Comment by davidmoten** [comment]
I don't thinks that's the case for ```from```. Its ```Producer``` does nothing at all if request is 0.

**Comment by davidmoten** [comment]
Same for ```range```.

**Comment by akarnokd** [comment]
@davidmoten you're right, I just checked the code.

**Comment by viktorklang** [comment]
Hi @davidmoten,

since `request` is for `elements` and `complete` and `error` are not elements,
it is intended for these signals to be propagated as soon as they are known.

Let me know if you have any follow-on questions!

**Comment by davidmoten** [comment]
Thanks @viktorklang. Do you think that intention should be a SHOULD addition to the Publisher rules in reactive-streams-jvm?

**Comment by viktorklang** [comment]
Given that 2.9 already provisions for this I think a good compromise (I am not a fan of SHOULDs in general) to include this explanation as a part of https://github.com/reactive-streams/reactive-streams-jvm/issues/177

Would that cover it?

**Comment by davidmoten** [comment]
Sounds fine, thanks.

**Comment by viktorklang** [comment]
@davidmoten Great. I'd like to take the opportunity to encourage you to assist with that Issue, if you have any cycles to spare. :)

**Comment by davidmoten** [comment]
@akarnokd as you suspected originally `range` does emit `onCompleted` eagerly from an empty range. `from` does not emit `onCompleted` eagerly from an empty iterable so I submitted #2899.

**Comment by akarnokd** [comment]
Seems to be fixed. Closing.
