### ISSUE TITLE
Parallel requests

### ISSUE THREAD

**Issue by lawloretienne** [ReactiveX/RxJava#2888]
How would you kick off two parallel http requests and receive the result in one event so that the UI can be updated all at once, instead of having sequential execution of http requests?

Is this possible in RxJava?  What method or methods are required to pull this off?

**Comment by JakeWharton** [comment]
[`combineLatest()`][1] or [`merge()`][2]

 [1]: http://reactivex.io/documentation/operators/combinelatest.html
 [2]: http://reactivex.io/documentation/operators/merge.html

**Comment by artem-zinnatullin** [comment]
Take a look at Combining Operators http://reactivex.io/documentation/operators.html

Example with `Zip Operator` (pseudo code):

```java
Observable
  .zip(firstHttpRequestObservable, secondHttpRequestObservable, 
      (firstResponse, secondResponse) -> { return combinationOfResponses; })
  .subscribeOn(Schedulers.io())
  .observeOn(uiScheduler) // for example AndroidSchedulers.mainThead() from RxAndroid
  .subscribe(combinationOfResponses -> {
    // do what you want with result
  });
```

See also: `CombineLatest Operator` and `Merge Operator`

**Comment by lawloretienne** [comment]
What if the two requests return different Objects?  It looks like merge is equipped to only handle Objects of the same type.

**Comment by artem-zinnatullin** [comment]
@lawloretienne `Zip` and `CombineLatest` accept Function that can combine results into one object.

**Comment by lawloretienne** [comment]
Thanks @JakeWharton and @artem-zinnatullin `combineLatest` worked for me.
