### ISSUE TITLE
Proposal: plugin to statically check for OnErrorNotImplementedException

### ISSUE THREAD

**Issue by festevezga** [ReactiveX/RxJava#2893]
Something that may be useful in the future is a plugin that checks every for subscription and .toBlocking() up the chain to see if there is potential for a user-defined error.

Example:

    public Observable<Integer> toInt(final String s){
        return Observable.create((Subscriptor sub) -> {
            try {
                sub.onNext(Integer.parseInt(s));
                sub.onCompleted();
            } catch (NumberFormatExcetption e) {
                sub.onError(e);
            }
     });

    public void main(){
        toInt("5").subscribe((Integer number) -> Systemout.println(number); )
    }

In this example the toInt() line would get a warning not because the result is analyzed but because it can be checked that the producer can launch an exception and the subscriber may not recover from it.

**Comment by akarnokd** [comment]
Exceptions are first class citizens in RxJava and they can appear virtually everywhere.

**Comment by pakoito** [comment]
And many cases can not be analyzed, yes. This propose only covers a subset of them that can.

**Comment by akarnokd** [comment]
The best one can do is to warn when you use ```subscribe(Action1)``` instead of the other subscribe methods.

**Comment by pakoito** [comment]
Fair enough.
