### ISSUE TITLE
Call Observable.subscribe(Subscriber s)  use the same subscriber

### ISSUE THREAD

**Issue by sxyzgit** [ReactiveX/RxJava#2910]
Hello,
When I call Observable.subscribe(Subscriber s)  use the same subscriber many times, it call Observable.OnSubscribe.call() only the first time.
Like this:
```
Subscriber mSubscriber;
void test() {
    Observable.subscribe(mSubscriber);
}
```
But
```
void test() {
    Observable.subscribe(new Subscriber(){...});
}
```
Not.
Is there any other methods can resolve this?
Thanks!

**Comment by akarnokd** [comment]
Hello. What is this Observable? Sources published via ```publish``` will subscribe to their source only once regardless of how many subscribers there are. For a regular cold observable, resubscribing the same subscriber works although it is discouraged:
```java
@Test
public void testSameSubscriberMultipleSubscriptions() {
    AtomicInteger count = new AtomicInteger();
    Observable<Integer> source = Observable.create(s -> {
        count.getAndIncrement();
        s.onNext(1);
    });
    Assert.assertEquals(0, count.get());
    
    TestSubscriber<Integer> ts = new TestSubscriber<>();
    
    source.subscribe(ts);
    ts.assertReceivedOnNext(Arrays.asList(1));
    Assert.assertEquals(1, count.get());
    
    source.subscribe(ts);
    ts.assertReceivedOnNext(Arrays.asList(1, 1));
    Assert.assertEquals(2, count.get());

    source.subscribe(ts);
    ts.assertReceivedOnNext(Arrays.asList(1, 1, 1));
    Assert.assertEquals(3, count.get());
}
```

**Comment by sxyzgit** [comment]
```
Observable<Integer> source = Observable.create(s -> {
    count.getAndIncrement();
    s.onNext(1);
    // s.onComplete();
});
```

**Comment by sxyzgit** [comment]
The occurrence of this problem is because I call the onComplete() method at the wrong time.
```
Observable<Integer> source = Observable.create(s -> {
    count.getAndIncrement();
    s.onNext(1);
    // s.onComplete();
});
```
Thanks very much!

**Comment by sxyzgit** [comment]
s

**Comment by sxyzgit** [comment]
Hello,

Now I have a new doubt that why when call `Subscriber.onComplete()` it can't be subscribe again (means even if you call `Observable.subscribe(mSubscriber)` again, it doesn't call Observable.OnSubscribe.call()). It is supposed to be like this?

Because I use the `Retrofit` and read the source at `retrofit.RxSupport` found it call `subscriber.onCompleted()` after `subscriber.onNext(wrapper.responseBody)` immediately in `getRunnable(...)` method, so it leads to the previous issue

Thinks!

**Comment by akarnokd** [comment]
That is true. Calling ```onCompleted``` on a ```Subscriber``` is a terminal event and the subscriber won't respond to any further events.

**Comment by benjchristensen** [comment]
A `Subscriber` can only be used once as it is stateful (the subscription). You can use an `Observer` instead if you want to reuse it, or pass in Actions instead.

**Comment by sxyzgit** [comment]
@akarnokd Thanks, I got it.

**Comment by sxyzgit** [comment]
@benjchristensen 
Ok, I got it.
I'll try it, thanks!
