### ISSUE TITLE
Proposal: Manage CompositeSubscription in the Subscription/Subscriber

### ISSUE THREAD

**Issue by Diolor** [ReactiveX/RxJava#2919]
For a `CompositeSubscription cSubscription = new CompositeSubscription();` / example in Android.

The below can become really lengthy if there are many subscriptions that have to be unsubscribed:

        Subscription s1 = bindActivity(this, estimationsModel.getEtaObservable())
                .subscribe(this::setEtaText, baseAction1);

        Subscription s2 = bindActivity(this, estimationsModel.getTipObservable())
                .subscribe(this::setTip, baseAction1);

        cSubscription.add(s1);
        cSubscription.add(s2);

Proposal add a `addTo(CompositeSubscription subscription)` in the Subscription interface/subscribers. The above can look more elegant with the following:

        bindActivity(this, estimationsModel.getEtaObservable())
                .subscribe(this::setEtaText, baseAction1)
                .addTo(cSubscription);

        bindActivity(this, estimationsModel.getTipObservable())
                .subscribe(this::setTip, baseAction1)
                .addTo(cSubscription);

Would it be a bad idea in terms of testing?

**Comment by akarnokd** [comment]
Hello. This change can't be done in an API-safe manner: Subscription is an interface and we can't break it and even if, the interface referencing a concrete (public) implementation of itself is an API design to be avoided in general.

**Comment by Diolor** [comment]
I see. Well, inspiration for the future :)
