### ISSUE TITLE
Missing from Gradle

### ISSUE THREAD

**Issue by kamoljan** [ReactiveX/RxJava#2922]
Hi guys

I cannot access your repo via gradle:

    compile 'com.netflix.rxjava:rxjava-core:1.0.9'
    compile 'com.netflix.rxjava:rxjava-android:1.0.9'

Anyone can help to push to your repo?

Best regards
Kamol

**Comment by akarnokd** [comment]
What do you mean? If you want to contribute, clone the repo on github, create a branch then push to your repo/branch. After this, you will see an option on github to create PR against this main repository.

**Comment by kamoljan** [comment]
@akarnokd thank you!

**Comment by benjchristensen** [comment]
> compile 'com.netflix.rxjava:rxjava-core:1.0.9'

That is the wrong Maven IDs.

See here: http://search.maven.org/#artifactdetails%7Cio.reactivex%7Crxjava%7C1.0.9%7Cjar

It should instead be:

> compile 'io.reactivex:rxjava:1.0.9'

**Comment by kamoljan** [comment]
@benjchristensen thank you! All good now!

Here code, maybe it will be useful for someone:

    compile 'io.reactivex:rxandroid:0.24.0'
    compile 'io.reactivex:rxjava:1.0.9'
