### ISSUE TITLE
Almost every operator documentation link in wiki pages is broken

### ISSUE THREAD

**Issue by GNima** [ReactiveX/RxJava#2941]
Apparently http://reactivex.io/documentations/ has changed to http://reactivex.io/documentation/

For example [in this page](https://github.com/ReactiveX/RxJava/wiki/How-To-Use-RxJava#creating-observables), `create()` points to http://reactivex.io/documentations/operators/create.html while the correct link is http://reactivex.io/documentation/operators/create.html. Same case for almost every other operator.

**Comment by DavidMGross** [comment]
Hmmm... I thought I'd caught all of those. I'll go back through and
reinvestigate. Thanks for letting me know.

On Sat, May 9, 2015 at 8:16 AM, Nima Ghafoori <notifications@github.com>
wrote:

> Apparently http://reactivex.io/documentations/ has changed to
> http://reactivex.io/documentation/
>
> For example in this page
> <https://github.com/ReactiveX/RxJava/wiki/How-To-Use-RxJava#creating-observables>,
> create() points to
> http://reactivex.io/documentations/operators/create.html while the
> correct link is http://reactivex.io/documentation/operators/create.html.
> Same case for almost every other operator.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ReactiveX/RxJava/issues/2941>.
>



-- 
David M. Gross
PLP Consulting

**Comment by DavidMGross** [comment]
I found and corrected faulty "documentations/" URLS on these two pages:

https://github.com/ReactiveX/RxJava/wiki/How-To-Use-RxJava
https://github.com/ReactiveX/RxJava/wiki/Implementing-Your-Own-Operators

I didn't find any such faulty URLs on any of the other pages in the wiki
