### ISSUE TITLE
TestObserver thread-safety

### ISSUE THREAD

**Issue by artem-zinnatullin** [ReactiveX/RxJava#2947]
Disclaimer: I understand, that `TestObserver` and `TestSubscriber` were made for Unit testing purposes, but they are pretty convenient because you can record received notifications and emissions, make assertions and so on, so we used them it in our Integration test and faced problem with thread-safety of `TestObserver`.

The problem is that `TestObserver` uses `ArrayList` to store notifications and received items, in case of multi-threaded `Observable` `ArrayList` may be corrupted and tests can fail randomly.

What do you think about using thread-safe list implementation in `TestObserver`? It should not break public API. I can prepare PR for that.

**Comment by benjchristensen** [comment]
None of these types are thread safe and are not supposed to be as Observables are single threaded. We do not serialize by default for performance reasons. 

If you need to serialize a Subject, use the toSerialized() method. An Observer should never need to be thread safe unless an Observable is breaking the contract, in which case use Observable.serialize()

**Comment by artem-zinnatullin** [comment]
Oh.. Dived in sources for couple hours, wrote several questions and then deleted them, now I understand more. Thanks.

One question left: am I correct that there is no need to serialize `PublishSubject` because it's already serialized per each `Observer`, because each `Observer` wrapped into `SubjectSubscriptionManager.SubjectObserver` which is serialized?

**Comment by akarnokd** [comment]
No. You need to front-serialize a ```PublishSubject``` via ```toSerialized()```. Technically, a concurrent ```onNext()``` call doesn't break ```PublishSubject``` itself but observers don't and shouldn't anticipate concurrent calls to their ```onXXX``` methods.

**Comment by artem-zinnatullin** [comment]
Checked sources again, now I see. Thanks! Issue solved.
