### ISSUE TITLE
Flatten operator

### ISSUE THREAD

**Issue by mttkay** [ReactiveX/RxJava#295]
This is more a request for discussion.

I'm not sure .NET's Rx has something like this, but one thing I miss in RxJava is an operator to flatten an `Observable<List<T>>` to `Observable<T>`. As far as I can tell, this currently requires one to write somewhat clunky code using flatMap:

```
Observable.from(...).toList().flatMap(new Func1<List<...>, Observable<...>>() {
        @Override
        public Observable<...> call(List<...> list) {
            return Observable.from(list);
        }
    });
```

i.e. there seems to be no standard reverse operation for toList. Is this something you would deem worth having in the library itself? It would simplify the above call to:

```
Observable.from(...).toList().flatten()
```

**Comment by vincent-paing** [comment]
Hello, there's no more from method in rxjava 2. Is there a workaround?

**Comment by akarnokd** [comment]
@vincent-paing check again, it is still called `flatMapIterable` in 2.x.

**Comment by vincent-paing** [comment]
@akarnokd  yea but there's no longer "from" method. I tried used fromIterable(myArrayList) but IDE gives me error due to different type

**Comment by akarnokd** [comment]
It is called `fromArray()` to avoid ambiguities in Java 8+.

**Comment by vincent-paing** [comment]
@akarnokd  Thanks, that works :D
