### ISSUE TITLE
Runtime Error

### ISSUE THREAD

**Issue by ronakvbhalani** [ReactiveX/RxJava#2952]
com.example.demo.MainActivity.onCreate
FATAL EXCEPTION: main
com.android.internal.os.ZygoteInit.main
com.android.internal.policy.impl.PhoneLayoutInflater.onCreateView
com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java:290)
com.example.demo.MainActivity.onCreate

**Comment by akarnokd** [comment]
Could you be more specific? What kind of application is this, what does it try to accomplish and what is the concrete underlying exception?

**Comment by akarnokd** [comment]
The question is not specific enough and stale. I'm closing this.
