### ISSUE TITLE
How do I waiting for one observable complete?

### ISSUE THREAD

**Issue by jiqimaogou** [ReactiveX/RxJava#2954]
```
AccountService.logout().subscribe();

view.setOnClickListener(new onClickListener() {
@override
public void onClick(View view) {
AccountService.login().subscribe();//<<<<<here to waiting for logout is complete and then login
}
}
```

**Comment by zsxwing** [comment]
You can call `AccountService.login().toBlocking()` to convert it to a `BlockingObservable` and choose a proper method in `BlockingObservable` to use. However, it's not a good idea to block the UI thread. For Android stuffs, it's better to ask in the [maillist](https://groups.google.com/forum/#!forum/rxjava) or [stackoverflow](http://stackoverflow.com/questions/tagged/rx-java).

**Comment by farmazon3000** [comment]
Please note (from BlockingObservable docs):
```
It can be useful for testing and demo purposes, but is generally inappropriate for production applications (if you think you need to use a BlockingObservable this is usually a sign that you should rethink your design)
```
