### ISSUE TITLE
Schedulers documentation improvements

### ISSUE THREAD

**Issue by JensRantil** [ReactiveX/RxJava#2955]
Source: http://reactivex.io/documentation/scheduler.html

 * Neither of the schedulers has a working link to corresponding JavaDoc.
 * `Schedulers#computation` documentation doesn't state how many threads it runs. Whether it runs async or really anything. I had to dig into source code and finally ended up on https://github.com/ReactiveX/RxJava/pull/2580/files which states it defaults to number of processors threads.
 * `Schedulers#io` is missing the same documentation; how many threads? Does it grow infinitely?

**Comment by DavidMGross** [comment]
Moved over to the website issues section:

https://github.com/ReactiveX/reactivex.github.io/issues/114
