### ISSUE TITLE
Observable.any, Observable.all backpressure support

### ISSUE THREAD

**Issue by davidmoten** [ReactiveX/RxJava#2957]
Looks like an easy win here to get backpressure support on the `any` and `all` operators with the addition of `.takeLast(1)`:

```
public final Observable<Boolean> all(Func1<? super T, Boolean> predicate) {
        return lift(new OperatorAll<T>(predicate)).takeLast(1);
    }
```

Any objections? If not I can make a couple of PRs with unit tests for these operators.

**Comment by akarnokd** [comment]
I like operators with as little internal chains as possible. They could use some rewriting, see my [blog posts](http://akarnokd.blogspot.hu/2015/05/pitfalls-of-operator-implementations_14.html).

**Comment by davidmoten** [comment]
All right, I knock something up as per your posts. They are an excellent resource, thanks a lot for them!

**Comment by akarnokd** [comment]
Both support backpressure for some time now. I'm closing this. Thanks!
