### ISSUE TITLE
Backpressure and "nested Observables"

### ISSUE THREAD

**Issue by HugoCrd** [ReactiveX/RxJava#2958]
Hi,

I encountered a behavior with Backpressure that I found weird.
Here is a working example (in Groovy) with backpressure : 

```
rx.Observable.from([1, 2, 3, 4])
    .flatMap({ rx.Observable.just(it+1) })
    .delay(2, java.util.concurrent.TimeUnit.SECONDS)
    .subscribe(new rx.Subscriber<Integer>() {
      public void onStart() {
        request(2);
      }
      public void onNext(Integer t) {
        println(t)
        request(1);
      }
      public void onCompleted() { }
      public void onError(Throwable e) { }
    });

// Prints : 
2
3 //waits 2 seconds here
4
5
```

Let's apply ```delay``` directly on the Observable into the ```flatMap``` Operator : 
```
rx.Observable.from([1, 2, 3, 4])
    .flatMap({rx.Observable.just(it+1).delay(2, java.util.concurrent.TimeUnit.SECONDS)})
    .subscribe(new rx.Subscriber<Integer>() {
      public void onStart() {
        request(2);
      }
      public void onNext(Integer t) {
        println(t)
        request(1);
      }
      public void onCompleted() { }
      public void onError(Throwable e) { }
    });

// Prints : 
// waits 2 seconds
2
5
4
3// In a random order
```

I can't see why the second one is not acting like the first, printing 2 results, waiting 2 seconds before printing 2 other ones.
Is this the normal behavior? Why? How should I do to achieve such a thing?

Thanks a lot for your hard work and this amazing library ;)

**Comment by akarnokd** [comment]
They work as expected. 

The first case, you should see a 2 second delay before 2 too, but because you delay request(1) as well, the next value will get 2 second delay relative to that.

In the second case, since all just values are delayed independently and emit from different threads, the end result order is random.

You can use timeinterval() to see the delays between values.

**Comment by HugoCrd** [comment]
So ```rx.Observable.just(it+1)``` are all subscribed when I subsribe to the Observable. In that case I understand why they all complete at the same time.

I thought backpressure would allow me to subscribe to whatever[1] is into the ```flatMap``` when ```request(1)``` is called (and not before).

Well I got some other solutions to do that, but I was happy to use backpressure in a real case ;)

[1] which in my real world problem is not a ```delay``` but a long processing
