### ISSUE TITLE
Throwables, throwIfFatal and addValueAsLastCause usage

### ISSUE THREAD

**Issue by akarnokd** [ReactiveX/RxJava#2962]
I've seen many places so far where once a Throwable is caught, we check for its fatality and attach the last value to it, however, many other places don't do this. Should the following pattern be universally applied?

```java
T v = ...
try {
    doSomeWork(v);    
} catch (Throwable e) {
    Exceptions.throwIfFatal(e);
    Throwable e1 = OnErrorThrowable.addValueAsLastCause(e, v);
    // child.onError(e1)
    // plugin.handleError(e2)
    return;
}
```

**Comment by benjchristensen** [comment]
I only ever considered it needed when wrapping around user provided functions. Is there a use case that isn't a user function where we need it?

**Comment by stealthcode** [comment]
Is this implemented in #3183?

**Comment by akarnokd** [comment]
Only those places that didn't conflict with my other PRs.

**Comment by akarnokd** [comment]
Several fixes delivered.
