### ISSUE TITLE
1.0.11

### ISSUE THREAD

**Issue by benjchristensen** [ReactiveX/RxJava#2965]
https://github.com/ReactiveX/RxJava/pull/2948 More assertions for TestSubscriber
https://github.com/ReactiveX/RxJava/pull/2956 OperatorObserveOn should not request more after child is unsubscribed
https://github.com/ReactiveX/RxJava/pull/2951 OperatorConcat - prevent request overflow and fix race condition
https://github.com/ReactiveX/RxJava/pull/2950 OperatorGroupBy - check for request overflow and don't decrement when at Long.MAX_VALUE
https://github.com/ReactiveX/RxJava/pull/2923 OnBackpressureLatest: Non-blocking version of the toBlocking().latest() operator.
https://github.com/ReactiveX/RxJava/pull/2907 Fixed schedule race and task retention with ExecutorScheduler.
https://github.com/ReactiveX/RxJava/pull/2929 OperatorObserveOn onComplete can be emitted despite onError being called
https://github.com/ReactiveX/RxJava/pull/2940 Remove unnecessary localHasValue check
https://github.com/ReactiveX/RxJava/pull/2939 publish: Fix another race between terminalEvent and the queue being empty.
https://github.com/ReactiveX/RxJava/pull/2938 Fixed Observable.combineLatest overflow bug on Android
https://github.com/ReactiveX/RxJava/pull/2936 Fix TestSubject bug
https://github.com/ReactiveX/RxJava/pull/2934 Fix termination race condition in OperatorPublish.dispatch
https://github.com/ReactiveX/RxJava/pull/2963 Set of standard producers and updated queue implementations with some

**Comment by benjchristensen** [comment]
I propose releasing with the above changes as 1.0.11 then following up with some of the non-trivial open pull requests for 1.0.12 after thorough review of them.

**Comment by akarnokd** [comment]
Sounds good.

**Comment by akarnokd** [comment]
Released. Closing.
