### ISSUE TITLE
OnSubscribeRefCountTest.testConnectUnsubscribeRaceCondition failed

### ISSUE THREAD

**Issue by akarnokd** [ReactiveX/RxJava#2974]
The test is not deterministic and may fail on line 314: ```assertEquals(0, subUnsubCount.get());```.

**Comment by davidmoten** [comment]
Could you change the title so we know it's about `OnSubscribeRefCount`?

**Comment by akarnokd** [comment]
May need increased wait time before the assertion. Travis tends to trip this in rush hours.
