### ISSUE TITLE
Make Time unit configurable on Timestamped

### ISSUE THREAD

**Issue by yogurtearl** [ReactiveX/RxJava#2976]
Right now, Timestamped assumes milliseconds. 

Java convention is take a "long" and a "java.util.concurrent.TimeUnit" .
Can we change to allow this?

**Comment by akarnokd** [comment]
The highest resolution, consistent across cores and absolute timer in Java is System.currentTimeMillis(); we can't timestamp events in any higher resolution.

**Comment by schrepfler** [comment]
Why was System.currentTimeMillis() chosen rather than System.nanoTime()?

**Comment by akarnokd** [comment]
System.nanoTime() is not an absolute time and it is not guaranteed to be consistent across cores. See [this](http://shipilev.net/blog/2014/nanotrusting-nanotime/) for details.

**Comment by yogurtearl** [comment]
A custom scheduler might want to use a different time source that can support nanos.

Also, just for consistency with JDK APIs and other RxJava APIs, it might be nice.

```java
new TimeStamped( 42, SECONDS, foo );

timestamped.read(SECONDS);
```

RxJava API that takes TimeUnit: Worker.schedule( Action0 action, long time, TimeUnit unit)

**Comment by akarnokd** [comment]
Pull requests are welcome :)

**Comment by akarnokd** [comment]
This would be a public API break for 1.x. The 2.x developer preview has been implemented with this in mind.
