### ISSUE TITLE
Flatmap error handling oddity/bug?

### ISSUE THREAD

**Issue by spodila** [ReactiveX/RxJava#2977]
When one of the inner observables of a flatmap returns an error, the handling of the error via onErrorResumeNext() seems incorrect. 

The following unit test fails when I omit the onErrorResumeNext() on each of the inner observable. When one of the inner observables returns an error, the entire outer observable is being completed, even though the outer observable has its own onErrorResumeNext() defined. It does get into that handler, but, the entire observable chain is completed. I am expecting that the error handler on the outer observable should let me handle that error and continue. 

Uncommenting out the onErrorResumeNext() on the inner observables in the test does make it behave as I would like it to. However, it seems tedious (and unnecessary?) to put that handler on every inner observable. Especially when there may be another level or two of further inner observables. 

``` java
public class FlatmapErrorHandlerTest {

    private static Observable<Long> createO(final Integer source) {
        return Observable.create(new Observable.OnSubscribe<Long>() {
            @Override
            public void call(Subscriber<? super Long> subscriber) {
                Observable.timer(1, 1, TimeUnit.SECONDS)
                        .flatMap(new Func1<Long, Observable<Long>>() {
                            @Override
                            public Observable<Long> call(Long aLong) {
                                if (source == 2 && aLong > 2) // simulate condition for needing to pass an error through
                                    return Observable.error(new Exception("Test exception from " + source));
                                return Observable.just(aLong);
                            }
                        })
                        .subscribe(subscriber);
            }
        });
    }

    @Test
    public void TestInnerObsErrorHandling() throws Exception {
        final long until=7;
        final CountDownLatch latch = new CountDownLatch(1);
        Observable.from(new Integer[] {1, 2, 3})
                .flatMap(new Func1<Integer, Observable<Long>>() {
                    @Override
                    public Observable<Long> call(Integer integer) {
                        return createO(integer)
//                                .onErrorResumeNext(new Func1<Throwable, Observable<? extends Long>>() {
//                                    @Override
//                                    public Observable<? extends Long> call(Throwable throwable) {
//                                        System.err.println("Inner error: " + throwable.getMessage());
//                                        return Observable.empty();
//                                    }
//                                })
                                ;
                    }
                })
                .onErrorResumeNext(new Func1<Throwable, Observable<? extends Long>>() {
                    @Override
                    public Observable<? extends Long> call(Throwable throwable) {
                        System.err.println("error: " + throwable.getMessage());
                        return Observable.empty();
                    }
                })
                .doOnNext(new Action1<Long>() {
                    @Override
                    public void call(Long aLong) {
                        if (aLong >= until) latch.countDown();
                    }
                })
                .doOnCompleted(new Action0() {
                    @Override
                    public void call() {
                        System.out.println("Completed");
                    }
                })
                .subscribe();
        if(!latch.await(10, TimeUnit.SECONDS))
            Assert.fail();
    }
}
```

**Comment by akarnokd** [comment]
It works as expected. If an inner Observable errors out, the error is propagated as the merge result and your merged stream completes after 3 seconds and the values can never reach 7 at that point, hence the latch is not counted down(). With the inner resumes, you just swallow the exception and sequence 2 falls out while the rest continue.

**Comment by benjchristensen** [comment]
> the error handler on the outer observable should let me handle that error and continue

An error is still a terminal event so everything upstream will be terminated. The error handlers allow handling an error and deciding what to emit downstream, but do not allow ignoring an error in the upstream which is now terminated. 

The errors will need to be handled on each inner Observable if you want to prevent a terminal event from being propagated. Or you can use `mergeDelayError` if you want to collect all errors and delay them until the stream is completed ... but don't use that on an infinite stream.

**Comment by spodila** [comment]
Thank you, @akarnokd and @benjchristensen .
I appreciate the fact that my expectations on error handling behavior for a flatmap must be reset. In which case, I am looking for ideas on how to achieve what I am trying to do. 

Say, I have 3 levels of nested (for lack of a better word) observables (although, it's a few more in reality). At the highest level, Level2, it creates inner observables, one each for a group. Each of these Level1 observables in turn create inner observables, one each for connection into a specific server that belongs to that group. These are the Level0 observables. Now, say, one of the Level0 observables propagates an application level error that says that the service request is invalid or disallowed. Note that this isn't an error in communicating to the server (which is handled via retryWhen operator), but an actual application error condition. 

At the highest level, Level2, it needs to notice the specific error from Level0, report that the request is disallowed at a specific server, but, continue with processing results from the rest of servers at Level0. 

If I am writing that entire piece of code, I suppose I can put onErrorResumeNext() for every observable I create. However, If I am only writing the Level2 code, but am given a flat map of Level1 observables, which are flatmapping over their Level0 observables, and this code was written elsewhere, how does one go about achieving this? 

If Level1 observables are given to me as a library, for example, what is the best practice for the library developer to achieving this? Is a flatmap the wrong choice? If so, this could take on an Observable<Observable<Observable<...>>> form, which is a bit unwieldy. 

Is this making sense?

One way to achieving this may be to change from O<T> to O<WrpdT>, where WrpdT wraps T with metadata that indicates errors. Then, that specific Level0 observable transmits a final WrpdT that indicates the error. That seems somewhat like an ugly workaround.

How else would one do this?

**Comment by spodila** [comment]
After a brief conversation with Ben, it seems that I'll have to deal with it in my app via error handling for the inner observables. An alternative is to materialize the events with the slight overhead of object creations. 
Closing the issue.
