### ISSUE TITLE
Race condition in NewThreadWorker

### ISSUE THREAD

**Issue by headinthebox** [ReactiveX/RxJava#2980]
https://github.com/ReactiveX/RxJava/blob/1.x/src/main/java/rx/internal/schedulers/NewThreadWorker.java

Thread A calls w.schedule(…), passes the test on line 151, then sits at line 153
Thread B calls w.unsubscribe() and sits at line 213
Thread A enters scheduleActual and executes until line 169 where it calls schedule on an executor that has been shut down.

**Comment by akarnokd** [comment]
The executor handles the race and we simply ignore the RejectedExecutionException.

**Comment by headinthebox** [comment]
Where do they get caught?

**Comment by benjchristensen** [comment]
Okay I'm curious now ... where do we catch that exception to ignore it? :-)

It definitely throws one: http://docs.oracle.com/javase/8/docs/api/java/util/concurrent/ExecutorService.html#submit-java.util.concurrent.Callable-

I've been tracing through the code and honestly can't figure out where the try/catch is at if we do catch and ignore it.

**Comment by iNoles** [comment]
@benjchristensen It is in https://github.com/ReactiveX/RxJava/blob/1.x/src/main/java/rx/schedulers/ExecutorScheduler.java

**Comment by akarnokd** [comment]
ScheduledAction.run
Observable.create
Observable.lift

**Comment by headinthebox** [comment]
We cannot rely on the latter two, as schedulers are useful by themselves.
