### ISSUE TITLE
how to best inspect multiple merged observables for a minimal state

### ISSUE THREAD

**Issue by simonbasle** [ReactiveX/RxJava#2984]
Hi,
I have a case where we fire multiple polling requests that get merged into one `Observable`. We collect the results into a state of two counters, each response potentially incrementing one or both counters.

Sometimes, some requests take a little too much time responding.
Also when starting this polling, we specify N and M criteria (the thresholds for each counter where we should consider the whole polling a success and continue processing).

What I'd like to do is build a stream that will take the shortcut and complete as soon as counters reach N and M, even if we launched the merge with more polling than required (and despite the fact that some of them take a long time / timeout).

Think of it like a merge of ping requests on a cluster of servers: calling mergedPing(2) on servers A, B and C should return as soon as A and B have responded, discarding the fact that C stalls / times out.

Do you see any clever (or obvious) way of doing this?
Thanks in advance!

**Comment by akarnokd** [comment]
Lets assume each of your service returns the following value class:

```java
class Counters {
    final int n;
    final int m;
    public Counters(int n, int m) {
        this.n = n;
        this.m = m;
    }
    public Counters add(Counters other) {
        return new Counters(n + other.n, m + other.m);
    }
}
```
You merge into an ```Observable<CounterDeltas>```, scan the stream and aggregate, then you take until the counters reached the desired limit and then take the last value:

```java
Observable<Counters> a = Observable.just(new Counters(1, 0));
Observable<Counters> b = Observable.just(new Counters(0, 1));
        
Observable.merge(a, b, a, b, a, b, a, b)
.scan(new Counters(0, 0), (r, v) -> r.add(v))
.takeUntil(c -> c.n == 2 && c.m == 2)
.takeLast(1)
.subscribe(c -> System.out.printf("%d, %d%n", c.n, c.m));
```

**Comment by simonbasle** [comment]
Thanks @akarnokd
I was thinking about `scan` and it turns out it was the way to go. Very good insight on the immutable state  class.

Here's about what I ended up doing (with the example of the ping, `PingStats` tracks number of pings > 100ms and number of pings < 100ms):

```java
Observable<Ping> poll = sendPingRequests(); //sends to, say, 5 nodes

//will send pings to all servers every 1s until at least 2 nodes report a ping < 100ms
return poll
    .map(ping -> new PingStats(ping))
    .scan(EMPTY_PINGSTATS, (pollStats, next) -> pollStats.add(next))
    .repeatWhen(voidObs -> Observable.timer(1, TimeUnit.SECONDS)) //repeat every 1s
    .skipWhile(pingStats -> pingStats.lessThan100ms() < 2) //wait for criteria to be met
    .take(1)
    .map(pingStats -> true);
```
