### ISSUE TITLE
Suggest to add pom.xml for Maven. 

### ISSUE THREAD

**Issue by gencube** [ReactiveX/RxJava#3005]
Many company uses Maven as a corporate level standard.

Please consider adding a file to help others to try your code in common ide like netbeans and eclipses.

**Comment by benjchristensen** [comment]
Gradle is widely supported in the industry and by the major IDEs. 

Netbeans: https://netbeans.org/features/java/build-tools.html
Eclipse: https://docs.gradle.org/current/userguide/eclipse_plugin.html
Eclipse: https://marketplace.eclipse.org/content/gradle-integration-eclipse-44
IDEA: https://www.jetbrains.com/idea/help/gradle.html
IDEA: https://docs.gradle.org/current/userguide/idea_plugin.html
Android Studio: https://developer.android.com/tools/building/configuring-gradle.html

If you do not wish to use a plugin, just type "./gradlew eclipse" and it will prepare your working folder as an Eclipse project that you can import into your Eclipse IDE.

**Comment by davidmoten** [comment]
A few more details about importing to Eclipse are here: https://github.com/ReactiveX/RxJava/wiki/How-to-Contribute

**Comment by gencube** [comment]
Thanks David. Helpful. I am new to RxJava.

**Comment by gencube** [comment]
I just tried, had this issue instead: 

Download https://jcenter.bintray.com/org/apache/httpcomponents/httpcore/4.2.4/httpcore-4.2.4.jar

FAILURE: Build failed with an exception.

* Where:
Build file '/home/mattong/NetBeansProjects/downloaded/ReactiveIO/RxJava-1.x/build.gradle' line: 8

* What went wrong:
A problem occurred evaluating root project 'rxjava'.
> Failed to apply plugin [id 'rxjava-project']
   > repository not found: /home/mattong/NetBeansProjects/downloaded/ReactiveIO/RxJava-1.x

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 3 mins 29.589 secs

**Comment by gencube** [comment]
However, I can try other RxJava Project with already published dependency on maven. Not a huge issue for trying out. But to see how the internal code works. I can create my own maven project. Since I never used "gradlew" before, where are the list of dependencies for building my own RxJava?

**Comment by gencube** [comment]
anyhow, this is the pom.xml file for RxJava 1.0.11 if any is looking for it:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>io.reactivex</groupId>
    <artifactId>rxjava</artifactId>
    <version>1.0.11</version>
    <packaging>jar</packaging>
    <name>${project.artifactId}</name>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
        <maven.test.skip>true</maven.test.skip>        
        <maven.compiler.source>1.7</maven.compiler.source>
        <maven.compiler.target>1.7</maven.compiler.target>                
    </properties>

    <dependencies>
        <dependency>
            <groupId>org.mockito</groupId>
            <artifactId>mockito-core</artifactId>
            <version>1.10.19</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit-dep</artifactId>
            <version>4.11</version>
            <scope>test</scope>
        </dependency>        
    </dependencies>
    <build>
        <finalName>${project.name}</finalName>   
    </build>            

</project>
```
