### ISSUE TITLE
Javadoc for cache suggests eager subscribe

### ISSUE THREAD

**Issue by mattrjacobs** [ReactiveX/RxJava#3007]
Lines 27-28 of OnSubscribeCache:
* This method has similar behavior to {@link Observable#replay()} except that this auto-subscribes
 * to the source Observable rather than returning a connectable Observable.

It appears that the subscribe() to the source is lazy

**Comment by akarnokd** [comment]
Care to submit a PR for this?

**Comment by akarnokd** [comment]
See #4026 for the proposed javadoc changes.

**Comment by akarnokd** [comment]
Closing via #4026.
