### ISSUE TITLE
Data loss with RetryWithPredicate as compared to Retry Infinite

### ISSUE THREAD

**Issue by stealthcode** [ReactiveX/RxJava#3008]
The following test fails once when mapping 3 values. The subscribe only receives 2 values. 
```java
final AtomicBoolean isFirst = new AtomicBoolean(true);
Observable.<Long> just(1L, 2L, 3L).map((Long x) -> {
    System.out.println("map " + x);
    if (x == 2 && isFirst.getAndSet(false)) {
        throw new RuntimeException("retryable error");
    }
    return x;
})
.retry((i, t) -> {return true;})
.forEach(System.out::println);
```

**output**
```
map 1
1
map 2
map 3
3
```

When you replace `.retry((i, t) -> {return true;})` with the retry infinite `retry()` then the output looks like this...

```
map 1
1
map 2
map 1
1
map 2
2
map 3
3
```

**Comment by davidmoten** [comment]
Yep, I'll have a look at it in the next couple of days. @stealthcode I'll check it with #2997 which is looking to address a few `retry` issues.

**Comment by davidmoten** [comment]
I've tested these with #2997 and they both pass.

The emissions are for retry with always true predicate:
```
map 1
1
map 2
map 3
map 1
1
map 2
2
map 3
3
```
and for infinite retry:
```
map 1
1
map 2
map 1
1
map 2
2
map 3
3
```

The emissions are the same and are expected. I'm unsure why the extra line `map 3` occurs in the logging of retry with predicate but might be worth checking.

I'll commit the two new unit tests (in `OperatorRetryWithPredicateTest` to the #2997 PR.

**Comment by stealthcode** [comment]
This seems to be fixed in the latest master
