### ISSUE TITLE
Custom Operators and onBackpressureBuffer

### ISSUE THREAD

**Issue by davidmoten** [ReactiveX/RxJava#3020]
A very common use case for me is  to need an `Operator` that takes a backpressure supporting stream and for every arrival makes 0..* emissions. 

I can get a backpressure compliant Operator by:

* requesting one from upstream when no emissions are made from an arrival so stream doesn't stall
* buffering emissions using the new `QueuedProducer` 

The second action is doable but is a bit invasive to implement and I would normally check the RxJava codebase for an Operator that used it and make sure I did something similar. 

Instead of using `QueuedProducer` I'd like a simpler solution that uses composition and `onBackpressureBuffer` looks like the one but has one significant defect in that it always requests `Long.MAX_VALUE` of upstream instead of requesting only what it needs.

 Is there an idiom I'm overlooking? Can we modify `OperatorOnBackpressureBuffer` to support this use case or would a new `Operator` be the go (that uses `QueuedProducer` internally).

**Comment by akarnokd** [comment]
> A very common use case for me is to need an Operator that takes a stream and for every input makes 0..* emissions.

`flatMap` ?

Otherwise, I don't believe you can achieve this with existing operators and retaining backpressure values all the way. `QueueProducer` might not be the best for the job because no need to handle the case when the queue becomes empty and you have to request more from upstream at that point. So I think, for an efficient implementation, you have to start from [first principles](http://akarnokd.blogspot.hu/2015/05/operator-concurrency-primitives.html).

**Comment by davidmoten** [comment]
Thanks @akarnokd, I should clarify that internal to the Operator is a subscriber-specific state machine which undergoes transitions as items arrive and transitions can cause emissions. For this reason `flatMap` doesn't cut it.

I think I'm missing describing another important detail. Namely that the number of emissions from the Operator never exceeds the number of arrivals. So a request to the child is passed straight through to the parent, and any extra requests made by the Operator itself in reaction to not emitting when something arrives may cause too many items to eventually be emitted from the Operator. So all I want to bolt on here is something like `onBackpressureBuffer` but I want it too request what is requested from it instead of just requesting `Long.MAX_VALUE`.

**Comment by davidmoten** [comment]
I'll mention a concrete example that is similar to what I encounter in my work. I have a stream of timestamped position+speed reports from a ship and from that stream I want to emit only those reports where the vessel was travelling slowly but not stopped for at least an hour.

**Comment by davidmoten** [comment]
Yep I'm familiar with the queue drainers from your very handy blog posts, I just think would be useful encapsulated in an Operator so could use composition in this use case to easily get backpressure conformance.

**Comment by davidmoten** [comment]
I just updated the first comment to mention that upstream of the custom Operator is a backpressure supporting stream.

**Comment by abersnaze** [comment]
> Thanks @akarnokd, I should clarify that internal to the Operator is a subscriber-specific state machine which undergoes transitions as items arrive and transitions can cause emissions. For this reason flatMap doesn't cut it.

@davidmoten `flatScan`?

**Comment by davidmoten** [comment]
This common use case for me can be implemented idiomaticallly using `scan` and `flatMap` (thus supporting backpressure) as @akarnokd  and @abersnaze have suggested and I'll be trialling an abstraction that simplifies the implementation next week. I'll report back after that.

**Comment by davidmoten** [comment]
I've been trialling a method that does `materialize`, `scan` and `flatMap` under the covers with this signature:

```java
    public static <State, In, Out> Transformer<In, Out> stateMachine(
            Func0<State> initialStateFactory,
            Func3<? super State, ? super In, ? super Observer<Out>, ? extends State> transition,
            Action2<? super State, ? super Observer<Out>> completionAction) ;
```

On top of this I built 

```java
public static <T> Transformer<T, List<T>> toListWhile(
            final Func2<? super List<T>, ? super T, Boolean> condition);
```
and 

```java
public static <T, R extends Collection<T>> Transformer<T, R> collectWhile(
            final Func0<R> factory, final Action2<? super R, ? super T> collect,
            final Func2<? super R, ? super T, Boolean> condition);
```

Use cases for the above methods crop up frequently for me and also appeared in http://stackoverflow.com/questions/31523884/rxjava-group-emit-and-zip-sorted-chunks-with-a-common-property.

I've implemented them in [rxjava-extras](https://github.com/davidmoten/rxjava-extras) if anyone is curious. 

I'd like to get peoples opinions on whether our busting-at-the-seams codebase should get these methods or if they should be external libraries (managed by others). If the operators get used by many then I'd suggest they end up in rxjava because the oversight from the community is so valuable.
