### ISSUE TITLE
Passing a lambda with an infinite loop to Observable.create(...) causes a compiler error

### ISSUE THREAD

**Issue by breandan** [ReactiveX/RxJava#3025]
The following piece of code does not compile on RxJava 0.20.7 with javac 1.8.0_45.

```java
Observable.create(subscriber -> {
    while(true) {
        System.out.println("Hello.");
        //Some other stuff.
    }
});
```

Omitting `while(true)` or replacing it with an always-true expression (ie. `Math.random() < 1`) eliminates the error.

Related: https://youtrack.jetbrains.com/issue/IDEA-141580

**Comment by JakeWharton** [comment]
This is not a library problem per the bug you linked.

**Comment by JakeWharton** [comment]
Also RxJava 0.20 is a year old. The artifact coordinates moved a while back. See the README for the latest.

**Comment by breandan** [comment]
> Also RxJava 0.20 is a year old. The artifact coordinates moved a while back.

Ah, yes. That would explain why. Thanks Jake!
