### ISSUE TITLE
takeLast() javadoc suggestion

### ISSUE THREAD

**Issue by davidmoten** [ReactiveX/RxJava#3027]
@DavidMGross `takeLast` and `takeLastBuffer` methods are inconsistent in the javadoc about their behaviour when less is available than requested. When less is available than requested all are emitted but this behaviour is not clear in the javadoc of all of the variations. Should I leave this to you?

**Comment by DavidMGross** [comment]
You should feel free to change the javadocs as you find errors,
ambiguities, missing information, or as you change the behavior of methods
(e.g. to add backpressure support).  I've done a lot of work with these
javadocs as the tech writer guy, but philosophically I think the front-line
developers ought to consider it part of their responsibility to maintain
their accuracy.

On Wed, Jun 17, 2015 at 10:19 PM, Dave Moten <notifications@github.com>
wrote:

> @DavidMGross <https://github.com/DavidMGross> takeLast and takeLastBuffer
> methods are inconsistent in the javadoc about their behaviour when less is
> available than requested. When less is available than requested all are
> emitted but this behaviour is not clear in the javadoc of all of the
> variations. Should I leave this to you?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ReactiveX/RxJava/issues/3027>.
>



-- 
David M. Gross
PLP Consulting

**Comment by davidmoten** [comment]
no probs
