### ISSUE TITLE
NullPointerException at rx.exceptions.CompositeException.getListOfCauses(CompositeException.java:245)

### ISSUE THREAD

**Issue by sgonchar** [ReactiveX/RxJava#3046]
I use RxAndroid library in my project and I have next exception :

E/AndroidRuntime(27849): Error reporting crash
E/AndroidRuntime(27849): java.lang.NullPointerException
E/AndroidRuntime(27849): at rx.exceptions.CompositeException.getListOfCauses(CompositeException.java:245)
E/AndroidRuntime(27849): at rx.exceptions.CompositeException.getCause(CompositeException.java:100)
E/AndroidRuntime(27849): at android.util.Log.getStackTraceString(Log.java:454)
E/AndroidRuntime(27849): at android.util.Slog.e(Slog.java:151)
E/AndroidRuntime(27849): at com.android.internal.os.RuntimeInit$UncaughtHandler.uncaughtException(RuntimeInit.java:109)
E/AndroidRuntime(27849): at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:693)
E/AndroidRuntime(27849): at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:690)
E/AndroidRuntime(27849): at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:66)
E/AndroidRuntime(27849): at android.os.Handler.handleCallback(Handler.java:733)
E/AndroidRuntime(27849): at android.os.Handler.dispatchMessage(Handler.java:95)
E/AndroidRuntime(27849): at android.os.Looper.loop(Looper.java:146)
E/AndroidRuntime(27849): at android.app.ActivityThread.main(ActivityThread.java:5653)
E/AndroidRuntime(27849): at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime(27849): at java.lang.reflect.Method.invoke(Method.java:515)
E/AndroidRuntime(27849): at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1291)
E/AndroidRuntime(27849): at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1107)
E/AndroidRuntime(27849): at dalvik.system.NativeStart.main(Native Method)

Somebody know how can I fix it ?
Thank you

**Comment by akarnokd** [comment]
It appears you have a `null` exception added to a composite somewhere. What operators are you using. Do you call `onError(null)` somewhere by accident?

**Comment by sgonchar** [comment]
I try to get throwable.getMessage callback and have this null pointer.
I already find the reason. I make mistake at URL and try to connect to non-existent URL. I changed it and all is fine.
I think you need handle this null pointer in other way, because currently I can't normally find the reason of exception.
Thank you

**Comment by akarnokd** [comment]
Fix already delivered. Thank you for reporting.
