### ISSUE TITLE
Question: what rxjava uses to create documentation images

### ISSUE THREAD

**Issue by zhuker** [ReactiveX/RxJava#3051]
like this one
https://raw.github.com/wiki/ReactiveX/RxJava/images/rx-operators/create.png
i would like to document my code which uses rxjava with images like the above

**Comment by DavidMGross** [comment]
The application is called OmniGraffle, and the file that contains the image source files is rx-operators.graffle (https://raw.githubusercontent.com/wiki/ReactiveX/RxJava/images/rx-operators.graffle)

**Comment by zhuker** [comment]
thanks
