### ISSUE TITLE
window/buffer overload questions, incompatibility with Rx.NET?

### ISSUE THREAD

**Issue by wujek-srujek** [ReactiveX/RxJava#3053]
It seems, by reading the introtorx.com book and the docs (and testing out) that the buffer and window overloads which take an Observable windowCloseSelector might not be behaving as they do in .NET.

The original SO topic is here: http://stackoverflow.com/questions/30963993/rxjava-window-buffer-overload-questions-incompatibility-with-rx-net

**Comment by akarnokd** [comment]
This should be fixed in 1.0.13 RC.

**Comment by akarnokd** [comment]
Fixed in 1.0.14.
