### ISSUE TITLE
SafeSubscriber does not call `onCompleted` after `unsubscribe`, allows further calls to `onNext`

### ISSUE THREAD

**Issue by dlew** [ReactiveX/RxJava#3059]
[The documentation for `SafeSubscriber`](http://reactivex.io/RxJava/javadoc/rx/observers/SafeSubscriber.html) states:

> If `unsubscribe` is called, calls `onCompleted` and forbids any further `onNext` calls.

However, in practice, it appears that `SafeSubscriber` does neither of those.

------

The following code should call `onCompleted`:

```java
Subscription sub = Observable.interval(10, TimeUnit.MILLISECONDS)
  .subscribe(
    l -> System.out.println("Received: " + l),
    e -> System.out.println("Error: " + e),
    () -> System.out.println("Completed")
  );

sleep(50);
sub.unsubscribe();
```

However, the output is as follows:

```
Received: 0
Received: 1
Received: 2
Received: 3
Received: 4
```

------

The following code should not call `onNext` after unsubscription:

```java
Observable<Long> observable = Observable.create(subscriber -> {
  long n = 0;
  while (true) {
    sleep(10);
    subscriber.onNext(n++);
  }
});

Subscription sub = observable
  .subscribeOn(Schedulers.newThread())
  .subscribe(
    l -> System.out.println("Received: " + l),
    e -> System.out.println("Error: " + e),
    () -> System.out.println("Completed")
  );
sleep(50);
sub.unsubscribe();
System.out.println("Unsubscribed!");
```

However, this is the output:

```
Received: 0
Received: 1
Received: 2
Received: 3
Received: 4
Unsubscribed!
Received: 5
Received: 6
Received: 7
Received: 8
...
```

-----

It seems to me that one of three things is going on:

1. `SafeSubscriber` isn't as safe as it should be.
1. The documentation is out-of-date.
1. I'm missing something.

**Comment by davidmoten** [comment]
>If unsubscribe is called, calls onCompleted...

* `onCompleted` should only be called after all the `onNext` notifications have arrived so the behaviour described in the javadoc does not comply with the Observable contract. We should remove this. 

>and forbids any further onNext calls.

* if unsubscription occurs it is preferred that no more notifications be forwarded to the subscriber (though this is not mandated behaviour generally). `SafeSubscriber` attempts no such guarantees currently as you've noticed though it could do so by adding an unsubscribe action to the underlying subscriber that sets a volatile boolean  when called. That boolean could then be checked on each arrival to `SafeSubscriber` of a notification. I assume the addition of a volatile read on every emission could be sufficiently expensive at runtime to make this undesirable. I'm sure @akarnokd will have an opinion on this one for us.

**Comment by JakeWharton** [comment]
> I assume the addition of a volatile read on every emission could be sufficiently expensive at runtime to make this undesirable.

and 

> if unsubscription occurs it is preferred that no more notifications be forwarded to the subscriber 

seem to slightly contradict in that to accurately stop notifications one has to check `!s.isUnsubscribed()` before emitting which _is_ that very volatile read anyway.

I discovered this problem last night when `unsubscribe()` was being called from a thread different than subscribe and emission and in order to stop future emission I had to get back onto the original thread.
```java
Thing thing = //...
Observable<Object> o = Observable.create(s -> {
  checkUiThread();
  Thing.Listener listener = v -> s.onNext(v);
  s.add(Subscriptions.create(() -> {
    postUiThread(() -> thing.removeListener(listener));
  }));
  thing.addListener(listener);
});
```
When unsubscribe happens, we cannot detach the emitter without moving back to the original subscription thread. This runs synchronously if you are already on that thread, but sometimes it has to be queued and there might be an event already queued for processing.

Where I find this extremely problematic is when you have a `doOnUnsubscribe` action on the stream. This action will be fired yet you still might receive an `onNext`.

**Comment by davidmoten** [comment]
Hah, yes of course, just need to check `isUnsubscribed` on the underlying subscriber as you point out! 

No surprise to you I'm sure but `doOnUnsubscribe` will report the unsubscribe request on its way upstream to the source and there could still be inflight emissions. Another possibility is that sources and operators are not bound to honour unsubscribe by the Observable contract, it's best endeavours.

The catch with all this is that putting the `isUnsubscribed` check in `SafeSubscriber` doesn't help much  if our Observable looks like this:

```java
observable.doOnNext(System.out::println).subscribe(...);
```
In this case though `unsubscribe` was called and `SafeSubscriber` prevented the endpoint subscriber getting notifications after unsubscription we might still get more emissions fed to the `doOnNext`.

I suppose there are probably techniques for making your use case more responsive to unsubscription @JakeWharton and you are no doubt on top of them. Is there support you'd like to see in the API that would help you? What sort of reliance on `doOnUnsubscribe` do you have (you said it's extremely problematic)?

**Comment by JakeWharton** [comment]
Oops, I may have a been a bit too apocalyptic with my words. I have used subscribe/unsubscribe callbacks for holding state as a side-effect. This almost certainly would trigger an unexpected condition if I tear down/complete the side-effect state and then receive another event and assume I could act on it. But you're right, it makes total sense that the notifications are happening in two directions here.

Thankfully, in practice this has never been a problem. In all of these cases unsubscription has happened from the UI thread which allows everything to happen synchronously anyway. I only discovered the errant behavior (and its subsequent documentation problem) during a unit test which was operating on two threads.

I think all we're really after here is a documentation change to remove the guarantees it currently claims to offer. As to whether guarantees about `onNext` will be enforced on not, I'll leave that up to you all to decide based on the performance implications. I'm pretty sure that checking for unsubscription before emitting is a best practice for operators so I'm perfectly fine if it results only in a documentation change as well.

**Comment by JakeWharton** [comment]
Well, @dlew found the errant documentation and wrote the nice tests. I just assumed it was user error in my operator implementation!

**Comment by akarnokd** [comment]
The first example works as expected and the documentation is wrong.

The behavior of `SafeSubscriber` is somewhat questionable but the general expectation is that sources check for `isUnsubscribed` before calling `onNext`, therefore, `SafeSubscriber` doesn't duplicate such work.

**Comment by akarnokd** [comment]
Posted a PR that changes the javadoc in #3512.
