### ISSUE TITLE
toBlocking ignore all

### ISSUE THREAD

**Issue by davidmoten** [ReactiveX/RxJava#3063]
When I want to use `toBlocking` and I want to ignore results but wait for completion I will often do 

```java
observable.count().toBlocking().single();
```
This works but I'd like something concise for this common use case. We have a `forEach` method that takes an `Action1`. What about a `forEach` overload that takes no argument?

```java
observable.toBlocking().forEach();
```

or perhaps `.ignoreElements()`?

**Comment by akarnokd** [comment]
I've been thinking about this too and could use these new blocking methods:

  - `run()` or `subscribe()` run to completion or exception
  - `subscribe(Observer)`, `subscribe(Action1, Action1)` and `subscribe(Action1, Action1, Action0)` blocking callback style
  - `subscribe(Subscriber)` allow breaking out of the iteration and have the unsubscription properly propagate up.

**Comment by davidmoten** [comment]
Sounds good, may as well duplicate all the `subscribe()` overloads across to `BlockingObservable` that make sense. That symmetry would be nice.

**Comment by pkafel** [comment]
+1 for the topic. I have many use cases where I would love to use something like that !

**Comment by tommack** [comment]
I'll throw ``none()`` out there. Would be a void method that threw an Exception if any elements were output.

```
observable.ignoreElements().toBlocking().none();
```

**Comment by akarnokd** [comment]
See for the proposed methods in #3174.
