### ISSUE TITLE
OperatorGroupBy - redundant onStart implementation

### ISSUE THREAD

**Issue by davidmoten** [ReactiveX/RxJava#3067]
These lines

https://github.com/ReactiveX/RxJava/blob/1.x/src/main/java/rx/internal/operators/OperatorGroupBy.java#L262-L264

are redundant. I'm concerned that there is some intent behind placing these lines here that is not honoured.  @akarnokd looks like you put these lines here, what do you think?

The same goes for `OperatorDoOnUnbsubscribe`.

**Comment by akarnokd** [comment]
Yes, that start is unnecessary.

**Comment by KevinTCoughlin** [comment]
Related PR #3342.

**Comment by akarnokd** [comment]
Fix merged via #3342 and delivered in 1.0.15.
