### ISSUE TITLE
onErrorResumeNext may sometimes miss the onNext in it, if onError is after it

### ISSUE THREAD

**Issue by luiges90** [ReactiveX/RxJava#3068]
In particular, if I call both `onNext` before `onError` in the observable of `onErrorResumeNext`, sometimes `onNext` call is missed.

"sometimes" indicates there may be threading issues, and from my testing remove both `subscribeOn` and `observeOn` in the reproduction code (see below) seem to fix this issue. (However this is not an option for me because the observable is doing IO-bound work that shouldn't block the main thread)

Replacing `onError` with `onComplete` doesn't seem to have issue as I tested a few times, but threading issue are by nature elusive so it might actually have an issue too :confused: 

RxJava version: 1.0.12 (also happens on 1.0.0 which we are currently using)

Expected output:
```
onNext 1
onError inner
```

Actual output:
```
onError inner
```

Not always reproducible, but like half of the time.

Code to reproduce:
```
Observable.<String>error(new RuntimeException("inner"))
                .onErrorResumeNext(new Func1<Throwable, Observable<? extends String>>() {
                    @Override
                    public Observable<? extends String> call(final Throwable throwable) {
                        return Observable.create(new Observable.OnSubscribe<String>() {
                            @Override
                            public void call(Subscriber<? super String> subscriber) {
                                subscriber.onNext("1");
                                subscriber.onError(throwable);
                            }
                        });
                    }
                })
                .observeOn(Schedulers.newThread())
                .subscribeOn(Schedulers.newThread())
                .subscribe(new Subscriber<String>() {
                    @Override
                    public void onCompleted() {
                        System.out.println("onCompleted");
                    }

                    @Override
                    public void onError(Throwable e) {
                        System.out.println("onError: " + e.getMessage());
                    }

                    @Override
                    public void onNext(String s) {
                        System.out.println("onNext " + s);
                    }
                });
```

Do I do anything wrong or any bug on rxJava side?

**Comment by benjchristensen** [comment]
The `observeOn` operator allows `onError` to jump ahead of `onNext` if the `onNext` are still queued when the error is emitted. This is a unique behavior to `observeOn` since it schedules delivery asynchronously. You can see the history of this decision at https://github.com/ReactiveX/RxJava/issues/1680

**Comment by luiges90** [comment]
Ok it looks like I need another approach then...

**Comment by headinthebox** [comment]
Interesting side-effect of letting `onError` jump the queue BTW.

Wondering why you do `.observeOn(Schedulers.newThread()).subscribeOn(Schedulers.newThread())`, that is a whole lot of thread hopping going on.

**Comment by luiges90** [comment]
in fact that is testing code, in my production code it is actually `.subscribeOn(Schedulers.io()).observeOn(AndroidSchedulers.mainThread())`

Anyway I decided to use `runOnAiThread()` insider the subscriber and rid `observeOn`
