### ISSUE TITLE
Async Observable.from(future)

### ISSUE THREAD

**Issue by samhendley** [ReactiveX/RxJava#307]
I was surprised that Observable.from(future) doesn't return a truly async future. I wrote one for my own purposes and thought it might be useful as a core part of rxJava.

https://gist.github.com/samhendley/6030565

``` java

Observable<T> obs = Observable.future(future);

// would be converted to

// class level or static members probably
FutureWatcher futureWatcher = new FutureWatcher();
Executor callbackPool = new ThreadPoolExecutor(5);

Observable<T> obs = futureWatcher.watchFuture(future, callbackPool);
```

I imagine the most straightforward implementation would be something like `Observable.from(future, executor)`, a bit like the scheduleOn() method from Hystrix.

I would also suggest that you update the documentation on `Observable.from(future)` to reflect that the observable are effectively blocking, I had assumed otherwise and was very disappointed in the performance of my system as a whole when I integrated with a library that returned futures (hystrix in this case). A co-worker was asking some probing questions and it made me actually look at the implementation and once I integrated the FutureWatcher our performance was back to where I expected it to be.

**Comment by neozax** [comment]
Isn't this new `fromFuture(java.util.concurrent.Future<? extends T> future, Scheduler scheduler)` in 2.x still going to return a blocking Observable? Because if you trace the code path of this function, in `ObservableFromFuture` class, there's this line:

`v = ObjectHelper.requireNonNull(unit != null ? future.get(timeout, unit) : future.get(), "Future returned null");`

it still uses `future.get()`, which is a blocking call.

**Comment by JakeWharton** [comment]
Yes. You can use subscribeOn to control the thread on which it blocks.

**Comment by akarnokd** [comment]
That overload applies the `subscribeOn` and when subscribed to, the code blocks on that `Scheduler`. For example, using the `io()` scheduler, when you subscribe to the returned `Observable`, the `subscribe()` call returns promplty without blocking. Note also that there is no non-blocking way to listen to a `java.util.concurrent.Future`: we are limited to Java 6.
