### ISSUE TITLE
switchOnNext() can lose requests

### ISSUE THREAD

**Issue by davidmoten** [ReactiveX/RxJava#3073]
There is a race condition in `OperatorSwitch` that may cause requests to be lost:

1. `onNext` proceeds to just before [L137](https://github.com/ReactiveX/RxJava/blob/d32a1b0ea7ee455a23082cd1a7db80b3adef6d2b/src/main/java/rx/internal/operators/OperatorSwitch.java#L137) 
2. on a different thread `request` proceeds to just before [L112](https://github.com/ReactiveX/RxJava/blob/d32a1b0ea7ee455a23082cd1a7db80b3adef6d2b/src/main/java/rx/internal/operators/OperatorSwitch.java#L112)
3. `onNext` continues and exits method
4. `request` continues and requests from unsubscribed subscriber
5. At this point stream could stall because requests were lost 

Looks like a candidate for `ProducerArbiter` help. I'll work on a PR if no-one else has started on this issue yet (let me know if you have). There may be other race conditions as well that turn up which I'll document in the PR.

**Comment by akarnokd** [comment]
Fixed and released with 1.0.14.
