### ISSUE TITLE
Reference leak via SafeSubscriber.actual?

### ISSUE THREAD

**Issue by loganj** [ReactiveX/RxJava#3074]
Is there any reason for SafeSubscriber to retain `actual` after `unsubscribe()`? I'm seeing a reference leak through the actual subscriber, and it looks like it should probably be broken by dropping that reference.

**Comment by akarnokd** [comment]
If the actual leaks it means the Subscriber leaks because it is retained somewhere outside the library. Otherwise, it provides performance benefits and avoids null checks.

**Comment by loganj** [comment]
I _was_ holding a reference to the _Subscription_, but it had been unsubscribed. Nulling that reference allowed the Subscriber to be collected. I suppose it was naive to expect that unsubscribing a Subscription would release internal references, but there's no indication in the API how Subscription behaves with respect to references, or how a user should manage them to avoid leaks. It also appears to be inconsistent, unless I'm misreading (entirely possible): SubscriptionList and CompositeSubscription, for instance, do appear to release references to their member Subscriptions when unsubscribed.

**Comment by loganj** [comment]
For what it's worth, it looks like SubscriptionList got the same change I'm proposing in #1440, as a response to discussion in #1292.

**Comment by adi1133** [comment]
I also faced this undocumented behaviour, now I release my **Subscribtion** references or use a **CompositeSubscription**
This should be documented !

**Comment by akarnokd** [comment]
Improving the documentation is a good thing and I encourage you, @loganj  or @adi1133 to post a PR with your proposed changes.

**Comment by akarnokd** [comment]
Any move on this issue?

**Comment by adi1133** [comment]
Does this issue only involve SafeSubscriber ?
