### ISSUE TITLE
Slow performance of groupBy

### ISSUE THREAD

**Issue by krisskross** [ReactiveX/RxJava#3080]
Hi

Here's some silly code for testing the performance of groupBy. Not sure if i'm doing something wrong but the groupBy seems very slow ~ 10x in comparison to the plain case, and it gets worse as number of items go up. 

Is the code and performance figures correct and fair? Are there smarter ways to do this?

Cheers,
-Kristoffer

```java
  static int num = 100_000;
  static Observable<Integer>[] obs = new Observable[]{
    Observable.range(0, num),
    Observable.range(0, num),
    Observable.range(0, num)
  };

  public static void main(String[] args) {
    for (int i = 0; i < 100; i++) {
      long now = System.currentTimeMillis();
      plain();
      System.out.println("plain " + (System.currentTimeMillis() - now));
      now = System.currentTimeMillis();
      rx();
      System.out.println("rx " + (System.currentTimeMillis() - now));
    }
  }

  public static void plain() {
    HashMap<Integer, ArrayListWrapper> map = new HashMap<>();
    for (Observable<Integer> o : obs) {
      for (int number : o.toBlocking().toIterable()) {
        ArrayListWrapper list = map.get(number);
        if (list == null) {
          list = new ArrayListWrapper(number);
          map.put(number, list);
        }
        list.add(number);
      }
    }
    AtomicInteger count = new AtomicInteger();
    map.entrySet().stream().forEach(e -> count.incrementAndGet());
  }


  public static void rx() {
    Observable<ArrayListWrapper> result = Observable.from(new Integer[]{0, 1, 2})
      .flatMap(i -> obs[i])
      .groupBy(i -> new ArrayListWrapper(i))
      .flatMap(group ->
        group.collect(() -> group.getKey(), (list, number) -> list.add(number)));
    AtomicInteger count = new AtomicInteger();
    result.toBlocking().forEach(l -> count.incrementAndGet());
  }
```

**Comment by akarnokd** [comment]
Why do you group by the ArrayListWrapper?

**Comment by krisskross** [comment]
A way to emulate HashMap<Integer, List> and be able to add items to each of them in the collect().

**Comment by krisskross** [comment]
Should be HashMap[Integer, List].

**Comment by krisskross** [comment]
The result of each is...

[0, 0, 0]
[1, 1, 1]
[2, 2, 2]
[3, 3, 3]
.
... and so on.

**Comment by akarnokd** [comment]
What is the `hashCode()` of `ArrayListWrapper`. If it isn't constant then it can play havoc in `groupBy`.

**Comment by akarnokd** [comment]
In addition, I'm not sure what you try to accomplish, but the `plain()` is very similar to the behavior of `toMultimap()`.

**Comment by krisskross** [comment]
The hashCode of ArrayListWrapper is the integer passed into the constructor. 

Yes, multimap works for what i'm trying to accomplish. And it's as fast as you'd expect. 

Still, i'm not sure what's going on with the groupBy?

**Comment by akarnokd** [comment]
Could you create a fully runnable gist for your case?

**Comment by krisskross** [comment]
https://gist.github.com/krisskross/33567f6532eaa4aa3a0c

**Comment by krisskross** [comment]
If I pick a bigger 'num' like 500_000, the plain case takes about 3.5 sec and the groupBy doesn't complete at all. Maybe a deadlock?

Thread dump looks like threads are idle and main is waiting for the blocking operation.

**Comment by akarnokd** [comment]
I think I know what's happening: the (horizontally unbounded) flatMap is accumulating the open groups which causes O(n * n) maintenance cost and O(n) cost per a new group since flatMap needs to loop over n groups to see if they have any new item for the downstream. So in total grouping by and merging n values costs O(n * n) in total steps.

**Comment by krisskross** [comment]
Ah, that makes sense. But not immediately obvious :-)

Ok, so toMultimap is fine but not that efficient since it must wait for all observables to finish. But, in my use case, the source observables are actually sorted and contain equally many items so I think zip() would be the correct operation here.

**Comment by asereda** [comment]
Hello,

Any way to avoid `O(n * n)` cost for grouping and merging  operation (in 1.x) ? Our use-case is market data where one has to throttle events (market ticks) per symbol (key) but not of entire stream. Think about UI grid where only latest event (per symbol) is important and not more frequently than every X seconds.

So far, we have came up with:
```java
// flat map
return observable.groupBy(bySymbol()).flatMap(obs -> obs.throttleLast(100, TimeUnit.MILLISECONDS));

========= 
// publish subject
PublishSubject<T> subject = PublishSubject.create();
observable.groupBy(bySymbol()).subscribe( obs ->  obs.throttleLast(100, TimeUnit.MILLISECONDS).subscribe(subject));

return subject;
```
Elegant but, unfortunately, not very performant.

**Comment by akarnokd** [comment]
@asereda

How many symbols do you have? The throttleLast's 100ms is likely way bigger than, the time to scan 1000 symbols.

The `PublishSubject` version violates the `Observer` contract; you have to use `PublishSubject.<SymbolType>create().toSerialized()`.

Your case may be best solved with a custom operator that performs the per-symbol timed latest operation without splitting into sub-Observables.

**Comment by asereda** [comment]
@akarnokd 
We have about 1M symbols (products). So quadratic time becomes noticeable.
At thousands (~500-1k symbols)  the difference between RX (`O(n * n)`) and handmade (`O(n)`) throttler  is negligible.

**Comment by akarnokd** [comment]
Wow, that's a lot of flows and delayed/scheduled emissions. If you have 1M unique groups, the periodic (active) sampling of those is going to be expensive no matter what.

**Comment by jamesgorman2** [comment]
@asereda 
can you afford to store a copy of the last seen values? If you can, you could use a scan/throttle to keep latest state. You'll have to optimise the memory management though.

```
return observable.scan(
    initialState(),
    (lastSeenState, nextEvent) -> lastSeenState.updateWith(nextEvent)
  )
  . throttleLast(...);
```

EDIT: helps if I get the right operator!

**Comment by asereda** [comment]
@jamesgorman2 , Thanks will try it out.
What exactly do you mean by 
> optimise the memory management

**Comment by jamesgorman2** [comment]
Mostly just making sure that if you're going down the immutable state route you're data state objects aren't eating up your GC time, and if it's mutable you're happy with how you're managing the race between state updates and reads.

**Comment by asereda** [comment]
So I wrote a little benchmark using [JMH](http://openjdk.java.net/projects/code-tools/jmh/). Comparisons are below :
```
# Run complete. Total time: 00:08:36

Benchmark                  (buckets)        (factory)  (window)   Mode  Cnt  Score   Error   Units
ThrottleBenchmark.consume    1048576         EXECUTOR       100  thrpt   50  0.655 ± 0.067  ops/us
ThrottleBenchmark.consume    1048576   RXJAVA_FLATMAP       100  thrpt   50  0.001 ± 0.001  ops/us
ThrottleBenchmark.consume    1048576   RXJAVA_SUBJECT       100  thrpt   50  0.048 ± 0.009  ops/us
ThrottleBenchmark.consume    1048576  RXJAVA_OPERATOR       100  thrpt   50  0.572 ± 0.027  ops/us
```
`EXECUTOR` benchmark is home-made solution using JDK [ScheduledExecutorService](https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/ScheduledExecutorService.html).

`OPERATOR` and `EXECUTOR` implementations seem comparable within error margin. 
@akarnokd Do you find these results plausible ?

**Comment by akarnokd** [comment]
Could you post the benchmark code?

**Comment by asereda** [comment]
Sorry for late response.
Please take a look here: [rxjava-throttle-bench](https://github.com/asereda/rxjava-throttle-bench)

**Comment by akarnokd** [comment]
Seeing the code the results are plausible. With the operator version, you have only one timed task whereas the flatMap version has as many timed tasks as there are groups.
