### ISSUE TITLE
TestObserver should use compareTo with types that use Comparable

### ISSUE THREAD

**Issue by chrulri** [ReactiveX/RxJava#3094]
I currently use TestSubscriber in my JUnit tests. This works great as long as I don't assert on values of types that rely on Comparable rather than on equals.

In the current version (1.0.12) the class TestObserver (used by TestSubscriber) uses "equals" in its method "[assertReceivedOnNext(List&lt;T&gt;)][1]" to check if the value(s) match the expectation(s). This is unfortunate if you try to verify BigDecimal values for example as the following code snippet should demonstrate:
```java
BigDecimal a = new BigDecimal("5.0");
BigDecimal b = new BigDecimal("5.00");
System.out.println(a.equals(b));
System.out.println(a.compareTo(b) == 0);
```

This snippet results in:
```plain
false
true
```

IMHO TestObserver should use compareTo if T is of a type that implements Comparable<T>.

For my current use cases I simply extended TestSubscriber and added additional assert methods to deal with this issue.

[1]: https://github.com/ReactiveX/RxJava/blob/1.x/src/main/java/rx/observers/TestObserver.java#L125

**Comment by davidmoten** [comment]
This is problematic because `a.compareTo(b)==0` may occur when `a` is nothing like `b`. In your case `a.compareTo(b)` implies the content of `a` equals the content of `b` but I can construct a class that happens to implement `Comparable` that I definitely would not want `TestSubscriber` to identify as being equal:

```java
public class Person implements Comparable<String> {
    String name;

    @Override
    public int compareTo(String o) {
        // order just by first letter of name
        return Character.compare(name.charAt(0), p.charAt(0));
    }
}
```

**Comment by chrulri** [comment]
@davidmoten what would your solution for using TestObserver/TestSubscriber with types like BigDecimal be? Maybe another set of assertValue methods?

I have to admit, that BigDecimal is really one special use case:
> Virtually all Java core classes that implement Comparable have natural orderings that are consistent with equals. One exception is java.math.BigDecimal, whose natural ordering equates BigDecimal objects with equal values and different precisions (such as 4.0 and 4.00).
> - https://docs.oracle.com/javase/8/docs/api/java/lang/Comparable.html

**Comment by davidmoten** [comment]
What you could do is `.map(d -> roundToPrecision(d))` and then use `TestSubscriber.assertValues` method against double values to desired precision:

```java
Observable<BigDecimal> o = ...
TestSubscriber<Double> ts = TestSubscriber.create();
o.map(d -> roundToPrecision(d)).subscribe(ts);
ts.assertValues(1.0, 2.1, 3.2);

public static double roundToPrecision(BigDecimal d) {
    //trim to say 3 decimal places
    return Math.round(d * 1000) / 1000.0; 
}
```

Would this work for you?

**Comment by chrulri** [comment]
Yes that works as long as precision and rounding is not an issue in test cases. I'd suggest the following snippet in that case for such simple test samples:
```java
o.map(BigDecimal::doubleValue).subscribe(ts);
```

side note: ```d * 1000``` does not work as BigDecimal does not support standard arithmetic operators.

**Comment by davidmoten** [comment]
Oh yeah that should be d.double value() * 1000.
