### ISSUE TITLE
SubscriptionList and CompositeSubscription duplicated classes

### ISSUE THREAD

**Issue by adi1133** [ReactiveX/RxJava#3096]
https://github.com/ReactiveX/RxJava/blob/1.x/src/main/java/rx/internal/util/SubscriptionList.java
https://github.com/ReactiveX/RxJava/blob/1.x/src/main/java/rx/subscriptions/CompositeSubscription.java

I see that the two classes share the same code. Which one should I use ?

**Comment by JakeWharton** [comment]
`SubscriptionList` is an internal API. Use the other one.

**Comment by akarnokd** [comment]
> I see that the two classes share the same code

The structure is very similar but the backing data structure is not.

**Comment by akarnokd** [comment]
I think this question has been answered. Closing.
