### ISSUE TITLE
materialize() and dematerialize() backpressure support

### ISSUE THREAD

**Issue by davidmoten** [ReactiveX/RxJava#3098]
Just a note that I'm working on PRs for backpressure support for `materialize()` and `dematerialize()`. Let me know if you are already working on this.

The problems are these
* `materialize` can emit one more than requested (the completion or  error notification)
* `dematerialize` on a source of N items should emit N-1 items but requires a request of N to also report the completion event

**Comment by akarnokd** [comment]
Solved via #3103
