### ISSUE TITLE
Enforce min code coverage level in the project

### ISSUE THREAD

**Issue by artem-zinnatullin** [ReactiveX/RxJava#3100]
Recently @davidmoten submitted PR with code coverage tool Jacoco #3089.

I'd like to submit another PR on top of his PR (after merge of #3089) **to enforce minimal code coverage level in RxJava** and **fail builds on CI** if level of code coverage will be smaller than desired value.

You can take a look at current level of code coverage via running `./gradlew clean build jacocoTestReport` on PR #3089, unfortunately, I found completely untested branches of code and even fully untested classes.

Some screenshots:

**Root**:
<img width="1041" alt="screen shot 2015-07-23 at 15 28 40" src="https://cloud.githubusercontent.com/assets/967132/8850288/8fcfa020-314f-11e5-8b8e-6dd5c3f6b7a5.png">

**rx.internal.operators**:
<img width="1372" alt="screen shot 2015-07-23 at 15 29 17" src="https://cloud.githubusercontent.com/assets/967132/8850292/9ec21298-314f-11e5-8987-121d731ff606.png">

I'd set some min level of code coverage for the whole project in the initial PR, for example — 60% and maybe add some tests, then we can add more and more tests and increase min coverage level.

I hope you'll find this useful for new PRs and for finding old bugs.

I think it's possible to have 100% coverage in RxJava, that would be awesome.

**Comment by akarnokd** [comment]
The tool has some shortcomings, for example, marking a utility class' private constructor as untested. There are a few dozen trivial classes and many methods with behavior not even covered by contracts. Other places are subject to races and are difficult to establish the required interleaving in short-timed unit tests.

I'd love to see the coverage numbers go up but we have to set a limit and not flood the project with 1000 more tests.

**Comment by artem-zinnatullin** [comment]
> for example, marking a utility class' private constructor as untested. 

Yep, but I've found it's okay and now I have tests which assert that required constructors are `private` (via reflection) and now I am sure that nobody will break this contract (though I try to review PRs carefully, I can miss something because everybody makes mistakes).

As addition I even test `equals()`, `hashCode()` and `toString()` for value classes and it's great!

> There are a few dozen trivial classes and many methods with behavior not even covered by contracts. 

Such places are usually "bug holes", code coverage will found them all and force us to test them.

> Other places are subject to races and are difficult to establish the required interleaving in short-timed unit tests.

I understand this, we can make exclusions for such classes in build config and keep other code tested as well. 

@akarnokd let's try it? Testier, Better, Stronger :shipit:

**Comment by akarnokd** [comment]
We have an overall 80% coverage as of now in 1.x. I'm not too keen on going 100% (which is impossible due to how switch-case of enums are checked anyway).

Btw, increasing the coverage number can become quite addictive, so I'd say reserve it for times when you feel low and need the feel of statistics increase :)

I'm closing this for now. If anybody wishes to impove the coverage in any version, PRs are welcome.

**Comment by artem-zinnatullin** [comment]
I'll post a PR with min coverage threshold for 1.x to fail PRs that significantly decrease coverage, ok?

**Comment by akarnokd** [comment]
Sure.

**Comment by artem-zinnatullin** [comment]
Short update here: codecov doesn't pick config file in my fork for some reason, talking to their support.
