### ISSUE TITLE
SubscriptionRandomList - can we remove?

### ISSUE THREAD

**Issue by davidmoten** [ReactiveX/RxJava#3105]
The class `rx.internal.util.SubscriptionRandomList` is not used and the `forEach` method has a bug where [line 116](https://github.com/ReactiveX/RxJava/blob/1.x/src/main/java/rx/internal/util/SubscriptionRandomList.java#L116) will throw a NPE. Can we chuck this class?

**Comment by akarnokd** [comment]
Fine with me.

**Comment by akarnokd** [comment]
I can't remember, did you post a PR for this or not. Can the issue be closed?

**Comment by akarnokd** [comment]
I've posted #3511 for this.
