### ISSUE TITLE
Add SafeSubscriber constructor that takes an Observer

### ISSUE THREAD

**Issue by yogurtearl** [ReactiveX/RxJava#3114]
The "actual" field inside SafeSubscriber could be an Observer ( you only call Observer methods on actual ).
Then you could add a constructor that takes an Observer.

This way you could avoid the wrapper object in 

```
    public final Subscription subscribe(final Observer<? super T> observer) {
```

Avoiding the wrapper object would shorten Thread stacks and reduce allocations.

**Comment by akarnokd** [comment]
SafeSubscriber has to compose the backpressure and unsubscribtion through so it can't just operate an `Observer`.
