### ISSUE TITLE
NoSuchMethodError + delaySubscription() causes BlockingObservable hang forever

### ISSUE THREAD

**Issue by gdela** [ReactiveX/RxJava#3122]
Recently I stumbled upon issue, where `.toBlocking().single()` hanged forever. After painful debugging I traced it down to issue during our build/deploy pipeline which resulted in `NoSuchMethodError` thrown from one of the libraries. This error was swallowed completely by RxJava, and the end result was a hanging thread.

Here is a minimal test case to reproduce the issue:

    Object result = Observable
        .create(subscriber -> {
            subscriber.onNext("item 1");
            if (true) throw new NoSuchMethodError();
            subscriber.onCompleted();
        })
        .delaySubscription(() -> Observable.just("delay"))
        .toBlocking()
        .single();
    System.out.println(result);

This will hang like that:

    "main" #1 prio=5 os_prio=0 tid=0x000000000217e000 nid=0x1d80 waiting on condition [0x000000000207e000]
    java.lang.Thread.State: WAITING (parking)
        at sun.misc.Unsafe.park(Native Method)
        ...
        at java.util.concurrent.CountDownLatch.await(CountDownLatch.java:231)
        at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:461)
        at rx.observables.BlockingObservable.single(BlockingObservable.java:341)
        at Sandbox.main(Sandbox.java:14)

Of course I've fixed it by fixing our build/deploy pipeline, but I'm reporting it because the swallowed exception makes such issues really hard to debug. If the RxJava could somehow report it and/or not hang, it would be nice.

**Comment by akarnokd** [comment]
The `lift` operator doesn't use `Exceptions.throwIfFatal` but only checks for `OnErrorNotImplementedException` and tries to send the error back downstream which is dropped because the take inside the `delaySubscription` operator is already completed at that point. @davidmoten, would you like to locate such cases in the codebase?

**Comment by akarnokd** [comment]
This should be fixed and if not already, released with the next version.
