### ISSUE TITLE
Subscriber onErrror not called if exception is null

### ISSUE THREAD

**Issue by vandzi** [ReactiveX/RxJava#3125]
rxjava version 1.0.13

Subscriber onErrror not called if exception passed to onError is null.

 @Override
public void onError(Throwable e) {
           //this is method in subscriber
}

If this is called onError is not called
 subscriber.onError(null); 
if works if
 subscriber.onError(new Exception());

**Comment by akarnokd** [comment]
In what context does this happen?

**Comment by vandzi** [comment]
I have observable:
Observable.create(new Observable.OnSubscribe<ArrayList<String>>() {

            @Override
            public void call(Subscriber<? super ArrayList<String>> subscriber) {
                 ArrayList<String> result = new RestApi().getFromUrl("someurl");
                 if (result != null) {
                    subscriber.onNext(result);
                    subscriber.onCompleted();
                } else {
                    subscriber.onError(null); //this doesn't work
                  //  subscriber.onError(new Exception());//this works
                }
            }


 Subscriber<ArrayList<String>> subscriber = new Subscriber<ArrayList<String>>() {
            @Override
            public void onCompleted() {
              
            }

            @Override
            public void onError(Throwable e) {
             //this is not called when  subscriber.onError(null);
            }

            @Override
            public void onNext(ArrayList<String> result) {
            }
        };

**Comment by akarnokd** [comment]
Your example works for me if I put `System.out.println(e);` into the onError method and prints `null`.

**Comment by artem-zinnatullin** [comment]
@akarnokd I've found that `TestSubscriber.assertError()` does not allow to use `null` as error because it uses `error.equals(...)` which throws `NullPointerException` if we pass `null` as error, so I made PR for that and also added test which asserts that we can pass `null` as error to the subscriber.

See PR #3126.

@vandzi I think you have some problem in your code, try to remove anything but `subscriber.onError(null)` and check that subscriber receives in in `onError()`.

**Comment by benjchristensen** [comment]
It is invalid to call `onError(null)`. Similar to how "throw null" is invalid.

**Comment by vandzi** [comment]
If onError(null) is invalid, it will be good to throw exception if null is passed as parameter. This way you will not figure out there is problem until you realise that callback is not called.

**Comment by akarnokd** [comment]
Whenever you want to throw or send `null` throw or send `new NullPointerException()` instead.
