### ISSUE TITLE
.groupBy(…).toSortedList(…) never completes

### ISSUE THREAD

**Issue by dallasgutauckis** [ReactiveX/RxJava#3127]
**Tested with** RxJava 1.0.13

It would appear that a grouped stream of items completes, a stream into a sorted list completes, but a grouped, then sorted stream does not complete.

**Demonstrative code**

In the following example, "Done with first\nDone with second" is printed to console, but the program continues to run without end, waiting for the third stream to complete.

```java
final Func1<Integer, Boolean> halfsies = new Func1<Integer, Boolean>() {
    @Override
    public Boolean call(Integer integer) {
        return integer >= 2;
    }
};

final GroupedObservable<Boolean, Integer> first1 = Observable.just(0, 1, 2, 3)
        .groupBy(halfsies)
        .toBlocking()
        .first();

assertNotNull(first1);

System.out.println("Done with first");

final List<Integer> first2 = Observable.just(0, 1, 2, 3)
        .toSortedList()
        .toBlocking()
        .first();

assertNotNull(first2);

System.out.println("Done with second");

final List<GroupedObservable<Boolean, Integer>> first3 = Observable.just(0, 1, 2, 3)
        .groupBy(halfsies)
        .toSortedList()
        .toBlocking()
        .first();

assertNotNull(first3);

System.out.println("Done with third");
```

**Comment by benjchristensen** [comment]
A GroupedObservable must be subscribed to. The outer Observable will not complete until all inner children (the GroupedObservables) are completed.

**Comment by dallasgutauckis** [comment]
I thought this might have something to do with that note. Thanks.
