### ISSUE TITLE
Concat / MergeWithDelay errors jump the queue when switching threads

### ISSUE THREAD

**Issue by pterhx** [ReactiveX/RxJava#3131]
Hi! I'm pretty new to RxJava, so I might be misunderstanding things.

So this works as expected:

        TestSubscriber<String> testSubscriber = new TestSubscriber<>();
        Observable.concat(
                Observable.just("A")
                        .doOnNext(str -> str.length()),
                Observable.error(new NullPointerException())
        ).subscribeOn(Schedulers.io())
                .observeOn(Schedulers.immediate())
                .subscribe(testSubscriber);
        testSubscriber.assertValues("A");
        testSubscriber.assertError(NullPointerException.class);

But when I `subscribeOn(Schedulers.io())` and `observeOn(AndroidSchedulers.mainThread())` (not this test specifically, but on a device), the error jumps the queue, and I'll never receive "A". Is this supposed to happen? 

Note that the `doOnNext` does get called. It only jumps the queue in the Subscriber. Also, when I put breakpoints to debug, sometimes the error would not jump the queue, so I suspect it's a race condition?

**Comment by akarnokd** [comment]
`observeOn` when run with a truly async scheduler will make sure the error reaches the downstream even if there are other values queued up. `immediate()` is not a real scheduler and keeps everything in sequence.

**Comment by akarnokd** [comment]
There are plans/preview implementation for 2.x to allow specifying error delay behavior on more kinds of operators, not just merge/flatMap. I don't really see this feature being added to 1.x in a short timeframe due to API concerns.
