### ISSUE TITLE
.dematerialize() backpressure

### ISSUE THREAD

**Issue by davidmoten** [ReactiveX/RxJava#3136]
Follow on from #3098 

At the moment in theory `.dematerialize()` supports backpressure but it does so with what I suspect is an undesirable effect.

Consider the observable `Observable.just(onNext(1), onNext(2), completed()).dematerialize()`

If I request 2 from this observable then I will receive 1, 2 as emissions but will not receive the `completed` notification till I request one more.

I lean towards changing `dematerialize` so that in the case above the `completed` notification arrives with the 1, and 2 on a request of 2. The operator would need to buffer one emission until termination.

Are people happy for me to submit a PR with this change?

**Comment by davidmoten** [comment]
Notice also that because of this behaviour of existing `dematerialize` the following operations which I would hope to be a no-op is not:

`observable.materialize().dematerialize()`

**Comment by akarnokd** [comment]
If you introduce queueing, it will penalize all events. Most consumers will keep requesting more so the final completion value should't be that far behind.

**Comment by davidmoten** [comment]
Yep that's true.  I'm happy not to change it. I'll leave the issue open for a week in case anyone wants to have a say and then close.
