### ISSUE TITLE
Fusing filter() with an emission/drain loop

### ISSUE THREAD

**Issue by akarnokd** [ReactiveX/RxJava#3139]
I've been experimenting with operator fusion (for my future work chapter in my dissertation) and it is simple to inline a filter function into the emission/drain loop so that the overhead of `request(1)` for a skipped value can be avoided/amortized, giving some interesting throughput improvements. 

Here are some benchmark (i7 4770K, Windows 7 x64, Java 8u51, JMH 1.10.3) results that compare an RxJava from().filter() with an absolute minimalist Reactive-Streams implementation of the two operators + fusing capability:

```
Benchmark                (times)   Mode  Cnt         Score        Error  Units
FilterPerf.filter              1  thrpt   15  24873462,666 ? 419852,680  ops/s
FilterPerf.filter           1000  thrpt   15    723886,848 ?   2070,738  ops/s
FilterPerf.filter        1000000  thrpt   15       661,785 ?     23,987  ops/s
FilterPerf.filter3             1  thrpt   15  22287395,076 ?  62387,334  ops/s
FilterPerf.filter3          1000  thrpt   15    216723,981 ?    480,625  ops/s
FilterPerf.filter3       1000000  thrpt   15       217,875 ?      0,464  ops/s
FilterPerf.filterNoFuse        1  thrpt   15  21124310,001 ? 215214,806  ops/s
FilterPerf.filterNoFuse     1000  thrpt   15    217239,919 ?    671,578  ops/s
FilterPerf.filterNoFuse  1000000  thrpt   15       211,587 ?      3,689  ops/s
FilterPerf.rxFilter            1  thrpt   15   3775438,637 ?  44175,577  ops/s
FilterPerf.rxFilter         1000  thrpt   15    159261,153 ?    986,562  ops/s
FilterPerf.rxFilter      1000000  thrpt   15       163,976 ?      1,132  ops/s
FilterPerf.rxFilter3           1  thrpt   15   2906599,609 ?  17758,800  ops/s
FilterPerf.rxFilter3        1000  thrpt   15     76846,788 ?    742,776  ops/s
FilterPerf.rxFilter3     1000000  thrpt   15        78,284 ?      0,997  ops/s
```

Observations:
  - RxJava has quite the overhead of creating a sort lived observable sequence observable sequence.
  - RxJava's `Func1<T, Boolean>` has higher overhead than a primitive boolean returning predicate from Java 8  (+33% throughput).
  - Fusing a filter into an emission loop can decrease the overhead drastically. Fusing 3 filters has the roughly the same throughput as having 1 unfused filter.

I personally don't often use `filter()` so I don't know if there is some typical chain of operators involving filter that could be optimized this way. Even if `filter()` is not fused into `from()`, combining subsequent filter functions can reduce the allocation cost of a chain (similar fusing is possible with `map()`).

Thoughts?

**Comment by davidmoten** [comment]
Looks great. I've been meaning to put through optimizations with empty for a while (not inlining of course just straightforward collapsing of composed operators).

A common pattern for me is `create(AbstractOnSubscribe).map().filter()...` so I'd like to see `map` and `filter` fusion.

**Comment by stealthcode** [comment]
Sounds promising. I'm certainly interested in seeing more about this.

**Comment by akarnokd** [comment]
Operator-fusion, if it ever happens, will take care of this in 2.x.
