### ISSUE TITLE
OnSubscribeTimerPeriodically ignores worker-returned subscription

### ISSUE THREAD

**Issue by JakeWharton** [ReactiveX/RxJava#3140]
In diagnosing an [RxAndroid bug][1] in our `HandlerScheduler`, I noticed that `OnSubscribeTimerPeriodically` calls `worker.schedulePeriodically` and ignores its returned `Subscription`. The code inside `schedulePeriodically` which is scheduled uses the unsubscription check on this instance to determine whether to run and re-schedule itself.

_Every_ caller of this method in RxJava ignores the return type. I am unable to determine if this is in error or not, but it looked to be due to the allocation and deliberate checking. If it in fact is not erroneous, removing the allocation and check should give a nice little 0.001% speedup on periodic actions!

I believe this does not manifest itself as a behavior error in RxJava's schedulers because they also check the unsubscription state of the worker itself. I did not verify this, though, as I stopped digging here.

 [1]: https://github.com/ReactiveX/RxAndroid/issues/214

**Comment by akarnokd** [comment]
RxJava schedulers track all the submitted actions and `worker.unsubscribe()` will cancel all pending tasks. Therefore, therefore, if there is no particular need to cancel individual task in an operator, we just add the worker to the Subscriber and it will clean up.

I'll check your former and patched scheduler to see what's wrong.
