### ISSUE TITLE
'lift(final Operator<? extends R, ? super T>)' has private access in 'rx.Single'

### ISSUE THREAD

**Issue by passsy** [ReactiveX/RxJava#3161]
I was expecting `Single#lift()` to be part of the public API like `Observable#lift()`. Is there a reason for this restriction?

`Single#compose()` is public, too (and links to `#lift()` in the docs). I guess the private access is just a bug.

https://github.com/ReactiveX/RxJava/blob/1.x/src/main/java/rx/Single.java#L176

My workaround:

```
Single.just("value")
        .toObservable()
        .lift(myOperator)
        .toSingle();
```

**Comment by akarnokd** [comment]
Single is in experimental phase, its API is not stable and there wasn't enough confidence to open up many of the methods, including lift.

**Comment by akarnokd** [comment]
I think the time has come to expose `Single.lift()`. PRs welcome.
