### ISSUE TITLE
Using buffer with concatMap always eventually hangs JVM?

### ISSUE THREAD

**Issue by clemper** [ReactiveX/RxJava#3162]
Hi,

I have what seems like fairly straight forwarded pipeline using buffer and concatMap which always eventually hangs the JVM.  I am using the Spring XD rxjava integration: https://github.com/spring-projects/spring-xd/blob/master/spring-xd-rxjava/src/main/java/org/springframework/xd/rxjava/SubjectMessageHandler.java

My processor implementation is as follows:

```java
    @Override
    public Observable<Message<?>> process(final Observable<Message<?>> input) {
        return input.buffer(maxBatchIntervalSeconds, SECONDS, maxBatchSize)
                .onBackpressureDrop(new Action1<List<Message<?>>>() {
                    @Override
                    public void call(List<Message<?>> buffer) {
                        LOGGER.warn("Dropping buffer");
                    }
                }).concatMap(new Func1<List<Message<?>>, Observable<Message<?>>>() {
                    @Override
                    public Observable<Message<?>> call(List<Message<?>> buffer) {
                        return distinct(buffer);
                    }
                });
    }

    /**
     * @return the distinct messages in the buffer as an Observable
     */
    private Observable<Message<?>> distinct(final List<Message<?>> buffer) {
        return Observable.create(new Observable.OnSubscribe<Message<?>>() {
            @Override
            public void call(Subscriber<? super Message<?>> observer) {
                if (!observer.isUnsubscribed()) {
                    final Set<Object> distincts = new HashSet<>(initalCapacity);
                    for (Message<?> message : buffer) {
                        if (distincts.add(getKey(message))) {
                            observer.onNext(message);
                        }
                    }
                    observer.onCompleted();
                }
            }
        });
    }
```

I have also tried using the built-in distinct operator with the exact same result as follows:

```java
    @Override
    public Observable<Message<?>> process(final Observable<Message<?>> input) {
        return input.buffer(maxBatchIntervalSeconds, SECONDS, maxBatchSize)
                .onBackpressureDrop(new Action1<List<Message<?>>>() {
                    @Override
                    public void call(List<Message<?>> buffer) {
                        LOGGER.warn("Dropping buffer");
                    }
                }).concatMap(new Func1<List<Message<?>>, Observable<Message<?>>>() {
                    @Override
                    public Observable<Message<?>> call(List<Message<?>> buffer) {
                        return Observable.from(buffer).distinct(keySelector);
                    }
                });
    }
```
The getKey(...) function (also called by the keySelector in the second example) evaluates a Spring Expression Language expression against the Message.  It seems very unlikely to me that this is part of the problem as the entire Spring XD framework does this repeatedly across the entire application without issue or similar hanging.

The maxBatchSize is 65536 and maxBatchIntervalSeconds is 5 minutes.  The buffer is always filled within 5 minutes.

The input stream throughput is approximately 6000 events per seconds.  This runs without issue for 2 - 3 days and then eventually hangs the JVM.  I do not get any stack traces or OOME; the VM just becomes unresponsive and has to be killed.  

I see the same behavior on Ubuntu 14.04.2 or Mac OS X 10.10.4.  I also see the same behavior running my processor in a unit test independent of Spring XD.  

The java version is:

```
java version "1.7.0_72"
Java(TM) SE Runtime Environment (build 1.7.0_72-b14)
Java HotSpot(TM) 64-Bit Server VM (build 24.72-b04, mixed mode)
```

I am new to rxjava and have no idea how to debug this.  Any help would be greatly appreciated.

Thanks.

**Comment by clemper** [comment]
Forgot the rxjava version: 1.0.13

**Comment by akarnokd** [comment]
Does it max out the CPU when it hangs?

**Comment by clemper** [comment]
I was not sure of the answer to this so tried to reproduce it with my unit test.  I either got lucky or it is easier to reproduce than I thought.  It looks like the answer is yes it does max out the CPU.  I also got the following exception:

```
Exception in thread "RxNewThreadScheduler-1" Exception in thread "RMI TCP Connection(idle)" Exception in thread "RMI TCP Connection(idle)" java.lang.OutOfMemoryError: GC overhead limit exceeded
java.lang.IllegalStateException: Fatal Exception thrown on Scheduler.Worker thread.
	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:62)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.OutOfMemoryError: GC overhead limit exceeded
java.lang.OutOfMemoryError: GC overhead limit exceeded
```

So apparently I was mistaken regarding my previous comment about not getting any OOME.  

Here's my unit test:

```java
public class DistinctBatchProcessorTest {
  
    @Test
    public void testDistinctBatchLongRunning() {
        DistinctBatchProcessor processor = new DistinctBatchProcessor("payload.toString()", 3600, 2000000);
        Observable<Message<?>> result = processor.process(infiniteStream());
        result.toBlocking().forEach(new Action1<Message<?>>() {
            @Override
            public void call(Message<?> message) {
                System.out.println(message);
            }
        });
    }

    private static Observable<Message<?>> infiniteStream() {
        return Observable.create(new Observable.OnSubscribe<Message<?>>() {
            @Override
            public void call(Subscriber<? super Message<?>> s) {
                int i = 0;
                while (!s.isUnsubscribed()) {
                    s.onNext(new GenericMessage<>("www.reallyreallyreallyreallylongdomain.com" + (i++ % 1000)));
                }
            }
        }).subscribeOn(Schedulers.newThread());
    }

}

```
Note that I am using a maxBatchSize of 2 million in an attempt to trigger the hang sooner but it still eventually hangs with a maxBatchSize of 64K.

I do not see any obvious leaks in the code where I am hanging on to any objects longer than needed, so it is not clear to me what could be causing the OOME.

**Comment by akarnokd** [comment]
Could you take a memory dump and analyze it with Eclipse MAT or a equivalent tool?

**Comment by headinthebox** [comment]
You do understand `distinct` is a rather dangerous operator (and IMHO should not be part of the API). Assuming there are a billion different registered domains out there and that you want your server to truly process an infinite stream of them, you will run out of space eventually.

http://www.cs.berkeley.edu/~satishr/cs270/sp11/rough-notes/Streaming.pdf

**Comment by clemper** [comment]
@headinthebox 

Thanks for your note and link.  I do understand that I cannot keep in memory all of the distinct domains that might come through my infinite stream;  however, this is not what I am trying to do.  I am trying to effectively de-dupe the stream by buffering a chunk of messages and then only emitting those messages that have distinct domains.  The messages are then sent downstream (actually to a different VM) and can be garbage collected very quickly.  Even assuming worse case that each message has a distinct domain, and that my maximum throughput in production is 10K/sec, the JVM has to execute my distinct function on a list of 65K roughly once every 6.5 seconds.  I would think the JVM on our hardware can easily handle this, and indeed it does for many days until it inevitably hangs.  

I ran another test using a batch size of 500K and it ran like that for about an hour before it finally failed with the GC overhead limit exceeded.  It did not grow the heap or CPU usage slowly over time before it failed, rather it ran at a steady state never using more than 700MB of heap before it suddenly failed.

I am willing to entertain that the overhead is simply too much for the JVM to handle, but it seems to me like a perfectly reasonable use case for rxjava to handle.

**Comment by clemper** [comment]
I modified my distinct function to just return the first element in the buffer and indeed the stream then seems to run without issue (at least overnight).  This leads me to think that it is not an issue with rxjava.  Thanks for your help.
