### ISSUE TITLE
Code Coverage and Static Analysis Tools

### ISSUE THREAD

**Issue by stealthcode** [ReactiveX/RxJava#3164]
The developers on RxJava have historically avoided adding new tools to the project in the interests of keeping the release and build processes as simple as possible. Today this includes Gradle, Nebula, JMH, and JUnit. So, if this impacts you we'd like to know. What tools do you like to use and how can we help make your hacking experience more productive? Can they be easily integrated and optionally executed or would they require integrating into the release process? Note that it's very unlikely that we'll choose to add complexity to the build process without a compelling reason. 

Right now our guidelines for assessing tools related pull requests are roughly the following:

* For changes which integrate a new tool which is not essential to the release process there should be no changes to the `build.gradle`. 
* Auxiliary tools that require gradle changes must remain unlinked to the build system. They should be optionally included as an init script via the `-I` gradle parameter on an as-needed basis by the developer.
* Runtime code should not /suffer/ for the benefit of an auxiliary tool. This includes adding mental overhead (readability, complexity) or reducing the efficiency of crucial computational paths. 

Hope to hear your ideas and suggestions.

**Comment by akarnokd** [comment]
Closing this as we added code coverage to the build process. Apart for indicating what extra unit tests are needed, it already helped discovering bugs by highlighting code sections that never run but should.

**Comment by vanniktech** [comment]
What about static analyze tools though such as PMD / Findbugs / Checkstyle?

**Comment by akarnokd** [comment]
My personal opinion about PMD / Findbugs is that they tend to give too many false positives on RxJava. As for Checkstyle, we didn't have a strict code style so far and were forgiving in many cases.

As with the code coverage, the best would be if you or somebody else posted a PR with the tools added to the build process to see how it works out.

**Comment by vanniktech** [comment]
I could prepare branches with those. Should I target 1.x or 2.x?

**Comment by akarnokd** [comment]
Start with 1.x as it builds faster.
