### ISSUE TITLE
How to group similar requests and provide a retry behavior

### ISSUE THREAD

**Issue by vekexasia** [ReactiveX/RxJava#3165]
Hello There,

I want to both mitigate same long running tasks defined in different instances of an observable to actually do the work 
Example, (dummy and dumb i know)

```java
public void example() {
	getUserInfo();
	getUserFriends();
}

void getUserInfo() {
	doTask(
		createLoginObservable()
			.flatMap( loginResult -> newUserInfoObservable();),
		(userInfo) -> {
			// do something with the user info
		}
	);
}
void getUserFriends() {
	doTask(
		createLoginObservable()
			.flatMap( loginResult -> newUserFriendsObservable();),
		(userFriends) -> {
			// do something with the user friends
		}
	);
}

<R> void doTask(Observable<R> observable, Action1<R> successAction) {
	observable
		.subscribe(
			successAction,
			throwable -> {
				// wait 1 Second &
				// lets retry! by calling myself again
				doTask(observable, successAction)
			}
		);
}
```

As you can see, calling `example()` will cause `createLoginObservable` to be called twice causing the login routine to hit the network twice for no reason!

For this reason i created something that groups the same requests in different Observable instances and when `createLoginObservable` of `getUserFriends()` gets created it actually is the same instance of `getUserInfo` (which was called before).

This is done using `.cache()` and a static HashMap of observables. 

the problem with .cache() is that if the LoginObservable returns an error then `doTask` gets re-called with the same Observable which has a .cache() version of the LoginObservable that will re-emit the error causing the task to not be re-loaded from scratch again.

I wrote a more specific text here http://stackoverflow.com/questions/32119802/rxjava-user-retry-observable-with-cache-operator with also the transformer i use to achieve same tasks grouping using .cache.

**Comment by vekexasia** [comment]
Basically What I think I would need. is some operator `.cacheUntilLatestSubscriberUnsubscribe(1, TimeUnit.SECONDS)` that will cache the emitted items and keep the subscription to the original observable for at least 1 Second (in the example) after the latest Subscriber unsubscribes.

If a later Subscriber comes then the original observable will get the "Observable.OnSubscribe".call method called allowing it to re-emit the data that will, again, be cached entirely after the latest subscriber will unsubscribe.

**Comment by akarnokd** [comment]
If I understand your problem correctly, what I'd do is use AsyncSubject to store the result of the last login attempt and check its error state otherwise:

```java
volatile AsyncSubject<LoginInfo> login;

public Observable<LoginInfo> login() {
    return Observable.defer(() -> {
        AsyncSubject as = login;
        if (as == null || as.hasThrowable()) {
            synchronized (guard) {
                if (as == null || as.hasThrowable()) {
                    as = AsyncSubject.create();
                    actualLogin.subscribe(as);
                }
        }
        return as;
    });
}
```
