### ISSUE TITLE
Version 2.x Maven Central Identification

### ISSUE THREAD

**Issue by benjchristensen** [ReactiveX/RxJava#3170]
The intent of 2.x is to live side-by-side with 1.x. The package name (io.reactivex vs rx) is insufficient though, as the Maven Central artifactId needs to also be different otherwise both can't be imported. So instead of `rxjava` should it just be `rxjava2` like this?

```
compile 'io.reactivex:rxjava2:2.x.y'
compile 'io.reactivex:rxjava:1.x.y'
```

**Comment by benjchristensen** [comment]
@rspieldenner Rob, I can't figure out what I need to change in the Gradle properties to change the name from `rxjava` to `rxjava2` other than changing "project.name" which also changes everything else.

If I change `project.name` I end up with this:

```
/io/reactivex/rxjava2/2.0.0-DP1-SNAPSHOT/rxjava2-2.0.0-DP1-SNAPSHOT.jar
```

Is that what it should be? Or can it be this somehow with just 'rxjava' in the filename?

```
/io/reactivex/rxjava2/2.0.0-DP1-SNAPSHOT/rxjava-2.0.0-DP1-SNAPSHOT.jar
```

**Comment by benjchristensen** [comment]
Seems that the artifactId is most commonly or always also the prefix for the filename. That suggests something like rxjava2 as above. Changing the complete name would also have the side-benefit of allowing two separate projects with different names in an IDE at the same time: rxjava and rxjava2. 

However, I winder about the name rxjava2. If we need to make a 3.x but want to retain the same package names we would be stuck with the artifactId rxjava2 with version 3.x. 

Is there a better name to represent this next version of rxjava?

io.reactivex – rxjava2 – rxjava2-2.0.0.jar
io.reactivex – rxjava2 – rxjava2-3.0.0.jar

io.reactivex – rxjava – rxjava-2.0.0.jar (I really wish this could work)

**Comment by rspieldenner** [comment]
Why wouldn't this "io.reactivex – rxjava – rxjava-2.0.0.jar" work?

**Comment by akarnokd** [comment]
A separate project makes things much easier; no need to switch back-and-forth between two branches. We could call it `rsjava` but I can see the confusion due to the one letter change. Having just `rxjava-2.0.0` is also attractive. How about copying the current 1.x to a new project RxJava1 and have the 2.0 start in a cleared out RxJava project?

**Comment by rspieldenner** [comment]
I think changing the group and artifact name are some of the worst things
you can do. When you do that the 2 versions would no longer participate in
conflict resolution. So a gradle/maven/sbt etc. resolve could pull in 2
different versions of rxjava if you do anything besides moving to
io.reactivex:rxjava:2.x.x

**Comment by JakeWharton** [comment]
That's the point of the change. They are able to operate next to each other.

**Comment by benjchristensen** [comment]
> could pull in 2 different versions of rxjava

@rspieldenner As @JakeWharton said, that's the point. Otherwise as soon as v2 comes out it will break every application and basically be unusable without herculean efforts to upgrade everything from v1 to v2 - and that could only be possible if and once v2 accounts for every piece of functionality v1 had (not necessary a good thing to force upon v2).

RxJava is not a library that hides well, as it is intended to be exposed in the public APIs, and be used for composing libraries and systems together. Thus, a breaking change would mean coordinating all systems and libraries to all upgrade at the same time.

For example, at Netflix we would need to upgrade Hystrix for the entire company at the same time. Not going to happen. I consider this an even harder upgrade than Guava (which typically take many months of effort to upgrade) since Guava generally is not part of our public APIs, just internal implementation details. 

An application could have the following dependencies:

io.reactivex:rxjava:rxjava-1.0.14
io.reactivex:rxjava:rxjava2-2.0.0

They would then use different types like this:

rx.Observable (from rxjava-1)
io.reactivex.Observable (from rxjava-2) (or whatever we call the package and class names)

**Comment by benjchristensen** [comment]
@akarnokd I'm not a fan of splitting the projects. We split the community, lose the collaboration between 1.x and 2.x issues (which will be very common), will end up cross-posting things a lot, and would complicate the branding. The branding includes the Github URL, contributors, forks and stars. Those statistics (as superficial as it sounds) are meaningful. They represent the community around the project. Community, branding and marketing are honestly a massive part of a project like this. The code itself honestly is the easiest part.

**Comment by jkschneider** [comment]
@benjchristensen There is one alternative since you are also changing source package names which is to retain the same Maven coordinate, but to also provide a shim library that bridges 2.x functionality to the old package names.  Effectively, anybody needing both to coexist would just add an additional dependency on the shim, but it is a little more in your face and encourages upgrades.  Think of the SLF4J Log4J shim as a not-entirely-similar case.

**Comment by benjchristensen** [comment]
@jkschneider can you give me an example of how that would work? That sounds intriguing.

**Comment by benjchristensen** [comment]
I think I may understand. Is it as follows?

We could double publish RxJava v1 like this:

- io.reactivex:rxjava:1.x.y
- io.reactivex:rxjava1:1.x.y (or whatever name we want like rxjava-v1 or rxjava_1, etc)

Then we publish v2 as:

- io.reactivex:rxjava:2.x.y

So if someone gets upgraded to v2 and it breaks their world, and they need both to live together, they would have dependencies like:

- io.reactivex:rxjava1:1.x.y
- io.reactivex:rxjava:2.x.y

So, instead of us changing artifactIds for new versions, we actually add one for the old version?

**Comment by jkschneider** [comment]
@benjchristensen that's right -- the main benefit is a natural bias toward upgrading, especially for first order dependents.

**Comment by zsxwing** [comment]
@jkschneider I think it's possible that someone uses both a library A that depends on io.reactivex:rxjava:1.x.y, and a library B that depends on io.reactivex:rxjava:2.x.y. Then the user needs to fix the dependency tree manually, since maven/gradle only selects one version of `io.reactivex:rxjava`.

**Comment by simonbasle** [comment]
@jkschneider @benjchristensen @zsxwing that could indeed be the case for instance if said user depends on the Couchbase SDK (which in turn depends on `RxJava`).

**Comment by jkschneider** [comment]
@simonbasle @zsxwing while conflict resolution would evict io.reactivex:rxjava:1.x.y, adding the shim would make any dependency that requires rxjava 1.x happy, just not with the exact same binary it had before.

**Comment by zsxwing** [comment]
> @simonbasle @zsxwing while conflict resolution would evict io.reactivex:rxjava:1.x.y, adding the shim would make any dependency that requires rxjava 1.x happy, just not with the exact same binary it had before.

I see. However, my concern is that the user has to fix it manually. Sometimes, the dependency tree is very complicated and it's hard for the user to figure out how to fix it. E.g., I remember that I used several hours to understand the SLF4J Log4J shim things when I encountered the conflicts at the first time :(

**Comment by jkschneider** [comment]
@zsxwing That is a legitimate concern and the principle tradeoff.

**Comment by benjchristensen** [comment]
Talked with @rspieldenner about this today to get some guidance. We can make RxJava v1 double-publish artifacts for us to solve this.

The way it would work is:

##### RxJava v2 only
```groovy
compile 'io.reactivex:rxjava:2.x.y'
```

##### RxJava v1 only
```groovy
compile 'io.reactivex:rxjava:1.x.y'
```

##### RxJava v1 and v2 together

If someone needs both, v2 would override v1 and transitive dependencies would break. They would then manually opt-in to having 'rxjava_v1' included and they'll end up with both jars.

```groovy
compile 'io.reactivex:rxjava_v1:1.x.y'
compile 'io.reactivex:rxjava:2.x.y'
```

##### RxJava v2 and v3 together

Eventually (hopefully never or at least many years from now) if we need to do the same for v2/v3 we could add an artifact for v2 (and yet another set of package names for 3.x):

```groovy
compile 'io.reactivex:rxjava_v2:2.x.y'
compile 'io.reactivex:rxjava:3.x.y'
```

------------------------

The change from v1 to v2 is too significant for a thin shim. Virtually every single class in the entire project is going to be touched in the move from v1 to v2. Thus, we really do want to just provide all v1 byte code untouched with a different artifact so both can live side-by-side. We also intend on v1 living for a long time (at least while Android doesn't support Java 8), though hope that server-side projects will upgrade over a 12-18 month period from v1 to v2 so that most server environments would only need to be importing v2. 

So, unless there is dispute with what is stated above, it's time to debate the artifactId. 

I suggest `rxjava_v1`.

**Comment by simonbasle** [comment]
:+1: for this solution (great one)
:+1: for the name `rxjava_v1` (don't have a strong opinion on any other name anyway)

**Comment by zsxwing** [comment]
@benjchristensen :+1: for your proposal. This is just a tradeoff. Thanks for explaining why you made this choice.

**Comment by JakeWharton** [comment]
As RxJava 2 has yet to be released, I would like to propose `io.reactivex.rxjava2:rxjava` as the Maven coordinates for the 2.0 major version release. The details on both group ID naming and artifact ID naming are encapsulated in [my blog post][1].

Multiple comments from this issue are addressed in the post:

> The package name (io.reactivex vs rx) is insufficient though, as the Maven Central artifactId needs to also be different otherwise both can't be imported.

Covered in the post.

> Is there a better name to represent this next version of rxjava?

Covered in the post. Group ID changes is the simple way to break this apart.

> They would then manually opt-in to having 'rxjava_v1' included and they'll end up with both jars.

and

> Eventually (hopefully never or at least many years from now) if we need to do the same for v2/v3 we could add an artifact for v2 (and yet another set of package names for 3.x):

This solution plays to the always-upgrading nature of consumers and some libraries. While it represents a non-zero effort on consumer's part, the naive remain blissfully unaware and allow natural progression of these APIs to take place.

 [1]: http://jakewharton.com/java-interoperability-policy-for-major-version-updates/

**Comment by benjchristensen** [comment]
Jake, thanks for the followup on this. I'm good with accepting the artifact name you propose.

**Comment by akarnokd** [comment]
:+1: to be able to import them the same time.

**Comment by akarnokd** [comment]
Jake's suggestion for `io.reactivex.rxjava2:rxjava` sounds reasonable for me. It also allows upgrading the neighboring libraries and have all of 2.x under the same groupId pattern (`io.reactivex.rxjava2:rxjava-math`).

Unfortunately, I'm not sure where this new group ID could be applied (hidden inside the nebula plugin?).

**Comment by artem-zinnatullin** [comment]
@akarnokd yeah, looks like it's in [nebula rxjava plugin](https://github.com/nebula-plugins/gradle-rxjava-project-plugin/blob/75a8d77e4618be7f02eb03ff04f5fea63009a0e3/src/main/groovy/nebula/plugin/rxjavaproject/RxjavaProjectPlugin.groovy#L73), but you can override it inside RxJava's `build.gradle`, add `group = 'io.reactivex.rxjava2'`. When I run `./gradlew publishToMavenLocal` it publishes it to overridden group.

**Comment by artem-zinnatullin** [comment]
👍 for Jake's proposal about `groupId` change to `io.reactivex.rxjava2`.

**Comment by JakeWharton** [comment]
Might be a good time to shed some nebula? RxAndroid got rid of all of them
and never looked back.

**Comment by akarnokd** [comment]
Sounds good, @JakeWharton . Was there something in RxAndroid regarding nebula that had to be replaced (such as travis-maven publish on release builds)?

**Comment by JakeWharton** [comment]
Yes. The challenging part was retaining the part which does the release
builds. @dlew helped set it up, and while it's not pretty it doesn't feel
any less brittle than Nebula already was.

**Comment by akarnokd** [comment]
Great. Not sure if we can actually test it before RC1 (release RC0 as is at the time of testing?).

**Comment by stevegury** [comment]
👍 for the groupId change.
@akarnokd I can try to find someone from our tools team to help with the migration out of Nebula.

**Comment by akarnokd** [comment]
@stevegury any help in this regard is appreciated, thanks!

**Comment by akarnokd** [comment]
Changing the group ID while still using Nebula does work for the snapshot release: https://oss.jfrog.org/artifactory/libs-snapshot/io/reactivex/rxjava2/rxjava/

The discussion about removing the plugin continues in #4032.
