### ISSUE TITLE
2.0 Package Name

### ISSUE THREAD

**Issue by benjchristensen** [ReactiveX/RxJava#3173]
I've been using `io.reactivex` as the assumed package name for v2, but that doesn't have to be what it is.

RxJava v1 ==> `rx`

We could do any of the following (or something else) for RxJava v2:

- `rx2`
- `io.rxjava`
- `io.rxjava2`
- `io.rx2`

The thinking behind this is keeping our options open for a v3 years from now (say after Java 10).

Let's assume we have 3 versions and want to decouple the upgrade cycles, it would look like this:

```
io.reactivex:rxjava:1.x.y – package rx.*
io.reactivex:rxjava2:2.x.y  – package rx2.* or io.reactivex.* or ???
io.reactivex:rxjava3:3.x.y  – package rx3.* or ???
```

I'd appreciate input on how this should be done as we'll have to live it with for many years.

Note that this is related to the discussion in https://github.com/ReactiveX/RxJava/issues/3170 where we are discussing having v1 and v2 as independent artifacts so an app could use both at the same time.

**Comment by benjchristensen** [comment]
rxjava.io is owned by Netflix, so we can use io.rxjava
rxjava2.io and rxjava3.io are owned by me in case we wanted to use them.

Are there others we should pick up in case we need/want them?

**Comment by JakeWharton** [comment]
Using `io.reactivex` would definitely put the library in an awkward place for a v3.

I'm not opposed to `rx2` despite versioned packages being somewhat of a rarity (counter example: Apache commons-lang3). It also has the bonus of retaining the aspect of being short. When there's clashes in an import scope, fully-qualifying becomes not only easy but also very explicit:
```java
// RxJava1 in an RxJava2 world
Observable<Magic> moreMagic(Observable<Magic> magic) {
  rx.Observable<Magic> oldMagic = getOldMagic();
  return Observable.merge(magic, RxConverter.to2(oldMagic));
}
```
or conversely:
```java
// RxJava2 in an RxJava1 world
Observable<Magic> moreMagic(Observable<Magic> magic) {
  rx2.Observable<Magic> newMagic = getNewMagic();
  return Observable.merge(magic, RxConverter.to1(newMagic));
}
```

**Comment by daschl** [comment]
I'm a little torn on putting the version of the package in the artifact id, since it's not really the place where it belongs.

@benjchristensen do you see the use case that people use the old and new rx versions side by side? For example with couchbase we had that explicit use case requested, so we went with a different artifact ID and the namespace was also different. But every project might be different in that regard.

**Comment by benjchristensen** [comment]
Yes, using side-by-side is expected for some time, especially in big companies. 

For example, using the current Couchbase client, Hystrix 1.x, or RxNetty 1.x with RxJava v1 while starting to use newer libraries, such as those I'm working on at reactivesocket.io which natively use Reactive Streams interfaces (and eventually Java 9 Flow). 

Also, v2 will be Java8+ so any library need <8 will stay on v1 and we don't want to prevent people from using libraries taking advantage of Java 8+ just because 1 library needs to stay on 6 or 7.

**Comment by jkschneider** [comment]
@JakeWharton Unfortunately, virtually nobody uses commons-lang3, even four years later.  We should approach these decisions cautiously.

**Comment by simonbasle** [comment]
I don't recall an example out there from the top of my head that puts version number in the package name (although @jakewharton mentioned `apache commons lang3`), so no real comparison point.
I agree with the point made by Jake on conciseness to help make code live side by side, so maybe `rx2` is a good choice?
Another solution can maybe be to include the major version number as another level of prefixing, ie `io.reactivex.v2` or something like that?

**Comment by benjchristensen** [comment]
Talked with @rspieldenner about this today to get some guidance. We can make RxJava v1 double-publish artifacts for us to solve this.

The way it would work is:

##### RxJava v2 only
```groovy
compile 'io.reactivex:rxjava:2.x.y'
```

##### RxJava v1 only
```groovy
compile 'io.reactivex:rxjava:1.x.y'
```

##### RxJava v1 and v2 together

If someone needs both, v2 would override v1 and transitive dependencies would break. They would then manually opt-in to having 'rxjava_v1' included and they'll end up with both jars.

```groovy
compile 'io.reactivex:rxjava_v1:1.x.y'
compile 'io.reactivex:rxjava:2.x.y'
```

##### RxJava v2 and v3 together

Eventually (hopefully never or at least many years from now) if we need to do the same for v2/v3 we could add an artifact for v2 (and yet another set of package names for 3.x):

```groovy
compile 'io.reactivex:rxjava_v2:2.x.y'
compile 'io.reactivex:rxjava:3.x.y'
```

------------------------

The change from v1 to v2 is too significant for a thin shim. Virtually every single class in the entire project is going to be touched in the move from v1 to v2. Thus, we really do want to just provide all v1 byte code untouched with a different artifact so both can live side-by-side. We also intend on v1 living for a long time (at least while Android doesn't support Java 8), though hope that server-side projects will upgrade over a 12-18 month period from v1 to v2 so that most server environments would only need to be importing v2. 

So, unless there is dispute with what is stated above, it's time to debate the artifactId. 

I suggest `rxjava_v1`.

**Comment by benjchristensen** [comment]
A related post is at https://github.com/ReactiveX/RxJava/issues/3170#issuecomment-135279828 about the maven artifactId name. I have been convinced that we should retain `rxjava` as the artifactId and just have an option for pulling in v1 with a different artifactId such as `rxjava_v1` for those who do need both.

As for the package, I'm still leaning towards `io.reactivex` and not putting the version in the package name. 

```
io.reactivex:rxjava:1.x.y – package rx.*
io.reactivex:rxjava:2.x.y – package io.reactivex.*
io.reactivex:rxjava:3.x.y – package io.rxjava (or some other made up name, or back to rx.*)
```

:+1:  :-1:  ?

**Comment by simonbasle** [comment]
:+1:, double maven publication sounds like a great solution IMHO

**Comment by daschl** [comment]
:+1:

**Comment by benjchristensen** [comment]
Thanks for the positive feedback @simonbasle and @daschl 

@ReactiveX/rxjava-committers I'd appreciate your vote on this.

**Comment by zsxwing** [comment]
:+1:

**Comment by alkemist** [comment]
Interesting discussion. I don't have any unique input.

**Comment by akarnokd** [comment]
I'm closing this for now. 

2.x will go with `io.reactivex.rxjava2:rxjava:2.x.y` pattern and packages start with `io.reactivex`. We can revisit the latter organization in the RC timeframe once others start to adapt and give feedback.
