### ISSUE TITLE
How to create a set of separated eventhandler

### ISSUE THREAD

**Issue by vekexasia** [ReactiveX/RxJava#3178]
Hello there, suppouse i've an observable that emits user events. For clarity lets assume the emitted events are "Point(x,y)" coordinates on where the user taps on the screen.

Then i've multiple pieces of code capable of handling these coordinates and decide accordingly how to "react". Example:
1. RectClickHandler - Handles only coordinates that are inside a given rectangle (say, a rectangle-shaped button)
2. NavigationClickHandler - Handles only coordinates within navigation elements

Lets say I've 3 buttons on my screen (3 x RectClickHandler) and 1 NavigationElement. 

Given the single emitting Observable what would be the best way to replicate this non-reactive code:

```java

 RectClickHandler btn1;
 RectClickHandler btn2;
 RectClickHandler btn3;

 PointHandler pointHandlers[] = new PointHandlers[]{btn1, btn2, btn3, navHandler}; 
 new PointEmitterObservable().
   subscribe(
       point -> {
          for (PointHandler ph: pointHandlers) {
            if (ph.canHandle(point)) {
               ph.reactToPoint(point);
               break;
            }
          }
      }
  );
```

Should i use `.toList().filter(btn1).filter(btn2).filter(btn3)...` ?

**Comment by akarnokd** [comment]
Do you want to process the point further on? If not, then your approach looks fine to me.
