### ISSUE TITLE
.just(1).filter().first().subscribe(throw) swallows the exception

### ISSUE THREAD

**Issue by konmik** [ReactiveX/RxJava#3182]
The test:

    @Test(expected = Throwable.class)
    public void testThrowDuringOnNext() throws Exception {
        Observable
            .just(1)
            .filter(new Func1<Integer, Boolean>() {
                @Override
                public Boolean call(Integer integer) {
                    return true;
                }
            })
            .first()
            .subscribe(new Action1<Integer>() {
                @Override
                public void call(Integer integer) {
                    throw new RuntimeException();
                }
            });
    }

If I remove `filter` or `first` the test gets passed.

**Comment by akarnokd** [comment]
Thanks for reporting. The fatal error `OnErrorNotImplemented` is swallowed by filter. I'll do a sweep of places where a `catch (Throwable` is not followed by `Exceptions.throwIfFatal()`

**Comment by akarnokd** [comment]
Fixed via #3183.

**Comment by konmik** [comment]
Thanks! :)
