### ISSUE TITLE
TestSubscriber.await throws InterruptedException

### ISSUE THREAD

**Issue by benjchristensen** [ReactiveX/RxJava#3216]
Is there a reason we must throw `InterruptedException` on `TestSubscriber.await`? It means that every unit test must now catch or throw. If an `InterruptedException` occurs, that means it unblocks and returns false, doesn't it?

It's quite annoying to use right now. In v1 `awaitTerminalEvent` didn't throw an `InterruptedException` and it was much nicer to use. 

cc @akarnokd

**Comment by akarnokd** [comment]
I'll add these methods.

**Comment by akarnokd** [comment]
Done.
