### ISSUE TITLE
2.0 TestSubscriber.assertValue should not assert completion

### ISSUE THREAD

**Issue by benjchristensen** [ReactiveX/RxJava#3218]
Right now TestSubscriber.assertValue has this:

```java
    public final void assertValue(T value) {
        String prefix = "";
        if (done.getCount() != 0) {
            prefix = "Subscriber still running! ";
        }
```

It should not assert completion, as that means values can't progressively be asserted while synchronously delivering values prior to completion. 

Same for the other assertValue methods.

**Comment by akarnokd** [comment]
It doesn't assert it, just prefixes the error message to let the dev know if the subscriber hung.
