### ISSUE TITLE
`onBackpressureBuffer(int)` errors on overflow

### ISSUE THREAD

**Issue by abersnaze** [ReactiveX/RxJava#3233]
Talking with @neerajrj this morning about various Rx issues. One of them is that `onBackpressureBuffer(int)` defaults to sending an error if the limited buffer is full.  He would like to have the option to do different things on overflow.

I'm suggesting adding an `enum OnOverflow { DROP_OLDEST, DROP_LATEST, ERROR }` to the arguments to allow the user to decide what the overflow behavior should be.

Could `onBackpressureDrop()` be rewritten to `onBackpressureBuffer(0, OnOverflow.DROP_OLDEST)` and `onBackpressureLatest()` would be `onBackpressureBuffer(1, OnOverflow.DROP_OLDEST)`?

**Comment by neerajrj** [comment]
+1 Also have an Action0 option to be informed when dropping is occuring.

**Comment by srvaroa** [comment]
I've got this almost ready, I need some polishing but will be pushing a PR today/tomorrow the latest.
