### ISSUE TITLE
Add Single.toBlocking?

### ISSUE THREAD

**Issue by hyleung** [ReactiveX/RxJava#3252]
Now that we have `rx.Single`,  would it make sense to add a `toBlocking()` method on the`rx.Single` that would return the blocking version of the Single, similar to `rx.Observable.toBlocking()`?

Given that Single either returns a single item or fails, I'd imagine it would be pretty minimal. I took a stab at it [here](https://github.com/hyleung/RxJava/tree/blocking-single) - just a `get()` to return the value and `toFuture()` at the moment, couldn't think of anything else that would be useful on a blocking Single...

**Comment by stealthcode** [comment]
Do you want to open a pull request with your change to branch 1.x?

**Comment by hyleung** [comment]
Close by #3286
