### ISSUE TITLE
Single doOnSuccess / doOnError

### ISSUE THREAD

**Issue by JolandaVerhoef** [ReactiveX/RxJava#3266]
Observable has doOn* methods to put side effects in. Single has no such methods yet.

**Comment by akarnokd** [comment]
Single is in experimental state. If you wish, you can post a PR that adds these methods.

**Comment by hyleung** [comment]
@JolandaVerhoef I believe #3417 and #3419 (courtesy of @artem-zinnatullin) add `doOnSuccess` and `doOnError`, respectively.
