### ISSUE TITLE
2.0 Constructing an Observable

### ISSUE THREAD

**Issue by stealthcode** [ReactiveX/RxJava#3269]
Creating an observable happens in a couple different ways. This issue relates specifically to the semantics of using a static initializer method for creating an Observable. In 1.x we are discovering use cases for creating new kinds of Observables (such as the existing Observable, Single, GroupedObservable, as well as the various Subjects). These sometimes created by modifying an existing Observable (such as when using `groupBy`). Other times these can be constructed directly via static initializer methods. 

In 1.x the static methods (`.from()`, `.create()`, `.just()`) exists on the class you want to construct. These constructors then exist along side the standard member operators of that observable class. We could consolidate the  static initializer methods under the namespace of a single class. This class could serve as a general entry point for creating and using RX. For instance, there could be a `rx.Streaming` class which has classes such as `Observable<T> fromFuture(Future<T>)` and `Observable<T> fromIterable(Iterable<T>)` as well as other use cases such as `CachedObservable<T> collectionBackedCache(Collection<T>)`. This would have the advantage of a single entry point. 

There are also use cases for instance operators that convert to a different class of observable (for instance `groupBy()`). These instance methods are very use-case dependent. They give clear paths for converting between types of observables. However for types of observables that are experimental (as is the case currently with `rx.Single`) it may not be desirable to create fluent operators on the `rx.Observable` class. In this case, I think that the `R x(Func1<OnSubscribe<T>, R>)` method could be used to convert from one class of observable to another using standard conversion funcs before we are ready to add APIs to the tried and true rx.Observable. Should we implement standard conversion functions for each class of observables (such as a `ConvertToSingle` function)?

**Comment by akarnokd** [comment]
I don't understand your proposal.

We now have 4 reactive base types, each offering a `to` method for fluent conversion to anything. Also moving all factory methods of these 4 types into a single factory class creates a lot of prefixing/renaming since `fromIterable` is viable for both `Observable` and `Flowable`.
