### ISSUE TITLE
JavaDoc for flatMapIterable(Func1, Func2) doesn't look right

### ISSUE THREAD

**Issue by tommack** [ReactiveX/RxJava#3288]
http://reactivex.io/RxJava/javadoc/rx/Observable.html#flatMapIterable(rx.functions.Func1, rx.functions.Func2)

The picture seems to imply that the signature of the `Func2` is `Func2<T, Iterable<U>, R>` when in fact it is `Func2<T,U,R>`. (Omitting the supers for clarity.)

Additionally the picture shows only the emissions, when I think it would actually be six.

**Comment by DavidMGross** [comment]
How does this look to you: 
![](https://raw.github.com/wiki/ReactiveX/RxJava/images/rx-operators/mergeMapIterable.r.png)

**Comment by tommack** [comment]
That seems much better.
