### ISSUE TITLE
Wiki page for RxJava Android Module is outdated

### ISSUE THREAD

**Issue by steffandroid** [ReactiveX/RxJava#3290]
The [wiki page](https://github.com/ReactiveX/RxJava/wiki/The-RxJava-Android-Module) for the RxJava Android Module refers to version 0.23.0. This should be updated to reflect the substantial changes made in 1.0.0.

**Comment by artem-zinnatullin** [comment]
I think that best RxJava can do — just give a link to RxAndroid repository's wiki https://github.com/ReactiveX/RxAndroid/wiki and remove all documentation related to Android.

**Comment by DavidMGross** [comment]
I've added a note to the top of that RxJava wiki page linking to the RxAndroid wiki and have changed the link in the sidebar to go straight to the RxAndroid wiki.
