### ISSUE TITLE
merge vs concat for synchronous sources

### ISSUE THREAD

**Issue by davidmoten** [ReactiveX/RxJava#3296]
Given two synchronous sources I wondered which would be faster between `merge` and `concat` so I made some jmh benchmarks. Thought I'd share the results.

`Some` is concat/merge of two observables with 5 elements.
`Many` is concat/merge of two observables with 1000 elements.

```
Benchmark               Mode  Cnt        Score       Error  Units
Benchmarks.concatMany  thrpt   10  1659537.566 ±  7855.471  ops/s
Benchmarks.concatOne   thrpt   10  1646163.597 ± 18000.352  ops/s
Benchmarks.concatSome  thrpt   10  1028804.686 ±  8443.497  ops/s
Benchmarks.mergeMany   thrpt   10  4035027.312 ± 52827.465  ops/s
Benchmarks.mergeOne    thrpt   10  3908960.531 ± 40511.640  ops/s
Benchmarks.mergeSome   thrpt   10   960602.879 ±  6814.269  ops/s
```
For my current use case I will probably use `merge` because it wins so convincingly on the One and Many cases.

Benchmark [source](https://github.com/davidmoten/rxjava-extras/blob/master/src/test/java/com/github/davidmoten/rx/Benchmarks.java).

**Comment by akarnokd** [comment]
Concat doesn't have any scalar optimizations. Besides, your xOne and xMany do the same thing because you apply an operator to a single value.

**Comment by davidmoten** [comment]
You might be misreading the source. The benchmarks use o.concatWith(o) or o.mergeWith(o).

**Comment by akarnokd** [comment]
```java
private static final Observable<Integer> o1 = Observable.just(1);
...
private static final Observable<Integer> o1000 = Observable.just(1);
```

These look exactly the same. Didn't you want to run `range(1, 1000)` instead?

**Comment by davidmoten** [comment]
Ta! I'll revisit!

**Comment by davidmoten** [comment]
Thanks for the correction @akarnokd.

Not so clear cut this time. Scalar optimisations a big help for the One case, `flatMap` encouragingly fast for the `Many` case (great work @akarnokd for your `merge` rewrite). 

```
Benchmark               Mode  Cnt        Score       Error  Units
Benchmarks.concatMany  thrpt   10    14033.178 ±   573.867  ops/s
Benchmarks.concatOne   thrpt   10   886380.263 ± 10976.982  ops/s
Benchmarks.concatSome  thrpt   10   687147.336 ± 10232.043  ops/s
Benchmarks.mergeMany   thrpt   10    15091.032 ±   387.125  ops/s
Benchmarks.mergeOne    thrpt   10  2274263.641 ± 39795.030  ops/s
Benchmarks.mergeSome   thrpt   10   477307.189 ±  6837.012  ops/s
```

I'm not expecting any follow up on this one, just thought I'd share this little exploration.

**Comment by akarnokd** [comment]
Thanks @davidmoten. Its always good to see high performance operators!
