### ISSUE TITLE
2.x: Observable.just Performance

### ISSUE THREAD

**Issue by benjchristensen** [ReactiveX/RxJava#3336]
I have a library using v2 `Observable.just` like this:

```java
return Observable.just(frame);
```

but the performance degrades compared with my creating a `Publisher` manually. I then tried this:

```java
return (Subscriber<? super Frame> s) -> {
	s.onSubscribe(new ScalarSubscription<Frame>(s, frame));
};
```

The perf is then more-or-less equal. 

Here are perf numbers of my library with everything else the same except for the 3 variants of `just`.

Manual `Publisher`:

```
Iteration   1: 3602663.765 ops/s
Iteration   2: 3589466.569 ops/s
Iteration   3: 3540823.028 ops/s
Iteration   4: 3580512.428 ops/s
Iteration   5: 3599728.601 ops/s
```

Manual `Publisher` with `ScalarSubscription`:

```
Iteration   1: 3520232.687 ops/s
Iteration   2: 3487323.518 ops/s
Iteration   3: 3520324.490 ops/s
Iteration   4: 3502789.786 ops/s
Iteration   5: 3450273.680 ops/s
```

`Observable.just`:

```
Iteration   1: 3298463.662 ops/s
Iteration   2: 3343857.219 ops/s
Iteration   3: 3325536.413 ops/s
Iteration   4: 3192566.805 ops/s
Iteration   5: 3218123.155 ops/s
```

It seems that the cost may be because `Observable.just` requires allocating both a `Publisher` and an `Observable`. I'll dig further to see if we can eliminate this overhead.

**Comment by benjchristensen** [comment]
This is where the time seems to be going: `Observable.subscribeActual`

<img width="1325" alt="screen shot 2015-09-09 at 3 37 14 pm" src="https://cloud.githubusercontent.com/assets/813492/9775994/afd2712a-5708-11e5-8b77-8a4672d3379d.png">

**Comment by akarnokd** [comment]
This is the drawback when one doesn't have extension methods. We need to wrap everything into an `Observable` which increases the allocation count:

1 new `Observable` (the wrapper)
1 new `Publisher` (for the custom subscribe logic)
1 new `ScalarSubscription` (for honoring backpressure)

If you know a source is a `ObservableScalarSource`, you can cast it and call `value()`. That saves the final allocation of a `ScalarSubscription` and a CAS. If there would be an `NbpObservableScalarSource`, that doesn't have to consider backpressure and can save the last allocation permanently.

**Comment by akarnokd** [comment]
While we are at the topic, using operators with lift also adds an extra allocation of the `PublisherLift`:

`create` + `PublisherLift` + `Operator`

The classical way is to have everything as `Publisher` that takes another `Publisher` (unwrap it from the `Observable` if necessary) as source and the lift object is no longer necessary.

The `PublisherLift` overhead matters with short lived but frequently called sequences.
