### ISSUE TITLE
 Equivalent with CompletableFuture.complete

### ISSUE THREAD

**Issue by GrapeBaBa** [ReactiveX/RxJava#3343]
Hi,
Dose Rxjava Observable has equivalent with CompletableFuture.complete?
like: CompletableFuture future=new CompletableFuture();
       ...do  something...
       future.complete(xxx)

**Comment by benjchristensen** [comment]
You can use a Subject for that type of 'promise' usage. 

Subject s = ReplaySubject.create()
... do something ...
s.onCompleted()

Or for the more idiomatic approach, create a lazy Observable:

return Observable.create(s -> {
  ... do something ...
  s.onCompleted()
});

**Comment by GrapeBaBa** [comment]
Awesome.

发自我的 iPhone

> 在 2015年9月14日，下午2:25，Ben Christensen <notifications@github.com> 写道：
> 
> You can use a Subject for that type of 'promise' usage. 
> 
> Subject s = ReplaySubject.create()
> ... do something ...
> s.onCompleted()
> 
> Or for the more idiomatic approach, create a lazy Observable:
> 
> return Observable.create(s -> {
> ... do something ...
> s.onCompleted()
> });
>
