### ISSUE TITLE
Hundreds of 2.x operators/classes for NbpObservable

### ISSUE THREAD

**Issue by akarnokd** [ReactiveX/RxJava#3368]
I believe I can derive non-backpressure operators from backpressured operators with a relatively simple process (delete backpressure related fields, fix up the classes). Such task would take me 1-1.5 days tops and I can do it in a single PR. The work, unlike the run on the backpressured, can now be done in parallel as there aren't really and cross-dependencies or algorithmic challenges; it's mostly a simple mechanical process. Once all of them is "ported", the NbpObservable can be modified to access them in one PR.

However, this is at least 20kloc for classes and another 20kloc for unit test where such large amount of change is practically non-reviewable.

My question is, how should this be handled? One by one and with 200+ PRs or batched into ~1kloc chunks and thus within ~40 PRs?

**Comment by benjchristensen** [comment]
Go ahead and do it as a big commit (or a few big commits) and I'll treat it special with a :+1: just to get it in, like you did all the rest in 2.x. Then I'll start reviewing it as part of the 2.x branch and we can do revisions through the normal PR process as we do a thorough review.

**Comment by stevegury** [comment]
I agree, that's a valid use case where we can break the rule and only do one big PR.
Thanks for doing this.

**Comment by akarnokd** [comment]
Merged in #3371
