### ISSUE TITLE
2.x: Merge and Queue Pooling

### ISSUE THREAD

**Issue by benjchristensen** [ReactiveX/RxJava#3375]
@akarnokd Reading through the `merge` code in 2.x, it appears to not use pooling any longer. As soon as contention happens, it allocates a new array. We have proven previously as we've iterated on `merge` that we can't allocate arrays for every `InnerSubscriber`. What new data or evidence suggests that we can ignore past findings and do without pooling?

**Comment by benjchristensen** [comment]
Is it perhaps that the only time they are allocated is when contention occurs, and contention is already costly enough that the extra allocation no longer matters?

Trying to match this design up with past efforts on `merge` ...

**Comment by akarnokd** [comment]
> it appears to not use pooling any longer

That's right.

> As soon as contention happens, it allocates a new array

It's a Queue but yes.

> We have proven previously as we've iterated on merge that we can't allocate arrays for every InnerSubscriber

True, doesn't happen until contention.

> What new data or evidence suggests that we can ignore past findings and do without pooling?

#3352. Async performance improved over 1.x. Synchronous tests don't allocate any queue.

> contention is already costly enough that the extra allocation no longer matters?

In 1.x the pooling and the inner synchronization of the RxRingBuffer contributed even more to the contention. If there are multiple async sources and all but one encounter a contention, they all start to contend on the pool. This is a transient event and if the sequences are long-running, doesn't appear on measurements. However, short lived sequences encounter this much more frequently.

**Comment by benjchristensen** [comment]
Great, thanks for confirming my understanding and clarifying more.
