### ISSUE TITLE
Releasing 1.1.0

### ISSUE THREAD

**Issue by abersnaze** [ReactiveX/RxJava#3378]
I would like to share what out plans are for 1.1.0.  At the moment we've built up quite a lot of `@Experimental` APIs that we would like more confidence in using long term in production.  To that end we would like to promote them to express that they are stable. I've captured some consensus among the core committers about what APIs we would like the promote. Because it wasn't entirely unanimous this is what I plan to do:

- [x] Last call for merges before publishing 1.0.15 for the next two weeks. Our goal is to only have changes to the annotations between the last patch and 1.1.0 so that they are functionally equivalent.
- [x] Submit PRs to change the annotations on various APIs but not merge them.
- [x] Discus the various merits of the PRs.
- [x] Publish 1.0.15.
- [x] Merge the annotation change PRs that we can agree on (minimum of 3 :+1: or three weeks which ever is first).
- [x] Publish 1.1.0.

**Comment by akarnokd** [comment]
:+1: sounds great.

> Submit PRs to change the annotations on various APIs but not merge them.

I'd like to add that `Observable` hosts quite a set of the proposed APIs and may become difficult to have non-conflicting PRs targeting this single class, if said PRs are per functionality and not per class.

**Comment by DavidMGross** [comment]
Please don't forget to update the "@since" javadoc annotations as well if
you remove the @Experimental/@Beta annotations as you promote any APIs.
You can set @since to simply the string "1.1.0"

On Fri, Sep 25, 2015 at 12:45 PM, George Campbell <notifications@github.com>
wrote:

> I would like to share what out plans are for 1.1.0. At the moment we've
> built up a quite a lot of @Experimental APIs that we would like more
> confidence in using long term in production. To that end we would like to
> promote them to express that they are stable. I've captured some consensus
> among the core committers about what APIs we would like the promote. It
> wasn't entirely unanimous and this is what I'm planning to do.
>
>    - Last call for merges before publishing a 1.0.15 for the next two
>    weeks. Our goal is to only have changes to the annotations between the last
>    patch and 1.1.0; so that they are functionally equivalent.
>    - Submit PRs to change the annotations on various APIs but not merge
>    them.
>    - Discus the various merits of the PRs.
>    - Publish 1.0.15.
>    - Merge the annotation change PRs that we can agree on (minimum of 3 [image:
>    :+1:] or three weeks which ever is first).
>    - Publish 1.1.0.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ReactiveX/RxJava/issues/3378>.
>



-- 
David M. Gross
PLP Consulting

**Comment by abersnaze** [comment]
@akarnokd I have faith in git's abilities to handle mutually exclusive changes in the same file.

**Comment by abersnaze** [comment]
@DavidMGross thanks for the reminder.

**Comment by akarnokd** [comment]
> Submit PRs to change the annotations on various APIs but not merge them.

To be clear, will you @abersnaze  port these PRs or should this task be shared among us all?

**Comment by abersnaze** [comment]
I've got a spreadsheet that I've collected the feed back in.  I was planning on submitting most these PRs.

**Comment by akarnokd** [comment]
If you don't mind, I'll handle the cases which I proposed, especially if it involves removing a feature because the dependencies have to be cleared up as well.

**Comment by akarnokd** [comment]
Never mind, I've done all PRs, although grouped by function instead of the grouping in the spreadsheet.

**Comment by abersnaze** [comment]
Last call for pull requests to be merged for 1.0.15. I'm trying to recruit @stevegury and @stealthcode to help review #3169 and #3150.

**Comment by stealthcode** [comment]
@akarnokd @abersnaze the public api promotion changes all have the javadoc annotation `@since 1.0.15`. I thought the promotions were going to be accepted after 1.0.15 but before 1.1.0. In that case shouldn't the annotations say 1.1.0?

**Comment by abersnaze** [comment]
All the tasks were done.
