### ISSUE TITLE
OnSubscribeCombineLatest#MultiSourceProducer#collectedValues leaks?

### ISSUE THREAD

**Issue by konmik** [ReactiveX/RxJava#3379]
It looks to me that it should be cleared when the child `subscriber` is unsubscribed.

The issue is that when I keep a subscription this automatically mean that I will keep a reference to the latest emitted value even if the subscription is unsubscribed. This prevents us from using `combineLatest` on memory-heavy objects.

**Comment by akarnokd** [comment]
Why do you keep the subscription once the sequence is unsubscribed through it? Even if the array is cleared, its surroundings will keep leaking.

**Comment by konmik** [comment]
I keep subscription because I don't want to attach side-effects to the chain clearing the reference to the subscription when it is completed. I find it a good practice to follow some functional practices when using RxJava.

Why the environment would leak? The value has been passed into the chain, that's it.

**Comment by konmik** [comment]
So, should I write something like this?

```java
    Subscription subscription;

    void connect() {
        subscription = combineLatest(api.login(), heavyViewThatDisappearsAndAppearsRandomly)
            .doOnUnsubscribe(() -> subscription = null).
            .subscribe();
    }
```

**Comment by akarnokd** [comment]
The setting of the subscription may race with each other. Instead:

```java
CompositeSubscription composite = new CompositeSubscription();

void connect();
    Subscriber<T> subscriber = new Subscriber<T>() {
         // onNext logic here
    });
    composite.add(subscriber);

    combineLatest(...)
    .doOnUnsubscribe(() -> composite.remove(subscriber))
    .subscribe(subscriber);
}
```

**Comment by konmik** [comment]
So, if there is no guarantee that operators will not leak events after unsubscription, should I apply this pattern *always*? I think that having such guarantee would simplify the usage a lot.

**Comment by akarnokd** [comment]
I've seen some people creating their own `Subscriber` wrapper which has nulls out the reference to the original in case of a terminal event. Otherwise, cleaning up in operators all the time may hinder performance in case the references go away anyways.

**Comment by konmik** [comment]
I don't see how performance can be hindered. OK, understood. I'll write my own wrapping function around rx ro prevent leaks.
