### ISSUE TITLE
Applying `scan` after `delay` will delay the initial value 

### ISSUE THREAD

**Issue by mbrandonw** [ReactiveX/RxJava#3387]
Consider the following observable:

```java
Observable.just(1)
  .delay(10, TimeUnit.Seconds)
  .scan(2, (accum, x) -> accum + x)
```

I would expect this to emit `2` immediately, and then 10 seconds later emit `3`. Instead it waits 10 seconds, and then emits `2` and `3` immediately.

Am I interpreting this incorrectly?

**Comment by artem-zinnatullin** [comment]
You're delaying emission of `just(1)`, then operator `scan()` does it's job and emits two values without delay.

Try:

```java
Observable
  .just(1)
  .scan(2, (accum, x) -> accum + x)
  .delay(10, SECONDS)
```

**Comment by akarnokd** [comment]
This is a bug with the `scan` operator emitting its initial value only when the first value arrived and has been fixed via #3171. It will be part of the next release.

**Comment by mbrandonw** [comment]
Thanks @akarnokd. I only just realized this issue is related to #3168, which I also filed.

So just to confirm, the expected behavior of `scan` is to emit the initial value immediately, and then the accumulated values as they come?

**Comment by akarnokd** [comment]
Exactly.

**Comment by mbrandonw** [comment]
perf thanks!
