### ISSUE TITLE
Protect 1.x and 2.x branches from direct pushes

### ISSUE THREAD

**Issue by artem-zinnatullin** [ReactiveX/RxJava#3409]
https://twitter.com/akarnokd/status/650429581573378048 :)

Here is the documentation about this feature of GitHub https://github.com/blog/2051-protected-branches-and-required-status-checks

**Comment by JakeWharton** [comment]
That tweet references a fast-forward, not a force push.

**Comment by artem-zinnatullin** [comment]
Yep, but GitHub Protected branch also prevents not only force pushes, but also direct fast-forward! (Only via PR)

**Comment by akarnokd** [comment]
I'd definitely support such protection, but the article mentions force pushes instead of any pushes outside the github gui.

**Comment by artem-zinnatullin** [comment]
It works even for non-force pushes.

Fast-forward pushing from terminal:
<img width="592" alt="screen shot 2015-10-04 at 18 24 55" src="https://cloud.githubusercontent.com/assets/967132/10268565/85b5d604-6ac5-11e5-9cb9-a3e8f4d712d8.png">

Trying to make change from GitHub UI:
<img width="979" alt="screen shot 2015-10-04 at 18 26 12" src="https://cloud.githubusercontent.com/assets/967132/10268567/93607142-6ac5-11e5-8d05-cd5553a376f9.png">


Just try to enable it :shipit:

**Comment by akarnokd** [comment]
It seems to work for some now. Closing.
