### ISSUE TITLE
OperatorDebounceWithTime needs volatile?

### ISSUE THREAD

**Issue by keinfarbton** [ReactiveX/RxJava#3412]
Hi

I'm not completely sure about, if this is a potential problem.
In rx.internal.operators.OperatorDebounceWithTime, there is DebounceState with a member boolean variable "emitting", which shall protect against a race condition.

Afaik this variable must be declared as volatile to ensure, the other thread reading this variable is really seeing it changed.

Frank

**Comment by davidmoten** [comment]
I've had a look at the source and it looks like all access to the emitting
field is synchronised so is thread safe. Do you have a particular problem
that led you suspect this code?

**Comment by keinfarbton** [comment]
Right, after more research, i see this is sufficient. Sorry for the noise.
