### ISSUE TITLE
Invalid marble diagram in javadoc for flatMap(collectionSelector, resultSelector)

### ISSUE THREAD

**Issue by tkowalcz** [ReactiveX/RxJava#3420]
Marble diagram here: http://reactivex.io/RxJava/javadoc/rx/Observable.html#flatMap(rx.functions.Func1, rx.functions.Func2)

suggests that resultSelector accepts originally emitted element (T) and stream produced by collectionSelector for this element (Observable<U>). 
In fact resultSelector operates on originally emitted element (T) and each element emitted by stream generated by collectionSelector (U) separately.

I would create pull request but don't know which tool you use to create marble diagrams. If it's just raster graphics then I can GIMP something up.

**Comment by DavidMGross** [comment]
The tool we use for making the marble diagrams is called OmniGraffle. You can find the source for our diagrams at https://raw.githubusercontent.com/wiki/ReactiveX/RxJava/images/rx-operators.graffle

**Comment by DavidMGross** [comment]
Fixed:
![flatMap()](https://raw.githubusercontent.com/wiki/ReactiveX/RxJava/images/rx-operators/mergeMap.r.png)
