### ISSUE TITLE
BehaviorSubject's subscriber doesn't receive initial value if using observeOn

### ISSUE THREAD

**Issue by adennie** [ReactiveX/RxJava#3421]
I have an object that exposes a `BehaviorSubject` as an `Observable`.  The `BehaviorSubject` has an inital value.  If the subscriber subscribes while specifying `observeOn()`, it doesn't receive the initial value, except for the special case where it specifies `observeOn(Schedulers.immediate())`.

Reproduced on 1.0.14.

Here's some sample code from a simple Android app that reproduces (also available as a complete project at https://github.com/adennie/BehaviorSubjectBug):

```
public class MainActivity extends AppCompatActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {

        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        Foo foo = new Foo();

        Log.i("BehaviorSubjectBug", "subscribing");
        Subscription sub = foo.getObservable()
                // works if observeOn not used
                //.observeOn(Schedulers.immediate()) // also works
                //.observeOn(AndroidSchedulers.mainThread()) // fails
                //.observeOn(Schedulers.io()) // fails
                .subscribe(new Action1<Integer>() {
                    @Override
                    public void call(Integer integer) {
                        Log.i("BehaviorSubjectBug", "received item: " + integer);
                    }
                });

        sub.unsubscribe();
    }

    private static class Foo {
        private Subject<Integer, Integer> subject = BehaviorSubject.create((Integer) 1);

        private Observable<Integer> getObservable() {
            return subject;
        }
    }
}
```

**Comment by akarnokd** [comment]
There is a race between `sub.unsubscribe()` and `observeOn()` so you may not receive that single value. You should see this if you add a small sleep before sub.

What would you like to achieve anyways?

**Comment by adennie** [comment]
Hmm, yes, you're right.  I was trying to create a simple demo app that would exhibit a BehaviorSubject problem I'm seeing, but it seems I oversimplified.  I'll close this and open a new one when I've got a better example.
