### ISSUE TITLE
Single.onErrorResumeNext

### ISSUE THREAD

**Issue by TastyPi** [ReactiveX/RxJava#3440]
Observable has a onErrorResumeNext to continue with a new Observable if onError is called. I'd like something similar for Single, so:

```java
Single<T> onErrorResumeNext(Single<? extends T> resumeSingle)

Single<T> onErrorResumeNext(Func1<? super Throwable, ? extends Single<? extends T>> resumeFunction)
```

Single already has onErrorReturn, it makes sense to have onErrorResumeNext as well.

**Comment by adennie** [comment]
related: https://groups.google.com/forum/#!topic/rxjava/vCMxB6CY88w

**Comment by artem-zinnatullin** [comment]
I'll work on this.

**Comment by artem-zinnatullin** [comment]
@akarnokd I can do it in 2 ways: 

1. Convert `Single` to `Observable` and `lift` already implemented and tested `OperatorOnErrorResumeNextViaFunction` and `OperatorOnErrorResumeNextViaObservable`.
2. Re-implement these operators for `Single`, it may give some performance boost, but adds two classes to the library.

I guess you'll vote for 2nd way, but I think it worth to ask :)

**Comment by akarnokd** [comment]
Frankly, I'm not satisfied with 1.x Single and how it tries to reuse Observable components; it leads to wrappers and un-wrappers and so on even for the trivial operators. If they were `retryWhen` then I'd say convert back and forth like I do with 2.x. So yes, I vote for option 2.

**Comment by artem-zinnatullin** [comment]
ok, no problem :)
