### ISSUE TITLE
Single.defer?

### ISSUE THREAD

**Issue by serandel** [ReactiveX/RxJava#3441]
Hi, this is a feature request por Single.defer(), analog to Observable.defer().

The idiom I've settled for now is

    Observable.defer(() -> Observable.just(produceValue())).toSingle()

But I find it very cumbersome and considerably more difficult to read that

    Single.defer(() -> Single.just(produceValue()))

Of course, I can be missing something, as I'm just adopting rx.Single in my codebase. :)

Thanks!

**Comment by akarnokd** [comment]
Hello. There is already a PR for this: #3433.

**Comment by serandel** [comment]
Sorry, I didn't see it.

El mar., 13 de octubre de 2015 17:56, David Karnok <notifications@github.com>
escribió:

> Hello. There is already a PR for this: #3433
> <https://github.com/ReactiveX/RxJava/pull/3433>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ReactiveX/RxJava/issues/3441#issuecomment-147758442>.
>
-- 

Sergio Delgado -- Serandel
mailto:serandel@gmail.com

Quoth the raven, 'Nevermore.'

'Ever tried. Ever failed. No matter. Try again. Fail again. Fail better.'
-- Samuel Beckett
