### ISSUE TITLE
1.x: Writing backpressure supporting operators

### ISSUE THREAD

**Issue by davidmoten** [ReactiveX/RxJava#3442]
We know that writing a custom operator is a very tricky business if we are not composing existing operators.

I'm particularly interested in implementing custom Operators that for each arriving emission of type `T` a state machine consumes the arrival and emits 0..\* items of type `R`.

I've raised examples of this in #3020 but didn't get any bites in terms of an assessment of `Transformers.stateMachine`. I've been using it for a few months and it has evolved both internally and in terms of its API signature. 

For  me this utility is the missing link for producing new operators (well, a certain class of operators). It is not very complex under the covers in that it just composes a bunch of existing operators but it is complex enough that its worth making a utility from. 

Using this operator I now have my own versions of operators like [`StringObservable.split`](https://github.com/davidmoten/rxjava-extras/blob/master/src/main/java/com/github/davidmoten/rx/internal/operators/TransformerStringSplit.java) and `StringObservable.decode` that support backpressure safely (unlike current versions in RxJavaString) and reasonably efficiently. What really sells me about the approach is that the code is almost identical so that backpressure support is not something that the developer need consider much for this class of problem.

Submissions by @stealthcode like `AsyncOnSubscribe` and `SyncOnSubscribe`  provide means of creating observables safely that support backpressure and are more efficient than just throwing `.onBackpressureBuffer` on the end. I'm interested in getting review of [`Transformers.stateMachine`](https://github.com/davidmoten/rxjava-extras/blob/master/src/main/java/com/github/davidmoten/rx/internal/operators/TransformerStateMachine.java) with the intent of submitting it into RxJava so if you've got a moment have a gander, thanks.

**Comment by akarnokd** [comment]
The thing I don't see is that what how is the 0..* amount determined; i.e., in the callback, should one call `onCompleted` or not to singal a batch is completed?

**Comment by davidmoten** [comment]
At the moment you don't need to call `onCompleted` because once the transition completes synchronously it is called for you on L92. 

It might be good to make a call to `onCompleted` in the transition terminate the entire stream (I've taken this approach with the ability to unsubscribe from the transition, and of course on error so that would be consistent).  That way the user doesn't have to think about signals on batch streams but think only of the overall stream.

**Comment by akarnokd** [comment]
Any new input on this issue?

**Comment by akarnokd** [comment]
Closing as 1.x is EOL.
