### ISSUE TITLE
Add delaySubscription(Observable<U>) overload?

### ISSUE THREAD

**Issue by JakeWharton** [ReactiveX/RxJava#3445]
Usage of `delaySubscription` has started popping up in our code base, and I've noticed that we always have to define a `Func0` simply to yield an observable that's either cold (in which case the function provides no value) or hot (in which case the function also provides no value). It's not clear to me why the function indirection was added in the first place as it's provided no data and `Observable.defer` could have served in its place.

I would like to propose adding an `Observable`-taking overload and replacing the `Func0` variant to instead wrap its given argument in `Observable.defer` before passing to `OnSubscribeDelaySubscriptionWithSelector`.

Being able to sneak this in before 1.0.15 / 1.1.0 would also be nice :grinning:

**Comment by akarnokd** [comment]
See #3447. I didn't touch the current `Func0` variant to avoid introducing unexpected effects to existing code.

**Comment by JakeWharton** [comment]
:+1: Thanks @akarnokd!

**Comment by akarnokd** [comment]
Fix merged.
