### ISSUE TITLE
My Ongoing Involvement

### ISSUE THREAD

**Issue by benjchristensen** [ReactiveX/RxJava#3453]
Since I have left Netflix and am now at Facebook, I want to provide some guidance on my involvement in this project going forward. 

My "day job" does not require use of RxJava right now, thus I can not allocate hours a day to the project. Even while I was at Netflix though, my time was being torn in different directions so over the past ~9 months I started to back out and allow the community to become more involved by adding committers and review processes not needing me. It has somewhat worked, but I have seen that without my day-to-day involvement in decision making, things have become much slower. I hope that the community can work together to improve that. 

In other words, I can not be counted on for timely code reviews, or for reading and responding to all issues coming through the project. However, I do intend on staying involved in the following ways:

#### 2.x Design

I intend on working with the community to finish defining the design and contracts of 2.x in this document -> https://github.com/ReactiveX/RxJava/blob/2.x/DESIGN.md 

#### 2.x Public API Review

As the community hardens the 2.x codebase, I'd like to review the public APIs and help validate the release candidates.

#### RxJava O'Reilly Book

@nurkiewicz is writing a book for O'Reilly about RxJava (https://twitter.com/tnurkiewicz/status/653616822818877440). I have accepted his invitation to be involved for a couple chapters, and for reviewing it (https://twitter.com/benjchristensen/status/653621165307510784).

#### Design Discussions

If there are design discussions about current or future code that someone would like me involved in, I'd be happy to do so. Just bring me into the conversation either through an @benjchristensen mention, or harass me on Twitter with a link to where I should involve myself. 

#### Broader Reactive Community

I am not yet done with this space and fully expect to be involved in broader discussions and applications of "reactive", async, push, and push-pull patterns, either personally or professionally for a while still.

**Comment by akarnokd** [comment]
Thanks for all the good work Ben!
