### ISSUE TITLE
High CPU usage after time changed on device

### ISSUE THREAD

**Issue by tehmur** [ReactiveX/RxJava#3461]
On Android using this library, if the user changes the system time, there is a huge spike in the CPU usage emanating from the RXComputationThreadPool, without any expensive calls being made to the RX library.

**Comment by akarnokd** [comment]
Thanks for reporting. It has been already reported in #2943.

**Comment by tehmur** [comment]
Thanks for your swift reply.

Do we have a feel of when we might have a fix for this on v1.x?

**Comment by artem-zinnatullin** [comment]
// one of the possible fixes — Abstraction for Clock #3295.

**Comment by nachodeh** [comment]
I also experienced this issue and it's quite serious. Will this be fixed soon?

**Comment by akarnokd** [comment]
I've proposed a fix for this issue in #3467. I don't know if and when this can get into a release.
