### ISSUE TITLE
when exception is thrown in subscriber `onNext`, `doOnTerminate` actions are not called

### ISSUE THREAD

**Issue by weefbellington** [ReactiveX/RxJava#3463]
Here is a unit test that demonstrates the issue I'm seeing:

https://gist.github.com/weefbellington/7f7e2a0a19ea80357f5f

##### Problem description

An exception is thrown inside of `onNext`. The `onError` callback fires, but the `doOnTerminate` callback does not fire. `doFinally` exhibits the same issue.

##### Expected behavior

From the documentation:

> The doOnTerminate operator registers an Action which will be called just before the resulting Observable terminates, whether normally or with an error.

I would expect `doOnTerminate` to always be called, even if an exception is thrown inside the subscriber callback.

**Comment by weefbellington** [comment]
So far, I have only seen this with hot observables. Replacing the PublishSubject with a cold observable (`Observable.just(null)`) makes the test pass.

**Comment by akarnokd** [comment]
Hi. What happens is that `subscribe` wraps your subscriber into a `SafeSubscriber` which catches the NPE and calls onError. `DoOnTerminate` can only react to errors coming from upstream. Some operators may bounce an uncaught exception back down so `DoOnTerminate` receives it.

**Comment by weefbellington** [comment]
> Some operators may bounce an uncaught exception back down so DoOnTerminate receives it.

So what you are saying is that a downstream error may cause an upsteam `doOnTerminate` action to fire, or it may not, depending on how the operator does error handling? That makes sense, even if it's a little unintuitive.

If I want to ensure that an Action is always called when an observable terminates, whether with onCompleted or onError, what do you suggest? Something like `subscribe(onNext, onTerminate, onTerminate)`?

**Comment by akarnokd** [comment]
That is a way. Alternatively, catch the exception in `onNext` manually and invoke the same terminal action as with `doOnTerminate`.

**Comment by weefbellington** [comment]
Thanks for the explanation! Feel free to close this issue.

**Comment by cxzhang2** [comment]
@akarnokd is there a way to throw the downstream error back up stream?

context: I have some generic error handlers up stream.

**Comment by akarnokd** [comment]
No. Have your error handlers downstream.
