### ISSUE TITLE
Document getting snapshots in the wiki

### ISSUE THREAD

**Issue by simonbasle** [ReactiveX/RxJava#3471]
While browsing around a bit I found out that snapshots were indeed published to JFrog's OSS Artifactory and could be added to a Maven project using the following repository configuration in the `pom.xml`:

```xml
<repository>
  <snapshots />
  <id>snapshots</id>
  <name>libs-snapshot</name>
  <url>http://oss.jfrog.org/artifactory/libs-snapshot</url>
</repository>
```

Maybe it would be worth it to add that information (plus instructions for Gradle/SBT/Ivy) in a "*Getting Snapshots*" section of the "`Getting Started`" wiki page?

**Comment by akarnokd** [comment]
Updated: https://github.com/ReactiveX/RxJava/wiki/Getting-Started

Let me know if it needs further changes.

**Comment by simonbasle** [comment]
I think it should be fine, thanks!
