### ISSUE TITLE
Flatmap Single into Observable and ignore errors

### ISSUE THREAD

**Issue by passsy** [ReactiveX/RxJava#3472]
I have UI observable which should work as long as my UI lives. When my UI emits I create a network request which could be an Observable or a Single. A Single fits best for a network call.

```java
RxView.clicks(myButton)
    .flatMap(v - > networkRequest())
    .subscribe(data -> showSomething(data),
            e -> {
                // should only be called when the RxView.clicks() throws. 
                // should not be called for network errors
            });
```

When using an Observable I would use `onErrorResumeNext` returning `Observable.empty()` to prevent errors coming from the network request going into my UI Observable and calling `onError` because the UI Observable should life forever:

```java
Observable networkRequest() {
    mApiService.fireActionObservable()
        .onErrorResumeNext(throwable -> {
            // somehow handle error here
            return Observable.empty();
     });
}
```

This, in my opinion, elegant way does not work for Single because no `Single.empty()` exists.

```java
Single networkRequest() {
    mApiService.fireActionSingle()
        .onErrorResumeNext(throwable -> {
            // somehow handle error here
            return Single.empty(); // <-- does not exist. I have to call success or error :/
     });
}
```

`Single.onErrorResumeNext` is btw only available in 2.x

Converting my `Single` to an `Observable` seems wrong, because the network request is a `Single`!

**Comment by akarnokd** [comment]
`Single.empty()` doesn't make sense because `Single` has to emit either an `onSuccess` or an `onError`. The best you can do is to return have a `Single.just()` with a normal value that represents emptiness.

Generally, this is why I'm skeptic about `Single` and `Completable` because `Observable` can "emulate" both and the overhead in true async use is negligible.

**Comment by passsy** [comment]
My current solution wraps my Singles:

```java
    public static <T> Observable<T> onErrorResumeNext(final Single<T> single,
            final Observable<? extends T> resumeSequence) {
        return single.toObservable().onErrorResumeNext(resumeSequence);
    }

    public static <T> Observable<T> onErrorResumeNext(final Single<T> single,
            final Func1<Throwable, ? extends Observable<? extends T>> resumeFunction) {
        return single.toObservable().onErrorResumeNext(resumeFunction);
    }
```


@benjchristensen what happened to the [initial idea](https://github.com/ReactiveX/RxJava/issues/1594#issuecomment-101300655) of heaving a `Single` with 3 final states?

> A Single will always behave in one of 3 ways:

> 1) respond with an error
2) never respond
3) respond with a success

I was hoping a `Single` is a `Observable` where I don't have to care about multiple items. Nothing more. Like `Observable#single()` but with zero item support and type safetyness.

**Comment by akarnokd** [comment]
@artem-zinnatullin I'm starting to loose what is implemented where. Do you work on `Single.onErrorResumeNext(Func1)`?

**Comment by artem-zinnatullin** [comment]
@akarnokd damn… will submit PR today/tomorrow!

**Comment by MalekKamel** [comment]
My solution:
RxView.clicks(myButton)
    .flatMap(v - > networkRequest())
    .compose(exceptionHandling())
    .subscribe(data -> showSomething(data),
            e -> {
                // Now you should remove this lambda as it will never be called.
            });
Final: 
RxView.clicks(myButton)
    .flatMap(v - > networkRequest())
    .compose(exceptionHandling())
    .subscribe(data -> showSomething(data));
exceptionHandling:
   protected  <T> ObservableTransformer<T, T> exceptionHandling() {
        return observable ->
                observable
                        .doOnError(t ->{ /* handle error here */})
                        .retry(); // Ignore error to keep subscription.
    }
