### ISSUE TITLE
retryWhen does not resubscribe to its immediate parent Observable

### ISSUE THREAD

**Issue by chefhoobajoob** [ReactiveX/RxJava#3473]
Gist is here: https://gist.github.com/chefhoobajoob/eb473f26f7ad342be28f

I'm finding that if you have a processing chain like so:

rootObservable()
.retry()
.flatMap()
.retryWhen()
.subscribe()

...the retryWhen() operator will not resubscribe to the Observable produced by the flatMap() operator above,  but will instead resubscribe to the rootObservable in the chain.

I did not expect this, and it seems like it could be a defect, either in code or in documentation.

Please advise, if this is not a defect of any kind, how to achieve what I would like, which is for a way to retry the output from the flatMap() operator above.

Thanks!

**Comment by akarnokd** [comment]
The retry works as expected. What do you mean by resubscribe to flatMap() only? You should retry inside the function and not return an Observable.error().

**Comment by chefhoobajoob** [comment]
The problem isn't with the retry(). That does work as expected, as you say.

The problem is with the retryWhen() operator.

As I understand it, the source Observable for the retryWhen() operator in this chain is the Observable that is returned from the flatMap() operator, not the root Observable at the top of the chain.

According to the documentation:

> The retryWhen operator is similar to retry but decides whether or not to resubscribe to and mirror **the source Observable** by passing the Throwable from the onError notification to a function that generates a second Observable, and observes its result to determine what to do. If that result is an emitted item, **retryWhen resubscribes to** and mirrors **the source** and the process repeats; if that result is an onError notification, retryWhen passes this notification on to its observers and terminates.

So, I'm expecting retryWhen() to re-subscribe to the Observable emitted by the flatMap() operator, but it isn't. That's why I think this is a possible defect.

**Comment by akarnokd** [comment]
FlatMap flattens the error as well, breaking the entire chain; retryWhen detects that the error and triggers a resubscription which reestablishes the whole chain before retryWhen. Perhaps you should apply retryWhen to the result of defer inside the flatMap on line 46.

**Comment by chefhoobajoob** [comment]
Do you mind walking me through this? I'm still learning the library, so want to get my knowledge solid here.

Here's my understanding of the behavior in the gist - please let me know the step where I'm going wrong:

1) The root observable will emit a single, non-error result.
2) The retry operator will forward that non-error result to flatMap()
3) flatMap() will look at the value of the non-error result from the root and emit a deferred Observable (line 35) that will emit an error on the first few subscribe attempts. This is the source Observable for the retryWhen() operator
4) retryWhen() will receive the first error emission from the Observable on line 53
5) retryWhen() inspects the error emitted by flatMap() and determines that it's one for which a retry can be attempted (line 54), so it emits a timer Observable (line 56)
6) after 1 second, the timer emits a non-error value to retryWhen(), which then (I have been assuming) re-subscribes to its source Observable, which is the deferred Observable emitted by flatMap() from line 53.
7) At this point, I really don't know what is happening, but it seems to have the effect of cascading the retry backwards to the root Observable, which is the thing I was not expecting.

**Comment by chefhoobajoob** [comment]
I'm trying your suggestion to move the retryWhen() - but I don't fully understand why that would work and the current version doesn't. Thank you for your feedback, and if you are able to set me straight on my understanding above, that would be a great help.

**Comment by akarnokd** [comment]
Flatmap flattens your deferred observable into a single stream of values, including errors so retryWhen won't see you observable but only its events. If you want to retry the individual observable then you should apply retryWhen to it directly:

```
AtomicInteger calls = new AtomicInteger();

Observable.range(1, 10)
.flatMap(v -> {
    return Observable.defer(() -> {
        if (calls.getAndIncrement() % 2 == 0) {
            return Observable.just(1);
        } else {
            return Observable.error(new RuntimeException());
        }
    }).retryWhen(...);
})
.subscribe(...)

**Comment by chefhoobajoob** [comment]
Ok - this is making sense now - the consumer of flatMap sees emitted values, not observables.  Thank you for the feedback. You can close the issue if you like.
