### ISSUE TITLE
Backpressure on OperatorZip doesn't work when the observable is created using toList()

### ISSUE THREAD

**Issue by MaltAlex** [ReactiveX/RxJava#3492]
I've written an "SortedMerge" operator, which is used to orderly merge several ordered observables. The operator is based on [OperatorZip](https://github.com/ReactiveX/RxJava/blob/f2410f88dc28c1013f48754606e38507e493245f/src/main/java/rx/internal/operators/OperatorZip.java) except for several key differences:

 1. Instead of passing an array of items into a zip function the items are compared using a comparator and only the smallest one is emitted.
 2. After emissions, `requestMore` is called only on the observable from which the minimum was taken, and only its buffer's head is removed. The others are left untouched for future comparison. So no items are lost.
 3. Additional type safety is added since the types of the incoming observables is known.

(I can contribute the operator to the project if anyone's interested).

During testing, I stumbled upon a use case that failed for my operator, and it turns out that the same problem exists in the original Zip.

Take a look at the following observables. First, o1:

	Observable<Integer>[] osArray = new Observable[] { Observable.range(0, 10), Observable.range(0, 10) };
	Observable<Observable<Integer>> os = (Observable<Observable<Integer>>) Observable.from(osArray);
	Observable<Integer> o1 = Observable.zip(os, (a) -> 0);

Second, o2:

	Observable<Integer> o2 = Observable.zip(Observable.range(0, 10), Observable.range(0, 10), (a, b) -> 0);

According to my understanding, both should work in exactly the same way. However, their response to requests from the subscriber is different:

	TestSubscriber<Integer> sub1 = new TestSubscriber<>(5);
	TestSubscriber<Integer> sub2 = new TestSubscriber<>(5);
	
	o1.subscribe(sub1);
	o2.subscribe(sub2);
	
	sub1.requestMore(5);
	sub2.requestMore(5);
	
	sub1.awaitTerminalEvent(1, TimeUnit.SECONDS);
	sub2.awaitTerminalEvent(1, TimeUnit.SECONDS);
	
	System.out.println(sub1.getOnNextEvents().size());
	System.out.println(sub2.getOnNextEvents().size());

produces this response:
     5
     10

Which is exactly what happened to my SortedMerge operator. After poking at the operator for a while, it turned out that the issue can be solved by changing the construction of the Zip subscriber ZipSubscriber from this:

    public ZipSubscriber(Subscriber<? super R> child, Zip<R> zipper, ZipProducer<R> producer) {
            super(child);
            this.child = child;
            this.zipper = zipper;
            this.producer = producer;
        }

to this:

    public ZipSubscriber(Subscriber<? super R> child, Zip<R> zipper, ZipProducer<R> producer) {
            super();
            this.child = child;
            this.zipper = zipper;
            this.producer = producer;
        }

Which seems to make sense, but I'm not sure that I understand Rx's backpressure well enough to know whether that's indeed the right solution.

**Comment by akarnokd** [comment]
Hello and thanks for the in-depth analysis. What happens is that the child is caputed by `ZipSubscriber` and when it receives its `Producer` from `toList`, that also gets forwarded to child which overwrites the `ZipProducer` and thus no further requests get accounted. The fix is posted in #3493

Ordered merging comes up from time to time on StackOverflow; you can post a PR for it but frankly, if Netflix doesn't need one urgently, it can take a long time to get it approved.

**Comment by MaltAlex** [comment]
Thanks. That's pretty much what I suspected.

So if I understand correctly, your solution was to disconnect the child from the backpressure chain, but add the `ZipSubscriber` to its subscription list so it'll know whether the downstream is subscribed.

**Comment by akarnokd** [comment]
Yes. I've fixed like dozens of such bugs before; it is a design shortcoming of `Subscriber`.

**Comment by davidmoten** [comment]
@MaltAlex re your sorted merge operator. You can find one at [rxjava-extras](https://github.com/davidmoten/rxjava-extras) as well (`Transformers.orderedMergeWith`) with almost complete test coverage (for what that's worth). Even if you don't use it the testing strategy might be useful to you:

* test ordered merge of all pairs of sorted sets taken from a Power Set of numbers from 1..n, perform for n=0 to 10
* do the above synchronously and asynchronously

The operator I made requires backpressure supporting sources but does not support backpressure itself and would be combined with `.onBackpressureXXX`.

I think @akarnokd has one of these floating around as well but I don't know if it has unit tests.

**Comment by akarnokd** [comment]
I [have one](https://gist.github.com/akarnokd/c86a89738199bbb37348) that supports backpressure but without unit tests.

**Comment by davidmoten** [comment]
I'll have a look at your SortedMerge @akarnokd and beef up unit tests
(there were some with your gist)

**Comment by MaltAlex** [comment]
@davidmoten I looked at your implementation before going forward with my own. There were a few details in the implementation that I couldn't figure out, plus the lack of backpressure support was a complete deal breaker in my case. That's why I modified the Zip operator to fit my needs. Its functionality is almost identical.

So now I have one of those operators too, and the only test that failed for it (erm... so far) was a test that failed for the original Zip as well (hence this issue). I might put it on github sometime later.

**Comment by davidmoten** [comment]
would be good to see your implementation @MaltAlex. Operators are complex and are hard to test due to async possibilities but I'll chuck the best candidate in a *rxjava-extras* release. The candidate from @akarnokd will have a good chance of winning out because he knows this domain so well!

**Comment by davidmoten** [comment]
The implementation from @akarnokd passes my power set tests. Do you have any plans for it @akarnokd? Do you mind if I throw it in to *rxjava-extras* (I'd make clear your authorship in the source)?

**Comment by akarnokd** [comment]
No plans, go ahead.

**Comment by akarnokd** [comment]
Fix delivered with 1.0.16. The discussion about sorted merge can continue in a different thread if you wish.
