### ISSUE TITLE
Create operator for delaying each item in a List 

### ISSUE THREAD

**Issue by greenspand** [ReactiveX/RxJava#3505]
I noticed there is no operator for delaying each item in a list with a specific time Interval and still getting the entire list one delayed item at a time.
There is throttle(), debounce(), timer(), interval(), delay(), but none of these work. 
I'm not an rx guru, I would implement it myself. What do you think?

**Comment by akarnokd** [comment]
We usually zip the source with a timer which gives a delayed items relative to each other:

```java
source.zipWith(Observable.timer(100, TimeUnit.MILLISECONDS).onBackpressureDrop())...
```

I never felt the need for such operator, but perhaps there are others in need as well. Or maybe @davidmoten has it already in rxjava-extras.

**Comment by greenspand** [comment]
Let's say I have an ArrayList of several elements, how would it in this case look like if I were to delay each item 5 seconds?

**Comment by akarnokd** [comment]
Emit each item 5 seconds after the previous item:
```java
List<Integer> list = new ArrayList<>(Arrays.asList(1, 2, 3, 4, 5, 6));

Observable
  .interval(5, TimeUnit.SECONDS)
  .map(i -> list.get(i.intValue()))
  .take(list.size())
  .toBlocking()
  .subscribe(System.out::println)
;
```

Emit everything after 5 seconds passed:
```java
Observable
  .from(list)
  .delay(5, TimeUnit.SECONDS)
  .toBlocking()
  .subscribe(System.out::println);
```

**Comment by greenspand** [comment]
Awesomr it works gracefully. Thx for the input.

**Comment by sourabhv** [comment]
Alternatively, you can do something like this

```
Observable.zip(
                Observable.interval(1000, TimeUnit.MILLISECONDS).take(5),
                Observable.fromArray(1, 2, 3, 4, 5),
                (aLong, integer) -> integer)
                .subscribe(System.out::println);
```

**Comment by yaircarreno** [comment]
Here another alternative :)

```java
List<String> letters = new ArrayList<>(Arrays.asList("a", "b", "c", "d"));

Observable.fromIterable(letters)
                .concatMap(item -> Observable.interval(1, TimeUnit.SECONDS)
                        .take(1)
                        .map(second -> item))
                .subscribe(System.out::println);
```

**Comment by aballano** [comment]
Great stuff @yaircarreno!! @akarnokd Please note that this solution is the only one that works also with Hot observables, imagine this scenario:

```
clickSubject.concatMap { item ->
    //Updated: `interval + take 1` can be optimized to just `timer`
    Flowable.timer(2, TimeUnit.SECONDS) 
        .map { item }
}

// Several seconds or minutes later

clickSubject.onNext(...)
```

This way the timer is not triggered until the subject emits, which wasn't covered with the zip operator as this one is not invoking the interval lazily :+1: 

RxMarbles:
<details>

![image](https://user-images.githubusercontent.com/3294640/58755404-c0e22700-84e3-11e9-81a6-19828745ad0f.png)
</details>

PD: Sorry for reviving the thread, but this info might be useful for others looking like me for this behaviour :pray:
