### ISSUE TITLE
OSGi install fails because sun.misc package is not exported via Felix

### ISSUE THREAD

**Issue by dzharikhin** [ReactiveX/RxJava#3516]
Hi!, trying to install bundle I get this one
org.osgi.framework.BundleException: Unresolved constraint in bundle io.reactivex.rxjava [274]: Unable to resolve 274.0: missing requirement [274.0] package; (package=sun.misc)
        at org.apache.felix.framework.Felix.resolveBundle(Felix.java:3409)
        at org.apache.felix.framework.Felix.startBundle(Felix.java:1709)
        at org.apache.felix.framework.BundleImpl.start(BundleImpl.java:905)
        at org.apache.felix.framework.BundleImpl.start(BundleImpl.java:892)

I see there is fallback implemented in src if Unsafe is unavailable, 
but in MANIFEST.MF package sun.misc is still strongly required.
It would be nice to make resolution:=optional for this package because its absence breaks nothing inside

**Comment by 2686747** [comment]
To append packages to the default set of exported system packages add needed value to this propertie:
 **org.osgi.framework.system.packages.extra=sun.misc**

**Comment by dzharikhin** [comment]
It is wrong way. This package is not public any way. And that package import is really optional - I see there is fallback implemented already)

**Comment by nedtwigg** [comment]
You can also fix this by adding [com.diffplug.osgi:com.diffplug.osgi.extension.sun.misc:0.0.0](http://search.maven.org/#artifactdetails%7Ccom.diffplug.osgi%7Ccom.diffplug.osgi.extension.sun.misc%7C0.0.0%7Cjar) from MavenCentral.  See [here](https://github.com/diffplug/osgiX) for more details on  extension bundles.

**Comment by akarnokd** [comment]
Thanks for the help @2686747 and @nedtwigg !
