### ISSUE TITLE
Support Observable.from(array_of_primitives)

### ISSUE THREAD

**Issue by tomkur** [ReactiveX/RxJava#3518]
It seems that it is currently impossible to create an `Observable` from an array of primitives, e.g.:

```java
char[] chars = "some string".toCharArray();
Observable.from(chars); //does not compile
```

Is this a conscious decision?

**Comment by vanniktech** [comment]
Could not you just use `Observable.from(Arrays.asList(chars))` ?

**Comment by tomkur** [comment]
There's a gotcha with this approach. ```Arrays.asList(chars);``` will return a one-element list containing char array `chars` instead of list of characters from `chars`. So it's not what I'd hope for and I can't use it with `Observable` the way I'd like to

**Comment by abersnaze** [comment]
We named it just.

**Comment by akarnokd** [comment]
A proper support would require specializing RxJava types to primitive types which is quite cumbersome for minimal benefit.

**Comment by tomkur** [comment]
I probably didn't make myself clear. I'd like to have an option to observe a sequence of characters in a String, so that:
```java
char[] chars = "some string".toCharArray();
Observable.from(chars).subscribe(curr -> System.out.println("next: " + curr)); //currently does not compile
```
outputs:

```
next: s
next: o
next: m
next: e
next:  
next: s
next: t
next: r
next: i
next: n
next: g
```

The options you mentioned work the following way:
```java
Observable.from(Arrays.asList(chars)).subscribe(curr -> System.out.println("next: " + curr)); 
```

outputs:
```
next: [C@6193b845
```

and the same for the other case

```java
Observable.just(chars).subscribe(curr -> System.out.println("next: " + curr));
```

outputs:
```
next: [C@1f17ae12
```

**Comment by akarnokd** [comment]
```java
char[] chars = "string".toCharArray();

Observable.range(0, chars.length).map(i -> chars[i]).subscribe(...)
```

**Comment by tomkur** [comment]
@akarnokd I can understand it as long as it's a conscious decision. Note however that without this support it's easy to fall for a trap, such as:
```java
Observable.from(Arrays.asList(chars))
```
which as described above does not do what might seem most intuitive.
In Java typically you'll have many overloads of methods accepting array of primitive types, e.g.
```
Arrays.copyOf(T[] original, int newLength)
Arrays.copyOf(boolean[] original, int newLength)
Arrays.copyOf(byte[] original, int newLength)
Arrays.copyOf(char[] original, int newLength)
//and others
```

**Comment by tomkur** [comment]
@akarnokd regarding your example - sure, it's doable, I'm just asking to facilitate usage.

**Comment by akarnokd** [comment]
Such source factory methods doesn't have to be on the `Observable` itself so you can have your own class with `from` in it. You can take the `OnSubscribeFromArray` [implementation](https://github.com/akarnokd/RxJava/blob/FromArray1x/src/main/java/rx/internal/operators/OnSubscribeFromArray.java) of #3477 and change the array type at your leisure.

**Comment by ultraon** [comment]
Another way to do it: 
`Observable.fromArray("string".split("")).map(s -> s.charAt(0)).subscribe(...)`
