### ISSUE TITLE
synchronous sample with time

### ISSUE THREAD

**Issue by davidmoten** [ReactiveX/RxJava#3527]
Just read this 

http://stackoverflow.com/questions/33693958/rxjava-sample-is-cpu-intensive

and it struck me that we should be able to use `sample(long, TimeUnit, scheduler)` with a synchronous scheduler like `Schedulers.immediate`. At the moment this doesn't work (the stream hangs because a worker for a synchronous scheduler has been scheduled periodically and the operator never returns the upstream subscriber). 

I'd like to get this working and in `OperatorSampleWithTime` thought to check the `scheduler` parameter to see if it is an instance of `ImmediateScheduler` or `TrampolineScheduler` and offer a path that just accepts emissions and forwards them if the specified interval has passed since the last emission. We would still hang if provided a custom synchronous `Scheduler`  but I doubt this is a use case to be expected (?).

Before I knock up a PR are people happy with this approach?

**Comment by akarnokd** [comment]
I find `Schedulers.immediate` nothing but trouble and a relic from Rx.NET. Making `sample` synchronous doesn't make sense as it will block its incoming source for the waiting duration.

**Comment by davidmoten** [comment]
>Making sample synchronous doesn't make sense as it will block its incoming source for the waiting duration.

I'm suggesting not using a scheduler at all when the passed scheduler is synchronous.

**Comment by akarnokd** [comment]
You mean by checking `System.currentTimeMillis()` and dropping values that arrived within the timeframe?

**Comment by davidmoten** [comment]
yep

**Comment by davidmoten** [comment]
The main difference between sampling synchronously and asynchronously is this:

* Async sample reports the last emission from each time frame and reports that emission very close to the frame end regardless of when in the frame the emission occurred
* Sync sample reports the first emission from each time frame and reports it on arrival (no wait). This means that it's possible for an emission to be emitted half way through the frame if the source is quietish.

For a fast emitting source this really won't make much difference and I wonder why `sample` is by default asynchronous (with it's associated overhead including relying on a possibly busy scheduler) instead of the simpler synchronous option. 

For my purposes I use a synchronous version (not part of the API).

Can people mention here what use cases they have that are best served by the async version? (I'm wondering if sync version should be default in v1/v2).

**Comment by akarnokd** [comment]
The problem with the synchronous version that it changes the emission pattern from regular to irregular since you can only emit values if the upstream emits a value. There is also the problem what value to emit once it has been determined the time window has elapsed (the last or the current).

**Comment by abersnaze** [comment]
The synchronous sampling sounds like `throttleFirst()`? I wonder if we are missing an opportunity for composition.  Does `throttleFirst()` exist because `concat(window(...).map(win -> win.first()))` is too slow?

**Comment by davidmoten** [comment]
>The problem with the synchronous version that it changes the emission pattern from regular to irregular since you can only emit values if the upstream emits a value. 

I just looked at the source and it appears to me that `sample` doesn't emit if  no new upstream value has been emitted. It's regularity is dependent on the regularity of the source.

>There is also the problem what value to emit once it has been determined the time window has elapsed (the last or the current).

As mentioned above in synchronous version you select first emission in each time window.

**Comment by davidmoten** [comment]
@abersnaze `throttleFirst` is indeed quite similar to this synchronous sample suggestion and is almost what I'm after except that the time window restarts from the time of each emission to downstream. See the extract below from `OperatorThrottleFirst`:

```java
@Override
            public void onNext(T v) {
                long now = scheduler.now();
                if (lastOnNext == 0 || now - lastOnNext >= timeInMilliseconds) {
                    lastOnNext = now;
                    subscriber.onNext(v);
                } 
            }
```

This means that the time window can gradually offset and produce results not consistent with the javadoc for `throttleFirst`:

>Returns an Observable that emits only the first item emitted by the source Observable during sequential time windows of a specified duration, where the windows are managed by a specified Scheduler.

In particular the current implementation of `throttleFirst` allows any time window to extend right so that the time windows are sequential but of duration potentially longer than the specified duration. I'll raise a PR for this fix (feel free to talk me out of it).

**Comment by akarnokd** [comment]
Do you want to pursue this issue with `sample` further?

**Comment by akarnokd** [comment]
I'm closing this for now. If you have further input on the issue, don't hesitate to reopen this issue or post a new one.
