### ISSUE TITLE
Adjust backpressure buffer (onBackpressureLatest/observeOn used)

### ISSUE THREAD

**Issue by Diolor** [ReactiveX/RxJava#3533]
RxJava 1.0.16:

I have an `interval()` which emits items (created in `computation` thread) with a rate of e.g. 100ms.
I then change the thread and my scheduler can consume with are rate of 1s and requests 1 item per time.

(Android) code:
```java
interval(0, 100, TimeUnit.MILLISECONDS) // computation thread
		.doOnNext(aLong -> wtf("Interval onNext", String.valueOf(aLong)))
		.onBackpressureLatest()
		.observeOn(AndroidSchedulers.mainThread())
		.subscribe(new Subscriber<Long>() {

			@Override
			public void onStart() {Consumed
				super.onStart();
				request(1);
			}

			@Override
			public void onCompleted() {

			}

			@Override
			public void onError(Throwable e) {
				e.printStackTrace();
			}

			@Override
			public void onNext(Long aLong) {
				try {
					Thread.sleep(1000);
					wtf("Consumed", String.valueOf(aLong));
					request(1);
				} catch (InterruptedException e) {
					e.printStackTrace();
				}
			}
		});
```

The code above will print:

```
Interval onNext: 0
Interval onNext: 1
    ...
Interval onNext: 10
Consumed: 0
Interval onNext: 11
// and after a while:
Interval onNext: 162
Consumed: 15
Interval onNext: 163
    ...
Interval onNext: 173
Consumed: 162
Interval onNext: 174
```

---

##### Feature question/proposal:
The jump form "Consumed 15" to "324" is because the RxRingBuffer.SIZE in Android is 16. The only way to make it lower number is to create a new `OperatorObserveOn` which requests 1 instead of the 16. Which is ugly solution. Any thoughts on that?

---

##### Question:
Even if my new "OperatorObserveOn" which requests only 1 item (described above) is used instead of the observeOn, then the "Consumed" will not be a sequence of 16 but a "more real time-ish" result:

```
Interval onNext: 0
    ...
Interval onNext: 10
Consumed: 0
Interval onNext: 11
    ...
Interval onNext: 20
Consumed: 10
Interval onNext: 21
    ...
Interval onNext: 30
Consumed: 20
```
 
Still, the "Consumed" is receiving the emition of the last "Inverval onNext". Is the lock in `OperatorOnBackpressureLatest.LatestEmitter` working as expected?
Is something like "as soon as my subscriber requests I want the really latest object - drop the previous ones" with RxJava? The example below will look like the expected behavior. Assuming always that we have a slower consumption that object generation and different threads. 

```
Interval onNext: 0
    ...
Interval onNext: 10
Consumed: 10
Interval onNext: 11
    ...
Interval onNext: 20
Consumed: 20
Interval onNext: 21
    ...
Interval onNext: 30
Consumed: 30
```

---
Thanks!

**Comment by akarnokd** [comment]
The operator `onBackpressureLatest` can introduce disontinuity, especially if the drain happens on another thread and the latest value keeps changing underneath even if there are plenty of requests.

The javadoc states this:

> Note that due to the nature of how backpressure requests are propagated through subscribeOn/observeOn, requesting more than 1 from downstream doesn't guarantee a continuous delivery of onNext events.

**Comment by akarnokd** [comment]
I don't know if `observeOn` will expose its prefetch amount in 1.x.

I'm closing this old question for now. Let me know if you need further assistance.
