### ISSUE TITLE
SerializedSubject slow multi-threading

### ISSUE THREAD

**Issue by krisskross** [ReactiveX/RxJava#3534]
```SerializedSubject``` is really slow when multiple threads are banging on it concurrently. I'm guessing because its ```Observer.onNext``` is synchronized.

Are there any way recommended ways to create highly concurrent and thread safe Subjects?

I've tried ThreadLocal subjects which is quite nice, but require quite some code effort. You could also stick a MPSC queue infront but that would defeat the purpose of RxJava.

**Comment by akarnokd** [comment]
Any concurrency structure can be easily overwhelmed if there are more producers to it than consumers.

What is your use case where you encounter such high contention?

**Comment by krisskross** [comment]
A log buffer for example, where multiple threads writes sequentially to the same file on disk.

**Comment by akarnokd** [comment]
You could try and buffer values before the subject to reduce contention.

**Comment by krisskross** [comment]
The only thing I can think of is using a MPSC queue and drain it periodically outside of RxJava?

**Comment by akarnokd** [comment]
Or you could try the LMAX Disruptor for this.

**Comment by krisskross** [comment]
Maybe another Subject/Observer implementation backed by MpscLinkedAtomicQueue would also be feasible?

**Comment by akarnokd** [comment]
I did some benchmarks some time ago and for 2-3 concurrent senders, there was no clear winner between an Mpsc serializer and a synchronized serializer. The first has node allocation cost and the second has a likelihood for blocking.

**Comment by krisskross** [comment]
Hmm. Maybe because of the low number of senders. Let me run a few test and get back.

**Comment by krisskross** [comment]
Implementing a MpscSubject was a bit harder than expected so instead I made a offer/poll JMH test for ```synchronized(ArrayList)```, ```MpscLinkedAtomicQueue``` and ```ConcurrentLinkedQueue``` running a single consumer thread and 4 producer threads.

https://gist.github.com/krisskross/ce6af3f2a0dbecf500ad

```
Benchmark            Mode  Cnt         Score           Error  Units
Mpsc.conc            avgt    5      1501.816 ±       120.254  ns/op
Mpsc.conc:concOffer  avgt    5      1768.706 ±       145.273  ns/op
Mpsc.conc:concPoll   avgt    5       434.255 ±        28.040  ns/op
Mpsc.mpsc            avgt    5       979.540 ±       207.045  ns/op
Mpsc.mpsc:mpscOffer  avgt    5      1155.358 ±       250.301  ns/op
Mpsc.mpsc:mpscPoll   avgt    5       276.268 ±        49.358  ns/op
Mpsc.sync            avgt    5  61919852.786 ± 327568809.819  ns/op
Mpsc.sync:syncOffer  avgt    5  64666466.042 ± 430190427.169  ns/op
Mpsc.sync:syncPoll   avgt    5  50933399.762 ± 428632155.573  ns/op
```

I guess the test does not exactly mirror the use case for ```SerializedSubject``` but at least it gives a hint. 

If you still have the MpscSubject code you mentioned I could give it a try. Or if you could briefly explain how it was implemented.

**Comment by akarnokd** [comment]
It is the standard queue-drain approach:

```java
public final class MpscObserver<T> implements Observer<T> {

    volatile boolean done;
    Throwable error;
    final AtomicInteger wip;
    final Observer<? super T> actual;
    final Queue<T> queue;

    public MpscObserver(Observer<? super T> actual) {
        this.actual = actual;
        this.wip = new AtomicInteger();
        this.queue = new MpscLinkedAtomicQueue<T>();
    }

    @Override
    public void onNext(T value) {
        queue.offer(value);
        drain();
    }

    @Override
    public void onError(Throwable e) {
        error = e;
        done = true;
        drain();
    }

    @Override
    public void onCompleted() {
        done = true;
        drain();
    }

    void drain() {
	    AtomicInteger wip = this.wip;
        
		if (wip.getAndIncrement() != 0) {
            return;
        }
		
		final Observer<? super T> a = actual;
		final Queue<T> q = queue;
        int missed = 1;
        for (;;) {
            if (done && q.isEmpty()) {
               Throwable e = error;
               if (error != null) {
                   a.onError(e);
               } else {
                   a.onCompleted();
               }
               return;
            }

            for (;;) {
                boolean d = done;
                T v = q.poll();

                if (d && v == null) {
                   Throwable e = error;
                   if (error != null) {
                       a.onError(e);
                   } else {
                       a.onCompleted();
                   }
                   return;
               }

               if (v == null) {
                   break;
               }

               a.onNext(v);
            }
        
            missed = wip.addAndGet(-missed);
            if (missed == 0) {
               break;
            }
        }
    }
}
```

**Comment by krisskross** [comment]
Ahh, the ```MpscObserver``` suffers a lot from GC pressure like you said. And the blocking in ```SerializedObserver``` provide automatic backpressure which is easier on GC. 

Thanks for your help David! Interesting and good learning exercise.

**Comment by krisskross** [comment]
And nice work there I should say :-)
