### ISSUE TITLE
Wrong link on https://github.com/ReactiveX/RxJava/wiki/Transforming-Observables

### ISSUE THREAD

**Issue by asco33** [ReactiveX/RxJava#3537]
Clicking on cast() leads to http://reactivex.io/documentation/operators/map.html.

**Comment by DavidMGross** [comment]
This is not a bug. That is the correct page on which the cast() operator is documented. "The cast operator is a specialized version of Map that transforms each item from the source Observable by casting it into a particular Class before reemitting it."

**Comment by asco33** [comment]
Oh sorry about that.

David Gross <notifications@github.com> schrieb am Di., 24. Nov. 2015, 19:43:
