### ISSUE TITLE
Scheduling should serialize notifications.

### ISSUE THREAD

**Issue by Dorus** [ReactiveX/RxJava#3542]
Currently, `onError` cuts ahead of `onNext` calls when you schedule work, but does not (cannot) when you use a single thread.

	Observable.create(o -> {
		o.onNext(1);
		o.onError(new NotImplementedException());
	})
	.observeOn(Schedulers.newThread())
	.subscribe(i -> System.out.println(i), 
			e -> System.out.println("error:" + e));

This yields `error` instead of `1, error` as expected. Other implementations of Rx like Rx.Net do serialize notifications. This 'cut ahead' behavior is actually described as a [common pitfall](https://realm.io/news/gotocph-mattias-kappler-reactive-architecture-android/) in RxJava by some.

**Comment by akarnokd** [comment]
RxJava 2.0 will allow you to customize this behavior in many operators, including `observeOn`, `delay`, `combineLatest`, `zip`, `groupBy`, `onBackpressureBuffer`, `skipLast` and `takeLast`.

I was planning to post a PR targeting `observeOn` to remove some unnecessary code (#3002) and may well do this as well.

**Comment by Dorus** [comment]
This is really scary nondeterministic behavior, and against Rx contract.I hope the (future) default will be to not lose data. If anything it might be an appropriate setting on the subscriber.

**Comment by akarnokd** [comment]
The `observeOn` operator received an overload that takes a `delayError` parameter you can set.

Closing via #3682.
