### ISSUE TITLE
rxjava error Caused by java.lang.NoSuchFieldException: value

### ISSUE THREAD

**Issue by chonamdoo** [ReactiveX/RxJava#3552]
http://crashes.to/s/00db6f57d09

**Comment by akarnokd** [comment]
Either wrong ProGuard ruleset or you run a particularly flawed Samsung Android version.

**Comment by chonamdoo** [comment]
proguard  setting 

# rxjava
-dontwarn rx.**
-keep class rx.schedulers.Schedulers {
    public static <methods>;
}
-keep class rx.schedulers.ImmediateScheduler {
    public <methods>;
}
-keep class rx.schedulers.TestScheduler {
    public <methods>;
}
-keep class rx.schedulers.Schedulers {
    public static ** test();
}

**Comment by vanniktech** [comment]
Yup those are definitely wrong. Those are the rules with RxJava 1.0.16 (Unless they changed something with 1.0.17, those should also work)

```proguard
-keepclassmembers class rx.internal.util.unsafe.*ArrayQueue*Field* {
    long producerIndex;
    long consumerIndex;
}
-keepclassmembers class rx.internal.util.unsafe.BaseLinkedQueueProducerNodeRef {
    rx.internal.util.atomic.LinkedQueueNode producerNode;
}
-keepclassmembers class rx.internal.util.unsafe.BaseLinkedQueueConsumerNodeRef {
    rx.internal.util.atomic.LinkedQueueNode consumerNode;
}
-dontwarn sun.misc.Unsafe
```

**Comment by chonamdoo** [comment]
@vanniktech  thx T_T

**Comment by artem-zinnatullin** [comment]
Looks like this issue is resolved and can be closed.

// @chonamdoo you can use ProGuard rules for RxJava baked as `aar`  https://github.com/artem-zinnatullin/RxJavaProGuardRules, I keep them updated with RxJava releases!

**Comment by zsxwing** [comment]
Closing. Please reopen it if you still have any question for proguard
