### ISSUE TITLE
Proposal: TestObservable for testing

### ISSUE THREAD

**Issue by artem-zinnatullin** [ReactiveX/RxJava#3564]
What if we could assert things in our tests in a reactive manner?

What if we have a `TestObservable` with assertion operators and we could write something like this:

```java
TestObservable
  .from(someObjectUnderTest.doSomethingRx())
  .assertEachValue(value -> ...)
  .assertValueAt(2, expectedValue)
  .assertNoErrors()
  .assertError(expectedError)
  .assertError(ExpectedError.class)
  .etc()
```

And so on. You can then just call `subscribe()` if `Observable` you're testing is synchronous or `toBlocking().subscribe()` if it's async.

Also, you can easily skip parts of emissions, do transformations and all other stuff you like to do with regular `Observable`s!

**Chainable**, **declarative**, **reactive** assertions!

**Comment by NiteshKant** [comment]
Would it achieve different results than the currently existing `TestSubscriber`?

**Comment by artem-zinnatullin** [comment]
Nope, same or even extended functionality as TestSubscriber but in a
chainable and declarative manner.

On Tue, Dec 8, 2015, 20:19 Nitesh Kant <notifications@github.com> wrote:

> Would it achieve different results than the currently existing
> TestSubscriber?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ReactiveX/RxJava/issues/3564#issuecomment-162950539>.
>
-- 

@artem_zin

**Comment by digitalbuddha** [comment]
@artem-zinnatullin Is there any reason why ```TestObservable``` cannot be its own library or at the very least an extension to RxJava?

**Comment by JakeWharton** [comment]
Seems to have way too much overlap with `TestSubscriber` for inclusion in 1.x. I'm :+1: on having it be something separate unless you are proposing a refactor of `TestSubscriber` for 2.x. I tend to copy around my own [`RecordingObserver`][1] for this case which has a better API (in my opinion) than `TestSubscriber`.

 [1]: https://github.com/JakeWharton/RxBinding/blob/master/testing-utils/src/main/java/com/jakewharton/rxbinding/RecordingObserver.java

**Comment by benjchristensen** [comment]
I agree with Jake

**Comment by artem-zinnatullin** [comment]
I'm totally open for a separate library approach, just wanted to know what does community and RxJava team think about it. So, looks like it makes sense and worth doing.

So, I'll continue my work on it here https://github.com/artem-zinnatullin/rxjava-testobservable

I'll add a comment here once it'll reach first release. If you'd like to see something similar right in the RxJava 2 — feel free to ping me.

Closing the issue then, thanks for comments!

**Comment by benjchristensen** [comment]
Yes I think exploring his space is a great thing to do and that it should influence what is included in 2.x. Thanks for pursuing further innovation!
