### ISSUE TITLE
2.0: Extending Observable/Single

### ISSUE THREAD

**Issue by artem-zinnatullin** [ReactiveX/RxJava#3572]
During my work on #3564 I've realized that `Observable` and `Single` are not very friendly for extending, I mean, you can extend them but as soon as you apply any operator from `Observable` or `Single` you won't be able to work with child class anymore.

Example:

```java
TestObservable
  .from(Observable.from(asList(1, 2, 3, 4, 5))
  .map(number -> toJson(number)) // Returns Observable instead of TestObservable.
  .expectError(IllegalArgumentException.class) // We can not apply this operator because it's not TestObservable anymore.
  .subscribe()
```

Maybe we can change it in RxJava 2? It's tricky but doable (and RxJava already has some kind of such thing — `extend` operator). I know several projects with custom `Observable`s but not sure if it worth in general for the library.

What do you think about this? 

If you want an example of a library that does something similar — AssertJ does it with its assertions https://joel-costigliola.github.io/assertj/core/api/org/assertj/core/api/AbstractAssert.html

I guess, for RxJava it would require kind of `AbstractObservable` where all common operators will live and then libraries/users will be able to extend it to add additional functionality with keeping child type after applying operators.

**Comment by roideuniverse** [comment]
+1

**Comment by akarnokd** [comment]
[I don't think](http://akarnokd.blogspot.hu/2016/03/writing-custom-reactive-base-type.html) this is possible with Java's typesystem. The main reason for this is the need to return `<U extends AbstractObservable>` from each method but U requires target typing to work. I.e., if chained, the compiler can only infer `AbstractObservable` and not your subtype.

**Comment by artem-zinnatullin** [comment]
Ok, let's close it for now. We're currently solving it Kotlin's extention functions.
