### ISSUE TITLE
Clarify behaviour in JavaDoc of switchOnNext() with respect to completions

### ISSUE THREAD

**Issue by grodin** [ReactiveX/RxJava#3576]
The JavaDoc of `switchOnNext()` doesn't currently say anything about how the resulting Observable will complete. 

The marble diagram implies (but not totally clearly) that if an inner Observable completes after an outer `onNext()`, that completion is swallowed, and if an inner Observable completes after the outer Observable completes, that the resulting Observable also completes.

However, there's no info about what happens in an inner Observable completes _before_ an outer `onNext()`. Does the resulting Observable complete at that point or not?

I've read the tests, and it seems the answer is that the resulting Observable will complete exactly when the following happen, in this order:

1. the outer Observable completes (implying that the current inner Observable will never be switched to any other);

2. the current inner Observable completes.

And that the resulting Observable won't complete under any other circumstances.

Firstly, is my understanding correct, and secondly, can the JavaDoc be improved?

**Comment by grodin** [comment]
If I have understood things correctly, I'd be happy to submit a PR clarifying the JavaDoc.

**Comment by akarnokd** [comment]
PRs are welcome!

**Comment by akarnokd** [comment]
See #3974
