### ISSUE TITLE
MergeDelayError missing Iterable overload

### ISSUE THREAD

**Issue by juxeii** [ReactiveX/RxJava#3577]
I'm missing an overload for the mergeDelayError method which takes an Iterable of Observables as parameter.
The "normal" merge method has
http://reactivex.io/RxJava/javadoc/rx/Observable.html#merge%28java.lang.Iterable,%20int%29

Is there a special reason why this overload is missing?
Thx,
Juergen

**Comment by akarnokd** [comment]
No particular reason. Would you like to submit a PR?

**Comment by juxeii** [comment]
Yes please :-)

**Comment by akarnokd** [comment]
Closing via #3627.
