### ISSUE TITLE
Observable share() with skip() usage issue

### ISSUE THREAD

**Issue by httpdispatch** [ReactiveX/RxJava#3578]
I have a code, where the shared observable is used. One of the shared instances there uses extra skip and debounce operators. The problem is that sometimes the action for the instance where skip and debounce is used is not called
```
Observable<Integer> beginChanged = RxBindingUtils
        .valueChanged(begin)
        .doOnEach(value -> Timber.d("Begin value changed: " + value.getValue()))
        .share();

monitor(
        beginChanged
                .map(minutes -> minutesToTime(minutes))
                .subscribe(beginTime.asAction()));
monitor(
        beginChanged
                .map(minutes -> minutes / interval)
                .subscribe(rangeBegin.asAction()));
monitor(
        beginChanged 
                .skip(1)// skip initial value emitted automatically right after the
                        // subsription
                .debounce(500, TimeUnit.MILLISECONDS)// such as range bar may change the
                        // value very quickly use the
                        // debounce function for the timeout
                        // based processing
                .doOnEach(value -> Timber.d("Begin value changed 2: " + value.getValue()))
                .subscribe(mSchedulerRangeBegin.asAction()));
```
If i replace the last occurrence of the beginChanges with the new observable it works as expected
```
monitor(
        RxBindingUtils
                .valueChanged(begin) // can't use shared observable because of unexpected behaviour with skip call
                .skip(1)// skip initial value emitted automatically right after the
                        // subsription
                .debounce(500, TimeUnit.MILLISECONDS)// such as range bar may change the
                        // value very quickly use the
                        // debounce function for the timeout
                        // based processing
                .doOnEach(value -> Timber.d("Begin value changed 2: " + value.getValue()))
                .subscribe(mSchedulerRangeBegin.asAction()));
```
Are there any restrictions which don't allow to use skip and debounce on shared observables?

**Comment by akarnokd** [comment]
There are no such restrictions. What do you do when the action is not triggered? What happens if you don't have `debounce`?

**Comment by httpdispatch** [comment]
The action is not triggered when i have single calls of the begin.set() method (changing value manually in dialog). When i have multiple value changes within short interval (moving rangebar) the action is triggered properly.

**Comment by httpdispatch** [comment]
I can say that it works without skip. Regarding debounce i will check

**Comment by httpdispatch** [comment]
removing debounce doesn't change the behaviour (the issue is still there).

**Comment by akarnokd** [comment]
Strange. Could you try and use `publish()` instead of `share()`, capture it with `ConnectableObservable` and call `connect()` after the last monitor call? It is likely `valueChanged` is hot. Could you completely remove `share` and see if it works or not?

**Comment by httpdispatch** [comment]
@akarnokd Thank you very much for your help, with the publish - connect it works as expected.

Code:

```
ConnectableObservable<Integer> beginChanged = RxBindingUtils
        .valueChanged(begin)
        .doOnEach(value -> Timber.d("Begin value changed: " + value.getValue()))
        .publish();

monitor(
        beginChanged
                .map(minutes -> minutesToTime(minutes))
                .subscribe(beginTime.asAction()));
monitor(
        beginChanged
                .map(minutes -> minutes / interval)
                .subscribe(rangeBegin.asAction()));
monitor(
        beginChanged // can't use shared observable because of unexpected behaviour with skip call
                .skip(1)// skip initial value emitted automatically right after the
                        // subsription
                .debounce(500, TimeUnit.MILLISECONDS)// such as range bar may change the
                        // value very quickly use the
                        // debounce function for the timeout
                        // based processing
                .doOnEach(value -> Timber.d("Begin value changed 2: " + value.getValue()))
                .subscribe(mSchedulerRangeBegin.asAction()));

beginChanged.connect();
```

**Comment by akarnokd** [comment]
The problem with `share` in general is that it tends to reconnect if the number of interested parties fluctuate, but I don't see this happening in this setup and `share` should work (you can check this by adding `doOnUnsubscribe` + logging before `share`. What is this `RxBindingUtils` you use?

**Comment by httpdispatch** [comment]
RxBindingUtils is a custom tool to build observable for Android Data Binding bindable fields

https://github.com/httpdispatch/MissedNotificationsReminder/blob/master/app/src/main/java/com/app/missednotificationsreminder/binding/util/RxBindingUtils.java
https://github.com/httpdispatch/MissedNotificationsReminder/blob/master/app/src/main/java/com/app/missednotificationsreminder/binding/util/BindableObjectValueChangedOnSubscribe.java

What should i check in the doOnUnsubscribe ?

The interesting thing that if i use share and change order of the subscriptions and put the one with the skip to the first place the second and the third will not be called.

**Comment by akarnokd** [comment]
I'll look into the helper utility.

> What should i check in the doOnUnsubscribe ?

```java
Observable<Integer> beginChanged = RxBindingUtils
        .valueChanged(begin)
        .doOnEach(value -> Timber.d("Begin value changed: " + value.getValue()))
        .doOnUnsubscribe(() -> System.out.println("Unshared?!"))
        .share();
```

> The interesting thing that if i use share and change order of the subscriptions and put the one with the skip to the first place the second and the third will not be called.

This may indicate there is a hidden failure somewhere. Could you use the two argument `subscribe` version and see if it receives an error?

**Comment by httpdispatch** [comment]
No errors are catched. But i can see the "Unshared?!" in the log.
```
12-17 14:05:32.689 3533-3533/com.app.missednotificationsreminder.debug D/SchedulerViewModel: Unshared?!
12-17 14:05:34.960 3533-3533/com.app.missednotificationsreminder.debug D/SchedulerViewModel: Begin value changed: 475
```

**Comment by akarnokd** [comment]
Are the `Observer`s `asAction()` returns by any chance call unsubscribe or otherwise use `take`?

**Comment by httpdispatch** [comment]
No, asAction method is very simple

public Action1<? super T> asAction() {
    return new Action1<T>() {
      @Override public void call(T value) {
        set(value);
      }
    };
  }

**Comment by akarnokd** [comment]
Okay. If you are willing to diagnose this further, that would be great.

The next step is to find out where the unsubscribe call comes. Could you change the `doOnUnsubscribe` to this:

```java
() -> new Exception().printStackTrace()
```

**Comment by httpdispatch** [comment]
I'll try to prepare test case for you. Also will try that instruction.

**Comment by httpdispatch** [comment]
Here is a test case which fails on last value comparison
https://gist.github.com/httpdispatch/966b2c23b50e85b000e2

**Comment by akarnokd** [comment]
Could you post something that doesn't depend on the Android platform?

**Comment by httpdispatch** [comment]
There are no android import there

**Comment by akarnokd** [comment]
`android.databinding.Observable.OnPropertyChangedCallback callback = new android.databinding.Observable.OnPropertyChangedCallback()`

**Comment by httpdispatch** [comment]
I was wrong regarding unsubscribe is called. It is not called. 

I will try to fix the test case

**Comment by httpdispatch** [comment]
Embedded all dependencies
https://gist.github.com/httpdispatch/966b2c23b50e85b000e2

**Comment by akarnokd** [comment]
Okay, I see what's wrong. The `begin` emits its current value on subscription which is triggered by the first Subscriber to share() and since all is synchronous, the subsequent subscribers don't get anything at that point because they are not yet subscribed. When the first event arrives, it gets skipped and only the second event is then processed. If you replace `share` with `replay().refCount()`, the test passes.

**Comment by httpdispatch** [comment]
Thank you very much for your time. 

How to explain that all future begin.set calls could be ignored by last action if they were called with some long interval (so not only initial value was ignored)? It is just curiosity because i've solved the initial issue by using publish-connect approach. I can try to reproduce issue in test if required.

**Comment by akarnokd** [comment]
If you could create a test which demonstrates this problem, it would be great. You could use `doOnNext` before debounce and after to see if `debounce` drops values unnecessarily or not.

**Comment by httpdispatch** [comment]
I can't reproduce that in test case yet, even in android test case. But i can reproduce it in the android app intself. Very weird.

**Comment by httpdispatch** [comment]
But i can say that both `publish-connect` and `replay().refCount()` approaches work fine

**Comment by artem-zinnatullin** [comment]
@httpdispatch any new input here? Will be great if you could close the issue with your findings or add something to continue investigation.

// trying to prevent issues hell in RxJava…

**Comment by httpdispatch** [comment]
For a now i can't reproduce issue in the plain java test case, only in live android app. Lets close the issue. If i'll find a way to reproduce the problem constantly i'll reopen it. Thank You guys for your great library and fast feedback and help.

**Comment by artem-zinnatullin** [comment]
:+1:
