### ISSUE TITLE
Completable operator review

### ISSUE THREAD

**Issue by stealthcode** [ReactiveX/RxJava#3580]
Before we release `rx.Completable` into the wild (that is before we release v1.1.1) I'd like to open up a thread for discussion regarding `Completable`'s instance methods, static methods, as well as any conversion methods to/from Observable and Single. Please feel free to review and comment here with any concerns. Any that need to be addressed should result in either a PR or another issue to track or discuss.

**Comment by stealthcode** [comment]
Note that there is already a discussion in #3570 regarding the instance method `Observable<T> endsWith(Observable<T>)` and the proposed rename to `andThen`.

**Comment by stealthcode** [comment]
If we rename `endWith` then I suggest we rename the `Completable startWith(Observable<T>)` method to an overload of `concatWith(Observable<T>)` and deleting `Completable startWith(Completable)`.

**Comment by stealthcode** [comment]
Also the `get()` method (and overload) are very similar to the functionality of `Observable.toBlocking()` except that it returns the error if any exists. This differs from Observable and Single toBlocking in that a BlockingObservable will throw any exception emitted to the subscriber's onError. Should we make Completable's `get` method consistent in behavior with a `BlockingObservable`? If so then a rename may also be in order. Thoughts?

**Comment by akarnokd** [comment]
> rename the Completable startWith(Observable<T>) method to an overload of concatWith(Observable<T>)

The problem with this rename is that `startWith` indicates the `Observable` runs first whereas `concatWith` indicates the `Observable` runs last which doesn't preserve the intention.

> deleting Completable startWith(Completable)

Okay.

> Also the get() method (and overload) are very similar to the functionality of Observable.toBlocking() except that it returns the error if any exists.

I've omitted BlockingCompletable because there are only 2 x 2 reasonable blocking operations: `await` and `get()` +1 timed overload each. But we can remove `get` for the sake of clarity.

**Comment by akarnokd** [comment]
Any more on this or can it be closed?
