### ISSUE TITLE
observable.first() not working properly after grouping data

### ISSUE THREAD

**Issue by eyeced** [ReactiveX/RxJava#3581]
I am calling things like this
```
Observable.just(1, 2, 3, 4, 5, 6)
                .groupBy(i -> i % 3)
                .flatMap(o -> o.first())
                .subscribe(System.out::println);
```
Ideally this should return 1,2,3
But the result is - 
```
1
2
3
4
5
6
```

got this issue in version 1.0.10 and 1.1.0 as well

**Comment by zsxwing** [comment]
This is expected. `groupBy` will emit a new `Observable` if the previous `Observable` of the same group is subscribed.

**Comment by davidmoten** [comment]
This has been discussed in #3411. It's about time I made this clearer in the javadoc so I'll knock up a PR soon.

**Comment by artem-zinnatullin** [comment]
Looks like this issue can be closed?

**Comment by zsxwing** [comment]
#3584 has updated the doc.
