### ISSUE TITLE
OSGI Equinox Mars RXJava not installing/starting on bundle startup in Linux

### ISSUE THREAD

**Issue by bppause** [ReactiveX/RxJava#3583]
I am unable to get rxjava to install during during osgi equinox startup. It doesnt even show in list of bundles after issuing ss command.

it does work once OSGI console comes up and I manually issue install command and then start bundle

steps:
install file:plugins/rxjava-1.0.17.jar*

Doing an 'ss' after that will show the bundle in the installed state.  
You can then start it, and it will work fine.  But I can't seem to get a 
working bundles.info entry to do this. 

Tried with both RXjava 1.1 and 1.0.17 and same outcome.

Note: Works perfectly on windows (only issue on Lunx)

Here is the bundles.info entry
io.reactivex.rxjava,1.0.17,plugins/rxjava-1.0.17.jar,4,true

Here is the manifest (Note: I did remove the sun.misc entry referencing this issue https://github.com/ReactiveX/RxJava/issues/3516  as this would not allow bundle to start on linux, windows or manually on osgi command line )

Manifest-Version: 1.0
Export-Package: rx;version="1.0.17";uses:="rx.functions,rx.observables
 ,rx.schedulers,rx.singles",rx.annotations;version="1.0.17",rx.excepti
 ons;version="1.0.17";uses:=rx,rx.functions;version="1.0.17",rx.intern
 al.operators;version="1.0.17";uses:="rx,rx.functions,rx.observables,r
 x.schedulers,rx.subjects",rx.internal.producers;version="1.0.17";uses
 :=rx,rx.internal.schedulers;version="1.0.17";uses:="rx,rx.functions,r
 x.internal.util,rx.subscriptions",rx.internal.util;version="1.0.17";u
 ses:="rx,rx.exceptions,rx.functions,rx.internal.schedulers",rx.intern
 al.util.atomic;version="1.0.17",rx.internal.util.unsafe;version="1.0.
 17";uses:="rx.internal.util.atomic,sun.misc",rx.observables;version="
 1.0.17";uses:="rx,rx.functions",rx.observers;version="1.0.17";uses:="
 rx,rx.functions",rx.plugins;version="1.0.17";uses:="rx,rx.functions",
 rx.schedulers;version="1.0.17";uses:=rx,rx.singles;version="1.0.17";u
 ses:=rx,rx.subjects;version="1.0.17";uses:="rx,rx.internal.operators,
 rx.schedulers",rx.subscriptions;version="1.0.17";uses:="rx,rx.functio
 ns"
Implementation-Title: io.reactivex#rxjava;1.0.17
Built-By: travis
Change: a65ca70
Gradle-Version: 2.2.1
Tool: Bnd-2.1.0.20130426-122213
Built-OS: Linux
Build-Host: testing-worker-linux-docker-dc38aa25-3188-linux-5.prod.tra
 vis-ci.org
Build-Number: LOCAL
Module-Origin: https://github.com/ReactiveX/RxJava.git
Bundle-SymbolicName: io.reactivex.rxjava
Build-Id: LOCAL
X-Compile-Target-JDK: 1.6
Implementation-Version: 1.0.17
Module-Owner: benjchristensen@netflix.com
Bundle-Name: rxjava
Created-By: 1.7.0_76-b13 (Oracle Corporation)
Build-Job: LOCAL
Build-Date: 2015-12-02_20:27:10
X-Compile-Source-JDK: 1.6
Build-Java-Version: 1.7.0_76
Bundle-Vendor: ReactiveX
Built-Status: release
Bundle-Version: 1.0.17
Bnd-LastModified: 1449087991000
Bundle-ManifestVersion: 2
Bundle-DocURL: https://github.com/ReactiveX/RxJava
Module-Email: benjchristensen@netflix.com
Module-Source: 

Please advise

**Comment by artem-zinnatullin** [comment]
Can you try RxJava v1.1.0 with Oracle JDK/JRE on Linux in your setup?

// Would be great if you could close the issue if it was successfully resolved (with some info for others) or add more input to continue investigation.

**Comment by mattrifidi** [comment]
Hi,

I tried that as suggested, and Oracle JDK does seem to work where OpenJDK fails.  Is there any reason that it works but OpenJDK has trouble?  Doing a manual "install" on the jar after startup with OpenJDK does seem to work.  If at all possible I would like to get this working on OpenJDK.  

Thanks for your help!

**Comment by bppause** [comment]
Why was this closed. We're the issues supporting via openjdk..resolved?

**Comment by akarnokd** [comment]
@artem-zinnatullin posted a possible solution but there was no response for a month. If you think you can add more input I'd be glad to reopen the issue.

**Comment by bppause** [comment]
I tried that as suggested, and Oracle JDK does seem to work where OpenJDK fails. Is there any reason that it works but OpenJDK has trouble? Doing a manual "install" on the jar after startup with OpenJDK does seem to work. If at all possible I would like to get this working on OpenJDK.

Thanks for your help!
