### ISSUE TITLE
SingleSubscriber should be an interface or there should be an interface with onSuccess/onError

### ISSUE THREAD

**Issue by lfscheidegger** [ReactiveX/RxJava#3591]
Right now, SingleSubscriber combines the regular Observable-like interface of onSuccess/onError with Subscription-related methods, and crucially also has a public add() method.

I have some unit tests where I was using Observable before, and because Observable is an interface, I was having no problems mocking it and verifying calls to onNext. After refactoring to use a Single, and SingleSubscriptions (instead of Observable), those tests are running into problems. Specifically, the add() method is final, so Mockito doesn't mock it, and calls through to the original code. But because the rest of the code is a mock, the value of cs (the SubscriptionList) isn't initialized, causing an NPE in the tests.

Is there any reason why SingleSubscriber isn't an interface with just onSuccess/onError (similar to Observable), or that there isn't such an interface, and then SingleSubscriber would implement that (in addition to Subscription, as it does right now)? The crucial change would be to make Single's subscribe method take that interface, so that mocking in unit tests would work.

Alternatively, the add() method could be non-final, but I think that's also not ideal.

**Comment by akarnokd** [comment]
Yes, you are right. `Single` was designed with an "outdated" reactive pattern and thus has a `SingleSubscriber` class similar to `Subscriber` but we never felt the need to mock an entire `Observable` or `Single`.

However, `Completable` and 2.x `Single` is designed with the Reactive-Streams pattern and feature XXXSubscriber interfaces.

For a proper design, `onSuccess` and `onError` are not enough and there has to be a way of chaining cancellations; for this reason, there is a need for a third method: `onSubscribe(Subscription s)`.

The problem now is that `Single` is in `@Beta` and its API can't change so drastically.
