### ISSUE TITLE
Intellij auto import error 

### ISSUE THREAD

**Issue by suiwenfeng** [ReactiveX/RxJava#3593]
Bad   method call from inside of a branch Exception Details: Location: nebula/core/NamedContainerProperOrder. (Ljava/lang/Class;Lorg/gradle/internal/reflect/Instantiator;Lgroovy/lang/Closure;)V @125: invokespecial Reason: Error exists in the bytecode Bytecode: 0000000: b800 173a 0406 bd00 2859 032b 5359 042c 0000010: 5359 052d 5359 10ff 1205 b800 2e2a 5fab 0000020: 0000 0147 0000 0006 d8f5 c64c 0000 0039 0000030: e5f5 61f5 0000 0064 11f8 6d3a 0000 009b 0000040: 4408 d7d4 0000 00d2 59b0 7b8f 0000 00fd 0000050: 741a af72 0000 0128 5f5a 5903 32b8 0034 0000060: c000 365f 5904 3212 38b8 003c c000 385f 0000070: 5905 3212 3eb8 003c c000 3e5f 57b7 0040 0000080: a700 f05f 5a59 0332 b800 34c0 0036 5f59 0000090: 0432 1238 b800 3cc0 0038 5f59 0532 123e 00000a0: b800 3cc0 003e 5f59 0632 1242 b800 3cc0 00000b0: 0042 5f57 b700 45a7 00b9 5f5a 5903 32b8 00000c0: 0034 c000 365f 5904 3212 38b8 003c c000 00000d0: 385f 5905 3212 3eb8 003c c000 3e5f 5906 00000e0: 3212 47b8 003c c000 475f 57b7 004a a700 00000f0: 825f 5a59 0332 b800 34c0 0036 5f59 0432 0000100: 1238 b800 3cc0 0038 5f59 0532 1247 b800 0000110: 3cc0 0047 5f57 b700 4da7 0057 5f5a 5903 0000120: 32b8 0034 c000 365f 5904 3212 38b8 003c 0000130: c000 385f 5905 3212 42b8 003c c000 425f 0000140: 57b7 0050 a700 2c5f 5a59 0332 b800 34c0 0000150: 0036 5f59 0432 1238 b800 3cc0 0038 5f57 0000160: b700 19a7 000d bb00 5259 1254 b700 57bf 0000170: 572a b600 1d3a 0519 052a 5fb5 001f 1905 0000180: 57b1 Stackmap Table: full_frame(@88,{UninitializedThis,Object[#54],Object[#56],Object[#71],Object[#91]},{Object[#93],UninitializedThis}) full_frame(@131,{UninitializedThis,Object[#54],Object[#56],Object[#71],Object[#91]},{Object[#93],UninitializedThis}) full_frame(@186,{UninitializedThis,Object[#54],Object[#56],Object[#71],Object[#91]},{Object[#93],UninitializedThis}) full_frame(@241,{UninitializedThis,Object[#54],Object[#56],Object[#71],Object[#91]},{Object[#93],UninitializedThis}) full_frame(@284,{UninitializedThis,Object[#54],Object[#56],Object[#71],Object[#91]},{Object[#93],UninitializedThis}) full_frame(@327,{UninitializedThis,Object[#54],Object[#56],Object[#71],Object[#91]},{Object[#93],UninitializedThis}) full_frame(@358,{UninitializedThis,Object[#54],Object[#56],Object[#71],Object[#91]},{Object[#93],UninitializedThis}) full_frame(@368,{Object[#2],Object[#54],Object[#56],Object[#71],Object[#91]},{Object[#93]}) 

Any idea to fix the issue?

**Comment by zsxwing** [comment]
How did you import it? I guess it may because the version conflicts of gradle. Could you just use the default gradle wrapper to import?

**Comment by suiwenfeng** [comment]
Thanks, I will try your solution tomorrow.

**Comment by artem-zinnatullin** [comment]
@suiwenfeng any news? If you've resolved this issue — please close it or add more info to continue investigation, thanks!
