### ISSUE TITLE
Why the executors only use one thread?

### ISSUE THREAD

**Issue by rockman12352** [ReactiveX/RxJava#3594]
I have created a fixed thread-pool to process an event emit per 300 milliseconds and assume the process need 1000 millisecond. Suppose the multi-thread will work but only one thread reused.

If i set the sleepTime smaller than 300ms, the processing thread change, but that is useless.

Questions: What can I do to make it concurrent? Why the program reuse the thread?

Thank you in advance

```java
public static void main(String[] args) throws InterruptedException {
    long sleepTime = 1000;
    ExecutorService e = Executors.newFixedThreadPool(3);

    Observable.interval(300, TimeUnit.MILLISECONDS)
    .subscribeOn(Schedulers.computation())
    .flatMap(new Func1<Long, Observable<Long>>() {
        @Override
        public Observable<Long> call(Long pT) {
            return Observable.just(pT).subscribeOn(Schedulers.from(e));
        }
    })
    .doOnNext(new Action1<Long>() {

        @Override
        public void call(Long pT) {
            try {
                Thread.sleep(sleepTime);
            } catch (InterruptedException e) {
                e.printStackTrace();
            }

        }
    })
    .subscribe(new Action1<Long>() {

        @Override
        public void call(Long pT) {
            System.out.println("i am " + pT + "in thread:" + Thread.currentThread().getName());

        }
    });


    Thread.sleep(50000);
    e.shutdownNow();

}



i am 0in thread:pool-1-thread-1
i am 1in thread:pool-1-thread-1
i am 2in thread:pool-1-thread-1
i am 3in thread:pool-1-thread-1
i am 4in thread:pool-1-thread-1
i am 5in thread:pool-1-thread-1
i am 6in thread:pool-1-thread-1
i am 7in thread:pool-1-thread-1
i am 8in thread:pool-1-thread-1
i am 9in thread:pool-1-thread-1
i am 10in thread:pool-1-thread-1
i am 11in thread:pool-1-thread-1

**Comment by akarnokd** [comment]
Its a thread pool and if you don't have high enough throughput, it won't even create new threads. That single thread can serve all tasks easily.

**Comment by rockman12352** [comment]
@akarnokd Thank you for your reply. I have set sleep time, it doesn't count?

**Comment by akarnokd** [comment]
What happens is that the first `just` value runs on the other scheduler and gets blocked by sleep so that the other values have plenty of time to run and get queued up in flatMap. Once the first thread unblocks it finds a ton of values available and resumes emitting on the same thread. Thus, on the output side, only one thread shows up but inside, just execute on the rest of the thread. put doOnNext on those inner sequences and see where they run.

**Comment by rockman12352** [comment]
@akarnokd With your advice, i modify the code. just and sleep are not in the same thread. So it should not effect each other

**Comment by rockman12352** [comment]
@akarnokd Finally, i got what you mean, you are right!  Million thanks!

**Comment by akarnokd** [comment]
Great!
