### ISSUE TITLE
Execution hook for Single

### ISSUE THREAD

**Issue by phajduk** [ReactiveX/RxJava#3595]
`RxJavaObservableExecutionHook` is not compatible with [`Single`](https://github.com/ReactiveX/RxJava/blob/1.x/src/main/java/rx/Single.java) type. For example: [`RxJavaObservableExecutionHook#onCreate`](https://github.com/ReactiveX/RxJava/blob/1.x/src/main/java/rx/plugins/RxJavaObservableExecutionHook.java#L54) method tooks [`Observable#OnSubscribe`](https://github.com/ReactiveX/RxJava/blob/1.x/src/main/java/rx/Observable.java#L101) type as a parameter. However, `Single` is using it's own [`OnSubscribe`](https://github.com/ReactiveX/RxJava/blob/1.x/src/main/java/rx/Single.java#L149) type. Shall we implement new class to handle `Single`'s hooks let's say `RxJavaSingleExecutionHook` ?

**Comment by akarnokd** [comment]
Would you like to post a PR for this?

**Comment by phajduk** [comment]
If you agree with my proposition then I will create PR for that feature for sure.

**Comment by akarnokd** [comment]
I don't see anything wrong upfront so go ahead with the PR.
