### ISSUE TITLE
rxjava in java project   confused

### ISSUE THREAD

**Issue by lejun** [ReactiveX/RxJava#3596]
code:
```java
Observable.create(new Observable.OnSubscribe<String>() {
    @Override
    public void call(Subscriber<? super String> subscriber) {

        for (int i = 0; i < 4; i++) {
            System.out.println("send "+i + " " + new Date(System.currentTimeMillis()));
            subscriber.onNext(i + " rx");

        }
    }
})
        .delay(1000, TimeUnit.MILLISECONDS)
        .subscribe(new Action1<String>() {
            @Override
            public void call(String s) {
                System.out.println("reciver "+ s + " " + new Date(System.currentTimeMillis()));
            }
        });
```

in java project output log:

>send 0 Sat Jan 02 22:50:41 CST 2016
send 1 Sat Jan 02 22:50:42 CST 2016
send 2 Sat Jan 02 22:50:42 CST 2016
send 3 Sat Jan 02 22:50:42 CST 2016
Process finished with exit code 0

in android project output log:
>01-02 09:55:32.700 1946-1946/com.mbl.hello.mac E/send: 0 Sat Jan 02 09:55:32 EST 2016
01-02 09:55:32.701 1946-1946/com.mbl.hello.mac E/send: 1 Sat Jan 02 09:55:32 EST 2016
01-02 09:55:32.701 1946-1946/com.mbl.hello.mac E/send: 2 Sat Jan 02 09:55:32 EST 2016
01-02 09:55:32.702 1946-1946/com.mbl.hello.mac E/send: 3 Sat Jan 02 09:55:32 EST 2016

>01-02 09:55:33.702 1946-2131/com.mbl.hello.mac E/reciver: 0 rx Sat Jan 02 09:55:33 EST 2016
01-02 09:55:33.702 1946-2131/com.mbl.hello.mac E/reciver: 1 rx Sat Jan 02 09:55:33 EST 2016
01-02 09:55:33.702 1946-2131/com.mbl.hello.mac E/reciver: 2 rx Sat Jan 02 09:55:33 EST 2016
01-02 09:55:33.702 1946-2131/com.mbl.hello.mac E/reciver: 3 rx Sat Jan 02 09:55:33 EST 2016

**Why the difference?** please help me
rxjava version:1.0.14

**Comment by akarnokd** [comment]
RxJava has daemon threads and the desktop program quit before the delayed events could be printed.

**Comment by lejun** [comment]
THS @akarnokd 
http://stackoverflow.com/questions/30791902/rxjava-subscribeonschedulers-newthread-questions

**Why ok in android?**

**Comment by akarnokd** [comment]
I assume your Android app didn't quit and stayed on screen.

**Comment by lejun** [comment]
Million thanks! @akarnokd
