### ISSUE TITLE
BehaviorSubject deadlocks when using subject.single().toBlocking().single()

### ISSUE THREAD

**Issue by austynmahoney** [ReactiveX/RxJava#3598]
When I use `.single().toBlocking().single()` on a `BehaviorSubject` (where a default item has been set), it will deadlock the following test. When `.take(1).toBlocking().single()` is used, the test completes successfully.

```java
System.out.println("take(1) started");
BehaviorSubject.create("Item").take(1).toBlocking().single();
System.out.println("take(1) finished");

System.out.println("single() started");
BehaviorSubject.create("Item").single().toBlocking().single(); // Deadlocks here
System.out.println("single() finished");
```

Am I doing something wrong here?

**Comment by akarnokd** [comment]
`Observable.single` requires 1 element and 1 completion signal to emit a single item or 2 elements to emit an overflow error. Since there is no more item, the second stream will hang indefinitely. This is the expected behavior.

**Comment by austynmahoney** [comment]
Thanks for the confirmation.
