### ISSUE TITLE
NPE in CompositeException when nested throws on initCause

### ISSUE THREAD

**Issue by emilianogc** [ReactiveX/RxJava#3599]
The following example throws a NPE
```java
public class Test {
    public static class CustomException extends Throwable {
        public synchronized Throwable initCause(Throwable cause) {
            throw new UnsupportedOperationException();
        }
    }
    public static void main(String ... args) {
        new CompositeException(Arrays.asList(
                new CustomException(),
                new UnsupportedOperationException(),
                new IllegalStateException())).getCause();
    }
}
```
The stacktrace is the following:
```
Exception in thread "main" java.lang.NullPointerException
	at rx.exceptions.CompositeException.getCause(CompositeException.java:126)
	at Test.main(Test.java:18)
```

**Comment by emilianogc** [comment]
Also, when created with two exceptions with the first containing a cause, the second exception will be present in the resulting chain.

Is there a plan to move to java7? In that case this same feature can be implemented using Throwable#addSupressed.

**Comment by akarnokd** [comment]
Hi. 1.x won't move beyond Java 6. I've looked at the crashing code but don't know how to fix it as I don't understand the logic in there exactly.

**Comment by emilianogc** [comment]
Any help on what should be the expected behaviour for getCause so I can propose a fix? The test doesn't really show what's the contract for CompositeException#getCause.

**Comment by akarnokd** [comment]
Closing via #3620
