### ISSUE TITLE
 myTextView.setText () can be performed in a non-UI thread, Why 

### ISSUE THREAD

**Issue by YongHuiLuo** [ReactiveX/RxJava#3605]
Hello, I have a question on the use of Schedulers in the process, the operation of the UI in Android development, should be the main thread of execution, why I use the observeOn (Schedulers.io ()), TextView can still assignment, which is how to do, please help me to answer, very grateful.Code is as follows:

```java
myTextView.setText("thread 1 id=" + Thread.currentThread().getId());
Observable.just(1, 2, 3, 4)
    .subscribeOn(Schedulers.io())
    .observeOn(Schedulers.newThread())
    .map(new Func1<Integer, String>() {
        @Override
        public String call(Integer integer) {
            myTextView.setText(myTextView.getText() + "\n" + "thread 2 id =" +
                 Thread.currentThread().getId());
            return "5" + integer;
        }
    })
    .observeOn(Schedulers.io())
    .map(new Func1<String, Integer>() {
        @Override
        public Integer call(String s) {
            myTextView.setText(myTextView.getText() + "\n" + "thread 3 id =" + 
                  Thread.currentThread().getId());
            return Integer.parseInt(s);
        }
    });
```

Results ： TextView normal display

**Comment by akarnokd** [comment]
You didn't schedule on the proper thread. You have to use `observeOn(AndroidSchedulers.mainThread())` so `setText` runs on the main thread.

**Comment by YongHuiLuo** [comment]
First of all thank you for your answer, But I mean that I did not use observeOn (AndroidSchedulers.mainThread ()), however, still setText assignment success. Under normal situation, the program should throw an exception and fail the assignment. But using observeOn (Schedulers.io ()) did not appear abnormal.

**Comment by akarnokd** [comment]
I'm not an Android expert so I don't know why the `setText` didn't throw on an off-main-thread.

**Comment by YongHuiLuo** [comment]
Anyway thank you very much.

**Comment by YongHuiLuo** [comment]
The results show that the myTextView：
 * thread 1 id=1
 * thread 2 id =13567
 * thread 3 id =13755
 * ...

**Comment by hzsweers** [comment]
@YongHuiLuo link some sample code that exhibits this, only way for anyone to really debug it. Also I think you should post this in RxAndroid, as it's a little too specific for RxJava by itself unless there's a problem in `observeOn`

**Comment by JakeWharton** [comment]
All view code does not throw if accessed off the main thread. Most calls
silently fail.

**Comment by YongHuiLuo** [comment]
@hzsweers   
I'm very sorry, I've realized that  I should post this in RxAndroid. Also, I should submit a complete code on my question. I will note this in the future.

**Comment by YongHuiLuo** [comment]
@JakeWharton   Privately, my colleagues and I call you to Jake Great God, thank you for answering my questions. However, I would like to know more about the related information,

**Comment by Chaoba** [comment]
Did you run your code in onCreate method? It has no relationship with Rxjava. You can create a new thread to set the text and run it in onCreate method and it will also work. 
```java
class TestThread extends Thread{
        public void run() {
            myTextView.setText(myTextView.getText() + "\n" + "thread 2 id =" +
                    Thread.currentThread().getId());
        }
    }
```
The reason why it can work need further study.

**Comment by Harto-Lin** [comment]
@Chaoba 
I  don't know the reason for you said.And I try write the code as you write,but it is wrong.
Who can tell me the reason ? Thanks.

**Comment by Chaoba** [comment]
> I don't know the reason for you said.And I try write the code as you write,but it is wrong.
> Who can tell me the reason ? Thanks.

Did you run the thread in onCreate() method? It works ok for me and will not work if you run it in onResume etc.

**Comment by EhsanMashhadi** [comment]
Any clue about the reason why it is work on onCreate method?
