### ISSUE TITLE
rx.Observable.switchIfEmpty(Observable<? extends T>) need a marble diagram

### ISSUE THREAD

**Issue by ronanM** [ReactiveX/RxJava#3606]
rx.Observable.switchIfEmpty(Observable<? extends T>) need a marble diagram in the javadoc.

**Comment by akarnokd** [comment]
![image](https://cloud.githubusercontent.com/assets/1269832/16411687/97ebab92-3d28-11e6-9a73-2def0a0944ae.png)

**Comment by akarnokd** [comment]
Image available: https://raw.github.com/wiki/ReactiveX/RxJava/images/rx-operators/switchifempty.png

1.x: added reference in #4963.

**Comment by akarnokd** [comment]
Closing via #4990 for 2.x.
