### ISSUE TITLE
flatMap onCompleted not called if onNext is null

### ISSUE THREAD

**Issue by gborland** [ReactiveX/RxJava#3613]
I am using the three-argument variant of `flatMap()` which allows me to pass functions for `onNext`, `onError` and `onCompleted`.

I have observed that if I pass `null` as the `onNext` callback, then the `onCompleted` callback is never called even if the source observable does complete. I would expect that either `onError` or `onComplete` would always be called, but it seems that neither is called in this case.
```java
sharedLibrary.syncAllData()
        .flatMap(
                 null, // onNext
                 new Func1<Throwable, Observable<Void>>() {
                     @Override
                     public Observable<Void> call(Throwable throwable) {
                         Timber.d("** onError");
                         return sharedLibrary.generatePendingTransactions();
                     }
                 },
                 // this is never called :(
                 new Func0<Observable<Void>>() {
                     @Override
                     public Observable<Void> call() {
                         Timber.d("** onCompleted");
                         return sharedLibrary.generatePendingTransactions();
                       }
                 })
          .subscribe();
```

If I do pass an `onNext` callback, then both `onNext` and `onCompleted` are called as expected.
```java
sharedLibrary.syncAllData()
        .flatMap(
                 new Func1<Boolean, Observable<Void>>() {
                     @Override
                     public Observable<Void> call(Boolean aBoolean) {
                         Timber.d("** onNext");
                         return sharedLibrary.generatePendingTransactions();
                     }
                 },
                 new Func1<Throwable, Observable<Void>>() {
                     @Override
                     public Observable<Void> call(Throwable throwable) {
                         Timber.d("** onError");
                         return sharedLibrary.generatePendingTransactions();
                     }
                 },
                 // called as expected :)
                 new Func0<Observable<Void>>() {
                     @Override
                     public Observable<Void> call() {
                         Timber.d("** onCompleted");
                         return sharedLibrary.generatePendingTransactions();
                       }
                 })
          .subscribe();
```
Background: I have this code which is intended to execute one operation (`syncAllData()`) and then another (`generatePendingTransactions()`) when the first completes. They have different return types so I can't use a simple `concat`.

I also want to execute the second operation regardless of whether the first one succeeds or fails.

**Comment by gborland** [comment]
This is probably my mistake. It just can't be valid to pass `null` as `onNext` as otherwise `flatMap()` would have no idea what to do with the values coming out of the source observable, right? I'll just close this.

**Comment by JakeWharton** [comment]
> It just can't be valid to pass null as onNext as otherwise flatMap() would have no idea what to do with the values coming out of the source observable, right?

RxJava rarely cares about actual values. And `flatMap` shouldn't care, just hand the value to the function responsible for creating the new `Observable<R>`.

**Comment by akarnokd** [comment]
This was the `flatMap` which replaces standard events with observables and merges the result. All method parameters are mandatory, but 1.x is not too keen about parameter validation. PRs welcome.
