### ISSUE TITLE
When/Why should I use RxJava?

### ISSUE THREAD

**Issue by fatihcamuz** [ReactiveX/RxJava#3615]
Examples or scenarios ? 

Thank you.

**Comment by hzsweers** [comment]
Literally a whole wiki page: https://github.com/ReactiveX/RxJava/wiki/How-To-Use-RxJava

And a whole website about why to use Reactive Extensions: http://reactivex.io/intro.html

Further reading: http://bfy.tw/3jxB

**Comment by adam-arold** [comment]
You might also want to take a look at [this](http://blog.danlew.net/2014/09/15/grokking-rxjava-part-1/) article which is the first part of a series about understanding RxJava.

**Comment by fatihcamuz** [comment]
I'll examine these links but it's hard for me cause of I'm new on design pattern so I have to step by step. Thank you.
