### ISSUE TITLE
doOnEmpty() Operator?

### ISSUE THREAD

**Issue by thomasnield** [ReactiveX/RxJava#3621]
Is it possible we can add an `Observable.doOnEmpty()` operator? Sometimes when I'm debugging or want to handle an empty `Observable` I'd like to raise an error, display a message, or some other action to handle the emptiness...

```
Observable<String> source = ...


source.doOnEmpty(() -> System.out.println("No items were emitted!")).subscribe(System.out::println);
```

**Comment by thomasnield** [comment]
Put in a PR with this operator implemented #3624

**Comment by zsxwing** [comment]
The name of `doOnEmpty` is not consistent with other methods. E.g., doOnNext means triggering a function when `onNext` is called.

**Comment by thomasnield** [comment]
Technically that is true, but I can't really think of a better operator name that expresses the intent as clearly as 'doOnEmpty()'. Trying to conform with 'doOnCompletedIfEmpty()' or some other excessively descriptive name can make it verbose.

You all are welcome to change it if you feel its warranted though.

**Comment by thomasnield** [comment]
Although it does not follow the strict definition of "event" by Rx standards, one could argue that emptiness is an event resulting from the 'onCompleted() event. But the more I think about it I do see what you are saying. I guess the real question is will RxJava users get confused by the name 'doOnEmpty()' implying there is a nonexistant 'onEmpty()' event... or is it more intuitive to call it that?

**Comment by davidmoten** [comment]
I think `doOnEmpty` is a natural name for this one.

**Comment by thomasnield** [comment]
What's the status on this? Is this planned for a layer release?

**Comment by akarnokd** [comment]
You can achieve a similar effect via composition

```java
Observable.empty().switchIfEmpty(Observable.empty().doOnCompleted(() -> { ... })).subscribe();
```

**Comment by thomasnield** [comment]
Oh nice, that's clever. And it doesn't even require any custom Operator implementation. 

I can go ahead and close this then. I've started using Kotlin with extension functions so it's marginalized the need personally for me to put this in a centralized library.

**Comment by hzsweers** [comment]
Sorry to necro this, but I still think this would be useful as a public API, even if it's a small composition under the hood. There's precedent for it a few other areas in the API that just call a few other top-level methods under the hood.

**Comment by thomasnield** [comment]
You can try convincing @akarnokd as I agree this would be a good operator. 

If not, seriously check out Kotlin. You can add your own operators to Observable via extension functions, without any call to lift() or compose(). Kotlin is officially supported on Android as well.

**Comment by hzsweers** [comment]
Android is supported by JetBrains, Kotlin is not officially supported by Android. It's nice but not everyone is using Kotlin in their projects.
