### ISSUE TITLE
doOnNextCount(), doOnErrorCount(), and  doOnCompletedCount()?

### ISSUE THREAD

**Issue by thomasnield** [ReactiveX/RxJava#3628]
Feel free to close if this sounds too niche, but I'd like to create `doOnNextCount()`, `doOnErrorCount()`, and `doOnCompletedCount()` operators. 

I'm finding a need to quickly get a count of cumulative emissions on `doOnNext()`, `doOnError()`, and `doOnCompleted()` events. This would be helpful for debugging as well as updating UI's with "processed x items" notifications. Otherwise you have to create an entirely separate `Subscriber` and do a `count()` operation separately, which could be inefficient. 

They each would accept an `Action1<Integer>` argument to specify what to do with the cumulative count. A `Long` could also work if that is deemed more appropriate. 

```
Observable<Integer> source = Observable.range(1,10000);

source.doOnCompleted(i -> System.out.prinlnt("Processed " + i " items")).map(i -> processItem(i)).subscribe();
```

**Comment by thomasnield** [comment]
I already implemented these internally, and it definitely has made debugging Observables much more efficient for me. If you guys want them let me know.

**Comment by akarnokd** [comment]
Hi. I personally don't see the general need for these operators.

**Comment by davidmoten** [comment]
Vaguely related to this you might want to have a look at [rxjava-slf4j]( https://github.com/davidmoten/rxjava-slf4j).

**Comment by thomasnield** [comment]
@davidmoten I was wondering if you or someone else might have come up with a logging framework for RxJava. Thanks Dave! My colleague will be thrilled.
