### ISSUE TITLE
ThrottleFirst - Discrepancy between implementation & marble diagrams

### ISSUE THREAD

**Issue by jayrave** [ReactiveX/RxJava#3636]
By [implementation](https://github.com/ReactiveX/RxJava/blob/884e49b437c25fa44d2469a3a0388a756dc40d2d/src/main/java/rx/internal/operators/OperatorThrottleFirst.java#L48), the operator's window isn't fixed width. Whenever a new item is emitted, a window is started and the operator makes sure that another item isn't emitted before the window expires. There is no fixed width window or ticking at scheduled intervals

**Discrepancies**
- The [doc](https://github.com/ReactiveX/RxJava/blob/1.x/src/main/java/rx/Observable.java#L8763) says that it has fixed width window
- The marble diagrams - [diagram 1](https://github.com/ReactiveX/RxJava/wiki/Backpressure#throttlefirst) & [diagram 2](https://raw.githubusercontent.com/wiki/ReactiveX/RxJava/images/rx-operators/throttleFirst.s.png) depict as if it ticks at scheduled intervals

**Comment by akarnokd** [comment]
Closing via https://github.com/ReactiveX/reactivex.github.io/issues/159. The updated diagram should appear on the webpage with the next reactivex.github.io update I guess.
