### ISSUE TITLE
Observable.repeat(final long count) marble diagram is misleading

### ISSUE THREAD

**Issue by gjesse** [ReactiveX/RxJava#3650]
The repeat marble diagram is incorrect - The actual documentation is OK but the diagram referenced here https://github.com/ReactiveX/RxJava/blob/1.x/src/main/java/rx/Observable.java#L6394 shows `repeat(1)` causing 2 repetitions of the source observable.

The diagram in question: https://raw.githubusercontent.com/wiki/ReactiveX/RxJava/images/rx-operators/repeat.on.png

**Comment by akarnokd** [comment]
To me `repeat(0)` would mean don't repeat but let it only run once whereas `repeat(1)` tells repeat once so run twice.

**Comment by abersnaze** [comment]
That was something I noticed when combining the retryWhen and repeatWhen. I looked around and having repeat(0) mean do nothing seemed to be consistent with other APIs.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/repeat

**Comment by gjesse** [comment]
repeat(0) doing nothing is documented in the text. I would also normally expect repeat(1) to cause 2 instances of the source observable (the original and 1 repeat) to be seen, but that's not how it's implemented.

**Comment by DavidMGross** [comment]
Fixed. I changed the labels on those diagrams to be repeat(2).

**Comment by gjesse** [comment]
confirmed the diagram reflects the behavior.

**Comment by akarnokd** [comment]
Great!
