### ISSUE TITLE
Mapping onError notifications

### ISSUE THREAD

**Issue by twz123** [ReactiveX/RxJava#3652]
I often have the use case that I want to map the `Throwable` emitted by an `onError` notification of an `Observable` to something else, for example wrapping or unwrapping it.

Maybe I missed something, but apparently there is no stock solution in RxJava to achieve this. Currently, I use a custom `Operator`. Would it make sense to add such an `Operator` along with its corresponding `Observable.mapError` / `Single.mapError` methods to RxJava directly?

**Comment by akarnokd** [comment]
There is the `onErrorReturn` and `onErrorResumeNext` operators that will give you the Throwable which you can then map to a value or another error through `Observable.error()`, i.e.:

```java
source.onErrorResumeNext(e -> Observable.error(e.getCause()))...
```

**Comment by davidmoten** [comment]
'materialize()' is useful in this regard too

**Comment by twz123** [comment]
Ah yeah, `onErrorResumeNext` is a bit more verbose, but does the trick, thanks! On the other hand, there's no `onErrorResumeNext` for `Single`, only `onErrorReturn`, which cannot be used for the described use case.

Would it then perhaps make sense to add an implementation of `onErrorResumeNext` to `Single`, too?

**Comment by artem-zinnatullin** [comment]
I'll add required operators for `Single`, first one is #3655, next one later.

@twz123 looks like your issue is now resolved? If so — please close it :)

**Comment by twz123** [comment]
Cool! `onErrorResumeNext(Func1<Throwable, Single>)` would be the thing I need. I'll close this and wait for the PR ;) Thanks a lot!

**Comment by twz123** [comment]
See #3766 for second part...
