### ISSUE TITLE
Add support for adding multiple subscriptions to a composite subscription at once

### ISSUE THREAD

**Issue by ZakTaccardi** [ReactiveX/RxJava#3654]
Instead of multiple `compositeSubscription.add(subscription)` calls, it would be nice to be able to do something like `compositeSubscription.add(Subscription... subscriptions)`.

Currently you can only do something like this in the constructor for `CompositeSubscription`.

**Comment by akarnokd** [comment]
Hi. What is your use case for it? Does it have to be atomic?

I particularly never needed such a method but PRs are welcome.

**Comment by ZakTaccardi** [comment]
It would help reduce the verbosity of multiple `compositieSubscription.add(subscription)` calls.

I'm calling it from the main thread (android) to register for events, so no it would not need to be atomic for my specific use case.

**Comment by akarnokd** [comment]
#3720

**Comment by akarnokd** [comment]
Closing via #3720
