### ISSUE TITLE
Take and debounce usage

### ISSUE THREAD

**Issue by httpdispatch** [ReactiveX/RxJava#3656]
I have the next test case
```    @Test
    public void testLimitAndPublishSubject() throws InterruptedException {
        PublishSubject<Boolean> mBooleanPublishSubject = PublishSubject.create();
        mBooleanPublishSubject.asObservable()
                .doOnEach(__ -> System.out.println("on value emitted "+System.currentTimeMillis()))
                .take(1)
                .doOnEach(__ -> System.out.println("on value emitted 2 "+System.currentTimeMillis()))
                .debounce(1000, TimeUnit.MILLISECONDS)
                .doOnEach(__ -> System.out.println("on value emitted 3 "+System.currentTimeMillis()))
                .subscribe(__ -> System.out.println("done "+System.currentTimeMillis()));
        mBooleanPublishSubject.onNext(true);
        Thread.sleep(1000);
        mBooleanPublishSubject.onNext(true);
        Thread.sleep(2000);
    }
```
and the output is
```
on value emitted 1454063289770
on value emitted 2 1454063289770
on value emitted 2 1454063289779
on value emitted 3 1454063289780
done 1454063289780
on value emitted 3 1454063289780
```

I can't figure out why the `on value emitted 2` and `on value emitted 3` appears in the log twice and why the debounce delay doesn't work. Can somebody please help?

**Comment by akarnokd** [comment]
Hi. The debounce doesn't work because with `take(1)` you immediately complete the stream which forces debounce to emit (because no further value will come thus it's safe to emit the last value).

As for why the duplication, doesn't look to me right either so I'll investigate it further.

**Comment by httpdispatch** [comment]
Thank You for the help. Should i use flatMap or defer to overcome the debounce issue?

**Comment by akarnokd** [comment]
The reason you see the duplication because you peek via `doOnEach` which is get called for `onNext` and `onCompleted` in your test. You can see this if you append the `__` to the output:

```java
                .doOnEach(__ -> System.out.println("on value emitted "+System.currentTimeMillis() + __))
```

which prints:

```
on value emitted 1454068146563[rx.Notification@1e307009 OnNext true]
on value emitted 2 1454068146563[rx.Notification@1e307009 OnNext true]
on value emitted 2 1454068146565[rx.Notification@4edde6e5 OnCompleted]
on value emitted 3 1454068146565[rx.Notification@1e307009 OnNext true]
done 1454068146565
on value emitted 3 1454068146565[rx.Notification@4edde6e5 OnCompleted]
```

If you are not interested in all the event types, use `doOnNext` instead.

**Comment by httpdispatch** [comment]
Oh, thank you very much for explanation

**Comment by akarnokd** [comment]
> Thank You for the help. Should i use flatMap or defer to overcome the debounce issue?

That do you want to achieve in the first place? Using `take(1).debounce()` is pointless because there won't be more values for debounce to work on.

**Comment by httpdispatch** [comment]
I want the subscription to work like a replacement for CountDownTimer. When first event arrives - timer starts. All next events should be ignored

**Comment by akarnokd** [comment]
In this case, you can use delay instead:

```java
source.take(1).delay(1, TimeUnit.SECONDS)...
```

**Comment by httpdispatch** [comment]
Looks like flatMap also works, but your solution is much better. Thank You very much for your help
