### ISSUE TITLE
Sample operator: last item before termination is dropped after sampling

### ISSUE THREAD

**Issue by kboyarshinov** [ReactiveX/RxJava#3657]
Hi. Recently I found that `sample` operator drops last value before `onCompleted` event. This is behaviour is valid according to these discussions https://github.com/ReactiveX/RxJava/pull/566 and https://github.com/ReactiveX/RxJava/pull/571 and this [test](https://github.com/ReactiveX/RxJava/blob/1.x/src/test/java/rx/internal/operators/OperatorSampleTest.java#L190). It originated in Rx.NET and still exists in RxJava to be consistent across all implementations as far as I understood.

But, marble diagram in documentation shows otherwise: item 5 is emitted before termination and sampled by sampler.
![sample_marble](https://cloud.githubusercontent.com/assets/1917615/12701532/b435ef44-c846-11e5-841f-92eb8d4c4418.png)

This behaviour is odd and unexpectable. I stumbled across it trying to resolve backpressure issue with observables where last emitted item is the most important.

So, my question is whether it can be changed? I prepared [a commit](https://github.com/kboyarshinov/RxJava/commit/29ad810a7d134afa0b43703fcd162e1cfee006de) with fixes and corresponding tests. 
Or at least marble diagram should be changed to showcase this behaviour and it would be good to have a note about it in documentation.

Thank you.

**Comment by akarnokd** [comment]
What about when the source completes and the sampler doesn't?

**Comment by kboyarshinov** [comment]
@akarnokd it would emit the last item from completed source and nothing after that, no?

**Comment by akarnokd** [comment]
Right, the diff tricked me. I expected 3 calls to emit, 1 in sampler's onNext, 1 in sampler's onCompleted and 1 in parent's onCompleted.

Besides, I can see that operator still has some issues with unsubscription and backpressure management.

**Comment by kboyarshinov** [comment]
Yep, 2 calls is enough: 1 in sampler's onNext and 1 in parent's onCompleted.

**Comment by akarnokd** [comment]
So if the sampler completes, then the value should be dropped just like now?

**Comment by kboyarshinov** [comment]
It is ok in my usecase. If sampler completes before source completes it means no values are expected before completion. But if source completes before sampler does it should emit last value. 

However, it worth discussion.

**Comment by akarnokd** [comment]
See #3658 that contains other fixes.

**Comment by kboyarshinov** [comment]
Great! Also `OperatorSampleWithTime` will require fixes too.

**Comment by akarnokd** [comment]
Would you like to submit a PR?

**Comment by kboyarshinov** [comment]
@akarnokd I would like to. Will submit soon.

**Comment by kboyarshinov** [comment]
Done https://github.com/ReactiveX/RxJava/pull/3757

**Comment by akarnokd** [comment]
#3757 merged.
