### ISSUE TITLE
Ambiguous reference error raised by error-prone

### ISSUE THREAD

**Issue by ppeeth** [ReactiveX/RxJava#3666]
Compiling with error-prone (Gradle error-prone plugin version 0.0.8, java full version "1.8.0_60-b27") raises ambiguous reference error while calling Observable.subscribe(Subscriber) method. 
The conflict is with Observable.subscribe(Observer) as Subscriber implements Observer interface.

Observable.subscribe(Observer) method checks if the Observer passed in, is an instanceof Subscriber and calls Observable.subscribe(Subscriber).

**Comment by akarnokd** [comment]
Those are there for historical reasons and I haven't run into issues with javac/Eclipse regarding them.

**Comment by akarnokd** [comment]
Let me know if you have further issues.
