### ISSUE TITLE
`Observable.scan()` overload to take a factory for initial value?

### ISSUE THREAD

**Issue by NiteshKant** [ReactiveX/RxJava#3667]
Currently the scan operator has [an overload](https://github.com/ReactiveX/RxJava/blob/1.x/src/main/java/rx/Observable.java#L7356) to take an initial value for the accumulation. The problem with this is that the initial value is the same for all subscribers of this observable, which hardly is intended by the user. It is actually a source of subtle bugs for a casual user.

I think there should atleast be an overload that instead of the realized initial value takes a factory for the initial value for each subscription. The underlying [`OperatorScan`](https://github.com/ReactiveX/RxJava/blob/1.x/src/main/java/rx/internal/operators/OperatorScan.java#L73) already supports an initial value factory.

I would also suggest to either deprecate the current `scan()` method or if it is usable in some cases, atleast put a warning in the javadoc.

**Comment by zsxwing** [comment]
See #1881 for the type erase issue and #1884 for `collect`.

**Comment by NiteshKant** [comment]
Thanks @zsxwing. But `collect` and `scan` have different behaviors, isn't? 
So, the question here still makes sense?

**Comment by NiteshKant** [comment]
If there is some agreement on what to do here, I can send a PR.

**Comment by zsxwing** [comment]
Technically, you can implement `scan(Func0, accumulator)` using `collect`. I tried in RxScala but the code looks ugly, so I'm very happy to have a `scan` overload. However, we need a new method name due to the ambiguity. Any suggestion for the new method name?

**Comment by akarnokd** [comment]
PRs are always welcome and sometimes the only means to get people moving around here.

**Comment by akarnokd** [comment]
See #3959.

**Comment by akarnokd** [comment]
Due to potential problems with the two parameter variant proposed in #3959, I added some javadoc instead showing how one can use `defer` to avoid sharing the mutable initial value (#4063).

If you have further input on the issue, don't hesitate to reopen this issue or post a new one.
