### ISSUE TITLE
Make Observable.doOnCompleted name match Completable.doOnComplete in 1.x

### ISSUE THREAD

**Issue by zach-klippenstein** [ReactiveX/RxJava#3700]
`Observable` has a `doOnCompleted` method (past tense), and `Completable` has `doOnComplete` (present tense). The 2.x branch changes `Observable`'s method to be present tense. The 1.x branch can add alias the past tense method in `Observable` and deprecate it.

I'm happy to make the change if this is approved.

**Comment by akarnokd** [comment]
Sure.
