### ISSUE TITLE
Confused about documentation of replay()

### ISSUE THREAD

**Issue by DavidMihola** [ReactiveX/RxJava#3703]
In the [documentation of the `replay()` operator in RxJava](http://reactivex.io/documentation/operators/replay.html) it says

> In RxJava there is a variety of the replay operator that returns a connectable Observable. You must Publish this connectable Observable before observers can subscribe to it, and then Connect to it in order to observe its emissions.

This means I should do the following, right?

    ConnectableObservable replayedAndPublished = sourceObservable
        .replay()
        .publish();
   
    replayedAndPublished.subscribe(...);
    replayedAndPublished.subscribe(...);

    replayedAndPublished.connect();

Why is that? Why do I have to add a `publish()` after the `replay()`? Like `publish()`, `replay()` also returns a `ConnectableObservable`, so why can't I just `subscribe()` to one returned by `replay()` and then `connect()` to _that_?

And regarding the second variety of `replay()` - the one that returns an ordinary `Observable`:
* Is the resulting Observable also meant to be subscribed to by multiple `Subscriber`s?
* Since it does not have a `connect()`, it will subscribe to its source Observable immediately when the first Subscriber subscribes to it?
* When will it unsubscribe?
* How is it different from `replay().map(new Func1(...))` - or maybe `cache().map(new Func1(...))`?

I am asking about the second variety more out of curiosity but I use the first variety every now and then so I'd really like to understand it properly.

**Comment by akarnokd** [comment]
That sentence is bad, you don't have to publish a `ConnectableObservable`.

The `publish` and `replay` operators that simply return an `Observable` publish or replay for the sake of the function you also have to pass. Each subscriber will get an individually published/replayed connection to the upstream. For example, you can consume a source twice but without duplicating the side-effects of subscribing to the upstream:

```java
Observable.range(1, 10).publish(o -> Observable.concat(o.take(2), o.takeLast(2))).subscribe(...)
```
Here, `range` will be subscribed once even though the inner function's take/takeLast would suggest otherwise.

With `replay().map` you are mapping the items, whereas `replay(Func1) you are reusing the same shared `Observable`.

**Comment by DavidMihola** [comment]
1.) Thanks for the confirmation!

2.) Ah! Yes, that makes sense and in that case it also obviously different from `map()`. The signature of that variant of the method should have given me clue:

        public final <R> Observable<R> replay(Func1<? super Observable<T>, ? extends Observable<R>> selector)

But in that case, isn't the documentation wrong again? It says:

>  this function accepts an item emitted by the source Observable as its parameter, and returns an item to be emitted by the resulting Observable.

This reads almost exactly like the description of `map()`:

> The Map operator applies a function of your choosing to each item emitted by the source Observable, and returns an Observable that emits the results of these function applications.

Shouldn't that me something more along the lines of

> this function accepts the source Observable as its parameter, and returns a transformed version of that Observable.

One last thing: I think I'll have to post another question about hot vs. cold Observables soon, but applied to replay(): Is it true that the first variety transforms the source into a hot Observable while the second one leaves it cold?

**Comment by akarnokd** [comment]
> Shouldn't that me something more along the lines of

The function will receive an Observable which can be subscribed to as many times as necessary without causing multiple subscriptions to the upstream Observable. The function then should return an Observable whose values will be emitted to the downstream subscriber.

> Is it true that the first variety transforms the source into a hot Observable while the second one leaves it cold?

Yes.

**Comment by akarnokd** [comment]
This should be fixed via https://github.com/ReactiveX/reactivex.github.io/pull/253 now.
