### ISSUE TITLE
concatMapEager and maxConcurrent

### ISSUE THREAD

**Issue by adi1133** [ReactiveX/RxJava#3710]
How should I limit the maximum number of concurrently subscribed observables ?

I think a parameter like the one in flatMap (maxConcurrent) could be very useful.
concatMapEage currently has an optional parameter, capacityHint.

I think this is not very useful, I expected to find something like maxConcurrent
This operator might be confusing for some people, similar with #3498

**Comment by akarnokd** [comment]
The operator was designed to be eager on the input side and bounded on the mapped inner Observables.

I agree that adding a parameter would be confusing to `concatMapEager` but you can name the maxConcurrent+capacityHint version like `orderedMerge` or something like it.

Would you like to post a PR for this?

**Comment by adi1133** [comment]
Are you proposing to rename`concatMapEager(Func1 mapper, int capacityHint)` into `orderedMerge` ?

**Comment by akarnokd** [comment]
Don't rename `concatMapEager`, just add an overload `concatMapEager(Func1 mapper, int capacityHint, int maxConcurrency)` and modify the `OperatorConcatMapEager` to support the maxConcurrency mode.

**Comment by adi1133** [comment]
I am not sure how to write a proper test case for this change

**Comment by akarnokd** [comment]
Add a `doOnRequested` before the operator and capture the long values in a List. Then compare it against the expected pattern, i.e., `5, 1, 1, 1, 1, 1, 1`.

**Comment by akarnokd** [comment]
Closing via #3714
