### ISSUE TITLE
flatMapIterable with maxConcurrent

### ISSUE THREAD

**Issue by ginbalin** [ReactiveX/RxJava#3711]
As far as I saw flatMapIterable doesn't have maxConcurrent parameter and thus doesn't offer a way to apply backpressure. In order to align it with other flatMap would be good to add an overload with maxConcurrent.

What do you think?

**Comment by akarnokd** [comment]
PR is welcome.

**Comment by ginbalin** [comment]
Although you stated here that this was useless https://github.com/ReactiveX/RxJava/pull/2627 . Is it really the case?
I believe with current implementation this would be usefull to control backpressure.

**Comment by akarnokd** [comment]
I was wrong back then.

**Comment by akarnokd** [comment]
Closing via #3722
