### ISSUE TITLE
new method concatMapIterable

### ISSUE THREAD

**Issue by ginbalin** [ReactiveX/RxJava#3713]
Hello,

I think it would be nice to have an concatMapIterable method beeing the counterpart of flatMapIterable.
Indeed concatMapIterable  would seems to me the best and safest way to flatten a Observable<List<T>> -> Observable<T>

Problem with flatMapIterable is that as flatMap use by default an unbounded buffer and unlimited source subscription. I recently had the problem having a producer producing faster than a consumer.
I naively used flatMap(t->Observable.from(t)) or flatMapIterable to flatten the produced list wich always lead to OutOfMemory. 
concatMap on the other way doesn't have this issue and thus would be safer to use to flatten Observable<List> for which you don't have implementation detail.

I'm quite new with RxJava so please tell me if I totaly missed the point.

**Comment by akarnokd** [comment]
PRs are welcome, but note that some are concerned with the API surface area and may not want a convenience overload such as this.

**Comment by akarnokd** [comment]
Closing via #3718
