### ISSUE TITLE
SerializedBehaviorSubject

### ISSUE THREAD

**Issue by hzsweers** [ReactiveX/RxJava#3723]
Looking at the changes in #2470, a useful `getValue()` method was added to `BehaviorSubject`. This goes away though if you want to serialize it. Would there be feasible to have something like a `SerializedBehaviorSubject` that maintains the API of `BehaviorSubject`?

**Comment by akarnokd** [comment]
You can keep a reference to the original BehaviorSubject; the method is threadsafe by itself.

**Comment by hzsweers** [comment]
Ah! Good to know, thanks!
