### ISSUE TITLE
APIs for easily changing the thread priority of default schedulers via hook.

### ISSUE THREAD

**Issue by JakeWharton** [ReactiveX/RxJava#3724]
On Android, the main thread is a sacred holy land at which we must all worship. As such this means other threads (ideally) shouldn't be favorably scheduled in priority with it. For network and filesystem operations this usually means using low priority threads.

One solution is to just use low priority threads on our own schedulers, but this doesn't affect code using the standard `io()` and `computation()` schedulers. Unfortunately there's a whole bunch of ceremony around how various schedulers are initialized which includes a mixed bag of public vs. non-public types and APIs which makes replacing them in a scheduler hook difficult.

I think the most easy way to accomplish this is the following:
 * [x] ~~`RxThreadFactory` constructor overload which takes a thread priority to use.~~ Not needed.
 * [ ] Factory methods on `Schedulers` for creating instances of `io()`, `computation()`, and `newThread()` except using a supplied `ThreadFactory`
   * [ ] `Schedulers.createIoScheduler(ThreadFactory)`
   * [ ] `Schedulers.createComputationScheduler(ThreadFactory)`
   * [ ] `Schedulers.createNewThreadScheduler(ThreadFactory)`

Nice to have:
 * [x] `Schedulers` using these factory methods to create the default implementations. This involves moving the thread factories from the individual types "up" to `Shedulers`.

**Comment by JakeWharton** [comment]
Happy to do some of the work if this sounds acceptable.

**Comment by stevegury** [comment]
@JakeWharton I think that sound acceptable, I'm happy to review your PR.

**Comment by JakeWharton** [comment]
This is a little more tricky than I had initially anticipated. Perhaps it's worth talking about a means of setting the default priority of the internal thread pools through a mechanism like properties as a separate, easier first step? Plus that would be a lot lower-overhead for Android users anyway, and we could even use the existing Android platform detection to lower the thread priority by default.

**Comment by erDaren** [comment]
so, how to set thread priority in android with android values(like`Process.THREAD_PRIORITY_BACKGROUND`)?

**Comment by JakeWharton** [comment]
Pass a ThreadFactory
