### ISSUE TITLE
Completable.subscribe() swallows errors by default

### ISSUE THREAD

**Issue by kotucz** [ReactiveX/RxJava#3726]
The default behavior of `Completable.subscribe()` for errors is different from that of `Observable` or `Single`. Errors in `Completable` are just passed to `RxJavaErrorHandler` which does nothing by default. While `Observable` and `Single` cause runtime `OnErrorNotImplementedException` which is expected. 

*Completable.java*

            @Override
            public void onError(Throwable e) {
                ERROR_HANDLER.handleError(e);
            }

*Observable.java*

            @Override
            public final void onError(Throwable e) {
                throw new OnErrorNotImplementedException(e);
            }

**Comment by akarnokd** [comment]
Throwing like `Observable` relies on the expectation that the execution won't switch to other thread. This `OnErrorNotImplemented` is remnant of the imperative style of programming. Using try-catch around a sequence doesn't make sense and throwing upward has no guarantees either.

**Comment by kotucz** [comment]
I do not want to wrap the `subscribe()` call in try-catch. Problem is that I do when I not specify `onError` callback in `Completable.subscribe()` I do not expect the completable to emit and error. But when the `Completable` emits an unexpected error, that is an programming error and shall be processed as such. The `OnErrorNotImplementedException` is then expected to e.g. crash the application.

**Comment by loganj** [comment]
@akarnokd Throwing upward does have a crucial guarantee-- reaching the thread's uncaught exception handler.  

Delivering to the plugin is effectively swallowing the exception, since it receives all exceptions and cannot safely propagate any of them anywhere.

Failing to propagate exceptions was a huge problem (#1682) in scheduled actions before 1.0.

**Comment by akarnokd** [comment]
PRs are welcome.

**Comment by loganj** [comment]
:+1: Working on one now. Just going to deliver to the uncaught exception handler after the plugin, wherever it seems to make sense.

**Comment by loganj** [comment]
@akarnokd Can you explain the usage of `toNpe()` in Completable, e.g. here?: https://github.com/ReactiveX/RxJava/blob/1.x/src/main/java/rx/Completable.java#L1946

**Comment by akarnokd** [comment]
You can replace/precede them with `Exceptions.throwIfFatal`.
