### ISSUE TITLE
failed to build RxJava ,this is my first try gradle,don't know how to solve this problem

### ISSUE THREAD

**Issue by joe-zheng** [ReactiveX/RxJava#3729]
it repository not found at D:\Opensource\JAVA\RxJava-1.x -- nebula-release tasks will not be available. Use the git.root Gradle property to specify a different directory.

FAILURE: Build failed with an exception.

* Where:
Build file 'D:\Opensource\aJAVA\RxJava-1.x\build.gradle' line: 9

* What went wrong:
A problem occurred evaluating root project 'rxjava'.
> Failed to apply plugin [class 'nebula.plugin.rxjavaproject.RxJavaReleasePlugin']
   > Cannot set property 'defaultVersionStrategy' on null object

any clue to solve this problem, i googled but stilled can't found answer

Thanks!

**Comment by akarnokd** [comment]
You have to check out the source via git and then you will be able to run gradle. The zip option doesn't work.

**Comment by joe-zheng** [comment]
Thanks a lot, i will try again

**Comment by Fox-Legend** [comment]
I also have this question，Have you solved it?　can you tell me the answer?

**Comment by mlick** [comment]
I am too. have solved it?

**Comment by joe-zheng** [comment]
sorry ,i haven't try it

**Comment by mlick** [comment]
I Have Sovled It!   <#3978(comment)>,

**Comment by ZJL2018** [comment]
I am using SVN as a version control tool ,so how should I do to solve this?
