### ISSUE TITLE
Request: Completable.andThen(Single)

### ISSUE THREAD

**Issue by GrahamRogers** [ReactiveX/RxJava#3730]
To match `Completable#andThen(Observable<T> next)` it would be nice if there were an operator like this:

    public <T> Single<T> andThen(Single<T> next)

**Comment by akarnokd** [comment]
I don't know, do you want the next's value replace the first's value.

**Comment by JakeWharton** [comment]
There is no first value because the method is on `Completable`. It's essentially a `flatMap`.

**Comment by akarnokd** [comment]
Right, didn't connect `Completable`. I don't see any problem with such an overload. PRs are welcome.

**Comment by GrahamRogers** [comment]
I'll probably give it a go this weekend if no-one else has started.

**Comment by stevegury** [comment]
Sounds good, glad to review a PR.

**Comment by geralt-encore** [comment]
Will implementation be just like:

```
    public final <T> Single<T> andThen(Single<T> next) {
        requireNonNull(next);
        return next.toObservable().delaySubscription(toObservable()).toSingle();
    }
```

Or it is a bad practice to use these wrappers internally?

**Comment by akarnokd** [comment]
If you took the time and implement this operator directly, that would be great.

**Comment by akarnokd** [comment]
Closing via #3799
