### ISSUE TITLE
Request: Single.using

### ISSUE THREAD

**Issue by GrahamRogers** [ReactiveX/RxJava#3732]
To match `Observable.using`

    public static <T, Resource> Single<T> using(
            Func0<Resource> resourceFactory,
            Func1<? super Resource, ? extends Single<? extends T>> singleFactory,
            Action1<? super Resource> disposeAction)

and

    public static <T, Resource> Single<T> using(
            Func0<Resource> resourceFactory,
            Func1<? super Resource, ? extends Single<? extends T>> singleFactory,
            Action1<? super Resource> disposeAction, boolean disposeEagerly)

**Comment by akarnokd** [comment]
Would you like to submit a PR?

**Comment by akarnokd** [comment]
I'll do this.

**Comment by akarnokd** [comment]
See #3752

**Comment by artem-zinnatullin** [comment]
PR was merged and released as part of v1.1.2, this issue can be closed!

**Comment by akarnokd** [comment]
Closing via #3752.
