### ISSUE TITLE
Proposal: Add "Help Wanted" labels for feature requests that the project is open to PRs for

### ISSUE THREAD

**Issue by hzsweers** [ReactiveX/RxJava#3734]
`Help Wanted`, `PRs Welcome`, etc. Would be helpful for those looking to contribute

**Comment by prt2121** [comment]
:+1:  good idea

**Comment by akarnokd** [comment]
I'd like to encourage feature-requesters to go ahead and implement their proposals as PRs. It's not about our lack of technical knowledge or time to do it ourselves, but the opportunity to get others engaged in RxJava. So in that sense, many community content would be flagged as either of these, which I already do with the feature-request tag.

**Comment by hzsweers** [comment]
Good point. Maybe the collaborators can be more proactive about
suggesting/inviting that in issues rather than the help wanted label. My
main point is that just putting the "feature request" label alone might not
make it clear to the issue author or others if it's something the
collaborators would be interested in, so they won't put in the work to open
a PR.

**Comment by akarnokd** [comment]
Added a label, see the example on this issue.

**Comment by hzsweers** [comment]
:+1:
