### ISSUE TITLE
How to get filtered POJO when used getXXX()?

### ISSUE THREAD

**Issue by deviltsw** [ReactiveX/RxJava#3736]
```
.flatMap(new Func1<Area, Observable<Store>>() {
    @Override
     public Observable<Store> call(Area area) {
        return Observable.from(area.getStores());
     }
})
.filter(new Func1<Store, Boolean>() {
    @Override
    public Boolean call(Store store) {
        return store.getName().contains(text);
    }
})
```
> i want to get the filtered **Area**

**Comment by davidmoten** [comment]
One way is to wrap every instance of Store with its Area:

```java
.flatMap(area -> 
    Observable.from(area.getStores())
        .map(store -> new Wrapper(area, store)))
.filter(wrapper -> wrapper.store().getName().contains(text))
.map(wrapper ->wrapper.area());
```

**Comment by kotucz** [comment]
or you could use this trick

    oa.flatMap(new Func1<Area, Observable<Area>>() {
            @Override
            public Observable<Area> call(final Area area) {
                return Observable.from(area.getStores())
                        .filter(new Func1<Store, Boolean>() {
                            @Override
                            public Boolean call(Store store) {
                                return store.getName().contains(text);
                            }
                        })
                        .map(new Func1<Store, Area>() {
                            @Override
                            public Area call(Store store) {
                                return area;
                            }
                        });
            }
        });

but you maybe do not need to wrap Stores in the `Observable` so this should be fine too

    oa.filter(new Func1<Area, Boolean>() {
            @Override
            public Boolean call(Area area) {
                return areaHasStoreWithText(area, text);
            }
        });

**Comment by davidmoten** [comment]
One thing to note is that my suggestion and @kotucz first suggestion both potentially produce multiple copies of `Area` so you might want to use `.distinct()`.

**Comment by akarnokd** [comment]
@deviltsw Are the answers satisfactory?

**Comment by deviltsw** [comment]
@akarnokd yes.
