### ISSUE TITLE
New Operator Request Pluck

### ISSUE THREAD

**Issue by digitalbuddha** [ReactiveX/RxJava#3737]
Seems like "pluck" would be a useful operator.  RxJs has it implemented, any reason to not port over to RxJava as well? I would be happy to open the pr if feature request is approved. Pluck "Returns an Observable containing the value of a specified nested property from all elements in the Observable sequence. If a property can't be resolved, it will return undefined for that value."
Reference: https://github.com/Reactive-Extensions/RxJS/blob/master/doc/api/core/operators/pluck.md

**Comment by JakeWharton** [comment]
Seems inherently unsafe in a library thats otherwise very safe with regard to the type system. For this to work you'd need to specify the type of the thing you were reflecting on.
```java
users.pluck("firstName", String.class)
```
This doesn't seem any better than
```java
users.map(u -> u.firstName)
```
Which is shorter and safer both against refactoring and with type safety.

**Comment by digitalbuddha** [comment]
makes sense, thank you for explanation. closing
