### ISSUE TITLE
SafeSubscriber.java the 141 line always throw the exception

### ISSUE THREAD

**Issue by petma** [ReactiveX/RxJava#3739]
SafeSubscriber.java the 141 line always throw the nullpointexception
the actual'subscriber is null,but I don't know why

**Comment by akarnokd** [comment]
Do you have a code example to help us repoduce the problem?

**Comment by petma** [comment]
I find out the reason:
  public Subscriber<Week> getSubscriber() {
        return new Subscriber<Week>() {
……
          @Override
            public void onNext(Week week) {
                iView.setModel(week);
                iView.setLoading(false);
                if(week!=null) {
                    onCompleted();
                }

            }  
……
}}
in Activity which implements iView.setModel<T>,I do this work:
 @Override
    public void setModel(Week week) {
        if(week!=null) {
            mSyllabusView.setWeek(week);
            mSyllabusView.show();
        }else{
            times--;
            if(times>0) {
                syllabusPresenter.start();
            }
        }
    }

and the really error is from  mSyllabusView.show(); this method throws a nullpoint exception.but It does't  evident in the console;

**Comment by akarnokd** [comment]
Great!
