### ISSUE TITLE
ConcurrentModificationException in RxJavaPlugins.getPluginImplementationViaProperty

### ISSUE THREAD

**Issue by niqo01** [ReactiveX/RxJava#3749]
I am using RxJava 1.1.1 on Android and getting the following error:
```java
Caused by java.util.ConcurrentModificationException
       at java.util.Hashtable$HashIterator.nextEntry(Hashtable.java:727)
       at java.util.Hashtable$EntryIterator.next(Hashtable.java:778)
       at java.util.Hashtable$EntryIterator.next(Hashtable.java:776)
       at rx.plugins.RxJavaPlugins.getPluginImplementationViaProperty(RxJavaPlugins.java:177)
       at rx.plugins.RxJavaPlugins.getSchedulersHook(RxJavaPlugins.java:232)
       at rx.schedulers.Schedulers.(Schedulers.java)
       at rx.schedulers.Schedulers.(Schedulers.java)
```

My code is 

```java
unreadConversationsServer = unreadConversations;
      final Scheduler.Worker worker = Schedulers.io().createWorker();
      worker.schedule(() -> {
        try {
          computeUnreadUnSyncedConversationCount();
        } catch (Exception e) {
          Timber.e(e, "Error while computing Unread Unsynced Conversation Count");
        }
        worker.unsubscribe();
      });
```
Full detail here: http://crashes.to/s/4ecb8083b7f

**Comment by akarnokd** [comment]
You seem to have something changing `System.getProperties()` concurrently with the initialization of the plugin.

**Comment by artem-zinnatullin** [comment]
Ping @niqo01: were you able to fix the problem? 

@akarnokd gave most possible reason of the issue, probably some third-party library modifies system properties concurrently (you can debug access to system properties to find that out).

// We can try to `clone()` properties before iterating over them (it's a `Hashtable` (ew) which is `synchronized` almost everywhere but iterating), but personally, I'd like to not do it if possible.

**Comment by akarnokd** [comment]
I don't know what kind of map it is thus copying might have the same issue. We could catch the CME and retry the operation with a fresh iterator.

**Comment by zsxwing** [comment]
`clone` looks good to me, since it's called only `once` for each hook. We won't lose any performance after warming up.

> I don't know what kind of map it is thus copying might have the same issue. We could catch the CME and retry the operation with a fresh iterator.

According to the javadoc of Properties, I think `clone` is safe.

> Each key and its corresponding value in the property list is a string.
> Because Properties inherits from Hashtable, the put and putAll methods can be applied to a Properties object. Their use is strongly discouraged as they allow the caller to insert entries whose keys or values are not Strings. The setProperty method should be used instead. If the store or save method is called on a "compromised" Properties object that contains a non- String key or value, the call will fail. Similarly, the call to the propertyNames or list method will fail if it is called on a "compromised" Properties object that contains a non- String key.

**Comment by akarnokd** [comment]
@zsxwing Great!

**Comment by akarnokd** [comment]
Closing via #3822
