### ISSUE TITLE
 Subject<T1, T2> implementation in which T1 != T2 

### ISSUE THREAD

**Issue by bobymicroby** [ReactiveX/RxJava#3750]
Hello guys,

I have a use case where I need a ```Subject<T1,T2>```  implementation for rxjava like  [the  one shown in the 101 samples](http://rxwiki.wikidot.com/101samples#toc45) 
I am trying to create a wrapper around google's grpc-java's bidirectional streaming
```java
public StreamObserver<Request>  call(final StreamObserver<Response> responseObserver) {
```

So my question is, is there a implementation of ```Subject<T1,T2>``` for rxjava ? 

Regards,B.

**Comment by akarnokd** [comment]
Not sure what you want to achieve. We have `Subject<T, R>` as an abstract base class and same-type implementations such as `PublishSubject<T>`. That pattern looks like RxJava's lift() Operator where you have to instantiate a StreamObserver and wrap the responseObserver with a transformation.

**Comment by bobymicroby** [comment]
Hello  @akarnokd 

I am trying to create a RxJava wrapper around Google's [Java gRPC implementation](https://github.com/grpc/grpc-java), an HTTP/2 based RPC http://grpc.io.  

The java client side rpc method, supporting bi-directional streaming is generated from a service definition that looks like this:
 ```
rpc  call(stream Request) returns (stream Response) {}
```
which generates a java stub : 

```java
public io.grpc.stub.StreamObserver<Request> call(
        io.grpc.stub.StreamObserver<Response> responseObserver);
```

The  [StreamObserver](https://github.com/grpc/grpc-java/blob/master/stub/src/main/java/io/grpc/stub/StreamObserver.java) has the same signature as RxJava Observer. For sending Request messages, a  ```StreamObserver``` is provided by the stub to the the application, while for Response messages, I must implement a ```StreamObserver```  and pass it to the stub for receiving. 
The server can return Response values in onNext of the response observer, while the client is still writing messages via onNext of the request observer. Each side will always get the other's messages in the order they were written. Both the client and server can read and write in any order — the streams operate completely independently.

So, after doing some reading about RxJava ( your blog posts about Subjects ),  I have decided that I can use an implementation of  ```Subject<Request,Response> ``` that can wrap the grpc client. There are some threading issues that I have to take into consideration : Access to the ```StreamObserver<Request>``` must be serialized, while the ```StreamObserver<Response>``` will be called from the grpc implementation on a executor provided by me. 

I am still an Rx newbie, and probably missing a lot of concepts, and I was unable to find an existing implementation of Subject, or some example how to approach this problem. 
I will be really grateful if you can tell me your opinion.  Is   ```Subject<Request,Response> ```  the right direction to go?

I have an Observable that is producing Request values, which I intend to push to the server internally in the Subject. On the other hand, in the subject I will produce Response values once the grpc client notifies me via the the ```StreamObserver<Response>``` 

```
 ---Request---Request---->[ Subject<Request,Response>]-----Response---Response---->
                            calls StreamObserver<Request>
                            and listens on  StreamObserver<Response>
                                  
```

**Comment by akarnokd** [comment]
> Is Subject<Request,Response> the right direction to go?

No, this looks like our `Operator` API which is 1-on-1, not 1-on-N. Subject is rarely the answer inside a cold sequence (and can misdirect an entire library).

You need a custom Observable that calls the grpc API for each subscriber independently:

```java
Observable<Request> request = ...
Observable.create(child -> {
    StreamObserver<Request> in = call(new StreamObserver() {
        @Override public void onNext(Response r) {
            child.onNext(r);
         }
         // ...
    });
    request.subscribe(in::onNext, in::onError, in::onCompleted);
}).subscribe(...);
```

Unfortunately, I don't see an option for cancellation or proper backpressure support via grpc, so you are stuck with `onBackpressureXXX`.

**Comment by bobymicroby** [comment]
Thank you very much for the advice! I will give it a shot right away.  And thanks again for the great work you are contributing back to the OSS world. I saw your work on https://github.com/reactor/reactive-streams-commons and it is amazing.
Regards, B. 

P.S Actually grpc-java supports backpressure  and cancellation but one must implement [ClientCall](https://github.com/grpc/grpc-java/blob/master/core/src/main/java/io/grpc/ClientCall.java) himself and not use the generated stub. The guys behind the project are doing a fantastic job, but the client stub can be improved for sure.

**Comment by artem-zinnatullin** [comment]
@bobymicroby can this be closed?

**Comment by bobymicroby** [comment]
@artem-zinnatullin Sure thing.
