### ISSUE TITLE
I would like to achieve a common dialog

### ISSUE THREAD

**Issue by guoyoujin** [ReactiveX/RxJava#3769]
Hello I would like to achieve a common dialog, do not know how to achieve better, like the code below each had to re-write it again , which is not what I wanted

```java
postLoginResultUsecase.execute().retryWhen(new RetryWithDelay(3,2000)).subscribe(new Subscriber<LoginModel<User>>() {
                @Override
                public void onStart() {
                    super.onStart();
                    progressDialog.show();
                }

                @Override
                public void onCompleted() {
                    progressDialog.dismiss();
                }

                @Override
                public void onError(Throwable e) {
                    progressDialog.dismiss();
                }

                @Override
                public void onNext(LoginModel<User> userLoginModel) {
                    System.out.println(userLoginModel);
                    progressDialog.dismiss();
                    listener.onSuccess();
                }
            });
```

**Comment by akarnokd** [comment]
I don't understand what the problem is. Do you want this logic be type-independent?

```java
public static <T> void observe(Observable<T> o, Listener listener, Dialog progressDialog) {
    .retryWhen(new RetryWithDelay(3,2000)).subscribe(new Subscriber<T>() {
                @Override
                public void onStart() {
                    super.onStart();
                    progressDialog.show();
                }

                @Override
                public void onCompleted() {
                    progressDialog.dismiss();
                }

                @Override
                public void onError(Throwable e) {
                    progressDialog.dismiss();
                }

                @Override
                public void onNext(T v) {
                    System.out.println(v);
                    progressDialog.dismiss();
                    listener.onSuccess();
                }
            });
}

observe(postLoginResultUsecase.execute(), listener, progressDialog);

observe(someRequest.execute(), listener, progressDialog);

observe(otherRequest.execute(), listener, progressDialog);
```

**Comment by guoyoujin** [comment]
@akarnokd Thank you，I have found a solution, may be my description of the problem is unclear , please forgive me ,This is the solution I found , can some advice


`public class BindDialog {
    public static final String TAG = "BindDialog";
    public static final <T> Observable<T> bindDialogLoading(final Dialog dlg, final Observable<T> source) {
        final Observable<T> o = source.observeOn(AndroidSchedulers.mainThread());
        return o.lift(new Observable.Operator<T, T>() {
            @Override
            public Subscriber<? super T> call(final Subscriber<? super T> child) {
                return new Subscriber<T>() {
                    @Override
                    public void onStart() {
                        super.onStart();
                        Log.e("onStart=======","dialog show");
                        new Handler(Looper.getMainLooper()).post(new Runnable() {
                            @Override
                            public void run() {
                                dlg.show();
                                Log.e("onStart===","dialog show");

                            }
                        });
                        child.onStart();
                    }

                    @Override
                    public void onCompleted() {
                        dlg.dismiss();
                        Log.e("onCompleted===","dialog dismiss");

                        child.onCompleted();
                    }

                    @Override
                    public void onError(Throwable e) {
                        dlg.dismiss();
                        Log.e("onError===","dialog dismiss");

                        child.onError(e);
                    }

                    @Override
                    public void onNext(T t) {
                        Log.e("onNext===","dialog dismiss");
                        dlg.dismiss(); // Dismiss dialog or update it. Its depend your logic.
                        child.onNext(t);
                    }
                };
            }
        });
    }
}`
