### ISSUE TITLE
2.x: Drop io.reactivex.functions, use java.util.function

### ISSUE THREAD

**Issue by dwaite** [ReactiveX/RxJava#3771]
As it appears that RxJava 2 is targeting at least Java 8 (I've heard Java 9 stated), it seems appropriate to drop at very least the duplicate functional interfaces from io.reactivex.functions. 

I can submit a pull request doing so (removing everything except Function3-Function9)

**Comment by akarnokd** [comment]
No, RxJava 2 targets Java 6 to remain in good terms with the Android folks.

**Comment by dwaite** [comment]
Will that change if Android N final release switches to OpenJDK as rumored?

**Comment by JakeWharton** [comment]
It has switched, but that doesn't help the 1.4 billion devices already
deployed yet running older versions. It also currently doesn't include the
entire standard JDK API.

**Comment by akarnokd** [comment]
Thanks @JakeWharton for the clarification. Netflix will write up a design document for 2.x sometime soon to clarify things further.
