### ISSUE TITLE
withLatestFrom interface inconsistent with combineLatest

### ISSUE THREAD

**Issue by MidnightWonderer** [ReactiveX/RxJava#3779]
Why withLatestFrom has only 1 calling signature while combineLatest has plenty of convenient overload for combining multiple observables.  
Should it be the same or this is by design?

**Comment by akarnokd** [comment]
How would you imagine those missing forms of `withLatestFrom`, especially in their behavior?

**Comment by MidnightWonderer** [comment]
Does this make sense?
a$.withLatestFrom(b$, c$, d$, new Func4<a,b,c,d>{
// use a, b, c, d relying on timing emit by a only
});

**Comment by akarnokd** [comment]
Would you like to submit a PR?

**Comment by MidnightWonderer** [comment]
I would love to if I have some spare time.  
I look into the code a bit and found out that combineLatest is just thin wrapper of OnSubscribeCombineLatest factory inside Observable class.  
The test is done on OnSubscribeCombineLatest class itself the factory methods are untested.  
  
It will be trivial if I can just create an overload by the calling exist (current) withLatestFrom method multiple times to aggregate the value one by one in Observable class without additional test on the overloads.  
  
Is this the way to go?  
If yes you can expect me to send the PR eventually.
(Don't know when. If anyone want it fast feel free to pick it up. It is just convenient overloads after all we can continue working without it.)  
If no please give me your opinion about my proposed method. At least I will learn a thing or two from this issue.

**Comment by akarnokd** [comment]
No, you have to work from `withLatestFrom` with more sources, subscribers and current values.

**Comment by MidnightWonderer** [comment]
Yep that's the reply I expected.
By looking at the code I have to integrate Iterable into the operator class.
  
For sure it will be easier than CombineLatest implementation but I don't know concurrency concerns and proper way (exist method/pattern) to handle it inside RxJava that well.
So it will require more time digging into the code I don't even sure if I am able to do it.
  
So I will say don't expect PR from me anytime soon.
Thank you for your feedback.

**Comment by akarnokd** [comment]
Do you have an use case for such an operator? I'd say it is uncommon and I'd guess the original [request](https://github.com/ReactiveX/RxJava/issues/405) for `withLatestFrom` didn't mention a multi-source version.

You can achieve an effect with some tuple types:

```java
source.withLatestFrom(b, (a, b) -> Pair.of(a, b))
.withLatestFrom(c, (ab, c) -> func.call(ab.a, ab.b, c))
```

**Comment by MidnightWonderer** [comment]
Sorry for the delay.
Yes this is coming from a real use case.
I use withLatestFrom heavily to handles Observable from user. (e.g. button pressed)

The actual case I am facing is a bit complicate but I can give you one common concrete case of multiple withLatestFrom usage. It is for handle (says) form validation and submit.
  
If all fields in form are valid the submit button will be enabled and when user press submit button all value emit from field observables will form the server request.
withLatestFrom will be used for field observables compilation based on timing of button press in this case.

Thank you for Pair suggestion but I already go with SparseArray (List, Map will work the same way too but SparseArray just fit the bill in my case) the downsize is losing type safety but it is so local so I am OK with it.

**Comment by mlatu** [comment]
I also have a use case for that. Basically I want to get latest state of several observables when main 'trigger' event happens.

I approached it by creating observable that is `combineLatest` of all the 'secondary' observables; and then used it as an argument for `withLatestFrom`. Unfortunately it involved creating of mostly useless holder object just to feed last items of several observables into `withLatestFrom`.

I guess the better way would be to use `combineLatest` chained by `distinctUntilChanged(selector)` where selector would return items of 'trigger' observable.

**Comment by dragantl** [comment]
I have a use case for this in the current project. I am using reactive sensors to keep track of motion, position, env, and location sensors. Location sensor is the driving sensor. Others use `.window(locationObservable)` to then compute min, max, avg for the windowed list for x, y, z. Because location is the driver, I was hoping that I could do:

`locationObservable.withLatestFrom(positionObs, motionObs, envObs, (location, position, motion, env) -> SensorPoint::new)...`

But it only takes just one observable.

**Comment by akarnokd** [comment]
See #3966.

**Comment by akarnokd** [comment]
Added via #3966.
