### ISSUE TITLE
Single.zip on empty collection never terminate

### ISSUE THREAD

**Issue by Centaur** [ReactiveX/RxJava#3784]
```java
Single.zip(new ArrayList<Single<Integer>>(), i -> i)
          .doAfterTerminate(() -> System.out.println("terminated"))
          .subscribe();
```
this behavior is different from `Observable.zip`

```java
Observable.zip(new ArrayList<Observable<Integer>>(), i -> i)
                   .doAfterTerminate(() -> System.out.println("terminated"))
                   .subscribe();
```

**Comment by artem-zinnatullin** [comment]
What do you expect it to do? Throw error? Single either emits one result or throws error. 

Looks like the best we can do is to throw something like `IllegalArgumentException`.

**Comment by akarnokd** [comment]
Observable.zip just completes if there are no sources. If one converts an empty Observable to single, it produces a NoSuchElementException error.

**Comment by artem-zinnatullin** [comment]
I'll check this and work on PR soon.
