### ISSUE TITLE
TestSingleSubscriber missing

### ISSUE THREAD

**Issue by vanniktech** [ReactiveX/RxJava#3785]
Is there any reason why there's no `TestSingleSubscriber` but there is `TestSubscriber`?

**Comment by artem-zinnatullin** [comment]
You can use `TestSubscriber` to test `Single`. 

Or you see some need in special test subscriber for `Single`?

**Comment by vanniktech** [comment]
I'd want to test some special functionality of the `SingleSubscriber` and hence I can't use `Subscriber` since the methods are not present there.

**Comment by artem-zinnatullin** [comment]
Can you provide any example?

**Comment by vanniktech** [comment]
I basically want to test the `onError` and `onSuccess` methods

**Comment by akarnokd** [comment]
We use:

```java
testSubscriber.assertValue(1);
testSubscriber.assertCompleted();

// or

testSubscriber.assertError(TestException.class);
```

**Comment by vanniktech** [comment]
Yeah but still I have I'm working with `SingleSubscriber` and that one is not compatible with `TestSubscriber` or am I missing something?

**Comment by artem-zinnatullin** [comment]
`Single` has `subscribe()` overload that takes `Subscriber` -> takes `TestSubscriber` too.

**Comment by vanniktech** [comment]
I want to test only the `SingleSubscriber` though

**Comment by akarnokd** [comment]
If you want, you can post a PR for `TestSingleSubscriber `.

**Comment by jenzz** [comment]
I was looking for a `TestSingleSubscriber` recently too.

I have an implementation locally based off of `TestObserver`.
Let me clean it up and I'll send over a PR.

**Comment by akarnokd** [comment]
@jenzz not necessary. Could you look at and comment on #3834 instead?

**Comment by artem-zinnatullin** [comment]
Idk, existing `TestSubscriber` can do same things, yes sometimes you have to extract values from lists, but usually it's not required with `assertValue()` and `assertError()`.

Not sure it worth to add one more entity with pretty much the same functionality. And btw, then we'll need `TestCompletableSubscriber` to have fulfilled API family.

Sorry, but I vote :-1: at the moment.

**Comment by stevegury** [comment]
I agree with @artem-zinnatullin here, I see little value to introducing a new class.

**Comment by akarnokd** [comment]
Thanks for the suggestion but we think such a class brings little to no value to RxJava and its current tests. Since `TestSingleSubscriber` doesn't have to depend on any internals of RxJava, you are welcome to implement it in your project or as a separate library.
