### ISSUE TITLE
How do I edit the marble in the documentation?

### ISSUE THREAD

**Issue by MidnightWonderer** [ReactiveX/RxJava#3804]
For combineLatest operation
![marbles](http://i.imgur.com/6p1i1Dz.png)
I want to add another color ball before the purple one to indicate that it was discarded
but I don't know how to edit that image.

So I asked.

**Comment by JakeWharton** [comment]
You probably want to file a bug on https://github.com/ReactiveX/reactivex.github.io

**Comment by JakeWharton** [comment]
Also, the source files which generate the images appear to be missing from that repository.

**Comment by MidnightWonderer** [comment]
@JakeWharton Thank you
https://github.com/ReactiveX/reactivex.github.io/issues/220

**Comment by DavidMGross** [comment]
For historical reasons, the source for the marble diagrams (an
"OmniGraffle" diagram) is checked in at the RxJava Wiki:
https://raw.githubusercontent.com/wiki/ReactiveX/RxJava/images/rx-operators.graffle

It may be time to revisit the decision to keep it there.

On Mon, Mar 28, 2016 at 2:05 PM, Sarun Rattanasiri <notifications@github.com
> wrote:

> @JakeWharton <https://github.com/JakeWharton> Thank you
> ReactiveX/reactivex.github.io#220
> <https://github.com/ReactiveX/reactivex.github.io/issues/220>
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/ReactiveX/RxJava/issues/3804#issuecomment-202580709>
>



-- 
David M. Gross
PLP Consulting
