### ISSUE TITLE
Using Lambdas in RxJava source code

### ISSUE THREAD

**Issue by stealthcode** [ReactiveX/RxJava#3805]
Opening to capture discussion regarding Retrolambda usage in RxJava. 

I believe that the current thinking is that we will make the following changes:

1. Change the build to publish a Java 1.6 jar using Retrolambda
2. Change the source code to use lambda expressions 

Are there steps that I'm missing (i.e. should there be additional incremental steps)? Is there any reason not to proceed with this?

**Comment by JakeWharton** [comment]
I would think you also want to use Animal Sniffer to enforce only JDK 6 APIs are used.

**Comment by stealthcode** [comment]
Good point. Thanks. 

@JakeWharton is there any concern with IDEs? For instance when you drill into the implementation source code will Eclipse/IntelliJ baulk at lambdas?

**Comment by JakeWharton** [comment]
That's a good question and worth investigating.

I've only used it at the application level. I can say that line numbers and metadata are preserved such that debugging continues to work well (again, only tested in an application though).

**Comment by hzsweers** [comment]
Reiterating what I brought up in the 2.x design decisions PR:

> Also, how would you include sources for the jdk6 distribution since retrolambda only operates on the bytecode? It would make the IDE have to decompile the classes to represent them rather than being able to just click in. Would this not make debugging unnecessarily more tedious and also sacrifice javadoc/comment access?

Basically, if all the JDK-6 compatible classes are generated at compile time, what will the consumer see if they try to click into the source code? I happened to come across a [library](https://github.com/damien5314/RxReddit) recently that ships retrolambda'd code, I'll dig into it later and report back.

**Comment by akarnokd** [comment]
I have mixed feelings about a middle-tier Retrolambda recompilation. Most IDEs have support for converting a lambda into a regular inner-class, even if the project itself is set to Java 6. I think we should endure the small inconvenience of using inner classes in tests.

I'm closing this issue for now but the **Animal Sniffer** suggestion is interesting, let's discuss adding that to the build process in a separate issue of #4067.
