### ISSUE TITLE
Convert an Observable stream to Completable

### ISSUE THREAD

**Issue by jmmk** [ReactiveX/RxJava#3807]
If I'm not mistaken, Completable is supposed to be a replacement for things like `Observable<Void>`, but it seems like combining them with Observables is messier.

It's possible I'm doing something weird here, but this is what I want to do:

Given
```java
Observable<Data> makeHttpCall();
Completable storeInDatabase(Data data);
```

Ideally I would be able to do something like this:
```java
Completable syncData() {
    return makeHttpCall().flatMap(storeInDatabase);
}
```

But currently this is what I have:
```java
Completable syncData() {
    return makeHttpCall()
        .flatMap(data -> storeInDatabase(data).toObservable<Void>())
        .toCompletable();
}
```

**Comment by hzsweers** [comment]
You don't explicitly have to convert it to `Observable<Void>` first, all `toCompletable()` does is basically ignore `onNext()` emissions and listen for a terminal event. If you care about non-terminal event emissions, you presumably need to make sure you're doing whatever it is you need with them before calling `toCompletable()`

**Comment by jmmk** [comment]
The problem with that is that `makeHttpCall().map(storeInDatabase)` returns `Observable<Completable>`, and if I call `toCompletable()` on that, I'm not actually waiting for the Completable to complete right? But if I call `toObservable()` on the result of `storeInDatabase`, it will hook up the subscribe correctly. My understanding of this is not clear - am I wrong here?

**Comment by akarnokd** [comment]
You can do this with some conversions:

```java
Completable.merge(makeHttpCall.map(v -> storeInDatabase(v).toCompletable())).await();
```

**Comment by jmmk** [comment]
@akarnokd to be clear, you are calling this method:

![image](https://cloud.githubusercontent.com/assets/1122242/14123903/ad7a8c20-f5d0-11e5-9e9c-e5b5cce8a6ea.png)
is that right?

Are there other methods that operate on `Observable<Completable>` like this or is it a special case?

**Comment by akarnokd** [comment]
Yes, `Completable.concat` and `Completable.mergeDelayError`.

**Comment by jmmk** [comment]
So now I have the following

```java
// Given
Observable<Data> makeHttpCall();
Completable storeInDatabase(Data data);

// Do Work
Completable syncData() {
    return Completable.merge(makeHttpCall().map(db::storeInDatabase));
}

// Subscribe
syncData().await();
```

Is this the correct way to accomplish this?

**Comment by akarnokd** [comment]
If you want to wait blockingly then yes.

**Comment by hzsweers** [comment]
Ah sorry, didn't read your full sample snipped before. Disregard my earlier comment

**Comment by jmmk** [comment]
It looks like `Completable.merge` solves my issue of transforming `Observable<Completable>` to `Completable` then. Thanks!
