### ISSUE TITLE
About Subscriber

### ISSUE THREAD

**Issue by dieyidezui** [ReactiveX/RxJava#3811]
When I watch the source code of operators, I found that in order to keep the unsubscribe chain, the parent subscriber always created by two way:

    Subscriber<T> parent = new Subscriber(child){ ... };
or

    Subscriber<T> parent = new Subscriber{ ... };
    child.add(parent);

I know that the first one can pass through the producer.
And, What else can decide the choosing?

**Comment by akarnokd** [comment]
If the parent may issue `unsubscribe` on its own, you have to chose the second pattern because otherwise the call may go downstream and cause trouble.

**Comment by dieyidezui** [comment]
@akarnokd Thanks a lot.It is really helpful.
