### ISSUE TITLE
OperatorSwitch keeping reference to previous Observable longer than expected

### ISSUE THREAD

**Issue by Thomvis** [ReactiveX/RxJava#3812]
Hi & thanks for this amazing library!

For the past few days I've been confused by some memory leaks that caused by RxJava or, more likely, my misunderstanding of RxJava. I've reduced the issue to a very simple test case that you can find here: https://gist.github.com/Thomvis/18474b51b1b4dff79191f93330ae627e.

The issue has to do with `switchMap`. I'd expect that when the source Observable emits an onNext event (containing a new Observable), the operator will unsubscribe from the previous Observable and release all references to that Observable. The unsubscribing part is happening, but the releasing is not. Because the Observable is not released, any upstream operators, anonymous inner classes and their captures are also not released and subsequently not garbage collected.

I've read https://github.com/ReactiveX/RxJava/issues/1292 and https://github.com/ReactiveX/RxJava/issues/3074, but I'm not sure if they're related.

So what I'm hoping to get from this issue is one of the following:
- My test is wrong
- I'm using `switchMap` wrong / have wrong assumptions on the memory model
- (There's a bug in OperatorSwitch)

Thanks in advance,
Thomas

**Comment by davidmoten** [comment]
I had a quick look at `OperatorSwitch` and didn't pick up on any obvious retention of references. One thing I notice from your test is that you can't assume `System.gc()` is run synchronously and to have a hope of it doing something I imagine you'd need to put a sleep in after it.

**Comment by Thomvis** [comment]
Thanks for the super quick response!

I re-ran the tests with a 1 and 10 second sleep after each `System.gc()`, but the results were the same.

The internals of RxJava are still a bit over my head, but looking at the following path from a heap dump, it could have something to do with the arbiter keeping a reference to the producer. Note that this dump is from the real app I'm building, not the reduced test case.

<img width="749" alt="screen shot 2016-03-31 at 11 28 02" src="https://cloud.githubusercontent.com/assets/134170/14171666/676209ce-f734-11e5-9a13-877343793fa7.png">

**Comment by Thomvis** [comment]
I've some more evidence which indicates that the operator is not properly releasing a reference to an old observable. The following screenshots were taken while stepping through the test. Please note the following:

- The field of interest `currentProducer` is highlighted
- `currentProducer` is `null` until `just` is _fed_ to the operator, after that it contains an `IterableProducer` with id `@1058`
- The value of `currentProducer` does not change, even if new observables are fed to the operator. Until giving it an observable with two values, the producer remains `@1058`. I would expect the producer to change to the producer of the subsequent observables.
- Feeding the two-element observable finally results in a new producer (`@1108`)

![1](https://cloud.githubusercontent.com/assets/134170/14174063/5588e7fa-f742-11e5-8efd-26875ac83b06.png)
![2](https://cloud.githubusercontent.com/assets/134170/14174064/55a78c0a-f742-11e5-8bad-dc9bfec1b833.png)
![3](https://cloud.githubusercontent.com/assets/134170/14174067/55ac98f8-f742-11e5-9740-e69eb187f94c.png)
![4](https://cloud.githubusercontent.com/assets/134170/14174066/55a9a058-f742-11e5-8f3b-ea8654746bf5.png)
![5](https://cloud.githubusercontent.com/assets/134170/14174065/55a8f6ee-f742-11e5-8740-0140615d258e.png)

**Comment by akarnokd** [comment]
I guess we could flush the arbiter in case the next source doesn't do backpressure and thus never calls `setProducer()`. However, `just()` does support backpressure since 1.1.1. Are you testing the latest RxJava?

**Comment by akarnokd** [comment]
Fix in #3814.

**Comment by Thomvis** [comment]
Thanks so much, this is great. Hope to see the fix in a release soon. 

I was testing with 1.1.0, for no good reason other than that we've not upgraded yet. In the real app, the observable that was not getting released was followed by an Observable.empty(), not sure if that one has back pressure so that it would've made a difference.

Thanks again!

**Comment by HotIceCream** [comment]
I had similar problem. I wrote test: https://gist.github.com/HotIceCream/8010c296d6f1ad9fc6882e2dcf2d13d3 with some reflection hack.

I build library from 3814 pull request but test still not passed. Is it different bug? Or it isn't it correct test?

**Comment by akarnokd** [comment]
@HotIceCream your sources never complete and keep the subscriber active.

**Comment by akarnokd** [comment]
@HotIceCream your sources never complete and keep the subscriber active.

**Comment by HotIceCream** [comment]
@akarnokd, yes. But when i use subjects it is correct behavior. I waiting new elements from subject until switchMap called. And when switch map called, from previous observable should producer removed.

**Comment by akarnokd** [comment]
You are calling cache on the same source you are testing; the switchMap just keeps resubscribing to `o` and thus you always have 1 subscriber to it.

**Comment by HotIceCream** [comment]
@akarnokd, yes. It is what i want. But inside CachedObservable after each resubscribing in array of producers adding new ReplayProduecer. And it isn't removed until `o` called onComplete (i.e. if using subjects - never). Test create 100 ReplayProduecers.
May be it is separate bug?

**Comment by akarnokd** [comment]
No, its the misunderstanding of the lifecycle of `cache()`. If you do this without the `switchMap`, you'll get 100 subscribers in the subject as well:

```java
PublishSubject<Object> ps = PublishSubject.create();

for (int i = 0; i < 100; i++) {
    ps.cache().subscribe().unsubscribe();
}
```

Once started, `cache()` can't be stopped. This was a decided tradeoff.

**Comment by akarnokd** [comment]
Closing via #3836.
