### ISSUE TITLE
Concurrency against ArrayDeque?

### ISSUE THREAD

**Issue by cy6erGn0m** [ReactiveX/RxJava#3838]
See

rx.internal.operators.OperatorTakeLast
rx.internal.operators.TakeLastQueueProducer

What if there is `OperatorTakeLast.onCompleted` has already started emit loop and there is `TakeLastQueueProducer.request(n)` trying to run this loop as well. Shouldn't it cause concurrent access to `ArrayDeque.poll/clear`?

**Comment by akarnokd** [comment]
That producer looks shady and unconventional to my eyes. If the source completes the same time there is a request that transitions from 0 to n, both would end up in the emit() method. Let me write a test that breaks it...

**Comment by akarnokd** [comment]
Yes, it has concurrency issues + late delivery of onCompleted. Will open a PR to fix it.

**Comment by akarnokd** [comment]
Fix posted: #3839.

**Comment by akarnokd** [comment]
Closing via #3839. Thanks for reporting!

**Comment by hzsweers** [comment]
@akarnokd I think you forgot to hit close ;)
