### ISSUE TITLE
Completable.subscribe(onError, onComplete) design issue

### ISSUE THREAD

**Issue by artem-zinnatullin** [ReactiveX/RxJava#3851]
This [particular overload](https://github.com/ReactiveX/RxJava/blob/3c5efaa9442ee24227b63ad039eb965b59aad774/src/main/java/rx/Completable.java#L1916) of `Completable.subscribe()` looks out of design in compare to other RxJava classes like `Observable` and `Single`.

Spent ~5 minutes trying to understand why such code didn't compile:

```java
Completable
  .fromAction(() -> doSomething())
  .subscribe(
    () -> ui.success(), 
    error -> ui.error(error)
  );
```

And the reason is because this overload accepts `error` handler **first** and `complete` handler second.

I do understand that it comes from `Observable.subscribe(onNext, onError, onComplete)`. 

But in compare to many other overloads like:

* `Observable.subscribe(onNext, onError)`
* `Single.subscribe(onSuccess, onError)` // this one has very similar semantic to target overload.
* `Observable.subscribe(onNext)`
* `Single.subscribe(onSuccess)`

Error handler is **never first** parameter in `Observable.subscribe()` and `Single.subscribe()`.

Another point is that compiler error displayed in IDE makes it even worse:
<img width="303" alt="screen shot 2016-04-12 at 00 35 50" src="https://cloud.githubusercontent.com/assets/967132/14443236/f19ec000-004e-11e6-95bb-178466587d52.png">

-------

`Completable` is still in `@Experimental`, so, we can change this signature as we want. We can `@Deprecate` this overload and add "better" alternative and then delete deprecated overload after one-two releases.

**Comment by akarnokd** [comment]
The design pattern was:

```java
subscribe(Action0 onComplete)
subscribe(Action0 onComplete, Action1<Throwable> onError)
```

**Comment by artem-zinnatullin** [comment]
@akarnokd what do you mean by

>was

?

**Comment by akarnokd** [comment]
I mean that is your suggestion but the current is swapped for case 2 because it is in the same order as the 3 arg `Observable.subscribe` minus `onNext`. Not sure which order feels more consistent with the other classes.

**Comment by artem-zinnatullin** [comment]
Right, I pointed that in the issue description, but we do have `Single.subscribe(onSuccess, onError)` even though it's also `Observable.subscribe(onNext, onError, onComplete)` minus `onNext`.

As said before: no other overloads of `subscribe()` in any classes accept `onError` first -> makes `Completable` inconsistent.

**Comment by akarnokd** [comment]
Okay. Since Completable is experimental, lets swap the arguments as you suggested.

**Comment by artem-zinnatullin** [comment]
Oh great, will do PR soon!
