### ISSUE TITLE
About Schedulers.computation()

### ISSUE THREAD

**Issue by lolobug** [ReactiveX/RxJava#3858]
"meant for computational work such as event-loops and callback processing; do not use this scheduler for I/O (use Schedulers.io( ) instead); the number of threads, by default, is equal to the number of processors"

I wonders why.
What's the advantage of running in  a  thread picked from a fixed number thread pool when  doing computational work.

**Comment by davidmoten** [comment]
This may assist a bit:

http://stackoverflow.com/questions/31276164/rxjava-schedulers-use-cases

**Comment by lolobug** [comment]
Thanks a lot.
