### ISSUE TITLE
How to pass a (Test)Scheduler into a nested Observable?

### ISSUE THREAD

**Issue by Konrad-Morawski** [ReactiveX/RxJava#3859]
In my code I'm using a `switchMap` to switch from an external datasource (progress updates) into a timer - `Observable.interval` - so that consuming code keeps on receiving updates periodically even if the observed operation froze.

I am unit-testing the solution with a `TestScheduler` to make use of time virtualization (`advanceTimeBy`).

The problem I'm facing is that while `subscribeOn(testScheduler)` gets the main Observable to run on test scheduler, the nested `Observable.interval` still runs on its default scheduler (computation, I believe).

Code excerpt:

    // source of progress updates 
    .switchMap(
            new Func1<String, Observable<String>>() {
                @Override
                public Observable<String> call(String s) {
                    return Observable

                            // to preserve the last update we have seen...
                            .just(s)
                            .concatWith(
                                    Observable

                                            // switching to timer if there's no new data
                                            // and here I have to pass TestScheduler in manually;
                                            // the same I use in subscribeOn in consuming code.

                                            .interval(1, 1, TimeUnit.SECONDS, scheduler)
                                            .map(new Func1<Long, String>() {
                                                @Override
                                                public String call(Long tick) {
                                                    return "tick " + tick;
                                                }
                                            }));
                }
            })
    .doOnNext(
    // snip

It feels clunky, as if I'm breaking the abstraction apart. Is there any workaround for that? Is my approach wrong?

For a full story, and compilable code - I had some more issues with getting it to work - you can take a peek at http://stackoverflow.com/questions/36626268/how-to-alternate-between-calling-code-input-and-timer-based-input-and-unit-test/

I'd be really grateful if someone could point me in the right direction.

**Comment by Konrad-Morawski** [comment]
I would label it as a Question, but if I'm not mistaken I'm not authorized to do that

**Comment by akarnokd** [comment]
This appears to be answered on SO. Basically, you have to inject the required schedulers all the way, even if it means across more inner classes.

If you have further input on the issue, don't hesitate to reopen this issue or post a new one.
