### ISSUE TITLE
Completable swallows OnErrorNotImplementedException

### ISSUE THREAD

**Issue by kotucz** [ReactiveX/RxJava#3860]
In the following case, the `IllegalStateException` should cause `OnErrorNotImplementedException`, because `subscribe()` has no onError handler specified.

```java
        Completable.fromCallable(() -> {
            throw new IllegalStateException("FOO");
        })
            .toSingleDefault(1)
            .subscribe();
```

In the related issue #3726 and PR #3733, similar problem was solved, that the exception was propagated to the thread exception handler. For example it works correctly in the following snippet and the `OnErrorNotImplementedException` delivered.

```java
        Completable.fromCallable(() -> {
            throw new IllegalStateException("FOO");
        })
            .subscribe();
```

Maybe more of the usages of the `toNpe()` shall be replaced with `deliverUncaughtException()`?

**Comment by akarnokd** [comment]
Relying on `OnErrorNotImplementedException` being thrown is a fragile position but for consistency, PR welcome.

**Comment by kotucz** [comment]
Not relying on it. But it hides programming errors. The app then behaves incorrectly instead of crashing.
