### ISSUE TITLE
Exceptions thrown by Iterator.next() cannot be caught by the observer whe

### ISSUE THREAD

**Issue by Hezj** [ReactiveX/RxJava#3863]
When trying to pass an Iterable to Observable.from() and it's Iterator.next() throws an exception, the observer subscribed or doOnError() method can't catch the exception

**Comment by Hezj** [comment]
When trying to pass an Iterable to Observable.from() and it's Iterator.next() throws an exception, the observer subscribed por doOnError() method can't catch the exception.

**Comment by tilal6991** [comment]
Pretty sure this is what https://github.com/ReactiveX/RxJava/pull/3862 is addressing.

**Comment by Hezj** [comment]
my fault.will close.
