### ISSUE TITLE
initial value factory overload for scan?

### ISSUE THREAD

**Issue by davidmoten** [ReactiveX/RxJava#3873]
I was just using `Observable.scan()` and it has a method with an initial value but no method with an intial value factory like:

```java
public final <R> Observable<R> scan(Func0<R> initialValue, Func2<R, ? super T, R> accumulator); 
```

I can work around this with `defer` but are people happy if I submit a PR with a factory parameter (and perhaps for the `reduce` method as well)?

**Comment by zsxwing** [comment]
See #3667

**Comment by akarnokd** [comment]
Closing as duplicate to #3667.
