### ISSUE TITLE
How can i do this?

### ISSUE THREAD

**Issue by zlm54585652** [ReactiveX/RxJava#3875]
[Uploading Help.txt…]()

import java.util.List;

public class aaa {
    List<Data> list;

    private int getCount(){
        //for
		
    //how can i do this whith Rxjava.....thanks
        int size=list.size();
        int count=0;
        for(int i=0;i<size;i++){

            count=count+list.get(i).count;

        }

      return count;
    }

    class Data{

        String name="";
        int count;

    }

}

I have a List<Data> and Data have an int count,i want use `Rxjava` to get All count of this List ,how can i do it?

**Comment by akarnokd** [comment]
First, how would you do it with plain Java?

**Comment by akarnokd** [comment]
```java
Observable.from(list)            // <-- loop over each item
.map(item -> item.count)         // <-- extract count from each item
.reduce(0, (a, b) -> a + b);     // <-- sum up the counts
.subscribe(System.out::println); // <-- get the final sum
```
