### ISSUE TITLE
doOnUnsubscribe behaviour does not align with documentation

### ISSUE THREAD

**Issue by rossdanderson** [ReactiveX/RxJava#3877]
Hi,

According to the documentation [here](http://reactivex.io/RxJava/javadoc/rx/Observable.html#doOnUnsubscribe(rx.functions.Action0)), when my source observable is reference counted I should only be notified of the final subscriber's unsubscription, however, unless I am misunderstanding the term _source_ - or misusing it, it appears to be called on every subscriber's unsubscription.

Below is a simple test which demonstrates what I mean - `onUnsubscribeAfterRefCount` will fail, while `onUnsubscribeBeforeRefCount` will pass

```
package streams;

import org.junit.Test;
import rx.Observable;
import rx.Subscription;
import rx.observers.TestSubscriber;
import rx.subjects.PublishSubject;

import java.util.concurrent.atomic.AtomicInteger;

import static org.junit.Assert.assertEquals;

public class UnsubscribeTest {

    @Test
    public void onUnsubscribeAfterRefCount() {
        AtomicInteger count = new AtomicInteger();

        Observable<String> publishSubject = PublishSubject.<String>create().publish().refCount().doOnUnsubscribe(count::getAndIncrement);

        TestSubscriber<String> testSubscriber1 = TestSubscriber.create();
        Subscription subscription1 = publishSubject.subscribe(testSubscriber1);

        TestSubscriber<String> testSubscriber2 = TestSubscriber.create();
        Subscription subscription2 = publishSubject.subscribe(testSubscriber2);

        subscription1.unsubscribe();
        subscription2.unsubscribe();

        assertEquals(1, count.get());
    }

    @Test
    public void onUnsubscribeBeforeRefCount() {
        AtomicInteger count = new AtomicInteger();

        Observable<String> publishSubject = PublishSubject.<String>create().doOnUnsubscribe(count::getAndIncrement).publish().refCount();

        TestSubscriber<String> testSubscriber1 = TestSubscriber.create();
        Subscription subscription1 = publishSubject.subscribe(testSubscriber1);

        TestSubscriber<String> testSubscriber2 = TestSubscriber.create();
        Subscription subscription2 = publishSubject.subscribe(testSubscriber2);

        subscription1.unsubscribe();
        subscription2.unsubscribe();

        assertEquals(1, count.get());
    }
}
```

**Comment by akarnokd** [comment]
You get two calls because the two subscribers create two separate chains up until the `publish()` stage and two `unsubscribe` calls are issued. In the second (synchronous) case, `publish().refCount()` makes sure the unsubscription happens only once and the preceding `doOnUnsubscribe` only gets called once.

**Comment by rossdanderson** [comment]
Yes I follow what is happening but this does not seem to align with the documentation where it says the source observable is modified to call doOnUnsubscribe, and that if the source observable is ref counted then it should only happen once.
The source observable is the one on the left I presume? In which case is this an invalid statement?

**Comment by akarnokd** [comment]
Ah, yes, that statement is invalid. Would you like to submit a PR and fix that?

**Comment by rossdanderson** [comment]
Certainly, is the intention to fix the documentation to match the actual behavour?
Cheers

**Comment by akarnokd** [comment]
Fix the documentation.

**Comment by akarnokd** [comment]
See my proposed updates to the javadoc in #3907

**Comment by akarnokd** [comment]
Closing via #3907.
