### ISSUE TITLE
onCompleted swallows all exceptions

### ISSUE THREAD

**Issue by dlew** [ReactiveX/RxJava#3885]
I was fairly surprised by the behavior of this stream:

```java
Observable.empty()
    .subscribe(
        System.out::println, 
        System.err::println,
        () -> { throw new RuntimeException(); }
    );
```

What I expected to see was the thread crashing due to the exception; instead absolutely nothing happens because `onCompleted` swallows the exception entirely.

**Comment by akarnokd** [comment]
`SafeSubscriber.OnCompleted` rethrows it as `OnCompletedFailedException` which then bounced back to `onError` because `throwIfFatal` doesn't recognize it (only `OnErrorNotImplementedException` and `OnErrorFailedException` are rethrown from this class of failures).

**Comment by dlew** [comment]
Would a reasonable solution be to add `OnCompletedFailedException` to `throwIfFatal`, then? I could work on that PR if that's all it takes.

**Comment by akarnokd** [comment]
Yes, go ahead.
