### ISSUE TITLE
Nit suggestion: Set repo settings to squash and merge PRs rather than always asking contributors to.

### ISSUE THREAD

**Issue by hzsweers** [ReactiveX/RxJava#3916]
This also has added benefit in that commits remain intact in the PR, which helps if you want to glance at the PR later and read through the review. 

Someone from Netflix would have to do this I think (@stevegury).

https://github.com/blog/2141-squash-your-commits

**Comment by JakeWharton** [comment]
There is no setting. It's per-merge.

**Comment by hzsweers** [comment]
If you only allow squash commits per the admin settings, that forces all of them to the same behavior though no? Or at least that was my interpretation of their description at the bottom:

> Only allow squash commits

> This is a new option which lets you force commit squashing on all pull requests merged via the merge button.

**Comment by JakeWharton** [comment]
Yes, but that's different than what your original intent was: not having to
wait. You already don't have to wait by selecting squash when you perform
the merge.

**Comment by hzsweers** [comment]
Fair enough, I guess it's just a suggestion then. Mostly just been @akarnokd that's asked me or others to squash first before merging. I'll change the title/post to rephrase it as a suggestion, though curious to know if reviewers intentionally ask contributors to do it first.

**Comment by akarnokd** [comment]
I stopped asking for squashing once the feature came out and I've been using squash-and-merge by default.

**Comment by hzsweers** [comment]
Ah, neeeeevermind :)
