### ISSUE TITLE
a Subscriber object  only has effect when be subscribed first time by Observable.just(...).subscribe()

### ISSUE THREAD

**Issue by gaobq** [ReactiveX/RxJava#3920]
I just test Observable.just(...) by click a button;
` private void rxUseJustCreateObserable(){
        Log.d(TAG,"rxUseJustCreateObserable");
        Observable<String> observable = Observable.just("just 1","just 2");
       ...}`

**1.**if I use `observable.subscribe(mSubscriber);`  only the first time when I click button it has effect;

**2.**if I use `observable.subscribe(new Subscriber<String>(){...});` every time I click  button, it's has effect;

what the different between **1** and**2** ?
could anyone give me an answer?

**Comment by akarnokd** [comment]
`Subscriber` instances are not reusable, you may want to use `Observer` instead.

**Comment by gaobq** [comment]
@akarnokd  ,thanks

**Comment by artem-zinnatullin** [comment]
Looks like it can be closed.
