### ISSUE TITLE
When performing a shallow clone, build fails

### ISSUE THREAD

**Issue by kageiit** [ReactiveX/RxJava#3926]
When cloned with --depth 1, `./gradlew tasks` fails with

```
* What went wrong:
A problem occurred evaluating root project 'rxjava'.
> Failed to apply plugin [class 'nebula.plugin.bintray.NebulaBintrayPublishingPlugin']
   > Walk failure.
```

**Comment by akarnokd** [comment]
Unfortunately, working from the github zip download doesn't work. Please do a full checkout.

If you have further input on the issue, don't hesitate to reopen this issue or post a new one.
