### ISSUE TITLE
.groupBy should not hold strong references to keys

### ISSUE THREAD

**Issue by gumanoid** [ReactiveX/RxJava#3929]
Actual result: .groupBy maintains internal map with strong references to keys. In case when key is large object, or references another large objects, this can lead to OOM eventually.

Expected result: groupBy keeps week references to keys, which does not prevent GC from collecting the keys.

**Comment by akarnokd** [comment]
GroupBy has to remember the whole key because values have to go to the associated `GroupedObservable`. A weak key would imply groups get recreated multiple times or worse, an old group's `getKey()` suddenly returning `null`.

You could try extracting only the necessary key material into a separate, independent data class and use that in the keyselector:

```java
source.groupBy(v -> new MyKey(v.name, v.age))...
```

**Comment by gumanoid** [comment]
Thanks for quick reply.
Lightweight key is the best solution of course, but I'm not sure it's always a possible one.
I guess you're right about weak refs also. I spent extra half an our in attempts to invent feasible solutions for various scenarios with weak refs and GC, and failed.
At least the key extractor can return weak refs, if this is the only way.
Can be closed.

**Comment by akarnokd** [comment]
Yes, if your key class depends on a `List<String>` with million items then it is hard to avoid the retention. A possible solution is perhaps to reduce that large data amount with a hash function (SHA256) which gives a manageable key size at the cost of a very low chance of key collision.

**Comment by abersnaze** [comment]
If you unsubscribe from the GroupedObservables it should remove the reference to the key so that it can be GC'd.  If a new value that maps to the old key shows up a new GroupedObservable is started up.

```
import java.util.concurrent.TimeUnit;
import rx.Observable;

public class Main {
    public static void main(String[] args) {
        Observable<Long> fast = Observable.interval(10, TimeUnit.MILLISECONDS).map(i -> i * 2).take(10);
        Observable<Long> slow = Observable.interval(20, TimeUnit.MILLISECONDS).map(i -> i * 2 + 1).take(10);

        fast.mergeWith(slow)//
                .groupBy(i -> i % 2)
                .flatMap(grp -> {
                    System.out.println("New group for key " + grp.getKey());
                    Observable<Long> timeLimitedGrp = grp.take(100, TimeUnit.MILLISECONDS).doOnUnsubscribe(() -> System.out.println("Unsub group for key " + grp.getKey()));
                    // do other stuff
                    return timeLimitedGrp;
                })
                .toBlocking()
                .forEach(System.out::println);
    }
}
```

produces the output

```
New group for key 0
0
2
New group for key 1
1
4
6
3
8
10
5
12
7
14
16
18
9
Unsub group for key 0
11
Unsub group for key 1
New group for key 1
13
15
17
19
Unsub group for key 1

```
