### ISSUE TITLE
BackPressure and nested flatMap

### ISSUE THREAD

**Issue by feneuilflo** [ReactiveX/RxJava#3933]
Hi, can someone explain why the following code (without nested flatmap)
<div class="highlight highlight-source-java"><pre>
Observable.from(new IterateOverFloat(1))) //
				.flatMap(__ -> Observable.create(new OnSubscribeFromIterable<>(new IterateOverFloat(10_000_000)))) //
				.flatMap(Observable::just) //
				.observeOn(Schedulers.computation()) //
				.subscribe();
</pre></div>
goes through method `slowPath(long)` of `OnSubscribeFromIterable.IterableProducer`,

while the following code (with nested flat map)
<div class="highlight highlight-source-java"><pre>
Observable.from(new IterateOverFloat(1)) //
				.flatMap(__ -> Observable.create(new OnSubscribeFromIterable<>(new IterateOverFloat(10_000_000))) //
						.flatMap(Observable::just)) //
				.observeOn(Schedulers.computation()) //
				.subscribe();
</pre></div>
goes through method `fastPath()` ?

`IterateOverFloat` is just a basic iterable that produces the asked number of floats.

I've tested with both RxJava-1.1.0 and 1.1.5 with the same results.

EDIT : ok, I have looked around a bit more, and here is what I have found.
I have created an Observable with backpressure support, which prints the first number of requested items:
<div class="highlight highlight-source-java"><pre>
Observable<Long> myObsWithBackPressureSupport = Observable.create(subs -> {
			subs.setProducer(new Producer() {

				AtomicBoolean bool = new AtomicBoolean(true);

				@Override
				public void request(long n) {
					if(bool.getAndSet(false)){
						System.out.println("request " + n);
					}
					
					LongStream.range(0, n).forEach(subs::onNext);
				}
				
			});
		});
</pre></div>

and I used it the following ways: 
<div class="highlight highlight-source-java"><pre>
// case 1
myObsWithBackPressureSupport //
		.observeOn(Schedulers.computation()) //
		.subscribe();

// case 2
myObsWithBackPressureSupport //
		.flatMap(l -> Observable.just(l)) //
		.observeOn(Schedulers.computation()) //
		.subscribe();
</pre></div>

In case 1, first request of 128 items.
In case 2, first request of Long.MAX_VALUE items.

I have concluded that using `flatMap` disables the backpressure support. Can someone tell me if I am right and if it is an intended behavior ?

**Comment by akarnokd** [comment]
FlatMap has multiple entry points: one front and any number of inner sequences. 

By default, `flatMap` requests the `Long.MAX_VALUE` - which is called unbounded mode - from its main upstream, which may trigger the fast-paths in sources. 

The inner, mapped sequences, request a fixed amount - default 128 - and keeps requesting as those inner values get consumed and merged into the output sequence. This doesn't trigger the fast-paths in most inner sequences. 

You can restrict the outer unbounded mode by setting the `maxConcurrency` parameter but you can't unbound the inner sequences. 

If you are dealing with inner `Iterable`s, you can avoid the genreal overhead by using `flatMapIterable`.

**Comment by feneuilflo** [comment]
Thanks for this answer. Using the `maxConcurrency` parameter has solved my problem.
