### ISSUE TITLE
What's the best way to have a side effect of a different type

### ISSUE THREAD

**Issue by mhgrove** [ReactiveX/RxJava#3939]
I'd like to have an `Observable` that represents some long running action, such as `Observable<ProgressEvent>` where the event holds progress information for the task, such as a status message or percentage completed.

At the end of the task I'd like to return a value of a different type. A trivial example would be counting the number of mis spelled words in some text. The progress would be processing word X of Y, but the result might be the list of mis-spelled words.

The first thing I looked at was`Subject`, but that won't work since the thing is really an `Observable` of the events and an `Observable` of the result, rather than an `Observable` an an `Observer` like `Subject`. Then I thought maybe simply extending `Observable` would work; I'd add an extra method `Optional<Result> result()` which would return the result of the computation after `onComplete`. But you "lose" the type of the `Observable` if you call other methods on it like a map, then a filter. You can get around that obviously, either extending all of the methods on Observable to return the subtype, or saving the variable, then chaining method calls to it, then finally, getting the result.

I also considered adding the `result` method to the event interface such that the last call to `onNext` would have an event whose `Optional<Result>` is not empty. This seems pretty easy, but did not feel like the cleanest solution.

Wondering if there's a mechanism in the framework that I missed, or some best practice for this type of situation that I'm not aware of.

The reason I don't return an `Observable<Result>` in the first place is I wanted the caller to have the option of subscribing to the event stream to do something like show a progress monitor.

**Comment by davidmoten** [comment]
You could emit a custom object that has a ProgressEvent and List<String>
being the list of misspelled words so far and then:

```java
observable
    .doOnNext(x -> updateProgress(x.event))
    .last()
    .map(x -> x.list);
```

**Comment by davidmoten** [comment]
Trying again with formatting fixed.

You could emit a custom object that has a `ProgressEvent` and `List<String>`
being the list of misspelled words so far (only needs to be present on the last emission though) and then:

```java
observable
    .doOnNext(x -> updateProgress(x.event))
    .last()
    .map(x -> x.list);
```

**Comment by mhgrove** [comment]
Yeah, that's similar to what I had stubbed out:

```
	public interface ProgressEvent<T> {

		public long progress();
		public long maxProgress();

		public default Optional<T> result() {
			return Optional.empty();
		}
	}
```

That's the event that any `Observable` emitted that was a process that reported progress on the creation of a result.

It had not occurred to me `last().map(ProgressEvent::result).map(Optional::get)` could pretty cleanly get the result of the operation. I had been trying to use `compose`, `extend`, or `lift`, but those couldn't really be provided by the caller since the functions would need the state of the process being observed to potentially build the result. Extending `Observable` didn't feel clean, nor did hacking the builder creating the process to add observers to the resulting `Observable` or having it provide the function needed to get the final result.

`last`/`map` seems like it might be the best option.

**Comment by akarnokd** [comment]
Looks like the question has been answered. If you have further input on the issue, don't hesitate to reopen this issue or post a new one.
