### ISSUE TITLE
switchMap() link points to the flatMap() documentation

### ISSUE THREAD

**Issue by blacharnia** [ReactiveX/RxJava#3945]
here: https://github.com/ReactiveX/RxJava/wiki/Transforming-Observables

**Comment by DavidMGross** [comment]
This is not a bug, as the switchMap( ) operator is one of the variants of flatMap that are documented on that page.

**Comment by blacharnia** [comment]
Ok, get your point, just was a bit confusing to me, as this is a separate bullet point on the page.
Thanks for the prompt answer.

**Comment by DavidMGross** [comment]
The list of operators on the reactivex.io site is more complete and
up-to-date than the list on the RxJava wiki:

http://reactivex.io/documentation/operators.html

In general, you're better off going there to research operators.

On Mon, May 16, 2016 at 12:09 PM, Piotrowski <notifications@github.com>
wrote:

> Ok, get your point, just was a bit confusing to me, as this is a separate
> bullet point on the page.
> Thanks for the prompt answer.
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub
> <https://github.com/ReactiveX/RxJava/issues/3945#issuecomment-219517221>
>



-- 
David M. Gross
PLP Consulting
