### ISSUE TITLE
Remove master branch?

### ISSUE THREAD

**Issue by zsxwing** [ReactiveX/RxJava#3946]
Otherwise people may open a PR against a wrong branch, like #3944.

**Comment by artem-zinnatullin** [comment]
👍

**Comment by akarnokd** [comment]
I'm kind of afraid to do that...

**Comment by artem-zinnatullin** [comment]
If you don't mind I'd propose to switch to [Git FTFY model](https://artemzin.com/blog/git-ftfy-branching-model-continuation-of-git-flow-considered-harmful/) which includes removing master branch. It fits RxJava development process especially well in my opinion. (Works really well for app development.)

We can have multiple `dev/` branches like: `dev/1.1.7`, `dev/1.1.8`, `dev/2.0.0` and so on (pretty much how it works now). Moreover, we can add release candidates flow to the project and publish release candidates first to collect feedback from early adopters for few days and only then release final version.

**Comment by JakeWharton** [comment]
I don't see any benefits of that which are not already afforded with the current setup. It seems like just a bunch of extra bookkeeping for no benefit.

**Comment by JakeWharton** [comment]
Strongly in favor of removing `master`.

```
$ git push origin :master
```

**Comment by stevegury** [comment]
I agree, the `master` branch has been a source of confusion for new users, I vote for removing it.

**Comment by akarnokd** [comment]
:+1: Okay. I'll now attempt pressing the delete icon...

**Comment by akarnokd** [comment]
Done, there's a restore option for 30 days I believe.
