### ISSUE TITLE
Request: Completable.andThen(Completable)

### ISSUE THREAD

**Issue by vanniktech** [ReactiveX/RxJava#3947]
To match `Completable#andThen(Observable<T> next)` and `Completable#andThen(Single<T> next)` it would be nice if there were an operator like this:

`Completable#andThen(Completable next)`.

Unless there is some other way to achieve the same functionality right now.

**Comment by akarnokd** [comment]
There is the `endWith` operator for this purpose, but you can post a PR renaming it.

**Comment by vanniktech** [comment]
@akarnokd thanks for the quick reply. Posted a PR for that. Just a quick question what about `endWith(Observable<T> next)` should that stay or should there also be `andThen` used?

**Comment by akarnokd** [comment]
You can deprecate that as well.

**Comment by vanniktech** [comment]
Alright thanks. I updated the PR let me know whether I should squash commits and change commit message to match the new updated title or whether you'll use the GitHub squash and merge functionality.

**Comment by akarnokd** [comment]
No need for squashing on your end.

**Comment by zsxwing** [comment]
Closing via #3948
