### ISSUE TITLE
PublishSubject has 0 observers in some instances

### ISSUE THREAD

**Issue by lawloretienne** [ReactiveX/RxJava#3954]
So I am in `Activity A` then I launch `Activity B` (which has a custom `ImageView` with a `PublishSubject` with `setImage*` methods that call `publishSubject.onNext()` )

The first time launching `Activity B` it works fine, `onNext()` gets called and when I subscribe to the `PublishSubject`, the `Action1` `call()` method gets called .

However, subsequent times of launching `Activity B` , `onNext()` will get called but inside of that method it attempts to loop through `state.observers()` which at this point is 0.

Why is that?

**Comment by akarnokd** [comment]
Can you post a small example?

**Comment by lawloretienne** [comment]
Nevermind I figured it out.  I was doing a call to load an Image with Picasso before I set up the ImageView subscription.  I don't know why that didn't fail 100% of the time. Anyway, I changed the ordering around and all works fine now.
