### ISSUE TITLE
concatMap not working

### ISSUE THREAD

**Issue by personshelldon** [ReactiveX/RxJava#3955]
Hello! I'm using a RxJava to login to server. I need to create next logic of login:
**1. Get version of API from server and create (based on version) server urls
2. Get tokens from the first server url
3. If tokens received, I need to check if other servers (that I created in point 1) can be accessed by connecting to them**

I writed next logic: 

```
// getObservable() funcion;
retrun Observable.create(new Observable.OnSubscribe<Integer>() {
            @Override
            public void call(Subscriber<? super Integer> subscriber) {
                if (subscriber.isUnsubscribed()) return;
//get version from server
                int version = ServerAPI.getInstance(mContext).getVersion(User.this);
                if (version < 5) {
                    subscriber.onNext(AccountsAdapter.ERROR_OLD_API);
                    subscriber.onCompleted();                 
                    return;
                }
//get tokens
                Pair<Integer,Tokens> data = ServerAPI.getInstance(mContext).getTokens(User.this, ServerAPI.GRANT_TYPE_PASSWORD);
                if (data.first==ServerAPI.CODE_OK&&data.second.isValid()) {
                    setAccessToken(data.second.getAccessToken());
                    setRefreshToken(data.second.getRefreshToken());
                    setUserId(data.second.getUserID());
                    setApiVersion(data.second.getApiVersion());
                    setTypeToken(data.second.getTokenType());
                    setMacAlgorithm(data.second.getMacAlgorithm());
                    setMacKey(data.second.getMacKey());
                    setApiServer(createApiLink(version));
                    setImagesServer(createImagesLink());
 //at this point result retuns to subscriber
                    subscriber.onNext(data.first);
                } else if (data.first==ServerAPI.CODE_OK
                        ||data.first==ServerAPI.CODE_INVALID_RESPONSE_DATA) {
                    subscriber.onNext(AccountsAdapter.ERROR_LOGIN_OR_PASS_INVALID);
                } else {
                    subscriber.onNext(data.first);
                }
                subscriber.onCompleted();
            }
        })
               .concatMap(integer -> {
// this code never called
                if (integer==ServerAPI.CODE_OK) {
// checking access to the servers
                    return Observable.zip(getUserModules(), Observable.just(ServerAPI.getInstance(mContext).checkAccessToImagesServer(User.this)), (strings, aBoolean) -> {
                        if (SystemUtils.isEmpty(strings)) {
                            logOut();
                            return AccountsAdapter.ERROR_INVALID_API_SERVER;
                        } else if (aBoolean) {
                            Users.getInstance(mContext).setCurrentUser(User.this);
                            NotificationsManager.enableAllNotifications(mContext, getUserId());
                            return ServerAPI.CODE_OK;
                        } else {
                            logOut();
                            return AccountsAdapter.ERROR_INVALID_IMAGES_SERVER;
                        }
                    });
                } else {
                    return Observable.just(integer);
                }
            })
         .subscribeOn(scheduler);
```

But this Observable ignores concatMap and returns result from commented string. How to fix this?

Subscriber is called by `getObservable().observeOn(AndroidSchedulers.mainThread()).subscribe();`

**Comment by akarnokd** [comment]
RxJava is not using the builder pattern; each operator returns a new `Observable`. In your example, result won't change by calling `concatMap` on it. You should chain the `subscribeOn` after the application of `concatMap` return the resulting `Observable`.

**Comment by personshelldon** [comment]
I don't understand what You say: I'm returning Observable with already concatMap implemented (I corrected code), but it does not work. Please, explain what I need to do in detailes to get this scheme to work? 
Documentation says that concatMap will convert emitted items to another Observable, but concatMap ignores that items.
Sorry for my English.

**Comment by akarnokd** [comment]
What do you get as `integer` in the `concatMap`? Did you debug your `OnSubscribe` implementation to see what it does and what it gets from the API calls?

**Comment by personshelldon** [comment]
Ah, sorry, I understood Your words about the "not builder pattern" I need to write`result = result.concatmap()` instead of `result.concatMap()`. Thank You a lot. Now it is working fine.

One more question: there are many articles that that say `Observable.create()`causes memory leaks if do not call `subscriber.unsubscribe()` in `OnSubscribe()` implementation. Is that true? Or `subscriber.onComplete()` is enough?

**Comment by akarnokd** [comment]
Sorry for the late response. If an `Observable` is run to completion, resources are released. Otherwise, if your activity is destroyed before that, you have to call `unsubscribe` manually. The problem with `create` is that people tend to implement it poorly, ignoring backpressure and most importantly, resource management.

If you have further input on the issue, don't hesitate to reopen this issue or post a new one.
