### ISSUE TITLE
takeLast method does not act as the marble diagram in JavaDoc described 

### ISSUE THREAD

**Issue by otal1105** [ReactiveX/RxJava#3957]
rx.Observable.takeLast(int, long, TimeUnit) does not act as the marble diagram in JavaDoc described.

[takeLast](file:///C:/lib-java/rxjava/rxjava-1.1.3-javadoc/rx/Observable.html#takeLast%28int,%20long,%20java.util.concurrent.TimeUnit,%20rx.Scheduler%29)'s marble diagram shows that `takeLast(1, 2100L, TimeUnit.MILLISECONDS)` is the same as `takeLast(2100L, TimeUnit.MILLISECONDS).take(1)`.
In the diagram, the observable emit the blue item.

But, actually, takeLast method emit the last item like `takeLast(2100L, TimeUnit.MILLISECONDS).takeLast(1)`.
The observable emit the purple item instead of blue one in the marble diagram.

I'm not sure whether the marble diagram would be wrong or the actual program would be wrong.

See [stackoverflow](http://stackoverflow.com/questions/37312624/rxjavas-takelast-method-does-not-act-as-javadoc-described)

**Comment by DavidMGross** [comment]
Diagram fixed.
