### ISSUE TITLE
concatMap and Subject weirdness

### ISSUE THREAD

**Issue by mateherber** [ReactiveX/RxJava#3962]
Hi,

Maybe I just interpret it wrong but I found some unexpected behaviour.

``` java
Observable.just(1,2,3).concatMap(new Func1<Integer, Observable<String>>() { //flatmap <-- gets called 3 times
    @Override
    public Observable<String> call(Integer integer) {
        return BehaviorSubject.create("one"); //Observable.just("one"); <-- This gets called 3 times
    }
}).subscribe(new Action1<String>() {
    @Override
    public void call(String s) {
        //This gets called once... :(
    }
});
```

The interesting thing is that if I use flatMap instead of concatMap the callback gets called 3 times. also if I don't use the subject but the Observable.just() it also gets called 3 times what I expect. Can someone describe me this outcome?

**Comment by akarnokd** [comment]
You need a source to complete with `concatMap` before it can move to the next. `BehaviorSubject` emits its initial value and just waits there, never completing.

**Comment by mateherber** [comment]
Thanks @akarnokd! That makes sense, should have figured it out myself
