### ISSUE TITLE
Overloaded method for Observable.subscribe(Action1<Throwable>)

### ISSUE THREAD

**Issue by VictorAlbertos** [ReactiveX/RxJava#3968]
Hi :)

I've been seeking for an overloaded method on `Observable` class with this signature:

`Observable.subscribe(Action1<Throwable>)`

That way I could focus on the error, ignoring the successful item emitted:

``` java
observable.subscribe(new Action1<Throwable>() {
    @Override public void call(Throwable throwable) {

    }
});
```

But it seems that there isn't any overloaded method with this signature.

Is there an alternative which I'm missing it? If not, would be accepted a PR to add this signature method?

Thanks!

**Comment by vanniktech** [comment]
Also `Completable.subscribe(Action1<Throwable>)` is missing.

**Comment by gkhom** [comment]
You could use the `doOnError` operator:

``` Java
observable.doOnError(new Action1<Throwable>() {
    @Override
    public void call(Throwable throwable) {

    }
}).subscribe();
```

Or if you have access to lambda syntax:

``` Java
observable.doOnError(throwable -> {

}).subscribe();
```

I think that due to type erasure in Java it's not possible to add the overload that you describe.

`Subscription subscribe(Action1<? super T> onNext)` and `Subscription subscribe(Action1<Throwable> onError)` would be ambiguous.

**Comment by artem-zinnatullin** [comment]
This is not possible because of type erasure, it'll have same signature as
subscribe(Action1<T>) that handles result.

**Comment by VictorAlbertos** [comment]
@GeorgiKhomeriki I think if I use `doOnError` operator it won't prevent of throwing the exception outside of the observable pipeline. So, the program will crash. Because I need to catch the exception, I think I will use `onErrorResumeNext( )` operator.

But, still, is not the same that handling from `Observable.subscribe`

But you both are right, I missed the type erasure problem. 

Thanks!

**Comment by JakeWharton** [comment]
Use the two action overload with Actions.empty() as the first argument.

**Comment by VictorAlbertos** [comment]
That's better. Thanks @JakeWharton
