### ISSUE TITLE
Custom Terminal Operators

### ISSUE THREAD

**Issue by HaloFour** [ReactiveX/RxJava#3973]
I'd like to propose the addition of a generic terminal operation method on `rx.Observable` that would accept an implementation of a terminal operator interface and returns any generic type:

``` java
CompletionStage<Integer> stage = rx.Observable.just(1, 2, 3)
    .map(value -> value * 2)
    .max()
    .terminate(TerminalOperators.toCompletionStage());
```

The existing aggregate and collection operators are great, but they all currently produce `rx.Observable`.  In our project we mostly make use of Java 8 `CompletionStage<T>` as well as some assorted `Future<T>` implementations from other libraries.  We have static helper methods to convert from `rx.Observable` to `CompletionStage<T>` already, but it breaks the fluent API.

**Comment by HaloFour** [comment]
Actually, it looks like the experimental method `rx.Observable#extend` will meet my needs.  I'll take a look at it and if it does I will close this issue.

**Comment by akarnokd** [comment]
Yes, we have the `extend` operator (experimental) where you get an `OnSubscribe` value and can return whatever you want:

`public <R> R extend(Func1<? super OnSubscribe<T>, ? extends R> conversion)`

Its downside is that you get only an `OnSubscribe` on which you have to call `call(Subscriber<? super T>)` to get things running.

**Comment by HaloFour** [comment]
@akarnokd

Yes, that does seem like a bit of a limitation.  In my case since I'm transforming the observable into a future-like I want to ensure that the observable emits exactly one result.  In my static helper method I use the `single()` function to ensure this.  It seems that with `extend` I'd be required to effectively reimplement the subscriber from `OperatorSingle`.  It might be nice to have an overload of `extend` that can accept a different interface capable of transforming the sequence before subscribing.

**Comment by akarnokd** [comment]
@HaloFour. When the `extend` operator was introduced, I argued for using `Observable` but I was unable to convince the author. You don't need to reimplement all but use `Observable.create` to re-wrap the source:

``` java
Observable.just(1).extend(os -> Observable.create(os).toBlocking().first());
```

**Comment by HaloFour** [comment]
@akarnokd Ah, not too bad then:

``` java
public static <T> Func1<? super Observable.OnSubscribe<T>, ? extends CompletionStage<T>> toCompletionStage() {
    return onSubscribe -> {
        CompletableFuture<T> future = new CompletableFuture<>();
        Observable.create(onSubscribe)
                .single()
                .subscribe(future::complete, future::completeExceptionally);
        return future;
    };
}

// later

Observable<Foo> observable = observeFoo();
CompletionStage<Foo> stage = observable.extend(toCompletionStage());
```
