### ISSUE TITLE
Only part of chain executed after exception

### ISSUE THREAD

**Issue by slawomir-b** [ReactiveX/RxJava#3976]
Hi. Rx java is pretty new to me and I have one problem that I can't understand. After exception only part of my operator chain is executed for next objects and I don't know why. 
I have kafka consumer that polls server for messages and then turns them in infinitie observable:

```
public Observable<Event> consume() {
    return Observable.create(subscriber -> {
        try {
            consumer.subscribe(Arrays.asList(topic));

            while (running) {
                ConsumerRecords<String, Event> records = consumer.poll(pollTimeout);
                for (TopicPartition partition : records.partitions()) {
                    for (ConsumerRecord<String, Event> record : records.records(partition)) {
                        Event event= record.value();
                        subscriber.onNext(event);

                        long offfset = record.offset() + 1;
                        consumer.commitSync(Collections.singletonMap(partition, new OffsetAndMetadata(offfset)));
                        LOGGER.info("Comitted offset "+offfset);
                    }
                }
            }
            subscriber.onCompleted();
        } catch (Exception ex) {
            LOGGER.error("Exception thrown during events consuming", ex);
            subscriber.onError(ex);
        }
    });
}
```

And here is my problem:

```
    public Observable<ProcessDoneEvent> doSth(Event event) {
    String vin = event.getVin();
    return vehicleStateRepository.getState(vin)
            .filter(state -> shouldProcess(state, event))
            .flatMap((State state) -> {
                return backendService.getVehicle(vin)
                        .map(this::getCarLicense)
                        .flatMap((CarLicense carLicense) -> api.apiAction(carLicense)
                                .map((ActionConfirmation confirmation) -> {
                                    log(carLicense, confirmation, event);
                                    return confirmation;
                                })
                                .flatMap((ActionConfirmation t) -> {
                                    return vehicleStateRepository.saveState(vin, State.IDLE)
                                            .map((String sth) -> createProcessDoneEvent(vin));
                                }));
            });
}
```

In normal situation all operators are executed, state is fetched from db, api is called and finally vehicle state is saved in db. And this is working fine for any amount of events.

Now lets consider situation that timeout occurred in backendService.getVehicle(vin). Exception is handled in retry operator and we are ready for next events. And now what happens - for next events, only lines above api.apiAction(carLicense)(including) are executed and lines below are skipped. So result is that: vehicle state is fetched, api is called and then control returns to loop in message consumer so it's committing new offset without saving vehicle state to db and logging it. 

Why is this happening? :(

Also here is code with subscription:

```
    public void startConsuming() {

    consumer.consume() <- code in first posted snipplet
            .flatMap(this::doAction)
            .retry((count, e) -> {
                LOGGER.error("aaaaaaaa", e);
                return true;
            }).subscribe(subscriber);
}

private Observable<ProcessDoneEvent> doAction(Event event) {
    if (Event.getEventType().equals(EventType.TYPE_ONE)) {
        return process.doSth(event); <- this is method posted above
    } else {
        return process.doSthOther(event);
    }
}
```

**Comment by akarnokd** [comment]
For one, you didn't implement unsubscription in your `create`d `Observable` properly. You should check `subscriber.isUnsubscribed()` and quit the method if `true`. Second, many operators have either variants or parameters that allow delaying errors to the end, they should allow you to finish up with good values before failing/retrying.

**Comment by slawomir-b** [comment]
I changed my consumer loop to exit when subscriber.isUnsubscribed() and it looks like it was it! I will make further tests, please don't close issue yet but thank you very very much for now.

**Comment by slawomir-b** [comment]
ok everything is ok now. Thank you one more time.
