### ISSUE TITLE
Cannot set property 'defaultVersionStrategy' on null object

### ISSUE THREAD

**Issue by mlick** [ReactiveX/RxJava#3978]
I hava the error,how to solved?
Error:(9, 1) A problem occurred evaluating root project 'rxjava'.

> Failed to apply plugin [class 'nebula.plugin.rxjavaproject.RxJavaReleasePlugin']
> Cannot set property 'defaultVersionStrategy' on null object

**Comment by akarnokd** [comment]
You have to check out the project with git or an IDE.

**Comment by mlick** [comment]
@akarnokd  Yes! I solved it! I direct fork and buid in my android studio. Thanks for your answer!

**Comment by akarnokd** [comment]
Great!
