### ISSUE TITLE
doOnSubscribe & doOnTerminate prevents invocation of producer function when using Observable.create

### ISSUE THREAD

**Issue by martyglaubitz** [ReactiveX/RxJava#3983]
I am making an api call reactive with wrapping an async operation into Observable.create to make the result consumable as subscription. Also i want to automatically show an Android progressDialog when an subscriber subscribes and the api call gets invoked and dismiss it again when the call terminates (whether with error or successful)

``` kotlin
val producer = object : Observable.OnSubscribe<Result> {
    var apiCancellation: ApiCancellation? = null

    var progressDialog: ProgressDialog? = null

    override fun call(t: Subscriber<in Result>) {
        apiCancellation = api.call(operation) { result ->
            if (result.isFailure) {
                 t.onError(result.failure.exception())
            }
            else {
                t.onNext(result.response)
                t.onCompleted()
            }
        }
    }
}

return Observable.create(producer)
    .doOnSubscribe { producer.progressDialog = ProgressDialog.show(context, null, context.getString(R.string.msg_sending_invitation), true, false) }
    .doOnTerminate { producer.progressDialog?.dismiss() }
```

however if i subscribe to returned observable the producer will never get invoked.
if i remove the _doOnSubscribe_ and _doOnTerminate_ callbacks it'll work fine

**Comment by akarnokd** [comment]
Maybe `doOnSubscribe` crashes if it is not invoked on the Android mainThread? Same for `doOnTerminate`?

**Comment by martyglaubitz** [comment]
Ok, turns out i used the wrong context to create the progressdialog in which case the call just silently dies
