### ISSUE TITLE
Proposal: Make Schedulers should be more friendly to tests

### ISSUE THREAD

**Issue by ZacSweers** [ReactiveX/RxJava#3985]
`RxJavaPlugins.reset()` was recently made public, but there was a common misconception that this would also reset schedulers. This isn't the case however since Schedulers permanently cache their resolved schedulers, so `RxJavaPlugins.reset()` actually doesn't help in this regard. 

I'd like to propose adding a `Schedulers.reset()` function as well. It comes with same caveats that `RxJavaPlugins.reset()` has in that it's dangerous to call in live code, but it would be enormously helpful in testing. This would simply null out the cached schedulers to force a re-check the next time they're used, and thus letting you change the scheduling hook and have the new one's output propagate. 

With JUnit, it could be nicely wrapped up in a rule that could be optionally dropped into test suites on the fly. Otherwise, schedulers must be set at the beginning of your whole test suite and delegate schedulers put in place that can be configured later.

If people would be open to this, I'd be happy to provide a PR. I looked for prior discussion around this but wasn't able to find any. If I missed them somewhere, please let me know.

**Comment by zsxwing** [comment]
👍 In the long term, I would like to see that `RxJavaPlugins.reset()` can reset static fields related to plugins.

**Comment by ZacSweers** [comment]
Actually it wouldn't just be nulling out those fields. It would have to replace the singleton `INSTANCE` of Schedulers to re-trigger its constructor and evaluation of those scheduler instances. For just tests though, I still think this is a reasonable tradeoff since it's opt-in and doesn't change existing behavior by default.

**Comment by zsxwing** [comment]
@hzsweers That's what I meant :)

**Comment by ZacSweers** [comment]
Opened a PR in #3986 for further review
