### ISSUE TITLE
Proposal: tests based on marble diagrams in ASCII forms

### ISSUE THREAD

**Issue by alexvictoor** [ReactiveX/RxJava#3988]
Hello all,
I really like what has been done in RxJS with [marble diagrams](https://github.com/ReactiveX/rxjs/blob/master/doc/writing-marble-tests.md).
I have already written a [C# port](https://github.com/alexvictoor/MarbleTest.Net) and I guess it will be even easier to write a Java one.
Would you be interested by a PR that would enhance the TestScheduler with 'marble features', just as it is done in RxJS?
Regards

**Comment by akarnokd** [comment]
I don't know. We have +2500 unit tests already. I could see the value when given a pattern, the test routine automatically tries some backpressure and cancellation patterns.

**Comment by alexvictoor** [comment]
I am not thinking converting the whole test codebase to ascii marble tests.
My idea is to provide to RxJava users new ways to write tests that will be more concise and readable.
Do you think these features should rather be implemented in a module outside RxJava?

**Comment by stealthcode** [comment]
I think it would make a good addition as an external library.

**Comment by alexvictoor** [comment]
Ok I'll do that
Thanks for your answers

**Comment by JakeWharton** [comment]
Please link it here when ready for people to look at it.

**Comment by mattbishop** [comment]
Yes this would be awesome!

**Comment by alexvictoor** [comment]
Here we go: https://github.com/alexvictoor/MarbleTest4J

**Comment by davidmoten** [comment]
That's cool, thanks!
