### ISSUE TITLE
Debounce timeout

### ISSUE THREAD

**Issue by lawloretienne** [ReactiveX/RxJava#3995]
When using the debounce() operator for form validation how long should the debounce timeout be?
I currently have mine set to 400 milliseconds but idk if that is too short.

**Comment by artem-zinnatullin** [comment]
It's a question for ux.stackexchange.com, if you'll ask it there please post link back here, I'm curious to read the answers!

**Comment by lawloretienne** [comment]
http://ux.stackexchange.com/questions/95336/debounce-timeout

**Comment by artem-zinnatullin** [comment]
Thanks! Can you please close the issue here?
