### ISSUE TITLE
RxJavaPlugins.getInstance()

### ISSUE THREAD

**Issue by pavlospt** [ReactiveX/RxJava#4003]
Hello, 

I am trying to create a custom ErrorHandler for RxJava and while trying to get the RxJavaPlugins instance to register the ErrorHandler, it does not seem to be giving me access to the `.getInstance()`
public static method.

I checked the RxJavaPlugins class and saw that `.getInstance()` is actually public. I can not understand though why I can not access it. 

I am using RxJava 1.1.5.

**Comment by akarnokd** [comment]
What IDE are you using? Is the JRE/JDK properly setup in your project? What is the actual error message when you write `RxJavaPlugins.getInstance()`?

**Comment by pavlospt** [comment]
I am using Android Studio. JRE and JDK are correctly setup for the project. There is no error message actually. It just does not seem to have an available method called .getInstance().

**Comment by egor-n** [comment]
Are you sure your import points to `rx.plugins.RxJavaPlugins`?

**Comment by pavlospt** [comment]
@egor-n Yes, that was my first check.

**Comment by pavlospt** [comment]
Actually it was an IDE problem. Could not pinpoint exactly what was causing it. I am closing the issue per se.
