### ISSUE TITLE
RxJavaPlugins.reset() does not reset Observable.hook

### ISSUE THREAD

**Issue by DariusL** [ReactiveX/RxJava#4006]
I tried using the RxJavaObservableExecutionHook and noticed that once used, it cannot be changed. It seems that `Observable` holds a static reference to this hook and uses whatever was set when the class was created. Calling `reset()` has no effect on `Observable`.

```
import org.junit.Test;

import rx.Observable;
import rx.plugins.RxJavaObservableExecutionHook;
import rx.plugins.RxJavaPlugins;

import static org.junit.Assert.assertTrue;

public class HookTest {

    @Test
    public void testChangeHooks() {
        Hook first = new Hook();
        RxJavaPlugins.getInstance().registerObservableExecutionHook(first);

        Observable.just(null).subscribe();

        assertTrue(first.invoked);

        RxJavaPlugins.getInstance().reset();
        Hook second = new Hook();
        RxJavaPlugins.getInstance().registerObservableExecutionHook(second);

        Observable.just(null).subscribe();

        assertTrue(second.invoked);
    }

    static class Hook extends RxJavaObservableExecutionHook {
        boolean invoked = false;

        @Override
        public <T> Observable.OnSubscribe<T> onSubscribeStart(Observable<? extends T> observableInstance, Observable.OnSubscribe<T> onSubscribe) {
            invoked = true;
            return super.onSubscribeStart(observableInstance, onSubscribe);
        }
    }
}
```

The second assert fails. I'm using 1.1.5.

**Comment by akarnokd** [comment]
Yes, you can't override that once the `Observable` class has been loaded. `Single` and `Completable` allow it to be replaced manually, but only from unit tests of the same package. The whole `RxJavaPlugins` has to be redesigned.

**Comment by artem-zinnatullin** [comment]
For now you can register kind of super execution hook and add/remove
listeners to it.

**Comment by DariusL** [comment]
Yeah, I figured I needed some sort of composite hook.

**Comment by DariusL** [comment]
An easy fix would be to remove the `hook` field from `Observable`. I assume it is there for performance.

**Comment by akarnokd** [comment]
I'm working on a PR to solve problems like this. Stay tuned.

**Comment by akarnokd** [comment]
Closing via #4007.
