### ISSUE TITLE
TestObserver is not thread-safe

### ISSUE THREAD

**Issue by Petikoch** [ReactiveX/RxJava#4010]
Hi there,

after a quick look into the TestObserver source code, I saw that is not thread-safe. 
I suggest to use e.g. CopyOnWriteArrayList instances internally instead of ArrayList instances.

Scenario:
I think it's ok in a unit test to create the TestObserver in one thread (e.g. main-Thread), then have some logic-under-test call it using e.g. an IO-Thread, and await the asynchronous incoming events in the main-thread again (using e.g. https://github.com/jayway/awaitility or Spock's polling conditions). 

What do you think?

Best regards,
Peti

**Comment by akarnokd** [comment]
The contract is that you have to drive an `Observer` sequentially, that is, calls to `onXXX` have to happen sequentially. Since `onNext` should not run concurrently, using an `ArrayList` is acceptable.

In other words, you can't reuse a TestObserver by subscribing it to multiple sources.

What is your concrete example?

**Comment by Petikoch** [comment]
Thanks @akarnokd for your reply.

Sure, the observer is called in sequence and usually by one and the same thread. 

But: You can create the TestObserver in one thread, pass it over to some logic which calls it then with a different thread. That's fine -> according the "happend-before rule" the second thread "sees" the list. But... when the second thread updates the internal ArrayList of the TestObserver, the original (first) thread doesn't necessarly see those changes, it _might_ still see the empty list from the creation, since there is no synchronisation between the two (syncronized etc) which would force the "publication of the changes across memory barriers".

I hope I made my thoughts more clear with this. 

What do you think?

Best regards,
Peti

**Comment by akarnokd** [comment]
> it might still see the empty list from the creation, since there is no synchronisation between the two (syncronized etc) which would force the "publication of the changes across memory barriers".

If you retain reference in the first thread, its your responsibility to make values visible across threads. The only support for this is `awaitTerminalEvent` that waits on a latch.

**Comment by Petikoch** [comment]
Ok, you can push that problem to the user. The solution for the user is not trivial. The user could e.g. wrap the Observer with a "proxy with a sync" or write a ThreadSafeTestObserver.

Or you could easily provide a solution in the TestObserver and solve this problem for the user.

I'd solve it. I'd use CopyOnWriteArrayList instances internally and would be happy that this scenario is also covered.

**Comment by akarnokd** [comment]
The whole cross-thread TestObserver use sounds odd to me; this is why I asked for a concrete example, the unit test that causes you problems.

**Comment by Petikoch** [comment]
Ok... here's an example using Groovy and https://github.com/spockframework/spock

```
import rx.Observable
import rx.observers.TestObserver
import spock.lang.Specification
import spock.util.concurrent.PollingConditions

import java.util.concurrent.TimeUnit

class MultiThreadedTestObserverExample extends Specification {

    def conditions = new PollingConditions(timeout: 2)

    def 'my funny testcase'(){
        given:
        def testObserver = new TestObserver()
        println "${Thread.currentThread().getName()} is working in given:"
        def codeUnderTest = new AsyncLogicDoingSomeMagic()

        when:
        codeUnderTest.doSomeMagic(testObserver)

        then:
        conditions.eventually {
            println "${Thread.currentThread().getName()} is working in then:"
            assert testObserver.onNextEvents == ['Maaagic!']
        }
    }


    private static class AsyncLogicDoingSomeMagic {

        void doSomeMagic(rx.Observer<String> observer) {
            Observable.timer(1, TimeUnit.SECONDS)
                    .map { 'Maaagic!' }
                    .doOnNext { println "${it} from ${Thread.currentThread().getName()}" }
                    .subscribe(observer)
        }

    }
}
```

Output: 

```
main is working in given:
main is working in then:
main is working in then:
main is working in then:
main is working in then:
main is working in then:
main is working in then:
main is working in then:
main is working in then:
main is working in then:
main is working in then:
Maaagic! from RxComputationScheduler-1
main is working in then:

Process finished with exit code 0
```

**Comment by akarnokd** [comment]
Use `TestSubscriber`:

``` java
TestSubscriber<String> ts = TestSubscriber.create();

Observable.timer(1, TimeUnit.SECONDS)
.map(v -> "Maaagic!")
.doOnNext(v -> System.out.println(v + " from " + Thread.currentThread().getName()))
.subscribe(ts);

ts.awaitTerminalEvent(5, TimeUnit.SECONDS);
ts.assertValue("Maaagic!");
ts.assertNoErrors();
ts.assertCompleted();
```

**Comment by Petikoch** [comment]
And here an example with Java 8 and JUnit 4:

```
import com.google.common.collect.Lists;
import com.jayway.awaitility.Awaitility;
import org.junit.Test;
import rx.Observable;
import rx.observers.TestObserver;

import java.util.concurrent.TimeUnit;

public class MultiThreadedTestObserverExample2 {

    @Test
    public void my_funny_testcase() {
        // arrange:
        TestObserver<String> testObserver = new TestObserver<>();
        System.out.println(Thread.currentThread().getName() + " is working in arrange:");
        AsyncLogicDoingSomeMagic codeUnderTest = new AsyncLogicDoingSomeMagic();

        // act:
        codeUnderTest.doSomeMagic(testObserver);

        // assert:
        Awaitility.await().atMost(2, TimeUnit.SECONDS).until(() -> {
            System.out.println(Thread.currentThread().getName() + " is working in assert:");
            return testObserver.getOnNextEvents().equals(Lists.newArrayList("Maaagic!"));
        });
    }

    private static class AsyncLogicDoingSomeMagic {

        void doSomeMagic(rx.Observer<String> observer) {
            Observable.timer(1, TimeUnit.SECONDS)
                    .map(event -> "Maaagic!")
                    .doOnNext(s -> System.out.println(s + " from " + Thread.currentThread().getName()))
                    .subscribe(observer);
        }

    }
}
```

Output:

```
main is working in arrange:
pool-1-thread-1 is working in assert:
pool-1-thread-1 is working in assert:
pool-1-thread-1 is working in assert:
pool-1-thread-1 is working in assert:
pool-1-thread-1 is working in assert:
pool-1-thread-1 is working in assert:
pool-1-thread-1 is working in assert:
pool-1-thread-1 is working in assert:
pool-1-thread-1 is working in assert:
Maaagic! from RxComputationScheduler-1
pool-1-thread-1 is working in assert:

Process finished with exit code 0
```

The interesting part here is, that Awaitility adds even a third thread to the party.

**Comment by Petikoch** [comment]
Thanks @akarnokd for the thread-safe TestSubscriber#awaitTerminalEvent solution. I didn't know that.

As you see above, I usually use either Spock with "polling condtions" or https://github.com/jayway/awaitility.

Why not make TestObserver ready for those? It's trivial.

**Comment by Petikoch** [comment]
Plus: TestSubscriber#awaitTerminalEvent doesn't allow me to await e.g. the first of a series of events.

**Comment by akarnokd** [comment]
That would duplicate the latching of `TestSubscriber`. Otherwise, waiting for first N events is quite uncommon in our tests.

**Comment by Petikoch** [comment]
Why is there then a **public** class called TestObserver? When I should **not** use it and should use instead TestSubscriber. Why not just delete TestObserver? 

Or why not just make TestObserver "better", in terms of general thread-safety or adding thread-safe, blocking await*-methods on it?

PS: I hope you @akarnokd are not getting angry because of my "insisting". Just close the issue if you don't want it.

**Comment by akarnokd** [comment]
TestObserver is a remnant from the early Rx days and didn't attract attention. It should be deprecated but quite a few tests from those early days use it. I'll post a PR that deprecates it and cleans up.

**Comment by Petikoch** [comment]
Thanks a lot @akarnokd for your time and especially for your fast feedback. Very much appreciated!

Best regards,
Peti

**Comment by akarnokd** [comment]
See #4011.
