### ISSUE TITLE
Contribution agreement change in RxJava.

### ISSUE THREAD

**Issue by stevegury** [ReactiveX/RxJava#4013]
In an effort to streamline decision-making and to facilitate more direct contributions from the community, we are making @akarnokd the lead contributor of RxJava. As lead contributor @akarnokd will have the ability to merge PRs at his discretion, he will lead the design of the 2.x branch and new features and seek reviews from other contributors when necessary.

Many other open-source projects follow this strategy and it better positions the project to have a greater cohesion in the design; it should also increase the speed of execution by avoiding debate.

RxJava continues to be the base of Netflix architecture, we still maintain our interest and plan to continue contributing and reviewing PRs but will no longer reserve the right to review changes prior to merging.

**Comment by artem-zinnatullin** [comment]
Thanks, last weeks discussions in 2.x PRs were really worrying.

"Release button" will still be maintained by Netflix team?

**Comment by stevegury** [comment]
No the "button" is shared, @akarnokd is free to do a release on his own.
In practice, nothing will change, we'll still 👍 on the proposed changelog.

**Comment by zsxwing** [comment]
:+1:

**Comment by benjchristensen** [comment]
I agree with this change. @akarnokd has earned this, and I appreciate this decision to allow 2.x to move forward.

**Comment by davidmoten** [comment]
:+1:  I think this will work well

**Comment by akarnokd** [comment]
Thank you and I accept the position!

**Comment by thomasnield** [comment]
Nice to see this become official. I'm always glad to get his help when he volunteers it. Thanks for all you do @akarnokd!
