### ISSUE TITLE
1.X: Why is CompletableSubscriber not a Subscription?

### ISSUE THREAD

**Issue by bryant1410** [ReactiveX/RxJava#4017]
I see that `CompletableSubscriber` is not a `Subscription`, but `Subcription` is. So, when I use `Completable#subscribe(CompletableSubscriber)`, I cannot then unsubscribe if I want to.

**Comment by akarnokd** [comment]
`CompletableSubscriber` was designed along the Reactive-Streams pattern where cancellation support is injected via `onSubscribe` call. Consumers extending `CompletableSubscriber` then can decide individually if they want to expose this cancellation support to the outside world by implementing `Subscription` themselves. In contrast, `Subscriber` can never revoke its ability to be unsubscribed externally.

If you are using `subscribe()` or the lambda versions of `subscribe`, you get a `Subscription` back. As for the `subscribe(CompletableSubscriber)`, indeed we don't have a supporting class for it (as far as I remember). I'll post a PR for it today.

**Comment by akarnokd** [comment]
Closing via #4020.
