### ISSUE TITLE
Question about onError propagation in Completable#onErrorComplete

### ISSUE THREAD

**Issue by vanniktech** [ReactiveX/RxJava#4025]
I was just browsing some of the source code to get a better understanding and I stumbled upon [https://github.com/ReactiveX/RxJava/blob/1.x/src/main/java/rx/Completable.java#L1666](this line). Isn't there a call to `s.onError(e)` missing?

**Comment by akarnokd** [comment]
Good catch!

**Comment by akarnokd** [comment]
See #4027.

**Comment by akarnokd** [comment]
Closing via #4027
