### ISSUE TITLE
Remove dependency on Nebula plugin for 2.x

### ISSUE THREAD

**Issue by akarnokd** [ReactiveX/RxJava#4032]
(Previously came up in #3170)

In the past, the Nebula plugin was source of trouble and RxAndroid got rid of it some time ago. This suggests and issue tracks the removal of Nebula and the replacement of its relevant features:
- [ ] Remove from `build.gradle`
- [ ] Make sure creating a release through Github still triggers an upload to maven from Travis CI
- [ ] Make sure patch version numbers are automatically incremented and inferred

**Comment by ZacSweers** [comment]
What were the benefits of it? From what I remember the most common usage was its `provided` plugin but that exists natively through gradle now as `compileOnly`.

The maven releases via travis should totally be doable.

Automating patch versions should be easy too, could easily make that a tiny gradle task

**Comment by akarnokd** [comment]
Great! Anybody who wants to tackle this, a PR are welcome. Please notify us if someone starts working on this so won't get PR conflicts on `build.gradle` updates (like PMD).

**Comment by akarnokd** [comment]
Closing. I don't have the skill and nobody else picked this up. The current nebula setup works anyway.
