### ISSUE TITLE
2.x: Backpressure annotation retention.

### ISSUE THREAD

**Issue by JakeWharton** [ReactiveX/RxJava#4037]
Currently `RUNTIME`. Any reason for this? Can we make them `SOURCE`? As I understand they serve merely as documentation.

**Comment by akarnokd** [comment]
The intention was to enable runtime code analysis and document generation (without finding a working source file parser). Plus, you mentioned lint as a means for detecting bad use of `subscribe()`; it could also warn about operators with incompatible backressure modes, such as `zip(interval(), range())`. If lint doesn't need such annotation to be runtime, I'm open to change the retention to source for now.

**Comment by JakeWharton** [comment]
Actually Android's lint (and most static analysis tools) would only need them in `CLASS` retention, not `SOURCE`, since we want them packaged with the library for consuming in applications. If runtime analysis was also desired I think you'd want the operator to be annotated instead of the method for use in a central place like hooks?

**Comment by akarnokd** [comment]
Right. The benefit of the method annotations is that it shows up in the tooltip/javadoc until we add the usual backpressure/scheduler notes. I'm assuming having them on the methods and `RUNTIME` counts towards some Android limit right? Can ProGuard strip the annotations?

**Comment by artem-zinnatullin** [comment]
Never heard of limit on annotations in Android (there might be some, but I think it's per annotated element). It just makes resulting apk file of Android application a little bit bigger since bytecode stores this information.

ProGuard strips annotations by default: http://proguard.sourceforge.net/manual/examples.html#annotations.
