### ISSUE TITLE
2.x: XCompletable refactor

### ISSUE THREAD

**Issue by akarnokd** [ReactiveX/RxJava#4040]
I apologize for two things: 
- I accidentally committed to the 2.x branch directly. I don't have the necessary right on the project to protect branch like 1.x.
- The number of changes is large (due to the switch to the XCompletable base types as @stealthcode proposed). Reviewers can comment on the [commit itself](https://github.com/ReactiveX/RxJava/commit/3382fe792dec743a5250bb9ad877fb98ca828f3c). Naming and location is up for discussion.

**Comment by stevegury** [comment]
No big deal.

**Comment by akarnokd** [comment]
@stevegury I think only the owner can protect branches. Could you turn on protection for 2.x?

**Comment by stevegury** [comment]
I'm not an owner, but @benjchristensen or @abersnaze can do the change.

**Comment by abersnaze** [comment]
@akarnokd i've marked it protected. I wasn't sure if you wanted even more strict than that.

> Disables force-pushes to this branch and prevents it from being deleted.

**Comment by akarnokd** [comment]
Thanks. Yes, I'd like it that regular pushes to 2.x are rejected as well.
