### ISSUE TITLE
1.x: Flaky test OperatorSwitchTest > switchAsyncHeavily

### ISSUE THREAD

**Issue by artem-zinnatullin** [ReactiveX/RxJava#4047]
```
rx.internal.operators.OperatorSwitchTest > switchAsyncHeavily FAILED
    java.lang.AssertionError: switchAsyncHeavily timed out @ 1 (2564049 onNexts received, last was 0 ms ago
        at org.junit.Assert.fail(Assert.java:93)
        at rx.internal.operators.OperatorSwitchTest.switchAsyncHeavily(OperatorSwitchTest.java:880)
```

https://travis-ci.org/ReactiveX/RxJava/builds/139025751#L3527

Seen in #4046.

**Comment by artem-zinnatullin** [comment]
In total: 4 tests from `OperatorSwitchTest` failed in that build:
- https://travis-ci.org/ReactiveX/RxJava/builds/139025751#L3527
- https://travis-ci.org/ReactiveX/RxJava/builds/139025751#L3534
- https://travis-ci.org/ReactiveX/RxJava/builds/139025751#L3551
- https://travis-ci.org/ReactiveX/RxJava/builds/139025751#L3560

**Comment by akarnokd** [comment]
Travis overload/throttling effect, may need to increase the timeout or decrease the amount.

**Comment by artem-zinnatullin** [comment]
Yeah, Travis becomes more and more flaky, especially noticeable with instrumentation tests on Android Emulator…

We can add one more CI to the project, keep both working for some time (it'll appear as separate status check on PRs/commits) and then decide which to keep. CircleCI is pretty ok and free for OSS.

**Comment by JakeWharton** [comment]
Every other cloud CI will see the same problems since they all run on the backs of platform-as-a-service providers. The release infrastructure is also currently tied to Travis.

Raising the timeout seems 1000x easier than something so drastic as changing CI providers.

**Comment by artem-zinnatullin** [comment]
@akarnokd does it make sense to add a constant multiplier for flakiness, shared between all async tests or each one needs individual value? 

``` java
@Test(timeout = 3000 * FLAKINESS)
```

> so drastic as changing CI providers

If it's drastic — it's bad…

**Comment by akarnokd** [comment]
Not all timeouts are in the annotation, some are in the code. I suggest increasing the numbers for tests that show up in these failures.

**Comment by artem-zinnatullin** [comment]
You can apply multiplier in the code too, but I'm ok with tweaking individual ones too of course.

**Comment by akarnokd** [comment]
Closing as not happening for a while now.
