### ISSUE TITLE
2.x: Change SchedulerSupport to string?

### ISSUE THREAD

**Issue by JakeWharton** [ReactiveX/RxJava#4052]
In some specific uses of RxJava it's common to have other important schedulers that one cares about. If the `@SchedulerSupport` annotation was changed to use a `String` as its value and provide constants on that type for its first-party values this would allow those other schedulers to be analyzed in the same way.

This will allow static analysis tools to enforce constraints with these "custom" schedulers as actual named-entities instead of having to rely on the otherwise opaque `CUSTOM` value. Additionally, libraries will be able to annotate their factory methods which operate on these schedulers appropriately.

I'm thinking specifically of Android, RxAndroid, and having `"mainThread"` be a value.

Happy to make this change if it sounds like a good idea.

**Comment by akarnokd** [comment]
:+1:, I'm not touching the base reactive types in the next 12 hours so go ahead with the PR.

**Comment by JakeWharton** [comment]
Resolved by #4053. Not sure why it didn't auto-close.

**Comment by zsxwing** [comment]
> Resolved by #4053. Not sure why it didn't auto-close.

Only patches merged to the `default` branch can auto-close issues.

**Comment by JakeWharton** [comment]
Ah, good call.
