### ISSUE TITLE
2.x: Unify two type parameters from Subject into one?

### ISSUE THREAD

**Issue by JakeWharton** [ReactiveX/RxJava#4056]
This came up in passing in an issue or PR before (that I can't find at this moment), but the two type parameters on `Subject` seem to only be a nuisance instead of a benefit.

Should we remove them?

None of the built-in implementations allow consuming a type different than is being emitted, which makes the two type parameters on the supertype seem very out of place.

**Comment by zsxwing** [comment]
:+1: RxScala uses one parameter for a long time and no one complaints.

**Comment by akarnokd** [comment]
It's a remnant of the "Subject as a processing stage" mentality of Rx.NET, but unlike Java, you can have classes with the same name and different number of type parameters.

:+1:, would you like to do it?

**Comment by JakeWharton** [comment]
I can tomorrow! It's 3am here and that other PR I sent wore me out.
