### ISSUE TITLE
2.x: SerialDisposable and MultipleAssignmentDisposable are exactly the same

### ISSUE THREAD

**Issue by JakeWharton** [ReactiveX/RxJava#4057]
Either one is erroneously implemented or let's pick one to keep.

**Comment by akarnokd** [comment]
There is a difference:

https://github.com/ReactiveX/RxJava/blob/2.x/src/main/java/io/reactivex/disposables/SerialDisposable.java#L33

https://github.com/ReactiveX/RxJava/blob/2.x/src/main/java/io/reactivex/disposables/MultipleAssignmentDisposable.java#L32

Multiple doesn't dispose the previous Disposable but Serial does.

However, I'm totally for merging the two classes and have `set` and `replace` on them.

**Comment by JakeWharton** [comment]
Wow super subtle! I had them open side-by-side and wasn't able to see that.

I can take this change tomorrow as well. Is there a preference for the name
of this merged type?

**Comment by akarnokd** [comment]
Open for discussion, I was leaning towards `SingleDisposable` but could get confused with `Single` in IDE content assist.

**Comment by JakeWharton** [comment]
`AssignableDisposable`? `ReferenceDisposable`?

**Comment by artem-zinnatullin** [comment]
Closed by #4070.

**Comment by akarnokd** [comment]
I think `SerialDisposable` is good enough now.
