### ISSUE TITLE
Official javadoc access for 1.x and 2.x

### ISSUE THREAD

**Issue by akarnokd** [ReactiveX/RxJava#4061]
Currently, the link http://reactivex.io/RxJava/javadoc/ points to the 1.x documentation. Since the two library versions will live side-by-side for some years, we have to make sure their javadocs are accessible.

I suggest having links as 

http://reactivex.io/RxJava/1.x/javadoc/ and 
http://reactivex.io/RxJava/2.x/javadoc/ 

and if possible, have a redirect in http://reactivex.io/RxJava/javadoc/ for 1.x.

**Comment by stevegury** [comment]
👍

**Comment by ZacSweers** [comment]
👍

**Comment by akarnokd** [comment]
Closing via #4424.
