### ISSUE TITLE
2.x: DisposableHelper set() and replace() are confusing 

### ISSUE THREAD

**Issue by artem-zinnatullin** [ReactiveX/RxJava#4073]
Maybe it's just me, but it took me some time to understand the difference between those methods while I was reading #4070.

Can we give more meaningful names to those methods, like `setAndDisposePrevious()` and `set()`? 

`replace()` and `set()` are ~ synonyms and it's really hard to get the difference without reading sources.

**Comment by akarnokd** [comment]
Maybe it gets less confused when they get javadoc; but I definitely dislike `setAndDisposePrevious`.

**Comment by artem-zinnatullin** [comment]
I tried to follow pattern of Atomic\* classes methods, like `compareAndSet`.

**Comment by akarnokd** [comment]
This is an internal tool and its naming is irrelevant. I like to keep it short.
