### ISSUE TITLE
2.x: Expose Disposable.isDisposed()?

### ISSUE THREAD

**Issue by JakeWharton** [ReactiveX/RxJava#4075]
In `Disposable.java` currently:

``` java
// TODO let's see if we really need this
// boolean isDisposed();
```

I think we should add this since `dispose()` already states:

> Dispose the resource, the operation should be idempotent.

Which means every disposable already needs a mechanism for idempotence which should trivially translate into `isDisposed()`.

There's some massive refactors that can be done if this change is made. `BooleanDisposable` can completely disappear from the public API since `Disposables.from(Runnable)` + `Disposables.empty()` mimic its behavior. Additionally a large portion of the other internal, custom disposables can be rewritten to build on an internal `BooleanDisposable` which manages both idempotence and the `isDisposed()` implementation for you.

I did some of this work last night as an experiment and it looks like a good win. The argument against the refactor would be if there's a reason we don't actually want to expose `isDisposed()` on `Disposable` directly. I'll note that `BooleanDisposable` is not unique in having an `isDisposed()` method. Most other implementations also have this method, they simply don't share it from the interface.

**Comment by JakeWharton** [comment]
And I'm volunteering for this work, if that wasn't obvious...

**Comment by akarnokd** [comment]
The problem with adding `isDisposed` that it mandates stateful `Disposable` implementations for all use cases (empty can't be constant but requires newing up a new instance because it has to switch to disposed state in a visible manner). As the current 2.x demonstartes, checking for `isDisposed` is only required by a few container classes. Thus, I'd like to keep `Disposable` as is. You can introduce an interface on top of it for the container classes if you really want to.

**Comment by JakeWharton** [comment]
Ok let me see how far I can get without exposing method. I did see that empty had to become a factory as a result, but I don't know how frequent the need for an empty instance is such that it would be a problem.

**Comment by JakeWharton** [comment]
After more investigation it looks like `empty()` is the _only_ stateless `Disposable` in the entire lib aside from `disposed()`. Every other implementation is stateful and if it doesn't already declare `isDisposed()`, it can do so trivially.

Tell me what you think about this plan:
1. Document `DisposableHelper.DISPOSED` as a marker instance to be compared by identity (done in #4081) and `EmptyDisposable.INSTANCE` as a no-op implementation to be used internally as a value.
2. Change `Disposables.empty()` to return `new BooleanDisposable()`
3. Uncomment `isDisposed()` on `Disposable` and ensure a proper implementation on all implementations.

That said, I'm not convinced `empty()` needs to even exist as a public API. But if it does, then it's likely used so rarely that the fact that it needs to allocate a single, tiny object shouldn't matter. Internally all "empty" values will use `EmptyDisposable.INSTANCE` which will behave like an already-disposed `Disposable`.

**Comment by akarnokd** [comment]
Okay, go ahead with the PR.
