### ISSUE TITLE
2.x: Subscribers, Observables classes leak internal types into the public API

### ISSUE THREAD

**Issue by JakeWharton** [ReactiveX/RxJava#4082]
All of the methods doing this are at present unused. If they're for public consumption we need `DisposableSubscriber` and `NbpDisposableSubscriber` (or equivalent) to be in a public package.

**Comment by akarnokd** [comment]
Yes, we should avoid these.

**Comment by akarnokd** [comment]
I'd like to resolve this; could you point me to the problematic classes and what exactly is leaking?

**Comment by JakeWharton** [comment]
It's the `createDisposable` methods in `Subscribers` and `Observers` which return `DisposableSubscriber` and `DisposableObserver`.

**Comment by akarnokd** [comment]
See #4337.

**Comment by akarnokd** [comment]
I think this has been resolved. Let me know if you find something else (or post a fix PR).
