### ISSUE TITLE
Proposal: filterBy(Class) API

### ISSUE THREAD

**Issue by ZacSweers** [ReactiveX/RxJava#4089]
When dealing with polymorphic types, I've often had cases where I needed to `filter` by a type and then immediately have to follow that with a seemingly-redundant `cast` to that type that I've already filtered on. This issue proposes an operator that would add a convenience API for this.

Example:

``` java
myMammalObservable
    .filter(m -> m instanceof Dog)
    .cast(Dog.class)
    .subscribe(dog -> dog.playFetch());
```

Proposal would probably encapsulate that exact logic, though we could combine it into a single operator if there's a perf gain to be had by doing so. Would look like this in use:

``` java
myMammalObservable
    .filterBy(Dog.class)
    .subscribe(dog -> dog.playFetch());
```

Up for better naming suggestions, just found myself doing this several times in the last week. Totally understand if it's trivial enough not to warrant something on the first-party API. Happy to submit a PR if you'd want it.

**Comment by akarnokd** [comment]
We have such an operator from very early on:

``` java
    /**
     * Filters the items emitted by an Observable, only emitting those of the specified type.
     * <p>
     * <img width="640" height="310" src="https://raw.github.com/wiki/ReactiveX/RxJava/images/rx-operators/ofClass.png" alt="">
     * <dl>
     *  <dt><b>Scheduler:</b></dt>
     *  <dd>{@code ofType} does not operate by default on a particular {@link Scheduler}.</dd>
     * </dl>
     * 
     * @param <R> the output type
     * @param klass
     *            the class type to filter the items emitted by the source Observable
     * @return an Observable that emits items from the source Observable of type {@code klass}
     * @see <a href="http://reactivex.io/documentation/operators/filter.html">ReactiveX operators documentation: Filter</a>
     */
    public final <R> Observable<R> ofType(final Class<R> klass) {
```

**Comment by ZacSweers** [comment]
ಠ_ಠ brb going to go buy reading glasses because I'm apparently blind.

**Comment by davidmoten** [comment]
@hzsweers the alias `Observable.filterBy(...)` for `Observable.ofType` would be a useful PR though I think. Discoverability improvement (I'd forgotten it existed and had been using `filter`!)

**Comment by DavidMGross** [comment]
A good example of where the website documentation of operators improves on
the javadocs: `filter` and `ofType` are documented side-by-side there:
http://reactivex.io/documentation/operators/filter.html

On Thu, Jun 23, 2016 at 5:32 AM, Dave Moten notifications@github.com
wrote:

> @hzsweers https://github.com/hzsweers the alias Observable.filterBy(...)
> for Observable.ofType would be a useful PR though I think.
> Discoverability improvement (I'd forgotten it existed and had been using
> filter!)
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> https://github.com/ReactiveX/RxJava/issues/4089#issuecomment-228035483,
> or mute the thread
> https://github.com/notifications/unsubscribe/AESHoA4yIuvZaF4F5ZPJYgq4QTfBf4O9ks5qOnzUgaJpZM4I8irS
> .

## 

David M. Gross
PLP Consulting
