### ISSUE TITLE
What's different in 2.0 from user|developer perspective

### ISSUE THREAD

**Issue by akarnokd** [ReactiveX/RxJava#4121]
I've started writing up wiki pages for detailing what's the difference between 1.x and 2.x:

https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0
~~https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0-(draft)~~

Let me know what else to describe from a library user's perspective.

**Comment by JakeWharton** [comment]
> `Action1` has been renamed to `Consumer` ... `ActionN` is replaced by the `Action1<Object[]>` type declaration.

The latter presuambly should be `Consumer<Object[]>`

**Comment by akarnokd** [comment]
Closing via 2nd side: https://github.com/ReactiveX/RxJava/wiki/Writing-operators-for-2.0
