### ISSUE TITLE
Trailing whitespace

### ISSUE THREAD

**Issue by vanniktech** [ReactiveX/RxJava#4123]
Often when submitting a PR the trailing whitespace gets automatically deleted because Sublime / IntelliJ was configured that way.

What do you guys think about passively trying to remove those?

In 1.x version PR's containing removal of trailing whitespaces could be accepted rather than letting the PR OP removing it.
In 2.x version there could be one bulk PR that deletes all of those spaces. If this is not wanted it could go also along with every PR.

Personally I'd love to see no file having trailing whitespace. If this is not wanted, also not a problem.

**Comment by akarnokd** [comment]
My grief is when unrelated content changes due to these settings. Otherwise I don't mind if a PR contains extra spaces.

**Comment by JakeWharton** [comment]
I spend a non-trivial amount of time doing `git add -p` and editing diffs so reduce whitespace changes. I've even resorted to turning off "trim trailing whitespace" in my editor, which is something I never thought I'd do (and why isn't trimming the default in _every_ editor?).

**Comment by vanniktech** [comment]
@JakeWharton I've been using the solution proposed [here](http://stackoverflow.com/questions/3515597/add-only-non-whitespace-changes) to not waste my time dividing and adding individual chunks.

`git diff -U0 -w --no-color | git apply --cached --ignore-whitespace --unidiff-zero -` did the job for me. Only stages chunks that contain valid changes and ignores white space only changes.

Nonetheless I feel like trimming trailing whitespace should be the default option and no one would need to go through those magic git tips to create a PR here.

**Comment by JakeWharton** [comment]
Looks like it didn't work on your PR though. I already need to use -p to
"fix" the star imports as well.

**Comment by vanniktech** [comment]
True I first created the PR containing the whitespace changes. After that I fixed it and force pushed it. All whitespaces are preseverd now.

Yes the star imports are another problem ...

**Comment by akarnokd** [comment]
I don't mind whitespaces or if you removed them in PRs anyomore but I won't bother removing them in my PRs.

How about everybody posts with what whitespace settings he/she sees adequate?

**Comment by vanniktech** [comment]
How about configuring your IDE so that it'll strip them out automatically?

**Comment by vanniktech** [comment]
@akarnokd are you willing to merge one PR that removes all of the trailing white space and nothing else in 2.x branch? After that a simple Checkstyle rule could be added to enforce no trailing whitespace anymore. There are also options available in Eclipse to [automate this](http://stackoverflow.com/a/2618521/1979703).

**Comment by akarnokd** [comment]
PR yes, Checkstyle no. It complains about too much thing and setting it up for a fresh checkout is non-trivial. How about writing some code in build.gradle that scans through the files before build and lists those lines where they are still there?

**Comment by akarnokd** [comment]
But please wait with the PR until I post my cleanup/enhancements of today.

**Comment by vanniktech** [comment]
Alright will do 👍

**Comment by akarnokd** [comment]
Closing via #4500 and #4496.
