### ISSUE TITLE
Inverted onError and onComplete in Completable

### ISSUE THREAD

**Issue by lukasz-gosiewski** [ReactiveX/RxJava#4137]
In completable subscribe method there is inverted order of methods (in compare to ex. Observable). In every other classes there is onNext/onSucces first, and in Completable there is onError first.

**Comment by vanniktech** [comment]
Dupe of #3851

**Comment by akarnokd** [comment]
Closing as duplicate. If you have time, you could post a PR that swaps the params as described in #3851.
