### ISSUE TITLE
2.x: Subscription (Disposable) optimization

### ISSUE THREAD

**Issue by artem-zinnatullin** [ReactiveX/RxJava#4147]
It's a continuation of [twitter conversation](https://twitter.com/akarnokd/status/748168094368079873).

Here is comparison of RxJava v1, RxJava v2 and Streams API (omit others for now) performance in a "Shakespeare" test made by @akarnokd.

![cmigserweaahpw7](https://cloud.githubusercontent.com/assets/967132/16472969/48c5bf28-3e7a-11e6-9de4-fd7b0e56ce92.jpg)

RxJava v2 is obviously faster than RxJava v1 because of different optimizations techniques @akarnokd has already applied. I'm going to suggest one that I see possible.

About ~30% of `subscribe()` calls (including test code) in my experience from production projects do not handle returned `Subscription`, which means that whole subscription management overhead is not needed for such calls.

What if we make 2 kinds of `subscribe()` function, one will return `Subscription` (Disposable) and one will not and will disable subscription management in this whole Rx chain.

Probably I've missed something, feedback is welcomed.

**Comment by JakeWharton** [comment]
Subscribe returns void in v2. You pass in the cancelation signal.

**Comment by artem-zinnatullin** [comment]
Hm, I see. I'll try to dive into 2.x code soon, probably it's already
implemented in some manner. Looks like the only thing we can save is
allocation of Disposable.

**Comment by akarnokd** [comment]
It's not the subscription that makes RxJava 1 slower but the infrastructure overhead and allocation in each `Subscriber`. RxJava 1 `Subscriber` has resource management and deferred `Producer` management even though they are not required in most of the cases and the role can be shifted to the upstream - as it is done in v2.

**Comment by akarnokd** [comment]
Closing as nothing to do in v2.
