### ISSUE TITLE
1.x: concatDelayError with multiple args

### ISSUE THREAD

**Issue by bryant1410** [ReactiveX/RxJava#4152]
I think it'd be great if `concatDelayError` supports multiple parameters as `mergeDelayError`.

Btw, doesn't `mergeDelayError` miss a variation in which a variable number of args is admitted?

**Comment by akarnokd** [comment]
The general problem with these that they expand the API surface (like + 8 methods per operator) which is already 'bloated'.

We don't do variable arguments in Java 6 because it necessitates `@SuppressWarnings` almost always (hence the convenience 2-9 arg operators).

**Comment by akarnokd** [comment]
Closing via #4261.
