### ISSUE TITLE
Use of Marble Diagrams for Commercial Book

### ISSUE THREAD

**Issue by benjchristensen** [ReactiveX/RxJava#4158]
Hello everyone, I'm helping @nurkiewicz write a book about RxJava (http://shop.oreilly.com/product/0636920042228.do). It intends to use marble diagrams in explaining the operators. 

The intent is to use (with slight modification such as color) the same ones used for RxJava documentation and contained in this file: https://raw.githubusercontent.com/wiki/ReactiveX/RxJava/images/rx-operators.graffle

As long as the book references this URL as their source, does anyone have issues with the use of these images in a commercial book by O'Reilly?

In the past when I was leading this project, we granted everyone the right to use the images for presentations and whatever use they wished, but I was never aware of commercial use. Since this is for a book that will provide profits to O'Reilly and @nurkiewicz (disclosure, I have no financial interest in the book, but my name will be associated with it), I want to confirm with the community if you are okay with the usage. 

If not, the book will still use marble diagrams, just re-create them to look slightly different (size, color, whatever). 

Thank you.

**Comment by akarnokd** [comment]
The `reactivex.github.io` has an [Apache 2.0 license file](https://github.com/ReactiveX/reactivex.github.io/blob/develop/LICENSE) so I'd assume the images also follow this license. I don't see any problems and from my side so you can reuse the images :+1:.

/cc @DavidMGross

**Comment by abersnaze** [comment]
👍 fine with me.

**Comment by DavidMGross** [comment]
Fine by me. There are a few operators and operator variants that don't have
diagrams yet, so this might be a good opportunity for @nurkiewicz
https://github.com/nurkiewicz to add those to the mix (see e.g. ReactiveX/
reactivex.github.io#213).

On Fri, Jul 1, 2016 at 9:55 AM, David Karnok notifications@github.com
wrote:

> The reactivex.github.io has an Apache 2.0 license file
> https://github.com/ReactiveX/reactivex.github.io/blob/develop/LICENSE
> so I'd assume the images also follow this license. I don't see any problems
> and from my side so you can reuse the images 👍.
> 
> /cc @DavidMGross https://github.com/DavidMGross
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/ReactiveX/RxJava/issues/4158#issuecomment-229996194,
> or mute the thread
> https://github.com/notifications/unsubscribe/AESHoK3AxJnGJS06ZJq2Us6AUt88LgaIks5qRUaVgaJpZM4JDS2g
> .

## 

David M. Gross
PLP Consulting

**Comment by benjchristensen** [comment]
Thanks everyone. @nurkiewicz, go ahead and use that file linked to above.
