### ISSUE TITLE
Method for shutdown CachedObservable

### ISSUE THREAD

**Issue by HotIceCream** [ReactiveX/RxJava#4164]
I have endless stream (which is not called onComplete at all). And I cache last value in it:

```
Observable<T> endlessStream = createStream().cache();

Subscription s1 = endlessStream.subscribe(...)
Subscription s2 = endlessStream.subscribe(...)
```

By some condition endlessStream become not valid and I replace it (with switchMap, but it's not important).

```
s1.unsubscribe()
s2.unsubscribe()
```

But CachedObservable will always store connection to source stream (returned from createStream()). This leads to memory leak. How to disconnect CachedObservable from source observable?

More information:

CachedObservable contains field state, which contain SerialSubscription to source observables (connection). If I call next hack, everything becomes OK:

```
private void disconnectCachedObservable(CachedObservable<T> observable) {
    try {
        Field fieldState = CachedObservable.class.getDeclaredField("state");
        fieldState.setAccessible(true);
        Object state = fieldState.get(observable);
        Field fieldConnection = state.getClass().getDeclaredField("connection");
        fieldConnection.setAccessible(true);
        SerialSubscription subscription = (SerialSubscription) fieldConnection.get(state);
        subscription.unsubscribe();
    } catch (NoSuchFieldException e) {
        e.printStackTrace();
    } catch (IllegalAccessException e) {
        e.printStackTrace();
    }
}
```

But reflection isn't good solution:(

Maybe create public method it?

**Comment by akarnokd** [comment]
You can use 

``` java
replay().autoConnect(1, toStop -> { /* store Subscription to cancel later */ });
```

which let's you stop the upstream by giving you a `Subscription`.

**Comment by HotIceCream** [comment]
Oh yes. It's help. Thank you!
I tried replay + autoConnect, but didn't know about second argument in autoConnect.
