### ISSUE TITLE
Cannot customize ThreadFactory in GenericScheduledExecutorService

### ISSUE THREAD

**Issue by ffgiraldez** [ReactiveX/RxJava#4171]
Some platform like AppEngine have limitations populating threads and have their own mechanism to do it. with last version (1.1.6 at this moment) it's not posible to use rx-java in gae due to don't exist a mechanism to override via RxPlugin or whatever the ThreadFactory in GenericScheduledExecutorService used in [ObjectPool](https://github.com/ReactiveX/RxJava/blob/ed92ba833f05b7eb04ff7d592040656f9bcbcf32/src/main/java/rx/internal/util/ObjectPool.java#L109).

In 1.0.X version don't exist that class and[ ObjectPool(1.0.X)](https://github.com/ReactiveX/RxJava/blob/v1.0.16/src/main/java/rx/internal/util/ObjectPool.java#L107) use Schedulers.computation().createWorker instead.
Please add some mechanism to pass our custom ThreadFactory into GenericScheduledExecutorService in order to use last version of rx-java in GAE

**Comment by akarnokd** [comment]
See #4173. It would be great if you could check that PR out and see if there isn't anything pre-initializing the GSES if your first action only touches `RxJavaHooks`.

**Comment by akarnokd** [comment]
Closing via #4173.

**Comment by ffgiraldez** [comment]
work like a charm with 1.1.7 using RxJavaHooks instead of RxJavaPlugin thanks a lot @akarnokd

**Comment by akarnokd** [comment]
Great, thanks for confirming!
