### ISSUE TITLE
1.2 API promotion/demotion referendum

### ISSUE THREAD

**Issue by akarnokd** [ReactiveX/RxJava#4185]
Dear @ReactiveX/rxjava-committers and frequent contributors,

We have accumulated quite the number of `@Beta` and `@Experimental` APIs since `1.1` and I believe it's about time we release 1.2  (within a month unless there are problems with 1.1.7's set of experimental APIs).

[This gist](https://gist.github.com/akarnokd/5c3e7cd6239f691194b78e38bf706dbe) lists all these methods and entire classes.

Please take some time, organize the components by what should happen with that particular entry:
- promote experimental/beta to standard
- promote experimental to beta
- demote beta to experimental
- remove beta
- remove experimental
- keep it as experimental/beta

Please post a gist of your results here or privately to **akarnokd at gmail dot com**. Based on the majority votes for each entry, PRs will be posted that perform the annotation/javadoc change.

Then, unless there are some problems/expansions with 1.1.7, the expected release date for 1.2 is 

**July 31, 2016**.

**Comment by akarnokd** [comment]
[My votes](https://gist.github.com/akarnokd/cfabbb184efa96d8c52443f89a6f38e4)
- promote beta to standard: _39 components_
- promote experimental to standard: _0 components_
- promote experimental to beta: _56 components_
- keep as is: _43 components_
- demotions or removals: _0 components_

**Comment by JakeWharton** [comment]
I mostly agree with your list. Instead of listing them all, I'm going to just show a diff:

#### `@Experimental` to `@Beta`
- rx.exceptions.Exceptions.throwOrReport(Throwable, Observer<?>, Object)
- rx.exceptions.Exceptions.throwOrReport(Throwable, Observer<?>)
- rx.exceptions.Exceptions.throwOrReport(Throwable, SingleSubscriber<?>)
- rx.Observable.distinctUntilChanged(Func2<? super T, ? super T, Boolean>)

**Comment by akarnokd** [comment]
I've extended the deadline till 30th August in case of holidays.

**Comment by artem-zinnatullin** [comment]
Can someone else please join discussion about renaming `fromAsync()` #4255? I would like to make it available for library developers.

**Comment by akarnokd** [comment]
Closing. Continued in #4549.
