### ISSUE TITLE
Merge of Observable using SyncOnSubscribe and PublishSubject does not work 

### ISSUE THREAD

**Issue by Witko** [ReactiveX/RxJava#4198]
You can reproduce mentioned behaviour with:

```
    @Test
    public void name() throws Exception {
        Observable<String> ahoj =
                Observable.create(SyncOnSubscribe.createStateless(o -> {
                    o.onNext("ahoj");
                    try {
                        sleep(50);
                    } catch (InterruptedException e) {
                        e.printStackTrace();
                    }
                }));
        PublishSubject<String> subject = PublishSubject.create();

        Observable.merge(ahoj, subject)
                .subscribeOn(Schedulers.io())
                .subscribe(System.out::println);

        for (int i = 0; i < 10; i++) {
            subject.onNext("Subject!");
            sleep(100);
        }
        sleep(100);
    }
```

This never writes "Subject!"
When tried with  `ahoj = Observable.just("1", "2", "3")` it worked.

Tested with 1.1.6 & 1.1.7
Thanks!

**Comment by akarnokd** [comment]
You are merging the two on the same background thread where first the ahoy is requested 128 elements. Since you sleep, it takes 128 \* 50 ms = 6400 it to produce all the requested item and until then `subject` is not even subscribed to. Swap the two in merge so `subject` is subscribed first. Alternative is to apply `subscribeOn` only to `ahoy` and not the entire `merge`.

**Comment by Witko** [comment]
Hi @akarnokd ,
thank you for reply. I've tried both approaches you mentioned and it worked. Still I'm a bit curious why this happens - I've tried the original solution with longer time for the `Subject!` message to arrive but nothing happened.
To my understanding the `observeOn` operator defines on which thread pool the values will be produced. The `subscribeOn` defines on which thread pool the sysout will be performed.
Do I understand this correctly? Why is then the producing influenced by `subscribeOn`?

**Comment by akarnokd** [comment]
http://tomstechnicalblog.blogspot.hu/2016/02/rxjava-understanding-observeon-and.html

http://akarnokd.blogspot.hu/2016/03/subscribeon-and-observeon.html

**Comment by Witko** [comment]
Thanks, that was quite helpful. I have also one related question.
To clarify what I'm trying to achieve - I'm periodically reading new data from database and emitting it through observable. The actual implementation is that the observable gets the next data item from a buffer. If it gets empty it blocks until there is some. So the observable reads data from a blocking source.
Into this stream of data I want to merge control message.
The rough implementation with incorporated suggestions:

```
    @Test
    public void name() throws Exception {
        AtomicInteger emitCounter = new AtomicInteger();
        AtomicInteger receiveCounter = new AtomicInteger();

        SerializedSubject<String, String> ss = PublishSubject.<String>create().toSerialized();

        Observable<String> ob = Observable.create(
                SyncOnSubscribe.createStateless(observer -> {
                    observer.onNext("Data");
                    emitCounter.incrementAndGet();
                    // Pause emitting after 100 000 emits
                    if (emitCounter.get() >= 100_000) {
                        sleep(10000000);
                    }
                }));

        ob = ob.observeOn(Schedulers.computation());

        ob = Observable.merge(ss.asObservable(),
                              ob);
        ob.subscribe(s -> {
            receiveCounter.incrementAndGet();
        });

        for (int i = 0; i < 10; i++) {
            ss.onNext("Subject!");
            sleep(100);
        }

        sleep(4000);
        System.out.println(emitCounter.get());
        System.out.println(receiveCounter.get());
    }
```

The issue I'm having now is that the amount of received data is always less than produced. It almost always prints:

```
100000
99946
```

Is there some buffering in between? The issue is I cannot afford to lose data. Also it can occur that no new data will arrive in some period of time. But all the data loaded should reach the subscriber.
Thank you for your help!

**Comment by akarnokd** [comment]
The `observeOn` uses a replenishment strategy that requests while it emits data. Because you block in the generator, the operator is stopped and can't emit the last set of values in its buffer.

**Comment by Witko** [comment]
Thank you for you help!
