### ISSUE TITLE
add documentation for AsyncEmitter.BackpressureMode

### ISSUE THREAD

**Issue by weefbellington** [ReactiveX/RxJava#4199]
`AsyncEmitter.BackpressureMode` does not have documentation explaining how the different backpressure modes work. Maybe there could be a breadcrumb linking to `Observable#onBackpressureDrop`, `Observable#onBackpressureBuffer` and `Observable#onBackpressureLatest`?

It doesn't look like there's a corresponding `Observable` method for `BackpressureMode.ERROR` so this could also be documented.

**Comment by akarnokd** [comment]
A PR is welcome.

**Comment by akarnokd** [comment]
See #4442.

**Comment by akarnokd** [comment]
Closing via #4442.
