### ISSUE TITLE
Wiki url of contains and exists has same link

### ISSUE THREAD

**Issue by xwendotnet** [ReactiveX/RxJava#4201]
In the list page https://github.com/ReactiveX/RxJava/wiki/Conditional-and-Boolean-Operators.

methods: contains exists navigate to the same url. So where is the doc of exists?

**Comment by DavidMGross** [comment]
contains(), exists(), and isEmpty() are all described on the same reactivex.io webpage: http://reactivex.io/documentation/operators/contains.html

Open the "RxJava" accordion on that page by clicking "RxJava contains exists isEmpty" to see descriptions of all three operators.
