### ISSUE TITLE
I can download it from "https://jcenter.bintray.com/io/reactivex/rxjava/1.1.3/rxjava-1.1.3.jar" ,but can't use compile 'io.reactivex:rxjava:1.1.3'

### ISSUE THREAD

**Issue by halibobo** [ReactiveX/RxJava#4203]
> Could not download rxjava.jar (io.reactivex:rxjava:1.1.3)
> Could not get resource 'https://jcenter.bintray.com/io/reactivex/rxjava/1.1.3/rxjava-1.1.3.jar'.
>       > Could not GET 'https://jcenter.bintray.com/io/reactivex/rxjava/1.1.3/rxjava-1.1.3.jar'.
>          > Connect to akamai.bintray.com:443 [akamai.bintray.com/127.0.0.1] failed: Connection refused: connect

**Comment by artem-zinnatullin** [comment]
https://jcenter.bintray.com/io/reactivex/rxjava/1.1.3/rxjava-1.1.3.jar works for me.

You can also try to use Maven Central repository if jCenter doesn't work for you. Probably global firewall in your country blocks access to bintray.

**Comment by halibobo** [comment]
It's ok now, thanks!
