### ISSUE TITLE
Option for Subscription to add self to CompositeSubscription

### ISSUE THREAD

**Issue by bakua** [ReactiveX/RxJava#4205]
Hey, when managing multiple subscriptions I am a little bit frustrated with a confused code the `CompositeSubscription` causes.
In following example you can see that the Observable itself is a little bit hidden.

```
CompositeSubscription compositeSubscription = new CompositeSubscription();
compositeSubscription.add(Observable.just("test")
    .subscribe(new Subscriber<String>() {
            @Override
            public void onCompleted() {

            }

            @Override
            public void onError(Throwable e) {

            }

            @Override
            public void onNext(String s) {

            }
        }));
```

It would be great to have something convinient. For example something as simple as one method in Subscriber

```
    public void addTo(@NonNull CompositeSubscription compositeSubscription) {
        compositeSubscription.add(this);
    } 
```

This way the previous example would change into:

```
CompositeSubscription compositeSubscription = new CompositeSubscription();
Observable.just("test")
   .subscribe(new Subscriber<String>() {
            @Override
            public void onCompleted() {

            }

            @Override
            public void onError(Throwable e) {

            }

            @Override
            public void onNext(String s) {

            }
        })
   .addTo(compositeSubscription);
```

I am more than happy to make a pull request for such a thing.

Thanks.
bakua

**Comment by akarnokd** [comment]
I'm sorry but no. `Subscription` is a deliberately minimal interface with one objective: unsubscribe a potential chain of resources. Since we are **Java 6, no default methods are allowed** (besides, it would lead to cyclic dependency between the two), plus **we have to maintain binary compatibility** and changing `Subscription` into an abstract class would break it.

Why not have a static method somewhere which you import statically what does the boilerplate for you:

``` java
public static <T> void subscribeForMe(
        Observable<T> source, Subscriber<? super T> subscriber, 
        CompositeSubscription container) {
    container.add(source.subscribe(subscriber));
}

CompositeSubscription compositeSubscription = new CompositeSubscription();

subscribeForMe(Observable.just("test"), new Subscriber<String>() {
            @Override public void onCompleted() { }

            @Override public void onError(Throwable e) { }

            @Override public void onNext(String s) {  }
        }, 
    compositeSubscription);
```

**Comment by bakua** [comment]
Hi, sorry I've expressed myself incorrectly. My intention was not to extend Subscription interface, but rather to add method to Subscriber implementation.

There already is a method in Subscriber that does:

```
public final void add(Subscription s) {
    subscriptions.add(s);
}
```

I'd love to have a 2nd one that works the way around:

```
public final void addTo(Subscription s) {
    s.add(this);
}
```

**Comment by akarnokd** [comment]
That would still require the changing of `Subscription` thus my comment still stands.

**Comment by JakeWharton** [comment]
This was also already suggested in #2919.

**Comment by bakua** [comment]
I see, thanks. I took an inspiration from RxSwift where such an option exists.

```
Observable<Int>.interval(1.0, scheduler: MainScheduler.instance)     
    .map({num in num * 10})
    .subscribeNext({num in print(num)})
    .addDisposableTo(disposeBag)
```

But if it is not possible to have it in RxJava, feel free to close this issue.
