### ISSUE TITLE
RxJavaHooks.enableAssemblyTracking() breaks error handling

### ISSUE THREAD

**Issue by artem-zinnatullin** [ReactiveX/RxJava#4212]
Problem:

If user enables assembly tracking then **ALL** exceptions get wrapped into `AssemblyStackTraceException` which breaks all error handling code that expects particular exceptions.

Solution:

Do not change type of original exception and modify its stacktrace directly. I'll work on that soon, both for 1.x and 2.x.

// Spent an hour today trying to figure out what was causing app misbehave, glad we have `git bisect`, was very surprised to see commit where I enabled assembly tracking…

**Comment by akarnokd** [comment]
Yeah, in [Java 8](https://github.com/reactor/reactive-streams-commons/blob/master/src/main/java/rsc/publisher/PublisherOnAssembly.java#L140) I simply add it as a suppressed exception. In Java 8, you have to find an unused slot of cause in a potentially complicated graph of exceptions and composites.

**Comment by pyricau** [comment]
This change likely caused #4737
