### ISSUE TITLE
BehaviorSubject that emits last item even after completion

### ISSUE THREAD

**Issue by Alxandr** [ReactiveX/RxJava#4214]
I'm looking for the following functionality: 
1. A subject that initially works like a BehaviorSubject. If I `create` it with no initial value, any subscribers will wait for the first value before `onNext` is called.
2. Similarly, if `create` is called with an initial value, then any subscribers will be invoked with `onNext` immediately upon subscription, and after that whenever `onNext` is called on the subject.
3. Upon calling `onComplete` on the subject, it effectively turns into a ReplySubject with the last emitted event and the completion event. As in, any subscriber that subscribes to the subject after `onComplete` is invoked will immediately be invoked with `onNext(lastItem)` followed by `onComplete()`.
4. If `onComplete()` is called on the subject before an initial/first item is set/emitted, an error is thrown.

Do something like this exist in RxJava? Cause I couldn't find it, and had to create it on my own. And if not, shouldn't this be a thing? It's sort of a computation that emits intermediate values, until when it's done, after that point it only emits the end-result again and again.

**Comment by akarnokd** [comment]
You can compose this from existing behavior.

``` java
ReplaySubject.<T>create(1)
.switchIfEmpty(Observable.<T>error(new IllegalStateException("Subject is empty")));
```

**Comment by Alxandr** [comment]
Great. This seems to be working. I don't really like the `switchIfEmpty` solution, cause it does not actually throw on `onComplete()` call, but rather emits an error through the observable, but I can deal with that.
