### ISSUE TITLE
1.x: Feature Request Single#flatMapCompletable

### ISSUE THREAD

**Issue by vanniktech** [ReactiveX/RxJava#4216]
Would be nice to flatMap from Single to Completable unless there is any other way to do this right now. `flatMapObservable` already does exist.

Happy to hear thoughts on that from you guys.

**Comment by akarnokd** [comment]
PR welcome.

**Comment by vanniktech** [comment]
I'm curious how would you start implementing this?

**Comment by akarnokd** [comment]
Subscribe to the `Single` and in the `onSuccess`, call the mapper and subscribe to the returned `Completable`.

**Comment by akarnokd** [comment]
Closing via #4226.
