### ISSUE TITLE
complicated flow by using rxjava .

### ISSUE THREAD

**Issue by pinkApple** [ReactiveX/RxJava#4218]
for example:

> List<Group> 
> Group ---> List<Child>
> compose:
>  List<Pair<Group,List<Child>>>

   java implement should be like this:

> ```
>   List<Pair<Group,List<Child>>>  group_childs = new xxx;
>    List<Group>  group = findGroups();
>     for( group  ){
>            group= list.get()
>            List<Child> childs = findChilds(group);
>           group_childs .add(group,childs)
>    }`
> ```

  so , how to implement it by using rxjava?

**Comment by akarnokd** [comment]
It depends on which of the sources you want reactive: `findGroups()` and/or `findChilds()`?

1) None
You don't need RxJava and can go with plain looping.

2) `findGroups()` is an `Observable<Group>`

``` java
findGroups().map(g -> Pair.of(g, findChilds(g))).toList()...
```

3) `findChilds` is `Observable<Child>`

``` java
Observable.from(findGroups()).concatMap(g -> findChilds(g).toList().map(u -> Pair.of(g, u)))...
```

4) Both

``` java
findGroups().concatMap(g -> findChilds(g).toList().map(u -> Pair.of(g, u)))...
```

**Comment by pinkApple** [comment]
@akarnokd 
both findgroups and findchilds are db operation, 
since rxjava can do background tasks as well,
so i try them by async way. 
but this logic may be too hard for newer;
anyway, thank u;

**Comment by pinkApple** [comment]
```
    findGroups()
            .flatMap(Observable::from)
            .flatMap(
                    g -> findChilds(g).map((List<Child> children)
                            -> Pair.create(g, children)))
            .toList()
            .subscribe(pairs -> {
                // adapter set List<Pair<Group, List<Child>>>
            });
```

i implement it!  nice.

**Comment by daschl** [comment]
@pinkApple in your case you probably want to use `forEach` instead of `subscribe`. On the other hand its considered bad practice to not implement an error handler on the subscriber like in your case, you'd just get an OnErrorNotImplementedException

**Comment by pinkApple** [comment]
@daschl  yeah,  you are right.
                forEach can do it as well.  i'm using rxjava just to test the data flow..
                onError , onComplete do not implement in code.
                 normally , i should use a subscriber.
