### ISSUE TITLE
CompositeObservable

### ISSUE THREAD

**Issue by thomasnield** [ReactiveX/RxJava#4235]
I am implementing a new utility called `CompositeObservable` in the [RxJavaFX](https://github.com/ReactiveX/RxJavaFX/issues/38) project. I wanted to throw it by you guys first to see if it might be appropriate for the RxJava library.

Essentially it is an `Observable#merge()` except you can add/remove Observables from it at any time, and this immediately affects all existing subscribers. @akarnokd helped [give me a start on SO](http://stackoverflow.com/questions/38493677/rxjava-merged-observable-that-accepts-more-observables-at-any-time/38498213#38498213) and after overcoming a few complications, I created an implementation that works exactly like I would expect. 

``` java
import javafx.collections.FXCollections;
import javafx.collections.ObservableList;
import rx.Observable;
import rx.observables.JavaFxObservable;

public final class CompositeObservable<T> {

    private final ObservableList<Observable<T>> sources;

    private final Observable<T> observable;

    public CompositeObservable(int cacheCount) {

        this.sources = FXCollections.synchronizedObservableList(FXCollections.<Observable<T>>observableArrayList());

        this.observable = JavaFxObservable.fromObservableList(sources)
                .switchMap (list -> Observable.from(list).flatMap(t -> t))
                .cacheWithInitialCapacity(cacheCount);

    }

    public Observable<T> toObservable() {
        return observable;
    }

    public void add(Observable<T> observable) {
        sources.add(observable);
    }
    public void remove(Observable<T> observable) {
        sources.remove(observable);
    }
}
```

This is a reliable implementation that completely avoids the use of Subjects. Unfortunately, it uses JavaFX's `ObservableList<T>` which can easily be hooked and turned into an `Observable<ObservableList<T>>` that emits the list every time it changes, but I doubt you guys want JavaFX types.

If you guys see value in this I can try to take a stab at a non-JavaFX implementation. If this is too niche or belongs in [RxJava-Extras](https://github.com/davidmoten/rxjava-extras) I'm fine with that. Just thought I'd offer it because I needed it really badly, and I imagine others doing UI development do too.

**Comment by thomasnield** [comment]
Just realized this implementation works best for compositing infinite hot Observables (e.g. UI events). For cold or finite Observables, it might make sense for them to remove themselves from the list after they complete. Otherwise they could get re-subscribed if they sit there.

**Comment by akarnokd** [comment]
Such source-like Observables can live in any library, not necessarily in RxJava.

**Comment by thomasnield** [comment]
I already ran with it in my library, so that's cool. I'll go ahead and close.
