### ISSUE TITLE
1.x: RxSchedulerPurge always take periodic cpu load even in the background on Android5.0- 

### ISSUE THREAD

**Issue by xihua** [ReactiveX/RxJava#4240]
![image](https://cloud.githubusercontent.com/assets/2015563/17095720/901409a8-5288-11e6-92c9-501173276778.png)

I use RxJava 1.0.14 in my app. 
When i analysis TraceView , there is a ScheduledExecutorService **RxSchedulerPurge** calls purge **at interval of 1000ms**. 
I think it's unacceptable on mobile device and this drains the battery. 
Is it necessary ??

**Comment by akarnokd** [comment]
It is required to free up delayed but cancelled tasks on Android runtimes that don't support Java 7-like threadpools. You can adjust the purge period via `rx.scheduler.jdk6.purge-frequency-millis` system parameter. Also you may want to upgrade to a more recent version of RxJava.

**Comment by xihua** [comment]
@akarnokd ok i see. 
Should i set 'purge-frequency-millis' pretty long like 60s on mobile device？
Thanks u

**Comment by akarnokd** [comment]
It's up to you really. If your app doesn't frequently schedule delayed tasks and then cancels them, you can set the parameter higher. If you have further input on the issue, don't hesitate to reopen this issue or post a new one.
