### ISSUE TITLE
Question about SyncOnSubscribe / SubscriptionProducer

### ISSUE THREAD

**Issue by vanniktech** [ReactiveX/RxJava#4247]
Was diving into those two guys and noticed that in the `SubscriptionProducer#onNext` `actualSubscriber.onNext(value);` is called without checking `isUnsubscribed`. Is this wanted behavior and if so could you explain why?

**Comment by akarnokd** [comment]
There is a `tryUnsubscribe` after an iteration.

**Comment by vanniktech** [comment]
Alright thanks a lot 👍
