### ISSUE TITLE
OperatorDoEach could do with some work

### ISSUE THREAD

**Issue by davidmoten** [ReactiveX/RxJava#4260]
While looking for emissions after terminal events I was looking at `OperatorDoEach` which is called by `doOnNext`, `doOnError`, `doOnCompleted`, and `doOnEach` of course. I noticed these things:
- lots of wasted allocations per call (use of `ActionSubscriber` when all that is needed is an `ActionObserver`) and passing three actions to `OperatorDoEach` when for three of the four operators we only need one action.
- it doesn't call `RxJavaHooks.error` for secondary error emissions from upstream
- it does call `Exceptions.throwIfFatal` for all error emissions (do we want to do this generally? I haven't seen it much outside error catching on externally supplied functions or actions)

I'd quite like to see `doOnNext` and `doOnError` in particular more efficient because I use them a lot. Should I create dedicated Operator/OnSubscribe classes for the single action operators or perhaps one shared one that has an extra parameter (to indicate what notification type is being used)?

**Comment by akarnokd** [comment]
You may optimize it into an OnSubscribe. I'm not sure about splitting as it triples the method count for the sake of saving 16 bytes.

**Comment by davidmoten** [comment]
I could also use `ActionObserver` instead of `ActionSubscriber` I suppose (saves 32 bytes). Let me know what you think of the `throwIfFatal` issue and I'll do it.

**Comment by akarnokd** [comment]
The `throwIfFatal` shouldn't be there; the operators should not call onError with a fatal exceptions anymore but throw them immediately - this should be also reviewed and fixed in 2.x as well.

**Comment by akarnokd** [comment]
FYI, I follow [this](https://gist.github.com/akarnokd/693866d6b4453ca8c66b866584163e5e) list when I port tests.

**Comment by akarnokd** [comment]
Closing via #4262.
