### ISSUE TITLE
Observable.sort method

### ISSUE THREAD

**Issue by davidmoten** [ReactiveX/RxJava#4263]
I'd like to add `Observable.sort` (or `Observable.sorted`) to the API. I tried this a couple of years ago and it was knocked back but now that people are getting used to the offerings of java 8 streams for instance (and its `.sorted()` method) I thought I'd raise it again.

In particular to sort a stream at the moment  I have to call 

`observable.toSortedList().flatMapIterable(x -> x)`

or using an internal class:

`observable.toSortedList().flatMapIterable(UtilityFunctions.<T>identity())`

This is poor for discoverability, hard to read, and pretty disappointing when I want to show off RxJava's coolness.

Any takers?

**Comment by SherifMakhlouf** [comment]
@davidmoten would you forward the calls to corresponding toSortedList() like your example: 
`observable.toSortedList().flatMapIterable(UtilityFunctions.<T>identity())`  ?
I'm curious if you would implement it differently

**Comment by davidmoten** [comment]
@SherifMakhlouf yes I'd forward the call because I think there are enough operators to support as is.

**Comment by davidmoten** [comment]
@SherifMakhlouf happy for you to run with PR. I was looking for support from committers before making one.

**Comment by SherifMakhlouf** [comment]
@davidmoten Thanks ! glad to support !

**Comment by abersnaze** [comment]
We may want to consider `Observable<T> mergeSorted(Observable<Observable<T> sortedObservables, Func2<T, T, Integer> sortFunction)` that takes a two or more already sorted observables and produces a new sorted observable with the results merged. It would work kind of like zip where is would wait for at least one onNext from each inner `Observable<T>` and only emit the smallest `T`.

**Comment by davidmoten** [comment]
@abersnaze yep I use that functionality and there is an operator for that [`orderedMergeWith`](https://github.com/davidmoten/rxjava-extras#transformersorderedmergewith) in _rxjava-extras_. It was written by @akarnokd.

**Comment by akarnokd** [comment]
Closing via #4264.
