### ISSUE TITLE
1.x: Should TestSubscriber.assertValues() check that subscription has happened?

### ISSUE THREAD

**Issue by artem-zinnatullin** [ReactiveX/RxJava#4271]
Found false positive test in our codebase where we were checking `TestSubscriber.assertNoValues()` but it was not subscribed at that point and test passed though it shouldn't…

Should we fail-fast in that case and throw `AssertionError` if subscriber was not subscribed before call to `assertNoValues()`?

Basically:

``` java
class TestSubscriber extends Subscriber {

  private int startCounter = 0;

  @Override public void onStart() {
    startCounter++;
  }

  public void assertNoValues() {
    if (startCounter == 0) {
      throw new AssertionError("TestSubscriber was not subscribed before!");
    }
  }
}
```

**Comment by akarnokd** [comment]
Adding a `startCounter` is okay but I'm not convinced the existing assert values should be changed but rather add `assertStarted()`. Also you should call `fail` so it prints the status info and add `assertBackpressure()` to verify `setProducer` was called too.

**Comment by artem-zinnatullin** [comment]
Ok, mostly sounds good to me, except that original problem of `assertNoValues()` won't be solved without adding `assertStarted()` which is not great because basically I don't see cases when you'll need `assertNoValues()` without `assertStarted()`. Maybe reconsider?

Other than that I can take this one to implement.

**Comment by akarnokd** [comment]
What's the underlying issue? Are you forgetting to subscribe in your tests? Do you test operators that don't respond often that the asserts don't give you proper feedback?

**Comment by artem-zinnatullin** [comment]
Something like this:

``` java
Observable<Data> stream = streamUnderTest();
TestSubscriber<Data> subscriber = new TestSubscriber<>();

// Forgot to subscribe it.

@Test
public void streamShouldHasNoDefaultValue() {
  subscriber.assertNoValues();
}
```

And when I came to add more tests for this stream of data I've found that subscriber was never subscribed and existing test was false positive. I understand that it's rare case because usually you will have other tests that will use same pair of stream and subscriber and fail without subscription, but anyway seems that `assertNoValues()` should always implicitly include `assertStarted()`.

**Comment by akarnokd** [comment]
I don't think such programmer errors should be addressed by RxJava. Next time, you forget to call any assert methods and get a false positive, then you want RxJava to assert by just creating TestSubscriber or something - sorry if I put it so bluntly.
