### ISSUE TITLE
2.x: proposition - define our functional interfaces with throws Exception

### ISSUE THREAD

**Issue by akarnokd** [ReactiveX/RxJava#4272]
Since RxJava 2.x aims at Java 6 and we have to roll our own functional interfaces, it gives the opportunity to define them in a way that allows user code to throw checked exceptions:

``` java
interface Function<T, R> {
    R apply(T t) throws Exception;
}
```

This may save some annoyance with operators whose functions may contain throwing code and avoid the need to try-catch and wrap the checked exceptions into unchecked exceptions.

My proposition is to add `throws Exception` to these interfaces (and not some generic `E extends Exception` to avoid drastic signature changes) plus remove `Supplier` in favor of `Callable` which already throws. The operators themselves already do try-catch around function invocations (and if don't this will highlight them nicely) should not affect them.

**Comment by artem-zinnatullin** [comment]
On first sight 👍 

Also it'll help at compile time to not forget to handle exceptions in Operators that accept such functions from user.

**Comment by abersnaze** [comment]
It's been proposed before and rejected 😞 #1305

**Comment by akarnokd** [comment]
@abersnaze This is for 2.x where everything is new and/or binary incompatible already and there won't be 2 sets of interfaces (Function, CheckedFunction) but only a single set of interfaces. It has the added benefit of not needing a wrapper (thus allocation) every time and feel fluent. I'm always a bit sad when I have to demo `using` or `SyncOnSubscribe` and have to omit the try-catches for simplicity. Now it becomes totally fine and compiles:

``` java
Flowable.using(
   () -> new FileInputStream(), // throws IOException, totally fine now
   in -> {
       byte[] bytes = new byte[1024];
       in.read(bytes); // can throw IOException
       return Flowable.just(bytes);
   },
   in -> in.close()  // this also throws IOException
);
```

**Comment by davidmoten** [comment]
:+1: I'm keen to see that in. I've missed it many times since your proposal @abersnaze!

**Comment by akarnokd** [comment]
See #4278.

**Comment by akarnokd** [comment]
Closing via #4278; works out so far.
