### ISSUE TITLE
subscribe is only executed the first time

### ISSUE THREAD

**Issue by cristianhoyos66-zz** [ReactiveX/RxJava#4275]
I don't know if I'm doing bad, but this is which I have:

```
 String[] test = {"aaa", "ddddd"};
  private void methodTest() {

    Observable.from(test)
        .subscribe(new Action1<String>() {
          @Override
          public void call(String s) {
            System.out.println(s);
          }
        });
    final Runnable runnable = new Runnable() {
      @Override
      public void run() {
        System.out.println("I work");
        test[test.length-1] = "fff";
        for (int i = 0; i < test.length; i++) {
          System.out.println(test[i]);
        }
      }
    };
    final Handler handler  = new Handler();
    handler.postDelayed(runnable, 5000);
  }
```

and when I execute that function I get this result: 

```
aaa
ddddd
I work
aaa
fff
```

and for this `test[test.length-1] = "fff";` I think that my expected result would be: 

```
aaa
ddddd
I work
aaa
fff
aaa
fff
```

**Comment by LalitMaganti** [comment]
I think there's a fundamental misunderstanding of how Observables work. Changing the array does not in any way notify the subscriber that the array has changed. All you are doing is changing the data inside the array. The subscriber has no link to the array after the initial subscription (which actually terminates through onComplete after the initial printing of "aaa" and "ddddd").

I'm not sure what exactly the context for this code so I'm not sure what the best way to structure your code is. I would suggest revisiting http://reactivex.io/ so you're clear on how Observables work.

**Comment by cristianhoyos66-zz** [comment]
In this example I'm trying to do something that notify when array changes and I don't know the better way to do that. I don't think that after this `test[test.length-1] = "fff"` should do this again 

```
Observable.from(test)
     .subscribe(new Action1<String>() {
       @Override
       public void call(String s) {
         System.out.println(s);
       }
     });
```

or yes?

**Comment by LalitMaganti** [comment]
Well if you want to notify of the array being changed, you can make an Observable<String[]> and then emit your new array once you've modified it. You would need to use a PublishSubject/BehaviorSubject if you want to use your example ad lib though.

**Comment by cristianhoyos66-zz** [comment]
I studied both options, and both worked for me. Thank you :)
