### ISSUE TITLE
1.x: Feature Request Observable.firstOrDefaultSingle

### ISSUE THREAD

**Issue by vanniktech** [ReactiveX/RxJava#4277]
How do you guys feel about an overload that is named something along the lines of `Observable.firstOrDefaultSingle` and basically does the same as `Observable.firstOrDefault` with the difference of returning a `Single<T>` instead of `Observable<T>`?

Edit: Could also maybe be called `firstOrDefaultAsSingle`

**Comment by akarnokd** [comment]
What's wrong with `firstOrDefault().toSingle()` ?

**Comment by JakeWharton** [comment]
Or `switchIfEmpty().toSingle()` for async defaults.

**Comment by vanniktech** [comment]
Nothing is wrong with that, I'm right now using `firstOrDefault().toSingle()`.

**Comment by JakeWharton** [comment]
I don't like that it conflates two concepts: taking the empty stream and ensuring it's non-empty but also transforming the type from Observable to Single.

**Comment by vanniktech** [comment]
Closing since if this type of suggestion would be approved (basically transforming Observable in any way into one that only emits one item and then converts itself into Single a lot of other operators would need to get the `asSingle` matching method e.g. first(), `last()`, `lastOrDefault()` for consistency
