### ISSUE TITLE
2.x: Exceptions is in internal package

### ISSUE THREAD

**Issue by JakeWharton** [ReactiveX/RxJava#4280]
...despite its tests being in the public API package.

It's hard to write libraries without `Exceptions.throwIfFatal`. Should this be in the public API?

**Comment by akarnokd** [comment]
Possibly, what should happen with the rest of the methods?

If you'd review #4278 that would allow the refactoring to happen without interference.

**Comment by JakeWharton** [comment]
I would think they'd split, although having two classes of the same name would obviously be less than ideal. Maybe it could be hoisted onto RxJavaPlugins since its often used with calling `RxJavaPlugins.onError`? There could even be a combination method that does both, since there's a few hundred uses of the pair throughout RxJava's codebase as-is.

**Comment by JakeWharton** [comment]
This can be closed! 🎉

**Comment by JakeWharton** [comment]
Oh wait it's my issue, I can do that!
