### ISSUE TITLE
2.x: Add fromAsync Observable factory

### ISSUE THREAD

**Issue by JakeWharton** [ReactiveX/RxJava#4286]
but potentially with a different name based on what the resolution of #4255 is.

**Comment by JakeWharton** [comment]
And bonus: no backpressure strategy argument needed!

**Comment by JakeWharton** [comment]
I would also argue for the deletion of `Flowable.fromAsync` since it's just `Observable.fromAsync(...).toFlowable(strategy)` which isn't much longer than `Flowable.fromAsync(..., strategy)`. Plus visitor/callback-based APIs are unlikely to have built-in backpressure so it makes sense to wrap them as a backpressure-free type and then apply a strategy.

**Comment by akarnokd** [comment]
:+1:

**Comment by JakeWharton** [comment]
I'll try to give this a go tomorrow. I'm afraid I've sent too many PRs already and the statistical likelihood of conflicts is approaching 100%.

**Comment by JakeWharton** [comment]
I have an alternate proposal:
- Remove `Flowable.fromAsync` + `AsyncEmitter`
- Rename `Observable.create` to `Observable.unsafeCreate`
- Add `Observable.create` which wraps the incoming `Observer` in one which checks for cancelation (similar to what `BaseAsyncEmitter` is doing now).

This has a few advantages:
- It makes `Observable.create(ObservableSource)` actually usable by "normal" users! No more traps to fall in!
- It still allows fully-compliant `ObservableSource` implementations via `unsafeCreate` (or subclassing).
- It re-uses the same interface types and names we already have without needing new ones.
- It re-uses the existing `onBackpressure*` methods for adding backpressure to created observables.

And disadvantages:
- It removes the ability to do proper backpressure-aware implementations easily. But perhaps something similar to `AsyncOnSubscribe` could be brought along for handling requests and then using this new, safer `Observable.create` for its return values.

**Comment by JakeWharton** [comment]
In terms of the last disadvantage, `Flowable.create` could be renamed to `Flowable.unsafeCreate` and `Flowable.create(BatchPublisher)` could be added where `BatchPublisher` is something like a pared down `AsyncOnSubscribe`.

**Comment by JakeWharton** [comment]
This happened!
