### ISSUE TITLE
1.x : the way to test that there is no output.

### ISSUE THREAD

**Issue by imcharsi** [ReactiveX/RxJava#4320]
Hi

At first, My English is not good. forgive me.

I have a question.

Below is [RxScala](https://github.com/ReactiveX/RxScala) code but there should not be any problem about this question.

``` scala
val subscriber = TestSubscriber[Int]
val subjectA = BehaviorSuject[Int](1)
subjectA.filter(_ > 1).subscribe(subscriber)
subscriber.assertNoValues()
subjectA.onNext(1)
subscriber.assertNoValues()
subjectA.onNext(2)
subscriber.assertValue(2)
// subscriber.virtualMethodThatClearInnerValues()
subjectA.onNext(1)
subscriber.assertNoValues() // failed
subscriber.assertValues(2) // passed
```

My question is "How can I test that there is no output?".

Currently, last assertion is passed with `subscriber.assertValue(2)` but not `subscriber.assertNoValues()`.

Do you have any idea?

Thanks for reading.

**Comment by artem-zinnatullin** [comment]
assertValues() asserts not the number of values, but values themselves, in
your case assertValues(2) passes because subscriber actually received value
== 2.

See assertValueCount(), in your case it'll be assertValueCount(1).

**Comment by imcharsi** [comment]
Hi

Thanks for reply.

I'm afraid that my key point is not told exactly.

``` scala
val subscriber = TestSubscriber[Int]
val subjectA = BehaviorSuject[Int](1)
subjectA.filter(_ > 1).subscribe(subscriber)
subscriber.assertNoValues()
subjectA.onNext(1)
subscriber.assertNoValues()
subjectA.onNext(2)
subscriber.assertValue(2)
subjectA.onNext(1)
subscriber.assertNoValues()
```

As above, if there are some input that greater than `1`, then there is some output.
if not, then there is no output.
What I want to do is that test whether there is no output for `subjectA.onNext(1)` or not.

Currently, `TestSubscriber` remembers last output. So, if there is no output, last output is preserved but not cleared.
So, in above code, some output(in this case `2`) is remaining in `TestSubscriber` even though last input(in this case `subjectA.onNext(1)`) does not make any output.

Of course, I understand that initialy design intention for `assertValue`/`assertValueCount` is not for this case.

So, my suggestion is that if there are `whateverThatClearInnerValues()` that clear inner state, it would be something helpful.

If so, usage will be like below

``` scala
val subscriber = TestSubscriber[Int]
val subjectA = BehaviorSuject[Int](1)
subjectA.filter(_ > 1).subscribe(subscriber)
subscriber.assertNoValues()
subjectA.onNext(1)
subscriber.assertNoValues()
subjectA.onNext(2)
subscriber.assertValue(2)
subscriber.whateverThatClearInnerValues() // here!!!
subjectA.onNext(1)
subscriber.assertNoValues()
```

Thanks for reading.

**Comment by artem-zinnatullin** [comment]
Ok I see.

Yeah, current design of `TestSubscriber` is accumulative, it only records state. We're currently writing all tests with Kotlin's Spek and found this behavior inconvenient for deep tests hierarchy.

@akarnokd, can we add such `clear()` method to reset state of the `TestSubscriber`? 

Internally I was thinking about `TestSubscriber.branch()` that would return new `TestSubscriber` and proxy all **new** state to it so you could use both old and new if needed.

**Comment by akarnokd** [comment]
See #4322.

**Comment by imcharsi** [comment]
Thanks everybody.

Have a nice day :)

**Comment by akarnokd** [comment]
Closing via #4322
