### ISSUE TITLE
Concat<Iterable<Observable>>

### ISSUE THREAD

**Issue by PaulWoitaschek** [ReactiveX/RxJava#4329]
Is there a reason that there is `Observable.merge(Iterable<Observable>)` but not `Observable.concat(Iterable<Observable>)`?

If I understand correctly it could work similarly as
`concat(from(iterable));`

**Comment by akarnokd** [comment]
Can't remember. People just kept writing `concat(from(iterable))`.

**Comment by PaulWoitaschek** [comment]
Working on it ;-)

**Comment by akarnokd** [comment]
Closing via #4330.
