### ISSUE TITLE
RxJavaHooks.onError() catches all Throwables (not just undeliverable ones)

### ISSUE THREAD

**Issue by dlew** [ReactiveX/RxJava#4332]
The `RxJavaHooks.onError()` documentation says:

> Consume undeliverable Throwables (acts as a global catch).

However, it consumes deliverable `Throwables` just as much. For example, `SafeSubscriber._onError()` immediately calls it ([source](https://github.com/ReactiveX/RxJava/blob/1.x/src/main/java/rx/observers/SafeSubscriber.java#L150)) whether there's an onError set for the subscriber or not.

Either the documentation is wrong (and it should say it consumes _all_ `Throwables`) or the behavior is wrong.

**Comment by akarnokd** [comment]
The behavior of `SafeSubscriber` is wrong but many rely on this property already.

**Comment by dlew** [comment]
Would it make sense to have a second hook that is _really_ just for undelivered `Throwables`? That would be handy.

**Comment by akarnokd** [comment]
Maybe `SafeSubscriber` could call `RxJavaPlugins...handleError()` again, skipping `RxJavaHooks` entirely.

**Comment by dlew** [comment]
That would work for me - want a PR?

**Comment by akarnokd** [comment]
Sure.

**Comment by akarnokd** [comment]
See #4641

**Comment by akarnokd** [comment]
Closing via #4641
