### ISSUE TITLE
Difficulty propagating exceptions through onError

### ISSUE THREAD

**Issue by dlew** [ReactiveX/RxJava#4334]
This is a problem I've had for a while and wanted to open it up for discussion...

RxJava is designed to handle exceptions in `onError`. However, when that exception is one that should just be propagated (and crash the entire app), things get hairy. Take this for example:

``` java
Observable.error(new IllegalArgumentException("The mistake."))
  .subscribeOn(Schedulers.io())
  .subscribe(__ -> {}, ex -> { Exceptions.propagate(ex); });
```

A summary of the resulting stack trace:
1. `IllegalStateException`: Fatal Exception thrown on Scheduler.Worker thread.
2. `OnErrorFailedException`: Error occurred when trying to propagate error to Observer.onError
3. `CompositeException`, except there's only ONE exception with in it!
4. Inside of that `CompositeException`, the actual `IllegalArgumentException` I was trying to propagate.

This stack trace is difficult to work with for a few reasons:
1. It hides the actual exception deep down the stack trace.
2. The unnecessary `CompositeException` masks the actual exception from analysis.
3. The wrappers confuse crash loggers into thinking that multiple different exceptions all have the same root cause.

I was wondering if anyone has ever looked into a better way to handle this situation, such that you can end up with a stack trace that is just the original exception.

**Comment by vanniktech** [comment]
Not part of the discussion but instead of `__ -> {}` you could use `Actions.empty()`

**Comment by akarnokd** [comment]
The 1) and 2) wrappers are indicator exceptions but I guess you could replace their stacktrace with the stacktrace of the original exception + have a composited message like `OnErrorFailedException: IllegalArgumentException - blah`. Still the exception class wouldn't be your exception's.

3) could be because the original exception coming into the callback was not added to the composite, would be great if you could pinpoint that in the code.

**Comment by dlew** [comment]
Would it be possible to skip the indicator exceptions entirely? Maybe in the spirit of `RxJavaHooks`, there could be a hook for when exceptions are thrown inside of `onError` (or other unexpected locations) that lets you handle it in a non-wrapped way.

**Comment by akarnokd** [comment]
Maybe, but the changes may get quite ugly.

**Comment by dlew** [comment]
What if it were, instead of a hook, just a toggle that lets you turn off indicator exceptions?

**Comment by akarnokd** [comment]
I don't have the time to experiment with this so I encourage you to post a PR and see what it takes.

**Comment by akarnokd** [comment]
I'm closing this for now; not sure if we want to put in the effort into 1.x.

**Comment by tir38** [comment]
I had this same issue too (but in RxJava2). My solution was to:

1. "propagate" instead of "rethrowing" (Thanks @dlew for introducing me to that one) otherwise you'll get a CompositeException with 2 causes.

```
Observable.just("abc")
        .map(string -> {
            throw new RuntimeException("string stream failed");
        })
        .subscribe(
                o -> {
                    // no op
                },
                throwable -> {
                    // throw new RuntimeException("Error observing strings", throwable);
                    // instead of throwing, just propagate
                    Exceptions.propagate(throwable);
                });
```
2.  Check for only one cause and unfurl:

```
RxJavaPlugins.setErrorHandler(error -> {
    if (error instanceof CompositeException
            && ((CompositeException) error).getExceptions().size() == 1) {
        // unfurl and add just the cause
        sendToCrashReporting((CompositeException) error).getExceptions().get(0));
    } else {
        sendToCrashReporting(error);
    }
});
```

3. if I actually need the app to crash (for early bug detection) I just propagate *again* in global RxJava error handler:

```
RxJavaPlugins.setErrorHandler(error -> {
    // throw inside global RxHandler to leave the RX world and have our app crash
    if (error instanceof CompositeException
            && ((CompositeException) error).getExceptions().size() == 1) {
        // unfurl and add just the cause
        Exceptions.propagate(((CompositeException) error).getExceptions().get(0));
    } else {
        Exceptions.propagate(error);
    }
});
```

https://gist.github.com/tir38/59374738cec898138f01e8299a9e83aa
