### ISSUE TITLE
Single.create correct usage question

### ISSUE THREAD

**Issue by vanniktech** [ReactiveX/RxJava#4335]
I've got a question whether I use the Single.create function correctly or not in this case since there's been some debate about the correct use of Observable.create. Basically I want to wrap an API call and return the value that I got from a Callback.

``` java
return Single.create(singleSubscriber -> myApi.getSomething(new Callback() {
    @Override
    public void onComplete(final String string) {
        if (string != null) {
            if (!singleSubscriber.isUnsubscribed()) {
                singleSubscriber.onSuccess(string);
            }
        } else if (!singleSubscriber.isUnsubscribed()) {
            singleSubscriber.onError(new SomeException());
        }
    }
}));
```

**Comment by akarnokd** [comment]
If there is no way to cancel the API call then yes. You don't have to worry about backpressure, only unsubscription happening while waiting for the value and making sure you only call one of the onXXX methods.

**Comment by vanniktech** [comment]
Let's say there would be a way to cancel the API call, what would I need to change?

**Comment by JakeWharton** [comment]
Add a subscription to the subscriber which will provide a callback that you can use to cancel.

**Comment by artem-zinnatullin** [comment]
To react on unsubscription use: Subscriber.add(), like this
`subscriber.add(Subscriptions.create(() -> request.cancel())`

**Comment by vanniktech** [comment]
Alright cool. Thanks guys 👍
