### ISSUE TITLE
2.x: Move 2-9 argument operators into separate classes

### ISSUE THREAD

**Issue by akarnokd** [ReactiveX/RxJava#4340]
The `Flowable` (and `Observable`) types are quite bloated with operators that take 2-9 arguments (such as `concat`, `merge`, `zip`, etc.).

Since these are sources, they can live in a separate class (or even a library) they could be moved outside of the base reactive types into utility classes:

``` java
Concat.of(s1, s2, s3).map().observeOn()...
Zip.of(p1, p2, (a, b) -> a + b)...
```

Pros:
- smaller base reactive classes
- can have more than 9 parameters
- can support more parametrization beyond the 2-9 arguments
- Unused classes can be removed by ProGuard (?)

Cons:
- loss of some convenience
- discoverability
- How to support all base reactive types: same class, different classes (prefixed?)

Thoughts?

**Comment by artem-zinnatullin** [comment]
Sorry, but I vote for convenience and discoverability -> for keeping
overloads.

For source code readability we can move all overloads to the bottom of the
file with some huge divider comment.

**Comment by artem-zinnatullin** [comment]
Regarding ProGuard — it already removes unused methods and classes, so it's
not an issue

**Comment by zsxwing** [comment]
I'm curious if anyone really uses 4-9 arguments overloads.

I suggest that keeping 2-9 arguments for `just` and remove 4-9 arguments for most operators (except `zip` that has a function argument). The only disadvantage for removing them is people just need to call `just` methods manually (`concat(just(o1, o2, o3, ...))`). The cons of keeping them are
- More methods in the base classes. Note: We need to maintain both codes and javadoc.
- IDE displays many overloads when typing an operator. See the example here: https://github.com/ReactiveX/RxJava/issues/686#issue-24736439

**Comment by akarnokd** [comment]
See #4413.

**Comment by akarnokd** [comment]
Closing via #4413.
