### ISSUE TITLE
filter + map in a single operator

### ISSUE THREAD

**Issue by aballano** [ReactiveX/RxJava#4341]
Hello there!

I've seen several times (specially when working with Buses or generic events) this kind of method chain:

`observable.filter(clazz::isInstance).map(clazz::cast)`

Would make sense to have another operator that does this already? Something like a `filterClass` or similar?

If so I could gladly create a PR with all the needed changes.

Cheers!

**Comment by artem-zinnatullin** [comment]
There is already operator for your case: ofType().

**Comment by aballano** [comment]
Ouch, I must be blind, thank you Artem!

**Comment by davidmoten** [comment]
This has come up before and i always forget it exists.  For discoverability
purposes I'd support the addition of an alias method (preferably beginning
with filter).
