### ISSUE TITLE
Help! With retrofit, first call subscribe takes a long time 

### ISSUE THREAD

**Issue by CodingPapi** [ReactiveX/RxJava#4347]
I'm using kotlin, below is my test code 

RestApi

```
class RestApi {
    var weatherApi: WeatherApi
    init {
        val logIntercepter = HttpLoggingInterceptor()
        logIntercepter.level = HttpLoggingInterceptor.Level.BODY
        val okclient = OkHttpClient.Builder()
                .addInterceptor(logIntercepter)
                .retryOnConnectionFailure(true)
                .connectTimeout(15, TimeUnit.SECONDS)
                .build()
        val retrofit = Retrofit.Builder()
                .baseUrl(WeatherApi.HOST)
                .addConverterFactory(JacksonConverterFactory.create(ObjectMapper().registerModule(KotlinModule())))
                .addCallAdapterFactory(RxJavaCallAdapterFactory.create())
                .client(okclient)
                .build()

        weatherApi = retrofit.create(WeatherApi::class.java)
    }
}

interface WeatherApi {
    companion object {
        val HOST = "https://api.heweather.com/x3/"
        val KEY = "41054a8f1d1a4ac992b1683e47a50146" //TestKey
    }

    @GET("weather")
    fun getWeather(@Query("city") city: String, @Query("key") key: String) : Observable<Weather>

}
```

Fire code

```
            val start = System.currentTimeMillis()
            Log.d("kkk","touch start")
            restApi.getWeatherData("Qingdao", WeatherApi.KEY)
                    .subscribeOn(Schedulers.io())
                    .observeOn(AndroidSchedulers.mainThread())
                    .subscribe { t -> helloText?.text = t.data.first().basic.city }

            val end = System.currentTimeMillis()
            Log.d("kkk", "cost time :" + (end - start))
            Log.d("kkk","touch end")
```

**when first call fire code , it cost 3369ms!** I have used  .subscribeOn(Schedulers.io()) and it works, but why it cost 3369ms in main thread?

```
08-13 11:02:31.906 30606-30606/com.supermario.enjoy.simpleweather D/kkk: touch start
08-13 11:02:35.276 30606-30606/com.supermario.enjoy.simpleweather D/kkk: cost time :3369
08-13 11:02:35.276 30606-30606/com.supermario.enjoy.simpleweather D/kkk: touch end
```

after first call fire code ,just cost 1ms

```
08-13 11:02:47.438 30606-30606/com.supermario.enjoy.simpleweather D/kkk: touch start
08-13 11:02:47.439 30606-30606/com.supermario.enjoy.simpleweather D/kkk: cost time :1
08-13 11:02:47.439 30606-30606/com.supermario.enjoy.simpleweather D/kkk: touch end
```

> **Is this buggy or I did something wrong?**

**Comment by CodingPapi** [comment]
It seems like jackson module convertor doing costly reflection in main thread
Is there any way to avoid this?
![screenshot](https://cloud.githubusercontent.com/assets/13818981/17641372/85a649ec-614f-11e6-98e1-7847bfbb9dce.jpg)

**Comment by artem-zinnatullin** [comment]
Hey, @CodingPapi!

Unfortunately, RxJava issue tracker is not a great place to get answer about Retrofit and Jackson, I would suggest to go on stackoverflow and ask there.

Fast suggestion: try to make `Retrofit` lazy, so that it would be initialized on the worker thread (in your case `Schedulers.io()` because of `subscribeOn(io())`):

``` kotlin
class RestApi {

  val weatherApi by lazy { Retrofit.Builder()…build() } // Here is the trick.

  // Weather api will be created on subscribeOn() scheduler -> off main thread.
  fun weatherData(params: Params): Observable<Weather> = Observable
    .fromCallable { weatherApi.get() } // And here is the trick.
    .flatMap { it.weatherData(params) }
}
```

**Comment by CodingPapi** [comment]
@artem-zinnatullin Thanks for ur apply, I will close this issue

**Comment by gaara87** [comment]
@CodingPapi if http://stackoverflow.com/questions/41385648/retrofit2-deserialization-conversion-on-non-main-thread-using-rxjava sounds very similar to your issue, please let me know, i can provide a temporary solution

**Comment by iNoles** [comment]
There is like
```java
.addCallAdapterFactory(RxJavaCallAdapterFactory.createWithScheduler(Schedulers.io()))
```
it automatically set Schedulers.io() to all retrofit requests.

**Comment by gaara87** [comment]
That is my existing configuration, that does not assure deserialization on io() thread.

**Comment by JakeWharton** [comment]
Yes it does.

**Comment by gaara87** [comment]
Calling
    
    Observable<SearchResponse> searchObservable=retrofitService.search(searchData);
    searchObservable.subscribeOn(Schedulers.io())
                    .observeOn(AndroidSchedulers.mainThread())
                    .subscribe(response -> {...});

with the following configuration 

    .addCallAdapterFactory(RxJavaCallAdapterFactory.createWithScheduler(Schedulers.io()))
    .addConverterFactory(JacksonConverterFactory.create(ObjectMapperFactory.getObjectMapper()))

with a breakpoint in `responseBodyConverter` in the JacksonConverterFactory, when it breaks, it can be seen that it happens on the main thread.

**Comment by CodingPapi** [comment]
I just changed retrofit return type from Observable to Call

**From**
@GET("weather")
    fun getWeather(@Query("city") city: String, @Query("key") key: String) :  **Observable** <Weather>


**TO**


@GET("weather")
    fun getWeather(@Query("city") city: String, @Query("key") key: String) : **Call** <Weather>

Then get Observable using fromCallable method:
Observable.fromCallable { **returnedCall**.execute().body() }

And this is ugly,  do u have any good idea about this?    @gaara87

**Comment by gaara87** [comment]
@CodingPapi I dont know if its better, but this works for me

    Observable<SearchResponse> searchObservable = Observable.just(retrofitService).observeOn(Schedulers.io())
                                 .flatMap(service->service.search(searchData));

Also, maybe its better to run this conversation in a retrofit issue for people to become aware in that.

@JakeWharton it always seems to do the conversion on the thread in which the observable was created. Is that expected?
