### ISSUE TITLE
setCancellation for Single and Completable 

### ISSUE THREAD

**Issue by AntonHolovin** [ReactiveX/RxJava#4356]
We can use `setCancellation` for the `AsyncEmitter` that we have inside `Observable.fromAsync` method. It's very useful because we are able to release something in the case when the subscription was terminated. For example: 

``` Java
Observable.fromAsync(emitter -> {
    SomeProtocolClient client = new SomeProtocolClient(getUri());

    Callback callback = new Callback() {
        @Override
        public void onLoad(Response response) {
            Model model = parse(response);

            emitter.onNext(model);
            emitter.onCompleted();
        }

        @Override
        public void onError() {
            emitter.onError(new ApiException("No response"));
        }
    };

    Request request = client.get(callback);
    emitter.setCancellation(request::cancel); // release some resources, it's useful to have setCalcellation
}, AsyncEmitter.BackpressureMode.BUFFER);
```

Wouldn't it be nice to have something like that for the `Single` and `Completable`?

**Comment by akarnokd** [comment]
Sounds good.

**Comment by artem-zinnatullin** [comment]
There is already such API:

``` java
Single.create(subscriber -> {
  subscriber.add(Subscriptions.create(request::cancel))
})
```

Same for `Consumable`.  Not sure if we should add `fromAsync` to `Completable` and `Single` in 1.x since in 2.x it'll be `create()`

**Comment by akarnokd** [comment]
A small drawback with the `SingleSubscriber.add` approach is that you need try-catch if `request::cancel` throws checked exception.

Completable doesn't support such resource management so you'd need to manually use `MultipleAssignmentSubscription` or other containers before calling `onSubscribe`.

Besides, we will (have to) provide a safe `create` in 2.x with similar API for all base reactive types.

**Comment by artem-zinnatullin** [comment]
// Damn, why we didn't do it for `Completable`?!

Ok, 👍 for adding `fromAsync` to both `Completable` and `Single` in 1.x, I can work on that if you don't mind

**Comment by akarnokd** [comment]
Go ahead, I'll do 2.x anyway within a few days.

**Comment by JakeWharton** [comment]
Why not just call `.toSingle()` or `.toCompletable()` on the `Observable.fromAsync`?

**Comment by akarnokd** [comment]
To indicate on the API level that you should call exactly one of `onSuccess(T)`, `onError()` or `onCompleted()` methods.

**Comment by JakeWharton** [comment]
I don't see how that's possible. `Single.OnSubscribe` doesn't prevent me from calling methods on the `SingleSubscriber` multiple times.

**Comment by akarnokd** [comment]
By having `SingleEmitter` and `CompletableEmitter` as input to you:

``` java
public static <T> Single<T> fromAsync(Action1<SingleEmitter<T>> emitter);

Single.fromAsync(e -> {
   e.setCancellable(() -> { });
   e.onSuccess(null);
   e.onSuccess(null); // will be dropped
});
```

> Single.OnSubscribe doesn't prevent me from calling methods on the SingleSubscriber multiple times.

Like all `create` operators, there are no safeguards with the raw access. Extending `fromAsync` (`create` in 2.x) to the other base reactive types give the necessary safeguards.

**Comment by JakeWharton** [comment]
That should throw an exception, not be silently ignored. You've violated the contract of the type.

**Comment by akarnokd** [comment]
See #4442. Should there be one for Single?

**Comment by PaulWoitaschek** [comment]
Agree. It's confusing that there is Observable.fromEmitter, Completable.fromEmitter but not Single.fromEmitter

**Comment by akarnokd** [comment]
See #4851

**Comment by akarnokd** [comment]
Closing via #4851 & #4442
