### ISSUE TITLE
2.x Design: Try+Optional vs Notification

### ISSUE THREAD

**Issue by akarnokd** [ReactiveX/RxJava#4365]
In 1.x we have the `Notification<T>` that can hold a value, error or completion.

When I started with 2.0, it was aimed at Java 8+ back then, thus I thought we could leverage Java 8's own `Optional` type plus a `Try<T>` to hold an error or an `Optional<T>`. Since now we aim at Java 6, the `Optional<T>` was manually ported back as well to retain the signatures of operators.

Uses: `materialize()`, `dematerialize()`; pacing out `onComplete()` with `retryWhen` and `repeatWhen`.

The drawback of `Try<Optional<T>>` is that for each normal value, it incurs 2 allocations whereas the 1.x notification required only 1 allocation. The completion signal in 1.x requires no allocation - 2.x requires 1 allocation (the `Try`).

Should we prefer less allocation and thus go back to (something like) `Notification<T>` or do we keep the Java 8 style?

**Comment by JakeWharton** [comment]
I much prefer the more semantic Notification type which maps into the Rx
domain better than Try+Optional.

**Comment by artem-zinnatullin** [comment]
:+1: for Notifications, less allocations, easier to understand.

**Comment by akarnokd** [comment]
See #4370
