### ISSUE TITLE
2.x Design: BlockingFlowable, BlockingObservable

### ISSUE THREAD

**Issue by akarnokd** [ReactiveX/RxJava#4366]
The `BlockingFlowable` and `BlockingObservable` classes host blocking operations. They were introduced to make absolutely clear someone uses blocking operations.

The drawback is that they wrap a `Flowable` and `Observable` respectively which incurs allocation whenever `toBlocking()` is called on the base class.

I suggest discarding these blocking classes and moving their operators into the base classes, prefixing the operator name with `blockingX`.

**Comment by artem-zinnatullin** [comment]
SGTM

**Comment by JakeWharton** [comment]
I'm supportive of this only to see two types removed from the public API
and seeing the disconnect of having no BlockingSingle and
BlockingCompletable eliminated. It seems a bit ridiculous to worry about a
single allocation, though, when every other operator already allocates at
least once and this operator is already doing something 10x worse by
throwing away the current thread on a lock.

**Comment by akarnokd** [comment]
See #4371.
