### ISSUE TITLE
2.x: Single & Completable have implicit Flowable subscribe methods but Observable does not

### ISSUE THREAD

**Issue by JakeWharton** [ReactiveX/RxJava#4373]
There's `Single.subscribe(Subscription)` and `Completable.subscribe(Subscription)` but no `Observable.subscribe(Subscription)`. Feels like we should either remove the two defined methods and require explicit conversions or add the missing method to `Observable`.

I'm in favor of removal, but I don't know if there's additional story as to why they're present.

**Comment by akarnokd** [comment]
It allows testing `Single` and `Compleatable` with `TestSubscriber`. I didn't add `Observable.subscribe(Subscriber)` to avoid overload resolution problems in case someone implements both ˙`Subscriber` and `Observer`.

**Comment by artem-zinnatullin** [comment]
Yup, noticed that too, but figured out there are both TestSubscriber and
TestObserver again (I was under impression that we're removing TestObserver
after changes in 1.x)

**Comment by JakeWharton** [comment]
Can we just add .test() methods to Single and Completable (if they're not
already there) to eliminate the subscribe() overloads then?

**Comment by akarnokd** [comment]
#4375 adds those methods so yes.

**Comment by JakeWharton** [comment]
I saw that. Great! Does that also mean we can remove the methods? Or do you
want them for some other purpose?

**Comment by akarnokd** [comment]
They are implemented like `toFlowable().subscribe()` anyway so I can live with that. So you can remove them. Also while you are at it, cosider renaming `Subject.hasSubscribers` to `Subject.hasObservers`.

**Comment by JakeWharton** [comment]
Will do after lunch!

**Comment by akarnokd** [comment]
I've started a PR myself with other changes so I'll make these as well.

**Comment by akarnokd** [comment]
See #4378.

**Comment by akarnokd** [comment]
Closing via #4375 and #4378
