### ISSUE TITLE
2.x: Ability/API to set thread priority of shared schedulers

### ISSUE THREAD

**Issue by JakeWharton** [ReactiveX/RxJava#4389]
In 1.x I implemented this with factory methods that accept user-supplied `ThreadFactory` instances. We could mimic this in 2.x, or we could add per-scheduler properties for the thread priority. A nice advantage of the property-based approach is that we can do platform detection and automatically lower the default when running on Android (which was the initial motivation for the feature).

**Comment by akarnokd** [comment]
PR welcome.

**Comment by akarnokd** [comment]
See #4503.

**Comment by akarnokd** [comment]
Closing via #4503.
