### ISSUE TITLE
2.x Design: subscribe() that returns

### ISSUE THREAD

**Issue by akarnokd** [ReactiveX/RxJava#4400]
Listening to the [Fragmented Podcast](http://fragmentedpodcast.com/episodes/053-jake-wharton-on-rxjava-2/) I came to the realization that the Reactive-Streams `void subscribe(Subscriber)` is going to be a problem for many users. Since we can't (nor should) change the RS interfaces, I suggest a new method on each of the base types:

``` java
<E extends Subscriber<? super T>> E subscribeWith(E subscriber);
<E extends Observer<? super T>> E subscribeWith(E observer);
<E extends SingleObserver<? super T>> E subscribeWith(E observer);
<E extends CompletableObserver> E subscribeWith(E observer);
```

Each of these will simply return the input subscriber after and if said consumer implements `Disposable` (i.e., `ResourceSubscriber`) you can add it to the `CompositeDisposable` as before. (Project Reactor already does offer these methods.)

**Comment by hamen** [comment]
We will still cry a little bit migrating to 2.x, but this will definitely help 😂

**Comment by mrsasha** [comment]
Hm, so what was the alternative? Without this, how were you able to get the ex-`Subscription` ie. `Disposable` reference with 2.0/RS calls?

**Comment by akarnokd** [comment]
Currently you need a `Subscriber` upfront:

``` java
ResourceSubscriber<T> rs = new ResourceSubscriber<T>() { ... };

source.subscribe(rs);

rs.cancel();
```

Or use only lambdas where you already get `Disposable`.

**Comment by hamen** [comment]
Most of my subscribers are anonymous:

``` java
Subscription subscription = source.subscribe(new Observer [...])
```

I guess this will need some work, but probably replacing every `.subscribe()` with `. subscribeWith()` will do as first refactoring cycle.

**Comment by mrsasha** [comment]
Ok, then I definitely think that having `.subscribeWith()` will make it easier to find them in the code.  To reduce cognitive overload one can use `subscribe()` for when there's no need for `Disposable` reference and `subscribeWith()` for other cases.

**Comment by akarnokd** [comment]
Closing via #4422
