### ISSUE TITLE
what's the way to return one observable like concat?

### ISSUE THREAD

**Issue by nicholas-fwang** [ReactiveX/RxJava#4402]
hi, I'm using rx java and sqlbrite on android.
In the observable, if I return `Observable<List<User>>` with `concat`, It is work well.
I read previous questions about toList() that was not working without onCompleted().
However using concat, It is available to use toList().
So can I use one observable like concat?
because of my shortage of english skill, I attached my code.

Observable --> Observer
SqlbriteService.java --> UsersManager.java --> Presenter.java

SqlbriteService.java

``` java
public Observable<List<User>> getUsers() {
    return databaseHelper.createQuery(UserEntry.TABLE_NAME, sql)
                .mapToList(userMapperFunction); 
}
```

UsersManager.java

``` java
public Observable<List<User>> getUsers() {
    Observable<List<User>> localUsers = sqlbriteService.getUsers();
    return Observable.concat(localUsers, localUsers).first(); 
}
```

It's so stupid code.. how to don't use concat?
`return localUsers;`
not working

Presenter.java

``` java
usersManager.getUsers()
.flatMap( ... )
.fileter(...)
.toList()
.subscribe(...)
```

thx!

**Comment by akarnokd** [comment]
Why did you even concat the `localUsers` twice?

**Comment by nicholas-fwang** [comment]
I read issue https://github.com/ReactiveX/RxJava/issues/3861

but I want to modify Observable to use flatMap.
If I return just localUsers, after filter not reach to toList().
however using concat, it reach toList(), so I can subscribe.
So I'm curious that there is method to reach toList() like concat.

**Comment by nicholas-fwang** [comment]
``` java
Map<K, V> USER_CACHE_DATA;
public Observable<List<User>> getUsers() {
       return Observable
               .from(USER_CACHE_DATA.values())
               .toList();
}
```

if I use getUsers() instead of in SqlbriteService.java and return localUsers, it is work.
What's different between toList() and mapToList() in sqlbrite ?

**Comment by nicholas-fwang** [comment]
I think it is subject about sqlbrite, no rx 😅 
it's better to close. Thx @akarnokd 👍
