### ISSUE TITLE
RxJavaObservableExecutionHook for only one Observable?

### ISSUE THREAD

**Issue by tir38** [ReactiveX/RxJava#4404]
If I understand correctly, using `RxJavaObservableExecutionHook` will respond for all observable calls within my app. Is there a way to hook `RxJavaObservableExecutionHook` into only a single observable? I'd like different hooks for different observables throughout my app.

**Comment by akarnokd** [comment]
Use the callbacks of `RxJavaHooks` like `setOnObservableCreate` or `setOnObservableStart` but you'll need to identify your `Observable` or `OnSubscribe` implementation in some way.

**Comment by tir38** [comment]
Excellent thanks.
