### ISSUE TITLE
Sync State Observable does not work well with subscribeOn

### ISSUE THREAD

**Issue by hf** [ReactiveX/RxJava#4405]
An observable created with `Observable.create(SyncOnSubscribe)` does not work well when that observable is assigned a scheduler with `Observable.subscribeOn(Scheduler)`. 

Specifically, the `SyncOnSubscribe.call(Subscriber)` method is not being called in the lifecycle of the `OperatorSubscribeOn.call(Subscriber)`.

This does not set the proper producer required for SyncOnSubscribe to work. 

This can be seen on RxJava 1.1.9 (on Android).

**Comment by akarnokd** [comment]
Could you post a code that's not working for you? You have to create an `Observable` from an instance of `SyncOnSubscribe` because `Observable` has to call `Subscriber.onStart` that may trigger the necessary `request(n)` calls down the chain.

**Comment by hf** [comment]
The issue was with a CompositeSubscription that got unsubscribed before the addition of the SyncOnSubscribe subscription. Sorry, everything is great. :)
