### ISSUE TITLE
2.x - Add interfaces for Action3 through Action9

### ISSUE THREAD

**Issue by pakoito** [ReactiveX/RxJava#4406]
Although maybe not required for the core package or can be expressed in terms of FunctionN, extension libraries for utils like [partial application](https://github.com/pakoito/RxPartialApplication/blob/master/rxpartialapplication/src/main/java/com/pacoworks/rxpartialapplication/RxPartialAction.java) will still need them. We also have a couple of Action3 and Action4 through the codebase.

If this proposal is accepted and If nobody else is willing to pick up the ticket, I can just PR them in in a tick.

**Comment by JakeWharton** [comment]
They'd be called Consumer3 through Consumer9. Very hesitant about putting them in RxJava when there's no first-party usage though.

What's the downside of defining your own?

**Comment by pakoito** [comment]
None from the technical perspective today, but more for extensibility and future-proofing. Keeping separate interfaces per library while using the rest of RxJava as a backend for FRP concepts seems a bit off, specially in Java 6 where SMIs are not interchangeable.

I too would like to, in the future, suggest adding some of the functional extension packages into the project to have first-party support for chain composition helpers like partial application or fmap. While they're more geared towards functional than reactive they've proven to be useful for conciseness in absence of lambdas in Java 6 projects without retrolambda or kotlin.

**Comment by akarnokd** [comment]
Such interfaces can live in any library and since we don't have any use for them in the core RxJava library, I deliberately didn't port them from 1.x. :-1:

**Comment by pakoito** [comment]
I see you didn't also port [Actions.java](https://github.com/ReactiveX/RxJava/blob/1.x/src/main/java/rx/functions/Actions.java) :(

While not part of the core they are definitely part of using RxJava as a tool, specially in Java 6 environments. Actions.empty(), Action conversors, Function to Action are tools necessary to avoid unnecessary duplication. They add to the ergonomics of large projects.

Making it almost mandatory to use a third party library or copypaste code across projects just to be able to represent many ui functions, compose them, and have empty Actions through the app is a big penalty for just a small price of 6 interfaces and one helper class that are easily portable.

**Comment by akarnokd** [comment]
> They add to the ergonomics of large projects.

Roll your own library with the classes and interfaces you need.

> Making it almost mandatory to use a third party library or copypaste code across projects just to be able to represent many ui functions, compose them

RxJava has to keep focus on reactive and host only what it needs to accomplish that task. By this logic we would have to include the whole world. The converse is also problematic: why include the whole RxJava for just its functional interfaces (like IxJava which I'll switch to its own interfaces for 2.x).

**Comment by pakoito** [comment]
I'm not asking to include the whole world, just 6 interfaces that already existed in 1.0 and were used in projects in prod and third party libraries, like your IxJava.

Not having a different set of interfaces that cannot be converted to one another, but rather a central point for all of them that all extension libs can use, and they do not need project-to-project convertors in Java 6 to compensate for lack of functional interfaces.

Extension libraries bank on RxJava being in the project because other functional backends like Javaslang, Reactor, or functionaljava are not available on Java 6 or well supported on Android. Previous attempts at unifying callbacks by using the same generic interfaces are non-existent or not widespread.

**Comment by akarnokd** [comment]
We are a reactive stream composition library and not a functional composition library. We can `map` twice if needed.

Having a separate library has its own benefits:
- compact and focused,
- any number of helper classes,
- include in other libraries and projects independent of RxJava
- separate lifecycle and versioning
- can have bridge companion library to support RxJava's types

**Comment by pakoito** [comment]
The functional composition can be kept as separate libraries, and I do understand your concern of keeping RxJava focused on being reactive rather than functional. I will refrain from suggesting adding any of those to RxJava in the future.

That's not exclusive from having 6 interfaces for Actions that are already used by 1.X consumers. The cost is non-existent and they do not introduce any problems on overhead or maintenance, but they do add value for RxJava projects and extension libraries.

**Comment by akarnokd** [comment]
Closing this as out of scope for 2.x.
