### ISSUE TITLE
How can I cancel the previous network request?

### ISSUE THREAD

**Issue by Jimmy-Fish** [ReactiveX/RxJava#4416]
I use this code to perform a network request:

```
   @Override
    protected void onResume() {
        super.onResume();
        subscription = Observable
                .create(new Observable.OnSubscribe<Object>() {

                    @Override
                    public void call(Subscriber<? super Object> subscriber) {
                        Log.i("thread", "" + Thread.currentThread().getId());
                        networkRequest(); //The request that cannot be cancelled.
                    }

                })
                .subscribeOn(Schedulers.io())
                .observeOn(AndroidSchedulers.mainThread())
                .subscribe(new Observer<Object>() {
                    @Override
                    public void onCompleted() {}

                    @Override
                    public void onError(Throwable e) {}

                    @Override
                    public void onNext(Object o) {}
                });
    }

    @Override
    protected void onPause() {
        super.onPause();
        subscription.unsubscribe();
    }
```

I start the activity, then the network request will be performed in onResume(). As far as I know, an IO operation cannot be cancelled actually, so when I press the back button, the request will continue though the subscription is unsubscribed. If I start the activity again, I find out that the newer request will not be performed until the previous one finishes. How can I cancel the previous network request? (According to the log, the thread perfoming the new request is the same as previous one. )

**Comment by akarnokd** [comment]
If the `networkRequest` doesn't respond to `Thread.interrupt()` you are out of luck. Are you using Retrofit 2?

**Comment by artem-zinnatullin** [comment]
> I find out that the newer request will not be performed until the previous one finishes. 

How exactly do you find this out?

> How can I cancel the previous network request? 

Basically you're already doing this with `subscription.unsubscribe()`, since in your code example you use `Observable.create()` I suspect that you haven't implemented unsubscription properly.

**Comment by Jimmy-Fish** [comment]
The code of networkRequest() is: 

```
 public void networkRequest() {
        for (int i = 0; i < 20; i++) {
            Log.i("networkRequest", i + " " + Thread.currentThread().getId());

            try {
                Thread.sleep(1000);
            } catch (InterruptedException e) {
                e.printStackTrace();
            }
        }
    }
```

To akarnokd:
As you say, networkRequest() doesn't respond to Thread.interrupt(),  I use networkRequest() to simulate an in-flight HTTP request that cannot be cancelled. I plan to use Retrofit 2, but I think the cancel() method of Retrofit2 might not cancel the request actually. 

To artem-zinnatullin:

> How exactly do you find this out?

The newer request don't print the log `i + " " + Thread.currentThread().getId()` until the previous one finishes printing the log.

After changing rxjava version from 1.1.0 to 1.1.9,  the newer request is performed by another thread and the previous request don't block the newer request, the onNext(Object) and onComplete() of previous subscriber are also not invoked. Now I just ignore the previous request, is it a correct practise?

I have another question: 
Why subscribe() is called inside onResume() and unsubscribe() is called inside onPause() usually?  An in-flight request or other operation may be easy to be discarded. If subscribe()/unsubscribe() is called inside onCreate()/onDestroy(), it will reduce number of HTTP requests and save resources.

**Comment by adipascu** [comment]
I suggest you reading more documentation  source code and maybe the book **Reactive Programming with RxJava** before diving head first into RxJava.
You are using RxJava in a different way than intended.

A beginner should not use Observable.create() because the method is unsafe. A lot of proper examples on how to use it can be found in the RxBinding project on github, but I suggest avoiding it in favor of other methods like **Observable.fromCallable()** .
If you plan to use retrofit2 use the RxJava call adapter instead (it properly creates observables that support backpressure and cancel)
Relevant link: https://medium.freecodecamp.com/rxandroid-and-retrofit-2-0-66dc52725fff

For more info about the android framework and RxJava I suggest asking on StackOverflow. Github is mostly used to fix issues inside the library.

**Comment by Jimmy-Fish** [comment]
@adi1133  Thank you for your suggestion. :-)
