### ISSUE TITLE
1.x: Base interface types

### ISSUE THREAD

**Issue by JakeWharton** [ReactiveX/RxJava#4420]
Before `Single` and `Completable` progress to stable, I'd like to address the interface naming inconsistency in a similar fashion to what #4044 did for 2.x.

Here's the current state:

<img width="614" alt="screen shot 2016-08-24 at 1 30 57 pm" src="https://cloud.githubusercontent.com/assets/66577/17940957/3f4ee112-69ff-11e6-8d0f-68dc06df051a.png">

It's very clear that there's a lack of normalization. ~~I'd like to take the same approach as we did in 2.x and move to prefixes and top-level types.~~ I'd like to normalize the names of the nested classes and make the subscribers top-level types. We can `@Deprecate` the existing types and make them extend from these new top-level types to make migration easier, deleting these `@Deprecated` types whenever these APIs turn stable. 👍 👎 ?

Additionally, there's a problem with `CompletableSubscriber` in that it's an interface instead of an abstract class that also implements `Subscription` (as both `Subscriber` and `SingleSubscriber` do). I would like to correct this. 👍 👎 ?

**Comment by akarnokd** [comment]
1) Kind of disruptive at this point, plus `@Deprecated` never get removed from the main versions (since it was promised)

2) It's a modern design just like in 2.x but you can introduce the `ResourceCompletable` similar to 2.x `ResourceSubscriber`.

**Comment by JakeWharton** [comment]
Er, sorry I meant to change that paragraph before hitting create. I want to propose non-prefixed inner types similar to what `Observable` has except for the `Subscribers` which will be top-level.

This will only change non-stable APIs so they could just be renamed.

I was suggesting `@Deprecating` these non-stable old interfaces so that it didn't immediately break people upgrading. Then eventually you could delete those interfaces since they were never stable in the first place. We also could just rename them though and not bother.

The changes would look like this:

<img width="614" alt="screen shot 2016-08-24 at 3 51 00 pm" src="https://cloud.githubusercontent.com/assets/66577/17945620/9e654228-6a12-11e6-96e5-8a3618d9f762.png">

**Comment by akarnokd** [comment]
Let's see a PR so the diff is more telling about the consequences.

**Comment by akarnokd** [comment]
Can we do more about this or can this be closed?

**Comment by JakeWharton** [comment]
I think we're now at a good enough place with 1.x here. Any more changes would only be disruptive for the sake of being disruptive.

**Comment by akarnokd** [comment]
Great!
