### ISSUE TITLE
Disposables.from annoying to use with lambda

### ISSUE THREAD

**Issue by robeden** [ReactiveX/RxJava#4446]
(Sorry if this isn't the best place for this feedback.)

Disposables.from() in 2.0 (RC-1) is annoying to use with a lambda because both Runnable and Action match. Example: 

```
Disposables.from( () -> {} );             // This won't compile
Disposables.from( (Runnable) () -> {} );  // This compiles
```

Perhaps one form should have different name?

**Comment by JakeWharton** [comment]
This is the place! We do that everywhere else (e.g., `Observable.fromXxx`), so it seems reasonable.

**Comment by akarnokd** [comment]
I'll deprecate them and add the postfixed versions in my upcoming PR (among other fixes).

**Comment by akarnokd** [comment]
Closing via #4450

**Comment by robeden** [comment]
Awesome, thanks guys.
