### ISSUE TITLE
2.x: No overload for first() which takes a predicate

### ISSUE THREAD

**Issue by emmaguy** [ReactiveX/RxJava#4449]
I was trying out the `2.0.0-RC1` release by upgrading a small project of mine, when I noticed that I can no longer do:

``` java
Observable.concat(cache, network)
                .first(token -> token != null && !token.isEmpty())
```

seeing as `first` now does not have an overload which takes a predicate. Was this removed for a reason or is it just something missed? Happy to create a PR for this if it's desired.

Without it I suppose I can do `takeFirst(predicate).single()`, which isn't too bad.

**Comment by akarnokd** [comment]
The predicate versions of `first`, `last` and `single` have been dropped, use `filter(predicate).op()` instead (this is btw mentioned in the [wiki article](https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0#instance-methods) the release refers to).

**Comment by emmaguy** [comment]
Ahhh okay - thanks! Didn't see that all the way down there on the wiki!
