### ISSUE TITLE
2.x: Patch releases to the release candidates

### ISSUE THREAD

**Issue by akarnokd** [ReactiveX/RxJava#4451]
There were a bunch of low-to-medium bugs and annoyances released with RC1 which have been already fixed in the last couple of days. However, RC2 is scheduled for September 23-24 (3 weeks from now) which is a lot of time to live with said issues.

Therefore, I suggest releasing patch updates to the release candidates as follows:
- Their version tag should be like `2.0.0-RC1-u1` if the Nebula/Maven cooperates on it
- Public API renames should keep the original as `@Deprecated` and the API stays until `2.0.0-RC2` in case some only update after each major RC. `2.0.0-RC2-u1` however can remove those deprecated APIs

This allows dependent libraries to walk with us and not revert back to snapshots of 2.x.

**Comment by vanniktech** [comment]
I also actually wanted to propose this since there have been a few things that prevented me from trying it out. 👍

**Comment by JakeWharton** [comment]
Do you think another intermediate release will be needed between this hypothetical one and the next scheduled RC?

**Comment by akarnokd** [comment]
There is an annoying bug in `Single.subscribeOn` I just fixed, many other components didn't work properly until I added the unit tests and fixed them as well. Naming corrections...

**Comment by zsxwing** [comment]
IMO, RC versions are experimental and I don't expect people use a RC version in production. Why not just release RC2 now? 

Moreover, there is no guarantee for APIs in a RC version, so `Deprecated` is not necessary as well.

**Comment by JakeWharton** [comment]
(Whoops got distracted...)

Yeah that was the point that I was leading to. Obviously I don't think we want RCs every week since the library should be stabilizing over time, but I don't think doing another one a week later to fix the initial flurry of problems is a bad thing.

**Comment by davidmoten** [comment]
Make as many RC candidates as you like as often as you want. My use of RxJava2 in production will be  more driven by awareness of the rate of discovery of significant problems than what label the artifact has.

**Comment by vanniktech** [comment]
So will there be something released before 23/09/2016?

**Comment by akarnokd** [comment]
I you don't mind the half-ready `Maybe` then I can release this today.

**Comment by vanniktech** [comment]
Nope I don't mind at all. The `subscribeOn` bug is biting me.

**Comment by akarnokd** [comment]
Sure. Closing via #4476
