### ISSUE TITLE
2.x: Naming of .doOnCancel()

### ISSUE THREAD

**Issue by Mauin** [ReactiveX/RxJava#4456]
As I understand it the `.doOnCancel()` operator is basically the replacement of `.doOnUnsubscribe()` in the 1.x world.

In that case: Just from a naming perspective wouldn't it be clearer to name it `.doOnDispose()` ?

**Comment by akarnokd** [comment]
`Flowable` -> `doOnCancel()` because of `Subscription.cancel()`, the other can be called `doOnDispose()`. Want to submit a PR?

**Comment by Mauin** [comment]
Ah, I was not looking much at Flowable yet, that's why I missed that part. Thanks for explaining!

I'll get started on the PR.
