### ISSUE TITLE
1.x: Single and Completable are missing doOnEach

### ISSUE THREAD

**Issue by vanniktech** [ReactiveX/RxJava#4457]
Both are missing that method. Is this one wanted?

**Comment by JakeWharton** [comment]
Single is either success or error and Completable is either complete or error, and both types have doOn- methods for those events.

**Comment by vanniktech** [comment]
Yes I'm aware of that however I'd like something like a `doOnEach`. Also in Observable `doOnEach` includes terminal events.

If you want to execute some code regardless of whether it was successful or an error was thrown you'd need to call that method  in `onSuccess` and `onError`, where as with a `doOnEach` you'd call it once instead.

Again just a proposal if this is not wanted at all I'm also happy to live without it.

**Comment by JakeWharton** [comment]
Oh I misread as next not each. Go for it.

**Comment by vanniktech** [comment]
Alright will do in the next few hours.

**Comment by Mauin** [comment]
How about 2.x in this case? Both `Single` and `Completable` are also "missing" `doOnEach` there. Will the changes automatically be merged from 1.x to 2.x?

**Comment by akarnokd** [comment]
For 2.x, I'd imagine `Completable.doOnEvent(Consumer<? super Throwable> onEvent)` and `Single.doOnEvent(BiConsumer<? super T, ? super Throwable>)` where if the `Throwable` is null, it means the other event happened. There is a similar  API in `CompletableFuture.whenComplete(BiConsumer)` or something.

**Comment by vanniktech** [comment]
What about the Maybe type? That one would need one too, right?

**Comment by akarnokd** [comment]
I'm currently expanding Maybe so I'll add one.
