### ISSUE TITLE
1.x: Unused Notification.createOnCompleted(Class<T> type)

### ISSUE THREAD

**Issue by vanniktech** [ReactiveX/RxJava#4462]
While reading the Notification class due to #4457 I noticed [`Notification.createOnCompleted(Class<T> type)`](https://github.com/ReactiveX/RxJava/blob/30da1aa1e38a5ead8965d1784ab8c6df8111d354/src/main/java/rx/Notification.java#L73) which seems to be only used in one [test](https://github.com/ReactiveX/RxJava/blob/30da1aa1e38a5ead8965d1784ab8c6df8111d354/src/test/java/rx/NotificationTest.java#L89) and that test does not really add any value. So I'm wondering since this is in the public API and not used can be it removed or do you see any value in having this method around?

**Comment by akarnokd** [comment]
You could deprecate it but since the 1.x series can't remove methods that are non-beta and non-experimental, it doesn't make much difference.
