### ISSUE TITLE
2.x: operator method naming in Observable

### ISSUE THREAD

**Issue by XizhiXu** [ReactiveX/RxJava#4465]
hi guys,

I think there is much redundancy in many operator methods comparing to 1.x. For example, the `from` series:

`fromCallable(Callable<? extends T> supplier)`

The parameter (list) has already indicated the object and can help to set the methods apart syntactically. I think we can leave out the unnecessary `Callable` part in the name.  I mean it's trouble to have something like this:  `justTwoItems(T item1, T item2)` right? :) 

Never mind,  `just` is fine.

There are many similar cases mainly in `from` and `concat` series. But sorry I can't list them all.

**Comment by akarnokd** [comment]
These methods have prefixes because Java 8 compilers can't disambiguate properly between the methods, forcing you to cast them to the proper functional interface type; a postfix is simply shorter and more explicit to the reader.
