### ISSUE TITLE
1.x: SingleDoAfterTerminateSubscriber swallowing exception

### ISSUE THREAD

**Issue by vanniktech** [ReactiveX/RxJava#4473]
Isn't `SingleDoAfterTerminateSubscriber` swallowing an exception?

e.g. when action that get's invoked throws an excpetion for instance NullPointerException It'll be just rethrown but not delivered through onError

Also could not `SingleDoOnEvent` be reused for this behavior of invoking an action when Single has completed or errored?

**Comment by akarnokd** [comment]
It is **AfterTerminate**, that is, called after onXXX of the downstream has been called. At that point, the exception can't go anywhere other than the global onError handler.

**Comment by vanniktech** [comment]
Okay makes sense. Thanks for the explanation!
