### ISSUE TITLE
2.x TestObserver and TestSubscriber for unit testing

### ISSUE THREAD

**Issue by VictorAlbertos** [ReactiveX/RxJava#4477]
In 1.x I was using `TestSubscriber` to perform assertions in unit tests. But it seems that in 2.x is `TestObserver` the class that we need to use for this matter. Is that correct? And if that's correct, when I should use `TestSubscriber`?

Thanks.

**Comment by vanniktech** [comment]
All reactive types also have a built in `test` method that can be used.

**Comment by VictorAlbertos** [comment]
Very handy. Thanks @vanniktech

**Comment by akarnokd** [comment]
You use `TestSubscriber` with `Flowable` and `TestObserver` with `Observable`. You can test `Single`, `Completable` and `Maybe` by converting them to either `Flowable` or `Observable`, but the built-in `test()`s for these three return `TestObserver`.

**Comment by VictorAlbertos** [comment]
Thanks @akarnokd

**Comment by andreathacker** [comment]
In 2.x @akarnokd mentioned that the built-in return for `Single`, `Completable` and `Maybe` is `TestSubscriber` but it looks like it actual default for `Completable` is now `TestObserver`

```
    @CheckReturnValue
    @SchedulerSupport(SchedulerSupport.NONE)
    public final TestObserver<Void> test() {
        TestObserver<Void> ts = new TestObserver<Void>();
        subscribe(ts);
        return ts;
    }
```

**Comment by akarnokd** [comment]
@davidargylethacker Thanks, edited my comment to define the correct type.

**Comment by osvalr** [comment]
Thanks @akarnokd
