### ISSUE TITLE
How to implement polling using Observables?

### ISSUE THREAD

**Issue by lexer** [ReactiveX/RxJava#448]
I've got parametrized rest call with Observable interface:

```
   api.updateAppState(params);
```

I want to repeat it with delay so I have created delayed version of it:

```
   Observable<AppState> delayedApiCall = Observable.interval(delay, TimeUnit.SECONDS)
            .first()
            .flatMap(new Func1<Long, Observable<AppState>>() {
        @Override
        public Observable<AppState> call(Long seconds) {
            return lyftApi.updateAppState(params);
        }
    });
```

But now I want to have polling observable that will recreate "delayedApiCall" with params and produce continuous results. I also want observable to continue producing results even if error was returned in "delayedApiCall".

```
    pollingObservable.subscribe(new Observer<AppState>() {
        onNext(AppState appSte) {
           ....
        },
        onError(Throwable e) {
           ....
        }
    });
```

**Comment by roman-ku** [comment]
@benjchristensen 

How can _scheduling periodically but wait for completion_ be done today using RxJava? Your code snippet has several things that have been deprecated, so I am wondering what an alternative would look like?

**Comment by akarnokd** [comment]
Use  `Observable.interval()` as the starting point and forget that manual recursion.

``` java
Observable.interval(1, TimeUnit.SECONDS, Schedulers.io())
.map(time -> pollSource())
.toBlocking()
.subscribe(System.out::println, Throwable::printStackTrace)
```

**Comment by roman-ku** [comment]
@akarnokd 

The problem with that is that the "interval" operator is dumb. It will continue to pump out a pulse every X seconds without any regards what happens down the line. That is not what I want. The "toBlocking" does nothing to fix this.

The behavior I want is a new tick from the time the poll finished not every 20 seconds:

What your code does:
0 (seconds): tick generated
0: poll started
5: poll finished
20: new tick generated

What I want:
0 (seconds): tick generated
0: poll started
5: poll finished
25: new tick generated

**Comment by akarnokd** [comment]
Okay then, how about:

``` java

Observable.fromCallable(() -> pollValue())
.repeatWhen(o -> o.concatMap(v -> Observable.timer(20, TimeUnit.SECONDS)));
```

**Comment by roman-ku** [comment]
@akarnokd 

I did some testing and it looks like it's working as intended. I will have to throw in some conditional check so it doesn't go on forever but it looks like we have a winner!

Thank you so much! I really appreciate your help!

**Comment by cxzhang2** [comment]
@akarnokd 
I maybe be doing something wrong but it looks like unsubscribing to the Observable you suggested won't stop the currently scheduled emission from going out, any way to get around this? Thanks!

**Comment by akarnokd** [comment]
@cxzhang2 An unsubscribe should stop that timer. Do you have some code that demonstrates what you experience?

**Comment by cxzhang2** [comment]
@akarnokd totally my mistake, great solution thank you!

**Comment by lby1992** [comment]
I found this [post](http://blog.danlew.net/2016/01/25/rxjavas-repeatwhen-and-retrywhen-explained), hope it helps.

**Comment by Lavaei** [comment]
You can use `retryWhen` instead of `repeatWhen` and in your `map()` operator use `Rx.Observable.throw(new Error('My Error Message'))` in case you want to retry the request
