### ISSUE TITLE
Renaming RxCachedThreadScheduler

### ISSUE THREAD

**Issue by richardradics** [ReactiveX/RxJava#4485]
Is it possible to simply change the name `RxCachedThreadScheduler` to something else?

Thanks in advance!

**Comment by akarnokd** [comment]
Not without recompiling the library. Why do you want to change it?

**Comment by richardradics** [comment]
I am working on an android project which has really long package name, so i just wondering how to reduce the lines in the logcat.

Thank you for the answer.
