### ISSUE TITLE
2.x: SerializedEmitter not implementing Disposable

### ISSUE THREAD

**Issue by Mauin** [ReactiveX/RxJava#4489]
While looking at the different `Observable`/`Single`/`Completable` Emitters I noticed that the ObservableCreate `SerializedEmitter` is the only one not implementing `Disposable` and thus `#dispose`.

Is this intended?

**Comment by akarnokd** [comment]
Yes, you are not supposed to dispose it from inside the emitter callback anyway.

**Comment by Mauin** [comment]
Okay, thanks for the clarification @akarnokd 👍
