### ISSUE TITLE
toSortedList and friends should return a Single

### ISSUE THREAD

**Issue by DavidDTA** [ReactiveX/RxJava#4495]
There are several methods of Observable which are defined to return an observable which emits exactly one item.  It seems like these should actually return Singles instead.  Has this been discussed?

**Comment by JakeWharton** [comment]
#4321

**Comment by DavidDTA** [comment]
#4321 discusses changes for 2.0.  Have we considered adding this to 1.x?

**Comment by vanniktech** [comment]
Kinda in #4277

**Comment by akarnokd** [comment]
It is a breaking change for 1.x so we won't do it there.

**Comment by JakeWharton** [comment]
That would be a binary-incompatible change without creating new methods
with different names.

**Comment by DavidDTA** [comment]
Correct.  I am proposing adding additional methods.

**Comment by akarnokd** [comment]
That just adds to the API surface without any benefit; the performance won't improve but now 20+ methods need to be documented, communicated and maintained. Use `toSingle()` in 1.x.

**Comment by DavidDTA** [comment]
The small benefit this grants is that stack sizes are reduced.  I understand if this is not sufficient motivation to include additional API methods.
