### ISSUE TITLE
Matcher for TestSubscriber.assertError()

### ISSUE THREAD

**Issue by dkhmelenko** [ReactiveX/RxJava#4498]
In order to test occurred error in subscriber we are using `TestSubscriber.assertError()`. However, the method accepts either `Throwable` or class. So if we want to check the details of the thrown exception, we need to have methods `equals()` and `hashCode()` in each exception. But it's a bad practice.

Does it make sense to have a matcher for checking thrown exception and it?

**Comment by akarnokd** [comment]
Not sure what you mean or how you imagine it, but PR is welcome.

**Comment by akarnokd** [comment]
Closing via #4586.
