### ISSUE TITLE
2.x: Matching DisposableObserver class for Single

### ISSUE THREAD

**Issue by vanniktech** [ReactiveX/RxJava#4501]
How do you feel about adding a matching class for `DisposableObserver` with Single support?

Instead of `Observer` it'll implement `SingleObserver`

**Comment by akarnokd** [comment]
Sounds good; please add one for Completable and Maybe while you are at it.

**Comment by vanniktech** [comment]
Will do 👍

**Comment by vanniktech** [comment]
Closing via #4504
