### ISSUE TITLE
skipUntil with "empty" observable causes source obs to never complete.

### ISSUE THREAD

**Issue by vekexasia** [ReactiveX/RxJava#4511]
Hello,

``` java
Observable.interval(1, TimeUnit.SECONDS)
      .doOnNext(n -> Timber.d("firstObs %s", n))
      .doOnUnsubscribe(() -> Timber.d("onUnsubscribe"))
      .doOnCompleted(() -> Timber.d("onCompleted"))
      .skipUntil(Observable.timer(3, TimeUnit.SECONDS)
        .flatMap(b -> Observable.empty())
        .doOnCompleted(() -> Timber.d("onCompleted2")))
      .subscribe(
        n -> Timber.d("Next? %s",n),
        e -> Timber.d(e, "Err"),
        () -> Timber.d("Completed")
      );
    Timber.d("Ciao");
```

Looking at this snippet I would expect "Completed" to be triggered upon skipUntil observable completion ('after 3 seconds'). 

After some time of debugging I found out it's not the case and the Source observable does not get "onCompleted" or "onUnsubscribe" called when the latter `skipUntil` obs completes its execution.

This means that the first obs is never gonna end and the emitted items are not going to reach the end of the chain

**Comment by JakeWharton** [comment]
flatMap does not propagate completion events

**Comment by vekexasia** [comment]
why do I get the following output 

```
09-08 16:50:05.670 D/MainActivity: onSubscribe2
09-08 16:50:05.672 D/MainActivity: onSubscribe
09-08 16:50:05.674 D/MainActivity: Ciao
09-08 16:50:06.674 D/MainActivity: firstObs 0
09-08 16:50:07.674 D/MainActivity: firstObs 1
09-08 16:50:08.672 D/MainActivity: onCompleted2
09-08 16:50:08.672 D/MainActivity: onUnsubscribe2
09-08 16:50:08.674 D/MainActivity: firstObs 2
09-08 16:50:09.674 D/MainActivity: firstObs 3
09-08 16:50:10.674 D/MainActivity: firstObs 4
...
```

when using the following code then?

``` java
Observable.interval(1, TimeUnit.SECONDS)
      .doOnNext(n -> Timber.d("firstObs %s", n))
      .doOnSubscribe(() -> Timber.d("onSubscribe"))
      .doOnUnsubscribe(() -> Timber.d("onUnsubscribe"))
      .doOnCompleted(() -> Timber.d("onCompleted"))
      .skipUntil(Observable.timer(3, TimeUnit.SECONDS)
        .flatMap(b -> Observable.empty())
        .doOnCompleted(() -> Timber.d("onCompleted2"))
        .doOnSubscribe(() -> Timber.d("onSubscribe2"))
        .doOnUnsubscribe(() -> Timber.d("onUnsubscribe2"))
      )
      .subscribe(
        n -> Timber.d("Next? %s", n),
        e -> Timber.d(e, "Err"),
        () -> Timber.d("Completed")
      );
    Timber.d("Ciao");
```

**Comment by JakeWharton** [comment]
Because timer completes. I guess you're just using that as an `ignoreElements()`?

**Comment by vekexasia** [comment]
Actually I was hoping that when the skipUntil observable completes, then "parent"."unsubscribe"  is triggered so that no more elements are sent through the pipeline.

**Comment by JakeWharton** [comment]
`skipUntil` is documented to require an emission to unlatch upstream events so all you need to do is remove your `flatMap`.

> Returns an Observable that skips items emitted by the source Observable until a second Observable emits an item.

**Comment by vekexasia** [comment]
the code above is just as "sample". Consider an observable that completes after three seconds without emitting any item (used as skipUntil parameter).

In such case the first obs will just continue emit its elements without ever completing (and without any chance for the items to reach the end of the chain)

**Comment by vekexasia** [comment]
Just to mention that I rewrote the OperatorSkipUntil so that it unsubscribes from `child` when `other` completes without emitting any element.

I figured it would be something to raise here since someone might expect the same behavior ( if `other` completes without emitting any elements then unsubscribe from `child`)

**Comment by JakeWharton** [comment]
Ahhh, I see. That makes sense I think. I thought you were proposing that it become unlatched when the inner observable completes.

**Comment by akarnokd** [comment]
Yes, `skipUntil` requires the other `Observable` to signal an item in 1.x and just ignores an empty other `Observable`. In 2.x `skipUntil` enables the gate when the source either signals or just completes.

This signals-or-completes is a common practice in such operators that take auxiliary sources to trigger one-time events. I guess the 1.x `skipUntil` not opening the gate on a plain `onComplete` is a bug.

**Comment by vekexasia** [comment]
Thank you all :)
