### ISSUE TITLE
2.x: ResourceSubscriber & ResourceObserver

### ISSUE THREAD

**Issue by vanniktech** [ReactiveX/RxJava#4517]
Why is `ResourceSubscriber` using `CompositeDisposable` and `ResourceObserver` using `ListCompositeDisposable`?

Also the java documentation does not seem to fit of the disposables.
`/** The resource composite, can be null. */`

It's initialized and made final and adding a `null` Disposable will throw a `NullPointerException`.

In addition is there a need for ResourceMaybeObserver and the alike implementation for Single & Completable?

**Comment by akarnokd** [comment]
> Why is ResourceSubscriber using CompositeDisposable and ResourceObserver using ListCompositeDisposable?

By mistake, both should be `ListCompositeDisposable`

> Also the java documentation does not seem to fit of the disposables.

Used to be optional to have resource support there, the javadoc was not updated when the class was changed to always support resources.

> It's initialized and made final and adding a null Disposable will throw a NullPointerException.

Yes, that's intentional.

> In addition is there a need for ResourceMaybeObserver and the alike implementation for Single & Completable?

PR welcome.

**Comment by vanniktech** [comment]
Alright I'll get working 👍

**Comment by vanniktech** [comment]
Closing via #4518
