### ISSUE TITLE
2.x: Maybe.complete()

### ISSUE THREAD

**Issue by vanniktech** [ReactiveX/RxJava#4520]
Was a bit astonished that there was no `Maybe.complete()` then I saw `Maybe.empty()` which seems to be doing the thing. Any interest in a shortcut or maybe a rename of the method?

**Comment by akarnokd** [comment]
Completable is either complete or error, Maybe is has something or is empty (or error).

**Comment by vanniktech** [comment]
Alright still feels odd to me but acceptable.
