### ISSUE TITLE
RxJava2 `Observable.zip` taking `Iterable` and a `zipper` is broken

### ISSUE THREAD

**Issue by dynaxis** [ReactiveX/RxJava#4524]
http://reactivex.io/RxJava/2.x/javadoc/io/reactivex/Observable.html#zip-java.lang.Iterable-io.reactivex.functions.Function-

The `zipper` signature is `Function<? super T[]>, ? extends R> zipper`, where use of `T[]` breaks it. Just invoke it with non `Object` T, and a `ClassCastException` is thrown.

I checked with `Single` and `Flowable`, they have different signatures for the comparable `zip` operators. They use `Object[]` where `T[]` is used for `Observable`, which are also consistent with the 1.x zip operator.

I think this is just a bug in the signature.

**Comment by akarnokd** [comment]
Totally possible. Can you post a small unit test that fails?

**Comment by dynaxis** [comment]
``` Java
    @Test
    public void zipIterableOfObservables() {
        List<Observable<Integer>> observables =
                new ArrayList<Observable<Integer>>();
        observables.add(Observable.just(1, 2, 3));
        observables.add(Observable.just(1, 2, 3));

        Observable.zip(observables, new Function<Integer[], Integer>() {
            @Override
            public Integer apply(Integer[] o) throws Exception {
                int sum = 0;
                for (int i : o) {
                    sum += i;
                }
                return sum;
            }
        }).test().assertResult(2, 4, 6);
    }
```

Please note that if we use lambda as a zipper, it eventually generates what the above test has.

**Comment by dynaxis** [comment]
FYI, the following works and it's what is generated with the 1.x signature:

``` Java
    @Test
    public void zipIterableOfObservables() {
        List<Observable<Integer>> observables =
                new ArrayList<Observable<Integer>>();
        observables.add(Observable.just(1, 2, 3));
        observables.add(Observable.just(1, 2, 3));

        Observable.zip(observables, new Function<Object[], Object>() {
            @Override
            public Object apply(Object[] o) throws Exception {
                int sum = 0;
                for (Object i : o) {
                    sum += (Integer) i;
                }
                return sum;
            }
        }).test().assertResult(2, 4, 6);
    }
```

**Comment by akarnokd** [comment]
Thanks. The underlying problem is that we can't do `new T[n]` and such lambdas cast the bridge `Object apply(Object[])` argument to `Integer[]` which fails since `zip` and `combineLatest` use `Object[]` internally.

Currently I can't write a PR. @vanniktech could you change all `? super T[]` signatures back to `? super Object[]` and add unit tests like above to verify there is no `ClassCastException` in a PR?

**Comment by vanniktech** [comment]
Sure 👍

**Comment by akarnokd** [comment]
Closing via #4525.

**Comment by dynaxis** [comment]
BTW, why use array instead of `List` there? Any reason? If `List` is used, then at least it seems safe with generics, doesn't it?

**Comment by akarnokd** [comment]
Using array has reduced allocation cost and less indirection.

**Comment by hafs-r** [comment]
I've Singles of different types to run with Single.zip, and I'm getting ClassCastException as SingleZipIterable. Is it wrong zipping Singles of different type together?

**Comment by akarnokd** [comment]
You have to be careful which index you cast back to what type.

**Comment by hafs-r** [comment]
My Single.zip returns io.reactivex.internal.operators.single.SingleZipIterable but I'm expecting a Single<Object>, any Advice?

**Comment by akarnokd** [comment]
Please provide a standalone unit test that demonstrates your problem.
