### ISSUE TITLE
Maybe.just is not calling onComplete

### ISSUE THREAD

**Issue by mattinger** [ReactiveX/RxJava#4534]
If you create a MaybeObservable with Maybe.just("foo"), it is never triggering an onComplete call on the MaybeObserver.  Unless i'm missing something, shouldn't Maybe follow the same pattern as Observable?  Either:

observer.onSuccess
observer.onComplete

OR

observer.onError

**Comment by vanniktech** [comment]
AFAIK this is intended. It's either `onError | onComplete | onSuccess`

**Comment by mattinger** [comment]
So, it's either a value was loaded, a value was not loaded, or there was an error.  corresponding to onSuccess, onComplete and onError, respectively?

Is there documentation for 2.0?  That's something i was not able to really find.

**Comment by akarnokd** [comment]
See its javadoc: https://github.com/ReactiveX/RxJava/blob/2.x/src/main/java/io/reactivex/Maybe.java#L36

**Comment by akarnokd** [comment]
Flowable: `onSubscribe oNext* (onError | onComplete)?`
Observable: `onSubscribe oNext* (onError | onComplete)?`
Single: `onSubscribe (onSuccess | onError)?`
Completable: `onSubscribe (onError | onComplete)?`
Maybe: `onSubscribe (onSuccess | onError | onComplete)?`

Maybe is a hybrid of `Single` and `Completable` where only one of the `|`-ed method is called.

**Comment by mattinger** [comment]
Thanks.  On an unrelated note, any reason why there's no switchIfEmpty on Maybe?

**Comment by mattinger** [comment]
I suppose you can also close this issue.

**Comment by akarnokd** [comment]
I had to release RC2 because of a few annoying bugs and Maybe got in partially implemented. RC3 will have all reasonable operators added but you can use the 2.x snapshot right now which does already have `switchIfEmpty`.

**Comment by mattinger** [comment]
By the way. Maybe.switchIfEmpty(Single) is semantically a single if you haven't created that function yet. Bit would've a nice addition

**Comment by schwiz** [comment]
I am having the opposite problem! in version 2.1.4 calling Maybe.just(item) and my unit test is saying
java.lang.AssertionError: Completed! (latch = 0, values = 1, errors = 0, completions = 1)

How is this possible???
