### ISSUE TITLE
2.x: combineLatest typing is lost.

### ISSUE THREAD

**Issue by toonsevrin** [ReactiveX/RxJava#4545]
The "Function" parameter in the following methods
`Observable#combineLatest(Iterable, Function), line 157 
and Observable#combineLatest(Iterable, Function, int), line 188.`
it's typing does not work. And a ClassCastException is thrown.

**Reproduction:**

``` java
List<Observable<String>> observableList = Arrays.asList(Observable.just("a"), Observable.just("b"));
Observable<String> obs = Observable.combineLatest(observableList, new Function<String[], String>() {
  @Override
  public String apply(String[] strings) throws Exception {
    StringBuilder combined = new StringBuilder();
    Arrays.asList(strings).forEach(s -> combined.append(s));
    return combined.toString();
  }
});
obs.subscribe(string -> System.out.println(string));
```

**Exception:**

``` java
at io.reactivex.internal.operators.observable.ObservableCombineLatest$LatestCoordinator.drain(ObservableCombineLatest.java:242)
at io.reactivex.internal.operators.observable.ObservableCombineLatest$LatestCoordinator.combine(ObservableCombineLatest.java:197)
at io.reactivex.internal.operators.observable.ObservableCombineLatest$CombinerSubscriber.onNext(ObservableCombineLatest.java:342)
```

**Cause:**
[Misscast class](https://github.com/ReactiveX/RxJava/blob/2.x/src/main/java/io/reactivex/internal/operators/observable/ObservableCombineLatest.java#L81)

**Comment by akarnokd** [comment]
Thanks for the feedback. This is a known issue (#4524) and has been fixed in the RxJava 2 snapshots and will be available in RC3 (due in ten days). Use `Function<Object[], R>` directly.

**Comment by toonsevrin** [comment]
:+1: Very nice to hear.
