### ISSUE TITLE
Prevent release builds with the wrong version tag

### ISSUE THREAD

**Issue by akarnokd** [ReactiveX/RxJava#4553]
Currently, the build script reads the release tag and assigns that to the built RxJava library. One should chose the tag to build on that screen (1.x, 2.x) but it looks too easy to forget to switch over to 2.x and now you have RxJava 1 code released with 2.x tag to maven.

It would be great if someone could figure out how and then a version check to `build.gradle` that refuses to build if the associated tag doesn't start with `1.`.

(An alternative I've been thinking of is to simply move 2.x under `ReactiveX/RxJava2` and have them separately.)

**Comment by zsxwing** [comment]
I usually manually tag the version locally, check the commit history (see the attached screenshot, it shows the branch names and tags in the history) and push the tag to GitHub, then just edit the release note for RxScala. This may be less error-prone.

<img width="614" alt="screen shot 2016-09-14 at 11 07 38 am" src="https://cloud.githubusercontent.com/assets/1000778/18524026/9c1bba1a-7a6b-11e6-8e41-6d096b14f6b2.png">

This special log is set using the following command. After running it, you can use `git lg` to show it.

```
git config --global alias.lg "log --color --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit --"
```

**Comment by akarnokd** [comment]
I guess I have to read [these environment variables](https://github.com/ReactiveX/RxJava/blob/1.x/gradle/buildViaTravis.sh#L13) from build.gradle and fail:

**Comment by akarnokd** [comment]
Closing via #4556
