### ISSUE TITLE
(Question) How to consume Observable from client-side

### ISSUE THREAD

**Issue by enelson** [ReactiveX/RxJava#456]
Sorry if this is not the best place to ask this, but I was looking for some quick suggestions. Specifically, if my service layer returns an Observable<?> to the controller, how does the client-side handle the eventual results of that observable? Normally, you would process the results of the service call in the controller, formate the response, and send that down to the client. What is the best, and most "FRP" way of doing this, so as to not tie up the request thread waiting for the results? If this question doesn't make sense, let me know and I'll try to rephrase. Thanks so much for you help in advance!

**Comment by jonefeewang** [comment]
@benjchristensen thanks ben ,your explanation make me more clear
