### ISSUE TITLE
Alternative to RxJavaErrorHandler

### ISSUE THREAD

**Issue by bobvanderlinden** [ReactiveX/RxJava#4566]
I'd like to catch unhandled errors that arise from Observables globally.

The documentation [here](https://github.com/ReactiveX/RxJava/wiki/Plugins) suggests to use `RxJavaPlugins.getInstance().registerErrorHandler`, but both `getInstance` and `RxJavaErrorHandler` are deprecated with no hints as what to use instead.

The documentation on error handling in RxJava [here](https://github.com/ReactiveX/RxJava/wiki/Error-Handling) also has no mention of globally handling errors.

I did find `RxJavaHooks.setOnError`, but I have not found any documentation on this, so I was unsure whether it should be used.

Is this still on-going work or can anyone suggest what to use as an alternative to `registerErrorHandler`?

**Comment by aaronweihe** [comment]
The documentation on the Wiki is probably outdated. If you look at the [java doc](http://reactivex.io/RxJava/javadoc/rx/plugins/RxJavaPlugins.html#getInstance%28%29) of `RxJavaPlugins#getInstance()`, it says 

> Deprecated. use the static methods of RxJavaHooks.

😄

**Comment by akarnokd** [comment]
Hi and thanks for the feedback. Those articles are a bit outdated and will be updated in a few days to better reflect the current status with 1.2.

> I did find RxJavaHooks.setOnError, but I have not found any documentation on this, so I was unsure whether it should be used.

There is not much to that method. By default, undeliverable exceptions are routed to `RxJavaHooks.onError` which then calls an `Action1<Throwable>` you can change via `RxJavaHooks.setOnError`.

Here is the [release](https://github.com/ReactiveX/RxJava/releases/tag/v1.1.7) info and the [PR](https://github.com/ReactiveX/RxJava/pull/4007)

**Comment by bobvanderlinden** [comment]
Thank you both for the feedback. `RxJavaHooks.setOnError` it is! I've made a PR that documents the new alternative (#4569).

**Comment by akarnokd** [comment]
Updated the [Plugins](https://github.com/ReactiveX/RxJava/wiki/Plugins) wiki page. Let me know if it's adequate for you.

**Comment by bobvanderlinden** [comment]
@akarnokd Yes, that makes things a lot more clear. Thank you!
