### ISSUE TITLE
Notify End of Use of An Object

### ISSUE THREAD

**Issue by sirinath** [ReactiveX/RxJava#4568]
For automatic resource management and disposing it would be needed to know when an object is no longer in use by an `Observable`. So is it possible to add a `do` event to notify the end of use of an object. End of use is when all notification have been fired an all subscribers have been notified and their `OnNext` methods have returned, if they are in a window or buffer the object is no longer in the windows or buffers.

Is it possible to target this for 2.0?

**Comment by akarnokd** [comment]
Yes, it's a good candidate for 2.0. We usually call it `doAfterNext`. PR welcome.

**Comment by sirinath** [comment]
`doAfterNext` would be useful indicate current stage (onNext is over) but again `doAfterUsing` may also be useful to imply the lifetime of the object is over and you can de allocate / dispose the resource used by the particular object in the sequence.

**Comment by akarnokd** [comment]
`doAfterNext` will be available in 2.0.1 tomorrow.
