### ISSUE TITLE
fromEmitter cleanup

### ISSUE THREAD

**Issue by davidmoten** [ReactiveX/RxJava#4577]
The rename of `Observable.fromAsync` to `Observable.fromEmitter` isn't quite complete in that the signature of `Observable.fromEmitter` still refers to an interface `AsyncEmitter` which I would like to rename to `Emitter`.

 I'm happy to make a PR. It would add a new method 

``` java
@Experimental
public static <T> Observable<T> fromEmitter(Action1<Emitter<T>> emitter, Emitter.BackpressureMode backpressure) ;
```

and I would deprecate this one:

``` java
public static <T> Observable<T> fromEmitter(Action1<AsyncEmitter<T>> emitter, AsyncEmitter.BackpressureMode backpressure);
```

Proceed with PR?

**Comment by akarnokd** [comment]
Yes, PR welcome.
