### ISSUE TITLE
Can combineLatest(a, b) trigger only once when a, b is triggered "at same time"?

### ISSUE THREAD

**Issue by molikto** [ReactiveX/RxJava#4587]
```
        BehaviorSubject<Integer> a = BehaviorSubject.create(0);
        BehaviorSubject<Integer> b = BehaviorSubject.create(0);

        Observable.combineLatest(a, b, Cu::pair).subscribe(ignore -> {
            Log.d("test", "trigger " + ignore.first + " " + ignore.second);
        });

        a.onNext(1);
        b.onNext(1);
```

the result is 

```
 D/test: trigger 0 0
 D/test: trigger 1 0
 D/test: trigger 1 1
```

Is there anyway I can make it only fire once 1 1? because I need the data to be consistent.

**Comment by JakeWharton** [comment]
Use `zip` instead?

**Comment by molikto** [comment]
@JakeWharton it is not necessary a b always fire the same time.

**Comment by JakeWharton** [comment]
They don't in your test. a clearly fires before b.

**Comment by molikto** [comment]
@JakeWharton does this helps https://github.com/square/sqlbrite/blob/master/sqlbrite/src/main/java/com/squareup/sqlbrite/BriteDatabase.java#L66 ? A single Subject?

**Comment by JakeWharton** [comment]
I don't know anything about your use case, but a single subject certainly give you more control over downstream emissions because they happen directly rather than delegating to a combining operator.

**Comment by molikto** [comment]
thx
