### ISSUE TITLE
2.x: Convert Observable to Single without a default value

### ISSUE THREAD

**Issue by vanniktech** [ReactiveX/RxJava#4588]
With the RC3 changes I don't see an easy way of converting an Observable into a Single without giving a default value.

How do you feel about adding methods for that?

**Comment by akarnokd** [comment]
@abersnaze didn't like throwing because being empty. Try your API through `Maybe` and `switchIfEmpty(Maybe.error())`.

**Edit** wrong method name, fixed.

**Comment by vanniktech** [comment]
`defaultIfEmpty(MaybeSource<T>)` does not exist

**Comment by akarnokd** [comment]
Yeah sorry, `switchIfEmpty()` (I sometimes mix the two as `defaultIfEmpty` delegates to `switchIfEmpty`).

**Comment by vanniktech** [comment]
I don't quite see how `switchIfEmpty` solves my original problem. `Maybe.switchIfEmpty()` still returns a `Maybe`.

Also I'd rather have a `NoSuchElementException` and fail early than passing in a default value when converting an Observable to Single.

**Comment by akarnokd** [comment]
You could restore `toSingle` (under `singleOrError`), only the surface API has been removed.

**Comment by vanniktech** [comment]
So basically add to Observable + Flowable:

`singleOrError`
`firstOrError`
`lastOrError`
`elementAtOrError`

**Comment by akarnokd** [comment]
Yes.

**Comment by vanniktech** [comment]
Alright cool will do

**Comment by abersnaze** [comment]
Does singleElement() error on more than one but not on empty?

**Comment by akarnokd** [comment]
Yes, that was kept and also why firstElement is there to ignore more without signalling.

**Comment by JakeWharton** [comment]
This can be closed right?
