### ISSUE TITLE
Some typos on What's different in 2.0 wiki page.

### ISSUE THREAD

**Issue by toyamah** [ReactiveX/RxJava#4591]
I found the following typos in [Operator differences](https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0#operator-differences).
1. At `isEmpty` row, *RC3 is written, so is not bold.  
2. At `first(Func1)` row, it remains using `first()` which was renamed to `firstElement` by **RC3**
3. At `last(Func1)` row, it remains using `last()` which was renamed to `lastElement` by **RC3**

**Comment by akarnokd** [comment]
Thanks! Fixed.
