### ISSUE TITLE
concatWith not called when exception thrown in a following flatMap

### ISSUE THREAD

**Issue by ufoscout** [ReactiveX/RxJava#4596]
Hi all,

I am struggling to understand why the concatWith() or onErrorResumeNext() Observables are never executed when an exception happens in a flatMap() call performed **after** the concatWith like in this unit test:

```
    @Test
    public void concatWithTest() {
        Observable.fromCallable(() -> {
            System.out.println("start");
            return "start";
        })
        .doOnError(e -> {
            System.out.println("doOnError");
        })
        .doOnCompleted(() -> {
            System.out.println("doOnCompleted");
        })
        .concatWith(Observable.fromCallable(() -> {
            System.out.println("concatWith");
            return "concatWith";
        }))
        .onErrorResumeNext(e -> {
            return Observable.fromCallable(() -> {
                System.out.println("onErrorResumeNext");
                return "onErrorResumeNext";
            });
        })
        .flatMap(firstname -> {
            System.out.println("flatMap");
            //throw new RuntimeException();
            return Observable.just(firstname);
        })
        .subscribe(new TestSubscriber<>());
    }
```

This test prints:

```
start
flatMap
doOnCompleted
concatWith
flatMap
```

Nevertheless, if in the last flatMap() an exception is thrown (uncomment the "throw new RuntimeException();" line in the unit test) then it prints:

```
start
flatMap
```

Surprisingly, the concatWith() is not called but not even the doOnCompleted(), doOnError() or onErrorResumeNext(). In our situation this involves that resources closed in those methods are never released (in our case an async database connection) when an exception is thrown somewhere in the chain.
The same behaviour is present in RxJava 1.1.10 and 1.2.0.

**Comment by davidmoten** [comment]
When you call `.doOnError` or `onErrorResumeNext` they handle errors reported _upstream_ of each call (your final `flatMap` is _downstream_). The first emission will eventually hit the final `flatMap` and provoke an error which will terminate the stream and unsubscribe the subscriber. The unsubscribe action in the subscriber would then initiate a chain of unsubscription actions up the observable chain. Naturally the `concatWith` never gets initiated.

You mention a need to release resources. To properly handle releasing resources a resource needs to be released on unsubscription (which happens after an error or completion or an explicit unsubscribe call). Have a look at the `Observable.using` method which handles this cleanly for you.

**Comment by ufoscout** [comment]
@davidmoten thanks for your reply, now things are a little bit more clear even if not very intuitive to me.
I have already investigated the `Observable.using`; however, I need to execute another Observable when the main one ends but it allows me to only execute a synchronous action. Could you please help me understand how to achieve my objective?
What I really need is to execute an observable in case of success (`concatWith` should be fine for this task) and another Observable in case of failure.

**Comment by akarnokd** [comment]
> What I really need is to execute an observable in case of success (concatWith should be fine for this task) and another `Observable` in case of failure.

The closest thing is the `flatMap` overload whose functions return `Observable` but is relatively expensive. There, you could map onNexts to `Observable.just()` and the other two event types to the `Observable` of your chosing.

**Comment by ufoscout** [comment]
@akarnokd Thanks for your support; however, I moved my code to rxjava 2.0 and, with my big surprise, in this new version the concatWith() method is called even when there are exceptions thrown downstream in a flatMap call. So in 2.0 my issue does not exist any more.

**Comment by akarnokd** [comment]
I've tried with both 2.x Flowable and Observable and if the `flatMap` throws, I get

```
start
flatMap
```

with them as well. Maybe you forgot to uncomment the throwing code? Nevertheless, it is the expected behavior.

**Comment by ufoscout** [comment]
@akarnokd 
I tested it again, this is my code:

```
    @Test
    public void concatWithTest() {
        Observable.fromCallable(() -> {
            System.out.println("start");
            return "start";
        })
        .concatWith(Observable.fromCallable(() -> {
            System.out.println("concatWith");
            return "concatWith";
        }))
        .onErrorResumeNext(e -> {
            return Observable.fromCallable(() -> {
                System.out.println("onErrorResumeNext");
                return "onErrorResumeNext";
            });
        })
        .flatMap(firstname -> {
            System.out.println("flatMap");
            throw new RuntimeException();
        })
        .subscribe(new TestObserver<>());
    }

```

If executed with 2.0.0-RC4 it prints:

```
start
flatMap
concatWith
```

but with 2.0.0-RC5 it prints 

```
start
flatMap
```

So my code was working fine with RC4 and now it is again broken :(

At this point I guess I should try what suggested by you some comments ago:

> The closest thing is the flatMap overload whose functions return Observable but is relatively expensive. There, you could map onNexts to Observable.just() and the other two event types to the Observable of your chosing.

but I don't understand exactly what it means. Would it be possible to provide a small example?

**Comment by akarnokd** [comment]
``` java
source.flatMap(
   v -> Observable.just(v.toString()),
   e -> Observable.just("error"),
   () -> Observable.just("complete")
);
```

**Comment by ufoscout** [comment]
@akarnokd I tried your solution but it still does not work the way I need. In fact, this test:

```
    @Test
    public void flatMapErrorHandling() {
        doSomething()
        .flatMap(firstname -> {
            System.out.println("flatMap");
            throw new RuntimeException();
        })
        .subscribe(new TestObserver<>());
    }

    Observable<String> doSomething() {
        return Observable.fromCallable(() -> {
            System.out.println("start");
            return "start";
        })
        .flatMap(
                v -> Observable.just(v),
                e -> Observable.fromCallable(() -> {
                    System.out.println("Error");
                    return "Error";
                }),
                () -> Observable.fromCallable(() -> {
                    System.out.println("Complete");
                    return "Complete";
                })
             );
    }
```

still prints:

```
start
flatMap
```

I cannot handle the error in the flatMap which is in the test method because it is only a consumer of a library that exposes the doSomething() method. 
It seems to me that RxJava here breaks the encapsulation principle, in fact, the behaviour of the doSomething() method is somewhat altered by outside interference.

The original java code before we moved to RxJava was as simple as:

```
    void doSomething(Consumer<Connection> consumer) {
        Connection connection = // get some type of connection somewhere
        try {
            consumer.accept(connection);
            connection.commit();
        } catch (Throwable e) {
            connection.rollback();
        } finally  {
            connection.close();
        }
    }
```

Now we are unable to handle the rollback-then-close case.
I am close to give in with this. I couldn't believe this was so incredibly complex to achieve with RxJava.

**Comment by akarnokd** [comment]
You should apply the 3-arg flatMap after the one that crashes.

What do you want to achieve with that connection example? Send a connection along a complex set of operators? Have you looked at `using`?

**Comment by ufoscout** [comment]
> What do you want to achieve with that connection example? Send a connection along a complex set of operators?

yes, and we want the connection to be closed at the end no matter the outcome.

> Have you looked at using?

yes, we tried. But with "using" the connection is closed too early, even with eager=false, so when we access the result set a "Connection is already closed" Exception is thrown.

**Comment by akarnokd** [comment]
Maybe you have to redesign the processing chain as well.

**Comment by akarnokd** [comment]
If you have further input on the issue, don't hesitate to reopen this issue or post a new one.
