### ISSUE TITLE
"404 not found" on picture "Observable.create(syncOnSubscribe)"

### ISSUE THREAD

**Issue by qwert2603** [ReactiveX/RxJava#4598]
It's 404 error while loading picture for
public static <S, T> Observable<T> create(SyncOnSubscribe<S, T> syncOnSubscribe){...}
The link from documentation is:
https://raw.githubusercontent.com/wiki/ReactiveX/RxJava/images/rx-operators/create-async.png
Rx version is 1.2.0.

**Comment by akarnokd** [comment]
Temporarily fixed both [create-sync](https://raw.githubusercontent.com/wiki/ReactiveX/RxJava/images/rx-operators/create-sync.png) and [create-async](https://raw.githubusercontent.com/wiki/ReactiveX/RxJava/images/rx-operators/create-async.png) with a non-graffle images. Unfortunately the javadoc view is skewed and requires a separate PR to RxJava itself to fix the width/height.
