### ISSUE TITLE
1.x @Beta and @Experimental annotations are annotated with itself. 

### ISSUE THREAD

**Issue by VictorAlbertos** [ReactiveX/RxJava#4608]
In branch 1.x both @Beta and @Experimental annotations are annotated with itself. That's not the case for the branch 2.x.

I don't understand the purpose of annotating those annotation with itself. Should they not be annotated?

**Comment by akarnokd** [comment]
No idea.

**Comment by zsxwing** [comment]
I guess it's added when they were experimental but we totally forgot to delete them. I think we can remove them now since they are definitely stable APIs.

@VictorAlbertos  could you submit a PR to remove them?

**Comment by VictorAlbertos** [comment]
Sure 👍
