### ISSUE TITLE
1.x: remove NotificationLite fields?

### ISSUE THREAD

**Issue by davidmoten** [ReactiveX/RxJava#4611]
I notice a lot of field declarations in `Subscriber` subclasses like below (assignment usually happens in the constructor). I assume this is unnecessary allocation and we could use a local variable or the whole `NotificationLite.instance()` and perhaps a cast or perhaps a local method `nl()` that does the typing (a good candidate for inlining by the JIT I imagine) .  The aim would be to maintain readability yet recover a bit of allocation. 

``` java
final NotificationLite<T> nl = NotificationLite.instance();
```

It's a pretty trivial change so if people want me to proceed with PR I'd do a bunch of classes at a time, probably spread over a few PRs just to reduce the review load, avoid conflict with other PRs, and to match my free time slots for doing it.

Proceed?

**Comment by akarnokd** [comment]
It would be better to turn it into a utility class with static methods and use it like in 2.x.

**Comment by davidmoten** [comment]
Thanks I'll have a look.

**Comment by JakeWharton** [comment]
This happened in #4621  :+1:

**Comment by akarnokd** [comment]
Closing via #4621
