### ISSUE TITLE
gh-pages: fromAsync() in "Creating Observables" wiki page

### ISSUE THREAD

**Issue by szymonkozak** [ReactiveX/RxJava#4618]
In this wiki page: https://github.com/ReactiveX/RxJava/wiki/Creating-Observables `fromAsync()` in 2 places should be replaced by `fromEmitter()` (in description of `create()` method also).
And link should be changed to:
http://reactivex.io/RxJava/javadoc/rx/Observable.html#fromEmitter(rx.functions.Action1,%20rx.AsyncEmitter.BackpressureMode)

**Comment by akarnokd** [comment]
Thanks! Fixed.

**Comment by szymonkozak** [comment]
@akarnokd Ok, but still in desctiption of `create()` is "consider fromAsync instead".

**Comment by akarnokd** [comment]
Right, thanks.
