### ISSUE TITLE
doOnCancel method not found

### ISSUE THREAD

**Issue by ufoscout** [ReactiveX/RxJava#4623]
The documentation reports that the doOnUnsubscribe() method has been renamed doOnCancel(); however, there is no such a doOnCancel() method in 2.0.0-RC3. For example, this code fails to compile:

```
Observable.just("").doOnCancel(() -> {});
```

**Comment by Mauin** [comment]
In that case the documentation is still outdated. The correct method you're searching for is `doOnDispose()`.

**Comment by akarnokd** [comment]
It's `Flowable.doOnCancel()` and `Observable.doOnDispose()`. I've updated the wiki page to clarify this.
