### ISSUE TITLE
2.x Flowable::amb(Iterable) and Observable::amb(Iterable) throw NP

### ISSUE THREAD

**Issue by VictorAlbertos** [ReactiveX/RxJava#4640]
I was working on #4633 and I found this behaviour, which is not consistent with the current implementation of Maybe::ambIterable, Single::ambIterable and Completable::ambIterable.

The next tests throws NP

``` java
@Test
public void Verify_Flowable_Amb_Iterable() throws InterruptedException {
  List<Flowable<String>> flowables = Arrays.asList(null, null, null);
  Flowable.amb(flowables).test();
}

@Test
public void Verify_Observable_Amb_Iterable() throws InterruptedException {
  List<Observable<String>> observables = Arrays.asList(null, null, null);
  Observable.amb(observables).test();
}
```

But for Maybe, Single and Completable the exception is catched and passed to the pipeline error.

Becase I'm using Flowable::amb(Iterable) and Observable::amb(Iterable) as a model to merge Maybe::ambIterable, Single::ambIterable and Completable::ambIterable into a single amb operator, I thought that Flowable::amb(Iterable) and Observable::amb(Iterable) should catch the error too. Doing something like [this](https://github.com/ReactiveX/RxJava/blob/2.x/src/main/java/io/reactivex/internal/operators/completable/CompletableAmbIterable.java#L130).

**Comment by akarnokd** [comment]
Yes, they should be signalling NPE. Since traversing the Iterable happens way before the subscription, you could just end the traversal via `EmptySubscription.error(npe, s)` right there and not even subscribe to any non-null source.

**Comment by VictorAlbertos** [comment]
Perfect, and I'll add some test to cover this scenario. 

Should I use the same PR to address both this issue and #4633?

**Comment by akarnokd** [comment]
It's up to you; if there is no conflicting changes, you can do it separately.
