### ISSUE TITLE
2.x: Guide for library developers

### ISSUE THREAD

**Issue by artem-zinnatullin** [ReactiveX/RxJava#4642]
// Few issues after attending Jake's talk about RxJava2.

It looks like we'll need a guide for library developers about what type to use (Flowable/Observable) with examples or better a decision tree.

Also, if library developer decided to return `Flowable`, which backpressure strategy should be applied or should it always be passed by user? Problem here is that change of backpressure strategy is actually breaking for clients, but is not braking in terms of type system.

**Comment by akarnokd** [comment]
It depends on what the library does. If it's GUI stuff then `Observable` is a prime candiate. If it does streaming I/O of some sort (parsing a file, getting items over the network, rows from the database) then it should use `Flowable`.

**Comment by artem-zinnatullin** [comment]
Ok, that's already ∞ times better than nothing! What about putting this to the Wiki page about RxJava 2 ("Observable and Flowable" section)?

**Comment by akarnokd** [comment]
https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0#which-type-to-use

Let me know if you find some other use cases which could be added.

**Comment by artem-zinnatullin** [comment]
👍
