### ISSUE TITLE
2.x: Remove/Hide Flowable BackpressureMode.NONE?

### ISSUE THREAD

**Issue by artem-zinnatullin** [ReactiveX/RxJava#4643]
So, we have `Observable` for nbp streams and `Flowable` for bp streams.

What I'm afraid of is that a lot of users will do `Flowable.create(emitter, BackpressureMode.NONE)` or `toFlowable(BackpressureMode.NONE)` while in fact they should use `Observable`.

The only correct usage of `BackpressureMode.NONE` I see at the moment is RS interop since `Observable` is not RS type (please share other valid cases that can't be changed to `Observable`).

I might be overworrying of course, so opinions of project members are very appreciated.

**Comment by akarnokd** [comment]
The `NONE` can be used if you use `onBackpressureBuffer(int capacity)` or other parametrized `onBackpressureXXX` method. The default enums only support the parameterless behavior of `onBackpressureXXX`s.

**Comment by akarnokd** [comment]
```
        /**
         * OnNext events are written without any buffering or dropping.
         * Downstream has to deal with any overflow.
         * <p>Useful when one applies one of the custom-parameter onBackpressureXXX operators.
         */
        NONE,
```

**Comment by artem-zinnatullin** [comment]
Yeah I see, hm. But isn't it kind of weird to create Flowable with no
backpressure strategy and apply afterwards If you can accept it from client
and use it at creation time?

**Comment by artem-zinnatullin** [comment]
So, what should we do about it? 

I still think that it's kind of weird to have such easily-available API that can and probably will be misused pretty often and as a result will lead to `MissingBackpressureException` though one of the ideas of `Flowable` was to move Backpressure to type level and force users to handle it while `BackpressureMode.NONE` basically disables that.

Closest semantic problem I can think of is `Observable.create()` in RxJava v1 which was misused so often that we had to "deprecate" it.

> The NONE can be used if you use onBackpressureBuffer(int capacity) or other parametrized onBackpressureXXX method. The default enums only support the parameterless behavior of onBackpressureXXXs.

@akarnokd what if we add APIs to apply parametrized `onBackpressureXXX()` at creation time?

cc @JakeWharton, we've discussed that offline a little bit and I would like to invite you to discussion here.

**Comment by akarnokd** [comment]
> what if we add APIs to apply parametrized onBackpressureXXX() at creation time?

Either you supply a varargs of options or introduce 8+ overloads.

> I still think that it's kind of weird to have such easily-available API that can and probably will be misused pretty often.

Here, the user puts in the mode parameter and is explicit. So if someone reports a MissingBackpressureException and posts a create(..., NONE), that's a clear indication of the user error.

**Comment by artem-zinnatullin** [comment]
> Here, the user puts in the mode parameter and is explicit. So if someone reports a MissingBackpressureException and posts a create(..., NONE), that's a clear indication of the user error.

Yes, but I'm not sure that a lot of users will understand that `BackpressureMode.NONE` basically `== MissingBackpresssureException`.

And even worse that when you use already created `Flowable` you can't be sure that it handles backpressure which basically `==` situation with `Observable` in RxJava v1.

**Comment by akarnokd** [comment]
Lot of users copy from examples and so far, almost all 2.x create examples used `BackpressureMode.BUFFER`.

> you can't be sure that it handles backpressure

If you wrote the `create()`, then it's on you. If you get a `Flowable` somewhere and fails, you can check the source code of the provider and apply the missing operator. If no source available, complain to the developer who created it.

**Comment by artem-zinnatullin** [comment]
Can't completely agree. Ok, what about renaming `BackpressureMode.NONE` to something that mentions consequences of its usage? I'm bad at naming: `UNSAFE_NONE`, etc.

**Comment by akarnokd** [comment]
If you find a good name...

**Comment by artem-zinnatullin** [comment]
Variants from my team: `MISSING`, `UNSAFE_NONE`, `TODO`, `UP_TO_DOWNSTREAM`.

I really like `MISSING` because it matches `MissingBackpressureException`.

**Comment by JakeWharton** [comment]
UNSUPPORTED

**Comment by adi1133** [comment]
Why not force the user to create an Observable in this situation ?
Seems counter intuitive to allow non backpressure data in Flowable, this also voids the reactive streams specification. Am I wrong ?

**Comment by akarnokd** [comment]
Alright, `MISSING` is compact enough. PR welcome.

**Comment by akarnokd** [comment]
Closing via #4767
