### ISSUE TITLE
1.2.1 preparations

### ISSUE THREAD

**Issue by akarnokd** [ReactiveX/RxJava#4649]
#### API enhancements
- [Pull 4555](https://github.com/ReactiveX/RxJava/pull/4555): enhance generics of `doOnError` and `doOnRequest`
- [Pull 4580](https://github.com/ReactiveX/RxJava/pull/4580): rename `AsyncEmitter` to `Emitter`
#### Performance enhancements
- [Pull 4621](https://github.com/ReactiveX/RxJava/pull/4621): `NotificationLite` - reduce allocations
- [Pull 4648](https://github.com/ReactiveX/RxJava/pull/4648): rework `Single` internals to reduce overhead and stack depth
#### Deprecations
- [Pull 4580](https://github.com/ReactiveX/RxJava/pull/4580): `CompletableEmitter.setCancellation` will change its type in 1.2.2.
- [Pull 4648](https://github.com/ReactiveX/RxJava/pull/4648): Deprecate `Single(Observable.OnSubscribe)` constructor
#### Bugfixes
- [Pull 4641](https://github.com/ReactiveX/RxJava/pull/4641): `SafeSubscriber` not to call `RxJavaHooks` before delivering the error

**Comment by davidmoten** [comment]
👍 thanks @akarnokd

**Comment by zsxwing** [comment]
👍

**Comment by akarnokd** [comment]
Closing via https://github.com/ReactiveX/RxJava/releases/tag/v1.2.1
