### ISSUE TITLE
2.x: Possible 6.x/Android compatibility issue

### ISSUE THREAD

**Issue by ZacSweers** [ReactiveX/RxJava#4653]
If I have an Android app targeting source compatibility 1.8, I get the following exception at runtime on a 7.0 device:

```
FATAL EXCEPTION: RxSchedulerPurge-1
     Process: io.sweers.catchup.debug, PID: 29250
     java.lang.NoSuchMethodError: No virtual method keySet()Ljava/util/concurrent/ConcurrentHashMap$KeySetView; in class Ljava/util/concurrent/ConcurrentHashMap; or its super classes (declaration of 'java.util.concurrent.ConcurrentHashMap' appears in /system/framework/core-libart.jar)
         at io.reactivex.internal.schedulers.SchedulerPoolFactory$1.run(SchedulerPoolFactory.java:69)
         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
         at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:278)
         at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:273)
         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
         at java.lang.Thread.run(Thread.java:761)
```

The exact line is:

``` java
for (ScheduledThreadPoolExecutor e : new ArrayList<ScheduledThreadPoolExecutor>(POOLS.keySet())) {  // CHM.keySet returns KeySetView in Java 8+; false positive here
```

When I look at it in the debugger, it is indeed a KeySetView, but I'm not sure what the issue is here. Let me know if this would be better served posting in RxAndroid.

CC @JakeWharton

**Comment by ZacSweers** [comment]
Interestingly, if I breakpoint this line, the rest of the app appears to run just fine and isn't blocked. As soon as I let it pass though, it crashes.

**Comment by akarnokd** [comment]
Java 8 changed the return type of `keySet` and it trips AnimalSniffer as well. In theory, by compiling with javac 7, there should be no binding to Java 8's type there.

**Comment by ZacSweers** [comment]
doesn't that come at the expense of being able to target Java 8 entirely though?

**Comment by akarnokd** [comment]
Let's see if http://stackoverflow.com/a/32955708/61158 works for us as well.

**Comment by akarnokd** [comment]
While you are at this, could you post a PR with the fix above?

**Comment by ZacSweers** [comment]
Looks like that fixed it when I test locally, will upload a PR in a sec

**Comment by akarnokd** [comment]
Closing via #4654.
