### ISSUE TITLE
2.x: Should Observable.compose() use its ObservableTransformer?

### ISSUE THREAD

**Issue by dlew** [ReactiveX/RxJava#4656]
Along the same lines as #4650, is there a reason why `Observable.compose()` doesn't use the (already in existence) `ObservableTransformer`?

**Comment by akarnokd** [comment]
Yes.

**Comment by ferhatparmak** [comment]
Great answer

**Comment by akarnokd** [comment]
It was simply overlooked. PR velcome

**Comment by dlew** [comment]
Thanks for fixing this in #4658.
