### ISSUE TITLE
Subscriber unsubscribe doubt

### ISSUE THREAD

**Issue by kennedyoliveira** [ReactiveX/RxJava#4657]
Hello!

I'm with a doubt about the unsubscribe process and memory related stuff, today i faced a simple case that made me wonder, the case is, i have a web Event Stream that i'll send some information when receive a request, but this information is sent with an interval, suppose each 500 milliseconds, and when the request ends, i want to clear all the resources allocated so i don't get a memory leak, the simplified code looks like this:

``` java
final Subscription metricsSubscription = Observable.interval(delay, TimeUnit.MILLISECONDS, scheduler)
                                                   .map(i -> new DashboardData(HystrixCommandMetrics.getInstances(),
                                                                               HystrixThreadPoolMetrics.getInstances(),
                                                                               HystrixCollapserMetrics.getInstances()))
                                                   .concatMap(dashboardData -> Observable.from(SerialHystrixDashboardData.toMultipleJsonStrings(dashboardData)))
                                                   .subscribe(metric -> writeMetric(metric, response),
                                                              ex -> log.error("Error sending metrics", ex));
```

Pretty simple, when the request ends, the client disconnect, i call:

``` java
metricsSubscription.unsubscribe();
```

What happens to the interval observable? It'll stop emitting events, but it'll be garbage collected?

**Comment by akarnokd** [comment]
The internal sequences should become collectable but it is possible that holding the `Subscription` reference itself may keep alive components. Use `onTerminateDetach` to make sure that doesn't happen.

**Comment by kennedyoliveira** [comment]
@akarnokd thank you for your response, so basically the code is correct, the problem would be the `Subscription` reference as you state, so basically, if there are no problems with references, unsubscribing would clean everything that needs to be clean so the observable can stop and be collected?

**Comment by akarnokd** [comment]
Yes.

**Comment by kennedyoliveira** [comment]
@akarnokd thanks for clarifying things out, i didn't know about this onTerminateDetach, it was implemented recently or i missed it?

Another thing, there is any performance impact using it?

**Comment by akarnokd** [comment]
A couple of patch versions before.

> Another thing, there is any performance impact using it?

It has minimal overhead, just like an extra `map` or `filter`.

**Comment by kennedyoliveira** [comment]
@akarnokd thank you very much for the information, very helpful!
