### ISSUE TITLE
2.x: ElementAt Operators in Observable and Flowable don't behave correctly on empty sources

### ISSUE THREAD

**Issue by vanniktech** [ReactiveX/RxJava#4680]
`elementAtOrError(1)` on an empty source just leaves the new Single hanging without signalling `onError()`:

``` java
Observable.empty()
    .elementAtOrError(1)
    .test()
    .assertFailure(NoSuchElementException.class);
```

`elementAt(1)` on an empty source just leaves the Maybe hanging without signalling `onComplete()`:

```
Observable.empty()
    .elementAt(1)
    .test()
    .assertResult();
```

Just tested this against RC4. Happy to fix this.

**Comment by akarnokd** [comment]
Sure.

**Comment by akarnokd** [comment]
Closing via #4681
