### ISSUE TITLE
2.x: Observable.range(long start, long count)

### ISSUE THREAD

**Issue by vanniktech** [ReactiveX/RxJava#4683]
I'd like to have a range of long values as an Observable however only a range method with ints do exist. Is there a reason for this?

The only way I could imagine doing this now would be by using `intervalRange` with a low period however that does not seem right.

**Comment by akarnokd** [comment]
Nobody wanted to have more than 2^31 elements and you can map an int to long via `map`.

**Comment by davidmoten** [comment]
I've often wanted a range that wouldn't run out. Using 1.x when I call 

```
Observable.range(1, Integer.MAX_VALUE).subscribe();
```

it completes in 6 seconds. Sure I can manufacture a `rangeLong` myself but library support might be nice.

**Comment by akarnokd** [comment]
PR welcome. You may call it rangeLong() to avoid overload problems down the line.

**Comment by vanniktech** [comment]
Alright will add it for Flowable too

**Comment by vanniktech** [comment]
Should I copy the existing classes and just them to work on long instead of int or should I make them reusable?

**Comment by akarnokd** [comment]
Copy.

**Comment by akarnokd** [comment]
Closing via #4687.
