### ISSUE TITLE
Observable.using async resource factory?

### ISSUE THREAD

**Issue by kennedyoliveira** [ReactiveX/RxJava#4700]
Hello,

i have a use case where i will use a resource that need to be released after usage, so i thought the `Observable.using` fit in these case, but i obtain the resource from a `Observable` that could do a network call if it's not available local.

The resource is a session identifier with expiration time, so when it's not expired i have it local and it's fast, otherwise i do a network call, but the problem is, the `Observable.using` resourceFactory (first param), is a `Func0`, and i don't want to block inside it with `toBlocking.single`, how could i use it? Is there any alternative?

Here is an example code, i wan't to remove the blocking part

``` java
return Observable.using(
      // create resource
      () -> getSession().toBlocking().single(), // i don't want to do that!
      // use it
      session -> doWork(session), // returns a observable
      // release
      session -> // release session,
      true)
```

**Comment by akarnokd** [comment]
FlatMap over it and have it as a constant in using.

``` java
getSession()
.flatMap(session -> Observable.using(() -> session, s-> doWork(s), s -> { }));
```

**Comment by kennedyoliveira** [comment]
@akarnokd I just thought about this solution when I woke up, maybe I just needed some sleep haha, anyway thank you!
