### ISSUE TITLE
1.x: Replaying a `Single` to future subscribers. cache() missing?

### ISSUE THREAD

**Issue by JakeWharton** [ReactiveX/RxJava#4702]
As far as I can tell, there isn't a way to replay a `Single`'s result to future subscribers without re-subscribing upstream or round-tripping through an `Observable` for `cache()`. This has come up 3 times in various channels with no good answer found.

Is `cache()` missing? Or is there some other way of doing this that I can't see?

**Comment by akarnokd** [comment]
So far, nobody complained about it for 1.x. PR welcome.

**Comment by akarnokd** [comment]
Closing via #4757.
