### ISSUE TITLE
Subject should throw exception when calling onNext after onComplete

### ISSUE THREAD

**Issue by runningcode** [ReactiveX/RxJava#4703]
```
PublishSubject publishSubject = PublishSubject.create();
publishSubject.onCompleted();
publishSubject.onNext(new Object());
```

In 1.x you can call onNext after onCompleted and no exception will be thrown. 
I think it should throw an exception, but maybe it isn't possible to reliably assert that the observable hasn't completed before calling onNext when dealing with different threads.

**Comment by akarnokd** [comment]
This change would break the expectation that these methods don't throw. Why do you call onNext after onComplete?

**Comment by runningcode** [comment]
Maybe `onCompleted` and `onNext` are called from different threads. I guess that's the problem with subjects anyways. :\

**Comment by akarnokd** [comment]
Then you should use `toSerialized` and work with that `Subject` as regular `Subject`s are not thread safe. If you work with `SerializedSubject` then there is no reason to penalize that thread that didn't and can't know some other thread brought the `Subject` to a terminal state.

**Comment by runningcode** [comment]
Ah ok. Perhaps I misunderstood that RxJava enforces the contract. It only guarantees that Observers receive events that follow the contract by wrapping Observers inside a SafeSubscriber.
