### ISSUE TITLE
2.x: Remove checked exceptions from transformer interfaces?

### ISSUE THREAD

**Issue by JakeWharton** [ReactiveX/RxJava#4709]
Now that transformers are not `Function` extensions, does it makes sense that they allow throwing checked exceptions? When a transformer is being invoked, its job is taking an observable and _transforming_ it into another observable but not actually doing any real work. Thus, it seems strange that you would ever encounter something that threw a checked exception in this operation. It would be a sign that you need to move that work into the stream pipeline instead of the observable creation pipeline.

This also makes code that has to deal with transformers annoying because they now have to handle (aka wrap and throw) these checked exceptions.

Happy to send a PR, but wanted to get some thoughts first and make sure I wasn't missing anything.

**Comment by akarnokd** [comment]
Works for me both ways so its up to the community to decide.

**Comment by JakeWharton** [comment]
Ok. Sent a PR for it. No rush to merge if you want to wait for other opinions.

**Comment by dlew** [comment]
I'm a fan of this change, for the reason stated above - due to its nature, a transformer should rarely (never?) be throwing a checked exception.

**Comment by akarnokd** [comment]
I thought about it and couldn't find a reason to allow throwing there.

Closing via #4710.
