### ISSUE TITLE
1.x - Throwing an error in single's onError does not propagate to outside of the class

### ISSUE THREAD

**Issue by ZakTaccardi** [ReactiveX/RxJava#4719]
Sometimes, we have to leave the reactive world. I'm in a scenario (because of an external library) where I need to catch an exception thrown within a stream outside of the stream as a `OnErrorFailedException`. This works for observables, but not singles. Singles swallow the exception, Observables throw it

Wrote an test that reveals this issue in Kotlin, but happens in java too.

![Screenshot of results](http://i.imgur.com/5JtEJ8o.png)

```
class SingleExampleTest {

    @Test(expected = OnErrorFailedException::class)
    fun single() {
        Single.just(null)
                .map { throw Exception() }
                .subscribe(
                        {},
                        { e -> throw e }
                )
    }

    @Test(expected = OnErrorFailedException::class)
    fun observable() {
        Observable.just(null)
                .map { throw Exception() }
                .subscribe(
                        {},
                        { e -> throw e }
                )
    }

    @Test(expected = OnErrorFailedException::class)
    fun singleToObservable() {
        Single.just(null)
                .map { throw Exception() }
                .toObservable()
                .subscribe(
                        {},
                        { e -> throw e }
                )
    }
}
```

Using versions: `1.2.1` of RxJava and `0.60.0` of rxKotlin.

**Comment by ZakTaccardi** [comment]
note: `Completable` swallows the exception as well.

**Comment by akarnokd** [comment]
There is no `SafeSingleSubscriber` that would handle a failing call to `onError` and you are not supposed to throw from `onError`. The rethrown exception goes into the `RxJavaHooks.onError` handler.

**Comment by ZakTaccardi** [comment]
I'm using a [job queue library](https://github.com/yigit/android-priority-jobqueue#show-me-the-code) that has a `void onRun() throws Throwable` method.
- when `onRun` completes without exception, the job is considered a "success"
- when `onRun` throws an exception, the job is considered "failed" (so it can be retried later).

Within `onRun()`, I execute a synchronous observable. How should I throw an in-stream Rx exception from this synchronous observable to the outer `onRun()` method, then?

**Comment by JakeWharton** [comment]
CountDownLatch + AtomicReference<Throwable> + subscribe(new
SingleObserver() { ... })

**Comment by akarnokd** [comment]
Or `toBlocking().lastOrDefault(null)`.

**Comment by ZakTaccardi** [comment]
thanks! I'll probably just extend the `Job` class in this library and provide a base class that blocks the `onRun()` method from completing until `jobSuccess()` or `jobFailed(Throwable throwable)` are manually called to be more Rx friendly.
