### ISSUE TITLE
2.x: PublishSubject and serialize()

### ISSUE THREAD

**Issue by davidmoten** [ReactiveX/RxJava#4724]
When `PublishSubject.onNext()` is called from multiple threads it can be necessary to use `subject.serialize()` in the observable chain instead of just `subject`.

This is a sharp edge in RxJava that users frequently get cut on. What about we make serialized emission the default and advanced users can opt out for performance reasons when appropriate.

We might end up with `PublishSubject.create()` (serialized) and `PublishSubject.createUnserialized()`.

I haven't considered the other `Subject` implementations yet.

Happy to make PR if people interested.

**Comment by akarnokd** [comment]
I have doubts about this idea. There must be a line drawn where we try to save the users from themselves.

**Comment by djodjoni** [comment]
I am also not that much in favor of implicitly serializing the Subject for the users. For lots of(most of) the use cases I encountered ppl use Subjects in the form of 1 inlet many outlets and this single input calls onNext form a single thread. This will also create inconsistency of API and behavior of 1.x and 2.x.

**Comment by JakeWharton** [comment]
Inconsistency between major versions is the whole point of bumping the
major version so that argument should not apply.

But I too don't think this should be the default. Concurrent publishing
seems rare to me and probably served with better abstractions such as two
create()s and merge().

**Comment by artem-zinnatullin** [comment]
I vote for serialized behavior by default and different create() method to
create unsafe non-serialized instance.

RxJava does this for you in many places like merge(), zip(), and so on,
subjects should be safe by default too.

**Comment by akarnokd** [comment]
I could imagine a new subject type: `DispatchSubject` or `BusSubject` that serializes by default and can optinonally suppress terminal events on its input side.

**Comment by akarnokd** [comment]
Closing as no changes for now.

**Comment by arturdryomov** [comment]
Is there any chance to revisit this for `3.x`?

Writing this after fighting yet another multi-threading issue related to not serialized `Subject`.
