### ISSUE TITLE
2.x Why is FlowableEmitter.BackpressureMode and BackpressureStrategy not merged

### ISSUE THREAD

**Issue by adipascu** [ReactiveX/RxJava#4727]
Why are the two enums not merged into one, they both serve the same purpose and both places where they are used should have the same features.

Also because 
`BackpressureStrategy.NONE` does not exist, I currently can not use a `BufferStrategy` on an `Observable`

I don't think this code is simple easy

``` java
Observable.toFlowable(BackpressureStrategy.NONE)
.onBackpressureBuffer(10, Functions.EMPTY_ACTION, BackpressureOverflowStrategy.DROP_OLDEST)
```

**Comment by akarnokd** [comment]
If you can make it work, then PR welcome.

**Comment by akarnokd** [comment]
Closing via #4729
