### ISSUE TITLE
how can I use rxjava with grpc?

### ISSUE THREAD

**Issue by macjay** [ReactiveX/RxJava#4733]
as title

**Comment by akarnokd** [comment]
No idea. Maybe someone on StackOverflow has experience with GRPC, such as [this](http://stackoverflow.com/questions/36613214/kotlin-grpc-streamobserver-to-deletate-to-rx-publishsubject).

**Comment by macjay** [comment]
thank you

**Comment by akarnokd** [comment]
Great!

**Comment by rmichela** [comment]
There is now a project solving this problem: https://github.com/salesforce/reactive-grpc
