### ISSUE TITLE
fromEmitter same-pool deadlock

### ISSUE THREAD

**Issue by akarnokd** [ReactiveX/RxJava#4735]
This affects both 1.x and 2.x.

There is a question on [StackOverflow](http://stackoverflow.com/questions/40145203/rxjava-observable-fromemitter-odd-backpressure-behaviour) where the example program hangs after it delivered the default bufferSize elements until the `fromEmitter` source completes.

The problem is that `subscribeOn` schedules the downstream's replenishing `request` on the same thread that is busy/sleeping and has no opportunity to update its internal requested amount. We had similar problems with `onBackpressureBlock` which had to be dropped.

We could introduce a `subscribeOn` mode in which it doesn't reschedule the `request` from downstream but it will confuse some and make wonder others.

**Comment by akarnokd** [comment]
This was resolved in 2.x by making sure a `subscribeOn` after `create` doesn't reschedule downstream requests.

**Comment by bobvanderlinden** [comment]
I think I'm running into this problem as well. `fromEmitter` suddenly stops emitting `onNext` items whereas the emitter itself is still being called.

I was using a single-thread-scheduler for the emitter, so I thought (from your explanation) that moving to a threadpool would resolve the problem. It apparently does not for my case. I'm probably misunderstanding what is going on behind the scenes.

Do you have any suggestions on how to workaround this issue (without moving to 2.x).

**Comment by akarnokd** [comment]
@bobvanderlinden Yes, use the NONE policy and apply `onBackpressureXXX` *after* `subscribeOn`.

**Comment by bobvanderlinden** [comment]
@akarnokd That works like a charm! Thanks a lot!

**Comment by akarnokd** [comment]
Closing via #5091 for 1.x  and #4770 for 2.x.
