### ISSUE TITLE
Changes from 2.0.0-RC5 to 2.0.0 final

### ISSUE THREAD

**Issue by Mauin** [ReactiveX/RxJava#4741]
I didn't find any details in the README/Wiki.

What will be the changes that still go into 2.x until the final release? Is the API considered stable for now and the final release will pretty much just bump the version number, aside from internal bugfixes or should we expect more changes until the final release?

So as library developers, could one prepare a RxJava2 variant which uses RC5 and just bump the version to final 2.0.0 to release a 2.x variant of the library?

**Comment by akarnokd** [comment]
I'll continue with the coverage work and in case we stumble upon an API problem, we will add RC6. You could help by walking through the API looking for mistakes or inconsistencies.

**Comment by Mauin** [comment]
👍 Thanks for the explanation, then I'll start updating some of my older 2.0.0-RC1/2 branches to see.
