### ISSUE TITLE
2.x - Subscription.request(0) doesn't signal onError

### ISSUE THREAD

**Issue by otal1105** [ReactiveX/RxJava#4753]
According to Reactive Streams, `Subscription.request(0)` must signal onError with IllegalArgumentException.

However, it doesn't signal onError. Instead, it just calls `Throwable.printStacktrace`.

I tried the below code with RxJava-2.0.0-RC5

``` java
    Flowable.range(1, 3).subscribe(new Subscriber<Integer>() {

      @Override
      public void onSubscribe(Subscription s) {
        s.request(0L);
      }

      @Override
      public void onError(Throwable e) {
        System.err.println("error");
      }
      ...
    }
```

The cause is that `Consumer<Throwable> f` is null in `RxJavaPlugins.onError`.

**Comment by akarnokd** [comment]
True. The spec is too harsh there and requires very high overhead to support a case which should be considered a bug. We report it to the plugins and keep going. 

Hopefully a next version of the spec will losen this requirement and a few others.

Why do you request 0 btw?

**Comment by otal1105** [comment]
I found this when I was checking the behavior of `Subscrition.requet`. 
So, I really don't have the use case of this. 
Maybe, it might happen when the number were created dynamically.
So, there may be a little possibility to request 0 without accidents.

However, there might be a danger to become a bug which were not easy to be found.
Since the flowable which were requested 0 just quits without emitting onError, throwing an exception, or calling cancel.  
Also, I wonder what status (completed, error, canceled) the flowable become when 0 was requested.

Additionally, the behavior were different between the kinds of Flowable.
When I tried the flowable from `Flowable.create`, it emits onComplete, although the flowable from `Flowable.range` doesn't.

``` java
Flowable.create(emitter -> {
      emitter.onNext(1);
      emitter.onNext(2);
      emitter.onNext(3);
      emitter.onComplete();
    }, BackpressureStrategy.DROP)
    .subscribe(new Subscriber<Integer>() {

      @Override
      public void onSubscribe(Subscription s) {
        s.request(0L);
      }
      ...
  });
```

So, it might be no problem if all kinds of Flowable would act the same.
I even think it might be no problem to act like `request(Long.MAX_VALUE)`, if it clearly states so,

**Comment by akarnokd** [comment]
We practically ignore 0 requests beyond calling `RxJavaPlugins.onError`. Simply make sure you don't call with zero and if you dynamically generate the request amount (I don't see why you would do that), simply check for zero yourself before calling `request`. You should install a logger to track such extra errors and look for the error entries.

Create with drop drops elements because you don't request any positive amount but onComplete is not part of backpressure logic and goes through. Range waits for requests and won't run ahead skipping elements thus it won't complete.

**Comment by otal1105** [comment]
OK! I understand the behavior about 0 request.
The reason to ignore 0 requests is also understandable.
Thank you for answering my questions.

However, It's might be better if the things that don't follow the Reactive Streams spec were listed in Wiki. Since Reactive Streams have Subscriber and Subscription interfaces, RxJava's javadoc cannot cover about this.

If I had a better English skill, I would send PullRequest for wiki because you guys would be very busy since the stable release were coming soon.

**Comment by akarnokd** [comment]
I've added a section to the wiki: https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0#reactive-streams-compliance

**Comment by otal1105** [comment]
Thank you very much!!
