### ISSUE TITLE
Regression in Single.takeUntil() in 1.2.1

### ISSUE THREAD

**Issue by dlew** [ReactiveX/RxJava#4768]
The following test passes in 1.2.0 but fails in 1.2.1:

```
@Test
public void singleTakeUntil() {
    PublishSubject<String> controller = PublishSubject.create();

    TestSubscriber<String> testSubscriber = new TestSubscriber<>(0);

    Single.just("Hello")
        .takeUntil(controller)
        .subscribe(testSubscriber);

    controller.onNext("Stop flow");

    testSubscriber.requestMore(1);
    testSubscriber.assertNoValues();
    testSubscriber.assertError(CancellationException.class);
}
```

It looks like `Single` emits regardless of whether it was requested or not. (I can reproduce this using `defer()` as well, so it's not just `just()`).

The same behavior is not seen in `Observable.takeUntil()` (it still works in all of my tests).

First noticed via https://github.com/trello/RxLifecycle/pull/158

**Comment by akarnokd** [comment]
Actually, this is the expected behavior. When you subscribe, just signals and the whole sequence is terminated. Then you get the control back and call `controller.onNext` which doesn't have any subscribers anymore.

**Comment by akarnokd** [comment]
> It looks like Single emits regardless of whether it was requested or not.

Single doesn't support backpressure. The transition to Subscriber has a one element buffer that makes sure the Subscriber receives the element already emitted when requested. By the time there is a request, the buffer already contains the emitted value.

**Comment by dlew** [comment]
Why did the test used to pass, then?

**Comment by akarnokd** [comment]
In 1.2.0, the code worked essentially like this:

``` java
Single.just("Hello")
        .toObservable()                     // <--------------------
        .takeUntil(controller.map(v -> { throw new CancellationException(); }))
        .subscribe(testSubscriber);
```

After the internal restructuring of 1.2.1, it works like this:

``` java
Single.just("Hello")
        .takeUntil(controller)
        .toObservable()                     // <--------------------
        .subscribe(testSubscriber);
```

The `toObservable` marks the position of the backpressure-aware single element buffer. In 1.2.0 it was before the operator so the `1` was held in the buffer and not emitted due to lack of requests. When the `subscribe()` returned, the `controller` was still active.

**Comment by dlew** [comment]
Alright, so it seems that it's just my tests that are the problem (since they assume that `Single` is backpressure aware). If I redesign them without backpressure then they should work fine.
