### ISSUE TITLE
doOnUnsubscribe() not called for Single 

### ISSUE THREAD

**Issue by AntonHolovin** [ReactiveX/RxJava#4772]
I've just noticed that `doOnUnsubscribe` not called when I use `Single` along with `observeOn(AndroidSchedulers.mainThread())`. 

For example this code

``` java
 Single.fromCallable(() -> 42)
    .subscribeOn(Schedulers.io())
    .observeOn(AndroidSchedulers.mainThread())
    .doOnSubscribe(() -> Log.d(MainActivity.class.getName(), "subscribed"))
    .doOnUnsubscribe(() -> Log.d(MainActivity.class.getName(), "unsubscribed"))
    .subscribe(integer -> Log.d(MainActivity.class.getName(), "got result"));
```

will provide next output: "subscribed", "got result"

I also tested this code with `observeOn(Schedulers.immediate())` and I got correct output.

**Comment by akarnokd** [comment]
Thanks for reporting. This has been fixed already in the snapshot version and will be part of 1.2.2.

**Comment by akarnokd** [comment]
Closing via 1.2.2
