### ISSUE TITLE
2.x: queue drain pattern and Long.MAX_VALUE optimisation

### ISSUE THREAD

**Issue by davidmoten** [ReactiveX/RxJava#4774]
@akarnokd Nice work on the RxJava 2 writing operators wiki page by the way. Looking forward to reading more as it gets fleshed out.

I was curious about the queue-drain pattern that we don't look to reduce volatile reads when `Long.MAX_VALUE` is requested. Setting a mutable non-volatile boolean field `unbounded` (or whatever) to true the first time that `requested.get()` returns `Long.MAX_VALUE` and then checking that to avoid volatile reads later might yield performance gains in some scenarios.

I haven't browsed the `Flowable` operators yet but `FlowableZip` for starters could be enhanced in this way and I suspect ten or so more from doing a quick grep.

Happy to do PRs if you think this is of benefit.

**Comment by akarnokd** [comment]
Volatile reads are non-issue, eliminating writes are. Plus those reads are amortized by the available number of values. Your suggestion adds another possible false-sharing scenario along with an extra branch on the common path. In addition, it is the question how many times you have an unbounded consumer with very fast inputs that just pound on the loop.

**Comment by davidmoten** [comment]
ok, thought you had it covered.
