### ISSUE TITLE
Error handling when operate observable

### ISSUE THREAD

**Issue by julist213** [ReactiveX/RxJava#4778]
when i do operator like Map to observable  ,then  function throws exception ,is there a way to let  the subscriber 's onError know error emit?

**Comment by davidmoten** [comment]
If the exception is  a checked exception then rethrow it wrapped in a RuntimeException (or your own class that extends RuntimeException). A non-checked exception will turn up as an onError emission.

**Comment by davidmoten** [comment]
Example:

``` java
Observable.just(1)
  .map(x -> {
      try { 
          return canThrow(x);
      } catch (IOException e) { 
          throw new RuntimeException(e);}
    });
```

**Comment by julist213** [comment]
@davidmoten thanks ,it's helpful!

**Comment by akarnokd** [comment]
Sidenote: you could go with 2.x and avoid these try catches almost always. 

If you have further input on the issue, don't hesitate to reopen this issue or post a new one.
