### ISSUE TITLE
2.x - the code below Subscription.request(long) in onSubscribe() would't be executed until a flowable were completed

### ISSUE THREAD

**Issue by otal1105** [ReactiveX/RxJava#4781]
When a flowable works on the main thread, `request(long)` in `onSubscribe(Subscription)` always calls `onNext(T)` and then `onComplete()`.
Therefore, the code below `request(long)` in `onSubscribe(Subscription)` would be executed after `onNext(T)` and `onComplete()`.

```
Flowable.just(1, 2, 3).subscribe(new Subscriber<Integer>() {

  @Override
  public void onSubscribe(Subscription s) {
    s.request(Long.MAX_VALUE);
    System.out.println("onSubscribe done");
  }

  @Override
  public void onNext(Integer t) {
    System.out.println(t);
  }
  ...
}
```

The result is always like this.

```
1
2
3
onComplete called
onSubscribe done
```

I can avoid this by calling `request(long)` at the end of `onSubscribe()`.
However, this behavior is different from RxJava 1.x.

Also, there is a problem to override ResourceSubscriber's onStrat().
Since `request(long)` acts this way, if I want to do something in `onStart()`, I have to put `super.onStart()` on the bottom of `onStart()`.

```
@Override
protected void onStart() {
  initialize();
  super.onStart();
}
```

If I write below, `intitalize()` would be called after `onComplete()`.

```
@Override
protected void onStart() {
  super.onStart();
  initialize();
}
```

I think that this is a problem since developers always have to care about where they writie a request method.

**Comment by akarnokd** [comment]
Yes, this is a property of how Reactive-Streams request-onNext pair work. You have to do initialization before you call `request(n)` or make sure whatever you do after is thread-safe when looked at from `onNext`.

I'll update the wiki and mention this case.

**Comment by otal1105** [comment]
Thank you! I checked the updated wiki! I really appreciate your hard working!
