### ISSUE TITLE
2.0 Nulls > Signaller doc clarification

### ISSUE THREAD

**Issue by ersin-ertan** [ReactiveX/RxJava#4784]
https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0#nulls

`source.subscribe(e -> { /* Ignored. */ }, Throwable::printStackTrace);`

Having `/* Ignored */` is a bit misleading when it populates the entire block, the example conflicts with its explanation passage above it; you mention the signaller but fail to use it.

The example can be made explicit: the source values are ignored, however the logic within the block is not because it uses the signaller.

Proposed Change:
```java
source.subscribe(onNextValue -> { myToggle = !myToggle; /* onNextValue is ignored */ }, Throwable::printStackTrace);
```

**Comment by akarnokd** [comment]
There is no conflict, what matter is the side-effect in create and not what values travel the sequence. The `subscribe` is there to trigger the source and not to perform work on the ignored values.

**Comment by ersin-ertan** [comment]
Hmm, so would the guarantee of the API designer come from documenting the sequence and quantity of side-effects? 
- in memory cache, onNext
- in file system, onNext
- in database, onNext

**Comment by akarnokd** [comment]
Your examples typically involve reasonable types or using `Completable` to indicate they have completed some valueless operation (delete an entry, file or row).

Do you have something concrete or are these only theoretical questions?

**Comment by ersin-ertan** [comment]
I don't have something concrete, just trying to envision a more concrete use case.
