### ISSUE TITLE
How to add proguard?

### ISSUE THREAD

**Issue by yubaokang** [ReactiveX/RxJava#4786]
rxjava:2.0.0

**Comment by JakeWharton** [comment]
No rules are required.

**Comment by artem-zinnatullin** [comment]
See https://github.com/artem-zinnatullin/RxJavaProGuardRules/issues/44 for more info.

**Comment by akarnokd** [comment]
As the experts said, there is no need for it in 2.x. If you have further input on the issue, don't hesitate to reopen this issue or post a new one.
