### ISSUE TITLE
Emitter vs. Observer - what is the difference?

### ISSUE THREAD

**Issue by dkhmelenko** [ReactiveX/RxJava#4787]
I discovered that there are two interfaces [Emitter](http://reactivex.io/RxJava/2.x/javadoc/io/reactivex/Emitter.html) and [Observer](http://reactivex.io/RxJava/2.x/javadoc/io/reactivex/Observer.html). Both of them have similar methods. The question is where should each of them be used? 
Because `Observable.create()` receives as a parameter type `Emitter` and `PublishSubject.subscribe()` receives as a parameter type `Observer` (or `Consumer`). What makes impossible to use `Emitter` for subscribing in subject (and that was possible in RxJava 1.x).

Can somebody clarify or update documentation what is the difference between all of them and when should they be used?

**Comment by akarnokd** [comment]
The `Emitter` is an abstraction over `Observer` that handles cancellation for you. In 1.x it extends `Observer` because that interface is just 3 methods. In 2.x the `Observer` has a 4th method, `onSubscribe` which you should not interact with but can't hide it if 2.x `Emitter` extended `Observer`. The sole purpose of `Emitter` is to let you interact with the downstream in a safe manner from within `Observable.create`.

**Comment by dkhmelenko** [comment]
@akarnokd Thanks for explanation. 
Because before I used `Observer` from `Observable.create()` to subscribe it to `PublishSubject.subscribe()`. But what is the best practice now as I cannot use `Emitter` for subscibing in `Subject`?

I would appreciate if you share some good approach of dealing with `Observable.create()` and `Subject.subscibe()`.

**Comment by akarnokd** [comment]
Depends on what you were trying to do and why the indirection? Chain calls on PublishSubject directly for example, wrap the Emitter into an Observer.

**Comment by dkhmelenko** [comment]
@akarnokd Thanks for you suggestions. I'll give you my example, just in case and better understanding the issue. 
I just wanted to wrap some async functions (like location request) with callbacks into Rx way. So I do function call in `Observable.create()`, but in order to handle the results of that async function from listener, I subscribe subsciber to subject and then that subject emits a value when callback is called.

**Comment by dkhmelenko** [comment]
Anyway, for my purposes I will go with your suggestion wrapping Emitter into an Observer.
Thank you. This question is answered.

**Comment by akarnokd** [comment]
Great!
