### ISSUE TITLE
Make 2.x the default branch

### ISSUE THREAD

**Issue by passsy** [ReactiveX/RxJava#4789]
RxJava `2.x` is now stable and the way to go. It should be the default branch when visiting https://github.com/ReactiveX/RxJava/

**Comment by akarnokd** [comment]
Feels too early.

**Comment by ZacSweers** [comment]
I'd err on the side of too soon than too late. RxJava 2 is never going to get as much attention toward migrating as it is right now.

**Comment by akarnokd** [comment]
This is my suggestion about managing the versions:

February 15, 2017: Set 2.x as the default branch
June 1, 2017: 1.x no longer accepts feature requests, only bugfixes to existing operators
March 31, 2018: 1.x end-of-life

**Comment by akarnokd** [comment]
Somebody switched the default to 2.x without noticing me?! @ReactiveX/rxjava-committers  ?

**Comment by akarnokd** [comment]
Looks like I have to go with this now. Updated readme with additional info.
