### ISSUE TITLE
Feature Request: Passing only an Error action to a subscriber

### ISSUE THREAD

**Issue by digitalbuddha** [ReactiveX/RxJava#4794]
We have cases where we create an observable to kick off an async operation.  There is nothing for an observer to do. For example
`Observable.fromCallable(someCallable()).subscribe();`

The problem with passing in an empty subscribe is that if the callable throws an error we will not be handling it.  The only options I currently know of is to pass a `onNext` & `onError` action to the subscribe or to pass in an `observer/subscriber` with an empty `onNext` & `OnCompleted`.  Ideally what I'd like is the ability to pass in the error action without having to also pass in an onNext  action ie:
```
Observable.fromCallable(someCallable()).subscribe(new Action1<Throwable>() {
                    @Override
                    public void call(Throwable throwable) {
                    }
                });
```

in Java8 this is less of a problem, but in Android where we do not have lambdas the code starts to look unwieldy to have to do:
```
Observable.fromCallable(someCallable()).subscribe(new Action1<BufferedSource>() {
                    @Override
                    public void call(BufferedSource bufferedSource) {

                    }
                }, new Action1<Throwable>() {
                    @Override
                    public void call(Throwable throwable) {

                    }
                })
```

Apologies if there is another way to only pass an onError without having to implement the onNext action.

**Comment by JakeWharton** [comment]
You can pass Actions.empty() as the first argument to the two-argument
variant. Not perfect, but close enough. It also documents your clear intent
to ignore items.
