### ISSUE TITLE
Different Transformer interfaces

### ISSUE THREAD

**Issue by vRallev** [ReactiveX/RxJava#4796]
In our code we have some reusable transformers. In RxJava 2 it became even harder to maintain the code, because the logic has to be copied five time (for `Observable`, `Flowable`, `Single`, `Maybe` and `Completable`). In the end we have something like

```java
public static <T> ObservableTransformer<T, T> createObservableTransformer(@NonNull final Object key) {...}

public static <T> FlowableTransformer<T, T> createFlowableTransformer(@NonNull final Object key) {...}
// ...  
```

I'm wondering if there is an easier solution or what's the recommended way to handle this scenario?

**Comment by JakeWharton** [comment]
Make one type that implements all 5 transformer interfaces.

**Comment by akarnokd** [comment]
The base types have independent type hierarchies. You could try reflection or invokedynamic magic but it is probably more easy to just have 5. What kind of transformers do you need for all 5 types at the same time that is such a maintenance problem?

**Comment by vRallev** [comment]
@JakeWharton That base class wouldn't solve it. In the end I still have to implement those methods 5 times. 

@akarnokd Reflection wouldn't make it easier I guess :) In this specific case it's a transformer that puts the sources into a cache and re-subscribes when necessary (Android). If you need to overload  the method with more parameters, then you need to do this 5 times. 

I also thought about transforming the sources to other types and to have only one implementation of the transformer. But I don't know if this is a good idea.

**Comment by JakeWharton** [comment]
It would seem the emission differences between all the types would require
5 different strategies, though.

**Comment by dlew** [comment]
I've been working on upgrading RxLifecycle to RxJava2 today. Creating a single `OmniTransformer` is a good solution. Implementing the five methods has been (for RxLifecycle) necessary because of the differences between the different types.

If you _could_ use the same implementation between all five, then I would recommend having all five methods call a common sixth method.

**Comment by vRallev** [comment]
@dlew That's what I tried to do as much as I can. 

I was curios if there is a fancy trick to avoid it, but it seams like there isn't. Thanks for the help.
