### ISSUE TITLE
Assembly tracking in 2.0.0

### ISSUE THREAD

**Issue by vRallev** [ReactiveX/RxJava#4799]
I was reading about [assembly tracking](https://medium.com/square-corner-blog/no-cause-for-concern-rxjava-and-retrofit-throwing-a-tantrum-96c9e4ba8a6c#.ny2vj3ulm) and wanted to give it a try. `RxJavaHooks` was removed in version `2.0.0` and `RxJavaPlugins` doesn't provide a method for the feature. 

Was it removed or is it simply not implemented, yet?

**Comment by akarnokd** [comment]
It lives in the [RxJava2Extensions](https://github.com/akarnokd/RxJava2Extensions#debug-support) library.

**Comment by vRallev** [comment]
Perfect, thanks!
