### ISSUE TITLE
2.x "Reactive Pull", how to implement for 2.x?

### ISSUE THREAD

**Issue by kennedyoliveira** [ReactiveX/RxJava#4800]
Hello, 
i'm starting to use 2.x version now, and something i still didn't figure out how works is the "Reactive Pull" from 1.x, how can i manually implement it? 

In 1.x we had the `SyncOnSubscribe` class to help creating this type of observable, how it works on 2.x?

Using the code below as example, i took from this [post](http://vlkan.com/blog/post/2016/07/20/rxjava-backpressure/), how it can be rewrited to work on 2.x?

````
SyncOnSubscribe<Integer, InputStream> binaryReader = SyncOnSubscribe.createStateful(

	// Create the initial state. (Invoked per subscriber.)
	() -> new FileInputStream("data.bin"),

	// Upon request, emit a new item and return the new state.
	(inputStream, output) -> {
		try {
			int byte = inputStream.read();
			if (byte < 0) output.onCompleted()
			else output.onNext(byte);
		} catch (IOException ex) {
			output.onError(ex);
		}
		return inputStream;
	},

	// Perform final clean-up using the state. (Invoked upon unsubscription.)
	inputStream -> {
		try { inputStream.close(); }
		catch (IOException error) { RxJavaHooks.onError(error); }
	} 

);

Observable<Integer> observableBinaryReader = Observable.create(binaryReader);
````

**Comment by kennedyoliveira** [comment]
I just found the [generate](http://reactivex.io/RxJava/2.x/javadoc/io/reactivex/Flowable.html#generate%28java.util.concurrent.Callable,%20io.reactivex.functions.BiConsumer%29), i guess this answer my question, am i right or still missing something?

**Comment by akarnokd** [comment]
You don't really need try-catches around your callbacks anymore but that't it.

**Comment by kennedyoliveira** [comment]
thank you @akarnokd!
