### ISSUE TITLE
Android handling screen orientation change

### ISSUE THREAD

**Issue by dominolog** [ReactiveX/RxJava#4805]
I have an Activity and a CompositeSubscription that is subscribed in onResule and unsubscribed in onPause. The app calls a login network request method using RxJava observable and subscribe to the returned Observable. How to handle a screen orientation change when the request is still executing. Currently, my Activity will unsubscribe from current subscriptions and my network call will not be delivered back to newly recreated activity. 
Is there a way to serialize subscriptions objects to recreate them and be able to get the response from Observable?

**Comment by akarnokd** [comment]
Such Android specific questions are better suited for StackOverflow where many RxJava+Android developers frequent. I don't know Android well enough to point you to the right place.

**Comment by dlew** [comment]
You have to store your subscription somewhere outside of the `Activity`. The same would be true of any network request that you want to outlive the lifecycle, Rx or not.

**Comment by akarnokd** [comment]
Closing via http://stackoverflow.com/questions/40419251/rxjava-android-handling-screen-orientation-change
