### ISSUE TITLE
Can I force zip opertaer work on AndroidSchedulers.mainThread()

### ISSUE THREAD

**Issue by lengyue524** [ReactiveX/RxJava#4806]
zip combine varlues on the Scheduler which last Observable worked on.
I want zip operate work on AndroidSchedulers.mainThread() or anyone of the Observable Schedulers.

How could I do?

**Comment by akarnokd** [comment]
2 options
-  apply `observeOn(AndroidSchedulers.mainThread())` on all of its inputs
- identity map (or pair up) the zipper function's input, apply `observeOn` after the zip then use `map` to work with the pair/array of values.

**Comment by lengyue524** [comment]
Thanks, It works.
