### ISSUE TITLE
reactive-streams should be scoped as compile dependency

### ISSUE THREAD

**Issue by davidmoten** [ReactiveX/RxJava#4813]
Something is wrong in the build process that produces the released pom.xml. The pom.xml for 2.0.0 has 

```xml
<dependency>
    <groupId>org.reactivestreams</groupId>
    <artifactId>reactive-streams</artifactId>
    <version>1.0.0</version>
    <scope>runtime</scope>
</dependency>
```

Scope for this dependency should be `compile`.  As it stands maven builds of projects that use RxJava 2 will fail with compile errors. The workaround for anyone encountering this error is to add the `reactive-streams` dependency explicitly (scoped `compile`) above the `rxjava` dependency.

**Comment by akarnokd** [comment]
Found [this](https://discuss.gradle.org/t/maven-publish-plugin-generated-pom-making-dependency-scope-runtime/7494/14).

**Comment by akarnokd** [comment]
See #5015. It works locally for me:

![image](https://cloud.githubusercontent.com/assets/1269832/22243465/bdf6ac8e-e227-11e6-8b3f-c7d8f1abf4b9.png)

**Comment by akarnokd** [comment]
https://oss.jfrog.org/libs-snapshot/io/reactivex/rxjava2/rxjava/2.0.0-DP0-SNAPSHOT/rxjava-2.0.0-DP0-20170124.111838-392.pom

Closing via #5015
