### ISSUE TITLE
2.x: mention the absence of TestSubject in "What's different in 2.0"

### ISSUE THREAD

**Issue by tbcs** [ReactiveX/RxJava#4816]
It seems that `TestSubject` is gone in 2.x.  Is the replacement simply the use of any `Subject`/`Processor` and `observeOn(scheduler)`?  If so, then maybe this could be mentioned in [_What's different in 2.0_]( https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0).

**Comment by akarnokd** [comment]
[Done](https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0#testsubject).

**Comment by tbcs** [comment]
Great, thank you!
