### ISSUE TITLE
1.2.2 Please implement Completable.doAfterTerminate to be called after onError also

### ISSUE THREAD

**Issue by StanislavChumarin** [ReactiveX/RxJava#4822]
Completable.doAfterTerminate is called only "after this Completable completes normally" but that is differ from Observable/Single implementation of same operation.

I think that this method must be reimplemented to be similar to those in Observable/Single and current implementation to be renamed to `doAfterCompleted`. 

I know that there is `doOnTerminate` (same operation was deprecated in Observable). I just what to have predictable API with need to dig into documentation word by word.

**Comment by akarnokd** [comment]
`Completable` is in `@Beta` still so you can post a PR that updates some names and adds the call to that callback for `onError`. There is no need to introduce a new operator as `doAfterTerminate` is supposed to work like that.

**Comment by StanislavChumarin** [comment]
Looks like this issue was resolved.
