### ISSUE TITLE
2.x: TestSubscriber.requestMore missing

### ISSUE THREAD

**Issue by davidmoten** [ReactiveX/RxJava#4823]
When I want to do backpressure testing on a `Flowable` with the `Flowable.test(0)` method I'm forced out of method chaining because `request(n)` is a void. Am I missing something? Shall I add a fluent `requestMore(n)`?

**Comment by akarnokd** [comment]
Yes, but don't forget to mark it as experimental.

**Comment by akarnokd** [comment]
Closing via #4838
