### ISSUE TITLE
subscribeOn (rx.Scheduler) in Observable cannot be applied to (io.reactivex.Scheduler) 

### ISSUE THREAD

**Issue by ljf1172361058** [ReactiveX/RxJava#4829]
Gradle:
    // 编译RxJava
    compile 'io.reactivex:rxjava:1.2.2'
    // 编译RxAndroid
    compile 'io.reactivex:rxandroid:1.2.1'
    // 编译Retrofit网络加载框架
    compile 'com.squareup.retrofit2:retrofit:2.1.0'
    // 编译Retrofit网络加载框架直接解析JSON数据变成JAVA对象
    compile 'com.squareup.retrofit2:converter-gson:2.1.0'
    // 编译Retrofit对RxJava的支持
    compile 'com.jakewharton.retrofit:retrofit2-rxjava2-adapter:1.0.0'

**Comment by akarnokd** [comment]
You have the wrong imports:

```
compile 'io.reactivex.rxjava2:rxjava:2.0.0'
compile 'io.reactivex.rxjava2:rxandroid:2.0.0'
```

**Comment by ljf1172361058** [comment]
@akarnokd thank you

**Comment by akarnokd** [comment]
You are welcome.
