### ISSUE TITLE
The CompletableSubscriber API is a little confusing

### ISSUE THREAD

**Issue by ZacSweers** [ReactiveX/RxJava#4836]
I'm trying to write a custom `CompletableOperator` and using `CompletableSubscriber`, but its `onSubscribe()` API is a little confusing to me. If I were to call plain `unsafeSubscribe()` with a `Subscriber`, I could keep that `Subscriber` instance and call `unsubscribe()`. With `CompletableSubscriber` though, this seems to need to be done via `onSubscribe()`, but even if I give it a simple `BooleanSubscription` and unsubscribe it manually after, it doesn't actually seem to unsubscribe the stream under the hood. Just hangs. There aren't any real examples in tests of using `CompletableOperator` in general either, so it's a little difficult to wrap my head around how it's supposed to be used.

Could anyone share some example or shed some light on the above example case?

**Comment by akarnokd** [comment]
http://akarnokd.blogspot.hu/2015/12/the-new-completable-api-part-2-final.html

**Comment by ZacSweers** [comment]
Thanks, totally forgot you wrote that awhile back and should have read there. It did get me a bit closer, but I think I'm still missing something. I tried putting together something in the same vein as `takeUntil` and also reading from `amb`'s implementation, and while there is no completion/error event, the subscription continues to remain alive as well.

``` java
final class CompletableubscribeUntil implements Completable.CompletableOperator {

    private final Observable<?> other;

    public CompletablSubscribeUntil(final Observable<?> other) {
        this.other = other;
    }

    @Override
    public Completable.CompletableSubscriber call(final Completable.CompletableSubscriber s) {
        final SerialSubscription serial = new SerialSubscription();
        final Completable.CompletableSubscriber inner = new Completable.CompletableSubscriber() {
            @Override
            public void onCompleted() {
                s.onCompleted();
            }

            @Override
            public void onError(Throwable e) {
                s.onError(e);
            }

            @Override
            public void onSubscribe(Subscription d) {
                serial.set(d);
            }
        };

        final Subscriber<Object> so = new Subscriber<Object>() {
            @Override
            public void onStart() {
                request(Long.MAX_VALUE);
            }

            @Override
            public void onCompleted() {
                serial.unsubscribe();
            }

            @Override
            public void onError(Throwable e) {
                inner.onError(e);
            }

            @Override
            public void onNext(Object t) {
                onCompleted();
            }
        };

        other.unsafeSubscribe(so);

        return inner;
    }
}
```

**Comment by akarnokd** [comment]
What do you want to achieve? `takeUntil(Observable)` but on a `Completable` "stream"?

**Comment by akarnokd** [comment]
``` java

BothConsumer both = new BothConsumer(child);
child.onSubscribe(both);
until.subscribe(both);
source.subscribe(both);

static final class BothConsumer extends Subscriber<Object> implements CompletableSubscriber {
    final CompletableSubscriber actual;
    final AtomicBoolean once;

    BothConsumer(CompletableSubsciber actual) {
        this.actual = actual;
        this.once = new AtomicBoolean();
        request(Long.MAX_VALUE);
    }

    @Override
    public void onSubscribe(Subscription s) {
        add(s);
    }

    @Override
    public void onNext(Object t) {
        onComplete();
    }

    @Override
    public void onError(Throwable e) {
        unsubscribe();
        if (once.compareAndSet(false, true)) {
            actual.onError(e);
        } else {
            RxJavaHooks.onError(e);
        }
    }

    @Override
    public void onCompleted() {
        unsubscribe();
        if (once.compareAndSet(false, true)) {
            actual.onCompleted();
        }
    }
}
```

**Comment by ZacSweers** [comment]
Similar to takeUntil, but we want to unsubscribe downstream (I know, operator pitfalls, but we have a lint that enforces the safe placement of this). Having access to the Subscriber in Observable's operator allowed for this

**Comment by akarnokd** [comment]
> Similar to takeUntil, but we want to unsubscribe downstream

That's not possible with `Completable`. You complete or error your downstream as an indication and it should cleanup its level of resources. RxJava 1.x' `Observable`/`Subscriber` is flawed in this aspect by allowing an upstream to unsubscribe its downstream.

**Comment by ZacSweers** [comment]
I figured that was probably coming. Unfortunately this requires annoying wrapping of rx calls or keeping the returned subscription/disposable to handle later, leading to awkward API tradeoffs later. Thanks anyway for the insight, that blog post was really good and looking forward to your 2.0 series!
