### ISSUE TITLE
Using TestSubscriber

### ISSUE THREAD

**Issue by AlokBansal8** [ReactiveX/RxJava#4843]
My following test runs successfully:

```java
RxDatabase.setValue(reference, "a").subscribe(new Observer<Boolean>() {
   @Override public void onCompleted() {
     assertThat(Boolean.TRUE).isTrue();
   }

   @Override public void onError(Throwable e) {
     assertThat(e).isNull();
   }

   @Override public void onNext(Boolean aBoolean) {
     assertThat(aBoolean).isTrue();
   }
});
```

But following code fails with error `java.lang.AssertionError: Number of onNext events differ; expected: 1, actual: 0 (1 completion)`
```java
TestSubscriber<Boolean> test1 = new TestSubscriber<>(1);
RxDatabase.setValue(reference, "a").subscribe(test1);
test1.assertNoErrors();
test1.assertValueCount(1);
test1.assertValue(Boolean.TRUE);
test1.unsubscribe();
```

Both onCompleted and onNext code is running in the first example.

**Comment by akarnokd** [comment]
Does this work?

``` java
TestSubscriber<Boolean> test1 = new TestSubscriber<>(1);
RxDatabase.setValue(reference, "a").subscribe((Observer<Boolean>)test1);
test1.assertValueCount(1);
test1.assertValue(Boolean.TRUE);
```

When you test, do you start with a fresh database or maybe you try to set a value again which doesn't happen the second time?

**Comment by AlokBansal8** [comment]
@akarnokd Test failed even with the changes you suggested.
Yes, I start with fresh database. As database functionality is mocked in my tests. If you want I can share the full piece of code here.

**Comment by akarnokd** [comment]
That would be great.

**Comment by AlokBansal8** [comment]
Test file code:

``` java
@Mock DatabaseReference reference;

@Before public void setup() {
  MockitoAnnotations.initMocks(this);
}

@Test public void testSetValue() {
  doAnswer(new Answer<Object>() {
    @Override public Object answer(InvocationOnMock invocation) throws Throwable {
      CompletionListener listener = invocation.getArgument(1);
      listener.onComplete(null, reference);
      return null;
    }
  }).when(reference).setValue(any(), any(CompletionListenerImpl.class));

  TestSubscriber<Boolean> test1 = new TestSubscriber<>(1);
  RxDatabase.setValue(reference, "a").subscribe((Observer<Boolean>) test1);
  test1.assertNoErrors();
  test1.assertValueCount(1);
  test1.assertValue(Boolean.TRUE);
  test1.unsubscribe();
}
```

Relevant method in RxDatabase class:

``` java
@NonNull @CheckResult
public static Observable<Boolean> setValue(@NonNull final DatabaseReference reference,
    final Object o) {
  final CompletionListenerImpl listener = new CompletionListenerImpl();
  return listener.getObservable().doOnSubscribe(new Action0() {
    @Override public void call() {
      reference.setValue(o, listener);
    }
  });
}
```

CompletionListenerImpl class:

``` java
class CompletionListenerImpl implements DatabaseReference.CompletionListener {

  private final Subject<Boolean, Boolean> subject =
      new SerializedSubject<>(BehaviorSubject.<Boolean>create());

  CompletionListenerImpl() {
  }

  Observable<Boolean> getObservable() {
    return subject;
  }

  @Override public void onComplete(final DatabaseError databaseError,
      final DatabaseReference databaseReference) {
    if (databaseError == null) {
      subject.onNext(Boolean.TRUE);
      subject.onCompleted();
    } else {
      subject.onError(new RxDatabaseError(databaseError));
    }
  }
}
```

You can find the complete project [RxFirebase](https://github.com/AlokBansal8/RxFirebase)

**Comment by akarnokd** [comment]
It may take some time before I can setup a devenv for your code. Could you single-step through it to see where it stops? I don't like Mockito because non-interface mocks tend to not do some things real objects do and you get similar hard-to-explain hangs or missed data like this.

**Comment by akarnokd** [comment]
Works for me with AS 2.2.2 freshly installed:

![image](https://cloud.githubusercontent.com/assets/1269832/20245196/70a2b720-a99c-11e6-9b45-6087bd584275.png)

**Comment by AlokBansal8** [comment]
@akarnokd Yes because in the pushed version of the library I have tweaked the CompletionListenerImpl.java to the following:

``` java
@Override public void onComplete(final DatabaseError databaseError,
      final DatabaseReference databaseReference) {
    if (databaseError == null) {
      subject.onNext(Boolean.TRUE);
      Observable.timer(10, TimeUnit.MILLISECONDS).subscribe(new Action1<Long>() {
        @Override public void call(Long aLong) {
          subject.onCompleted();
        }
      });
    } else {
      subject.onError(new RxDatabaseError(databaseError));
    }
  }
```

In this case testSubscriber increases the valueCount but doesn't register the terminal event.
Try adding `test1.assertCompleted();` to your test.

**Comment by AlokBansal8** [comment]
But with my first example in my first comment I needn't modify my code for Test and it still worked.
It seems there is some problem with TestSubscriber when I write subject.onCompleted just after subject.onNext

If I remove subject.onCompleted it works fine. But this is not ideal because I am not conveying the terminal event.

**Comment by akarnokd** [comment]
Okay, I see it now. If you complete a `BehaviorSubject` it loses its last value. If you do this:

``` java
@Override public void onComplete(final DatabaseError databaseError,
      final DatabaseReference databaseReference) {
    if (databaseError == null) {
      Assert.assertTrue("No subscribers?", subject.hasObservers());
      subject.onNext(Boolean.TRUE);
      subject.onCompleted();
    } else {
      subject.onError(new RxDatabaseError(databaseError));
    }
  }
```

the assertTrue will fail because at this point there is no subscriber.

**Comment by AlokBansal8** [comment]
@akarnokd Are you saying that onComplete is running without any subscriber? If so, then I think it is because I am doing something wrong in setting up the test.

But still why was first example getting both the callbacks.

**Comment by akarnokd** [comment]
It passed because its `onNext` was never called but only its `onCompleted` and with that setup, you didn't verify if `onNext` was called or not at all.

**Comment by AlokBansal8** [comment]
@akarnokd Yes you are right. So do you have any suggestions about how can I test my code?

**Comment by akarnokd** [comment]
Use `ReplaySubject`.

**Comment by AlokBansal8** [comment]
Thanks.
