### ISSUE TITLE
WithLatestFrom and Buffer in RxJava 2

### ISSUE THREAD

**Issue by antonshkurenko** [ReactiveX/RxJava#4844]
I read docs, but I can't find any existing operator for my situation. I need something like withLatestFrom with buffer functionality:

I painted marbles for it (hope you will understand what I want):
[withLatestBufferFrom()](http://imgur.com/a/Eyc1i)

Can you help me with existing RxJava API?

**Comment by akarnokd** [comment]
Looks like you want to buffer and have a boundary which is also appended to the buffered elements?

``` java
PublishSubject<Integer> boundary = PublishSubject.create();

PublishSubject<Integer> source = PublishSubject.create();

boundary.publish(b -> source.buffer(b).zipWith(b, (list, e) -> { list.add(e); return list; }))
.subscribe(System.out::println);

source.onNext(1);
source.onNext(2);
source.onNext(3);

boundary.onNext(100);

source.onNext(4);
source.onNext(5);

boundary.onNext(200);

source.onNext(6);
boundary.onNext(300);

boundary.onNext(400);
```

prints

```
[1, 2, 3, 100]
[4, 5, 200]
[6, 300]
[400]
```

**Comment by antonshkurenko** [comment]
Not append, but apply combining function (sorry, that it wasn't clear in picture :) ).

Thanks for the very fast answer!
