### ISSUE TITLE
Completable.concat(Obsevable<Completable>..) unsubscribes  from child completables not in time

### ISSUE THREAD

**Issue by sobersanta** [ReactiveX/RxJava#4848]
Hi

Loving playing with new Completables and Singles! But seems that we have found a bug running them on our production server,
and after fighting for 30 minutes with and not being able to find the exact cause, we have written a simple test which is attached here and proves the issue.

By executing it you can see that old good Observables.concat works perfectly, but it's younger brother Completable.concat does not.

We observe that it ubsubscribes somewhere in the chain from child completables, and by executing the test several times you can see that sequence is uneven and order of processing/ubsubscribed messages changes from time to time.

The file attached:

[Test.zip](https://github.com/ReactiveX/RxJava/files/589964/Test.zip)

I believe it's not how it should work - I expect that all child completables complete before they are unsubscribed from by the upstream operator.

The sample code that does not work as I expect:

`

        System.out.println("Testing Completable.concat");
        System.out.println();
        Completable.concat(
                Observable.range(1, 5).map(integer -> Completable.fromAction(() -> {
                    try {
                        System.out.println("Processing " + integer + "...");
                        Thread.sleep(100);
                        System.out.println("Processing " + integer + " finished");
                    } catch (InterruptedException e) {
                        e.printStackTrace();
                    }
                })
                        .doOnUnsubscribe(() -> System.out.println("Unsubscribed from " + integer))
                        .subscribeOn(Schedulers.io()).observeOn(Schedulers.computation()))
                        .doOnUnsubscribe(() -> System.out.println("Unsubscribed from parent observable"))
        ).subscribe(() -> {
                    System.out.println("Finished Completable.concat");
                }, Throwable::printStackTrace
        );
 

`

**Comment by akarnokd** [comment]
What version are you using?

**Comment by sobersanta** [comment]
Well, left the PC and will be back in an hour but its either 1.2.1 or 1.2.2
not sure i refreshed my gradle deps in the ide today.
let me check precisely and tell for sure later tonight

**Comment by akarnokd** [comment]
Thought so. This setup works with 2.x and it prints all 5+5 "Processing". In 1.2.2 it only prints up to 4 and somehow misses 5. This looks like a bug, I'll investigate it further and post a fix soon.

**Comment by sobersanta** [comment]
I can say for sure now and its the latest version, 1.2.2

**Comment by akarnokd** [comment]
See #4849

**Comment by akarnokd** [comment]
Closing via #4849

**Comment by sobersanta** [comment]
Wow, that was quick :)
Thanks a lot!!

Could please take a look at the version of concat which takes Iterable,
isn't it affected too?
