### ISSUE TITLE
1.x: Something happens with Message.what onNext value

### ISSUE THREAD

**Issue by danielgomezrico** [ReactiveX/RxJava#4855]
Rxjava 1.1.8

Maybe its an issue with `Parcelable` management since `Message` is parcelable.
The idea is to listen to handler messages with subscriptions but `message.what` attribute comes with 0 always.

```
class RxHandler(looper: Looper) : Handler(looper) {
  val messagesObservable = PublishSubject<Message>()

  override fun handleMessage(msg: Message?) {
    super.handleMessage(msg)
    msg?.let { messagesObservable.onNext(it) }
  }
}
```

and then subscribe to it:

```
playbackHandler.messagesObservable
          .subscribe({
              // it.what is always 0 
          }, { Timber.e(it, "Error on playback handler message handling") })

```

and then:

```
playbackHandler.sendEmptyMessage(1)
```

**Comment by akarnokd** [comment]
RxJava doesn't know about the internals of your values so this must be something to do with how Android message passing works in a handler. You have better chance asking this on StackOverflow.
