### ISSUE TITLE
Could we get RxValve added as an official operator?

### ISSUE THREAD

**Issue by ScottCooper92** [ReactiveX/RxJava#4859]
Hi @akarnokd, I recently asked a question on SO and you directed me to the custom operator you'd written for Rx 1.x that acts as a [valve in the stream](https://gist.github.com/akarnokd/1c54e5a4f64f9b1e46bdcf62b4222f08). 

Most reactive extensions for other languages can achieve something similar using various operators in combination but I'm struggling to recreate it in RxJava, I'm also struggling to convert the above operator into Rx 2.x to use it personally.

The goal is to be able to trigger the valve to open or close using a boolean value, when open the stream should flow as normal, when closed the items are buffered until the valve is opened again, where all buffered items are then emitted. I can see this being quite useful for a number of reasons so I was hoping it could become officially supported.

**Comment by akarnokd** [comment]
This is more suited for an extension library such as [RxJava2Extensions](https://github.com/akarnokd/RxJava2Extensions).

**Comment by ScottCooper92** [comment]
Should I create a new issue on that repo or are you happy for me to keep this one?

**Comment by akarnokd** [comment]
Yes, please re-post this there.
