### ISSUE TITLE
SerializedSubscriber should propagate onStart()

### ISSUE THREAD

**Issue by adamdyga** [ReactiveX/RxJava#4861]
`rx.observers.SerializedSubscriber` should also propagate `onStart()` event to the original subscriber, similar to other `on*()` methods

**Comment by akarnokd** [comment]
Do you have an use case for this? Currently it doesn't do that because that usually leads to double calls to `onStart` in some operators.

**Comment by adamdyga** [comment]
In my case `onStart()` is used to initiate backpressure (reactive pull):

```
public class MySubscriber extends Subscriber<...>
{
	@Override
	public void onStart()
	{
		request(1);
	}
        ....
}
```

When the subscriber is wrapped with `SerializedSubscriber` it doesn't work. Yes, it can be easily fixed  by subclassing `SerializedSubscriber` and propagating `onStart()`, but this just doesn't feel right. If all `on*()` events are propagated, why not `onStart()` too? I understand that it was omitted due to some operators calling it multiple times, but can it also happen to my (or any other) subscriber if I don't wrap it with `SerializedSubscriber`? If so, shouldn't the operators be fixed, instead of mitigating the problem in subscriber(s)?

**Comment by akarnokd** [comment]
It has been fixed; it is called RxJava 2. Call `request(1)` in the constructor of your subscriber.

**Comment by adamdyga** [comment]
OK. Thanks for the hint. I thought that calling it in constructor is a little bit too early...

**Comment by akarnokd** [comment]
Such request calls get accumulated and forwarded to the upstream when the time is right.

**Comment by akarnokd** [comment]
If you have further input on the issue, don't hesitate to reopen this issue or post a new one.
