### ISSUE TITLE
2.x: RxJavaPlugins.reset() doesn't reset after Schedulers initializaion

### ISSUE THREAD

**Issue by peter-tackage** [ReactiveX/RxJava#4862]
I have a query about whether or not the current behavior of`RxJavaPlugins`'s 
`setInit<XYZ>SchedulerHandler` hooks are behaving as intended. It seems that it is not possible to revert to the "out of the box" `Schedulers` state.

Take the example of `Scheduler.computation()`. If I set a new default `Scheduler` using `setInitComputationSchedulerHandler` (which, to be applied successfully, must be done prior to accessing the `Schedulers` class), then once set this default cannot be changed; even using `RxJavaPlugins.reset()`.

To elaborate, when I override the default `Scheduler` instance, using the aforementioned hook, then the overriding `Function<Callable<Scheduler>>` is assigned to the non-final static field: `RxJavaPlugins.onInitComputationHandler`.

As per:

```java
    public static void setInitComputationSchedulerHandler(Function<Callable<Scheduler>, Scheduler> handler) {
        if (lockdown) {
            throw new IllegalStateException("Plugins can't be changed anymore");
        }
        onInitComputationHandler = handler;
    }
```   

Now in `Schedulers.java`, the static final field `COMPUTATION` is statically initialized via the result of `RxJavaPlugins.initComputationScheduler()` using the eventual default value of `new ComputationScheduler()` when no override is set. 

If an override was set via `setInitComputationSchedulerHandler`,then that override is applied, but that result is final, as can be seen below -

```java
static final Scheduler COMPUTATION;

static final class ComputationHolder {
    static final Scheduler DEFAULT = new ComputationScheduler();
}

static {
    COMPUTATION = RxJavaPlugins.initComputationScheduler(new Callable<Scheduler>() {
                @Override
                public Scheduler call() throws Exception {
                    return ComputationHolder.DEFAULT;
                }
            });
    }
``` 

This means that `COMPUTATION` is permanently assigned to be the override value. When a class accessess `Schedulers.computation()`, they will get the `COMPUTATION` instance by default.

See:

```java
    public static Scheduler computation() {
        return RxJavaPlugins.onComputationScheduler(COMPUTATION);
    }
```

If they again call `setInitComputationSchedulerHandler` or `reset()` to clear the `RxJavaPlugins.onInitComputationHandler` field, then regardless, the original `COMPUTATION` value remains.

Now they *can* call `RxJavaPlugins.setComputationSchedulerHandler()` to change the `Scheduler` that is eventually returned, but my opinion at least, is that it should be possible to revert back to the "out of the box" `Schedulers` state. Also being subject to the vagueries of static initialization order timing has the potential to cause debugging headaches for those overriding `Schedulers`.

Without suggesting an implementation, I would at least suggest that `RxJavaPlugins.reset()` should at least allow the caller the potential to reassign the default `Scheduler` instance.

What thoughts do you have on the current behavior and my suggested change?

**Comment by akarnokd** [comment]
The current setup is introduced to prevent instantiating the default schedulers in environments where the default ExecutorService-based schedulers are not allowed. Instead of overriding the initial value, override the individual `setComputationSchedulerHandler` to return the scheduler of your chosing dynamically.

**Comment by peter-tackage** [comment]
There are similar use cases in the Android world (which has the same API); we don't want the equivalent default Scheduler to be initialized in `AndroidSchedulers.mainThread()` when executing on the desktop JVM. So I'm comfortable with the motivation for having an alternative default Scheduler. 

However; is the intent behind the current implementation that once set (even implicitly, by accessing the `Schedulers` class), one should expect that it cannot be changed? `RxJavaPlugins.reset()` gives the impression that can reset to the out-of-the-box state (by calling `setInitComputationSchedulerHandler(null);`, but currently that would only be effective when done _before_ the `Schedulers` class is accessed.

**Comment by akarnokd** [comment]
You set the baseline Schedulers once then dynamically override them. Because the dynamic override takes precedence, there is no loss of functionality.

**Comment by peter-tackage** [comment]
OK. Thanks for the clarification.

**Comment by akarnokd** [comment]
If you have further input on the issue, don't hesitate to reopen this issue or post a new one.
