### ISSUE TITLE
Observing dynamic data set

### ISSUE THREAD

**Issue by ghost** [ReactiveX/RxJava#4865]
Hey,

What is the best approach to observe dynamic data set? 
For example, I have a list of items which is being updated every few seconds and I want to somehow trigger `onNext()` and notify subscribers only after update event.

I have already tried `PublishSubject` - I was calling `publishSubject.onNext(list)` after every update event, but I'm not sure this is the best approach.

Thanks!

**Comment by akarnokd** [comment]
It depends on your context. If you are processing the list in the same thread then `PublishSubject.onNext(list)` is okay. If you process it on a different thread while it may change on its "home" thread, you'd have to use `PublishSubject.toSerialized()` and emit a copy of the `list`.
