### ISSUE TITLE
Completable.doOnDipose() not called when disposing with TestObserver

### ISSUE THREAD

**Issue by vanniktech** [ReactiveX/RxJava#4872]
The following test case fails:

```java
final AtomicBoolean atomicBoolean = new AtomicBoolean();

assertThat(atomicBoolean.get()).isFalse();

Completable.complete()
    .doOnDispose(() -> atomicBoolean.set(true))
    .test()
    .assertResult()
    .dispose();

assertThat(atomicBoolean.get()).isTrue(); // Fails
```

In my opinion this is a bit misleading and probably should not be the case. Is this working as intended?

**Comment by akarnokd** [comment]
Apparently `TestObserver` disconnects from the upstream on `onComplete` but `TestSubscriber` doesn't so this might be some residue. I'll post a PR to fix this.

Generally though, some operators disconnect in a similar fashion so calling dispose has no effect after they complete.

**Comment by akarnokd** [comment]
Closing via #4873
