### ISSUE TITLE
Using Observable With Odata

### ISSUE THREAD

**Issue by davinder2385** [ReactiveX/RxJava#4875]
Hi Team,

I have Odata Services already existing. However, i intend to stream the data from backend using RxJava keeping my service as Odata. Is it possible?
Can you please help me with an example?

Thanks,
Davinder Singh

**Comment by akarnokd** [comment]
What is Odata? For questions like "how to use RxJava with technology X" you are better off asking it on StackOverflow.

**Comment by davinder2385** [comment]
Odata is protocol.
http://www.odata.org/
I am using it for my rest services, however i intend to stream the data using rxjava.
And hence the question.

**Comment by akarnokd** [comment]
RxJava doesn't do networking, you should check out Retrofit and RxNetty for that.

**Comment by davinder2385** [comment]
okay. Thanks
