### ISSUE TITLE
Should a disposed ConnectableObservable replay() still emit?

### ISSUE THREAD

**Issue by Mauin** [ReactiveX/RxJava#4888]
I have this test which passes, but I initially expected it (in particular the 2nd `test`) to fail:

```java
@Test
public void connectableReplay() throws Exception {
    ConnectableObservable<Integer> just = Observable.just(1).replay();

    just.test().assertNoValues();

    Disposable connect = just.connect();
    connect.dispose();

    just.test()
            .assertValue(1)
            .assertComplete();
}
```

So even after a `replay()` ConnectableObservable was disposed it can still emit it's replayed values? Is that the desired behaviour?

**Comment by akarnokd** [comment]
Yes. `connect.dispose` disconnects from the upstream in case it hasn't yet terminated but consumers still get the events received till then.

**Comment by Mauin** [comment]
Okay, thanks for the clarification! 👍
