### ISSUE TITLE
onError throws Exception after Flowable has been unsubscribed

### ISSUE THREAD

**Issue by flowsprenger** [ReactiveX/RxJava#4894]
We have recently run up against this in RxJava 2.0.x, and I would like to clarify that this is the intended behaviour.

We are creating a Flowable that connects to a remote server and first needs to resolve the host. If host cannot be resolved, the UnknownHostException is propagated via onError:
``` 
val messages = Flowable.create<SourcedMessage>({ subscriber ->
        this.subscriber = subscriber
        try{
            addr = InetAddress.getByName(host)
        }catch (e:UnknownHostException){
            subscriber.onError(e)
            return@create
        }
       .....
}
```

This seems to work fine (we can use an invalid hostname and the retry logic wrapping it fires just as expected), but we have seen crashes in our crashlogs, where the Android app crashes with an uncaught UnknownHostException, which we did not expect.
The crash goes away as soon as we check subscriber.isCancelled before calling onError as in:

```
val messages = Flowable.create<SourcedMessage>({ subscriber ->
        this.subscriber = subscriber
        try{
            addr = InetAddress.getByName(host)
        }catch (e:UnknownHostException){
            if(!subscriber.isCancelled){
                    subscriber.onError(e)
            }
            return@create
        }
       .....
}
```

For what it matters the Flowable is further chained in a subscribeOn(Schedulers.io()).retryWhen().publish.refCount() chain that is observedOn and subscribed to on the AndroidScheduler.mainThread.

We would have expected the onError just being silently ignored after unsubscription (which occurs when the app goes into the background).
Maybe #4863 and #4807 are related too.

**Comment by akarnokd** [comment]
2.x reports undeliverable exceptions, such as ones that happen around a cancellation to the RxJavaPlugins error handler which then forwards it to the current thread's uncaught exception handler. On desktop, this just prints the stacktrace to the console whereas some Android setups treat it as a fatal exception and stop the app. I suggest installing a custom global error handler via `RxJavaPlugins.setErrorHandler`. I'll think about how to deal with the situation by using system parameters.

**Comment by flowsprenger** [comment]
Thanks for clarification

**Comment by alouanemed** [comment]
@akarnokd, Can't find any guide to use `RxJavaPlugins.setOnError` in the wiki page https://github.com/ReactiveX/RxJava/wiki/Plugins

**Comment by akarnokd** [comment]
Sorry, mixed up the two versions. Otherwise, it is straightforward: you have to specify a callback `Action1`/`Consumer`:

```java
// 1.x
RxJavaHooks.setOnError(e -> System.out.println(e.getMessage()));

// 2.x
RxJavaPlugins.setErrorHandler(e -> System.out.println(e.getMessage()));
```

**Comment by alouanemed** [comment]
In Android, Where do you recommend putting that block of code ?  Thanks

**Comment by PaulWoitaschek** [comment]
@akarnokd Has this any side effects? Why is this not the default? If I understand correctly for example any call to .cache leads to the underlying observable not stopping when I'm unsubscribing. 

Thus my App crashes by default when onError gets called after I have unsubscribed?

**Comment by JakeWharton** [comment]
It prevents the app crashing when there's legitimate programming errors.

**Comment by PaulWoitaschek** [comment]
So with it I don't see legitimate programming erros and without it my App crashes without legitimate programming errors?

Is it possible to somehow get the old behaviour back so my app crashes only when I made a mistake?
