### ISSUE TITLE
[1.1.2] i dont know why you write code like this

### ISSUE THREAD

**Issue by Null0716** [ReactiveX/RxJava#4897]
the code in package rx/Observable.java   i dont know why you write the code like 
![b96f3486-cf8c-49b8-8ff6-04bb6ab0a37f](https://cloud.githubusercontent.com/assets/4793886/20783720/a670ff1e-b7d0-11e6-809a-3ef8125af799.png)
why not write like 
![62c12249-fd0d-4ee0-a253-e110ba46f2d9](https://cloud.githubusercontent.com/assets/4793886/20783745/cd88bb00-b7d0-11e6-8c7c-2349e20ef6e1.png)
then we can write less code

**Comment by JakeWharton** [comment]
Dupe of #3798. See explanations in there.

**Comment by Null0716** [comment]
Thanks for the explanation;
