### ISSUE TITLE
CompositeException breaks Serializable

### ISSUE THREAD

**Issue by chaviw** [ReactiveX/RxJava#4905]
CompositeException is not really Serializable because of the inner static class `PrintStreamOrWriter` which is not Serializable. The app will crash if you try to use a CompositeException as a Serializable.

Issue occurs on Android when trying to pass the exception around as a Serializable object.

**Comment by zsxwing** [comment]
`static class` should be fine. I ran the following test and it passed:
```Java
    @Test
    public void testSerialization() throws IOException, ClassNotFoundException {
        CompositeException e = new CompositeException(new RuntimeException("a"), new RuntimeException("b"));
        ByteArrayOutputStream bytes = new ByteArrayOutputStream();
        ObjectOutputStream output = new ObjectOutputStream(bytes);
        output.writeObject(e);
        output.close();

        ObjectInputStream input = new ObjectInputStream(new ByteArrayInputStream(bytes.toByteArray()));
        System.out.println(input.readObject());
    }
```

My hunch is you put some exceptions that break Serializable into `CompositeException`.

**Comment by akarnokd** [comment]
An unit test demonstrating the problem would be great. Also please include the version number.

**Comment by chaviw** [comment]
It doesn't look like the inner class is ever getting stored as a local variable in the CompositeException so I think you're right. This doesn't seem like the issue. Must be another weird Serialization issue elsewhere

**Comment by chaviw** [comment]
Found the real issue. It was a bug in rx java that fixed in rx java here
https://github.com/ReactiveX/RxJava/pull/4841/files

We're still using an older version of RxAndroid so we never got that fix in

**Comment by JakeWharton** [comment]
Do not use RxAndroid to dictate your RxJava version. Read and heed its
README.

**Comment by chaviw** [comment]
Thanks for that. Will update RxJava so we can get that fix in
