### ISSUE TITLE
The order of `doOnSubscribe` changed in RxJava 2 without documentation

### ISSUE THREAD

**Issue by ansman** [ReactiveX/RxJava#4906]
We noticed one of our tests failing because or an ordering issue with `doOnSubscribe`. In RxJava 1 downstream `doOnSubcribe` would be called before upstream but it's the reverse in RxJava 2.

Here's a code snippet that showcases the problem:
```java
Observable.empty()
	.doOnSubscribe(() -> System.out.println("RX1 upstream"))
	.doOnSubscribe(() -> System.out.println("RX1 downstream"))
	.subscribe();
```
This will produce the following log statements:
```
RX1 downstream
RX1 upstream
```
while the following snippet:
```java
io.reactivex.Observable.empty()
	.doOnSubscribe(d -> System.out.println("RX2 upstream"))
	.doOnSubscribe(d -> System.out.println("RX2 downstream"))
	.subscribe();
```
produces the following statement:
```
RX2 upstream
RX2 downstream
```

Is this an intended change?

**Comment by akarnokd** [comment]
Yes. The 1.x operator is lift based which executes the downstream operations first. In 2.x, the onSubscribe happens starting from upstream travelling downstream like the onNext events. Why do you have order-dependent doOnSubscribe?

**Comment by ansman** [comment]
We had a test that tested a retry transformer and we needed to simulate getting different errors on different tries. Here's the code that caused the issue:
```java
AtomicInteger subscribeCount = new AtomicInteger(0);
IOException e = new IOException();
RuntimeException re = new RuntimeException();

Observable
        .defer(() -> subscribeCount.get() >= 2 ?
                Observable.error(re) :
                Observable.concat(Observable.just("1"), Observable.just("2"), Observable.error(e)))
        .doOnSubscribe(subscribeCount::incrementAndGet)
        .compose(retry())
        .subscribe(subscriber);
```

**Comment by akarnokd** [comment]
Relplace `get()` with `incrementAndGet()` and drop the `doOnSubscribe()` call.

**Comment by ansman** [comment]
Ok, great!
Just wanted to make sure this wasn't unexpected.
