### ISSUE TITLE
2.x: Misbehavior of BehavoirProcessor when converted to Single

### ISSUE THREAD

**Issue by sergejsha** [ReactiveX/RxJava#4913]
io.reactivex.rxjava2:rxandroid:2.0.1

I believe `BehaviorProcessor` does not work correctly with `Single` observable. I am using `BehaviorProcessor` similarly to how I used `BehaviorSubject` with RxJava1, but this time with a `Single` observable.

Event producer
```java
BehaviorProcessor<Event> bp = BehaviorProcessor.create();

public Single<Event> getEvent() {
    return bp.singleOrError();
}

void onEventReceived(Event event) {
    bp.onEvent(event);
    bp.onComplete();
}
```

Event observer
```java

producer.getEvent().subscribeWith(
    new DisposableSingleObserver<Event>() {
        @Override public void onSuccess(Event value) {
            Log.e(TAG, "success");
        }

        @Override public void onError(Throwable e) {
            Log.e(TAG, "error");
        }
    }
);
```

Observed behavior:
1. If observers get subscribed **before** `onEventReceived()` is called, then all observers receive their `onSuccess()` callback, which is OK.
2. If observers get subscribe **after** `onEventReceived()` (meaning after `onEvent()` and `onComplete()` are emitted), then `Single` receives `java.util.NoSuchElementException`. I believe this is NOT OK. Expected behavoir would be receiveing `onSuccess()` with the last value. This is what `BehaviorProcessor` should do for downstream observers, isn't it? Otherwise it appears to be useless for `Single` observers.

Thanks!

**Comment by akarnokd** [comment]
This is the correct behavior for `BehaviorProcessor`. It doesn't retain the last value if it gets terminated. This has been so since day 1 with `BehaviorSubject` as well. Use `ReplayProcessor.createWithSize(1)` instead.

**Comment by sergejsha** [comment]
This is true what you say. But if I try to keep it not terminated by not calling `onComplete()`, the `Single` doesn't receive `onSuccess()`, which is also ok. Just out of curiosity, what would be the main use case for `BehavoirProcesser` with `Single` then, if later subscriptions always receive `onError()` instead of the most recent item it has observed?

**Comment by akarnokd** [comment]
I don't understand what you try to achieve here. If you want a `Single` of the latest of the `BehaviorProcessor`, use `take(1).singleOrError()` so a `SingleObserver` will receive at most one success value and disconnect from the `BehaviorProcessor`.

**Comment by sergejsha** [comment]
That's fine. Thanks for supporting David!
