### ISSUE TITLE
2.x: retryWhen signature

### ISSUE THREAD

**Issue by davidmoten** [ReactiveX/RxJava#4916]
The `retryWhen` signature doesn't look right:

```java
public final Single<T> retryWhen(Function<? super Flowable<Throwable>, ? extends Publisher<Object>> handler); 
```
The function should be able to return any `Flowable` for instance but at the moment has to be cast to `Flowable<Object>`. I think the signature should be:

```java
public final Single<T> retryWhen(Function<? super Flowable<Throwable>, ? extends Publisher<?>> handler);
```

**Comment by akarnokd** [comment]
Right. Could you post a PR?

**Comment by davidmoten** [comment]
Yep

**Comment by davidmoten** [comment]
Looks like your recent work on `retry` and `repeat` fixed those signatures so no further changes needed.
