### ISSUE TITLE
2.x Single.flatMapCompletable expects Completable instead of CompletableSource

### ISSUE THREAD

**Issue by vanniktech** [ReactiveX/RxJava#4923]
The signature looks like this:

`final Function<? super T, ? extends Completable> mapper`

although it should be 

`final Function<? super T, ? extends CompletableSource> mapper`

**Comment by akarnokd** [comment]
I don't think there are any `CompletableSource` implementations other than RxJava but you are welcome to send a PR.

**Comment by vanniktech** [comment]
Well it's mostly for consistency and I'll send one right away.

**Comment by akarnokd** [comment]
Closing via #4924
