### ISSUE TITLE
ConnectableObservable#eagerConnect()

### ISSUE THREAD

**Issue by thomasnield** [ReactiveX/RxJava#4929]
I am finding several cases where I am using `replay()` with hot Observables but I need to immediately subscribe just so I can capture the emissions coming from the source, and have them cached and ready for future Subscribers. Therefore I created this Kotlin extension function: 

```kotlin
fun <T> ConnectableObservable<T>.eagerConnect() = autoConnect().apply { subscribe().unsubscribe() }
```

Would it make sense just to add this a standard method in RxJava 2.0?

**Comment by JakeWharton** [comment]
You can pass a count to autoConnect. Passing 0 immediately connects and
should have this behavior.

**Comment by thomasnield** [comment]
That's the second time you've helped me today Jake, thank you!
