### ISSUE TITLE
1.x OperatorOnBackpressureDrop but still get MissingBackpressureException

### ISSUE THREAD

**Issue by imzoer** [ReactiveX/RxJava#4933]
hi,
I am using rxjava version 1.2.1

I included rxjava in my android app, using onBackpressureDrop to prevent Observable flooding android main thread. But some app users still get a MissingBackpressureException.

`cause by:
rx.exceptions.MissingBackpressureException: null
rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.onNext(SourceFile:160)
rx.internal.operators.OperatorOnBackpressureDrop$2.onNext(SourceFile:98)
rx.subjects.PublishSubject$PublishSubjectProducer.onNext(SourceFile:304)
rx.subjects.PublishSubject$PublishSubjectState.onNext(SourceFile:219)
rx.subjects.PublishSubject.onNext(SourceFile:72)
cook.core.watcher.Watchers.trigger(SourceFile:332)
cook.core.watcher.Watchers.access$100(SourceFile:82)
cook.core.watcher.Watchers$WatcherHandler.invoke(SourceFile:231)
java.lang.reflect.Proxy.invoke(Proxy.java:393)
$Proxy34.updateDiscover(Unknown Source)
com.cookies.cook.model.manager.Manager.handleGlobalDiscover(SourceFile:4990)`

I can not reproduce this exception myself.

**Comment by akarnokd** [comment]
Could you try with the latest 1.2.4?

**Comment by imzoer** [comment]
Since I can not reproduce this myself, I will try version 1.2.4 in our app in future release, several days later.

Is this issue fixed in 1.2.4?  Is there another issue you talk about this problem? Sorry I didn't see any...

**Comment by akarnokd** [comment]
This isn't a known issue. Please make sure you don't call `onNext` on the `PublishSubject` from multiple threads concurrently.

**Comment by imzoer** [comment]
**Sorry I didn't mention it that I call onNext concurrently with multi threads in my app.**

Don't rxjava's PublishSubject support calling onNext concurrently?

I **tested** PublishSubject with multithread, **but didn't reproduce this problem**. So **I suppose that PublishSubject support multithread by default.**

**Comment by akarnokd** [comment]
None of the `Subject`s support that but you may not encounter the failure immediately. Use `toSerialized` to get a `Subject` that is safe to call concurrently.

One of the purpose of `Subject`s are to be used as event dispatchers in an UI environment and since UI is single threaded, this makes them low overhead. If needed, they can be made thread safe via `toSerialized` but the opposite, namely making a thread-safe `Subject` drop its safety, wouldn't work.

**Comment by imzoer** [comment]
Ok. Thanks for your reply
