### ISSUE TITLE
2.x: Custom stream types

### ISSUE THREAD

**Issue by ZacSweers** [ReactiveX/RxJava#4938]
*Intended as a discussion*

We often find ourselves creating an observable somewhere and exposing it later. While this is fine for local construction+usage, we lose important behavioral information about upstream behavior when we expose these downstream. Two large examples of where we run into this are around threading and `BehaviorSubject`-backed Observables.

- For threading, some streams might implicitly be acting on a specific scheduler. For instance, Retrofit 1 (and optionally on 2) will `subscribeOn` the returned stream before returning it to a background scheduler of some sort. We have some internal APIs for local storage that do the same. This information is lost to the consumer, who may either *not* observe on a main thread if necessary or try to force a background thread not knowing that they're already on one.
- For subjects, the behavior is useful information to the consumer but we don't want to expose it as a Subject directly to avoid leaking its API and allowing downstream consumers to call their own events. The "behavior" portion is often an important detail that leads to subtle bugs when not actively accounted for.

For threading, one might expose the observable downstream as a "BackgroundObservable" of sorts. For BehaviorSubject-backed ones - BehaviorObservable. It would probably be shallow at best, but the only other thing I can think of to solve this would maybe be with annotations, which isn't as nice as leveraging the type system.

My early thinking would be to basically copying how `ObservableHide` works, and impose our own tooling (lint, error-prone, etc) to try to enforce some level of protection if we recognize that a returned observable exhibits traits like what I mentioned above. Would be curious to know if and how others have handled this case. We have over a hundred engineers using a monorepo with extensive Rx APIs, so good documentation about the behavior of APIs is essential. A hide-style approach still induces some overhead though, and operators like `map` still upconvert the type to `Observable` even though it doesn't change the behavior of the underlying stream (i.e. `customObservable.map(_ -> stuff())` should ideally still be recognized as a `CustomObservable` type).

**Comment by ZacSweers** [comment]
Seeing as it's generally a pattern in 2.x to create a custom Observable already, having the ability to make behavior explicit in the type system would be advantageous for API design.

@akarnokd I'd be curious for your thoughts on this.

**Comment by akarnokd** [comment]
This has the same problems as any custom type:
  - you end up loosing the custom type pretty quickly
  - requires custom implementation of all operators due to the base class difference
  - you may get into a combinatorial explosion because the need for combining multiple "indicators" like BackgroundSingleThrowsIOException and others.

**Comment by ZacSweers** [comment]
Yep, agreed, especially in light of those last two points. One approach we're thinking about as an alternative is annotations + static analysis, but that that might not get much mileage. Looks like what I was proposing first isn't really viable though, at least not beyond a single level. 

Another could be trying to educate around using thin wrapping custom observables just for API means (e.g. only expose `BehaviorObservable` when you're putting it in the method signature). Would you foresee any issues with taking that approach?

**Comment by ZacSweers** [comment]
One thing that would help with the latter proposal would be an API to transform an observable to another type and bridge to other APIs. Currently everything returns `Observable`, but something like this would be useful:

```java
public <T, R> R transformTo(Function<Observable<? super T>, ? extends R> transformer);
```

Which allow anyone to break out of the chain with their own types, or even to their own APIs.

```java
/**
 * An Observable whose behavior is similar to that of a {@link BehaviorSubject} but read-only.
 */
public final class BehaviorObservable<T> extends Observable<T> {

  private final Observable<T> actual;

  public static <T> BehaviorObservable<T> wrap(Observable<T> other) {
    return new BehaviorObservable<>(other);
  }

  public static <T> Function<Observable<T>, BehaviorObservable<T>> asBehaviorObservable() {
    return BehaviorObservable::wrap;
  }

  private BehaviorObservable(Observable<T> actual) {
    this.actual = actual;
  }

  @Override protected void subscribeActual(Observer<? super T> observer) {
    actual.subscribe(observer);
  }
}
```

Then when used, could do this:

```java
// Switch to new type
public BehaviorObservable<String> exposeAPI() {
    return myPrivateBehaviorSubject.transformTo(asBehaviorObservable());
}

// Or something more complex
public BackgroundObservable<String> exposeAPI() {
    return myObservable.transformTo(asBackgroundObservable());  // Implementation enforces this
}
```

**Comment by JakeWharton** [comment]
We have to()

**Comment by ZacSweers** [comment]
I am blind

**Comment by ZacSweers** [comment]
Alright, going to close this. Think `to()` and the approach above is probably going to get us the best mileage for now. Thanks for the discussion all
