### ISSUE TITLE
2.0.3 Single.takeUntil() crashes 

### ISSUE THREAD

**Issue by skgmn** [ReactiveX/RxJava#4961]
```java
Single<T> main;
Flowable<T> other;

main.takeUntil(other.take(1)).subscribe(...);
```

This pseudo-code crashes when `other` emits an item. `SingleTakeUntil.TakeUntilOtherSubscriber.onCompleted()` is called twice and second call generate a crash. Please fix this.

**Comment by akarnokd** [comment]
Please provide the crash stacktrace.

**Comment by akarnokd** [comment]
Closing via #4962
