### ISSUE TITLE
Less lambda support for RxJava2

### ISSUE THREAD

**Issue by reactivedroid** [ReactiveX/RxJava#4965]
I was using RxJava 1.2.1 where I used Retrolambda to avail the benefits of lambda expressions. In the process, the long expression of creating a subscription and then implementing the 3 methods `onCompleted`, `onError` and `onNext` were reduced to 3 lines of code. Now I am trying to migrate to RxJava 2. There is no `Subscription` in RxJava 2, so I am using `DisposableObserver` but this not being a Functional Interface, I am not able to use lambda expressions on it. Migration from RxJava 1.2.1  with lambda integrated to RxJava 2 seems to be a daunting task right now. Why lambda expressions have not been supported or less supported in RxJava 2?

**Comment by akarnokd** [comment]
I'm not sure what lambda support you are missing, there are a bunch of `subscribe` methods that [take lambda](http://reactivex.io/RxJava/2.x/javadoc/io/reactivex/Observable.html#subscribe(io.reactivex.functions.Consumer,%20io.reactivex.functions.Consumer,%20io.reactivex.functions.Action))

```java
Observable.just(1)
.subscribe(
    v -> System.out.println(e),
    e -> e.printStackTrace(),
    () -> System.out.println("Done")
);
```

**Comment by reactivedroid** [comment]
Sample code when RxJava2:
```java
compositeDisposable.add(movieDetailsEndpoint.getMovieTrailers(movie.getId())
                .subscribeOn(Schedulers.io())
                .observeOn(AndroidSchedulers.mainThread())
                .subscribeWith(new DisposableObserver<VideoViewModel>()
                {
                    @Override
                    public void onNext(VideoViewModel videoViewModel)
                    {
                            view.showTrailers(videoViewModel.getVideos());
                    }

                    @Override
                    public void onError(Throwable e)
                    {

                    }

                    @Override
                    public void onComplete()
                    {

                    }
                }));
```

Sample code when using RxJava 1.2.1:
```java
subscription = interactor.updateEventTime(event).
                    subscribeOn(Schedulers.io()).
                    observeOn(AndroidSchedulers.mainThread()).
                    subscribe(aVoid -> onUpdateRoutineEventResult(routineEvent), 
                       throwable -> onError());
```

The former has loads of boiler plate code expanded and the same when implemented using Retrolambda has reduced the code and made it way cleaner in RxJava 1.2.1. I am not able to achieve this when using `DisposableObserver` to `subscribeWith` as it tells that it is not a Functional Interface. Plz let me know if I am missing something

**Comment by akarnokd** [comment]
`subscribe` with lambdas returns a `Disposable` in 2.x which you can store somewhere; it is the same pattern as with 1.x.

```java
compositeDisposable.add(
    interactor.updateEventTime(event).
                    subscribeOn(Schedulers.io()).
                    observeOn(AndroidSchedulers.mainThread()).
                    subscribe(aVoid -> onUpdateRoutineEventResult(routineEvent), 
                       throwable -> onError())
);

compositeDisposable.add(
    movieDetailsEndpoint.getMovieTrailers(movie.getId())
                .subscribeOn(Schedulers.io())
                .observeOn(AndroidSchedulers.mainThread())
                .subscribe(videoViewModel -> view.showTrailers(videoViewModel.getVideos())
);
```

**Comment by reactivedroid** [comment]
Thanks for pointing it out. Working fine.
