### ISSUE TITLE
why takeWhile only takes a function and takeUntil only takes an observable?

### ISSUE THREAD

**Issue by fhalde** [ReactiveX/RxJava#4975]
Isn't it a perfect scenario to `takeWhile` while an observable is generating an event and `takeUntil` until a predicate is true?

Ref https://github.com/Reactive-Extensions/RxJS/issues/1399

**Comment by akarnokd** [comment]
a) There is a `takeUntil` overload that takes `Predicate` in RxJava.
b) Did you actually try to imagine how `takeWhile(Observable)` would work with discrete item emissions?

**Comment by fhalde** [comment]
a) Must've missed it then, apologies !!
b) My perspective of the functionality was that .. once a target observable gets completed, complete the source observable. Could you elaborate `discrete item emissions` ?

**Comment by akarnokd** [comment]
Observables emit in discrete fashion over time. With takeUntil(Observable) the fact that the Observable doesn't emit is the indication that the gate for the main source is open. However, takeWhile(Observable) would require some kind of continuous emission to keep the gate open, which is not possible.

**Comment by fhalde** [comment]
Oh. I thought the source observable could detech if `Observable` has completed when its `onCompleted` gets called

**Comment by akarnokd** [comment]
That's `takeUntil` and particularly `takeUntil(other.ignoreElements())`.

**Comment by fhalde** [comment]
@akarnokd Thanks. closing this !!
