### ISSUE TITLE
usage of mergeDelayError with observeOn is confusing

### ISSUE THREAD

**Issue by tomasbartalos** [ReactiveX/RxJava#4977]
When I use following code:
```
Observable.mergeDelayError(
                Observable.error(new RuntimeException()),
                Observable.just("Hello")
            )
            .subscribe(new Action1<Integer>() {
            @Override
            public void call(Integer integer) {
                Log.i(Thread.currentThread()  +": rxtest", "OnNext: " + integer);
            }
            }, new Action1<Throwable>() {
            @Override
            public void call(Throwable throwable) {
                Log.i(Thread.currentThread()  +": rxtest", "OnError");
            }
        });
```
I get correct output:

> I/Thread[main,5,main]: rxtest: OnNext: 1
> I/Thread[main,5,main]: rxtest: OnError

When I add observeOn(...), which is actually no change, because the first example runs by default on main thread:
```
Observable.mergeDelayError(
                Observable.error(new RuntimeException()),
                Observable.just("Hello")
            )
            //the change
            .observeOn(AndroidSchedulers.mainThread())
            .subscribe(...);
```
I get different output, **onNext is not called, mergeDelayError has no effect**:

> I/Thread[main,5,main]: rxtest: OnError

As I've read [here](http://stackoverflow.com/a/40337705/4018614), I can fix this with:
`.observeOn(AndroidSchedulers.mainThread(), true)`

However the need of specifying errorDelay 2 times creates unaware side effects in seemingly unrelated parts of code. As an example, if you're using Observable as a service and you wish to specify observeOn(..) in your client's code, you need to know the implementation of the service not to break the behavior (and of course you need to be aware of the overloaded observeOn method). 

**Expected behavior:**
If mergeDelayError is specified, there should be no need to specify the same information in observeOn(.., ..) method. If this is technically difficult to achieve, at least emphasize this information in observeOn's method javadoc

rxjava version: 1.1.6

PS: its a great product :+1: .
thank you,

**Comment by akarnokd** [comment]
This is the [default behavior](http://reactivex.io/RxJava/1.x/javadoc/rx/Observable.html#observeOn(rx.Scheduler)) of `observeOn`

>Note that onError notifications will cut ahead of onNext notifications on the emission thread if Scheduler is truly asynchronous. If strict event ordering is required, consider using the observeOn(Scheduler, boolean) overload.

Each operator has its scope and you have to specify your intention every time.
