### ISSUE TITLE
Change 2.x Copyright to "RxJava Contributors"

### ISSUE THREAD

**Issue by benjchristensen** [ReactiveX/RxJava#4978]
I noticed that the 2.x copyright still shows as Netflix, despite Netflix no longer leading the efforts of the project (since I left Netflix over a year ago). 

Since the 2.x code has been re-written from scratch outside the leadership of Netflix, I suggest that the copyright headers all be replaced with:

```
Copyright (c) 2016-present, RxJava Contributors. 
```

This would replace this line at the top of every file:

```
Copyright 2016 Netflix, Inc.
```

The precedent for this is shown by the Facebook project Yarn which is a community driven project from many companies, not just Facebook: https://github.com/yarnpkg/yarn/blob/master/LICENSE

Since that is how RxJava is being managed, I think it's a good change to make. 

cc @stevegury, @abersnaze, and @NiteshKant from Netflix who are the closest to RxJava from the v1.x time frame and who were involved in the initial design of 2.x and choice to handoff the project to the community and @akarnokd as the lead.

**Comment by benjchristensen** [comment]
Alright, based on the thumbs up ... should I submit a PR? cc @akarnokd in particular for answering whether you want me to submit this, or you do the change?

**Comment by JakeWharton** [comment]
For RxAndroid we use "The RxAndroid authors", but I'm happy to normalize that to whatever is chosen here.

**Comment by akarnokd** [comment]
@benjchristensen Sure.

**Comment by stevegury** [comment]
LGTM

**Comment by fanturbo** [comment]
@benjchristensen Maybe you forget to change README.md?

**Comment by akarnokd** [comment]
All updated. Thanks.
