### ISSUE TITLE
onBackpressureBuffer into custom queue

### ISSUE THREAD

**Issue by I60R** [ReactiveX/RxJava#4985]
I want to buffer elements produced by hot source into custom queue (PriorityQueue). Also I want to retreive unprocessed elements after unsubscription.  
Found, that source code of OperatorOnBackpressureBuffer.BufferSubscriber already has TODO for this task, so, extending this operator seems to be right way to go.  
Any progress on this?

**Comment by akarnokd** [comment]
That comment refers to a more lightweight queue but still fifo queue.

The problem with `PriorityQueue` is the probabilistic reordering in case of backpressure. Consider buffering with a fixed time/size and then sorting the resulting List based on some priority.

**Comment by I60R** [comment]
Why reordering not allowed? In my case it's expected behaviour

**Comment by akarnokd** [comment]
The emphasis is on **probabilistic** because you can't predict if and when the dowstream won't be able to process the data and the buffering starts to happen.

**Comment by I60R** [comment]
The idea is simple: `Subscriber` calls `request(1)` (this peeks element with highest priority from buffer), processes it asynchronously then do next `request(1)` until _terminal element_ (expected with lowest priority) received. Reordering and probablistic buffering are expectected here. 
Or I'm missing something important that will break contracts\my expectations?

**Comment by akarnokd** [comment]
Doesn't work.

1) case 1: you consume the `onBackpressureBuffer` immediately with a Subscriber and call `request(1)` from `onNext`, effect: due to call-stack blocking, the buffer won't have more than 1 element in it, thus no reordering
2) case 2: you apply some async operation (such as `onBackpressureBuffer().observeOn()`). such operators request some predetermined amount which will request in chunks. effect: sometimes the sequence will go 1-by-1, sometimes a chunk will have ordered items (just like with my buffer example) but no guarantee when.

**Comment by I60R** [comment]
Is there more information about call-stack blocking, or other information about **case 1**? 
Can't figure out, why `Subscriber` below won't work:

        elements.subscribe(new Subscriber<Element>() {

            @Override
            public void onNext(final Element element) {
                processAsync(element, new Callback() {

                    @Override
                    void doOnProcessingFinish() {
                        if (element.isTerminal()) {
                            unsubscribe();
                        } else {
                            request(1);
                        }
                    }
                });
            }

            …

        });
So, in **case 2** async operation "buffers" requests before sending them to source?
What means "predetermined amount"?

**Comment by akarnokd** [comment]
I suggest you take the source code of `onBackpressureBuffer`, apply your changes and experiment with it to see what happens.

**Comment by I60R** [comment]
Okay, now I understand problem. Thank for your answers
