### ISSUE TITLE
Share does not work with just() and from()

### ISSUE THREAD

**Issue by xdom** [ReactiveX/RxJava#4995]
Tested with RxJava <= 1.2.5:

Creating observable with _interval()_:
```java
Observable<Long> interval = Observable.interval(100, TimeUnit.MILLISECONDS);
Observable<Long> source = interval
        .take(2)
        .doOnNext(aLong -> System.out.println("Side effect"));
Observable<Long> published = source.share();
Observable<Zip> zip = Observable.zip(
        published.buffer(2),
        OperatorMinMax.max(published),
        Zip::new
);
zip.toBlocking().single();
```

results in (which is **correct** because of the _share()_ operator):
```
Side effect
Side effect
```

However, when creating Observable with _just()_:
```java
Observable<Long> interval = Observable.just(0L, 1L);
Observable<Long> source = interval
        .take(2)
        .doOnNext(aLong -> System.out.println("Side effect"));
Observable<Long> published = source.share();
Observable<Zip> zip = Observable.zip(
        published.buffer(2),
        OperatorMinMax.max(published),
        Zip::new
);
zip.toBlocking().single();
```
the result is:
```
Side effect
Side effect
Side effect
Side effect
```
which is in my opinion **incorrect** as I used the _share()_ operator. The same applies for operators _from()_, _range()_...
Is this a bug, or am I missing something important here?

**Comment by akarnokd** [comment]
With `share()`, if the upstream terminates, the internal subscriber count is set to zero. If a new subscriber comes in, that makes `share()` resubscribe to the upstream. 

In your second case, `just` completes within the buffer size of `zip` and now you have two subscriptions.

**Comment by xdom** [comment]
Thank you @akarnokd for clarification. Can you think of any solution for my issue?

**Comment by akarnokd** [comment]
Use `publish()` and when everything is set up, including the end consumer(s), call `connect()` on the `ConnectableObservable`.

**Comment by xdom** [comment]
Alright, and what if (in my real scenario) I return the zipped observable from a method and thus when subscribing to it, I don't have any access to the `ConnectableObservable`? Am I lost then?

**Comment by JakeWharton** [comment]
You can use the overload of `publish()` that takes a function.
```java
Observable<Zip> zip = source.publish(published -> {
    return Observable.zip(
          published.buffer(2),
          OperatorMinMax.max(published),
          Zip::new);
});
```

**Comment by xdom** [comment]
@JakeWharton Looks like this works perfectly! Thank you.
