### ISSUE TITLE
2.x: Single/Maybe repeat____() functions all return Flowable

### ISSUE THREAD

**Issue by ZacSweers** [ReactiveX/RxJava#4998]
`repeat`, `repeatWhen`, etc all return `Flowable` in `Single` and `Maybe`, while they return `Observable` and `Completable` in their respective types. Is this intentional?

**Comment by ZacSweers** [comment]
Specifically looks like it might have been a copy-pasta mistake? Looking at `Completable`'s implementation, it works similarly but just converts back to `Completable` before returning.

**Comment by ZacSweers** [comment]
@akarnokd these were all added during your major 6.x backport PR last year so I can't find any context around their implementations. Do you have any insight?

**Comment by akarnokd** [comment]
https://github.com/ReactiveX/RxJava/pull/4467#r77370497

**Comment by ZacSweers** [comment]
I think I get it now.
