### ISSUE TITLE
Flowable seeded scan is shifting items by 1 until completion.

### ISSUE THREAD

**Issue by Dorvaryn** [ReactiveX/RxJava#5001]
When using `Flowable.scan(seed, accumulator)` the items emitted by the scan are shifted by one until completion of the Flowable.

As you can see on the following outputs, the scan of the ongoing Flowable with seed never sends the value `6` associated with the last item received (`3`).
That value seems to be sent when the Flowable completes (see the completed Flowable with seed output).

The expected output of the ongoing Flowable with seed should be the same as the completed Flowable with seed.

The behaviour of `Flowable.scan(accumulator)` is correct the issue is contained to the seeded version.
The behaviour of both `Observable.scan(accumulator)` and `Observable.scan(seed, accumulator)` are correct, the issue is contained to the Flowable.

Issue observed on version 2.0.4, looking at the code of `FlowableScanSeed` it seems to still be present in the 2.x branch.

Here is the code to reproduce and the outputs form running it.
```
Flowable<Integer> ongoingFlowable = Flowable.create(new FlowableOnSubscribe<Integer>() {
    @Override
    public void subscribe(FlowableEmitter<Integer> emitter) throws Exception {
        emitter.onNext(1);
        emitter.onNext(2);
        emitter.onNext(3);
    }
}, BackpressureStrategy.BUFFER);

Flowable<Integer> completedFlowable = Flowable.create(new FlowableOnSubscribe<Integer>() {
    @Override
    public void subscribe(FlowableEmitter<Integer> emitter) throws Exception {
        emitter.onNext(1);
        emitter.onNext(2);
        emitter.onNext(3);
        emitter.onComplete();
   }
}, BackpressureStrategy.BUFFER);

System.out.println("ongoing Flowable without seed");
ongoingFlowable.scan(new BiFunction<Integer, Integer, Integer>() {
   @Override
    public Integer apply(Integer acc, Integer item) throws Exception {
        return acc + item;
    }
}).subscribe(new Consumer<Integer>() {
    @Override
    public void accept(Integer integer) throws Exception {
        System.out.println(integer);
    }
 });

System.out.println("-------------------------------");
System.out.println("completed Flowable without seed");
completedFlowable.scan(new BiFunction<Integer, Integer, Integer>() {
    @Override
    public Integer apply(Integer acc, Integer item) throws Exception {
        return acc + item;
    }
}).subscribe(new Consumer<Integer>() {
   @Override
    public void accept(Integer integer) throws Exception {
        System.out.println(integer);
    }
});

System.out.println("-------------------------------");
System.out.println("ongoing Flowable with seed");
ongoingFlowable.scan(0, new BiFunction<Integer, Integer, Integer>() {
    @Override
    public Integer apply(Integer acc, Integer item) throws Exception {
        return acc + item;
    }
}).subscribe(new Consumer<Integer>() {
    @Override
    public void accept(Integer integer) throws Exception {
        System.out.println(integer);
    }
});

System.out.println("-------------------------------");
System.out.println("completed Flowable with seed");
completedFlowable.scan(0, new BiFunction<Integer, Integer, Integer>() {
    @Override
    public Integer apply(Integer acc, Integer item) throws Exception {
       return acc + item;
    }
}).subscribe(new Consumer<Integer>() {
   @Override
   public void accept(Integer integer) throws Exception {
       System.out.println(integer);
    }
});
```

```
ongoing Flowable without seed
1
3
6
-------------------------------
completed Flowable without seed
1
3
6
-------------------------------
ongoing Flowable with seed
0
1
3
-------------------------------
completed Flowable with seed
0
1
3
6

```

**Comment by akarnokd** [comment]
Yes, this is deliberate. The reason is to avoid the excessive overhead of backpressure handling due to the very first item. If your source doesn't hold back its onComplete or the downstream doesn't target an exact request boundary then you get all items in time.

**Comment by Dorvaryn** [comment]
Maybe I'm using the wrong tool for the task then, I have a source that sometimes might take some time in between emitting items, what can I do to ensure I get the output accumulated value before I get the next item (since it might be a sizable delay between them).

**Comment by akarnokd** [comment]
For example:

```java
Flowable.just(0)
.concatWith(source.scan((a, b) -> a + b));
```

**Comment by Dorvaryn** [comment]
I did simplify the code example in my case the Seed/Accumulator are of a different type from the items being emitted, that is why a scan without seed is not possible.

**Comment by akarnokd** [comment]
The only workaround is to use `Observable.scan` instead since your source is emitting less frequently.

**Comment by Dorvaryn** [comment]
I might try later with a form of either type and a accumulator function that checks the variant. Feels like abusing the type system though. I would love to hear if you have any ideas on this issue. Thanks for the help and fast replies.

**Comment by Dorvaryn** [comment]
Ok thanks for the input and fast replies.
