### ISSUE TITLE
2.x: BaseTestConsumer.assertFailure(Throwable throwable)

### ISSUE THREAD

**Issue by vanniktech** [ReactiveX/RxJava#5008]
Would allow to test that a Throwable variable was the one who onerror'd instead of using `.assertFailure(MyException.class)` or `.assertFailure(throwable -> throwable == myException)`

**Comment by akarnokd** [comment]
Maybe. I wrote thousands of tests and it rarely ever came up to check for exact instance. I usually check the message and differentiate with that between sources of error.

**Comment by vanniktech** [comment]
Yup can understand which is why I brought it up for discussion. Also there's the workaround of using the Predicate.

**Comment by vanniktech** [comment]
I'll just stick to the predicate
