### ISSUE TITLE
How to set thread priority in android with android value(like Process.THREAD_PRIORITY_BACKGROUND) in 2.x

### ISSUE THREAD

**Issue by ghost** [ReactiveX/RxJava#5011]
I mean, the `Schedulers.io()`, `Schedulers.computation()` etc. I searched this for a long time, I just got a way to do this in java:`System.setProperty(String key, String value)`,this method just can make value[1,10] go into effect, not the android thread priority value [-20,19], I don't know how to set this in android.

**Comment by akarnokd** [comment]
The problem is:

> IllegalArgumentException - If the priority is not in the range MIN_PRIORITY to MAX_PRIORITY.

There is a PR in the works that let's you define your own `ThreadFactory` and replace the default schedulers on initialization.

**Comment by artem-zinnatullin** [comment]
Sample code from our project (kotlin):

```kotlin
import android.os.Process
import java.util.concurrent.ThreadFactory
import java.util.concurrent.atomic.AtomicInteger

/**
 * See [rx.internal.util.RxThreadFactory].
 */
class JunoRxThreadFactory(private val prefix: String, private val androidThreadPriority: Int) : ThreadFactory {

    private val counter = AtomicInteger()

    override fun newThread(runnable: Runnable?) = Thread(
            {
                Process.setThreadPriority(androidThreadPriority)
                runnable?.run()
            },
            "$prefix ${counter.incrementAndGet()}")
            .apply { isDaemon = true }
}
```

We use it for all schedulers and apply [`THREAD_PRIORITY_BACKGROUND`](https://developer.android.com/reference/android/os/Process.html#THREAD_PRIORITY_BACKGROUND). It reduces number of "descheduled frame" warnings noticed by systrace, especially during application startup.

**Comment by akarnokd** [comment]
I defer to @artem-zinnatullin 's expertise on this topic. If you have further input on the issue, don't hesitate to reopen this issue or post a new one.
