### ISSUE TITLE
2.x: Reusing observers with managing subscriptions/disposables. 

### ISSUE THREAD

**Issue by youngam** [ReactiveX/RxJava#5012]
I have the following problem: I have observer for network request, which can be reused in future (user swipe to refresh and etc). The problem is that I want to have ability to unsubscribe from results in any time and don't want to recreate observer each time. Code looks like that.
```java
protected Observer<Collection<T>> mResponseObserver = new Observer<Collection<T>>() {
        @Override
        public void onSubscribe(Disposable d) {
          // don't know how to store reference in another way     
          mDisposable = d;
        }
     .....................
    };
..........................
// can execute periodically
void onRefresh() {
    observableA.subscribe(mResponseObserver);
}

.........................
void dispose() {
    mDisposable.dispose();
}
```
I try variant replacing ``` Observer``` with ```DisposableObserver``` and save disposable using ```subscribeWith()``` method, but it throw ```java.lang.IllegalStateException: Disposable already set!``` which is logical.

Maybe I'm wrong and I need to create new observer each time ? What is the best practice?

**Comment by akarnokd** [comment]
The best practice is to create an `Observer` every time you want to subscribe.

**Comment by youngam** [comment]
Thank you very much for fast response. Can you please explain in two sentences or reference me to some source where I can read why it is not good to reuse observers?

**Comment by akarnokd** [comment]
Most developers don't know enough about concurrency, the java memory model, the flow and lifecycle model of RxJava to ensure such optimizations actually work. I don't think you have thousands or millions of subscriptions that you can't afford allocating a few dozen new `Observer`s when needed.
