### ISSUE TITLE
2.0.4 firstOrError result is random instead of emit first item

### ISSUE THREAD

**Issue by kxfeng** [ReactiveX/RxJava#5013]
This is my code, I expect only "123" is printed. But actually, most times the result is  throw a TestException, print "123", then the app crash. Some times only "123" or "TestException" is printed. 

```java
Observable.create(
                new ObservableOnSubscribe<String>() {
                    @Override
                    public void subscribe(ObservableEmitter<String> emitter) throws Exception {
                        Thread.sleep(1000);
                        emitter.onNext("123");
                        emitter.onNext("456");
                        emitter.onError(new Exception("TestException"));
                    }
                })
                .subscribeOn(Schedulers.io())
                .observeOn(AndroidSchedulers.mainThread())
                .firstOrError()
                .subscribe(
                    result -> System.out.println(result),
                    error -> System.out.println(error.getMessage())
                );
```

RxJava 2.0.4, RxAndroid 2.0.1, Android 7.1

Thanks to @akarnokd . With `RxJavaPlugins.setErrorHandler` everything works fine. I should read the wiki carefully about error handling in [What's different in 2.0](https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0#error-handling).

**Comment by akarnokd** [comment]
The `firstOnError` is racing with the `emitter.onError` and if `onError` can't get through due to the cancellation in `firstOnError`, the error is routed to the global error handler which crashes on Android. Since RxJava can't decide which exceptions to keep or drop, you should register a handler in `RxJavaPlugins.setErrorHandler` that consumes such errors.
