### ISSUE TITLE
Front page HelloWorld example does not work out of the box

### ISSUE THREAD

**Issue by dims12** [ReactiveX/RxJava#5014]
Library version is follows:

```
         <dependency>
            <groupId>io.reactivex.rxjava2</groupId>
            <artifactId>rxjava</artifactId>
            <version>2.0.4</version>
        </dependency>
```
Code is follows:

```
import io.reactivex.*;
public class HelloWorld {


   public static void main(String[] args) {
      Flowable.just("Hello world").subscribe(System.out::println);
   }

}
```

error messge is follows:

> Error:(12, 15) java: cannot access org.reactivestreams.Publisher
>   class file for org.reactivestreams.Publisher not found

**Comment by akarnokd** [comment]
Are you using just plain maven? You have to manually reference `org.reactivestreams:reactive-streams:1.0.0' as dependency in maven or switch to Gradle.

**Comment by dims12** [comment]
There is a maven snippet on the page and no any word about `org.reactivestreams:reactive-streams`

**Comment by akarnokd** [comment]
This will be addressed with the release of 2.0.5.

**Comment by akarnokd** [comment]
Closing via #5015.

**Comment by renderit** [comment]
@dims12 @akarnokd Hi, did you solve this? Having the same issue. My pom.xml:
```
<dependency>
      <groupId>org.reactivestreams</groupId>
      <artifactId>reactive-streams</artifactId>
      <version>1.0.0.final</version>
    </dependency>

    <dependency>
      <groupId>io.reactivex.rxjava2</groupId>
      <artifactId>rxjava</artifactId>
      <version>2.0.7</version>
    </dependency>
```
I'm using IDEA btw. When I try:
```
Flowable.just("Hello world").subscribe(System.out::println);
```
I get error: `Method reference are not supported at this language level` around the println statement

**Comment by xxLestadxx** [comment]
Hi, I started a Gradle project in intellij, but I am having the same problem, any thoughts?

**Comment by akarnokd** [comment]
Works for me:

![image](https://user-images.githubusercontent.com/1269832/42451102-83a57f4a-8386-11e8-9363-05a8aaf41239.png)

**Comment by xxLestadxx** [comment]
Thank you very much! ... had a typo...
