### ISSUE TITLE
CompositeDisposable holds reference from already disposed Disposable

### ISSUE THREAD

**Issue by StefMa** [ReactiveX/RxJava#5016]
Thanks for using RxJava but before you post an issue, please consider the following points:

  - [x] Please include the library version number, including the minor and patch version, in the issue text. In addition, if you'd include the major version in the title (such as `2.x`) that would be great.

->  compile 'io.reactivex.rxjava2:rxjava:2.0.3'

  - [x] If you think you found a bug, please include a code sample that reproduces the problem. Dumping a stacktrace is usually not enough for us.

-> This test is green.
Expected that `disposable.size` is `1`. Like in CompositeSuubscription from RxJava 1.
```java
    @Test
    public void name() throws Exception {
        final TestObserver<Integer> firstTestObserver = new TestObserver<>();
        firstTestObserver.dispose();
        final TestObserver<Integer> secondTestObserver = new TestObserver<>();

        assertThat(firstTestObserver.isDisposed(), is(equalTo(true)));
        assertThat(secondTestObserver.isDisposed(), is(equalTo(false)));

        final CompositeDisposable disposable = new CompositeDisposable();
        disposable.addAll(firstTestObserver, secondTestObserver);

        assertThat(disposable.size(), is(equalTo(2)));
    }
```
 
 - [x] RxJava has more than 150 operators, we recommend searching the [javadoc](http://reactivex.io/RxJava/2.x/javadoc/io/reactivex/Observable.html) for keywords of what you try to accomplish.

-> I expect that the CompositeDisposable don't add an already disposed `Disposable`.
Like the [CompsositeSubscription](https://github.com/ReactiveX/RxJava/blob/1.x/src/main/java/rx/subscriptions/CompositeSubscription.java#L99).

**Comment by akarnokd** [comment]
We don't do that anymore and the expected behavior is now deferred to the developer:

```java
if (!firstTestObserver.isDisposed()) {
    disposable.add(firstTestObserver);
}
```

**Comment by StefMa** [comment]
OK, when it is expected from your side it is ok for me 😄 ❤️ 
Thanks for the fast response 👎

**Comment by passsy** [comment]
@akarnokd can you go into detail why it is beneficial to hold a reference to an already disposed `Disposable`?

**Comment by akarnokd** [comment]
Why would you try to add them in the first place if you know they are disposed?
