### ISSUE TITLE
java.lang.RuntimeException: Can't create handler inside thread that has not called Looper.prepare()

### ISSUE THREAD

**Issue by CodeDogDream** [ReactiveX/RxJava#5018]
I use Rxjava2 with retrofit .It is right when the lenght of the paramete is short,When I make the length of the parameter longer.It report this error.I have this piece of code;

```java
public void sendRequest(String url, MySubscriber ss, HashMap<String, String> data) {
Flowable mObservable;
final String[] paths = url.split("/");
mObservable = myApi.getData(paths[0], paths[1], data);
mObservable.observeOn(new HandlerScheduler(new Handler(Looper.getMainLooper()))).
subscribeOn(Schedulers.io())
.subscribe(ss);
}
```
This is my Interface
```java
private interface MyApi {
@FormUrlEncoded
@Headers(HttpData.Header)
@POST("{path1}/{path2}")
Flowable getData(@Path("path1") String path1, @Path("path2") String path2, @FieldMap HashMap<String, String> data);
}
```

**Comment by akarnokd** [comment]
Hi.

1) There is the `AndroidSchedulers.mainThread()` instead of manually creating a looper.
2) Swap `subscribeOn` with `observeOn`.
3) On what thread does this `sendRequest` get called?
4) What is the stacktrace of the error?
