### ISSUE TITLE
Create Maybe from null in RxJava 2.0.4

### ISSUE THREAD

**Issue by AleksanderMielczarek** [ReactiveX/RxJava#5019]
Hi,

I wanted to created Maybe from null. When using Java 8 Optional there is `ofNullable`. In RxJava this can be achieved with:

```
Data nullableData = getNullableData();
Maybe<Data> maybe = nullableData == null ? Maybe.empty() : Maybe.just(nullableData);
```

Instead I'd prefer to use something like:

```
Data nullableData = getNullableData();
Maybe<Data> maybe = Maybe.ofNullable(nullableData);
```

Will similar method be added in any future release?

Best regards
Aleksander Mieczarek

**Comment by akarnokd** [comment]
No. Use a conditional and pick just() or empty().

**Comment by davidmoten** [comment]
I'm very accustomed to using java 8 `Optional.ofNullable` and guava's `Optional.fromNullable` to avoid the appearance of `null` in code so seems like a natural enough addition to me. What are the objections?

**Comment by akarnokd** [comment]
1) You want an entire operator for an `if` statement that you can do manually. Many don't see the associated maintenance cost: documentation, unit tests, education.
2) Source-like operators don't have to live in RxJava. You can have your own static factory method anywhere:

```java
public final class RxUtils {
    public static <T> Maybe<T> ofNullable(T value) {
        return value == null ? Maybe.empty() : Maybe.just(value);
    }
}
```

**Comment by AleksanderMielczarek** [comment]
@akarnokd I've heard that `Maybe` is reactive `Optional` so similar API is good. In Guava there is actually such an `if` underneath. 

If you don't mind I can create PR.

**Comment by akarnokd** [comment]
**Source-like operators don't have to live in RxJava. You can have your own static factory method anywhere.**

Also `Maybe.fromCallable(() -> null)` is permitted.

**Comment by davidmoten** [comment]
`Maybe.fromCallable(() -> null)` is good to know about, thanks. 

In general I think even simple convenience methods should be considered for the API because 

* it can improve peoples perception of the ease of use of the api
* it prevents people having to write these simple methods and their unit tests themselves 
* it prevents people needing to add external libraries to their project

Having said that I appreciate the impact of any api addition in the areas you mentioned. I'm happy to pass on this addition and see how much this comes up in the future.

**Comment by mapkuff** [comment]
`Maybe.fromCallable(() -> null)` I always use this one but I think it's make code hard to read 
but I really love this one `Maybe.fromNullable(something)`

**Comment by akarnokd** [comment]
See also [this Optional-to-RxJava](https://github.com/akarnokd/RxJava2Jdk8Interop#optional-to-rxjava).

**Comment by mapkuff** [comment]
In my opinion, Maybe is Maybe.
And it should be able to accept nullable value like `java.util.Optional` does.

Something like `Maybe.just(xx)` and `Maybe.justNullable(xx)`.

**Comment by ZacSweers** [comment]
I agree with @akarnokd on this one. You can just as easily add your own factory. This would kind of pollute null safety within rx IMO

**Comment by akarnokd** [comment]
Closing as won't happen. Static methods returning RxJava types can live on any external class.

**Comment by stephanenicolas** [comment]
Sorry to add to this, but `fromNullable` would be nice. And there is actually the same amount of logic in `fromCallable`...

**Comment by carterhudson** [comment]
@stephanenicolas @AleksanderMielczarek @mapkuff @davidmoten  I also ran into this issue, so I made this https://github.com/carterhudson/RxOptional
