### ISSUE TITLE
2.x: retryWhen not working

### ISSUE THREAD

**Issue by guidedways** [ReactiveX/RxJava#5028]
I'm using RxJava2 (v2.0.4). I've got a basic RxBus based around a Subject that I use to post UI events.

I'm trying to debounce incoming events and then only letting the observer see the event if the user isn't actively scrolling the list. I am throwing an error if a condition isn't met and then retrying after a short delay.

```java
RxBus.INSTANCE.asObservable()
            .subscribeOn(Schedulers.computation())
            .observeOn(AndroidSchedulers.mainThread())
            .filter(o -> (o instanceof EventDataChanged))
            .debounce(650, TimeUnit.MILLISECONDS)
            .map(o -> {
              if (/*!isListScrolling()*/ 1 == 1) {
                Log.d("NOTIFY", "LIST IS BUSY... ");
                return Observable.error(new Throwable());
              }
              return o;
            })
            .retryWhen(source -> {
              Log.d("NOTIFY", "... RETRYING: " + source);
              return source.delay(100, TimeUnit.MILLISECONDS);
            })
            .subscribe(o -> {
              Log.d("NOTIFY", "LIST SHOULD REFRESH NOW");
              refreshListNow();
            }));
```

What I see in the console is:

LIST IS BUSY...
LIST SHOULD REFRESH NOW

I'm not seeing '...RETRYING' at all. Nor does it retry. The code for RxBus is simple:

```java
public class RxBus {
  public static final RxBus INSTANCE = new RxBus();

  private final Subject<Object> _bus;

  private RxBus() {
    _bus = PublishSubject.create().toSerialized();
  }

  public void post(Object o) {
    _bus.onNext(o);
  }

  public io.reactivex.Observable<Object> asObservable() {
    return _bus.hide();
  }
}

public class EventDataChanged {
}
```

To test:

```java
RxBus.INSTANCE.post(new EventDataChanged());
```

**Comment by akarnokd** [comment]
Please avoid [cross posting](http://stackoverflow.com/questions/41900294/rxjava-retry-on-failure-thrown-inside-of-doonnext).

Why not just filter for `isListScrolling` after the debounce and drop the `retryWhen`?

**Comment by guidedways** [comment]
Sorry I wasn't trying to cross-post, a friend suggested this may be a bug in Rx so I thought I'd post it here, and if it turns out to be one, I'll update SO.

Yes I could in theory create a new observable for isListScrolling but any reason why retryWhen shouldn't work? The above example is an over simplification of what I'm trying to do.

**Comment by guidedways** [comment]
Regarding the filter - I don't want to use one after the debounce as that would drop incoming events. I want these to stick around and be retried. It's important all fired events are processed sequentially.

**Comment by akarnokd** [comment]
1) You should see the `RETRYING` exactly once when the subscription happens and not when an error occurs because the `Function` that has to return the signalling observable is called once for each subscriber.

2) In your map, you map to an `Observable.error()` object which is then emitted as-is, not unwrapped.

3) The single event you are emitting is consumed and when the resubscription happens, you have to send out another event via the bus.

4) The whole retryWhen setup is prone to data loss because multiple events might be in some internal buffer when you crash and retry the flow.

5) Since `RxBus` is a `Subject`, `subscribeOn` has no practical effect.

You may want to consider the operator [valve](https://github.com/akarnokd/RxJava2Extensions#flowabletransflormersvalve) that let's you pause streams without losing data.

**Comment by guidedways** [comment]
Thank you, that explains a lot. So my understanding of retry in general was flawed, as I assumed it would re-subscribe *and* cause the source to re-emit automagically. 

I think what I really need is the valve operator, as that might just solve my problem. What I actually want is to be able to pause the stream and resume it. Thank you!

**Comment by guidedways** [comment]
A clarification of point (3), if you may. So is that how retry() works in general? Does it simply resubscribe and hope the source re-emits? It works for observables since these emit when subscribed, but I guess in my case it didn't since it's an event bus, with no new events to process?

If so, the word retry sounds a bit misleading; I know there's no magic behind the scenes, but it sounds like and feels like an operator that wound somehow push the last failed emitted value back to the source to re-emit (now that I think about it, I know that's not how it should work in the first place).

**Comment by akarnokd** [comment]
> So is that how retry() works in general? Does it simply resubscribe and hope the source re-emits?

It is flow dependent. In your particular *hot* observable source, a resubscribe will find an empty Subject.

>I know that's not how it should work in the first place

RxJava is a dataflow library and not a reliable-messaging middleware like JMS. Besides, what you suggest would crash the flow in a tight loop until the not-crash condition is met which is a nice way of draining the battery.

**Comment by akarnokd** [comment]
Closing via [Stackoverflow](http://stackoverflow.com/questions/41900294/rxjava-retry-on-failure-thrown-inside-of-doonnext#comment70999286_41901541)
