### ISSUE TITLE
Codecov service integration changed

### ISSUE THREAD

**Issue by akarnokd** [ReactiveX/RxJava#5037]
You may have noticed that the last few PRs didn't receive the nice code coverage report as before. It looks like codecov.io changed their bot behavior and now one has to [install an integration](https://github.com/integration/codecov) to their services for the outermost user of the repository.

This means, for example, that if I followed the install links, I add the integration services to myself (github.com/akarnokd), even if going through the ReactiveX/RxJava repository.

Consequently, it is likely that the owner of the ReactiveX organization has to perform this service integration setup and restrict it to only the set of RxJava-related repos manually (otherwise everybody starts to get annoying "missing" codecov messages).

@abersnaze @benjchristensen do you know who can perform this change?

**Comment by benjchristensen** [comment]
I haven't had time to look into this this week but I'll help.

**Comment by benjchristensen** [comment]
Well that was easy. Clicked install. Authorized. Seems done. Can you confirm?

**Comment by akarnokd** [comment]
Needs a PR to trigger. I'll adjust something in README to trigger it. We'll find out in 15 minutes.

**Comment by akarnokd** [comment]
It works: #5046. Thanks Ben!
