### ISSUE TITLE
debounce operator with immediate/leading flag

### ISSUE THREAD

**Issue by linktohack** [ReactiveX/RxJava#5041]
Hello I understand that this is not really a technical question, I have posted it on StackOverflow but I have not found an answer yet... http://stackoverflow.com/questions/41964731/immediate-debounce-in-rx

I am looking an operator to `debounce` a series of event, let us say user's click. The input and output should be like this:

    interval :      ->     <-            ->     <-
    in       : 1--2--3-------4--5--5--6-7-8--------
    out      : 1-------------4---------------------

The idea is like underscore's debounce with `immediate` option `on` http://underscorejs.org/#debounce. The operator can be presented/implemented in any language that supports Reactive Extensions. Here is an image ![image][1] which can be found at the [original article][2]

A more understandable version: 

Assume that an interval of 5 seconds (5 spaces between two arrows) : `->     <-`

I have a user, he clicks repeatedly a button (1, 2, 3); I want to catch the first `click` (1) and ignore the rest. After a while, he is tired and rest for 7 seconds (which is longer than the 5 seconds interval between two arrows) and continue clicking the button again (4, 5, 6, 7, 8) I want to catch the first `click` (4) and ignore the rest.

If he clicks after the forth arrow, I want to catch that click, too.

Thank you

[1]: https://cdn.css-tricks.com/wp-content/uploads/2016/04/debounce-leading.png
[2]: https://css-tricks.com/debouncing-throttling-explained-examples/#article-header-id-1

**Comment by akarnokd** [comment]
Hi.

You barely asked this question 18 hours ago. Stackoverflow is a place to get answers within a few days and [my answers are often overlooked](http://stackoverflow.com/a/41969532/61158).

Based on the updated question, it seems you want to block out further events after the first and reset the grace period timer every time there is another emission. We don't have a specific operator for this but you can achieve this with a combination of non-trivial set of operators:

```java
import java.util.concurrent.TimeUnit;

import rx.Observable;

public class DebounceFirst {

    public static void main(String[] args) {
        Observable.just(0, 100, 200, 1500, 1600, 1800, 2000, 10000)
        .flatMap(v -> Observable.timer(v, TimeUnit.MILLISECONDS).map(w -> v))
        .doOnNext(v -> System.out.println("T=" + v))
        .compose(debounceFirst(500, TimeUnit.MILLISECONDS))
        .toBlocking()
        .subscribe(v -> System.out.println("Debounced: " + v));
    }
    
    static <T> Observable.Transformer<T, T> debounceFirst(long timeout, TimeUnit unit) {
        return f -> 
            f.publish(g ->
                g.take(1)
                .concatWith(
                    g.switchMap(u -> Observable.timer(timeout, unit).map(w -> u))
                    .take(1)
                    .ignoreElements()
                )
                .repeatWhen(h -> h.takeUntil(g.ignoreElements()))
            );
    }
}
```

**Comment by linktohack** [comment]
Thank you @akarnokd. That's exactly what I am looking for.
