### ISSUE TITLE
retrofit2 with doOnNext(),doAfterNext()

### ISSUE THREAD

**Issue by smzh369** [ReactiveX/RxJava#5042]
```java
queryBing.queryBingPic()
                .subscribeOn(Schedulers.io())
                .doAfterNext(new Consumer<ResponseBody>() {
                    @Override
                    public void accept(ResponseBody responseBody) throws Exception {
                        **String bingUrl = responseBody.string();**
                        SharedPreferences.Editor editor = PreferenceManager.getDefaultSharedPreferences(WeatherActivity.this).edit();
                        editor.putString("bing_pic",bingUrl);
                        editor.apply();
                    }
                })
                .observeOn(AndroidSchedulers.mainThread())
                .subscribe(new Subscriber<ResponseBody>() {
                    @Override
                    public void onSubscribe(Subscription s) {
                        s.request(Long.MAX_VALUE);
                    }
                    @Override
                    public void onNext(ResponseBody responseBody) {
                        try{
                            **String bingUrl = responseBody.string();**
                            Glide.with(WeatherActivity.this).load(bingUrl).into(bingPicImg);
                        }catch (Exception e){
                            e.printStackTrace();
                        }
                    }
                    @Override
                    public void onError(Throwable t) {
                    }
                    @Override
                    public void onComplete() {
                    }
                });
```

After I write 'String bingUrl = responseBody.string()' in doOnNext()/doAfterNext(),the responsebody seems
changed in onNext() method and the same code (String bingUrl = responseBody.string()) in onNext() only get "null" value.

And if I dont write that code in doOnNext()/doAfterNext() everything is ok

How does it happen?

**Comment by akarnokd** [comment]
`ResponseBody` is part of Retrofit2 and thus non-RxJava. I don't know what its access pattern, thread safety or lifecycle requirements are. You have better chance asking such kind of questions on [StackOverflow](https://stackoverflow.com).

**Comment by naturalwarren** [comment]
ResponseBody is actually an OkHttp 3 thing ;)

I'd encourage you to read the JavaDoc on top of the ResponseBody class. Note that each ResponseBody is backed by an active connection to a web server:

```
 * <p>Because this class does not buffer the full response in memory, the application may not
 * re-read the bytes of the response. Use this one shot to read the entire response into memory with
 * {@link #bytes()} or {@link #string()}. Or stream the response with either {@link #source()},
 * {@link #byteStream()}, or {@link #charStream()}.
 */
```

Note that you also need to make sure you call `.close()`!

**Comment by JakeWharton** [comment]
Call `.map(ResponseBody::string)` before your `doOn` operators to consume the body into an immutable string. Or, better yet, change your Retrofit interface to return a `String` directly instead of `ResponseBody` (by adding the 'scalars' converter).

This isn't a problem or at all related to RxJava though. You'd have the same problem calling `.string()` twice on a `ResponseBody` always.

**Comment by smzh369** [comment]
@naturalwarren 
thank you i will read :)

**Comment by smzh369** [comment]
@JakeWharton 
Thank you so much. I kown where the problem is by your reply 👍

**Comment by smzh369** [comment]
@akarnokd 
the other two solved my problem.it is indeed not a problem with rxjava at all
