### ISSUE TITLE
Declare subscription order for amb and ambWith in documentation.

### ISSUE THREAD

**Issue by JakeWharton** [ReactiveX/RxJava#5044]
`amb()` should declare that it subscribes to the supplied observables in the order of the iterable/array. `ambWith()` should declare that it subscribes to the host observable before the supplied 'other' observable.

This allows consumers to explicitly rely on this ordering and a deviation from it to be a bug.

**Comment by JakeWharton** [comment]
I can send a PR for this, I just wanted to make sure that the subscription order is something that we want to put into the public API. In theory a perfectly acceptable implementation of `ambWith` _could_ be `amb(other, this)` (but that'd be bad!).

**Comment by akarnokd** [comment]
This ordered subscribe is implied, what makes you want this to be explicitly defined?

**Comment by JakeWharton** [comment]
We have code whose behavior depends on it. It basically does
behaviorSubject.ambWith(just(sentinel)) to ensure a value is always
synchronously emitted downstream upon subscribe. Would the subscription
order of this (or amb) change we'd never see the subject value when it was
set.

**Comment by akarnokd** [comment]
This looks like you need `BehaviorSubject.createDefault(sentinel)` (or `create(sentinel)` to make sure you have something to start with when subscribing.

Generally, I don't think such ordering guarantee should explicitly be declared on `amb`.

**Comment by JakeWharton** [comment]
That was a contrived example so your suggestion won't work in practice. I
see no reason to omit ordering guarantees around subscription since the
behavior in the synchronous case relies on it. Also it would be completely
illogical to have any ordering but the obvious one that already exists, so
this really isn't a commitment of any challenge.

**Comment by akarnokd** [comment]
Okay then, but don't forget to add unit tests that verify the order is actually held by the implementation (in case of another complete rewrite for 3.x). 5 base types x 3 `amb` types == 15 tests.

**Comment by valeriyo** [comment]
Essentially, docs should (more) explicitly state that this:

`assertThat(amb(just(1), just(2)).toBlocking().single()).isEqualTo(1);`

**Comment by akarnokd** [comment]
Closing via #5047.
