### ISSUE TITLE
2.x: RxJavaPlugin.get/setXXX generics?

### ISSUE THREAD

**Issue by davidmoten** [ReactiveX/RxJava#5045]
For unit tests I frequently bump into the restrictiveness of 

```java
RxJavaPlugins.setErrorHandler(Consumer<Throwable> handler);
```

I would like the signature to be 

```java
RxJavaPlugins.setErrorHandler(Consumer<? super Throwable> handler);
```

There are many more methods in `RxJavaPlugins` that could support lower and upper bounded wildcards. Can I make these changes?

**Comment by akarnokd** [comment]
setErrorHandler: yes, others would bring trouble I think.

**Comment by jschneider** [comment]
I gave it a shot: https://github.com/ReactiveX/RxJava/pull/5058
Widening the generics seems to work so far

But of course I don't know about any side effects, possible problems.
