### ISSUE TITLE
1.x: observable with a subject as source

### ISSUE THREAD

**Issue by feresr** [ReactiveX/RxJava#5050]
#Hi, I'm still on RxJava1, I'll try to keep it short

**EDITED AFTER COMMENT FROM @akarnokd:** Reduced scope of the problem to a simple java console application

Sorry about the cross posting, I thought this might be something wrong with RxJava this is why I posted it here as well. I doubt that's the case but I've managed to reduce the scope of the problem, this is a simple java console app:

```
public static void main(String[] args) throws InterruptedException {
        BehaviorSubject<Integer> subject = BehaviorSubject.create();
        Observable<String> observable;
        
        CountDownLatch latch = new CountDownLatch(1);

        observable = subject.observeOn(Schedulers.io()).map(String::valueOf)
                .doOnNext(s -> {latch.countDown(); });

        subject.onNext(1);
        latch.await();
}
```
Why doesn't this program finishes? I know that no one is using the observable right now (I want to subscribe later), but it's there, and it's hot (its source is a subject). It should be taking items downstream and hitting latch.countDown().

**Comment by akarnokd** [comment]
Please avoid cross posting, especially if your problem involves Android and any complicated UI model.

http://stackoverflow.com/questions/42006077/how-to-modify-subject-output-type

**Comment by feresr** [comment]
Sorry about the cross posting, I thought this might be something wrong with RxJava this is why I posted it here as well. Now I don't think there's something wrong with it. There's something I am not getting right.

I've managed to reduce the scope of the problem, this is a simple java console app:

```
        BehaviorSubject<Integer> subject = BehaviorSubject.create();
        Observable<String> observable;
        
        CountDownLatch latch = new CountDownLatch(1);

        observable = subject.map(String::valueOf).observeOn(Schedulers.io())
                .doOnNext(s -> {latch.countDown(); });

        subject.onNext(1);
        latch.await();
```

Why doesn't this program finishes? I know that no one is using the observable right now (I want to subscribe later), but it's there, and it's hot (its source is a subject). It should be taking items downstream and hitting `latch.countDown()`.

**Comment by akarnokd** [comment]
> Why doesn't this program finishes?

You didn't subscribe to `observable`. If there is no subscriber listening, any value sent to `subject` is dropped.

**Comment by feresr** [comment]
There's no subscribers on the observable, but as it is hot, there doesn't need to be. right?

**Comment by akarnokd** [comment]
Okay, I see what you meant by hotness. Just applying operators to a subject doesn't make the resulting `Observable` hot - meaning that the operator executes its effect but nobody receives items from it.

It's like increasing the volume on a radio station but your radio is turned off. The radio station keeps playing independently but your volume settings have observable effect.

**Comment by feresr** [comment]
Oh, gotcha, thanks @akarnokd  
So basically what I'm looking for is a Subject with a output different from its input, where the transformation Input -> Output happens regardless of subscribers.
Why a subject? because I want to be able to feed them <Inputs> like this subject.onNext(input); 
I'll read on this to see if it's even possible. Thanks!

**Comment by akarnokd** [comment]
Closing via [StackOverflow](http://stackoverflow.com/a/42016452/61158).
