### ISSUE TITLE
2.x: SpscLinkedArrayQueue#poll returns null

### ISSUE THREAD

**Issue by jschneider** [ReactiveX/RxJava#5053]
io.reactivex.internal.queue.SpscLinkedArrayQueue#poll returns null

io.reactivex.internal.fuseable.SimpleQueue#poll is not documented or annotated. Therefore I do not know whether returning null is allowed. But I strongly suspect this is not the case.

If SimpleQueue#poll might return null, at least io.reactivex.internal.operators.flowable.FlowableGroupJoin.GroupJoinSubscription#drain needs to be fixed.

**Comment by akarnokd** [comment]
SimpleQueue may return null indicating an empty queue.

> If SimpleQueue#poll might return null, at least io.reactivex.internal.operators.flowable.FlowableGroupJoin.GroupJoinSubscription#drain needs to be fixed.

You mean L238? Due to the bi-offer, if the first call to poll is not null the second one is guaranteed to be non null. You have a false positive there.

**Comment by jschneider** [comment]
Yes, that is the line. Ok, is a false positive.
I will add some annotations to SimpleQueue to avoid confusion.

**Comment by jschneider** [comment]
https://github.com/ReactiveX/RxJava/pull/5054
