### ISSUE TITLE
Update ReadMe example of parallel operations

### ISSUE THREAD

**Issue by lucas34** [ReactiveX/RxJava#5061]
Hi,

The readMe has an example for execution of a parallel operations
```java
Flowable.range(1, 10)
  .flatMap(v ->
      Flowable.just(v)
        .subscribeOn(Schedulers.computation())
        .map(v -> v * v)
  )
.blockingSubscribe(System.out::println);
```

If I not mistaken since the version 2.0.5 we can implement as following 
```java
Flowable.range(1, 10)
.parallel()
.runOn(Schedulers.computation())
.map(v -> v * v)
.sequential()
.blockingSubscribe(System.out::println);
```

Should we update the readMe ?

**Comment by akarnokd** [comment]
Sure, I'll post an update.

**Comment by GeorgePetri** [comment]
Just a quick question: what are the advantages of using .parallel() over just flatmapping it?

**Comment by akarnokd** [comment]
Performance and the way you write more flat code.

**Comment by akarnokd** [comment]
Closing via #5062.
