### ISSUE TITLE
SerializedSubject no longer public in RxJava 2

### ISSUE THREAD

**Issue by mradzinski** [ReactiveX/RxJava#5065]
Is this by design? If so, is there any alternative to it? It doesn't appear to be part of the ```What's different``` documentation.

Change can be seen [here](https://github.com/ReactiveX/RxJava/blob/2.x/src/main/java/io/reactivex/subjects/SerializedSubject.java#L28)

**Comment by JakeWharton** [comment]
There's no useful methods on it vs. `Subject` so there's no reason to have a public type. You can still serialize a subject using the instance method that's on every `Subject`.

**Comment by mradzinski** [comment]
Brilliant. Thanks for the quick answer @JakeWharton

**Comment by akarnokd** [comment]
Updated the [wiki](https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0#serializedsubject) to mention this change.

**Comment by mradzinski** [comment]
That was fast! I was about to make a PR with those changes @akarnokd 😝
