### ISSUE TITLE
Documetation points to some nonexistent marble diagrams 

### ISSUE THREAD

**Issue by Stephan202** [ReactiveX/RxJava#5067]
Noticed this while reading some JavaDoc in the context of a 1.2.6 -> 2.0.5 upgrade. I wrote the following script to list all JavaDoc-referenced PNGs which do not yield an HTTP 200 response when resolved:
```sh
#!/usr/bin/env bash

find . -name '*.java' -print0 \
  | xargs -0 grep '^\s*\*' \
  | grep -oP 'https.*?\.png' \
  | sort -u \
  | while read -r I; do
      curl -L -o /dev/null -s -w "%{http_code} ${I}\n" "${I}"
    done \
  | grep -v '^200'
```
And then applied it to the `2.x` branch (rev 0a2610ef6ddfdcdce1e4fecf3434848390e9c6f4). The output is:
```
404 https://raw.github.com/wiki/ReactiveX/RxJava/images/rx-operators/Completable.toObservable.png
404 https://raw.github.com/wiki/ReactiveX/RxJava/images/rx-operators/Maybe.concat.png
404 https://raw.github.com/wiki/ReactiveX/RxJava/images/rx-operators/Maybe.error.png
404 https://raw.github.com/wiki/ReactiveX/RxJava/images/rx-operators/Maybe.flatMapCompletable.png
404 https://raw.github.com/wiki/ReactiveX/RxJava/images/rx-operators/Maybe.flatMap.png
404 https://raw.github.com/wiki/ReactiveX/RxJava/images/rx-operators/Maybe.flatMapPublisher.png
404 https://raw.github.com/wiki/ReactiveX/RxJava/images/rx-operators/Maybe.flatMapSingle.png
404 https://raw.github.com/wiki/ReactiveX/RxJava/images/rx-operators/Maybe.just.png
404 https://raw.github.com/wiki/ReactiveX/RxJava/images/rx-operators/Maybe.map.png
404 https://raw.github.com/wiki/ReactiveX/RxJava/images/rx-operators/Maybe.merge.oo.png
404 https://raw.github.com/wiki/ReactiveX/RxJava/images/rx-operators/Maybe.merge.png
404 https://raw.github.com/wiki/ReactiveX/RxJava/images/rx-operators/Maybe.observeOn.png
404 https://raw.github.com/wiki/ReactiveX/RxJava/images/rx-operators/Maybe.subscribeOn.png
404 https://raw.github.com/wiki/ReactiveX/RxJava/images/rx-operators/onExceptionResumeNextViaMaybe.png
404 https://raw.github.com/wiki/ReactiveX/RxJava/images/rx-operators/S.BehaviorProcessor.png
404 https://raw.github.com/wiki/ReactiveX/RxJava/images/rx-operators/Single.flatMapCompletable.png
404 https://raw.github.com/wiki/ReactiveX/RxJava/images/rx-operators/Single.flatMapMaybe.png
```

**Comment by akarnokd** [comment]
Thanks, I'll draw them next week.

**Comment by akarnokd** [comment]
Completable.toObservable.png
![image](https://raw.github.com/wiki/ReactiveX/RxJava/images/rx-operators/Completable.toObservable.png)

Maybe.concat.png
![image](https://raw.github.com/wiki/ReactiveX/RxJava/images/rx-operators/Maybe.concat.png)

Maybe.error.png
![image](https://raw.github.com/wiki/ReactiveX/RxJava/images/rx-operators/Maybe.error.png)

Maybe.flatMapCompletable.png
![image](https://raw.github.com/wiki/ReactiveX/RxJava/images/rx-operators/Maybe.flatMapCompletable.png)

Maybe.flatMap.png
![image](https://raw.github.com/wiki/ReactiveX/RxJava/images/rx-operators/Maybe.flatMap.png)

Maybe.flatMapPublisher.png
![image](https://raw.github.com/wiki/ReactiveX/RxJava/images/rx-operators/Maybe.flatMapPublisher.png)

Maybe.flatMapSingle.png
![image](https://raw.github.com/wiki/ReactiveX/RxJava/images/rx-operators/Maybe.flatMapSingle.png)

Maybe.just.png
![image](https://raw.github.com/wiki/ReactiveX/RxJava/images/rx-operators/Maybe.just.png)

Maybe.map.png
![image](https://raw.github.com/wiki/ReactiveX/RxJava/images/rx-operators/Maybe.map.png)

Maybe.merge.oo.png
![image](https://raw.github.com/wiki/ReactiveX/RxJava/images/rx-operators/Maybe.merge.oo.png)

Maybe.merge.png
![image](https://raw.github.com/wiki/ReactiveX/RxJava/images/rx-operators/Maybe.merge.png)

Maybe.observeOn.png
![image](https://raw.github.com/wiki/ReactiveX/RxJava/images/rx-operators/Maybe.observeOn.png)

Maybe.subscribeOn.png
![image](https://raw.github.com/wiki/ReactiveX/RxJava/images/rx-operators/Maybe.subscribeOn.png)

onExceptionResumeNextViaMaybe.png
![image](https://raw.github.com/wiki/ReactiveX/RxJava/images/rx-operators/onExceptionResumeNextViaMaybe.png)

S.BehaviorProcessor.png
![image](https://raw.github.com/wiki/ReactiveX/RxJava/images/rx-operators/S.BehaviorProcessor.png)

Single.flatMapCompletable.png
![image](https://raw.github.com/wiki/ReactiveX/RxJava/images/rx-operators/Single.flatMapCompletable.png)

Single.flatMapMaybe.png
![image](https://raw.github.com/wiki/ReactiveX/RxJava/images/rx-operators/Single.flatMapMaybe.png)

**Comment by akarnokd** [comment]
Note that the images inside the javadoc may be skewed. Let me know if you'd like to post a PR that fixes the width= and height= constants for these.

**Comment by Stephan202** [comment]
@akarnokd, thanks for generating these images. As for your fixing the dimensions, I filed PR #5087 for that; let me know whether that's what you intended.
