### ISSUE TITLE
RxJava 2.x Subject with Backpressure - let the whole list to emit once downstream has finished consuming

### ISSUE THREAD

**Issue by shakil807g** [ReactiveX/RxJava#5070]
i want all the items which emitted (list of all the buffered items) while the downstream is busy in consuming  here is the code i have come up with  is that any downside or case that need to handle

       Subject<Integer>  burstSubject =
            PublishSubject.<Integer>create().toSerialized(); 

     Subject<Integer> boundarySubject =
        PublishSubject.<Integer>create().toSerialized();

       Flowable.interval(1,TimeUnit.SECONDS)
            .observeOn(AndroidSchedulers.mainThread())
            .subscribe(value ->{

                burstSubject.onNext((int) (long)value);

      });

    burstSubject.buffer(boundarySubject)
     .subscribe(integers -> {

           Log.d(TAG, "total items "+integers.size());

    });

              //when some event come from UI or other source to get the list of
            //items emitted till now in the form of List

     fab.setOnClickListener(view -> {

        boundarySubject.onNext(++index); // ignore just for emits list from burstSubject

    }

**Comment by akarnokd** [comment]
Please avoid cross-posting.

http://stackoverflow.com/questions/42010084/rxjava-subject-with-backpressure-let-the-whole-list-to-emit-once-downstream-ha

**Comment by shakil807g** [comment]
sorry for cross-posting question but i just want to know if the solution i have come up with has any issues

**Comment by akarnokd** [comment]
Closing via [StackOverflow](http://stackoverflow.com/questions/42010084/rxjava-subject-with-backpressure-let-the-whole-list-to-emit-once-downstream-ha#comment71256655_42010084)
