### ISSUE TITLE
Code snippet in doc does not compile

### ISSUE THREAD

**Issue by asarkar** [ReactiveX/RxJava#5072]
`The code snippert shown in [Entering the reactive world](https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0#entering-the-reactive-world) is no longer valid as there is no `create` method with a single parameter in v2.0.5. The only `create` takes a `BackpressureStrategy` as the 2nd parameter.`
`Flowable.create((FlowableEmitter<Integer> emitter) -> {}`

**Comment by akarnokd** [comment]
There is no `Flowable.create` example there, deliberately. It is safe in 2.x but often used to perform something already available through other methods.

**Comment by asarkar** [comment]
@akarnokd Please pardon my sleep deprived mind. The doc does show a 2nd argument, I missed it. Should've deleted the issue but no such option, hence closed it.
