### ISSUE TITLE
[1.x] RxJavaHooks caches all Throwables (deliverable and undeliverable throwables)

### ISSUE THREAD

**Issue by mirland** [ReactiveX/RxJava#5074]
- RX Version 1.2.6

Regarding #4332, I see that in #4641 the behavior of `RxJavaHooks.onError()` changed (what is fine) in order to follow the [documentation](http://reactivex.io/RxJava/javadoc/rx/plugins/RxJavaHooks.html#setOnError(rx.functions.Action1)). In that pull request was changed the way of handling the deliverable errors, [the `RxJavaHooks.onError(e)` was changed to `RxJavaPlugins.getInstance().getErrorHandler().handleError(e)`](https://github.com/ReactiveX/RxJava/pull/4641/files#diff-f870e14888907157e70ba89d0c268dafL150), which now it's deprecated. 

I want to know if there is a clear way of catching all throwables (deliverable and undeliverable throwables) without using a deprecated function (`RxJavaPlugins.getInstance().getErrorHandler().handleError(e)`). If it doesn't exist, in my opinion it'd be nice adding it.

/cc @xmartlabs/android

**Comment by akarnokd** [comment]
https://github.com/ReactiveX/RxJava/wiki/Plugins

You can hook the assembly of a chain and extract the `Throwable` travelling through `onError`.

**Comment by mirland** [comment]
I don't understand. Can you explain further?

**Comment by akarnokd** [comment]
I recommend studying the assembly tracking support:

https://github.com/ReactiveX/RxJava/blob/1.x/src/main/java/rx/internal/operators/OnSubscribeOnAssembly.java#L29

https://github.com/ReactiveX/RxJava/blob/1.x/src/main/java/rx/plugins/RxJavaHooks.java#L1187

**Comment by mirland** [comment]
thanks @akarnokd, it was really helpful
