### ISSUE TITLE
RxJava 2.x does not have delaySubscription API for Completable.

### ISSUE THREAD

**Issue by tonycosentini** [ReactiveX/RxJava#5081]
Seems like an oversight since this exists in 1.x.

**Comment by akarnokd** [comment]
Could you be more specific?

**Comment by tonycosentini** [comment]
Apoligies for the vague issue.

I thought Rx 1.x had `delaySubscription` available for Completable and it was missing in 2.x. It looks like that's not the case though, delaySubscription is not available in either 1.x or 2.x.

Would it be ok to add `delaySubscription` for Completable in 2.x? I'm happy to open a PR, just want to double check if there is any reason it doesn't exist.

**Comment by akarnokd** [comment]
Delaying subscription to a `Completable` "b" by a `Completable` "a" is `a.andThen(b)`. The other types can be transformed into Completable to participate in this pattern.

If you want, go ahead with a PR.

**Comment by tonycosentini** [comment]
Makes sense - the same thing can be achieved with that and it's one less API to maintain.

I'm going to close this - using `andThen` solves my needs and is much simpler IMO.

Thank you!

**Comment by soshial** [comment]
@akarnokd , but why do we need to write this
`Completable.timer(1, TimeUnit.SECONDS).andThen(deleteDb()).subscribe();`
instead of just doing this:
`deleteDb().delaySubscription(1, TimeUnit.SECONDS).subscribe();`?

Also, we do not always have access to the beginning of Completable, we might want to alter its subscription time afterwards, isn't it?

**Comment by akarnokd** [comment]
@soshial I offered the option to write a PR for a specific timed `delaySubscription` but the OP chose the readily available workaround.

> Also, we do not always have access to the beginning of Completable, we might want to alter its subscription time afterwards, isn't it?

This makes no sense. You need the `Completable` to be able to delay a subscription to it. Also you can do this:

```java
deleteDb.compose(c -> timer(1, SECONDS).andThen(c));
```

Either way, the `Completable` instance has to exist.
