### ISSUE TITLE
Link error for Wiki

### ISSUE THREAD

**Issue by soulkeykim** [ReactiveX/RxJava#5082]
Hi, I just want to report link error.

Location
https://github.com/ReactiveX/RxJava/wiki
-> Javadoc 
-> 2.x

Actual
http://reactivex.io/RxJava/2.x/javadoc/io.reactivex/Flowable.html

Expect
http://reactivex.io/RxJava/2.x/javadoc/io/reactivex/Flowable.html

Cheers

**Comment by akarnokd** [comment]
Thanks! Fixed.
