### ISSUE TITLE
Immediate scheduler in 2.x

### ISSUE THREAD

**Issue by AlexBonel** [ReactiveX/RxJava#5084]
> The immediate scheduler is not present in 2.x. It was frequently misused and didn't implement the Scheduler specification correctly anyway; it contained blocking sleep for delayed action and didn't support recursive scheduling at all. Use Schedulers.trampoline() instead.

This prescription about using `Schedulers.immediate()` semantics is stated in [wiki](https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0#schedulers).

But at the same time there's publicly available [`ImmedateThinScheduler`](https://github.com/ReactiveX/RxJava/blob/2.x/src/main/java/io/reactivex/internal/schedulers/ImmediateThinScheduler.java) in the project. 

So I would like to know if the wiki is outdated in this context and it's ok to use `ImmediateThinScheduler` to achieve the same behavior/semantic as with 1.x version or there are some concerns about using of this scheduler and so it's not worth to be mentioned in wiki?

**Comment by JakeWharton** [comment]
The visibility of that class may be public but it's an 'internal' API and
therefore not suitable for use in client applications.

**Comment by AlexBonel** [comment]
I got it. Thanks!
