### ISSUE TITLE
2.0.4 FlowableScanSeed introduces delay

### ISSUE THREAD

**Issue by lambdas** [ReactiveX/RxJava#5089]
Hi guys! 

I'm using `Flowable.scan(seed)` to accumulate values of infinite sequence(stream of updates from server that comes not so often). The problem is that whenever FlowableScanSeed receives new value it publishes previous one. I guess it's not a problem with a finite sequence(at completion all values will be published anyway), but with infinite seq the last value is held until next comes.

I wrote test case to demonstrate the issue
```
    @Test
    public void testScanWithSeedEmitsAllItemsOnInfiniteSequence() {
        Flowable.concat(Flowable.just(1, 2, 3), Flowable.<Integer>never()).scan(0, SUM)
                .test(4)
                .assertValues(0, 1, 3, 6);
    }
```

Here seed+3 values are expected, but since sequence is infinite last value never comes.

I don't have much experience with rx so can't provide you with a patch, sorry ;)

**Comment by akarnokd** [comment]
Scan was changed to have less overhead than before at the cost of delaying the upstream values by one step. This works if the source keeps emitting frequently enough but as you demonstrated, if there is nothing to push more the operator just stops.

I'll create a PR that doesn't delay items shortly.

**Comment by akarnokd** [comment]
Closing via #5090.
