### ISSUE TITLE
replay() for Maybe?

### ISSUE THREAD

**Issue by neozax** [ReactiveX/RxJava#5095]
How come there's no `replay()` method for `Maybe`? I'd like to replay the emission of `Maybe` without having to re-execute the expensive operations.

Version: 2.0.1

**Comment by akarnokd** [comment]
Have you looked at `cache()`?

**Comment by neozax** [comment]
`cache()` works. Thanks. I wonder why's the decision not putting `replay()` in `Maybe`?

**Comment by akarnokd** [comment]
There is no notion for connectable-maybe and `cache()` fulfills most of the user demand along with `MaybeSubject`.
