### ISSUE TITLE
2.x : window(timespan, unit, count) always emit empty observable if not reach max count

### ISSUE THREAD

**Issue by xiemeilong** [ReactiveX/RxJava#5104]
This code will print nothing all the time.

```java
PublishSubject<String> vehicleToFetch = PublishSubject.create();
        vehicleToFetch
                .delay(2,TimeUnit.SECONDS)
                .window(10, TimeUnit.SECONDS, 5)
                .observeOn(Schedulers.io())
                .subscribe(w-> w.toList().subscribe(ws-> {
                    ws.forEach(v -> {
                        System.out.println(String.format("%s %d", v, Thread.currentThread().getId()));
                        vehicleToFetch.onNext(v);
                    });
                }));


        Observable.just("v1","v2","v3","v4")
                .subscribe(v->{
                    vehicleToFetch.onNext(v);
                });

```

I am using rxjava:2.0.6.

**Comment by akarnokd** [comment]
There are two problems with your code:

- You are using `toList` which requires a finite stream. Since you don't call `onComplete` on `vehicleToFetch` the sequence above won't print anything.
- You are probably not waiting long enough to see the results. The default RxJava schedulers are daemon threads and when the "main" thread ends, the whole application stops.

```java
PublishSubject<String> vehicleToFetch = PublishSubject.create();
vehicleToFetch
        .delay(2,TimeUnit.SECONDS)
        .window(10, TimeUnit.SECONDS, 5)
        .observeOn(Schedulers.io())
        .subscribe(w-> w.toList().subscribe(ws-> {
            ws.forEach(v -> {
                System.out.println(String.format("%s %d", v, Thread.currentThread().getId()));
                vehicleToFetch.onNext(v);
            });
        }));


Observable.just("v1","v2","v3","v4").subscribe(vehicleToFetch);

Thread.sleep(3000);
```

**Comment by xiemeilong** [comment]
@akarnokd Thanks.  I am calling `toList()` on a window observable ,not on `vehicleToFetch`, There is print if I change ` .window(10, TimeUnit.SECONDS, 5)` to `.window(10, TimeUnit.SECONDS, 4)`.

I am using a `CountDownLatch`(not show in code) to wait a long time.

**Comment by akarnokd** [comment]
Yes, because the window with limit 4 will call `onComplete` for you on the window that `toList()` consumes. With 5 there is noone to call `onComplete`. If you had a "v5" in that case, you'd see the printout again.

**Comment by xiemeilong** [comment]
Why did it not call `onComplete` when the timeout is reached?  Does not this method mean either timeout or max count is reach will emit a window?

**Comment by akarnokd** [comment]
Oh, I see it now. There is a bug in the operator that doesn't complete the old window if a new one is due to the timeout. I'll post a fix for it.

**Comment by akarnokd** [comment]
Closing via #5106.

**Comment by xiemeilong** [comment]
It  worked after upgrade to 2.0.7,  but after three times timeout, there is no timeout anymore.

**Comment by akarnokd** [comment]
Do you have a new unit test for it?

**Comment by xiemeilong** [comment]
You can use the same code , it will block after three new window emitted.

**Comment by akarnokd** [comment]
Odd. I'll look into it again.

**Comment by akarnokd** [comment]
Found a couple of remaining issues. See PR #5213; the example works with it properly for me.
