### ISSUE TITLE
2.x Flowable.generate stops due to inactivity?

### ISSUE THREAD

**Issue by doomchild** [ReactiveX/RxJava#5109]
I'm using `Flowable.generate` (`io.reactivex.rxjava2:rxjava:2.0.5`) to wrap calls to `AmazonSQSClient`, and it seems like if there are no messages for a period of time, the `Flowable` stops responding.

In effect, I have this:

```java
public class SqsObserver {
  public Flowable<SimpleMessage> getFlowable() {
    Flowable.generate(this::dequeAndTransmit);
  }

  private void dequeAndTransmit(final Emitter<? super SimpleMessage> emitter) {
    readSimpleMessageList().forEach(emitter::onNext);
  }

  private List<SimpleMessage> readSimpleMessageList() {
    // do the SQS calls and hand back a list of 0 - 10 items
  }
}
```

Is there something I'm missing about making the `Flowable` effectively infinite?  There might not be anything in the queue, and right now, it seems like the `Flowable` has some kind of stopping condition built-in.

**Comment by akarnokd** [comment]
For each invocation of the `dequeuAndTransmit`, you are supposed to emit 1 onNext. You likely try to emit multiple ones and the `Flowable` signals error you don't seem to handle. I assume `readSimpleMessageList()` returns a list, so emit that in entirety and have `flatMapIterable` unroll it:

```java
public Flowable<SimpleMessage> getFlowable() {
    Flowable.generate(this::dequeAndTransmit).flatMapIterable(v -> v);
  }

  private void dequeAndTransmit(final Emitter<? super List<SimpleMessage>> emitter) {
    emitter.onNext(readSimpleMessageList());
  }

  private List<SimpleMessage> readSimpleMessageList() {
    // do the SQS calls and hand back a list of 0 - 10 items
  }
```

**Comment by doomchild** [comment]
Yeah, that seems to have fixed it.  Thanks!

**Comment by akarnokd** [comment]
Great!
