### ISSUE TITLE
2.x: Disposal of ObservableCombineLatest's observers?

### ISSUE THREAD

**Issue by jbarr21** [ReactiveX/RxJava#5111]
When a ObservableCombineLatest is disposed, is there any particular reason why it does not dispose all of it's observers? i'm seeing `getAndIncrement()` be non-zero and that observer is not receiving any more events, so a memory leak is caused

https://github.com/ReactiveX/RxJava/blob/2.x/src/main/java/io/reactivex/internal/operators/observable/ObservableCombineLatest.java#L128

**Comment by akarnokd** [comment]
If there is no ongoing onNext, that should dispose the sources. Does your downstream block for any reason on onNext?

**Comment by akarnokd** [comment]
`Flowable` is implemented with an eager cancellation so I consider this to be a bug. I'll post a fix shortly.

**Comment by akarnokd** [comment]
Closing via #5114.

**Comment by jbarr21** [comment]
@akarnokd, thanks for the quick turnaround! would this also apply to [ObservableZip](https://github.com/ReactiveX/RxJava/blob/2.x/src/main/java/io/reactivex/internal/operators/observable/ObservableZip.java#L118), as well? here is [FlowableZip](https://github.com/ReactiveX/RxJava/blob/2.x/src/main/java/io/reactivex/internal/operators/flowable/FlowableZip.java#L146)'s cancel()

**Comment by akarnokd** [comment]
Indeed. Would you like to submit a PR?

**Comment by jbarr21** [comment]
will do
