### ISSUE TITLE
Add termination predicate for reduction operation

### ISSUE THREAD

**Issue by dalewking** [ReactiveX/RxJava#5116]
Have come across a case where I really want to do a reduce operation on an Observable, but need to possibly end the reduction before the observable has emitted all items depending on the current reduction value.

So I was contemplating that it would be nice to have methods like this on Observable that are a cross between reduce and takeWhile/takeUntil

```
<R> Maybe<R> reduceWhile(R seed, BiFunction<R,? super T,R> reducer, Predicate<? super R> predicate);
<R> Single<R> reduceUntil(R seed, BiFunction<R,? super T,R> reducer, Predicate<? super R> predicate);

```
These keep applying the reduction until the predicate evaluates to true. The difference is whether the result is the item that caused the predicate to evaluate to true (reduceUntil) or the last item before the predicate evaluated to false(reduceWhile).

ReduceWhile is a Maybe for the case where the predicate is false for the seed value.

If there is a better way to handle a case like this I am open to suggestions.

**Comment by dalewking** [comment]
For comparison here is what I am doing instead. The input is actually an Iterable:

        return Single.fromCallable(() ->
        {
            Result result= new EmptyResult();

            for(Item item: items)
            {
                Result nextResult = result.addItem(item);

                if(nextResult == null)
                {
                    break;
                }

                result = nextResult ;
            }

            return step;
        });

Where if this feature existed I would be replace that with:

     return Observable.fromIterable(items)
        .reduceWhile(new EmptyResult(), Result::addItem, r -> r != null)
        .toSingle();

**Comment by akarnokd** [comment]
You can compose this from existing operators, for example:

```java
Observable.range(1, 10)
.scanWith(() -> new ArrayList<Integer>(), (a, b) -> { a.add(b); return a; })
.takeUntil(a -> a.size() == 5)
.takeLast(1) // or lastElement()
.subscribe(System.out::println);
```

Otherwise, for a native implementation they are uncommon and are better hosted in [RxJava 2 Extensions](https://github.com/akarnokd/RxJava2Extensions#custom-operators-and-transformers) instead if not in your own codebase as `ObservableTransformer`s.

**Comment by dalewking** [comment]
Agreed
