### ISSUE TITLE
Why is there no share or publish/refcount for single?

### ISSUE THREAD

**Issue by bangarharshit** [ReactiveX/RxJava#5118]
RX Java version 2.0.4 - Single doesn't have share/publish/refcount and therefore we can't have hot observables. Is there any reason for the same.

**Comment by akarnokd** [comment]
It has a `cache` operator and a `SingleSubject` to help with many cases when the single item should be cached. You can always convert back to `Observable` and have access to the `publish` and `refCount` operators.

**Comment by bangarharshit** [comment]
Got it. Resolving.

**Comment by afaucogney** [comment]
I come back to the issue. Could we have more context about the "why" there is no "share" operator for single ? Even if we can maybe solve some requirement in another way. Is it by design decision ?

**Comment by akarnokd** [comment]
We limit the API surface of the library and the need for share in other types is rare.
