### ISSUE TITLE
[1.2.6] throttleFirst doesn't emit item if user changed system time as past

### ISSUE THREAD

**Issue by juhwan-jeong** [ReactiveX/RxJava#5120]
I used throttleFirst operator for prevening duplicated click event like below
```
RxView.clicks(v).throttleFirst(500, TimeUnit.MILLISECONDS, AndroidSchedulers.mainThread())
```

It works well in general case. But if user changed system time as past after click view, thrrottleFist doesn't emit item. (In the android, user can change system time using settings application.)
Because, OperatorThrottleFirst's below routine. 
```
    @Override
    public Subscriber<? super T> call(final Subscriber<? super T> subscriber) {
        return new Subscriber<T>(subscriber) {

            private long lastOnNext = -1;
            // ...
            @Override
            public void onNext(T v) {
                long now = scheduler.now();
                if (lastOnNext == -1 || now - lastOnNext >= timeInMilliseconds) {
                    lastOnNext = now;
                    subscriber.onNext(v);
                }
            }
```
I think (now - lastOnNext) become negative value, item should be emitted too.

**Comment by akarnokd** [comment]
I should have mentioned to clear the text field once you read the issue welcome list.

You forgot to post about your issue.

**Comment by juhwan-jeong** [comment]
I used throttleFirst operator for prevening duplicated click event like below
```
RxView.clicks(v).throttleFirst(500, TimeUnit.MILLISECONDS, AndroidSchedulers.mainThread())
```

It works well in general case. But if user changed system time as past after click view, thrrottleFist doesn't emit item. (In the android, user can change system time using settings application.)
Because, OperatorThrottleFirst's below routine. 
```
    @Override
    public Subscriber<? super T> call(final Subscriber<? super T> subscriber) {
        return new Subscriber<T>(subscriber) {

            private long lastOnNext = -1;
            // ...
            @Override
            public void onNext(T v) {
                long now = scheduler.now();
                if (lastOnNext == -1 || now - lastOnNext >= timeInMilliseconds) {
                    lastOnNext = now;
                    subscriber.onNext(v);
                }
            }
```
I think (now - lastOnNext) become negative value, it's similar with lastOnNext is -1.

**Comment by akarnokd** [comment]
Would you like to post a fix?

**Comment by juhwan-jeong** [comment]
Thank you for your feedback.

**Comment by akarnokd** [comment]
I've restructured the issue and moved your comment into the top field. If you have the means, you are welcome to verify #5123.

**Comment by akarnokd** [comment]
Closing via #5123 & release 1.2.7
