### ISSUE TITLE
1.x: unsubscribeOn for Single?

### ISSUE THREAD

**Issue by yshrsmz** [ReactiveX/RxJava#5138]
RxJava version: v1.2.7

Although Single may be unsubscribed on a different thread than subscribed one, there seems to be no `unsubscribedOn` operator for Single.

It would be nice if there is a `Single#unsubscribeOn`.
I currently convert to Observable and use subscribeOn/unsubscribeOn methods for Observable, and then convert back to Single.

**Comment by akarnokd** [comment]
PR welcome.

**Comment by akarnokd** [comment]
Closing via #5146.
