### ISSUE TITLE
Documentation bug in 2nd form of scan()

### ISSUE THREAD

**Issue by RobLewis** [ReactiveX/RxJava#5143]
In trying to fully understand the 2nd form of the RxJava `scan()` operator, I see that there is at least one error in its documentation [here](http://reactivex.io/RxJava/javadoc/rx/Observable.html#scan(R,%20rx.functions.Func2)). 

I'm referring to 
`public final <R> Observable<R> scan(R initialValue, Func2<R,? super T,R> accumulator)`

In the "Type Parameters" section, it says only this: "R - the initial, accumulator and result type". There is no mention of type T. This appears to be applicable to the _first_ form of `scan()`, but not this form (although the first-form documentation refers to the type as T, not R). 

I'm personally having trouble understanding this operator, and it occurs to me that faulty documentation could be part of the problem. Please check this over carefully.

**Comment by akarnokd** [comment]
Hi. Since the `scan` operator is an instance operator, it inherits the type variable `T` from `Observable` and thus it is not repeated in the documentation (that might be even a javadoc compilation warning to have that).

> I'm personally having trouble understanding this operator

If you'd clarify what you don't understand, we may help you.

`scan` is a rolling accumulator of values which also emits the intermediate values:

```java
Observable.range(1, 5)
.scan(0, (a, b) -> a + b)
.subscribe(System.out::println);
```

prints (comments added for clarity)

```
0  // = 0
1  // = 0 + 1
3  // = 1 + 2
6  // = 3 + 3
10 // = 6 + 4
15 // = 10 + 5
```

**Comment by RobLewis** [comment]
Thank you. I think I understand the first form of `scan()`, but I'm getting nowhere trying to understand the second form, as detailed [here](http://stackoverflow.com/questions/42449615/how-to-assemble-packets-from-an-observable-into-a-new-observable). I'd be most grateful for any help!

**Comment by akarnokd** [comment]
From [my StackOverflow comment](http://stackoverflow.com/questions/42449615/how-to-assemble-packets-from-an-observable-into-a-new-observable#comment72132133_42449615):

*This problem resembles the splitting of a virtual concatenation and splitting of strings through a regexp in RxJavaString library. You need a [custom operator](https://github.com/ReactiveX/RxJavaString/blob/1.x/src/main/java/rx/internal/operators/ObservableSplit.java) to control the excess and leftovers; you can replace string with `byte[]` and work out the concatenation and split logic.*
