### ISSUE TITLE
Promote DisposableLambdaObserver for public use?

### ISSUE THREAD

**Issue by jeremy303** [ReactiveX/RxJava#5144]
I noticed that `io.reactivex.internal.observers` includes `DisposableLambdaObserver`.  Might this class be promoted from the `internal` package for public use, thus allowing our `DisposableObserver`s to be defined with lambdas without resorting to writing our own lambda-friendly implementation?

**Comment by akarnokd** [comment]
`DisposableLambdaObserver` supports the lambda version of `Observable.subscribe()`. Why do you need that publicly?

**Comment by jeremy303** [comment]
@akarnokd You are totally right, it's not needed-- I was confused.  I was interpreting the documentation and tutorials I read as indicating that a `DisposableObserver` needed to be provided to  `subscribeWith` when I needed dispose capability, but I now see that is only when providing an `Observer` for the subscribe, not when using the `subscribe` methods that accept lambdas, which return a `Disposable`.
