### ISSUE TITLE
Is the "Rxjava" always can be written  general java application, for exapmle: java web,java console application

### ISSUE THREAD

**Issue by ghost** [ReactiveX/RxJava#5149]
##   And  thank you for writing  this great project

**Comment by akarnokd** [comment]
Thanks for the praising! The title indicates you have a question, right?

**Comment by ghost** [comment]
yes, and, I want kown, Rxjava  support the  java  forever, not the only one android .(maybe my poor english don't expressing my intention enough。。。 )

**Comment by akarnokd** [comment]
RxJava supports Java 6+, that includes Android and most desktop/server setups today.

**Comment by akarnokd** [comment]
Looks like this question has been answered. If you have further input on the issue, don't hesitate to reopen this issue or post a new one.
