### ISSUE TITLE
2.x: eliminate all anyonymous inner classes

### ISSUE THREAD

**Issue by akarnokd** [ReactiveX/RxJava#5150]
Currently, mostly the base reactive classes have been cleared of anonymous inner classes. Still, many stacktraces contain `SomeClass$1$2` that makes it difficult to figure out what that exact component was without having an IDE open.

I don't know if IDEs allow searching for anonymous inner classes and/or highlight them like warnings, thus the a reasonable way would be to scan the build directory for files containing the `$` pattern.

In addition, if there is an agreement, a new style-validation unit test could be added that does the same scanning at unit test time (ignoring `SomeClassTest`s) and warning/failing the build if any of such files was found.

PR welcome.

**Comment by MyDogTom** [comment]
IntelliJ has "search structurally" function with predefined search for anonymous classes (`search structurally` -> `copy existing template` -> `anonymous classes`)
Also it's possible to create inspection from search. See `Preferences` -> `Editor` -> `Inspections` -> `General` -> `Structural Search Inspection`

**Comment by akarnokd** [comment]
Thanks. It shows about 115 places under `src/main/java`.

**Comment by SleimanJneidi** [comment]
Hey guys, the issue is tagged with "PR welcome", so `i started working on it and removed all of them. Getting test errors due to naming violations. Early feedback is appreciated. https://github.com/SleimanJneidi/RxJava/tree/remove-anonymous-inner-classes

**Comment by akarnokd** [comment]
Hi and thanks for tackling this. See #5159 where I can comment on specific issues.

**Comment by akarnokd** [comment]
Looks like there are a bunch of copy-paste errors and the test hangs due to some unexpected code changes. I suggest you start over piece by piece and verifying after each java file the tests still pass.

**Comment by akarnokd** [comment]
Done.
