### ISSUE TITLE
Nullability Annotations

### ISSUE THREAD

**Issue by ScottPierce** [ReactiveX/RxJava#5151]
It would be helpful if RxJava had nullability annotations that might provide warnings to developers in a good IDE. This would be a helpful addition, especially considering RxJava no longer allows streaming of `null` types.

It would also provide helpful indicators for other JVM languages that have Nullability built in. [Kotlin is a good example of this](https://kotlinlang.org/docs/reference/java-interop.html#nullability-annotations). Currently using RxJava with Kotlin results in most code being interpreted as potentially nullable. Annotating types in the RxJava API would fix this in a way that a side library, like RxKotlin, couldn't.

**Comment by akarnokd** [comment]
There were several enhancements in this regard in the recent past: #5055, #5051, #5023 for example.

**Comment by ScottPierce** [comment]
I see. Now that you mention it I see them in certain places, but missing from others. It'd be helpful to have them on the `Observer` interfaces for instance. The `OnSubscribe`s too, such as `ObservableOnSubscribe`.

I'm sure there are a few others that are missing them as well, considering how often I see this.

**Comment by akarnokd** [comment]
PR welcome.

**Comment by ScottPierce** [comment]
Sounds reasonable. 

I had loaded the RxJava gradle project the other day, and came across several gradle errors. I ended up having to comment out a lot of the `build.gradle` regarding nebula, and animal sniffer to make gradle happy. Any idea why that might have been?

**Comment by akarnokd** [comment]
Use the gradle in the project: 2.14 . The 3.x don't work properly due to the outdated nebula plugin. In theory, the nebula is just an aggregator of other plugins which appear to be 3.x ready. We could use the help with them too.

**Comment by ScottPierce** [comment]
Oh right. Because I loaded the project with Android Studio, it forced the gradle wrapper to upgrade to 3.3. I'll just use IntelliJ next time. Thanks!

**Comment by akarnokd** [comment]
Continuing with #5341.
