### ISSUE TITLE
1.x: rename Single.fromEmitter() to Single.create()

### ISSUE THREAD

**Issue by lukaciko** [ReactiveX/RxJava#5158]
Following `Observable.create(OnSubscribe)` being deprecated and `Observable.fromEmitter()` being aliased to `Observable.create()` in 1.2.7 I think `Single` should follow suit. This would include:

* Add `Single.create(Action1<SingleEmitter<T>>)` with same implementation and documentation as `Single.fromEmitter()`
* Mark `Single.fromEmitter()` as deprecated and scheduled to be removed

**Comment by akarnokd** [comment]
Unlike `Observable`, `Single.create(s -> { })` would become ambiguous because there is no extra parameter to let javac distinguish.

**Comment by lukaciko** [comment]
Oh right, that's unfortunate. Perhaps this is another reason to migrate to 2.x.
