### ISSUE TITLE
2.x: Disposable returned from Single.subscribe() is not disposed after terminal event

### ISSUE THREAD

**Issue by kxfeng** [ReactiveX/RxJava#5160]
When using Single.subscribe(onSuccess, onError) , the returned Disposable is not disposed after terminal event. However , for Observable, Flowable, Maybe and Completable , the results are all disposed.

Here is the test code: 
```java
@Test
public void testDisposable() throws Exception {

	Disposable disposable;

	disposable = Single.just(1).subscribe(
		next -> System.out.println("Single Success"),
		error -> System.out.println("Single Error")
	);

	System.out.println("Single Disposed: " + disposable.isDisposed());

	disposable = Observable.just(1).subscribe(
		next -> System.out.println("Observable Next"),
		error -> System.out.println("Observable Error"),
		() -> System.out.println("Observable Complete")
	);

	System.out.println("Observable Disposed: " + disposable.isDisposed());
}
```

Output:
```
Single Success
Single Disposed: false

Observable Next
Observable Complete
Observable Disposed: true
```

I found the Disposeable not lazySet to DISPOSED in  ConsumerSingleObserver compared with LambdaObserver. Is this a bug or there are some special reasons to do this?

```java
ConsumerSingleObserver

@Override
public void onSuccess(T value) {
	try {
		onSuccess.accept(value);
	} catch (Throwable ex) {
		Exceptions.throwIfFatal(ex);
		RxJavaPlugins.onError(ex);
	}
}
```

```java
LambdaObserver

@Override
public void onComplete() {
	if (!isDisposed()) {
		lazySet(DisposableHelper.DISPOSED);
		try {
			onComplete.run();
		} catch (Throwable e) {
			Exceptions.throwIfFatal(e);
			RxJavaPlugins.onError(e);
		}
	}
}
```

RxJava 2.0.6

**Comment by akarnokd** [comment]
Thanks for reporting. It looks like a simple oversight since the tests pass when I add the `lazySet`s. See #5163.

**Comment by akarnokd** [comment]
Closing via #5163.

**Comment by apexkid** [comment]
Hello,

I am unable to understand the conclusion here. Is disposable supposed to be auto-disposed for Single? I wrote some code and i see it is not disposed. Is it the right behavior?

**Comment by akarnokd** [comment]
This issue has been closed and the fix has been available for a year now. What test did you write against which version?

**Comment by apexkid** [comment]
Sorry I have been testing it wrong. My bad!. Thanks for quick response though. :)
