### ISSUE TITLE
2.x: Transformers from Observable to Single

### ISSUE THREAD

**Issue by Oyashirox** [ReactiveX/RxJava#5164]
I'm refactoring some code, and I would like to have a reusable way to show the progress of a download and a button to cancel it. The client side is only interested to know if the download was completed (so it can chain other things after) or not. Here's my code right now : 
```java
public Single<Boolean> showCancellableDownload(Observable<Progress> download) {
        Completable cancel = mView.showLoading();

        return download
                .subscribeOn(Schedulers.io())
                .observeOn(AndroidSchedulers.mainThread())
                .doOnNext(progress -> {
                    mView.showLoadingProgress(progress.percent());
                })
                .ignoreElements()
                .toSingleDefault(true)
                .takeUntil(cancel)
                .onErrorResumeNext(throwable -> {
                    if (throwable instanceof CancellationException) {
                        Timber.w("showCancellableDownload: CancellationException");
                        return Single.just(false);
                    } else
                        return Single.error(throwable);
                })
                .doOnSuccess(aBoolean -> mView.hideLoading())
                .doOnError(throwable -> mView.hideLoading());
    }
```
As said Dan Lew [in this article](http://blog.danlew.net/2015/03/02/dont-break-the-chain/), I'd better use a Transformer, but existing classes only allows to transform to the same type (Observable<T> -> Observable<R>, Single<T> -> Single<R>). 

What's the cleanest way to achieve this ?

**Comment by akarnokd** [comment]
There is the generic `to(Function<Single<T>, R>)` that allows converting to any type with a function.

**Comment by Oyashirox** [comment]
Perfect !
