### ISSUE TITLE
1.x Execute action after flattened observable completes

### ISSUE THREAD

**Issue by kennedyoliveira** [ReactiveX/RxJava#5166]
Hello,

i'm with a doubt that i don't know how to write a flow that use a connection from database, but closes it a soon as the query ends, and before the downstream consume it's events.

I'm using vert.x rxfied jdbc client, example code:

```
jdbcClient.getConnectionObservable()
                  .flatMap(conn -> conn.queryWithParamsObservable("SQL QUERY ...", new JsonArray())
                                       .doOnTerminate(conn::close))
                  .map(ResultSet::getRows)
                  .groupBy( // ... )
```

How can i make the `conn::close` be classed **BEFORE** `map`, `groupby` and the rest of chian operators execute?

Currently, it will run the `doOnTerminate` only when the `subscriber` `unsubscribes`, since i'm returning it to other code, someone could do expensive things with the results, and i don't want the connection to be held due to that.

Other thing, ideally i will be using `Observable.using` to create generic repository methods, because `getConnectionObservable` isn't lazy, it fetches a connection on calling, but it's not a `hot` observable since it don't pushes the values until subscribed, so, a sampel code would look like this:

```
Observable.defer(jdbcClient::getConnectionObservable)
                  .flatMap(conn -> Observable.using(() -> {
                                                      log.debug("Fetching database connection");
                                                      return conn;
                                                  },
                                                  // handle the connection here,
                                                  connToClose -> {
                                                      log.debug("Returning connection to pool");
                                                      connToClose.close();
                                                  }));
```

I need to close the connection after it's used, before the chain ends.

**Comment by akarnokd** [comment]
Hi. You were almost there: you have to apply Observable.using() on the outside:

```java
Observable.using(
    jdbcClient::getConnectionObservable,
    conn -> conn.queryWithParamsObservable(...)
               .map(ResultSet::getRows)
               .groupBy( ... )
    conn -> conn.close(),
    false
)

// or
Observable.using(
    jdbcClient::getConnectionObservable,
    conn -> conn.queryWithParamsObservable(...)
    conn -> conn.close(),
    false
)
.map(ResultSet::getRows)
.groupBy( ... )

```

**Comment by kennedyoliveira** [comment]
Hey @akarnokd, thank you for the fast answer!

I forgot to mention i'm using 1.x version, and `jdbcClient.getConnectionObservable` returns a `Observable<SQLConnection>` and not a connection, so  i would not be able to close it on last function, or i'm missing something?

By the way, i don't understand how the last parameter `disposeEagerly`, would you mind explaining it or pointing a resource to read more, besides the documentation?

Thank you

**Comment by akarnokd** [comment]
In that case your `defer` approach should work.

> would you mind explaining it

If true, the dispose action is called before the onComplete is sent downstream. If false, the dispose action is called after. Sometimes you have to delay the dispose action with it because computation may still depend on the resource.

**Comment by kennedyoliveira** [comment]
@akarnokd thanks for explaining about the `disposeEagerly`, know i understand.

Back to the main question, the `defer` approach doesn't work, i created a simple example:

```
// defer because jdbcClient.getConnectionObservable() fetches a connection
final Observable<SQLConnection> lazyConnection = Observable.defer(() -> {
  log("Fetching connection");
  return jdbcClient.getConnectionObservable();
});

return lazyConnection
  .flatMap(resource ->
             Observable.using(
               () -> {
                 log("Creating resource");
                 return resource;
               },
               conn -> {
                 log("Doing select on the connection");
                 return conn.queryObservable("SELECT * FROM INFORMATION_SCHEMA.HELP ");
               },
               conn -> {
                 conn.close();
                 log("Closing the connection");
               }, false))
  .map(resultSet -> {
    log("Mapping, connection should be close");
    // this doesn't need database connection, because it's eagerly fetched by the jdbc client
    return resultSet.getRows();
  })
  .map(rows -> {
    log("Mapping again, the connection should be closed");

    // sleep to simulate some delay
    try { Thread.sleep(1_000); } catch (InterruptedException e) { }

    // random
    return rows.get(1);
  });
```

The output is the following:

```
2017-03-08T20:35:33.515 [vert.x-eventloop-thread-0] Fetching connection
2017-03-08T20:35:33.515 [vert.x-eventloop-thread-0] Creating resource
2017-03-08T20:35:33.516 [vert.x-eventloop-thread-0] Doing select on the connection
2017-03-08T20:35:33.518 [vert.x-eventloop-thread-0] Mapping, connection should be close
2017-03-08T20:35:33.519 [vert.x-eventloop-thread-0] Mapping again, the connection should be closed
2017-03-08T20:35:34.525 [vert.x-eventloop-thread-0] Closing the connection
```

I can upload the project on Github if you want to review.

Thank you.

**Comment by akarnokd** [comment]
So you need the connection closed before the downstream starts processing the single result set, right? In that case apply `.singleOrError()` before your first map and have the `using` eagerly dispose.

**Comment by kennedyoliveira** [comment]
Yes, that's exactly it, using single worked, now the connection is release before downstream starts to process.

I was trying to understand the `OperatorSingle`, but i got a little confused with the parent child relationship on subscribing, could you explain it a little?

```
    @Override
    public Subscriber<? super T> call(final Subscriber<? super T> child) {

        final ParentSubscriber<T> parent = new ParentSubscriber<T>(child, hasDefaultValue,
                defaultValue);
        child.add(parent);
        return parent;
    }
```

Thank you!

**Comment by kennedyoliveira** [comment]
Another thing, i noticed there are 2 single operators, `toSingle` and `single`, one use `Single.create` and other use `lift`, what are the differences between them?

**Comment by akarnokd** [comment]
I'm sorry, I currently don't have time to educate you personally.

**Comment by kennedyoliveira** [comment]
I see, sorry for taking you time, i appreciate your help.
