### ISSUE TITLE
2.x: TestObserver's "isDisposed"

### ISSUE THREAD

**Issue by ZacSweers** [ReactiveX/RxJava#5178]
I have a DisposableObserver that has its own disposability implementation. It will correctly return the state when you hit `isDisposed`, but it is backed by a different enum (basically a fork of `DisposableHelper`, since it's internal-only). This is the delegate that `TestObserver` ends up wrapping in my test. Thing is, when you hit `TestObserver#isDisposed()`, it explicitly only does a reference comparison check between the disposable and the enum instance in `DisposableHelper`.

Is this intentional? If so, should `isDisposed` not be used with `TestObserver` in testing?

**Comment by ZacSweers** [comment]
Another note on this - this also seems to break `isSubscribed` checks. The delegate observer is disposed now, but the wrapping `TestObserver` is still subscribed

**Comment by akarnokd** [comment]
`TestObserver` is a special kind which has to allow `dispose()` to be called after it has received the terminal event. See #4872.

**Comment by ZacSweers** [comment]
Gotcha, thanks!
