### ISSUE TITLE
Backpressure Mode "Drop" is in fact "Buffer and Drop"? How to get "real" drop? (RxJava 1.2.7)

### ISSUE THREAD

**Issue by Petikoch** [ReactiveX/RxJava#5190]
I do a lot of GUI programming using RxJava and was really surprised about the behaviour of the DROP backpressure mode. 

**DROP seems to be "BUFFER 128 and then DROP".**

See the output of the following example:

```
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import rx.Observable;
import rx.schedulers.Schedulers;

import java.util.concurrent.TimeUnit;

public class DropBackpressureExample {

	public static void main(String[] args) throws InterruptedException {
		Logger logger = LoggerFactory.getLogger("Output");

		Observable.range(1, 10_000)
				.subscribeOn(Schedulers.computation())
				.doOnNext(value -> logger.info("produced " + value))
				.onBackpressureDrop()
				.observeOn(Schedulers.io())
				.doOnNext(value -> logger.info("got " + value))
				.map(value -> {
					try {
						TimeUnit.SECONDS.sleep(1);
					} catch (InterruptedException e) {
						throw new RuntimeException(e);
					}
					return value;
				})
				.subscribe(
						value -> logger.info("handled " + value),
						Throwable::printStackTrace,
						() -> logger.info("completed")
				);

		TimeUnit.MINUTES.sleep(3);
	}
}
```
Output 

```
16.03.2017 10:43:39 INFO  [RxComputationScheduler-1] Output: produced 1
16.03.2017 10:43:39 INFO  [RxComputationScheduler-1] Output: produced 2
16.03.2017 10:43:39 INFO  [RxComputationScheduler-1] Output: produced 3
16.03.2017 10:43:39 INFO  [RxIoScheduler-2] Output: got 1
16.03.2017 10:43:39 INFO  [RxComputationScheduler-1] Output: produced 4
16.03.2017 10:43:39 INFO  [RxComputationScheduler-1] Output: produced 5
16.03.2017 10:43:39 INFO  [RxComputationScheduler-1] Output: produced 6
16.03.2017 10:43:39 INFO  [RxComputationScheduler-1] Output: produced 7
...
16.03.2017 10:43:39 INFO  [RxComputationScheduler-1] Output: produced 9998
16.03.2017 10:43:39 INFO  [RxComputationScheduler-1] Output: produced 9999
16.03.2017 10:43:39 INFO  [RxComputationScheduler-1] Output: produced 10000
16.03.2017 10:43:40 INFO  [RxIoScheduler-2] Output: handled 1
16.03.2017 10:43:40 INFO  [RxIoScheduler-2] Output: got 2
16.03.2017 10:43:41 INFO  [RxIoScheduler-2] Output: handled 2
16.03.2017 10:43:41 INFO  [RxIoScheduler-2] Output: got 3
16.03.2017 10:43:42 INFO  [RxIoScheduler-2] Output: handled 3
16.03.2017 10:43:42 INFO  [RxIoScheduler-2] Output: got 4
16.03.2017 10:43:43 INFO  [RxIoScheduler-2] Output: handled 4
16.03.2017 10:43:43 INFO  [RxIoScheduler-2] Output: got 5
16.03.2017 10:43:44 INFO  [RxIoScheduler-2] Output: handled 5
...
16.03.2017 10:45:46 INFO  [RxIoScheduler-2] Output: got 127
16.03.2017 10:45:47 INFO  [RxIoScheduler-2] Output: handled 127
16.03.2017 10:45:47 INFO  [RxIoScheduler-2] Output: got 128
16.03.2017 10:45:48 INFO  [RxIoScheduler-2] Output: handled 128
16.03.2017 10:45:48 INFO  [RxIoScheduler-2] Output: completed
```

The downstream can't obviously keep up (sleep 1 sec... in the map operator). 

I expect in this example that the upstream produces 10'000 values and the downstream handles 1 value, 99'999 should be dropped. But there seems to be an internal buffer of 128 and actually 128 values are handled. 

This leads to the following for me surprising behaviour:
- a producer creates 10'000 values in less than a couple of ms
- the consumer is very very slow and can consume only one value per second
- the consumer accepts 128 values and processes them in 128 seconds

The following questions arise: 
- What about renaming DROP to BUFFER_128_AND_DROP? ;-)
- What's the best way to achieve "my expected" behaviour? "Real" drop? RxJava 2 and Flowable?

**Comment by akarnokd** [comment]
You are forgetting that `observeOn` has a default internal buffer of 128 elements. It will buffer that amount upfront but then `onBackpressureDrop()` will drop the rest. If you want to drop elements while one is asynchronously being processed, you have to use a different set of operators:

```java
Observable.range(1, 10_000)
.onBackpressureDrop()
.delay(0, TimeUnit.MILLISECONDS, Schedulers.io())
.rebatchRequests(1)
.doOnNext(value -> logger.info("got " + value))
.map(value -> {
    try {
        TimeUnit.SECONDS.sleep(1);
    } catch (InterruptedException e) {
        throw new RuntimeException(e);
    }
    return value;
})
.subscribe(
    value -> logger.info("handled " + value),
    Throwable::printStackTrace,
    () -> logger.info("completed")
);
```

**Comment by Petikoch** [comment]
Thanks a lot @akarnokd. Excellent!

**Comment by Whathecode** [comment]
This seems like a fairly common use case, and it is not clear to me at all why the code provided solves it:
```
.delay(0, TimeUnit.MILLISECONDS, Schedulers.io())
.rebatchRequests(1)
```

For example, in the case of a `concatMap` it still buffers 1 item.
```
Flowable.interval( 1000, TimeUnit.MILLISECONDS )
    .onBackpressureDrop()
    .delay(0, TimeUnit.MILLISECONDS, Schedulers.io())
    .rebatchRequests(1)
    .concatMap {
        // Make first item take longer to process than for the second item to arrive.
        if (it == 0L) {
            Flowable.just( it ).delay( 5000, TimeUnit.MILLISECONDS )
        }
        else {
            Flowable.just( it )
        }
    }
    .subscribe { println( it ) }
```

This does not return '0 6 7 ,..' but '0 1 6 7 ...'. And, in fact, removing `delay` and `rebatchRequests` does not change the output.

Could you clarify what exactly the combination of `delay` with `rebatchRequest` does? To me, it seems much better/cleaner/more readable to introduce a variable `isRunning` and return a `Flowable.empty()` in case it is `true`, and set it to `false` on e.g., `doOnNext`.

Alternatively, I would imagine an operator along the lines of `onBackpressureDrop( 0 )` where `0` indicates the amount of elements to buffer prior to start dropping items.

**Comment by akarnokd** [comment]
Backpressure is negotiated between subsequent operators, so if one buffers (like `concatMap`) or modulates requests in between, your ideal 1-request-1-response is no longer achieved.

> Could you clarify what exactly the combination of delay with rebatchRequest does?

Delay does not interfere with requests and rebatchRequest requests only if it has finished onNext-ing the item. This works for the original requirement as there is no other async boundary or request modulation going on.

The flow shape, i.e., a controlled feedback loop can't be generally achieved with arbitrary operators. You have to open up the loop and trigger the emission manually. For example, use a `PublishProcessor` as the event source for indicating the next item should be retrieved from a database:

```java
FlowableProcessor<Integer> fp = PublishProcessor.<Integer>create().toSerialized();

fp.observeOn(Schedulers.computation())
  .flatMap(id -> database.query(id).subscribeOn(Schedulers.io()))
  .subscribe(result -> fp.onNext(result.id + 1))
;

fp.onNext(0);
```
