### ISSUE TITLE
2.x Actions.empty(), EmptyAction

### ISSUE THREAD

**Issue by mtychyna** [ReactiveX/RxJava#5192]
I consider there are any alternative for [Actions.empty()](http://reactivex.io/RxJava/1.x/javadoc/rx/functions/Actions.html#empty()) in 2.x. What are you suggesting to use instead of?
`__ -> {}` ? Thx.

**Comment by akarnokd** [comment]
Yes.

**Comment by vanniktech** [comment]
Check out the [Functions](https://github.com/ReactiveX/RxJava/blob/7265d33caddf62c58acc4ffc5df366bc0c14312f/src/main/java/io/reactivex/internal/functions/Functions.java) class.

**Comment by akarnokd** [comment]
@vanniktech Note that's `internal`.

**Comment by vanniktech** [comment]
How come that those functions are internal? Up until today I thought that those aren't.

**Comment by TakuSemba** [comment]
I also want to know why it's internal.  is it supposed to not be named internal?

**Comment by akarnokd** [comment]
Their purpose is to support the public API and behavior without requiring them to conform to public expectations.
