### ISSUE TITLE
Consider adding Canonical URLs for Javadocs

### ISSUE THREAD

**Issue by vanniktech** [ReactiveX/RxJava#5194]
When searching for TestScheduler via Google you'll only find the documentation for RxJava 1.x. Most probably though you want to have the Documentation for RxJava 2. Although I'm not able to see a search for RxJava 2 at all when using google with `rxjava TestScheduler`. Searching with `site:reactivex.io rxjava TestScheduler` does the trick but also then RxJava 2 is at position 2.

Adding Canonical URLs for Javadocs would help telling Google to list the RxJava 2 version before RxJava 1.

For reference [here](https://publicobject.com/2017/02/14/canonical-urls-for-javadocs/) is a blog post about Canonical URLs.

**Comment by akarnokd** [comment]
Wouldn't that require the editing the generated javadoc whenever there is a version change for 1.x?

**Comment by vanniktech** [comment]
Yes. Maybe there's a way to automate this so the moment the docs are generated for 1.x. the `<link rel="canonical" href=""/>` are inserted at the right location. 

OkHttp also does no further developments of 1.x and 2.x AFAIK. So they don't need to automate it.

**Comment by akarnokd** [comment]
I'm not certain if we could do this before the EOL because even after the feature freeze of 1.x, the bugfixes may include javadoc changes.

**Comment by vanniktech** [comment]
I'll leave the decision up to you. I just thought it would be a nice way to push 2.x even further and make it more visible.

**Comment by akarnokd** [comment]
See #5212.

**Comment by akarnokd** [comment]
Closing viy #5212.
