### ISSUE TITLE
2.x distinctUntilChanged should not update its value reference unless it changes

### ISSUE THREAD

**Issue by ansman** [ReactiveX/RxJava#5200]
RxJava version: 2.0.7

The `ObservableDistinctUntilChanged` caches the last emitted value regardless if it changes or not, this can waste memory needlessly if the emits emitted are large. 

For example, consider this snippet:
```java
Observable.concatArray(loadHeavyResourceFromCache(), observeHeavyResourceFromNetwork())
    .distinctUntilChanged()
    .subscribe(this::showHeavyResource);
```

Assuming they resources are equal and that `showHeavyResource` stores a reference to the item both the cached value and the network value are kept in memory.
I feel like `ObservableDistinctUntilChanged` probably shouldn't change its internal value if it doesn't change between emissions.

**Comment by akarnokd** [comment]
The contract is that subsequent elements are compared and thus the last seen element is always stored to be ready for comparing with the upcoming element.

**Comment by ansman** [comment]
But why does it need to update the value if they are equal?

**Comment by akarnokd** [comment]
Equality is a funny thing when mutable objects are involved. See #4743 for example. You can use `onTerminateDetach` to get rid of any internal references after termination.

**Comment by ansman** [comment]
My stream is endless so there is no termination.
I assume mutable objects break all sorts of things, but with the PR you linked it should make no difference if you store the first or the last of the duplicate values?

**Comment by akarnokd** [comment]
Then you need a custom operator.

**Comment by akarnokd** [comment]
```java
public static <T> ObservableTransformer<T, T> distinctUntilChangedNoUpdate() {
    return o -> Observable.defer(() -> {
        AtomicReference<T> last = new AtomicReference<T>()
        return o.filter(v -> {
            if (last.get() == null || !last.get().equals(v)) {
               last.lazySet(v);
               return true;
            }
            return false;
        }); 
    });
}
```

**Comment by ansman** [comment]
I see, and there is no way that the built in operator will change?

Also, how come an `AtomicReference` is needed? Access should be serialised by upstream, right?

**Comment by akarnokd** [comment]
> I see, and there is no way that the built in operator will change?

Established operators' behavior won't change.

> Also, how come an AtomicReference is needed? Access should be serialised by upstream, right?

You can't create a `T[]` and `AtomicReference` already stores items on the heap and casts it properly. This is why `lazySet` is in there.

**Comment by ansman** [comment]
Ah, I see. Thanks.

Why would I need to create a `T[]`? I would only ever store a single object, right?

**Comment by radityagumay** [comment]
> > I see, and there is no way that the built in operator will change?
> 
> Established operators' behavior won't change.
> 
> > Also, how come an AtomicReference is needed? Access should be serialised by upstream, right?
> 
> You can't create a `T[]` and `AtomicReference` already stores items on the heap and casts it properly. This is why `lazySet` is in there.

thanks for this @akarnokd
