### ISSUE TITLE
Maybe is not calling onComplete after onSuccess

### ISSUE THREAD

**Issue by MarcinMoskala** [ReactiveX/RxJava#5204]
I started:
```
val singleEventDelayedFlowable = Maybe
        .just("test")
        .delay(100, TimeUnit.MILLISECONDS)
val latch = CountDownLatch(1)
var tokens = listOf<String>()
val subscription = maybe.subscribeBy(
        onSuccess = { tokens += onSuccessToken },
        onComplete = { tokens += onCompleteToken; latch.countDown() },
        onError = { tokens += onErrorToken; latch.countDown() }
)
latch.await(5, TimeUnit.SECONDS)
subscription.dispose()
```

And in tokens, i had only onSuccessToken. Is it ok?

**Comment by akarnokd** [comment]
The [javadoc](http://reactivex.io/RxJava/2.x/javadoc/io/reactivex/Maybe.html) of `Maybe` should be pretty clear:

![Image](https://raw.github.com/wiki/ReactiveX/RxJava/images/rx-operators/maybe.png)

> The main consumer type of Maybe is MaybeObserver whose methods are called in a sequential fashion following this protocol:
>
>onSubscribe (onSuccess | onError | onComplete)?.

**Comment by MarcinMoskala** [comment]
Thanks :)
