### ISSUE TITLE
Modify Consumer accept() throw Exception to throw Throwable instead.

### ISSUE THREAD

**Issue by RyanRamchandar** [ReactiveX/RxJava#5206]
For RxJava 2.0.7, the `Consumer` interface is defined as:
```java
public interface Consumer<T> {
    void accept(@NonNull T t) throws Exception;
}
```

Modifying it to 
```java
public interface Consumer<T> {
    void accept(@NonNull T t) throws Throwable;
}
```

allows us to rethrow the `Throwable` instead of an `Exception` (its subclass). This is helpful when we want to do something with the throwable (such as logging, or sending to crash reporting) and then rethrowing the Throwable to fail our application quickly.

For example:
```java
    public static Consumer<Throwable> logError(final String tag, final String msg) {
        return new Consumer<Throwable>() {
            @Override
            public void accept(@NonNull Throwable throwable) throws Exception {
                Log.e(tag, msg, throwable);
                throw throwable; // unreported exception Throwable; must be caught or declared to be thrown
            }
        };
    }
```

The throwable cannot be thrown here since since it is not an `Exception`. To make it work we have to:
 `throw new Exception(throwable)`

However, this causes the stack trace to show a CompositeException which is not as useful as the original stack trace of the Throwable:
```
Non-fatal Exception: io.reactivex.exceptions.CompositeException: 2 exceptions occurred. 
```

*Note: I realize that modifying `Consumer` may have larger consequences elsewhere, but mentioning it here anyways.*

**Comment by akarnokd** [comment]
I'm sorry, we can't change the signatures of our functional interfaces. Either you can check-and-cast the throwable back to a `RuntimeException` or `Exception` or you can smuggle the throwable as is via sneaky-throws technique.

**Comment by JakeWharton** [comment]
Exceptions aren't part of the method signature so a change would only be
source-incompatible and never binary incompatible.

**Comment by akarnokd** [comment]
Thanks @JakeWharton.

That source-incompatibility bothers me because we'd force our developer base to widen their `throws` declaration with unforseen consequences.

**Comment by akarnokd** [comment]
This won't happen in 2.x and we should come back to the case when 3.x development starts. Till then, I'm closing this issue.

**Comment by artem-zinnatullin** [comment]
@akarnokd can you please add `3.x` label or create separate 3.x issue?

**Comment by akarnokd** [comment]
You can create a new issue **when** the 3.x development starts, which is likely not before Java 9 comes out and the relevant tools (Gradle, Eclipse) support it properly.

**Comment by artem-zinnatullin** [comment]
Well I'm just afraid that we'll forget about it, but okay

**Comment by akarnokd** [comment]
I've run into situations with operator-fusion when a `T poll() throws Throwable` could have been a better option but such change to this internal feature would have propagated too far. Thus `throws Throwable` will be revisited anyway for 3.x.
