### ISSUE TITLE
2.x ObservableFromCallable crashes the app (UndeliverableException) if unsubscribed

### ISSUE THREAD

**Issue by konmik** [ReactiveX/RxJava#5214]
2.0.7

Reproduce (see test below):

1. subscribe to `Observable.fromCallable`
2. wait until is starts working
3. dispose
4. throw an exception inside the callable
5. get you app crashed

From my standpoint, if observer disposed an observable, it does not care about it anymore and thrown exceptions should be swallowed. Callable has no means to detect if is it still subscribed, so error handing inside of it is meaningless. even if it will have the means to check if it is still subscribed, raising the exception can result in a race condition between the check and actually throwing.

The current workaround is to install `RxJavaPlugins.setErrorHandler`, but this is unexpected behavior and I doubt it should be this way.

The test:

```
    @Test
    public void callableFail() throws Exception {
        AtomicReference<Throwable> ref = new AtomicReference<>();
        RxJavaPlugins.setErrorHandler(ref::set);

        Semaphore ready = new Semaphore(0);
        Semaphore crash = new Semaphore(0);

        Disposable disposable = Observable
                .fromCallable(() -> {
                    ready.release();
                    crash.acquireUninterruptibly();
                    throw new RuntimeException("Shouldn't it be swallowed?");
                })
                .subscribeOn(Schedulers.newThread())
                .subscribe(emptyConsumer(), ON_ERROR_MISSING);

        ready.acquire();
        disposable.dispose();
        crash.release();

        long start = nanoTime();
        while (nanoTime() - start < SECONDS.toNanos(1)) {
            assertNull(ref.get());
        }
    }
```

**Comment by akarnokd** [comment]
RxJava can't decide if your exception thrown from you callable is important or not, even if the sequence is cancelled. Indeed you have to install a global error consumer and decide yourself if that error is something your app should crash on or not. 

The current wisdom is that `NullPointerException`s, `IllegalArgumentException`s, `IllegalStateException`s are crash-worthy while `IOException`s, `SocketException`s and `InterruptedException`s are likely not, but depends on your actual app.

**Comment by konmik** [comment]
OK, I understand. Thanks for the answer.

I think it is better to make a strong statement in tutorial that users MUST override `RxJavaPlugins.setErrorHandler()` because RxJava can not guarantee exception-free execution while using just `onError` consumers in `subscribe` methods.

**Comment by akarnokd** [comment]
There is a sort section about this in the wiki: [Error handling](https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0#error-handling).

**Comment by konmik** [comment]
Wow, sorry for not being attentive.

Thanks a lot! :)

**Comment by akarnokd** [comment]
You are welcome.
