### ISSUE TITLE
2.x reuse CompositeDisposable

### ISSUE THREAD

**Issue by mibac138** [ReactiveX/RxJava#5215]
While working on a project I found out that after disposing `CompositeDisposable` it's completely useless. You can't reset it and use it again. From what I know you need to create a new instance of it to use it again and while it isn't very expensive, I'd love to see a reuse or reset kind of method to allow using the same instance again.

**Comment by JakeWharton** [comment]
clear()

**Comment by mibac138** [comment]
Thanks for the quick response. But after clearing the CompositeDisposable `disposed` is still `true` which prevents from using it again. It would need to set `disposed` to false in order to be reusable

**Comment by akarnokd** [comment]
@mibac138 You probably left in the original `dispose()` call somewhere.

**Comment by mibac138** [comment]
@akarnokd I get it now, thanks and sorry for the trouble!
