### ISSUE TITLE
2.x BiConsumer nullability annotations violated

### ISSUE THREAD

**Issue by davidschreiber** [ReactiveX/RxJava#5216]
**RxJava 2.0.7**

The `BiConsumer` interface has both parameters of its `accept()` method marked as `@NonNull`. However, when using the `BiConsumer` interface as result callback for a `Single`, the received parameter values are mutually exclusive being a non-null value and the other one being `null`. Although it seems to make sense in use, it violates the interface annotations and makes usage, at least, confusing.

```
Single.just("Some string")
    .subscribe(new BiConsumer<String, Throwable>() {
        @Override
        public void accept(@io.reactivex.annotations.NonNull String s, @io.reactivex.annotations.NonNull Throwable throwable) throws Exception {
            assert s != null;
            assert throwable == null;
        }
    });

Single.<String>error(new RuntimeException())
    .subscribe(new BiConsumer<String, Throwable>() {
        @Override
        public void accept(@io.reactivex.annotations.NonNull String s, @io.reactivex.annotations.NonNull Throwable throwable) throws Exception {
            assert s == null;
            assert throwable != null;
        }
    });
```

**Comment by akarnokd** [comment]
Indeed, those use cases should override the default annotation with `@Nullable`. Would you like to submit a PR?

**Comment by bloderxd** [comment]
@akarnokd I can submit a PR if @davidschreiber can't, but what do you suggest? An exclusive ```BiConsumer``` for ```Single``` ?

**Comment by akarnokd** [comment]
That would be a breaking change. I see 3 options:

- remove annotations from `BiConsumer`,
- change annotations on `BiConsumer` to `@Nullable` - may introduce a lot of warnings, 
- Do nothing and have your IDE suppress/ignore that warning.

**Comment by bloderxd** [comment]
Well I don't think it's a breaking change, it's just an interface extending ```BiConsumer``` example:

```java
  public void biconsumerWithCorrectNullableAnnotationInThrowable() {
        Single.just(1).subscribe(new SingleBiConsumer<Integer, Throwable>() {
            @Override
            public void accept(@Nullable Integer integer, @Nullable Throwable throwable) throws Exception {
                assertNull(throwable);
            }
        });
    }
```
What do you think?

**Comment by akarnokd** [comment]
Yes, you can simply delete the annotations or ignore them in your code.

**Comment by bloderxd** [comment]
Yes I know, but sometimes it's important to let developers know about property nullability, but ok thank you about your suggestions.

**Comment by PaulWoitaschek** [comment]
With kotlin it's actually more of an issue because if you create a biConsumer subclass it will take both parameters NonNull and throw an exception at runtime. 

I think the correct solution here is to remove the annotation (makes sense, sometimes it's nullable, sometimes it it's nonNull, )

**Comment by akarnokd** [comment]
Closing via #5257
