### ISSUE TITLE
FlatMap with Completable 

### ISSUE THREAD

**Issue by reactivedroid** [ReactiveX/RxJava#5218]
Basically I want to have the option of converting an Observable from flatMap to use as Completable. I am using RxJava 1.2.1 and trying to migrate to RxJava 2. Following the lead by Jake, I am removing all the Observable<Void> declarations  and replacing them with Completable. Here is the problem where I am stuck
```
 public Observable<Void> saveReminder(final Reminder reminder)
    {
        return Observable.fromEmitter((Emitter<DataSnapshot> dataSnapshotAsyncEmitter) ->
        {
            FirebaseApi.getReminderReference().addListenerForSingleValueEvent(new ValueEventListener()
            {
                @Override
                public void onDataChange(DataSnapshot dataSnapshot)
                {
                    dataSnapshotAsyncEmitter.onNext(dataSnapshot);
                    dataSnapshotAsyncEmitter.onCompleted();
                }

                @Override
                public void onCancelled(DatabaseError databaseError)
                {
                    if (databaseError != null)
                    {
                        dataSnapshotAsyncEmitter.onError(databaseError.toException());
                    }
                }
            });
        }, Emitter.BackpressureMode.LATEST).observeOn(Schedulers.io()).flatMap(reminderCardsSnapshot ->
        {
            try
            {
                return Observable.just(saveData(reminder, reminderCardsSnapshot));
            } catch (Exception e)
            {
                return Observable.error(e);
            }
        });
    }
```
I need to replace **Observable<Void>** with **Completable**. Plz help

**Comment by akarnokd** [comment]
Which one?

**Comment by reactivedroid** [comment]
@akarnokd I want to replace Observable<Void> to return Completable. 
`try
            {
                return Observable.just(saveData(reminder, reminderCardsSnapshot));
            } catch (Exception e)
            {
                return Observable.error(e);
            }`
How can the above method return Completable when it is wrapped inside flatMap which returns an Observable. Can you plz change the method above to return Completable?

**Comment by akarnokd** [comment]
```java
.flatMapCompletable(reminderCardsSnapshot ->
    Completable.fromAction(() -> saveData(reminder, reminderCardsSnapshot)))
```

As a general tip, I suggest you walk through each method in the classes so you can build a mental map on what's available.

**Comment by reactivedroid** [comment]
Agreed. But `flatMapCompletable` is available in RxJava2...do you know any way where we can achieve the same in RxJava 1.2.1?

**Comment by akarnokd** [comment]
Upgrade to 1.2.9.

**Comment by reactivedroid** [comment]
@akarnokd Thanks 👍
