### ISSUE TITLE
Information about RxJava

### ISSUE THREAD

**Issue by ocxler** [ReactiveX/RxJava#5228]
Hello guys,
I am writing a study work about RxJava and I am collecting information about it.
What I am most interested in: how you guys learned using RxJava and which way you would recommend?
There are some tutorials out there and I am going to pick a popular one to discuss the didactic and the provided information/concepts.
I would be thankful for any information!
Greetings

**Comment by akarnokd** [comment]
Please avoid cross posting.

http://stackoverflow.com/questions/43016876/how-did-you-learn-rxjava

I think most of the people kept searching for blogs and tutorial, read the official wiki and then went in and experimented with it.

**Comment by akarnokd** [comment]
Closing as the related StackOverflow question has been closed as well.
