### ISSUE TITLE
how to use observable.zip(array, function) like rxjs does

### ISSUE THREAD

**Issue by eccentricyan** [ReactiveX/RxJava#5229]
i want to use observable.zip(array, function) like rxjs did
http://stackoverflow.com/questions/35053384/rxjs-observable-zip-array-of-observables

```
compile 'io.reactivex.rxjava2:rxjava:2.0.5'
```
i have seen documents about zipArray, but it is difficult...

**Comment by akarnokd** [comment]
Questions like "how do I X with RxJava" are generally better suited for StackOverflow (where it may already have an answer).

What do you find difficult about `zipArray`?

**Comment by akarnokd** [comment]
Closing via [StackOverflow answer](http://stackoverflow.com/a/43020179/61158).
