### ISSUE TITLE
More general flavor of the sample() operator which allows duplicates?

### ISSUE THREAD

**Issue by sevar83** [ReactiveX/RxJava#5232]
Please look at the diagram:

[sample() with ObservableSource as selector](https://raw.github.com/wiki/ReactiveX/RxJava/images/rx-operators/sample.o.png)

What if I wish the third rhomboid item to cause emitting of a green circle downstream? Why `sample()` de-duplicates by default if that can be achieved just by composition with `distinctUntilChanged()` ?

Is it proper to add a boolean parameter that instructs if deduplication should be on or off? I give a very common example. The circles are combined sign-in credentials (POJO of username + password). The rhomboids are "Submit" button clicks. User clicks "Submit" but a network sign-in fails then the user clicks again after few seconds. The sample operator discards that click. I've tried to find some operator to model this scenario but didn't find one. Tried also with `JoinObservable` but not sure if that's what I need.

**Comment by akarnokd** [comment]
Please look at the following operators:

  - `withLatestFrom`
  - `combineLatest`
  - `debounce`
  - `switchMap`

([JavaDoc](http://reactivex.io/RxJava/2.x/javadoc/io/reactivex/Observable.html))

**Comment by sevar83** [comment]
10x, looking the marble diagrams, `withLatestFrom` has exactly the behavior I was searching for!

**Comment by akarnokd** [comment]
Great!
