### ISSUE TITLE
why Maybe.toSingle() if maybe is empty 2.x 

### ISSUE THREAD

**Issue by mortada-codes** [ReactiveX/RxJava#5233]
Single<Integer> singleOdd = Single.just(1);
        Single<Integer> singleEven = Single.just(2);

        Single.concat(singleOdd.filter(integer -> integer%2 ==0).toSingle(),singleEven).doOnError(throwable -> throwable.printStackTrace()).subscribe();
  
NoSuchElementException: The MaybeSource is empty

**Comment by akarnokd** [comment]
Please avoid cross posting, thanks.

http://stackoverflow.com/questions/43028932/rxjava-2-maybe-tosingle-error

**Comment by akarnokd** [comment]
Closing via http://stackoverflow.com/a/43032867/61158 .
