### ISSUE TITLE
2.1 API promotions

### ISSUE THREAD

**Issue by akarnokd** [ReactiveX/RxJava#5243]
Planned release date: **April 29, 2017**

### Experimental to Standard

- `CheckReturnValue` (since 2.0.2)
- `Scheduler.when()` (since 2.0.1)
- `CompletableSubject` (since 2.0.5)
- `MaybeSubject` (since 2.0.5)
- `SingleSubject` (since 2.0.5)
- `TestSubscriber.requestMore()` (since 2.0.1)

#### `Completable`
- `cache()` (since 2.0.4)
- `doFinally()` (since 2.0.1)
- `hide()` (since 2.0.5)

#### `Flowable`

- `doAfterNext()` (since 2.0.1)
- `doFinally()` (since 2.0.1)
- `sample()` with emitLast option (since 2.0.5)

#### `Maybe`

- `doAfterSuccess()` (since 2.0.1)
- `doFinally()` (since 2.0.1)
- `flatMapSingleElement()` (since 2.0.2)

#### `Observable`

- `doAfterNext()` (since 2.0.1)
- `doFinally()` (since 2.0.1)
- `sample()` with emitLast option (since 2.0.5)

#### `Single`

- `doAfterSuccess()` (since 2.0.1)
- `doAfterTerminate()` (since 2.0.6)
- `doFinally()` (since 2.0.1)

#### `BaseTestConsumer`

- `assertNever()` (since 2.0.5) 2 overloads
- `assertNoTimeout()` (since 2.0.7)
- `assertTimeout()` (since 2.0.7)
- `awaitCount()` (since 2.0.7) 3 overloads
- `clearTimeout()` (since 2.0.7)
- `isTimeout()` (since 2.0.7)
- `TestWaitStrategy` (since 2.0.7)
- `withTag()` (since 2.0.7)

#### `RxJavaPlugins`

- `createComputationScheduler()` (since 2.0.5)
- `createIoScheduler()` (since 2.0.5)
- `createNewThreadScheduler()` (since 2.0.5)
- `createSingleScheduler()` (since 2.0.5)
- `getOnBeforeBlocking()` (since 2.0.5)
- `isFailOnBlockingScheduler()` (since 2.0.5)
- `onBeforeBlocking` (since 2.0.5)
- `setFailOnBlockingScheduler()` (since 2.0.5)
- `setOnBeforeBlocking()` (since 2.0.5)

### Beta to Standard

There are no components marked with `@Beta` in the 2.0.x version additions.

### Experimental to Beta

- `FlowableSubscriber` (since 2.0.7)
- `Flowable.parallel()` (since 2.0.5) 3 overloads
- `Flowable.subscribe(FlowableSubscriber)` (since 2.0.7)
- `OnErrorNotImplementedException` (since 2.0.6)
- `ProtocolViolationException` (since 2.0.6)
- `UndeliverableException` (since 2.0.6)
- `ParallelFlowable` (since 2.0.5)
- `RxJavaPlugins.getOnParallelAssembly()` (since 2.0.6)
- `RxJavaPlugins.onAssembly(ParallelFlowable)` (since 2.0.6)
- `RxJavaPlugins.setOnParallelAssembly()` (since 2.0.6)

### Leave as is

- `Observable.switchMapSingle()` (since 2.0.8 - experimental)
- `Observable.switchMapSingleDelayError()` (since 2.0.8 - experimental)
- `ParallelFailureHandling` (since 2.0.8 - experimental)
- `ParallelFlowable.doOnNext(Consumer, ParallelFailureHandling)` (since 2.0.8 - experimental)
- `ParallelFlowable.map(Consumer, ParallelFailureHandling)` (since 2.0.8 - experimental)
-` ParallelFlowable.filter(Consumer, ParallelFailureHandling)` (since 2.0.8 - experimental)
- `ParallelTransformer` (since 2.0.8 - experimental)
- `BehaviorProcessor.offer()` (since 2.0.8 - experimental)
- `PublishProcessor.offer()` (since 2.0.8 - experimental)
- `UnicastProcessor.create(boolean)` (since 2.0.8 -experimental) 2 overloads of fail-fast mode
- `UnicastSubject.create(boolean)` (since 2.0.8 -experimental) 2 overloads of fail-fast mode
- `Single.unsubscribeOn(Scheduler)` (since 2.0.9 - experimental)

### Remove

`Flowable.strict()` (since 2.0.5, deprecated in 2.0.7)

**Comment by vanniktech** [comment]
What about the `@CheckReturnValue` annotation? Right now it's experimental.

**Comment by akarnokd** [comment]
Thanks, added to the experimental -> standard section.

**Comment by akarnokd** [comment]
I'd like to define what should happen with the `@since` tags and the old version number:

- the standard promotions will be updated to `@since 2.1`
- the experimental-beta promotions will be updated to `@since 2.1 - beta`
- the previous version value will be moved into just before the first param or return tag:

```java
/**
 * The operator ...
 * <p>History: 2.0.6 - experimental.
 * @param x ...
 * @since 2.1
 */
@CheckReturnValue
public final Flowable<R> operator(...)
```

This small addendum should help quickly pinpoint when certain features were added and were promoted without the need to scan through release logs, commits and PRs.

**Comment by akarnokd** [comment]
Closing via #5307.
