### ISSUE TITLE
1.x 2.x Use IDE friendly assertion failed statements 

### ISSUE THREAD

**Issue by mtiidla** [ReactiveX/RxJava#5249]
Currently the assertItem prints by the following statements, focus on "_expected to be_"
```
private void assertItem(T expected, int i) {
        T actual = values.get(i);
        if (expected == null) {
            // check for null equality
            if (actual != null) {
                assertionError("Value at index: " + i + " expected to be [null] but was: [" + actual + "]\n");
            }
        } else if (!expected.equals(actual)) {
            assertionError("Value at index: " + i
                    + " expected to be [" + expected + "] (" + expected.getClass().getSimpleName()
                    + ") but was: [" + actual + "] (" + (actual != null ? actual.getClass().getSimpleName() : "null") + ")\n");

        }
    }
```

However, it does not match any of the IntelliJ assertion regex patterns, thus making it very difficult to visually compare expected and actual values. We forked `assertItem()` using one of the following patterns from [this](https://github.com/JetBrains/intellij-community/blob/3f7e93e20b7e79ba389adf593b3b59e46a3e01d1/plugins/testng/src/com/theoryinpractice/testng/model/TestProxy.java) and could immediately see the `<Click to see difference>` link in the IDE.

**Comment by akarnokd** [comment]
PR welcome.

**Comment by vanniktech** [comment]
@mtiidla is 2.x also affected?

**Comment by mtiidla** [comment]
@akarnokd Could you please choose the most pleasing pattern from the IntelliJ class I linked to? If you don't have any preference, then I would go with EXPECTED_BUT_WAS_PATTERN as JUnit4 is using it `"expected:<" + expected + "> but was:<" + actual + ">"`

@vanniktech The output is different, but also not recognized, for example the following code:
`Observable.just("Test").test().assertValue("test");`
produces: _Expected: test (class: String), Actual: Test (class: String)_ and there is no link presented by IntelliJ to compare the output. (I have also edited the Issue title with 2.x)

**Comment by akarnokd** [comment]
The JUnit pattern is fine with me.
