### ISSUE TITLE
Is it possible to do real non-blocking IO with RxJava?

### ISSUE THREAD

**Issue by jfconavarrete** [ReactiveX/RxJava#5260]
Hello all,

I have been trying to do non-blocking IO requests with RxJava without success, all I have been able to achieve is making my calls run asynchronously on a thread from the Schedulers.io thread pool. It seems that the threads from Schedulers.io still block waiting for the response, therefore not doing real NIO.

Is it possible to do real NIO using just RxJava or does one have to use another library that does NIO (such as Unirest)?

Thanks in advance

**Comment by akarnokd** [comment]
RxJava doesn't do IO on its own and you need some other library for that, such as Netty for example.

**Comment by akarnokd** [comment]
Looks like this question has been answered. If you have further input on the issue, don't hesitate to reopen this issue or post a new one.
