### ISSUE TITLE
2.x: dematerialize and completion

### ISSUE THREAD

**Issue by davidmoten** [ReactiveX/RxJava#5261]
I do not expect `Flowable.just(Notification.createOnNext(1)).dematerialize()` to complete but it does.

Do you think this is a bug too? If so I can submit a PR.

**Comment by davidmoten** [comment]
Ditto `Observable.dematerialize`

**Comment by akarnokd** [comment]
It't not a bug.

**Comment by davidmoten** [comment]
Yes I agree that formally it's not a bug because the javadoc for `dematerialize` says:

>Returns a Flowable that reverses the effect of materialize by transforming the Notification objects emitted by the source Publisher into the items or notifications they represent.

A simpler example of the issue is that `Flowable.empty().dematerialize()` should not complete because `Notification.onComplete`/`Notification.onError` were not emitted by `Flowable.empty()`. I think the current behaviour is counter-intuitive and should be changed (will not contradict the javadoc by the way because its behaviour was undefined).

@akarnokd If you don't agree that the current behaviour should be changed then I suggest I supplement the javadoc to describe the operator's behaviour more precisely.

**Comment by akarnokd** [comment]
You can suppress the terminal event by concatenating with never. You can post a PR that adds more clarification.

**Comment by akarnokd** [comment]
PR welcome.

**Comment by davidmoten** [comment]
Will do, I'll make it this weekend.

**Comment by akarnokd** [comment]
Do you still want to contribute the clarification?
