### ISSUE TITLE
The ParallelFlowable's behavior of the cancel method had been changed between 2.0.6 and 2.0.7

### ISSUE THREAD

**Issue by otal1105** [ReactiveX/RxJava#5263]
In the case that a ParallelFlowable was subscribed by an array of Subscribers, 
when one Subscriber calls the cancel method, the ParallelFlowable stops emitting and all the Subscribers don't get any items on 2.0.6.
However, I upgraded to 2.0.7, the ParallelFlowable stops emitting to only the Subscriber which called the cancel method and the others keep getting items.

I wonder which one would be the expected behavior.
To me, 2.0.7's behavior makes more sense.

**Comment by akarnokd** [comment]
See #5117.

**Comment by otal1105** [comment]
Thank you. I didn't check this issue since I thought that this issue is about an exception handling.
