### ISSUE TITLE
doOnDispose / doOnLifecycle onDisposed action not being called

### ISSUE THREAD

**Issue by fqborges** [ReactiveX/RxJava#5264]
Maybe I am doing something wrong, but this just stopped working when I updated version from 2.01 to 2.07 and 2.08.

The doOnDispose and the doOnLifecycle onDisposed action are not being called.

Sample code:

        Observable.fromCallable(() -> "1")
                .doOnLifecycle(
                        disposable -> Log.i(TAG, "1:doOnSubscribe"),
                        () -> Log.i(TAG, "1:doOnDispose")
                )
                .subscribe()
                .dispose();

        Observable.fromCallable(() -> "2")
                .doOnSubscribe(disposable -> Log.i(TAG, "2:doOnSubscribe"))
                .doOnDispose(() -> Log.i(TAG, "2:doOnDispose"))
                .subscribe()
                .dispose();

**Comment by akarnokd** [comment]
`subscribe` disconnects the upstream `Disposable` when it receives a terminal event thus you can't dispose an already completed sequence. This change was introduced in 2.0.5 via #4957.

**Comment by fqborges** [comment]
Is there a way to receive onDispose events after 2.0.5?
I was using subscribe and dispose events for showing and hiding activity indicators/progress bar on when doing network.

For example, I used to do something like this:

                doSomethingUsingNetwork()
                .doOnSubscribe(d -> showProgress() )
                .doOnDispose(() -> hideProgress() )
                .subscribe(
                        this::handleNext,
                        this::handleError
                )

Edit: Why using onDispose? Because I missed the onFinally events when the subscription was disposed before onComplete/onError

**Comment by akarnokd** [comment]
Use doFinally.

**Comment by fqborges** [comment]
Thanks, it works like a charm in this version.

**Comment by akarnokd** [comment]
Looks like this question has been answered. If you have further input on the issue, don't hesitate to reopen this issue or post a new one.
