### ISSUE TITLE
CombineLatest computation explosion

### ISSUE THREAD

**Issue by diorcety** [ReactiveX/RxJava#5266]
Hi,
I'm massively using RXjava for compute actions in my program.
According to the user wanted actions and program settings, I'm computing the task duration and other stuff.
I'm falling on tricky situation that which maybe can't be solve with Rx.
The users actions with parameters are kind of tree of "small actions". I'm building an observable tree according to the user choice. In some "small actions", I'm using software parameters. So my observable tree is built using switchMap(transform user choice) and combineLatest (for combining two successive actions).
The issue appeas with lot of actions. I'm creating the observable tree according to the user choice, take few times (<2s)(The user parameters are not observable yet, so i'm rebuilding all the tree from the root for each user changes). But if i'm changing one parameter which is used repetitively inside the tree(as "leaf" observable), it takes ages. It seems logical due to combineLatest which change two times (previous action, and the action) and that for all the tree nodes.
I'm already thinking to an alternative which will consist to associate the "leaf" observables to the tree construction and only combileLatest with all the "leaf" observables.
I don't want complexify more the tree builder, I'm wondering if there is inside RxJava already a solution for that issue.
A kind of debounce of all the "leaf" observables which will recompute the tree from the root to the leaf (like my observable tree building)

Here an overview (obs1 and obs2 are the "leaf" observables).

<pre>
Obs1\                                                              
     |-> combineLatest \                               
Obs2/                  |        
                       | -> combineLatest  \                       
Obs1\                  |                   |
     |-> combineLatest /                   |
Obs2/                                      |
                                           |
                                           |
                                           |
                                           |-->combineLatest ---- .... many more
                                           |
Obs1\                                      |
     |-> combineLatest \                   |
Obs2/                  |                   |
                       | -> combineLatest  /
Obs1\                  |                             
     |-> combineLatest /
Obs2/

many more ...
</pre>

Thanks,

**Comment by akarnokd** [comment]
This question is better suited for StackOverflow.
