### ISSUE TITLE
compile "io.reactivex.rxjava2:rxjava:2.x.y"

### ISSUE THREAD

**Issue by sheep0704** [ReactiveX/RxJava#5269]
无法使用"Could not find resource"

**Comment by karl1992** [comment]
Error:A problem occurred configuring project ':library'.
> Could not resolve all dependencies for configuration ':library:_debugCompile'.
   > Could not find io.reactivex.rxjava2:rxjava:2.x.y.
     Searched in the following locations:
         https://jcenter.bintray.com/io/reactivex/rxjava2/rxjava/2.x.y/rxjava-2.x.y.pom
         https://jcenter.bintray.com/io/reactivex/rxjava2/rxjava/2.x.y/rxjava-2.x.y.jar
         file:/F:/android/sdk/extras/android/m2repository/io/reactivex/rxjava2/rxjava/2.x.y/rxjava-2.x.y.pom
         file:/F:/android/sdk/extras/android/m2repository/io/reactivex/rxjava2/rxjava/2.x.y/rxjava-2.x.y.jar
         file:/F:/android/sdk/extras/google/m2repository/io/reactivex/rxjava2/rxjava/2.x.y/rxjava-2.x.y.pom
         file:/F:/android/sdk/extras/google/m2repository/io/reactivex/rxjava2/rxjava/2.x.y/rxjava-2.x.y.jar

**Comment by sheep0704** [comment]
如果
