### ISSUE TITLE
Rxjava2.0 And RxAndroid 1.2.1

### ISSUE THREAD

**Issue by sheep0704** [ReactiveX/RxJava#5270]
rxandroid:1.2.1 And rxjava:2.0  一起使用的话是否会有问题？

**Comment by akarnokd** [comment]
Could you please state your problem in English?

Here is an example of how to set up an Android project: https://github.com/amitshekhariitbhu/RxJava2-Android-Samples/blob/master/app/build.gradle#L27

**Comment by artem-zinnatullin** [comment]
I guess it duplicates https://github.com/ReactiveX/RxAndroid/issues/369 and could be closed as well.

**Comment by sheep0704** [comment]
GET
