### ISSUE TITLE
1.x repeatWhen does not call onCompleted on child subscription

### ISSUE THREAD

**Issue by Chubacca** [ReactiveX/RxJava#5272]
Tested using RxJava 1.2.9.

The description of `repeatWhen` implies if the `notificationHandler` call an `onComplete` it should pass it onto the child subscription: "If that Observable calls onComplete or onError then repeatWhen will call onCompleted or onError on the child subscription."

However, this doesn't seem to happen. The `onError` seems to work, but `onCompleted` does not. This code illustrates this:

```java
Subscriber<Integer> subscriber = new Subscriber<Integer>() {
    @Override public void onCompleted() {
        System.out.println("completed");
    }

    @Override public void onError(Throwable e) {
        System.out.println("error");
    }

    @Override public void onNext(Integer i) {

    }
};

// Does not output anything
Observable.just(1)
        .repeatWhen(observable -> observable.flatMap(ignored -> Observable.empty()))
        .subscribe(subscriber);

// Prints "error" (as expected)
Observable.just(1)
        .repeatWhen(observable -> observable.flatMap(ignored -> Observable.error(new Exception())))
        .subscribe(subscriber);
```

**Comment by akarnokd** [comment]
You can't complete an entire `flatMap` with an inner `empty()` source, that just counts as 'skipping' and the merged flow is kept intact. For `repeatWhen` and `retryWhen`, you need a different mechanism and make `observable` complete, for example, with `takeWhile` or `takeUntil` or some lifted operator that can turn an `onNext` into an `onCompleted`.

**Comment by Chubacca** [comment]
Ah, makes sense, the flatMap won't pass the onComplete through (because it's mapped). Thanks!
