### ISSUE TITLE
2.x: Flowable.error and onSubscribe

### ISSUE THREAD

**Issue by davidmoten** [ReactiveX/RxJava#5273]
When testing a custom operator I noticed that `Flowable.error` does not call `onSubscribe` before emitting `onError`. This is against [reactive-streams 1.9](https://github.com/reactive-streams/reactive-streams-jvm#1-publisher-code). Bug?

**Comment by davidmoten** [comment]
my mistake, it does call `onSubscribe`!

**Comment by akarnokd** [comment]
`EmptySubscription` has a convenience method to do an `onSubscribe` + `onError` call.
