### ISSUE TITLE
2.x: Reactive Streams Rule 3.9 violations

### ISSUE THREAD

**Issue by artem-zinnatullin** [ReactiveX/RxJava#5274]
Rule [3.9](https://github.com/reactive-streams/reactive-streams-jvm/tree/a570a7f88a922752ed35ee28322db9f23e740ae6#3.9) of Reactive Streams:

>While the`Subscription` is not cancelled, `Subscription.request(long n)` MUST signal `onError` with a `java.lang.IllegalArgumentException` if the argument is <= 0. The cause message MUST include a reference to this rule and/or quote the full rule.

Current implementation of RxJava v2 seems to violate this rule in two places:

1) Signal with `IllegalArgumentException` is delivered to the `RxJavaPlugins.onError()` and not the `Subscriber.onError()`.

Tests:

```java
@Test
public void negativeRequestShouldSignalOnError() {
    TestSubscriber<Integer> ts = TestSubscriber.create(0);
    Flowable.just(1).subscribe(ts);
    
    ts.request(-1);
    
    ts.assertError(IllegalArgumentException.class);
}

@Test
public void zeroRequestShouldSignalOnError() {
    TestSubscriber<Integer> ts = TestSubscriber.create(0);
    Flowable.just(1).subscribe(ts);

    ts.request(0);

    ts.assertError(IllegalArgumentException.class);
}
```
2) Cause message does not include reference to the rule nor quotes it.

Test:

```java
@Test
public void illegalRequestShouldReferenceRuleOrQuoteIt() {
    TestSubscriber<Integer> ts = TestSubscriber.create(0);
    Flowable.just(1).subscribe(ts);

    ts.request(-1);

    String cause = ts.errors().get(0).getMessage();
    
    assertTrue(cause.contains("3.9") || cause.contains("While the Subscription is not cancelled, Subscription.request(long n) MUST signal onError with a java.lang.IllegalArgumentException if the argument is <= 0. The cause message MUST include a reference to this rule and/or quote the full rule. The intent of this rule is to prevent faulty implementations to proceed operation without any exceptions being raised. Requesting a negative or 0 number of elements, since requests are additive, most likely to be the result of an erroneous calculation on the behalf of the Subscriber."));
}
```

I can open two separate PRs to fix these violations if issue will be approved.

**Comment by akarnokd** [comment]
See 
- https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0#reactive-streams-compliance
- #5110 
- #5112

Also note that we pass the TCK which has explicit checks for this rule...

**Comment by artem-zinnatullin** [comment]
Aha, I see, so when we use RxJava v2 specific `Subscriber` types — 3.9 is relaxed, but if Reactive Streams `Subscriber` subscribes — these rules are not violated.

👍 what a slowpoke am I…
