### ISSUE TITLE
Can distinctUntilChanged operator work on custom Flowable?

### ISSUE THREAD

**Issue by Joseph82** [ReactiveX/RxJava#5275]
In order to create a new Flowable, in RxJava 2 (2.0.8), I use `create(FlowableOnSubscribe<T> source, BackpressureStrategy mode)`.

In some situation, instead, I need to extend the Flowable class, overriding `subscribeActual(Subscriber subscriber)`, where, using the data passed in the constructor, I create the actual subscriber and start the subscription calling `onSubscribe(Subscription s)`. 
Eventually I create the Flowable, instantiating directly my custom Flowable.

Both implementations works fine, except the following:

For the Flowable created using `create()` method, the operator `distinctUntilChanged(BiPredicate<? super T, ? super T> comparer)` works fine. Instead, the same operator, used on a custom Flowable, doesn't work: I keep receiving in the `test()` method of the comparator, the same object for both parameters.

The implementation of my custom Flowable is very similar to the [TextViewTextChangeEventObservable](https://github.com/JakeWharton/RxBinding/blob/master/rxbinding/src/main/java/com/jakewharton/rxbinding2/widget/TextViewTextChangeEventObservable.java) class from RxBinding2 library:  (except of course that for me it is Flowable). And indeed I tried also testing the Observable retrieved from: 

`RxTextView.textChangeEvents(mEditText) // it is a TextViewTextChangeEventObservable  object`

and, if I apply on this Observable the operator `distinctUntilChanged` I receive the same object in both the parameters of the `test()` method. 

Why this happens? What can I do in order to allow a custom `Flowable` to work fine also with `distinctUntilChanged` operator?

**Comment by akarnokd** [comment]
No idea since you don't show any code...

What I learned from Android text fields is that they signal the same mutable CharSequence instance and you have to make a snapshot of it via toString.

**Comment by Joseph82** [comment]
Ok, you are right. I give here an example:

1. using `Flowable.create()`
**CREATION**: 
```
Flowable<Integer> createdFlowable = Flowable.create(e -> {
            e.onNext(1);
            e.onNext(2);
            e.onNext(2);
            e.onNext(2);
            e.onNext(3);
            e.onNext(4);
            e.onNext(5);
            e.onNext(5);
        }, BackpressureStrategy.DROP);
```
**USAGE**:
```
createdFlowable.distinctUntilChanged((integer, integer2) -> integer.intValue() == integer2.intValue())
                .subscribe(integer -> Log.d("Consumer", "Value: " + integer.intValue()));

```
**OUTPUT**:

Value: 1
Value: 2
Value: 3
Value: 4
Value: 5

2. Using custom Flowable. (It is a dummy Flowable, that in a real world doesn't make sense)

```
public final class CustomFlowable extends Flowable<Integer> {

    @Override
    protected void subscribeActual(Subscriber subscriber) {
        Listener listener = new Listener(subscriber);
        subscriber.onSubscribe(listener);
        listener.start();
    }

    static final class Listener implements Subscription {
        private final Subscriber<Integer> subscriber;


        Listener(Subscriber<Integer> subscriber) {
            this.subscriber = subscriber;
        }

        public void start() {
            subsciber.onNext(1);
            subsciber.onNext(2);
            subsciber.onNext(2);
            subsciber.onNext(2);
            subsciber.onNext(3);
            subsciber.onNext(4);
            subsciber.onNext(5);
            subsciber.onNext(5);
        }

        @Override
        public void request(long n) {

        }

        @Override
        public void cancel() {
        }
    }
}
```

**USAGE**:

```
new CustomFlowable().distinctUntilChanged((integer, integer2) -> integer.intValue() == integer2.intValue())
                .subscribe(integer -> Log.d("Consumer", "Value: " + integer.intValue()));
```

**OUTPUT**:

Value: 1
Value: 2
Value: 2
Value: 2
Value: 4
Value: 5
Value: 5

**Comment by akarnokd** [comment]
Works for me:

```java
import org.junit.Test;
import org.reactivestreams.*;

import io.reactivex.Flowable;

public class CustomFlowableTest {

    @Test
    public void test() {
        new CustomFlowable().distinctUntilChanged((integer, integer2) -> integer.intValue() == integer2.intValue())
        .subscribe(integer -> System.out.println("Consumer | Value: " + integer.intValue()));
    }
    
    public static final class CustomFlowable extends Flowable<Integer> {

        @Override
        protected void subscribeActual(Subscriber<? super Integer> subscriber) {
            Listener listener = new Listener(subscriber);
            subscriber.onSubscribe(listener);
            listener.start();
        }

        static final class Listener implements Subscription {
            private final Subscriber<? super Integer> subscriber;


            Listener(Subscriber<? super Integer> subscriber) {
                this.subscriber = subscriber;
            }

            public void start() {
                subscriber.onNext(1);
                subscriber.onNext(2);
                subscriber.onNext(2);
                subscriber.onNext(2);
                subscriber.onNext(3);
                subscriber.onNext(4);
                subscriber.onNext(5);
                subscriber.onNext(5);
            }

            @Override
            public void request(long n) {

            }

            @Override
            public void cancel() {
            }
        }
    }
}
```

```
Consumer | Value: 1
Consumer | Value: 2
Consumer | Value: 3
Consumer | Value: 4
Consumer | Value: 5
```

**Comment by Joseph82** [comment]
I'm sorry for wasting your time. It works for me as well. 
There was something wrong, that I can't reproduce anymore. Probably there was something dirty in the same class (other observable and subscribers).

And about the same mutable `CharSequence` instance, you were right. 

Sorry again, and thank you.

**Comment by akarnokd** [comment]
Looks like this question has been answered. If you have further input on the issue, don't hesitate to reopen this issue or post a new one.
