### ISSUE TITLE
1.2.7 Completable swallowing errors

### ISSUE THREAD

**Issue by qazt482** [ReactiveX/RxJava#5278]
Can someone explain why the Completable test below fails because no exception was thrown?

    	@Test
	public void testCompletableError() {
		try {
			new MyExplodingCompletable().someMethod().subscribe();
			fail("error not thrown up");
		} catch (Exception e) {
			assertEquals(OnErrorNotImplementedException.class, e.getClass());
		}
	}

	@Test
	public void testSingleError() {
		try {
			new MyExplodingSingle().someMethod().subscribe();
			fail("error not thrown up");
		} catch (Exception e) {
			assertEquals(OnErrorNotImplementedException.class, e.getClass());
		}
	}

	@Test
	public void testObservableError() {
		try {
			new MyExplodingObserver().someMethod().subscribe();
			fail("error not thrown up");
		} catch (Exception e) {
			assertEquals(OnErrorNotImplementedException.class, e.getClass());
		}
	}

	class MyExplodingCompletable {

		Completable someMethod() {
			return Completable.error(new Exception("boom"));
		}
	}

	class MyExplodingSingle {
		Single someMethod() {
			return Single.error(new Exception("boom"));
		}
	}

	class MyExplodingObserver {
		Observable someMethod() {
			return Observable.error(new Exception("boom"));
		}
	}

**Comment by akarnokd** [comment]
`Completable` was designed a bit differently, and comes as a backport from 2.x where `CompletableObserver` is not allowed to throw.

**Comment by akarnokd** [comment]
Looks like this question has been answered. If you have further input on the issue, don't hesitate to reopen this issue or post a new one.

**Comment by dklotz** [comment]
@akarnokd This inconsistency between Single, Observable and Completable is driving me crazy while trying to have one unified way of handling uncaught exceptions that works for all singles, observables and completables in an application. If I e.g. have a single and subscribe without giving an onError callback, I can see OnErrorNotImplementedException bubble up to some central place where I can handle it, if I call toCompletable on the same Single and subscribe again without an onError callback, the exception is completely swallowed. From an API user standpoint, its really difficult to understand why Completable should work any different from Single or Observable.

**Comment by akarnokd** [comment]
@dklotz always specify an `onError` handler.
