### ISSUE TITLE
Handling null in RxJava2

### ISSUE THREAD

**Issue by reactivedroid** [ReactiveX/RxJava#5289]
I am migrating from RxJava1.x to RxJava2. I have to handle null in many scenarios because previously RxJava1.x was supporting Observable<Void> which accepted null. Here is the scenario:

```
 public Completable updatePatient(final Patient patient)
    {
        return Completable.fromCallable(() -> update(patient));
    }

    private static Void update(Patient patient) throws HttpException, NoNetworkException, JSONException, IOException
    {
        ...code to update patient
        return null;
    }
```

As seen from above example, the updatePatient does not return any value. Hence Completable is used to indicate onComplete or onError only. I want this null to be removed following RxJava2 conventions. Plz help

**Comment by akarnokd** [comment]
See https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0#nulls

**Comment by akarnokd** [comment]
Looks like this question has been answered. If you have further input on the issue, don't hesitate to reopen this issue or post a new one.
