### ISSUE TITLE
2.x `Flowable.create` parameter ordering is awkward (especially in Kotlin)

### ISSUE THREAD

**Issue by joshfriend** [ReactiveX/RxJava#5291]
The ordering of the `Flowable.create` parameters makes it impossible to use trailing closures in Kotlin, causing calls that look like this:

```kotlin
Flowable.create({ emitter ->
  // etc...
}, LATEST)
```

If the declaration were `Flowable.create(BackpressureStrategy, FlowableOnSubscribe<T>)` it would be possible to do this instead:

```kotlin
Flowable.create(LATEST) { emitter ->
  // etc...
}
```

Ordinarily, I'd solve this by making an extension function on the class, but Kotlin can't add static methods to java classes as they lack a `companion object`.

**Comment by JakeWharton** [comment]
You can use a top-level function instead:
```kotlin
fun flowable(strategy: BPS, onSubscribe: (Emitter) -> Unit) = Flowable.create(onSubscribe, strategy)
```

**Comment by joshfriend** [comment]
That's what I ended up with too, but it doesn't "feel right". Is this a change that could be considered for a future release?

**Comment by akarnokd** [comment]
RxJava is a Java library where the current parameter order "feels right". Source like static operators, such as `create` can live in any other class, not necessarily in `Flowable` thus you can create your own class with parameter ordering as you see fit. In addition, Kotlin has extension methods so you you can "add" instance operators without going through the hassle of waiting for / requesting one in RxJava proper.

**Comment by akarnokd** [comment]
Closing as the signature can't be changed but Kotlin users can define their own functions with the parameter ordering as they see fit.
