### ISSUE TITLE
rx.exceptions.OnErrorThrowable$OnNextValue

### ISSUE THREAD

**Issue by gewuxy** [ReactiveX/RxJava#5293]
I use rxjava and retrofit to send audio file after recording,but sometimes server reports that audio file broken,the log is:
rx.exceptions.OnErrorThrowable$OnNextValue
OnError while emitting onNext value: com.lizhiweike.network.HttpResult.class

`

    compile 'com.squareup.retrofit2:retrofit:2.2.0'
    compile 'com.squareup.retrofit2:adapter-rxjava:2.2.0'
    compile 'com.squareup.retrofit2:converter-gson:2.2.0'
    compile 'io.reactivex:rxjava:1.0.14'
    compile 'io.reactivex:rxandroid:1.0.1'

        File file = new File(path);
        RequestBody requestFile = RequestBody.create(MediaType.parse("audio/*"), file);
        body = MultipartBody.Part.createFormData("audio_file", file.getName(), requestFile);

        HashMap<String,RequestBody> params = new HashMap<>();
        params.put("lecture_id",RequestBody.create(MediaType.parse("multipart/form-data"), mId + ""));
        params.put("need_encode",RequestBody.create(MediaType.parse("multipart/form-data"), String.valueOf(false)));
        params.put("duration",RequestBody.create(MediaType.parse("multipart/form-data"),attachment.getDuration() + ""));

        Subscription subscription = ApiService.getInstance().sendAudioMessage(body,params).subscribe(new HttpObserver<IMMessage>() {
            @Override
            protected void onError(ApiException ex) {
                CrashReport.postCatchedException(ex);
                ToastUtil.showToast(getActivity(),ex.getMsg());
                onSendMessageFail(msg);
            }

            @Override
            public void onNext(IMMessage imMessage) {
                onSendMessageSuccess(msg);
            }
        });
        mCompositeSubscription.add(subscription);
`

**Comment by gewuxy** [comment]
`

    @Multipart
    @POST("api/upload_audio")
    Observable<HttpResult<IMMessage>> sendAudioMessage(@Part MultipartBody.Part audio, @PartMap Map<String,RequestBody> map);

    public Observable<IMMessage> sendAudioMessage(MultipartBody.Part file, Map<String,RequestBody> params){
        return weikeApi.sendAudioMessage(file,params)
                .map(new ServerResultFunc<IMMessage>())
                .onErrorResumeNext(new HttpResultFunc<IMMessage>())
                .subscribeOn(Schedulers.io())
                .unsubscribeOn(Schedulers.io())
                .observeOn(AndroidSchedulers.mainThread());
    }
`

**Comment by akarnokd** [comment]
Could you share the full stacktrace?

**Comment by gewuxy** [comment]
com.xx.network.exception.ApiException:com.xx.network.exception.ServerException
2 com.xx.network.ExceptionEngine.handleException(ExceptionEngine.java:55)
3 ......
4 Caused by:
5 rx.exceptions.OnErrorThrowable$OnNextValue:OnError while emitting onNext value: com.xx.network.HttpResult.class
6 rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:73)
7 retrofit2.adapter.rxjava.BodyOnSubscribe$BodySubscriber.onNext(BodyOnSubscribe.java:48)
8 retrofit2.adapter.rxjava.BodyOnSubscribe$BodySubscriber.onNext(BodyOnSubscribe.java:36)
9 retrofit2.adapter.rxjava.CallArbiter.deliverResponse(CallArbiter.java:115)
10 retrofit2.adapter.rxjava.CallArbiter.emitResponse(CallArbiter.java:97)
11 retrofit2.adapter.rxjava.CallExecuteOnSubscribe.call(CallExecuteOnSubscribe.java:46)
12 retrofit2.adapter.rxjava.CallExecuteOnSubscribe.call(CallExecuteOnSubscribe.java:24)
13 retrofit2.adapter.rxjava.BodyOnSubscribe.call(BodyOnSubscribe.java:33)
14 retrofit2.adapter.rxjava.BodyOnSubscribe.call(BodyOnSubscribe.java:25)
15 rx.Observable.unsafeSubscribe(Observable.java:10151)
16 rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
17 rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
18 rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
19 rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
20 rx.Observable.unsafeSubscribe(Observable.java:10151)
21 rx.internal.operators.OperatorSubscribeOn$1.call(OperatorSubscribeOn.java:94)
22 rx.internal.schedulers.CachedThreadScheduler$EventLoopWorker$1.call(CachedThreadScheduler.java:228)
23 rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
24 java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
25 java.util.concurrent.FutureTask.run(FutureTask.java:237)
26 java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152)
27 java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265)
28 java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
29 java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
30 java.lang.Thread.run(Thread.java:818)

**Comment by akarnokd** [comment]
Looks like your `ServerResultFunc` crashes.  But it is still unclear why; maybe there is another cause below what you posted?

**Comment by gewuxy** [comment]
the server side reports that file broken

**Comment by gewuxy** [comment]
`    

    private class ServerResultFunc<T> implements Func1<HttpResult<T>, T> {
        @Override
        public T call(HttpResult<T> httpResult) {
            if (httpResult.getCode() != 0) {
                throw new ServerException(httpResult.getCode(),httpResult.getMsg());
            }
            return httpResult.getData();
        }
    }`

**Comment by akarnokd** [comment]
Since RxJava doesn't do networking, you should see what's wrong with Retrofit (for example, stripping RxJava and doing plain Retrofit calls). It is possible you run into a bug that's been fixed in a newer version. Also you may try StackOverflow and ask how and why Retrofit would upload incomplete data.

**Comment by akarnokd** [comment]
Looks like this question has been answered. If you have further input on the issue, don't hesitate to reopen this issue or post a new one.
