### ISSUE TITLE
`2.x` dispose() doesn't work if called on the object returned by doOnSubscribe()

### ISSUE THREAD

**Issue by kmalmur** [ReactiveX/RxJava#5299]
The following test doesn't work. Somehow `savedDisposable.dispose()` works different way comparing to `TestObserver.dispose()` 

	private Disposable savedDisposable;

	@Test
	public void test() {
		final TestObserver<Integer> observer = new TestObserver<>();

		Observable<Integer> t = Observable.just(10)
				.delay(100, TimeUnit.MILLISECONDS)
				.doOnSubscribe(disposable -> savedDisposable = disposable);

		t.subscribe(observer);

		savedDisposable.dispose();  //this doesn't work
		//observer.dispose();       //this works  

		assertTrue(observer.isDisposed());
	}

**Comment by akarnokd** [comment]
You are disposing in the middle thus the end `Disposable` can't know about its upstream has been disposed because `dispose()` calls always travel upstream.

**Comment by kmalmur** [comment]
@akarnokd since the subscribe() doesn't return disposable, how can I save the disposable so that to be able to dispose the whole stream?

**Comment by akarnokd** [comment]
See the [Wiki](https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0#subscriber).

There is the `DisposableObserver` and the `subscribeWith` method.

**Comment by kmalmur** [comment]
@akarnokd thanks. Two more questions:
- `subscribeWith` basically does the same thing as the `subscribe()` method. It only returns the input argument. What is the benefit of using it?
- `DisposableObserver` seems to be fine for my purpose. Is there any way I can something like `TestObserver` as a substitute for methods that expect `DisposableObserver` ?

**Comment by akarnokd** [comment]
> subscribeWith basically does the same thing as the subscribe() method. It only returns the input argument. What is the benefit of using it?

The `subscribe()` signature was locked down by Reactive-Streams specification and by symmetry, in all of the other classes. Also it enables you to do what you wanted...

> DisposableObserver seems to be fine for my purpose. Is there any way I can something like TestObserver as a substitute for methods that expect DisposableObserver ?

I don't understand, what features of `TestObserver` you are missing? It is up to you to process the events you receive through the `Observer` interface.

**Comment by kmalmur** [comment]
@akarnokd 
1. what I ment is that for my case using `subscribe()` will do basically the same thing as the `subscribeWith()` since I don't need the return value. 
2. `TestObserver` doesn't extend the `DisposableObserver` so if I have a method in production code that requires `DisposableObserver`, I cannot use the `TestObserver` as the substitution for tests. Anyway, I did manage to achieve a similar thing using generics. Instead of expecting `DisposableObserver` I'm expecting a generic type `<K extends Observer<R> & Disposable>`

Thanks

**Comment by akarnokd** [comment]
`subscribeWith` allows you to work with the instance you passed in without the need to introduce a local variable first in some cases:

```java
composite.add(source.subscribeWith(new TestObserver()));
```

1.x `subscribe` returned a `Subscription` and many Android folks used the pattern above. We added `subscribeWith` to ease on the transition.

> `<K extends Observer<R> & Disposable>`

Great!

**Comment by akarnokd** [comment]
Also on [StackOverflow](http://stackoverflow.com/questions/43513399/rxjava2-dispose-doesnt-work-if-called-on-the-object-returned-by-doonsubscribe).
