### ISSUE TITLE
Interval: Immediately emit 0?

### ISSUE THREAD

**Issue by samuelgruetter** [ReactiveX/RxJava#530]
Before it's too late, I'd like to discuss the following question: When should `Observable.interval(t)` emit its first element (which is 0): 
a) right after the observer subscribed, or
b) only after a delay of `t`?

Currently, we have b), but I'd vote for a), because I've seen many people stumble over this. I think it makes more sense if after `n*t` time, it emits `n`.
Or a third possiblilty:
c) start with 1, and emit it after a delay of `t`

**Comment by FireZenk** [comment]
```java 
Observable.timer(0, 100, TimeUnit.MILLISECONDS)
```
is deprecated but now you can use

```java 
Observable.interval(0, 100, TimeUnit.MILLISECONDS)
```
