### ISSUE TITLE
2.x TestObserver#assertAlways TestObserver#assertAtLeast

### ISSUE THREAD

**Issue by I60R** [ReactiveX/RxJava#5305]
Emulating first with negated value of assertNever makes tests not fluent.
Second don't exists.

Can make PR

**Comment by akarnokd** [comment]
What is their definition and how should they work?

**Comment by I60R** [comment]
```Observable.just(true, true, true ).test().assertAlways(b -> b)``` don't throw AssertionError
```Observable.just(true, true, false).test().assertAtLeast(2, b -> b)``` don't throw AssertionError 
```Observable.just(true, true, false).test().assertAtLeast(3, b -> b)``` throws AssertionError

**Comment by akarnokd** [comment]
Why do you need such assertions? This works:

```java
Observable.just(true, true, true)
    .test()
    .assertNever(b -> !b)
    .assertCount(3)
    .assertComplete();
```

The rest sounds like you have a particular source where its enough some values pass the test which is quite uncommon.

**Comment by I60R** [comment]
It's easier to think about 
```java
    source.assertAlways(o -> o.checkSomething())
          .assertNever(o -> o.checkOther());
```
instead of
```java
    source.assertNever(o -> !o.checkSomething())
          .assertNever(o -> o.checkOther());
```
Also it displays other error message than ```assertNever```.

-----
Second can be useful on need to ensure that event(s) of some type was received and don't break the chain.
```java
    source.assertAtLeast(1, o -> (o instanceof DesiredEvent))
        .assertAtLeast(1, o -> (o.isOtherEvent());
```

I want to describe Android's Activity lifecycle using that operator (i.e. one OnDestroy per sequence)

**Comment by I60R** [comment]
Sorry if I just waste your time
