### ISSUE TITLE
Confusing about request() method in a custom Flowable

### ISSUE THREAD

**Issue by Joseph82** [ReactiveX/RxJava#5311]
Let's say I create a custom `Flowable`:

```
public final class CustomFlowable extends Flowable<Integer> {

    @Override
    protected void subscribeActual(Subscriber subscriber) {
        Listener listener = new Listener(subscriber);
        subscriber.onSubscribe(listener);
    }

    static final class Listener implements Subscription {
        private final Subscriber<Integer> subscriber;


        Listener(Subscriber<Integer> subscriber) {
            this.subscriber = subscriber;
        }

       public void onSensorChanged(SensorEvent event) {
            subscriber.onNext(event));
        }

        @Override
        public void request(long n) {
            // how to deal with this method?
        }

        @Override
        public void cancel() {
        }
    }
}
```

I have no clue about how to implement the `request(long n)` method in order to handle gracefully the backpressure. 
My guess it is that when the `request()` method is called, I should send a number of items equals to `n` . But, should I stop in the meantime the normal stream of data coming from external source ( sensors)?
Do I have a way for accessing the items in the queue and call a sequence of `onNext()` for those items?

**Comment by akarnokd** [comment]
There is rarely any reason to implement custom Flowables. Why do you want it? Based on the naming, you should be using `Flowable.create()` instead.

**Comment by Joseph82** [comment]
With `Flowable.create()` I have to define a `BackpressureStrategy` (as second parameter). 

What if I want to let the user to define a different backpressure strategy?

**Comment by akarnokd** [comment]
There is the `BackpressureStrategy.MISSING` and the requirement that the consumer applies one of the `onBackpressureX` operators.

**Comment by Joseph82** [comment]
Ok. I wasn't sure about the meaning of `MISSING`. 

I'll try to switch to a Flowable created with `Flowable.create()`.

Thank you.

**Comment by akarnokd** [comment]
Looks like this question has been answered. If you have further input on the issue, don't hesitate to reopen this issue or post a new one.
