### ISSUE TITLE
Disposable state in onComplete

### ISSUE THREAD

**Issue by qwert2603** [ReactiveX/RxJava#5312]
Hello! Version of RxJava is 2.0.9.
In my app I use ```Disposable```'s state to determine if some work is done or still running.
I noticed, that in ```onComplete``` callback ```Single```'s ```Disposable``` returns ```true``` from isDisposed while ```Completable```'s ```Disposable``` returns ```false```.

Does it correct? Or I should not rely on ```Disposable``` state in ```onComplete``` callback?

Code sample:
```
import io.reactivex.Completable
import io.reactivex.Single
import io.reactivex.disposables.Disposable
import io.reactivex.schedulers.Schedulers

fun main(args: Array<String>) {

    var sin_disposable: Disposable? = null
    sin_disposable = Single.just(34)
            .subscribeOn(Schedulers.computation())
            .observeOn(Schedulers.io())
            .subscribe { _, _ ->
                println("sin 1 ${sin_disposable?.isDisposed}")
            }
    println("sin 2 ${sin_disposable?.isDisposed}")

    var сom_disposable: Disposable? = null
    сom_disposable = Completable.complete()
            .subscribeOn(Schedulers.computation())
            .observeOn(Schedulers.io())
            .subscribe({
                println("сom 1 ${сom_disposable?.isDisposed} completed")
            }, { e ->
                println("сom 1 ${сom_disposable?.isDisposed} error $e")
            })
    println("сom 2 ${сom_disposable?.isDisposed}")

    Thread.sleep(1000)
    println("sin 3 ${sin_disposable?.isDisposed}")
    println("сom 3 ${сom_disposable?.isDisposed}")

}
```

Output is:
```
sin 2 false
sin 1 true
сom 2 false
сom 1 false completed
sin 3 true
сom 3 true
```

**Comment by akarnokd** [comment]
Relying on such external `isDisposed` is not recommended and is considered a non-reactive thinking. The Completable.subscribe() sets the disposed state after the callback, probably because some test wants to call dispose that propagates upstream.

**Comment by qwert2603** [comment]
Thanks for reply. I'll rethink some things in my app to avoid relying on ```isDisposed```.
