### ISSUE TITLE
RxAndroid 2.x.x compiler error with RxJava2 when using AndroidSchedulers.mainThread()

### ISSUE THREAD

**Issue by dkotin-cs** [ReactiveX/RxJava#5313]
I just updated my rxjava libraries to RxJava2 and noticed that the type of AndroidSchedulers.mainThread is now different and cannot be used with Observable.observeOn(...) as that method expects type rx.Scheduler. I did a quick search and didn't see any open issues related to the topic. Known issue?

To test, try `Observable.observeOn(AndroidSchedulers.mainThread()) `with:

RxAndroid: 2.0.1
RxJava: 2.0.9
RxKotlin: 2.0.0

**Comment by dkotin-cs** [comment]
Just found this which seems to address the issue: https://github.com/ReactiveX/RxAndroid/issues/348. Closing!

**Comment by akarnokd** [comment]
http://stackoverflow.com/a/43565795/61158

**Comment by dkotin-cs** [comment]
Thanks. For anyone who stumbles upon this in the future, my issue was not switching retrofit2 to the rxjava2 adapter [ `com.squareup.retrofit2:adapter-rxjava2` ]

**Comment by PangMing** [comment]
this solve my problem   `compile 'com.netflix.rxjava:rxjava-android:0.17.0'`

**Comment by FrancisRR** [comment]
**import io.reactivex.Observable**

interface RepoApi {
   @GET(ApiConstant.LOCATIONURL)
    fun getAddress1(): Observable<ResponseE>

}

**import io.reactivex.android.schedulers.AndroidSchedulers
import io.reactivex.schedulers.Schedulers**

  fun getValue1() {
        var re = repoApi?.getAddress1()
            ?.subscribeOn(Schedulers.io())
            ?.observeOn(AndroidSchedulers.mainThread())
            ?.subscribe { it }
   }
please  import correct package .
