### ISSUE TITLE
Documentation: Observable.singleElement() states wrong Maybe contract

### ISSUE THREAD

**Issue by realdadfish** [ReactiveX/RxJava#5317]
The javadoc of `Observable.singleElement()` says:

```
* Returns a Maybe that emits the single item emitted by this Observable if this Observable
* emits only a single item, otherwise if this Observable emits more than one item or no items, an
* {@code IllegalArgumentException} or {@code NoSuchElementException} is signalled respectively.
```

This is not the contract of `Maybe` and also not what the `ObservableSingleMaybe` operator implements. It _will_ complete if there is no value, return a single value and error out if there is more than one value.

Version: 2.0.7

**Comment by akarnokd** [comment]
Do you mean the doc doesn't explicitly mention that if the Observable is empty, the Maybe completes?

**Comment by jschoedt** [comment]
I also got confused about this. It states :

> or **no items**, an {@code IllegalArgumentException} or {@code NoSuchElementException} is signalled respectively.

A Maybe should return **no items** without any exception.

**Comment by akarnokd** [comment]
PR welcome but the actual behavior regarding the exceptions should be verified.

**Comment by jschoedt** [comment]
Agree... one could otherwise use .singleOrError() which is documented to have the same semantics.

**Comment by akarnokd** [comment]
Closing via #5668.
