### ISSUE TITLE
Replay-like operator which caches items only when no one observes

### ISSUE THREAD

**Issue by stanmots** [ReactiveX/RxJava#5334]
I'm wondering whether there is an operator with such behavior (or maybe it was considered at some point):

1. When there are some observers it should behave exactly like `PublishSubject`, namely, it should emit only the new items to all the observers
2. When the last observer unsubscribes it should start caching all new items which are emitted by the source `Observable`.
3. Upon a new subscription it should emit all the cached items, clear buffer, and then restore the behavior described in step 1.

Use case: 

On Android we can save `Observable` in the retained `Fragment`. When a configuration change occurs (e.g. device rotation) we must unsubscribe from it to prevent memory leaks. At the same time an asynchronous operations should not be stopped. With such setup there can be a situation when the items are emitted during `Activity` reconstruction. 

Currently I'm using a combination of `replay` + `autoConnect` to guarantee that no items will be lost. What I don't like in this approach is that `replay` always emits all the items even when I need only the items which were emitted upon a configuration change (when no one was subscribed). 

Maybe I missed something and there is already such operation or combination of operations I can use to achieve the discussed behavior. Thank you in advance for your reply.

**Comment by akarnokd** [comment]
For 1.x, there is no standard operator that behaves like you described. For 2.x, there is the [valve](https://github.com/akarnokd/RxJava2Extensions#flowabletransflormersvalve) extension operator that let's you pause and resume a stream but it is bounded.

**Comment by stanmots** [comment]
Thanks, the `valve` operator looks interesting. I'll try to play with it. I'm just a little bit confused after checking its [docs](https://github.com/akarnokd/RxJava2Extensions/blob/e3135211e46817abe09411c12be4817a60cd77f4/src/main/java/hu/akarnokd/rxjava2/operators/FlowableTransformers.java#L115). It is stated that this operator
> starts with the specivied valve state and the specified buffer size hint

If the given size is just a hint what will be used as the actual buffer size? Will it grow dynamically as the new items are being emitted until there is available memory?

**Comment by akarnokd** [comment]
Okay, I checked the code. It uses an unbounded buffer and otherwise doesn't interfere with the request amount, thus if the downstream requests a larger amount and the valve gets closed, the internal buffer will grow to accomodate all values. The hint just tells how large each island inside that internal buffer should be as a tradeoff between allocation rate and memory usage.

**Comment by stanmots** [comment]
Thank you, I'm closing this issue. If I'll have problems with `valve` operator it seems RxJava2Extensions repo is a more appropriate place to discuss it.
