### ISSUE TITLE
2.x: withLatestFrom() doesn't return the latest value

### ISSUE THREAD

**Issue by arazabishov** [ReactiveX/RxJava#5342]
Version of RxJava - `2.1.0`. Here is an example which involves use of `PublishSubject`:

```
// Subject is used to communicate changes in the model
PublishSubject modelSubject = PublishSubject.create();
modelSubject.subscribe(model -> {
    editText.setText(model.value());   // this will cause a new event in the stream below
});

// Observing changes in the form
RxTextView.afterTextChangeEvents(editText)
     .takeUntil(RxView.detaches(parent))
     .filter(event -> event.editable() != null)
     .withLatestFrom(modelSubject, (event, model) -> {
          return Pair.create(event, model);
     })
     .filter(pair -> {
         return !pair.val0().editable().toString()
             .equals(String.valueOf(pair.val1().value()));
         })
     .debounce(512, TimeUnit.MILLISECONDS)
     .map(pair -> RowAction.create(pair.val1().uid(),
            pair.val0().editable().toString()))
     .subscribe(processor::onNext, throwable -> {
            throw new OnErrorNotImplementedException(throwable);
      });
```

As you can see, `modelSubject` here can trigger events in the `RxTextView.afterTextChangeEvents(editText)` stream, meaning that consequent call to the `.withLatestFrom()` should return the value which caused the event in the stream. 

It is quite interesting that for the first event emitted by `RxTextView.afterTextChangeEvents(editText)`, `withLatestFrom()` captures correct model value. Let's say that we push second model through subject which triggers another event in `editText` observable. Instead of pulling newest model instance from `modelSubject`, `.withLatestFrom()` returns an old value which is not relevant anymore.

**Comment by akarnokd** [comment]
There are two subscribers to the `modelSubject` of which the first one triggers a text event change synchronously before the second subscriber is notified, thus when the `withLatestFrom` is reached you'll have the old model. Swap the two `subscribe()` calls which should make sure `withLatestFrom` is notified first.

Alternatively, consider using `BehaviorSubject` and `map` by mapping in the `BehaviorSubject.getValue()` instead of `withLatestFrom`.

```java
BehaviorSubject modelSubject = BehaviorSubject.create();

 .map(event -> {
      return Pair.create(event, modelSubject.getValue());
 })
```

**Comment by arazabishov** [comment]
Thank you very much for pointing out the problem with synchronicity.
