### ISSUE TITLE
RxJava 2: Observable.concatWith variants for Single, Completable & Maybe.

### ISSUE THREAD

**Issue by vanniktech** [ReactiveX/RxJava#5350]
How do you guys feel about `concatWith` variants that take `Single`, `Completable` and `Maybe`. For now they could internally just use `toObservable()` and then maybe later receive custom implementations.

**Comment by vanniktech** [comment]
Another nice addition would be the `mergeWith()` as well. Given that this has received some upvotes would you consider adding those methods?

**Comment by akarnokd** [comment]
Use Kotlin?

**Comment by vanniktech** [comment]
I'm doing that right now however having custom implementations could improve performance since certain shortcuts can be taken. For instance knowing that Single can only emit once or error once unlike `Observable` / `Flowable` variants.

**Comment by vanniktech** [comment]
This can be closed now with #5845 & #5847
