### ISSUE TITLE
RxJava 1.x Event Bus with sticky events

### ISSUE THREAD

**Issue by sourabhv** [ReactiveX/RxJava#5360]
I am using an event bus, which was linked on Square's Otto library page

    public class RxBus<T> {
    
        private final Subject<T, T> bus = new SerializedSubject<>(PublishSubject.create());
    
        public void send(T object) {
            bus.onNext(object);
        }
    
        public Observable<T> toObservable() {
            return bus;
        }
    
    }

It was working well until I tried sending an event from Activity to Fragment (Android). It didn't work because the fragment wasn't created when I sent the event. Is there a way to add sticky events in RxBus, something like in GreenRobot's EventBus. Any ideas and hints about how I can do it would be great :)

**Comment by I60R** [comment]
You don't need event bus with RxJava. Try with BehaviorSubject or ReplaySubject instead

**Comment by sourabhv** [comment]
No, I didn't say I am using any event bus. In the code above, I am using `PublishSubject`. But I doubt ReplaySubject will serve the purpose, I don't want every event to be streamed to new subscribers. `BehaviorSubject` won't work either I think. ReplaySubject can work if there's a way to flush the whole subject after use. Is there a way to do it?

**Comment by I60R** [comment]
Yes, you can use `take(1)` operator. 

*P.S:* It's not good idea to use ReplaySubject, because all events will be stored in memory. BehaviorSubject stores only last

**Comment by akarnokd** [comment]
`UnicastSubject` let's you cache items until a single `Subscriber` subscribes to it and doesn't retain elements. Note, however, that it doesn't support multiple `Subscriber`s.

**Comment by akarnokd** [comment]
Looks like this question has been answered. If you have further input on the issue, don't hesitate to reopen this issue or post a new one.
