### ISSUE TITLE
Observable interval scheduling on Schedulers.trampoline cause a infinite loop

### ISSUE THREAD

**Issue by sopping** [ReactiveX/RxJava#5365]
This code cause a infinite loop when snippt-1 interval complete. 
```
        System.out.println("start");
        // snippt-1
        Observable.interval(1, TimeUnit.SECONDS, Schedulers.trampoline()).take(10)
                .subscribe(aLong -> System.out.println(aLong + "; " + Thread.currentThread().getName()), Throwable::printStackTrace,
                        () -> System.out.println("complete1."));
        // snippt-2
        Observable.interval(1, TimeUnit.SECONDS, Schedulers.trampoline()).take(10)
                .subscribe(aLong -> System.out.println(aLong + "; " + Thread.currentThread().getName()), Throwable::printStackTrace,
                        () -> System.out.println("complete2."));

        Thread.sleep(30000);
        System.out.println("end");
```

This code will be fine
```
        System.out.println("start");

        Observable.interval(1, TimeUnit.SECONDS).take(10).subscribeOn(Schedulers.trampoline())
                .subscribe(aLong -> System.out.println(aLong + "; " + Thread.currentThread().getName()), Throwable::printStackTrace,
                        () -> System.out.println("complete1."));

        Observable.interval(1, TimeUnit.SECONDS).take(10).subscribeOn(Schedulers.trampoline())
                .subscribe(aLong -> System.out.println(aLong + "; " + Thread.currentThread().getName()), Throwable::printStackTrace,
                        () -> System.out.println("complete2."));

        Thread.sleep(30000);
        System.out.println("end");
```
Is something wrong with me?

**Comment by akarnokd** [comment]
It is the effect of sleeping-blocking nature of the trampoline scheduler that when it enters a synchronous periodic loop, the parent stream simply won't get the control to cancel that loop.

The second set of cases work because using `subscribeOn` has no effect (and runs on the main thread anyway) as the `interval` itself executes on the computation thread afterwards.

**Comment by sopping** [comment]
The tampoline works when I use `1.x`. 
I want to execute some `interval` sequentially on current thread. Can I?

**Comment by akarnokd** [comment]
> The tampoline works when I use 1.x.

API changes and scheduler use has changed that exposes this issue.

> I want to execute some interval sequentially on current thread. Can I?

That is `Thread.sleep()` in a loop. Why do you want this?

I've posted a fix for this type of cases in #5367.

**Comment by sopping** [comment]
Is there some replaceable way to do the same thing now?
This code seems ok:
```
Observable.range(1, interval).subscribeOn(Schedulers.trampoline()).map(aLong -> {
            TimeUnit.SECONDS.sleep(1);
            return aLong;
        }).subscribe(aLong -> System.out.println(aLong + "; " + Thread.currentThread().getName()));
```

**Comment by akarnokd** [comment]
You don't try to stop that setup, plus the sleep is so small I guess the whole thing completes pretty quickly anyway.

Closing via #5367.
