### ISSUE TITLE
[2.x] Difference in error handling between Observer and LambdaObserver

### ISSUE THREAD

**Issue by saket** [ReactiveX/RxJava#5366]
I'm sorry if this is already documented before and I failed to find them. I'm trying to understand why a `LambdaObserver` handles errors in its `onNext()` block differently than how Observables handle `Observer`.

`LambdaObserver` catches all errors thrown in `onNext()` and propagates them to `onError()`:
https://github.com/ReactiveX/RxJava/blob/2.x/src/main/java/io/reactivex/internal/observers/LambdaObserver.java#L64

So for an Rx chain that uses individual actions in `subscribe()`, any errors thrown in `onNext()` are received in `onError()`L:

```java
Observable.just(1, 2, 3, 4, 5)
  .subscribe(integer -> {
    if (integer == 3) {
      throw new RuntimeException("Poop");
    }
    System.out.println(integer);
  }, error -> {
    error.printStackTrace();    // This gets called.
  });
```

However, when passing an `Observer` to `subscribe()`, any errors thrown in `onNext()` are re-thrown as `UndeliverableException`.

```java
Observable.just(1, 2, 3, 4, 5)
  .subscribe(new Observer<Integer>() {
    @Override
    public void onSubscribe(Disposable d) {
    }
    @Override
    public void onNext(Integer integer) {
      System.out.println(integer);
      if (integer == 3) {
        throw new RuntimeException("Poop");
      }
    }
    @Override
    public void onError(Throwable e) {
      e.printStackTrace();
    }
    @Override
    public void onComplete() {
      System.out.println("Completed");
    }
  });
```

I'm trying to understand why is there a difference here and which one is correct. Does RxJava2 recommend that any error thrown in `onNext()` gets rethrown?

**Comment by akarnokd** [comment]
The Reactive-Streams protocol forbids throwing from `onNext`, `onError` or `onComplete` and by symmetry we expect this from the standard consumer interfaces of RxJava 2. The `LambdaSubscriber` ensures this by catching any exception an user-provided lambda may throw and if possible, it relays to `onError`. Thus the lambdas can throw but the `Observer` methods can't and is considered a bug by the developer. There is a `safeSubscribe` method that tries to correct such mistakes by doing try-catch over the invocation of the standard `Observer` methods.

**Comment by saket** [comment]
Thanks for replying, David. So are you saying that instead of following the protocol strictly, `LambdaObserver` tries to be forgiving and relays the errors to `onError()`?

**Comment by akarnokd** [comment]
`LambdaObserver` enforces the protocol by doing try-catch for `Consumer`s and `Action` which are not part of the Reactive-Streams specification and by declaring `throws Throwable` in them indicates they allow exceptions - for user convenience.

**Comment by saket** [comment]
Got it.
