### ISSUE TITLE
Performance: RxJava 1x expensive reflection call on first use of computation scheduler

### ISSUE THREAD

**Issue by digitalbuddha** [ReactiveX/RxJava#5369]
Howdy! We are happily using RxJava 1.3.  In doing some performance testing of our startup time I noticed a slowdown the first time we call Scheduler.computation().  
The slowdown is due to a reflective call here:
```
 static Method findSetRemoveOnCancelPolicyMethod(ScheduledExecutorService executor) {
        // The reason for the loop is to avoid NoSuchMethodException being thrown on JDK 6
        // which is more costly than looping through ~70 methods.
        for (final Method method : executor.getClass().getMethods()) {
            if (method.getName().equals("setRemoveOnCancelPolicy")) {
                final Class<?>[] parameterTypes = method.getParameterTypes();

                if (parameterTypes.length == 1 && parameterTypes[0] == Boolean.TYPE) {
                    return method;
                }
            }
        }

        return null;
    }
```

Particularly ` executor.getClass().getMethods()` which on a new Android Phone (5in Pixel) 
we are seeing the call run for 130ms.  In our case this is 10% of our total app start time.  

 Proof: I can submit the trace file too
<img width="1401" alt="screen shot 2017-05-25 at 3 29 57 pm" src="https://cloud.githubusercontent.com/assets/4528092/26467082/221f03e6-415f-11e7-85a5-38aad4aef6e4.png">

**Comment by akarnokd** [comment]
See #3121 which is a fix for #3119 reported by ... you.

**Comment by digitalbuddha** [comment]
I'm not sure what was fixed if it is still coming up on traces...  The fix made it better but it still is a bit of an issue.

**Comment by akarnokd** [comment]
I don't think we can do much about that but you might be able to hide the initialization cost by going async in your app startup via a plain thread.

**Comment by digitalbuddha** [comment]
Thanks David will fix on our end.  Our issue was that we are instantiating our object graph through DI which eagerly loaded the schedulers. Lazy should fix it.
