### ISSUE TITLE
Flowable.switchIfEmpty interrupts thread

### ISSUE THREAD

**Issue by jozuasijsling** [ReactiveX/RxJava#5370]
Is it expected behavior that `switchIfEmpty` may interrupt its thread?

### Problem

Within a `switchIfEmpty` block, I'm using `Completable.blockingAwait(long, TimeUnit)` which throws an `InterruptedException` upon entry because the current thread's interrupt flag is raised.

### Analysis

I ran the debugger and stepped through this scenario. `SubscriptionArbiter.setSubscription` cancels the previous observable before switching to the next. Disposing the observable is done with a call to `ScheduledThreadPoolExecutor.ScheduledFutureTask.cancel(true)` which then interrupts the thread.

**Comment by akarnokd** [comment]
Please try with a newer version as the unnecessary self-interrupt behavior has been already fixed: [v2.0.8](https://github.com/ReactiveX/RxJava/releases/tag/v2.0.8) via PR #5207.

Also the test case you showed doesn't contain any Scheduler (or an alternate Observable in fact to switch to) thus unless some other test leaves the test thread in an interrupted state, this test should pass.

**Comment by jozuasijsling** [comment]
Confirmed! Does not occur with 2.1.0.

In hindsight the test case was rushed and oversimplified so I removed it. Thanks for the help!
