### ISSUE TITLE
What can RxJava do on the server side？

### ISSUE THREAD

**Issue by netyjq** [ReactiveX/RxJava#5371]
Thanks for using RxJava but before you post an issue, please consider the following points:

  - [ ] Please include the library version number, including the minor and patch version, in the issue text. In addition, if you'd include the major version in the title (such as `2.x`) that would be great.

  - [ ] If you think you found a bug, please include a code sample that reproduces the problem. Dumping a stacktrace is usually not enough for us.

  - [ ] RxJava has more than 150 operators, we recommend searching the [javadoc](http://reactivex.io/RxJava/2.x/javadoc/io/reactivex/Observable.html) for keywords of what you try to accomplish.

  - [ ] If you have a question/issue about a library/technology built on top of RxJava (such as Retrofit, RxNetty, etc.), please consider asking a question on StackOverflow first (then maybe on their issue list).

  - [ ] Questions like "how do I X with RxJava" are generally better suited for StackOverflow (where it may already have an answer).

  - [ ] Please avoid cross-posting questions on StackOverflow, this issue list, the Gitter room or the mailing list.

**Comment by akarnokd** [comment]
Don't ask what RxJava can do for you but ask what you can do for RxJava :)
