### ISSUE TITLE
A crash occur when a activity is destroyed if I call dispose.

### ISSUE THREAD

**Issue by PowerCool** [ReactiveX/RxJava#5373]
below rxjava version

```groovy
    compile 'io.reactivex.rxjava2:rxandroid:2.0.1'
    // Because RxAndroid releases are few and far between, it is recommended you also
    // explicitly depend on RxJava's latest version for bug fixes and new features.
    compile 'io.reactivex.rxjava2:rxjava:2.1.0'
```

why not called accept(@NonNull Throwable throwable)  method.

android crash my app.

example )
```java
class MyActivity extends Activity{

Disposable disposable;

protected void onCreate(@Nullable Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);
    Disposable disposable = Observable.create(
                new ObservableOnSubscribe<File>() {
                    @Override
                    public void subscribe(@NonNull ObservableEmitter<File> e) throws Exception {
                           // doing my work.
                            while(true){
                                e.onNext(pictureFile);
                                Thread.sleep(500);
                            }
                            e.onComplete();
                    }
                }
        )
        .subscribeOn(new NewThreadScheduler())
        .observeOn(AndroidSchedulers.mainThread())
        .subscribe(new Consumer<File>() {
                       @Override
                       public void accept(@NonNull File file) throws Exception {
                           logger.e("accept : " + isDestroy);
                       }
                   },
                new Consumer<Throwable>() {
                    @Override
                    public void accept(@NonNull Throwable throwable) throws Exception {
                        logger.e("accept");
                    }
                }
        );
        ;
}

public void onDestory(){
super.onDestory)();
disposable.dispose();
}

}
```

**Comment by oldergod** [comment]
How about you format your code https://help.github.com/articles/getting-started-with-writing-and-formatting-on-github/ and say what the error actually is?

**Comment by PowerCool** [comment]
what is my format code?

the crash log is below.

05-29 11:36:06.037 30205-30383/com.test W/System.err: io.reactivex.exceptions.UndeliverableException: java.lang.InterruptedException
05-29 11:36:06.038 30205-30383/com.test W/System.err:     at io.reactivex.plugins.RxJavaPlugins.onError(RxJavaPlugins.java:349)
05-29 11:36:06.038 30205-30383/com.test W/System.err:     at io.reactivex.internal.operators.observable.ObservableCreate$CreateEmitter.onError(ObservableCreate.java:83)
05-29 11:36:06.038 30205-30383/com.test W/System.err:     at io.reactivex.internal.operators.observable.ObservableCreate.subscribeActual(ObservableCreate.java:43)
05-29 11:36:06.038 30205-30383/com.test W/System.err:     at io.reactivex.Observable.subscribe(Observable.java:10842)
05-29 11:36:06.038 30205-30383/com.test W/System.err:     at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
05-29 11:36:06.038 30205-30383/com.test W/System.err:     at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:452)
05-29 11:36:06.038 30205-30383/com.test W/System.err:     at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:61)
05-29 11:36:06.038 30205-30383/com.test W/System.err:     at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:52)
05-29 11:36:06.039 30205-30383/com.test W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
05-29 11:36:06.039 30205-30383/com.test W/System.err:     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272)
05-29 11:36:06.039 30205-30383/com.test W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
05-29 11:36:06.039 30205-30383/com.test W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
05-29 11:36:06.039 30205-30383/com.test W/System.err:     at java.lang.Thread.run(Thread.java:761)
05-29 11:36:06.039 30205-30383/com.test W/System.err: Caused by: java.lang.InterruptedException
05-29 11:36:06.039 30205-30383/com.test W/System.err:     at java.lang.Thread.sleep(Native Method)
05-29 11:36:06.039 30205-30383/com.test W/System.err:     at java.lang.Thread.sleep(Thread.java:371)
05-29 11:36:06.039 30205-30383/com.test W/System.err:     at java.lang.Thread.sleep(Thread.java:313)
05-29 11:36:06.040 30205-30383/com.test W/System.err:     at com.test.ui.activity.main.fragment.PictureFragment$1.subscribe(PictureFragment.java:115)
05-29 11:36:06.040 30205-30383/com.test W/System.err:     at io.reactivex.internal.operators.observable.ObservableCreate.subscribeActual(ObservableCreate.java:40)

**Comment by akarnokd** [comment]
The sleep in your code is interrupted by the destruction of the Activity which doesn't allow the error to propagate through the regular channels. Use `try-catch` around the sleep to quit the loop in this case:

```java
while (!emitter.isDisposed()) {
    // ...
    try {
        Thread.sleep(500);
    } catch (InterruptedException ex) {
        return;
    }
}
```

**Comment by PowerCool** [comment]
Thx for akarnokd.

What kind of exception doesn't throw regular channel?

This information Where can I get?

**Comment by akarnokd** [comment]
A regular channel is calling `onError` but in your case that would also crash. You can read more about the error handling in the [wiki](https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0#error-handling).
