### ISSUE TITLE
Rx 2.x SingleMap should not allow null mapper?

### ISSUE THREAD

**Issue by kojilin** [ReactiveX/RxJava#5376]
RxJava 2.0.8

Found code like below can works
```
Single.just("1234").map(s -> null)
              .subscribe(s -> {
                  System.out.println(s);
              });
```

Because Single#just not allow null, so SingleMap should not allow it?
should like this? https://github.com/ReactiveX/RxJava/compare/2.x...kojilin:FIX-NPE?expand=1

**Comment by davidmoten** [comment]
Your PR looks good to me, I'd say submit it but remember to remove the "Thank you contributing..."  template from the description.

**Comment by akarnokd** [comment]
Closing via #5378
