### ISSUE TITLE
2.x Single.delay documentation and implementation inconsistent

### ISSUE THREAD

**Issue by mmallozzi** [ReactiveX/RxJava#5382]
The documentation for Single.delay says that success or error signals will be delayed by the specified amount, but in fact errors are not delayed, only successes. I have no opinion on which one should be correct - I ran into it when mocking out the response for an incomplete backend to test a loading/error UI, e.g. `Single.error(...).delay(3, TimeUnit.SECONDS)`, and found that my errors never had a delay. It seems that Observable has both options, with a version of the method that has a boolean flag `delayError`.

https://github.com/ReactiveX/RxJava/blob/2.x/src/main/java/io/reactivex/Single.java#L1636
https://github.com/ReactiveX/RxJava/blob/2.x/src/main/java/io/reactivex/internal/operators/single/SingleDelay.java#L66

**Comment by akarnokd** [comment]
Indeed there is no option for that in `Single` and `Maybe`. Would you like to submit a PR?

**Comment by mithunsasidharan** [comment]
@akarnokd : I've submitted my first PR fixing this -> https://github.com/ReactiveX/RxJava/pull/5409 Kindly review and advice. Thanks.

**Comment by akarnokd** [comment]
Closing via #5409.
