### ISSUE TITLE
RxJava 1.x Skip first item if it satisfies a condition 

### ISSUE THREAD

**Issue by sourabhv** [ReactiveX/RxJava#5384]
I'm looking for an operator that is like skip(int) but also has a condition and only skips the first item if if satisfies a condition (empty list in my case). If the item is not empty, continue normally, don't  try to skip any more items. 

Is there a way to do this with current operators?

**Comment by JakeWharton** [comment]
`upstream.publish(u -> merge(u.take(1).filter(i -> YOUR_CONDITION_HERE), u.skip(1)))`

**Comment by sourabhv** [comment]
Works great! Thanks!
