### ISSUE TITLE
RxJava 2: LambdaObserver.onNext() attempts propagate error to disposed observer

### ISSUE THREAD

**Issue by master-den** [ReactiveX/RxJava#5388]
Hi!
Version rxjava is 2.1.0.
May be error or dead code in method onNext of LambdaObserver:

    @Override
    public void onNext(T t) {
        if (!isDisposed()) {
            try {
                onNext.accept(t);
            } catch (Throwable e) {
                Exceptions.throwIfFatal(e);
                get().dispose();    <-- Observer is disposed
                onError(e);  <-- Here does attempt to propagate error, however onError() check state of observer and do nothing.
            }
        }
    }

**Comment by akarnokd** [comment]
I'm pretty sure there is a unit test that proves the contrary. `get().dispose()` disposes the this' content but the `isDisposed` uses `DisposableHelper.isDisposed` that essentially checks for the this' content for reference equality with `DisposableHelper.DISPOSED`.

**Comment by master-den** [comment]
Thanks for answer.
It inspired me to deep research our code. And I found in our code where a subscribtion was disposed rather by time that onError() will be invoked from LambdaObserver.onNext(). Thus, the problem of swallowed exception is in our architecture of app.

**Comment by akarnokd** [comment]
Looks like this question has been answered. If you have further input on the issue, don't hesitate to reopen this issue or post a new one.
