### ISSUE TITLE
Combine stream of SQLBrite and Retrofit

### ISSUE THREAD

**Issue by sourabhv** [ReactiveX/RxJava#5396]
I am looking for a way to combine the streams of SQLBrite and Retrofit with following constraints:

1. SQLBrite returns a 0 length list in case there was no database in DB, I want to skip this item, so the progress bar in my UI keeps showing while data is fetched from the server.
2. The data will be written in SQLite, triggering an SQLBrite update.
3. The SQLBrite stream should remain subscribed for any future database updates
4. I am planning to fetch only diff changes from server, in which case, the API will return less data than what there actually is, so only data from database should be passed on in the stream
5. If any error happens in any stream, it should also propagate down the stream.
6. If an error occurs, and there is data in DB, the data should be returned before onError is called.

What I am currently using:

```
public Observable<List<Items>> getItems() {
    Observable<List<Items>> server = restApi.getItems().
        .doOnNext(this::writeItemsToDb)
        .flatmap(this::getItemsFromDb)
        .delaySubscription(200, TimeUnit.MILLISECONDS);
    Observable<List<Items>> db = getItemsFromDb()
            .filter(items -> items != null && items.size() > 0)
            .doOnSubscribe(() -> server.subscribe(items -> { }, throwable -> { }));
    return Observable.amb(db, server);
}
```

The `amb` returns DB observable in every case except if there's an error or if there is nothing in the database. And when data is returned from DB, a server call is triggered in the background. I know it's not the prettiest and that's why I am here asking for help :)

PS: I couldn't use `concat` or `combineLatest` because SQLBrite stream never ends and combineLatest would return data on when server call completes, making the database kinda useless

**Comment by akarnokd** [comment]
Questions such as this are better asked on StackOverflow, especially due to involving other technologies.

**Comment by sourabhv** [comment]
I did but I didn't get any reply. So after searching a lot, I ended up asking it here. Maybe not the answer but hopefully someone can point me in the right direction

**Comment by akarnokd** [comment]
I personally don't know much about these technologies and not many others frequent around RxJava lately that might. You have the highest chance of getting an answer on StackOverflow.

https://stackoverflow.com/questions/41572091/refreshing-data-using-sqlbrite-retrofit
