### ISSUE TITLE
Fix HTTPS for the Javadoc

### ISSUE THREAD

**Issue by Coffee2CodeNL** [ReactiveX/RxJava#5399]
It appears the Javadocs for 2.x are not available over HTTPS, please fix this

**Comment by JakeWharton** [comment]
They're hosted on GitHub pages which doesn't easily support it. Why do you need HTTPS? Please don't enter your bank account information into the RxJava javadoc...

**Comment by akarnokd** [comment]
Unfortunately, this is beyond our control: https://github.com/isaacs/github/issues/156

**Comment by Coffee2CodeNL** [comment]
@JakeWharton because the GitHub pages enable HTTPS by default, linking to the RxJava2 Javadocs won't work because you can't load a HTTP resource in an IFrame on an HTTPS website, or at least, it appears so, it's being blocked by the browser.
