### ISSUE TITLE
combineLatest with Iterable  not work 

### ISSUE THREAD

**Issue by benlinx1018** [ReactiveX/RxJava#5402]
What I am currently using:
```
Observable.combineLatest(countsObslist,objects -> {
            Log.d("Rx","check");
            for (Object obj:objects) {
                if(((CharSequence)obj).length()>0){
                    return true;
                }
            }
            return false;
        }).subscribe(aBoolean -> RxView.enabled(btnOder).accept(aBoolean));
```
countsObslist is List<Observable<CharSequence>> type

this funtion can not run correctly.....

**Comment by akarnokd** [comment]
What exactly are you trying to achieve and what is it that doesn't work?

**Comment by benlinx1018** [comment]
I want to subscribe all edittext in  list view
if anyone has value,enable button

using follow code subscribe the edittext and add to list:

`  countsObslist.add(RxTextView.textChanges(viewHolder.edtTxtCount));`

**Comment by akarnokd** [comment]
`combineLatest` acts only if all sources have emitted an item. You have to start the sources with some default value to get it going:

```java
countsObslist.add(RxTextView.textChanges(viewHolder.edtTxtCount).startWith(""));
```

**Comment by benlinx1018** [comment]
Thanks, I see
