### ISSUE TITLE
Propose emit NoSuchElementException in SingleFromCallable on empty callable result

### ISSUE THREAD

**Issue by ultraon** [ReactiveX/RxJava#5404]
RxJava version: 2.1.0

I propose emit NoSuchElementException instead NPE in SingleFromCallable on empty callable result because it is more logically. For example class MaybeToSingle throws NoSuchElementException (not NPE).

**Comment by akarnokd** [comment]
It signals NPE because you are not supposed to return `null`. Null doesn't hold any semantic indication about whether it means emptiness or a bug. You can, however, design a wrapper that turns a null into NSE:

```java
public static <T> Callable<T> nullToNSE(Callable<T> call) {
    return () -> {
       T t = call.call();
       if (t == null) {
           throw new NoSuchElementException();
       }
       return t;
    };
}
```

**Comment by ultraon** [comment]
I agree with you after reading java.util.concurrent.Callable JavaDoc for call() method: Computes a result, or throws an exception if unable to do so.
