### ISSUE TITLE
Interval on a repetitive task & run an observable on a conditional

### ISSUE THREAD

**Issue by madd86** [ReactiveX/RxJava#5408]
Running with retrofit

This is my interface:

      @GET("solicitation/all")
      Observable<SolicitationResponse> getAll(@Query("X-Authorization") String apiKey);

This is where I run it:

        apiService.getAll(getResources().getString(R.string.api_key))
                .subscribeOn(Schedulers.io())
                .flatMapIterable(SolicitationResponse::getData)
                .observeOn(AndroidSchedulers.mainThread())
                .delay(5L, java.util.concurrent.TimeUnit.SECONDS) // THIS DOESN'T WORK LIKE I WANT IT TO..
                .repeat()
                .subscribe(s -> Log.e(TAG, "data: " + s.getName()));

****

# So, two questions:

**1)** How can I add a conditional to only run if we have internet connection?

This doesn't work:

    if (NetworkUtils.isConnected()) {
        //observable above here
    }

Why? Because the conditional code doesn't run itself endlessly, which means it will only check if we have internet connection once, ergo, it will crash if we lose it.

Is there any way to add a conditional before running the getAll method?

**2)** I need to add an interval before or after the task, by inserting `.delay` it will delay the subscription, which is not what I want or need. How can I accomplish it in this particular situation?

**Comment by akarnokd** [comment]
Please avoid cross posting (even if you are impatient). Thanks.

https://stackoverflow.com/questions/44490773/rxjava2-interval-on-a-repetitive-task-run-an-observable-on-a-conditional
