### ISSUE TITLE
combineLatest(Iterable<Publisher<>>, Function<>) not emitting on empty iterable 

### ISSUE THREAD

**Issue by Sroka** [ReactiveX/RxJava#5412]
I am using RxJava 2.10 and operator

io.reactivex.Flowable#combineLatest(java.lang.Iterable<? extends org.reactivestreams.Publisher<? extends T>>, io.reactivex.functions.Function<? super java.lang.Object[],? extends R>)

 but I've seen this behavior in 1.x as well. 

Overload of combineLatests (and combineLatestsDelayError) that takes Iterable of Publishers is not emitting any items and 'combiner' function passed to it is not called when iterable is empty. For this operator I would expect it to scale linearly, that is:

- If I pass Iterable of size 2 as a first argument I expect an Array of size 2 to be passed to combiner function
- If I pass Iterable of size 1 as a first argument I expect an Array of size 1 to be passed to combiner function
- If I pass Iterable of size 0 as a first argument I expect an Array of size 0 to be passed to combiner function

**Comment by akarnokd** [comment]
Wrong expectation. If you know you have zero sources, you are using the wrong operator to trigger actions. You can pick `just`, `map` it and actually ignore the input value. If you don't know you have zero sources, you still have the option to switch to a non-empty source via `switchIfEmpty`.

**Comment by Sroka** [comment]
@akarnokd Well, OK, makes sense. It took me quite a while to track this one down. Do you think it should be included in the docs? I can document it and make pull request

**Comment by akarnokd** [comment]
Yes, something along the line of this:

> Providing an empty array/Iterable will result in an immediate completion without any calls to the provided combiner function.

Note that there are several overloads to be considered in both `Flowable` and `Observable`.
