### ISSUE TITLE
(2.x) repeatWhen operator does not re-subscribe to source when func-parameter emits (before source completes)

### ISSUE THREAD

**Issue by valeriyo** [ReactiveX/RxJava#5414]
This test passes (RxJava 1.3):

```
package com.squareup;

import org.junit.Test;
import rx.observers.TestSubscriber;
import rx.subjects.BehaviorSubject;
import rx.subjects.PublishSubject;

public class RxJava1Test {
  @Test public void repeatWhen() {
    PublishSubject<Object> repeat = PublishSubject.create();
    TestSubscriber<Integer> output = TestSubscriber.create();
    BehaviorSubject.create(0).repeatWhen(a -> repeat).subscribe(output);
    output.assertValues(0);

    // Action!
    repeat.onNext(new Object());

    output.assertValues(0, 0);
  }
}

```

but fails with RxJava 2.1:

```
package com.squareup;

import io.reactivex.observers.TestObserver;
import io.reactivex.subjects.BehaviorSubject;
import io.reactivex.subjects.PublishSubject;
import org.junit.Test;

public class RxJava2Test {
  @Test public void repeatWhen() {
    PublishSubject<Object> repeat = PublishSubject.create();
    TestObserver<Integer> output = TestObserver.create();
    BehaviorSubject.createDefault(0).repeatWhen(a -> repeat).subscribe(output);
    output.assertValues(0);

    // Action!
    repeat.onNext(new Object());

    output.assertValues(0, 0);
  }
}
```

on the last line: `Expected: [0, 0], Actual: [0]`

It looks like 2.x `repeatWhen` operator now requires that the source observable terminates, before its Func-parameter emissions begin to matter.

This new 2.x behavior runs counter to Dan Lew's great explanation (http://blog.danlew.net/2016/01/25/rxjavas-repeatwhen-and-retrywhen-explained/) and in my view, it reduces the utility of the `repeatWhen` operator considerably.

**Comment by akarnokd** [comment]
> It looks like 2.x repeatWhen operator now requires that the source observable terminates

This is the correct behavior as it is supposed to repeat when the source terminates and reacts to the indicator signal, not in any other case.

> it reduces the utility of the repeatWhen operator considerably

You seem to misuse `repeatWhen` through this bug; you may want to use `switchMap` instead:

```java
PublishSubject signaller = PublishSubject.create();
BehaviorSubject data = BehaviorSubject.createDefault(0);

signaller.switchMap(v -> data).subscribe(...);

singaller.onNext(1);
```

**Comment by valeriyo** [comment]
@akarnokd excellent point, it looks like the bug was in 1.x. The `switchMap` works correctly for my use-case.. THANKS!

**Comment by akarnokd** [comment]
Great!
