### ISSUE TITLE
2.x defaultIfEmpty for Maybe

### ISSUE THREAD

**Issue by uzzu** [ReactiveX/RxJava#5417]
Hi. I'm glad that I started using 2.x and be able to use Maybe.
I started using it, and wanted to ask a question.

Now `Maybe#defaultIfEmpty` returns `Maybe`, but because this operator guarantees to emit data, I think should be `Maybe#defaultIfEmpty` returns `Single`.

I would like to know if there is a reason to return `Maybe`.

**Comment by akarnokd** [comment]
It was probably overlooked but we can't change the type now.

**Comment by vanniktech** [comment]
`defaultIfEmptySingle` that returns Single?

**Comment by akarnokd** [comment]
There is the `toSingle(T defaultValue)`.

**Comment by akarnokd** [comment]
Also `defaultIfEmpty` is based on `switchIfEmpty` thus it returns `Maybe`.

**Comment by uzzu** [comment]
OK. :+1:
I write unit tests and it seems that there is no problem with substituting `toSingle(T defaultValue)`, so I will use that.

[IMO] I think that `defaultIfEmpty` is more readable than `toSingle` , so I'd like to return `Single` in 3.x or future versions.

Thank you for answering my question 😄
