### ISSUE TITLE
Subscribe is not returning disposable when using repeat operator

### ISSUE THREAD

**Issue by vicpinm** [ReactiveX/RxJava#5420]
Hi, I'm using rxjava 2.1.0. I want to make a pooling to a server, so I'm using a repeat operator. But when I subscribe to the observable, it does not return a disposable. 

For example, if I do: 

 Disposable s = Observable.just(true).repeat().subscribe();
 int i = 0;

The second line i = 0 is never reached. I cant get a disposable reference after calling to subscribe(), in order to call to dispose() when I want to finish my pooling.

I'm not sure if this is a bug, or I dont understand the behaviour of the repeat operator. It is working fine, but I'm not able to finish the subscription when using the repeat operator.

**Comment by akarnokd** [comment]
You built a sequence that repeats a constant, immediate source indefinitely upon subscription on the current thread and thus you won't get the control back. You have to specify where the asynchronous execution should happen via `subscribeOn` in this case. Also such immediate repeats are not really recommended for pooling and instead you should consider using `interval()`.

**Comment by vicpinm** [comment]
You are right, is a thread-related issue. I have fixed it with a the subscribeOn operator, thanks a lot!

**Comment by akarnokd** [comment]
Looks like this question has been answered. If you have further input on the issue, don't hesitate to reopen this issue or post a new one.
