### ISSUE TITLE
java.lang.NoClassDefFoundError

### ISSUE THREAD

**Issue by daimonkor** [ReactiveX/RxJava#5428]
Hi, please help.
http://prntscr.com/flzchw
http://prntscr.com/flzcp3
http://prntscr.com/flzdgr
http://prntscr.com/flzf3l
http://prntscr.com/flzfcr
`compile` `'io.reactivex.rxjava2:rxjava:2.1.0'`
Debug
` java.lang.NoClassDefFoundError: Failed resolution of: $$Lambda$5;`
Thanks for support.

**Comment by akarnokd** [comment]
This is likely a project setup issue (i.e., multidex) and not many Android experts frequent these issue list. You may have better luck on Stackoverflow.

**Comment by daimonkor** [comment]
http://prntscr.com/fm12fd
http://prntscr.com/fm12k3
http://prntscr.com/fm12sr

multiDex activated.

**Comment by daimonkor** [comment]
I posted question
https://stackoverflow.com/questions/44663228/java-lang-noclassdeffounderror-rxjava-retrolambda

**Comment by akarnokd** [comment]
Closing via the [StackOverflow](https://stackoverflow.com/a/44665336/61158) answer.

**Comment by daimonkor** [comment]
Thanks for help.
