### ISSUE TITLE
2.x Filtered Single never completes

### ISSUE THREAD

**Issue by alexvasilkov** [ReactiveX/RxJava#5431]
RxJava v2.1.0

Next code:

``` Java
Single.just(true)
            .filter(val -> val)
            .subscribe(val -> Log.d("TEST", "SUCCESS"),
                    throwable -> Log.d("TEST", "ERROR"),
                    () -> Log.d("TEST", "COMPLETE"));
```

Only prints "SUCCESS" in logs but never "COMPLETE".

But since `filter` returns `Maybe` I expect complete action to be called.

**Comment by akarnokd** [comment]
`Single.filter` returns `Maybe` where the signal types [are exclusive](http://reactivex.io/RxJava/2.x/javadoc/io/reactivex/Maybe.html).

**Comment by alexvasilkov** [comment]
That's true, sorry for the rookie question, I was sure `Maybe` should always complete.
