### ISSUE TITLE
2.x Time bounded replaySubject getValue() unexpected behavior

### ISSUE THREAD

**Issue by nathankooij** [ReactiveX/RxJava#5433]
Affects 2.1.1.

The Javadoc for ReplaySubject::getValue states the following:
> Returns a single value the Subject currently has or null if no such value exists.

In combination with a time bounded replay subject I would expect `null` if either:
* there has not yet been an emission
* the emitted item's age is too old

Currently this is not the case as demonstrated by the following test: https://github.com/nathankooij/RxJava/commit/6afa40c0493bd90f012a91f2c20ce4cc2695826e
However, getValues() does return `null` (that is, old items are evicted), which is also demonstrated by the aforementioned test. To me it seems that either the implementation of `getValue/getValues` is inconsistent with each other, and the current behavior is not obvious to me from the documentation.

I've added what I think could be the fix in: https://github.com/nathankooij/RxJava/commit/bf1c1895f5fb66fdb38f1ad9d09212b3462a1ffd

**Comment by akarnokd** [comment]
Yes, it looks like an inconsistency. Do you want to post a PR? Please don't forget to verify/fix `ReplayProcessor` if possible.

**Comment by nathankooij** [comment]
Yes, will open a PR.

**Comment by akarnokd** [comment]
Closing via #5434.
