### ISSUE TITLE
[Feature request] A block until operator or buffer until operator

### ISSUE THREAD

**Issue by vRallev** [ReactiveX/RxJava#5438]
My use case is the following: I want to block a subscriber receiving events until another event occurred. Once the event occurred, I want to emit the old blocked events again. The buffer shouldn't grow indefinitely, too old events should eventually be dropped. 

My test code looks like this and it's also the closest I could get 
```java
Relay<Integer> relay = PublishRelay.<Integer>create().toSerialized();

Observable<Integer> share = relay.share();

Flowable<Integer> filter = share
        .filter(event -> event >= 3)
        .toFlowable(BackpressureStrategy.LATEST);

share
        .toFlowable(BackpressureStrategy.BUFFER)
        .onBackpressureBuffer(2, Functions.EMPTY_ACTION, BackpressureOverflowStrategy.DROP_OLDEST)
        .delaySubscription(filter)
        .subscribe(event -> System.out.println("" + event));

for (int i = 0; i < 10; i++) {
    relay.accept(i);
}
```
`delaySubscription` seemed to be the perfect candidate, but unfortunately it's not buffering any events, because the subscription didn't happen, yet. I'm basically looking for a `blockUntil` or `bufferUntil` operator similar to `skipUntil`. 

Is there an obvious solution to my use case that I missed?

**Comment by akarnokd** [comment]
Looks like you need `skipUntil` in place of `delaySubscription`.

**Comment by vRallev** [comment]
But that doesn't replay the skipped events. In this sample `1 2 3...` should be printed, because 1 and 2 should be buffered when the filter returns true.

**Comment by akarnokd** [comment]
Correction, you can use `concatEager`:

```java
Flowable.concatArrayEager(
    share.takeUntil(event -> event >= 3).ignoreElements().toFlowable(),
    share.toFlowable(BackpressureStategy.NONE)
       .onBackpressureBuffer(2, Functions.EMPTY_ACTION, BackpressureOverflowStrategy.DROP_OLDEST)
)
.subscribe(System.out::println);
```

**Comment by vRallev** [comment]
Hm, I've tried it, but it prints all events.

**Comment by vRallev** [comment]
Ah, I need to adjust the prefetch parameter.
```java
        Flowable
                .concatArrayEager(Integer.MAX_VALUE, 1,
                        share.takeUntil(event -> event >= 4).ignoreElements().toFlowable(),
                        share.toFlowable(BackpressureStrategy.MISSING).onBackpressureBuffer(2, Functions.EMPTY_ACTION, BackpressureOverflowStrategy.DROP_OLDEST)
                )
                .subscribe(event -> Log.d("Hello", "" + event));

        for (int i = 0; i < 10; i++) {
            relay.accept(i);
        }
```
I've adjusted the filter slightly. This prints `0 2 3 4 ...`. I would only expect `2 3 4 ...`. I don't know where the 0 is coming from. It seems to be tied to the prefetch parameter.

**Comment by akarnokd** [comment]
You could also use a rolling buffer that keeps the last few elements:

```java
int numPrevious = 2;
        
share.buffer(numPrevious, 1)
    .filter(b -> b.size() < numPrevious || b.get(numPrevious - 1) >= 3)
    .map(v -> v.get(0))
    .subscribe(System.out::println);
```

**Comment by akarnokd** [comment]
However, it requires `onComplete` otherwise the very last event is delayed by one onNext. The best would be to rethink the original emission pattern.

**Comment by vRallev** [comment]
That's not possible in the real use case, because there the buffer is bigger and the source never completes. I still like the idea of the custom operator. For now I'll keep my "cheat", that writes the filtered events from the original sample into a list, which are then emitted with a `startWith`. But it doesn't feel right.

Feel free to close the issue, if you think such an operator isn't needed.

**Comment by akarnokd** [comment]
Such operator is too peculiar for inclusion in RxJava. Maybe you can get tips from the [`valve()` extension operator](https://github.com/akarnokd/RxJava2Extensions/blob/master/src/main/java/hu/akarnokd/rxjava2/operators/FlowableValve.java) and [`onBackpressureBuffer`](https://github.com/ReactiveX/RxJava/blob/2.x/src/main/java/io/reactivex/internal/operators/flowable/FlowableOnBackpressureBufferStrategy.java).
