### ISSUE TITLE
Observable#concat(Observable,Observable) subscribed with an Observer has Disposable#isDisposed false after completion

### ISSUE THREAD

**Issue by vietj** [ReactiveX/RxJava#5439]
Thanks for using RxJava but before you post an issue, please consider the following points:

  - Please include the library version number, including the minor and patch version, in the issue text. In addition, if you'd include the major version in the title (such as `2.x`) that would be great.

2.1.1

  - If you think you found a bug, please include a code sample that reproduces the problem. Dumping a stacktrace is usually not enough for us.

```
  // Fail
  @Test
  public void testConcatWithObserver() {
    Observable<String> s = Observable.concat(Observable.just("abc"), Observable.just("def"));
    AtomicReference<Disposable> disposable = new AtomicReference<>();
    LinkedList<String> list = new LinkedList<>();
    AtomicBoolean completed = new AtomicBoolean();
    s.subscribe(new Observer<String>() {
      public void onSubscribe(Disposable d) { disposable.set(d); }
      public void onNext(String s) { list.add(s); }
      public void onError(Throwable e) {}
      public void onComplete() { completed.set(true); }
    });
    assertTrue(completed.get());
    assertEquals(Arrays.asList("abc", "def"), list);
    assertTrue(disposable.get().isDisposed());
  }

  // Pass
  @Test
  public void testConcatWithActions() {
    Observable<String> s = Observable.concat(Observable.just("abc"), Observable.just("def"));
    AtomicReference<Disposable> disposable = new AtomicReference<>();
    LinkedList<String> list = new LinkedList<>();
    AtomicBoolean completed = new AtomicBoolean();
    s.subscribe(list::add, err -> {}, () -> completed.set(true), disposable::set);
    assertTrue(completed.get());
    assertEquals(Arrays.asList("abc", "def"), list);
    assertTrue(disposable.get().isDisposed());
  }
```

**Comment by akarnokd** [comment]
Why do you want to rely on `isDisposed` externally to a sequence?

**Comment by vietj** [comment]
it is for testing `isDisposed` in the RxJava2 / Vert.x integration

**Comment by akarnokd** [comment]
You could call `disposable.set(Disposables.disposed())` in `onError` and `onComplete` or otherwise simply rely on `complete.get()`.

**Comment by vietj** [comment]
I don't understand what you mean.

I am merely reporting a difference of behavior where `disposable.get().isDisposed()` returns `false` for `testConcatWithObserver `and it seems to me that it should return `true` with this above reproducer.

If I replace the `Observable.concat(...)` by `Observable.just("foo")`, then `disposable.get().isDisposed()` will be `true` in both cases.

**Comment by akarnokd** [comment]
Closing via #5440.
