### ISSUE TITLE
2.x: Consumer contract is violated when using doOnEvent

### ISSUE THREAD

**Issue by ansman** [ReactiveX/RxJava#5442]
The following code showcases the problem:
```java
Completable.complete()
  .doOnEvent(t -> {})
```
`t` in this case is annotated with `@NonNull` but it will be `null` since the completable completes.

This is a real pain in Kotlin since the following code crashes in runtime:
```kotlin
Completable.complete()
  .doOnEvent {}
```

**Comment by sakuna63** [comment]
BiConsumer is also violated when using `Single#subscribe`. Either value or throwable will be null.

**Comment by akarnokd** [comment]
Removing the annotation from `Consumer` may affect all other places where it is not-null. Can you override the annotation somehow at the call site?

@sakuna63 [BiConsumer](https://github.com/ReactiveX/RxJava/blob/2.x/src/main/java/io/reactivex/functions/BiConsumer.java#L29) doesn't have the annotations.

**Comment by svenjacobs** [comment]
I just stumbled upon this while using Kotlin, too. However I wonder how a function argument annotated with `@NonNull` can ever be `null`? Even in Java this should be problematic as the contract is broken.

**Comment by akarnokd** [comment]
Maybe RxKotlin has/could have workarounds for these. /cc @thomasnield

**Comment by sakuna63** [comment]
Sorry, I read old source code. 
The annotations have already been removed at https://github.com/ReactiveX/RxJava/pull/5257

**Comment by svenjacobs** [comment]
This was introduced with #5023

**Comment by svenjacobs** [comment]
> Removing the annotation from Consumer may affect all other places where it is not-null. Can you override the annotation somehow at the call site?

@akarnokd If there's just one call that passes `null` to the function then *imho* the argument must be annotated with `@Nullable` and not `@NonNull`. What's the point of `@NonNull` when it can be `null`?

**Comment by ansman** [comment]
@akarnokd no, the problem cannot be remidied in kotlin which completely prevents the usage of that operator in kotlin. 
Removing the annotation won't make it nullable though, it would just mean that we don't know the nullability status which is the case too. Why is it important to keep it? I see very little harm in removing it and as @svenjacobs said the contract is broken in java too. If I were to null check it in java I would probably get lint warning telling me to remove the null check.
Ideally there should be multiple interfaces like @rharter suggested in the issue for BiFunction

**Comment by akarnokd** [comment]
If you can think you can resolve this with minimal changes, PR welcome.

**Comment by svenjacobs** [comment]
By the way this issue emerged with the release of Kotlin 1.1.3. Although `@NonNull` has already been added months ago it seems that the compiler/runtime library of Kotlin 1.1.3 became stricter in regards to nullability.

**Comment by ansman** [comment]
Ah, that explains why I just recently starting having problems.

**Comment by artem-zinnatullin** [comment]
Huh, I thought implementing `Consumer` interface manually with correct nullability will help:

```kotlin
Completable
        .fromCallable {  }
        .doOnEvent(object : Consumer<Throwable> {
            override fun accept(t: Throwable?) { // Error: 'accept' overrides nothing
                println("event: $t")
            }
        })
        .subscribe()
```

But Kotlin compiler (1.1.3-eap34) does not even let such code to compile, so there is probably no clear way to solve this in Kotlin without using Java code.

**Comment by dhruvj** [comment]
Is `doOnEvent` the only operator that needs a `Consumer` that accepts Nullable data? If so, why remove `@NonNull` which is fairly useful annotation for most of the other operators? Why not have a different, let's say, `Consumer2` specifically for doOnEvent and such operators?
