### ISSUE TITLE
Feature request: onBackpressureReduce

### ISSUE THREAD

**Issue by konmik** [ReactiveX/RxJava#5443]
It would be nice to have an operator like this.

    <R> Flowable<R> onBackpressureReduce(Callable<R> initialValueProvider, BiFunction<R, T, R> reducer)

Example:

I have a stream of items which should be animated sequentially, each item one after another. But once the pending amount of them hits 5 I want them to be added in a batch without animation.

Using the operator I would be able to write something like this:

    .onBackpressureReduce(emptyList(), (item, accumulatorList) -> add(accumulatorList, item))
    .flatMap(list -> list.size() > 5 ? just(list) : fromIterable(slice(list, 1)))
    .subscribe(this::animate);

Other backpressure operators can be re-implemented using `onBackpressureReduce`, because reducing is a quite general concept that fits into reducing backpressure events naturally.

**Comment by akarnokd** [comment]
This is too peculiar for RxJava and may be a better candidate for [rxjava2-extras](https://github.com/davidmoten/rxjava2-extras).

**Comment by konmik** [comment]
Reduction is the very basic way of dealing with state.

It should have been there from the draft of Rx-v1!

**Comment by akarnokd** [comment]
There exist a couple of extension operators that deal with backpressure and they are available in their respective libraries:

- [onBackpressureTimeout](https://github.com/akarnokd/RxJava2Extensions#flowabletransformersonbackpressuretimeout)
- [onBackpressureBufferToFile](https://github.com/davidmoten/rxjava2-extras#onbackpressurebuffertofile)

Both are too peculiar for RxJava proper but they happily live where they are now.

Consequently, this is a great opportunity for you to gain some operator writing skills and release it via your own library.

**Comment by akarnokd** [comment]
A similar operator, [coalesce()](https://github.com/akarnokd/RxJava2Extensions#flowabletransformerscoalesce) is available in the RxJava 2 Extensions project.
