### ISSUE TITLE
NPE when Flowable goes parallel `2.x`

### ISSUE THREAD

**Issue by lakemove** [ReactiveX/RxJava#5445]
Flowable throws NPE if goes parallel 
```
//throws NPE
Flowable.fromPublisher({
  it.onNext(1)
  it.onNext(2)
  it.onComplete()
}).parallel().sequential().subscribe({println(it)})
```
But if i use `range` instead of `fromPublisher` it will be fine 
```
Flowable.range(1,2).parallel().sequential().subscribe({println(it)})
```
Am i missing something ?

**Comment by akarnokd** [comment]
`fromPublisher` requires you to implement a Reactive-Streams `Publisher` correctly. Use `Flowable.create()` instead.
