### ISSUE TITLE
use GET @Path(value = "url", encoded = true)   but encoded not  take effect

### ISSUE THREAD

**Issue by mynamenoway** [ReactiveX/RxJava#5450]
gradle:
compile 'com.squareup.retrofit2:retrofit:2.3.0'
compile 'com.squareup.retrofit2:converter-gson:2.3.0'
compile 'com.squareup.retrofit2:adapter-rxjava:2.3.0'

**Comment by akarnokd** [comment]
Please ask such "questions" on StackOverflow.
