### ISSUE TITLE
About single.

### ISSUE THREAD

**Issue by yangwuan55** [ReactiveX/RxJava#5451]
To be honest,I don't know why there is a concept is “Single”.It's just a single data of observabe,but they are not the same kind of interface.

At rx1,I never use the single,observable is quite enough for me.
Now I want change the rx1 to rx2,I found the functions like "toList" return a "Single" instance,but I just want use observable to do something,I must change the single to observable,it's redundantly to do this,or single is redundantly for my code.

In the end,please tell me why produce the "Single" concept？

**Comment by yangwuan55** [comment]
I think the ObservableSource and SingleSource should has a same father.

and now I can do this : 

```

Observable.zip(observableOrSingle,xxx);

```

**Comment by akarnokd** [comment]
`Single` captures the fact of 1 element or error only in the type. Indeed it has a subset of capabilities of `Observable` but uses simpler internal state to represent a flow. You can always convert back to `Observable`/`Flowable` via `toObservable()`/`toFlowable()`. This distinction allows better reasoning about the flows by the developer and also allows certain flow optimizations.

The protocols are not the same: `Single` has `onSuccess` and `onError` while `Observable` has `onNext`, `onError` and `onComplete`. In addition, there are two problems: RxJava 2 is stable thus can't just change parameter- or return types or hierarchies; having the same base type can cause ambiguities in compilation.

**Comment by yangwuan55** [comment]
OK, thanks for answer!I will try to understand more.
