### ISSUE TITLE
The number of method references in a .dex file cannot exceed 64K after adding rx dependencies

### ISSUE THREAD

**Issue by lennonpetrick** [ReactiveX/RxJava#5452]
I had the error "The number of method references in a .dex file cannot exceed 64K" when I try to generate an apk. When I remove ReactiveX's dependencies, I have no error anymore.

I'm using the following dependencies:
`compile 'io.reactivex.rxjava2:rxjava:2.1.1'`
`compile 'io.reactivex.rxjava2:rxandroid:2.0.1'`

I know I need to use `multiDexEnabled=true` to solve this issue, but I don't want my app being multDex for now.

**Comment by JakeWharton** [comment]
You can enable ProGuard to remove unused methods and also to optimize method count by inlining small methods. This library ProGuard's fantastically.

**Comment by akarnokd** [comment]
Looks like this question has been answered. If you have further input on the issue, don't hesitate to reopen this issue or post a new one.
