### ISSUE TITLE
Problems caused by  rxjava version and rxAndroid version

### ISSUE THREAD

**Issue by ltigers** [ReactiveX/RxJava#5455]
RxJava2.1.0 does not execute onComplete when used in conjunction with RxAndroid2.0.1
When RxJava2.1.1 is used in conjunction with RxAndroid2.0.1, onComplete is executed
Why?

**Comment by akarnokd** [comment]
Unknown, also please provide context and unit test that demonstrates the flow that behaves unexpectedly.
