### ISSUE TITLE
Remove (or change wording) reference to "Akka Futures" which are gone since some years

### ISSUE THREAD

**Issue by ktoso** [ReactiveX/RxJava#5458]
Hi everyone,
I'd like to propose a small update to the wiki's `Home.md`, sadly it's not possible to PR to a Wiki as far as I know so opening this issue and linking the proposed change below.

Background: The section refers to "Akka Futures", which are not a thing anymore since a few years, since they have become incorporated into Scala itself ( http://docs.scala-lang.org/sips/completed/futures-promises.html ) years ago. So nowadays (from 2.3 onwards, which means since 4 years or so), there is no such thing as an "Akka Future" (that would be the "Scala Future", with no dependencies other than Scala itself, nowadays), so I wanted to remove the reference to "Akka Future" since it may be confusing / misleading to people researching / comparing libraries.

Hope the background makes sense :-)

The proposed change would just remove the refer: https://github.com/ktoso/rx-wiki/commit/f54c2fd348c0f0f1c3179694470cb5ec5171f458 though I'd be perfectly fine with some rewording. 

If you want to keep the explicit comparison we can work on a rewording I guess. It would be true to compare libraries and claim that e.g. Akka Streams (the closest thing to Rx in our libs) would indeed pull in the Actors library which some may not want to do.  Though then perhaps comparing to other libraries could be in place too perhaps growing this section too much... Just stating that it is lightweight with almost no dependencies is already a very cool thing to say and perhaps good enough for the Home.md, leaving other discussions to other files?

(branch: https://github.com/ktoso/rx-wiki/tree/wip-reference-to-outdated-akka )

What do you think @benjchristensen @akarnokd ?

**Comment by ktoso** [comment]
Forgot to ref to the page I'm talking about: https://github.com/ReactiveX/RxJava/wiki

**Comment by akarnokd** [comment]
Hi, I removed that sentence for simplicity. We'll see about comparisons with other libraries and designs when there is interest in reworking the wiki (I don't have time for it in the coming months).

**Comment by ktoso** [comment]
Sounds good and less stuff to debate then too :)
Thanks a lot, David :)
