### ISSUE TITLE
2.x: FlowableTimeoutTimed enhancement

### ISSUE THREAD

**Issue by davidmoten** [ReactiveX/RxJava#5461]
I'm debugging a production problem where a timeout did not fire so having a close look at `FlowableTimeoutTimed`. I notice in `TimeoutTimedSubscriber` that multiple terminal events can be emitted to the downstream subscriber in race between the scheduled timeout runnable and the `onError` and `onComplete` methods. The volatile `done` flag doesn't provide complete protection unless we turn it into an `AtomicBoolean` and use `compareAndSet`. 

The other thing I notice is that the `timer` field is accessed synchronously (only via `onSubscribe` and `onNext`) so rather than an `AtomicReference` can be a mutable field.

I can make PR if you think these are valid.

**Comment by davidmoten** [comment]
The `onNext` method would need protection as well.

**Comment by akarnokd** [comment]
See [FlowableTimeoutTimed:51](https://github.com/ReactiveX/RxJava/blob/2.x/src/main/java/io/reactivex/internal/operators/flowable/FlowableTimeoutTimed.java#L51).

**Comment by davidmoten** [comment]
Ah good, thanks. And the `timer` field doesn't need to be `AtomicReference`?

BTW prod problem was external API not defined properly so all good.

**Comment by akarnokd** [comment]
You mean [this](https://github.com/ReactiveX/RxJava/blob/2.x/src/main/java/io/reactivex/internal/operators/flowable/FlowableTimeoutTimed.java#L191) and [this](https://github.com/ReactiveX/RxJava/blob/2.x/src/main/java/io/reactivex/internal/operators/flowable/FlowableTimeoutTimed.java#L232)?

**Comment by davidmoten** [comment]
Yep

**Comment by akarnokd** [comment]
Yeah, doesn't really need AtomicReference in its current algorithm.

**Comment by davidmoten** [comment]
I'll fix

**Comment by akarnokd** [comment]
Btw, there is [a more modern algorithm](https://github.com/akarnokd/Reactive4.NET/blob/master/Reactive4.NET/operators/FlowableTimeout.cs) for this operator that doesn't need an additional layer of serialization.

**Comment by akarnokd** [comment]
Closing via #5466
