### ISSUE TITLE
Copyrights of marble diagrams

### ISSUE THREAD

**Issue by Chaoba** [ReactiveX/RxJava#5463]
@akarnokd I want to write a book about Rxjava in Chinese, I want to know if I could use the diagrams of Rxjava in my book? Thanks a lot.

**Comment by akarnokd** [comment]
The diagrams are Apache 2.0 too so you can reuse them in a book.

Related: #4158

**Comment by Chaoba** [comment]
Got it. Thank you very much.

**Comment by Chaoba** [comment]
@akarnokd Sorry to bother you again. I have almost completed my book and wonder if you could write a forward for my book? It will be my great honor if you could  help me. Let me introduce my book in brief.

**Comment by Chaoba** [comment]
@akarnokd Sorry to bother you again. I have almost completed my book and wonder if you could write a forward for my book? It will be my great honor if you could help me. Let me introduce my book in brief.

**Comment by Chaoba** [comment]
@akarnokd Sorry to bother you again. I have almost completed my book and wonder if you could write a forward for my book? It will be my great honor if you could help me. Let me introduce my book in brief.

Chapter 1 Introduce RxJava
Chapter 2 Combined with marble diagrams to introduce kinds of operators
Chapter 3 Introduce Schedulers
Chapter 4 Combiled with source codes to introduce the realization principle of some operators and Schedulers.
Chapter 5 Give some demos on how to solve practical problems and usage of RxLifecycle and RxBinding
Chapter 6 What's new on RxJava2

My email is qqliys@126.com. Look forward to hear from you.
Thanks a lot.

**Comment by akarnokd** [comment]
Hi. I'm afraid I don't have the literacy do that, sorry.
