### ISSUE TITLE
`doAfterSubscribe` operator?

### ISSUE THREAD

**Issue by wbinarytree** [ReactiveX/RxJava#5473]
So I came from this StackOverFlow thread [RxJava - .doAfterSubscribe()?](https://stackoverflow.com/questions/44836438/rxjava-doaftersubscribe). So that combination of `mergeWith()/startWith()` and `doOnComplete` works really fine but I think it's a bit too creative to come up with by myself. I think lots of us want this approche because we are trying/experimenting for this architecture by Jake Wharton in the talk of Devoxx here: [The State of Managing State with RxJava
](http://jakewharton.com/the-state-of-managing-state-with-rxjava/) . 
So I wonder why don't we have a build-in operator that can do this sort of work after your subscriber set up.
So it's like a part of Observable can survive  out side of the stream as a Subject. 
Thanks!

**Comment by akarnokd** [comment]
Operators have to be common enough, in-sequence and well defined to be considered including in RxJava proper. Sometimes, the context isn't well defined or the operator is supposed to support a small set of developers' thinking about solving a problem that can be solved through existing operators and composition (often requiring changing the viewpoint on the original problem as well).

RxJava is quite extendable through `compose` and you can write your own operator that intervenes in the lifecycle of a flow. For added convenience, you can consider using Kotlin where its extension methods even help you to make that custom operator appear to be an instance method on the reactive types of RxJava.

**Comment by wbinarytree** [comment]
Thanks. Another question. Is there a way rewrite something in `subscribeActual()`? Or I should extending Observable to make my own approche and use it inside my custom operator?

**Comment by akarnokd** [comment]
What do you mean by "rewrite something"? Extending an Observable gives you access to subscribeActual?

**Comment by wbinarytree** [comment]
Sorry My English is too bad.  I means like your combination of `startWith()` and `doOnComplete()`. I think maybe I could write it properly inside `subscribeActual()` that can be triggered at exactly the time that I want. Is there another besides extending an `Observable`?

**Comment by akarnokd** [comment]
Write an ObservableTransformer and call compose with it.
