### ISSUE TITLE
Suggest Maybe#toSingle in Maybe#defaultIfEmpty documentation

### ISSUE THREAD

**Issue by alexeyr** [ReactiveX/RxJava#5480]
Looking at http://reactivex.io/RxJava/2.x/javadoc/io/reactivex/Maybe.html#defaultIfEmpty%28T%29, I was surprised to find it didn't return `Single`. Searching in closed issues found the answer: https://github.com/ReactiveX/RxJava/issues/5417. Perhaps documentation could be improved by explicitly mentioning `toSingle` as an alternative?

**Comment by akarnokd** [comment]
PR welcome.

**Comment by akarnokd** [comment]
Closing via #5486.
