### ISSUE TITLE
1.x: Un-deprecate RxJavaPlugins.getInstance()

### ISSUE THREAD

**Issue by JakeWharton** [ReactiveX/RxJava#5483]
There is no replacement for the scheduler hooks which are registered via `RxJavaPlugins`. Because its `getInstance()` method is deprecated, though, it gives the appearance that this method should not be used.

It seems like the individual `register*` methods on the `RxJavaPlugins` class which have replacements in `RxJavaHooks` should be deprecated instead.

**Comment by akarnokd** [comment]
Do you mean like [RxJavaHooks.setOnComputationScheduler](http://reactivex.io/RxJava/1.x/javadoc/rx/plugins/RxJavaHooks.html#setOnComputationScheduler(rx.functions.Func1))

**Comment by JakeWharton** [comment]
Those are called for every invocation of `Schedulers.computation()` whereas I'm looking for something that's only called once, similar to 2.x's `setInitComputationSchedulerHandler`.

**Comment by akarnokd** [comment]
I see. Can't you just use `@SuppressWarnings("deprecation")` on some helper method or invocation?

**Comment by JakeWharton** [comment]
I publish a library that exposes a hook for use with this method so it's my
consumers that I'm worrying about, not me. When a new library tells me to
use a deprecated method that's a huge red flag to me, but in this case
there's no actual alternative.

It's weird to have something deprecated that has no replacement. I feel
like we should either add the 'init' versions to the hooks (like 2.x) or
only deprecate the part of the plugin that's been made redundant by the
hooks.

**Comment by akarnokd** [comment]
You mean [RxIdler](https://github.com/square/RxIdler#usage)? I guess `RxIdler.hooks()` is not much of use on itself so you could have a method `RxIdler.registerStandardHooks()` that doesn't expose the deprecated plugins class.

**Comment by JakeWharton** [comment]
Sure. And maybe that's a good approach.

I guess the question here is a bit more fundamental. There's functionality
in 1.x which was only partially replaced and yet the old system was
entirely deprecated. 2.x has a the "init" functions but 1.x does not. It
just seems the deprecation of the entirety of plugins was premature and it
should have been much more targeted. Or, otherwise, we should expose the
equivalent "init" function configuration option in 1.x.

**Comment by akarnokd** [comment]
The original RxJava 1.x plugin components initialized themselves at class initialization time, optionally from system properties defining what class should be instantiated, which is such a strong expectation from the class that it couldn't be changed and still remain compatible. The deprecation indicates that overriding via RxJavaPlugins is no longer the preferred way. Unless you want to prevent the initialization of the standard schedulers of v1, the RxJavaHooks' per invocation override should be reasonable alternative:

```java
Scheduler myScheduler = ...

RxJavaHooks.setOnComputationScheduler(original -> myScheduler);
```

You don't have to rewrap the original Scheduler all the time.

**Comment by JakeWharton** [comment]
In this case I want to wrap the built-in Schedulers which I can still do, albeit not lazily such as with the "init" hooks of 2.x. Is there a reason the init hooks didn't make it into 1.x?

**Comment by akarnokd** [comment]
I didn't want to change `RxJavaPlugins` due to possible conflicts with existing users and can't use `RxJavaHooks` because of the initialization cycle between the two classes that would happen between them.

**Comment by JakeWharton** [comment]
Makes sense. Thanks for the explanations.
