### ISSUE TITLE
1.x: Single.flatMapCompletable and Observable.flatMapCompletable have inconsistent signatures

### ISSUE THREAD

**Issue by nlebas** [ReactiveX/RxJava#5487]
Using 1.3.0, my understanding is that flatMapCompletable will never call onNext() since none of the flatMapped Completables will. 
I think the signature is correct in Single but not in Observable:
```
public class Single<T> {
[...]
    public final Completable flatMapCompletable(final Func1<? super T, ? extends Completable> func) {
```
```
public class Observable<T> {
[...]
    public final Observable<T> flatMapCompletable(Func1<? super T, ? extends Completable> mapper) {
```

**Comment by akarnokd** [comment]
The practice of returning a different reactive type from non-conversion `Observable` operators started out in 2.x and would be inconsistent in relation to the other operators in `Observable`. For `Single`, there was simply not much choice as there is no empty `Single`, hence `Completable`.

**Comment by nlebas** [comment]
I guess it's OK.
I'll have to wait until all my dependencies are ready for rxjava2, though.
