### ISSUE TITLE
Operators such as DistinctObserver & TakeObserver missing required memory barriers

### ISSUE THREAD

**Issue by AttwellBrian** [ReactiveX/RxJava#5489]
**Version**: RxJava: 2.1.0. Issue can be seen in latest source.
**Bug Report**
Consider the following boring RxChain. The "friendly string" is omitted on the IO thread and watched on the app's main thread. There is only one omission. So this Rx chain shouldn't contain any violations of the Observable contract.

```
// Execute this on the mainThread
Observable
    .just("a friendly example string")
    .observeOn(Schedulers.io())
    .take(1)
    .observeOn(AndroidSchedulers.mainThread())
    .subscribe(observer);
```

When this thread is executed, [ObservableTake](https://github.com/ReactiveX/RxJava/blob/d3455d0c9d57d522c31b5c25af83e8f2b8df12b6/src/main/java/io/reactivex/internal/operators/observable/ObservableTake.java)'s TakeObserver#ctor is executed on the main thread. But TakeObserver#onNext is executed on the IO thread. Given that TakeObserver#remaining is not volatile, it is possible that `TakeObserver#onNext` will never see the initialized value of TakeObserver#remaining. Instead it will see the value of zero. As a result the `observer` will never see an emission (in rare circumstances).

The `distinctUntilChanged` operator appears to have a similar issue. Except it contains a crash instead a missing emission. Other operators have this issue as well.

**Question**
This appears to be a widespread issue. Or am I misunderstanding something about java's memory model or the observable contract?

If I'm not misunderstanding, do you have thoughts on fixing this? How widespread are issues like this likely to be? How could you (or I) go about verifying we've fixed all issues?

**Comment by akarnokd** [comment]
Have you looked at observeOn? The answer is in there. Let me know if you still don't understand it.

**Comment by haiminh87** [comment]
I think the main question is that: inside ObservableTake and other operators, there are code that either intentionally or unintentionally NOT thread safe.

For example, in ObservableTake, field "remaining" is initialized in the constructor and modified in onNext (which might be a different thread) and not marked as volatile. According to the Java memory model, there is no "happens before" relationship in this case, so it's possible for onNext to see the uninitialized value of "remaining".

This is different from the threading issue of concurrent notifications which violates the Observable Contract described here: https://artemzin.com/blog/rxjava-thread-safety-of-operators-and-subjects/


If I understand correctly, observeOn was used to illustrate the point but it's not necessary to use observeOn in the example above. You just need the constructor ObservableTake and onNext to run on different threads.

**Comment by akarnokd** [comment]
If you know the Java Memory Model and the standard concurrency tools, you should have no trouble finding out why there is no such grand scale concurrency problem with RxJava. Except if you are unwilling to look at one of the thing that can prove it to you.

**Comment by haiminh87** [comment]
I'm not saying that there's a grand scale concurrency problem with RxJava. I'm just trying to clarify the question as I understand it.

**Comment by akarnokd** [comment]
I understood the questions and the preconceptions of the OP but I didn't want to "steal" the "aha" moment for discovering the answer for it by the OP himself, given that he already spent time poking around the internals of RxJava.

**Comment by AttwellBrian** [comment]
Sounds like there is no bug. So I'll close out this Issue :)

 But first, mind humoring me and telling me if my understanding is correct?

**Reason this is safe**
The `ObserveOnObserver#actual` field is final. This provides a recursive initialization guarantee for the `actual` field as well as all subfields including `TakeObserver#remaining`, even though `TakeObserver#remaining` is not final?

**Comment by akarnokd** [comment]
No, because you didn't look at all components of the picture. Whenever there is an asynchronous boundary, we have a `AtomicInteger.getAndIncrement()` which is a full barrier, releasing any writes it happened before, including the non-final constructor values. Since the first onNext value observed on the other thread happens after this barrier, the take() will see its remaining field properly initialized.

**Comment by AttwellBrian** [comment]
Thanks David.

**Comment by haiminh87** [comment]
Thanks for the explanation. What about the following scenario:

```
subject.subscribe(observable);
backgroundExecutor.execute(
   @Override
    public void run() {
        subject.onNext("Hello world");
    });
```

In this case, the constructor and onNext are called on 2 different threads. I don't think there's any Atomic involved in this chain and the subject still fulfills the Observable Contract.

**Comment by akarnokd** [comment]
Any respectable executor defines a happens-before relationship between what happened before the submission of the task and its execution. Usually there is an internal queue that is written in a volatile manner.

**Comment by haiminh87** [comment]
Thanks David. That makes sense.
