### ISSUE TITLE
One Observable, Multiple Subscribers - Repeat Data for all subscribers [2.x] 

### ISSUE THREAD

**Issue by RomanTcv** [ReactiveX/RxJava#5499]
I already create question on stackoverflow but nobody can't answer. 
[https://stackoverflow.com/questions/45173278/rxjava2-ormlite-one-observable-multiple-subscribers-repeat-data-for-all-su](url)

**Comment by akarnokd** [comment]
> Please avoid cross-posting questions on StackOverflow, this issue list, the Gitter room or the mailing list.

https://stackoverflow.com/questions/45173278/rxjava2-ormlite-one-observable-multiple-subscribers-repeat-data-for-all-su

**Comment by RomanTcv** [comment]
@akarnokd 
I created this question, but nobody can't answer.

**Comment by akarnokd** [comment]
You have to be patient on StackOverflow, 14 hours is not much time to get the resident knowledgeable persons find and understand your question.
