### ISSUE TITLE
Memory leak issue

### ISSUE THREAD

**Issue by BootsSiR** [ReactiveX/RxJava#5504]
Using v2.1.0

I have a regular java project where I'm using RxJava to process 'events' which come into the system via a TCP connection.  I have a Flowable which internally reads the packet data from the tcp socket, creates an Event instance and then emits it.  I have a subscriber which processes the events.  Everything works great for a while but I have a slow memory leak which eventually kills my process after a day or so.   I've done some profiling with YourKit and I'm seeing a large amount of retained objects tied to SpscLinkedArrayQueue and AtomicReferenceArray.  I've done a bit of digging and can't seem to find out how to solve my problem.  This is a fairly large codebase and I am not at liberty to share the code but I'm hoping someone may be able to point me in the right direction as to where I should focus?  Any suggestions?  Any assistance would be greatly appreciated.

Here's a screenshot of what I'm seeing in YourKit
![image](https://user-images.githubusercontent.com/350484/28385255-d268392a-6c9d-11e7-9552-e495d779292d.png)

**Comment by akarnokd** [comment]
Looks like you create items way faster than you consume it and the `Flowable.create` in buffering mode just keeps growing. If your network code is blocking, you could consider using `Flowable.generate` instead where each invocation of the function can be used for triggering the read from the socket.

It's unlikely we could help you much without code that reflects your use pattern, like a minimalist example that exhibits the same problem.

**Comment by BootsSiR** [comment]
@akarnokd I was thinking that was the case so I assign an incrementing id to Event before emitting.  I track the last emitted ID in the Flowable.create and also in the last step of my subscriber.  I have a timer that spits out the values every x seconds and I don't ever seem to fall behind.

I'll attempt to share some code.  Here is a chopped down version of how I am handling the socket data to generate the events from tcp data

```
public Flowable<Event> startTCPListenerNIO() {
        return Flowable.create(emitter -> {
            try {
                while (_running) {
                    // snip
                    // network code to read from socket and when enough data is there to create an event, it's emitted
                    Event newEvent = new Event(socketdata);
                    emitter.onNext(newEvent);
                }
            } catch (Exception e) {
                _log.error("TCP socket error", e);
            }
            emitter.onComplete();
        }, BackpressureStrategy.BUFFER);
    }
```

and then my subscription which processes the emitted events

```
        Flowable<List<EventProcessingModel>> eventFlowable = startTCPListenerNIO()
            .subscribeOn(Schedulers.newThread()) // generate the tcp events from a new thread
            .observeOn(Schedulers.from(_eventExecutor)); // EVENT THREAD POOL
            // several more doOnNext() calls here to process the events


        // our subscriber
        DisposableSubscriber subscriber = new DisposableSubscriber<List<EventProcessingModel>>() {
            @Override
            public void onNext(List<EventProcessingModel> eventProcessingModels) {
            }
            
            @Override
            public void onError(Throwable throwable) {
                _log.fatal("Error processing event", throwable);
                dispose();
            }
            
            @Override
            public void onComplete() {
                dispose();
            }
        };

        DisposableSubscriber<List<EventProcessingModel>> disposableSubscriber = eventFlowable.subscribeWith(subscriber);
        _disposables.add(disposableSubscriber);
```

and when the application is going to shutdown, I clear _disposables.

See any glaring mistakes?  Thank you for the prompt reply.

**Comment by akarnokd** [comment]
This looks like a pretty typical setup, but the speed difference may be relatively small enough to accumulate over time unnoticed at first. If you can debug your flow, let it run for a bit, then place a breakpoint in you loop with the `onNext` and drill down into the emitter, locating the SpscLinkedArrayQueue there and look at its consumerIndex and producerIndex fields. In well consumed queues, the difference between the two should be close to zero.

**Comment by BootsSiR** [comment]
@akarnokd thank you.  I'm going to check that next.  I can easily debug the process.

Know of any good documentation on the Flowable.generate method aside from the API docs?

**Comment by BootsSiR** [comment]
@akarnokd After 1.5h of uptime and ~19,700,000 events processed, I put a breakpoint on onNext and the indexes in the SpscLinkedArrayQueue are identical at 19907237.  I guess falling behind isn't the issue.  I'm going to continue to profile and see if I can get any more information.  You've been helpful!

**Comment by BootsSiR** [comment]
This did seem to be a case of things getting backed up under high load and the memory footprint growing.  Thanks for your help.
