### ISSUE TITLE
Request N was changed when I used subscribeOn.

### ISSUE THREAD

**Issue by lengxf** [ReactiveX/RxJava#5513]
compile 'io.reactivex.rxjava2:rxjava:2.1.2'

The fellow is How is I using the Flowable and  subscribeOn , I need request Long.MaxValue, but
  it Changed to 128.

![screenshot from 2017-07-24 16-14-15](https://user-images.githubusercontent.com/10055394/28514314-2fd4d256-701f-11e7-98a4-df20f8f3f594.png)

**Comment by lengxf** [comment]
The rxandroid version:
    compile 'io.reactivex.rxjava2:rxandroid:2.0.1'

**Comment by akarnokd** [comment]
`subscribeOn` doesn't manipulate request amount, `observeOn` does. Besides, request amounts depend on the subsequent operators and is not an end-to-end amount as some believe.

**Comment by akarnokd** [comment]
Also please avoid cross-posting: https://github.com/ReactiveX/RxAndroid/issues/384 !

**Comment by lengxf** [comment]
Yes , 
I realized it might be rxandroid operators issue , posted to rxandroid .   sorry about that.

**Comment by lengxf** [comment]
'observeOn(AndroidSchedulers.mainThread()'  maybe is not end-to-end.  
How can I deal to request more than 128 ?

**Comment by akarnokd** [comment]
You can increase the buffer size via the `observeOn(Scheduler scheduler, boolean delayError, int bufferSize)` overload, but why isn't 128 enough? The operator will keep requesting when it has successfully consumed most of the previously requested items.

**Comment by lengxf** [comment]
Thank for your response. 
I found The operator will keep requesting until emitter call onCompleted  , not just when it has successfully consumed all of the previously requested items.

**Comment by akarnokd** [comment]
Great!
