### ISSUE TITLE
Rx java does not emit error signal when an exception is thrown in the map operator

### ISSUE THREAD

**Issue by codefacts** [ReactiveX/RxJava#5520]
static void main(String[] as) {
        Observable
            .fromPublisher(s -> {
                s.onNext("ok");
                s.onComplete();
            })
            .flatMap(s -> Observable.defer(() -> Observable.just("ok22")))
            .map(s -> {
                throw new RuntimeException("Exception");
            })
            .doOnError(throwable -> System.out.println("Throwable == " + throwable))
            .toList()
            .subscribe(o -> {
            }, throwable -> System.out.println("throwable = " + throwable));
    }

It should print out the throwable. But the Observable is throwing NullPointerException instead and no error signal is propagated to any of the error handlers. I have tested it using RxJava2@2.0.8, RxJava2@2.1.1 and RxJava2@2.1.2 versions

**Comment by JakeWharton** [comment]
I think you want Observable.create(). You're not honoring the Publisher
contract in that lambda.
