### ISSUE TITLE
Migrating from RxJava 1.0 to RxJava 2.0  - Missing Subscriptions.from() method

### ISSUE THREAD

**Issue by ghost** [ReactiveX/RxJava#5525]
Hi, 

I'm already working on migrating to RxJava2 version 2.01.

Here's the code I want to rewrite:

```
 CompositeSubscription subscription = new CompositeSubscription();
 subscription.add(Subscriptions.from(
                presenter.getDataSuccess().subscribe(adapter),
                RxRecyclerView.scrollEvents(recyclerView)
                        .map(LoadMoreHelper.mapToNeedLoadMore(layoutManager, adapter))
                        .subscribe(presenter.loadMoreObserver())
        ));
```

This is what I've done already:

```
        CompositeDisposable composite = new CompositeDisposable();
        composite.add(Disposables.fromSubscription(
                mPresenter.getDataSuccess().subscribe(adapter),
                RxRecyclerView.scrollEvents(recyclerView)
                .map((Function<? super RecyclerViewScrollEvent, ? extends R>) LoadMoreHelper.mapToNeedLoadMore(layoutManager, adapter))
                .subscribe(mPresenter.loadMoreObserver())
                ));
```

Could anyone tell me what I am doing wrong with it?

**Comment by akarnokd** [comment]
> what I am doing wrong with it?

- Not verifying what types are involved in those method calls.
- Not reading the [wiki](https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0) about the related [changes](https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0#subscriber).

**Comment by ghost** [comment]
@akarnokd I read wiki about changes twice, but there so no information about Subscriptions class.
How can I replace it?

**Comment by akarnokd** [comment]
Depends on what `adapter` and `loadMoreObserver` is. If they are `Observer`s, you have to change them into `DisposableObserver`, use `Observable.subscribeWith()` and add each of them individually via `CompositeDisposable.add()`.

**Comment by ghost** [comment]
@akarnokd I changed a bit of code so last question:

I've created
` private final PublishSubject<Object> loadMoreSubject = PublishSubject.create();`

and then I'm getting it via:

`    @Nonnull
    public Observer<Object> getLoadMoreObserver() {
        return loadMoreSubject;
    }`

In **second class** I also have:
```
  @Nonnull
    private final PublishSubject<Object> loadMoreSubject = PublishSubject.create();
```

and then I try to get subscription:
`
        subscription = loadMoreSubject.subscribe(fixerDao.getLoadMoreObserver());`

This `subscription` would be added then to CompositeDisposable.


The question is how to make a `subscription` like you said Observable.subscribeWith(x instanceOf DisposableObserver)?

To make more clear, please check my repo: https://github.com/piotrek1543/fixer-android

**Comment by akarnokd** [comment]
Wrap and delegate to it:

```java
new DisposableObserver<Object>() {
    @Override public void onNext(Object t) {
        loadMoreSubject.onNext(t);
    }
    @Override public void onError(Throwable t) {
        loadMoreSubject.onError(t);
    }
    @Override public void onComplete() {
       loadMoreSubject.onComplete();
    } 
};
```

**Comment by ghost** [comment]
@akarnokd simple and effective. Thanks!
