### ISSUE TITLE
ParallelFlowable  concatMapDelayError emits items out of order

### ISSUE THREAD

**Issue by shakil807g** [ReactiveX/RxJava#5526]
here is my code  with  parallel operator 

```
disposable.add(RxFirebase.observeChildEvent(mDatabase.child(AppConstant.MESSAGES).child(myID_otherID))
                .filter(event -> event.getEventType() == RxFirebaseChildEvent.EventType.ADDED )
                .parallel().runOn(Schedulers.io())
                .concatMapDelayError(messageEvent-> {

                  
                  Message msg = messageEvent.getValue().getValue(Message.class);

                    if(msg.getType().equals(AppConstant.MSG_TYPE_VIDEO))
                    {

                       return Flowable.zip(Flowable.just(msg),AppDatabase.getInstance(getContext()).downloadDoa().getDownloadtem(msg.getVideo_url())
                            .defaultIfEmpty(new DownloadItem(null,null,null,null))
                            .toFlowable().observeOn(AndroidSchedulers.mainThread()),(message, downloadItem) -> {

                                message.setLocal_video_Path(downloadItem.local_path);
                                message.setStatus(downloadItem.status);
                                return message;

                        });

                    }else {
                        return Flowable.just(msg);
                    }

                },2,true)
                .sequential()
                .observeOn(AndroidSchedulers.mainThread())
                .subscribe(event -> {
                    if(event.getLocal_video_Path() != null)
                    Log.d(TAG, "setMessagesListener: "+event.getLocal_video_Path());

                    messagesAdapter.addItem(event);
                }, Throwable::printStackTrace));
```

it emit item out of order   but when i remove   .parallel().runOn(Schedulers.io())   and  .sequential()  and add subscribeOn(Schedular.io())  at zip operator  it emit item in order ???

**Comment by akarnokd** [comment]
If you go parallel, the source is dispatched to parallel, independent rails that can go on their own speed. If joined together with `sequential` the output order is indeterminate.

**Comment by shakil807g** [comment]
but then what is difference between using flatmap with ParallelFlowable and using contactMap ( which emit items in order)

**Comment by akarnokd** [comment]
`concatMap` keeps a relative order within a rail and `flatMap` doesn't as it by itself can run sources concurrently that can finish at any time.

**Comment by shakil807g** [comment]
ok but how can i go parallel and maintain order as well  ?? and does using contactMap without ParallelFlowable  will work in case of  1000 of message coming in from upper stream and i want to maintain order as well ??

**Comment by akarnokd** [comment]
Keeping a relative order between the sequential front and sequential back is not supported by RxJava's implementation. You have to manually pack the data and a monotonic index into a tuple, parallelize the flow and then use `sorted(Comparator)` to collect them back in order. However, when using `concatMap`, you have to unpack the data and then repack it with the original index. 

Without parallel, `concatMap`'s output will remain ordered, i.e., if given an input output mapping of  `a -> (1, 2)` and `b -> (3, 4)`, the operator's final output will be `1, 2, 3, 4` because `a` is processed fully before `b`.

**Comment by shakil807g** [comment]
ok thanks without parallel and having 1000 of events coming from upper stream will concatMap flood the system with threads

**Comment by akarnokd** [comment]
`concatMap` runs one source at a time and if you use `Schedulers.io()`, the number of threads created will be small.

**Comment by akarnokd** [comment]
Looks like this question has been answered. If you have further input on the issue, don't hesitate to reopen this issue or post a new one.
