### ISSUE TITLE
Would like you to reconsider issue 5356

### ISSUE THREAD

**Issue by marcosb** [ReactiveX/RxJava#5528]
Apologies, I don't seem to be able to reopen https://github.com/ReactiveX/RxJava/issues/5356 as I'm not a collaborator.

**Comment by akarnokd** [comment]
We are not going to change how RxJava operates. What you want points into the direction of Reactive RPC and/or bidirectional flows, which topic currently is not under significant research afaik. You can develop your own library/transformers that behave the particular way you think.
