### ISSUE TITLE
RxJava 2 and async subscriber

### ISSUE THREAD

**Issue by sergey-morenets** [ReactiveX/RxJava#5532]
Hi, I am using RxJava 2.1.2 and found recently sample code that worked in RxJava 1.x but seems to work differently in RxJava 2.
When I execute the code below I assume that each "subscribe" code will be run in new thread. However it is run in new but the same thread "RxNewThreadScheduler-1". I assume that Schedulers.io() should create a new thread per each long-running task. Please advice.

```java
public class SampleRx {
	public static void main(String[] args) throws Exception {
		Observable.fromArray("1", "2", "3")
			.observeOn(Schedulers.io())
			.subscribe(item -> { 
				System.out.println(
						Thread.currentThread().getName());
			Thread.sleep(2000); });
		Thread.sleep(7000);
	}
}
```

**Comment by akarnokd** [comment]
`Schedulers.io()` reuses threads so if there is a small delay after a flow terminates, the same thread will appear to serve the next flow. This behavior should be the same for both v1 and v2. Your sample code has one flow so it can't show any effects of multiple flows. Could you clarify it?

**Comment by sergey-morenets** [comment]
Hi @akarnokd 

Yes, it's strange but it seems to work the same way in 1.x.
Can you advise then how to to modify the original code so that each subscribe method will be invoked in the separate thread ?

**Comment by akarnokd** [comment]
There is the `Schedulers.newThread` for that.

**Comment by sergey-morenets** [comment]
Thank you, @akarnokd 

Do you mean this code? Unfortunately it still uses one thread "RxNewThreadScheduler-1"

```java
		Observable.fromArray("1", "2", "3")
			.observeOn(Schedulers.newThread())
			.subscribe(item -> { 
				System.out.println(
						Thread.currentThread().getName());
			Thread.sleep(2000); });
		Thread.sleep(7000);
```

**Comment by akarnokd** [comment]
It's unclear to me how do you expect multiple threads when subscribing once?

Try this:

```java
Observable<String> source = 
    Observable.fromArray("1", "2", "3")
    .observeOn(Schedulers.newThread());

source.subscribe(v -> System.out.println(Thread.currentThread().getName()));

source.subscribe(v -> System.out.println(Thread.currentThread().getName()));

Thread.sleep(10000);
```

or this:

```java
Observable.fromArray("1", "2", "3")
  .flatMap(v -> 
    Observable.just(v)
       .subscribeOn(Schedulers.newThread())
       .map(v -> Thread.currentThread().getName())
  )
  .subscribe(System.out::println);

Thread.sleep(10000);
```

**Comment by sergey-morenets** [comment]
Thank you, @akarnokd 

It works perfectly.
