### ISSUE TITLE
Bug in JavaDocs?

### ISSUE THREAD

**Issue by RobLewis** [ReactiveX/RxJava#5536]
The [description](http://reactivex.io/RxJava/2.x/javadoc/index.html?io/reactivex/Observable.html) of `FlowableSubscriber` says that its `onSubscribe()` method returns a `Subscription`. But version 2 doesn't have Subscriptions. Don't you mean `Disposable`?

**Comment by JakeWharton** [comment]
`Flowable` is a reactive streams type which uses `Subscription`.

**Comment by RobLewis** [comment]
Oh, right, because RxJava 2 is built on top of Reactive Streams, eh? I should have noticed that the supertype is `org.reactivestreams.Subscriber<T>`
