### ISSUE TITLE
2.x: Zip operator do not handle infinite cold observables

### ISSUE THREAD

**Issue by Phil4** [ReactiveX/RxJava#5539]
In RxJava 2.1.1, to always use the same events, I use the "repeat" operator. However, when I try to use it together with the Zip operator, I end up with an infinite loop at subscription instead of returning control when one of the zipped observables do not emit values anymore (even with bufferSize = 1):

```
final Observable<Integer> obs1 = Observable.just(1).repeat();
final PublishSubject<Integer> obs2 = PublishSubject.create();
final Observable<Integer> result = Observable.zip(obs2, obs1, (o1, o2) -> {
      return 1;
}, true, 1);
result.subscribe(e -> {});
obs2.onNext(2);
obs2.onNext(3);
```

**Comment by akarnokd** [comment]
Exactly. This is an expected behavior from a `Observable`s; they just keep emitting as fast as they can irrespective of the consumer's ability to handle it.

However, if you turn the example into `Flowable`s, everything starts working properly:

```java
final Flowable<Integer> flo1 = Flowable.just(1).repeat();
final FlowableProcessor<Integer> flo2 = PublishProcessor.create();
final Flowable<Integer> result = Flowable.zip(flo2, flo1, (o1, o2) -> {
      return 1;
}, true, 1);
result.subscribe(e -> {});
flo2.onNext(2);
flo2.onNext(3);
```

Welcome to RxJava 2.

**Comment by Phil4** [comment]
OK, thank you for this clarification. 
It seemed a little strange from a functional viewpoint because, in this case, Zip do not even emit a single value.

I have absolutely no back-pressure issue and have a synchronous flow so, reading [this section](https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0#which-type-to-use), I thought the right type to use was Observable. I completely skipped the first point about "_no more than 1000 elements_"...
