### ISSUE TITLE
Maybe.toSingle() - default value supplied via function

### ISSUE THREAD

**Issue by ZakTaccardi** [ReactiveX/RxJava#5543]
If I have a maybe, I can call `.toSingle(defaultValue)` which provides a default value if the maybe completes instead of emitting an onNext. However, that default value is provided immediately, rather than via a function that's lazily executed.

In Kotlin (`{}` denotes a function), I want an API like: 

```
.toSingle { /** function that is executed to provide a default value when maybe completes */  }
```

An analogy: I want the `Observable.fromCallable { }` version of `Observable.just()` here.

**Comment by JakeWharton** [comment]
You can use .switchIfEmpty to provide another Maybe that lazily looks up
its value. You get back a Maybe not a Single though.

**Comment by artem-zinnatullin** [comment]
Problem with overload is that then we'll also need overload with `Single` as default value, because sometimes function is not enough if you want to use rx chain to compute default value.

**Comment by akarnokd** [comment]
> In Kotlin [...] I want an API

The answer lies in your question/post.

**Comment by ZakTaccardi** [comment]
> Problem with overload is that then we'll also need overload with `Single` as default value, because sometimes function is not enough if you want to use rx chain to compute default value.

I'm not sure I follow this exactly, but the API requested here does not have to be exactly named `.toSingle`. For example, it could be `.toSingleCallable {}`.

Or do you mean that we would need another overload like `.toSingle(observableSource)` as well?

> The answer lies in your question.

I just referred to Kotlin because that was the language I used in my example. This feature request has nothing to do with Kotlin.

> You can use .switchIfEmpty to provide another Maybe that lazily looks up
its value. You get back a Maybe not a Single though.

This is a decent workaround. I still think it would be nice if there was something in the `.toSingle()` family that did this in one step, and avoided having to return an observable. It seems like a lot of other Rx APIs are like this though, like `.startWith(observableSource)` (there's no `.startWithCallable { }`)

**Comment by JakeWharton** [comment]
He was alluding to the fact that you can add an extension method for
Maybe<T>.toSingle(Single<T>)

**Comment by akarnokd** [comment]
RxJava is already crowded with convenience methods and for each new one, the added value vs. maintenance cost has to be considered so the project remains sustainable. Consequently, before asking for such additions, the following route should be exhausted first:

- have convinience (static/extension) methods in your project(s) locally,
- write a Transformer by composing or creating custom ops locally,
- create or contribute the previous two to an external library, or
- kindly ask for inclusion in RxJava proper.

**Comment by ZakTaccardi** [comment]
> He was alluding to the fact that you can add an extension method for Maybe<T>.toSingle(Single<T>)

> have convenience (static/extension) methods in your project(s) locally

> write a Transformer by composing or creating custom ops locally

Yeah, this can certainly be solved locally. Kotlin + composing operators makes this easy. Ex:

```
fun <T : Any> Maybe<T>.toSingle(defaultIfCompleted: () -> T): Single<T> {
    return this.switchIfEmpty(
            Maybe.fromCallable { defaultIfCompleted() }
    )
            .toSingle()
}
```

If you guys don't think it's worth the maintenance cost of bringing this functionality in RxJava proper, then feel free to close. Thanks!
