### ISSUE TITLE
RxJava2: how to wrap asynchronous api in RxJava2

### ISSUE THREAD

**Issue by suceser** [ReactiveX/RxJava#5547]
I need to use libraries that don’t support RxJava, but use the Listener pattern instead, how to wrap asynchronous api in RxJava2?

**Comment by JakeWharton** [comment]
`Observable.create`.

Please consider asking questions on StackOverflow or the mailing list instead of filing issues.

**Comment by akarnokd** [comment]
> RxJava has more than 150 operators, we recommend searching the [javadoc](http://reactivex.io/RxJava/2.x/javadoc/io/reactivex/Observable.html) for keywords of what you try to accomplish.

~

> Questions like "how do I X with RxJava" are generally better suited for StackOverflow (where it may already have an answer).

The [`create`](http://reactivex.io/RxJava/2.x/javadoc/io/reactivex/Observable.html#create(io.reactivex.ObservableOnSubscribe)) method has a nice example of just that.

**Comment by suceser** [comment]
Thanks
