### ISSUE TITLE
[2.x] Return first emitted result from list of observables or return error if empty

### ISSUE THREAD

**Issue by sourabhv** [ReactiveX/RxJava#5548]
Hey

I have a `List<Observable<?>>` and I want to get the first item emitted by any of these (running sequentially) or return error from last observable if all returned error or custom error if all were empty (which I can do with `.switchIfEmpty(Observable.error(RuntimeException()))`).

Currently, I have something like this:

    Observable.fromIterable(listOfObservables)
            .take(1)
            .switchIfEmpty(Observable.error(RuntimeException()))

This code handles getting only first emitted value and returning an error if all observables were empty but don't handle error case. Any ideas how I can solve that part?

**Comment by akarnokd** [comment]
If you don't read the welcome text of our issue list, why sould I think you'd read any answer?

> Questions like "how do I X with RxJava" are generally better suited for StackOverflow (where it may already have an answer)
