### ISSUE TITLE
retryWhen() method signature for Observable differs from other Rx types

### ISSUE THREAD

**Issue by jeremy303** [ReactiveX/RxJava#5549]
`Flowable`, `Single`, `Maybe` and `Completable` implementations of `retryWhen()` accept a `hander` parameter is typed that is typed `Function<? super Flowable<Throwable>, ? extends Publisher<?>>`.  `Observable.retryWhen()` uses a different type for `handler` which is not compatible with a handler written for the other types.

```
public final Single<T> retryWhen(
    Function<? super Flowable<Throwable>, ? extends Publisher<?>> handler)

public final Completable retryWhen(
    Function<? super Flowable<Throwable>, ? extends Publisher<?>> handler) 

public final Maybe<T> retryWhen(
    final Function<? super Flowable<Throwable>, ? extends Publisher<?>> handler)

public final Flowable<T> retryWhen(
    final Function<? super Flowable<Throwable>, ? extends Publisher<?>> handler)
```
 versus

```
public final Observable<T> retryWhen(
    final Function<? super Observable<Throwable>, ? extends ObservableSource<?>> handler)
```

It seems instead that this should be:

```
public final Observable<T> retryWhen(
    final Function<? super Flowable<Throwable>, ? extends Publisher<?>> handler)
```

**Comment by akarnokd** [comment]
Observable driven by Observable, Flowable by Flowable, and the rest had options for both. In v3 the 0-1 types run with Observable as they are in different subproject from Flowable.
