### ISSUE TITLE
2.1.2 Completable with andThen never completes

### ISSUE THREAD

**Issue by micHar** [ReactiveX/RxJava#5551]
**This test fails**:

    Completable.complete()
            .andThen{ Completable.complete() }
            .test()
            .assertComplete()

However this one succeeds:

    Completable.complete()
            .test()
            .assertComplete()

This one also succeeds:

        Flowable.just("")
                .flatMap { Flowable.just("") }
                .test()
                .assertComplete()

My understanding is that concating (which is what andThen does?) two completables which complete immediately should complete. 
I tried:
- using `awaitForTerminalEvent` but it just runs forever in the first case.
- `.andThen{}` instead of `.andThen{ Completable.complete() }`
- `Completable.fromCallable` instead of `Completable.complete()` or switching from a `Flowable` to `Completable`

**Comment by JakeWharton** [comment]
You want andThen(Completable.complete()). Note the use of parenthesis and
not curly braces. The latter creates a lambda that doesn't call its emitter.

**Comment by micHar** [comment]
So simple. Thanks!

**Comment by akarnokd** [comment]
Please be patient on [StackOverflow](https://stackoverflow.com/questions/45653474/rxjava2-completable-with-andthen-operator-never-completes) (deleted) next time!

**Comment by micHar** [comment]
Generally I am, but it honestly looked like an error to me, especially given the way flatMap and similar operators work for Flowable. Sorry!

**Comment by afaucogney** [comment]
@micHar I agree with you, the .andThen{} is equivalent to .doOnComplete{}, isn't it? I mean what would be the use case that only .andThen{} solve ?

**Comment by amanshuraikwar** [comment]
I am having a similar problem:

`someCompletable().andThen(someObservable()).subscribe{...}`

my `someObservable()` is never being called. Please help! I am new to Rx.

On a similar note, how can I sequence an `Observable` after a `Completable`. Is that even possible?

**Comment by akarnokd** [comment]
@amanshuraikwar That is how it is supposed to be done. How is it not working. Could you write an unit test demonstrating your problem?

**Comment by amanshuraikwar** [comment]
Here is how I am using it:

```
Observable<Integer> observable = Observable.just(1).doOnSubscribe(disposable -> System.out.println("observable-subscribed"));

Completable completable = new Completable() {
    @Override
    protected void subscribeActual(CompletableObserver s) {
        System.out.println("completable-subscribed");
    }
};

completable
        .andThen(observable)
        .subscribe(integer -> System.out.println("emitted:"+integer));
```

And this is my output:

`completable-subscribed`

The `observable` is not even being subscribed. What am I doing wrong?

**Comment by akarnokd** [comment]
For one, you implemented `Completable` incorrectly and in a way most people don't need to do it. Use `Completable.create()` instead. Second, you have to complete the `CompletableObserver`, otherwise `andThen` won't know to switch to the other source.

```java
Completable completable = Completable.create(emitter -> {
    emitter.onComplete();
});

completable
        .andThen(observable)
        .subscribe(integer -> System.out.println("emitted:"+integer));
```

**Comment by amanshuraikwar** [comment]
@akarnokd It works now, I was not completing the Completable. Thanks for your help! I really appreciate it.

**Comment by AlexeyPoldeo** [comment]
This is definitely frustrating issue for beginners. I think it's good idea to do something to warn on incorrect usage.

**Comment by ursusursus** [comment]
This is a very silly api tbh, everyone I know was burned by this

**Comment by AndroidDeveloperLB** [comment]
Is it also ok to use this:

```kt
someCompletable.andThen{
//do something
it.onComplete()
}
```
?

**Comment by holdbetter** [comment]
One more example for clearly understanding. You can also add `Thread.sleep(millis)` for playing by yourself. Single is there for same reason

```
Completable.create {
    println("ends")
    it.onComplete()
}.andThen {
    println("andThen1")
    it.onComplete()
}.andThen(Single.just("andThen2"))
    .subscribe { it -> println(it) }
```

it's the same as

```
val completable = Completable.create {
    println("andThen1")
    it.onComplete()
}

Completable.create {
    println("ends")
    it.onComplete()
}.andThen(completable)
    .andThen(Single.just("andThen2"))
    .subscribe { it -> println(it) }
```

**Comment by ericntd** [comment]
I've been working with RxJava for ~5 years now and `andThen { someCompletable }` has tripped me several times, the latest being last week 😅 
Would migrating to RxJava 3 solves this problem, anyone knows? 🙏

**Comment by akarnokd** [comment]
@ericntd It's not an issue with RxJava but how Kotlin trains you to use { } as the convenient lambda syntax. So RxJava 3 can't help you solve this problem either.
