### ISSUE TITLE
2.x: BaseObserver.assertOnlyValues(T...)

### ISSUE THREAD

**Issue by vanniktech** [ReactiveX/RxJava#5555]
I'd like to introduce `assertOnlyValues` to the `BaseObserver`. It's the counterpart to `assertResult(T...)` which does almost the same except for the fact that the type hasn't completed yet.

I'm open if anyone has a better function name. Internally it'd delegate to:

```java
  assertValues(values)
      .assertNoErrors()
      .assertNotComplete()
      .assertSubscribed();
```

**Comment by akarnokd** [comment]
assertResult will eventually fail so assertValues was generally enough. When there is a bug, you can apply the other methods on a case by case basis.

**Comment by vanniktech** [comment]
> assertResult will eventually fail so assertValues was generally enough.

Although `assertValues` does not check for errors nor it'll fail when the stream does complete. Basically with that method I want to test that the stream will stay alive and not terminate.

**Comment by akarnokd** [comment]
You can write this utility method in a class:

```java
public static <T, U extends BaseTestConsumer<T>> assertValuesOnly(U ts, T... values) {
    return ts.assertValues(values).assertNoErrors().assertNotComplete().assertSubscribed();
}
```

And IntelliJ will happily staticly import it.

**Comment by artem-zinnatullin** [comment]
I tend to agree with @vanniktech on this feature-request.

>When there is a bug, you can apply the other methods on a case by case basis.

It's usually too late because code was shipped…

>You can write this utility method in a class:

For sure, I'm also pretty sure @vanniktech uses Kotlin so he could add extension function.

Not a fan of naming though, but I see the pattern, `assertOnlyValues()` should fit test API design.

**Comment by vanniktech** [comment]
> For sure, I'm also pretty sure @vanniktech uses Kotlin so he could add extension function.

That's what I'm doing right now. However I still think a lot of other people could benefit from this and the cost of adding this is really low.

> Not a fan of naming though, but I see the pattern, assertOnlyValues() should fit test API design.

Open for any better name.

**Comment by akarnokd** [comment]
Okay, let's add it. 

I'd name it `assertValuesOnly` so it should show up right after `assertValues` in code completion.
