### ISSUE TITLE
[question] Is WebFlux based on RxJava?

### ISSUE THREAD

**Issue by archenroot** [ReactiveX/RxJava#5556]
Is WebFlux based on RxJava? Or what is relationship between these 2 frameworks/libs?

**Comment by akarnokd** [comment]
> Is WebFlux based on RxJava?

No. WebFlux runs on Pivotal's Reactor 3 reactive library internally but afaik they accept any Reactive-Streams compatible types thus you can get your flows written with RxJava 2.

> what is relationship between these 2 frameworks/libs?

They are on different levels of abstraction; RxJava is a foundational, non-networking concurrency library and WebFlux is a functional web library built on top of a foundational concurrency library.

**Comment by akarnokd** [comment]
Here is a recent video about WebFlux: 

https://www.infoq.com/presentations/servlet-reactive-stack

**Comment by archenroot** [comment]
@akarnokd superior answer! Thanks a lot.
