### ISSUE TITLE
Sample operator with BehaviorSubject issue

### ISSUE THREAD

**Issue by jaumard** [ReactiveX/RxJava#5559]
When trying to use the sample operator with a BehaviorSubject as sampler it didn't work as expected (or understood).
For instance, this simple unit test fails:

```java
 @Test
    public void testSampler() {
        PublishSubject<Long> generator = PublishSubject.create();

        BehaviorSubject<Boolean> sampler = BehaviorSubject.createDefault(true);

        TestObserver<Long> sampledGeneratorObserver = generator.sample(sampler).test();
        generator.onNext(2L);

        sampledGeneratorObserver.assertValueCount(1);
    }
```

RX version: 2.1.x

**Comment by akarnokd** [comment]
Sampler is subscribed before the generator source thus the default `true` sampled nothing as the generator hasn't emitted anything yet. If you call `sampler.onNext(true)` after `generator.onNext(2L)`, the test should pass.

**Comment by jaumard** [comment]
Yeah I know it will work if I do it after but it doesn't fit my needs like that. I was thinking it will emit the default one again. 
Thanks for the explanation !
