### ISSUE TITLE
 (v 2.1.3) observeOn(Schedulers.computation()) throws NPE when used with Observable.fromPublisher

### ISSUE THREAD

**Issue by Setheck** [ReactiveX/RxJava#5563]
Using the maven dependencys
```
<dependency>
    <groupId>io.reactivex.rxjava2</groupId>
    <artifactId>rxjava</artifactId>
    <version>2.1.3</version>
</dependency>
<dependency>
    <groupId>org.reactivestreams</groupId>
    <artifactId>reactive-streams</artifactId>
    <version>1.0.1</version>
</dependency>
```
The following example fails with NPE, however if i remove the ".observeOn(..." or replace that observeOn with a subscribeOn it seems to work just fine.
```
Observable.fromPublisher((Publisher<String>) subscriber ->
	{
            for (int i = 0; i < 10; i++)
            {
            	subscriber.onNext(String.format("Test: %d", i));
            }
            subscriber.onComplete();
        })
	.observeOn(Schedulers.computation())
	.subscribe((string) ->
		System.out.println(String.format("Thread: %s, String: %s", Thread.currentThread().getName(), string))
	);
```
I'm still new to RxJava but, i can't find any documentation that signifies that I am doing something incorrect.

**Comment by JakeWharton** [comment]
The `Publisher` lifecycle dictates that you call `onSubscribe` before any other `on*` method. Consider using `Observable.create` instead which eliminates this requirement.

**Comment by Setheck** [comment]
I'm not sure I follow, can you link me to the documentation that talks about the Publisher lifecycle?
All I can find is that the publisher must implement the subscribe method. 
Furthermore, this doesn't really explain why it works without issue when subscribeOn or when using the default scheduler.

**Comment by akarnokd** [comment]
When you work with `Publisher`, you have to follow the rules of the [Reactive-Streams](https://github.com/reactive-streams/reactive-streams-jvm#goals-design-and-scope) specification. `fromPublisher` is provided by RxJava 2 to interoperate with other libraries supporting the Reactive-Streams specification.

RxJava provides operators such as `create` for general emission and `range` for your specific case so you don't have to deal with `Publisher`s and most of the Reactive-Streams rules by yourself.

**Comment by akarnokd** [comment]
> Furthermore, this doesn't really explain why it works without issue when subscribeOn or when using the default scheduler.

It is an implementation effect of the `subscribeOn` operator that calls the downstream with a custom `Subscription` through `onSubscribe` before the actual subscription, which can happen on some other thread anytime later, actually sends down the "real" `Subscription`.

**Comment by Setheck** [comment]
Got it, makes sense after looking at the reactive-streams readme.
Thanks for the info, looks like i can just close this out
