### ISSUE TITLE
RxJava 2.1.3: Flowable's doOnSubscribe takes subscription consumer instead of disposable one?

### ISSUE THREAD

**Issue by TomasBlazej** [ReactiveX/RxJava#5565]
Hi, 
is there a reason why Flowable still has a subscription consumer instead of a disposable one as a parameter of doOnSubscribe? 

public final Flowable<T> doOnSubscribe(Consumer<? super Subscription> onSubscribe)

**Comment by JakeWharton** [comment]
`Flowable` uses `Subscription` and not `Disposable` as it is the mechanism through which backpressure flows.

**Comment by TomasBlazej** [comment]
Thanks, I thought so, but I was a little bit confused, since its `subscribe` returns `Disposable.

**Comment by JakeWharton** [comment]
Since backpressure is controlled from the listener you pass into subscribe,
all that needs returned outside subscribe is a handle to unsubscribe, which
is what Dispose models.

**Comment by TomasBlazej** [comment]
Thank you, I get it.
