### ISSUE TITLE
Enable TestObservable chaining for more actions

### ISSUE THREAD

**Issue by dmstocking** [ReactiveX/RxJava#5566]
I do a lot of verification that timeouts are being applied correctly. So I have a lot of code that looks like

>     when(dependency.logout()).thenReturn(Single.never());
>     TestObserver<Result> test = service.logout()
>             .test();
>     customRxJavaRule.testScheduler().triggerActions();
>     test.assertEmpty();
>     customRxJavaRule.testScheduler().advanceTimeBy(1, TimeUnit.SECONDS);
>     verify(dependency).disconnect();
>     test.assertValue(Result.Error.create());

and I wish it could be more readable by just being able to chain any action inside of a TestObservable.

>     when(dependency.logout()).thenReturn(Single.never());
>     service.logout()
>             .test()
>             .do(() -> customRxJavaRule.testScheduler().triggerActions())
>             .assertEmpty()
>             .do(() -> {
>                 customRxJavaRule.testScheduler().advanceTimeBy(1, TimeUnit.SECONDS);
>                 verify(dependency).disconnect();
>             })
>             .assertValue(Result.Error.create());

or even

>     when(dependency.logout()).thenReturn(Single.never());
>     service.logout()
>             .testWithTestScheduler(customRxJavaRule.testScheduler())
>             .triggerActions())
>             .assertEmpty()
>             .advanceTimeBy(1, TimeUnit.SECONDS)
>             .assertValue(Result.Error.create());
>     verify(dependency).disconnect();

I couldn't find anything today that would enable this. I am pretty sure that 2.X can't change the public API, so this would have to be 3.X. I also don't know what is easy or feasible. But, I have a problem testing classes and keeping them readable. RxJava has made my code have some really nice and easy to use features but has made my tests look a little messy.

**Comment by akarnokd** [comment]
There is a method on `TestSubscriber` only called [`assertOf`](http://reactivex.io/RxJava/2.x/javadoc/io/reactivex/subscribers/TestSubscriber.html#assertOf-io.reactivex.functions.Consumer-) that let's one do this for `Flowable`s. It can be added to `TestObserver` as well. `testWithTestScheduler` definitely won't be added.

Would you like to post a PR.

**Comment by dmstocking** [comment]
So I had no idea that assertOf even existed. I did go and look and it appears that [assertOf](http://reactivex.io/RxJava/2.x/javadoc/io/reactivex/observers/TestObserver.html#assertOf-io.reactivex.functions.Consumer-) exists on TestObserver already. (I don't know if I am interpreting you correctly. It seemed like you suggested it didn't.) I am going to go play around with this and see how to use it. Maybe it can solve my problems.

**Comment by akarnokd** [comment]
Indeed, I forgot about it and missed it the method list as well.

**Comment by vanniktech** [comment]
> There is a method on TestSubscriber only called assertOf that let's one do this for Flowables. It can be added to TestObserver as well. 

Since I was just in that class, `TestObserver` has `assertOf`.

**Comment by akarnokd** [comment]
Looks like this question has been answered. If you have further input on the issue, don't hesitate to reopen this issue or post a new one.
