### ISSUE TITLE
RxJavaHooks installation instructions?

### ISSUE THREAD

**Issue by spekary** [ReactiveX/RxJava#5570]
This page:

https://github.com/ReactiveX/RxJava/wiki/Plugins

Should include installation instructions, since RxJavaHooks is not installed by default.

**Comment by artem-zinnatullin** [comment]
>not installed by default

What do you mean by that? It's just API that you can call.

I might be wrong, but looks like you're using RxJava 2.x while reading docs for 1.x, please see https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0#runtime-hooks

@akarnokd we should probably do something about splitting wiki into 1.x and 2.x articles, we can start by adding `1.x`/`2.x` to article names. Maybe deprecating 1.x articles in future.

**Comment by spekary** [comment]
Yep, that was the issue. 

The doc I read says: As of 1.1.6 the regular RxJavaPlugins and the other hook classes have been deprecated in favor of RxJavaHooks.

So I assumed it was the latest. Its really unclear from the docs whether 2.0 deprecates 1.0, or whether you are trying to maintain two code bases. If 2.0 is released, shouldn't that be the default doc, rather than "read the 1.0 doc, and then read the what's changed in 2.0 doc to really know about 2.0"

What lead me to all of this was that thrown errors from other threads are not giving me a lot of information on where the error was thrown. I saw that:
```
RxJavaHooks.enableAssemblyTracking()
```
Could help with this, but I don't see the equivalent in 2.0. Is there some way of configurating 2.0 to report file and line numbers when throwables are thrown?

**Comment by artem-zinnatullin** [comment]
There is no direct equivalent of `RxJavaHooks.enableAssemblyTracking()` in 2.x. 
I believe it's possible to implement similar kind of tracking by using `RxJavaPlugins.onAssembly(*)`.

1.x is not actively developed anymore ([README.md](https://github.com/ReactiveX/RxJava/tree/994c65d2e680cb820c8140890b37c8428aeb1263#version-1x-javadoc)):

>* June 1, 2017 - feature freeze (no new operators), only bugfixes
>* March 31, 2018 - end of life, no further development

So we encourage everybody to migrate existing code to RxJava 2.x and start new projects with 2.x right away.

**Comment by akarnokd** [comment]
> we should probably do something about splitting wiki into 1.x and 2.x articles, we can start by adding 1.x/2.x to article names. Maybe deprecating 1.x articles in future.

That's a lot of work and afaik one can't PR the wiki so the task would need someone with access, knowledge and vision on how it should look. 

Also most concepts are still valid in 2.x but the references to classes and packages need changing.

> RxJavaHooks.enableAssemblyTracking()

This has been done in the [extensions project](https://github.com/akarnokd/RxJava2Extensions#debug-support) and is implemented in a way that supported my view of debugging flows. There is also the [Traceur](https://github.com/T-Spoon/Traceur) project based on the extensions project but with different set of features.

> March 31, 2018 - end of life

Once 1.x has been retired, I or any other volunteer can go in, clean up the wiki and make it 2.x completely.

**Comment by artem-zinnatullin** [comment]
@akarnokd I think we can close this one

**Comment by akarnokd** [comment]
Sure.
