### ISSUE TITLE
Observable throw exception after isDisposed

### ISSUE THREAD

**Issue by PoetKing** [ReactiveX/RxJava#5584]
hi,god:Sorry for this Chinese style English.

rxjava-2.1.1

Use ObservableFromCallable,I disposed the Disposable before Callable return,then in the call() method  throw an exception(maybe custom), and then the Application crash by UndeliverableException.

I do not want to set an errorHandler,because i do not know to do what when i accept a UndeliverableException(or other).

I want i can ignore the exception,because i know why and how the exception happened, and i really don't care the 'return value' by Callable#call()  at that time.

**Comment by akarnokd** [comment]
You could use `Observable.create()` instead with `ObservableEmitter.tryOnError` to avoid signalling the error. Alternatively, you could take the `ObservableFromCallable` implementation and modify it slightly:

```java
public final class ObservableFromCallable<T> extends Observable<T> implements Callable<T> {
    final Callable<? extends T> callable;
    public ObservableFromCallable(Callable<? extends T> callable) {
        this.callable = callable;
    }
    @Override
    public void subscribeActual(Observer<? super T> s) {
        DeferredScalarDisposable<T> d = new DeferredScalarDisposable<T>(s);
        s.onSubscribe(d);
        if (d.isDisposed()) {
            return;
        }
        T value;
        try {
            value = ObjectHelper.requireNonNull(callable.call(), "Callable returned null");
        } catch (Throwable e) {
            Exceptions.throwIfFatal(e);
            if (!d.isDisposed()) {
                s.onError(e);
            // ===============================
            //} else {
            //    RxJavaPlugins.onError(e);
            // ===============================
            }
            return;
        }
        d.complete(value);
    }

    @Override
    public T call() throws Exception {
        return ObjectHelper.requireNonNull(callable.call(), "The callable returned a null value");
    }
}
```

**Comment by PoetKing** [comment]
Thinks for your answer!
Finally，use this code:

```java
public abstract class ObservableIgnoreGhostCall<T> extends Observable {

    @Override
    protected void subscribeActual(Observer s) {
        DeferredScalarDisposable<T> d = new DeferredScalarDisposable<T>(s);
        s.onSubscribe(d);
        if (d.isDisposed()) {
            return;
        }
        T value;
        try {
            value = ObjectHelper.requireNonNull(call(), "call returned null");
        } catch (Throwable e) {
            Exceptions.throwIfFatal(e);
            if (!d.isDisposed()) {
                s.onError(e);
//            } else {
//                RxJavaPlugins.onError(e);
            }
            return;
        }
        d.complete(value);
    }

    protected abstract T call() throws Exception;
}
```

**Comment by artem-zinnatullin** [comment]
@akarnokd hmm, do you think this is what we should suggest people to handle `UndeliverableException`? 

Lots of operators in RxJava deliver errors arrived after terminal event to `RxJavaPlugins.onError()`, ie `observeOn()`, `take()`, etc so fixing one of them in userland won't help in complex Rx chains.

Since exception is clearly named `UndeliverableException`, I guess we can safely suggest users to set `RxJavaPlugins.setErrorHandler()` that ignores and/or logs `UndeliverableException` ie:

```java
final class CustomRxJava2ErrorHandler implements Consumer<Throwable> {

    @Override
    public void accept(Throwable throwable) {
        if (throwable instanceof UndeliverableException) {
            L.d(throwable, "Exception arrived after termination of RxJava2 chain.");
        } else {
            // Mimics default RxJavaPlugins.onError() behavior.
            // Crashes on Android, prints error to System.err on JVM.
            Thread currentThread = Thread.currentThread();
            
            currentThread
                .getUncaughtExceptionHandler()
                .uncaughtException(currentThread, throwable);
        }
    }
}

// Needs to be called before any use of RxJava, ie in Application.onCreate().
RxJavaPlugins.setErrorHandler(new CustomRxJava2ErrorHandler());
```

**Comment by akarnokd** [comment]
This was a particular issue with `fromCallable` where suppressing the interruption exception requires you to return some non-null value. So either you write a custom operator or you use `create()`:

```java
Observable.create(e -> {
    try {
        e.onNext(compute());
        e.onComplete();
    } catch (Throwable e) {
       e.tryOnError(e);
    }
})
```

The `UndeliverableException` can hold anything so throwing away all of them might not be the best action. If you scroll up from [the wiki](https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0#schedulers), the example handler starts with unwrapping the cause of the `UndeliverableException` and decides on that instead.
