### ISSUE TITLE
Nested obseverable chain

### ISSUE THREAD

**Issue by felix2ch** [ReactiveX/RxJava#5593]
The goal is send data to device via Blue tooth LE by phone.
Whole task chained by lots async operators in single thread.

Library version:
rxandroid:2.0.1
rxjava:2.1.3

Below code simulate communication with device.
There are two buttons, one is response from BLE, other one is response from Device.
BLE respond for every SendBleData, Device respond for every sendPacketToDevice.

On the beginning, everything works as my expecting.
But when SendAllData be called, It stoped when sendPacketToDevice(pageAddr) complete at first page.

Any suggestion will be appreciate.

    /*
    Task queue:
        ->SendBleData
        ->sendPacketToDevice
                ->SendBleData
                ...
        ->sendPacketToDevice
                ->SendBleData
                ...
        ->Send All Data
                -> Send Page
                          -> sendPacketToDevice(page addr--small package)
                                ->sendBleData
                          -> sendPacketToDevice(page data--lage packet)
                                ->sendBleData
                                ->sendBleData
                                ->sendBleData
                                ->sendBleData
                                ......
                -> Send Page
                ......

     */

    private Observer bleObserver;
    private Observer deviceObserver;

    private View.OnClickListener onDeviceResponse = new View.OnClickListener() {
        @Override
        public void onClick(View view) {
            Log.v("RxJava", "Device success");
            deviceObserver.onNext("");
            deviceObserver.onComplete();
        }
    };

    private View.OnClickListener onBLESent = new View.OnClickListener() {
        @Override
        public void onClick(View view) {
            Log.v("RxJava", "BLE success");
            bleObserver.onNext("");
            bleObserver.onComplete();
        }
    };
    public Observable sendBleData(byte[] data){
        return new Observable() {
            @Override
            protected void subscribeActual(Observer observer) {
                bleObserver = observer;
                Log.v("RxJava", "BLE Data Send");
                //Send data here
            }
        };
    }

    boolean isLarge = false;

    public Observable sendPacketToDevice(final byte[] cmd){
        return new Observable() {
            @Override
            protected void subscribeActual(Observer observer) {
                deviceObserver = observer;

                byte[] a;
                byte[] a1 = {1};
                byte[] a4 = {1, 2, 3, 4};
                if(isLarge){
                    a = a4;
                    Log.v("RxJava", "Large packet");
                }else{
                    a = a1;
                    Log.v("RxJava", "Small packet");
                }

                isLarge = !isLarge;

                //Below code does not work
                //Observable.fromArray(a).flatMap(d -> sendBleData(d)).subscribe(ret -> {}, error -> observer.onError(new Throwable()));
                //OR
                //Observable.fromArray(a).concatMap(d -> sendBleData(d)).subscribe(ret -> {}, error -> observer.onError(new Throwable()));

                Observable o = Observable.just("");
                for (int i = 0; i < a.length; i++){
                    o = o.flatMap(data ->sendBleData(a1));
                }
                o.subscribe(ret -> {}, error -> observer.onError(new Throwable()));

            }
        };

    }

    public Observable SendAllData(byte[] d){
        Log.v("RxJava", "Send all");
        byte[] pageAddr = {1};
        byte[] pagedata={1};

        //Expect below format but not work
        //
        //byte[] pageArray = {1,2,3};
        //return Observable.fromArray(pageArray)
        //        .flatMap(page -> sendPage(page));
        //OR
        //          .concatMap(page -> sendPage(page));

        Observable o = Observable.just("");
        for (int i = 0; i < 3; i++){
            //pageAddr = ...
            //pageData = ...
            o = o.flatMap(s ->sendPacketToDevice(pageAddr)).flatMap(s -> sendPacketToDevice(pagedata));
        };

        return o;
    }

    public Observable sendPage(byte[] d){
        byte[] pageAddr = {1};
        byte[] pagedata={1};
        return Observable.just("").flatMap(s -> sendPacketToDevice(pageAddr)).flatMap(s -> sendPacketToDevice(pagedata));
    }

    public void test(){

        byte[] cmd = {50};

        Observable.just("")
                .flatMap(d -> sendBleData(cmd))
                .flatMap(d -> sendPacketToDevice(cmd))
                .flatMap(d -> sendPacketToDevice(cmd))
                .flatMap(d -> sendPacketToDevice(cmd))
                .flatMap(d -> SendAllData(cmd))
                .subscribe();
    }

**Comment by akarnokd** [comment]
There are a couple of red flags:

- Calling `onComplete` from the click handler which likely doesn't allow multiple invocation of the chain. Also you may want to use `PublishSubject`.
- Using `new Observable` and not honoring the protocol, use `Observable.create()` instead
- Sneaking out the `Observer` is risky and prone to protocol violations as well, you should chain your actions onto a `PublishSubject`.

**Comment by felix2ch** [comment]
It's work perfect after add .subscribeOn(Schedulers.io()) to observables.

> Calling onComplete from the click handler which likely doesn't allow multiple invocation of the chain.

Yes, How about replace it with Single?

Is it possible to replace the "for ...o = o.flatmap" things with obserable.fromArray ?

I will learn about Subject.
Thanks a lot, @akarnokd .

**Comment by felix2ch** [comment]
> Sneaking out the Observer is risky and prone to protocol violations as well, you should chain your actions onto a PublishSubject.

In this task, All response created by a single BLE callback object, send the observer to it is the only way I can find.
If another approach is better than it, I will be glad to replace it.

**Comment by akarnokd** [comment]
First, use `Observable.create()` instead of `new Observable() { }`.

**Comment by RobLewis** [comment]
Have you considered a reactive BLE library like [RxAndroidBle](https://github.com/Polidea/RxAndroidBle)? I've used it quite a bit with good success. Currently it only supports RxJava 1, but plans for RxJava 2 are underway.

**Comment by felix2ch** [comment]
> First, use Observable.create() instead of new Observable() { }.

Already did it.

**Comment by akarnokd** [comment]
Are your issues resolved?

**Comment by felix2ch** [comment]
It works.

But I hate the "for ...o = o.flatmap" things.
It looks not rx style.
How can i replace it with Obserable.fromArray().concatMap()... ?

**Comment by akarnokd** [comment]
Use an array of byte arrays as the input:

```java
// prepare commands
byte[][] cmds = {
  new byte[] { },
  new byte[] { },
  new byte[] { },
  new byte[] { },
};

Observable.range(0, cmds.length)
.concatMap(i -> {
    if (i == 0) {
       return sendBleData(cmds[i]);
    } else if (i == cmds.length - 1) {
       return SendAllData(cmds[i])
    }
    return sendPacketToDevice(cmds[i])
})
.subscribe(...)
```

**Comment by akarnokd** [comment]
Looks like this question has been answered. If you have further input on the issue, don't hesitate to reopen this issue or post a new one.
