### ISSUE TITLE
2.x: Documentation error in Observable for "any" operator

### ISSUE THREAD

**Issue by RobLewis** [ReactiveX/RxJava#5595]
In v.2 javadoc for `Observable`, it is stated (in at least 2 places) that the `any()` operator returns an `Observable`. This appears to be wrong: it returns a `Single` (which is stated correctly in other places). The corresponding entry in the `Flowable` docs appears to be correct.

**Comment by akarnokd** [comment]
Yes, there are a couple of such mistakes, i.e. `all` is wrong as well. Would you like to submit a PR?

**Comment by RobLewis** [comment]
TBH I don't know enough about GitHub to feel comfortable with creating/submitting PRs. Sorry.

**Comment by akarnokd** [comment]
Perhaps someone else can pick it up. PR welcome.

**Comment by akarnokd** [comment]
Closing via #5600.

**Comment by RobLewis** [comment]
Got another one for you: in Observable, it's stated that isEmpty() returns an Observable when it's actually a Single. 

On Sep 14, 2017, at 07:24 AM, David Karnok <notifications@github.com> wrote:

Closed #5595.

**Comment by akarnokd** [comment]
Covered by #5600.
