### ISSUE TITLE
the operate about "replay"

### ISSUE THREAD

**Issue by 364089999** [ReactiveX/RxJava#5596]
the png "http://reactivex.io/documentation/operators/images/replay.c.png" 
and the png "https://raw.githubusercontent.com/wiki/ReactiveX/RxJava/images/rx-operators/replay.png"
are different.

**Comment by akarnokd** [comment]
It is listed on #5319 to be fixed:

> `Observable.replay()` + overloads: remove publish

Not sure what you mean otherwise.

**Comment by akarnokd** [comment]
Closing as already tracked by #5319.
