### ISSUE TITLE
2.x: wiki writing operators 2.0

### ISSUE THREAD

**Issue by ctranxuan** [ReactiveX/RxJava#5598]
Hi, 
In the wiki "Writing operators for 2.0", there are some issues in the following code sample of the section [Operator targeting lift()](https://github.com/ReactiveX/RxJava/wiki/Writing-operators-for-2.0#operator-targeting-lift):

```java
   @Override
    public Subscriber<? super Integer> apply(Subscriber<? super Integer> child) {
        return new Op(child);
    }
```
-> there shouldn't be `@Override` on the constructor

```java
       @Override
        pubic void onSubscribe(Subscription s) {
            this.s = s;
            actual.onSubscribe(this);
        }
```
-> there is a reference to an `actual` field throughout the code but it's not declared. I do believe it's actually the `child` field instead of `actual`.

Hope this help a bit. Thanks for this great lib!

**Comment by akarnokd** [comment]
Thanks! Fixed.
