### ISSUE TITLE
io.reactivex.internal.operators.observable.ObservableIgnoreElementsCompletable cannot be cast to io.reactivex.Observable

### ISSUE THREAD

**Issue by cloudshooterhuman** [ReactiveX/RxJava#5599]
- RxJava version : 2.1.1

```
studentAuthentication.resetPassword(email).observeOn(AndroidSchedulers.mainThread()).subscribe(() -> {
            //
        }, throwable -> {
            //
        });
```

```
public Completable resetStudentPassword(String email) {
        return Completable.defer(() -> {
             ....
            return retofitApi.resendPassword(resetPasswordRequest);
        });
    }
```
```
@POST("student/resendPassword")
    Completable resendPassword(@Body MyRequest request);
```

- Exception : **io.reactivex.internal.operators.observable.ObservableIgnoreElementsCompletable cannot be cast to io.reactivex.Observable**

**Background :** Issue raised when converting Observable<T> to Completable

**Comment by akarnokd** [comment]
I don't see `ignoreElemets()` here, perhaps there is something wrong with the Retrofit 2 RxJava 2 adapter: misaligned or too old version of Retrofit.

**Comment by cloudshooterhuman** [comment]
I'm using the last retrofit version 2.3.0

**Comment by JakeWharton** [comment]
What's the stacktrace?

**Comment by cloudshooterhuman** [comment]
`throwable` method is called with the following stacktrace
`java.lang.ClassCastException: io.reactivex.internal.operators.observable.ObservableIgnoreElementsCompletable cannot be cast to io.reactivex.Observable`

**Comment by JakeWharton** [comment]
That is just the message. What's the full stacktrace showing the call stack?

**Comment by cloudshooterhuman** [comment]
Thank you @JakeWharton @akarnokd 
The error is in our custom `addCallAdapterFactory`

**Comment by akarnokd** [comment]
Okay.

**Comment by ivnsch** [comment]
What was the error @selmanon  ?

**Comment by cloudshooterhuman** [comment]
@i-schuetz https://github.com/ReactiveX/RxJava/issues/5599#issuecomment-329490447 but I forgot the details :=(
