### ISSUE TITLE
1.x: RxJava v1.3.1 references method not present in JRE < 8 (NewThreadWorker.purgeExecutors)

### ISSUE THREAD

**Issue by artem-zinnatullin** [ReactiveX/RxJava#5601]
Follow up after https://github.com/artem-zinnatullin/RxJavaProGuardRules/issues/62 once we've figured out that issue caused by changes in RxJava, specifically [switch to jdk8 from jdk7 on Travis CI](https://github.com/ReactiveX/RxJava/commit/ed35a14b8b8c5899f292e60905e082563d516539).

**Comment by akarnokd** [comment]
See #5602

**Comment by koral--** [comment]
Shouldn't CI configuration include both jdk7 and 8? It may help detecting this kind of issues.

**Comment by JakeWharton** [comment]
No. JDK 7 is EOL and shouldn't be used. JDK 9 and the -release flag fixes
this problem as it sets the source compatibility, target compatibility, and
bootstrap classpath all in one shot. It will support 3 versions back which
means JDK 9 supports 9, 8, 7, and 6 for the flag. We just need to wait a
week for JDK 9 GA and then however long it takes Travis to update. Then we
can set -release to 6 and get rid of animal sniffer.

**Comment by artem-zinnatullin** [comment]
Yep, also it won't really matter even if we had jdk7 in build matrix but
still made this release with jdk8, we had this animalsniffer check
suppressed :(

**Comment by akarnokd** [comment]
Closing via #5602 and [1.3.2](https://github.com/ReactiveX/RxJava/releases/tag/v1.3.2).
