### ISSUE TITLE
rx Observable is dropping results in downstream while no backpressure exception is thrown

### ISSUE THREAD

**Issue by HanCheng** [ReactiveX/RxJava#5604]
I have a method that is making api call using rxjava. The downstream of this method is updating UI, and does some time consuming work. The caller of this method is triggered whenever user clicks the button. So if the button is clicked very fast, sometimes one of the response is missing. But I can see the response back from Charles proxy. So my gut is that this is back pressure issue that the producer is producing faster than consumer to execute. But if its a back pressure issue, am i supposed to get a MissingBackPressureException (for rxjava 1)? But I didnt see any exceptions.  

I noticed that for observeOn() method, we have unbounded buffer, so seems like if upstream is passing down new data while downstream is still processing the previous data, the buffer will cache that new data, so does this data cached and never fetched from this buffer, or is there a way to fetch these data from buffer?

This is happening both rxjava 1 and 2 using Observable. Havent try the Flowable yet.
Sorry if i posted here, since i asked on stackoverflow for month, still not get correct response.

Much appreciated for any advise.

**Comment by akarnokd** [comment]
Please do not cross post on multiple sites.

https://stackoverflow.com/questions/46228592/rxjava-drops-downstream-results

**Comment by HanCheng** [comment]
@aballano  i also posted same problem almost half year ago, https://stackoverflow.com/q/43505320/3304280 still didnt get a valid response. Can someone help me with that? 

Also updated post added more information of my implementation https://stackoverflow.com/questions/46228592/rxjava-drops-downstream-results

**Comment by akarnokd** [comment]
Please post something reproducible on StackOverflow; perhaps even start over with your solution. Also blocking queue doesn't mix well with RxJava constructs.
