### ISSUE TITLE
RxJava 2.x toList() return Single rather than Observable

### ISSUE THREAD

**Issue by KhalidElSayed** [ReactiveX/RxJava#5611]
I'm using the RxJava 1.x Observable#toList() and it returns an Observable but when I using it in RxJava 2.x it returns a Single so I've to converted back to Observable each time!

for example:

```java
DataManager.getInstance().loadBooks()
                .map(Model::getModel)
                .flatMapIterable(books -> books)
                .filter(book -> book.isNew())
                .toList()
                .toObservable()
                .subscribe(mView::onLoadBooks);
```

so my questions are:
Why did you do this change in RxJava 2?
Should I converted the Single back to Observable each time to keep using Observable rather than Single?

**Comment by JakeWharton** [comment]
It only emits one item which is what a `Single` conveys. Delete your `toObservable()` call and your code will still compile and work the same way.

**Comment by akarnokd** [comment]
> Why did you do this change in RxJava 2?

[Many operators have changed](https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0#different-return-types) return type to better capture the cardinality of the flows. Operators known to return exactly one item or an error are now returning `Single`.
