### ISSUE TITLE
Observable retryWhen() argument differ from other Rx types

### ISSUE THREAD

**Issue by jeremy303** [ReactiveX/RxJava#5614]
Observable has the following signature:
```
public final Observable<T> retryWhen(final Function<? super Observable<Throwable>, ? extends ObservableSource<?>> handler)
```

Which accepts a Function with a different signature than the other Rx types:
```
public final Single<T> retryWhen(Function<? super Flowable<Throwable>, ? extends Publisher<?>> handler) 

public final Maybe<T> retryWhen(final Function<? super Flowable<Throwable>, ? extends Publisher<?>> handler) 

public final Completable retryWhen(Function<? super Flowable<Throwable>, ? extends Publisher<?>> handler) 
```

Thus the same `retryWhen()` function can be shared between `Completable`, `Single` and `Maybe`, but not `Observable`.

This has proven to be an issue with a shared error handler I have been providing to `retryWhen()` for the other Rx types.  Now I have need to add this shared error handling code to an `Observable.retryWhen()`, but unfortunately it is not compatible due to the differing `retryWhen()` signatures.

**Comment by akarnokd** [comment]
You specifically have asked this question before: #5549

**Comment by jeremy303** [comment]
@akarnokd  Wow, I certainly did.  Sheesh...  I need to get more sleep. :-)
