### ISSUE TITLE
Decouple API and implementation

### ISSUE THREAD

**Issue by gabrielhuff** [ReactiveX/RxJava#5629]
Do you guys think that it would be a good idea to restructure RxJava by spliting it into API and implementation (like Gradle for example)?

For instance, what if `Observable<T>` and `Subject<T>` were interfaces and we could do stuff like this (assuming that `publishSubject()` is equivalent to `PublishSubject.create()`):

```Kotlin
// Foo is a simple class that invokes onBar whenever bar is called
open class Foo(private val onBar: (Int) -> Unit) {

    open fun bar() { onBar(value) }
}

// ObservableFoo is a Foo and also an Observable
class ObservableFoo private constructor(private val subject: Subject<Unit>) :
        Observable<Unit> by subject,
        Foo({ subject.onNext(Unit) }) {

    constructor() : this(publishSubject())
}

// We can subscribe to ObservableFoo instances
ObservableFoo().subscribe { print("Bar changed to $it") }
```

Currently the only way to create a custom observable would be by inheriting from `Observable`. Making it an interface instead of a class would satisfy the 'composition over inheritance' principle.

This is my first time posting here so I apologise in advance if this is not the place to start this kind of discussion.

**Comment by JakeWharton** [comment]
There is `ObservableSource` (and friends for other types) which provide the `subscribe` method that takes an `Observer`. You have to know what you're doing for this, though, and instead you should implement `ObservableOnSubscribe` (and friends for other types) which can be wrapped by the `Observable.create`.

**Comment by akarnokd** [comment]
That principle leads to unnecessary allocation and indirection. We went extra lengths to reduce such things in v2. Besides, an overridable operator method is an invitation for megamorphic dispatch and people trying to override it with inadequate operator writing skills. Third, an exteding type would immediately get lost as the existing operators still return the base type. The most workable solution would be the language level extension methods which sadly is not available in Java.

**Comment by gabrielhuff** [comment]
@JakeWharton True. In fact, one could make things even more generic by implementing `Publisher` (thus removing a dependency from RxJava itself). Thing is, none of these interfaces have access to the `Observable` class utility (i.e. operators), which is pretty much what makes RxJava special.

Of course, all of the above interfaces can be wrapped into `Observable` instances. But the overhead introduced by wrapping them every time would make things inviable from an API design perspective.

@akarnokd  I agree with the part about the risk of breaking contracts, but this is intrinsic to everything that separates interface from implementation.

About the part about the exteding types getting lost due to operators returning the base type, I don't see it as a problem. In fact, this is the current behavior (every operator returns an `Observable`).

It might look like I'm disagreeing with you guys, but I think everything you said make perfect sense. To be honest, I see this as an alternative rather than an improvement. It's a matter of design choices and you gave me good reasons why things are the way they are.

**Comment by abersnaze** [comment]
@stealthcode and I did some tinkering on an idea to build a gradle plugin for merging dependencies. The idea being that you could add methods to any class prior to the building of your code. I had envisioned the syntax being something like

```
dependencies {
    colliderCompile 'org.reactivestreams:reactive-streams:1.0.1' {
         merge 'reactivex.io.rxjava3:rxjava3:1.0'
         merge 'reactivex.io.rxjava3:rxmath:1.0'
    }
}
```

The `rxjava3` jar would contain a duplicate the interface of `org.reactivestreams.Publisher<T>` but with default methods for core things like `scan` and `flatMap`. The collider plugin would repackage the reactive-streams-1.0.1.jar on disk with the injected methods so IDEs and JVM would be none the wiser that they weren't there all along. Then the `rxmath` could add thing related to `count`, `average`, `mean` and `standardDeviation`.

Of course that plugin would be an entirely independent project and NOT discussed here in rx java. If you have more questions ping me directly.

**Comment by akarnokd** [comment]
Looks like this question has been answered. If you have further input on the issue, don't hesitate to reopen this issue or post a new one.
