### ISSUE TITLE
2.x: Gradle 4 & removing the nebula plugin

### ISSUE THREAD

**Issue by akarnokd** [ReactiveX/RxJava#5632]
I've created a [new branch](https://github.com/ReactiveX/RxJava/tree/Gradle4) to work out the release process of RxJava without the nebula plugin.

This required replacing it with the standard bintray plugin and some [extra logic](https://github.com/ReactiveX/RxJava/blob/Gradle4/build.gradle#L256). Creating a snapshot release can be done via push to the RxJava repo and by itself is not a big issue to iron out. The trouble is with the full release because it has to be triggered by the "Publish release" button of the release screen. A failed release will waste tags.

I mainly tried to follow the instructions of [the plugin itself](https://github.com/bintray/gradle-bintray-plugin) but I'm not sure if we'd have to specify some of the optional properties or not.

**Comment by JakeWharton** [comment]
Did you look at RxAndroid? We got rid of nebula back in the 1.x days. The
only difference to what you described is that a tag being pushed triggers
the release upload. We still run the risk of burning a version if the
release process fails halfway through.

**Comment by akarnokd** [comment]
I've been looking at it and applied it in the given branch. The full release requires the PGP signed jars which keys I don't have; bintray is supposedly setup with it.

**Comment by akarnokd** [comment]
The snapshot seems to work at least: https://oss.jfrog.org/artifactory/libs-snapshot/io/reactivex/rxjava2/rxjava/2.2.0-SNAPSHOT/

**Comment by akarnokd** [comment]
Closing via #5633 .
