### ISSUE TITLE
Disposing previous stream in flatMap

### ISSUE THREAD

**Issue by jbialkowski13** [ReactiveX/RxJava#5636]
Hi,

I've found interesting behaviour and I am not sure is it intended behaviour and if so how I can actually aim my need.

RxJava version I checked:
- 2.1.2
- 2.1.4

Issue:
Kotlin example
```
 val single = Single.just("single")
                .doOnDispose({ println("single disposed") })
                .doOnSuccess({ println("single success") })
                .doAfterTerminate({ println("single after terminate") })

val single2 = Single.just("single 2")
                .doOnDispose({ println("single2 disposed") })
                .doOnSuccess({ println("single2 success") })
                .doAfterTerminate({ println("single2 after terminate") })

single.flatMap { single2 }
                .test()
                .dispose()
```

The output is following:
```
single success
single2 success
single2 after terminate
single after terminate
single2 disposed
```

So the `single` was never disposed in this case. My expectation was to call `doOnDispose` as well in single, as I have some logic connected to lifecycle of this stream.

I assume it is expected behaviour, but I really need such lifecycle in my case. Is it possible to force such behaviour in this case?

**Comment by akarnokd** [comment]
`single` was not disposed because it was no longer part of the chain at that moment but `single2` was. If you want to perform guaranteed cleanup operation after a flow terminates or gets disposed, use `doFinally` instead of `doAfterTerminate`.

**Comment by jbialkowski13** [comment]
Actually it won't work in my case as `doFinally` is called as well after `onSuccess` was called, and in my case it is not expected result. I expect that I can be notified in original stream, that client has disposed it, without knowing how it was chained later by client.

**Comment by akarnokd** [comment]
That is not possible in this setup. You could try `zip` or `Observable` that doesn't terminate and as such is kept as reference.

**Comment by jbialkowski13** [comment]
Thanks for tips.

**Comment by AllenVork** [comment]
I wonder whether the single leads to memory leaks?
