### ISSUE TITLE
Reduce .onBackpressureLatest() cache from 127 to 1

### ISSUE THREAD

**Issue by Alisunov** [ReactiveX/RxJava#5638]
Hi!

Could you please explain how does `buffer(bufferOpenings, bufferClosingSelector)` work?

I want to use Observables (especially, `interval()`) as triggers to do some long-lasting job.

In easy words, trigger observable emits an item, it's being processed and while it is processed, my trigger emits 5 more items.
When the first item is processed, I don't care, how many items were emitted, I only want to know if there were items emitted or not.
In the former case, I want to start processing, in the latter case - I want to wait until the next trigger emission.

![How it should work](https://user-images.githubusercontent.com/19324857/31134001-46a51624-a861-11e7-90e1-72d3e95633ab.png)

I have looked into the backpressure, but RxJava caches the items before backpressure strategies are applied (127 items are cached, other are dropped/buffered).

All other operators are also only delaying the items, but send to the downstream all of them.

The last working solution was to:
```kotlin
val lock = BehaviorSubject.create(true)

fun run() = triggerObservable
    .buffer { lock }
    .observeOn(Schedulers.io())
    .map {
        if (!it.isEmpty()) {
            Thread.sleep(5000) // time consuming operation
        }
        lock.onNext(true)
    }
```

The problems here are with the second case in the image:
- If I move the `lock.onNext(true)` to the `if()`, buffer will stuck if there were no trigger emissions before `Thread.sleep(5000)`.
- If I leave it outside `if()`, it will run in a loop eating device power and be doing nothing until there is a new trigger emission.

I have thought, that I can keep the buffer opened (emit the items instantly) when no items are being processed. And to start buffering when an item is being processed, then opening the "gate" again.

What can you suggest here?
Thanks!

**Comment by akarnokd** [comment]
You need `Flowable.onBackpressureLatest` which will buffer at most one item and `observeOn()` with perfetch of 1.

**Comment by akarnokd** [comment]
Also you can have a look at the [coalesce](https://github.com/akarnokd/RxJava2Extensions#flowabletransformerscoalesce) extension operator.

**Comment by Alisunov** [comment]
@akarnokd Hi! Sorry, I'm using RxJava1, and there is no possibility to migrate to RxJava2.

I have tried `onBackpressureLatest()` in RxJava1, and it does what I need, BUT after 127 emissions are cached.

So, if 200 items were emitted during the time I'm processing the first emitted item - 127 would be cached and send to downstream ignoring the backpressure strategies. 73 would be dropped though.

I know, that I can only change the cache size with `System.setProperty("rx.ring-buffer.size", "8");` but I want to change it only for one Observable.

Was there a change in RxJava2?

**Comment by akarnokd** [comment]
There is an overload to [observeOn](http://reactivex.io/RxJava/1.x/javadoc/rx/Observable.html#observeOn-rx.Scheduler-boolean-int-) which allows you to limit the number of items buffered by it.

**Comment by Alisunov** [comment]
@akarnokd Thanks a lot! That helped.

```kotlin
fun run() = triggerObservable
    .onBackpressureLatest()
    .observeOn(Schedulers.io(), 1)
    .map { Thread.sleep(5000) /* time consuming operation */ }
```

Does the trick. It drops all but one emitted items while previous one is being processed.

**Comment by akarnokd** [comment]
Looks like this question has been answered. If you have further input on the issue, don't hesitate to reopen this issue or post a new one.
