### ISSUE TITLE
Maybe.subscribeWith() has incorrect documentation

### ISSUE THREAD

**Issue by dimsuz** [ReactiveX/RxJava#5642]
`Maybe.subscribeWith()` [documentation ](https://github.com/ReactiveX/RxJava/blob/v2.1.5-RC4/src/main/java/io/reactivex/Maybe.java#L3771-L3799) suggests that it returns a `Disposable` and contains this example (translated to Kotlin):

```kotlin
    val source = Maybe.just(1)
    val composite = CompositeDisposable()
    val ms = object : MaybeObserver<Int> {
      // ...
    }
    composite.add(source.subscribeWith(ms))
```

This code does not compile, because `MaybeObserver` does not implement `Disposable`.

Should the documentation suggest to use `DisposableMaybeObserver` here?
If yes, I can submit a PR.

**Comment by akarnokd** [comment]
Yes, `DisposableMaybeObserver` should be there. PR welcome.

**Comment by dimsuz** [comment]
Closing as PR got merged.
