### ISSUE TITLE
2.x: wiki has some broken links

### ISSUE THREAD

**Issue by ctranxuan** [ReactiveX/RxJava#5643]
Hi,
Really a tiny tiny issue but some links are broken in the ToC of the page https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0. 
Clicking on the following links in the ToC of the page:

- Subjects and Processors
- Other classes

redirects to the Home page (https://github.com/ReactiveX/RxJava/wiki) instead of the proper section.
Thanks for this great lib!

**Comment by akarnokd** [comment]
Thanks. Fixed.
