### ISSUE TITLE
3.x: drop CHANGES.md

### ISSUE THREAD

**Issue by akarnokd** [ReactiveX/RxJava#5646]
It has become somewhat of an inconvenience to update `CHANGES.md` before pasting in the release text into the GitHub's own release page, causing a full build before the release build just for that single file.

I don't remember exactly why `CHANGES.md` was introduced but my assumption is that searching inside it via CTRL+F is simpler than searching within the [Releases](https://github.com/ReactiveX/RxJava/releases) tab.

Options:

- Keep it.
- Drop it.
- Use a dedicated wiki page instead.

**Comment by artem-zinnatullin** [comment]
Yis! Keeping changelog file under version control always feelt wrong, releasing and versioning is much easier when it's decoupled from regular code history, branching and PRs routine.

Sometime ago we've decided to just put a [giant link to Releases page in changelog files](https://github.com/gojuno/koptional/blob/master/CHANGELOG.md).

I only see few non-major benefits of keeping changelog under version control:

1. Someone can submit a PR fixing small typos/etc, but then they have to be repeated for releases page
1. If for some reason we'll need to migrate git hosting to lets say GitLab, migrating releases page will be a manual work
1. Releases could potentially be lost in case of GitHub failure
1. Offline access

All of them except №1 could be somewhat solved by duplicating changelog in version tag message.

---

So I'd propose to only leave a link in the changelog file that'll point to Releases page and maintain changelog on releases page (and optionally in git tag messages).

**Comment by akarnokd** [comment]
Closing via #6533.
