### ISSUE TITLE
How to delay emission conditionally if then came under x time?

### ISSUE THREAD

**Issue by ursusursus** [ReactiveX/RxJava#5650]
_Hi, this is UI related, loading of data on screen start.
I am showing a progressbar while data is being loaded. Sometimes data can be loaded too quickly and progressbar just flashes and creates a jarring ux effect._

**Is there a way to delay emissions conditionally if they arrive under x ms? If they arrive after the x time, then let them through immediately**. Ive looked into delay or buffer but can figure out how to work in that condition.

Thanks

**Comment by akarnokd** [comment]
There is an extension operator [spanout](https://github.com/akarnokd/RxJava2Extensions#flowabletransformersspanout) for this.

**Comment by ursusursus** [comment]
thank you
