### ISSUE TITLE
RxJava 1.3 -- timeout not unsubscribing from original observable

### ISSUE THREAD

**Issue by sfitts** [ReactiveX/RxJava#5657]
Version -- 1.3.0 (did not see any release notes in the subsequent 1.3.x releases about this).

Not sure if this is the expected behavior or not, but when I use the operator:

```
timeout(long timeout, TimeUnit timeUnit, Observable<? extends T> other)
```

it seems that if the timeout occurs and we switch to mirroring the `other` observable the operator does not unsubscribe from the original observable.  Based on the documentation I was expecting that this would essentially execute a "switch" like behavior, which would result in the original observable being unsubscribed.

Here is some code that demonstrates what I'm seeing:

```
        Subject<Long, Long> subject = PublishSubject.create();
        Observable<Long> initialObservable = subject.share().map(value -> {
            System.out.println("Received value " + value);
            return value;
        });

        Observable<Long> timeoutObservable = initialObservable.map(value -> {
           System.out.println("Timeout received value " + value);
           return value;
        });

        TestSubscriber<Long> subscriber = new TestSubscriber<>();
        initialObservable.timeout(1, TimeUnit.SECONDS, timeoutObservable).subscribe(subscriber);
        subject.onNext(5L);
        Thread.sleep(1500);
        subject.onNext(10L);
        subject.onCompleted();

        subscriber.awaitTerminalEvent();
        subscriber.assertNoErrors();
        subscriber.assertValues(5L, 10L);
```

Here is the output:

```
Received value 5
Received value 10
Received value 10
Timeout received value 10
```

I was only expecting one `Received value 10`.

**Comment by sfitts** [comment]
Inserting `this.unsubscribe();` before line 200 in `OperatorTimeoutBase` gives me the behavior I was expecting.  Of course I'm not enough of an RxJava internals expert to know what other, less desirable side effects this might have (though naively it seems that once the timeout subscriber marks itself as terminated, it pretty much gets out of the way).

**Comment by akarnokd** [comment]
Thanks for reporting. This seems to be a bug somewhere in that operator which I can't pinpoint, the 1.x architecture is awkward. See #5660 for the proposed fix.

**Comment by akarnokd** [comment]
Closing via #5660.
