### ISSUE TITLE
Exception thrown on Scheduler.Worker thread. Add `onError` handling.

### ISSUE THREAD

**Issue by a8453770** [ReactiveX/RxJava#5658]
Exception java.lang.IllegalStateException: Exception thrown on Scheduler.Worker thread. Add `onError` handling.
rx.a.b.b$b.run (SourceFile:112)
android.os.Handler.handleCallback (Handler.java:751)
android.os.Handler.dispatchMessage (Handler.java:95)
android.os.Looper.loop (Looper.java:154)
android.app.ActivityThread.main (ActivityThread.java:6682)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:1520)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1410)
arrow_drop_down
Caused by rx.b.f:
rx.internal.util.d$a.a (SourceFile:386)
rx.internal.util.d$a.call (SourceFile:383)
rx.internal.util.b.onError (SourceFile:44)
rx.e.a.a (SourceFile:153)
rx.e.a.onError (SourceFile:115)
rx.internal.a.w$a.a (SourceFile:273)
rx.internal.a.w$a.call (SourceFile:216)
rx.a.b.b$b.run (SourceFile:107)
android.os.Handler.handleCallback (Handler.java:751)
android.os.Handler.dispatchMessage (Handler.java:95)
android.os.Looper.loop (Looper.java:154)
android.app.ActivityThread.main (ActivityThread.java:6682)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:1520)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1410)
arrow_drop_down
Caused by rx.b.c:
rx.internal.a.w$a.onNext (SourceFile:160)
rx.e.b.onNext (SourceFile:91)
rx.e.c.onNext (SourceFile:94)
rx.internal.a.ac$1.onNext (SourceFile:45)
rx.internal.a.aa$1$1.onNext (SourceFile:53)
rx.internal.a.r$1.call (SourceFile:52)
rx.g$a$1.call (SourceFile:137)
rx.internal.c.b$a$2.call (SourceFile:189)
rx.internal.c.h.run (SourceFile:55)
java.util.concurrent.Executors$RunnableAdapter.call (Executors.java:428)
java.util.concurrent.FutureTask.run (FutureTask.java:237)
java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run (ScheduledThreadPoolExecutor.java:272)
java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1133)
java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:607)
java.lang.Thread.run (Thread.java:762)

**Comment by a8453770** [comment]
????

**Comment by akarnokd** [comment]
> ????

My thoughts exactly. Dumping just a stacktrace, especially if it is obfuscated, is not a valid issue and how do you expect us to figure out what `Caused by rx.b.c:` is?

**Comment by henrypan** [comment]
What's the suggested action to fix this error?

Tks

**Comment by bigman212** [comment]
> What's the suggested action to fix this error?
> 
> Tks

Firstly, look in the mapping.txt at "/your_project_place/build/outputs/mapping/release/" and find what `rx.a.b.b$b.run ` mean.
