### ISSUE TITLE
Cancel task without unsubscribe();

### ISSUE THREAD

**Issue by smith-prnd** [ReactiveX/RxJava#5659]
I'm using rxjava 2.1.0

Is there a way to cancel the currently running job?
Of course, it can be cancel by unsubscribing() [like this](https://github.com/square/retrofit/issues/2147).
However, there are cases where need to cancel only tasks, not unsubscribe.

**Comment by akarnokd** [comment]
Depends on what you mean by currently running job. RxJava is dataflow based so there are no user facing "jobs" but flows that have `Disposable`s returned by the lambda-`subscribe()` methods for example.

**Comment by smith-prnd** [comment]
oh, that's great. 
I'll close it.
