### ISSUE TITLE
3.x: Disposable changes

### ISSUE THREAD

**Issue by akarnokd** [ReactiveX/RxJava#5665]
#### Introduction

One of my regrets is the introduction of `Disposable.isDisposed()` which had to be implemented on all components regardless if the disposed state exposure was necessary or not. In practice, only a handful container-like types require `isDisposed`: `BooleanDisposable`, `CompositeDisposable`, `ObservableEmitter`, etc.

Apart from making such use sites hard to cover with unit tests (i.e., one needs to get to the inner parts of the operator in question), it requires the implementor to be stateful since `dispose()` should lead to `isDisposed` true. Having `isDisposed` has the same problems as `Future.isDone()`: one has to loop or otherwise come back to it regularly.

How should one now if a flow terminated then? By reacting to `onError`, `onComplete` or `onSuccess` and/or by using `Observer` subclasses that decide to expose an `isDisposed`.

#### Propositions

- Drop `isDisposed` from the main `Disposable` interface.
- Introduce a separate interface, e.g., `IsDisposed` or `DisposableIntrospection`, that can be used on the container types.

#### If JDK 9 is targeted

Java 7 introduced the `AutoCloseable` interface with a single `void close() throws Exception` method. If JDK 9 is chosen as a target, the `Disposable` interface could extend `AutoCloseable` (and dropping the throws part) which makes it usable in try-with-resources constructs.

```java
interface Disposable extends AutoDisposable {
    void close();
}
```

**Comment by martinandersson** [comment]
lol I'm very sorry but I fail to see the problem. Firstly, it appears that even if you in hindsight know that it was hard or a lot of work to implement `isDisposed` for a comparable "small" payback, the method is still implemented and functional? So why drop something that is already there and working?

But then, the suggestion is actually not to drop it, simply to move it into another type.  Again, what are we trying to accomplish, make it easier for future implementations to be written? Maybe/potentially let 2-3 coders in the future save a few keystrokes on their keyboard by skipping the implementation versus making the type system more complex and harder for thousands of end-users to understand and use?

I have certainly not groked the whole picture, I am sure of. In the end, all I am looking for at this point is a bit more clarification and motivation. It should probably be added that I just started learning RxJava lololol.

I think an interface named `IsDisposed` is a bit awkward. `myDisposable instanceof IsDisposed` sort of indicates that the instance is already disposed; disposed = true, which obviously doesn't have to be the case. I have long and hard tried to come up with an alternative. I hate being the one that says "the name A suck but I have no better idea". I think this could be a "smell", indicating that we're barking up the wrong tree here. If we can not find a suitable name for such type, then that is the Gods telling us we should stay away from creating such a type! =) See what I'm saying?

Anyways, just my five cents.

**Comment by lxsmnsyc** [comment]
any plans for this?

**Comment by akarnokd** [comment]
This is a tough one as it breaks everyone using `Disposable.isDisposed()` in some fashion. 

The primary concern is RxAndroid, although I have a feeling they would didn't like it much to begin with: https://github.com/ReactiveX/RxAndroid/search?q=isdisposed&unscoped_q=isdisposed

The maintenance problem is that removing them from RxJava is a considerable amount of work and if it doesn't work out, restoring it would be equally cumbersome.

**Comment by akarnokd** [comment]
After careful considerations, this change won't happen. It would break everybody due to how many depend on `isDisposed` being available everywhere. We may revisit this for RxJava 4 where switching to JDK 9+ would require separate packaging almost certainly (modules).
