### ISSUE TITLE
2.x improve delay method

### ISSUE THREAD

**Issue by JSpiner** [ReactiveX/RxJava#5674]
The [delay function](http://reactivex.io/RxJava/2.x/javadoc/io/reactivex/Observable.html#delay-io.reactivex.functions.Function-) runs delay after emit.
However, if emit takes a long time, it may not need delay at times.

```java
Observable.create(
    emitter -> {
        emitter.onNext( networkRequest() );      // if it takes 10 seconds,
    }
).delay(1000, TimeUnit.MILLISECONDS)      
.subscribe(networkHandling);       // it will be called in 11 seconds, but it don't have to wait long.
```

So, I want to make the `delayIn` function including time to emit.(like below)
How about this?

```java
Observable.create(
    emitter -> {
        emitter.onNext( networkRequest() );      // This takes 0~5 seconds.
    }
).delayIn(1000, TimeUnit.MILLISECONDS)      
.subscribe(networkHandling);       //If emit is less than 1 second, wait until 1 second. If not, it is called immediately.

/*
emit   delay  subscriber
0ms    1000ms 1000ms
100ms  900ms  1000ms
500ms  500ms  1000ms
1000ms 0ms    1000ms
1100ms 0ms    1100ms
2000ms 0ms    2000ms
*/
```

I think this function can be useful for UI tasks.

**Comment by JakeWharton** [comment]
You can use zip with a timer instead. Delay is a fixed stage that delays
emissions.

**Comment by JSpiner** [comment]
@JakeWharton 
```java
        Observable.zip(
                Observable.create(
                        emitter -> emitter.onNext(networkRequest())
                ),
                Observable.timer(1000, TimeUnit.MILLISECONDS),
                (response, __) -> response
        ).subscribe(networkHandling);       
//fixed that @akarnokd said.
```

Is this what you said?
This is a very smart way. And, This works 100% correctly. 
But does not it look too complicated?
If `dealyIn` does not hurt the style of rxjava, I think it can added. :)

**Comment by akarnokd** [comment]
This is an uncommon behavior for RxJava to consider it as a dedicated operator, plus as Jake indicated, can be solved locally with a short set of operators.

Also you don't have to apply `delay()` again once you zipped.

**Comment by smith-prnd** [comment]
good point, thanks!

**Comment by JSpiner** [comment]
good point, thanks!
