### ISSUE TITLE
2.x: Scheduler implement a Clock interface

### ISSUE THREAD

**Issue by davidmoten** [ReactiveX/RxJava#5678]
I have frequently passed through a `Scheduler` instance to a class that only uses the `now` method (and does no scheduling). In the interests of clarity in my code (and to leverage compile time checking) I'd prefer to pass through a `Clock` instance (without creating another object to wrap the Scheduler). Would you mind if I submitted a PR with the addition of a new interface Clock that would be implemented by Scheduler?

**Comment by artem-zinnatullin** [comment]
Well that sounds like wrong abstraction, scheduler shouldn't be source of time, it should depend on some source of time

See #3295

**Comment by akarnokd** [comment]
Standard `Scheduler`s return `System.currentTimeMillis()` and the `TestScheduler` returns an artificial value. Why is a wrapper so costly for you?

**Comment by davidmoten** [comment]
The wrapper is not costly, just more code to write or a dependency to add. If we had the interface we can use it internally as well, but this is just a convenience request that I'm assuming comes at little cost (?) and doesn't break apis.

**Comment by akarnokd** [comment]
I'm not fond of the idea. We have no use for this type of abstraction in RxJava and you'd still have to use RxJava as dependency to access such abstraction. You could simply not fully implement a `Scheduler`, making the other methods throw `UnsupportedOperationException`.

**Comment by davidmoten** [comment]
Ok, I'll close
