### ISSUE TITLE
confusion about onError in RxJava

### ISSUE THREAD

**Issue by wytings** [ReactiveX/RxJava#5679]
throwing an exception in _onSuccess_ ,RxJava  doesn't call _onError_ when using **Single**,
but it will call _onError_ if throwing an exception in _onNext_ when using **Observable** or **Flowable**

I have read the source code and found that RxJava  catches Exceptions for **Observable** and **Flowable**  when processing _onNext_. 
If _onNext_ throw exception, RxJava will call _onError_. 
If _onError_ throw exception, then let's crash.

So what has prompted RxJava to catch Exceptions for **Observable** and **Flowable**  , but not including **Single** and **Completable** ? 

Why can't they receive equal treatment? do we have any concerns ?

I have searched a lot and haven't found  any reasonable answers.

**Comment by akarnokd** [comment]
This has been explained quite a lot of times. Please use the search box in the issue list.

The Single protocol defines onSuccess as a terminal event. Similarly, an onError or onComplete crash is not routed back to onError. Use Observable if your solo value may lead to a crash.

**Comment by wytings** [comment]
OK,thank you for explanation...
