### ISSUE TITLE
2.x: Inefficient get/set checks in ReferenceDisposable?

### ISSUE THREAD

**Issue by rjuang** [ReactiveX/RxJava#5684]
Just browsing the code and noticed this code snippet inside ReferenceDisposable in 2.x branch:
  ```
  @Override
    public final void dispose() {
        T value = get();
        if (value != null) {
            value = getAndSet(null);
            if (value != null) {
                onDisposed(value);
            }
        }
    }
```

Wouldn't it be more efficient to do?

```
        T value = getAndSet(null);
        if (value != null) {
           onDisposed(value);
        }
```

**Comment by akarnokd** [comment]
The first approach saves the cost of an atomic exchange when it is invoked multiple times and/or concurrently. It depends on how pessimistic one is about the idempotent invocation. Performance wise, 1 and 2 invocations are indistinguishable, 3 or more invocations benefit from the first structure greatly.

**Comment by JakeWharton** [comment]
Do we have any idea of which case we're optimizing for here? I'm tempted to switch to the second to optimize for the active subscription case instead of the disposed case but I don't have any data to back it up, just feeling.

**Comment by rjuang** [comment]
Just a rough check running 100 million repetitions of AtomicReference.get vs AtomicReference.getAndSet.

AtomicReference.get averages about 20ns  and
AtomicReference.getAndSet averages around 26ns.

So, you would save about 6 ns per operation on average using get vs getAndSet  if get() returns null.

**Comment by akarnokd** [comment]
[Here is the JMH benchmark](https://gist.github.com/akarnokd/0dd5867c18aa3fd111377019207ea039) and results on my i7 4770K, Windows 7 x64, Java 8u152, JMH 1.19 (Nanosecond sampling on Windows is quite hectic, throughput is more reliable.)

```
Benchmark                Mode  Cnt          Score         Error  Units
TerminalAtomics.GASx1   thrpt    5  121176363,632 � 2059486,908  ops/s
TerminalAtomics.GASx2   thrpt    5   71435031,790 �  927630,149  ops/s
TerminalAtomics.GASx3   thrpt    5   51705827,414 �  714457,930  ops/s
TerminalAtomics.GASx4   thrpt    5   41688389,835 �  163648,988  ops/s
TerminalAtomics.GGASx1  thrpt    5  107360672,616 � 1689543,000  ops/s
TerminalAtomics.GGASx2  thrpt    5  101173686,808 � 1448503,467  ops/s
TerminalAtomics.GGASx3  thrpt    5   95889610,394 �  312943,270  ops/s
TerminalAtomics.GGASx4  thrpt    5   95766140,156 �  816690,557  ops/s
```

![image](https://user-images.githubusercontent.com/1269832/31854671-3b0dd8ce-b69d-11e7-9903-2631b11b29de.png)

**Comment by JakeWharton** [comment]
Is that for when the value is already null? Or when it's non-null?

**Comment by akarnokd** [comment]
> Performance wise, 1 and 2 invocations are indistinguishable

There was an benchmark I did a few years back (which I can't find now) where this was the conclusion then.

> Is that for when the value is already null? Or when it's non-null?

`count` indicates how many times the snippet is invoked, starting from a non-null value. Subsequent invocations find it null.

```java
@Benchmark
    public void GGASx4(Blackhole bh) {
        ref.lazySet(o);
        getGetAndSet(bh);
        getGetAndSet(bh);
        getGetAndSet(bh);
        getGetAndSet(bh);
    }
```

Since disposing brings the container into a terminal state, it has to be reset on each invocation of the benchmark method. This has the same up-front cost for each method.

**Comment by akarnokd** [comment]
Here are the use places for getAndSet: https://github.com/ReactiveX/RxJava/search?utf8=%E2%9C%93&q=getAndSet&type=

**Comment by JakeWharton** [comment]
Ah, got it. I'm just trying to discern usage patterns though as to whether that's a common case or a rare case.

**Comment by akarnokd** [comment]
I'd think the prior question is how often one disposes a container in practice? Second, do we want the trade-off of that 11% overhead for a one time cancellation for the 40% overhead of a double cancellation?

**Comment by akarnokd** [comment]
Looks like this question has been answered. If you have further input on the issue, don't hesitate to reopen this issue or post a new one.
