### ISSUE TITLE
Need JavaDoc for offline work in Netbeans. Where can I find the zip?

### ISSUE THREAD

**Issue by chjan** [ReactiveX/RxJava#5692]

**Comment by akarnokd** [comment]
Do you have maven/gradle? That should download the javadoc for you. Otherwise you have to manually download it from maven:

http://central.maven.org/maven2/io/reactivex/rxjava/1.3.3/rxjava-1.3.3-sources.jar
http://central.maven.org/maven2/io/reactivex/rxjava2/rxjava/2.1.6/rxjava-2.1.6-sources.jar

**Comment by akarnokd** [comment]
http://central.maven.org/maven2/io/reactivex/rxjava/1.3.3/rxjava-1.3.3-javadoc.jar
http://central.maven.org/maven2/io/reactivex/rxjava2/rxjava/2.1.6/rxjava-2.1.6-javadoc.jar

**Comment by akarnokd** [comment]
Looks like this question has been answered. If you have further input on the issue, don't hesitate to reopen this issue or post a new one.
