### ISSUE TITLE
2.x: BaseObserver.assertNothing

### ISSUE THREAD

**Issue by arturdryomov** [ReactiveX/RxJava#5693]
Just want to piggyback on #5555.

`assertOnlyValues` became very useful in our team, basically freeing us from writing multiple tests to check that the stream emitted values and, at the same time, did not produce errors or completion.

`assertNothing` should do pretty much the same thing as `assertOnlyValues` being an alias to other checks.

```java
public final U assertNothing() {
    return assertSubscribed()
        .assertNoValues
        .assertNoErrors()
        .assertNotComplete();
}
```

**Comment by vanniktech** [comment]
Can't you use `assertResult()`?

**Comment by arturdryomov** [comment]
Not exactly, we want to check that nothing was emitted, no error and no complete were passed as well.

**Comment by vanniktech** [comment]
Ah okay got it. Didn't see the `assertNotComplete`. I like the idea. I'm +1 for the operator.

**Comment by akarnokd** [comment]
It is called `assertEmpty`.

**Comment by arturdryomov** [comment]
Great, thanks! I guess we learn something every day :-)
