### ISSUE TITLE
2.x: Improper class name of ObservableFromCompletableTest

### ISSUE THREAD

**Issue by ShengChangYang** [ReactiveX/RxJava#5698]
The class `io.reactivex.internal.operators.observable.ObservableFromCompletableTest` only tests `Observable.fromCallable`. Why the class name is **Completable**?

**Comment by akarnokd** [comment]
Probably just a misnamed test file. Would you like to fix it?

**Comment by ShengChangYang** [comment]
Because there already had a class `io.reactivex.internal.operators.observable.ObservableFromCallableTest`.
So, what the new name you recommend?
Or just merge the test cases into `ObservableFromCallableTest`?

**Comment by akarnokd** [comment]
Just copy over the test methods.
