### ISSUE TITLE
2.x: Got exception from RxJavaPlugins after disposed

### ISSUE THREAD

**Issue by ShengChangYang** [ReactiveX/RxJava#5700]
Example:
```java
final Disposable d = Observable
    .fromCallable(new Callable<Object>() {
        @Override
        public Object call() throws Exception {
            // Long task that can't be interrupted
            // and execute more than 1 second.
            throw new IllegalStateException();
        }
    })
    .subscribeOn(Schedulers.io())
    .subscribe();
Thread.sleep(1000);
d.dispose();
```

I got the `IllegalStateException` from `RxJavaPlugins` because `ObservableFromCallable` check the **disposed** state then pass to `RxJavaPlugins`
https://github.com/ReactiveX/RxJava/blob/e92822cd4e35f481e506ce7765d2eba67ed075e3/src/main/java/io/reactivex/internal/operators/observable/ObservableFromCallable.java#L45-L49

Have same issue:
 * `ObservableFromCallable`
 * `MaybeFromCallable`

No such issue:
 * `CompletableFromCallable`
 * `SingleFromCallable`

Similar issue:
 * `FlowableFromCallable`
`FlowableFromCallable` doesn't check **disposed** state before calling `Subscriber#onError()`.
https://github.com/ReactiveX/RxJava/blob/d3455d0c9d57d522c31b5c25af83e8f2b8df12b6/src/main/java/io/reactivex/internal/operators/flowable/FlowableFromCallable.java#L38-L42
And `LambdaSubscriber` pass exception to `RxJavaPlugins` after disposed.
https://github.com/ReactiveX/RxJava/blob/99a620a38c38e5010dc5bcc338a13555b3ccb727/src/main/java/io/reactivex/internal/subscribers/LambdaSubscriber.java#L76-L86

So, what's the expected behavior for operators?
Should we pass the exception to `RxJavaPlugins` even client didn't care the result anymore (**disposed**)?

**Comment by akarnokd** [comment]
This is a feature. RxJava can't tell if an exception is relevant to you or not if it happens outside the normal Observer lifecycle, thus there is a global error handler that will receive them:

https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0#error-handling

**Comment by ShengChangYang** [comment]
Got it. Thanks for your quick answer!!
