### ISSUE TITLE
2.x: zipWith emits all values of the second observable when inside retryWhen

### ISSUE THREAD

**Issue by carlosefonseca** [ReactiveX/RxJava#5701]
When zipping two observables, when the first terminates, the second one is also terminated without emitting any other values, so: (this is kotlin, btw)

```kotlin
Observable.range(0, 2).zipWith(
    Observable.range(10, 15).doOnNext { println(">$it") }
).subscribe { println(it) }
```

outputs:

    >10
    (0, 10)
    >11
    (1, 11)

But if I do the same inside a `retryWhen` operator, the second observable goes all the way (this is based on the [`retryWhen` example from the docs](http://reactivex.io/RxJava/2.x/javadoc/io/reactivex/Observable.html#retryWhen-io.reactivex.functions.Function-)).

```kotlin
val rangeObservable = Observable.rangeLong(1, 3)
    .doOnNext { println(it) }
    .doOnComplete { println("done") }

Observable.create<String> { s ->
    println("subscribing")
    s.onError(RuntimeException("always fails"))
}.retryWhen({ attempts ->
    attempts.zipWith(rangeObservable, { n, i -> i }).flatMap({ i ->
        println("delay retry by $i second(s)")
        Observable.timer(i, TimeUnit.SECONDS)
    })
}).blockingSubscribe{println(it)}
```

I get:

    1
    2
    3
    done
    subscribing
    delay retry by 1 second(s)
    subscribing
    delay retry by 2 second(s)
    subscribing
    delay retry by 3 second(s)
    subscribing

The `rangeObservable` emits all values and completes when subscribing but that's not what the `zipWith` operator does regularly. I was playing with an infinite observable that generated delays but it would just block the program since it never terminated.

Is this a bug? I didn't see any reference to this behaviour on the docs of these operators.

I'm using RxJava 2.1.6.

Thanks.

**Comment by akarnokd** [comment]
This is the expected behavior of an `Observable`-based `zip` operator. There is no backpressure and a synchronous source like `range` will emit all of its values as soon as it is subscribed to; in this case as part of the preparation of the retryWhen operator. The zip will buffer events in an unbounded manner and match it one by one with the Throwable signal.

Consider using `Flowable` and then [`zip` with bufferSize](http://reactivex.io/RxJava/2.x/javadoc/io/reactivex/Flowable.html#zipWith-org.reactivestreams.Publisher-io.reactivex.functions.BiFunction-boolean-int-) parameter set to 1.

**Comment by carlosefonseca** [comment]
Yep, using that one did what I expected in the beginning.
Should I convert the `attempts` to `Flowable` and convert the result back to `Observable`? Seems a bit weird but it works fine.

```kotlin
Observable.create<String> { s ->
    println("subscribing")
    s.onError(RuntimeException("always fails"))
}.retryWhen({ attempts ->
    Flowable.zip(attempts.toFlowable(BackpressureStrategy.BUFFER), rangeFlowable, BiFunction<Throwable, Long, Long> { _, i -> i }, false, 1).flatMap({ i ->
        println("delay retry by $i second(s)")
        Flowable.timer(i, TimeUnit.SECONDS)
    }).toObservable()
}).blockingSubscribe({ println(it) }, { it.printStackTrace() })
```

On the other side, then doing `retryWhen` with a `Single`, it's already `Flowable`.
```kotlin
Single.create<String> { s ->
    println("subscribing")
    s.onError(RuntimeException("always fails"))
}.retryWhen({ attempts ->
    Flowable.zip(attempts, rangeFlowable, BiFunction<Throwable, Long, Long> { _, i -> i }, false, 1).flatMap({ i ->
        println("delay retry by $i second(s)")
        Flowable.timer(i, TimeUnit.SECONDS)
    })
}).toObservable().blockingSubscribe({ println(it) }, { it.printStackTrace() })
```

**Comment by akarnokd** [comment]
If the full realization of the range is an issue for you then yes.

**Comment by carlosefonseca** [comment]
I see now what I was doing wrong… zipping two ranges causes the second to emit a subset but using something like `Observable.create` causes the second to emit everything.

```kotlin
Observable.create<String> { s ->
    println("subscribing")
    s.onNext("a")
    s.onNext("b")
    s.onNext("c")
}.zipWith(
    Observable.range(1, 7).doOnNext { println(">$it") }.doOnComplete { println("done") }
).subscribe { println(it) }
```

```
subscribing
>1
(a, 1)
>2
(b, 2)
>3
(c, 3)
>4
>5
>6
>7
done
```

Thanks!
