### ISSUE TITLE
cache() vs replay().autoConnect()

### ISSUE THREAD

**Issue by bnvinay92** [ReactiveX/RxJava#5704]
What's the difference between using

`stream().cache()`

and

`stream().replay().autoConnect()`
?

**Comment by akarnokd** [comment]
Javadoc:
- http://reactivex.io/RxJava/2.x/javadoc/io/reactivex/Observable.html#replay--
- http://reactivex.io/RxJava/2.x/javadoc/io/reactivex/Observable.html#cache--
- http://reactivex.io/RxJava/2.x/javadoc/io/reactivex/observables/ConnectableObservable.html#autoConnect--

StackOverflow:
- https://stackoverflow.com/a/32537190/61158

Dan Lew's blog:
- http://blog.danlew.net/2016/06/13/multicasting-in-rxjava/
