### ISSUE TITLE
2.1.6 Unexpected concatMapEagerDelayError behavior 

### ISSUE THREAD

**Issue by Aschraf** [ReactiveX/RxJava#5707]
Hello,

I have an issue with concatMapEagerDelayError. 

When setting the parameter **tillTheEnd** to true, it works correctly as it waits till the end to send a CompositeException but when set to false, it seems to behave exactly as concatMapEager.

Instead of waiting for the running observables to terminates before sending a composite exception, it stops all of them and causes an UndeliverableException to be thrown.

Here is a code to show the issue:

```java
public class RxIssue {
  public static void main(String[] args) {
    long startTime = System.currentTimeMillis();

    Observable.just(1000L, 2000L, 3000L, 4000L)

        .concatMapEagerDelayError(value ->
                Observable.just(value)
                    .subscribeOn(Schedulers.io())
                    .map(RxIssue::intenseCalculation)
                    .doOnError(throwable -> System.out.println(throwable.getMessage()))
            , 2, 2, false)
        .blockingSubscribe(
            v -> System.out.println("Received value : " + v),
            t -> System.out.println("Received normal error : " + t.getMessage())
        );


    System.out.println("Finished on : " + (System.currentTimeMillis() - startTime));
  }

  private static long intenseCalculation(long value) throws Exception {
    try {
      Thread.sleep(value);
    } catch (InterruptedException e) {
//      e.printStackTrace();
    }
    throw new Exception("Error at " + value);
  }

}
```

I don't think that's the intended behavior, is it?

**Comment by akarnokd** [comment]
With `concatMapEagerX`, the main source can also fail. `tillTheEnd` `false` will fail when switching between sources whereas the `concatMapEager` will fail as soon as the main source or an inner source fails. If multiples of them fail, the exceptions can't be emitted and end up as `UndeliverableException`.

So what you experience is a legal outcome.

**Comment by Aschraf** [comment]
The documentation states : 
`
if true, exceptions from the current Observable and all the inner ObservableSources are delayed until
                    all of them terminate, if false, exception from the current Observable is delayed until the
                    currently running ObservableSource terminates
`

It's not clear that "true" would handle all errors while "false" will only handle the first errors and throws UndeliverableException afterwards.

**Comment by akarnokd** [comment]
See [error handling](https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0#error-handling) that defines the general behavior.

**Comment by Aschraf** [comment]
Thanks, It's too bad that I don't see the difference between ErrorModes IMMEDIATE and BOUNDARY in this case. 
The behavior seems strange for me but I'll try to find a workaround.

**Comment by akarnokd** [comment]
When multiple sources are involved, the signals can race and get interleaved in various ways. Therefore, there is a possibility that two modes may appear to act the same just because the timing.

**Comment by Aschraf** [comment]
I see. 
Do you know if there is any other way with concatMapEager and without using ErrorHandler to wait for the concurrent batch to finish before throwing an exception?

**Comment by akarnokd** [comment]
What do you mean by "current batch"?

**Comment by Aschraf** [comment]
It's, in this example, the 2 concurrent ObservableSources that concatMapEager subscribe to.

**Comment by akarnokd** [comment]
`concatMapEager` prefetches so once one source completes, it fetches and starts the next one. You have to use `buffer(2)`, then `concatMap` that has an inner `concatMapEagerDelayError`:

```java
source
.buffer(2)
.concatMap(v -> 
       Observable.fromIterable(v)
       .concatMapEagerDelayError(w ->
            Observable.just(w)
            .subscribeOn(Schedulers.io())
            .map(RxIssue::intenseCalculation)
            .doOnError(throwable -> System.out.println(throwable.getMessage()))
       , true)
);
```

**Comment by Aschraf** [comment]
That's actually a nice solution. Thank you very much.
