### ISSUE TITLE
2.x: retryWhen resubscribes too much

### ISSUE THREAD

**Issue by Oyashirox** [ReactiveX/RxJava#5714]
This class is a ViewModel in an Android MVVM, the corresponding View (the Activity) subscribes to `data` using a LiveData.
I use retryWhen as follow (GetEvents is a Single that emit error each time for now) : 
```kotlin
internal class AgendaListViewModel(getEvents: GetEvents) : ViewModel() {

    private val stream = getEvents.execute()
            .doOnSubscribe { loading.value = true }
            .doFinally { loading.value = false }
            .doOnError { error.value = it.localizedMessage; Timber.d("error event") }
            .retryWhen { error -> error.flatMap({ retryEvent.toFlowable(BackpressureStrategy.LATEST) }) }

    private val retryEvent = PublishSubject.create<Boolean>()

    //region state
    val loading: MutableLiveData<Boolean> = MutableLiveData<Boolean>().apply { value = false }

    val error = SingleLiveEvent<String>()

    val data: LiveData<List<Event>>
        get() = LiveDataReactiveStreams.fromPublisher(stream.toFlowable())

    val selectedEvent: SingleLiveEvent<Event> = SingleLiveEvent()
    //endregion

    //region Events
    fun selectedEvent(event: Event) {
        selectedEvent.value = event
    }

    fun refresh() {
        if (error.value != null) {
            retryEvent.onNext(true)
        }
    }
    //endregion
}
```

- First error occurs : Logcat displays `error event` correctly. 
- Calling `refresh` also works : the logcat display another `error event`, proving that it resubscribed
- Calling `refresh` a second time is problematic : I see two new `error events`, where I expect only one
- every subsequent call double the number of logs : 4, then 8, then 16...

Is it the correct behavior or am I missing something ?

**Comment by akarnokd** [comment]
You `flatMap` onto the same `Subject` which keeps getting more and more observers, thus every `onNext` on it will trigger multiple signals that `flatMap` merges into one sequence of multiple retries. You should use `zipWith` instead.

```kotlin
.retryWhen { error -> 
    error.zipWith(
        retryEvent.toFlowable(BackpressureStrategy.LATEST), 
        { (a, b) -> b} ) 
}
```
