### ISSUE TITLE
Is it possible to change the prefetch/buffersize of the Flowable.scan operator()? 

### ISSUE THREAD

**Issue by bnvinay92** [ReactiveX/RxJava#5720]
I want to use scan() with a prefetch of 1 in one stream, without overriding the global default for all operators.

**Comment by akarnokd** [comment]
It is not supported currently. You could apply `rebachRequests(1)` before `scan` as workaround.

**Comment by bnvinay92** [comment]
`rebatchRequests(1)` does not seem to do the trick. I'm still learning about backpressure so I could be way off but from my understanding since `scan()` requests for 127 items, `rebatchRequests()` does not apply the backpressure from `concatMap()`.

```
scrolledToEndOfScreenEvent().toFlowable(BackpressureStrategy.DROP)
        .doOnNext(s -> Timber.w("Scroll Event"))
        .doOnRequest(req -> Timber.w("Reba request: %s", req))
        .rebatchRequests(1)
        .doOnRequest(req -> Timber.w("Scan request: %s", req))
        .scan(1, (page, ignored) -> page + 1)
        .doOnRequest(req -> Timber.w("CMap request: %s", req))
        .concatMap(page -> fetchMoviesFromApi(page).subscribeOn(Schedulers.io())
            .doOnSubscribe(s -> Timber.w("Loading: %s", page))
            .doFinally(() -> Timber.w("Done: %s", page)), 1)
        .observeOn(AndroidSchedulers.mainThread())
        .subscribe(movies -> moviesAdapter.addMovies(movies));
```

I'm trying to implement infinite pagination. `scrolledToEndOfScreenEvent()` will fire multiple times when you reach the edge of the screen. I want to take an emission from this stream only when `fetchMoviesFromApi(page)` is not emitting and ignore the rest. Extra emissions from `scrolledToEndOfScreenEvent()` are not being dropped.
```

    CMap request: 1
    CMap request: 1
    Loading: 1
    Scan request: 127
    Reba request: 1
    Done: 1
    CMap request: 1
    Loading: 2
    Reba request: 1
    Scroll Event
    Scroll Event
    Reba request: 1
    Scroll Event
    Reba request: 1
    Scroll Event
    Reba request: 1
    Scroll Event
    Reba request: 1
    Scroll Event
    Reba request: 1
    Scroll Event
    Reba request: 1
    Scroll Event
    Reba request: 1
    CMap request: 1
    Loading: 3
    Done: 2
    CMap request: 1
    Loading: 4
    Done: 3
    CMap request: 1
    Loading: 5
    Done: 4
    CMap request: 1
    Loading: 6
    Done: 5
    CMap request: 1
    Loading: 7
    Done: 6
    CMap request: 1
    Loading: 8
    Done: 7
    CMap request: 1
    Loading: 9
    Done: 8
    Done: 9
```

**Comment by akarnokd** [comment]
Try `flatMap` with `maxConcurrency=1` instead of `concatMap`. `concatMap` will prefetch one extra item from upstream before the current one completes. `flatMap` will only fetch the next upstream item if the current one actually completed.

**Comment by bnvinay92** [comment]
```
private int page = 0;
processor
        .doOnNext(s -> Timber.w("pre"))
        .startWith(new Object())
        .onBackpressureDrop()
        .doOnNext(s -> Timber.w("post"))
        .flatMap(__ -> fetchMoviesFromApi(++page).subscribeOn(Schedulers.io()), 1)
        .observeOn(AndroidSchedulers.mainThread())
        .subscribe(movies -> moviesAdapter.addMovies(movies));
```
^This does drop extra emissions. But it uses a class level field.

```
processor
        .onBackpressureDrop()
        .rebatchRequests(1)
        .scan(1, (page, __) -> page + 1)
        .flatMap(page -> fetchMoviesFromApi(page).subscribeOn(Schedulers.io()), 1)
        .observeOn(AndroidSchedulers.mainThread())
        .subscribe(movies -> moviesAdapter.addMovies(movies));
```

^This does not drop extra emissions. Is this intended?

**Comment by akarnokd** [comment]
Yes. Due to the prefetch in `scan`, it will be ready to process 127 elements after the first triggers the page retrieval. In the field version, flatMap communicates with `onBackpressureDrop` more directly and thus only 1 item at a time can reach it.

**Comment by bnvinay92** [comment]
For now going with a custom operator that [counts emissions](https://gist.github.com/bnvinay92/d510b069a313afc51614de0929073a3c). Any specific reason that we cannot override `scan()`'s prefetch?

**Comment by akarnokd** [comment]
The possibility is there in the operator, it was just not exposed due to lack of an use case so far.

If you want, you can post a PR that exposes this configuration option.

**Comment by bnvinay92** [comment]
It was simpler to implement the behavior I wanted without backpressure using `scrollEvents.distinctUntilChanged(__ -> pageCount)`, which is also a more flexible solution. Given no one needs a `scan()` that takes a `prefetch` I don't think adding the method is worth it.
