### ISSUE TITLE
[RxJava 2.1.0] Single with Cache cancellable behaviour

### ISSUE THREAD

**Issue by BharathMG** [ReactiveX/RxJava#5727]
Hi,
I'm using `Single` in the following way,

           val bleConnection = Single.create({  
             emitter -> // Do some one-time bluetooth connection operation and emit ble connection
             emitter.setCancellable { 
                    // close the ble connection as this single is unsubscribed
             }
           }).cache()

Now I expected `setCancellable` block to run when all the subscribers are disposed. But that block gets called on `onSuccess` or `onError`. So `Single` terminates itself when either success or error happens. But I want to run some cleanup operation when all my subscribers are disposed. How would I do that with `Single`? This can be easily achieved with `Flowable` or `Observable`. But this is essentially `Single` operation (Not a stream, just an one-time connection value). So I thought `Single` is the correct operator to use in this case.

**Comment by akarnokd** [comment]
This is not supported by `Single`. You have to use `Observable.create()`, `share()` and `singleOrError()` to have the final type `Single`. A longer path is similar, given the current `cache()`, convert it via `toObservable()`, `share()` and then `singleOrError()` back.

**Comment by BharathMG** [comment]
Sure, but another problem with `cache()` is,

         val single = Single.create<Boolean>({ emitter ->
         emitter.setCancellable {
              println("CANCELLED")
          }
        }).cache()

        val test1 = single.subscribe()
        val test2 = single.subscribe()
        val test3 = single.subscribe()

        test1.dispose()
        test2.dispose()
        test3.dispose()

        println("ALL DISPOSED")

Here CANCELLED will not be printed as desired. It waits for `Single` to emit some value before cancelling and not for disposal. Is this intended?

**Comment by akarnokd** [comment]
You have to do it through `Observable` as I described:

```java
var single = Observable.create(emitter -> {
    emitter.setCancellable(() -> System.out.println("Cancelled"));
})
.replay()
.refCount()
.singleOrError();
```

**Comment by BharathMG** [comment]
Thank you!
