### ISSUE TITLE
How to execute a flowable dependent from another?

### ISSUE THREAD

**Issue by dafi** [ReactiveX/RxJava#5730]
I want to chain two flowables, when the first one finishes to collect data from the network its result (an array list) must be passed to the second flowable.
The flowables update the UI as described in the scenario shown below, when an error occurs the execution is stopped.

I hope to be more clear as possible adding all details about the expected result and the code I wrote

The scenario

1. flowable-1 makes X network calls (X value depends on some condition COND)
2. every network call returns a list of items (size can vary)
3. the UI shows the count of items (eg. "Retrieved 1 items", "Retrieved 5 items")
4. all calls are done (the condition COND is satisfied)
5. all items collected now must post-processed by flowable-2
6. the UI shows the progress (eg. 'item 1 of 9', 'item 2 of 9', ..., 'item 9 of 9')

A possible expected output should be

    Retrieved 1 item(s) |  
    Retrieved 3 item(s) |- printed inside the doOnNext() 'called' by flowable-1
    Retrieved 5 item(s) |  the array contains 9 items (1 + 3 + 5)

    Item 1 of 9         |
    ...                 |- printed inside the doOnNext() 'called' by flowable-2
    Item 9 of 9         |
      
    Finished            | printed inside the subscribe()

I've used Flowable.generate() to collected items from network calls

```java
public Flowable<List<String>> fetchFromNetFlowable() {
    offset = 0;
    return Flowable.generate(new Consumer<Emitter<List<String>>>() {
        @Override
        public void accept(Emitter<List<String>> emitter) throws Exception {
            List<String> subset = networkCall(offset);
            boolean loadNext = subset.size() > 0;
            offset += subset.size();

            final ArrayList<String> validItems = new ArrayList<>();
            for (String dummy : subset) {
                if (conditionMet(dummy)) {
                    validItems.add(dummy);
                } else {
                    loadNext = false;
                    break;
                }
            }
            if (!validItems.isEmpty()) {
                emitter.onNext(validItems);
            }
            if (!loadNext) {
                emitter.onComplete();
            }
        }
    });
}
```

The second flowable will be used to update UI from onNext() caller

```java
public Flowable secondFlowable(final Iterator<String> iterator) {
    return Flowable.generate((emitter) -> {
        if (iterator.hasNext()) {
            // do some stuff with value
            emitter.onNext(iterator.next());
        } else {
            emitter.onComplete();
        }
    });
}
```

Then I would use both flowables but I don't understard how to make the second dependent from the first one, the `processTheListCallingTheSecondFlowable()` must be called only when `fetchFromNetFlowable()` has finished

```java
public readDataAndProcess() {
    total = 0;
    compositeDisposable.add(postRetrieverRx.readPhotoPosts(blogName)
            .subscribeOn(Schedulers.io())
            .observeOn(AndroidSchedulers.mainThread())
            .toObservable()
            .doOnNext((tumblrPost) -> {
                    total += tumblrPost.size();
                    System.out.println("Retrieved " + total + " items");
            })
            .flatMap((posts) -> Observable.fromIterable(posts))
            .toList() // <--- now I have the single list with all items
            // I don't know how to do
            // processTheListCallingTheSecondFlowable() isn't an rx operator
            // consider it only pseudo code
            .processTheListCallingTheSecondFlowable()
            .subscribe((allPosts) -> System.out.println("Finished")
    );
}
```

**Comment by akarnokd** [comment]
The `flatMap` is a typical dependent continuation operator:

```java
    .toList()
    .flatMapPublisher(list -> processTheListViaFlowable(list))
    .subscribe(/* ... */);
```

**Comment by dafi** [comment]
Oh my God! Is it so simple?!?!
I turned around flatMapXXX for two days without notice this method.

Thanks a lot!!
