### ISSUE TITLE
amerlioration suggestion for parallel flow

### ISSUE THREAD

**Issue by acbeni** [ReactiveX/RxJava#5731]
Hi guys,

   First of all thank you for the wonderful work of creating such an awesome library 🥇 
I just have a small amelioration to sudgestion regading  the beta feature `ParallelFlowable` in version 2.1.6 , and this is regarding the [`public abstract void subscribe(@NonNull Subscriber<? super T>[] subscribers);`](https://github.com/ReactiveX/RxJava/blob/6a44e5d0543a48f1c378dc833a155f3f71333bc2/src/main/java/io/reactivex/parallel/ParallelFlowable.java#L52)
What i am suggesting is to change the signature to `public abstract void subscribe(@NonNull Supplier<Subscriber<? super T>> subscriberProvider);` this would allow me to create more elegant code such as `subscribe(MySubscriber::new)` which is really convenient since we don't have control over parallelism so no need to distinguish the subscribers.

Cheers,

**Comment by akarnokd** [comment]
Unless you are writing an operator for `ParallelFlowable`, there is not much reason to use `subscribe(Subscriber[])`. In addition, there has to be some matching with the non-parallel subscription model which also doesn't use a `Supplier` indirection.

Could you elaborate why do you want to change the existing pattern (and thus we have to modify every parallel operator)? You could just write an utility method:

```java
public static <T> ParallelFlowable<T> subscribeWithSupplier(
        ParallelFlowable<T> source, 
        Supplier<? super T> supplier) {
    Subscriber[] subscribers = new Subscriber[source.parallelism()];
    for (int i = 0; i < subscribers.length; i++) {
        subscribers[i] = supplier.get();
    }
    source.subscribe(subscribers);
    return source;
}

Flowable.range(1, 100)
.parallel()
.to(p -> subscribeWithSupplier(p, TestSubscriber::new));

```

**Comment by acbeni** [comment]
@akarnokd 😅 well now i see it, its more a misconception on my side, sorry for the inconvenience, we might close the issue.
