### ISSUE TITLE
Single.merge with more than than 4 parameters removed in RxJava 2

### ISSUE THREAD

**Issue by athkalia** [ReactiveX/RxJava#5732]
Hello,

As I was migrating a piece of RxJava 1 code to RxJava 2, I noticed that the overloaded versions of the `Single.merge()` function that have more than 4 parameters got removed (I was using 6). Is there a suggestion around how to tackle this? Should I do 2 merges or is there another way?

cheers,
Sakis

**Comment by akarnokd** [comment]
There is the [merge(Iterable)](http://reactivex.io/RxJava/2.x/javadoc/io/reactivex/Single.html#merge-java.lang.Iterable-) which you can combine with `java.util.Arrays.asList()`:

```java
Single.merge(Arrays.asList(s1, s2, s3, s4, s5, s6));
```

**Comment by athkalia** [comment]
Right, I didn't notice that. Thanks!
