### ISSUE TITLE
autoconnect() never reconnects to a completed source

### ISSUE THREAD

**Issue by uKL** [ReactiveX/RxJava#5754]
**RxJava 1.3.3**

I'm not sure if what I've found is a bug, edge case or works as designed... Let's roll.

## Assumptions
- Observable, which had completed can be subscribed again and act like it was fresh (at least most of them can (just, custom observables, etc)
- I use the same instance of the observable

## Source observable
Emitts `1` and never completes.

```
val source = Observable.just(1).mergeWith(Observable.never())
```

## Working example

1. Subscribe to source as soon as we have at least one subscriber
1. Source is completed as soon as releaseTrigger emits a value
1. Next subscription (`thirdSubscriber`) to the same observable (regardless it already completed once) received `42`

```
val releaseTrigger = PublishSubject.create<Boolean>()
        val source = Observable.just(42).mergeWith(Observable.never())
        val observable = source
                .takeUntil(releaseTrigger)
                .publish()
                .refCount()

        val subscriber = observable.test()
        subscriber.assertValue(42)

        val secondSubscriber = observable.test()
        secondSubscriber.assertNoValues()
        secondSubscriber.assertNoTerminalEvent()

        releaseTrigger.onNext(true)

        val thirdSubscriber = observable.test()
        thirdSubscriber.assertValue(42)
```

## Not working example

1. Subscribe to source as soon as we have at least one subscriber (due to `autoConnect(1)`)
1. Source is completed as soon as releaseTrigger emits a value
1. Next subscription (`thirdSubscriber`) to the same observable (regardless it already completed once) never receives any value, `autoConnect` won't establish the connection.

```
val releaseTrigger = PublishSubject.create<Boolean>()
        val source = Observable.just(42).mergeWith(Observable.never())
        val observable = source
                .takeUntil(releaseTrigger)
                .publish()
                .autoconnect()

        val subscriber = observable.test()
        subscriber.assertValue(42)

        val secondSubscriber = observable.test()
        secondSubscriber.assertNoValues()
        secondSubscriber.assertNoTerminalEvent()

        releaseTrigger.onNext(true)

        val thirdSubscriber = observable.test()
        thirdSubscriber.assertValue(42)
```

## Analysis

This is due to `autoConnect`'s implementation. `OnSubscribeAutoConnect` maintains `numberOfSubscribers` value, which is never decremented when subscribers are released therefore block

```
if (this.incrementAndGet() == numberOfSubscribers) {
    source.connect(connection);
}
```
is never executed.

## Questions and ideas

- Condiction could be changed to `this.incrementAndGet() >= numberOfSubscribers`. It seems to be pretty safe to call `connect()` on a `ConnectableObservable` which is already connected.
- The counter could be decremented when child subscriber is disposed.
- Some other?
- No, go away, this is intended (please tell me why)

**Comment by akarnokd** [comment]
The behavior is by design. `autoConnect` is for connecting once, `refCount` for connecting on a `0->1` transition.

**Comment by uKL** [comment]
It looks a little bit inconsistent with how it works. Do you think that it shouldn't be documented?

Side question, is there any way to introduce required behavior (with built-in operators) or should I keep with my own operator?

**Comment by akarnokd** [comment]
I don't understand you. If `refCount` does the expected behavior, use `refCount`.

> Do you think that it shouldn't be documented?

PR welcome.

**Comment by uKL** [comment]
`refCount` does not do the job because it unsubscribes when there are no subscribers left.

My expected result is to:
1. Connect when the first subscriber subscribes
1. Stay subscribed if all subscribers were unsubscribed
1. If the source is completed and some other subscriber is interested reconnect to source.

**Comment by akarnokd** [comment]
This behavior is not provided by RxJava. You have to write your own operator for it.
