### ISSUE TITLE
Use descriptive names in interfaces

### ISSUE THREAD

**Issue by EGecius** [ReactiveX/RxJava#5762]
Every time I implement one of these interfaces I rename 'e' to 'emitter'. This is repetitive and can be avoided with renaming the param in the interface.

```java
public interface SingleOnSubscribe<T> {

    /**
     * Called for each SingleObserver that subscribes.
     * @param e the safe emitter instance, never null
     * @throws Exception on error
     */
    void subscribe(@NonNull SingleEmitter<T> e) throws Exception;
}
```

This would be in line with naming in other interfaces, such as:

```java
public interface CompletableConverter<R> {

    /**
     * Applies a function to the upstream Completable and returns a converted value of type {@code R}.
     *
     * @param upstream the upstream Completable instance
     * @return the converted value
     */
    @NonNull
    R apply(@NonNull Completable upstream);
}
```

I am happy to do it myself, if you approve.

**Comment by akarnokd** [comment]
Why don't you use lambdas where you can specify the name of the parameter?

```java
Single.create(emitter -> { emitter.onSuccess(1); });
```

Besides, I'm not sure renaming the parameter wouldn't cause trouble with JVM languages where such change breaks existing code.

**Comment by vanniktech** [comment]
Not for kotlin. Named arguments are only supported from Kotlin compiled code where the Metadata annotation is present.

**Comment by EGecius** [comment]
Android Studio autogenerates the following with lambdas:
Single.create(e -> )

... which I repetitively rename to Single.create(emitter -> )

**Comment by akarnokd** [comment]
I think not many languages have upgraded their adapters to v2 yet (or will ever) so let's change it and see who's complaining.

**Comment by akarnokd** [comment]
Closing via #5766
