### ISSUE TITLE
Is there a way to remove items from Flowable backpressure buffer?

### ISSUE THREAD

**Issue by ursusursus** [ReactiveX/RxJava#5764]
Hi, im trying to adapt the usual download queue code with cancelation to reactive

```
public class DownloadQueue {

    private final LinkedBlockingQueue<DownloadTask> mQueue = new LinkedBlockingQueue<>();

    private void loop() {
        while (mQueue.peek() != null) {
            DownloadTask task = mQueue.poll();
            doDownload(task);
        }
        onQueueFinished();
    }

    abstract onQueueFinished();

    public void enqueue(DownloadTask task) {
        mQueue.offer(task);
    }

    public void cancel(DownloadTask taskToCancel) {
        mQueue.remove(task);
    }
}
```

Where loop() runs on a different thread from cancel() so items while waiting in queue can get removed from it (and also the currently processed one). Btw its sort of a "finishing" queue, i.e. when all tasks were processed it quits

My approach to this in RxJava was subject/processor which enqueues tasks onto it self and flatmaps with download flowable with buffer strategy. Stream should be synchronous for now (with possibility for paralelism in future), hence flowable and its buffer.

_However I do also need to support canceling, so I do need to remove tasks from download flowable buffer, is that possible?_ 

Do I need a custom flowable? Is this out of scope for reactive?

**Comment by akarnokd** [comment]
Depending on if retaining the `DownloadTask` references a bit longer is not an issue, you could adapt the example in [this StackOverflow answer](https://stackoverflow.com/a/47795609/61158).

**Comment by ursusursus** [comment]
Okay so only with "regular java", thanks
