### ISSUE TITLE
No mechanism for canceling an individual subscription 

### ISSUE THREAD

**Issue by kagile** [ReactiveX/RxJava#5765]
RxJava Version: 1

There is no mechanism for canceling an individual subscription in RxJava while using `Observable.from`.

Consider this example :
I am downloading some files from the network using retrofit and rxjava. In my app, the user may cancel the download.

Pseudo Code:

```
   Subscription subscription = Observable.from(urls)
            .concatMap(this::downloadFile)
            .subscribe(file -> addFileToUI(file), Throwable::printStackTrace);
```
Now, If I unsubscribe this subscription, then all requests get canceled. I want to download one by one, that's why used concatMap. How do I unsubscribe particular request?

It is only possible if I have separate subscription object per URL. But then how do I manage serial download?

SO question : https://stackoverflow.com/q/47844512/7809145

**Comment by akarnokd** [comment]
Please do not cross post and be patient on StackOverflow.

**Comment by kagile** [comment]
@akarnokd I'm unable to find any mechanism in RxJava. Can't you just help or guide me?
