### ISSUE TITLE
Transformers in RxJava2

### ISSUE THREAD

**Issue by lawloretienne** [ReactiveX/RxJava#5767]
How do you apply Transformers for the compose operator in RxJava2
http://blog.danlew.net/2015/03/02/dont-break-the-chain/

**Comment by FangforFun** [comment]
回复

**Comment by akarnokd** [comment]
The same way. Create an ObservableTransformer and use it with compose().

**Comment by FangforFun** [comment]
回复

**Comment by lawloretienne** [comment]
I went with SingleTransformer since I'm using Singles.
