### ISSUE TITLE
2.x: Race conditions in (Single|Maybe|Completable).observeOn()

### ISSUE THREAD

**Issue by yamasa** [ReactiveX/RxJava#5776]
I found race conditions in (Single|Maybe|Completable).observeOn() operators.
This is a code sample to reproduce it:

https://github.com/yamasa/RxJava/commit/88e0d884d014c868347d0de9dd20ef128d1826ae

When I call observeOn() with a single-threaded scheduler (e.g. Schedulers.single(), AndroidSchedulers.mainThread()) and then call its subscription's dispose() method from the same thread, I expect onSuccess() is never called after the dispose().
I believe RxJava should guarantee executions on a single-threaded scheduler are sequentially consistent.

This is a similar problem to https://github.com/ReactiveX/RxJava/issues/5742 , but this occurs only in extremely rare cases.

note: observeOn() operator for Observable and Flowable doesn't have this issue.

**Comment by yamasa** [comment]
I've created a PR to fix this issue.
Could you review it?
https://github.com/ReactiveX/RxJava/pull/5777

**Comment by akarnokd** [comment]
There is a very small window where the task can't be cancelled yet. It was decided long ago that this is not worth tackling and due to its probabilistic nature, it is very hard to interleave two threads to show the effect - no wonder you had to add a 200ms delay **inside the operator** to expose it.

Did you come across this in real code or is it a theoretical finding?

**Comment by yamasa** [comment]
Yes, I added the 200ms delay to reproduce the problem easily.
The real code is like this:
```
    private final CompositeDisposable disposables = new CompositeDisposable();

    @Nullable
    private Listener listener = null;

    void doLogin() {
        listener = new Listener(...);
        Disposable disposable = Single.fromCallable(() -> api.login())
                .subscribeOn(Schedulers.io())
                .observeOn(AndroidSchedulers.mainThread())
                .subscribe(account -> {
                    listener.onLogin(account);  // NullPointerException!
                });
        disposables.add(disposable);
    }

    @Override
    protected void onStop() {
        super.onStop();
        disposables.clear();
        listener = null;
    }
```
Actually, it's quite hard to reproduce NPE in this code. But, I believe the NPE caused by this issue.

**Comment by akarnokd** [comment]
Just use `if (listener != null)` check there and you should be fine.

**Comment by akarnokd** [comment]
Also you could apply `onTerminateDetach()` before `subscribe`.

**Comment by yamasa** [comment]
> Just use if (listener != null) check there and you should be fine.

Yes, it fixes my code, but... as I wrote above, I think RxJava should guarantee executions on a single-threaded scheduler are sequentially consistent.

I'm using `observeOn(AndroidSchedulers.mainThread())` and calling `dispose()` from the same Android main thread. So, is it wrong to expect `onSuccess` never happens after `dispose()`?

**Comment by akarnokd** [comment]
Changing the library should be the last resort and you were shown workarounds for a bug in your own code. Concurrency involves a lot of probabilistic cases where a library has to decide which to tackle and in what capacity. Here, a `listener == null` check in your code is equivalent to any eager `isDisposed` check done by RxJava and thus the fastest path is to fix your code.

**Comment by yamasa** [comment]
> Concurrency involves a lot of probabilistic cases where a library has to decide which to tackle and in what capacity.

I completely agree with it.
And, we should be able to avoid such complexity by using single-threaded execution.

If I called `dispose()` from another thread, it would be my bug definitely. But, as far as used within the same single thread, RxJava should guarantee "**strongly-sequential execution**" as written in the [JavaDoc](http://reactivex.io/RxJava/2.x/javadoc/io/reactivex/schedulers/Schedulers.html#single--).

`Observable` guarantees the sequential consistency like this:
```
fooObservable
.observeOn(Schedulers.single())
.subscribe(new Observer<Foo>() {

    Disposable d;

    @Override
    public void onSubscribe(Disposable d) {
        this.d = d;
    }

    @Override
    public void onNext(Foo foo) {
        // ...
        if (...) {
            d.dispose();  // onNext() will be no longer invoked.
            return;
        }
        // ...
    }
```
`Observer.onNext(foo)` will be never called after calling `d.dispose()`.
Why doesn't `Singe` guarantee the same consistency?

**Comment by akarnokd** [comment]
The reason there is no eager check in the 0..1 types of `observeOn` because that adds overhead for every use, even those where the given corner case is not a problem. You can leverage composition though via `onTerminateDetach` that will effectively perform that `isDisposed` check. In addition, the eager checking only works when the cancellation and task execution is on the same thread; any distinct threads and the race is back.

The reason `Observable` and `Flowable` check the cancellation flag is because they run in a loop which could take any length or many iterations before giving back the control to whomever triggered them.

**Comment by yamasa** [comment]
The "overhead" is only a AtomicReference.get() and a if-statement. I think this cost is much less than `scheduler.scheduleDirect()`.  And, the code like [this](https://github.com/ReactiveX/RxJava/issues/5776#issuecomment-353721439) is a very common use case rather than corner case, I think.

Anyway, I understood your opinion.
Thanks.
