### ISSUE TITLE
Documentation error?

### ISSUE THREAD

**Issue by RobLewis** [ReactiveX/RxJava#5782]
What does this mean in the [description](http://reactivex.io/RxJava/1.x/javadoc/rx/Observable.html#onTerminateDetach--) of `onTerminateDetach`? 

Returns:
an Observable which out references to the upstream producer and downstream Subscriber if the sequence is terminated or downstream unsubscribes

My guess: "nulls" belongs between "which" and "out"

**Comment by akarnokd** [comment]
Yes, the word `nulls` out is missing there and also from`Flowable` and `Observable` in v2. I'll post a fix to v2 and you are welcome to post a fix for v1 if you want.

**Comment by akarnokd** [comment]
Closing via #5783
