### ISSUE TITLE
2.x: part of the stream continues after error in Flowable but not Observable.

### ISSUE THREAD

**Issue by artur-jablonski** [ReactiveX/RxJava#5791]
Given an `Iterable<T>` that always fails on `next()`:

```
public Iterable<String> iterableThatThrowsException()
    {
        return () -> new Iterator<String>()
        {
            @Override
            public boolean hasNext() { true; }

            @Override
            public String next()
            {
                throw new RuntimeException("kaboom, kaboom");
            }
        };
    }
```

and this stream:

```
Flowable.fromIterable(Arrays.asList(1, 2))
                  .doOnNext(i -> out.println("fromIterable onNext() -> " + i))
                  .doOnComplete(() -> out.println("fromIterable onComplete()"))
                  .map(i -> iterableThatThrowsException())
                  .flatMap(l -> Flowable.fromIterable(l))
                  .doOnError(t -> out.println("flatMap onError()"))
                  .subscribe(
                    i -> out.println("subscriber onNext() -> " + i),
                    t -> out.println(
                        "subscriber onError() -> " + t.getClass().getName() +
                        " " + t.getMessage()),
                    () -> out.println("subscriber onComplete()")
                );
```
the `Flowable.fromIterable(Arrays.asList(1, 2))` continues to emit items after `flatMap(l -> Flowable.fromIterable(l))` signals error.

This is the output:
```
fromIterable onNext() -> 1
flatMap onError()
subscriber onError() -> java.lang.RuntimeException kaboom, kaboom
fromIterable onNext() -> 2
fromIterable onComplete()
```

Please note that:

1. When I substitute Flowable with Observable, then it outputs what **I** think is the correct behaviour
```
fromIterable onNext() -> 1
flatMap onError()
subscriber onError() -> java.lang.RuntimeException kaboom, kaboom
```
2. When I add a "dummy"`doOnError()` to the inner `fromIterable` it also produces "correct" output like in 1
```
.flatMap(l -> Flowable.fromIterable(l).doOnError(t -> {}))
```
3. The "incorrect" behaviour is consistent all the way down to version 2.0.0

**Comment by artur-jablonski** [comment]
a JUnit test to reproduce
https://gist.github.com/anonymous/1bda662f5383a410b33bcb4c1b229476

**Comment by akarnokd** [comment]
Thanks. It's a bug on the fusion path which doesn't cancel the upstream if `poll()` crashes. 

PR #5792 posted to fix it. 

Till then, you can use `.hide()` (prevents fusion thus the buggy part is skipped) or `flatMapIterable(list -> list)` (does not suffer from this problem and is a bit faster anyway).

**Comment by artur-jablonski** [comment]
Ha! I knew it was the fusion path! ;)

Thank you for the fix and suggestion of a workaround!
