### ISSUE TITLE
Error:Failed to resolve: io.reactivex.rxjava2:rxjava:2.x.y

### ISSUE THREAD

**Issue by taozh1218** [ReactiveX/RxJava#5794]
I added this in gradle,

> compile "io.reactivex.rxjava2:rxjava:2.x.y"

but when i sync the gradle ,it just cause an eror, **Error:Failed to resolve: io.reactivex.rxjava2:rxjava:2.x.y**

**Comment by JakeWharton** [comment]
Replace x with 1 and y with 8.

You can check
http://search.maven.org/#search%7Cga%7C1%7Cg%3A%22io.reactivex.rxjava2%22%20a%3A%22rxjava%22
for
the latest version.

**Comment by taozh1218** [comment]
thanks a lot ,I have just started to learn, thank my idol
