### ISSUE TITLE
RxJava2 & Room: Stop emitting events on delete

### ISSUE THREAD

**Issue by escar** [ReactiveX/RxJava#5796]
I have this database

```
interface UserDao {

    @Insert(onConflict = REPLACE)
    fun insert(user : User)

    @Query("SELECT * FROM user")
    fun get(): Flowable<List<User>>

    @Query("DELETE FROM user")
    fun deleteAll()
}
```
Everytime a record is inserted, `get()` will be triggered automatically, as expected.
```
override fun getUsers() : Flowable<User> {

    return db.userDao().get()
}
```
How can I stop this from happening when `deleteAll()` is called? Basically I don't wan't to get users again when the database is cleared.

**Comment by JakeWharton** [comment]
This is not related to RxJava. Please ask on StackOverflow with the appropriate tag for Room.

**Comment by escar** [comment]
Isn't it? Flowable allows the subscribers to act upon any changes in the database. So I thought there might be some operator I could use with Flowable to skip events on delete

**Comment by JakeWharton** [comment]
How would RxJava know it's a delete? All it sees are lists.

**Comment by escar** [comment]
https://stackoverflow.com/questions/47699390/drop-delete-trigger-for-room-database

**Comment by akarnokd** [comment]
Please avoid cross-posting [StackOverflow](https://stackoverflow.com/questions/48150937/rxjava2-room-stop-emitting-events-on-delete) questions.

As the issue text states:

>  -  If you have a question/issue about a library/technology built on top of RxJava (such as Retrofit, RxNetty, etc.), please consider asking a question on StackOverflow first (then maybe on their issue list).
>  - Please avoid cross-posting questions on StackOverflow, this issue list, the Gitter room or the mailing list.
