### ISSUE TITLE
Flowable stop emitting items in backpressure situatuons

### ISSUE THREAD

**Issue by ArtemShaban** [ReactiveX/RxJava#5801]
version 2.1.8

There is a flowable with "BackpressureStrategy.BUFFER". Items come in to flowable from multi-threads. After some time flowable stop emits items.
Next code snippet reproduce an issue:

 ```
Completable completable =
                Observable.range(1, 1_000_000)
                          .flatMap((Integer integer) ->
                                  Observable.just(integer)
                                            .observeOn(Schedulers.computation())
                          )
                          .toFlowable(BackpressureStrategy.BUFFER)
                          .flatMapCompletable((Integer integer) ->
                                  Completable.defer(() -> {
                                      if (integer % 1000 == 0)
                                      {
                                          logger.i("@@@ " + integer);
                                      }
                                      return Completable.timer(1, TimeUnit.MILLISECONDS);
                                  }), false, 1000);

        completable.blockingAwait();
```

Output for this code looks like:
```
@@@ 1000
@@@ 2000
@@@ 3000
@@@ 4000
@@@ 5000
@@@ 6000
@@@ 7000
@@@ 8000
@@@ 9000
@@@ 10000
@@@ 11000
@@@ 12000
@@@ 13000
@@@ 14000
@@@ 15000
@@@ 16000
```

If I comment "observeOn(Schedulers.computation()", flowable works as expected.

In my particular case, a source of items is PublishSubject. As workaround I simply add synchronization on invoking PublishSubject.onNext;

**Comment by akarnokd** [comment]
`Subject`s are not thread safe on their `onNext` methods and should not be called concurrently from multiple threads.

As for the stopping, the `Observable.flatMap` operator is still running but is overwhelmed by that thousands of inner Observables and spends most of its time trying to add new ones and remove old ones. Given time, you'll eventually see the numers resume again. You should use `Flowable.range()` instead which when run with `flatMap` is ensured to keep the active inner source count reasonable.

**Comment by akarnokd** [comment]
See also [which type to use](https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0#which-type-to-use) wiki entry.

**Comment by ArtemShaban** [comment]
@akarnokd Thanks for answers. 

About stopping - your right! Simply observable overwhelmed.

Actually, the main mistake which I've made - use subject without synchronization.  
After using `Subject.toSerialized()` everything works fine.
