### ISSUE TITLE
When I want to import io.reactivex.Observable,but it imports android.database.Observable

### ISSUE THREAD

**Issue by dujunily** [ReactiveX/RxJava#5808]
I use Android Studio 3.0.1 and my project dependencies
compile 'io.reactivex.rxjava2:rxjava:2.1.8'
compile 'io.reactivex.rxjava2:rxandroid:2.0.1'

When I input Observable, it imports android.database.Observable automatic,but not io.reactivex.Observable
![image](https://user-images.githubusercontent.com/5248527/34983413-6deea77a-fae8-11e7-96ff-ffd656eb321d.png)

This means I can't use rxjava2

but when I input Observable  and then manual import io.reactivex.Observable,it can work

I have done these steps:
1、download a new android studio and retry
2、restart android studio with Invalidate and Restart
but it doesn't work

**Comment by akarnokd** [comment]
This is not an issue with RxJava but your experience with your IDE and your IDE's experience with you. The `io.reactivex.Observable` should show up in the content assist. If it fails to do it, report the issue to the IDE's developers.
