### ISSUE TITLE
RxJavaPlugins always invoked printStackTrace

### ISSUE THREAD

**Issue by pli2014** [ReactiveX/RxJava#5817]
io.reactivex.plugins.RxJavaPlugins#onError  how to resolve this issue?  

![image](https://user-images.githubusercontent.com/6429799/35255334-7d27a57a-0029-11e8-80e8-be091a1c4ba2.png)

**Comment by pli2014** [comment]
errorHandler could catch all exception and return immediately.    f.accept(error); return;

**Comment by pli2014** [comment]
why do you design this? log system... @benjchristensen

**Comment by teaey** [comment]
What you mean baby? @pli2014

**Comment by pli2014** [comment]
@teaey  I found this topic: https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0#error-handling

When we integrated this RxJava in our product, we need to implement these handler with io.reactivex.plugins.RxJavaPlugins

**Comment by akarnokd** [comment]
> RxJavaPlugins always invoked printStackTrace

Not always, only when there is no error handler or that handler crashes. The purpose is to get at least some indication that there was an error.

> why do you design this? 

v1 swallowed errors and you had no idea your program was failing all the time. This way, there is a chance you can log the excess errors. Also see [the wiki](https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0#error-handling).

> log system...

Which log system? There are so many. Besides, by registering a handler, you can call into the log system of your choosing.

> benjchristensen

The v2 design is by me.

**Comment by pli2014** [comment]
Thanks, I got this. I will use slf4j logger with it.

**Comment by teaey** [comment]
@pli2014  稳
