### ISSUE TITLE
IO Scheduler reuse an unavailiable Worker

### ISSUE THREAD

**Issue by XDean** [ReactiveX/RxJava#5822]
I'm using RxJava 2.1.3. Consider following code

    Disposable d = test(5000); // task 1
    Thread.sleep(1000); // wait for task 1 into sleep
    d.dispose(); // dispose task 1
    d = test(1000); // task 2

    Disposable test(int i) {
      return Single.fromCallable(() -> sleep(i)) // here sleep don't response interrupt
          .subscribeOn(Schedulers.io())
          .subscribe();
    }

The `sleep` method ignore `InterruptedException` and insist to sleep.

The task1 wait for 5000ms and be disposed in 1000ms. Then we run task2. But task 2 will wait for task1 because `Schedulers.io()` distribute the same `Worker` to task2 as task1. If we remove the `d.dispose()`, task2 will run immediately in another `Worker`.

IO scheduler used an unavailiable `Worker` (which is sitll working) to schedule work.

And I also tried `Executors.newCachedThreadPool()`, it doesn't have this problem.

**Comment by akarnokd** [comment]
See https://github.com/ReactiveX/RxJava/issues/5346#issuecomment-301808817.
