### ISSUE TITLE
Proposal: More concise generate method for infinite streams (generateInfinite)

### ISSUE THREAD

**Issue by ghost** [ReactiveX/RxJava#5823]
I use the following pattern a lot:

```java
        Flowable.<Whatever>generate(emitter -> emitter.onNext(generateNextValue()))
                .sample(1, TimeUnit.SECONDS)
                .subscribe(whatever -> {
                    
                });
```

Opposed to `interval().map()` this allows the subscriber to set the rate. For this use case, it would be convenient to have a generate method which is more concise:

```java
Flowable.generate(() -> generateNextValue())
```

Here, the type can always be inferred automatically and there is no need for `emitter.onNext`. It could also be called `generateInfinite` because only the subscriber can stop it.

The implementation could look like this:

```java
    public <T> Flowable<T> generateInfinite(Supplier<T> supplier) {
        return Flowable.generate(emitter -> {
            try {
                emitter.onNext(supplier.get());
            } catch (RuntimeException e) {
                emitter.onError(e);
            }
        });
    }

    public <T> Flowable<T> generateInfinite(Callable<T> callable) {
        return Flowable.generate(emitter -> {
            try {
                emitter.onNext(callable.call());
            } catch (Exception e) {
                emitter.onError(e);
            }
        });
    }
```

What do you think about this proposal?

**Comment by akarnokd** [comment]
The extensions project already has such an operator: [repeatCallable](https://github.com/akarnokd/RxJava2Extensions#flowablesrepeatcallable). Being an item source and a static factory method, such operators can live on any class of yours and don't have to be on `Flowable`.
