### ISSUE TITLE
Improve takeUntil method

### ISSUE THREAD

**Issue by JSpiner** [ReactiveX/RxJava#5829]
rxJava version : 2.x

Both 'takeUntil' and 'takeWhile' functions have no inclusive functions.
So It is impossible to make the following code.

```java
Observable.just(1,2,3,4,-1,1,2,3,4)
.takeUntil(value -> value == -1)
// I wish : 1, 2, 3, 4, -1
// actually : 1, 2, 3, 4
```

or in real world...
```java
Observable.merge(
    cacheRequest,
    networkRequest
)
.takeUntilInclusive(data -> data.dataType == FROM_NETWORK);
// Load mem/network data. But when it comes to network data, it stops.
```

how about create blow functions?

`takeWhileInclusive`
`takeUntilInclusive`
`skipWhileInclusive`
`skipUntilInclusive`

**Comment by akarnokd** [comment]
Have you actually tried your code?

```java
Observable.just(1,2,3,4,-1,1,2,3,4)
        .takeUntil(value -> value == -1)
        .subscribe(System.out::println);
```

prints:

```
1
2
3
4
-1
```

I'm not sure what you tried to accomplish originally, but `merge()` looks suspicious as it can interleave your data unexpectedly. Try `concat()`.

**Comment by JSpiner** [comment]
Opps.....
It looks not tested enough. I was so ashame...
I'll close it.

Thanks!
