### ISSUE TITLE
Inconsistent multiple error handling in merge

### ISSUE THREAD

**Issue by neworld** [ReactiveX/RxJava#5831]
I noticed some inconsistency in handling multiple errors by using `merge` operator. 

This will crash always due `UndeliverableException`:
```kotlin
        val observable1 = Observable.create<Int>({
            println("Subscribe 1")
            it.onError(RuntimeException("Error1 foo"))
        }).subscribeOn(Schedulers.io())

        val observable2 = Observable.create<Int>({
            println("Subscribe 2")
            it.onError(RuntimeException("Error2 foo"))
        }).subscribeOn(Schedulers.io())

        Observable.merge(observable1, observable2).subscribe({

        }, {

        })
```

However, if I am running synchronous, I didn't get `UndeliverableException`:

```kotlin
        val observable1 = Observable.create<Int>({
            println("Subscribe 1")
            it.onError(RuntimeException("Error1 foo"))
        })

        val observable2 = Observable.create<Int>({
            println("Subscribe 2")
            it.onError(RuntimeException("Error2 foo"))
        })

        Observable.merge(observable1, observable2).subscribe({

        }, {

        })
```

I have large chains and I often I have such operations in the middle. I don't know exactly how upstream works, neither I care how downstream will be using my middleware. I just want to terminate the chain on the first error and let downstream resolve error.

The problem for me is, my tests are single threaded and everything works well.

However, I prefer both cases to work like single-threaded version (`UndeliverableException`). But `mergeFirstErrorOnly` works for me well as described here #5779.

**Comment by akarnokd** [comment]
The [`merge` JavaDoc](http://reactivex.io/RxJava/2.x/javadoc/io/reactivex/Observable.html#merge-io.reactivex.ObservableSource-io.reactivex.ObservableSource-) has been updated to explain the situation better.

In addition, the [comment](https://github.com/ReactiveX/RxJava/issues/5779#issuecomment-354115986) in contains a static factory method with the behavior. The fortunate thing with such methods is that they can live in any class and don't have to be part of `Observable`'s set of factories.

**Comment by neworld** [comment]
That comment works for me well. BTW, thanks for the solution! However, I am expecting to have `UndeliverableException` always, not only if they have emitted asynchronically.

**Comment by akarnokd** [comment]
The synchronous execution with `merge` will not subscribe to the next source if the previous one failed. You could try and use a `TestScheduler` or use asynchrony and looping the test several hundred times, but there is no guarantee you'll see an `UndeliverableException`.

**Comment by neworld** [comment]
In fact, asynchrony solution is reproducible 100%.

**Comment by akarnokd** [comment]
Looks like this question has been answered. If you have further input on the issue, don't hesitate to reopen this issue or post a new one.
