### ISSUE TITLE
Fix RxJavaHooks version in Plugins wiki page

### ISSUE THREAD

**Issue by mercer** [ReactiveX/RxJava#5840]
RxJavaHooks was introduced in 1.1.7 not 1.1.6 [1]

https://search.maven.org/#search%7Cga%7C1%7Cfc%3A%22rx.plugins.RxJavaHooks%22

If someone wants to do a minimal upgrade, just to get RxJavaHooks, then version matter.s

Thanks

**Comment by akarnokd** [comment]
Updated.
