### ISSUE TITLE
2.x TestObserver does not catch IllegalStateException.class in assertError function

### ISSUE THREAD

**Issue by da-na** [ReactiveX/RxJava#5846]
Thanks for using RxJava but before you post an issue, please consider the following points:

  - [x] Please include the library version number, including the minor and patch version, in the issue text. In addition, if you'd include the major version in the title (such as `2.x`) that would be great.

  - [x] If you think you found a bug, please include a code sample that reproduces the problem. Dumping a stacktrace is usually not enough for us.

  - [x] RxJava has more than 150 operators, we recommend searching the [javadoc](http://reactivex.io/RxJava/2.x/javadoc/io/reactivex/Observable.html) for keywords of what you try to accomplish.

  - [x] If you have a question/issue about a library/technology built on top of RxJava (such as Retrofit, RxNetty, etc.), please consider asking a question on StackOverflow first (then maybe on their issue list).

  - [x] Questions like "how do I X with RxJava" are generally better suited for StackOverflow (where it may already have an answer).

  - [x] Please avoid cross-posting questions on StackOverflow, this issue list, the Gitter room or the mailing list.

Hi!
I'm using RXJava '2.1.8' in an Android project, and I'm currently writing some tests with JUnit version '4.12'. I have noticed, that the TestObserver does not catch the RuntimeException, and since I couldn't find any documentation on why the RuntimeExceptions seem to be treated differently, that's why I'm asking my question here: Why the RuntimeException in my JUnit test is not caught by TestObserver? 

I have the following class that I'm testing:

```java
public class Authenticator implements IAuthenticator {

    private AuthenticationApi authApi;
    private UserCache userCache;

    @Override
    public Observable<User> authenticate(AuthParams params) {
        if (userCache == null) {
            throw new IllegalStateException("User cache must be set!");
        }
        return authApi.authenticate(params)
            .map(response -> {
                if (!response.authCode.equals("Successful")) {
                    throw new AuthException(response);
                }
                return new AuthResponseMapper().map(response);
            });
    }
}
```
NOTE: AuthException extends Exception, while IllegalStateException extends RuntimeException

Here are my two tests that verify that the exception is thrown: 

```java
public class AuthenticatorTest {
// (...)
    @Test
    public void test_authService_authenticate_throwsAuthException() {
        testAuthResponse.authCode = "Fail";
        authenticator = new Authenticator(mockAuthApi, mockUserCache);

        Observable<User> testObservable = authenticator.authenticate(testAuthParams);
        TestObserver<User> testObserver = testObservable.test();

        testObserver.assertError(AuthException.class);
        testObserver.assertNoValues();
        testObserver.assertNotComplete();
    }

    @Test // - doesn't pass, since it doesn't catch the IllegalStateException
    public void test_authService_authenticate_throwsIllegalStateExceptionError() {
        authenticator = new Authenticator(mockAuthApi, null);

        Observable<User> testObservable = authenticator.authenticate(testAuthParams);
        TestObserver<User> testObserver = testObservable.test();

        testObserver.assertError(IllegalStateException.class);
        testObserver.assertNoValues();
        testObserver.assertNotComplete();
    }
    
}
```

I don't really understand why the AuthException is caught, however the IllegalStateException throws, and my test fails. Is there any better way to write that test using TestObserver? 
Thanks!

**Comment by akarnokd** [comment]
You throw the `IllegalStateException` outside RxJava:

```java
if (userCache == null) {
    throw new IllegalStateException("User cache must be set!");
}

return authApi.authenticate(params) // <------- RxJava enters here
            .map(...);
```
and the test crashes here:

```java
Observable<User> testObservable = authenticator.authenticate(testAuthParams);
```

never actually reaching `test()` and thus `TestObserver` is never involved in that case.

**Comment by da-na** [comment]
Thanks for your prompt response @akarnokd !
You are absolutely right.
Closing the ticket.
