### ISSUE TITLE
toList(int) should not throw an exception if the capacityHint is 0

### ISSUE THREAD

**Issue by ivanfeli** [ReactiveX/RxJava#5849]
Right now an IllegalArgumentException is thrown if the hint is 0. ArrayLists can handle a capacityHint of 0, I believe RxJava shouldn't be crashing at runtime for this.

**Comment by akarnokd** [comment]
It may be not as beneficial as it looks: https://stackoverflow.com/a/28345648/61158

I have some faded memory this being discussed somewhere already though and the verdict was, it is fine as it is. Besides, you can supply your own collection, initialized as you see fit via [toList(Callable)](http://reactivex.io/RxJava/2.x/javadoc/io/reactivex/Flowable.html#toList-java.util.concurrent.Callable-).
