### ISSUE TITLE
Why zip(range(0, 1mi)), range(0, 100)) never finishes, when inverting the order does?

### ISSUE THREAD

**Issue by AllanHasegawa** [ReactiveX/RxJava#5855]
Version: "2.1.9"

I recently ran into a problem where the order of my parameters to the Zip function matters, and now I'm trying to understand why.

Here's a simplified test:

```kotlin
val bigRange = Observable.range(0, 1_000_000_000)
val shortRange = Observable.range(0, 100)

val ts = Observable.zip(shortRange, bigRange, BiFunction<Int, Int, Int> { _, b -> b }).test()
// val ts = Observable.zip(bigRange, shortRange, BiFunction<Int, Int, Int> { a, _ -> a }).test()

ts.awaitTerminalEvent(10, TimeUnit.SECONDS)
```

In the test above, the stream completes as expected; with 100 items. However, if I uncomment the other `ts`, then the app hangs.

From the docs it makes me believe that if any of the streams completes, then the whole "zip" completes, but this is maybe not the case? Is it something to do with the Observable being a "pusher" and not a "puller"?

**Comment by akarnokd** [comment]
`Observable` doesn't have backpressure and `range` is synchronous and will fill up the internal queue of `zip` before giving the chance to the other source. If the short one is first, that happens quickly. If the longer one is first, that may take a lot of time and memory. Try with `Flowable` and you should see both cases complete within reasonable time.

RxJava is synchronous by default and you have to introduce asynchrony explicitly.

**Comment by AllanHasegawa** [comment]
Awesome explanation; very clear.

Made a few experiments with Flowable and others "async" operators (intervalRange) and I think I understand it now :)

Thank you very much.
