### ISSUE TITLE
RxJavaHook onCreate throwing --> java.lang.NoSuchMethodError: rx.plugins.RxJavaPlugins.getCompletableExecutionHook()Lrx/plugins/RxJavaCompletableExecutionHook;

### ISSUE THREAD

**Issue by anand1430** [ReactiveX/RxJava#5866]
Hi,

I am trying to use the Completable.fromAction() method. But getting exception in the RxJavaHook.onCreate method. Below are the details - 

**Code Snippet -** 

```
Completable completable1 = Completable.fromAction(() -> {
	try {
		assignActionsToUser(actions, newUserId, start.getTime(), end.getTime(), "EXTTMS");
		} catch (EUMException e) {
				e.printStackTrace();
		}
		}).subscribeOn(Schedulers.io());_


private void assignActionsToUser(List<String> actions, String newUserId, Date startTime,
										Date endTime, String lastUpdUserId) throws 
		externalUserManagementService.assignActionsToUser(actions, newUserId, startTime, endTime, 
	}

```

**Maven dependency -** 

        <dependency>
            <groupId>io.reactivex</groupId>
            <artifactId>rxjava</artifactId>
            <version>1.3.6</version>
        </dependency>

**Exception -** 

java.lang.NoSuchMethodError: rx.plugins.RxJavaPlugins.getCompletableExecutionHook()Lrx/plugins/RxJavaCompletableExecutionHook;

    /**
     * Hook to call when a Completable is created.
     * @param onSubscribe the original OnSubscribe logic
     * @return the original or replacement OnSubscribe instance
     */
    public static Completable.OnSubscribe onCreate(Completable.OnSubscribe onSubscribe) {
        Func1<Completable.OnSubscribe, Completable.OnSubscribe> f = onCompletableCreate;
        if (f != null) {
            return f.call(onSubscribe); // exception thrown here
        }
        return onSubscribe;
    }

**Comment by akarnokd** [comment]
This is due to incorrect setup in your project. Either you have multiple RxJava jar files there or you are using Multidex (and maybe ProGuard).

**Comment by anand1430** [comment]
I am positive there is no multiple RxJava jars. I am able to debug the RxJavaHooks.java file up to the line -
 **return f.call(onSubscribe); // exception thrown here**. The file path is showing the 1.3.6 version during debug as well.

Any thoughts ?

**Comment by akarnokd** [comment]
What is your platform, Android? Are you using ProGuard?

**Comment by anand1430** [comment]
I am having a spring boot application with Tomcat server. Intellij is the IDE. Maven for building the app.

**Comment by akarnokd** [comment]
Please create a fresh project with only RxJava as a dependency and a plain old Java `main(String[] args)` method with the basic `Completable.create`. If that works, your other project is likely not cleaned up properly after a version upgrade.

**Comment by anand1430** [comment]
@akarnokd - Apologize its a project issue. I was able to make it work with a new project. My bad. Thanks.
