### ISSUE TITLE
Request: Add operator to cache only onSuccess value from Single

### ISSUE THREAD

**Issue by technoir42** [ReactiveX/RxJava#5874]
Basically like `Single#cache` but that would re-subscribe to source if it previously terminated with `onError`.
Use case: caching network responses in memory. `Single#cache` is not suitable for this purpose because we generally don't want to cache network errors but instead retry the request on subsequent subscriptions.

This is what we currently use https://gist.github.com/technoir42/93cf3647aa869dde498b0afe663c83ea (based upon `Single#cache`).

**Comment by akarnokd** [comment]
Such behavior seems to be peculiar to your use case and you did a good job implementing a solution for it locally. I'm not convinced the operator should be added to RxJava though.

**Comment by technoir42** [comment]
I was asked to publish this operator somewhere. @akarnokd would it be a worthwhile addition to RxJava2Extensions? I believe this use case is actually a pretty common on Android.

**Comment by akarnokd** [comment]
Publish it in your own library.

**Comment by halfhp** [comment]
This sounds exactly like what I'm currently looking for.  @technoir42 it looks like your gist got deleted?  :(

**Comment by technoir42** [comment]
@halfhp I've updated the link in the description.

**Comment by grAPPfruit** [comment]
> Such behavior seems to be peculiar to your use case and you did a good job implementing a solution for it locally. I'm not convinced the operator should be added to RxJava though.

Can you explain why _you are not conviced_?
Rx offers operators for pretty much everything, why exclude this one? There are definitely use-cases for it...

**Comment by beloglazov178** [comment]
This operator would be very useful!
