### ISSUE TITLE
1.x: BlockingSingle.value() does not unsubscribe

### ISSUE THREAD

**Issue by luks91** [ReactiveX/RxJava#5884]
Found on the latest 1.x head (1.3.6). Consider a following example:

```java
Single.create(new Single.OnSubscribe<Object>() {
    @Override
    public void call(SingleSubscriber<? super Object> singleSubscriber) {
        singleSubscriber.onSuccess(new Object());
        singleSubscriber.add(Subscriptions.create(new Action0() {
            @Override
            public void call() {
                System.out.println("Hello!");
            }
        }));
    }
}).toBlocking().value();
```
  
Upon success the Action will not be called. ```BlockingSingle.value()``` is missing unsubscribing the upstream upon ```onSuccess``` and ```onError```. 

This doesn't occur for ```Observable.toBlocking().first()```:
```java
        Observable.create(new Observable.OnSubscribe<Object>() {
            @Override
            public void call(Subscriber<? super Object> singleSubscriber) {
                singleSubscriber.onNext(new Object());
                singleSubscriber.onCompleted();
                singleSubscriber.add(Subscriptions.create(new Action0() {
                    @Override
                    public void call() {
                        new Throwable().printStackTrace();
                        calls[0]++;
                    }
                }));
            }
        }).toBlocking().first();
```

produces:

```java
java.lang.Throwable
	at rx.singles.BlockingSingleTest$2$1.call(BlockingSingleTest.java:115)
	at rx.subscriptions.BooleanSubscription.unsubscribe(BooleanSubscription.java:71)
	at rx.internal.util.SubscriptionList.add(SubscriptionList.java:88)
	at rx.Subscriber.add(Subscriber.java:93)
	at rx.singles.BlockingSingleTest$2.call(BlockingSingleTest.java:112)
	at rx.singles.BlockingSingleTest$2.call(BlockingSingleTest.java:107)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.Observable.subscribe(Observable.java:10352)
	at rx.Observable.subscribe(Observable.java:10319)
	at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:443)
	at rx.observables.BlockingObservable.first(BlockingObservable.java:166)
	at rx.singles.BlockingSingleTest.testUnsubscribedAfterValue2(BlockingSingleTest.java:120)
```

The ```toBlocking().first()``` upstream is definitely unsubscribed in this case. I am not sure about the intermediate operators being used by the flow (```take(1).single()``` used by ```first()```). For now BlockingSingle seems to be the issue. I have a fix ready and will create a pull request soon.

**Comment by akarnokd** [comment]
The v1 design is awkward in this regard. The [documentation](https://github.com/ReactiveX/RxJava/blob/1.x/src/main/java/rx/SingleSubscriber.java#L28) indicates one has to call `unsubscribe` to clean up but single operators [clean up after themselves](https://github.com/ReactiveX/RxJava/blob/1.x/src/main/java/rx/internal/operators/SingleObserveOn.java#L91) in a terminal case. Therefore, it is unclear if it was supposed to behave this way or not.

Why do you want this particular cleanup?

**Comment by luks91** [comment]
Hmm.. nice to find out this Schrödinger's Single rule - thank you for pointing out. :)
In this case, if the current architecture leaves the ```unsubscribe``` call choice to the end Subscriber, should the ```value``` operator follow the same principle? Not sure if we do anything toward this path.

On the other hand, what could we do instead of calling ```toObservable().toBlocking().first()``` to work it around? I guess the cleanup could take place immediately after calling ```onSuccess(T)``` inside of the ```OnSubscribe``` too...

Our use case for this operator is when we need to exit the reactive world back into imperative (Android AIDL, legacy API we need to support). Being fairly familiar with the Observable behavior, we were adding Subscriptions that cleanup some of the resources (like callbacks) to all the Singles we were creating. We were surprised to find out one day that none of them were actually being called. We're still at 1.x for this project but will migrate to 2.x soon.

**Comment by akarnokd** [comment]
You could use [`doAfterTerminate`](http://reactivex.io/RxJava/1.x/javadoc/rx/Single.html#doAfterTerminate-rx.functions.Action0-) and [`doOnUnsubscribe`](http://reactivex.io/RxJava/1.x/javadoc/rx/Single.html#doOnUnsubscribe-rx.functions.Action0-) or [`using`](http://reactivex.io/RxJava/1.x/javadoc/rx/Single.html#using-rx.functions.Func0-rx.functions.Func1-rx.functions.Action1-boolean-), but the best option is to migrate to 2.x.

**Comment by luks91** [comment]
I just had some time to investigate further.  When you look at overloads of ```Single.subscribe()``` you can see the following:
 - ```subscribe(SingleSubscriber<T>)``` allows user to call unsubscribe(), thus the choice whether to do that or not ends up in user's hands
 - ```subscribe(Action1<T>)``` will instantiate the SingleSubscriber under the hood that will call ```unsubscribe``` in its terminal events. What's interesting is that ```subscribe(Observer)``` does not follow the pattern.

The logic of the latter suggests that when user is not able to call unsubscribe (access the underlying Subscription object) the library does that automatically. It feels like the same should be consistent for toBlocking().value(). ```Single.subscribe(Observer)``` is the same case.

**Comment by akarnokd** [comment]
I suggest not relying on that and using doAfterTerminate and doOnUnsubscribe. Since 1.x is End-of-life on 31st of March, I wouldn't change its behavior. 

The best option is to migrate and use `doFinally` in v2, or backport it to v1 as a transformer and have it in your project/library. Lastly, you could implement a blocking operator that unsubscribes and use it via [`to`](http://reactivex.io/RxJava/1.x/javadoc/rx/Observable.html#to-rx.functions.Func1-).
