### ISSUE TITLE
2.x: scan operator emits seed

### ISSUE THREAD

**Issue by watanavex** [ReactiveX/RxJava#5896]
This codes are output 8.
scan operator is emits only seed value.
```
        val observable = Observable.never<Int>()
                .scan(8, { t1, t2 -> t1 + t2 })

        observable.subscribeBy {
            print($it)
        }
```

It bug?
RxSwift show me different behavior.

**Comment by akarnokd** [comment]
It's not a bug. What do you do when you need that first item in RxSwift after all?.

See also [StackOverflow](https://stackoverflow.com/questions/48282685/rxjava-scan-emits-first-item-other-rx-libraries-do-not-why)
