### ISSUE TITLE
3.x: Flowable.publish() should not drop items if there are no consumers

### ISSUE THREAD

**Issue by akarnokd** [ReactiveX/RxJava#5899]
Unlike `Observable.publish()`, the `Flowable.publish()` has an internal queue and fetches data from upstream based on consumption. For historical reasons, the 2.x implementation drops items when there are no consumers, which can lead to unnecessary dataloss when switching between consumers on an item boundary.

I propose changing the operator in 3.x to not drop items when there are no consumers. The 2.x behavior can be achieved via an additional unbounded consumer which stays subscribed until the operator completes.

**Comment by davidmoten** [comment]
>I propose changing the operator in 3.x to not drop items when there are no consumers.

Does this only apply after the first subscription has happened?

**Comment by akarnokd** [comment]
If there are no subscribers, don't consume the queue. The [2.x](https://github.com/ReactiveX/RxJava/blob/2.x/src/main/java/io/reactivex/internal/operators/flowable/FlowablePublish.java#L474) version has dedicated logic to keep consuming the queue.

**Comment by akarnokd** [comment]
Closing via #6519.
