### ISSUE TITLE
2.x: Pulib constructor for TestScheduler that already takes the time

### ISSUE THREAD

**Issue by vanniktech** [ReactiveX/RxJava#5901]
I'd like to have the ability to have an instantiated TestScheduler which already has a time. Internally it'd just delegate to `advanceTimeTo` and the constructor would also take the same parameters as that method.

What are your thoughts?

**Comment by akarnokd** [comment]
You can do it simply after construction:

```java
TestScheduler scheduler = new TestScheduler();
scheduler.advanceTimeBy(System.currentTimeMillis(), TimeUnit.MILLISECONDS);
```

If this is frequent, just create a static helper method:

```java
public static TestScheduler newTestScheduler(long initialTimeMillis) {
    TestScheduler scheduler = new TestScheduler();
    scheduler.advanceTimeBy(initialTimeMillis, TimeUnit.MILLISECONDS);
    return scheduler;
}
```

**Comment by vanniktech** [comment]
Yeah with Kotlin it's even easier. I still feel like a constructor that takes the time would be beneficial. I'm not feeling too strong about it so I'll see what the opinions of other folks are.

**Comment by akarnokd** [comment]
I guess this isn't that of a maintenance intensive change so PR welcome. You could set the current time directly without wasting time by calling `advanceTimeBy`.
