### ISSUE TITLE
1.x OperatorTake seem to swallow Exceptions

### ISSUE THREAD

**Issue by awenger** [ReactiveX/RxJava#5934]
We have a Observable that is transformed into a Single. Some unrelated changes caused a Exception in the `onSuccess` Action of the Subscriber. This exception seems to get lost. It neither gets propagated to the `onError` Action, nor to the `RxJavaHooks.setOnError` Action.

Sample that reproduces the problem:

```java
RxJavaHooks.setOnError(error -> System.out.println("got global error " + error));
Observable.just("1")
        .first()
        .toSingle()
        .subscribe(
                it -> {
                    System.out.println("going to throw");
                    throw new NullPointerException("bla");
                },
                error -> System.out.println("got error " + error)
        );

// Output:

going to throw

Process finished with exit code 0
```

If I change the sample to this it does propagate the error (removed the `first()` call):
```java
RxJavaHooks.setOnError(error -> System.out.println("got global error " + error));
Observable.just("1")
        .toSingle()
        .subscribe(
                it -> {
                    System.out.println("going to throw");
                    throw new NullPointerException("bla");
                },
                error -> System.out.println("got error " + error)
        );

// Output

going to throw
got error java.lang.NullPointerException: bla

Process finished with exit code 0

```

This is what I found out while debugging.
Exception is caught here:
https://github.com/ReactiveX/RxJava/blob/1.x/src/main/java/rx/internal/operators/OnSubscribeLift.java#L49-L55

`st` is in this case the OperatorTake:
https://github.com/ReactiveX/RxJava/blob/1.x/src/main/java/rx/internal/operators/OperatorTake.java#L60-L70
it is already `completed`. So the `Throwable` is just ignored.

Could be related/the same as #3571.

**Comment by akarnokd** [comment]
Hi and thanks for reporting. Indeed 1.x was not too keen on reporting undeliverable errors. I'll post a fix shortly but note that support for 1.x will end on March 31 with a final release.

**Comment by vanniktech** [comment]
This can be closed now.
