### ISSUE TITLE
Canceling an Observable in RxJava 2.x

### ISSUE THREAD

**Issue by akoshman** [ReactiveX/RxJava#5944]
**Observable.fromFuture**'s javadoc says "Unlike 1.x, cancelling the Observable won't cancel the future. If necessary, one can use composition to achieve the cancellation effect: futureObservableSource.doOnCancel(() -> future.cancel(true));."

Flowable has this method and it works as expected like this:

```
    Disposable disposable = Flowable.fromFuture(response, Schedulers.io())
      .doOnCancel(() -> response.cancel(true))
      .subscribe();
```

But Observable seems to lack **doOnCancel** method, doesn't it?
Tested RxJava's version is 2.1.10.

**Comment by akarnokd** [comment]
Its equivalent is doOnDispose. A copy-paste error. PR welcome.

**Comment by RomanWuattier** [comment]
Hello,
Does someone work on this topic? I would like to start contributing, can I do it?

**Comment by akarnokd** [comment]
@RomanWuattier You can start working on this.

**Comment by akarnokd** [comment]
Closing via #5948.
