### ISSUE TITLE
Thread interruption on unsubscribe

### ISSUE THREAD

**Issue by zishanj** [ReactiveX/RxJava#5946]
I am receiving this crash randomly on some of my user devices:

> Fatal Exception: b.b.c.f: java.io.InterruptedIOException: thread interrupted
>        at io.reactivex.plugins.RxJavaPlugins.isFailOnNonBlockingScheduler(Unknown Source)
>        at io.reactivex.internal.operators.single.SingleCreate$Emitter.onError(Unknown Source)
>        at io.reactivex.internal.operators.single.SingleCreate.subscribeActual(Unknown Source)
>        at io.reactivex.Single.create(Unknown Source)
>        at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(Unknown Source)
>        at io.reactivex.Scheduler$DisposeTask.run(Unknown Source)
>        at io.reactivex.internal.schedulers.ScheduledRunnable.run(Unknown Source)
>        at io.reactivex.internal.schedulers.ScheduledRunnable.call(Unknown Source)
>        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
>        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272)
>        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
>        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
>        at java.lang.Thread.run(Thread.java:761)

Any idea what is the cause of this error?

**Comment by akarnokd** [comment]
Does anybody else work on the codebase? Are you using 3rd party Rx-based libraries? Did you truncate the stacktrace?

**Comment by zishanj** [comment]
I am using Crashlytics from Fabric and this is the bottom log showing in Crashlytics:

> Caused by java.io.InterruptedIOException: thread interrupted
>        at com.android.okhttp.okio.Timeout.throwIfReached(Timeout.java:145)
>        at com.android.okhttp.okio.Okio$1.write(Okio.java:73)
>        at com.android.okhttp.okio.AsyncTimeout$1.write(AsyncTimeout.java:155)
>        at com.android.okhttp.okio.RealBufferedSink.flush(RealBufferedSink.java:237)
>        at com.android.okhttp.internal.http.HttpConnection.flush(HttpConnection.java:141)
>        at com.android.okhttp.internal.http.HttpTransport.finishRequest(HttpTransport.java:52)
>        at com.android.okhttp.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:940)
>        at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:818)
>        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:480)
>        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:422)
>        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:538)
>        at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getResponseCode(DelegatingHttpsURLConnection.java:105)
>        at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java)
>        at com.google.api.client.http.javanet.NetHttpResponse.(Unknown Source)
>        at com.google.api.client.http.javanet.NetHttpRequest.addHeader(Unknown Source)
>        at com.google.api.client.http.HttpRequest.execute(Unknown Source)
>        at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.buildHttpRequestUrl(Unknown Source)
>        at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(Unknown Source)
>        at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.execute(Unknown Source)
>        at com.alhuda.al_huda_live.common.data.Calendar.getJSONEvents(Unknown Source)
>        at com.alhuda.al_huda_live.common.data.Calendar$$Lambda$1.subscribe(Unknown Source)
>        at io.reactivex.internal.operators.single.SingleCreate.subscribeActual(Unknown Source)
>        at io.reactivex.Single.create(Unknown Source)
>        at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(Unknown Source)
>        at io.reactivex.Scheduler$DisposeTask.run(Unknown Source)
>        at io.reactivex.internal.schedulers.ScheduledRunnable.run(Unknown Source)
>        at io.reactivex.internal.schedulers.ScheduledRunnable.call(Unknown Source)
>        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
>        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272)
>        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
>        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
>        at java.lang.Thread.run(Thread.java:761)

This error is returning from a module which runs in background to fetch Calendar data from Google Calendar API. This error is occurring randomly on 2-3 user devices only.

**Comment by zishanj** [comment]
This is my sample code from that module:

```
public Single<String> getJSONEvents() {
        return Single.create(emitter -> {
            if (! isGooglePlayServicesAvailable())
                acquireGooglePlayServices(emitter);
            else if (! isDeviceOnline())
                emitter.tryOnError(new Throwable("EVENT_OFFLINE"));
            else {
                initializeCalendarAPI();

                SimpleDateFormat fmtDate = new SimpleDateFormat("yyyy-MM-dd'T00:00:00'+00:00");
                DecimalFormat df = new DecimalFormat("#");
                df.setRoundingMode(RoundingMode.UP);

                java.util.Calendar calMinTime = java.util.Calendar.getInstance();
                calMinTime.setTime(new Date());
                int currentDay = calMinTime.get(java.util.Calendar.DAY_OF_MONTH);
                int week = Integer.parseInt(df.format((double)calMinTime.getActualMaximum(java.util.Calendar.DAY_OF_WEEK_IN_MONTH)/((double)calMinTime.getActualMaximum(java.util.Calendar.DAY_OF_MONTH)/(double)currentDay)));
                int weekFirstDay = (week*7-6)-currentDay;
                calMinTime.add(java.util.Calendar.DATE, weekFirstDay);
                DateTime minTime = DateTime.parseRfc3339(fmtDate.format(calMinTime.getTime()));

                java.util.Calendar calMaxTime = java.util.Calendar.getInstance();
                calMaxTime.setTime(new Date());
                calMaxTime.add(java.util.Calendar.DATE, weekFirstDay + 7);
                DateTime maxTime = DateTime.parseRfc3339(fmtDate.format(calMaxTime.getTime()));

                Events events = service.events().list("abc@group.calendar.google.com")
                        .setOrderBy("startTime")
                        .setSingleEvents(true)
                        .setTimeMin(minTime)
                        .setTimeMax(maxTime)
                        .setTimeZone(TimeZone.getDefault().getID())
                        .execute();

                emitter.onSuccess(events.getFactory().toString(events));
            }
        });
    }
```

From last few lines there is `service.events().list` which is a service function from Google Calendar that fetch events data.

**Comment by akarnokd** [comment]
This is a common question on [StackOverflow](https://stackoverflow.com/search?q=%5Brx-java%5D+or+%5Brx-java2%5D+or+%5Bjava-flow%5D+interruptedioexception)  regarding Okio. Please check those first eapecially since Okio or its wrapper libraries are not maintained in this project.
