### ISSUE TITLE
AsyncSubject doesn't lend itself to RxJavaHook

### ISSUE THREAD

**Issue by asarkar** [ReactiveX/RxJava#5949]
Many libraries, and people, depend on the RxJava instrumentation beyond the plethora of (very) useful operators; one such library is [Spring Cloud Sleuth](https://cloud.spring.io/spring-cloud-sleuth/). Turns out, when using [Couchbase Java client](https://github.com/couchbase/couchbase-jvm-core), that uses RxJava 1.x (`master` is using `1.6.0-SNAPSHOT` as of this writing), Sleuth loses track of the query. After some back and forth with the developers, and based on my own investigation, the problem appears to be [here](https://github.com/couchbase/couchbase-jvm-core/blob/master/src/main/java/com/couchbase/client/core/message/AbstractCouchbaseRequest.java#L101).

There doesn't seem to be any way to attach RxJava hooks with `AsyncSubject`. Unlike the approach taken by Sleuth so far, which is a polite form of "RxJava 1.x instrumentation sucks", I'm apprehensive in chalking it up to simply "doesn't work". Note that moving to 2.x, or to a different Reactive library like Reactor is not an immediate option, since Couchbase guys are unlikely to rewrite their whole codebase for Sleuth.

Original ticket I opened against Sleuth: https://github.com/spring-cloud/spring-cloud-sleuth/issues/914

Spin-off ticket in Zipkins: https://github.com/openzipkin/brave/issues/664

I'm not a Reactive expert, but open to making contributions to RxJava 1.x as well as Couchbase if either doesn't turn out to be a 6-month project.

**Comment by akarnokd** [comment]
RxJava 1.x is end-of-life, no further developments. Also I don't understand what the problem is, how it is related to hooks or this project in general. 

In general you can create a wrapper subject around any other subject and have whatever hook you want between that and the original.

**Comment by asarkar** [comment]
>  create a wrapper subject around any other subject

Do you've any code samples I could look at?

**Comment by akarnokd** [comment]
https://github.com/ReactiveX/RxJava/blob/1.x/src/main/java/rx/subjects/SerializedSubject.java
