### ISSUE TITLE
PublishSubject/Processor are not delivering onNext calls

### ISSUE THREAD

**Issue by muzzah** [ReactiveX/RxJava#5956]
- Using library version 2.1.6
 
HI devs, 

I am seeing a weird issue with PublishSubjects and PublishProcessors where elements are not being delivered to their observers. Ill try to explain my structure below. The abstractions are mainly because of the need to transform lower level objects to higher level abstractions. Its difficult to produce a test case as I think its concurrency related

I have a Java NIO loop that is listening on a socket  This uses a Completable to do the looping and then uses a PublishSubject to deliver its messages downstream. 

```java
class MessageQueueLoop {

    private PublishSubject msgs = PublishSubject.create();

        void loop() {
            //When message arrives
            msgs.onNext(new Msg());
        }
    }
}
```

There are two downstream listeners on this stream of messages within a single class

```java
class ServerEventLoop {
        messageRouter = new MessageQueueLoop();
        serverEventStream = PublishSubject.create()

        disposables.add(messageRouter.messageRouterEventStream()
                .observeOn(computationScheduler)
                .subscribe(
                        this::handleMessageQueueEvent,
                        error -> {
                            shutdownLoop();
                            serverEventStream.onError(error);
                        },
                        () -> {
                            shutdownLoop();
                            serverEventStream.onComplete();
                        }
                ));


        disposables.add(messageRouter.messageRouterEventStream()
                .observeOn(ioScheduler)
                .filter(messageQueueEvent -> messageQueueEvent.type().equals(MessageQueueEvent.Type.READY))
                .doOnSubscribe(disposable -> messageRouter.startMessageQueueLoop())
                .subscribe(
                        this::startListeningForClients, //Initialise server socket and accepts clients
                        this::handleMessageQueueError)); 

     void handleMessageQueueEvent(MessageQueueEvent messageQueueEvent){
        switch (messageQueueEvent.type()) {
            case CLIENT_REGISTERED:
                serverEventStream.onNext(ServerEvent.newClient());
                break;
            case CLIENT_REGISTRATION_FAILED:
                break;
            case CLIENT_UNREGISTERED:
                serverEventStream.onNext(ServerEvent.clientDisconnected());
                break;
            case MESSAGE:
                serverEventStream.onNext(ServerEvent.newMessage()));
                break;
            case READY:
                break;
            default:
               //Error, throw exception
        }

    }
```

Now the weirdness happens when the listener on the server event loop receives two messages from separate clients in very close succession.  There is the following class which listens to the ServerEventLoop PublishSubject as per below

```
serverEventLoop = new ServerEventLoop(bindAddress, Schedulers.computation(), messageProvider);
// Serialise the subject here
serverEventsStream = PublishSubject.create().toSerialized();
        
serverEventLoop.getServerEventsStream()
                .observeOn(computation)
                .filter(serverEvent -> !serverEvent.isNewMessage())
                .subscribe(//Do stuff)


serverEventLoop.getServerEventsStream()
                .observeOn(computation)
                .filter(serverEvent -> {
                    boolean shouldDeliver = serverEvent.isNewMessage() && clients.containsKey(serverEvent.connectionId());
                    return shouldDeliver;
                })
                .subscribe(
                        event -> {
                            serverEventsStream.onNext(ServerEvent.newMessage(event.message(), event.connection()));
                        }
                );
```

The problem starts at the last line which filters for new messages and checks that clients still exists
`                        
serverEventsStream.onNext(ServerEvent.newMessage());
`

This line gets called, but the messages do not get delivered even though there are observers.  The observer for these messages do some filtering/mapping then passes it onto the main scheduler in Android  for processing and rendering on views. If multiple clients send messages around the same time I can detect that 

`                        
serverEventsStream.onNext(ServerEvent.newMessage());
`

is called but the messages are not delivered downstream.  I have also verified that the observers exists and are listening and that the subjects are all valid (no errors or complete signal have been delivered). I wanted to see if this is a bug or if I am doing something wrong before I go about refactoring things a little.

**Comment by akarnokd** [comment]
`PublishSubject`s are not thread safe and you call `onXXX` methods on them on various threads. There could be a possibility of dataloss. Second, your filter definitions could be wrong and filtering out events. Third, place a couple of `doOnNext()`s at various places to see where events disappear.

**Comment by muzzah** [comment]
I've verified that the filters are not being called on the downstream observers as I put logging into all filters and operators. That last output is from where I mentioned above. Would calling toSerialize on all publish subjects potentially fix this problem? Is there a need to convert the subjects into processors? As from what I understand the difference between subjects and processors is paying attention to downstream backpressure requests?

**Comment by akarnokd** [comment]
There is no need for Processors in this case. Please provide a standalone example that demonstrates your problem.

**Comment by muzzah** [comment]
Hey @akarnokd Please find an example [here](https://gist.github.com/mustafasezgin/09e142e1bd2e36b640588efc78f8625d)

This structure resembles what I have in my code. As mentioned, it happens intermittently and requires two events to be fired in close succession. Let me know if there are changes I could make that could mitigate this including calling toSerialize on the PublishSubjects or changing them to Processors.

**Comment by akarnokd** [comment]
I don't see any problems in that example. Does it exhibit the problem for you? Also there is no need for `toSerialized` there.

**Comment by muzzah** [comment]
In the example I created not so far, but in my application yes. And it happens intermittently in my application so not easily reproducible. Though I am a little confused. Im calling the onNext of a PublishSubject possibly on multiple threads in that example by using the computation scheduler no?
And if a PublishSubject is not thread safe then why would I not need to call toSerialized to ensure well defined behaviour as you mentioned in your first comment? If data loss can occur then how can one prevent it in a multithreaded environment without calling toSerialized?

**Comment by akarnokd** [comment]
Mustafa, what is preventing you from applying `toSerialized` in your program then?

**Comment by muzzah** [comment]
Nothing :) I only recently discovered the fact that Subjects/Processors are not thread safe while researching this problem. I will need to do some refactoring but I just wanted to confirm if my suspicions were correct or if there was a chance of an underlying problem. Ill re-open the issue if I find something different.

**Comment by muzzah** [comment]
Just to let you know @akarnokd Ive confirmed that even after converting all subjects to `PublishProcessor.<ServerEvent>create().toSerialized();` I still see messages being dropped. Im not going to re-open the issue for now but I do think that even after converting all subjects to be threadsafe subjects if I am still seeing elements being dropped, then there might be an issue.

**Comment by muzzah** [comment]
Ok an interesting finding. At the end of the downstream observers, if I change the scheduler used from computation to `Scheduler.newThread() ` , then I cannot reproduce the problem. Could this be related to me using up all the workers/threads in the computation scheduler somehow and RxJava dropping the delivery of elements? (Related to the chain of subjects all observing on the computation scheduler). Im not familiar with the internals so any insight you can provide would help here. Im going to try and change the rx2.computation-threads property to see if it helps

**Comment by akarnokd** [comment]
If your loop occupies a worker without giving the thread up and if you use the computation scheduler for other work, you can end up deadlocking other computation scheduler users.

**Comment by muzzah** [comment]
Yeah I was aware of that and ensure I use the io scheduler for any potentially blocking operations but I will review my code
