### ISSUE TITLE
2.x: Observable.mergeDelayError behavior

### ISSUE THREAD

**Issue by juzabel** [ReactiveX/RxJava#5962]
When I use `Observable.mergeDelayError` , the error is not delayed and there is no diference with the simple `Observable.merge`. To force delay the error, I've to put the flag `delayError` of the `observeOn ` method to true. If I'm not wrong it is a bug since _delayError = true + merge_ should do the same as simply using _mergeDelayError_.

Here you can see the code that does not work:

        val networkSingle: Observable<List<User>> = Observable.error(Exception("Exception"))
        val defaultSingle: Observable<List<User>> = Observable.just<List<User>>(listOf())

        Observable.mergeDelayError(defaultSingle, networkSingle)
                .subscribeOn(Schedulers.io())
                .observeOn(Schedulers.newThread())
                .subscribeBy(onError = {
                    errorsUI++

                    println("errorsUI $errorsUI")
                }, onNext = {
                    valuesUI++
                    println("valuesUI $valuesUI")

                }).addTo(CompositeDisposable())
    }

And there the same code working:

        val networkSingle: Observable<List<User>> = Observable.error(Exception("Exception"))
        val defaultSingle: Observable<List<User>> = Observable.just<List<User>>(listOf())

        Observable.merge(defaultSingle, networkSingle)
                .subscribeOn(Schedulers.io())
                .observeOn(Schedulers.newThread(), true)
                .subscribeBy(onError = {
                    errorsUI++

                    println("errorsUI $errorsUI")
                }, onNext = {
                    valuesUI++
                    println( "valuesUI $valuesUI")

                }).addTo(CompositeDisposable())
    }

**Comment by akarnokd** [comment]
Works as intended. 

Each operator has a scope where their behavior takes effect. Separate operator, separate behavior and configuration. If you want to keep delaying errors and prevent errors from cutting ahead, you have to specify `delayError = true` in every operator supporting such configuration.
