### ISSUE TITLE
Rxjava like event bus

### ISSUE THREAD

**Issue by preyesm** [ReactiveX/RxJava#5963]
Hi, I am stuck in implementing RxJava as event bus in one scenario of my application. Here it goes,
I have a singleton RxBus
GrandParentFragment -> subscribe to RxBus.
GrandParentFragment -. loads Parent Fragment-> which also subscribes to RxBus
ParentFragment->loads GrandChild-> which emits an item using the singleton RxBus.
This value is intended only for the parent and not the Grand parent. But because Grand Parent Fragment is live in memory it uses the stream to perform some ops. 

I was thinking of unsubscribing from RxBus in the Grand parent fragment in onPause method and subscribe back on the onResume. But this has same overhead like event bus to register and unregister.

Do share some other solution for this use case.

**Comment by akarnokd** [comment]
Don't do event bus in RxJava as it defeats the benefits of it. Also StackOverflow is full of event bus questions, please go there and search/ask this type of question there.
