### ISSUE TITLE
2.x: Maybe.flatMapXXX overload with onSuccessMapper, onErrorMapper, onCompleteSupplier

### ISSUE THREAD

**Issue by GeorgePetri** [ReactiveX/RxJava#5973]
Hello

When working with maybes i find this overload useful.
```java
<R> Maybe<R> flatMap(
            Function<? super T, ? extends MaybeSource<? extends R>> onSuccessMapper,
            Function<? super Throwable, ? extends MaybeSource<? extends R>> onErrorMapper,
            Callable<? extends MaybeSource<? extends R>> onCompleteSupplier)
```
Having the same overload for flatmapCompletable, flatmapSingle and maybe the others would make working with maybes easier. At the moment it is necessary to add toMaybe() and convert various stream.

Thanks!

**Comment by akarnokd** [comment]
I'm not convinced. You could use Kotlin and extension methods or have a respective transformer that does the conversion inside the lambdas and use `compose`.

**Comment by GeorgePetri** [comment]
Yup, kotlin extensions do help.

And  rxjava is wonderful for modeling stuff as streams, but it gets harder when there is business logic of the form "If this stream emits do X if it does not do Y". For those situations I think those operators would help.

**Comment by akarnokd** [comment]
PR welcome, also consider it for `Single` and `Completable` for feature parity.

**Comment by sorianog** [comment]
Would love to review the PR or help out with it 😄

**Comment by akarnokd** [comment]
FYI, I added most of the operators to [RxJava2Extensions](https://github.com/akarnokd/RxJava2Extensions#flatmap-signal)
