### ISSUE TITLE
Single.concatEager is not implemented

### ISSUE THREAD

**Issue by boris-petrov** [ReactiveX/RxJava#5974]
`Single.concatEager` and `Completable.concatEager` are not available. `Observable.concatEager` and `Maybe.concatEager` are. Is there any reason for that or you just haven't gotten to that?

It's kind of a pain as I currently cast all my Singles to Maybes, use `Maybe.concatEager` and then cast back... :)

**Comment by akarnokd** [comment]
How would `Completable.concatEager` work?

**Comment by boris-petrov** [comment]
@akarnokd - well, I guess subscribe to all Completables at the same time and complete when all of them complete. I think the current `Completable.concat` subscribes to the Completables one after the other?

**Comment by akarnokd** [comment]
There is already an operator for that specific behavior with `Completable`s.

**Comment by boris-petrov** [comment]
Ah, OK, sorry for the confusion then. But the `Single.concatEager` is missing indeed.

**Comment by akarnokd** [comment]
PR welcome.

**Comment by Desislav-Petrov** [comment]
What should be the behaviour of the Single.concatEager - subscribe to all and push  just the first value received ?

**Comment by akarnokd** [comment]
It should match `Maybe.concatEager`.

**Comment by Desislav-Petrov** [comment]
Ok.. i think i know what's going on - will try to submit a pull req for initial review tonight (please bear in mind it will be my first contrib :))

**Comment by akarnokd** [comment]
Closing via #5976.
