### ISSUE TITLE
2.x: subscribeActual() accidental public

### ISSUE THREAD

**Issue by akarnokd** [ReactiveX/RxJava#5980]
Looks like the following `protected void subscribeActual()` implementations have unintentionally become public:

- [`PublishSubject`](https://github.com/ReactiveX/RxJava/blob/2.x/src/main/java/io/reactivex/subjects/PublishSubject.java#L134)
- [`PublishProcessor`](https://github.com/ReactiveX/RxJava/blob/2.x/src/main/java/io/reactivex/processors/PublishProcessor.java#L95)

There is no reason to call `subscribeActual` from outside of RxJava, however, making these `protected` counts as a breaking change. However, it should be extremely unlikey somebody was actually using these methods directy.

The question is: do we take the risk and fix the visibility in 2.x or it has to wait for 3.x?

Note that many operators are also having this method as public but those are not really accessible from the outside.

**Comment by vanniktech** [comment]
In this case I'd consider making the fix with version 2.2

**Comment by sircelsius** [comment]
I don't know If this is still relevant, but I opened a PR for it, let me know if it helps
