### ISSUE TITLE
2.x: Question: blockingSubscribe() semantics

### ISSUE THREAD

**Issue by mrkeuz** [ReactiveX/RxJava#5983]
Hi all, i'm newbie in rxjava, love it, but i have a question and maybe need advice. 

I have simple case: 
1. Want to do some parallel operations i.e. on Scheduler.io() 
2. Next i want consume results on main thread and want to re-throw all exceptions from reactive into main thread.

Real example can be spring and jpa transactions inheritance. 
In short, such transactions does not support multi-thread execution, so it needed to execute all transaction code in same, parent thread for supporting rollback of entire transaction. 
Otherwise every execution of commitAndSave() will have it own new transaction and this rollback will be incorrect.

Approx example can be next:
```
 @Transactional
  public void doSomeWork() {
        Observable.just(1, 2, 3)
                .map(e -> doSomeInParallel(e))
                .subscribeOn(Schedulers.newThread())
                .observeOn(MAIN_THREAD_SCHEDULER)
                .blockingSubscribe(e -> commitAndSave());
        
        //1. commitAndSave() should in main thread for inherit transaction for correct rollback
        //2. Should re-throw exception (i.e. for legacy, non reactive code)
    }
```

For achieve this simple goals it need working VERY carefully with blockingSubscribe() 
(see examples below) 

I understand that this can be done for some important reasons. But i think it is little counter-intuitive to have different semantics for almost identical blockingSubscribe() methods.

Main question about blockingSubscribe() api semantics.
Is there a plan for changing the semantics in the future? 
Are there good reasons for such a different behavior of overloaded methods? 
Maybe i don't understand some api design decisions here? 

Please advice. 

Thanks!

Here working example for observeOn(-main thread-) and correct re-throw form reactive (tested on 2.1.13):

```
import io.reactivex.Observable;
import io.reactivex.Observer;
import io.reactivex.Scheduler;
import io.reactivex.disposables.Disposable;
import io.reactivex.schedulers.Schedulers;
import org.assertj.core.api.AbstractCharSequenceAssert;
import org.junit.Test;

import static com.google.common.util.concurrent.MoreExecutors.directExecutor;
import static org.assertj.core.api.Java6Assertions.assertThat;

public class SubscribeObservableTest {

    private static final Scheduler MAIN_THREAD_SCHEDULER = Schedulers.from(Runnable::run);

    @Test(expected = RuntimeException.class)
    public void testObserveOnMain_swallowInBlockingSubscribe() {
        Observable.just(1, 2, 3)
                .subscribeOn(Schedulers.newThread())
                .observeOn(MAIN_THREAD_SCHEDULER)
                .map(e -> assertIsMainThread())
                .map(stringAbstractCharSequenceAssert -> {
                    throw new RuntimeException("test");
                })
                .blockingSubscribe(e -> {
                }, throwable -> {
                    throw new RuntimeException(throwable);
                });

        //FAIL: due exception swallow by default exceptionHandler()
    }

    @Test(expected = RuntimeException.class)
    public void testObserveOnMain_swallowInMap() {
        Observable.just(1, 2, 3)
                .subscribeOn(Schedulers.newThread())
                .observeOn(MAIN_THREAD_SCHEDULER)
                .map(e -> assertIsMainThread())
                .map(e -> {
                    throw new RuntimeException("test");
                })
                .blockingSubscribe(e -> assertIsMainThread());

        //FAIL: Executed in main, BUT cannot re-throw exceptions here
    }

    @Test(expected = RuntimeException.class)
    public void testObserveOnMain_notInMain() {
        Observable.just(1, 2, 3)
                .subscribeOn(Schedulers.newThread())
                .observeOn(Schedulers.from(directExecutor()))
                .map(e -> assertIsMainThread())
                .map(e -> {
                    throw new RuntimeException("test");
                })
                .blockingSubscribe();

        //FAIL: Will re-throw exception but FAIL due NOT main thread
    }

    @Test(expected = RuntimeException.class)
    public void testObserveOnMain_workingSample_correctRethrow() {
        Observable.just(1, 2, 3)
                .subscribeOn(Schedulers.newThread())
                .observeOn(MAIN_THREAD_SCHEDULER)
                .map(e -> assertIsMainThread())
                .map(stringAbstractCharSequenceAssert -> {
                    throw new RuntimeException("test");
                })
                .blockingSubscribe(new Observer<Object>() {
                    @Override
                    public void onSubscribe(Disposable d) {

                    }

                    @Override
                    public void onNext(Object o) {

                    }

                    @Override
                    public void onError(Throwable e) {
                        assertIsMainThread();
                        throw new RuntimeException(e);
                    }

                    @Override
                    public void onComplete() {

                    }
                });

        //PASS: Observe on MAIN and re-throw in main but very strange using of blockingSubscribe()
    }

    @Test
    public void testObserveOnMain_workingSample_executeInMain() {
        Observable.just(1, 2, 3)
                .subscribeOn(Schedulers.newThread())
                .observeOn(MAIN_THREAD_SCHEDULER)
                .map(e -> assertIsMainThread())
                .blockingSubscribe(new Observer<Object>() {
                    @Override
                    public void onSubscribe(Disposable d) {
                        assertIsMainThread();
                    }

                    @Override
                    public void onNext(Object o) {

                    }

                    @Override
                    public void onError(Throwable e) {

                    }

                    @Override
                    public void onComplete() {

                    }
                });

        //PASS: Observe on MAIN and re-throw in main but very strange using of blockingSubscribe()
    }

    private AbstractCharSequenceAssert<?, String> assertIsMainThread() {
        return assertThat(Thread.currentThread().getName()).isEqualTo("main");
    }
}
```

**Comment by akarnokd** [comment]
> i'm newbie in rxjava [...]
> Real example can be spring and jpa transactions inheritance.

Please ask such multi-technology questions on StackOverflow.

> But i think it is little counter-intuitive to have different semantics for almost identical blockingSubscribe() methods.

I don't understand what you are talking about here.

> Is there a plan for changing the semantics in the future?

`blockingSubscribe` has a specific behavior, there is no reason to change it.

> Maybe i don't understand some api design decisions here?

It's unclear what you try to achieve here. Using `blockingSubscribe` is very likely the wrong abstraction. You wanted total ordering of transactions and for that, you could use a single-threaded theadpool wrapped into a `Scheduler`.

Also omitting the `onError` handler is almost always wrong. You could store the exception in an `AtomicReference<Throwable>` and rethrow it after `blockingSubscribe` returns control to the caller thread.

**Comment by mrkeuz** [comment]
@akarnokd 

> It's unclear what you try to achieve here

Just want execute some logic in parallel (on some Scheduler), consume results in current thread and re-throw exception from stream.

> Please ask such multi-technology questions on StackOverflow.

This part wrote just for example. So don't required any explanation.

> I don't understand what you are talking about here.

I mean that `blockingSubscribe() ` and `blockingSubscribe(Consumer<? super T> onNext)` has different behaviour.

* `blockingSubscribe() ` re-throw exception from stream `blockingSubscribe(Consumer<? super T> onNext)` NOT re-trhow. 
*  `blockingSubscribe() ` work as "expected" with `.observeOn(MAIN_THREAD_SCHEDULER)`  but  `blockingSubscribe(Consumer<? super T> onNext)` don't and execution will on different thread.


> `blockingSubscribe` has a specific behavior, there is no reason to change it.

If this by design then ok. Just wanted some explanation.
Thanks in any case!

**Comment by akarnokd** [comment]
> blockingSubscribe() re-throw exception from stream blockingSubscribe(Consumer<? super T> onNext) NOT re-trhow.

I don't think you should use either of those overloads in your use case so their behavior is irrelevant in this context.

> blockingSubscribe() work as "expected" with .observeOn(MAIN_THREAD_SCHEDULER) but blockingSubscribe(Consumer<? super T> onNext) don't and execution will on different thread.

The way you defined `MAIN_THREAD_SCHEDULER` is essentially the `Schedulers.trampoline()` which can't be used to guaranteed return to a specific thread. Such schedulers are no-ops most of the time and their best usage is to strip asynchrony from RxJava operators in unit tests.

`blockingSubscribe(Consumer)` blocks/sleeps and loops in a way that the `onNext` callback is always executed on the thread which called `blockingSubscribe`. It doesn't matter what `observeOn` was before it. Whenever the source `Observable` produces an event, it wakes up the thread where `blockingSubscribe` is on and then that thread finds out what event it is supposed to relay to its handlers. Basically it is a classical wait-notify pair with a queue storing the events.

**Comment by mrkeuz** [comment]
Thank you very much! Will continue to learn rxjava. It seems I missing some important basic concepts.

Thanks a lot!
