### ISSUE TITLE
Buffer with time and count and republishing elements into same Observable.

### ISSUE THREAD

**Issue by benjaminroux** [ReactiveX/RxJava#5989]
Apologies for the bad title but I wasn't sure how to explain my problem.

What is the expected output of the following repro code (I'm using 2.1.13).

```
private static Subject<Integer> publisher = PublishSubject.create();

private static void testReactive() {
    publisher.buffer(100, TimeUnit.MILLISECONDS, 1)
            .doOnNext(System.out::println)
            .doOnNext(Main::fakeError)
            .subscribe();

    publisher.onNext(0);
}

private static void fakeError(List<Integer> integers) {
    integers.forEach(publisher::onNext);
}
```

I was expected to see `[0]` repeated indefinitely, however I just see it once followed by empty lists.
`buffer(100, TimeUnit.MILLISECONDS)` is giving me the expected output.

Futhermore `buffer(1)` ends-up in a `StackOverflowError` even though I was also expecting to see `[0]` repeated indefinitely (is it defined somewhere that `buffer` might return a list bigger than the one requested?)

Is that a bug or is that me not understanding the underlying implementation?

**Comment by akarnokd** [comment]
> Futhermore buffer(1) ends-up in a StackOverflowError

Subject don't support reentrance; your `forEach(publisher::onNext)` however does that and ends up recursively calling itself, which can lead to a messed up internal state. 

Specify the subject as serialized and the example should work as expected:

```java
static Subject<Integer> publisher = PublishSubject.<Integer>create().toSerialized();
```

**Comment by akarnokd** [comment]
From the [JavaDoc](http://reactivex.io/RxJava/2.x/javadoc/io/reactivex/subjects/PublishSubject.html)

> Calling `onNext(Object)`, `onError(Throwable)` and `onComplete()` is required to be serialized (called from the same thread or called non-overlappingly from different threads through external means of serialization). The `Subject.toSerialized()` method available to all `Subject`s provides such serialization and also **protects against reentrance (i.e., when a downstream `Observer` consuming this subject also wants to call `onNext(Object)` on this subject recursively)**.

**Comment by benjaminroux** [comment]
Okay, it makes sense. Thanks for the answer!
