### ISSUE TITLE
2.x: Wiki footer

### ISSUE THREAD

**Issue by akarnokd** [ReactiveX/RxJava#6000]
Currently, the Wiki has the original Netflix footer by default:

![image](https://user-images.githubusercontent.com/1269832/39746193-e25de1de-52a9-11e8-9091-0c8831508a16.png)

Since Netflix is not officially involved with RxJava anymore, I think the footer should be changed in a respectful manner. Ideas?

**Comment by vanniktech** [comment]
Let's use the same as in the copyrights?

`Copyright (c) 2016-present, RxJava Contributors.`

**Comment by akarnokd** [comment]
Done.
