### ISSUE TITLE
2.x: android.system.ErrnoException

### ISSUE THREAD

**Issue by JasonLian2020** [ReactiveX/RxJava#6007]
Library version: `io.reactivex.rxjava2:rxjava:2.1.12`

Build Environment

- compileSdkVersion 27
- buildToolsVersion "27.0.3"
- minSdkVersion 19
- targetSdkVersion 27

Crash Log

	android.system.ErrnoException
	android_getaddrinfo failed: ENETUNREACH (Network is unreachable)

	io.reactivex.exceptions.UndeliverableException:com.lizhiweike.network.exception.ApiException: java.net.UnknownHostException: Unable to resolve host "m.weike.com": No address associated with hostname
	io.reactivex.plugins.RxJavaPlugins.void onError(java.lang.Throwable)(TbsSdkJava:367)
	......
	android.system.ErrnoException:android_getaddrinfo failed: ENETUNREACH (Network is unreachable)
	libcore.io.Posix.android_getaddrinfo(Native Method)
	libcore.io.ForwardingOs.android_getaddrinfo(ForwardingOs.java:55)
	java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:106)
	java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java:74)
	java.net.InetAddress.getAllByName(InetAddress.java:752)
	okhttp3.Dns$1.java.util.List lookup(java.lang.String)(TbsSdkJava:40)
	okhttp3.internal.connection.RouteSelector.void resetNextInetSocketAddress(java.net.Proxy)(TbsSdkJava:185)
	okhttp3.internal.connection.RouteSelector.java.net.Proxy nextProxy()(TbsSdkJava:149)
	okhttp3.internal.connection.RouteSelector.okhttp3.internal.connection.RouteSelector$Selection next()(TbsSdkJava:84)
	okhttp3.internal.connection.StreamAllocation.okhttp3.internal.connection.RealConnection findConnection(int,int,int,boolean)(TbsSdkJava:213)
	okhttp3.internal.connection.StreamAllocation.okhttp3.internal.connection.RealConnection findHealthyConnection(int,int,int,boolean,boolean)(TbsSdkJava:134)
	okhttp3.internal.connection.StreamAllocation.okhttp3.internal.http.HttpCodec newStream(okhttp3.OkHttpClient,okhttp3.Interceptor$Chain,boolean)(TbsSdkJava:113)
	okhttp3.internal.connection.ConnectInterceptor.okhttp3.Response intercept(okhttp3.Interceptor$Chain)(TbsSdkJava:42)
	okhttp3.internal.http.RealInterceptorChain.okhttp3.Response proceed(okhttp3.Request,okhttp3.internal.connection.StreamAllocation,okhttp3.internal.http.HttpCodec,okhttp3.internal.connection.RealConnection)(TbsSdkJava:147)
	okhttp3.internal.http.RealInterceptorChain.okhttp3.Response proceed(okhttp3.Request)(TbsSdkJava:121)
	okhttp3.internal.cache.CacheInterceptor.okhttp3.Response intercept(okhttp3.Interceptor$Chain)(TbsSdkJava:93)
	okhttp3.internal.http.RealInterceptorChain.okhttp3.Response proceed(okhttp3.Request,okhttp3.internal.connection.StreamAllocation,okhttp3.internal.http.HttpCodec,okhttp3.internal.connection.RealConnection)(TbsSdkJava:147)
	okhttp3.internal.http.RealInterceptorChain.okhttp3.Response proceed(okhttp3.Request)(TbsSdkJava:121)
	okhttp3.internal.http.BridgeInterceptor.okhttp3.Response intercept(okhttp3.Interceptor$Chain)(TbsSdkJava:93)
	okhttp3.internal.http.RealInterceptorChain.okhttp3.Response proceed(okhttp3.Request,okhttp3.internal.connection.StreamAllocation,okhttp3.internal.http.HttpCodec,okhttp3.internal.connection.RealConnection)(TbsSdkJava:147)
	okhttp3.internal.http.RetryAndFollowUpInterceptor.okhttp3.Response intercept(okhttp3.Interceptor$Chain)(TbsSdkJava:125)
	okhttp3.internal.http.RealInterceptorChain.okhttp3.Response proceed(okhttp3.Request,okhttp3.internal.connection.StreamAllocation,okhttp3.internal.http.HttpCodec,okhttp3.internal.connection.RealConnection)(TbsSdkJava:147)
	okhttp3.internal.http.RealInterceptorChain.okhttp3.Response proceed(okhttp3.Request)(TbsSdkJava:121)
	okhttp3.logging.HttpLoggingInterceptor.okhttp3.Response intercept(okhttp3.Interceptor$Chain)(TbsSdkJava:143)
	okhttp3.internal.http.RealInterceptorChain.okhttp3.Response proceed(okhttp3.Request,okhttp3.internal.connection.StreamAllocation,okhttp3.internal.http.HttpCodec,okhttp3.internal.connection.RealConnection)(TbsSdkJava:147)
	okhttp3.internal.http.RealInterceptorChain.okhttp3.Response proceed(okhttp3.Request)(TbsSdkJava:121)
	okhttp3.RealCall.okhttp3.Response getResponseWithInterceptorChain()(TbsSdkJava:200)
	okhttp3.RealCall.okhttp3.Response execute()(TbsSdkJava:77)
	retrofit2.OkHttpCall.retrofit2.Response execute()(TbsSdkJava:180)
	retrofit2.adapter.rxjava2.CallExecuteObservable.void subscribeActual(io.reactivex.Observer)(TbsSdkJava:41)
	io.reactivex.Observable.void subscribe(io.reactivex.Observer)(TbsSdkJava:12005)
	retrofit2.adapter.rxjava2.BodyObservable.void subscribeActual(io.reactivex.Observer)(TbsSdkJava:34)
	io.reactivex.Observable.void subscribe(io.reactivex.Observer)(TbsSdkJava:12005)
	io.reactivex.internal.operators.observable.ObservableMap.void subscribeActual(io.reactivex.Observer)(TbsSdkJava:33)
	io.reactivex.Observable.void subscribe(io.reactivex.Observer)(TbsSdkJava:12005)
	io.reactivex.internal.operators.observable.ObservableOnErrorNext.void subscribeActual(io.reactivex.Observer)(TbsSdkJava:38)
	io.reactivex.Observable.void subscribe(io.reactivex.Observer)(TbsSdkJava:12005)
	io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.void run()(TbsSdkJava:96)
	io.reactivex.Scheduler$DisposeTask.void run()(TbsSdkJava:571)
	io.reactivex.internal.schedulers.ScheduledRunnable.void run()(TbsSdkJava:66)
	io.reactivex.internal.schedulers.ScheduledRunnable.java.lang.Object call()(TbsSdkJava:57)
	java.util.concurrent.FutureTask.run(FutureTask.java:237)
	java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272)
	java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
	java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
	java.lang.Thread.run(Thread.java:776)

My Code
       
	// called
	.onErrorResumeNext(new ErrorResultFunc<>())
	
	// Function
    private class ErrorResultFunc<T> implements Function<Throwable, Observable<T>> {
        @Override
        public Observable<T> apply(Throwable throwable) throws Exception {
            return Observable.error(ExceptionEngine.handleException(throwable));
        }
    }
	
	public static ApiException handleException(Throwable e) {
        ApiException ex;
        if (e instanceof HttpException) {//HTTP错误
		······
        } else if (e instanceof UnknownHostException) {//地址解析错误，视为网络错误
            ex = new ApiException(e, ERROR.NETWORD_HOST_ERROR);
            ex.setMsg(String.format(WeikeApplication.getContext().getString(R.string.host_parse_error), ERROR.NETWORD_HOST_ERROR));
            return ex;
        } else if (e instanceof SSLException) {//证书验证错误，视为请求错误
            ex = new ApiException(e, ERROR.SSL_ERROR);
            ex.setMsg(String.format(WeikeApplication.getContext().getString(R.string.ssl_error), ERROR.SSL_ERROR));
            return ex;
        } else if (e instanceof EOFException) {//文件结束异常
            ex = new ApiException(e, ERROR.EOF_ERROR);
            ex.setMsg(String.format(WeikeApplication.getContext().getString(R.string.eof_error), ERROR.EOF_ERROR));
            return ex;
        } else if (e instanceof FileNotFoundException) {//读写权限
            ex = new ApiException(e, ERROR.FILE_NOT_FOUND_ERROR);
            ex.setMsg(String.format(WeikeApplication.getContext().getString(R.string.file_not_found_error), ERROR.FILE_NOT_FOUND_ERROR));
            return ex;
        } else {//未知错误
            ex = new ApiException(e, ERROR.UNKNOWN);
            ex.setMsg(e.getMessage() + "(" + ERROR.UNKNOWN + ")");
            return ex;
        }
    }
	
	// ApiException.class
	public class ApiException extends Exception {
		private int code;
		private String msg;

		public ApiException(Throwable throwable, int code) {
			super(throwable);
			this.code = code;
		}

		public void setMsg(String msg) {
			this.msg = msg;
		}

		public String getMsg() {
			return msg;
		}

		public int getCode() {
			return code;
		}
	}

**Comment by akarnokd** [comment]
What is the problem?

**Comment by JasonLian2020** [comment]
@akarnokd 

My Problem：I don't know why this crash happened.

Locate in the **RxJava** code. -->**RxJavaPlugins.class**

Line 367？

	360    public static void onError(@NonNull Throwable error) {
	361        Consumer<? super Throwable> f = errorHandler;
	362
	363        if (error == null) {
	364            error = new NullPointerException("onError called with null. Null values are generally not allowed in 2.x operators and sources.");
	365        } else {
	366            if (!isBug(error)) {
	367                error = new UndeliverableException(error);
	368            }
	369        }
	370
	371        if (f != null) {
	372            try {
	373                f.accept(error);
	374                return;
	375            } catch (Throwable e) {
	376                // Exceptions.throwIfFatal(e); TODO decide
	377                e.printStackTrace(); // NOPMD
	378                uncaught(e);
	379            }
	380        }
	381
	382        error.printStackTrace(); // NOPMD
	383        uncaught(error);
	384    }

**Comment by akarnokd** [comment]
There is a nice javadoc on [the method](https://github.com/ReactiveX/RxJava/blob/2.x/src/main/java/io/reactivex/plugins/RxJavaPlugins.java#L339), have you read it?

**Comment by JasonLian2020** [comment]
@akarnokd OK，I'm trying to call **setErrorHandler** in **Application**.

If I have any questions, ask again.


My Code

	// Application.class
	public void onCreate() {
        super.onCreate();
        ``````
		setRxJavaErrorHandler();
    }

	// method
    private void setRxJavaErrorHandler() {
        RxJavaPlugins.setErrorHandler(new Consumer<Throwable>() {
            @Override
            public void accept(Throwable throwable) throws Exception {
                ``````
            }
        });
    }

**Comment by akarnokd** [comment]
Looks like this question has been answered. If you have further input on the issue, don't hesitate to reopen this issue or post a new one.
