### ISSUE TITLE
Should we have a code check for ObjectHelper.requireNonNull on a primitive?

### ISSUE THREAD

**Issue by jnlopar** [ReactiveX/RxJava#6013]
I found a couple small instances of `ObjectHelper.requireNonNull` being used on primitive ints, which I patched in #6012 . Does the Rx codebase have a code pattern checking framework that we could augment to find other potential instances of this that could be causing unnecessary boxing? Errorprone, for example, has this check: https://errorprone.info/bugpattern/PreconditionsCheckNotNullPrimitive for a similar pattern on Guava's `Preconditions.checkNotNull`, so having one for `ObjectHelper` could be potentially useful here.

**Comment by akarnokd** [comment]
You could create trap overloads that always throw then see if something does crash or shows up as dependency on that method.
