### ISSUE TITLE
Single.flatMapPublisher full implementation

### ISSUE THREAD

**Issue by davidmoten** [ReactiveX/RxJava#6015]
I noticed `Single.flatMapPublisher` is implemented as `toFlowable().flatMapPublisher(...)` which subjects the one flowable to batched requests. I'd like to have requests go straight through to the one flowable. Can I contribute this operator?

The operator at the moment is at https://github.com/davidmoten/rxjava2-http/blob/master/src/main/java/org/davidmoten/rx2/io/internal/FlowableSingleFlatMapPublisher.java without fusion. I can add more tests, fusion (transitive as per `doOnEach`) and follow the projects's naming and visibility conventions.

**Comment by akarnokd** [comment]
Sure.

**Comment by akarnokd** [comment]
In case you haven't started yet, you may want to wait for #6017 so the changes can be benchmarked.

**Comment by davidmoten** [comment]
That's brilliant, thanks

**Comment by davidmoten** [comment]
A question about fusion. I notice that `timeout(Long, TimeUnit)` doesn't support fusion and I suspect the operator I'm writing is similar. The problem is that a subscription is handed to downstream while the Single emission is being calculated and the resultant mapped Flowable is unknown. Just after the subscription is handed to downstream (via `onSubscribe`) `requestFusion` is called but of course at that point the fusion characteristics of the mapped Flowable is unknown and `QueueFuseable.NONE` is returned. 

Should I chase fusion for this operator? Any suggestions?

**Comment by akarnokd** [comment]
Fusion won't work here due to the delayed subscription to the Flowable. Don't bother with it.

**Comment by davidmoten** [comment]
Righto, ta.
