### ISSUE TITLE
crash 之后线程池停止运行，添加任务失败，捕获不到异常

### ISSUE THREAD

**Issue by SJJ-dot** [ReactiveX/RxJava#6016]
crash 之后线程池停止运行，添加任务失败，捕获不到异常

**Comment by SJJ-dot** [comment]
Android。crash 之后  在exceptionhandler中。   
 线程池停止运行，添加任务失败，捕获不到异常。

**Comment by radityagumay** [comment]
@lTBeL i believe you should post sample code for this
