### ISSUE TITLE
Retry root observable.

### ISSUE THREAD

**Issue by Merseyside** [ReactiveX/RxJava#6020]
Hi! I using Retrofit to send request to server. This looks like this:
`
    @POST("tapi")
    Observable<InfoTradeResponse> getInfoObservable(@FieldMap Map<String, String> params, @HeaderMap Map<String, String> headers);`

This api calls in method calls **login()**. After that I check status of this response. If it got an error i throw an exception and trying to retry all chain starts with **login()**. But it doesn't work like I expect. It calls one time **login()** and many times calls Observable returns me by flatMap() operator. But I need retry all chain, start with root Observable returns by login().

Here is my code on pastebin:
https://pastebin.com/cfXUgttj

What is the right chain of operators in this case?
Thank you!

Log:
D/YobitApi: login
D/YobitResponseCreator: params = method=getInfo&nonce=0
D/YobitResponseCreator: signed = 53ed824a89f8f48b5baa0c536751f934a96d9e7766cd3c9fc028f06a70b860bd5cc06f89e9cb7db7423a54b85e971a546f7594161a33b49e4c13490f713a9dc1
D/YobitApi: KeysNonceError
D/YobitApi: KeysNonceError
D/YobitApi: KeysNonceError
D/YobitApi: KeysNonceError
D/YobitApi: KeysNonceError
D/YobitApi: KeysNonceError
D/YobitApi: KeysNonceError

**Comment by akarnokd** [comment]
I can only see `tryToLogin` and no `flatMap`s. Besides, this type of question is better asked on StackOverflow.

**Comment by Merseyside** [comment]
Yeah, its map instead of flatMap. login() in third line. 
I asked on stack, no profit :(

**Comment by akarnokd** [comment]
Not sure what's wrong. Should the secret and the nonce generated fresh for each login or not? If so, just do something like:

```java
Observable.defer(() -> {
    int nonce = calculateFreshNonce();
    return login(api, secret, nonce)
    ...
});
```

Also you'w want to use `retryWhen` instead of `repeatUntil` to avoid storming the service:

```java
.retryWhen(err -> {
    int[] count = { 0 };
    return error
        .takeWhile(v -> count[0]++ <= Constants.MAX_RETRY)
        .delay(count[0] * 100, TimeUnit.MILLISECONDS);
})
```

**Comment by Merseyside** [comment]
Thank you so much. Works as expected now :)

**Comment by Merseyside** [comment]
I got one more question. When counts is over how can I handle it and throw error to interactor?

Now I'm doing it like this:
`.retryWhen(new RetryWithDelay(Constants.MAX_RETRY, Constants.RETRY_DELAY))
        .onErrorResumeNext(throwable -> {
            return Observable.just(false);
        });`

Nothing happens in onErrorResumeNext. Problems is interactor waiting forever for Observable.

**Comment by akarnokd** [comment]
Instead of `takeWhile`, use `flatMap` and return `Observable.just()` to repeat or `Observable.error()` to break with the last error.

**Comment by Merseyside** [comment]
It works, Thank you! :)
