### ISSUE TITLE
2.x: error handling - exception swallowed after explicit .dispose().

### ISSUE THREAD

**Issue by yunikkk** [ReactiveX/RxJava#6025]
Library verision : 2.1.7

The following code will silently swallow thrown exception without signalling to RxPlugins. 
```
        val subject = PublishSubject.create<Unit>()

        var disposable: Disposable? = null
        disposable = subject.subscribe(
                {
                    disposable?.dispose()
                    throw Exception("test")
                }
        )

        subject.onNext(Unit)
```

The same applies to BehaviourSubject, *Processor, but not SingleSubject or Observable.just (.range etc. ). Though sections about error handling are almost equal in [PublishSubject](http://reactivex.io/RxJava/2.x/javadoc/io/reactivex/subjects/PublishSubject.html) and [SingleSubject](http://reactivex.io/RxJava/2.x/javadoc/io/reactivex/subjects/SingleSubject.html).

The reason seems to be located in [LambdaObserver](https://github.com/ReactiveX/RxJava/blob/2.x/src/main/java/io/reactivex/internal/observers/LambdaObserver.java), which doesn't signal onError if is disposed already.

Is it expected behaviour?

**Comment by akarnokd** [comment]
Indeed it does not. The tradeoff here is that your code explicitly indicated it doesn't want to handle further events yet there would be no opportunity to have `onError` not signal to the global error handler.

I'm open for discussion.

**Comment by yunikkk** [comment]
As for me the exception should still be thrown somewhere, as the code is still executed and doing something wrong. So if `.dispose()` is requested and `onError` can not be called - it seems to me that this corresponds 2.x error handling philosophy when the error falls directly into global handler.

**Comment by akarnokd** [comment]
Well, other implementations do route to the global error handler so for the sake of consistency, this should be fixed. PR welcome.
