### ISSUE TITLE
2.x: Automatic shutdown of Executor service when Scheduler is shutdown

### ISSUE THREAD

**Issue by AarjavP** [ReactiveX/RxJava#6027]
Using version io.reactivex.rxjava2:rxjava:2.1.14-RC1

I create my schedulers using `Executors.xxx` methods:
```
Scheduler myScheduler = Schedulers.from( Executors.newSingleThreadExecutor() );
```

Later, when calling `myScheduler.shutdown()` I expected the wrapped Executor to also be shutdown. Looks like the `Schedulers.from` method creates and returns a new instance of `ExecutorScheduler` which does not override the no-op shutdown method from `Scheduler`. Is this an intentional design decision?

Currently the work around is to store a reference to the executor just for shutdown which I would like to avoid. It would be nice to be able to give a flag or something else to have scheduler shutdown the backing executor as well, or a hook on the scheduler where I can register the executor shutdown call at the time of creation.

**Comment by akarnokd** [comment]
This is by design. Since you give RxJava an instance, it can assume you are able to retain that reference and shut down the `ExecutorService` when you need it.

**Comment by AarjavP** [comment]
What is the recommended way to create a self cleaning scheduler with fixed thread pool size and possibly thread factory?

**Comment by akarnokd** [comment]
The [extensions project](https://github.com/akarnokd/RxJava2Extensions#parallelscheduler) has a custom scheduler with parameters for thread count and factory: [ParallelScheduler](https://github.com/akarnokd/RxJava2Extensions/blob/master/src/main/java/hu/akarnokd/rxjava2/schedulers/ParallelScheduler.java#L87).

**Comment by AarjavP** [comment]
awesome, thank you!
