### ISSUE TITLE
1.x Completable.subscribe(rx.CompletableSubscriber s) method return void instead of Subscription.

### ISSUE THREAD

**Issue by dekalo-stanislav** [ReactiveX/RxJava#6032]
`Completable.subscribe(rx.CompletableSubscriber s)` method return `void` instead of Subscription.

I am very curious why so happens, because:
1. All `Observable` and `Single` `subscribe(...)` methods return Subscription
2. Other `Completable.subscribe(...)` methods return subscription:
 * `Subscription subscribe()`
 * `Subscription subscribe(final Action0 onComplete)`
 * `Subscription subscribe(final Action0 onComplete, final Action1<? super Throwable> onError)`

Plus: `Completable.subscribe(Subscriber<T> s)` also returns `void`.

It looks inconsistent, and weird, so I suppose it is an issue.

**Comment by akarnokd** [comment]
1.x is no longer maintained or supported.
