### ISSUE TITLE
2.x: Why not using volatile on parameter `done` in BasicFuseableSubscriber ? Is that safe ?

### ISSUE THREAD

**Issue by happyomg** [ReactiveX/RxJava#6034]
i am using RxJava v2.1.12 , and i have some confused.

Why not using volatile on parameter `done` in BasicFuseableSubscriber ? Is that safe ? would it cause any memory visibility problems ?
The following is my understanding : 
BasicFuseableSubscriber is using at middle operations like map , filter , doOnEach and etc.. its upstream subscriber will ensure thread safe between `onNext` `onComplete` `onError` , so it don't have the necessary to use volatile ?

Is my understanding right ?

**Comment by akarnokd** [comment]
That's correct.

**Comment by pli2014** [comment]
@akarnokd  good job. BTW,  how do we switch threads between onNext onComplete onError in the same subscriber?   observeOn? but I always got same thread...

**Comment by akarnokd** [comment]
Please provide context for what you try to achieve and how do you check for the required thread.
