### ISSUE TITLE
Add possibility to process discarded elements

### ISSUE THREAD

**Issue by mostroverkhov** [ReactiveX/RxJava#6038]
Many operators and Processors just drop items, which becomes a problem with e.g. refcounted elements.
Reactor has related issue https://github.com/reactor/reactor-core/pull/1155. Implementing this properly requires significant changes in library, so I am wondering if updating some `Processor` factories with callback for discarded elements would be good transient solution.

**Comment by akarnokd** [comment]
This is a known property and adds overhead to operators. There was no need for this in our target platforms. On the desktop/server side, you are most likely not restricted to Java 6 so you can use Reactor Core.

**Comment by akarnokd** [comment]
I've decided not to make this change in RxJava. You can always have a custom operator(s) (applied via `compose`) that can do this type of resource-awareness.
