### ISSUE TITLE
2.x: Observable.throttleWithTimeout is confusing

### ISSUE THREAD

**Issue by romanzes** [ReactiveX/RxJava#6043]
The documentation for `Observable.throttleWithTimeout()` implies that it's different from `debounce()` and invites to read about the differences:

> Information on debounce vs throttle:
> <a href="http://drupalmotion.com/article/debounce-and-throttle-visual-explanation">Debounce and Throttle: visual explanation</a></li>
> <a href="http://unscriptable.com/2009/03/20/debouncing-javascript-methods/">Debouncing: javascript methods</a></li>
> <a href="http://www.illyriad.co.uk/blog/index.php/2011/09/javascript-dont-spam-your-server-debounce-and-throttle/">Javascript - don't spam your server: debounce and throttle</a></li>

Of these links, the first one isn't available anymore and the last two are about JS.

Looking at the method's implementation, it becomes clear that in RxJava it's not different from `debounce` in any way:
```java
@CheckReturnValue
@SchedulerSupport(SchedulerSupport.COMPUTATION)
public final Observable<T> throttleWithTimeout(long timeout, TimeUnit unit) {
    return debounce(timeout, unit);
}
```

Do we really need both methods? If yes, could the documentation say explicitly that they are synonyms? Could these links to third-party websites be removed?

**Comment by akarnokd** [comment]
Yes, it is an alias so it can be more easily discovered along the `throttle` methods. `debounce` is a traditional ReactiveX naming and we kept it for historical reasons.

You can update the javadocs (on both `Flowable` and `Observable` if you want. PR welcome.

**Comment by romanzes** [comment]
@akarnokd thanks for the clarification. Will open a PR soon :)

**Comment by akarnokd** [comment]
Closing via #6049
