### ISSUE TITLE
When to use ResourceSubscriber vs DisposableSubscriber?

### ISSUE THREAD

**Issue by ghost** [ReactiveX/RxJava#6050]
What are the differences between ResourceSubscriber and DisposableSubscriber? I looked at the interfaces and noticed that they are mostly the same, except ResourceSubscribe has an add() method to add disposables and DisposableSubscriber does not. Both, however, appear to allow outside access to dispose or request. So then, when are we supposed to use ResourceSubscriber and when are we supposed to use DisposableSubscriber? Asking here to get the community of experts directly, thanks!

**Comment by akarnokd** [comment]
Suggested reading:

- https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0#subscriber
- http://reactivex.io/RxJava/2.x/javadoc/io/reactivex/subscribers/ResourceSubscriber.html
