### ISSUE TITLE
2.x: Taking an element from the Observable randomly

### ISSUE THREAD

**Issue by BoxResin** [ReactiveX/RxJava#6051]
I suggest a feature to take a random element from the Observable.

Pseudo code:
```java
public class Observable<T>
{
    /** Takes a random element. If there is no elements, onComplete() is called.  */
    public Maybe<T> takeRandom();
}
```

**Comment by BoxResin** [comment]
It would work after `onComplete()` of the source observable is called.

**Comment by JakeWharton** [comment]
This seems extremely specialized. You can create this yourself by combining `toList()`, `map()`, and then `singleElement()`.

**Comment by BoxResin** [comment]
@JakeWharton
Thank you for the comment. I might as well consider using `compose()` method. :)
