### ISSUE TITLE
Kotlin type mismatch when using RxJava retryWhen operator

### ISSUE THREAD

**Issue by KonradSzewczuk** [ReactiveX/RxJava#6055]
I am trying create Observable, which will retryWhen when the network connection will be established.

I've created subject:

     private val retrySubject = PublishSubject.create<Unit>()()

And I am using it like this:

      private fun publishNetworkReconnection() {
        compositeDisposable?.add(
           connectionHelper.observeConnection()
            .subscribe {connected: Boolean
              if(connected){
              retrySubject.onNext(null)
              }
            }
         )
      }

Then I am trying to use it in my retryWhen operator:

       val disposable =
        Flowable.interval(0, UPDATE_INTERVAL, TimeUnit.SECONDS, Schedulers.io())
            .onBackpressureDrop()
            .flatMapCompletable {
              revocationRepository.sync(event.id)
            }
            .retryWhen { retryHandler -> retryHandler.flatMap({ nothing -> retrySubject.asObservable() }) }
            .observeOn(AndroidSchedulers.mainThread())
            .subscribe({ }, { Timber.e(it, "Unable to sync blacklist") })
        compositeDisposable?.add(disposable)
      }

How to use it properly in this case?

I am getting this error in Android Studio: 

> Type mismatch. Required: Publisher<< out (???..???) >>! Found: Observable<Void!>!

**Comment by akarnokd** [comment]
As requested in the issue welcome text, don't cross post on multiple forums. Thanks.

https://stackoverflow.com/questions/50967435/kotlin-type-mismatch-when-using-rxjava-retrywhen-operator
