### ISSUE TITLE
2.x: ObservableBufferExactBoundary can emit an empty list on complete

### ISSUE THREAD

**Issue by nateridderman** [ReactiveX/RxJava#6056]
Using RxJava 2.1.10

I noticed different behavior when I use a variant of buffer() that takes a count compared to a variant that takes an Observable as a boundary. When the upstream observable completes, I get an empty list with the latter, but not with the former. Comparing what happens when the source completes in [ObservableBuffer.java](https://github.com/ReactiveX/RxJava/blob/2.x/src/main/java/io/reactivex/internal/operators/observable/ObservableBuffer.java#L128) with [ObservableBufferExactBoundary.java](https://github.com/ReactiveX/RxJava/blob/2.x/src/main/java/io/reactivex/internal/operators/observable/ObservableBufferExactBoundary.java#L112), I noticed the former checks if the buffer is empty before calling actual.onNext(), but the latter does not make this empty check. This seems like a bug to me, and I've seen the empty list emitted in one of my projects. It's also interesting that some of the buffer variants have marble diagrams that show empty items emitted, but the boundary version does not.

**Comment by akarnokd** [comment]
> This seems like a bug to me

This is by design. With a buffer managed by external boundaries, if the boundary fires one expects a buffer with any number of items in it as a response. With the counted buffer, if the last buffer is empty it means the whole sequence length was a multiple of the buffer size and there is no value of having a last empty buffer. You can always filter out empty buffers if you don't need them.

> It's also interesting that some of the buffer variants have marble diagrams

Diagrams are sometimes outdated and sometimes don't try to express every aspect of the operator.

**Comment by nateridderman** [comment]
Thanks for the information! Indeed, I am filtering out the empty buffer so I have a workaround. 

> With a buffer managed by external boundaries, if the boundary fires one expects a buffer with any number of items in it as a response. 

While I agree with this statement, I don't think the boundary completing is the same as when it fires. When it completes, the buffered observable will complete anyways, so I don't see what value it provides to emit an empty list right before it completes.

**Comment by akarnokd** [comment]
The current behavior is there from the beginning and changing it could break existing users who expect (empty) buffer responses upon the barrier signal. You can always filter out elements of flows that you don't need.
