### ISSUE TITLE
[Documentation] Can you please indicate RxJava 1 or 2

### ISSUE THREAD

**Issue by eric-grab** [ReactiveX/RxJava#6058]
This Wiki page looks like it's talking about RxJava 1
https://github.com/ReactiveX/RxJava/wiki/Filtering-Observables

Can you please update  the page and state it clearly there?

**Comment by akarnokd** [comment]
Most of the wiki pages reflect the 1.x era, but you can help upgrading them as part of #6001. Simply post a PR against the file(s) in https://github.com/ReactiveX/RxJava/tree/2.x/docs .
