### ISSUE TITLE
Hi, is it possible to add a `takeWhen` operator?

### ISSUE THREAD

**Issue by tcw165** [ReactiveX/RxJava#6061]
![screen shot 2018-06-23 at 12 15 48 am](https://user-images.githubusercontent.com/6766554/41788028-c940b004-767c-11e8-9c8b-fbb6c2797252.png)

I wrote a blog about this including the code snippet and a concrete example:
https://tech.pic-collage.com/rxjava2-takewhenobservable-f0db9785c4a2

I need your help to see if it's possible to integrate to the library if it's really useful.

**Comment by akarnokd** [comment]
You can do it way simpler without changing RxJava. Simply have an `AtomicBoolean` and filter via it in the chain. You then simply set it on and off, which could happen as `doOnNext` on some other flow or in any method directly.

**Comment by tcw165** [comment]
I still don't get what you describe, so can you provide a simple code snippet? 

The `takeWhen` collects the items emitted during the filter is on, and it dump the items to its observer when the filter is off.

**Comment by akarnokd** [comment]
> collects the items emitted during the filter is on

Oh I see the numbers now. This operator is called `valve` and is available in the extensions project:

- [Example](https://github.com/akarnokd/RxJava2Extensions#flowabletransformersvalve)
- [JavaDoc](https://akarnokd.github.io/RxJava2Extensions/javadoc/hu/akarnokd/rxjava2/operators/FlowableTransformers.html#valve-org.reactivestreams.Publisher-boolean-int-)

**Comment by tcw165** [comment]
I see. Thanks for the clear sample and documentation, and now I realize the idea behind the proposal is already considered as in **Flowable**, which is great! I need to study your existing operator to see if any room for improvement.

As described in the blog post, one of the application for this **Flowable** or **Observable** is to postpone the Android *Activity* result sending at the right moment of when the Android *Activity* is in the right state.

You may come up with more use cases for it in terms of your field.

**Comment by akarnokd** [comment]
I think this operator is too peculiar for RxJava but can live as a transformer in any other library, even in your own.

**Comment by tcw165** [comment]
Agree, thanks @akarnokd .
