### ISSUE TITLE
onError not called for StackOverflowError?

### ISSUE THREAD

**Issue by boris-petrov** [ReactiveX/RxJava#6068]
I'm not exactly sure on the semantics of onError (any of those - Single, Observable, etc) - it has a `Throwable` as an argument however I don't see it being called for `StackOverflowError` for example. Am I doing something wrong or is this by design? If this is by design, a few things:

1) Why is this not written in the documentation?
2) Why is `onError` passed a `Throwable` and not `Exception`?
3) How do I actually catch ANY exception as I need to do some cleanup in all cases (unlock locks e.g.)?

Thanks!

**Comment by akarnokd** [comment]
`StackOverflowError` is considered fatal and is propagated via rethrows as you can't recover from it anyway.

https://github.com/ReactiveX/RxJava/blob/2.x/src/main/java/io/reactivex/exceptions/Exceptions.java#L50

#748

**Comment by boris-petrov** [comment]
Thanks for the response. I've read some of the threads on the topic, it makes sense. Perhaps that should be documented somewhere though. And, still, I'm not sure how to handle my question number 3 - in "normal synchronous" Java I can do:

```java
try {
    lockLocks();
} catch (Throwable t) {
    unlockLocks();
    throw t;
}
```

Which is "safe" in both senses - I unlock the locks and then I rethrow the lethal exception. How can I do the same in Rx?

P.S. Right now I do:

```java
Action doFinally = () -> { unlockLocks() };
maybe.doOnDispose(doFinally).doOnEvent((_unused1, _unused2) -> doFinally.run())
```

But this doesn't work for StackOverflow...

**Comment by akarnokd** [comment]
Don't use locks and RxJava together.

**Comment by boris-petrov** [comment]
Not exactly the answer I was looking for but thanks nevertheless! :)
