### ISSUE TITLE
Subjects have nullable `.value` even when created using `createDefault()`

### ISSUE THREAD

**Issue by feresr** [ReactiveX/RxJava#6069]
Thanks for using RxJava but before you post an issue, please consider the following points:

  - [x] Please include the library version number, 2.1.16
  - [x] If you think you found a bug, please include a code sample that reproduces the problem.

I believe `viewToDocSubject.value` cannot be null:
  
```
private val viewportSubject = BehaviorSubject.createDefault(someDoubleValue)

var viewToDoc: Double
    get() = viewToDocSubject.value // required Double, found Double?
```

I got this error after upgrading from `2.1.0`
Is this by design? am I missing something?

Thanks for a great library!

**Comment by tevjef** [comment]
Consider:
```
private val viewportSubject = BehaviorSubject.create<Double>()

var viewToDoc: Double? = null
    get() = viewportSubject.value 
```

The subject does not yet contain any value so it follows that a call to `getValue()` would result in `null`.

**Comment by TarasMazepa** [comment]
Or

```
var viewToDoc: Double
    get() = viewToDocSubject.value!!
```

Time to learn double exclamation mark operator :)
See this for more details https://stackoverflow.com/questions/34342413/what-is-the-kotlin-double-bang-operator

**Comment by feresr** [comment]
Thanks, I know how to avoid the problem, I wanted to understand why the problem existed in the first place. 
I try to keep my codebase `!!`free whenever possible, it's bad practice to be using it at willy-nilly. It just occurred to me that `.value` will be null if the subject is on a terminal state (error / complete). Will close this issue now. Thanks for your input!
