### ISSUE TITLE
Replace Schedulers.IO/COMPUTATION... because too many thread pool in my app

### ISSUE THREAD

**Issue by Kyson** [ReactiveX/RxJava#6072]
version:2.1.7

I hava some thread pools in my app's util module , and when i use rxjava , there are some other thread pools in Schedulers , i do not want these threads

so can i replace Schedulers thread pool with my util's?

thx :-)

**Comment by akarnokd** [comment]
Please read the documentation of [Schedulers](http://reactivex.io/RxJava/2.x/javadoc/io/reactivex/schedulers/Schedulers.html).
