### ISSUE TITLE
How can I transmiter one element of a List per second

### ISSUE THREAD

**Issue by chxchen** [ReactiveX/RxJava#6073]
I'm not good at English, so I don't find how to do with my problem on Issues and StackOverflow.
Thank you for seeing!
I'm confused with two scenes:
1.How can I transmiter one element of a List per second.
like:
```
Observable.interval(1,TimeUnit.SECONDS)
                .zipWith(Observable.just(1, 2, 3), (aLong, integer) -> aLong)
                .subscribe();

Observable.just(1, 2, 3)
                .delay(5,TimeUnit.SECONDS)
                .zipWith(Observable.interval(1,TimeUnit.SECONDS), (aLong, integer) -> aLong)
                .subscribe();
```
They work fine,but The No.1 breaks the call chaining.  And 'interval' in No.2 will begin when subscribe,therefore "1,2,3" will come together after 5s.

2.How can I control the event flow to keep waiting for a condition.When the condition is ok, the event flow continues to go.
Now, I use `flatmap + interval + timeout` to handle this scene,but I think it urgly.
```
Single.just("1")
                .flatMap(s -> Observable.interval(200,TimeUnit.MILLISECONDS)
                        .filter(al -> condition())
                        .firstOrError()
                        .timeout(10,TimeUnit.SECONDS)
                        .map(al -> s)
                )
                .subscribe(str -> {},throwable -> {});
```
Can you do a favour for me? And there any place I can study some useful Rxjava2 using?

**Comment by akarnokd** [comment]
> - Questions like "how do I X with RxJava" are generally better suited for StackOverflow (where it may already have an answer).

**Comment by chxchen** [comment]
@akarnokd May you tell me a little hint about my problems?
