### ISSUE TITLE
concatArrayEagerDelayError documented but missing? 2.16

### ISSUE THREAD

**Issue by AndreasBackx** [ReactiveX/RxJava#6082]
On 2.1.16 it is documented in the [wiki](https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0#1x-observable-to-2x-flowable) and on [readthedocs](https://rxjava-doc.readthedocs.io/en/latest/What's-different-in-2.0/#1x-observable-to-2x-flowable) that `concatArrayEagerDelayError` is new in RxJava 2 together with:

- [`concatArray`](https://github.com/ReactiveX/RxJava/blob/2.x/src/main/java/io/reactivex/Observable.java#L1259)
- [`concatArrayDelayError`](https://github.com/ReactiveX/RxJava/blob/2.x/src/main/java/io/reactivex/Observable.java#L1286)
- [`concatArrayEager`](https://github.com/ReactiveX/RxJava/blob/2.x/src/main/java/io/reactivex/Observable.java#L1315)

Those are all there, but `concatArrayEagerDelayError` doesn't seem to be implemented:

```kotlin
Observable.concatArrayEagerDelayError()
```

Am I perhaps missing something?

**Comment by akarnokd** [comment]
Looks like `concatArrayEagerDelayError` has not been exposed so far: https://github.com/ReactiveX/RxJava/blob/2.x/src/main/java/io/reactivex/Observable.java#L1341

**Comment by AndreasBackx** [comment]
Yes, I've overlooked that, might've been because I'm on my laptop right now and it's chugging along slowly on those large files on GitHub.

Is the plan to expose this in the future?

**Comment by akarnokd** [comment]
No plans and there was no feature request for them. It would require 6~8 new methods: 

`{Flowable|Observable}.concatArrayEagerDelayError([tillTheEnd[, maxConcurrency [, prefetch]]], sources...)`

and at least 2 diagrams per base class.

**Comment by AndreasBackx** [comment]
I'm up for providing a PR if that's welcome. Thank you in advance for providing me with the methods that would need to be implemented. I haven't dabbled into the RxJava source, but I guess I can figure it out. What would I need to create the diagrams?

Looking at the [tests for concatArrayEager](https://github.com/ReactiveX/RxJava/blob/ab520503925bc9cdff47d6a4ceaf8b2209b61250/src/test/java/io/reactivex/internal/operators/observable/ObservableConcatMapEagerTest.java#L312), and [concatArrayDelayError](https://github.com/ReactiveX/RxJava/blob/ab520503925bc9cdff47d6a4ceaf8b2209b61250/src/test/java/io/reactivex/internal/operators/observable/ObservableConcatTest.java#L779-L796). I assume that I only have to implement the tests like `concatArrayDelay` but for `concatArrayEagerDelayError`.

**Comment by akarnokd** [comment]
I draw them in Excel but others use OmniGraffle or Inkscape.

You can try making a PR.

**Comment by AndreasBackx** [comment]
Small update. I was on holiday and am currently studying for exams for another month so it'll be more than a month till I can get to this unfortunately.

**Comment by akarnokd** [comment]
I've done it and the necessary marbles in #6143.

**Comment by AndreasBackx** [comment]
Too bad for me, I was looking forward to it. :(

Great to have it exposed now though.
