### ISSUE TITLE
2.x: Proposal - don't hold 2.2 release on marble documentation tasks

### ISSUE THREAD

**Issue by ZacSweers** [ReactiveX/RxJava#6088]
Currently, the remaining issues for the 2.2 release look like a nigh-insurmountable amount of work due to 300+ subtasks within them for documentation. There's a lot of new experimental/beta APIs that would be able to be promoted in the meantime though (such as the new `as` operator), and that would allow other libraries to make new stable releases that rely on them. I'd like to propose not holding the 2.2 release on any of these documentation tasks, as they can be continued after 2.2 while promoting the new APIs to beta/final. Thoughts?

**Comment by ZacSweers** [comment]
Disclaimer - I have a vested interest in a 2.2 release with a promoted `as` operator because that's the only thing preventing us from making our AutoDispose library 1.0 🙃. I do objectively worry that barring on that many subtasks might mean it never happens though

**Comment by akarnokd** [comment]
I wanted to ask the same question. I'm fine with a release at the end of July after 2.1.17 is pushed out next week.

**Comment by ZacSweers** [comment]
Awesome, sounds good to me!

**Comment by akarnokd** [comment]
See #6105 for the complete list.
