### ISSUE TITLE
2.x support another source at takeUntil method

### ISSUE THREAD

**Issue by JSpiner** [ReactiveX/RxJava#6107]
I would like to suggest a new feature.

The `observable.takeUntil` function provides the following two types.
```
- takeUntil(ObservableSource<U> other)
- takeUntil(Predicate<? super T> stopPredicate)
```

TakeUntil, which combines the two sources, the first function. This controls until the first item is emitted as shown below.

![2018-07-26 11 15 06](https://user-images.githubusercontent.com/5474864/43237530-328c64b0-90c5-11e8-9814-7e46682940db.png)

The point at which takeUntil controls is when the first item is emit, not when onComplete is called.

here I thought.
'If it detects when the first item is emit, is it possible to support Single or Completable...etc as well as Observable?'

If this suggestion does not depart from the intent of takeUntil of reactiveX,
I want to make a Pull Request that adds the following function.

```
- takeUntil(SingleSource<U> other)
- takeUntil(MaybeSource<U> other)
- takeUntil(CompletableSource<U> other)
- takeUntil(FlowableSource<U> other)
```

If this goes depart from the intent, please tell me why.

Thanks!

**Comment by akarnokd** [comment]
I'm not convinced we need those dedicated variants. Use the appropriate [conversion method](https://github.com/ReactiveX/RxJava#converting-to-the-desired-type).

There is, however, an [outstanding request](https://github.com/ReactiveX/RxJava/pull/6079#issuecomment-405057870) for `Completable.takeUntil(Publisher)` and/or `Completable.takeUntil(ObservableSource)`.

**Comment by JSpiner** [comment]
hmm....

For example,
> Only subscribe for 10 seconds

it would be implements like
```java
observable.takeUntil(Observable.timer(10, SECONDS))
    .subscribe(...);
```

Completable is enough, but should be used as Observable. And
I think there is a possibility of misrepresenting the meaning.

Of course, we can convert Completable to something like this, 
but it does not look good.
```java
observable.takeUntil(Completable.timer(10, SECONDS).toObservable())
    .subscribe(...);
```

**Comment by akarnokd** [comment]
Then use `Observable.timer()` and there is no misinterpretation. If the particular source is not known exactly, use `toObservable()`, otherwise use the same reactive type on the until part as the main source.

**Comment by JSpiner** [comment]
Do we need to discuss for this topic?
If not, I will close the issue.
