### ISSUE TITLE
Add Observable.concatWith variant for item

### ISSUE THREAD

**Issue by marianosimone** [ReactiveX/RxJava#6111]
After looking both at the proposal in #5350 (Observable.concatWith variants for Single, Completable & Maybe) and that `startWith` has a version that takes an item:

```public final Observable<T> startWith(T item)```

How would you feel about a `Observable<T> concatWith(T item)` method? (or why isn't there one already?)

**Comment by akarnokd** [comment]
The `concatWith(Single)` is [optimized pretty decently](https://github.com/ReactiveX/RxJava/pull/5845) and I'm not convinced that concatenating with one final item is that common (whereas `startWith` is common) to warrant an operator.

**Comment by marianosimone** [comment]
Even if it's not as common as starting a stream with just an item, both for API symmetry and ease of writing the use case,  I think it would be a valuable addition.

Right now, I'm doing this instead, which is not very symmetric:

```
myObservable
    .startWith(startValue)
    .concatWith(Single.just(endValue))
```

Obviously, I could do this instead:

```
Observable.concat(
    Observable.just(startValue),
    myObservable,
    Observable.just(endValue)
)
```
But that has a couple of "problems":

1. Forces me to use `Observable`s to wrap things that are in reality `Single`s
2. If I want to inline the definition of `myObservable`, then I'm "forced" to have it indented one level down, while in the original one, it was sitting neatly in the first indentation level.

I can totally live without having this implemented (and using Kotlin, I can just write my own extension method to support it), but thought it could be helpful ;)

**Comment by akarnokd** [comment]
> and using Kotlin

Kotlin is fantastic when it comes to extending RxJava. I suggest you write it for yourself first and then you can consider releasing it as your own library.
