### ISSUE TITLE
2.x: Expectations about stream replayability in libraries

### ISSUE THREAD

**Issue by RikkiGibson** [ReactiveX/RxJava#6112]
Some streams in RxJava will have an equivalent behavior across multiple subscriptions:

```java
Flowable<Integer> numbers = Flowable.just(1,2,3);
```

Others may support only a single subscriber by design:
```java
Flowable<ByteBuffer> responseContent = httpResponse.body();
```

Is there an idiomatic way to indicate in a method signature that:
- a parameter is required to be replayable versus only supporting a single subscriber
- a return type is guaranteed to be replayable versus only supporting a single subscriber

I know you can just put this in the JavaDoc for the parameter, but maybe an annotation would be appropriate here (resembling the `@NonNull` and `@Nullable` annotations).

**Comment by akarnokd** [comment]
You can specify it via annotations but currently there is nothing that could verify it for you, especially across multiple operators that could actually change this property.

**Comment by RikkiGibson** [comment]
Are there any built-in operators in RxJava which require the source stream to be replayable?

Also wondering if replayable is the best term, or if there exists a better term that would be easier for RxJava users to recognize and understand.

I am considering creating such a `@Replayable` annotation or similar in my library, so that it will show up right away in code completion for my users and serve as a hint without them needing to read the Javadoc.

**Comment by RikkiGibson** [comment]
Verification of replayability is a really interesting question, but I'm sure would require flow analysis that could get very complex.

**Comment by akarnokd** [comment]
> Are there any built-in operators in RxJava which require the source stream to be replayable?

Operators don't care about it. The source may decide to signal an error for subsequent subscription attempts.

> Also wondering if replayable is the best term, or if there exists a better term that would be easier for RxJava users to recognize and understand.

We don't use "replayable" as "replay" means caching events and replaying them to future observers. We sometimes call it unicast or "at most one subscriber".

> I am considering creating such a @Replayable annotation or similar in my library, so that it will show up right away in code completion for my users and serve as a hint without them needing to read the Javadoc.

We have the `SchedulerSupport` and `BackpressureSupport` annotations that have no runtime effect at all. They are used by verifying the associated JavaDoc has specific descriptions present.

> I am considering creating such a @Replayable annotation or similar in my library, so that it will show up right away in code completion for my users and serve as a hint without them needing to read the Javadoc.

I wouldn't spin on this topic too much. You should be testing your flows anyway and when users encounter the usual [`IllegalStateException("Only one Subscriber allowed!")`](https://github.com/ReactiveX/RxJava/blob/2.x/src/main/java/io/reactivex/internal/operators/flowable/FlowableGroupBy.java#L532), they apply one of the `publish` operators to make it multicast again.

**Comment by akarnokd** [comment]
Looks like this question has been answered. If you have further input on the issue, don't hesitate to reopen this issue or post a new one.
