### ISSUE TITLE
How to understand the protocol followed by RxJava2 Observable

### ISSUE THREAD

**Issue by CoXier** [ReactiveX/RxJava#6120]
From [doc](http://reactivex.io/RxJava/2.x/javadoc/io/reactivex/Observable.html), RxJava2 says:

> The Observable follows the protocol

>      onSubscribe onNext* (onError | onComplete)?

So can anyone explain this protocol?

In my opinion, above protocol shows `Observable`:

* an observable can be subscribed only once
* emit zero or several items 
* `onError` or `onComplete` appears in behaved well data follow.

I do not know where it's suitable to ask this question here. If not, please tell me. Thanks a lot for this awesome library.

**Comment by artem-zinnatullin** [comment]
You understood it pretty well, good job!

I'll just make it a bit more precise:

- You can subscribe multiple times, but behavior completely depends on the implementation of the `Observable`. However, mostly `Observable`s are "cold" which means they don't do work until you subscribe and they re-do the work for new subscribers.
- Observable can emit zero or several items, absolutely correct
- `onError` and `onComplete` are mutually exclusive. They're considered "terminal" events and well behaved Observable must not emit anything else after such an event. Most of Observables will deliver terminal events, however it's ok for an Observable to be endless.

**Comment by artem-zinnatullin** [comment]
I would recommend to not stop on the `Observable` type, and study other reactive types provided by RxJava library:

- Single
- Completable
- Maybe
- Flowable

If you still have questions, [Reactive Streams Specificication](https://github.com/reactive-streams/reactive-streams-jvm/) might answer some of them. It is a very well written document (everything important is in the README), that basically lists rules that an implementation like RxJava must follow (note that not all RxJava types implement the RS spec directly).

**Comment by CoXier** [comment]
Thanks for your nice explanation @artem-zinnatullin 

I want to know to whom such these methods `onSubscribe` and `onNext` belong?

**Comment by artem-zinnatullin** [comment]
They belong to Subscriber/Observer, RxJava normally uses same/similar terminology as the [Reactive Streams Specification](https://github.com/reactive-streams/reactive-streams-jvm/), I strongly recommend to read it at least twice (you'll need about 3-4 cups of tea/coffee), RxJava docs will be much easier to understand after that!

**Comment by CoXier** [comment]
Thanks again. Ok I will read it now.
