### ISSUE TITLE
3.x: Disambiguate startWith(T|Iterable<T>)?

### ISSUE THREAD

**Issue by akarnokd** [ReactiveX/RxJava#6122]
We were using postfixes to avoid inference problems around operator methods (such as `fromIterable` vs `fromArray`) but there is at least one operator currently, `startWith`, that [may exhibit type ambiguity](https://twitter.com/HansWurst315/status/1024386078785105921). A dedicated postfixed name should resolve the issue, such as:

1. `startWith(T)` + `startWithIterable(Iterable<T>)`
2. `startWithItem(T)` + `startWith(Iterable<T>)` + remove `startWith(T)`
3. `startWithItem(T)` + `startWithIterable(Iterable<T>)` + remove `startWith(T)`.

As a preparation, we can deprecate `startWith(T)` within 2.2.x in case option 2 or 3 is chosen.

**Comment by vanniktech** [comment]
The same also happens with some `onError*` methods.

I'm more inclined towards option 3 but no strong opinion.

**Comment by davidmoten** [comment]
For 3.x I'm happy with 3 also.

**Comment by davidmoten** [comment]
Perhaps instead of `startWithItem` we use `startWithJust` to match our `just` usage?

**Comment by RomanWuattier** [comment]
That's just my two cents' worth I would opt for the option 3.

I think `startWithJust` could be confusing since other methods call `just` for example, `range` when the count value is one or `fromArray` when the length is one.

**Comment by akarnokd** [comment]
3.x is now accepting PRs if somebody wants to tackle this.

**Comment by akarnokd** [comment]
Closing via #6530.
