### ISSUE TITLE
API rate limit example?

### ISSUE THREAD

**Issue by JavierSegoviaCordoba** [ReactiveX/RxJava#6124]
Is there any guide or example about how to manage the rate limit of an API.

API rate limit:

- Two general rate limits (you can know it previously and you can get it via response header too). Per seconds and minutes.
- Two specific rate limit for each method (you get it via response header). Per seconds and minutes.

**Comment by akarnokd** [comment]
Please have a look at some [StackOverflow](https://stackoverflow.com/search?q=%5Brx-java%5D+or+%5Brx-java2%5D+or+%5Bjava-flow%5D+rate+limit) questions and answers.

**Comment by JavierSegoviaCordoba** [comment]
I checked it before post here, but I do not see it clearly :/

**Comment by akarnokd** [comment]
There is not much to go on in your post. What API are you calling in what way? What data types are involved? Have you considered [this answer](https://stackoverflow.com/a/43041029/61158) as a basis?

**Comment by akarnokd** [comment]
You can also see if [Scheduler.when](http://reactivex.io/RxJava/2.x/javadoc/io/reactivex/Scheduler.html#when-io.reactivex.functions.Function-) could be used in your case.
