### ISSUE TITLE
[RxJava2.x][wiki] no fromEmitter() operator 

### ISSUE THREAD

**Issue by CoXier** [ReactiveX/RxJava#6127]
Hi, there is no `fromEmitter()` operator in RxJava1.x and RxJava 2.x now. Should you update wiki? 

https://github.com/ReactiveX/RxJava/wiki/Creating-Observables

**Comment by akarnokd** [comment]
> Should

This is an open-source project. If you find incorrect or missing stuff, you are welcome to post a PR.
The wiki can be PR'd too: https://github.com/ReactiveX/RxJava/tree/2.x/docs

**Comment by CoXier** [comment]
I just remove this line in https://github.com/ReactiveX/RxJava/pull/6128
