### ISSUE TITLE
[2.x] Enable usage of ExecutorScheduler with ScheduledExecutorService without creation of additional threads

### ISSUE THREAD

**Issue by gwarlester** [ReactiveX/RxJava#6130]
2.1.14

I work on an Android app with an existing set of ScheduledExecutorServices. I'd like to use these with RxJava. While `Schedulers.from(Executor)` works, it also creates a number of new threads. From looking at the source for ExecutorScheduler, it appears these threads are unused when the underlying Executor is a ScheduledExecutorService. However, there is no way to bypass the creation of the additional thread. This results in an increased cost in resources / battery (albeit a minor one), which are core constraints on Android, and is making it difficult to integrate.

Can an API be added to enable usage of Schedulers with provided ScheduledExecutorServices without the creation of new threads?

In particular, would it be feasible to split the ExecutorScheduler in two, eg. `ScheduledExecutorScheduler` and `FallbackExecutorScheduler`? This would basically just consist of splitting [if-elses like this](https://github.com/ReactiveX/RxJava/blob/2.x/src/main/java/io/reactivex/internal/schedulers/ExecutorScheduler.java#L54) into two separate classes. `Schedulers.from` could be updated to select the correct implementation. Schedulers would still statically initialize threads, but we'd be able to use the new class directly and bypass that.

If this sounds good, I can take care of the PR.

Thanks!

**Comment by akarnokd** [comment]
What threads are you referring to? The standard scheduler threads don't start until they receive a task.

**Comment by akarnokd** [comment]
You can read about the various standard schedulers in the [javadoc](http://reactivex.io/RxJava/2.x/javadoc/io/reactivex/schedulers/Schedulers.html) and you can shut down schedulers you don't need via the individual [Scheduler.shutdown()](http://reactivex.io/RxJava/2.x/javadoc/io/reactivex/Scheduler.html#shutdown--).

**Comment by gwarlester** [comment]
We're only using the ExecutorScheduler.

We're seeing two threads, with names prefixed with "RxSchedulerPurge" and "RxCachedWorkerPoolEvictor".

I figured they came from Schedulers.single(), as removing that call eliminated the additional threads. However, it looks like the threads are coming from other places, likely the static initializations in Schedulers.

[RxSchedulerPurge](https://github.com/ReactiveX/RxJava/blob/cb05a2614c11ebb7b86e723556f98e50546a50ed/src/main/java/io/reactivex/internal/schedulers/SchedulerPoolFactory.java#L68) looks like it can be disabled with a preference setting, but I haven't been able to get it to work. That's likely because the setting needs to be set on System, which we can't do with an Android config file. Performing the set from a static block seems inconsistent, as it relying on initialization order is inherently buggy.

It's unclear where [RxCachedWorkerPoolEvictor](https://github.com/ReactiveX/RxJava/blob/879d60f797aec6dfe17b5bc344451b5e53f9b09f/src/main/java/io/reactivex/internal/schedulers/IoScheduler.java#L80) is coming from, as I'm not using the IoScheduler at all.

**Comment by gwarlester** [comment]
As an update: overriding the scheduler init methods via RxJavaPlugins appears to work, though it seems brittle.

**Comment by akarnokd** [comment]
They support the standard schedulers. Overriding the standard schedulers via `RxJavaPlugins` is one way, shutting down all standard schedulers is another.

**Comment by gwarlester** [comment]
Do these threads need to be statically initialized on load? Can the initialization at least be made lazy, so they are only created if actually required (like the worker threads themselves)? That would be the most robust solution.

**Comment by akarnokd** [comment]
They support the standard schedulers which are used by most applications by default.

Making them lazy start is complicated because of shutdown as well as the overhead for every scheduler invocation to check if they have to be started or not.

Setting `rx2.purge-enabled` to false should disable the purge thread.

Currently, the evictor thread is initialized as soon as the class is without configuration option. I can imagine adding a `rx2.io-evictor-enable` system property that would let you prevent the startup of the evictor thread.

**Comment by gwarlester** [comment]
RxJavaPlugins will work in the short term, but it still is wasteful: we're creating a bunch of objects that we never plan to use just so RxJava doesn't create its own objects that we also don't actually need.

So, I think this is my real question: why isn't it possible to use RxJava without the standard schedulers?

As mentioned in the first comment, if ExecutorScheduler is increased in specificity to only apply to ScheduledExecutorServices, then all of these operations can be bypassed. This seems like a pretty straightforward thing to do, as described in my first comment. It also seems like it'd provide a (very minor) performance boost overall, as you'd only need to check `instanceof` once (when creating the scheduler) instead of repeatedly (during the regular operation of the scheduler).

**Comment by akarnokd** [comment]
>why isn't it possible to use RxJava without the standard schedulers?

RxJava is a general purpose library and your use case is special.

> This seems like a pretty straightforward thing to do, as described in my first comment. It also seems like it'd provide a (very minor) performance boost overall, as you'd only need to check instanceof once (when creating the scheduler) instead of repeatedly (during the regular operation of the scheduler).

You can have your custom `Scheduler` implementation in your project, for example, by taking `ExecutorScheduler` by source and removing things that are not needed.
