### ISSUE TITLE
NPE in internal LambdaSubscriber 

### ISSUE THREAD

**Issue by Lolmewn** [ReactiveX/RxJava#6139]
Using RxJava 2.2.0 (latest at time of writing), I'm getting an NPE in ` io.reactivex.internal.subscribers.LambdaSubscriber.onNext(LambdaSubscriber.java:68)` (full stacktrace: https://pastebin.com/ydJnRMUJ).

I have some classes that rely on Subscriptions, namely `PlayerContainer`, `StatsPlayer`, `StatsContainer` and `StatTimeEntry`. A PlayerContainer contains StatsPlayers, StatsPlayers contain StatsContainers and StatsContainers contain StatTimeEntries.
PlayerContainer, StatsPlayer and StatsContainer extend `Flowable` and each store their subscribers in an `ArrayList`. Whenever a new value is added, `this.subscribers.forEach(sub -> sub.onNext(value));` is executed.

I think it's pretty straightforward, except for this method I made in my PlayerManager:
```
public Observable<StatsPlayer> getPlayer(UUID uuid) {
        if (this.players.containsKey(uuid)) {
            return Observable.just(this.players.get(uuid));
        }
        if (this.loadingPlayers.containsKey(uuid)) {
            return this.loadingPlayers.get(uuid);
        }
        Observable<StatsPlayer> observable = Observable.fromCallable(StorageManager.getInstance().loadPlayer(uuid))
                .map(statsPlayer -> {
                    this.addPlayer(statsPlayer);
                    return statsPlayer;
                });
        this.loadingPlayers.put(uuid, observable);
        return observable;
    }

    public void addPlayer(StatsPlayer player) {
        this.players.put(player.getUuid(), player);
        this.loadingPlayers.remove(player.getUuid());
        this.subscribers.forEach(sub -> sub.onNext(player));
    }
```

I'm not sure where the issue resides and if more information is needed, but the following piece of code generates the NPE:
```
PlayerManager.getInstance().getPlayer(event.getEntity().getUniqueId()).subscribe(player ->
                StatManager.getInstance().getStat("Deaths").ifPresent(stat ->
                        player.getStats(stat).addEntry( // Creates new StatsContainer if none exists yet and updates subscribers
                                new StatTimeEntry(System.currentTimeMillis(), 1, generateMetadata(event))
                        )
                )
        , Util::handleError);
```

**Comment by akarnokd** [comment]
That particular line can only fail if you don't call `onSubscribe` in your custom `Observable`/`Flowable`/etc. If you are having trouble finding the faulty implementation use [this protocol validator](https://github.com/akarnokd/RxJava2Extensions#protocol-validation) in your code and look for its reports.

**Comment by Lolmewn** [comment]
Hi @akarnokd,
I've added the dependency and calls to my project. 
According to the exception, the subscriptions do flow through the debug dependency, but it appears no issues have been found: https://pastebin.com/QLy2LjzW, as the exception remains the same for the rest.
Do you have any other suggestions? Is it generally better to not make my objects extend Flowable and implement the reactive component differently?

**Comment by akarnokd** [comment]
>PlayerContainer, StatsPlayer and StatsContainer extend Flowable and each store their subscribers in an ArrayList. Whenever a new value is added, this.subscribers.forEach(sub -> sub.onNext(value)); is executed.

That's where the problem is, you don't call `sub.onSubscribe`.

> Is it generally better to not make my objects extend Flowable and implement the reactive component differently?

It is generally not advised to extend `Flowable` directly as it is hard to implement a `Flowable` correctly. Use `Flowable.create()` instead, or what it seems more appropriate in your case, `PublishSubject` to multicast events.

**Comment by Lolmewn** [comment]
Switched all `extends Flowable<T>` instances to a variable `PublishSubject.create()` and delegated its `subscribe` method, I'm now getting my downstream exceptions. Funnily enough it would seem as if my code would've functioned correctly but only if all subscriptions would never throw exceptions.
Thanks for the advice, my issue has been resolved!
