### ISSUE TITLE
Rename unsubscribeOn() to disposeOn()

### ISSUE THREAD

**Issue by UMFsimke** [ReactiveX/RxJava#6142]
Many callbacks and methods are already using `dispose` in name, it does makes sense to rename `unsubscribeOn(Scheduler)` to `disposeOn(Schduler)` in my opinion as we already have `onDispose`, `dispose` and similar methods.

**Comment by akarnokd** [comment]
Many more know it as `unsubscribeOn` from the 1.x era. This has been brought up and discussed before #4646.
