### ISSUE TITLE
2.x: concatWith exception bug

### ISSUE THREAD

**Issue by jlquintana** [ReactiveX/RxJava#6147]
I'm working on a solution using Rx(v.2.1.17) but I'd the following unexpected behavior when I use `concatWith` and I get an exception:

```
Flowable.just("one")
.concatWith(Flowable.error(new RuntimeException()))
.subscribeOn(Schedulers.computation())
.observeOn(AndroidSchedulers.mainThread())
.subscribe(
       item -> log("success: " + item),
       error -> log("error: " + error)
);
```

I expected to get the following output:
```
success: one
error: java.lang.RuntimeException
```

But the result is (bug?):
```
error: java.lang.RuntimeException
```

When I execute this example, without `subscribeOn` and `observeOn`, works as expected.

**Comment by akarnokd** [comment]
Please read the JavaDocs of `observeOn` carefully where the explanation and solution is also given: http://reactivex.io/RxJava/2.x/javadoc/io/reactivex/Flowable.html#observeOn-io.reactivex.Scheduler-
