### ISSUE TITLE
Unremoved subscribers after dispose

### ISSUE THREAD

**Issue by JSpiner** [ReactiveX/RxJava#6160]
version : RxJava 2.2.0

In many ways, such as 'rxLifecycle', the flow is controlled using 'subject' and 'takeuntil'.
The basic flow is similar to the code below.

```java
PublishSubject publishSubject = PublishSubject.create();

Disposable disposable = Single.timer(1000 * 2, TimeUnit.MILLISECONDS)
        .takeUntil(publishSubject.firstOrError())
        .subscribe(
                data -> DLog.i("data : " + data),
                throwable -> DLog.i("error")
        );
// disposable.dispose();

publishSubject.onNext(1); // emit end of lifecycle
DLog.i("end");
```

However, if the subscriber is disposed when the subject is emitted, an error occurs.
(As in the code `disposable.dispose();` above)

```
W: java.util.concurrent.CancellationException
W:     at io.reactivex.internal.operators.single.SingleTakeUntil$TakeUntilOtherSubscriber.onNext(SingleTakeUntil.java:150)
W:     at io.reactivex.internal.subscriptions.DeferredScalarSubscription.complete(DeferredScalarSubscription.java:133)
W:     at io.reactivex.internal.operators.single.SingleToFlowable$SingleToFlowableObserver.onSuccess(SingleToFlowable.java:63)
W:     at io.reactivex.internal.operators.observable.ObservableElementAtSingle$ElementAtObserver.onNext(ObservableElementAtSingle.java:91)
W:     at io.reactivex.subjects.PublishSubject$PublishDisposable.onNext(PublishSubject.java:265)
W:     at io.reactivex.subjects.PublishSubject.onNext(PublishSubject.java:184)
W:     at .......test(test.java:39) // this line is disposable.dispose();
```

I am a bit confused.
I thought 'No matter what the subscriber does, it should not affect the publisher'(edited)
(exclude flowable)

Is this `CancellationException` intended for this situation?
I think subscribers that are dispose within the subject do not seem to be removed.

**Comment by akarnokd** [comment]
I don't understand your post. 

`Single` has to produce an item or an error. Unlike `Observable.takeUntil`, `Single.takeUntil` can't complete a `Single` because it is impossible. It can't emit an item so what remains it signals an exception to stop the upstream `Single`. This error has been chosen to be `CancellationException`.

Upon termination by any of the participating sources of `takeUntil`, it should dispose any remaining subscriptions which you can verify via `publishSubject.hasObservers()` returning false.

The error you listed is from a `PublishSubject.onNext`, not a `dispose()` call.

**Comment by JSpiner** [comment]
> Single has to produce an item or an error. Unlike Observable.takeUntil, Single.takeUntil can't complete a Single because it is impossible. It can't emit an item so what remains it signals an exception to stop the upstream Single. This error has been chosen to be CancellationException.

If so, it looks the error should occur in subscriber's onError, not `subject.onNext`.

I think 'No matter what the subscriber does, it should not affect the publisher'.(edited)

**Comment by akarnokd** [comment]
> If so, it looks the error should occur in subscriber's onError, not subject.onNext.

There is this thing called "call stack" which could include different methods. It is possible an `onNext` will end up calling `onError`.

> I think 'No matter what the subscriber does, it should not affect the subscriber'.

This makes no sense to me.

**Comment by JSpiner** [comment]
> There is this thing called "call stack" which could include different methods. It is possible an onNext will end up calling onError.

Looking at the 'call stack' below, 
it starts from onNext and goes up to SingleTakeUntil.

However, the subscribe code line is not shown here. 
If I have multiple subscribes, I can not find the cause.

That's why the error should occur in subscriber's onError, not subject.onNext.
```
W: java.util.concurrent.CancellationException
W:     at io.reactivex.internal.operators.single.SingleTakeUntil$TakeUntilOtherSubscriber.onNext(SingleTakeUntil.java:150)
W:     at io.reactivex.internal.subscriptions.DeferredScalarSubscription.complete(DeferredScalarSubscription.java:133)
W:     at io.reactivex.internal.operators.single.SingleToFlowable$SingleToFlowableObserver.onSuccess(SingleToFlowable.java:63)
W:     at io.reactivex.internal.operators.observable.ObservableElementAtSingle$ElementAtObserver.onNext(ObservableElementAtSingle.java:91)
W:     at io.reactivex.subjects.PublishSubject$PublishDisposable.onNext(PublishSubject.java:265)
W:     at io.reactivex.subjects.PublishSubject.onNext(PublishSubject.java:184)
W:     at .......test(test.java:39) // this line is disposable.dispose();
```

**Comment by JSpiner** [comment]
Also, even if I use `hasObservers`, the same error will occur in the following cases.

```java
PublishSubject publishSubject = PublishSubject.create();

Disposable disposable1 = Single.timer(1000 * 2, TimeUnit.MILLISECONDS)
        .compose(upstream -> upstream.takeUntil(publishSubject.firstOrError()))
        .subscribe(
                data -> DLog.i("data : " + data),
                throwable -> DLog.i("error")
        );
Disposable disposable2 = Single.timer(1000 * 2, TimeUnit.MILLISECONDS)
        .compose(upstream -> upstream.takeUntil(publishSubject.firstOrError()))
        .subscribe(
                data -> DLog.i("data : " + data),
                throwable -> DLog.i("error")
        );

disposable1.dispose();

if (publishSubject.hasObservers()) {
    publishSubject.onNext(1);
}
```

**Comment by akarnokd** [comment]
You are using that `publishSubject` to stop two different `Single` sequences. Have them work with separate instances of `PublishSubject` so you don't stop the wrong one.

**Comment by ted-prnd** [comment]
@akarnokd 
```
PublishSubject publishSubject = PublishSubject.create();

Disposable disposable = Single.timer(1000 * 2, TimeUnit.MILLISECONDS)
        .takeUntil(publishSubject.firstOrError())
        .subscribe(
                data -> // do something
                throwable -> // handle error
        );
publishSubject.onNext(1); // emit end of lifecycle
```
This code occur `CancelationException` in `subscsribe()`'s consumer.
But if after dispose this single timer (`disposable.dispose();`), timer's error consumer dosen't receive any other `CancelationException`.

Developer thinks they can handle all exception in `subscsribe()`'s error consumer.
But this case(after dispose) will occur `CancelationException` out of error consumer.
I thinks @JSpiner said this point.

**Comment by akarnokd** [comment]
I still don't understand. Please provide a standalone unit test that demonstrates your problem.

**Comment by ted-prnd** [comment]
FYI @akarnokd 
Please run this code.

## Case 1.
```java

        PublishSubject publishSubject = PublishSubject.create();

        Disposable disposable = Single.timer(1000 * 2, TimeUnit.MILLISECONDS)
                .takeUntil(publishSubject.firstOrError())
                .subscribe(
                        data -> Log.d("ted", ""),
                        throwable -> Log.e("ted", throwable.toString())
                );
        publishSubject.onNext(1); // emit end of lifecycle

```
- CancellationException will handle in error cosumer.

## Case 2.
```java

        PublishSubject publishSubject = PublishSubject.create();

        Disposable disposable = Single.timer(1000 * 2, TimeUnit.MILLISECONDS)
                .takeUntil(publishSubject.firstOrError())
                .subscribe(
                        data -> Log.d("ted", ""),
                        throwable -> Log.e("ted", throwable.toString())
                );
        disposable.dispose();

        publishSubject.onNext(1); // emit end of lifecycle

```
- Application will crash not handled


This library version is 2.1.0

**Comment by akarnokd** [comment]
The original post mentions 2.2.0; it works for me.

**Comment by ted-prnd** [comment]
@akarnokd 
Yes, 2.2.0 version does not occur this problem.
I thinks this problem resolved at this commit.
https://github.com/ReactiveX/RxJava/commit/07e126f030a34d25b23c476fdb24384deb028c63#diff-46aae158ce9b767f0477279906db3ebc

When source dispose, other also dispose(), so error not occur.

**Comment by akarnokd** [comment]
Okay, so what is the issue then?

**Comment by ted-prnd** [comment]
You can close this issue.
I thinks @JSpiner think this error still occur at v2.2.0.
But already resolved.

@JSpiner 
Just update your library version. Then your problem will not appear

**Comment by akarnokd** [comment]
@JSpiner please always make sure you run with the latest version of RxJava to avoid situations where you run into bugs fixed months ago.

**Comment by JSpiner** [comment]
@akarnokd @ted-prnd 
oops 
No, it occurs in both `2.2.0`, `2.1.0`

But it need to be clear up. I'll make a new issue.
