### ISSUE TITLE
2.2.0: Improvement. Observable#onErrorReturnItem should return Single

### ISSUE THREAD

**Issue by Oleg-Beloy** [ReactiveX/RxJava#6166]
**Version 2.2.0**

Please look at current method declaration:
` public final Observable<T> onErrorReturnItem(final T item) {
        ObjectHelper.requireNonNull(item, "item is null");
        return onErrorReturn(Functions.justFunction(item));
    }`

According to the documentation & behaviour it _instructs an ObservableSource to emit an item (returned by a specified function) rather than invoking Observer#onError if it encounters an error. It is emitted along with a regular onComplete._ 

That falls under the description of Single.

So my suggestion is to make this method return `Single<T>` to avoid confusing in usage. 
Same for `onErrorReturn` methods
Also consider to add method like `onErrorReturnItemAndPropagateError` to emit the item followed with the error. But of course it could be achieved with `onErrorResumeNext` manually

**Comment by Oleg-Beloy** [comment]
sorry, it is impossible, because in regular case it works like observable

**Comment by akarnokd** [comment]
Changing the return type of any operator is a binary incompatible change and thus they can only happen at major version chages.
