### ISSUE TITLE
Give Flowable.sequenceEqual()/BiPredicate the option to use Single<Boolean> instead of boolean

### ISSUE THREAD

**Issue by Namnodorel** [ReactiveX/RxJava#6169]
I need to compare two `Flowable`s, that unfortunaley, due to `groupBy()` do not complete until all items it contains are subscribed to. 

Currently, this is not possible since test() in the BiPredicate you can implement for `sequenceEqual()` can only return a `boolean`, it expects the `Flowable` to be comparable one by one. I suggest to overload `test()` so that it can also return `Single<Boolean>` - thus allowing the comparison to happen for all elements of the `Flowable` before expecting it to complete, which lets every item be subscribed to.

**Comment by akarnokd** [comment]
I'm not sure what you try to achieve here. `sequenceEqual` compares item by item when both sources have at least one item ready for comparison.

**Comment by Namnodorel** [comment]
@akarnokd Yes. And this one-after-the-other comparison doesn't work if the items are (or come from a Flowable that was a) `GroupedFlowable`s. In that case, the first item won't complete until all the other items are subscribed to. But currently, `sequenceEqual()` waits until the first item comparison completes until it moves on to the next one. For this to work, `sequenceEqual()` would need to be able to compare the `Flowable`s asynchronously.

**Comment by akarnokd** [comment]
Please show some actual code that demonstrates your issue.

**Comment by Namnodorel** [comment]
Given a class `ValueGroup` with an object `key` and a `Flowable`. I want to squash multiple `ValueGroup`s with the same key together, like this:
```
Flowable<ValueGroup> myFlowable = ...;
myFlowable
.groupBy(ValueGroup::getKey)
    .map(groupedValueGroups -> new ValueGroup(
        groupedValueGroups.getKey(),
        groupedValueGroups
            .flatMap((Function<ValueGroup, Publisher<? extends Value>>) ValueGroup::getFlowable)
))
```
At some point later in the code, I then use
```
Flowable.sequenceEqual(myFlowable, anotherFlowable)
```
(`anotherFlowable` is basically the same as `myFlowable`)

What then happens, is: `sequenceEqual()` takes the first item of both Flowables, tries to compare them, and... gets stuck. Because to compare the `ValueGroup`s, the `Flowable`s inside them also need to be compared. But they don't complete, because all the other elements have not yet been subscribed to.

**Comment by akarnokd** [comment]
You have to consume the groups in order for them to make progress. A Single predicate won't help your case as it is too late by then. Turn the groups into Lists and compare that way.

**Comment by Namnodorel** [comment]
Turning `Flowable`s into a `List` is in th category of "it technically works, but it's not really a clean solution"...

I honestly don't quite understand why it wouldn't work for `sequenceEqual()` to call `test()` asynchronously for all objects that it will compare. That way, all `Flowable`s would be subscribed to "at once", and could properly complete. The groups would be consumed in the sense that their comparison emits a `Single<Boolean>`.

**Comment by akarnokd** [comment]
> I honestly don't quite understand why it wouldn't work 

`Flowable.groupBy` has backpressure and in order to have the sequence progress at all, you have to consume all groups it creates. Thus you can't just save up an inner `Flowable` to be compared later.

> call test() asynchronously 

Doesn't work, the operator would subscribe to that `Single` and then hang as well because of the above.

You could try and adapt the following:

```java
Flowable<Flowable<Integer>> seq1 = ...;
Flowable<Flowable<Integer>> seq2 = ...;

Flowable.zip(seq1, seq2, (a, b) -> 
    return Flowable.sequenceEqual(a, b);
)
.flatMapSingle(v -> v)
.all(v -> v);
```

**Comment by Namnodorel** [comment]
>Flowable.groupBy has backpressure and in order to have the sequence progress at all, you have to consume all groups it creates. Thus you can't just save up an inner Flowable to be compared later.

I know, that's not what I'm having trouble with understanding.
>Doesn't work, the operator would subscribe to that `Single` and then hang as well because of the above.

That would happen if it subscribed to only one `Single` at a time. But because it is async, it wouldn't need to wait for the first `Single` to complete, but could instead go on and subscribe to the rest of them as well. Until at some point, it has subscribed to all, and then they'll be able to complete.

I'll try your example.

**Comment by Namnodorel** [comment]
Example is also stuck.

**Comment by akarnokd** [comment]
Try with an `Observable`-based setup.

**Comment by Namnodorel** [comment]
Same result. RxJava makes so much processing so much easier, yet merging multiple datasets based on a key isn't possible without breaking the chain? Hm :/

**Comment by Namnodorel** [comment]
Nevermind, the first example was actually correct, and I made a mistake in implementing it (my actual scenario is a little more complex, but that isn't relevant to the problem itself).

The issue I had is thus solved, however I'd still like to keep the suggestion: Implement this as an alternative to the existing `sequenceEqual()` so that it works with data that can't be compared one after the other for one reason or the other.

**Comment by akarnokd** [comment]
> Nevermind, the first example was actually correct

Great!

> Implement this as an alternative

I'm not convinced this is common enough to add it to RxJava. What if the structure is different? What if other properties are different? What if the operation should be different?

**Comment by Namnodorel** [comment]
Structure? Of what? The elements held in the compared Flowable/Observable? I think that is specific to my case, what's on my mind is more something that is just capable of comparing sequences not "in order".

Basically a `sequenceEqual()` that does what your example did, but instead of returning `Flowable.sequenceEqual(a, b)` in `zip()` accessing an interface similar to `BiPredicate`, with the change of returning a `Single<Boolean>`. The elements themselves would be compared like usual; if they contain (or are) nested Flowables/Observables, you'll need a custom implementation of the comparing interface one way or the other.

Regarding being common... Well, to me it sounds like it could be common enough to be included, but - well, you're the expert :D
