### ISSUE TITLE
2.2.x: ObservableTakeUntil silently drops onNext events if it's currently processing an onNext event

### ISSUE THREAD

**Issue by rohandhruva** [ReactiveX/RxJava#6170]
Until RxJava 2.1, an `AtomicBoolean` was used inside `ObservableTakeUntil`, and the wrapped `ObservableTakeUntil` was able process `onNext` events happening at the same time because it directly called `onNext` on the `actual` observable. 

RxJava 2.2 switched to using an `AtomicInteger` internally, which is set to "1" as an `onNext` is being processed. Each `onNext` is also passed to the `HalfSerializer.onNext`.  If another `onNext` comes in the meantime, it's silently dropped by [`HalfSerializer.onNext`](https://github.com/ReactiveX/RxJava/blob/5445b4a18088a14185eb4bd7f2f7556a48698755/src/main/java/io/reactivex/internal/util/HalfSerializer.java#L44) because `wip.get()` is not zero. This effectively means that while an event is being processed by an `ObservableTakeUntil`, it drops any other events coming in `onNext`. 

Here's a short code sample that demonstrates the problem. When the `takeUntil` is commented out, both events 1 and 2 are processed, but with the `takeUntil`, only event 1 is processed. 

```kotlin
package rxjavabug

import io.reactivex.rxkotlin.subscribeBy
import io.reactivex.subjects.PublishSubject

fun main(args: Array<String>) {
    val destroyObservable = PublishSubject.create<Unit>()
    val eventsPublisher = PublishSubject.create<TestEvents>()

    eventsPublisher
            .takeUntil(destroyObservable)  // Commenting this line prints both events
            .subscribeBy(
                    onNext = {
                        when (it) {
                            is TestEvents.TestEvent1 -> {
                                System.out.println("Got event 1!")
                                eventsPublisher.onNext(TestEvents.TestEvent2)
                                Thread.sleep(1000)
                            }
                            is TestEvents.TestEvent2 -> {
                                System.out.println("Got event 2!")
                            }
                        }
                    }
            )

    eventsPublisher.onNext(TestEvents.TestEvent1)
}

sealed class TestEvents {
    object TestEvent1 : TestEvents()
    object TestEvent2 : TestEvents()
}
```

**Comment by akarnokd** [comment]
> This effectively means that while an event is being processed by an ObservableTakeUntil, it drops any other events coming in onNext.

The Observable protocol disallows reentrant `onNext`s so the bug is in your code calling `PublishSubject.onNext` from an `onNext` handler of the same flow.

If you, for some reason, need a feedback loop, use `PublishSubject.toSerialized()` which will work properly in such scenarios.

**Comment by rohandhruva** [comment]
@akarnokd , thank you for the explanation. I did not realise that code like this violates the Observable protocol. 

That said, it's _really_ easy to get in such a situation: my example code is obviously contrived, but imagine multiple (50-60?) UI elements on android sharing one observable stream to send events. It's not hard to imagine a situation where processing one event generates one or more other events on that shared stream. And since there are so many subscribers to run through for each event, it's likely to block. 

While I understand that I'm in violation of the spec, losing events seems like an odd penalty to pay just because I'm using `takeUntil`.

Do you think it's worth throwing an error when this happens, instead of silently swallowing the event? Also, this seems like a big change between 2.1 and 2.2: maybe it's worth calling out somewhere in the changelog or the javadoc for `takeUntil`? 

Thank you!

**Comment by julianomoraes** [comment]
+1 on @rohandhruva, silently dropping the event seems very unreliable and make `takeUntil` not consistent with other types of Observables.

I would suggest to make this behavior consistent with all kinds of Observables and not only `takeUntils`, or fire an `onError` when the ObservableTakeUntil drops it.

**Comment by akarnokd** [comment]
> Do you think it's worth throwing an error 

In `takeUntil` it is impossible to distinguish between an invalid concurrent `onNext` invocation from a valid concurrent termination signal.

> like an odd penalty

Violating the protocol leads to undefined behavior. Checking if one violates the protocol is expensive-to-impossible generally and even if, it would add overhead penalizing everybody, even the good citizens.

> this seems like a big change

It is a completely legal change as operators expect the protocol is followed. Besides, the `PublishSubject` javadoc specifically calls out for reentrant use: http://reactivex.io/RxJava/2.x/javadoc/io/reactivex/subjects/PublishSubject.html

> Calling onNext(Object), onError(Throwable) and onComplete() is required to be serialized (called from the same thread or called non-overlappingly from different threads through external means of serialization). The Subject.toSerialized() method available to all Subjects provides such serialization and **also protects against reentrance (i.e., when a downstream Observer consuming this subject also wants to call onNext(Object) on this subject recursively).**

In addition, the change made you detect you have an invalid usage of `PublishSubject` in your codebase after all.

**Comment by rohandhruva** [comment]
Fair points. I do want to mention that adding `.toSerialized()` to my `PublishSubject` before the `takeUntil` did not help: the second event is still silently dropped. 

This is the new code snippet, still only prints "Got event 1!". 
```kotlin
package rxjavabug

import io.reactivex.rxkotlin.subscribeBy
import io.reactivex.subjects.PublishSubject

fun main(args: Array<String>) {
    val destroyObservable = PublishSubject.create<Unit>()
    val eventsPublisher = PublishSubject.create<TestEvents>()

    eventsPublisher
            .toSerialized()
            .takeUntil(destroyObservable)  // Commenting this line prints both events
            .subscribeBy(
                    onNext = {
                        when (it) {
                            is TestEvents.TestEvent1 -> {
                                System.out.println("Got event 1!")
                                eventsPublisher.onNext(TestEvents.TestEvent2)
                                Thread.sleep(1000)
                            }
                            is TestEvents.TestEvent2 -> {
                                System.out.println("Got event 2!")
                            }
                        }
                    }
            )

    eventsPublisher.onNext(TestEvents.TestEvent1)
}

sealed class TestEvents {
    object TestEvent1 : TestEvents()
    object TestEvent2 : TestEvents()
}
```

**Comment by akarnokd** [comment]
You have to signal to the serialized Subject, not the original `PublishSubject`:

```kotlin
val eventsPublisher = PublishSubject.create<TestEvents>().toSerialized()
```
