### ISSUE TITLE
2.x: explain null plugin returns better

### ISSUE THREAD

**Issue by akarnokd** [ReactiveX/RxJava#6172]
When an `onSubscribe` hook is installed and returns a null consumer, the current error report says:

```java
ObjectHelper.requireNonNull(observer, "Plugin returned null Observer");
```

At least an "a" is missing but perhaps it would be better to word it more detailed:

> "The RxJavaPlugins.onSubscribe hook returned a null Observer. Please check the handler provided to RxJavaPlugins.setOnObservableSubscribe for invalid null returns. Further reading: https://github.com/ReactiveX/RxJava/wiki/Plugins"

Of course, all reactive types should be updated and adapted to the appropriate types and method names.

**Comment by logan-firefly** [comment]
I'm inexperienced but I would be a happy to try and help with this issue.

**Comment by akarnokd** [comment]
Closing via #6175.
