### ISSUE TITLE
2.2.1 ConnectedFlowable does not call complete or finally

### ISSUE THREAD

**Issue by liujoshua** [ReactiveX/RxJava#6176]
Hello,

I discovered a possible bug when connecting to an infinite `ConnectedFlowable` source. When I use a `ConnectedFlowable` source that terminates (like from an array), I receive _finally_ as expected. With an infinite source, no termination event is produced. 

I am able to turn the flow of data on and off using a `ConnectedFlowable`. However, after I turn off the `ConnectedFlowable`, no _complete_ or _finally_ is emitted.

At first, I thought maybe this is because I can call `connect` again to restart the flow. However, Calling `connect` does not emit additional next` calls. 

I am able to use the `Subscription` to call cancel, in which case I receive a _cancel_ and _finally_. 

[Test Code](https://gist.github.com/liujoshua/7a90bf698c31e6c8a08af906d930e26a)

**Comment by akarnokd** [comment]
Disconnecting a `ConnectableFlowable` does not call any terminal signal by design. You have to dispose the consumers first or use other means to have them get a terminal signal (such as `takeUntil`).

**Comment by liujoshua** [comment]
Thank you, that makes sense to me.

I'd like to implement the ability to pause and un-pause (as many times as needed) the flow of data to a set of downstream recorders. Is the way to achieve this by using `filter` with a `ConnectedFlowable`? 

If the caller of `connect` can synchronously disconnect the `ConnectedFlowable`, and disconnect does not send a terminal event, is there a way for the `ConnectedFlowable` to emit more items after a disconnect?  Calling `connect` subsequent times seem to have no effect.
 
If there is no way to reestablish the flow of items, it would seem that `ConnectedFlowable` functions like `skipUntil` or `filter` from the downstream's perspective, except without a terminal signal. It does provide efficiency benefits in that it does not subscribe to the upstream at all until `connect`, and is not just tossing items.

It would be great if `ConnectedFlowable` could be connected multiple times and subscribe/unsubscribe from the upstream, since this would seem more efficient than `filter`ing items to achieve the pausing effect. Since no termination signal is sent on disconnect of the upstream, seems it would be possible to support reestablishment of event flow.

**Comment by akarnokd** [comment]
There is an extension operator that lets you pause a sequence without disconnecting or losing data: https://github.com/akarnokd/RxJava2Extensions#flowabletransformersvalve

Otherwise, you could try `filter` if dataloss is not an issue.

**Comment by liujoshua** [comment]
Thank you

**Comment by liujoshua** [comment]
I am connecting to sensors on Android, so disconnecting a `ConnectedFlowable` is nice so it releases the sensor while `filter` would not. I think I can achieve pausing (discarding while paused) and releasing the sensor with `merge`(<Publisher<Publisher>>), adding a new `ConnectedFlowable` to reconnect with the sensor. Or do you have another suggestion?

Thanks for the advice
