### ISSUE TITLE
Publish Subject onerrror making app crash?

### ISSUE THREAD

**Issue by iamaravindh** [ReactiveX/RxJava#6181]
when subscribers get terminated automatically for some reasons. app is crashing in some devices. i assume the the publishsubject is running on background thread and subscribers become null..

```
 public void onError(Throwable t) {
        if (subscribers.get() == TERMINATED) {
            RxJavaPlugins.onError(t);
            return;
        }
        error = t;
    }
```
the above  `RxJavaPlugins.onError(t);` get called. i am attaching more stack traces.

````
io.reactivex.plugins.RxJavaPlugins.onError (RxJavaPlugins.java:367)
io.reactivex.subjects.PublishSubject.onError (PublishSubject.java:240)
com.VoDrive.util.S3Uploader$1.onStateChanged (S3Uploader.java:47)
com.amazonaws.mobileconnectors.s3.transferutility.TransferStatusUpdater$1.run (TransferStatusUpdater.java:187)
````

**Comment by akarnokd** [comment]
You are not allowed to call `onError` after `onComplete` and vice versa.

Suggested reading:

- http://reactivex.io/RxJava/2.x/javadoc/io/reactivex/subjects/PublishSubject.html
- http://reactivex.io/RxJava/2.x/javadoc/io/reactivex/Observer.html

**Comment by iamaravindh** [comment]
@akarnokd  then how to pass a error message?

**Comment by akarnokd** [comment]
What are you trying to achieve? Do you have multiple errors to deal with. Consider using [RxRelay](https://github.com/JakeWharton/RxRelay) instead with `Notification` objects wrapping your errors.

**Comment by iamaravindh** [comment]
i am using publishsubject for communicating to s3 servers.

u can see  [here](https://aws.github.io/aws-sdk-android/docs/reference/com/amazonaws/mobileconnectors/s3/transferutility/TransferObserver.html)

when transfer observer gives `onerror` , i am calling `publishSubject.onError` to communicate back to ui

**Comment by akarnokd** [comment]
Define the subject as `PublishSubject<Notification<T>>` and instead of calling `onError`, call `onNext(Notification.createOnError(exception)))`. Adjust the rest of the flow accordingly.

**Comment by iamaravindh** [comment]
@akarnokd  i can understand . but what is the reason behind, onError designed that way? when 
onNext  can simply return void when its terminated.
```
   public void onNext(T t) {
        ObjectHelper.requireNonNull(t, "onNext called with null. Null values are generally not allowed in 2.x operators and sources.");
        if (subscribers.get() == TERMINATED) {
            return;
        }
```

**Comment by akarnokd** [comment]
Please read this: https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0#error-handling

**Comment by iamaravindh** [comment]
@akarnokd  thanks for d link.

i have fixed by checking 

```
if (subject.hasObservers())
                subject.onError(ex);
```

**Comment by akarnokd** [comment]
Great!
