### ISSUE TITLE
Why doesn't Flowable#buffer(long, TimeUnit, int) support backpressure?

### ISSUE THREAD

**Issue by slisaasquatch** [ReactiveX/RxJava#6190]
Why doesn't Flowable#buffer(long, TimeUnit, int) support backpressure?

I'm using version 2.2.1, and here's the code for my experiment:
```java
	public static void main(String[] args) throws Exception {
		Flowable.range(0, 10000)
		.buffer(5, TimeUnit.SECONDS, 100)
//		.onBackpressureBuffer()
		.concatMap(list -> {
			System.out.println(list.size());
			return Flowable.just(list).delaySubscription(500, TimeUnit.MILLISECONDS);
		})
		.blockingSubscribe();
	}
```
The code above will cause a `MissingBackpressureException` unless I add `.onBackpressureBuffer()` after `.buffer(5, TimeUnit.SECONDS, 100)`, which is to be expected because the Javadoc for `Flowable#buffer(long, TimeUnit, int)` says `This operator does not support backpressure as it uses time`.

So here are my questions:
1. I understand why a size based buffer can support backpressure while a time based buffer cannot. But why can't a time and size based buffer support backpressure like a purely size based buffer does?
2. Is there a way to achieve a backpressured size based buffer with a time based "kick"?

**Comment by akarnokd** [comment]
> But why can't a time and size based buffer support backpressure like a purely size based buffer does

Because the time part makes it backpressure incompatible and backpressuring would result in time not being honored.

> Is there a way to achieve a backpressured size based buffer with a time based "kick"?

What if the downstream is not ready to receive a buffer when this "kick" happens? Apply one of the `onBackpressureXXX` operators to decide what should happen.

**Comment by slisaasquatch** [comment]
Thanks for your quick reply! I think I understand now. I'll close the issue.
