### ISSUE TITLE
doFinally(), doOnTerminate() not called after dispose() call

### ISSUE THREAD

**Issue by personshelldon** [ReactiveX/RxJava#6192]
Hello! I have a simple function:
```
fun execute(params: T, observer: BaseCompletableObserver) {
        buildUseCaseObservable(params, false)
                .subscribeOn(mWorkScheduler)
                .observeOn(mResultScheduler)
                .doOnSubscribe { addDisposable(it) }
                .doOnDispose { observer.onDispose() }
                .doFinally { observer.onFinally() }
                .doOnTerminate { observer.onOnTerminate() }
                .subscribe(observer)
    }

fun addDisposable(disposable: Disposable) {
        if (mDisposable == null || mDisposable!!.isDisposed)
            mDisposable = CompositeDisposable()
        mDisposable!!.add(disposable)
    }

interface BaseCompletableObserver : CompletableObserver {
    fun onDispose() {}
    fun onFinally() {}
    fun onOnTerminate() {}
}
```
When I run this code all callbacks work normally, but  if this job disposed during runtime (user cancelled) then  `doFinally()` and  `doOnTerminate()` never called, howhever `doOnSubscribe()` works as expected. What am I doing wrong?

**RxAndroidVersion:** 2.1.0
**RxJavaVersion:** 2.2.0
**RxKotlinVersion:** 2.2.0

**Comment by akarnokd** [comment]
You are disposing the sequence too early, basically at the upstream of `doFinally`. Since `dispose()` travels upstream only, the `doFinally` and `doOnDispose` are never invoked. Add the `Disposable` received in the `BaseCompletableObserver.onSubscribe` or move `doOnSubscribe` before `subscribe`.

```kotlin
buildUseCaseObservable(params, false)
                .subscribeOn(mWorkScheduler)
                .observeOn(mResultScheduler)
                .doOnDispose { observer.onDispose() }
                .doFinally { observer.onFinally() }
                .doOnTerminate { observer.onOnTerminate() }
                .doOnSubscribe { addDisposable(it) } // <----------------------------------
                .subscribe(observer)
```

**Comment by personshelldon** [comment]
Oh, my bad! It works. I thought upstream/downstream are actual only for `subscribeOn()` and `.observeOn()` functions. Thanks a lot!

**Comment by akarnokd** [comment]
Recommended reading: https://github.com/ReactiveX/RxJava#upstream-downstream
