### ISSUE TITLE
toList + blockingGet got No instance field actual of type

### ISSUE THREAD

**Issue by andruy94** [ReactiveX/RxJava#6201]
Hello.

  -Rx java version 2.2.1

  - Sample code ```Observable.fromIterable(Collections.asList(1,2,3,4,5).map(it->String.valuesOf(it)).toList().blockinGet()```

In version 2.2.0 this code works fine, but after update i got ```No instance field actual of type Lio/reactivex/Observer; in class Lcom/tspoon/traceur/ObservableOnAssembly$OnAssemblyObserver; or its superclasses (declaration of 'com.tspoon.traceur.ObservableOnAssembly$OnAssemblyObserver' appears in /data/app/<package>-70wiK-18tepU--Vcj9Vf3A==/base.apk!classes5.dex)```

**Comment by akarnokd** [comment]
This is a problem with `com.tspoon.traceur.ObservableOnAssembly`, not RxJava. Please contact the maintainers of that library.

**Comment by andruy94** [comment]
@akarnokd  thanks for answer
