### ISSUE TITLE
I want to create an Observable that enqueues its events as long as there are 0 subscribers, and receive a callback when subscriber count goes from 1 to 0

### ISSUE THREAD

**Issue by Zhuinden** [ReactiveX/RxJava#6202]
>  - [ ] Please include the library version number, including the minor and patch version, in the issue text. In addition, if you'd include the major version in the title (such as `2.x`) that would be great.

RxJava 2.2.0

>   - [ ] Questions like "how do I X with RxJava" are generally better suited for StackOverflow (where it may already have an answer).

Nah. This doesn't seem to exist although [someone else has seem to have worked around it by `extends Relay<T>` instead](https://stackoverflow.com/a/41272402/2413303) but that doesn't look nearly as tricky as typical Rx solutions, so it's unlikely to be correct 😄 

------

I can't seem to find a `doOnUnsubscribe` in RxJava2, which means I can't seem to find a reliable way to get a callback when a connected observable's last subscriber has unsubscribed from it (subscriber count goes from 1 -> 0).

Also, even after calling `publish`, I'm getting multiple calls from `doOnSubscribe`, which is unexpected.

Currently I have this:

``` kotlin
private val eventSource = PublishRelay.create<Event>()
private val gateSource = BehaviorProcessor.createDefault(false)

val pauseQueue: Observable<Event> = eventSource.toFlowable(BackpressureStrategy.BUFFER)
            .publish()
            .refCount()
            .valve(gateSource, false)
            .doOnSubscribe {
                gateSource.onNext(true)
            }
            .doOnTerminate {
                gateSource.onNext(false)
            }
            .toObservable()
```

But:

- I'm not getting the event that is sent into `eventSource` before the first subscriber subscribes

- I'm getting multiple `doOnSubscribe` calls for multiple `subscribe` calls even though I used `publish().refCount()`

- I'm not getting any calls to `doOnTerminate` which I added only because I don't expect `doOnDispose` at this time (although maybe that's what I need here after all)

So how can I make `valve` work based on the number of observers with connected observable? Because this is clearly not working.

**Comment by akarnokd** [comment]
> I want to create an Observable that enqueues its events as long as there are 0 subscribers

Please look at the [UnicastWorkSubject](https://github.com/akarnokd/RxJava2Extensions#unicastworksubject).

> receive a callback when subscriber count goes from 1 to 0

Unless you account the terminated and disposed observers manually, this is not supported in RxJava components.

> I can't seem to find a doOnUnsubscribe in RxJava2

It's either `doOnDispose` or `doOnCancel`; it's in the [What's new in 2.0](https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0#instance-methods) wiki section.

> Nah. This doesn't seem to exist

Such questions are better suited for StackOverflow, where you were pretty active recently yourself. Why not ask this question there?

> I'm getting multiple doOnSubscribe calls for multiple subscribe calls even though I used publish().refCount()

Not sure what you tried to achieve with them. The position of these does matter in respect to the control signals you try to react to.

> I'm not getting any calls to doOnTerminate

It does not react to disposing the sequence. `doFinally` does react to termination and disposing.

**Comment by Zhuinden** [comment]
You're right, technically my initial problem truly is resolved by `UnicastWorkSubject`! 

The `1 -> 0` would have been a question for imitating the behavior of LiveData's `onInactive` callback, but I guess I'll have to make do without that. Usually `Observable.create { emitter.setDisposable {` is enough for most cases.

> Such questions are better suited for StackOverflow. Why not ask this question there?

This wasn't a good question, but at least now I have the answer :confetti_ball: :tada: thanks!
