### ISSUE TITLE
Javadoc is a bit confusing as to what gets disposed

### ISSUE THREAD

**Issue by martinandersson** [ReactiveX/RxJava#6203]
Time and time again I get confused by both how the API is designed, but also how the disposed state or dispose action gets described. But - and I just started learning RxJava so please correct me if I am wrong! - it is not the source, the Observable, that gets disposed. It is the end consumer, the Observer that gets disposed.

One can not "dispose" an Observable. The developer should in this case simply drop all references to the Observable or otherwise "terminate" the observable (through completion or error). However, the observers can be disposed because these are registered with observable. If all of them are disposed, then effectively, the observable cease to "function" or operate because there is no one there to take notice!

Another way to look at it is to "cancel the subscription" (Observer). But again, if another dude wants to buy a newspaper then the printers will keep rollin' (Observable).

If all of this is true, then there's a lot of places both in the architecture and documentation that is simply wrong or misleading.

For example, there exists a non-static method called [Observable.doOnDispose()][1] which by it's sheer presence indicates that the observable may become disposed (?). Further more, the first sentence in this method's javadoc says: "Calls the dispose Action if the downstream disposes the sequence". This is wrong for a number of reasons. Firstly, the method doesn't _call_ anything. It _registers_ a callback. Furthermore, if "the sequence" is the observable itself, then it is wrong because it is not the observable that gets disposed. If "the sequence" refers to the observer, then there can be many of them and not just one; "the sequence". Plus, if the sequence is the observer, then what is the "downstream"?

As another example, this is an extract from the javadoc for [Single][2]: "Like Observable, a running Single can be stopped through the Disposable instance provided to consumers through SingleObserver.onSubscribe(io.reactivex.disposables.Disposable)." Erm no, no and no. The observable is not "stopped", the observer is!! =)

A gist to demonstrate that disposing an observer does not "stop" the observable: https://gist.github.com/martinanderssondotcom/9453c02160eaac5ef30df3ff2e74816e

[1]: http://reactivex.io/RxJava/2.x/javadoc/io/reactivex/Observable.html#doOnDispose-io.reactivex.functions.Action-
[2]: http://reactivex.io/RxJava/2.x/javadoc/io/reactivex/Single.html

**Comment by akarnokd** [comment]
> "Like Observable, a running Single can be stopped through the Disposable instance provided to consumers through SingleObserver.onSubscribe(io.reactivex.disposables.Disposable)."

This is one of the most precise description what happens, but it is also pretty long so the documentation simplifies it to "disposing the sequence" or "disposing the flow" most of the time.

> it is not the source, the Observable, that gets disposed. It is the end consumer, the Observer that gets disposed.

It's not the `Observer` either. Does it have a `dispose` method? No. In the control flow, the `Disposable.dispose()` is called to stop the flow. Some `Observer` subclasses, such as `DisposableObserver` expose a `dispose` method to the outside so the flow can be disposed that way. But it still calls `Disposable.dispose()` on the `Disposable` instance received via `onSubscribe` when the original subscription happened.

> Another way to look at it is to "cancel the subscription" (Observer). But again, if another dude wants to buy a newspaper then the printers will keep rollin' (Observable).

Yes, that's the typical pub-sub terminology. Canceling your subscription won't affect someone else's subscription.

> A gist to demonstrate that disposing an observer does not "stop" the observable: 

I'm not sure why you got confused. Disposing a subscription will stop the sequence. It does not prevent the source Observable to accept new observers or that other observers should be equally stop receiving events. Perhaps you should read about [hot and cold observables](https://blog.thoughtram.io/angular/2016/06/16/cold-vs-hot-observables.html).

**Comment by martinandersson** [comment]
> Like Observable, a running Single can be stopped [...]

I don't think this particular part is what you'd like to label a "precise description"?

We both agree that it is not the Observable that is disposed (or "stopped"). But this is exactly what the docs (and parts of the API; I argue) say. So, they are wrong. What's making it less of a good thing and what caused me to file this issue is the major effect this has on the semantics; Stopping/disposing an Observable indicates to the end user that the entire flow/stream/sequence/whatever is going to shut down and no more observers will be notified.

I do appreciate your feedback, I got slightly more intelligent from it, in that I hold it for true what you said; nor is it the observable that is disposed of. But, I am a far cry away from understanding what exactly gets disposed. In fact, currently, I feel like totally void of knowledge surrounding this concept. I thought I knew; the Observer. But you said it isn't. Gez, what if the docs could provide a bit of insight! ;)

You know sometimes, we simplify too much to the extent that it instead becomes hard to understand. For very important topics; e.g., anything related to life-cycle and how I manage my resources; I would love to have technically correct docs versus "simplified" human lingo. Just saying! Dunno if this applies necessarily to RxJava, I just started out lol.

**Comment by akarnokd** [comment]
To learn RxJava, some people have to overcome their own resistance against the paradigm change required as well as overcome the urge of questioning everything like "why doesn't it work the way I think it should work".

You can learn more about the internals via the [wiki](https://github.com/ReactiveX/RxJava/wiki/Writing-operators-for-2.0) specifically for 2.x and in general for RxJava in my [blog](http://akarnokd.blogspot.com/2015/05/operator-concurrency-primitives.html).

**Comment by martinandersson** [comment]
I must say that you are missing the point. Did you understand what I was getting at?

**Comment by martinandersson** [comment]
..and I must add that I argue javadoc is not meant for or targeting library developers already familiar with the code base. The fact that I "as a newbie" posted this issue should in all fairness have a certain weight.

**Comment by akarnokd** [comment]
All I can give you is more reading. We derive from the Reactive Streams specification so maybe it can clear your confusion: https://github.com/reactive-streams/reactive-streams-jvm#reactive-streams

**Comment by martinandersson** [comment]
David, I appreciate each and every link you have given me. Really, I do! But, it's not really about understanding what happens here during disposal of any resource. I am more concerned with the semantics and what one infer from reading the docs and API.

Either way, seems like our communication is failing and I don't think this is the end of the world. I sorted out my own "issue" by logical deduction and I am sure other will too. I was just hoping to contributing a bit lol.

I extend my greatest and most humble gratitude for your attention =) A big thank you for an awesome library ;)
