### ISSUE TITLE
2.X: ReplaySubject.createWithSize(1) differs from BehaviorSubject.create() when terminal event occurs?

### ISSUE THREAD

**Issue by suribada** [ReactiveX/RxJava#6204]
BehaviorSubject is a Subject with last event in buffer, and usually there is no problem.
But if terminal event occurrs and another observer subscribes to BehaviorSubject, last event is ignored and only terminal event is pushed to observer.
In my opinion, ReplaySubject.createWithSize(1) is similar to BehaviorSubject.create. However if termianl event occurrs and another observer subscribes to ReplaySubject, last event and terminal event are pushed to observer sequentially.
This is an intended action?

**Comment by akarnokd** [comment]
The respective behaviors are clearly stated in their JavaDocs:

http://reactivex.io/RxJava/2.x/javadoc/io/reactivex/subjects/BehaviorSubject.html

> When this BehaviorSubject is terminated via onError(Throwable) or onComplete(), the last observed item (if any) is cleared and late Observers only receive the respective terminal event.

http://reactivex.io/RxJava/2.x/javadoc/io/reactivex/subjects/ReplaySubject.html

> When this ReplaySubject is terminated via onError(Throwable) or onComplete(), late Observers will receive the retained/cached items first (if any) followed by the respective terminal event. If the ReplaySubject has a time-bound, the age of the retained/cached items are still considered when replaying and thus it may result in no items being emitted before the terminal event.
