### ISSUE TITLE
First Observable.create lag

### ISSUE THREAD

**Issue by UvarovBoris** [ReactiveX/RxJava#6206]
Hi, is it possible that Observable.create can lag during first call?
I use Rx 2.1.12 in android project and when create screen do this
```java
Disposable getNotificationsDisposable = Observable.create(
    (ObservableOnSubscribe<List<Notification>>) emitter -> {
            List<Data> data= Manager.getInstance().getData();
            emitter.onNext(data);
            emitter.onComplete();
    })
                .subscribeOn(Schedulers.newThread())
                .observeOn(AndroidSchedulers.mainThread())
                .subscribe(data-> mView.showData(data));
```

I try Schedulers.newThread and Schedulers.io.

Without this code no lag, during second call no lag.

Maybe there is some init method that i can call and speedup first observable create?

**Comment by akarnokd** [comment]
You may be experiencing class loading hiccups or the [framerate limit of the main thread](https://medium.com/@sweers/rxandroids-new-async-api-4ab5b3ad3e93). How do you detect this lag?

**Comment by UvarovBoris** [comment]
I measure this situation and first observable create need much more time, than second. I measure with System.nanoTime and first create was 0.0855 second and second was 0.0012.
Not sure, maybe this problem from this article. Maybe simple just create some fake observable somewhere on app start, and than other observables will created more quick.

**Comment by akarnokd** [comment]
This looks like some platform specific behavior, likely due to class loading. Please ask about this on StackOverflow.
