### ISSUE TITLE
Scheduler.schedulePeriodicallyDirect executes task after it was disposed

### ISSUE THREAD

**Issue by truebden** [ReactiveX/RxJava#6207]
RxJava version: 2.2.2

Example code:
```java
final Disposable schedulePeriodicallyDirect = Schedulers.io().schedulePeriodicallyDirect(new Runnable() {
	private int val = 0;

	@Override
	public void run() {
		System.out.println("executed " + (val++));
	}
}, 1000, 1000, TimeUnit.MILLISECONDS);

//delay waits for the amount if time and executes then the task
delay(2500, new Runnable() {
	@Override
	public void run() {
		schedulePeriodicallyDirect.dispose();
	}
});
```

If you do something like the above code, the base Worker class creates a `PeriodicTask` which owns a `SequentialDisposable` inside the method `Worker#schedulePeriodically`. This `SequentialDisposabled` is returned in `schedulePeriodicallyDirect`, but only the task is returned. When `schedulePeriodicallyDirect.dispose` is called, only the task is disposed and not the `SequentialDisposable`. If then `Scheduler$Worker$PeriodicTask` checks in its `run` function if the `SequentialDisposable` is disposed, it says it is not disposed and schedules a new execution. In the worker then checks if the worker is disposed and does nothing. Afterwords the `FutureTask`s are checked and they were canceled and the task is not scheduled again. So its stops, which is fine.

I have two complaints with this behaviour.
- Firstly another schedule is called, which is actually not needed.
- Secondly if you write some custom workers, which for example throw an exception if they are already disposed, they will fire it in a wrong case.

I would suggest to do something like this in the scheduler:

```java
@NonNull
public Disposable schedulePeriodicallyDirect(@NonNull final Runnable run, final long initialDelay, final long period, @NonNull final TimeUnit unit) {
	final Worker w = createWorker();
	final Runnable decoratedRun = RxJavaPlugins.onSchedule(run);
	final PeriodicDirectTask periodicTask = new PeriodicDirectTask(decoratedRun, w);
	final Disposable d = w.schedulePeriodically(periodicTask, initialDelay, period, unit);

	//main difference is here. We return a composite of the task and the disposable d to ensure both of them get disposed on dispose and not only the task.
	return new CompositeDisposable(periodicTask, d);
}
```

**Comment by akarnokd** [comment]
Disposing a worker is responsible for stopping all outstanding tasks. Ignoring the returned `Disposable` is fine as we need to dispose the worker anyway, which as mentioned before, stops all tasks, including that individual periodic one. 

I'm pretty sure the code properly cancels the task as placing a counted breakpoint in PeriodicTask::run never gets triggered the third time.

**Comment by truebden** [comment]
the task is properly canceled, but for my custom implementation of a worker it does not work. that´s because a schedule on the worker is called and my worker then throws an exception, because it is already disposed and does not return an empty disposable. Therefor I would say it is in general more usable to not ignore the disposable and dipose it. this way the schedule function of the code is not called.

**Comment by akarnokd** [comment]
> but for my custom implementation of a worker it does not work

That's a key information you omitted. Your implementation is then very likely incorrect. Have you read the JavaDocs of [Schedule.Worker](http://reactivex.io/RxJava/2.x/javadoc/io/reactivex/Scheduler.Worker.html) which contains details about what behavior is expected from an implementation.

**Comment by truebden** [comment]
Ah okay, that makes it clear.
I am sorry, I was only checking against the latest version of the code, but did not check the "new" javadoc (almost 7months ago it was updated). I only read the one from 2.1.7 which was included in the main project...

For me, I will stick for the moment to my solution as one of the main issues often is that people miss to cleanup the subscriptions. Throwing an exception makes it a little bit easier to find such issues.
