### ISSUE TITLE
About the concatArray question  

### ISSUE THREAD

**Issue by XiFanYin** [ReactiveX/RxJava#6208]
Use version ：2.1.3   
demand：Read the cache to update the UI, and then request the network to update the UI
example code：
```
    Observable.concatArray(cache,netWork)
                .subscribeOn(Schedulers.io())
                .observeOn(AndroidSchedulers.mainThread())
                .subscribe(new Observer<Patient>() {
                    @Override
                    public void onSubscribe(Disposable d) {

                    }

                    @Override
                    public void onNext(Patient patient) {

                    }

                    @Override
                    public void onError(Throwable e) {

                    }

                    @Override
                    public void onComplete() {

                    }
                });
```
Cached data is available locally，phones don't have Internet，The above code Inject Activity#onCreat call

Expect to get the cache fill UI and prompt the user for error information

but，no get the cache fill UI,Just prompt for error.

why? How to solve?

**Comment by akarnokd** [comment]
Please ask such questions on StackOverflow, especially regarding Android usages.

**Comment by XiFanYin** [comment]
@akarnokd  You're sure it's not a library bug?
