### ISSUE TITLE
2.x : Licensing issue with reactive-stream dependency

### ISSUE THREAD

**Issue by kdani41** [ReactiveX/RxJava#6209]
## Question
While migrating from rxjava **1** -> **2**. There was a change in dependency list of rxjava which is 
RxJava 2 has a transitive dependency on [reactive streams](https://mvnrepository.com/artifact/org.reactivestreams/reactive-streams/1.0.2)

Reactive Streams dependency has a license of [CC0](https://creativecommons.org/publicdomain/zero/1.0/)

**Issue** - Due to some reason the place where I work have some legal issue with the license. 

> Main concern regarding the license is that patent rights are expressly reserved. The license is only for copyright which eventually creates a risk of an IP claim.

Is there any alternative workaround for this dependency?? Or any way if reactive-streams can be offered under Apache-2.0 license??

**Comment by JakeWharton** [comment]
If you don't need backpressure you can just skip using Flowable which is the only type that uses it. I've never used Flowable with a ton of Rx usage.

**Comment by davidmoten** [comment]
>Main concern regarding the license is that patent rights are expressly reserved. The license is only for copyright which eventually creates a risk of an IP claim.

I just looked at your CCO [link](https://creativecommons.org/publicdomain/zero/1.0/) and I see this:

>The person who associated a work with this deed has dedicated the work to the public domain by waiving all of his or her rights to the work worldwide under copyright law, including all related and neighboring rights, to the extent allowed by law.

and from creativecommons.org [wiki](https://wiki.creativecommons.org/wiki/CC0_FAQ#What_about_other_IP_related_rights.2C_such_as_trademark_and_patent_rights.3F):

>What about other IP related rights, such as trademark and patent rights?
CC0 very clearly states that trademark and patent rights of the affirmer are not affected – CC0’s sole reach is copyright and related and neighboring rights, including database rights. Trademarks rights are not affected because creators who use CC0 should be able to protect the quality of products that are associated with their trademark (for example, by preventing a subsequent user of the work from leading others to believe the work in its subsequent use and/or form is associated with or endorsed by the affirmer). So if your primary concern is to ensure the quality and integrity of products associated with your name or your project, then trademark, combined with CC0, may be an option for you.

>Patents are fundamentally more challenging. One of our goals at Creative Commons is to encourage use and dissemination of information in a way that encourages others to build upon it, sometimes in surprising and unexpected ways. We can accomplish that objective through a copyright-only solution, without introducing the complexities associated with patent rights. We also wanted to keep CC0 as simple as possible, consistent with its original design goals. We concluded that any perceived benefits of including a patent waiver were significantly outweighed by the downsides of its inclusion.

Would be nice if licence was Apache Commons 2.0. Perhaps raise this on [reactive-streams-jvm](https://github.com/reactive-streams/reactive-streams-jvm)?

**Comment by kdani41** [comment]
> If you don't need backpressure you can just skip using Flowable which is the only type that uses it. I've never used Flowable with a ton of Rx usage.

Since **rxjava 1** is not in active development support any issue happens in it won't get resolved easily. That's why we were planning to upgrade to **rxjava 2** but then we're stuck because of this transitive dependency issue.

@JakeWharton @davidmoten 
- Having said that is there any risk involved if I run **rxjava2** excluding group `org.reactivestreams` dependency if I plan not to use any **Flowable**?? 
```gradle
implementation ("io.reactivex.rxjava2:rxjava:2.x.y") {
    exclude group "org.reactivestreams"
}
```

**Comment by kdani41** [comment]
@davidmoten  👍Thanks a lot for this info. I'll try to follow up on this.

**Comment by davidmoten** [comment]
@kdani41 raised issue https://github.com/reactive-streams/reactive-streams-jvm/issues/438

**Comment by akarnokd** [comment]
Another alternative would be to move to Java 9 and its Flow API in order to get back to zero dependency in RxJava. This might be done in a fork and find-replace `org.reactivestreams` with `java.util.concurrent.Flow` as well as use the bridge in the TCK tests.

**Comment by kdani41** [comment]
> Another alternative would be to move to Java 9 and its Flow API in order to get back to zero dependency in RxJava. This might be done in a fork and find-replace `org.reactivestreams` with `java.util.concurrent.Flow` as well as use the bridge in the TCK tests.

Thanks for replying. I'm planning to use this for an Android project which is supporting api>14. So this option won't be valid for me.

## Other alternative
Since I don't plan to use **Flowable** I tried running rxjava2 excluding group `org.reactivestreams` dependency. 
```groovy

android {
    ...
    packagingOptions {
        exclude 'META-INF/rxjava.properties'
    }
}

implementation ("io.reactivex.rxjava2:rxjava:2.x.y") {
    exclude group "org.reactivestreams"
}

```
build works fine but still not completely sure if there's any other potential risk involved with this approach. Except using flowable would there be any other potential risk??

**Comment by akarnokd** [comment]
I'm closing this as it should be resolved either in Reactive Streams or is likely a non-issue.
