### ISSUE TITLE
Issue about concatMapDelayError

### ISSUE THREAD

**Issue by Fozei** [ReactiveX/RxJava#6210]
I found this by accidentally.
By my understanding, of cause, may be wrong, the concatMapDelayError operator will continue the sequence even error occur. The operator works well while no thread switching. But once you point observeOn, it will miss emitters, some circumstances, only error can be observed.
I am using rxjava:2.1.5, and it is the same on rxjava:2.1.0
## The works well code:
```
final List<Integer> list = new ArrayList<>();
        for (int i = 0; i < 5; i++) {
            list.add(i);
        }
        ResourceSubscriber<Integer> resourceSubscriber = Flowable
                .fromIterable(list)
                .concatMapDelayError(new Function<Integer, Flowable<Integer>>() {
                    @Override
                    public Flowable<Integer> apply(Integer integer) throws Exception {
                        if (integer == 0) {
                            return Flowable.error(new Throwable("ERROR"));
                        }
                        return Flowable.just(integer);
                    }
                })
//                .subscribeOn(Schedulers.io())
//                .observeOn(AndroidSchedulers.mainThread())
                .subscribeWith(new ResourceSubscriber<Integer>() {
                    @Override
                    public void onNext(Integer integer) {
                        Log.i("yff", "BaseActivity.onNext: " + integer);
                    }

                    @Override
                    public void onError(Throwable t) {
                        Log.i("yff", "BaseActivity.onError: " + t.getMessage());
                    }

                    @Override
                    public void onComplete() {

                    }
                });
```
It gives the log as below
```
I/yff: BaseActivity.onNext: 1
I/yff: BaseActivity.onNext: 2
I/yff: BaseActivity.onNext: 3
I/yff: BaseActivity.onNext: 4
I/yff: BaseActivity.onError: ERROR
```
## The issue code: juse open the comment
It gives the log as below:
```
BaseActivity.onError: ERROR
```
When you compose the subscirbeOn and observeOn as .subscribeOn(Schedulers.io()) and .observeOn(Schedulers.computation()), the log will be like 
```
09-13 14:06:43.150 13146-13168/? I/yff: BaseActivity.onNext: 1
09-13 14:06:43.152 13146-13168/? I/yff: BaseActivity.onNext: 2
09-13 14:06:43.154 13146-13168/? I/yff: BaseActivity.onError: ERROR
```

**Comment by akarnokd** [comment]
The [JavaDocs](http://reactivex.io/RxJava/2.x/javadoc/io/reactivex/Flowable.html#observeOn-io.reactivex.Scheduler-) of `observeOn` has the relevant clause:

> Note that onError notifications will cut ahead of onNext notifications on the emission thread if Scheduler is truly asynchronous. If strict event ordering is required, consider using the observeOn(Scheduler, boolean) overload.

**Comment by Fozei** [comment]
Excellent! 
Thanks for your quick reply ! I tried it with <code>concatMapDelayError</code> + <code>observeOn(AndroidSchedulers.mainThread(),true)</code>, and now it works well !
As mentioned in JavaDocs,  observeOn Modifies a Publisher to perform its emissions and notifications on a specified Scheduler,asynchronously with a bounded buffer and optionally delays onError notifications, but when I tried with <code>concatMap</code> + <code>observeOn(AndroidSchedulers.mainThread(),true)</code>, it cuts ahead of onNext, but did not delay error, a little bit of confusing, anyhow, there is not problem with <code>concatMapDelayError</code> + <code>observeOn(AndroidSchedulers.mainThread(),true)</code>, Thanks Again !
