### ISSUE TITLE
[1.2.x] [Question] How to create taskgraph of rx.Single / rx.Observable?

### ISSUE THREAD

**Issue by sridivakar** [ReactiveX/RxJava#6218]
Thanks for using RxJava but before you post an issue, please consider the following points:

  - [x] Version : 1.2.7

  - [x] Not a bug, but a question.

  - [x] Posted in Stackoverflow : https://stackoverflow.com/questions/52386289/how-to-create-taskgraph-of-rx-single-rx-observable. It will be of great help, if any of you responds there.

**Comment by akarnokd** [comment]
> Please avoid cross-posting questions on StackOverflow, this issue list, the Gitter room or the mailing list.

You forgot to tick this point above!
