### ISSUE TITLE
Inner flatMapCompletable doesn't call following chain. [2.x][Documentation]

### ISSUE THREAD

**Issue by EningApps** [ReactiveX/RxJava#6221]
I've faced to some strange behavior of flatMapCompletablefunction. In the code snippet below I have multiple inner flatMapCompletable. Line marked with * doesn't call code in andThan. Although any other compellable in this code successfully executes andThan.

I suggested that my inner Completable.complete() doesn't call desired subscriber's Complete so I tried to play around braces, but nothing helps.

Thanks for the answer in advance!

**Comment by akarnokd** [comment]
You've asked this question on [StackOverflow](https://stackoverflow.com/questions/52456617/rxjava-2-inner-flatmapcompletable-doesnt-call-subscribers-following-chain) already. We asked you not to cross-post questions.
