### ISSUE TITLE
How to make chain atomic?

### ISSUE THREAD

**Issue by ursusursus** [ReactiveX/RxJava#6228]
Hi,
Id like advice on idiomatic way of doing this. 

Say I have a async senquence of operations, for example logout = request + clear user token + clear all local data.

request()
.flatmap { clearUserData() }
.flatmap { clearAllData() }
.subscribeOn(io)

My issue is if I model this via flatmaps, then stream is cancelable also mid way. That means disposable can be disposed of when the stream is at the "clear user data" observable, meaning "clear all data" will not get executed, which is a problem.

By atomicity I dont mean being rollback but atleast guaranteeing it will run whole, i.e. not being able to cancel.

Honestly the cleanest would be to leave is synchronous via Completable.fromAction { requestSync() clearUserDataSync().
clearAllDataSync() },

However lets say those calls are part of public api so pretend they cant be changed.

Is blockingGet() instead good idea? 

Completable.fromAction {
   request().blockingGet()
   clearUserData().blockingGet()
   clearAllData().blockingGet()
}

How about making the flatmapped stream hot via publish().autoconnect()? That should ignore the cancels when subscriber goes away right?

Btw if you like the publish approach. Is then a way to make it cold again? I.e. guaranteeing those 3 operations will finish but then fourth wont run, if stream was disposed at the time of 2nd operation forexample

**Comment by akarnokd** [comment]
Is there a case where the flow should be disposed? If you always want it to go through, don't dispose the subscription to it.

**Comment by ursusursus** [comment]
When for example caller has a lifecycle, and needs to dispose to free to subsricber reference so it doesnt leak

**Comment by akarnokd** [comment]
I'm not sure what you want to do. Do you want the operations to always execute or do you want the sequence to be stoppable? If you want to prevent cancellation for the duration of some set of operators, that requires a custom operator (i.e., you need to intercept the dispose call and delay it until dispose is enabled again).

**Comment by ursusursus** [comment]
Yes to the latter, id like for certain part of the chain to be basically unstoppable explicitly.

guaranteed {
   fooObservsble()
      .flatmap { barObservable() }
      .flatmap { quaxObservable() }
}
...
.whatever()
...
.subscribe()

So part of chain in guaranteed is uncancelable once running, but downstream from it is, so subscriber doesnt leak (so yea subscriber is no longer there and guaranteed chain continues until its completion)

**Comment by akarnokd** [comment]
What would be the start and end of such non-disposable region? I.e., the first item in and the terminal signal out or would it be in a form of an API (i.e., beginNonDisposable(), endNonDisposable())? 

Also even if a region is non disposable, should the upstream to that region be disposable? For example, you have a source that keeps emitting the input to the non-disposable region. You want to prevent disposing while the current item is processed but you'd still want to stop the generation of those original items.

**Comment by ursusursus** [comment]
Yes I like first in and terminal out. I.e. if it started running, block dispose until onComplete. So the second question is now the same I think: If it was not running at the time of disposal or already completed, dispose works as usual, upstream disposed also. 

Now that I think about it, its precisely like executor shutdown, refuse new stuff and let running stuff finish and only then really finish self

**Comment by akarnokd** [comment]
But that would make only a small window between subscription and the first item so that the flow could be stopped. You can do that via `takeUntil(PublishSubject)` before the non-disposable region and simply not dispose the subscription at the end. If you wanted the source to be stopped, signal an item to that `PublishSubject` that will eventually make the sequence stop.

**Comment by ursusursus** [comment]
right, but wouldnt that leak the subscriber? Simpler but possibly stupid example is making a request in the UI. After request you save the data to database. In this case you dont want to cancel the request when ui goes away (back press)

```
class UI  {
   fun click() {
      disposable = fooRequestSingle()
         .flatmap { databaseSaveSingle(it) }
         .subscribe {
            viewShowToast()
         }
   }

   fun onDestroy() {
      disposable.dispose()
   }
}
```

Here Id always want to save the data, but showing toast is not necessary when UI went away.
I know the better alternative is to not make request in ui but delegate to some singletone, but for sake of argument..

**Comment by akarnokd** [comment]
You can also separate out the non-disposable part into its own sequence and communicate with it via subjects:

```java
Subject<T> input = PublishSubject.create();
Subject<R> output = PublishSubject.create();

// the non-disposable sequence of transformations
input
  .flatMap(v -> operation1())
  .flatMap(w -> operation2())
  .subscribe(output);

// prepare handling the output of the non-disposable part
Disposable d1 = output
  .observeOn()
  .doOnNext()
  .subscribe();

// connect the main source of values to be processed non-disposable
Disposable d2 = mainSource.subscribe(input);

// stop generating and stop listening to items
// the non-disposable sequence will not be affected
d1.dispose();
d2.dispose();
```

**Comment by ursusursus** [comment]
Looks good, is there any chance I could compact this into single extension function? Probably not since I need the references to subjects in order to input values. Operator possibly?

Btw, isnt the 
// the non-disposable sequence of transformations
```
input
  .flatMap(v -> operation1())
  .flatMap(w -> operation2())
  .subscribe(output);
```
leaking `this` in the flatmap lambdas if its not disposed? Or is it smart enough to not have this if its not capturing lambda?

**Comment by akarnokd** [comment]
You can have a transformer:

```java
ObservableTransformer<T, R> nonDisposableWork = upstream -> Observable.defer(() -> {

  Subject<T> input = PublishSubject.create();
  Subject<R> output = PublishSubject.create();

  input
  .flatMap(v -> operation1())
  .flatMap(w -> operation2())
  .subscribe(output);

  Disposable d = upstream.subscribe(input);

  return output.doFinally(() -> d.dispose());
});

someSource.compose(nonDisposableWork)
.observeOn()
.doOnNext()
.subscribe();
```

> leaking this in the flatmap lambdas if its not disposed?

Afaik, Android lambda compilers should be smart enough to not capture `this` unnecessarily. If you put the transformer into a static method and only have static methods inside the lambda, there should be no `this` captured.

**Comment by akarnokd** [comment]
Looks like this question has been answered. If you have further input on the issue, don't hesitate to reopen this issue or post a new one.
