### ISSUE TITLE
SchedulerPoolFactory.java null pointer

### ISSUE THREAD

**Issue by Xenios91** [ReactiveX/RxJava#6229]
Location: RxJava/src/main/java/io/reactivex/internal/schedulers/SchedulerPoolFactory.java
Class: SchedulerPoolFactory.java
Line: 69
Statement: if (PURGE_THREAD.compareAndSet(curr, next)) 
Problem: Above this line, it checks if curr is NOT null, and if it is not null, it returns. If it does equal null, it will continue to this line where it passes curr. This can result in a null pointer exception.

**Comment by akarnokd** [comment]
No. The line tries to set `PURGE_THREAD` to the `next` value atomically if the its current value is still `null`. If successful, the purge task is started and the loop quits. If unsuccessful, the helper pool just created is shut down and the loop repeats. There is no circumstance there could be a `NullPointerException` in this method.
