### ISSUE TITLE
2.2.0 - Question - Flowable.GroupBy Memory Usage

### ISSUE THREAD

**Issue by ghost** [ReactiveX/RxJava#6233]
I have some questions about the groupBy operator and its memory usage.

1. Does Flowable.groupBy begin to emit GroupedFlowables as the groupBy keys are encountered or are they held back until the full set of groupBy keys can be identified?  How much buffering of source emissions does Flowable.groupBy do?  Or is it more like a situation where Flowable.groupBy publishes to the GroupedFlowable for a corresponding groupBy key as it's encountered?
2. If I have a very long source Flowable (millions of emissions) which emits its items in sorted order of the value I want to use as a groupBy key, should I be concerned about memory issues (OutOfMemoryError, etc.) with using Flowable.groupBy()?

**Comment by akarnokd** [comment]
> Does Flowable.groupBy begin to emit GroupedFlowables as the groupBy keys are encountered

Yes.

> How much buffering of source emissions does Flowable.groupBy

None.

> Flowable.groupBy publishes to the GroupedFlowable for a corresponding groupBy key as it's encountered?

Yes.

> If I have a very long source Flowable (millions of emissions) which emits its items in sorted order of the value I want to use as a groupBy key, should I be concerned about memory issues (OutOfMemoryError, etc.) with using Flowable.groupBy()?

Yes, groups live until they are individually no longer observed or when the source terminates.

**Comment by ghost** [comment]
Thanks so much for the response, I really appreciate it.  I have some follow up questions if you'd be so kind, then I will close the issue.
> Yes, groups live until they are individually no longer observed or when the source terminates.

When does a GroupedFlowable signal completion?  Only when the source terminates?  In the scenario I described where the source emissions come in the order of the groupBy key, what would happen if I applied a .take(n) operator to inner GroupedFlowables specifying an upper bound?  Would the GroupedFlowables be disposed in that case and then recreated if/when the groupBy key is seen again, or are they still kept alive?

Thanks again

**Comment by akarnokd** [comment]
> When does a GroupedFlowable signal completion? Only when the source terminates?

Yes.

> what would happen if I applied a .take(n) operator to inner GroupedFlowables specifying an upper bound?

Assuming you have strictly ordered keys, a take would end a group, freeing the associated resources and the operator would not create another one.

> Would the GroupedFlowables be disposed in that case and then recreated if/when the groupBy key is seen again

Yes.

**Comment by ghost** [comment]
Perfect, thank you.
