### ISSUE TITLE
Proguard issues

### ISSUE THREAD

**Issue by keithle888** [ReactiveX/RxJava#6237]
Hello, I am heavily using RxJava 2 for an Android library and proguard works when publishing a released version but when building an APK, these issues arise. Any advice would be appreciated.
(No proguard config for RxJava.)

````
Warning: x.x.x.x.x$method$2$1: can't find enclosing method 'io.reactivex.Single apply(retrofit2.Response)' in program class x.x.x.x.x$method$2
````
The chunk of code:
````
fun method(enable: Boolean): Completable {
        return retrofitClass.methodReturningASingle(enable)
                .flatMap {result ->
                   result.someWork.returnsAnotherSingle()
                }
                .flatMapCompletable {
                    returnsSomeCompletable()
                }.onErrorResumeNext { remapError() }
    }
````

Another warning I am getting is:
````
Warning: x.x.x.x.x$anotherMethod$1$1: can't find enclosing method 'io.reactivex.Single 
````

**Comment by artem-zinnatullin** [comment]
This doesn't seem to be an issue of proguarding RxJava, but rather Retrofit (maybe).

RxJava 2.x doesn't require proguard rules.

Check [Retrofit proguard rules](https://github.com/square/retrofit/blob/eb441ed140a124a9f152f82ad05993d502848d9a/retrofit/src/main/resources/META-INF/proguard/retrofit2.pro) (note that I've linked to a particular commit, make sure to check later version if you're reading this in far future)

**Comment by keithle888** [comment]
Thanks for the prompt reply! I did forget to include the retrofit proguard. Will update with results.

**Comment by artem-zinnatullin** [comment]
@keithle888 how did it go?

**Comment by keithle888** [comment]
@artem-zinnatullin Great! I added in the OkHttp3 rules but forgot to add in the retrofit rules. Thanks alot for the prompt response! I'll close this issue.
