### ISSUE TITLE
What's-different docs reference non-existent class: io.reactivex.functions.Functions

### ISSUE THREAD

**Issue by dpkirchner** [ReactiveX/RxJava#6239]
The documentation below references a utility class, `io.reactivex.functions.Functions`, but it appears that is now `io.reactivex.internal.functions.Functions`, which I assume should not be used by third parties. Is there a public equivalent?

https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0#functions

**Comment by akarnokd** [comment]
That's a mistake in the docs and we don't offer any public utilities for them.  If you need something from the internal `Functions`, they can be trivially recreated outside RxJava.
