### ISSUE TITLE
2.0: Operator for specifying used scheduler for all operators downstream

### ISSUE THREAD

**Issue by PawlikMichal25** [ReactiveX/RxJava#6240]
**Question/Enhancement**

Why there is no operator that would enable specifying scheduler used by all operators downstream?
With assumption that `scheduleOn` and `observeOn` would still keep working as they were so far.
 
**Problem/Background**
Recently I learned that there isn't really a concise, reliable way to specify on which scheduler actions from operators like eg. `doOnDispose` or `doOnSubscribe` will be executed. 
Furthermore, position of these operators in chain influences scheduler used by them, which seems logical, but how it's determined is rather unclear - at least from perspective of API. 

Esentially I would like to be able to write code like:
```
repository.getProducts()
    ...
    .subscribeOn(schedulers.io)
    ...
    .observeOn(schedulers.main)
    ...
    .doOnSubscribe {
        products.value = Resource.loading(emptyList())
    }.subscribe({
        products.value = Resource.success(it)
    }, {
        products.value = Resource.error(it.message)
    })
```
and feel safe that `doOnSubscribe` will be executed on main thread.

**Comment by akarnokd** [comment]
> Why there is no operator that would enable specifying scheduler used by all operators downstream?

Because it is not possible. Operators can't have such reach.

> which scheduler actions from operators like eg. doOnDispose

`unsubscribeOn` affects where the `dispose()` call of its upstream will be called.

> doOnSubscribe

There is no direct support for moving `doOnSubscribe` onto another thread but you can side-effect a different a preceding sequence.

```java
source
.startWith(
    Completable.fromAction(() -> { /* your onSubscribe */ })
    .subscribeOn(mainThread())
    .toObservable()
)
.subscribe(/* ... */);
```

With Kotlin, you can even create an extension method for the `startWith` part.

**Comment by PawlikMichal25** [comment]
Thanks for clarifying, just one more question then:

> Because it is not possible. Operators can't have such reach.

so the fact that sometimes eg. action from `doOnSubscribe` is executed on different schedulers  should be considered as a "side effect"?

**Comment by akarnokd** [comment]
The `doOnXXX` operators allow you to insert side effect at various points into a flow. They are not predicated on schedulers.

**Comment by PawlikMichal25** [comment]
Ok, thanks for responding, 
I will close the issue now
