### ISSUE TITLE
Why does delay() with function require ObservableSource, not SingleSource.

### ISSUE THREAD

**Issue by tir38** [ReactiveX/RxJava#6248]
I'm Using this `delay()` operator:

```
public final <U> Observable<T> delay(final Function<? super T, ? extends ObservableSource<U>> itemDelay) {
```

Why does this function return an `ObservableSource` instead of a `SingleSource`?

If I understand correctly these two streams are the same (i.e. emitting two items in `itemDelay` does the same thing as emitting one item):

    Observable.just("a", "b", "c")
            .delay(string -> {
                if (shouldDelay()) {
                    Thread.sleep(1000);
                    return Observable.just(1);
                } else {
                    // don't delay, return immediately
                    return Observable.just(1);
                }
    
            });

    Observable.just("a", "b", "c")
            .delay(string -> {
                if (shouldDelay()) {
                    Thread.sleep(1000);
                    return Observable.just(1, 2);
                } else {
                    // don't delay, return immediately
                    return Observable.just(1, 2);
                }
    
            });

So why not just require a `SingleSource`? 

_I realize this is a general "why did this get built this way?" question. I don't expect the API to change._

**Comment by akarnokd** [comment]
The signature of `delay` was established way before `Single` has been added to the library. Besides, the inner `ObservableSource` is expected to signal an item or completion in order for `delay` to signal the associated item. Consequently, you don't have to define that inner flow in a way to always produce an item.

**Comment by tir38** [comment]
thanks. What do you mean "you don't have to define that inner flow in a way to always produce an item."?

**Comment by akarnokd** [comment]
It means you don't have to add more transformations and defaults just to have an item emitted.
