### ISSUE TITLE
Proposal: Make NonBlockingThread public

### ISSUE THREAD

**Issue by ZacSweers** [ReactiveX/RxJava#6261]
The `NonBlockingThread` plugin control is pretty cool, but becomes unusable when using a custom `ThreadFactory` since it's internal. Would you be open to making this interface public so that custom provided threads could indicate that they should not be blocking as well?

**Comment by ZacSweers** [comment]
Alternatively - a plugin hook like `onBlockingOperator` such that we can basically perform our own check. That would allow for failing on threads we maybe don't control, such as the main thread on Android

**Comment by akarnokd** [comment]
There is the RxJavaPlugins.setOnBeforeBlocking hook for the case where existing threading can be checked.

**Comment by ZacSweers** [comment]
Ah! I misread the logic here

```java
Thread.currentThread() instanceof NonBlockingThread
                        || RxJavaPlugins.onBeforeBlocking()
```

and thought it was `&&` 🙄 . That covers it then!

**Comment by akarnokd** [comment]
I thought about such scenarios back then because of Android main thread which you don't control type-vise.

**Comment by ZacSweers** [comment]
yep it makes a lot of sense to have. Thanks again
