### ISSUE TITLE
2.x: subscribeOn does not work when Emitter's onNext called on another thread.

### ISSUE THREAD

**Issue by mateuszkwiecinski** [ReactiveX/RxJava#6265]
Let's assume we have following code structure
```
import kotlin.concurrent.thread

val dataLayer = Single.create<Unit>{ emitter ->
    thread(name = "John") {
        emitter.onSuccess(Unit)
    }
}

val domainLayer = dataLayer
    .flatMap {
        someHeavyOperation(it)
    }

val presentationLayer = domainLayer
    .subscribeOn(Schedulers.io())
    .observeOn(AndroidSchedulers.mainThread())
    .subscribe()
```
And the problem is that `someHeavyOperation` is called on the thread called _"John"_ instead of a thread provided by IO scheduler. 
**I expect calling `subscribeOn` would switch back to given thread type even if `SingleOnSubscribe` changes thread underneath.**
If that works as designed is there a possibility to wrap code that is called on other thread that does not affect the rest of created stream? I tried a solution similar to:

```
Single.create<Unit>{ emitter ->
    val countDownLatch = CountDownLatch(1)
    var result : Unit? = null
    thread(name = "John") {
        result = Unit
        countDownLatch.countDown()
    }
    countDownLatch.await()
    emitter.onSuccess(Unit)
}
``` 
but it gets complicated when using `emitter.setCancellable{ }` and I wasn't able to think of similar solution for `Observable` type.

I've seen comments in #941, but I can't to write any thread managing code outside `presentation` layer

**Comment by akarnokd** [comment]
Please, next time ask such questions on StackOverflow.

`subscribeOn` is for moving the subscription side effect to some other thread. Your subscription side-effect in `create` is to start another thread which will then drive the downstream, thus `someHeavyOperation`. `observeOn` should be used to move the success value back to a desired thread, which then will trigger `flatMap`:

```kotlin
import kotlin.concurrent.thread

val dataLayer = Single.create<Unit>{ emitter ->
    thread(name = "John") {
        emitter.onSuccess(Unit)
    }
}

val domainLayer = dataLayer
    .observeOn(Schedulers.io())
    .flatMap {
        someHeavyOperation(it)
    }

val presentationLayer = domainLayer
    .observeOn(AndroidSchedulers.mainThread())
    .subscribe()
```
