### ISSUE TITLE
2.x: firstOrError call on dispose twice

### ISSUE THREAD

**Issue by ibaca** [ReactiveX/RxJava#6268]
In  RxJava (2.2.2) if I use the next code the `onDispose` callback is called twice. I have already changed the code to not use this approach bc the `s.onNext` inside the subscribe is pretty obscure, but I report it just in case this can affect more cases. Looks like firstOrError (actually ObservableElementAtSingle) can call upstream cancelation twice.

Code that produces the problem:
```java
BehaviorSubject<Integer> s = BehaviorSubject.create();
s.doOnLifecycle(d -> out.println("subscribe"), () -> { out.println("dispose"); s.onNext(2); })
        .firstOrError().subscribe().dispose();
```
Console output:
```
subscribe
dispose
dispose
```

**Comment by akarnokd** [comment]
This is kind of an awkward reentrance problem. I'll have to investigate which components need to suppress dispose calls.
