### ISSUE TITLE
Make CompositeDisposable idiot-proof

### ISSUE THREAD

**Issue by tir38** [ReactiveX/RxJava#6274]
Feature request for 3.x.

In 2.x `CompositeDisposable.add()` returns a boolean if add() was successful. It is tedious to check this every time. Especially if it's rarely a problem. I would like a way to change/override this behaviour where it either throws or logs an error instead of just returning false.

**Comment by akarnokd** [comment]
I don't know anybody else who actually checks its return value. It has uses for certain operator types to detect when the composite has been disposed right when `add` was called and lets one not continue with certain logic unnecessarily. Also throwing is a very harsh penalty and would break practically everybody for no benefit.
