### ISSUE TITLE
flattenAsFlowable wrong wording in Javadocs

### ISSUE THREAD

**Issue by akarnokd** [ReactiveX/RxJava#6276]
The wording of `Single.flattenAsFlowable` is a bit off:

> "Returns a Flowable that **merges each item emitted by the source Single with the values in an Iterable corresponding to that item that is generated by a selector.**"

In contrast, `flattenAsObservable` is somewhat better:

> "Returns an Observable that maps a success value into an Iterable and emits its items."

I'd say something along the lines of:

"Maps the success value of the upstream `{@code Single}` into an `{@link Iterable}` and emits its items as an `{@link Observable}` sequence."

The `Maybe` variants have the same issues (they were copy-pasted back then).

**Comment by dilantha111** [comment]
Hi @akarnokd  I would like to start working on this. Could you please give me some heads up ?

**Comment by akarnokd** [comment]
> Could you please give me some heads up ?

Nobody has started working on this yet so go ahead.

**Comment by freakomonk** [comment]
@dilantha111 Have you finished working on this?

**Comment by dilantha111** [comment]
@freakomonk  Nope. Just got some other things coming up. If you are willing to do that, please go ahead. At the moment stuck with some other stuffs.

**Comment by freakomonk** [comment]
@dilantha111 Since I have finished some other issue as my first bug, I don't think its fair for me to take this up too. So leaving it open for others to take it.

**Comment by akarnokd** [comment]
@freakomonk Unfortunately, people are not lining up to work on issues right now so I suggest you do as much as you like and not worry about taking away opportunities.

**Comment by freakomonk** [comment]
@akarnokd Sure David. Will take it up tomorrow.

**Comment by thiyagu-7** [comment]
@akarnokd I would like to work on this

**Comment by akarnokd** [comment]
@thiyagu-7 Sure!
