### ISSUE TITLE
2.x Deadlock with Flowable.groupBy(...) if number of groups exceeds buffer size

### ISSUE THREAD

**Issue by jkarshin** [ReactiveX/RxJava#6284]
RxJava Version: 2.2.1
Java Version: 1.8.0_181

The following test consistently deadlocks on my machine:

```
int bufferSize = 128;

Flowable.range(0, 500)
        .doOnNext(x -> System.out.println("Before groupBy: " + x))
        .groupBy(Functions.identity(), Functions.identity(), false, bufferSize)
        .doOnNext(groupedFlow -> System.out.println("After groupBy: " + groupedFlow.getKey()))
        .flatMap(groupedFlow -> groupedFlow)
        .blockingSubscribe();
```

The output indicates that everything works as expected until the 129th item reaches the groupBy.

```
Before groupBy: 0
After groupBy: 0
Before groupBy: 1
After groupBy: 1
...
Before groupBy: 126
After groupBy: 126
Before groupBy: 127
After groupBy: 127
Before groupBy: 128
Before groupBy: 129
Before groupBy: 130
...
Before groupBy: 382
Before groupBy: 383
// No more logs here
```

Strangely, the `Before groupBy` logs consistently stop at 383 on my machine. Also note that removing the `flatMap(...)` operation causes the entire operation to succeed without deadlock.

Increasing the buffer size will increase the number of `Before groupBy` logs by an equal amount. Thus, with an input size of 500, increasing the buffer size to 244 will cause the test to pass, while increasing the buffer to 243 will cause a deadlock on the last element.

Also strangely, no matter what the buffer size is, the first 128 log statements alternate between "before" and "after", while the rest are a series of "before" logs, followed by "after" logs if the buffer is large enough for the test to pass. (Note that I am not changing the global RxJavaBuffer size property, only the buffer size passed to `groupBy`.)

**Comment by akarnokd** [comment]
The limitation of `Flowable.groupBy` is that you have to consume the `GroupedFlowable` instances it emits to your `flatMap` as well as consume the groups themselves. Otherwise, the sequence hangs as it is unable to request more items from the main source as it may either generate a new group or a new item in an existing group but there may be no room for them. 

The limit in your case is due to `flatMap` with its default concurrency level of 128. You have to parameterize `flatMap`'s `maxConcurrency` so that it is larger than the number of groups you may ever encounter with it.

**Comment by akarnokd** [comment]
PR welcome to update the documentation of all `Flowable.groupBy` to contain a `<p>` section about this property.

**Comment by jkarshin** [comment]
Thanks for the quick reply.

I am somewhat confused regarding this limitation as it pertains to `flatMap()`. I understand why I must consume the `GroupedFlowables`, but I thought that by using `flatMap()`, I am consuming the individual Integers out of the `GroupedFlowable` and combining them back into the main `Flowable`? Inserting a `doOnNext(...)` after the `flatMap()` operation shows that the main `Flowable` contains Integers once more, and not `GroupedFlowable<Integer>`.

Or are you saying I must have an explicit subscription within the `flatMap()` call? In which case, is it possible to combine the elements of the `GroupedFlowable` back to the main `Flowable`?

The actual production code in which I encountered the deadlock has a non-empty `flatMap()` operation; I merely cut it out to minimize the code necessary to reproduce the problem. The full code looks closer to this:

```
int bufferSize = 128;

Flowable.range(0, 500)
        .doOnNext(x -> System.out.println("Before groupBy: " + x))
        .groupBy(Functions.identity(), Functions.identity(), false, bufferSize)
        .doOnNext(groupedFlow -> System.out.println("After groupBy: " + groupedFlow.getKey()))
        .flatMap(groupedFlow -> groupedFlow.observeOn(Schedulers.io())
                .flatMap(x -> Flowable.just(x)
                        .map(this::doSomethingToX)
                        .doOnError(Throwable::printStackTrace)
                        .onErrorResumeNext(Flowable.empty())
                        ) // End of inner flatMap(...)
                ) // End of outer flatMap(...)
        .doOnNext(this::doSomethingElseToX)
        .blockingSubscribe();
```

The above deadlocks in the same way, after successfully processing the first 128 integers.

**Comment by akarnokd** [comment]
You have to subscribe to the `GroupedFlowable` `groupBy` gives you. `flatMap` would subscribe to it for you if you allowed `flatMap` to run more than 128 sources at once.

You have to allow it to run more, even unbounded: `flatMap(yourMapper, Integer.MAX_VALUE)`.

> Inserting a doOnNext(...) after the flatMap() operation shows that the main Flowable contains Integers once more, and not GroupedFlowable<Integer>.

Yes because `flatMap` extracts the items of those groups and gives you a straight sequence of Integers again. It is called flattening.

**Comment by akarnokd** [comment]
Posted #6289 to welcome contribution with a clearer description of the underlying issue..
