### ISSUE TITLE
How to not resubscribe switchMap unnecessarily?

### ISSUE THREAD

**Issue by ursusursus** [ReactiveX/RxJava#6292]
Hi, I am having trouble figuring this one out.

I have a stream of call states, where each call state carries username on it. Username is then queried for Contact object in the database. So basically what I have is a transformation of CallState(username) -> DifferentCallState(contact).

Database queries are observables as they can change. So far I have this, pretty straight forward

 ```kotlin
sipCallManager.callStateObservable
                   .switchMap { callState ->
                       contactRepository.contactByUsernameObservable(callState.username)
                            .map { contact ->
                                DifferentCallState(contact)
                            }
                   }
```

However, most of the time username will by the same, and therefore contactByUsernameObservable being resubscribed for no reason.

How could I optimize this away? I was thinking of mapping the callState to username, distinctUntilChanged to only get changes and then switchmap to contact query, but how can I join this, i.e. preserve the upstream call state, so I still can map FooCallState to FooDifferentCallState?

Maybe somehow with publish that takes observable?

**Comment by akarnokd** [comment]
What if the contact changed for the username? Generally you could introduce a cache (with time-to-live properties) and query/update that:

```java
ConcurrentMap<String, List<Contact>> cache = ...

callStateObservable
.switchMap( callState -> {
    List<Contact> contacts = cache.get(callState.username);
    Observable<Contact> contactObservable;
    if (contacts == null) {
        contactObservable = contactRepository.contactByUsernameObservable(callState.username)
            .toList()
            .doOnSuccess(list -> cache.put(callState.username, list));
            .flattenAsObservable(list -> list);
    } else {
        contactObservable = Obervable.fromIterable(contacts);
    }
    return contactObservable.map(contact -> new DifferentCallState(contact));
});
```

**Comment by ursusursus** [comment]
Hmm its not quite right, Id basically like to cache the contacts observable not the contact objects, since contact observable can emit n times while subscribed, not just once, so fromIterable wont do

**Comment by ursusursus** [comment]
If I were to cache the contacts observable in a variable outside of the stream, i.e. creating it eagerly, then just return this reference inside a switchMap, to avoid retriggering Id need to make it completly hot + replay 1 (no refCount) and then disconnecting it manually in some onDestroy right? (or ofc when username changes, then creating a new one)

**Comment by akarnokd** [comment]
If you have a hot `contactByUsernameObservable`, how should a state change trigger a different call state it the `contactByUsernameObservable` does not change after it produced items the previous time?

**Comment by ursusursus** [comment]
I was thinking replay(1)

```
var cachedContactsObservable

//

.switchMap { callState -> 
    if callState.username same as before
        cachedContactsObservable
    else 
        cachedContactsObservable?.disconnect()
        cachedContactsObservable = coldContactsObservable.replay(1)
}
```

**Comment by akarnokd** [comment]
I can't tell, could work for your specific case.
