### ISSUE TITLE
About observeOn Operator.

### ISSUE THREAD

**Issue by miaoMiaoDaShi** [ReactiveX/RxJava#6294]
Observable.just("mmp")
                .subscribeOn(Schedulers.io())
                .observeOn(AndroidSchedulers.mainThread())

                .doOnNext(new Consumer<String>() {
                    @Override
                    public void accept(String s) throws Exception {
                        Log.i(TAG, "doOnNext0: ");
                    }
                })
                .doOnNext(new Consumer<String>() {
                    @Override
                    public void accept(String s) throws Exception {
                        Log.i(TAG, "doOnNext1: ");
                    }
                })

                .doFinally(new Action() {
                    @Override
                    public void run() throws Exception {
                        Log.i(TAG, "doFinally: ");
                    }
                })
                .doOnNext(new Consumer<String>() {
                    @Override
                    public void accept(String s) throws Exception {
                        Log.i(TAG, "doOnNext2: ");
                    }
                })
                .observeOn(AndroidSchedulers.mainThread())
                .doOnNext(new Consumer<String>() {
                    @Override
                    public void accept(String s) throws Exception {
                        Log.i(TAG, "doOnNext3: ");
                    }
                })

                .subscribe(new Consumer<String>() {
                    @Override
                    public void accept(String s) throws Exception {
                        Log.i(TAG, "onNext: ");
                    }
                });

**log**

 I/MainActivity: doOnNext0: 
 I/MainActivity: doOnNext1: 
 I/MainActivity: doOnNext2: 
 I/MainActivity: doFinally: 
 I/MainActivity: doOnNext3: 
 I/MainActivity: onNext: 

**Why is this?**

**Comment by akarnokd** [comment]
ObserveOn. Code before it runs first, then the code  runs after it a bit later on the main thread.
