### ISSUE TITLE
2.x: Easy way to check if Observable, Single, etc., are subscribed or not in tests

### ISSUE THREAD

**Issue by ryu1-sakai** [ReactiveX/RxJava#6300]
I sometimes want to check if `Observable`, `Single`, etc., are subscribed or not in tests.
And I think it's convenient if RxJava has `TestObservable`, `TestSingle`, etc., which have methods `assertSubscribed()` and `assertNotSubscribed()`.

Don't you have a plan to add such classes/methods to RxJava? Or, is there already an alternative convenient way to achieve the purpose?

Let me give an example of when such verifications are desired.
Suppose that we are implementing `CertainService` like the following.

    public interface Authentication {
        Completable authenticate(long userId);
    }

    public interface Database {
        Single<String> read(long userId);
    }

    public class CertainService {
        private final Authentication authentication;
        private final Database database;

        public CertainService(Authentication authentication, Database database) {
            this.authentication = authentication;
            this.database = database;
        }

        public Single<String> readUserData(long userId) {
            return authentication
                    .authenticate(userId)
                    .andThen(database.read(userId));
        }
    }

We don't want to subscribe `Database.read()` when an authentication fails, in order to avoid an unnecessary database access.
So we want to write a test like the following. The last line confirms that `readDatabase` is not subscribed.

    @Test
    public void testReadUserData_authenticationFailure() {
        // Set up
        Authentication authentication = mock(Authentication.class);
        Database database = mock(Database.class);
        CertainService certainService = new CertainService(authentication, database);

        when(authentication.authenticate(anyLong()))
                .thenReturn(Completable.error(new RuntimeException()));

        TestSingle<String> readDatabase = TestSingle.just("user data");
        when(database.read(anyLong())).thenReturn(readDatabase);

        // Exercise
        TestObserver<String> testObserver = certainService.readUserData(1234).test();

        // Verify
        testObserver.assertError(RuntimeException.class);
        readDatabase.assertNotSubscribed(); // Shouldn't be subscribed!
    }

And here is an example implementation of `TestSingle`.
https://github.com/ReactiveX/RxJava/compare/2.x...ryu1-sakai:test-single

**Comment by akarnokd** [comment]
> Don't you have a plan to add such classes/methods to RxJava?

They are already available. There are two kinds of sources: hot and cold. You can check hot sources if they have consumers via `Subject.hasObservers()` or `FlowableProcessor.hasSubscribers()`.  Cold sources do not track their consumers in general so you have to side-effect the subscription via `doOnSubscribe` to know there was a subscription.

**Comment by ryu1-sakai** [comment]
Thank you, I understood.
Then my example case should be like the following.

    @Test
    public void testReadUserData_authenticationFailure() {
        // Set up
        Authentication authentication = mock(Authentication.class);
        final Database database = mock(Database.class);
        CertainService certainService = new CertainService(authentication, database);

        when(authentication.authenticate(anyLong()))
                .thenReturn(Completable.error(new RuntimeException()));

        AtomicBoolean databaseSubscribed = new AtomicBoolean(false);
        Single<String> readDatabase
                = Single.just("user data").doOnSubscribe(() -> databaseSubscribed.set(true));
        when(database.read(anyLong())).thenReturn(readDatabase);

        // Exercise
        TestObserver<String> testObserver = certainService.readUserData(1234).test();

        // Verify
        testObserver.assertError(RuntimeException.class);
        assertFalse(databaseSubscribed.get());
    }
