### ISSUE TITLE
Javadoc: Flowable::zipWith image is displayed incorrectly

### ISSUE THREAD

**Issue by lorenzpahl** [ReactiveX/RxJava#6302]
There is a small problem with the images in the current Javadoc (2.2.3) of the following operators:

- [`Flowable::zipWith(Publisher, BiFunction)`](http://reactivex.io/RxJava/2.x/javadoc/io/reactivex/Flowable.html#zipWith-org.reactivestreams.Publisher-io.reactivex.functions.BiFunction-)
- [`Flowable::zipWith(Publisher, BiFunction, boolean)`](http://reactivex.io/RxJava/2.x/javadoc/io/reactivex/Flowable.html#zipWith-org.reactivestreams.Publisher-io.reactivex.functions.BiFunction-boolean-)
- [`Flowable::zipWith(Publisher, BiFunction, boolean, int)`](http://reactivex.io/RxJava/2.x/javadoc/io/reactivex/Flowable.html#zipWith-org.reactivestreams.Publisher-io.reactivex.functions.BiFunction-boolean-int-)

If the Javadoc is viewed on a wide screen, the images are displayed on the right side instead of the left. I have a screenshot attached where the problem can be seen.

The problem can be resolved by adding `<p>` before the image element.

![screenshot_2018-11-11 flowable rxjava javadoc 2 2 3](https://user-images.githubusercontent.com/12369767/48316512-ec073680-e5e4-11e8-8d20-566b63d32a3e.png)

**Comment by akarnokd** [comment]
PR welcome
