### ISSUE TITLE
Lack of NonNull anotations in factory methods

### ISSUE THREAD

**Issue by MikolajKakol** [ReactiveX/RxJava#6309]
I was wondering if there shouldn't be an `@javax.annotation.Nonnull` it methods like:
`Single.just`
`Observable.just`
`Observable.fromX`
etc?

It would improve code quality on client side, since IDE might help detect early and compiler would print warning.

**Comment by akarnokd** [comment]
JSR 305 where that annotation lives is incompatible with Java 9 modules so we use our own annotations. Most ide will let you define RxJava's annotations as custom nullability annotations or are supported out of box.

PR welcome.

**Comment by MikolajKakol** [comment]
True, there are RxJava custom annotations and I see that most value for clients rely in `io.reactivex.functions` package. In order to make great improvements we should change 
`    R apply(@NonNull T t) throws Exception;`
to 
`    @NonNull R apply(@NonNull T t) throws Exception;`

Do you think that this is allowed?

**Comment by akarnokd** [comment]
The `functions` are a special case because some usages could work with nulls and they just create warnings. This has been discussed before:

https://github.com/ReactiveX/RxJava/issues?utf8=%E2%9C%93&q=is%3Aissue+nullable+is%3Aclosed+annotation

**Comment by freakomonk** [comment]
Hi. Can I take this up?

**Comment by akarnokd** [comment]
@freakomonk Fine by me. Nobody else seems to be working on this at the moment.

**Comment by freakomonk** [comment]
Sure @akarnokd . Any pointers to know before I start this up?

**Comment by akarnokd** [comment]
Beyond this issue, nothing specifically. We'll review the PR anyway and give you feedback if something needs changing.
