### ISSUE TITLE
add @NonNull annotation at generic type

### ISSUE THREAD

**Issue by JSpiner** [ReactiveX/RxJava#6316]
New feature suggestion.

How about adding `@NonNull` to the generic argument?
Since rxjava2,
it is impossible to emit `null`.
Therefore, there is no null in upstream and downstream.
It may be added except in the case of `ReplySubject::getValue`.

**Comment by ZacSweers** [comment]
This requires RxJava be built against java 8. That said, with Android Gradle Plugin 3.2 bringing in D8 and its desugaring, the android library community is moving toward Java 8 now. Maybe that can be considered here too

**Comment by akarnokd** [comment]
RxJava is set to support Android 2.3+ through Java 6. Would such old runtimes still work?

**Comment by ZacSweers** [comment]
With the D8 tool, these would be stripped at runtime and just be present for static analysis tools

**Comment by JSpiner** [comment]
However, `@NonNull` can be added separately from the java8 issue.
Can I take it?

**Comment by ZacSweers** [comment]
It cannot, Type Annotations are a Java 8 language feature. Also, in general, much more of a fan of assuming nonnull is the default and only indicating nullable types with `@Nullable`

**Comment by yzhong52** [comment]
To add to this, when using rxJava2 in Kotlin, we will get this warning: 

> "Declaration has type inferred from a platform call, which can lead to unchecked nullability issues. Specify type explicitly as nullable or non-nullable."

since it is missing the `null` vs `non-null` annotation, which is a bit annoying to work with.
