### ISSUE TITLE
Proposal: Incorporate Error-Prone

### ISSUE THREAD

**Issue by ZacSweers** [ReactiveX/RxJava#6318]
[Error-Prone](https://github.com/google/error-prone) is a static analysis tool from Google that runs a wealth of checks during compilation, and (in my opinion) is a no brainer for most standard Java projects today. 

it also supports custom checkers for internal or community checkers. One such community checks that would be useful here could be Uber's [NullAway](https://github.com/uber/nullaway), giving basically compile-time nullability checking in the project. Most things under the src/test `validators` package could also be moved to custom error-prone checks that run during compile-time rather than tests, for faster turnaround and also eliminate the need for some annotations to be `RUNTIME` retained.

Integration is fairly simple in Gradle. If this proposal sounds acceptable, I could start with a basic error-prone integration, and then followups to potentially include other checkers or migrate existing validators could happen after.

**Comment by akarnokd** [comment]
I have some concerns:
- How many false positives will be there due to the non-conventional atomics?
- Who is going to battle with them?
- How longer will the compilation take?
- Is there a risk of OOMKiller due to increased memory required on CI?

My suggestion is to not include it into RxJava, but you are free to run it locally and if it really detects a flaw, post a PR specifically fixing that.

**Comment by ZacSweers** [comment]
Error-Prone runs as either a custom compiler or as a compiler plugin, both are extremely fast and low overhead. NullAway is by far the most resource intensive checker we use inside of uber (among a few dozen other checkers + the built-in ones), and it adds somewhere in the realm of 5-8% to compilation overhead. For vanilla error-prone, we found the build times overhead to be negligible. We similarly don't see any noticeable memory increases. I can do some measurements on RxJava to report concrete numbers for here. @JakeWharton set this up in the AndroidX monorepo as well and I know that they only run them on CI, so maybe he could share some insights from their end?

For the non-conventional atomics - unclear, can find out! We can also disable individual checks as needed, or limit them to certain scopes in some cases.

**Comment by artem-zinnatullin** [comment]
>extremely fast and low overhead.

Well, that's debatable :)

>and it adds somewhere in the realm of 5-8% to compilation overhead

That's definitely not true, it's around 70% overhead in compile time, however it is still within tens of seconds for RxJava depending on hardware (+ Gradle integration is incremental)

See https://github.com/google/error-prone/issues/994 for details including benchmarks and discussion (RxJava was the test project I used for benchmarks, should be very relatable)

---

To add to concerns:

- If used as compiler — it'll be javac from OpenJDK 9 ([atm](https://github.com/google/error-prone/blob/v2.3.2/pom.xml#L37)), while right now RxJava release builds are built with Oracle JDK 8
- If used as compiler plugin, for proper integration it requires JDK 9+
- In long term, ErrorProne might be replaced by ~~Android~~ Lint, but we're talking years here

---

Despite that I gave pretty negative comment, I'm not against it, there is for sure value in it and Nullaway is extremely helpful in Java codebases.

**Comment by vanniktech** [comment]
I'm also in favor of adding Error prone with NullAway.

**Comment by ZacSweers** [comment]
I've got a working branch of this here: https://github.com/hzsweers/RxJava/tree/z/errorProneIntegration

And a sample gist of output here: https://gist.github.com/hzsweers/41ed9db9ebe473c72b49bc4b3b2231df

Unfortunately, there is a lot of things reported. Checks would probably need to be enabled one at a time to migrate progressively, and some suppressed due to either requiring API changes to fix or because it's intended "I know what I'm doing" behavior.

Another caveat - requires updating gradle (plus a couple of plugins along the way). It seems to work fine, but not sure if it was kept arbitrarily low before. This also revealed that targeting java 6 is deprecated and scheduled for removal (relates to https://github.com/ReactiveX/RxJava/issues/6317#issuecomment-440949408)

**Comment by ZacSweers** [comment]
And here's a much more thorough output with -Werror count raised to max 1000: https://travis-ci.org/hzsweers/RxJava/builds/458303615

**Comment by akarnokd** [comment]
The key line here: `Task :compileJava FAILED`

The drawback of such tools I find is that they complain endlessly and you spend days and days to suppress and/or have clumsy workarounds to satisfy them. 

RxJava works, compiles and passes its tests right now and there is no reason to worry about null dereferences or other presumed errors.

**Comment by ZacSweers** [comment]
I'm not sure I follow - is the stance here that its discovery of existing issues means it shouldn't be used?

**Comment by akarnokd** [comment]
I read the 100 issues and some of the 1000. Most of them complains about a null argument or uninitialized field in the constructor. Many complain about raw types even though those have suppress annotations there. Certain fields' get values as part of the lifecycle so them being null at some point is not an error. They were false positives but to know that, you'd have *someone* with deep knowledge to go over the thousands of reports and confirm them individually.

**Comment by ZacSweers** [comment]
For the raw types - we could also just disable that one for now.

For the nullability bits - that's actually easy to denote via `@Initializer` annotation.

For the someone with deep knowledge to go over reports - I suppose there's only one of you :), but some of these things are low hanging fruit that could be handled by anyone as well right?

**Comment by akarnokd** [comment]
Again, to satisfy this tool, you'd have to fill up the source code with suppressions, workarounds, mangled structures, etc. I accepted the nullability annotations in the public parts because that's useful for the consumer of the library. However, messing up the internal parts to suppress false positives which wouldn't even be there without the tool is wasteful. Remember, the reviewers have to go through all the changed locations anyway and wonder, "which rule required this change and why exactly?"

If you can filter out the noise and truly find an actual mistake, post a PR fixing that specifically without introducing the whole infrastructure. Hence I suggested using the tool only in your own local environment.

**Comment by ZacSweers** [comment]
Understood
