### ISSUE TITLE
"Problem Solving Examples in RxJava" not written in Java

### ISSUE THREAD

**Issue by nimiwio** [ReactiveX/RxJava#6323]
The examples in the "Problem Solving Examples in RxJava" section of the wiki do not seem to be written in Java.

https://github.com/ReactiveX/RxJava/wiki/Problem-Solving-Examples-in-RxJava

**Comment by akarnokd** [comment]
Indeed, many of the wiki pages remained from the early days where this repo was poliglot. You are welcome to turn them into Java (8) examples.

**Comment by hoangnam2261** [comment]
Hello hello, can i take care this?

**Comment by akarnokd** [comment]
@hoangnam2261 Sure!

**Comment by akarnokd** [comment]
Closing via #6324
