### ISSUE TITLE
PublishSubject with a TestScheduler seems to not emit items

### ISSUE THREAD

**Issue by humblerookie** [ReactiveX/RxJava#6325]
I'm running into this strange issue with TestScheduler and PublishSubject where despite invoking `onNext` on the subject and backing it with the `testscheduler.triggerActions()` the items aren't emitted.

However the test passes if 
- I substitute the `TestScheduler` with a trampoline one.
- I use an `Observable.just(item)` instead of the subject with `subject.onNext(item)` to emit.

Is there something I'm missing? I've raised an issue on SO to no avail though.

**Minimum reproducible project**
https://gitlab.com/anvith/testissues

**Versions**
RxJava: 2.2.0 RxAndroid: 2.0.2

**Sample Classes**

    RunWith(MockitoJUnitRunner::class)
    class DemoViewModelTest  {

    //Error Mocks
    private val actionsStream: PublishSubject<DemoContract.ViewEvent> = PublishSubject.create()

    private lateinit var viewModel: DemoViewModel

    private val handler = mock(DemoContract.Handler::class.java)

    @Before
    fun setup() {
        viewModel = DemoViewModel(schedulersProvider, handler)
        viewModel.viewEventsStream = actionsStream
    }
     //Failing test
    @Test
    fun testUpdateCounter() {
        actionsStream.onNext(DemoContract.ViewEvent.UpdateClick)
        testScheduler.triggerActions()
        verify(handler).onUpdate()
    }

    //Test Constants

    protected var testScheduler = TestScheduler()

    protected var schedulersProvider: SchedulersProvider = object : SchedulersProvider() {
        override fun mainThread(): Scheduler {
            return testScheduler
        }

        override fun io(): Scheduler {
            return testScheduler
        }

        override fun computation(): Scheduler {
            return testScheduler
        }

        override fun newThread(): Scheduler {
            return testScheduler
        }

        override fun trampoline(): Scheduler {
            return testScheduler
        }

        override fun single(): Scheduler {
            return testScheduler
        }
     }
     }

    class DemoViewModel (val schedulersProvider: SchedulersProvider, val handler:DemoContract.Handler) : DemoContract.ViewModel() {

    var viewEventsStream: PublishSubject<DemoContract.ViewEvent>? = null
        set(value) {
            field = value
            subscribeToViewEvents()
        }

    private fun subscribeToViewEvents() {
        viewEventsStream?.let {
            it.subscribeOn(schedulersProvider.io())
                .observeOn(schedulersProvider.mainThread())
                .subscribe(object:Observer<DemoContract.ViewEvent>{
                    override fun onComplete() {
                        println("Completed") 
                    }

                    override fun onSubscribe(d: Disposable) {
                        println("Subscribed $d")
                    }

                    override fun onNext(t: DemoContract.ViewEvent) {
                        onViewEvent(t)
                    }

                    override fun onError(e: Throwable) {
                        println("Error: $e")
                    }

                })
        }
    }
     fun onViewEvent(event: DemoContract.ViewEvent) {
        when (event) {
            is DemoContract.ViewEvent.UpdateClick -> {
               handler.onUpdate()
            }
        }
    }
    }

**Comment by akarnokd** [comment]
Please do not cross post issues, especially ones regarding the Android Platform and be more patient on StackOverflow.

https://stackoverflow.com/questions/53519339/issue-with-publishsubject-and-testscheduler-item-isnt-emitted

**Comment by humblerookie** [comment]
Sorry about the cross post and impatience.
