### ISSUE TITLE
2.x: Consider to add CompletableSubject.fromCompletable method to make cold Completable hot

### ISSUE THREAD

**Issue by gryphon2411** [ReactiveX/RxJava#6327]
In addition to current `CompletableSubject` creation methods (_fromX_), consider to add the following creation method:

```
// Returns a Completable instance that subscribes to the given Completable, and emits its normal
   onError or onComplete events.
public static Completable fromCompletable(CompletableSource completable)
```

By the way, how is it possible to achieve this kind of behavior using the current API (2.2.2)?

**Comment by akarnokd** [comment]
Please check the available methods next time before asking for enhancements. The method is called `wrap`.
