### ISSUE TITLE
concatWith after mergeWith not working with Completables

### ISSUE THREAD

**Issue by Zachinio** [ReactiveX/RxJava#6328]
lib version:    implementation 'io.reactivex.rxjava2:rxandroid:2.1.0'

I have a list of completables and I run them serially with "concatWith" operator - works fine.
Some of the completables have to run async so I used "mergeWith" operator to merge all the async completables together - works fine.
Now after these async completables complete I concat the next completable in the list, when I subscribe the completable everything works fine except the completables I concat after the async completables.

You can see this code to reconstruct the issue, I used "startWith" operator instead but still get the same result.
https://github.com/ZachBublil/Choreographer/blob/fix_choreograph/Choreographer/Choreograper/src/main/java/zachinio/choreograper/Choreographer.kt

**Comment by akarnokd** [comment]
It is unclear to me what your problem is. Please provide a standalone, non-Android unit test that demonstrates your problem.
