### ISSUE TITLE
2.x Operator proposal Maybe.interceptOnComplete()

### ISSUE THREAD

**Issue by GVFiQst** [ReactiveX/RxJava#6332]
All of the observables have `.flatMap()` method. This is a very convenient operator indeed. But it works with `onSuccess/onNext` callbacks only. And the `Maybe` observable has `onComplete` callback which has no similar operators. 

So I had an idea to introduce this operator and I called it `interceptOnComplete` His purpose is when `onComplete` occurs to subscribe to some other `Completable`, wait for it to complete, and pass this callback to downstream.

What are the use cases? Here is something I had an experience with. For instance, I have this manager class:
```
interface AuthManager {
  
     val currentUser: Maybe<User> // Maybe because user can be logged out

     fun logout(): Completable
}
```

And I use it like this

```
authManager.currentUser
// instead of .doOnComplete { authManager.logout().subscribe { router.navigateToLogin() } }
    .interceptOnComplete { authManager.logout() } // Clearly something gone wrong so notify the API that we're logged out
    .observeOn(AndroidSchedulers.mainThread())
    .subscribeOn(Schedulers.io())
    .subscribeBy(
            onSuccess = view::setUser,
            onError = ::handleError,
            onComplete = router::navigateToLogin
    )
```
In the profile screen, I want to show the user basic info and for this, I need `authManager.currentUser`. But there are possibilities when a user is blocked, or deleted, or filtered by `filter` operator, or some error happened in deeps of the data layer and in those cases `authManager.currentUser` returns null, which means `Maybe.onComplete()`. So, in that case, I should notify the API and show the login screen to the user. Before, it was done in a very simple but awful way. Or I put this code `onComplete = authManager.logout().subscribe { router.navigateToLogin() }` to `subscribe` method or I put the same code to `doOnComplete` method. It looked like I needed some new operator.

So I thought: "We're all programmers here, why not try and implement such operator"
And here is my "try":
```
import io.reactivex.*
import io.reactivex.disposables.Disposable
import io.reactivex.exceptions.Exceptions
import io.reactivex.internal.disposables.DisposableHelper
import java.util.concurrent.atomic.AtomicReference

fun <T> Maybe<T>.interceptOnComplete(provider: () -> Completable): Maybe<T> 
        = InterceptOnComplete(this, provider)

class InterceptOnComplete<T>(
        private val source: MaybeSource<T>,
        private val provider: () -> Completable
) : Maybe<T>() {

    override fun subscribeActual(observer: MaybeObserver<in T>) {
        source.subscribe(InterceptOnCompleteMaybeObserver(observer, provider))
    }

    private class InterceptOnCompleteMaybeObserver<T>(
            private val actual: MaybeObserver<in T>,
            private val provider: () -> Completable
    ) : AtomicReference<Disposable>(), MaybeObserver<T>, Disposable {

        var d: Disposable? = null

        override fun onSubscribe(d: Disposable) {
            if (DisposableHelper.validate(this.d, d)) {
                this.d = d

                actual.onSubscribe(this)
            }
        }

        override fun onComplete() {
            val next: Completable

            try {
                next = provider()
            } catch (e: Throwable) {
                Exceptions.throwIfFatal(e)
                actual.onError(e)
                return
            }

            if (!isDisposed) {
                next.subscribe(NextSubscriber())
            }
        }

        override fun onSuccess(t: T) = actual.onSuccess(t)

        override fun onError(e: Throwable) = actual.onError(e)

        override fun isDisposed() = DisposableHelper.isDisposed(get())

        override fun dispose() {
            DisposableHelper.dispose(this)
            d?.dispose()
            d = null
        }

        inner class NextSubscriber : CompletableObserver {
            override fun onSubscribe(d: Disposable) {
                DisposableHelper.setOnce(this@InterceptOnCompleteMaybeObserver, d)
            }

            override fun onComplete() = actual.onComplete()

            override fun onError(e: Throwable) = actual.onError(e)
        }
    }
}
``` 

While working on this class I was trying my best to develop the code that has the same look as any other rxjava operators. So I used `MaybeFlatten.java` source as a base.

So this is what I wanted to share with you. Waiting for your feedback and thanks in advance!

**Comment by akarnokd** [comment]
This is a very peculiar operator and I'm not convinced this should be in RxJava. Luckily, you are on Kotlin which allows you to have as many custom instance operators as you want via extension methods.
The extensions project has [`flatMap` for signal types](https://github.com/akarnokd/RxJava2Extensions#flatmap-signal) though.
