### ISSUE TITLE
combineLatest glitch problem?

### ISSUE THREAD

**Issue by ursusursus** [ReactiveX/RxJava#6338]
Hi,
Is there a out of the box solution to *glitch problem in combineLatest* in rxjava?
 (when source observables of the combineLatest are driven by common observable -- you get unexpected results since first source will emit first, therefore paired with  previous value of second source)

I do understand combineLatest as is, works as intended, however this is a real world use case, and I was wondering if there was some lower level solution (different operator possibly -- I do have looked in the extensions library, but nothing) like transactions I read, rather than debouncing for few nanoseconds, which might now be the most effective

Thanks

**Comment by akarnokd** [comment]
See:

- https://staltz.com/rx-glitches-arent-actually-a-problem.html
- https://stackoverflow.com/questions/25139257/terminology-what-is-a-glitch-in-functional-reactive-programming-rx

**Comment by ursusursus** [comment]
I've seen all that, and they do matter to me and I cannot use withLatestFrom.

So, only debounce?

(Actual usecase is mapping of LowerLevelEvent(val userId: String) to HigherLevelEvent(val user: User), where the User is provided by observable, so it can emit n times, so example output

```
LowerLevelEvent1(abc) -> HigherLevelEvent1(userAbc(nameVariation1)
LowerLevelEvent2(abc) -> HigherLevelEvent2(userAbc(nameVariation1)
LowerLevelEvent3(abc) -> HigherLevelEvent3(userAbc(nameVariation1)
LowerLevelEvent4(abc) -> HigherLevelEvent4(userAbc(nameVariation1)
                                       HigherLevelEvent4(userAbc(nameVariation2)
                                       HigherLevelEvent4(userAbc(nameVariation3)
```

so my naive solution is

```
val _lowerLevelEventObservable: Observable<LowerLevelEvent> = lowerLevelEventObservable
                        .replayingShare()

val _higherLevelEventObservable: Observable<HigherLevelEvent> = Observables
                        .combineLatest(
				_lowerLevelEventObservable, 
				_lowerLevelEventObservable
		                    .map { it.userId }
                		    .distinctUntilChanged()
		                    .switchMap { userRepository.findByIdObservable(it)
			) { lowerLevelEvent, user -> createHigherLevelInstance... }
```

So while userId is not changed user observable is subscribed, i.e. not resubscribed when new lowerLevelEmits & its userId is not changed

-- but here I do run into the glitch issue, because if new LowerlLevel1 with different userId comes, its paired with user object from previous userId

**Comment by akarnokd** [comment]
Why do you use `combineLatest`? You'd have to control the interleaving of signals to a great degree, which happens naturally with UI form validation.

**Comment by ursusursus** [comment]
I was thinking combineLatest to pair new lowerLevelEvent with cached value of the userObservable while userId is the same

Well, I could do it via

```
lowerLevelEventObservable.flatMap { lowerLevelEvent ->
    userRepository.findByIdObservable(lowerLevelEvent)
        .map { user -> createHigherLevelInstance ... }
}
```

but, this will keep the user observable (database query) subscribed indefinitely n times since its noncompleting cold,

using switchMap risks missing out HigherLevelEvent values (which I cannot have, downstream needs to see all of lowerLevelEvent types) since user observable is async and could take a while -- with 2 very fast lowerLevelEvents with 2nd coming before 1st one gets mapped waiting for user observable to finish query (also, it needlessly resubscribes the same observable if userId didnt change)
