### ISSUE TITLE
2.x: Observable.combineLatest skips async events

### ISSUE THREAD

**Issue by arturdryomov** [ReactiveX/RxJava#6341]
### Versions

* RxJava: 2.2.4
* RxAndroid: 2.1.0

### Sample

```kotlin
val numberStream = mainThreadObservable // emits something
    .map { 42 }
    .logOnNext("source: number")
val booleanStream = ioThreadObservable // emits "true" at undefined moment
    .startWith(false)
    .logOnNext("source: boolean")

disposable += Observable
    .combineLatest(
        numberStream.logOnNext("combination: number"),
        booleanStream.logOnNext("combination: boolean")
    )
    .logOnNext("combination")
    .subscribe()
```
#### Actual
```
13:06:44.654 I: [main] [source: boolean]: false
13:06:44.658 I: [main] [combination: number]: 42
13:06:44.660 I: [main] [combination: boolean]: false
13:06:44.661 I: [Rx-io-20] [source: boolean]: true
13:06:44.667 I: [main] [combination]: (42, false)
```
#### Expected
Everything as in **Actual**, but with this line in the end.
```
13:06:44.667 I: [main] [combination]: (42, true)
```
### Thoughts

This does not happen all the time consistently though. Researching this behavior lead me to #5325. Is it true that `Observable.combineLatest` is not guaranteed to process all `onNext` events when dealing with multi-thread streams? What is the best practice in this scenario? Add `observeOn(Schedulers.single())` to all streams in `combineLatest` statement?

**Comment by akarnokd** [comment]
This is called glitch and there were questions already: https://github.com/ReactiveX/RxJava/issues/6338#issuecomment-447252785 . It is not guaranteed you get a perfect zig-zag combination pattern with async sources running on different threads. The best behavior is when all sources emit from the same thread, such as UI events used for form validation. There is no clear good behavior, even if you wait for all sources to emit once, some may emit more so you also miss on combinations. You have to rethink why you wanted to rely on the zig-zag behavior in the first place.

**Comment by arturdryomov** [comment]
Damn, the referred issue was created 4 hours ago. I swear it wasn’t on purpose 😉 

I tend to disagree though. If I’m reading the article correctly André describes a case when both combinations are emitted. The sample I’ve attached above skips one entirely. I agree that the ordering might be lost due to async nature, but skipping the event looks like another issue.

**Comment by akarnokd** [comment]
One of the sources emits faster than the other so its first emission can't be paired. Why do you want to use `combineLatest` anyway? If you don't want to lose data, merge values (via records hosting source info), batch/coalesce them with time/conditions and then write logic that decides how to combine events.

**Comment by arturdryomov** [comment]
Totally agree about the first value, but the described case skips the second one, not the first.

**Comment by akarnokd** [comment]
The second value should arrive on the IO thread (due to `[Rx-io-20] [source: boolean]: true`) so it is very unlikely you'd get `[main] [combination]: (42, true)`.

**Comment by arturdryomov** [comment]
Fare, the threading mark is my bad. Should be:

```
13:06:44.668 I: [Rx-io-20] [combination]: (42, true)
```

About the motivation behind the code in the sample. It was desirable to monitor events from both streams and emit a new one when any of them changes. There is no clear control stream, i. e. the one the other one should `switchMap` from. The actual code is actually more complex — it involves not two but three streams in `combineLatest`. The same behavior applies though.

**Comment by akarnokd** [comment]
Is `(42, true)` is never printed? If so, please provide a standalone Java unit test that demonstrates your emission pattern.

**Comment by arturdryomov** [comment]
Yep, it is never here. I’ll do my best ASAP, can be tricky due to multithreading though, but let’s see how it goes. Thanks!
