### ISSUE TITLE
More descriptive error with map operators in 2.x

### ISSUE THREAD

**Issue by mkrussel77** [ReactiveX/RxJava#6342]
Thanks for using RxJava but before you post an issue, please consider the following points:

  - [ ] Please include the library version number, including the minor and patch version, in the issue text. In addition, if you'd include the major version in the title (such as `2.x`) that would be great.

  - [ ] If you think you found a bug, please include a code sample that reproduces the problem. Dumping a stacktrace is usually not enough for us.

  - [ ] RxJava has more than 150 operators, we recommend searching the [javadoc](http://reactivex.io/RxJava/2.x/javadoc/io/reactivex/Observable.html) for keywords of what you try to accomplish.

  - [ ] If you have a question/issue about a library/technology built on top of RxJava (such as Retrofit, RxNetty, etc.), please consider asking a question on StackOverflow first (then maybe on their issue list).

  - [ ] Questions like "how do I X with RxJava" are generally better suited for StackOverflow (where it may already have an answer).

  - [ ] Please avoid cross-posting questions on StackOverflow, this issue list, the Gitter room or the mailing list.

Currently it can be very hard to debug bugs with map methods.  If the map method returns null, something like SingleMap throws a a NullPointerException saying the mapper returned null.  The problem is that the code that produced the null is no longer in the stack trace.  Also if there was an observeOn, the stack trace doesn't include what generated the value being mapped.

If a code base has a lot use of map operator, and crashes are only happening in production, it can be very hard to determine which map method is broken.

This is mainly an issue when using global error handlers cannot log what stream encountered the error.

My thought would be to add the string representation of the mapper function to the exception message.  This might require adding an overload to requiredNonNull that supports arguments similar to how Guava preconditions work.

**Comment by mkrussel77** [comment]
I also noticed, that Function.apply is not annotated as NonNull like all the other functions.  Not sure if that is intentional.  If map took an interface that did not support null, static checkers could warn about broken implementations of Function.

**Comment by akarnokd** [comment]
> My thought would be to add the string representation of the mapper function to the exception message. This might require adding an overload to requiredNonNull that supports arguments similar to how Guava preconditions work.

This doesn't work properly and adds considerable overhead.

The workable solution is to use `Objects.requireNonNull()` (or equivalent) in your mapper functions/lambdas meticulously so the lambda itself crashes upon null, not the operator's failsafe.

> Function.apply

Sometimes it is legitimate to return null from a function because it is known it won't enter the sequence (i.e., key selectors). Marking it globally non-null prevents that and there is no good local way to define use-site nullness.

**Comment by sjr** [comment]
https://rongi.github.io/kotlin-blog/rxjava/2017/09/25/breadcrumbs-rxjava-error-handling.html could be helpful if you are getting stuck with these
