### ISSUE TITLE
Observable.using() disposes resource before upstream

### ISSUE THREAD

**Issue by AterIgnis** [ReactiveX/RxJava#6347]
I've expected that Observable.using flow is:
* create resource
* creates resource using observable, subscribe
* finish/cancel resource-using observable
* dispose resource

But for me actual is sometimes
* create resource
* creates resource using observable, subscribe
* dispose resource
* finish/cancel resource-using observable

As I understand, using 'eager' makes second flow consistent,but i need first behavior, which is not observed on dispose() call - resource is disposed first always, then observable. What is correct way to make Observable which is not eager even on dispose?

https://github.com/ReactiveX/RxJava/blob/5278124db4a93b8f59cee4e3baa9e864601637fd/src/main/java/io/reactivex/internal/operators/observable/ObservableUsing.java#L151

**Comment by akarnokd** [comment]
Indeed eagerness is not affecting the dispose order, and I'm not certain if it should or not. /cc @artem-zinnatullin @davidmoten @vanniktech 

The shortest workaround would be for you to take the operator by source and have a local version with the desired order of disposal.

**Comment by vanniktech** [comment]
I'm not sure either. Haven't really used `using`.

**Comment by AterIgnis** [comment]
My understanding was that resource is allocated firtst and free'd last, and i used it in Android to wrap some of APIs, like 'call register/start', 'handle results as observable', 'call unregister/stop'. But as on dispose Using first disposes resource (in my case - calls 'unregister/stop') it ended up in some kind of 'race conditon': observable chain is partially disposed, 'stop' is called, but as stop can be called by Android itself - it emits onError, which is not handled already, thus app crashes with undeliverable exception.
Second cause of issue was because i used SwitchMap on this Using, which first disposes upstream and then inner subscription, but that was fixed by moving switchMap inside of Using observable (second argument).

Currently i've went around this by copying code from Using and making it always dispose resource last, as was suggested.

**Comment by akarnokd** [comment]
This would be a change for 2.x with unexpected consequences so instead, this should be changed in 3.x. 
So eager disposes the resource first, non-eager disposes resource last.

**Comment by akarnokd** [comment]
Closing via #6534.
