### ISSUE TITLE
2.x: parallel blocks forever with TestScheduler

### ISSUE THREAD

**Issue by asarkar** [ReactiveX/RxJava#6355]
io.reactivex.rxjava2:rxjava:2.2.3

 ```java
public class DemoApplication {
    public static void main(String[] args) {
        List<Map.Entry<Integer, String>> entries = Arrays.asList(
                new AbstractMap.SimpleImmutableEntry<>(3, "hello"),
                new AbstractMap.SimpleImmutableEntry<>(3, "world")
        );

        Flowable.fromIterable(entries)
                .flatMap(entry -> Flowable.range(1, entry.getKey())
                        .parallel()
                        .runOn(Schedulers.io())
                        .flatMap(i -> logIt(entry.getValue()).toFlowable())
                        .sequential()
                )
                .all(success -> success)
                .doOnSuccess(success -> System.out.println("good"))
                .doOnError(Throwable::printStackTrace)
                .blockingGet();
    }

    private static Single<Boolean> logIt(String s) {
        System.out.println(s);

        return Single.just(true);
    }
}
```

This code works as expected. However, replacing `Schedulers.io()` with `TestScheduler` blocks forever. Gradle project attached.

[demo.zip](https://github.com/ReactiveX/RxJava/files/2722335/demo.zip)

**Comment by akarnokd** [comment]
Do you call `advanceTimeBy` anywhere?

**Comment by asarkar** [comment]
Nop, am I supposed to? I'm under the impression that the work only depends on availability of threads, and no delay is involved. Also, AFAIK, `TestScheduler` is single threaded, so all I'm expecting is the messages logged sequentially.

**Comment by akarnokd** [comment]
There are plenty of resources on the internet, such as [this](https://github.com/Froussios/Intro-To-RxJava/blob/master/Part%204%20-%20Concurrency/2.%20Testing%20Rx.md) that demonstrate `TestScheduler`. You can find other resources by searching for `RxJava TestScheduler` in your favorite search engine.

**Comment by asarkar** [comment]
There are exactly zero resources on the internet that demonstrate `TestScheduler` along with `parallel`. I couldn't find other resources for the same in my favorite search engine.

**Comment by akarnokd** [comment]
Schedulers are orthogonal to flows, so conceptually it doesn't matter if you run a sequential or parallel flow with them.

**Comment by asarkar** [comment]
Hmm, so `TestScheduler` doesn't start until the time is advanced, even if there's no delay or interval in the code (nothing that apparently involves "time"). That wouldn't be my first thought; perhaps you can add a note to the docs you linked to above to clarify this behavior, and why's it this way? Or, if you do that here, I'll be happy to send a PR for the docs.

**Comment by akarnokd** [comment]
> even if there's no delay or interval in the code [...] That wouldn't be my first thought

`TestScheduler` captures tasks scheduled by operators so that side-effects can be performed before the task then gets executed on demand via `advanceTimeBy`, even if they are logically not delayed. In reality, there is always some non-zero time elapsing between the scheduling and execution of such task. `TestScheduler` just makes it deterministic. 

> if you do that here, I'll be happy to send a PR for the docs.

If you wish to contribute, you could extend its [JavaDocs](https://github.com/ReactiveX/RxJava/blob/2.x/src/main/java/io/reactivex/schedulers/TestScheduler.java#L29) with the explicit mention of `advanceTimeBy` or even a short example.

**Comment by asarkar** [comment]
@akarnokd https://github.com/ReactiveX/RxJava/pull/6356
