### ISSUE TITLE
2.x: Deadlock when adding doOnSubscribe to Flowable

### ISSUE THREAD

**Issue by Whathecode** [ReactiveX/RxJava#6363]
For some time, I [have been investigating a deadlock that occurs in my codebase](https://stackoverflow.com/q/54116679/590790), seemingly after the default backbuffer size has been filled. While trying to create a repro, I ran into a similar issue which shows the same symptoms with a minimum amount of code. I see no obvious cause, and therefore believe this might be a potential RxJava 2.x bug (reproducible so far on 2.2.0 and 2.2.5).

```
fun main( args: Array<String> )
{
    // Override the default buffer size of 128 to 10 for easier testing.
    System.setProperty( "rx2.buffer-size", "10" )

    val numbers = Flowable
        .range( 0, Int.MAX_VALUE )
        // Commenting out '.doOnSubscribe' here prevents the deadlock.
        .doOnSubscribe { println( "Subscribed." ) }
        .share()
    val evenNumbers = numbers
        .filter { number -> number % 2 == 0 }
    val oddNumbers = numbers
        .filter { number -> number % 2 != 0 }
    val getNextOdd = oddNumbers.first( 0 )
    evenNumbers
        .concatMap { even ->
            Single.zip(
                Single.just( even ), getNextOdd,
                BiFunction { a: Int, b: Int -> Pair( a, b ) }
            ).toFlowable()
        }
        .takeWhile { it.first < 1000 }
        .doOnComplete { println( "Done." ) }
        .subscribe { println( it ) }

    readLine()
}
```
This halts depending on the backbuffer size. In the code example at:

> Subscribed.
> (0, 1)
> (2, 3)
> (4, 5)
> (6, 7)
> (8, 9)

As commented in the above code, commenting out the `doOnSubscribe` line will prevent the deadlock from occurring.

Is this a bug, or am I doing something inherently wrong? E.g., I imagine things get complicated the way I reuse the same stream to 'zip', but this is the use case which also is needed in my actual codebase. Regardless, I do not understand what `doOnSubscribe` would have to do with anything here.

**Comment by akarnokd** [comment]
Hi and thanks for reporting. This is a bug in the `publish` operator (part of `share`) not requesting more if there was a change in the subscriber array (due to `first` in your example). The reason it didn't happen without `doOnSubscribe` is that `range` and `publish` operators fuse together when adjacent to each other and there is no request management involved there as an optimization. Preventing this fusion resulted in the request mismanagement bug. I'll post a fix shortly.

*(Ps. Please next time, post a Java code example as not only there isn't an IntelliJ option to paste Kotlin code as Java, but I have to manually battle the lambdas for it to be Java 6 compatible. Thanks.)*

**Comment by Whathecode** [comment]
Thank you for the amazingly quick fix! At a glance, it might in fact be [the same deadlock I initially observed](https://stackoverflow.com/questions/54116679/avoiding-same-pool-deadlocks-when-using-flowable-in-reactive-extensions). I will keep you informed, and make sure to post Java code samples in the future.

In case upgrading to a temporary release would not be an option, would you know of any potential workaround which does not require a change to the 'publish' operator?

I believe for my use case, I might be able to call `publish( expectedMaxItems ).refCount()`. Would this imply `expectedMaxItems` would be kept in memory, or is this unrelated?
