### ISSUE TITLE
concat&concatMap  vs  BlockingQueue#take= ANR

### ISSUE THREAD

**Issue by DeanLXY** [ReactiveX/RxJava#6367]
hello,
   A new problem has arisen. When using the operator (concatMap), this operator uses the blockingQueue.take blocking method, which causes frequent anr. Version 1.x. Looking forward to reply

**Comment by akarnokd** [comment]
1.x is no longer supported. Also we don't use blocking queues in `concatMap`.

**Comment by DeanLXY** [comment]
Thanks answer
Using blockingQueue.take() in the concatMap operator thread, what is the cause of anr?
I understand that #take() is a blockQueue blocking method that can be used in any thread.

**Comment by akarnokd** [comment]
Please ask such questions on StackOverflow under the Android tag. You should also provide more context there as ANR is a typical issue when you are using blocking operations within RxJava or outside of it.
