### ISSUE TITLE
Interruption does not happen when timing out a task scheduled on `Schedulers.from(executor)`

### ISSUE THREAD

**Issue by BrynCooke** [ReactiveX/RxJava#6368]
It looks like when using a scheduler created from `Schedulers#from` using timeout will not interrupt the task:

Version 2.2.5

```java
ScheduledExecutorService scheduledExecutorService = Executors.newScheduledThreadPool(10);
        Scheduler schedulerFromExecutor = Schedulers.from(scheduledExecutorService);

        Flowable<Integer> results = Flowable.fromIterable(()-> {

            return new Iterator<Integer>() {
                @Override
                public boolean hasNext()
                {
                    try
                    {
                        Thread.sleep(1000);
                        return false;
                    }
                    catch (InterruptedException e)
                    {
                        System.out.println("Interrupted! " + e);
                        return true;
                    }
                }

                @Override
                public Integer next()
                {
                    return 2;
                }
            };

        }).subscribeOn(schedulerFromExecutor);//change to Schedulers.io() to make it work.

        results.timeout(500, TimeUnit.MILLISECONDS, Schedulers.single(), Flowable.error(new TimeoutException("Timed out")))
                .doOnTerminate(()-> System.out.println("Finished"))
                .subscribe(r-> System.out.println("Got " + r), e-> System.out.println("Error " + e));

        Thread.sleep(2000);
```

Output when using `schedulerFromExecutor`
```
Finished
Error java.util.concurrent.TimeoutException: Timed out
```

Output when using `Schedulers.io()`
```
Finished
Interrupted! java.lang.InterruptedException: sleep interrupted
Error java.util.concurrent.TimeoutException: Timed out
```

**Comment by akarnokd** [comment]
Hi and thanks for reporting. Looks like we don't have support for interrupting immediate tasks of `Schedulers.from`. Currently, there is no 1:1 mapping of a cancelable `Future` and RxJava tasks as every immediate task is coalesced into a trampolined execution, thus a `Future` is covering arbitrary tasks, not just 1 specifically like with the standard schedulers.

The solution is replicate the interruption logic of `FutureTask` but I have to think about a bit in context of our Scheduler requirements.

**Comment by BrynCooke** [comment]
Thanks for looking in to this so quickly.
In the meantime I am looking at using your implementation of ParallelScheduler https://github.com/akarnokd/RxJava2Extensions#parallelscheduler

**Comment by akarnokd** [comment]
/cc @artem-zinnatullin @vanniktech 

I think making the implementation interruptible by default is a change that could affect current users relying on it not being interruptible. I suggest adding a mode selector overload to `Schedulers.from`.

**Comment by vanniktech** [comment]
Yes. Let's keep the current behavior and add a flag to opt into the new one.

**Comment by artem-zinnatullin** [comment]
Sounds reasonable to me to make it opt-in while keeping current behavior as is.

**Comment by jonenst** [comment]
Hi,
out of curiosity, do you remember the reason for not using FutureTask, and instead writing InterruptibleRunnable ?
Cheers,
Jon

**Comment by akarnokd** [comment]
Because we needed to have cleanup running correctly with respect of the interrupt and normal termination without the extra feature baggage overhead of `FutureTask`:

https://github.com/ReactiveX/RxJava/blob/a1693ecc9215027a7a3eae75272979ebb4d79a27/src/main/java/io/reactivex/rxjava3/internal/schedulers/ExecutorScheduler.java#L358

https://github.com/ReactiveX/RxJava/blob/a1693ecc9215027a7a3eae75272979ebb4d79a27/src/main/java/io/reactivex/rxjava3/internal/schedulers/ExecutorScheduler.java#L385
