### ISSUE TITLE
Difference in behaviour when using newFixedThreadPool for execution

### ISSUE THREAD

**Issue by gauravthadani** [ReactiveX/RxJava#6374]
Hello,

### Brief details:
On using custom schedulers (Scheduler.from(Executors.newFixedThreadPool(100)), my program doesn't terminate. However with Scheduler.io() and Scheduler.computation() it works just fine. 

I have tried this with the RxJava 2.2.5 and 2.2.4
Not quite sure if its an issue, or I am missing something.

### Use case: 
- to stream the names of files in a file store
- and fetch the contents of each file using a reactive approach
- and then persist it to another store/database (API's with blocking i/o calls, hence using a large thread pool)
Difference in behavior simulated with code below using sleep and addition of 2 numbers.

### Issue
My production code that - Observable<Single<InputStream>>
- streams the names of the files 
- then gets the contents of each file
- and persists it to a database 
 the program does not terminate and hangs indefinitely despite shutting down the executorService.

I cannot use the Scheduler.computation() as there are too few threads, nor Scheduler.io() as the program goes out of memory. It creates a new thread for each task, which spawns into millions.

Hence using a fixed thread pool. The tasks all complete, prints the "SHUTTING DOWN" but does not terminate.

### Code:
Gist at https://gist.github.com/gauravthadani/10a58b0e67c235ac46115e0f3cb0cb00#file-rx-trial-L34

```
import io.reactivex.Observable;
import io.reactivex.Scheduler;
import io.reactivex.Single;
import io.reactivex.schedulers.Schedulers;

import java.time.Instant;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.stream.IntStream;

public class main {

    public static void main(String args[]) {
        System.out.println(Thread.currentThread().getName());
        System.out.print(Instant.now().toString());

        ExecutorService executorService = Executors.newFixedThreadPool(2500);

        Scheduler scheduler = Schedulers.from(executorService);
//        Scheduler scheduler = Schedulers.computation();

        Observable<Single<Integer>> streaming = Observable.create(emitter -> IntStream
                .range(1, 10000)
                .parallel().forEach(value -> {
                    print("streaming");
                    getSubscribe(value)
                            .subscribeOn(scheduler)
                            .subscribe(main::persist);
                }));

        streaming.flatMap(Single::toObservable)
                .toList().subscribe();

        executorService.shutdown(); //Do I really need this? how does it work fine with Schedulers.io()/Schedulers.computation()
        System.out.print(Instant.now().toString());
    }

    private static Single<Integer> getSubscribe(int value) {
        return Single.defer(() -> add(value));
    }


    private static Single<Integer> add(int args) {
        print("going to fetch number");
        try {
            Thread.sleep(200);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }

        return Single.just(args + args);
    }


    private static void print(Object args) {
        System.out.printf("Args : %s Thread name : %s \n", args.toString(), Thread.currentThread().getName());
    }

    private static void persist(Integer in) {
        print("fetched the number");
        print(String.format("going to save %s ", in));
        try {
            Thread.sleep(150);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
        print("finished saving the number");
    }
}
```

### Note:
I can't be sure if its an issue, or I am missing something. Any help will be appreciated.

**Comment by akarnokd** [comment]
Hi.

> Not quite sure if its an issue, or I am missing something.

You are missing on the default behavior of Java's `newFixedThreadPool`, namely it creates non-daemon thread that has to be shut down for the JVM to quit. RxJava's threads are daemon and thus don't prevent the JVM from quitting.

**Comment by gauravthadani** [comment]
Thank you for the quick response.
As mentioned, my production code does not terminate despite invikinh shutdown on the executor service. Any thoughts or ideas on why that could be behaving differently?
