### ISSUE TITLE
Add doOnTerminate to Single/Maybe for consistency

### ISSUE THREAD

**Issue by kennymacleod** [ReactiveX/RxJava#6379]
As mentioned in #5814, there is no `doOnTerminate` operator on `Single` or `Maybe`, but there is on `Observable`, `Flowable` and `Completable`. There doesn't seem to be any reason for this inconsistency, other than it's just an omission. 

Yes, you can workaround this using `donOnEvent`, but can we instead get this operator added just for API consistency?

**Comment by akarnokd** [comment]
Okay, PR welcome.

**Comment by skryvets** [comment]
@akarnokd, I would like to contribute to this feature, is this issue free to work on? However, even though it seems pretty straightforward, I'm new to this project and it may take some time for me to submit a final PR, is it acceptable? I don't want to block if it's an urgent need and can be done by somebody else in a faster manner. Thanks.

**Comment by akarnokd** [comment]
Nobody has started working on this to my knowledge. I suggest you do it either way so you gain experience with doing PRs as well as creating RxJava operators.

**Comment by skryvets** [comment]
Thanks for the tip. Will do.
