### ISSUE TITLE
Possible race condition in doOnLifeCycle and add doOnLifeCycle to Single

### ISSUE THREAD

**Issue by xblwyc** [ReactiveX/RxJava#6385]
Hi,

I am wondering why we do not make onSubscribe and onDispose actions synchronized, to avoid possible race condition? My case is we would like to prepare some resources on subscription and release them onDispose. Without synchronization it's easy to get a leak since the resource may not be ready when dispose() is triggered. 

Also, why there's no doOnLifeCycle in Single?

Thank you!

**Comment by akarnokd** [comment]
Their purpose is to side-effect those lifecycle events. It is up to you to coordinate between them if you need, but your use case implies anoter operator exactly for that type.of work: `using()`.
