### ISSUE TITLE
set timeout for each observable and not global

### ISSUE THREAD

**Issue by AhmadNemati** [ReactiveX/RxJava#6387]
Hi My observable is this:

```
public Observable<String> getPingObservable(String url) {


    return Observable.create(subscriber -> {

        connectionsManager.checkProxy(time -> {
            subscriber.onNext(time);
        }

        );
    });

}
```
and i set timeout

  ```
Observable.from(urlList)
            .subscribeOn(Schedulers.io())

            .flatMap(url -> {
                return getPingObservable(url)
                        .subscribeOn(Schedulers.io())
                        .timeout(500, TimeUnit.MILLISECONDS)
                        .onErrorResumeNext(throwable -> Observable.empty());

            })
            .toList()
           .subscribe();
```
after 500 MILLISECONDS all Observables emit onError method but i want to

use timeout for each Observable not global and do not terminate and

emit onError for other Observable

**Comment by akarnokd** [comment]
Because of `flatMap`, all your URLs run pretty much at the same time. Use `concatMap` to have them run one after the other or use `flatMap`'s `maxConcurrency` parameter to limit the active inner flows.

Also I recommend asking such questions on StackOverflow in the future.
