### ISSUE TITLE
How to force stop refCount(long timeout, .. )?

### ISSUE THREAD

**Issue by ursusursus** [ReactiveX/RxJava#6388]
Hi,
I would like to ask if there is a native way of force stopping the timout in a `refCount` overload that takes a timeout (only unsubscribes source after given timeout after all subscribers are gone

I am building a caching mechanism and would like to limit number of these in flight timeouts (force stopping it when a new item enters cache, etc)

**Comment by akarnokd** [comment]
The `timeout` in `refCount` is there to disconnect after all consumers have gone but new ones may show up in the meantime. To stop the timeout, you have to subscribe to it within the timeout period.
Also your use case may be better answered on StackOverflow.

**Comment by ursusursus** [comment]
No I meant to force stop it = instant unsubscribe as if there was no timeout, not rolling the observable back to "active"

(I do not believie it possible looking at sources, hence I asked here)

**Comment by akarnokd** [comment]
Why not use the [non-timeout overload](http://reactivex.io/RxJava/2.x/javadoc/io/reactivex/observables/ConnectableObservable.html#refCount--) then?

**Comment by ursusursus** [comment]
Sorry maybe I explained it wrong. I want to instant "run out and unsub the source" of the already in flight timeout, given some event (like another event entered cache (cache holding n observables), so only max x of these in flight timeouts are active and not unbounded)

**Comment by akarnokd** [comment]
I can't imagine what you try to achieve here. What you have described so far is certainly not possible with the standard refCount operator. You could look into managing the connectable observable yourself where you can disconnect at will.

**Comment by ursusursus** [comment]
Its quite mundane use case in mobile app. I am working with observable db queries, In order to not have multiple instances of the logically same query I use `replay(1).refCount()`

This query is run when entered a DetailScreen coming from a ListScreen, where there is list of items, ItemId is a paramter to DetailScreen which is then passed to the Repository which returns the observable

All works, but, if I go to detail screen 1, then back, then detail screen 2, then back to detail screen 1 quickly,  I am running query(item id = 1) twice, and this could be time-cached -- exactly what refCount(timeout) does

Hwoever, I do not want to have unlimited refCount timeouts running, but only lets say 3, to save resources of the computation scheduler

```
class AccountRepository(private val accountDao: AccountDao) {

    private val cache = ConcurrentHashMap<String, Observable<Optional<Account>>>()

    fun accountByIdObservable(accountId: String): Observable<Optional<Account>> {
        return cached(accountId) {
            accountDao.findByIdObservable(accountId)
        }
    }

    private fun cached(accountId: String, factory: () -> Observable<Optional<Account>>): Observable<Optional<Account>> {
        return cache.getOrPut(accountId) {
            factory()
                .distinctUntilChanged()
                .doFinally {
                    cache.remove(accountId)
                }
                .replay(1)
                .refCount(10, TimeUnit.SECONDS)
        }
    }
}
```

**Comment by akarnokd** [comment]
I suggest asking this Android specific use case on StackOverflow as others may have run into the same requirements and worked out a solution with other tools/technologies available on Android.

**Comment by ursusursus** [comment]
I dont believe its an android specific question, its more of a client thing, regardless, could be abstracted.

So you dont believe its possible natively and requires custom operator?

**Comment by akarnokd** [comment]
You'd likely have to go extra lengths to get it done with the standard operators. Custom one is certainly an option. The general case of having only a certain number of sequences running at once, throwing out old ones could be achieved via the [`switchFlatMap`](https://github.com/akarnokd/RxJava2Extensions#flowabletransformersswitchflatmap) operator.

**Comment by ursusursus** [comment]
Ok, thanks!
