### ISSUE TITLE
del

### ISSUE THREAD

**Issue by zubchenok** [ReactiveX/RxJava#6389]

**Comment by akarnokd** [comment]
RxJava is a well tested library and we successfully compile on all released JDK versions and compile targets: https://github.com/akarnokd/RxJava2_9#build-matrix . Please make sure first that you have a properly typed code and you understand the limits of the Java type system, especially in regards to co- and contravariance.

> some commits should be reverted

This doesn't make sense, even with the context of the `startWith` operator's commit more than 2 years ago. There must be a good reason to revert any commits, which we haven't done for years thanks to the rigorous testing and review process.

**Comment by zubchenok** [comment]
Sorry my fault, please ignore it. I just got wrong RxJava source.
