### ISSUE TITLE
I don't know why Schedulers class NewThreadTask implements Callable 

### ISSUE THREAD

**Issue by guohaiping521** [ReactiveX/RxJava#6391]
static final class NewThreadTask implements Callable<Scheduler> {
        @Override
        public Scheduler call() throws Exception {
            return NewThreadHolder.DEFAULT;
        }
    }

change to

getInstance(){
 return NewThreadHolder.DEFAULT;
}

the first What are the benefits?

**Comment by akarnokd** [comment]
It works around a problem with premature initialization of schedulers when they are overridden but the default implementation is not required nor is desirable to get initialized in the first place. This several indirections allow this to happen.

You can follow the Git Blame to find the relevant PRs/issues, such as #4585.

**Comment by guohaiping521** [comment]
Thank you very much
