### ISSUE TITLE
Catch operator

### ISSUE THREAD

**Issue by 155martinmoreno** [ReactiveX/RxJava#6393]
Is there a reason why RxJava does not have a "Catch" operator the way [C# does](http://introtorx.com/Content/v1.0.10621.0/11_AdvancedErrorHandling.html)? 

Would be useful if I want to handle a specific error type, but not to swallow all other errors.

**Comment by akarnokd** [comment]
Are you familiar with the keywords of the Java language? Or the [wiki page describing error management](https://github.com/ReactiveX/RxJava/wiki/Error-Handling-Operators)?

**Comment by 155martinmoreno** [comment]
I'm sorry to insist here, but I can't the answer on the wiki. 
I'm sure I must be missing something, but checking for a specific error to decide if switching or not to another stream would come down to something like 
```
Observable.error(new ExceptionToHandle("something went wrong!"))
                .onErrorResumeNext((Function<? super Throwable, ObservableSource<String>>) throwable -> {
                    if (ExceptionToHandle.class.equals(throwable.getClass())) {
                        return Observable.just("Stream Resumed!");
                    }
                    return Observable.error(new RuntimeException(throwable));
                })
                .subscribe(System.out::println)
```
When it could be something in the lines of 
```
Observable.error(new ExceptionToHandle("something went wrong!"))
                .resumeWhen(ExceptionToHandle.class, Observable.just("Stream Resumed!"))
                .subscribe(System.out::println)
```
as happens in [another implementations](http://introtorx.com/Content/v1.0.10621.0/11_AdvancedErrorHandling.html)


I'm just asking for the rationale behind this not existing in RxJava (if any)


As for the _"keywords of the Java language"_ question, I'm not going to answer much of it since it looks   like a condescending and plain rude comment.

**Comment by akarnokd** [comment]
RxJava is an established, more than 6 years old, open source library with a really small and dedicated people as maintainers remaining. Every question that can be researched and/or answered by the posters themselves saves time for us maintainers.

> Is there a reason why RxJava does not have a "Catch" operator the way C# does?

The API and method design was based on Rx.NET but adapted to the circumstances of the Java language and programming patterns. In Java, by convention, method names start with a lowercase letter, thus the C# `Catch` becoming `catch` is a keyword and cannot be a method name. Therefore, it was decided to change it to something else and probably convey more of the meaning of the operator: on-error-resume-next. Several overloads exist, including a function-handler variant which let's the user generate any resumption sequence based on the original error signal. The original C# could rely on the fact that C# preserves generic type information thus creating an API method that filters based on this generic parameter is straightforward and common. In contrast, this is not possible in Java as generic types are erased. A considered and abandoned resolution was to introduce a filter and then an error mapper callback version at the expense of API surface bloat.

> I'm just asking for the rationale behind this not existing in RxJava (if any)

Such specific error-management operator has not been common enough for RxJava to provide support for. Using the more generic [`onErrorResumeNext`](http://reactivex.io/RxJava/2.x/javadoc/io/reactivex/Observable.html#onErrorResumeNext-io.reactivex.functions.Function-) lets one implement the behavior relatively cheaply. If one can't live with the inconvenience and also is not tied to Java 6, [Project Reactor's Flux](https://projectreactor.io/docs/core/release/api/reactor/core/publisher/Flux.html#onErrorResume-java.lang.Class-java.util.function.Function-) does offer class and predicate-based filtering.

**Comment by camachoyury** [comment]
I would also like the idea of a Catch operator, because we usually would have something like the following
```
some_action.invoke()
                        .subscribeOn(Schedulers.io())
                        .observeOn(AndroidSchedulers.mainThread())
                        .subscribe(() -> {
                                    view.update();                                 
                                },
                                throwable -> {
                                    if (throwable instanceof UserNotLoggedInException) {
                                          view.showLoginError()
                                    } else {
                                        throw new Exception(throwable);
                                    }
                                })
```

when it could be 
```        some_action.invoke()
                        .subscribeOn(Schedulers.io())
                        .observeOn(AndroidSchedulers.mainThread())
                        .catchError(UserNotLoggedInException.class, {view.showLoginError()})
                        .subscribe(() -> {
                                     view.update();         
                                }
        );
```

**Comment by JakeWharton** [comment]
That wouldn't work. This is for recovery back into the stream and not for side-effects.

**Comment by 155martinmoreno** [comment]
@akarnokd I don't think Java erasure is the issue here...

> That wouldn't work. This is for recovery back into the stream and not for side-effects.

this looks more like a rationale behind the decision 

@JakeWharton what do you recommend to resume only on a specific error? 
(it would be a case of _recovery back into the stream_ just not for any error)

**Comment by camachoyury** [comment]
yeah I know , but I think the idea is to avoid having a lot of conditions for each type of errors(Exception) and catch them or resume the flow when something happens in the stream.  probably not is the best solution but a "resumeWhen" sound good
