### ISSUE TITLE
[2.x] Operator proposal: Flowable.compose() alternative which returns Maybe/Single.

### ISSUE THREAD

**Issue by daemas** [ReactiveX/RxJava#6395]
There is a `Flowable.compose()` operator which transforms a `Flowable` into another `Flowable` with different type of elements. But there is no operator to apply such a transformation which converts `Flowable` into `Single`/`Maybe`. This operator would allow to reuse complex logic on `Flowable`, which results in a single or optional element.

A simplified exapmle:

```java
class Test {
    public static Maybe<Integer> processFirstEven(Flowable<Integer> f) {
        return f.filter(i -> i % 2 == 0)
                .take(1)
                .singleElement()
                .map(s -> s * 12)
                // ... Some more complex logic here, including map/flatMap, switchIfEmpty etc...
                ;
    }

    public static void test() {
        Maybe<Integer> m = Flowable.fromArray(1, 3, 5, 6, 7, 8, 9)
                .compose(Test::processFirstEven) // Does not compile
                // ... Some more logic here on the resulting Maybe instance ...
                ;
    }
}
```

**Comment by akarnokd** [comment]
Hello. What's wrong with my comment on your [StackOverflow](https://stackoverflow.com/questions/54498104/flowable-compose-to-transform-to-single-or-maybe) post about this? Please do not cross post issues on multiple platforms. Thanks.

> To transform between the base types, use `to` or `as` instead of `compose`. – akarnokd yesterday

Use [to](http://reactivex.io/RxJava/2.x/javadoc/io/reactivex/Flowable.html#to-io.reactivex.functions.Function-) or [as](http://reactivex.io/RxJava/2.x/javadoc/io/reactivex/Flowable.html#as-io.reactivex.FlowableConverter-) to transfrom onto arbitrary output type, including Single or Maybe if the function returns that.
