### ISSUE TITLE
2.2.6 groupBy().flatMap() error handling

### ISSUE THREAD

**Issue by balakzde** [ReactiveX/RxJava#6396]
Hi,
I have encountered what I think is wrong behavior when combining groupBy and flatMap operator.

My example code of this behavior:

   

       val sequence = PublishSubject.create<Int>()
        sequence.groupBy { it / 3 }.flatMap { it }.subscribe({
            println(it)
        }, {
            //I thought the exception will be handeled here and that will be the end of it.
            println(it.message)
        })
        sequence.onNext(1)
        sequence.onNext(2)
        sequence.onNext(3)
        sequence.onNext(4)
        sequence.onNext(5)
        sequence.onNext(6)
        sequence.onNext(7)
        sequence.onNext(8)
        sequence.onError(Exception("Exception that is handled and also will ruin my day"))

I assumed once there is an error in sequence, it will be propagated once and handeled where I marked it in code.

The reality is that the excepion is propagated to every sequence created by groupBy, one is handeled and second one crashes the app with UndeliverableException.

If I look at the flatMap operator without groupBy, the behaviour is as expected:

``` val observableArray = Observable.fromArray(
                Observable.just("TEST1"),
                Observable.error<String>(Exception("first")),
                Observable.just("TEST2"),
                Observable.error<String>(Exception("second")),
                Observable.just("TEST3"),
                Observable.just("TEST4"),
                Observable.error<String>(Exception("third")),
                Observable.error<String>(Exception("fourth")),
                Observable.just("TEST5"),
                Observable.error<String>(Exception("fifth"))
        )

        observableArray.flatMap { it }.subscribe({
            println(it)
        }, {
            println(it.message)
        })
```
Output of this is:

```
TEST1
first
```

So my guestion is, is this the desired behaviour? How can I handle the exception correctly?

**Comment by akarnokd** [comment]
This is the expected behavior: `groupBy` notifies all active groups and the main output of the same error, `flatMap` handles only the very first error and routes any other errors into the global error handler. Use the `delayError` option with `flatMap` and/or install a global error handler in `RxJavaPlugins` to prevent crashes.
