### ISSUE TITLE
[2.x] Proposal: Alternate Computation and IO Schedulers

### ISSUE THREAD

**Issue by ChrisFrancis** [ReactiveX/RxJava#6399]
The current IO and computation schedulers bound Workers to particular threads, for the lifecycle of the worker. While this elegantly ensures that all work from a worker is serialized correctly, it has the potential for inefficiencies. We’ve noticed the following in our application:

1. The IO Scheduler under the hood doesn’t share ExecutorService among its workers, which leads to a high thread count at peak.
2. The Computation Scheduler assigns threads to workers round-robin. This may lead to an imbalance work between the underlying threads eg: With one thread constantly emitting while the other thread sits idly. 

We’d like to propose an alternate scheduler, The idea is to decouple threads from workers, using an approach similar to [work-stealing](https://en.wikipedia.org/wiki/Work_stealing) for both IO and computation. Each worker maintains its own queue of Runnables to ensure serialization, while a shared pool (one each for IO and computation) of Threads/Executor Services processes them. The stealing itself can be implemented round-robin, fifo, etc.

The new structure allows for the following:
- Continue to guarantee serialization as is.
- Have a smaller number of threads at peak, in the IO scheduler.
- More efficient sharing of resources between workers in the computation scheduler.

**Comment by akarnokd** [comment]
Please look at the existing option to wrap an arbitrary `Executor`/`ExecutorService` via [`Schedulers.from`](http://reactivex.io/RxJava/2.x/javadoc/io/reactivex/schedulers/Schedulers.html#from-java.util.concurrent.Executor-).

**Comment by yhartanto** [comment]
@akarnokd, I am working together with @ChrisFrancis. 

[Schedulers.from](http://reactivex.io/RxJava/2.x/javadoc/io/reactivex/schedulers/Schedulers.html#from-java.util.concurrent.Executor-) can cause race condition because essentially the executor may process multiple runnable from the same worker at the same time. 

I guess what we are trying to get input from is whether the opportunity to improve computation and io designed as we proposed makes sense?

**Comment by davidmoten** [comment]
Funny to see this issue, I was just thinking about work stealing in the RxJava context this morning. 

>Please look at the existing option to wrap an arbitrary `Executor`/`ExecutorService` via [`Schedulers.from`](http://reactivex.io/RxJava/2.x/javadoc/io/reactivex/schedulers/Schedulers.html#from-java.util.concurrent.Executor-).

@akarnokd yep, this gives them the ability to produce this themselves in a separate library.  Are you suggesting they work on this externally, benchmark etc, then seek review and possible incorporation into RxJava core?

>[Schedulers.from](http://reactivex.io/RxJava/2.x/javadoc/io/reactivex/schedulers/Schedulers.html#from-java.util.concurrent.Executor-) can cause race condition because essentially the executor may process multiple runnable from the same worker at the same time.

@yhartanto Can you give an example?

**Comment by akarnokd** [comment]
> [Schedulers.from](http://reactivex.io/RxJava/2.x/javadoc/io/reactivex/schedulers/Schedulers.html#from-java.util.concurrent.Executor-) can cause race condition because essentially the executor may process multiple runnable from the same worker at the same time.

No. The wrapper uses trampolining so submitting two tasks to the same worker will still execute them one after the other. You can easily verify this by submitting two tasks that sleep:

```java
Scheduler s = Schedulers.from(ForkJoinPool.commonPool());

Worker w = s.createWorker();

w.schedule(() -> {
    try {
        Thread.sleep(1000);
        System.out.println("Task 1");
        Thread.sleep(1000);
    } catch (InterruptedException ex) { }
});

w.schedule(() -> {
    try {
        Thread.sleep(1000);
        System.out.println("Task 2");
        Thread.sleep(1000);
    } catch (InterruptedException ex) { }
});

Thread.sleep(5000);
w.dispose();
```

> Are you suggesting they work on this externally

I meant the behavior they are looking for is, most likely, easily achievable currently with `Schedulers.from` so neither RxJava nor they have to write a custom scheduler.

**Comment by akarnokd** [comment]
> benchmark etc, then seek review and possible incorporation into RxJava core?

Even if one would optimize such schedulers for the described work-stealing, I find the use case uncommon to include the special scheduler(s) in RxJava proper. Unlike instance operators, `Scheduler`s can live anywhere outside RxJava as do my [custom Schedulers](https://github.com/akarnokd/RxJava2Extensions#custom-schedulers). Reviewing is possible.

**Comment by yhartanto** [comment]
Got it, thanks for that. We will go back and test that first. 

In general, is there high level concern with decoupling worker and the underlying ExecutorService for computation and IO? 

@davidmoten, we are still working on the implementation but what you suggested was what we were thinking. Build it outside this project and if we are happy with the improvement then discuss upstreaming.

**Comment by akarnokd** [comment]
There are rules for `Scheduler` and `Worker` implementors (see their JavaDocs) which is expected by operators, such as the FIFO guarantee. The simplest way to achieve them is a dedicated 1 thread per worker approach.

**Comment by davidmoten** [comment]
@ChrisFrancis  @yhartanto I'm happy to help review as well (in external project or whatever).

**Comment by davidmoten** [comment]
>1. The IO Scheduler under the hood doesn’t share ExecutorService among its workers, which leads to a high thread count at peak.

@akarnokd I haven't had a look at this yet. Is this complaint valid?

**Comment by akarnokd** [comment]
@davidmoten That's been the design forever, each worker is a separate thread and there is reuse but no bound on the total number of active threads. That's what `Schedulers.from` is supposed to enable via a bounded ExecutorService provided by the user.

**Comment by davidmoten** [comment]
@akarnokd ok, that's as I understood it too. The possibility of a high thread count is something the user needs to be aware of and it's documented already.

**Comment by yhartanto** [comment]
> @ChrisFrancis @yhartanto I'm happy to help review as well (in external project or whatever).

Sounds good, we will share with you as soon as it is in a decent shape.

**Comment by akarnokd** [comment]
I'm closing this as currently it does not affect RxJava. Post a comment here once your implementation is ready for review.
