### ISSUE TITLE
Timeout on Completable.merge doesn't unsubscribe child completables

### ISSUE THREAD

**Issue by mahmoudhanafy** [ReactiveX/RxJava#6400]
I'm using the latest version `1.3.8`. You can regenerate this bug using the following code:
```java
import rx.Completable;
import rx.Observable;
import rx.functions.Func1;
import rx.schedulers.Schedulers;

import java.util.concurrent.TimeUnit;

public class TestObservables {

    public static void main(String[] args) throws InterruptedException {
        Observable<Completable> completables = rx.Observable.range(1, 5).map(new Func1<Integer, Completable>() {

            @Override
            public Completable call(Integer integer) {
                return Completable.fromAction(() -> {
                    try {
                        System.out.println("Local Started");
                        Thread.sleep(3 * 1000);
                        System.out.println("Local Completed");
                    } catch (InterruptedException e) {
                        e.printStackTrace();
                    }
                }).subscribeOn(Schedulers.io()).observeOn(Schedulers.computation())
                  .doOnUnsubscribe(() -> System.out.println("Local Unsubscribed"))
                  .doOnSubscribe(subscription -> System.out.println("Local Subscribed"));
            }
        });

        Completable globalCompletable = Completable.merge(completables, 10)
                .doOnUnsubscribe(() -> System.out.println("Global Unsubscribed")).timeout(1, TimeUnit.SECONDS);

        try {
            globalCompletable.await();
        } catch (Exception e) {
            System.out.println("Global Thread timeout: " + e);
        }

//        Thread.sleep(20 * 1000);
    }
}
```
You can see that when the timeout occur, only the global completable unsubscribe but all child completables still running. The output is:

> Local Subscribed
> Local Subscribed
> Local Started
> Local Subscribed
> Local Started
> Local Subscribed
> Local Started
> Local Subscribed
> Local Started
> Local Started
> Global Unsubscribed
> Global Thread timeout: java.lang.RuntimeException: java.util.concurrent.TimeoutException
> 

if you uncomment the sleep line at the end. you can see the completables will continue to complete. in our case we wanted to kill all completables when timeout occur, but they keep running the background and cause problems.
Output if you comment the sleep line:

> Local Subscribed
> Local Subscribed
> Local Started
> Local Subscribed
> Local Started
> Local Subscribed
> Local Started
> Local Subscribed
> Local Started
> Local Started
> Global Unsubscribed
> Global Thread timeout: java.lang.RuntimeException: java.util.concurrent.TimeoutException
> Local Completed
> Local Completed
> Local Completed
> Local Completed
> Local Completed
> Local Unsubscribed
> Local Unsubscribed
> Local Unsubscribed
> Local Unsubscribed
> Local Unsubscribed
>

**Comment by akarnokd** [comment]
Hello. RxJava 1 is no longer supported or maintained.

> if you uncomment the sleep line at the end. you can see the completables will continue to complete

It may take some time the unsubscribe is propagated to all currently running completables. If you don't wait, your app quits and tasks on daemon threads should be stopped, never executing their remaining work as per standard Java behavior.

**Comment by mahmoudhanafy** [comment]
@akarnokd thank you for the quick reply. yes I figured out that it's not maintained any more :cry: 

> It may take some time the unsubscribe is propagated to all currently running completables. If you don't wait, your app quits and tasks on daemon threads should be stopped, never executing their remaining work as per standard Java behavior.


if you increase the child completable sleep time for ex. to be 100 seconds. You can see that it will not unsubscribe even if you wait for 99 seconds after the merged completable timeout occurs.

Also I tested `merge(Completable... sources)` and `merge(Iterable<? extends Completable> sources)` they both work as expected. I think the only problem is with `merge(Observable<? extends Completable> sources)`.

**Comment by akarnokd** [comment]
Seems to be working with 2.x:

```java
import java.util.concurrent.TimeUnit;

import io.reactivex.*;
import io.reactivex.schedulers.Schedulers;

public class MergeCompletablesTest {
    public static void main(String[] args) throws InterruptedException {
        Observable<Completable> completables = Observable.range(1, 5).map(integer -> {

                return Completable.fromAction(() -> {
                    try {
                        System.out.println("Local Started");
                        Thread.sleep(3 * 1000);
                        System.out.println("Local Completed");
                    } catch (InterruptedException e) {
                        e.printStackTrace();
                    }
                }).subscribeOn(Schedulers.io()).observeOn(Schedulers.computation())
                  .doOnDispose(() -> System.out.println("Local Unsubscribed: " + integer))
                  .doOnSubscribe(subscription -> System.out.println("Local Subscribed: " + integer));
        });

        Completable globalCompletable = Completable.merge(completables.toFlowable(BackpressureStrategy.MISSING), 10)
                .doOnDispose(() -> System.out.println("Global Unsubscribed")).timeout(1, TimeUnit.SECONDS);

        try {
            globalCompletable.blockingGet();
        } catch (Exception e) {
            System.out.println("Global Thread timeout: " + e);
        }

        Thread.sleep(20 * 1000);
    }
}
```

> if you increase the child completable sleep time for ex. to be 100 seconds. You can see that it will not unsubscribe even if you wait for 99 seconds after the merged completable timeout occurs.

This could be a bug in 1.x but 1.x is no longer supported, thus I can't help you with that.
