### ISSUE TITLE
[2.x] - Question - Flowable.intervalRange().subcribeOn behavior

### ISSUE THREAD

**Issue by damianofontana85** [ReactiveX/RxJava#6401]
Hi,
I have encountered a strange behavior when combining Flowable.intervalRange with subscribeOn.
I have noticed that the sequence generated by Flowable.intervalRange starts to be produced by a thread from RxComputationThreadPool (as expected) but sometimes it switches to the thread of the scheduler set by subcribeOn and after a while goes back to the original thread.

My example code of this behavior:

          
```java
TestSubscriber<String> subscriber = new TestSubscriber<>();

Flowable.intervalRange(1,4000,0,1,TimeUnit.NANOSECONDS)
        .onBackpressureBuffer()
        .subscribeOn(Schedulers.newThread())
        .map( value -> Thread.currentThread().getName())
        .distinct()
        .subscribe(subscriber);

subscriber.awaitTerminalEvent();
subscriber.assertComplete();
assertEquals(1, subscriber.valueCount());
```

So my guestion is, is this the desired behaviour?

**Comment by akarnokd** [comment]
This is a legal behavior. Using `subscribeOn` with `intervalRange` has no practical effect as `intervalRange` generates items on the computation scheduler by default and has no subscription side-effect to be moved elsewhere by `subscribeOn`. In addition, you are using `onBackpressureBuffer` which may push through an item from the sender thread (computation) or buffer and get replayed by the requestor thread, which in this case is driven by `subscribeOn` and happens on the new thread worker.

Please in the future, ask such questions on StackOverflow.
