### ISSUE TITLE
Proposal: new .retryWithResettableLimit( int consecutiveErrorLimit ) operator 

### ISSUE THREAD

**Issue by RobLewis** [ReactiveX/RxJava#6403]
Often when dealing with things like wireless connections, you get one or a few failures in a row before the connection recovers. 

It would be convenient to be able to retry these operations up to a set number of times before giving up, and reset the "consecutive errors" count when a successful emission is received. 

I've attempted to implement this as a composable `ObservableTransformer` but it might be a nice addition to the standard RxJava operator toolkit. 

```
// usage (in an operator chain)
//     .compose( new RetryLimiter( 10 ) )

public class RetryLimiter implements ObservableTransformer {
    
    private int errorCount = 0;
    private int maxErrorCount;
    
    // constructor passes max tolerated consecutive errors (count is rezeroed upon a successful emission)
    public RetryLimiter( int maxErrors ) {
        maxErrorCount = maxErrors;
    }
    
    @Override
    @SuppressWarnings("unchecked")  // this has nothing to do with the type of the Observable emissions
    public ObservableSource apply( Observable upstream ) {
        return upstream
                .doOnError( err -> errorCount++ )
                .doOnNext( next -> errorCount = 0 )
                .retryUntil( () -> errorCount > maxErrorCount );
    }
}
```

Additional features may be possible, such as providing a list of the types of exceptions to be considered when counting errors.

**Comment by akarnokd** [comment]
This operator and behavior is too peculiar to be included in RxJava proper and there are libraries offering [retry builders](https://github.com/davidmoten/rxjava2-extras#retrywhen).
