### ISSUE TITLE
2.x: SchedulerWhen increases thread num continuously

### ISSUE THREAD

**Issue by suribada** [ReactiveX/RxJava#6406]
Hello. I tested at RxJava 2.2.6.
I compared `Observable.flatMap(mapper, maxConcurrency)` with `Scheduler.when(maxCocurrentScheduler)`, and I saw a little subtle results.
When I use `Schedulers.io()`, I expected that `Scheduler.when(maxCocurrentScheduler)` uses only RxCachedThreadScheduler-1~RxCachedThreadScheduler-20 like `flatMap(mapper, maxConcurrency)`.
But `Schduler.when(maxCocurrentScheduler)` increases the thread number continuously and garbage collects often.
Is this a expected result? I think that a worker should return to worker pool when each observable stream completes.

```java
    public void takeProfilesFlatMap() {
        getMembers().subscribeOn(Schedulers.io())
                .flatMap(member -> getProfile(member).subscribeOn(Schedulers.io()), 20) // (1)
                .doOnEach(profile -> System.out.println(Thread.currentThread().getName() + ":" + profile.toString()))
                .observeOn(AndroidSchedulers.mainThread())
                .subscribe(System.out::println);
    }

    public void takeProfilesSchdulerWhen() {
        Scheduler maxConcurrentScheduler = getMaxConcurrentScheduler(); // (1)
        getMembers().subscribeOn(maxConcurrentScheduler)
                .doOnEach(System.out::println)
                .flatMap(member -> getProfile(member).subscribeOn(maxConcurrentScheduler)) // (2)
                .doOnEach(profile -> System.out.println(Thread.currentThread().getName() + ":" + profile.toString()))
                .observeOn(AndroidSchedulers.mainThread())
                .subscribe(System.out::println);
    }

    private Observable<Member> getMembers() {
        return Observable.range(1, 10000)
                .map(value -> new Member("David " + value));
    }

    private Observable<Member> getAnotherMembers() {
        return Observable.range(201, 200)
                .map(value -> new Member("David " + value));

    }

    private Observable<Profile> getProfile(Member member) {
        return Observable.create(emitter -> {
            SystemClock.sleep(2000);
            emitter.onNext(new Profile(member));
            emitter.onComplete();
        });
    }

    private Scheduler getMaxConcurrentScheduler() {
        return Schedulers.io().when(workerActions -> {
            Flowable<Completable> workers = workerActions.map(actions -> Completable.concat(actions));
            return Completable.merge(workers, 20);
        });
    }
```

02-14 05:24:23.374 I/System.out( 6630): name=David 1374
02-14 05:24:23.664 I/System.out( 6630): RxCachedThreadScheduler-1376:OnNextNotification[name=David 1375]
02-14 05:24:23.674 I/System.out( 6630): name=David 1375
02-14 05:24:24.014 I/System.out( 6630): RxCachedThreadScheduler-1377:OnNextNotification[name=David 1376]
02-14 05:24:24.014 I/System.out( 6630): name=David 1376
02-14 05:24:24.494 D/dalvikvm( 6630): GC_FOR_ALLOC freed 6296K, 31% free 22120K/31780K, paused 99ms, total 99ms
02-14 05:24:25.224 I/System.out( 6630): RxCachedThreadScheduler-1378:OnNextNotification[name=David 1377]
02-14 05:24:25.224 I/System.out( 6630): name=David 1377
02-14 05:24:25.344 I/System.out( 6630): RxCachedThreadScheduler-1379:OnNextNotification[name=David 1378]
02-14 05:24:25.344 I/System.out( 6630): name=David 1378
02-14 05:24:25.514 I/System.out( 6630): RxCachedThreadScheduler-
....
1394:OnNextNotification[name=David 1393]
02-14 05:24:31.744 I/System.out( 6630): name=David 1393
02-14 05:24:31.804 I/System.out( 6630): RxCachedThreadScheduler-1395:OnNextNotification[name=David 1394]
02-14 05:24:31.814 I/System.out( 6630): name=David 1394
02-14 05:24:31.874 I/System.out( 6630): RxCachedThreadScheduler-1395:OnNextNotification[name=David 1395]
02-14 05:24:31.884 I/System.out( 6630): name=David 1395
02-14 05:24:32.134 I/System.out( 6630): name=David 1396
02-14 05:24:32.134 I/System.out( 6630): RxCachedThreadScheduler-1397:OnNextNotification[name=David 1396]
02-14 05:24:32.894 D/DeviceforDRMService( 1190): handleMessage TIMEOUT_CHECK  mServiceState:1
02-14 05:24:33.664 I/System.out( 6630): RxCachedThreadScheduler-1398:OnNextNotification[name=David 1397]
02-14 05:24:33.674 I/System.out( 6630): name=David 1397
02-14 05:24:33.824 I/System.out( 6630): RxCachedThreadScheduler-1399:OnNextNotification[name=David 1398]
02-14 05:24:33.824 I/System.out( 6630): name=David 1398
02-14 05:24:33.864 I/System.out( 6630): RxCachedThreadScheduler-1399:OnNextNotification[name=David 1399]
02-14 05:24:33.864 I/System.out( 6630): name=David 1399
02-14 05:24:33.964 I/System.out( 6630): RxCachedThreadScheduler-1399:OnNextNotification[name=David 1400]
02-14 05:24:33.964 I/System.out( 6630): name=David 1400
02-14 05:24:34.204 I/System.out( 6630): RxCachedThreadScheduler-1402:OnNextNotification[name=David 1401]
02-14 05:24:34.204 I/System.out( 6630): name=David 1401
02-14 05:24:34.974 D/dalvikvm( 6630): GC_FOR_ALLOC freed 6293K, 31% free 22107K/31780K, paused 234ms, total 234ms
02-14 05:24:35.304 D/Ulp_jni ( 1190): Location CB invoked
02-14 05:24:35.744 I/System.out( 6630): name=David 1402
02-14 05:24:35.744 I/System.out( 6630): RxCachedThreadScheduler-1403:OnNextNotification[name=David 1402]
02-14 05:24:35.884 I/System.out( 6630): RxCachedThreadScheduler-1404:OnNextNotification[name=David 1403]

**Comment by akarnokd** [comment]
This operator is a complete mystery to me. Based on its [Javadocs](http://reactivex.io/RxJava/2.x/javadoc/io/reactivex/Scheduler.html#when-io.reactivex.functions.Function-), I'd say try `Completable.merge` instead of `Completable.concat`.
