### ISSUE TITLE
2.x: Question: Schedulers.io(RxCachedThreadScheduler) changed to Schedulers.computation(RxComputationThreadPool) in subscribe block

### ISSUE THREAD

**Issue by moltak** [ReactiveX/RxJava#6407]
Hi I am testing on RxJava 2.2.6.

I tested with `combineLatest` and `subscribeOn`. I wanted to see which thread the code block works on. I guessed `combineLatest` and `subscribe` block work on `Schedulers.io(RxCachedThread)`. But sometimes `subscribe` block works on `Schdulers.computation(RxComputationThreadPool)`. How does this happen?

```kotlin
 Observable.combineLatest(
        Observable.just("o1"),
        Observable.just("o2"),
        BiFunction<String, String, String> { _, _ -> Thread.currentThread().name }
    )
        .subscribeOn(Schedulers.io())
        .subscribe {
            println("With subscribeOn")
            println("in combineLatest: $it")
            println("in subscribe: ${Thread.currentThread().name}")
        }
```

Sometimes it prints like the below. But I don't know the condition.
```
With subscribeOn
in combineLatest: RxCachedThreadScheduler-1
in subscribe: RxComputationThreadPool-1
```

Normal output
```
With subscribeOn
in combineLatest: RxCachedThreadScheduler-1
in subscribe: RxCachedThreadScheduler-1
```

**Comment by akarnokd** [comment]
That doesn't seem to be a practically possible with the given example. Some operators default to the computation scheduler and subscribeOn is not the way to ensure where events are observed. The javadocs indicates the former.
