### ISSUE TITLE
2.X Question: buffer(...) boundary supplier triggers differently for the first event. 

### ISSUE THREAD

**Issue by yklymenko** [ReactiveX/RxJava#6410]
RXJava 2.2.3

I've used following code to split the stream based on data separator (#) to chunks

        Observable<String> source = Observable.fromArray(
                "a", "b", "#",
                "c", "d", "e", "#",
                "f", "g");

        source.publish(p ->
                p.buffer(() -> p.filter("#"::equals)))
                .subscribe(System.out::println);

So what I expected to see is:
Either
["a", "b", "#",]
["c", "d", "e", "#",]
["f", "g"]

or
["a", "b",]
["#", "c", "d", "e"]
["#", "f", "g"]

depending on how the selector close the boundary. 

But it returns currently: 
[a, b]
[#, c, d, e, #]
[f, g]

this is not very symmetrical :-) and I ask me, if this behavior is desired.

**Comment by akarnokd** [comment]
Hi. The boundary gets resubscribed which makes the triggering order change. There are dedicated [extension operators](https://github.com/akarnokd/RxJava2Extensions#flowabletransformersbufferwhile) for your expected cases.
