### ISSUE TITLE
Can you provide Chinese documents?

### ISSUE THREAD

**Issue by 237chenhao** [ReactiveX/RxJava#6411]
我很想在我的项目里使用RxJava,能提供一下中文文档吗?
I really want to use RxJava in my project. Can I provide Chinese documentation?

**Comment by akarnokd** [comment]
Unlikely. I know the **Reactive Programming with RxJava (Tomasz Nurkiewicz)** book is [being translated by this person](https://www.linkedin.com/in/%E5%8D%AB%E6%BB%A8-%E5%BC%A0-7a15976a/?midToken=AQEzoM1bE-HvtQ&trk=eml-email_m2m_invite_reminder_02-hero-4-profile_text&trkEmail=eml-email_m2m_invite_reminder_02-hero-4-profile_text-null-58c24t~jqoszdq4~9a-null-neptune%2Fprofile~vanity%2Eview) and my blog had also translations done by [someone](https://plus.google.com/u/0/+%E8%A8%B1%E5%BB%BA%E6%9E%97?cfem=1). Also there was [someone](https://plus.google.com/105348971047441745821) from InfoQ China ready to translate too.

**Comment by 237chenhao** [comment]
@akarnokd 谢谢你的回答.Thank you for your answer.
