### ISSUE TITLE
Flowable(or Observable) is blocked when thread pool executor throws RejectedExecutionException

### ISSUE THREAD

**Issue by mshabunin77** [ReactiveX/RxJava#6413]
Hello,

I just started using javarx2(version 2.2.6) and faced the next issue(or not, but it would be good to know what I'm doing not right): Flowable or observable is blocked forever on every blocking operation like blockingFirst or blockingSubscribe when Scheduler throws RejectedExecutionException.
Here is slightly modified example from your README that reproduce the issue:

```java
ThreadPoolExecutor executor = new ThreadPoolExecutor(1, 1,
        10, TimeUnit.MINUTES, new LinkedBlockingQueue<>(1));
try {
    Scheduler scheduler = Schedulers.from(executor);
    Flowable.range(1, 10)
           .flatMap(v ->
                    Flowable.just(v)
                            .subscribeOn(scheduler)
                            .map(w -> w * w)
            )
            .blockingSubscribe(System.out::println, System.err::println);
} finally {
    executor.shutdown();
}
```

So it would be good to know how to deal with the situation when executor throws RejectedExecutionException.

Thank you.
Max.

**Comment by akarnokd** [comment]
It's not possible to handle this case from within RxJava. Operators try to schedule emissions/processing and if it is rejected, we can't do anything about it. Signaling onError may run concurrently with existing emissions running on the scheduler in the chain and thus violate the protocol requirements or thread expectations. Don't shut down an executor before stopping flows that depend on it.

**Comment by mshabunin77** [comment]
Hm, interesting - I tried this scenario with javarx1 and everything is working - I'm getting onError event that I can handle. 

So what do you mean by 'violating protocol requirements or thread expectation'? 
Do you mean that onError will have to use the same executor(or specified in observeOn method) that also may reject?  
In that case I would rethrow rejection exception from observable rather than blocking it, or at least gave the possibility to configure such behaviour. IMHO from thread expectation perspective it's more fair not to hide rejection exception especially when the result is blocking thread.

Solving this may help in cases like this: imagine we have a service with limited thread pool for handling incoming requests and a simple circuit breaker to call another service. This circuit breaker is implemented by rejecting tasks in separate thread pool when the queue is bigger than some threshold or the waiting time in queue exceeded timeout value. In this situation we quickly run out of threads on our service because of this blocking situation and entire service will be down.
I know that hystrix uses similar approach with javarx1. 

Also RejectedExecutionException is valid exception that may be thrown from executors - this fact makes it dangerous to use(or switch to) different executors while using blocking method. 

At my work many developers use javarx1 (mostly simple cases - Single's returned from feign-hystrix and combined by zip or merge) and I was looking at possibility to upgrade to newer stack like resilience4j and javarx2. 
So dealing with this issue would be really helpful and more details would be really appreciated.

Thank you.
Max.

PS. About executor#shutdown - sorry that I included it in my example, it's irrelevant to this situation and by the way it's doing what is expected - every observable emit single event and then blockingSubscribe waiting for completion. After this executor can be shut down.

**Comment by akarnokd** [comment]
> I'm getting onError event that I can handle.
That was an invalid behavior in RxJava 1. RxJava 1 is no longer supported.

> Do you mean that onError will have to use the same executor(or specified in observeOn method) that also may reject?
Among other things, yes.

> In that case I would rethrow rejection exception from observable rather than blocking it,
Doesn't work. The flow execution is generally disconnected from the location you are blocking. Also if it were to throw, you lost the flow entirely so no way to retry.

> This circuit breaker is implemented by rejecting tasks in separate thread pool when the queue is bigger than some threshold or the waiting time in queue exceeded timeout value.
This undermines the fundamental expectation that a scheduler can run tasks when the flow is not disposed. Bounded-queue executors will most likely deadlock the flow anyway. Use backpressure and maxConcurrency settings instead.

> while using blocking method
There is rarely any reason to block.

**Comment by svishnyakoff** [comment]
We faced a similar issue in production when under high load we got the **entire system stuck**. In our case we tried to isolate rxJava logic in a single class without exposing rxJava type outside, thus had to use blocking operation. 

Right now the library silently ignores `subscribe` operation when we got out of threads, that leads to some kind of deadlock. As a user, if I had to choose to ignore lack of threads error and thus get deadlock or got notified in the current thread about error in `onError` method (but violate thread expectations), I would choose the second option, though it is quite subjective

Blocking operations are perfectly legitimate to use based on the existing API, or at least I have not seen any javadoc discouraging that nor @Depracated annotation. It is very scaring to see that existing API consider the possiblity of deadlock situations which usually occur under high load, and we not going to provide some generic solution that would fix it or at least make it fail fast

Example of the code which wait forever
```java
ThreadPoolExecutor executor = new ThreadPoolExecutor(0, 5, 60L, TimeUnit.SECONDS, new SynchronousQueue<Runnable>());

        Observable.range(1, 100)
                .flatMap(index -> Observable.just(index)
                        .map(i -> {
                            TimeUnit.SECONDS.sleep(5);
                            return i;
                        })
                        .subscribeOn(Schedulers.from(executor))
                )
                .toList()
                .blockingGet();
```

**Comment by akarnokd** [comment]
Again, we can't handle this type of resource exhaustion from within RxJava. Avoid blocking and limit concurrency to a level that your entire application is comfortable with.

**Comment by ashwing** [comment]
This is an issue even for non blocking subscribe. In our application we have seen the subscribe call failing silently making the application to get stuck and onNexct calls failing silently causing data loss issues. At bare minimum we expect the execute() exceptions like RejectedExecutionException to be propagated back to the caller thread so that we can catch the exception and take appropriate action.
