### ISSUE TITLE
RxJava2.1.0 : PublishSubject onNext not invoked when subscribed on different threads 

### ISSUE THREAD

**Issue by londonCyclist** [ReactiveX/RxJava#6415]
It is found that when subscribing to a serialized PublishSubject within 10-20 ms of invoking onNext events on the Subjects; the new subscriber's onNext is not invoked.

In the code snippet below; the value to observe[1] is given as "2000" and subscribeToSubject() is invoked after calling onNext() on the Subject with the value 1998 [2]; we see that if the interval is 10ms the new subscribers will miss the value 2000 being fired by the Subject; Whereas, if the interval is 50ms or greater then the new subscribers seems to receive the expected values; Is this an expected behavior?

// Update substituting BehaviourSubject will yield the exact same result.

```
public class PublishSubjectTest {

    private final Subject<String> singlePropertyUpdateSubject =
            PublishSubject.<String>create().toSerialized();


    public static void main(String[] args) {
        PublishSubjectTest obj= new PublishSubjectTest();
        obj.sendEvents();
        try {
            Thread.currentThread().join();
        } catch (InterruptedException e) {
            e.printStackTrace();
        }

    }


//[1]
    private final String valueToObserve = "2000";
    private void subscribeToSubject() {
        System.out.println("Subscribing .....");
        io.reactivex.Observable.range(1,10).subscribeOn(Schedulers.newThread()).subscribe(
                value -> getAndObserve(valueToObserve).subscribe(observedValue -> System.out.println("  Value Received   "+observedValue +" By "+Thread.currentThread() ))
        );



    }

    private io.reactivex.Observable<String> getAndObserve(String value) {
        final io.reactivex.Observable<String> observable = singlePropertyUpdateSubject
                //.doOnNext(v-> System.out.println("Received value "+v))
                .filter(v -> v.equals(value))
                .doOnSubscribe(c-> System.out.println("Consumer subscribed "+c));
        return observable;
    }


// 50ms >= expected result ;  Anything less than 10ms will fail.
    private void sendEvents() {
        io.reactivex.Observable.interval(10, TimeUnit.MILLISECONDS).subscribe(value -> {
            String key = value.toString();
            //System.out.println("Adding key "+key);
            singlePropertyUpdateSubject.onNext(key);
//[2]           
 if (value == 1998){
                subscribeToSubject();;
            }
            if (value%100==0) {
                System.out.println(value);
            }
            if (key.equals(valueToObserve)){
                System.exit(1);
            }
        });
    }
```

Yes. You are racing the `onNext` with the `subscribe` and thus it is not guaranteed you have a subscription when an item is emitted. Subscribe first, emit later or use `BehaviorSubject`/`ReplaySubject` to remember the very last or all elements respectively.

_Originally posted by @akarnokd in https://github.com/ReactiveX/RxJava/issues/6414#issuecomment-465350811_

I'm reopening it, as substituting BehaviourSubject makes no difference to the above code, something else is happening.

**Comment by akarnokd** [comment]
Please do not post duplicates but respond on the original thread.
