### ISSUE TITLE
RxJava 2 - Group by with predicate

### ISSUE THREAD

**Issue by DareUrDream** [ReactiveX/RxJava#6419]
Hi,

Is it possible to say that a group is complete based on a predicate function or some other function that gets evaluate for each row ?

Cheers !!
DareUrDream

**Comment by akarnokd** [comment]
Spray and pray? https://github.com/reactor/reactor-core/issues/1543

Please take some time while you browse through the available operators until a suitable match comes up.

**Comment by DareUrDream** [comment]
???

**Comment by DareUrDream** [comment]
@akarnokd I don't see an effective solution which can either cumulatively evaluate the data or take each data set and apply a predicate while grouping to see if the group can be closed ... And hence the question..

BTW, I am evaluating libraries to see the best for my use-cases

**Comment by akarnokd** [comment]
@DareUrDream You have received a very good response on the [Reactor forum](https://github.com/reactor/reactor-core/issues/1543#issuecomment-466957146). Please respond there.
Also note that we RxJava and Reactor are sibling libraries, therefore, most problems have the same solutions with both libraries.

**Comment by DareUrDream** [comment]
Sure Thanks !!

BTW how would you do that in Rx... It would be nice to see a sample...Sharing my use-case for your inputs and suggestions

What I am trying to achieve is to group a certain set of objects from a hot streaming source and then when the group has all the needed objects (want to determine that based on the condition evaluated with each data object) send the group downward for processing...In my case the number of objects in a group and number of groups can range from 1 to n.

Cheers !!
DareUrDream
