### ISSUE TITLE
AtomicReference Disposable**Observers

### ISSUE THREAD

**Issue by lxsmnsyc** [ReactiveX/RxJava#6422]
https://github.com/ReactiveX/RxJava/blob/9a74adf5f85ebfe5063e8191665956d547d515e0/src/main/java/io/reactivex/observers/DisposableSingleObserver.java#L56

Based on the operator implementations such as this one: https://github.com/ReactiveX/RxJava/blob/9a74adf5f85ebfe5063e8191665956d547d515e0/src/main/java/io/reactivex/internal/operators/single/SingleFlatMap.java#L39

Why aren't the Disposable**Observer classes not an AtomicReference themselves? but instead, you create an AtomicReference for a Disposable instance?

**Comment by akarnokd** [comment]
There is a decision to make when extending an Atomic X class: what atomic access is more frequent that could benefit from not having to go through an indirection. Sometimes there is no clear winner, hence having one of the subscription/disposable in an `AtomicReference` and the rest in instance references. Sometimes, especially in trampolines, the work-in-progress counter is accessed predominantly, thus extending `AtomicInteger` is beneficial.

**Comment by JakeWharton** [comment]
Doing so would also expose internal state allowing anyone to perform
mutative actions on it in ways that were unexpected. Strong encapsulation
is worth it for public API.

**Comment by lxsmnsyc** [comment]
That's what I thought at first, since if the Disposable**Observers are an AtomicReference themselves, AtomicReference methods are exposed for use.

**Comment by akarnokd** [comment]
How? You don't intetact with the internals and/or you'd have to cast them to the appropriate type back. Or just use reflection and wreak havoc anyway as we don't have the extra level of isolation offered by a module system.
