### ISSUE TITLE
RxJava 2: Is it possible to group and read the elments in a Flowable ?

### ISSUE THREAD

**Issue by DareUrDream** [ReactiveX/RxJava#6424]
Is it possible to group and read the elements in a Flowable ? In my use-case I would like to group elements coming into the system by a group id. Then I would like to write custom logic to read the elements in the group to determine if the group is complete for subscriber to consume. 

Cheers !!

**Comment by akarnokd** [comment]
Please stop cross posting here and on [StackOverflow](https://stackoverflow.com/questions/54927426/is-it-possible-to-group-and-read-the-elments-in-a-flowable).

Given the minimal number of maintainers remaining, this issue list is for reporting bugs, discussing/requesting features or discussing the deep internals of RxJava' design and architecture. Any question about "How do I X in RxJava" is more suited for StackOverflow.
