### ISSUE TITLE
[Enhancement] Support kotlin coroutines like Backpressure in java.

### ISSUE THREAD

**Issue by Guang1234567** [ReactiveX/RxJava#6426]
Hello dev:

I find the [backpressure](
https://github.com/Kotlin/kotlinx.coroutines/blob/master/reactive/coroutines-guide-reactive.md#backpressure) of [kotlinx-coroutines-rx2](
https://github.com/Kotlin/kotlinx.coroutines/blob/master/reactive/coroutines-guide-reactive.md#backpressure) maybe more natural. 

Could you support it in rxjava without kotlin? Thx.

>  Coroutines can suspend and they provide a natural answer to handling backpressure.

**Comment by akarnokd** [comment]
It is impossible as coroutines are the language and compiler feature of Kotlin and there is nothing equivalent in Java at the moment. Project Loom is far away and would require a future Java version Android folks may never get.
