### ISSUE TITLE
 Suggest to provide no-image javadoc.

### ISSUE THREAD

**Issue by SmallYuuu** [ReactiveX/RxJava#6427]
When I import rxjava lib and try to associate code, the Android studio is freezing. And I try to disconnect my network. And everything is OK. I guess downloading image block Android Studio process(Maybe I should create an issue for Google Developer Team). Can you publish a no-img version rxjava-sources.jar?

Freezing on "Fetching Documentation"
![2019-03-07 11-32-14](https://user-images.githubusercontent.com/10010149/53930705-487aee00-40cd-11e9-8fd1-25fa58e7c47a.png)

**Comment by akarnokd** [comment]
No. That would require a lot of complications. Please open a ticket with the IDE vendor.
