### ISSUE TITLE
flatMaps would override initial subscribeOn Thread

### ISSUE THREAD

**Issue by bhuvangu** [ReactiveX/RxJava#6428]
Important thing to note though, that if Observables inside flatMap would subscribe on some other thread, then these flatMaps would override initial thread. E.g.:

```
    public void main() {
        Observable.just(1)
                  .subscribeOn(scheduler.io())
                  .observeOn(scheduler.io())
                  .doOnNext(this::printThread) // IO
                  .flatMap(i -> single(i))
                  .subscribe(this::printThread // UI
                             , throwable -> {});
    }

    public Observable<Integer> single(int i) {
        return Observable.just(i + 1)
                         .subscribeOn(scheduler.ui());
    }

```

_Originally posted by @soshial in https://github.com/ReactiveX/RxJava/issues/2925#issuecomment-427839128_

Why is that .. uptill now i was assuming that flatmap is like chaining the executable code blocks.. but this behaviour breaks that mind model .. so what exactly does the flatmap do

**Comment by akarnokd** [comment]
Coordinating operators use the threads they interact with. Use `observeOn` to ensure the observation is routed to the expected thread.

**Comment by bhuvangu** [comment]
Your explanation is very way over me.. can you please explain so that a newbie like me can understand and build a mind model.

**Comment by akarnokd** [comment]
It is complicated. I suggest you read about `observeOn`.
