### ISSUE TITLE
Can I use .observeOn(Schedulers.newThread("read-thread"))， .observeOn(Schedulers.newThread("write-thread")) to appoint two thread to read and write?i hope i can do this

### ISSUE THREAD

**Issue by wrrgit** [ReactiveX/RxJava#6440]
Can I use .observeOn(Schedulers.newThread("read-thread"))， .observeOn(Schedulers.newThread("write-thread")) to appoint two thread to read and write?i hope i can do this. when "read-thread" is not available ,it will be created,otherwise , use "read-thread" that available.

**Comment by wrrgit** [comment]
Can I use .observeOn(Schedulers.newThread("read-thread"))， .observeOn(Schedulers.newThread("write-thread")) to appoint two thread to read and write?i hope i can do this. when "read-thread" is not available ,it will be created,otherwise , use "read-thread" that available.

**Comment by akarnokd** [comment]
No. Consider using `Schedulers.from` with a ExecutorService configured as you see fit.
