### ISSUE TITLE
2.x: Performance: Lock-free potential improvement

### ISSUE THREAD

**Issue by fadi-botros** [ReactiveX/RxJava#6443]
https://github.com/ReactiveX/RxJava/blob/2.x/src/main/java/io/reactivex/subjects/SingleSubject.java#L98

```java
final AtomicReference<SingleDisposable<T>[]> observers;
```

Putting observers in an array which would be changed as a reference may have another more effecient way, which is the use of Java's `ConcurrentLinkedList` or any other lock-free data structure (Like for example the Mpsc Queue which is already included in this repo if it is guaranteed that the consumer would be single).

This would be applied to all the implementors of `Subject<T>`. This issue exists in at least most of the Subject implementations inside this repo.

**Comment by akarnokd** [comment]
We already use lock free data structures, namely a copy-on-write arrays, when managing the consumers of subjects. It is a tradeoff between add/remove cost and traversal cost and RxJava chose the latter. This aspect has been thoroughly explored when RxJava 2 was implemented more than two years ago.
