### ISSUE TITLE
Terminating app due to an uncaught exception 'java.lang.UnsupportedOperationException', reason: 'Exceeded maximum number of wifi locks'

### ISSUE THREAD

**Issue by KumariAnjuThakur** [ReactiveX/RxJava#6444]
Last Exception Backtrace
--
0 | io.reactivex.exceptions.OnErrorNotImplementedException: Exceeded maximum number of wifi locks
1 | at io.reactivex.internal.functions.Functions$ag.a(SourceFile:704)
2 | at io.reactivex.internal.functions.Functions$ag.accept(SourceFile:701)
3 | at io.reactivex.internal.observers.LambdaObserver.onError(SourceFile:77)
4 | at io.reactivex.internal.observers.LambdaObserver.onNext(SourceFile:67)
5 | at io.reactivex.internal.operators.observable.ObservableSubscribeOn$a.onNext(SourceFile:58)
6 | at io.reactivex.internal.operators.observable.ObservableObserveOn$a.b(SourceFile:200)
7 | at io.reactivex.internal.operators.observable.ObservableObserveOn$a.run(SourceFile:252)
8 | at io.reactivex.internal.schedulers.ScheduledRunnable.run(SourceFile:66)
9 | at io.reactivex.internal.schedulers.ScheduledRunnable.call(SourceFile:57)
10 | at java.util.concurrent.FutureTask.run(FutureTask.java:266)
11 | at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
12 | at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
13 | at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
14 | at java.lang.Thread.run(Thread.java:764)
15 | Caused by: java.lang.UnsupportedOperationException: Exceeded maximum number of wifi locks
16 | at android.net.wifi.WifiManager$MulticastLock.acquire(WifiManager.java:4910)
17 | at com.android.netgeargenie.utils.nsdpdiscovery.SendNSDPPacket.callBroadcast(SourceFile:88)
18 | at com.android.netgeargenie.control.ScanManagerControl$4.a(SourceFile:496)
19 | at com.android.netgeargenie.control.ScanManagerControl$4.accept(SourceFile:488)
20 | at io.reactivex.internal.observers.LambdaObserver.onNext(SourceFile:63)
21 | at io.reactivex.internal.operators.observable.ObservableSubscribeOn$a.onNext(SourceFile:58)
22 | at io.reactivex.internal.operators.observable.ObservableObserveOn$a.b(SourceFile:200)
23 | at io.reactivex.internal.operators.observable.ObservableObserveOn$a.run(SourceFile:252)
24 | at io.reactivex.internal.schedulers.ScheduledRunnable.run(SourceFile:66)
25 | at io.reactivex.internal.schedulers.ScheduledRunnable.call(SourceFile:57)
26 | at java.util.concurrent.FutureTask.run(FutureTask.java:266)
27 | at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
28 | at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
29 | at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
30 | at java.lang.Thread.run(Thread.java:764)

**Comment by akarnokd** [comment]
You did not implement an onError handler in your subscribe method and hence the crash.

Also, please do not post a "core dump" without any context or example what you were doing and please post Android related problems on StackOverflow. Thanks.
