### ISSUE TITLE
RxCachedThreadScheduler Thread stopped without Exception v.2.2.3

### ISSUE THREAD

**Issue by lon-wolf** [ReactiveX/RxJava#6445]
- [ ] I am using version : 'io.reactivex.rxjava2:rxjava:2.2.3'

  - [ ] Below is my code snippet for publisher and subscriber, I am using Schedulers.io()

  ```
@Component
public class ReactiveEventUtil {

    private final Subject<EntityEvent> subject;
    private final Observable<EntityEvent> observable;

    public ReactiveEventUtil() {
        this.subject = PublishSubject.create();
        this.observable = subject.observeOn(Schedulers.io());
    }

    /**
     * Subscribe consumers in Sync for particular event
     *
     * @param eventType
     * @param eventProcessor
     * @param <T>
     * @return ReactiveSubscription
     */
    public <T extends EntityEvent> ReactiveSubscription subscribe(Class<T> eventType, Consumer<T> eventProcessor) {
        Disposable disposable =
                observable
                        .filter(e -> e.getClass().equals(eventType))
                        .map(eventType::cast)
                        .subscribe(eventProcessor::accept);

        return new ReactiveSubscription(disposable);
    }

    /**
     * Publish event that will accordingly picked up by corresponding consumer
     *
     * @param event
     * @param <T>
     */
    public <T extends EntityEvent> void publish(T event) {
        subject.onNext(event);
    }

    @RequiredArgsConstructor(access = AccessLevel.PRIVATE)
    private static class ReactiveSubscription {
        private final Disposable disposable;

        public void cancel() {
            disposable.dispose();
        }

        public boolean isActive() {
            return !disposable.isDisposed();
        }
    }
}
```

 - [ ] Issue is one of the processor thread "RxCachedThreadScheduler-1" stopped working in middle of the function without throwing any exception. And it remained in stopped state until I restart my application. As I know if some unchecked exception is thrown via processor then RX displays following stacktrace:
  

> io.reactivex.exceptions.OnErrorNotImplementedException: The exception was not handled due to missing onError handler in the subscribe() method call. Further reading: https://github.com/ReactiveX/RxJava/wiki/Error-Handling | java.lang.RuntimeException: HELOO

- [ ] So this is clear that "RxCachedThreadScheduler-1" doesn't stopped because of any exception, neither my function seems to throw any exception.

- [ ] Is there any other reason which may leads to stop thread?

**Comment by akarnokd** [comment]
Running out of memory may lead to dead schedulers. What thread(s) are calling the `publish` method?

**Comment by lon-wolf** [comment]
I didn't see any Memory issue, heap used was around 60%. 
JMS thread called the publish method, and JMS thread completed successfully.

**Comment by akarnokd** [comment]
The code you provided should never hang on its own. My best guess is that `publish` is called from multiple threads but `PublishSubject` doesn't allow that. Do`PublishSubject.<EntityEvent>create().toSerialized();` and see if it still hangs/dies.

**Comment by lon-wolf** [comment]
I tried reproducing the same, but not able to make that happen again.
Always same thread ("RxCachedThreadScheduler-1") is linked to that particular event which results in sequential processing of all events, neither it seems to be multiple thread problem.
As I tried publishing events from different threads at the same time, but as only single thread ("RxCachedThreadScheduler-1") is processing all events, all events processed sequentially.

**Comment by akarnokd** [comment]
> As I tried publishing events from different threads at the same time

Do not call `PublishSubject.onNext` from multiple threads!

>  only single thread ("RxCachedThreadScheduler-1") is processing all events

If you have one subscriber in a flow, it gets a dedicated thread.

**Comment by lon-wolf** [comment]
> Do not call `PublishSubject.onNext` from multiple threads!

But this is what my application does.

> If you have one subscriber in a flow, it gets a dedicated thread.

Yeah I got this point.

Inside my processor I am using mongoTemplate, very rare chance that mongo blocked that RX thread permanently to get connection from pool, as it was blocked for 2 days need to check that way as well. But didn't find any problem from mongo side till yet.

**Comment by akarnokd** [comment]
> But this is what my application does.

Do not call `PublishSubject.onNext` from multiple threads!

http://reactivex.io/RxJava/javadoc/io/reactivex/subjects/PublishSubject.html
