### ISSUE TITLE
Image on comment make ide pretty slow

### ISSUE THREAD

**Issue by qtiuto** [ReactiveX/RxJava#6446]
To generate a image I never need on coding, Android Studio get totally blocked on main thread. And I must wait for it. Can you just place text on comments. Too many html comments are annoying.
Example:
/**
     * Converts an {@link Iterable} sequence into an ObservableSource that emits the items in the sequence.
     * <p>
     * <img width="640" height="186" src="https://raw.github.com/wiki/ReactiveX/RxJava/images/rx-operators/fromIterable.png" alt="">
     * <dl>
     *  <dt><b>Scheduler:</b></dt>
     *  <dd>{@code fromIterable} does not operate by default on a particular {@link Scheduler}.</dd>
     * </dl>
     *
     * @param source
     *            the source {@link Iterable} sequence
     * @param <T>
     *            the type of items in the {@link Iterable} sequence and the type of items to be emitted by the
     *            resulting ObservableSource
     * @return an Observable that emits each item in the source {@link Iterable} sequence
     * @see <a href="http://reactivex.io/documentation/operators/from.html">ReactiveX operators documentation: From</a>
     */
 
Github access is not as fast as you wish in my country, remove the <img> tag, ok?

**Comment by akarnokd** [comment]
Images are an integral part of the Javadoc, we can't just not generate it and still have the same maven artifact.
Besides, this is an issue with your IDE (they should know better not to block on the main thread) so please report it on their issue list.
