### ISSUE TITLE
Populating nested objects with Flowable.fromIterable

### ISSUE THREAD

**Issue by gbirk** [ReactiveX/RxJava#6449]
Code for reference: (https://gist.github.com/gbirk/cfd1c591a57c4db4ad5b4d81f338600f)

I have a list of UserRelease objects where each one of them contains a list of UserTrack objects. Using `Flowable.fromIterable()` I can iterate over the results of `fun getUserReleases(): Flowable<List<UserRelease>>` and fetch the UserTrack objects for each UserRelease by using `fun getUserTracksByReleaseId(releaseIds: List<Int>): Flowable<List<UserTrack>>`

When I first load the app and call `fun getCachedUserReleaseList(): Flowable<List<UserRelease>>` I'm receiving a full list of UserRelease objects each time a a UserRelease is being populated inside `Flowable.fromIterable()`, which is expected. But there is a way I can get only the latest item emitted without completing the flowable? I don't need to receive one item for each time I populate a UserRelease, I need only one item when all UserRelease objects are done being populated.

**Comment by akarnokd** [comment]
Questions such as "How do I X with RxJava?" are better suited for StackOverflow.
