### ISSUE TITLE
About Take Observeble Conditional and  Boolean Operators

### ISSUE THREAD

**Issue by killetom** [ReactiveX/RxJava#6450]
I think TakeUntil and TakeWhile，it should be blong to Filtering Observables.
Although it can be do a Conditional and Boolean Operators. 
It was look like Take Observables Conditional and Boolean to be combination.
For example RepeatWhen or RepeatUntil they just like Repeat Observables Conditional and Boolean to be combination.
So I think TakeUntil and TakeWhile not just belong to Conditional and Boolean Operators.
If I was wrong ,please tell me. Make me how to know was right.

**Comment by akarnokd** [comment]
Why? What categories are they in right now?

**Comment by killetom** [comment]
I think that shoulde be blong toObservable but ,it could be Observables Conditional and Boolean too

**Comment by akarnokd** [comment]
They are in the [conditional and boolean operators](https://github.com/ReactiveX/RxJava/wiki/Conditional-and-Boolean-Operators) category because they stop the sequence. Filtering assumes you still have things going on, even if some items were not relayed.
