### ISSUE TITLE
Add wait operator

### ISSUE THREAD

**Issue by derolf** [ReactiveX/RxJava#6454]
Add an operator that waits for completition of all of one or more flowables, but never emits anything.

Should be equivalent to ‘merge(...).filter((_) -> false)’.

**Comment by akarnokd** [comment]
Use `merge().ignoreElements()`.

**Comment by derolf** [comment]
Does the following work?

F.ignoreElements().startWith(...)

**Comment by akarnokd** [comment]
What do you want to achieve?

**Comment by derolf** [comment]
I have a bidi-streaming gRPC service using rx-gRPC.

The service receives an incoming Flowable and produces an outgoing Flowable. They are kind of independent (incoming publishes to MQTT, outgoing originates from MQTT subscriptions), but I need to couple the outgoing stream to the complete/error-signals of the incoming stream.

**Comment by akarnokd** [comment]
`ignoreElements()` returns [`Completable`](http://reactivex.io/RxJava/2.x/javadoc/io/reactivex/Completable.html) and that has the `andThen` method to continue with another flow.

**Comment by derolf** [comment]
I need `startWith` and not `andThen`...

EDIT: I just saw it also has `startWith`.

**Comment by akarnokd** [comment]
Please see the Javadoc for the available operators.
