### ISSUE TITLE
Subject not notified when using IO scheduler?

### ISSUE THREAD

**Issue by ivnsch** [ReactiveX/RxJava#6456]
In the following snippet:

```kotlin
val myObs = Observable.just(1)
val mySubject = PublishSubject.create<Int>()

mySubject
    .doOnNext { Log.d("mydebug", "called on next") }
    .subscribeOn(Schedulers.io())
    .doOnError { Log.d("mydebug", "error: $it") }
    .subscribe { Log.d("mydebug", "event: $it") }

myObs.subscribe(mySubject)
```

Expected behavior:
Observer is notified. The logs "called on next" and "event: $it" appear.

Actual behavior:
No logs. The observer seems to not be notified.

Notes:
Apparently the combination of using a subject and the IO scheduler causes this. Either removing`.subscribeOn(Schedulers.io())` or subscribing directly to `myObs` produces the expected behavior.

**Comment by akarnokd** [comment]
`subscribeOn` on a `Subject` has no practical effect. It moves the subscription to another thread and you drive the subject still from the main thread. There is a race and thus the `subscribe { Log.d("mydebug", "event: $it") }` may not happen in time to see the value from `myObs`. Use `ReplaySubject` or `UnicastSubject` to ensure a late subscriber still gets all events.
