### ISSUE TITLE
2.2.7: Flowable subscribeOn ignored in some circumstances

### ISSUE THREAD

**Issue by arkivanov** [ReactiveX/RxJava#6459]
Here is the code (Kotlin):
```
fun foo() {
    lateinit var subscription: Subscription

    Flowable
        .create<String>(
            { emitter ->
                emitter.onNext("1")
                emitter.onNext("2")
                emitter.onComplete()
            },
            BackpressureStrategy.BUFFER
        )
        .subscribeOn(Schedulers.io())
        .map {
            println("map, $it, ${Thread.currentThread().name}")
            it.length
        }
        .observeOn(AndroidSchedulers.mainThread(), false, 1)
        .subscribe(
            {
                Thread.sleep(20L)
                subscription.request(1L)
            },
            {},
            {},
            {
                subscription = it
                it.request(1L)
            }
        )
}
```

Actual output:
> 
map, 1, RxCachedThreadScheduler-1
map, 2, main

Expected output:
>
map, 1, main
map, 2, main

**Comment by akarnokd** [comment]
`subscribeOn` moves the execution of the `create` body to the `io` thread where it emits the items. Map still executes on that thread so the actual output is the correct one. Why did you expect main, main?

**Comment by arkivanov** [comment]
I expect same thread as in `create` body as there is no scheduler switching between `create` and `map`. Moreover I don't expect different threads. If you change `observeOn` to `.observeOn(AndroidSchedulers.mainThread())` then output is main, main.

**Comment by akarnokd** [comment]
You are a bit confused by the operators. Please read any of the `subscribeOn`/`observeOn` articles:

- https://proandroiddev.com/understanding-rxjava-subscribeon-and-observeon-744b0c6a41ea
- https://medium.com/upday-devs/rxjava-subscribeon-vs-observeon-9af518ded53a
- http://rx-marin.com/post/observeon-vs-subscribeon/
- https://www.google.hu/search?q=subscribeon+observeon&oq=subscribeon+observeon
