### ISSUE TITLE
Publish.onNext with groupBy and slow Consumer (Backpressure)

### ISSUE THREAD

**Issue by FranRiadigos** [ReactiveX/RxJava#6462]
I spent some days with the following simple test:

```java
//https://stackoverflow.com/a/51279732/2571940
FlowableProcessor<Pair> emitter = PublishProcessor.<Pair>create().toSerialized();

TestScheduler testScheduler = new TestScheduler();

TestSubscriber<Pair> ts = emitter
        .onBackpressureBuffer()
        .groupBy(pair -> pair.x)
        .flatMap(flow -> flow.doOnNext(pair -> {
            Thread.sleep(50); // Delays consumer
            System.out.println(pair.x + ": " + pair.y);
        }))
        .subscribeOn(testScheduler)
        .observeOn(testScheduler)
        .test();

testScheduler.triggerActions();

emitter.onNext(new Pair("1", "a1"));
emitter.onNext(new Pair("1", "a2"));
testScheduler.advanceTimeBy(10, TimeUnit.MILLISECONDS);

// Emits much faster than it consumes
emitter.onNext(new Pair("2", "b1"));
emitter.onNext(new Pair("1", "a3"));
emitter.onNext(new Pair("1", "a4"));
testScheduler.advanceTimeBy(10, TimeUnit.MILLISECONDS);
```

Expected output:

```
1: a1
1: a2
1: a3
1: a4
2: b1
```

Current output:

```
1: a1
1: a2
2: b1
1: a3
1: a4
```

What's wrong with my test?
Thanks.

**Comment by akarnokd** [comment]
You signal "b1" which then goes through the chain without buffering as flatMap recombines the groups as soon as it can. Besides, with the TestScheduler, Thread.sleep just wastes time.

I assume you encountered the expected output with normal schedulers. What happens is that flatMap keeps draining the group that has more data, thus you don't get a perfect interleaving. With asynchrony around flatMap, often there is no clear order of items so you can only verify if they are in a set.

**Comment by FranRiadigos** [comment]
Then, how should I test streaming over time while slowing down the consumer?
Shall I use real Schedulers in a test to keep this ordering correct? 
(Since the order of items emitted and grouped is the real test I'm trying to ensure)

**Comment by akarnokd** [comment]
Why do you want to test RxJava itself on this flow?
You can use `concatMapEager` with large enough buffers or use `toList` to collect up each group.

**Comment by FranRiadigos** [comment]
My intention is to simplify and replace a mechanism I have with Queue and Maps using RxJava + Backpressure.

A publisher posts messages over the time, each message belongs to a group Id.

The Flowable should group them by their Id, keep them in the Backpressure buffer while they are being consumed and only emit items of that group until there is no more, otherwise jump onto the next item of the next group.

If while the subscriber is consuming an item, a new one is published on the same group, I expect this new item to be place at the queue of the consuming group and get emitted instead of jumping to the next group as it happens now.

I thought a combination of Backpressure + the groupBy operator should satisfy this requirement, but perhaps the library is not intended to it. 
Please let me know.

I can't use `toList` as the intention is not to wait until all grouped items are published, but to keep the `emitter` alive and emitting as they arise.
`concatMapEager` groups the items by the first group id and never jumps onto the next grouped items.

Anyway, I might find out how to achieve this, but my doubt is **how to simulate in a test that a subscriber is taking more time in consuming the emitted items**.

Thanks.

**Comment by akarnokd** [comment]
> If while the subscriber is consuming an item, a new one is published on the same group, I expect this new item to be place at the queue of the consuming group and get emitted instead of jumping to the next group as it happens now.

Sounds like you need some kind of priority queueing. GroupBy is not good for this type of operation. I suggest you ask this question on StackOverflow.

**Comment by FranRiadigos** [comment]
Well, I still don't know how to test a slow Consumer, but thanks anyway @akarnokd

**Comment by akarnokd** [comment]
You have to reduce the execution frequency of the processing by putting it behind a test scheduler:

`flow.observeOn(scheduler).doOnNext`.

Using `subscribeOn().observeOn()` at the end has no practical use in your case as the processing happens before that.

Alternatively, you can avoid using a scheduler by having another subject signal when doOnNext can happen:

```java
flow.zipWith(stepSubject, (a, b) -> a).doOnNext()

emitter.onNext(1);
emitter.onNext(2);

stepSubject.onNext(1);
```
