### ISSUE TITLE
Unhandled io.reactivex.exceptions.UndeliverableException when using combineLatest with error consumer

### ISSUE THREAD

**Issue by alexander-podshiblov** [ReactiveX/RxJava#6463]
- Version 2.2.8

  - Unhandled io.reactivex.exceptions.UndeliverableException

Simplified code sample:
```
Disposable test = Observable.combineLatest(
                Observable.error(new RuntimeException("Exception from first")),
                Observable.error(new RuntimeException("Exception from second")),
                (one, two) -> new Object()
            )
            .subscribe(
                s -> {},
                e -> System.out.println("error: " + e.toString())
            );
```

Error consumer prints "error: java.lang.RuntimeException: Exception from first", but then app crashes.

  - keywords: combineLatest, unhandled, UndeliverableException

**Comment by akarnokd** [comment]
The exception message should have an URL about why you get this and what you can do about it. Please consult https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0#error-handling
