### ISSUE TITLE
Flowable.doAfterTerminate not called in 2.2.4+

### ISSUE THREAD

**Issue by mik9** [ReactiveX/RxJava#6466]
After upgrade to latest version (2.2.8) `doAfterTerminate` callback is not called in one of my places.

See attached project with test case. There are two `doAfterTerminate`, first of which did not received callback.
[rxjava-bug.zip](https://github.com/ReactiveX/RxJava/files/3113204/rxjava-bug.zip)

Run test with:
```
/gradlew --rerun-tasks test
```

If you change rxjava version in `build.gradle` to `2.2.3` you will see that test success. But with `2.2.4+` it will fail.

**Comment by akarnokd** [comment]
There was a bugfix in 2.2.4 that made lifecycle handlers not to signal events when they get cancelled. In this case, `firstOrError` cancels the flow and `doOnSubscribe` will not relay the `onComplete` from its upstream. If you wanted to perform cleanup, use `doFinally` which is called upon termination and cancellation.

**Comment by mik9** [comment]
Thanks for explanation. I somehow missed `doFinally` operator and used `doAfterTerminate` for this purpose.
