### ISSUE TITLE
2.x debounce doesn't take durationSelector?

### ISSUE THREAD

**Issue by spacetimedecor** [ReactiveX/RxJava#6467]
Hello!

I've seen that in RxJS, the debounce operator takes a durationSelector, but that in RxJava, this isn't the case. Is there possibly a workaround to this?

Cheers,
Adam

**Comment by akarnokd** [comment]
It does: [debounce(Function<T, ObservableSource<U>> debounceSelector)](http://reactivex.io/RxJava/2.x/javadoc/io/reactivex/Observable.html#debounce-io.reactivex.functions.Function-). 

Please take the time and discover available operators before you post, as requested by the welcome text:
> RxJava has more than 150 operators, we recommend searching the [javadoc](http://reactivex.io/RxJava/2.x/javadoc/io/reactivex/Observable.html) for keywords of what you try to accomplish.

**Comment by akarnokd** [comment]
Also please do not cross post issues: https://stackoverflow.com/questions/55848822/how-to-change-rxjava-rxscala-operator-debounce-parameters-after-initialisatio
