### ISSUE TITLE
ObservableSampleWithObservable redundant methods

### ISSUE THREAD

**Issue by lxsmnsyc** [ReactiveX/RxJava#6468]
Inspected ObservableSampleWithObservable today, just to see how the resulting Observable acts if the sampler Observable completes, and found these method abstraction.

https://github.com/ReactiveX/RxJava/blob/deeb14150ac21ad8c7b38c1ac692be487375faf5/src/main/java/io/reactivex/internal/operators/observable/ObservableSampleWithObservable.java#L195

https://github.com/ReactiveX/RxJava/blob/deeb14150ac21ad8c7b38c1ac692be487375faf5/src/main/java/io/reactivex/internal/operators/observable/ObservableSampleWithObservable.java#L204

https://github.com/ReactiveX/RxJava/blob/deeb14150ac21ad8c7b38c1ac692be487375faf5/src/main/java/io/reactivex/internal/operators/observable/ObservableSampleWithObservable.java#L166

https://github.com/ReactiveX/RxJava/blob/deeb14150ac21ad8c7b38c1ac692be487375faf5/src/main/java/io/reactivex/internal/operators/observable/ObservableSampleWithObservable.java#L171

I don't see any point of them being separated if both methods just do the same thing, or am I missing something?

**Comment by akarnokd** [comment]
They can probably simplified. PR welcome.
