### ISSUE TITLE
Stateful Service sessioning

### ISSUE THREAD

**Issue by ghost** [ReactiveX/RxJava#6472]
Hey, this is rather a question then issue... In my project I want to have multiple clients connecting to a service. I am currently using the java Rsocket implementation.

The service should maintain a state for each client. Now at this point I either can manage the clients by some identifier. This option I have already implemented. But I do not want to manage the session manually using strings.

So another idea is to identify the clients by the Rsocket connection. Is there a way to use ReactiveX in my use-case for identification of a specific client?

**Comment by akarnokd** [comment]
RxJava works with in memory objects so you either access shared state or composite context information with each item flowing through. I don't know what RSocket can give you so you should ask such questions on their issue list or on Stackoverflow.

**Comment by ghost** [comment]
@akarnokd thank you for your response. Like lets say in my application, the server is holding an integer value for each client. Now each client will establish a channel with the server, and fire some increments , decrement commands. The server at this point should execute the commands on the integer value of the specific client who fired the command. 
To identify the client on the server I either can use a string identifier or maybe (the fancy idea) the channel. The question is wether i can use Reactivex for that... If not, than what could i use anyway?

Now to your comment. I have in memory integer values which are being changed by the server as it gets the command from a client. So RxJava should be able to work with those? How would RxJava identify which client's integer field is accessed?

**Comment by akarnokd** [comment]
I don't know, it is outside of the scope of RxJava as we don't do networking, flow context or sessioning. Please ask this question on StackOverflow or on the RSocket forums/issue list.
