### ISSUE TITLE
Endless loop on flatMap chain

### ISSUE THREAD

**Issue by aggressive-perfector** [ReactiveX/RxJava#6478]
I have this method for retrieving objects from Room database

    @Query("SELECT * FROM cars")
    Flowable<CarListData> getCarsFromCache();

and this method for making a network call

    @GET("list_cars.json")
    Flowable<CarListSchema> getCarsFromNetwork(@Query("page") int page);

I am trying to implement some kind of caching strategy, so after **getCarsFromCache()** completes, I call **getCarsFromNetwork()** and then I do some extra stuff for caching the returned network data.

    public Flowable<CarItemSchema> getPopularCars(String car) {
        return getCarsFromCache().flatMap(new Function<CarListData, Publisher<CarListData>>() {
            @Override
            public Publisher<CarListData> apply(CarListData carListData) throws Exception {
                return Flowable.just(carListData);
            }
        }).flatMap(new Function<CarListData, Publisher<CarListSchema>>() {
            @Override
            public Publisher<CarListSchema> apply(CarListData carListData) throws Exception {
                return getCarsFromNetwork(carListData.getCurrentPage);
            }
        }, new BiFunction<CarListData, CarListSchema, List<CarItemSchema>>() {
            @Override
            public List<CarItemSchema> apply(CarListData carListData, CarListSchema carListSchema) throws Exception {
                List<CarItemSchema> cars = carListData.getCars();
                cars.addAll(carListSchema.getData().getCars());
    
                // TODO save cars to cache ...
                return cars;
            }
        }).flatMap(new Function<List<CarItemSchema>, Publisher<CarItemSchema>>() {
            @Override
            public Publisher<CarItemSchema> apply(List<CarItemSchema> carItemSchema) throws Exception {
                return Flowable.fromIterable(carItemSchema);
            }
        });
    }

That method is called from this one

    @Override
    public Flowable<Car> onLoadCar(String brand) {
        return getCarData(brand).map(new Function<CarItemSchema, Car>() {
            @Override
            public Car apply(CarItemSchema carItemSchema) throws Exception {
                return new Car(carItemSchema.getModel(), carItemSchema.getCoverImage());
            }
        });
    }

and here I perform the subscription

    public void loadCars() {
        mSubscription = onLoadCar("fiat").subscribeOn(Schedulers.io()).observeOn(AndroidSchedulers.mainThread()).subscribeWith(new ResourceSubscriber<Car>() {
    
            @Override
            public void onNext(Car car) {
                mView.updateData(car);
            }
    
            @Override
            public void onError(Throwable e) {}
    
            @Override
            public void onComplete() {}
        });
    }

but the problem is that **getCarsFromCache** and **getCarsFromNetwork** methods get called automatically for ever on an endless loop.

Maybe I am using flatMap the wrong way. 
I just want to call **getCarsFromCache**, use it's response on **getCarsFromNetwork** method and then return the items to the view.

What am I doing wrong?

Thanks in advance!

**Comment by akarnokd** [comment]
I don't understand the question. What is doing an endless loop? Flowable Bridges to Android databases are usually never ending and can keep signaling more items if the database gets updated. Please ask this question on StackOverflow.
