### ISSUE TITLE
Support for `.collect(java.util.stream.Collector)`

### ISSUE THREAD

**Issue by kevmo314** [ReactiveX/RxJava#6489]
Hi, `Flowable.collect()` currently only supports `.collect(Callable<U>, BiConsumer<U, T>)`: https://github.com/ReactiveX/RxJava/blob/3.x/src/main/java/io/reactivex/Flowable.java#L7086. Can an overload for `.collect(java.util.stream.Collector)` also be added? I imagine it would be pretty straightforward, something like

```java
    public final <T, A, R> Single<R> collect(Collector<T, A, R> collector) {
        ObjectHelper.requireNonNull(collector, "collector is null");
        return collect(collector.supplier(), collector.accumulator()).map(collector.finisher());
    }
```

I can send a pull request and work out the details if this sounds good, but wanted to see if there was a reason this could not be done first.

**Comment by kevmo314** [comment]
I guess maybe this isn't done because Java 6 needs to be supported? Can a multi-release jar be used to allow Java 9+ interfaces?

**Comment by akarnokd** [comment]
No and multi-release jars can't br used to add api. Please see the RxJava 2 JDK 8 interop library. https://github.com/akarnokd/RxJava2Jdk8Interop#using-stream-collectors
