### ISSUE TITLE
Are hot non completing database observables a Rx usecase? Side-effect writing issue

### ISSUE THREAD

**Issue by ursusursus** [ReactiveX/RxJava#6490]
Hi, I have more of a opinions question, asi if this, what many people do, should be a Rx use case.

In apps there is usually sql database, which is queried by UI as a observable, which emits after the query is loaded + anytime data changes (Room / SqlDelight etc)

Reads sound okay, however, is it possible to have "pure" writes to the database?

Writing to the database might look like this

```
fun sync() = Completable.fromCallable {
   //  do something
   database.writeSomethingSynchronously()
}
```

```
SomeUi {
  init {
     database.someQueryObservable()
       .subscribe { show list }
   }
}
```

Imagine you want to display progressbar while this Completable is in flight.
What is effectively happening here is *sideffecting to the database*. Which means the opened database observable will re-emit when the data is written, **but still before the sync() returns** (assuming single threaded for simplicity)

_Now there is point in time where there is new data in the UI and the progressbar is shown._ (and worse with multithreading timings) This is invalid state.

In imperative world, sync would provide a completion callback, in which one would reload the query manually + show/hide progressbar synchronously. (And somehow block the database change listener for duration of the sync writes?)

Is there a way around this at all?

**Comment by akarnokd** [comment]
Please ask such questions about IO/networking/databases and RxJava on StackOverflow.

**Comment by ursusursus** [comment]
@akarnokd They'll shut me down too as its a opinions, but okay 

https://stackoverflow.com/questions/56328559/are-hot-non-completing-database-observables-a-rx-usecase-side-effect-writing-is
