### ISSUE TITLE
[Question] Parsing the results of serial requests.

### ISSUE THREAD

**Issue by ghost** [ReactiveX/RxJava#6491]
I tried finding for the solutions in stackoverflow but I couldn't.
[Question]
I am making an api call to A, which gives me some data, like (id, name, data etc). Now the id field from this result has to be passed to another api B which gives me more data. The problem is, A sometimes returns null ids too. So for that I want to just send the data received without request B.

So the flow is like [this](https://mermaidjs.github.io/mermaid-live-editor/#/view/eyJjb2RlIjoiZ3JhcGggVERcbkFbQVBJIGNhbGwgdG8gYXBpXzFdIC0tPkIoUmVjZWl2ZSBkYXRhIG9mIHR5cGUgJ0EnKVxuQiAtLT4gQ3tJZiBpZCA9PSBudWxsfVxuQyAtLT58dHJ1ZXwgRFtNYWtlIGFwaV8yIHJlcXVlc3RdXG5EIC0tPkUoUmVjZWl2ZSBkYXRhIG9mIHR5cGUgJ0InIGFuZCAnQScgZnJvbSB0aGUgcHJldmlvdXMgcmVxdWVzdClcbkUgLS0-IEZbRG8gc29tZSBvcGVyYXRpb24gb24gZGF0YSAnQScgYW5kICdCJyBhbmQgcmV0dXJuICdDJ11cbkMgLS0-IHxmYWxzZXwgRyhUYWtlIHRoZSBkYXRhICdBJyBvZiBwcmV2aW91cyByZXF1ZXN0KVxuRiAtLT4gSFtQYXJzZSBBIGFuZCBCIHRvIENdXG5HIC0tPiBIXG4iLCJtZXJtYWlkIjp7InRoZW1lIjoiZGVmYXVsdCJ9fQ).

**Comment by akarnokd** [comment]
Questions such as how do I X in RxJava are better asked on Stackoverflow.

In general, use flatMap with an external field to remember the previous item.
