### ISSUE TITLE
RxJava and Reactive Streams

### ISSUE THREAD

**Issue by lxsmnsyc** [ReactiveX/RxJava#6493]
I have inspected most of the RxJava source and this raised a question in mind.

Are the RxJava Reactive classes (Observable, Completable, etc.) excluding the Flowable class compliant to the Reactive Streams specifications? Are they to comply with the specifications if they behavior isn't in accord with the specifications?

If both answers are yes, then there are some operators that do not comply with the Reactive Streams.

For example, the [SingleAmb](https://github.com/ReactiveX/RxJava/blob/2.x/src/main/java/io/reactivex/internal/operators/single/SingleAmb.java) implementation do not comply.

The following are violated:

- 1.7 Once a terminal state has been signaled (onError, onComplete) it is REQUIRED that no further signals occur.
- 1.8 If a Subscription is cancelled its Subscriber MUST eventually stop being **signaled**
- 2.4 Subscriber.onComplete() and Subscriber.onError(Throwable t) MUST consider the Subscription cancelled after having received the signal.
- 2.5 A Subscriber MUST call Subscription.cancel() on the given Subscription after an onSubscribe signal if it already has an active Subscription.
- 2.6 A Subscriber MUST call Subscription.cancel() if the Subscription is no longer needed.
- 3.12 While the Subscription is not cancelled, Subscription.cancel() MUST request the Publisher to eventually stop signaling its Subscriber. The operation is NOT REQUIRED to affect the Subscription immediately.

And also raises another question, if the Observer onXXXX methods raises an error, should the error be:
- caught and silently consumed
- thrown into the Main Thread
- passed to an onError signal

This question is to clarify the expected vs "in reality" implementation for the operators.

**Comment by akarnokd** [comment]
They are based on the Reactive Streams specification and adapted to their specific signal properties.
How is SingleAmb violating those rules?

**Comment by lxsmnsyc** [comment]
If we check the terminal signals (onSuccess, onError), we can see this part:

```java
if (winner.compareAndSet(false, true)) {
    set.delete(upstream);
    set.dispose();
    onXXXX(value);
}
```

Since the set, which is a CompositeDisposable, serves as the `Subscription` for the `Subscribers` (SingleObserver), wouldn't it be violating the rules if SingleAmb disposes first the subscription and then signals the `Subscriber`s? Also, shouldn't the terminal signal dispose the upstream so that it is to notify the `Publisher` to stop sending signals to the `Subscriber` (the AmbSingleObserver)?

Another one:
```java
@Override
public void onSubscribe(Disposable d) {
      this.upstream = d;
      set.add(d);
}
```

Isn't this a 2.5 violation?

Some operators correctly implements these, and I find it contradictory to the other operators such as SingleAmb that do not.

**Comment by akarnokd** [comment]
The set contains all Disposables received via onSubscribe from their respective sources. A winner will first remove itself from the set as its source is now considered disposed thus no need to dispose it specifically. The remaining sources are then disposed en masse. This ordering is not mandated by the spec and has been chosen as you see in the code. Disposing is rarely expected to be long or indeterminate while onXXX could take an arbitrary time, keeping the non-winners active longer than necessary.

**Comment by lxsmnsyc** [comment]
I was actually talking about how the control flow is done, and not how SingleAmb as an operator behaves.

**Comment by akarnokd** [comment]
For the onSubscribe, in a strict sense, it lacks the usual validation call that would dispose an invalid call's Disposable. Effectively, since the Disposable is added to the set, it would be eventually disposed anyway. There are certainly places where the validation is not present and I'm willing to accept PR that add **and also test it** by providing a deliberately badly written source.

> I was actually talking about how the control flow is done

Not sure what you mean. The spec does not mandate in which order cancellation and downstream notification happens, mostly because it doesn't deal with chains of operators, only the direct interaction point between a Publisher and a Subscriber. As I described, RxJava decided to cancel first and notify termination later so that a likely arbitrary long onXXX does not keep upstream resource(s) open inconveniently long.

**Comment by lxsmnsyc** [comment]
> As I described, RxJava decided to cancel first and notify termination later so that a likely arbitrary long onXXX does not keep upstream resource(s) open inconveniently long.

Since it has been implemented that way, and my question about the Observer implementation has been answered in another issue, I have decided to close this issue. Thank you for the replies.
