### ISSUE TITLE
2.x: error: package rx does not exist with Gradle 5.1.1

### ISSUE THREAD

**Issue by Aure77** [ReactiveX/RxJava#6500]
I am using RxJava 2.2.8
When I upgrade my project from gradle 4.10.1 to 5.1.1, I can't build it because rx dependencies are not resolved correctly during task "compileDebugJavaWithJavac" :

> error: package rx does not exist
> import rx.Observable;

I found similar issues on stackoverflow, the only solution is to go back to the previous gradle version... that is not satisfying for me.
Have you ever encountered this problem ?

**Comment by akarnokd** [comment]
Something pulled in an RxJava 1.x dependency as RxJava 2 is packaged into `io.reactivex`. Please post your build.gradle

**Comment by Aure77** [comment]
You right. Gradle 5 seems have changed how it's references his dependencies. My project have a transitive dependency that contains RxJava 1.x but it's not referenced in classpath with gradle 5...
