### ISSUE TITLE
io.reactivex.exceptions.UndeliverableException: The exception could not be delivered to the consumer because it has already canceled/disposed the flow or the exception has nowhere to go to begin with. Further reading: https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0#error-handling | Failed to allocate a 25653658 byte allocation with 15801680 free bytes and 15MB until OOM

### ISSUE THREAD

**Issue by BXFei** [ReactiveX/RxJava#6502]
{“ptid”：“22209-1587”，“stacks”：“io.reactivex.exceptions.UndeliverableException：异常无法传递给消费者，因为它已经取消/处理了流量，或者异常无处可去开始。进一步阅读：https：//github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0#error-handling| 无法分配25653658字节分配15801680个空闲字节和15MB直到OOM \ n \ tat io.reactivex.plugins.RxJavaPlugins.onError（RxJavaPlugins.java:367）\ n \ tat io.reactivex.internal.schedulers.ScheduledRunnable.run （ScheduledRunnable.java:69）\ n \ tat io.reactivex.internal.schedulers.ScheduledRunnable.call（ScheduledRunnable.java:57）\ n \ tat java.util.concurrent.FutureTask.run（FutureTask.java:237）\ ñ\达java.util.concurrent.ScheduledThreadPoolExecutor中$ ScheduledFutureTask.run（ScheduledThreadPoolExecutor.java:272）\ n \达java.util.concurrent.ThreadPoolExecutor.runWorker（ThreadPoolExecutor.java:1133）\ n \针锋相对的java.util.concurrent .ThreadPoolExecutor $ Worker.run（ThreadPoolExecutor.java:607）\ n \ tat java.lang.Thread.run（Thread.java:760）\ n由：java.lang.OutOfMemoryError：
2019-06-14 14：47：27.847 22209-22932 / com.lvkakeji.faceball E / [RC：L-crash_main_trb -F]：。run（ScheduledRunnable.java:66）\ n \ t ... 6更多\ n“} 
2019-06-14 14：47：27.867 22209-22932 / com.lvkakeji.faceball E / RongLog：[RongExceptionHandler] uncaughtException 
io.reactivex.exceptions.UndeliverableException：无法将异常传递给消费者，因为它有已取消/处理流程或异常无处可去。进一步阅读：https：//github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0#error-handling |无法分配25653658字节分配15801680个空闲字节和15MB直到OOM 
at io.reactivex.plugins.RxJavaPlugins.onError（RxJavaPlugins.java:367）
在io.reactivex.internal.schedulers.ScheduledRunnable.run（ScheduledRunnable.java:69）
在io.reactivex.internal.schedulers.ScheduledRunnable.call（ScheduledRunnable.java:57）
在java.util.concurrent.FutureTask.run（FutureTask的.java：237）
在java.util.concurrent.ScheduledThreadPoolExecutor中$ ScheduledFutureTask.run（ScheduledThreadPoolExecutor.java:272）
在java.util.concurrent.ThreadPoolExecutor.runWorker（ThreadPoolExecutor.java:1133）
在java.util.concurrent.ThreadPoolExecutor中的$ 
java.lang.Thread.run中的Worker.run（ThreadPoolExecutor.java:607）（Thread.java:760）
引起：java.lang.OutOfMemoryError：无法分配25653658字节分配15801680个空闲字节和15MB直到OOM
在java.lang.StringFactory.newStringFromBytes（StringFactory.java:176）
在java.lang.StringFactory.newStringFromBytes（StringFactory.java:207）
在okio.Buffer.readString（Buffer.java:721）
在okio.Buffer.readString（ Buffer.java:704）
在okhttp3.logging.HttpLoggingInterceptor.intercept（HttpLoggingInterceptor.java:208）
在okhttp3.internal.http.RealInterceptorChain.proceed（RealInterceptorChain.java:147）
在okhttp3.internal.http.RealInterceptorChain.proceed（RealInterceptorChain的.java：121）
在com.faceball.module_common.retrofit.ResponseInterceptor.intercept（ResponseInterceptor.java:34）
在okhttp3.internal.http.RealInterceptorChain.proceed（RealInterceptorChain.java:147）
在okhttp3.internal.http.RealInterceptorChain.proceed（RealInterceptorChain.java:121）
在com.faceball.module_common.retrofit.CommomInterceptor.intercept（CommomInterceptor.java:147）
在okhttp3.internal.http.RealInterceptorChain.proceed（RealInterceptorChain.java ：147）
在okhttp3.internal.http.RealInterceptorChain.proceed（RealInterceptorChain.java:121）
在com.faceball.module_common.retrofit.TokenInterceptor.intercept（TokenInterceptor.java:118）
在okhttp3.internal.http.RealInterceptorChain.proceed（ RealInterceptorChain.java:147）
在okhttp3.internal.http.RealInterceptorChain.proceed（RealInterceptorChain.java:121）
在okhttp3.RealCall.getResponseWithInterceptorChain（RealCall.java:264）
在okhttp3.RealCall.execute（RealCall.java:93）
在retrofit2.OkHttpCall.execute（OkHttpCall.java:180）
在retrofit2.adapter.rxjava2.CallExecuteObservable.subscribeActual（CallExecuteObservable.java:42）
在io.reactivex.Observable.subscribe（Observable.java:12090）
在retrofit2.adapter。 rxjava2.BodyObservable.subscribeActual（BodyObservable.java:34）
at io.reactivex.Observable.subscribe（Observable.java:12090）
at io.reactivex.internal.operators.observable.ObservableFlatMap $ MergeObserver.subscribeInner（ObservableFlatMap.java:165）
在io.reactivex.internal.operators.observable.ObservableFlatMap $ MergeObserver.onNext（ObservableFlatMap.java:139）
在io.reactivex.internal.operators.observable.ObservableFromArray $ FromArrayDisposable.run（ObservableFromArray.java:108）
at io.reactivex.internal.operators.observable.ObservableFromArray.subscribeActual（ObservableFromArray.java:37）
at io.reactivex.Observable.subscribe（Observable.java:12090）
at io.reactivex.internal.operators.observable.ObservableFlatMap.subscribeActual （ObservableFlatMap.java:55）
在io.reactivex.Observable.subscribe（Observable.java:12090）
在io.reactivex.internal.operators.observable.ObservableSubscribeOn $ SubscribeTask.run（ObservableSubscribeOn.java:96）
在io.reactivex。调度$ DisposeTask.run（Scheduler.java:578）
在io.reactivex.internal.schedulers.ScheduledRunnable.run（ScheduledRunnable.java:66）
在io.reactivex.internal.schedulers.ScheduledRunnable.call（ScheduledRunnable.java:57） 
在java.util.concurrent.FutureTask.run（FutureTask.java:237）  
在java.util.concurrent.ScheduledThreadPoolExecutor中$ ScheduledFutureTask.run（ScheduledThreadPoolExecutor.java:272）  
在java.util.concurrent.ThreadPoolExecutor.runWorker（ThreadPoolExecutor.java ：1133）  
java.util.concurrent.ThreadPoolExecutor $ Worker.run（ThreadPoolExecutor.java:607）  
at java.lang.Thread.run（Thread.java:760)  
2013-06-14 14:47:27.979 1806-1806 /？E / Icon：无法从pkg = com.android.systemui加载资源0x00000000 
android.content.res.Resources $ NotFoundException：
android.content.res.ResourcesImpl.getValue（ResourcesImpl.java:201）
上的资源ID＃0x0 在android .content.res.MiuiResourcesImpl.getValue（MiuiResourcesImpl.java:94）
在
Android.graphics.drawable.Icon.loadDrawable（Icon.java:272）的android.graphics.drawable.Icon.loadDrawableInner（Icon.java:316）
的android.content.res.Resources.getDrawable（Resources.java:788） ）
在android.graphics.drawable.Icon.loadDrawableAsUser（Icon.java:380）
在com.android.systemui.statusbar.ExpandedIcon.getDrawable（ExpandedIcon.java:59）
在com.android.systemui.statusbar.StatusBarIconView.getIcon（ StatusBarIconView.java:195）
在com.android.systemui.statusbar.StatusBarIconView.setIcon（StatusBarIconView.java:142）
在com.android.systemui.statusbar.StatusBarIconView.updateDarkMode（StatusBarIconView.java:287）
在com.android.systemui .statusbar.phone.SimpleStatusBar.updateDarkMode（SimpleStatusBar.java:358）
在com.android.systemui.statusbar.phone.PhoneStatusBar $ 28.run（PhoneStatusBar.java:4458）
在android.os.Handler.handleCallback（Handler.java:754）
在android.os.Handler.dispatchMessage（Handler.java： 95）
在android.app.Looper.loop（Looper.java:163）
的android.app.ActivityThread.main（ActivityThread.java:6396）
，
位于com.android的java.lang.reflect.Method.invoke（Native Method）.internal.os.ZygoteInit $ MethodAndArgsCaller.run（ZygoteInit.java:904）
at com.android.internal.os.ZygoteInit.main（ZygoteInit.java:794）

**Comment by akarnokd** [comment]
Please read the exception message:

> Further reading: https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0#error-handling

> Failed to allocate a 25653658 byte allocation with 15801680 free bytes and 15MB until OOM

You run out of memory for some reason. Please note that core dumps without context is next to useless to us.
