### ISSUE TITLE
Add ParallelFlowable#flatMapX() and ParallelFlowable#concatMapX() operators

### ISSUE THREAD

**Issue by veyndan** [ReactiveX/RxJava#6503]
`Flowable` has several spin-off operators of `flatMap` and `concatMap` which I am requesting to be added to `ParallelFlowable`.

The operators are as follows:

- `flatMapCompletable`
- `flatMapSingle`
- `flatMapMaybe`
- `flatMapIterable`
- `concatMapCompletable`
- `concatMapCompletableDelayError`
- `concatMapSingle`
- `concatMapSingleDelayError`
- `concatMapMaybe`
- `concatMapMaybeDelayError`
- `concatMapEager`
- `concatMapEagerDelayError`
- `concatMapIterable`

**Comment by akarnokd** [comment]
Why?

**Comment by veyndan** [comment]
For the same reason `Flowable` has them: to improve semantics and the readability of my code. Unless the operators in `Flowable` are doing more than I assume.

**Comment by akarnokd** [comment]
We try to keep the operator count as small as possible and try to avoid bloat and combinatorial explosion. In practice, there was little need for specialized parallel operators targeting the other base reactive types.
If you have performance issues with the standard conversions applied in the parallel operators, you can create a `ParallelTransformer` and custom parallel operators. This shouldn't be difficult as many parallel operators [reuse](https://github.com/ReactiveX/RxJava/blob/2.x/src/main/java/io/reactivex/internal/operators/parallel/ParallelFlatMap.java#L59) the code of their non-parallel counterparts.

**Comment by veyndan** [comment]
Okay thanks for the clarification.
