### ISSUE TITLE
ConnectableFlowable doesn't start emitting on connect()

### ISSUE THREAD

**Issue by Dimezis** [ReactiveX/RxJava#6509]
Version used `io.reactivex.rxjava2:rxjava:2.2.9`

Example code:

```Kotlin
val connectable = Flowable.just("")
            .map { println("map") }
            .replay(1)

connectable.connect()
println("connect")
connectable.test()
```

Output: 
```
connect
map
```

Expected output:
```
map
connect
```

The same example with `publish` instead of `replay(1)` works as expected:

```Kotlin
val connectable = Flowable.just("")
            .map { println("map") }
            .publish()

connectable.connect()
println("connect")
connectable.test()
```

Output: 
```
map
connect
```

The same example with `Observable` works as expected:

```Kotlin
val connectable = Observable.just("")
            .map { println("map") }
            .replay(1)

connectable.connect()
println("connect")
connectable.test()
```

Output:
``` 
map
connect
```

**Comment by akarnokd** [comment]
This is by design and a consequence of backpressure support. Without it, a connect and a bounded buffer would probably run through all items and by the time subscribers arrive, they'd only get the very last items.

**Comment by Dimezis** [comment]
Hm, but does it even matter that subscribers will miss the items, if we are dealing with a connectable flowable/observable?
I mean, they are missing the items anyway if they subscribe after the `connect()`, except of those in the replay buffer.

**Comment by akarnokd** [comment]
We can't know in general. This behavior can be worked around via a dummy unbounded consumer, i.e., `subscribe()`. If it were the other way around, you couldn't prevent it from rushing though.
