### ISSUE TITLE
can you tell me why not to use isDisposed() method to control onXXX methods，thank you 

### ISSUE THREAD

**Issue by xchengDroid** [ReactiveX/RxJava#6521]
https://github.com/ReactiveX/RxJava/blob/31e8d48a53c42c46a01f1db3d09ab4cafe5133f6/src/main/java/io/reactivex/internal/observers/BasicFuseableObserver.java#L95

**Comment by xchengDroid** [comment]
```java
 @Override
    public void onError(Throwable t) {
        if (isDisposed()) {
            RxJavaPlugins.onError(t);
            return;
        }
        dispose();
        downstream.onError(t);
    }

```
just like this

**Comment by akarnokd** [comment]
Rule [§2.3](https://github.com/reactive-streams/reactive-streams-jvm#2.3): 
`Subscriber.onComplete()` and `Subscriber.onError(Throwable t)` MUST NOT call any methods on the `Subscription` or the `Publisher`. *The intent of this rule is to prevent cycles and race-conditions—between `Publisher`, `Subscription` and `Subscriber`—during the processing of completion signals.*

`dispose()` is tied to cancelling the upstream which shouldn't happen on this path, hence reusing the Disposable here is not valid.
