### ISSUE TITLE
Is 3.x really needed?

### ISSUE THREAD

**Issue by vanniktech** [ReactiveX/RxJava#6524]
Personally, I don't see a benefit for having a new major version of RxJava. Especially the way we want to publish it by keeping the same package names and artifact ids but removing/changing some of the behavior.

I don't get what the main incentive and reason is for a 3.x and which justification we use. Just cleaning up the API and changing a thing or two does not really justify a major version bump in my opinion.

Right now, we are at a point where every library has adopted RxJava 2 and if we release a new major version everyone would need to catch up again.

Can we talk about this before you continue spending more time on the 3.x development?

**Comment by akarnokd** [comment]
> Personally, I don't see a benefit for having a new major version of RxJava. Especially the way we want to publish it by keeping the same package names and artifact ids but removing/changing some of the behavior.

That's one of the benefits: same structure with better API and no need to re-learn the vast majority of the locations.

> Just cleaning up the API and changing a thing or two does not really justify a major version bump in my opinion.

Not just justifies it, but mandates it according to our [support pledge](https://github.com/ReactiveX/RxJava#versioning).

> Right now, we are at a point where every library has adopted RxJava 2 and if we release a new major version everyone would need to catch up again.

Only a small subset of the API get signature changes and even fewer operators change behavior. There is no need to learn many things again or even spend much time catching up. Consider this versus the case if we really changed big time like Java versions or architecture. That would need even more catch-up, doesn't it?

> Can we talk about this before you continue spending more time on the 3.x development?

It is my time. I more than welcome those who spend time on 2.x and would like to contribute to 3.x as well.

**Comment by vanniktech** [comment]
> That's one of the benefits: same structure with better API and no need to re-learn the vast majority of the locations.

The API changes are really minor though. Method rename here and there. Some return type changes but nothing crazy like it was the case for 1.x -> 2.x

Also, it does not seem like we can make all the changes we want. For instance, removing the `#isDisposed` method. 

We could do that if we decide to give 3.x a new package name and artifact id.

> Not just justifies it, but mandates it according to our [support pledge](https://github.com/ReactiveX/RxJava#versioning).

Then we should also aim for a new package name + artifact id.

> Only a small subset of the API get signature changes and even fewer operators change behavior. There is no need to learn many things again or even spend much time catching up. Consider this versus the case if we really changed big time like Java versions or architecture. That would need even more catch-up, doesn't it?

Let's say we keep 95% of the API the same under the same package name + artifact id. Now people might be using a library A which compiles with 2.x and is using one of the methods that got changed/removed with 3.x. A person who's using 3.x can't include the library. The library author is now forced to make a decision. Whether he wants to say on 2.x or move forward with 3.x. This is cumbersome and could easily be solved by a different package name + artifact id since you would not get any runtime/compiling issues.

> It is my time. I more than welcome those who spend time on 2.x and would like to contribute to 3.x as well.

I'd just like to avoid you spending a lot of time on 3.x and then being disappointed when the adoption rate of 3.x is close to being nonexistent.

**Comment by akarnokd** [comment]
> We could do that if we decide to give 3.x a new package name and artifact id.

We would instantly lose all libraries that were otherwise not depending on components affected by the API changes. In addition, having two of each component would result in far more conflicts, type mismatches, inconsistent library support, etc.

> Now people might be using a library A which compiles with 2.x and is using one of the methods that got changed/removed with 3.x.

I can't know which standard operator appears in other libraries. The main conflict point is most likely going to be `defer(Supplier)` or `buffer(..., Supplier)`. That's why Release Candidates will be out so that people can check out their favorite libraries, adjust only the dependency to 3.x and see what breaks.

> I'd just like to avoid you spending a lot of time on 3.x and then being disappointed when the adoption rate of 3.x is close to being nonexistent.

On the contrary, the suggested approaches such as separate packaging or waiting for major language/architecture changes hinders adoption. Separate package -> libraries don't switch for long or at all -> no users. Major language change -> people left behind switch to another language -> no users.

**Comment by vanniktech** [comment]
Alright. Just wanted to point out my concerns. Let's hope the transition will be smooth for everyone.
