### ISSUE TITLE
3.x: Test consumer method renames

### ISSUE THREAD

**Issue by akarnokd** [ReactiveX/RxJava#6527]
The feedback for the test consumers called for a few method renames (#6153):

- `assertResult` - test for values received followed by completion
- `assertFailure` - test for values received followed by error
- `assertEmpty` - test for no onNext/onError/onComplete signals
- `assertValuesOnly` - test for values received but no termination
- `awaitDone` - wait for termination via blocking or report timeout

Suggestions for better, more apt and hopefully not too long names are welcome.

**Comment by vanniktech** [comment]
I like the names as they are.

**Comment by maryang710** [comment]
I like it too.
