### ISSUE TITLE
[2.x] Maybe.switchIfEmpty(CompletableSource)

### ISSUE THREAD

**Issue by kevmo314** [ReactiveX/RxJava#6540]
In the same vein as #4544, can we get `Maybe.switchIfEmpty(CompletableSource)`? It would be identical to `maybe.switchIfEmpty(completable.toMaybe())`.

**Comment by akarnokd** [comment]
Is there a reason the manual application of `toMaybe()` is a problem for you? We usually don't add trivial or many conveninence operators.

**Comment by kevmo314** [comment]
We have a `CompletableSubject` which doesn't have `toMaybe()`. But I guess more broadly, `CompletableSource` is looser and doesn't actually require `toMaybe()` to exist and it seems consistent with the other overloads of `Maybe.switchIfEmpty()`.

**Comment by akarnokd** [comment]
`CompletableSubject` extends `Completable` thus it has `toMaybe`, not sure why you have problems (maybe forgot to add the target type argument for the conversion?) 

![image](https://user-images.githubusercontent.com/1269832/60036866-83bb2000-96b0-11e9-8cbd-e677aa288eb8.png)

`switchIfEmpty(Single)` makes sense on its own as it return a `Single` expecting and implying there is going to be a success item or an error. Switching to a `Completable` doesn't change the return type and thus `.toMaybe` conversion won't introduce more conversions down the line like `switchIfEmpty(Single.toMaybe())` would.

**Comment by kevmo314** [comment]
Ah okay we figured out what was going on on our end. Thanks for the context behind `SingleSource`, that makes sense. I'll close this one out as `.toMaybe()` isn't a problem. :)
