### ISSUE TITLE
2.2.0 How to chain a Single after a Completable

### ISSUE THREAD

**Issue by angelsanzn** [ReactiveX/RxJava#6547]
I have some code which sequentially performs two validations on an argument, then performs an async side-effect with it and finally returns the result of that async side-effect in a Single. The validations are async and return a complete Completable if valid, or an errored Completable if invalid. I would like the final Single to fail with either of the validation errors of the intermediate Completables, or else succeed after the async side-effect is done, returning its result.

I would like to write such code more or less like this:

```java
public class MyAction {
    public Single<Result> execute(String arg) {
        return performFirstValidation(arg)
                .andThen(Completable.fromCallable(() -> performSecondValidation(arg)))
                .andThen(Single.fromCallable(() -> performIOAndReturnResult(arg)));
    }

    private Completable performFirstValidation(String arg) {
      ...
    }

    private Completable performSecondValidation(String arg) {
      ...
    }

    private Single<Result> performIOAndReturnResult(String arg) {
      return ioGateway.performIO(arg);
    }
}
```

This code doesn't compile because Single.fromCallable expects its parameter to return a Result, not a Single<Result>. I can make it compile by changing Single.fromCallable to Single.defer, but then whenever the second validation returns an errored Completable, this error is inexplicably swallowed instead of making the returned Single fail with that error. This does not happen to the error returned by the first validation: if that validation fails, the returned Single does fail with the same error.

How can I achieve this behaviour?

**Comment by akarnokd** [comment]
I don't understand your issue. What's wrong with:

```java
performFirstValidation(arg)
                .andThen(performSecondValidation(arg))
                .andThen(performIOAndReturnResult(arg));
```

why would the method call `performSecondValidation` throw?

**Comment by angelsanzn** [comment]
I would like the validations to be performed sequentially. I believe your snippet triggers them eagerly (as well as potentially performing the IO before any validation completes or errors).

I edited my post to clarify my issue. It's not that the method call `performSecondValidation` is throwing, it's that it's returning an errored Completable, but this error gets ignored down the pipeline.

**Comment by akarnokd** [comment]
Sounds like you execute some code and then return a `Completable` instead of having a subscription trigger the execution:

```java
Completable performSecondValidation(String arg) {
     if (arg.contains("@")) {
         System.out.println("This runs eagerly!");
         return Completable.complete();
     }
     return Completable.error(new InvalidArgumentException());
}
```

`defer` should solve this case:

```java
performFirstValidation(arg)
                .andThen(Completable.defer(() -> performSecondValidation(arg)))
```

Also `andThen` won't continue if there is an error:

```java
Completable.complete()
   .andThen(Completable.error(new Exception()))
   .andThen(Completable.fromAction(() -> { System.out.println("This never runs"); }))
   .subscribe();
```

**Comment by angelsanzn** [comment]
I see. Using Completable.defer as you suggest definitely solves the issue.

What I wonder then is whether Single.defer provides the right behaviour. By its documentation, I believe it would call performIOAndReturnResult once every time the returned Single is subscribed. However, I would not like the IO to be performed every time the Single is subscribed, only once when the Single is first subscribed. Is Single.defer suitable for this use case?

**Comment by akarnokd** [comment]
You need [`Single.cache`](http://reactivex.io/RxJava/2.x/javadoc/io/reactivex/Single.html#cache--) and have that `Single` reference kept somewhere:

```java
Single<Result> cachedResult = Single.defer(() -> performIOAndReturnResult(arg)).cache();
```

**Comment by angelsanzn** [comment]
Great, thanks for your help.
