### ISSUE TITLE
Disambiguous some method call sites when calling from Kotlin 

### ISSUE THREAD

**Issue by vanniktech** [ReactiveX/RxJava#6551]
I vaguely remember that we already had a discussion about this but I don't know which conclusion was drawn. Observable.onErrorResumeNext is ambiguous when calling from Kotlin.

<img width="1370" alt="Screenshot 2019-06-30 at 12 09 33" src="https://user-images.githubusercontent.com/5759366/60395175-f18f9d80-9b2f-11e9-93cf-fd8d3f8081d3.png">

Since 3.x is a thing do we want to rename these methods. Similar to what we did with `startWith` (even though there was no type inference problem).

**Comment by akarnokd** [comment]
Yes, 3.x is a good place fix such ambiguities. My ideas are `onErrorResume(ObservableSource)` or `onErrorResumeWith(ObservableSource)`. PR welcome.

**Comment by vanniktech** [comment]
Those names sound good to me. I believe the onErrorReturn should also be renamd then.

**Comment by luis-cortes** [comment]
A few questions:

- Do you want to change `Maybe.onErrorResumeNext(MaybeSource)` as well? 
- To what should `Observable.onErrorReturn(Function valueSupplier)` be renamed? 
- Do you want to rename `Maybe.onErrorReturn(Function valueSupplier)` as well?
- What about `Single.onErrorReturn(Function resumeFunction)?`
- Is it ok to do all of this in the same PR?

**Comment by akarnokd** [comment]
> Do you want to change Maybe.onErrorResumeNext(MaybeSource) as well?

Yes, every class where `onErrorResumeNext` has a source type and a function.

> To what should Observable.onErrorReturn(Function valueSupplier) be renamed?

There is no ambiguity there as the other is called `onErrorReturnItem`

> Do you want to rename Maybe.onErrorReturn(Function valueSupplier) as well?

There is no ambiguity there either.

> What about Single.onErrorReturn(Function resumeFunction)?

There is no ambiguity there either.

> Is it ok to do all of this in the same PR?

You can rename multiple things within the same PR.

**Comment by luis-cortes** [comment]
@akarnokd Thanks for the clarification. 

Out of curiosity, @vanniktech was there a reason besides ambiguity that made you suggest renaming the `onErrorReturn`s?

**Comment by luis-cortes** [comment]
@akarnokd Is there a reason `Single.onErrorResumeNext(final Single<? extends T> resumeSingleInCaseOfError)` takes a `Single` and not a `SingleSource` like the other methods? 

I've made the change and run all the tests for this method and all of them pass. 

If there's no reason and it's ok with you I'd be happy to make the change since I'm in the area anyway.

**Comment by akarnokd** [comment]
Looks like an API mistake. You can change that too (and see if other places need fixing as well).
