### ISSUE TITLE
Remove onExceptionResumeNext?

### ISSUE THREAD

**Issue by akarnokd** [ReactiveX/RxJava#6554]
[JavaDocs](http://reactivex.io/RxJava/2.x/javadoc/io/reactivex/Flowable.html#onExceptionResumeNext-org.reactivestreams.Publisher-)

I don't remember ever needing, asked for or recommended this operator? The difference from `onErrorResumeNext` is that anything that's not extending `Exception` can pass through. I believe it was added to support some internal Netflix operation. It can be emulated via `onErrorResumeNext`: 

```java
source.onErrorResumeNext(
    error -> error instanceof Exception 
        ? fallback : Obserable.error(error))
```

**Comment by vanniktech** [comment]
Never used onExceptionResumeNext.

**Comment by suribada** [comment]
It was rather more confusing.
