### ISSUE TITLE
2.x : doFinally does not work at the timing I intended

### ISSUE THREAD

**Issue by heukhyeon** [ReactiveX/RxJava#6575]
I am using rxjava 2.2.0

When multiple Single-Observable-Completables are connected, I want to be notified when it is completely finished. 

The closest thing I want to do in the official document is doFinally, but this is slightly different from what I want.

     @Test
    public void test() throws Exception {
        TestObserver<Integer> observer = new TestObserver<>();
        createSingleWithDoFinally()
                .flatMapCompletable(integer -> createCompletable())
                .doFinally(() -> println("Actual Finally"))
                .subscribe(observer);

        observer.await();
    }

    private Single<Integer> createSingleWithDoFinally() {

        return Single.create((SingleOnSubscribe<Integer>) emitter -> emitter.onSuccess(1))
                .doFinally(() -> println("Expect doFinally"));
    }

    private Completable createCompletable() {
        println("I Have Some Delay");
        return Completable.timer(2L, TimeUnit.SECONDS)
                .andThen(Completable.defer(() -> {
                    println("Delay One More Time");
                    return Completable.timer(3L, TimeUnit.SECONDS);
                }));
    }

    private void println(String text) {
        System.out.println(text);
    }

Here is the result I want from the above code.

    I Have Some Delay
    Delay One More Time
    Expect doFinally
    Actual Finally

But the actual test results are like this.

    I Have Some Delay
    Expect doFinally
    Delay One More Time
    Actual Finally

doFinally seems to be called regardless of whether the observer's subscription is really over if the release of their item is complete.

I've looked through a lot of documents to solve this, but I could not find any events that happen later than doFinally (which happens when I want).

Is this a feature not supported by rxjava?

**Comment by akarnokd** [comment]
Please do not cross-post issues: https://stackoverflow.com/questions/56948592/is-there-a-callback-that-can-be-received-when-rxjava-is-finally-shutting-down-ob
