### ISSUE TITLE
ObservableBlockingSubscribe compares BlockingObserver.TERMINATED with wrong object

### ISSUE THREAD

**Issue by Erlkoenig90** [ReactiveX/RxJava#6576]
The `ObservableBlockingSubscribe.observe` function appears to compare the `o` variable, i.e. the `ObservableSource`, which shouldn't ever change, with `BlockingObserver.TERMINATED`. This will probably never be true. The intention was likely to use `v` instead of `o`, in:

https://github.com/ReactiveX/RxJava/blob/a38268c738af7ae1ca50dc4af2bfbb5713361411/src/main/java/io/reactivex/internal/operators/observable/ObservableBlockingSubscribe.java#L64 

Since this appears to be somewhat redundant with `bs.isDisposed()`, this probably does not cause any issues.

**Comment by akarnokd** [comment]
Yes, it should be `v == BlockingObserver.TERMINATED`. PR welcome.
