### ISSUE TITLE
Successfully sent two but responded to the corresponding number。

### ISSUE THREAD

**Issue by fengfengfeng1234** [ReactiveX/RxJava#6590]
This function is mainly to upload pictures, I see that there are two networks sent and responded successfully in android sudio -> profiler -> netWork. This is also very meaningful to me, meaning that it is not necessary to trigger io but now it is directly onError and then End. Request assistance

### use  Library  
       ` "rxandroid"        : 'io.reactivex.rxjava2:rxandroid:2.0.1',
            "rxjava"           : 'io.reactivex.rxjava2:rxjava:2.1.3',
            "rxbinding"        : "com.jakewharton.rxbinding2:rxbinding:2.2.0",
            "adapter-rxjava"   : 'com.squareup.retrofit2:adapter-rxjava2:2.3.0',`

### use code：
` static int count = 0;

    private void httpUploadMore() {

        ArrayList<String> images = new ArrayList<>();

        for (int i = 0; i < 15; i++) {
            images.add("" + i);
        }

        Flowable<Result<ArrayList<Object>>>[] list = new Flowable[images.size()];

        for (int i = 0; i < images.size(); i++) {
            /**
             * Analog network request response
             */
            list[i] = Api
                    .getInstance()
                    .getUtilsService()
                    .empty();
        }

        count = 0;

        Flowable.fromArray(list)
                .parallel(10)
                .runOn(Schedulers.io())
                .flatMap(new Function<Flowable<Result<ArrayList<Object>>>, Publisher<Result<ArrayList<Object>>>>() {
                    @Override
                    public Publisher<Result<ArrayList<Object>>> apply(Flowable<Result<ArrayList<Object>>> item) throws Exception {
                        count++;
                        if (count > 3) {
                            throw new ActivityNotFoundException();
                        }
                        return item.subscribeOn(Schedulers.io());
                    }
                })
                .doOnError(new Consumer<Throwable>() {
                    @Override
                    public void accept(Throwable throwable) throws Exception {

                    }
                })
                .sequentialDelayError()
                .observeOn(AndroidSchedulers.mainThread())
                .subscribe(new FlowableSubscriber<Result<ArrayList<Object>>>() {
                    @Override
                    public void onSubscribe(Subscription s) {
                        Log.d("mergeArray", " Result = onSubscribe ");
                    }

                    @Override
                    public void onNext(Result<ArrayList<Object>> arrayListResult) {
                        Log.d("mergeArray", " Result = onSuccess ");
                    }

                    @Override
                    public void onError(Throwable t) {
                        Log.d("mergeArray", " Result = throwable " + t.toString());
                    }

                    @Override
                    public void onComplete() {
                        /**
                         *  Will not trigger
                         */
                        Log.d("mergeArray", " Result = onComplete ");
                    }
                });

    }`

**Comment by fengfengfeng1234** [comment]
use :
     ` .subscribe(new Consumer<Result<ArrayList<Object>>>() {
                    @Override
                    public void accept(Result<ArrayList<Object>> arrayListResult) throws Exception {
                        Callcount++;
                        Log.d("mergeArray", " Result = Callcount= " + Callcount);
                    }
                }, new Consumer<Throwable>() {
                    @Override
                    public void accept(Throwable throwable) throws Exception {
                        Log.d("mergeArray", " Result = Throwable ");
                    }
                })`

**Comment by akarnokd** [comment]
Please in the future, ask such questions on StackOverflow.
