### ISSUE TITLE
Can I try catch Exceptions.throwIfFatal(e)  in  RxJavaPlugins.onError(e);

### ISSUE THREAD

**Issue by xchengDroid** [ReactiveX/RxJava#6605]
https://github.com/ReactiveX/RxJava/blob/228f6d9f8b717e7f46bdc5b5505d576b5e592375/src/main/java/io/reactivex/internal/schedulers/ScheduledRunnable.java#L68

**Comment by akarnokd** [comment]
I don't understand.

**Comment by xchengDroid** [comment]
just like this
```java
RxJavaPlugins.setErrorHandler(new Consumer<Throwable>() {
            @Override
            public void accept(Throwable throwable) throws Exception {
                try {
                    Exceptions.throwIfFatal(throwable);
                }catch (Throwable t){
                    t.printStackTrace();
                }
            }
        });
```
thank you

**Comment by akarnokd** [comment]
Why would you do that and what do you expect?

**Comment by xchengDroid** [comment]
I just want to ensure that   if I call  RxJavaPlugins.setErrorHandler method ,  is it necessary to filter  fatalError and ensure to crash.
```java

  RxJavaPlugins.setErrorHandler(new Consumer<Throwable>() {
            @Override
            public void accept(Throwable throwable) throws Exception {
                Exceptions.throwIfFatal(throwable);
                // ignore others
                throwable.printStackTrace();
            }
        });
```

**Comment by akarnokd** [comment]
If you crash the handler, exceptions go to the uncaught exception handler:

https://github.com/ReactiveX/RxJava/blob/3.x/src/main/java/io/reactivex/plugins/RxJavaPlugins.java#L375

**Comment by xchengDroid** [comment]
thank you
