### ISSUE TITLE
3.x: Revise AtomicThrowable.addThrowable usage

### ISSUE THREAD

**Issue by akarnokd** [ReactiveX/RxJava#6611]
Currently, many (if not all?) usage of `addThrowable` is as follows:

```java
if (errors.addThrowable(ex)) {
   // do something with the error case
} else {
    RxJavaPlugins.onError(ex);
}
```

The plugin error call could be inlined into the method call and renamed to `tryAddThrowable` to ensure all usage places are updated correctly.

**Comment by RomanWuattier** [comment]
Hey, do you need help doing this?

**Comment by akarnokd** [comment]
Each usage location has to be reevaluated and there are thousands of those. It would be easier if I do them.
