### ISSUE TITLE
# RxCachedThreadS(32579)  SIGSEGV(SEGV_MAPERR)

### ISSUE THREAD

**Issue by RuanJH** [ReactiveX/RxJava#6614]
#00 pc 000ebe04 /system/lib/libart.so (void std::__1::__tree_balance_after_insert<std::__1::__tree_node_base<void*>*>(std::__1::__tree_node_base<void*>*, std::__1::__tree_node_base<void*>*)+159) [armeabi-v7a]
--
2 #01 pc 001eead1 /system/lib/libart.so (std::__1::pair<std::__1::__tree_iterator<std::__1::__value_type<art::MethodReference, art::SafeMap<unsigned int, std::__1::set<unsigned int, std::__1::less<unsigned int>, std::__1::allocator<unsigned int> >, std::__1::less<unsigned int>, art::TrackingAllocator<std::__1::pair<unsigned int const, std::__1::set<unsigned int, std::__1::less<unsigned int>, std::__1::allocator<unsigned int> > >, (art::AllocatorTag)6> > >, std::__1::__tree_node<std::__1::__value_type<art::MethodReference, art::SafeMap<unsigned int, std::__1::set<unsigned int, std::__1::less<unsigned int>, std::__1::allocator<unsigned int> >, std::__1::less<unsigned int>, art::TrackingAllocator<std::__1::pair<unsigned int const, std::__1::set<unsigned int, std::__1::less<unsigned int>, std::__1::allocator<unsigned int> > >, (art::AllocatorTag)6> > >, void*>*, int>, bool> std::__1::__tree<std::__1::__value_type<art::MethodReference, art::SafeMap<unsigned int, std::__1::set<unsigned int, std::__1::less<unsigned int>, std::__1::allocator<unsigned int> >, std::__1::less<unsigned int>, art::TrackingAllocator<std::__1::pair<unsigned int const, std::__1::set<unsigned int, std::__1::less<unsigned int>, std::__1::allocator<unsigned int> > >, (art::AllocatorTag)6> > >, std::__1::__map_value_compare<art::MethodReference, std::__1::__value_type<art::MethodReference, art::SafeMap<unsigned int, std::__1::set<unsigned int, std::__1::less<unsigned int>, std::__1::allocator<unsigned int> >, std::__1::less<unsigned int>, art::TrackingAllocator<std::__1::pair<unsigned int const, std::__1::set<unsigned int, std::__1::less<unsigned int>, std::__1::allocator<unsigned int> > >, (art::AllocatorTag)6> > >, art::MethodReferenceComparator, true>, std::__1::allocator<std::__1::__value_type<art::MethodReference, art::SafeMap<unsigned int, std::__1::set<unsigned int, std::__1::less<unsigned int>, std::__1::allocator<unsigned int> >, std::__1::less<unsigned int>, art::TrackingAllocator<std::__1::pair<unsigned int const, std::__1::set<unsigned int, std::__1::less<unsigned int>, std::__1::allocator<unsigned int> > >, (art::AllocatorTag)6> > > > >::__insert_unique<std::__1::pair<art::MethodReference, art::SafeMap<unsigned int, std::__1::set<unsigned int, std::__1::less<unsigned int>, std::__1::allocator<unsigned int> >, std::__1::less<unsigned int>, art::TrackingAllocator<std::__1::pair<unsigned int const, std::__1::set<unsigned int, std::__1::less<unsigned int>, std::__1::allocator<unsigned int> > >, (art::AllocatorTag)6> > > >(std::__1::pair<art::MethodReference, art::SafeMap<unsigned int, std::__1::set<unsigned int, std::__1::less<unsigned int>, std::__1::allocator<unsigned int> >, std::__1::less<unsigned int>, art::TrackingAllocator<std::__1::pair<unsigned int const, std::__1::set<unsigned int, std::__1::less<unsigned int>, std::__1::allocator<unsigned int> > >, (art::AllocatorTag)6> > >&&)+216) [armeabi-v7a]
3 #02 pc 001eeb3f /system/lib/libart.so (bool art::interpreter::DoFieldGet<(art::FindFieldType)4, (art::Primitive::Type)0, true>(art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short)+70) [armeabi-v7a]
4 #03 pc 001ef045 /system/lib/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+1220) [armeabi-v7a]
5 #04 pc 000b2ccd /system/lib/libart.so (art::JValue art::interpreter::ExecuteGotoImpl<false, false>(art::Thread*, art::DexFile::CodeItem const*, art::ShadowFrame&, art::JValue)+27172) [armeabi-v7a]
6 #05 pc 001d4e4f /system/lib/libart.so (artInterpreterToInterpreterBridge+126) [armeabi-v7a]
7 #06 pc 001eecc7 /system/lib/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+326) [armeabi-v7a]
8 #07 pc 000b28a9 /system/lib/libart.so (art::JValue art::interpreter::ExecuteGotoImpl<false, false>(art::Thread*, art::DexFile::CodeItem const*, art::ShadowFrame&, art::JValue)+26112) [armeabi-v7a]
9 #08 pc 001d4e4f /system/lib/libart.so (artInterpreterToInterpreterBridge+126) [armeabi-v7a]
10 #09 pc 001eecc7 /system/lib/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+326) [armeabi-v7a]
11 #10 pc 001f2b25 /system/lib/libart.so (bool art::interpreter::DoFieldPut<(art::FindFieldType)7, (art::Primitive::Type)4, true, true>(art::Thread*, art::ShadowFrame const&, art::Instruction const*, unsigned short)+468) [armeabi-v7a]
12 #11 pc 000b2949 /system/lib/libart.so (art::JValue art::interpreter::ExecuteGotoImpl<false, false>(art::Thread*, art::DexFile::CodeItem const*, art::ShadowFrame&, art::JValue)+26272) [armeabi-v7a]
13 #12 pc 001d4e4f /system/lib/libart.so (artInterpreterToInterpreterBridge+126) [armeabi-v7a]
14 #13 pc 001eecc7 /system/lib/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+326) [armeabi-v7a]
15 #14 pc 001f0e89 /system/lib/libart.so (bool art::interpreter::DoFieldPut<(art::FindFieldType)3, (art::Primitive::Type)2, true, true>(art::Thread*, art::ShadowFrame const&, art::Instruction const*, unsigned short)+148) [armeabi-v7a]
16 #15 pc 000b2e0d /system/lib/libart.so (art::JValue art::interpreter::ExecuteGotoImpl<false, false>(art::Thread*, art::DexFile::CodeItem const*, art::ShadowFrame&, art::JValue)+27492) [armeabi-v7a]
17 #16 pc 001d4e4f /system/lib/libart.so (artInterpreterToInterpreterBridge+126) [armeabi-v7a]
18 #17 pc 001eecc7 /system/lib/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+326) [armeabi-v7a]
19 #18 pc 001f2b25 /system/lib/libart.so (bool art::interpreter::DoFieldPut<(art::FindFieldType)7, (art::Primitive::Type)4, true, true>(art::Thread*, art::ShadowFrame const&, art::Instruction const*, unsigned short)+468) [armeabi-v7a]
20 #19 pc 000b2949 /system/lib/libart.so (art::JValue art::interpreter::ExecuteGotoImpl<false, false>(art::Thread*, art::DexFile::CodeItem const*, art::ShadowFrame&, art::JValue)+26272) [armeabi-v7a]
21 #20 pc 001d4e4f /system/lib/libart.so (artInterpreterToInterpreterBridge+126) [armeabi-v7a]
22 #21 pc 001eecc7 /system/lib/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+326) [armeabi-v7a]
23 #22 pc 001f0c13 /system/lib/libart.so (bool art::interpreter::DoFieldGet<(art::FindFieldType)6, (art::Primitive::Type)6, true>(art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short)+226) [armeabi-v7a]
24 #23 pc 000b2d6d /system/lib/libart.so (art::JValue art::interpreter::ExecuteGotoImpl<false, false>(art::Thread*, art::DexFile::CodeItem const*, art::ShadowFrame&, art::JValue)+27332) [armeabi-v7a]
25 java:
26 [Failed to get Java stack]

**Comment by akarnokd** [comment]
What makes you think a core dump of C++ stacktrace without context or Java, yet alone RxJava code, allows us to help you in any capacity?
