### ISSUE TITLE
ConcatMap caches value from upstream

### ISSUE THREAD

**Issue by adrian-linca** [ReactiveX/RxJava#6617]
This issue was reproduces on RX-Java v2.2.6 and v3.0.0-RC1

I have this piece of code:

```java
@Test
public void concatMapCachedValueTest() throws InterruptedException {
  Flowable
    .interval(0, 1000, TimeUnit.MILLISECONDS, Schedulers.io())
    .onBackpressureDrop()
    .concatMap(aLong -> Flowable.just(aLong)
        .delay(3500, TimeUnit.MILLISECONDS, Schedulers.io())
    )
    .subscribe(aLong -> System.out.println(aLong));
    Thread.sleep(18000);
}
```

When I run it it prints:
0
1
4
5
11

I would expect it to print:
0
4
8
12
16

But it seems that concatMap is caching another value from the upstream while starting processing the Flowable returned by current value.
This happens even if you set the prefetch parameter of concatMap to 1, setting it to 0 is illegal.

**Comment by akarnokd** [comment]
Yes, `concatMap` has always a buffer to store one upstream element even if the inner source is still active. Try `flatMap` with `maxConcurrency = 1`.

**Comment by akarnokd** [comment]
Also if you are unfamiliar with markdown, please check my edits on your post so that you can format code properly.

**Comment by adrian-linca** [comment]
Thanks.
