### ISSUE TITLE
2.x: BehaviorProcessor.createDefault with lastElement does not emit default value

### ISSUE THREAD

**Issue by JoseLSG** [ReactiveX/RxJava#6619]
using rxjava:2.2.11.

Per docs, i'm expecting that the default value gets emitted  by the BehaviorProcessor and the lastElement() call to return this default value. The code below shows that no strings are printed out in the subscription.

Would this be a bug or a documentation update needed?

```
import io.reactivex.Maybe;
import io.reactivex.processors.BehaviorProcessor;

public class HelloWorld {

    public static void main(String[] args) {
        BehaviorProcessor<String> bp = BehaviorProcessor.createDefault("DEFAULT");
        Maybe<String> m = bp.lastElement();

        m.subscribe(System.out::println);  // no string printout
    }
}
```

**Comment by charl8182** [comment]
Ran into the same problem causing problems in production. The default value is not emitted after an invocation to _lastElement()_

**Comment by akarnokd** [comment]
Please read the [Javadocs](http://reactivex.io/RxJava/2.x/javadoc/io/reactivex/Flowable.html#lastElement--) carefully and look at the diagram. You need the source to complete in order to get the very last element. Your `BehaviorProcessor` doesn't terminate.

```java
BehaviorProcessor<String> bp = BehaviorProcessor.createDefault("DEFAULT");
Maybe<String> m = bp.lastElement();

m.subscribe(System.out::println);

bp.onComplete(); // <----------------------------------------------------
```
