### ISSUE TITLE
Observers run order issue while using observeOn() `2.x`

### ISSUE THREAD

**Issue by pkrysztofiak** [ReactiveX/RxJava#6623]
Library version 2.2.11
I have two `PublishSubject`s and two `Observer`s subscribed respectively. Between `PubslishSubject` and `Subscriber` I switch from [main] thread to [RxSingleScheduler] thread using `observeOn(Schedulers.single())`. I start to publish (`PubslishSubject.onNext()`) on both `PublishSubject`s inside the loop.

    publishSubject1.onNext("next");
    publishSubject2.onNext("next");
What I expected was the both subscribers run in the same order as emissions were published but the results I get is completely different. Subsriber1 handles all it's emissions and then Subscriber2 handles all it's emissions.
I expected emission scheduled and run in publish order. Is there any way to achive this?
```java
import java.util.concurrent.TimeUnit;

import io.reactivex.schedulers.Schedulers;
import io.reactivex.subjects.PublishSubject;

public class ObserveOnApp {
    
    public static void main(String[] args) {
        PublishSubject<String> publishSubject1 = PublishSubject.create();
        PublishSubject<String> publishSubject2 = PublishSubject.create();
        
        publishSubject1
        .observeOn(Schedulers.single())
        .subscribe(next -> {
            System.out.println("Subscriber1");
        });
        
        publishSubject2
        .observeOn(Schedulers.single())
        .subscribe(next -> {
            System.out.println("Subscriber2");
        });
        
        for (int i= 0; i < 10; i++) {
            publishSubject1.onNext("next");
            publishSubject2.onNext("next");
        }
        
        try {
            TimeUnit.SECONDS.sleep(2);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
    }
}
```

**Comment by akarnokd** [comment]
`Schedulers.single` uses a single thread and both of your subjects post work to this one thread. `observeOn` keeps working as long as it sees events so if you post events fast enough, the first subscription will get as much work done as it can, hence you don't see perfect interleaving of the two consumers.

You can try `delay(0, TimeUnit.SECONDS, Schedulers.single())` instead which posts events one by one.

**Comment by pkrysztofiak** [comment]
delay() works but I'm extremly confused. Isn't it should be the default behaviour? When calling
```
publishSubject1.onNext("next");
publishSubject2.onNext("next");
```
first line should schedule an execution. The second line should do the same and since I use the same scheduler subscriptions should interleave perfectly.

**Comment by akarnokd** [comment]
No. Any operator with a queue does as much work as it can in one run, including `observeOn`. Delay has to post events individually as it has to apply an user-defined delay to each, and there is no queue involved in RxJava for that. The underlying `ScheduledExecutorService` will interleave tasks in its own queue. Posting items individually to a thread pool is really inefficient as it causes a lot of extra allocation per task. The way RxJava does this is automatically coalescing nearby events and have one task serving them at once.
