### ISSUE TITLE
Work on Completable and if OnError perform other Completable and return this result

### ISSUE THREAD

**Issue by JitainSharma** [ReactiveX/RxJava#6624]
- library version 
     'io.reactivex.rxjava2:rxandroid:2.1.1'
     'io.reactivex.rxjava2:rxjava:2.2.6'

Execute the first Completable: 
if no error returns it
on error, execute the second Completable return result of this Completable. 

 I am doing like this, but no success as this returns asap first Completable return error, so 

```
return cartDao.insert(order)
            .doOnError {

                val orderRow = cartDao.getOrderById(order.productId, order.productVariant.variantId)
                orderRow.qty = orderRow.qty + order.qty

                //second Completable, never calls
                cartDao.update(orderRow).subscribeOn(Schedulers.io())
                    .doOnComplete {
                        Timber.e(it)
                    }
                    .doOnError {
                        Timber.e(it)
                    }
            }
```

help me to execute the second Completable over onError and return this Completable result.

**Comment by akarnokd** [comment]
Please ask such questions on StackOverflow.
