### ISSUE TITLE
2.x Calling hasNext() on a disposed blocking iterator hangs forever

### ISSUE THREAD

**Issue by BrynCooke** [ReactiveX/RxJava#6625]
Calling `hasNext()` on a a blocking iterator never returns if the iterator has been disposed. 

Tested on 2.2.11

To reproduce:
```
Iterator<Integer> iterator = Flowable.fromArray(1, 2, 3).delay(1, TimeUnit.SECONDS).blockingIterable().iterator();

System.out.println("start");
((Disposable)iterator).dispose();
iterator.hasNext(); //Hangs forever
```

**Comment by akarnokd** [comment]
Indeed, if you "hack" into that Iterator it won't work properly as it implementing Disposable is not part of the public intended API. I'll see what I can do about it in 2.x. For 3.x, it probably needs some redesign to work with try-with-resources for example.

**Comment by akarnokd** [comment]
Closing via #6626 & #6627.
