### ISSUE TITLE
System.properties access restriction.

### ISSUE THREAD

**Issue by aanton03** [ReactiveX/RxJava#6636]
I'm getting `access denied ("java.util.PropertyPermission" "*" "read,write")` error when using the IO Scheduler. 

Its coming from: 
https://github.com/ReactiveX/RxJava/blob/13772a173cb6a59643dfd5eaf023a1412f804096/src/main/java/io/reactivex/internal/schedulers/SchedulerPoolFactory.java#L93

```
static {
        Properties properties = System.getProperties();

        PurgeProperties pp = new PurgeProperties();
        pp.load(properties);

        PURGE_ENABLED = pp.purgeEnable;
        PURGE_PERIOD_SECONDS = pp.purgePeriod;

        start();
    }
```

All this seems to be from what I could see is that it's trying to get purge options from the system properties. 

```
static final class PurgeProperties {

        boolean purgeEnable;

        int purgePeriod;

        void load(Properties properties) {
            if (properties.containsKey(PURGE_ENABLED_KEY)) {
                purgeEnable = Boolean.parseBoolean(properties.getProperty(PURGE_ENABLED_KEY));
            } else {
                purgeEnable = true;
            }

            if (purgeEnable && properties.containsKey(PURGE_PERIOD_SECONDS_KEY)) {
                try {
                    purgePeriod = Integer.parseInt(properties.getProperty(PURGE_PERIOD_SECONDS_KEY));
                } catch (NumberFormatException ex) {
                    purgePeriod = 1;
                }
            } else {
                purgePeriod = 1;
            }
        }
    }
```

In my system I can't allow for read/write access to all System properties. Can this be changed to use `System.getProperty(PURGE_ENABLED_KEY)` or the like as I can allow for access to specific keys.

**Comment by akarnokd** [comment]
I'll look into it.

**Comment by akarnokd** [comment]
Fix posted for [3.x](https://github.com/ReactiveX/RxJava/pull/6637) and [2.x](https://github.com/ReactiveX/RxJava/commit/cc690ff2f757873b11cd075ebc22262f76f28459).
