### ISSUE TITLE
Feature Request: flatMapNullable

### ISSUE THREAD

**Issue by derektom14** [ReactiveX/RxJava#6643]
I think RxJava is missing a useful `flatMapNullable` operator on its main data flow classes. It would function as a combination of `filter` and `map`, the equivalent of:
```
stream.flatMapMaybe { item -> Maybe.fromCallable { function.apply(item) } }
```
Immediately obvious use cases:
```
streamOfOptionals.flatMapNullable { it.orNull() } // flattens Optional<T> into <T>, otherwise written as streamOfOptionals.filter { it.isPresent }.map { it.get() }
```
```
streamOfAnimals.flatMapNullable { it as? Dog } // equivalent to ofType<Dog> but with one operator
```

Why not use `flatMapMaybe`?

- It's much more verbose
- It requires the creation of another `Maybe` object, and the `FlatMapMaybeObserver` or `InnerObserver` object.

Basically, the same reasons we have a `flatMapIterable` method instead of always using:
```
stream.flatMapObservable { item -> Observable.fromIterable(function.apply(item)) }
```

Why not use `filter` and then `map`?

- There's often some intermediate computation involved in the output that wouldn't be passable from a `filter` to a `map`, unless you do `map` to an `Optional` and then `filter`
- Double the operators requires double the setup work and double the intermediate objects

Additionally, even though it uses nulls, it's only for filtering purposes similar to how `Maybe.fromCallable` accepts nulls. At no point does a null value ever enter an Rx stream.

I would write the operator, but I want to make sure that it's something that would be accepted first.

**Comment by akarnokd** [comment]
No. We don't want to encourage such null usages. Use flatMap with just or empty, which are optimized for. Alternatively, since youbseem to be on Kotlin, you can create an extension method for yourself and publish it as a library.
