### ISSUE TITLE
Feature Request: flatMapSequential

### ISSUE THREAD

**Issue by deripas** [ReactiveX/RxJava#6644]
Hi!
I periodically have to work with both **RxJava** and **Reactor**.
Sometimes the very absence of method in **RxJava** [flatMapSequential ](https://projectreactor.io/docs/core/snapshot/api/reactor/core/publisher/Flux.html#flatMapSequential-java.util.function.Function-int-) (as `concatMap`, only witch concurrency).
Or similar functionality is already available?

Thanks!

**Comment by akarnokd** [comment]
It is called [`concatMapEager`](http://reactivex.io/RxJava/2.x/javadoc/io/reactivex/Flowable.html#concatMapEager-io.reactivex.functions.Function-int-int-). 

Please familiarize yourself with the available features next time before requesting. Thanks.
