### ISSUE TITLE
2.x ObservableReplay NullPointerException when max buffer size is reached from concurrent threads

### ISSUE THREAD

**Issue by hujim** [ReactiveX/RxJava#6645]
Found on Versions 2.2.11~2.2.12

It seems that `ObservableReplay.java`'s `removeFirst()` can be called concurrently from multiple threads in the following thread, hence the 2nd one will encounter the null pointer.
```
 void truncate() {
        // overflow can be at most one element
        if (size > limit) {
             System.out.println("size:"+size+", limit:"+limit);
             removeFirst();
         }
 }
```
Not entirely sure what the ideal fix is, or is it never expected that callers onNext() at the same exact time?

Stacktrace:

> Caused by: java.lang.NullPointerException
> 	at io.reactivex.internal.operators.observable.ObservableReplay$BoundedReplayBuffer.removeFirst(ObservableReplay.java:616)
> 	at io.reactivex.internal.operators.observable.ObservableReplay$SizeBoundReplayBuffer.truncate(ObservableReplay.java:802)
> 	at io.reactivex.internal.operators.observable.ObservableReplay$BoundedReplayBuffer.next(ObservableReplay.java:660)
> 	at io.reactivex.internal.operators.observable.ObservableReplay$ReplayObserver.onNext(ObservableReplay.java:365)
> 	at io.reactivex.subjects.PublishSubject$PublishDisposable.onNext(PublishSubject.java:308)
> 	at io.reactivex.subjects.PublishSubject.onNext(PublishSubject.java:228)
> 	at io.reactivex.SimpleTest$3.accept(SimpleTest.java:40)
> 	at io.reactivex.SimpleTest$3.accept(SimpleTest.java:37)
> 	at io.reactivex.internal.observers.LambdaObserver.onNext(LambdaObserver.java:63)
> 	... 9 more

Repro test method:
```
 void main() {
        final PublishSubject<Long> resultPublish = PublishSubject.create();
        final TestObserver<Long> observer = resultPublish
                .replay(1)
                .autoConnect(1)
                .doOnNext(new Consumer<Long>() {
                    @Override
                    public void accept(Long it) throws Exception {
                        System.out.println(it);
                    }
                })
                .test();

        Observable.interval(0L, 30L, TimeUnit.MILLISECONDS).subscribe(new Consumer<Long>() {
            @Override
            public void accept(Long v) throws Exception {
                resultPublish.onNext(v);
            }
        });

        Observable.interval(0L, 30L, TimeUnit.MILLISECONDS).subscribe(new Consumer<Long>() {
            @Override
            public void accept(Long v) throws Exception {
                resultPublish.onNext(v);
            }
        });
        try {
            Thread.sleep(TimeUnit.MINUTES.toMillis(1));
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
    }
```

**Comment by akarnokd** [comment]
PublishSubject is not thread safe to call from multiple threads that way. Please read its JavaDocs.
