### ISSUE TITLE
Single.errror(new Exception()) in onErrorResumeNext creates RuntimeException

### ISSUE THREAD

**Issue by ChristianSchneeweiss** [ReactiveX/RxJava#6654]
Thanks for using RxJava but before you post an issue, please consider the following points:

  - [x] Please include the library version number, including the minor and patch version, in the issue text. In addition, if you'd include the major version in the title (such as `3.x`) that would be great.

  - [x] If you think you found a bug, please include a code sample that reproduces the problem. Dumping a stacktrace is usually not enough for us.

  - [x] RxJava has more than 150 operators, we recommend searching the [javadoc](http://reactivex.io/RxJava/3.x/javadoc/io/reactivex/Observable.html) for keywords of what you try to accomplish.

  - [x] If you have a question/issue about a library/technology built on top of RxJava (such as Retrofit, RxNetty, etc.), please consider asking a question on StackOverflow first (then maybe on their issue list).

  - [x] Questions like "how do I X with RxJava" are generally better suited for StackOverflow (where it may already have an answer).

  - [x] Please avoid cross-posting questions on StackOverflow, this issue list, the Gitter room or the mailing list.

I am using version 2.2.0

And the following Code fails

```
    @Test
    void checkCorrectExceptionType() {
        Single<Integer> exceptionSingle = Single.error(new Exception());
        exceptionSingle.onErrorResumeNext(throwable -> Single.error(new IOException()));
        
        assertThrows(IOException.class, exceptionSingle::blockingGet);
    }
```
with this message
`org.opentest4j.AssertionFailedError: Unexpected exception type thrown ==> expected: <java.io.IOException> but was: <java.lang.RuntimeException>`

I think the bug is somehow related to a recursive call of the onErrorResumeNext, I am not certain though.

I stumbled upon this bug when I tried to catch an Exception and create a custom Exception down the stream.

**Comment by akarnokd** [comment]
Please read the [javadoc of blockingGet](http://reactivex.io/RxJava/2.x/javadoc/io/reactivex/Single.html#blockingGet--). Any non-runtime exception is wrapped into a RuntimeException.
