### ISSUE TITLE
How to stay subscribed *while* certain types of events are emitted?

### ISSUE THREAD

**Issue by ursusursus** [ReactiveX/RxJava#6655]
I have one I cannot figure out

basically I have stream of polymorphic events, and want to subscribe a observable "while" in a given state, i.e. previous emit was event of same type, then keep the subscribtion and just proxy the event

```
Events = (A|B)
stream: A1 A2 B1 B2 B3 A3 A4 A5 B4 B5 B6
              ^------^          ^------^
              subscribed        subscribed
```
problem is how to attach the observable without resubscribing it i.e.

```
events.switchMap {
   if(it is B) {
      somethingIWant()
   } else {
      Observable.empty()
   }
}
```
which will obviously keep resubscribing somethingIwant in case of B1, B2, ...

I need it to stay subscribed during Bs, and if something else than B comes, unsubscribe

`events.ofType(B)` wont also work because it wont unsubscribe downstream in case A comes basically I want a conditional switchmap, with option to emit via already subscribed stream, whch Im not sure possible

**Comment by akarnokd** [comment]
Please do not cross post questions. https://stackoverflow.com/questions/58085829/how-to-stay-subscribed-while-certain-types-of-events-are-emitted
