### ISSUE TITLE
Completable.delay does not respect delayError=false

### ISSUE THREAD

**Issue by Maragues** [ReactiveX/RxJava#6659]
RxJava version: 2.2.12

Given this test suite

```kotlin
class KotlinSandboxUnitTest : BaseUnitTest() {

    //Test 1
    @Test
    fun `delay with delayError = false should immediately report error`() {
        val exception = Exception()
        Completable.error(exception)
            .delay(5, TimeUnit.SECONDS, TestScheduler())
            .test()
            .assertError(exception)
    }

    //Test 2
    @Test
    fun `delay with delayError = true should report error with delay`() {
        val scheduler = TestScheduler()

        val secondsDelay = 5L

        val exception = Exception()
        val observer = Completable.error(exception)
            .delay(secondsDelay, TimeUnit.SECONDS, scheduler, true)
            .test()
            .assertNoErrors()

        scheduler.advanceTimeBy(secondsDelay, TimeUnit.SECONDS)

        observer.assertError(exception)
    }
}
```

I would expect
- Test1: :white_check_mark:
- Test2: :white_check_mark:

What I actually get
- Test1: :red_circle:
- Test2: :white_check_mark:

```java.lang.AssertionError: No errors (latch = 1, values = 0, errors = 0, completions = 0)```

By modifying Test 2 a little bit, we can check that the error emission waits until the delay time has elapsed before emitting the error. The following test is green, and it should be red.
```kotlin
    @Test
    fun `delay with delayError = false should not wait to report error`() {
        val scheduler = TestScheduler()

        val secondsDelay = 5L

        val exception = Exception()
        val observer = Completable.error(exception)
            .delay(secondsDelay, TimeUnit.SECONDS, scheduler, false)
            .test()
            .assertNoErrors()

        scheduler.advanceTimeBy(secondsDelay, TimeUnit.SECONDS)

        observer.assertError(exception)
    }
```

**Comment by akarnokd** [comment]
[It does not delay error with time](https://github.com/ReactiveX/RxJava/blob/2.x/src/main/java/io/reactivex/internal/operators/completable/CompletableDelay.java#L88) but still emits it on the designated scheduler. In Test1, you should not just abandon a `TestScheduler` instance and you have to move the virtual time forward a bit or call [`triggerActions()`](http://reactivex.io/RxJava/2.x/javadoc/io/reactivex/schedulers/TestScheduler.html#triggerActions--).
