### ISSUE TITLE
subscribe throws java.lang.NullPointerException when minifyEnabled is true

### ISSUE THREAD

**Issue by Shanison** [ReactiveX/RxJava#6660]
Hi,

After upgrading some libraries, the subscribe() method will throw Null Pointer exception when minifyEnabled is set to true. If I remove minifyEnabled then the code is working fine. Basically null data is parsed to subscribe method. There are no problem with this before upgrading gradle. Anyone experienced this problem?

Below is the code that has issue. The id will be null. Again this is not the case before the upgrade and it only happens when minifyEnabled is set to true in gradle.  

 ```
     DataService.INSTANCE
          .getId()
          .subscribeOn(Schedulers.io())
          .observeOn(AndroidSchedulers.mainThread())
          .subscribe(
              id -> {
                goToView(context, id);
              },
              t -> {
                L.e("Exception happened", t);
              }
          )

```

Below are some environments

1. Android Studio v 3.5
2. Gradle V5.4.1
3. Android Gradle Plugin 3.5.0
4. android.useAndroidX=true

RXJava versions:

```
    implementation "io.reactivex.rxjava2:rxjava:2.2.12
    implementation "io.reactivex.rxjava2:rxandroid:2.1.1
    implementation "com.jakewharton.rxbinding2:rxbinding:2.2.0
    implementation "com.jakewharton.rxrelay2:rxrelay:$rootProject.ext.rx2Relay"
    implementation "com.squareup.retrofit2:adapter-rxjava2:2.1.1
```

Gradle Config
```
            shrinkResources true
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
```

**Comment by akarnokd** [comment]
It is explicitly asked not to cross post issues!

https://stackoverflow.com/questions/58200245/rxjava-subscribe-method-throws-nullpointerexception-when-minifyenabled-is-set-to

In addition, it is not an issue with the library but your tooling so you should ask such questions on StackOverflow under the relevant tags.
