### ISSUE TITLE
3.x: Proposal - Upstream AutoDispose library's core behavior into RxJava directly

### ISSUE THREAD

**Issue by ZacSweers** [ReactiveX/RxJava#6661]
We have a popular open source library called [AutoDispose](https://github.com/uber/AutoDispose). In short, it acts as a side-effect-free alternative to `takeUntil()` with some API sugar on top of it. We've worked a lot with RxJava over the years to facilitate its APIs as well, it's been a really good collaboration!

We'd like to propose upstreaming this core behavior as a disposal-only alternative API to `takeUntil()`.

## Motivation

`takeUntil()` has side effects. To abide by the Rx types' contracts it exists in, it _must_ send a completion event or `NoSuchElementException` for `Single`. It's technically accurate in both cases, but not really the desired behavior in practice and I feel it's often treated as a necessary evil to leverage `takeUntil()`'s functionality. I believe the relative popularity of AutoDispose supports this claim.

AutoDispose's API offers this behavior in a way that doesn't break this contract. Rather than expose the Rx type again for continued chaining, AutoDispose transforms the chain via `as()` (or `to()` in rx 3) to a custom `SubscribeProxy` interface that just mirrors the underlying type's subscribe methods. This prevents further chaining (so no disposing mid/down stream) and also absolves it of contract requirements since it's not actually a core Rx type/observer. It's just a mediator API at this point that the user has opted into by using this AutoDispose operator.

There is a precedent for this via `parallel()` or similar operators that return something other than an Rx type that mediates the underlying stream.

## Design

All Rx types would add a new top-level instance method similar to those found in `[AutoDispose.java](https://github.com/uber/AutoDispose/blob/master/autodispose/src/main/java/autodispose2/AutoDispose.java)`. Rather than return a Converter type though, it can just return the subscribe proxy directly since it no longer needs to lean on `as()`/`to()` operators.

```java
// Observable.java

@CheckReturnValue
@NonNull
@SchedulerSupport(SchedulerSupport.NONE)
public ObservableSubscribeProxy<T> autoDispose(CompletableSource scope) {
  // implementation
}
```

Names can always be tweaked, this is just what we use right now. Other ideas could be binding terms like `boundBy`/`bindTo`. Other APIs like the `AutoDisposeObservers` would be part of this, and the `hideProxies()` behavior would be ideal as a plugin but not a big loss.

We'd keep the unincorporated bits separate in AutoDispose still, but just make it lean on this and render it just a library for API sugar around this API. Though if you want to pull in other APIs for some reason, would be open to it! This technically could be contributed into RxJava 2 as well, unsure if that's at a feature freeze yet.

Also - feel free to completely reject this and no hard feelings. We think there's a compelling case for this core behavior to be part of RxJava's public API, but totally understand if there's hesitation to add to the API surface or if it's deemed too niche. I do think it would be at least as valuable as `takeUntil()` though :).

**Comment by akarnokd** [comment]
It looks too peculiar and for the specific needs of the Android platform (plus you seem to need to test it with an actual Android runtime). I'm not convinced.

**Comment by ZacSweers** [comment]
There are a few android artifacts but they're unrelated to this proposal (that's also where the android tests are). 

The core API being proposed here is not specific to android platform either, and just a subset of the core [`autodispose` artifact](https://github.com/uber/AutoDispose/tree/master/autodispose). It's true that much of this was built by Android developers, but that doesn't make it an Android-specific library.

I would be curious why you'd think this is too peculiar and `takeUntil()` isn't? They're effectively two sides of the same coin, but this implementation has no side effects. In practice, the code actually looks the same

```java
someObservable
    .boundTo(other)
    .subscribe()
```

**Comment by akarnokd** [comment]
What do you mean by `takeUntil` side-effect?

**Comment by ZacSweers** [comment]
Per the first paragraph of the Motivation section:

> `takeUntil()` has side effects. To abide by the Rx types' contracts it exists in, it _must_ send a completion event or `NoSuchElementException` for `Single`. It's technically accurate in both cases, but not really the desired behavior in practice and I feel it's often treated as a necessary evil to leverage `takeUntil()`'s functionality. I believe the relative popularity of AutoDispose supports this claim.

Almost every single case I've seen of `takeUntil()` before autodispose was written involved ignoring the completion event, or being surprised to receive one.

**Comment by akarnokd** [comment]
Ignoring a terminal event this way is not something to encourage with the main library. I don't see much downside having AutoDispose as its own library other than the minor inconvenience of using `to`. [I have several dozen](https://github.com/akarnokd/RxJavaExtensions#custom-operators-and-transformers) operators with this inconvenience. 

Along these lines, I'd me more inclined to add [subscribeAutoDispose](https://github.com/akarnokd/RxJavaExtensions#subscribeautodispose) so terminated flows don't leak via the composite unnecessarily longer.

**Comment by ZacSweers** [comment]
Yes, and my point in the motivation section was that `takeUntil()`'s behavior invites the user to ignore it anyway because they have no other recourse if they want its primary functionality. AutoDispose doesn't encourage ignoring a terminal event. It is a disposal mediator and behaves purely as a pass-through for events until a scope completion event (if it is not already terminated).

`subscribeAutoDispose` appears to be a different use case, despite the similar name.

**Comment by akarnokd** [comment]
One is supposed to dispose the end consumer (`DisposableObserver`, etc) to prevent it from receiving further events. AutoDispose just moved this one step up and had to introduced a separate terminal API so that one doesn't hang a follow-up chain.

I would instead create a class `ScopedObserver` that takes the relevant arguments and have users subscribe with it instead of the default:

```java
source.subscribeWith(
    new ScopedObserver<Integer>(
        otherSource, 
        next -> { }, error -> { }, () -> { }
    )
);
```

Think of it as a buffed up `DisposableObserver` which is already employed by users. Of course, being an end consumer, such scoped implementation don't have to live in RxJava proper either and can have as large API surface due to combinatorial options (6 types of source x 6 types of until x 4 consume options) as needed.

**Comment by ZacSweers** [comment]
That seems like just a less ergonomic alternative to AutoDispose's API. 

I'm curious to know why you think scope shouldn't be part of RxJava's core API? If anything, a more opinionated adoption of something like the above would vastly elevate RxJava 3's value prop vs just sticking with 2. This would also make it more competitive with something like Kotlin coroutines' structured concurrency, a pattern that's embraced at a core level in its API and quite powerful. 

AutoDispose' API doesn't go quite that far here as far (coroutines _only_ allows you to work under a scope), but it does at least offer similar functionality where there's clearly a demand for it. In this proposal, it would make it idiomatic as well rather than requiring a separate library or custom combinatorially-exploding observer.

**Comment by akarnokd** [comment]
After considerations, I have decided not to include AutoDispose's API in RxJava proper. 

The programming style is not well aligned with RxJava's, the surface API would increase considerably to support a narrow use case and there are introspection/hooks involved that add another dimension of complications. 

The proposed functionality is better served in a separate library like it is done now where one can extend the API for more bindings to other sources more freely at the small inconvenience of applying the functionality via `to` or using Kotlin with extension methods.
