### ISSUE TITLE
State of affairs

### ISSUE THREAD

**Issue by xificurC** [ReactiveX/RxJava#6667]
Szia David :)

I know this isn't the best place but I haven't found a better place, so here goes.

The JVM seems to be blessed with 2 high profile reactive libraries, rxjava and reactor. It seems you played a crucial role in both of them. The tone on the internet suggests that the new(er) kid is the one to pick if one has an option. But rxjava 3 is on its way too. When is it due by the way?

And so the blessing turns into a curse - for a newbie it makes it hard to decide which one to pick. Would it be rude to ask you, who knows the field better than probably anyone, what are the main differences between the 2 options right now?

**Comment by akarnokd** [comment]
Üdv!

The main deciding factor is if you can use Java 8+ or not. Reactor Core 3+ requires Java 8 runtime and integrates with Java 8 features (Stream, CompletableFuture) directly. In addition, they have [context support](https://projectreactor.io/docs/core/release/reference/#context) and integrates with Spring directly and without extra overhead.

RxJava 3 will be released end of this December or early January and is planned to keep supporting Java 6. If the Android ecosystem adds Java 9 support in some overarching fashion (i.e., standard backport/compat libraries) till then, we'd most likely switch to a Java 9 baseline with 3.

The programming style is pretty much the same and learning one will get you learn the other one much easier.

**Comment by xificurC** [comment]
So you're saying if one can afford java 8 one should pick reactor?

I'm running 8+ exclusively, but I like the richer types compared to reactor's mono and flux. But if the community is moving towards reactor I'm just asking for trouble integrating with other solutions. In the end I'm looking for the pragmatic choice but as a newcomer it's hard to decide.

**Comment by akarnokd** [comment]
It depends on what other libraries you plan to use. Some support both RxJava and Reactor in some way, some have decided for one or the other. RxJava and Reactor can live side by side and they can interoperate seamlessly thus, you can use RxJava's `Observable` for UI while using `Flux` for data accesses.

**Comment by xificurC** [comment]
I'm sorry, I know these questions are not well suited here. Even though you are the maintainer of one of the projects I trusted your answers will be objective.

At present some features are hard to compare, mainly because rxjava's readme is much shorter compared to reactor's user guide, e.g. debugging. I guess you are understaffed compared to reactor. I'd love to use both projects and compare them in the real world, but time is a precious commodity.

Koszonom a segitseget :)
