### ISSUE TITLE
3.x Proposal: Abstract out Scheduling logic from developer

### ISSUE THREAD

**Issue by pradeepsng30** [ReactiveX/RxJava#6669]
### 3.x Proposal: Abstract out Scheduling from the developer

**Current Behaviour**
Developers need to specify how they want to schedule the task using `subscribeOn` or `observeOn` APIs with the options available in [`Schedulers`.](https://github.com/ReactiveX/RxJava#schedulers) 

**Proposal**
Make RxJava smart enough to identify the type of task and apply schedulers accordingly. Especially for the tasks involving I/O RxJava should automatically schedule it with `Schedulers.io()`.
Or there could be an option given `Schedulers.auto()` which specifically tells RxJava to Schedule smartly.

**Comment by akarnokd** [comment]
This is impossible.
