### ISSUE TITLE
Observable blocks in case of throwing java.lang.Error, version 2.2.13

### ISSUE THREAD

**Issue by yklymenko** [ReactiveX/RxJava#6686]
I did the test with 2.2.13. Older versions, for example 2.2.8 have the same problem. 

Following code reproduces the problem:

```
import io.reactivex.Observable;
import io.reactivex.Scheduler;
import io.reactivex.schedulers.Schedulers;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import org.junit.Test;

public class TestError {

  @Test
  public void testError() {

    ExecutorService executors = Executors.newFixedThreadPool(4);
    try {

      Scheduler scheduler = Schedulers.from(executors);

      Throwable t = Observable.just(1, 2, 3).flatMap(i -> Observable.just(i).subscribeOn(scheduler).map(k -> {
        if (k == 2) {
//          throw new StackOverflowError("e");
          throw new OutOfMemoryError("e");
//          throw new RuntimeException("e");
        } else {
          return k;
        }
      }), 3).ignoreElements().blockingGet();

      System.out.println(t);

    } finally {
      executors.shutdown();
    }
  }
}
``` 
The problem is not occured in case of RuntimeException.

**Comment by akarnokd** [comment]
There is a category of errors RxJava considers fatal and does not turn them into `onError`s; see[Exceptions.throwIfFatal](http://reactivex.io/RxJava/2.x/javadoc/io/reactivex/exceptions/Exceptions.html#throwIfFatal-java.lang.Throwable-). 

Such errors are unrecoverable in general (allocation failure can lead to more allocation failure while trying to handle/report that failure). If for some reason you think you can recover from them, wrap them into `RuntimeException`s.

**Comment by yklymenko** [comment]
> There is a category of errors RxJava considers fatal and does not turn them into `onError`s; see[Exceptions.throwIfFatal](http://reactivex.io/RxJava/2.x/javadoc/io/reactivex/exceptions/Exceptions.html#throwIfFatal-java.lang.Throwable-).
> 
> Such errors are unrecoverable in general (allocation failure can lead to more allocation failure while trying to handle/report that failure). If for some reason you think you can recover from them, wrap them into `RuntimeException`s.

I understood your point, but I've expected that the application in this case will not hold in "blockingGet" forever. I don't see errors. It is frozen.

**Comment by akarnokd** [comment]
It is one of the unsolvable problems; unblocking implies receiving a terminal event but a fatal error indicates the system is in an unreliable state. So either you don't crash into RxJava, apply the `timeout`  operator to a flow or use `blockingGet(time, unit)`.

**Comment by yklymenko** [comment]
> It is one of the unsolvable problems; unblocking implies receiving a terminal event but a fatal error indicates the system is in an unreliable state. So either you don't crash into RxJava, apply the `timeout` operator to a flow or use `blockingGet(time, unit)`.

But in case of blocking get, I will never receive the original exception. It's dissapear. Actually this is my  main problem.  You ignore this exception, which might be ok, but in the flow I can not catch it anymore. It even worse in case of OutOfMemory, because application doing "nothing" without any feedback. The solution to wrap each "map/flatMap" with try/catch für OutOfMemory checks looks not so good

**Comment by akarnokd** [comment]
This type of exception should bubble up to the thread's uncaught exception handler eventually. You can detect any of those with `https://docs.oracle.com/javase/7/docs/api/java/lang/Thread.html#setDefaultUncaughtExceptionHandler(java.lang.Thread.UncaughtExceptionHandler)`.

> wrap each "map/flatMap" with try/catch für OutOfMemory checks looks not so good

Introduce an utility function that does this wrapping for you:

```java
public static <T, R> Function<T, R> checked(Function<T, R> f) {
    return v -> {
         try {
             return f.apply(v);
         } catch (Error e) {
             throw new RuntimeException(e);
         }
    };
}

source.map(checked(v -> {
    if (k == 2) {
//          throw new StackOverflowError("e");
          throw new OutOfMemoryError("e");
//          throw new RuntimeException("e");
    } else {
        return k;
    }
}));
```
