### ISSUE TITLE
Hundreds of RxCachedThreadS

### ISSUE THREAD

**Issue by changxiangzhong** [ReactiveX/RxJava#6688]
Hi thank you very much for this amazing project. Our product is using this framework and we have delivered into the market with great success. 

However we have observed considerable amount of Exception among our users. 
```
OutOfMemoryError: pthread_create (1040KB stack) failed: Try again
```
On some of our test devices, we found that we get 200+ *RxCachedThreadS*. listed as following
```
android_device:/ $ ps -t 26731 |grep RxCachedThread| wc -l                                                                                                                                                  
201
```

My opinion is those cached threads is way too much. I found a relevant article [here](https://stackoverflow.com/questions/31294431/schedulers-io-creates-hundreds-of-rxcachedthreadschedulers). I've made sure every `Observable.create` calls the `onComplete` method. But the issue persists. 

Can you please provide some suggestions which orientation shall we look into? 

We are using RxJava:2.1.8 and RxAndroid:2.0.1

**Comment by akarnokd** [comment]
Please, do a thread dump and see where those threads are stuck.

**Comment by changxiangzhong** [comment]
@akarnokd Thank you very much for the guidance. I'll do that within 24 hours

**Comment by changxiangzhong** [comment]
```
"RxCachedThreadScheduler-8" daemon prio=5 tid=64 Waiting
  | group="main" sCount=1 dsCount=0 obj=0x159c59d0 self=0x89e61100
  | sysTid=7765 nice=0 cgrp=default sched=0/0 handle=0x7dcfa920
  | state=S schedstat=( 0 0 0 ) utm=1 stm=0 core=1 HZ=100
  | stack=0x7dbf8000-0x7dbfa000 stackSize=1038KB
  | held mutexes=
  at java.lang.Object.wait!(Native method)
  - waiting on <0x0cb0e8e6> (a java.lang.Object)
  at java.lang.Thread.parkFor$(Thread.java:2127)
  - locked <0x0cb0e8e6> (a java.lang.Object)
  at sun.misc.Unsafe.park(Unsafe.java:325)
  at java.util.concurrent.locks.LockSupport.park(LockSupport.java:161)
  at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2035)
  at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1091)
  at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1084)
  at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1058)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1118)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
  at java.lang.Thread.run(Thread.java:761)

```
It seems like a thread is `wait()` for another thread to `notify()` forever.

Is there options to print all the *observeOn* and *subscrieOn* threads?

**Comment by akarnokd** [comment]
That stacktrace indicates an idle threadpool worker, so it seems you have hung or infinite sources. Are you using Observables with Room or some other Android database?

> Is there options to print all the observeOn and subscrieOn threads?

There is no way to correlate worker threads with flows out of box.

You could apply `timeout` to your flows and see which doesn't terminate in a reasonable time.

**Comment by changxiangzhong** [comment]
No, we are not using ROOM, we are just using sqlite. Can I make the conclusion that creating a `Subject`/`Observable` without invoking `onComplete` could introduce a leak? Especially the `subscriber` does not `unsubscribe()`.

**Comment by changxiangzhong** [comment]
My guess is this issue is caused by `Observable` not calling the `onComplete()` method. Is there any way to correlate worker threads with flow?

**Comment by akarnokd** [comment]
If a source never ends (never calls `onComplete`) or a `subscribe` is never disposed, you got a leak.

> Is there any way to correlate worker threads with flow?

You could try and change the current thread's name to something that makes it easier to find in thread dumps later:

```java
source.doOnEvent(e -> {
    String name = Thread.currentThread().getName();
    if (name.startsWith("RxCached")) {
        int idx = name.indexOf("|");
        if (idx >= 0) {
             name = name.substring(0, idx + 1);
        } else {
             name += "|";
        }
        Thread.currentThread().setName(name + "This is the flow doing X because of Y");
    }
})
```

**Comment by changxiangzhong** [comment]
Thank you @akarnokd. It's really helpful

**Comment by changxiangzhong** [comment]
Thread **NOT** recycled even `doAfterTerminate()` have been invoked.

```
Observable.create{
    println(getThreadPid())
    ...
}.subscribeOn(Schedulers.io())
.doAfterTerminate{println("Observable completed")}
```
The pattern in our code is like above mentioned. To detect *thread leak*, we print out the *pid* so that we can detect if the thread is recycled through `ps -t $app_pid` after a force gc.

The result is bit discouraging - we've confirmed the `doAfterTerminate()` has been invoked. But the thread was **NOT** recycled.

Can you please comments on this issue?

**Comment by radityagumay** [comment]
in my case, this basically happens due to the source never emit an emission to the upstream and eventually leading to a thread waiting. in order to `fix` that I'd install a `timeout`

**Comment by daixj** [comment]
> Thank you @akarnokd. It's really helpful

how to solve this question?
