### ISSUE TITLE
Memory Leak observables 2.x/3.x

### ISSUE THREAD

**Issue by ldrrp** [ReactiveX/RxJava#6691]
I am having this issue, my applications uses many long running observable that i cant dispose of. I need them to run for service checks etc. My problem is that there is a leak and each one i have just amplifies that leak. My application is designed to run 24/7/365 on a kiosk machine so a slight leak can grow over a day or so and cause problems.

'io.reactivex.rxjava2:rxandroid:2.1.1'
'io.reactivex.rxjava2:rxjava:2.2.13'
Test device Android 7.1.2

This is a simple example of one I checked with the functions commented out and its leaking.

```
Observable.timer(60, TimeUnit.SECONDS)
            //.subscribeOn(Schedulers.io())
            //.concatMap { validateNetwork(context) }
            .subscribe({
              //Timber.tag(SUBTAG).i("Network check complete")
            }, {
              //Timber.tag(SUBTAG).e(it, "Error -> ${it.message}")
            })
```

As you can see over the course of 10 minutes it has managed to keep leaking. even before the actual 60 interval was hit.

![image](https://user-images.githubusercontent.com/985837/67780063-edbb4b80-fa3b-11e9-9174-75c1b81ccb41.png)

**Comment by ldrrp** [comment]
@akarnokd idk if it matters but i also have the same result on 3.0.0-RC4

**Comment by akarnokd** [comment]
Can you do a memory snapshot and see what objects are being held up? Also [`timer`](http://reactivex.io/RxJava/2.x/javadoc/io/reactivex/Observable.html#timer-long-java.util.concurrent.TimeUnit-) is one-shot so there is no reason the example should leak any reachable objects.

**Comment by ldrrp** [comment]
![image](https://user-images.githubusercontent.com/985837/67781849-59061d00-fa3e-11e9-9383-015b01975c12.png)

**Comment by akarnokd** [comment]
You have a lot of task schedules in your app but a 1 minute interval should not create 12,000 futures. Could you share your project or a standalone project demonstrating the problem?

**Comment by ldrrp** [comment]
Thats tricky, Its not my project to share. Ill see what i can conjure up standalone

**Comment by ldrrp** [comment]
I have stripped the application from all crud and left the one observable in there. ran the profiler and the leak is still there. Keep in mind that this is running under a service that needs to be started. You can start it in the menu bar top right of the app.


[Check.zip](https://github.com/ReactiveX/RxJava/files/3784652/Check.zip)

**Comment by akarnokd** [comment]
I'm unable to run this app as I'm getting 

> The application could not be installed: INSTALL_FAILED_NO_MATCHING_ABIS Installation failed due to: 'null'"

When I tried to run on an Nexus 5 x86 API 26 emulator. Workarounds I've found didn't work.

Did you try removing the RxJava code, but not the service and see if you have a leak or not?

**Comment by ldrrp** [comment]
Yea with that observable commented out it pretty much flatlines memory usage the entire time.

**Comment by ldrrp** [comment]
As for your running issue, yea i haven't really tried it in an emulator. Maybe your missing some of the sdk tools?

Im downloading the Nexus 5 x86 API 26 image now, to try it out in that

**Comment by ldrrp** [comment]
@akarnokd  You might want to try deleting my local.properties file, sorry.

**Comment by akarnokd** [comment]
I removed `org.apache.directory.studio:org.apache.commons.io:2.4` based on the hint of [this post](https://stackoverflow.com/a/52336575/61158).

I let it run for 10 minutes and 52.7 MB flat.

**Comment by ldrrp** [comment]
are you saying theres no leak in the emulator? i removed that apache line but no luck. i cant seem to download 8.0 image fast enough. But my boxes are 7.1.2.

**Comment by akarnokd** [comment]
No leak. Without seeing more RxJava code of yours, I don't think I can help you much. Maybe GC didn't trigger for 10 minutes for you, hence the appearance of a leak?

**Comment by ldrrp** [comment]
So after leaving it running under profiler for a longer period i notice GC runs every 30 minutes so i may have to force it inside manually. But still if i look at the low points on my graph its 
4895 - 4903 - 4911, about 8 bytes every 30 minutes. Technically a leak if GC couldn't clear it

**Comment by ldrrp** [comment]
So ive given up on rxjava. Moving towards Handler()

After about 24 hours worth of profiling i charted a comparison of the two at each low point where gc was run. This is definitely a leak. 

![image](https://user-images.githubusercontent.com/985837/67858083-b78ad400-faee-11e9-8da3-1301e2165662.png)

**Comment by akarnokd** [comment]
I can't help you with this without seeing the actual code or something that represents your code and reproduces the issue.

**Comment by ldrrp** [comment]
I can see why u think its flat. I was able to finally download the emulator image and the profiler is different for this android version. Enable full allocation tracking and watch the allocated counter in bytes. You will notice it gradually increasing. When u see a GC run hover over the lowest point and look at the allocated count. it will always be increasing.

![image](https://user-images.githubusercontent.com/985837/67873274-94b9e900-fb09-11e9-8232-910886788841.png)

**Comment by akarnokd** [comment]
I'd presume allocation count is cumulative over the lifetime so GC won't zero it. Also it is possible System.gc() on Android does nothing or doesn't do it just then. By the way, in the class dump, I don't see RxJava related classes which would otherwise accompany scheduled tasks.

**Comment by ldrrp** [comment]
No allocated is current. it drops when gc is run

**Comment by akarnokd** [comment]
I don't see any indication of a leak. You are probably seeing the work of the purge thread which runs every second by default and thus a fresh task is created by Java's executor service upon each run. You could check its effect by changing the `rx2.purge-period-seconds` system property (see [Schedulers](http://reactivex.io/RxJava/2.x/javadoc/io/reactivex/schedulers/Schedulers.html) javadoc).

**Comment by andreyfomenkov** [comment]
FYI, I created a plugin that shows up a list of leaked Disposable subscriptions in a detailed HTML report. See post on Medium: [Detect Leaked Subscriptions in RxJava code using RxDisposableWatcher](https://andrey-fomenkov.medium.com/find-leaked-subscriptions-in-rxjava-code-using-rxdisposablewatcher-8c2226dce01c)
