### ISSUE TITLE
3.x: Add assertValuesAndClear back to TestObservers

### ISSUE THREAD

**Issue by BraisGabin** [ReactiveX/RxJava#6693]
At 1.x there was the function [`assertValuesAndClear`](https://github.com/ReactiveX/RxJava/blob/1.x/src/main/java/rx/observers/AssertableSubscriber.java#L226-L235) and it was really handy. I propouse to bring it back.

I know that there was a survey talking about the all the test part but I think that this topic was not included there.

The point is that I have a lot of tests like this:

```kotlin
val test = observable.test()
test.assertValues("a", "b", "c")

subject.doSomething()
test.assertValues("a", "b", "c", "d", "e")
```

With my proposal this code would be:

```kotlin
val test = observable.test()
test.assertValuesAndClear("a", "b", "c")

subject.doSomething()
test.assertValuesAndClear("d", "e")
```

At this sample it doesn't seems a huge different but those varibles could be more difficult to instantiate. And it force you to repeat a lot of code. If I could "clean" my stream I can do the first part of the test in a function and call it for every test and then I just need to care about the important part of this test.

There are libraries that find its own solution to this problem, for example [RxBindings](https://github.com/JakeWharton/RxBinding/blob/master/rxbinding-leanback/src/androidTest/java/com/jakewharton/rxbinding3/leanback/RxSearchEditTextTest.java#L30), and I think that they could use this new feature.

**Comment by akarnokd** [comment]
There is currently no plan to expand the test assertion APIs. Users should extend `TestObserver` with methods they need (through a subclass or extension methods). You can clean the list with `values().clear()`.

**Comment by BraisGabin** [comment]
Oh! I didn't know that `values().clear()` does the trick. With that it's enought I think. We are enable to implement it if we want and we keep the default API clean 👍.

**Comment by arturdryomov** [comment]
@akarnokd, WDYT about providing a public `BaseTestConsumer` `clear` method? While `values().clear()` works right now it’s based on implementation details. If the underlying `List` will become immutable this workaround will cease to exist.

**Comment by akarnokd** [comment]
They won't. An immutable values would mean copy on every onNext and huge test time wasted on longer sequences produced by datarace tests for example.
