### ISSUE TITLE
3.x: update javadoc for observeOn to mention its eagerness

### ISSUE THREAD

**Issue by akarnokd** [ReactiveX/RxJava#6697]
`Flowable.observeOn` and `Observable.observeOn` try to do as much event delivery as they can.
Add a section explaining this property to all these multi-valued `observeOn` overloads:

"This operator keeps emitting as many signals as it can on the given Scheduler's Worker thread, which may result in a longer than expected occupation of this thread. In other terms, it does not allow per-signal fairness in case the worker runs on a shared underlying thread. If such fairness and signal/work interleaving is preferred, use the `delay` operator with zero time instead."

Also link to the `@see #delay(long,TimeUnit,Scheduler)`.

**Comment by JosemyDuarte** [comment]
Hi! Do we only need to add the quoted message in both classes? I can do it if it is ok.

**Comment by akarnokd** [comment]
> I can do it if it is ok.

Sure.

> Do we only need to add the quoted message in both classes?

`Single`, `Maybe` and `Completable` can signal only one event and thus can't exhibit the property described.

**Comment by JosemyDuarte** [comment]
Hi @akarnokd! Just one silly question: 

When you say 

> Add a section explaining this property to all these multi-valued observeOn overloads

You mean all but `observeOn(Scheduler scheduler)`, right?

In any case, I just created a PR with what I understood was required. Please, if there is something wrong let me know to fix it.

Thanks

**Comment by ArtyomBasharkevich** [comment]
@akarnokd could you take a look at this?
https://github.com/Polidea/RxAndroidBle/issues/628
You can just test my last example, your suggestion to use `delay()` did not help me solve the problem.
