### ISSUE TITLE
Java 11 support

### ISSUE THREAD

**Issue by vinayak-kuchekar** [ReactiveX/RxJava#6701]
Hello,
We are currently using the rxjava.jar version 1.2.4 in our project. This version as well as the latest version (1.3.8) are not safe to use with Java 11. Following is the jdeps report:
rx.internal.util.unsafe                            -> sun.misc                                           JDK internal API (jdk.unsupported)

Is there any plan for java 11 support in upcoming library version?

**Comment by akarnokd** [comment]
RxJava 1.x is no longer supported. There was a system property to disable unsafe usage: `rx.unsafe-disable` at runtime.

RxJava 2.x onward doesn't use unofficial APIs and thus is safe for newer JDKs.
