### ISSUE TITLE
DeferredScalarDisposable calls onNext() with null value [RxJava 2]

### ISSUE THREAD

**Issue by vRallev** [ReactiveX/RxJava#6702]
There's a similar issue that has been closed #6059, but I still see the problem. `DeferredScalarDisposable [emits a null](https://github.com/ReactiveX/RxJava/blob/2.x/src/main/java/io/reactivex/internal/observers/DeferredScalarDisposable.java#L79) value.

I use a custom `Observer` as proxy in `RxJavaPlugins.setOnObservableSubscribe()`. `onNext()` is [marked as non-null](https://github.com/ReactiveX/RxJava/blob/2.x/src/main/java/io/reactivex/Observer.java#L99), but the value actually is null. This is especially problematic with Kotlin. You can't force the code to accept a null value, because these are different types.

**Comment by akarnokd** [comment]
How is your proxy implemented? RxJava uses fusion which internally calls `onNext(null)` to indicate the shared queue can be polled. The [documentation](https://github.com/ReactiveX/RxJava/wiki/Writing-operators-for-2.0#operator-fusion) about writing operators warns about plain forwarding.

**Comment by vRallev** [comment]
It directly delegates the method call to the original Observer.
```kotlin
  private class ObserverProxy(
    private val original: Observer<Any>
  ) : Observer<Any> by original {
    override fun onSubscribe(d: Disposable) {
      addDisposables(d, original)
      original.onSubscribe(d)
    }
  }
```
Which results in this crash
```
java.lang.IllegalArgumentException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkParameterIsNotNull, parameter p0
at com.squareup.rx2.utilities.RxClass$ObserverProxy.onNext(RxClass.kt)
at io.reactivex.internal.observers.DeferredScalarDisposable.complete(DeferredScalarDisposable.java:79)
at io.reactivex.internal.operators.observable.ObservableFromCallable.subscribeActual(ObservableFromCallable.java:53)
```

**Comment by akarnokd** [comment]
This is not allowed: `original.onSubscribe(d)`. You have to supply a fresh `Disposable` so fusion doesn't come into play. The `ObserverProxy` could implement `Disposable` itself and delegate to the `Disposable` received in `onSubscribe`.

As for `null`, we can't do much about it. This is not an issue in Java so maybe you could write the proxy in Java as well.

**Comment by vRallev** [comment]
Got it, I'll fix that. For anyone wondering, this is my workaround. I created this interface in Java:
```java
interface ObserverFix<T> extends Observer<T> {
  @Override void onNext(@Nullable T t);
}
```
And then the implementation looks like this:
```kotlin
  private class ObserverProxy(
    private val original: Observer<Any>
  ) : ObserverFix<Any>, Observer<Any> by original {
    override fun onSubscribe(d: Disposable) {
      DelegateDisposable(d).run {
        addDisposables(this, original)
        original.onSubscribe(this)
      }
    }
  }
```
