### ISSUE TITLE
[3.0 Suggestion / Question] Should RxJava 3 prefer locks over synchronized blocks?

### ISSUE THREAD

**Issue by slisaasquatch** [ReactiveX/RxJava#6707]
I just watched [this talk about Project Loom](https://www.youtube.com/watch?v=lIq-x_iI-kc), and one thing he mentioned is that locks work better with Project Loom compared to synchronized blocks. RxJava 2/3 still uses synchronized blocks in quite a few places and barely use locks. Are those worth replacing? Or do synchronized blocks perform better?

**Comment by akarnokd** [comment]
No. Loom requires the lock to be in a fiber scope. Our locks and synchronized blocks are generally short and infrequent enough to not cause too much trouble. 

The place that mattered, namely the blocking operations, already use locks so running them in a fiber scope by the user is already compatible.

[This project shows](https://github.com/akarnokd/RxJavaFiberInterop) what it takes to make operators with fiber scope.
