### ISSUE TITLE
2.x PublishSubject Emissions are dropped in observeOn

### ISSUE THREAD

**Issue by rluick15** [ReactiveX/RxJava#6716]
Version: 2.2.10

Hello, having a bit of an issue with my PublishSubject flow. Basically I have two items being emitted into my subject in quick succession(theoretically at almost the same time), and one is occasionally being dropped in the observeOn call. Here's my code:

```
        subject
            .doOnEach {
                  Timber.d("before ${it.emissionName}")
            }
            .observeOn(Schedulers.single())
            .doOnEach {
                  Timber.d("after ${it.emissionName}")
            }
            .map { item -> mapper.map(item) }
            .subscribe({
                //handle subscribe
            } {
                //handler error
            })

```

I placed doOnEach with logs before and after every method and was able to see that both emissions are present before observeOn is called, but one is dropped afterwards. I have tried adding onBackpressureBuffer prior to observeOn, but the problem persisted.

Other things to note:

- As mentioned these items are being emitted at basically the same time.
- This isn't 100% reproducible, happens frequently enough though ~1/10
- Only one subscriber
- These specific emissions are being called from the same thread
- There are many other places emitting to this stream while this is going on. Everything else seems chill, but these two emissions are having issues.

**Comment by akarnokd** [comment]
Please verify that you don't call `onNext` from multiple threads. Concurrent `onNext` calls are [not allowed](http://reactivex.io/RxJava/2.x/javadoc/io/reactivex/subjects/PublishSubject.html).

**Comment by rluick15** [comment]
Yep, looks like that was the issue. I mistakenly thought I was posting from the same thread, in fact it was separate threads on the rx computation pool. Thanks for the intel, this was helpful
