### ISSUE TITLE
NullPointerException in BasicFuseableObserver 

### ISSUE THREAD

**Issue by vRallev** [ReactiveX/RxJava#6717]
We're sometimes seeing this exception
```
java.lang.NullPointerException: Attempt to invoke interface method 'boolean io.reactivex.disposables.Disposable.isDisposed()' on a null object reference
at io.reactivex.internal.observers.BasicFuseableObserver.isDisposed(BasicFuseableObserver.java:157)
at com.squareup.rx2.utilities.RxKillSwitchRule$DelegateDisposable$dispose$1$1.invoke(RxKillSwitchRule.kt:189)
at com.squareup.rx2.utilities.RxKillSwitchRule$DelegateDisposable$dispose$1$1.invoke(RxKillSwitchRule.kt:183)
```

In #6702 you already mentioned that fusion could be a problem and I implemented a Disposable proxy, but this issue happens nonetheless. Is this a bug on our side or a rare use case? It's also possible I misunderstood you. 

The code simplified looks like this:
```
  private inner class ObserverProxy(
    private val originalObserver: Observer<Any>
  ) : ObserverFix<Any>, Observer<Any> by originalObserver {
    override fun onSubscribe(d: Disposable) {
      val delegateDisposable = DelegateDisposable(d)
      addDisposables(delegateDisposable, originalObserver)
      originalObserver.onSubscribe(delegateDisposable)
    }
  }

  private fun addDisposables(
    d: Disposable,
    originalObserver: Any
  ) {
    _disposables += WeakReference(d)
    if (originalObserver is Disposable) {
      _disposables += WeakReference(originalObserver)
    }
  }

  // Wrap disposables / subscriptions to avoid problems with operator fusion,
  // see https://github.com/ReactiveX/RxJava/issues/6702#issuecomment-550512032
  private inner class DelegateDisposable(private val delegate: Disposable) : Disposable by delegate {
    override fun dispose() {
      delegate.dispose()

      synchronized(monitor) {
        // Clean up WeakReferences that either are disposed or don't contain a reference anymore.
        _disposables.removeAll { it.get()?.isDisposed ?: true }
      }
    }
  }
```
The crash happens in this line `_disposables.removeAll { it.get()?.isDisposed ?: true }`.

**Comment by akarnokd** [comment]
It appears you call `isDisposed` on a `BasicFuseableObserver` before it has subscribed and received a proper `Disposable` via its `onSubscribe`.

**Comment by vRallev** [comment]
Yes, that is possible. I see this for other Observer implementations, too. It happens randomly. Shouldn't these implementations handle that instead of crashing?

**Comment by akarnokd** [comment]
No. You are basically hacking into the flow and interacting with implementations not designed to be disposed at anytime. Why do you even have the `originalObserver is Disposable` check?

**Comment by vRallev** [comment]
Without this check this pseudo code would fail.
```
Rule setup and wrap all observers

val disposable = Observable.never<Nothing>().subscribe()
assertThat(disposable.isDisposed).isFalse()

Dispose all disposables

assertThat(disposable.isDisposed).isTrue()
```
The last check would fail.

**Comment by akarnokd** [comment]
You'll have to identify the end subscribers by type in the proxy.

**Comment by vRallev** [comment]
I see. But I think that makes it more difficult and I'm afraid to miss certain types. The easier solution probably is to wrap things in a try-catch block for now.
