### ISSUE TITLE
Improve the CompositeDisposable

### ISSUE THREAD

**Issue by djohannot** [ReactiveX/RxJava#6718]
This message is a proposal to add a functionality to have a method `addDistinct` for the disposable, using a mechanism of tag that will release any previous recorded disposable with the same tag.

Does this idea makes sense for other developers?

**Comment by akarnokd** [comment]
No. Why would your disposables have identity like that? What is your use case? You could implement any form of disposable container based on `CompositeDisposable`'s source.
