### ISSUE TITLE
Observable vs Flowable on Interfaces With Unknown Implementations

### ISSUE THREAD

**Issue by pixelshaded** [ReactiveX/RxJava#6724]
We have a base library which provides interfaces for repository / database access and some basic implementations. In the case of getOne, insert, update, and delete, these all make sense as singles / maybes. However in the case of getAll for instance, this could be a ```Single<List<Model>>``` or ```Observable<Model>```. We considered using single, since that's usually how our data is consumed, but these interfaces could hold implementations that support streaming, so using single would essentially prevent those types of implementations from being realized. The consumer can always use the ```toList``` operator if they dont want to consume it like a stream or need all the results for business logic. 

So now where we are stuck is whether or not these interfaces should return Observables or Flowables. From what I understand, the main difference between the two is that Flowables have added overhead which allow a Consumer to control the rate at which a Producer emits items, where as an Observable does not and will just emit as quickly as possible.

Would it make sense then to always return lower overhead Observables from these interfaces, and to leave it up to the consumer to use ```toFlowable``` if they need control over the rate of the Producer? Would this even work or would the Observable consume memory with its unbounded buffer (potential out of memory issues) before being converted to a Flowable which has bounded buffers?

**Comment by akarnokd** [comment]
You can always unbound `Flowable` or turn it into a `Single`. Rebounding an `Observable` will be still prone to excessive memory usage. There isn't that much of an overhead difference between `Flowable` and `Observable` otherwise.

**Comment by pixelshaded** [comment]
It seems then, based on docs, that Flowable is essentially what Observable was in rxjava1, and now Observables are just an alternative to something like Java8 streams. Is that accurate?

**Comment by akarnokd** [comment]
> Flowable is essentially what Observable was in rxjava1

Yes.

> Observables are just an alternative to something like Java8 streams

No, they are for cases where there can't be a reasonable backpressure (UI events) or backpressure doesn't matter due to short sequences.

**Comment by pixelshaded** [comment]
Thanks for the quick replies.
