### ISSUE TITLE
[Suggestion/Question] Replace wildcard imports?

### ISSUE THREAD

**Issue by slisaasquatch** [ReactiveX/RxJava#6725]
I just noticed that wildcard imports are heavily used in this project. Is there a good reason for doing that? I think most people agree that using wildcard imports is a bad practice.

**Comment by akarnokd** [comment]
We use wildcard imports to reduce the noise in PRs. It was especially bad with the main java files (`Flowable`, etc.) as multiple PRs targeting the same file would conflict on import changes most of the time.
