### ISSUE TITLE
use javadoc.io for javadoc hosting?

### ISSUE THREAD

**Issue by maxcellent** [ReactiveX/RxJava#6726]
Not sure how javadoc is managed currently. But I hope this could save some effort on every release.

Basically https://javadoc.io/doc/io.reactivex.rxjava3/rxjava will always point to the latest version published to JCenter / Central Maven. 

Or you can add a badge with versions always up to date:

`[![javadoc](https://javadoc.io/badge2/io.reactivex.rxjava3/rxjava/javadoc.svg)](https://javadoc.io/doc/io.reactivex.rxjava3/rxjava)
`

[![javadoc](https://javadoc.io/badge2/io.reactivex.rxjava3/rxjava/javadoc.svg)](https://javadoc.io/doc/io.reactivex.rxjava3/rxjava)

Disclaimer: I creates javadoc.io

**Comment by akarnokd** [comment]
We use `gh-pages` to host each individual released javadoc and the snapshots: 

- http://reactivex.io/RxJava/3.x/javadoc/
- http://reactivex.io/RxJava/3.x/javadoc/3.0.0-RC5
- http://reactivex.io/RxJava/3.x/javadoc/snapshot

**Comment by maxcellent** [comment]
thanks for the reply.

In that case I do see some benefit switching then. 

With `gh-page` we would have to commit generated javadoc files and publish manually. It's not the most painful thing in the world but this is an extra procedure. This is the same reason why many other popular java libraries are using javadoc.io, like gson, mockito etc.

**Comment by akarnokd** [comment]
The release is automated so we don't have to do anything in this regard. Changing the process for a badge doesn't seem to be worth it for us. We can, of course, add that link to the readme.

**Comment by maxcellent** [comment]
cool, so no action needed. 

cheers,
