### ISSUE TITLE
what rxjava version should use when in new project?

### ISSUE THREAD

**Issue by zhenqinrui** [ReactiveX/RxJava#6727]
I want to know what rxjava version we should use, the 2.x perhaps is more stable， but 3.x is now in development, so what choose?

**Comment by akarnokd** [comment]
2.x has an established 3rd party library support, which may come much later for 3.x. If your project is shorter than a year, stick with 2.x.

**Comment by zhenqinrui** [comment]
so, haven't a range time the 3.x version can stable?

**Comment by akarnokd** [comment]
January to March 2020, depending on how [AGP 4's backport support](https://github.com/ReactiveX/RxJava/issues/6695) will come along. Support for 2.x ends in a year after.
