### ISSUE TITLE
OSGi warning about io.reactivex.rxjava3.disposables using private

### ISSUE THREAD

**Issue by akarnokd** [ReactiveX/RxJava#6742]
Since the OSGi update #6675, packaging the jar gives the [following warning](https://travis-ci.org/ReactiveX/RxJava/builds/620101751#L239):

```
warning: Export io.reactivex.rxjava3.disposables,  has 1,  private references [io.reactivex.rxjava3.internal.disposables]
```

I don't know why this package gets a warning but not `core`.

/cc @io7m

**Comment by io7m** [comment]
What this message is saying is that a class in the exported package `io.reactivex.rxjava3.disposables` references a class in the non-exported package `io.reactivex.rxjava3.internal.disposables`. This isn't _always_ indicative of a real problem - it might just indicate that your API classes are leaking implementation details -  but I'll take a look at it.

**Comment by akarnokd** [comment]
Thanks, it is likely due to the internal `DisposableContainer` interface referenced. I've moved it into public in #6745 and should no longer give a warning.
