### ISSUE TITLE
Is it assumed that CompositeException is eligible to modify the cause of exceptions passed in constructor of CompositeException?

### ISSUE THREAD

**Issue by zubchenok** [ReactiveX/RxJava#6747]
Since RxJava modifies exceptions during call of `getCause` method of `CompositeException` instance and connect these exceptions in chains we have finally millions of exceptions and quickly getting out of memory.

```
    @Test
    public void compositeExceptionIssue() {
        Single
            .just(new Throwable("ROOT ERROR"))
            .flatMapCompletable(rootError -> Observable
                .range(1, 10)
                .flatMapCompletable(testNumber -> Completable
                    .mergeArrayDelayError(
                        Completable.error(new RuntimeException("Test#" + testNumber + "A", rootError)),
                        Completable.error(new RuntimeException("Test#" + testNumber + "B", rootError))
                    )
                    .doOnError(Throwable::getCause)
                    .onErrorComplete()
                )
                .doOnComplete(() -> {
                    rootError.printStackTrace();
                })
            )
            .blockingAwait();
    }
```
This simple test demonstrates that  cause of `rootError` throwable is changed.

**Comment by akarnokd** [comment]
Do you mean those "Caused by: java.lang.RuntimeException: Duplicate found in causal chain so cropping to prevent loop" listings?

**Comment by akarnokd** [comment]
The `getCause` looks needlessly convoluted. I presume it was implemented that way that IDEs show some usable stacktraces of the individual inner exceptions. Java 7's `addSuppressed` is better in this regard but we can't use it just yet.

I can probably have such duplicate indicator show up at most once.

**Comment by zubchenok** [comment]
I mean that original exception is actually chained with other exceptions. `rootError.getCause()!=null` while expected to be null (in my option).

**Comment by akarnokd** [comment]
I see. To resolve it, we'd have to remove the custom `getCause` implementation otherwise it will keep touching all sorts of inner exceptions. We could also probably fake a `StackTraceElement` array containing all inner exceptions too.

**Comment by zubchenok** [comment]
Or you could probably just override printStackstace methods.

**Comment by akarnokd** [comment]
Thanks for reporting. This is a shortcoming of the 1.x and 2.x composite design and I'm afraid we can only resolve this for 3.x because it is a breaking change in the structure of the composite verified by unit tests.
