### ISSUE TITLE
io.reactivex.exceptions.CompositeException: 3 exceptions occurred. 

### ISSUE THREAD

**Issue by yanweiqiang** [ReactiveX/RxJava#6759]
![image](https://user-images.githubusercontent.com/5111354/70844186-50479a00-1e78-11ea-8bf0-2671e38d5826.png)

Test code:
```
fun main() {
    /*RxJavaPlugins.setErrorHandler {
        it.cause?.let {
            throw it
        }
    }*/

    val obs1 = Observable.create<String> {
        it.onError(Throwable())
    }
    val obs2 = Observable.create<String> {
        it.onError(Throwable())
    }
    val obs3 = Observable.create<String> {
        it.onError(Throwable())
    }
    val obs4 = Observable.create<String> {
        Thread.sleep(1000)
        it.onError(Throwable())
    }.subscribeOn(Schedulers.io())

    val composite = CompositeDisposable()

    val dis = Observable.mergeDelayError(arrayListOf(obs1, obs2, obs3, obs4)).subscribe({
        print(it)
    }, {
        print(it.message)
    })
    composite.add(dis)
    composite.clear()

}
```

**Comment by akarnokd** [comment]
Please read the exception messages: user not login. This is a workflow error in your app.

**Comment by yanweiqiang** [comment]
**I know it was throwed by my error. But, I think it can be catched in onError, dose it? I defined the onError method in Observer but it throwed it out, So strange**

**Comment by yanweiqiang** [comment]
> Please read the exception messages: user not login. This is a workflow error in your app.

I know it was throwed by my error. But, I think it can be catched in onError, dose it? I defined the onError method in Observer but it throwed it out, So strange

**Comment by yanweiqiang** [comment]
> Please read the exception messages: user not login. This is a workflow error in your app.

I think the error must be catched in onError or disappare, but it throwed out in compositeDisposable.clear()

**Comment by yanweiqiang** [comment]
> Please read the exception messages: user not login. This is a workflow error in your app.

When I use mergeDelayError, create multi Observable ,now  I  do finish activity , you has a function named compositeDisposable.clear()  throws ExceptionHelper.wrapOrThrow(errors.get(0)); please view code  extra seriously

**Comment by yanweiqiang** [comment]
> Please read the exception messages: user not login. This is a workflow error in your app.

Have you see the code in rxjava method call stack? Please see it. I am very disappointed with you.

**Comment by akarnokd** [comment]
Dumping a stackrace without any context or code to reproduce the issue is unlikely to get you support from us. Nor does certain attitude. Please ask your question on StackOverflow.

**Comment by yanweiqiang** [comment]
> Dumping a stackrace without any context or code to reproduce the issue is unlikely to get you support from us. Nor does certain attitude. Please ask your question on StackOverflow.

I do not understand what you mean. But thanks.

**Comment by yanweiqiang** [comment]
I just want to know why you throw the exception when CompositeDisposable.clear(). I think you must not do it when someone alread call dispose.

**Comment by yanweiqiang** [comment]
> Dumping a stackrace without any context or code to reproduce the issue is unlikely to get you support from us. Nor does certain attitude. Please ask your question on StackOverflow.

I just want to know why you throw the exception when CompositeDisposable.clear(). I think you must not do it when someone already called dispose(). Or should I try catch the CompositeDisposable.clear() function whenever I use it on a merge delay subscribe?

**Comment by akarnokd** [comment]
Please read https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0#error-handling . Exceptions gathered by `mergeDelayError` are reported to the global error handler upon disposing the sequence so that errors possibly important to the developer are not lost.

**Comment by yanweiqiang** [comment]
> Please read https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0#error-handling . Exceptions gathered by `mergeDelayError` are reported to the global error handler upon disposing the sequence so that errors possibly important to the developer are not lost.

RxJavaPlugins.setErrorHandler(e -> { }); I have set the global function. It still throwed out. I think that's not the point, because the exception is directly throwed in function rather than in Rx try catch block, so it can not be catch by RxJavaPlugins.setErrorHandler(e -> { });

**Comment by yanweiqiang** [comment]
![image](https://user-images.githubusercontent.com/5111354/70790619-70238300-1dd0-11ea-8493-7bed929395f1.png)
It thow directly. Dose it?

**Comment by akarnokd** [comment]
None of the provided stacktraces indicate your code crashes while disposing a flow. Please provide a test case that demonstrates your problem.

**Comment by yanweiqiang** [comment]
> None of the provided stacktraces indicate your code crashes while disposing a flow. Please provide a test case that demonstrates your problem.

OK. I will try it. Thanks for your support.

**Comment by yanweiqiang** [comment]
> None of the provided stacktraces indicate your code crashes while disposing a flow. Please provide a test case that demonstrates your problem.
I mocked this exception, but the stacktrace is strange.

```
fun main() {
    val obs1 = Observable.create<String> {
        it.onError(Throwable())
    }
    val obs2 = Observable.create<String> {
        it.onError(Throwable())
    }
    val obs3 = Observable.create<String> {
        it.onError(Throwable())
    }
    val obs4 = Observable.create<String> {
        Thread.sleep(1000)
        it.onError(Throwable())
    }.subscribeOn(Schedulers.io())

    val composite = CompositeDisposable()

    val dis = Observable.mergeDelayError(arrayListOf(obs1, obs2, obs3, obs4)).subscribe({
        print(it)
    }, {
        print(it.message)
    })
    composite.add(dis)
    composite.clear()
}
```

![image](https://user-images.githubusercontent.com/5111354/70800167-83d9e400-1de6-11ea-9126-5a2db202ca4f.png)

**Comment by akarnokd** [comment]
Again, exceptions gathered by `mergeDelayError` are reported to the global error handler upon disposing the sequence. Where did you set `RxJavaPlugins.setErrorHandler(e -> { });`?

**Comment by yanweiqiang** [comment]
> Again, exceptions gathered by `mergeDelayError` are reported to the global error handler upon disposing the sequence. Where did you set `RxJavaPlugins.setErrorHandler(e -> { });`?

I'm very sorry, it's my fault. I think because my code logic has something wrong. The `RxJavaPlugins.setErrorHandler(e -> { });` set after the exception occured. Thank you very much.
