### ISSUE TITLE
3.x: [Java 8] Use diamond <> where possible in unit tests.

### ISSUE THREAD

**Issue by akarnokd** [ReactiveX/RxJava#6767]
The upgrade to Java 8 caused more than 4,000 locations to report as diamond capable, including regular classes and tests.

In the first round, fix the unit test files, but beware:
- Do not change the non-test files yet. (Avoid conflict with other cleanups and Java 8 additions.)
- Do not change the existing tests' functional interface usages to lambdas. (Undoing lambdaification is extremely painful because tools guess the inner class types wrong almost always.)
- On a rare occasion, the warning is wrong in the IDE and breaks the Gradle compilation with javac.

I'd appreciate this to be split between several PRs or ~100 file changes per PR tops to still be able to review them on GitHub.

**Comment by dvolkovv** [comment]
Hello! I've made several PR's with ~100 file changes in each, more detailed information is in PR's.

**Comment by akarnokd** [comment]
Done.
