### ISSUE TITLE
3.x: RxScala3 for RxJava3

### ISSUE THREAD

**Issue by sinwe** [ReactiveX/RxJava#6807]
With RxJava3 release is imminent, is there any plan for RxScala3?

**Comment by akarnokd** [comment]
It is up to the RxScala developers.

**Comment by sinwe** [comment]
What would be the process to create repo for rxscala3 under ReactiveX?

**Comment by akarnokd** [comment]
Talk to @dhoepelman about what he plans in the main https://github.com/ReactiveX/RxScala repo.
