### ISSUE TITLE
3.x simple cleanup: Remove the duplicate Comparator in Functions

### ISSUE THREAD

**Issue by slisaasquatch** [ReactiveX/RxJava#6816]
In `io.reactivex.rxjava3.internal.functions.Functions`, [this](https://github.com/ReactiveX/RxJava/blob/79f8e6dde6446b1aa33c146eaedbb958086daf56/src/main/java/io/reactivex/rxjava3/internal/functions/Functions.java#L154) and [this](https://github.com/ReactiveX/RxJava/blob/79f8e6dde6446b1aa33c146eaedbb958086daf56/src/main/java/io/reactivex/rxjava3/internal/functions/Functions.java#L523) look like the exact same thing. Is it worth it to delete one of them?

**Comment by akarnokd** [comment]
Yes. PR welcome.
