### ISSUE TITLE
Question about the lazySet() usage within the ObservableWithLatestFrom operator

### ISSUE THREAD

**Issue by Manabu-GT** [ReactiveX/RxJava#6836]
[Environment]
RxJava: 2.2.16

When using a `withLatestFrom` operator, I noticed a case where the latest emitted value from the 2nd observable specified with the `withLatestFrom` operator does not immediately become visible due to its `lazySet()` call at
https://github.com/ReactiveX/RxJava/blob/2.x/src/main/java/io/reactivex/internal/operators/observable/ObservableWithLatestFrom.java#L134.

This issue occurs if `another` observable in the below example emits its value on a thread different from where the `sourceObservable` gets emitted. Is this by design? Why does the  `withLatestFrom` use `lazySet()` instead of `set()`?

```
souceObservable
.withLatestFrom(another, (source, another) -> {
  return xxx;
})
```

This might not be a good example to demonstrate the issue, but if I have a chain of Rx stream like below, its `subscribe` block at the end should keep getting called again and again if a change to `controlMode` is immediately visible when `withLatestFrom` runs, but it very occasionally sees a stale value `ControlMode.PAUSE` updated within the `doOnNext`  call and its `subscribe` block won't be called in such case.

```
enum ControlMode {
    ACTIVE,
    PAUSE,
}

Relay<ControlMode> controlMode = BehaviorRelay.createDefault(ControlMode.ACTIVE).toSerialized();
Relay<Irrelevant> requestRelay = PublishRelay.<Irrelevant>create().toSerialized();

controlMode
        .skip(1)
        .filter(controlMode -> !controlMode.equals(ControlMode.PAUSE))
        .subscribe(s -> requestRelay.accept(Irrelevant.INSTANCE));

requestRelay.startWith(Irrelevant.INSTANCE)
        .observeOn(Schedulers.io())
        .withLatestFrom(controlMode, (request, controlMode) -> controlMode)
        .filter(controlMode -> !controlMode.equals(ControlMode.PAUSE))
        .doOnNext(unused -> controlMode.accept(ControlMode.PAUSE))
        .switchMap(unused -> Observable.just(Irrelevant.INSTANCE).delay(100, TimeUnit.MILLISECONDS))
        .subscribe(unused -> controlMode.accept(ControlMode.ACTIVE));
```

Thank you in advance for your input on this.

**Comment by akarnokd** [comment]
What platform are you?

> Why does the withLatestFrom use lazySet() instead of set()?

Why do you think that's the problem? LazySet values will eventually become visible to other threads, usually within tens on nanoseconds. Unless your main source and other emits really close together, it shouldn't matter. In addition, you are using `toSerialized` which has a synchronized block that acts as a full barrier so the lazySet will be committed before the next value is delivered. If you want, you can add a volatile variable `int x` to the class and `doAfterNext(v -> x = 0)` to force a flush.

`withLatestFrom` emits items only if the main source emits and the other source has signaled a value as well. If your main source signals first, then the other source, you won't get an emission.

I suspect you have a logic or timing error in your code. Log the signals of the relays and see what signal ordering you actually get.

**Comment by Manabu-GT** [comment]
> What platform are you?

Android.

>  Log the signals of the relays and see what signal ordering you actually get.

After flipping the subscription order of `controlMode` and `requestRelay` in the above example, the issue no longer reproduces :)

Thanks for your explanation.
