### ISSUE TITLE
API Design Review: DelayError

### ISSUE THREAD

**Issue by benjchristensen** [ReactiveX/RxJava#684]
The `mergeDelayError` operator has been in RxJava from very early and evolved out of experience with the Netflix API use cases. It is not from Rx.Net.

It has proved very valuable and it has been suggested that this pattern be expanded to other combinatorial operators where lazily handling errors is sometimes appropriate.

These include:

- `concatDelayError`
- `combineLatestDelayError`
- `switchLatestDelayError`

Are there others? Any reason not to do this?

/cc @headinthebox and @jhusain

**Comment by akarnokd** [comment]
Do we still want these versions?

**Comment by jhusain** [comment]
I do.

**Comment by akarnokd** [comment]
Okay, 

  - `combineLatestDelayError` is implemented operator-vise, just needs exposure.
  - for `concatDelayError`, concat needs full rewrite anyway
  - `switchLatestDelayError` is `switchOnNext` with error delay I presume.

**Comment by akarnokd** [comment]
See #3759 for `concatDelayError`.

**Comment by akarnokd** [comment]
See #3763 for `combineLatestDelayError`.

**Comment by akarnokd** [comment]
See #3765 for `switchOnNextDelayError`.

**Comment by akarnokd** [comment]
Operators have been added. Let us know if there are some more required.
