### ISSUE TITLE
refCount() with delay doesn't support multicasting

### ISSUE THREAD

**Issue by harisudhan7889** [ReactiveX/RxJava#6851]
**RxJava Version: 2.2.13**

Suppose multiple observers subscribe with some delay between each subscription then `refCount()` is not supporting Multicasting. Below is the sample for this scenario

**Code Sample**
```
val observable = Observable.range(1, 3)
            .subscribeOn(Schedulers.io())
            .map(object : Function<Int, Int> {
                override fun apply(input: Int): Int {
                    println("Inside map operator Squaring the input")
                    return input * input
                }
            })

val refCountObservable = observable.publish().refCount()
println("Wait for 3 seconds for observer1 to subscribe")
Thread.sleep(3000)
refCountObservable.subscribe(observer1)
println("Wait for 3 seconds for observer2 to subscribe")
Thread.sleep(3000)
refCountObservable.subscribe(observer2)
```
**Output**

```
Wait for 3 seconds for observer1 to subscribe
Observer1 onSubscribe
Wait for 3 seconds for observer2 to subscribe
Inside map operator Squaring the input
Observer1 Output 1
Inside map operator Squaring the input
Observer1 Output 4
Inside map operator Squaring the input
Observer1 Output 9
Observer1 onComplete
Observer2 onSubscribe
Inside map operator Squaring the input
Observer2 Output 1
Inside map operator Squaring the input
Observer2 Output 4
Inside map operator Squaring the input
Observer2 Output 9
Observer2 onComplete
```
In the above output, you can see the map operator is called for the two observers instead of doing Multicasting.

**Comment by akarnokd** [comment]
It's unclear what you try to achieve here and what output are you expecting. By design, when a shared source terminates, `refCount` is reset and will be ready to establish a fresh connection.

**Comment by harisudhan7889** [comment]
With further more details. As we know `refCount` instructs **ConnectableObservable**

**Comment by harisudhan7889** [comment]
As we know **ConnectableObservable** is the way to convert Cold to Hot Observable and it supports Multicasting. Secondly my understanding of `refCount()` is it instructs **ConnectableObservable** to start emitting items at any time it sees at least one subscriber. 

In the above code sample, I have subscribed two observers to the refCountObservable but I am providing a time delay between each subscription. My expectation here is, the map operation which I do should have happened only once for each emission of the first observer and not for the second observer. But because of the delay which I have provided between subscriptions,  map operation is processed even for a second observer.

Suppose multiple observers subscribes without any delay between each subscription then I find that multicasting works perfectly and the output is like below.

```
Observer1 onSubscribe
Observer2 onSubscribe
Inside map operator Squaring the input
Observer1 Output 1
Observer2 Output 1
Inside map operator Squaring the input
Observer1 Output 4
Observer2 Output 4
Inside map operator Squaring the input
Observer1 Output 9
Observer2 Output 9
Observer1 onComplete
Observer2 onComplete
```
My question here is whether the delay between the subscriptions will
disconnect the previous connection and creates a new connection for each observer?

**Comment by akarnokd** [comment]
As I mentioned, `refCount` starts over if the source completes. If you don't have a second observer while the connection is live, it will start a new connection and duplicate the side-effects.

You are most likely using the wrong overload or the wrong operator.

Case 1: you want to wait until both observers subscribe: use [`refCount(2)`](http://reactivex.io/RxJava/2.x/javadoc/io/reactivex/observables/ConnectableObservable.html#refCount-int-).

Case 2: you want to replay items to late observers: use [`cache`](http://reactivex.io/RxJava/2.x/javadoc/io/reactivex/Observable.html#cache--) instead of `publish`.

Case 3: you want to replay items to late observers but eventually want to rerun the source: use [`replay`](http://reactivex.io/RxJava/2.x/javadoc/io/reactivex/Observable.html#replay--) without `refCount` and manually call `connect`.

**Comment by harisudhan7889** [comment]
@akarnokd  Thanks for the reply. Yes, I can use `refCount(2)` instead, but I am trying to understand when the connection to upstream gets closed for different refCount variants?. As per your reply, I understood that the second observer is subscribed after the disconnect so a new connection is started. But we do have refCount variant with connection timeout - `refCount(timeout, TimeUnit.MILLISECONDS)` that connects to the upstream ConnectableObservable if the number of subscribed observers reaches 1 and disconnect after the specified timeout if all subscribers have unsubscribed. This shows that the connection will be available for a mentioned time period. Even with this operator, I am getting the same result that I got with `refCount()` without Multicast. 

Below is the code snippet that I tried.
```
val observable = Observable.range(1, 3)
            .subscribeOn(Schedulers.io())
            .map(object : Function<Int, Int> {
                override fun apply(input: Int): Int {
                    println("Inside map operator Squaring the input")
                    return input * input
                }
            }) 
val refCountObservable = observable.publish().refCount(10000, TimeUnit.MILLISECONDS)
refCountObservable.subscribe(observer1)
Thread.sleep(1000)
 refCountObservable.subscribe(observer2)
```
**Output**
```
Observer1 onSubscribe
Inside map operator Squaring the input
Observer1 Output 1
Inside map operator Squaring the input
Observer1 Output 4
Inside map operator Squaring the input
Observer1 Output 9
Observer1 onComplete
Observer2 onSubscribe
Inside map operator Squaring the input
Observer2 Output 1
Inside map operator Squaring the input
Observer2 Output 4
Inside map operator Squaring the input
Observer2 Output 9
Observer2 onComplete
```
In the above code, I have specified a delay of 1000 milliseconds between each subscription and set the refCount timeout to 10000 milliseconds. My question here is whether the connection gets closed within this time period? If not why I am getting the output without Multicasting.

**Comment by akarnokd** [comment]
Again, `refCount` starts over if the source completes. Timeout after a completed source has no effect. Even if it delayed a reconnection, you'd not get items for `Observer2` because `publish` requires live audience while it emits its values.

**Comment by harisudhan7889** [comment]
@akarnokd Thanks for the clarification.
