### ISSUE TITLE
3.x: Swap Maybe.flatMapSingle and Maybe.flatMapSingleElement ?

### ISSUE THREAD

**Issue by akarnokd** [ReactiveX/RxJava#6878]
Currently, `flatMapSingle` returns `Single` and signals `NoSuchElementException` if the source `Maybe` is empty. `flatMapSingleElement` remains `Maybe`.

I'd consider renaming `flatMapSingle` to `flatMapSingleOrError` and `flatMapSingleElement` to `flatMapSingle` as I think a default `Maybe` -> `Maybe` transformer should better match the other such transformers.

Alternatively, drop `flatMapSingle` and rename `flatMapSingleElement` to `flatMapSingle` so that the original behavior could be achieved via `flatMapSingle.toSingle())`.

**Comment by slisaasquatch** [comment]
Personally I'm in favor of dropping the old `flatMapSingle` and renaming `flatMapSingleElement`, because I found the behavior of the old `flatMapSingle` surprising at first, and using `toSingle().flatMap()` is more readable.

**Comment by akarnokd** [comment]
Let's drop `flatMapSingle` and rename `flatMapSingleElement`. 

@slisaasquatch would you like to post a PR? If so, please keep the unit tests and use `flatMapSingle().toSingle()`.
