### ISSUE TITLE
2.x: Unexpected behaviour of GroupBy operator wrt. request handling

### ISSUE THREAD

**Issue by AnitaMell** [ReactiveX/RxJava#6889]
The groupBy operator does not work as expected wrt. request handling.
If a subscriber of one of the GroupedFlowables is cancelled, the buffer space occupied by this GroupedFlowable is not released. 

The code below illustrates this behavior:

### Code
```java
        List<TestSubscriber> listOfSubscribers = new ArrayList<>();

        Flowable.range(1, 1000)
            .doOnNext(n -> System.out.printf("onNext (%d) \n", n))
            .doOnRequest(r -> System.out.printf("%d requests send \n", r))
            .groupBy(integer -> integer % 10)
            .subscribe(groupedFlowable -> {
                TestSubscriber<Integer> subscriber = TestSubscriber.create(0);
                listOfSubscribers.add(subscriber);
                groupedFlowable.subscribe(subscriber);
            });
```
### output result
```java
        128 requests send 
        onNext (1) 
        1 requests send 
        onNext (2) 
        1 requests send 
        onNext (3) 
        1 requests send 
        onNext (4) 
        1 requests send 
        onNext (5) 
        1 requests send 
        onNext (6) 
        1 requests send 
        onNext (7) 
        1 requests send 
        onNext (8) 
        1 requests send 
        onNext (9) 
        1 requests send
        onNext (10) 
        1 requests send 
        onNext (11) 
        onNext (12) 
        onNext (13) 
        ...
        onNext (136) 
        onNext (137) 
        onNext (138)
```
As I expected, the buffer is filled up with items until the buffer is completly full and, as a result, requests are no longer signalled to upstream

If I add a line of code which cancels all TestSubscribers I would expect that the groupBy operator signals 128 requests to upstream, because the buffer should be empty again. However this is not the case, and cancelling all TestSubscribers has no effect on the result.

### Modified code with same output
```java
        List<TestSubscriber> listOfSubscribers = new ArrayList<>();

        Flowable.range(1, 1000)
            .doOnNext(n -> System.out.printf("onNext (%d) \n", n))
            .doOnRequest(r -> System.out.printf("%d requests send \n", r))
            .groupBy(integer -> integer % 10)
            .subscribe(groupedFlowable -> {
                TestSubscriber<Integer> subscriber = TestSubscriber.create(0);
                listOfSubscribers.add(subscriber);
                groupedFlowable.subscribe(subscriber);
            });

        listOfSubscribers.forEach(TestSubscriber::cancel);
```
What's your opinion on this? Could this be a bug or does it work as designed?
Thank you

**Comment by akarnokd** [comment]
This is a shortcoming of the 2.x implementation and should be fixed in the latest 3.x release candidate (RC-8). 

Since there were other changes to `groupBy` in 3.x, I have to look into if the resolution to this particular behavior can be backported or not. Until then, it would be great if you checked your setup with the RC-8.
