### ISSUE TITLE
"Cannot access io.reactivex.functions.Actions" when RxJava is used in an Android library and the library is used by an app

### ISSUE THREAD

**Issue by Muddz** [ReactiveX/RxJava#6898]
I'm using `RxJava` in a Android library which is only available for use by a public static constructor. The library-class using RxJava have implemented `Action` and `CompletableObserver` interfaces in the class signatur header, but by doing so Android Studio tells me `"Cannot access io.reactivex.functions.Actions"`

Library version: `io.reactivex.rxjava2:rxjava:2.2.6`

**Android app module**

```
public class Bar implements Foo.FooListener {

    public Bar(){
        Foo.of(this); // "Cannot access io.reactivex.functions.Actions"
    }

    @Override
    public void hello() {

    }
}
```

**Android library module:**

```
public class Foo implements Action, CompletableObserver {

    private FooListener listener;

    private Foo(FooListener listener) {
        this.listener = listener;
    }
    

    public static Foo of(@NonNull FooListener listener) {
        return new Foo(listener);
    }

    //This don't work
    public void save(){
        Completable.fromAction(this)
                .subscribeOn(Schedulers.io())
                .observeOn(Schedulers.io())
                .subscribe();
    }


    //This work!
    public void save(){
        Completable.fromAction(new Action() {
            @Override
            public void run() throws Exception {
                
            }
        })
                .subscribeOn(Schedulers.io())
                .observeOn(Schedulers.io())
                .subscribe(new CompletableObserver() {
                    @Override
                    public void onSubscribe(Disposable d) {
                        
                    }

                    @Override
                    public void onComplete() {

                    }

                    @Override
                    public void onError(Throwable e) {

                    }
                });
    }
    
    @Override
    public void onSubscribe(Disposable d) {
        listener.hello();
    }

    @Override
    public void onComplete() {
        listener.hello();
    }

    @Override
    public void onError(Throwable e) {
        listener.hello();
    }

    @Override
    public void run() throws Exception {
        listener.hello();
    }

    public interface FooListener {
        void hello();
    }
}

```

**Comment by akarnokd** [comment]
Does this happen in a fresh project? What are your dependencies? I can only guess something imports two distinct RxJava versions and there is a conflict.

**Comment by Muddz** [comment]
@akarnokd 

No it's not a fresh project, but If you wan't, I can make a quick little project demonstrating the issue and push it to Github

App dependencies
```
dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    implementation 'androidx.appcompat:appcompat:1.1.0'
    implementation 'com.google.android.material:material:1.0.0'
    implementation project(path: ':myLibrary')
}

```

Library dependencies

```
dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    implementation 'androidx.appcompat:appcompat:1.1.0'
    implementation 'com.google.android.material:material:1.0.0'
    implementation 'io.reactivex.rxjava2:rxandroid:2.1.1'
    implementation "io.reactivex.rxjava2:rxjava:2.2.6"
    androidTestImplementation 'androidx.test:runner:1.2.0'
    androidTestImplementation 'androidx.test:rules:1.2.0'
}

```

I also tried with RxJava3 and without RxAndroid without any successful effect

**Comment by akarnokd** [comment]
Yes, a working fresh project indicates you have some configuration issue in your original project.

**Comment by Muddz** [comment]
@akarnokd 

Here is it: https://github.com/Muddz/RxError
When running the app module I get the error:

 ```error: cannot access Action
class file for io.reactivex.functions.Action not found
```

[MainActivity](https://github.com/Muddz/RxError/blob/master/app/src/main/java/com/muddzdev/rxerror/MainActivity.java)

[Library Foo Class](https://github.com/Muddz/RxError/blob/master/mylibrary/src/main/java/com/muddzdev/mylibrary/Foo.java)

**Comment by akarnokd** [comment]
The problem is that the `myLibrary` uses RxJava as `implementation` dependency which is not exposed to your `app` module, hence it can't find the files.

Changing to `api` works for me:

```
    api 'io.reactivex.rxjava2:rxandroid:2.1.1'
    api "io.reactivex.rxjava2:rxjava:2.2.6"
```

**Comment by Muddz** [comment]
@akarnokd

But that will mean that any who add the library to their app, will automatically also add RxJava to their project, or at least have access to RxJava methods, right?

**Comment by akarnokd** [comment]
`Foo` implements `Action` and you expose it transitively via `of()`, thus you'll have to open it up via `api`.

**Comment by Muddz** [comment]
@akarnokd Alright. Thanks for the help and clarification!
