### ISSUE TITLE
3.x: Add "exhaustMap" (flatMapFirst) operator

### ISSUE THREAD

**Issue by hoc081098** [ReactiveX/RxJava#6902]
Please add flatMapFirst (exhaustMap) operator, like this [exhaustMap-rxjs](https://rxjs-dev.firebaseapp.com/api/operators/exhaustMap), flatMapFirst in RxSwift.
Thanks!
![](https://rxjs-dev.firebaseapp.com/assets/images/marble-diagrams/exhaustMap.png)

**Comment by akarnokd** [comment]
No. This is an uncommon operation to perform that can be emulated with existing operators:

`source.onBackpressureDrop().flatMap(mapper, 1)`

or

[flatMapDrop](https://github.com/akarnokd/RxJavaExtensions#observabletransformersflatmapdrop) for `Observable`.

**Comment by hoc081098** [comment]
Thanks @akarnokd

**Comment by jnorkus** [comment]
@akarnokd  I could not agree less. ExhaustMap should be made standard. Coming from RxJs this is very inconvenient to use additional libraries for functionality that seems so common.

**Comment by dkuteynikov** [comment]
> No. This is an uncommon operation to perform that can be emulated with existing operators:

I don't agree that it's an "uncommon" operation - it's very frequently used in GUI apps to prevent initiating the same action while the previous one hasn't completed (e.g. a safety net against repeated clicking of the same button).

Here are some possible implementations of this functionality:

```kotlin
fun <T : Any, R : Any> Observable<T>.exhaustMapSingle(mapper: (T) -> Single<R>) : Observable<R> {
    return this.toFlowable(BackpressureStrategy.DROP)
            .concatMapEager({ mapper(it).toFlowable() }, 1, 1).toObservable()
}

fun <T : Any, R : Any> Observable<T>.exhaustMapMaybe(mapper: (T) -> Maybe<R>) : Observable<R> {
    return this.toFlowable(BackpressureStrategy.DROP)
            .concatMapEager({ mapper(it).toFlowable() }, 1, 1).toObservable()
}

fun <T : Any> Observable<T>.exhaustMapCompletable(mapper: (T) -> Completable) : Completable {
    return this.toFlowable(BackpressureStrategy.DROP)
        .concatMapEager({ mapper(it).toSingleDefault(Unit).toFlowable() }, 1, 1).ignoreElements()
}

fun <T : Any, R : Any> Observable<T>.exhaustMap(mapper: (T) -> Observable<R>) : Observable<R> {
    return this.toFlowable(BackpressureStrategy.DROP)
        .concatMapEager({ mapper(it).toFlowable(BackpressureStrategy.MISSING) }, 1, 1)
        .toObservable()
}
```

**Comment by akarnokd** [comment]
> frequently used in GUI apps to prevent initiating the same action while the previous one hasn't completed

How about disabling the button and re-enabling it afterwards?

> Here are some possible implementations of this functionality

Kotlin has extension methods so you can just have these in your code or as a separate library without losing convenience of using the operator.

**Comment by dk-3cx** [comment]
> How about disabling the button and re-enabling it afterwards?

But what if the same action can be triggered both by the UI and programmatically? We must be sure not to trigger the same code simultaneously from two unrelated entry points. So it makes sense to guarantee it on Rx level in the action itself.

> you can just have these in your code or as a separate library

But why does RxJS have it then? For some reason they understood that it's a common pattern.

**Comment by akarnokd** [comment]
1) Okay, use flags to protect against reentrance.
2) Different library. We are restraining ourselves and no whim based inclusions.
3) This topic, It's been 3-6 years old. How and why does this trigger you right now. I mean this exact hour ago? Kyle.
