### ISSUE TITLE
2.x Observable.concat firstElement and firstOrError calls subsequent methods after returning a valid observable

### ISSUE THREAD

**Issue by jurajTomko** [ReactiveX/RxJava#6906]
Hi, I'm using version 2.2.17 but I've tried several other versions and result is the same.

```kotlin
Observable.concat(
            Observable.just("source1"),
            getSource2()
    ).firstOrError()
```
From what I understand this example should produce observable "source1" and then end the stream. Nevertheless it produces "source1" and then it invokes method "getSource2". Same thing happens when I call .firstElement() instead of firstOrError(). Same result when I try Maybe.concat or Single.concat with .firstElement() or .firstOrError().

If I put more observable sources into picture, the result is the same. The method "getSource4" is still invoked.

```kotlin
Observable.concat(
            Observable.just("source1"),
            Observable.just("source2"),
            Observable.just("source3"),
            getSource4()
    ).firstOrError()
```
Is it required behaviour or a bug? I'm implementing repository pattern in which I don't want to make unnecessary network API call when I've got the data cached.

**Comment by akarnokd** [comment]
How did you implement `getSource2()`?

It's the Java runtime that invokes your method, not RxJava.

Please think about this. If I refactor your code, is `getSource2()` invoked?

```java
Observable<Integer> source2 = getSource2();

Observable.concat(
            Observable.just("source1"),
            source2
    ).firstOrError()
```

How about now?

```java
Observable<Integer> source2 = getSource2();

/*
Observable.concat(
            Observable.just("source1"),
            source2
    ).firstOrError()
*/
```
