### ISSUE TITLE
Type erasure issues in RxJava3 that aren't present in RxJava2

### ISSUE THREAD

**Issue by JacobKingDev** [ReactiveX/RxJava#6908]
Consider the following code:

```
Single.create<List<String>> {  }
            .flatMapObservable {
                Observable.fromIterable(it)
            }
```

This should take a single that emits a list (such as an API endpoint that returns a list of objects, and act on each one in turn.

On RxJava 2.4.0, this all compiles and works correctly, but on RxJava 3.0.0, the Kotlin compiler throws the following error:

```
Type Mismatch
Required: ((List<String>!) -> ObservableSource<out (???..???)>!)!
Found: (List<String>!) -> Observable<String!>!
```

This looks like some kind of type erasure issue, but for now I'll be reverting back to 2.4.0.

Versions:
RxJava: 3.0.0
RxKotlin: 3.0.0-RC1
RxAndroid: 3.0.0
Kotlin: 1.3.50

**Comment by akarnokd** [comment]
Works for me in Kotlin 1.3.61:

![image](https://user-images.githubusercontent.com/1269832/74816928-605a7a80-52fc-11ea-8585-2bb02bf7d4cf.png)

**Comment by JacobKingDev** [comment]
Yep, seems to be a Kotlin issue - 1.3.61 is working for me. Closing.
