### ISSUE TITLE
[2.x] `TestObserver.assertTerminated()` says "Subscriber still running!" after `dispose()` called

### ISSUE THREAD

**Issue by lemoinem** [ReactiveX/RxJava#6909]
Version: 2.2.10 (using RxKotlin 2.4.0 & RxAndroid 2.1.1)

Calling `.assertTerminated()` on a TestObserver does not check correctly whether `.dispose()` has been called.

This is an issue as it's making my tests fail.

I'm not sure whether the issue is with the implementation of `.dispose()` in `TestObserver` or (the `CountDownLatch` isn't `countDown()`'d) with the implementation of `.assertTerminated()` in `BaseTestObserver` (checking whether the subscriber is still running should be done differently)...

Code to reproduce (I guess this could be added to the `TestObserverTest`):

```
@Test
fun testThatDisposedObserverIsTerminated()
{
   val subject = PublishSubject.create<Unit>()
   val observer = subject.test()
   observer.dispose()
   observer.assertTerminated() // java.lang.AssertionError: Subscriber still running! (latch = 1, values = 0, errors = 0, completions = 0, disposed!)
}
```

**Comment by akarnokd** [comment]
`assertTerminated` is not meant to detect `dispose`, only if there was a call to `onError` or `onComplete`. Use `assertTrue(observer.isDisposed())` instead.

**Comment by lemoinem** [comment]
@akarnokd: The assertion thrown is still invalid:
There are no subscriber still running since the observer has been disposed.

Maybe changing the message could help. For example: "Final event (completion or error) not reached yet!" or something like that.

Currently, the documentation says: "Assert that the TestObserver/TestSubscriber terminated (i.e., the terminal latch reached zero)." The only other mention of a terminal latch is in the documentation for `assertNotTerminated`. Which doesn't help. Having:
"Assert that a final/terminal event has been reached (i.e. an error or a completion event has been received)." as documentation would be much more explicit.

Unless we are intimately familiar with the implementation, the current documentation is misleading and seems to imply that it could detect `dispose`: `dispose` terminates an observer or subscriber and I have no clue what a terminal latch is.

I would suggest updating both the Assertion message and the documentation.

**Comment by akarnokd** [comment]
Why do you think "terminated" includes cancellation/dispose?

Besides, 2.x is in maintenance mode (so no javadocs or API changes) and [3.x](https://github.com/ReactiveX/RxJava/wiki/What's-different-in-3.0#test-support-methods) does not have those methods.

**Comment by lemoinem** [comment]
Why wouldn't I think terminated includes cancellation/dispose?

When I tried to use it, when I looked a the documentation and when I looked at the code, I never thought it wouldn't.
The code as an assertion message saying the subscriber is still running, and I don't expect the subscriber to be running after I disposed it.
The documentation refer to a "terminated TestObserver/TestSubscriber", the notion isn't really explicitly defined, it also mentions a terminal latch, that isn't used anywhere else. but a disposed observer sounds terminated/terminal enough.

That's my point, both the documentation and the code are confusing.

A stable 3.x hasn't been released for two weeks yet (and this is a one-week-old issue). I'd expect some kind of overlap in the maintenance... A big project can't really change their dependency on day 1 of a release. Especially given the size of the changelog...

**Comment by akarnokd** [comment]
Nobody asked you to migrate right away and I've already given an example to check for the disposed state.

Besides, your original test makes little sense because `TestObserver` is disposable and thus if disposed, it is sure to report `true` for it, but that doesn't mean the dispose has propagated all the way up. That's why given an `Subject` source, we check `hasObservers` before and after the `dispose` call.

However, the converse test makes sense: checking that the source hasn't signaled any terminal signal (i.e., `onError` or `onComplete`) following the `dispose` call.

I've decided not to take further actions in this regard.
