### ISSUE TITLE
groupby

### ISSUE THREAD

**Issue by peica** [ReactiveX/RxJava#6911]
according to the manual, the groupby should return as following
Observable<String> animals = Observable.just(
    "Tiger", "Elephant", "Cat", "Chameleon", "Frog", "Fish", "Turtle", "Flamingo");

animals.groupBy(animal -> animal.charAt(0), String::toUpperCase)
    .concatMapSingle(Observable::toList)
    .subscribe(System.out::println);

// prints:
// [TIGER, TURTLE]
// [ELEPHANT]
// [CAT, CHAMELEON]
// [FROG, FISH, FLAMINGO]

but in real code, it returns

[TIGER, TURTLE]
[ELEPHANT]
[CAT]
[CHAMELEON]
[FROG]
[FISH]
[FLAMINGO]

I am using the 3.0.0.

**Comment by akarnokd** [comment]
See https://github.com/ReactiveX/RxJava/wiki/What's-different-in-3.0#group-abandonment-in-groupby

`concatMapSingle` creates abandonment so groups are recreated. Use `concatMapEager` or `flatMapSingle` instead.
