### ISSUE TITLE
[3.0.0] groupBy creates duplicate groups

### ISSUE THREAD

**Issue by slisaasquatch** [ReactiveX/RxJava#6912]
Thanks for using RxJava but before you post an issue, please consider the following points:

Here's my code sample:

```java
	public static void main(String[] args) {
		Flowable.range(0, 5)
		.groupBy(i -> 1) // Always the same group
		.blockingForEach(group -> System.out.println(group.getKey()));
	}
```

The code above will print `1` five times with 3.0.0. If I use 2.x with the same code, it prints `1` once.

**Comment by akarnokd** [comment]
https://github.com/ReactiveX/RxJava/wiki/What's-different-in-3.0#group-abandonment-in-groupby
