### ISSUE TITLE
Flowable.Switchmap sometimes doesn't unsubscribe from inner stream

### ISSUE THREAD

**Issue by Dimezis** [ReactiveX/RxJava#6914]
RxJava version - 2.2.18.

Sometimes, when the inner flowable emits >1 item, the unsubscription from the outer chain after receiving the first item doesn't trigger the unsubscription from the inner Flowable.
The completion of the outer chain also doesn't trigger the `finally` of the inner Flowable.
This doesn't happen if I replace Flowable with Observable.

Sorry for the pretty dumb example code, but not sure how to illustrate the problem better.

So the expected result would be that `Outer finally` and `Inner finally` both printed `10000` times.
What happens is that `Inner finally` is sometimes not printed, and the subscription to the inner flowable remains hanging, even though the outer chain has completed.
On my machine this test produces around 9970 - 9990 `Inner finally` results instead of 10000 (It varies from run to run).

```Kotlin
    private val inner = AtomicInteger()
    private val outer = AtomicInteger()

    @Test
    fun test() {
        repeat(10_000) {
            thread {
                Flowable.create<Unit>({
                    it.onNext(Unit)
                }, BackpressureStrategy.LATEST)
                    .switchMap { createFlowable() }
                    .observeOn(Schedulers.computation())
                    .doFinally {
                        println("Outer finally")
                        outer.incrementAndGet()
                    }
                    .take(1)
                    .subscribe({}, Throwable::printStackTrace)
            }.join()
        }

        assert(inner.get() == outer.get())
    }

    private fun createFlowable(): Flowable<Unit> {
        return Flowable
            .create<Unit>({
                Schedulers.io().scheduleDirect({
                    it.onNext(Unit)
                }, 10, TimeUnit.MILLISECONDS)

                Schedulers.io().scheduleDirect({
                    it.onNext(Unit)
                }, 10, TimeUnit.MILLISECONDS)
            }, BackpressureStrategy.BUFFER)
            .subscribeOn(Schedulers.single())
            .unsubscribeOn(Schedulers.single())
            .doFinally {
                println("Inner finally")
                inner.incrementAndGet()
            }
    }
```

**Comment by akarnokd** [comment]
You are invoking the emitter's `.onNext(Unit)` concurrently in the inner `Flowable`, which is not allowed. The [JavaDocs](http://reactivex.io/RxJava/2.x/javadoc/io/reactivex/FlowableEmitter.html) also mentions this:

> The Emitter.onNext(Object), Emitter.onError(Throwable), tryOnError(Throwable) and Emitter.onComplete() methods should be called in a sequential manner, just like the Subscriber's methods. Use the FlowableEmitter the serialize() method returns instead of the original FlowableEmitter instance provided by the generator routine if you want to ensure this. The other methods are thread-safe.

**Comment by Dimezis** [comment]
Do I understand it right that if I serialize this emitter, it should work?
The test still fails.

Edit: if I change the scheduler to `Schedulers.single` it still fails, although this scheduler executes tasks sequentially

```Kotlin
            Flowable
            .create<Unit>({
                val serializedEmitter = it.serialize()

                Schedulers.single().scheduleDirect({
                    serializedEmitter.onNext(Unit)
                }, 10, TimeUnit.MILLISECONDS)

                Schedulers.single().scheduleDirect({
                    serializedEmitter.onNext(Unit)
                }, 10, TimeUnit.MILLISECONDS)
            }, BackpressureStrategy.BUFFER)
```

**Comment by akarnokd** [comment]
You start the flow in a `Thread` and even though you join onto it, the `take(1).subscribe()` will keep running after. Once all 10000 such threads have apparently ended, you compare the counters of some still live outer and inner sources thus there is an inherent race between the two counters as well as the test thread itself. 

Try using `blockingSubscribe` and see if you now get all 10000 across each counter at the end.

**Comment by Dimezis** [comment]
Yeah the test is flawed probably, but it fails with `blockingSubscribe()` as well.
Or if I put a `Thread.sleep` before the assertion

**Comment by Dimezis** [comment]
Or you can forget the counters I added and just check the console output, it will always lack Inners anyway

**Comment by akarnokd** [comment]
Thanks for the feedback. After investigating, I found a bug in the operator's implementation: when timed right, the reference to the inner gets nulled out before the cancellation could reach it. This null shouldn't actually happen.

I'll post fixes shortly.

**Comment by Dimezis** [comment]
Wow, great, thank you for the quick fix
