### ISSUE TITLE
How to map exceptions?

### ISSUE THREAD

**Issue by lexer** [ReactiveX/RxJava#692]
I have Observable<MyResult> that could produce onError with Exception1. I want to remap it so I can handle Exception1 and rethrow my own Exception2.

What is the proper way to do it?

**Comment by PaulWoitaschek** [comment]
@akarnokd 

I ran into that problem on RxJava 2.

Could you take a look a this implementation and tell me if this is implemented properly?

```kotlin
class ObservableMapError<T : Any>(private val source: Observable<T>, private val errorMapper: (Throwable) -> Throwable) : Observable<T>() {

  override fun subscribeActual(observer: Observer<in T>) {
    source.subscribe(MapErrorObserver(observer, errorMapper))
  }

  class MapErrorObserver<T : Any>(val actual: Observer<in T>, val errorMapper: (Throwable) -> Throwable) : Observer<T>, Disposable {

    private var source: Disposable? = null

    override fun onSubscribe(s: Disposable) {
      if (DisposableHelper.validate(source, s)) {
        this.source = s
        actual.onSubscribe(this)
      }
    }

    override fun dispose() {
      source!!.dispose()
    }

    override fun isDisposed(): Boolean = source!!.isDisposed

    override fun onNext(t: T) {
      actual.onNext(t)
    }

    override fun onError(t: Throwable) {
      val mapped = errorMapper(t)
      actual.onError(mapped)
    }

    override fun onComplete() {
      actual.onComplete()
    }
  }
}
```

**Comment by akarnokd** [comment]
Almost. I wouldn't trust `errorMapper(t)` to not throw thus I'd wrap it into try-catch and call the `actual.onError` with a composite of the original and this latter exception.

**Comment by arturszymanski** [comment]
@akarnokd I ran into same problem on RxJava2 maybe it is worth to add those operators to Single, Observable, Flowable, Completable as official ones?

**Comment by akarnokd** [comment]
I still don't think so.

**Comment by jkaan** [comment]
> You can use 'onErrorResumeNext': http://netflix.github.io/RxJava/javadoc/rx/Observable.html#onErrorResumeNext(rx.util.functions.Func1)
> 
> Inside the function perform your conditional logic and return Observables as appropriate, such as using 'Observable.error' with your new Exception.

@benjchristensen I'm currently debugging an issue in our app where we use `onErrorResumeNext` and I wanted to verify something with you about this.

Does this mean that this will create a new observable, so this could lead to an `UndeliverableException` since the stream has died but we try to recreate it here?

**Comment by HideakiSago** [comment]
I did the following:
```
                .onErrorResumeNext { Single.error(Exception()) }
```

Is this something wrong?
