### ISSUE TITLE
groupBy operation doesn't work well.

### ISSUE THREAD

**Issue by anastr** [ReactiveX/RxJava#6922]
V`3.0.0`

i have this simple code:
```kotlin
Observable.fromIterable(sections)
        // sectionCode is an integer.
        .groupBy(Section::getSectionCode)
        .observeOn(Schedulers.computation())
        .doOnNext(g -> Log.d("key", g.getKey().toString()))
        ..
        .subscribe()
```
the output is:
```
D/key: 1
D/key: 1
D/key: 4
D/key: 1
D/key: 4
D/key: 4
D/key: 2
D/key: 2
D/key: 4
...
```
as you can see, key isn't unique as it should be!.

**Comment by akarnokd** [comment]
https://github.com/ReactiveX/RxJava/wiki/What's-different-in-3.0#group-abandonment-in-groupby

**Comment by anastr** [comment]
looking into the update and the new behavior, `sorting` groups by key is not possible after `groupBy` operation.
or i did miss something up!

**Comment by akarnokd** [comment]
You have to have a subscription established to the groups.

Also, to sort groups by key, you have to know all groups have been created, which only happens when the source completed. At that point, you could just pre-sort the sequence and then apply groupBy.

**Comment by anastr** [comment]
fare enough, sorting the sequence before `groupBy` did not work.
the only way to do so, is after `flatMapSingle` and it has to be done hard coded for this.

**Comment by akarnokd** [comment]
Is the sorting dependent on the group content? Please post the entire code you have problems with.

**Comment by anastr** [comment]
actually the sorting depends on the key itself, while the key is an integer in my example and the "work logic" required custom sorting for it something like this "1,2,4,3...", it looks like `groupBy` resorting them to "1, 2, 3, 4.." for some reason.
thanks in advance.

**Comment by anastr** [comment]
Update:
the problem about sorting is invalid since i'm using `flatMap` which cause the disorder.
thanks.
