### ISSUE TITLE
2.x: observeOn() behaves differently after the buffer has been filled up once

### ISSUE THREAD

**Issue by junhong-leanix** [ReactiveX/RxJava#6923]
RxJava version: 2.2.9

A little bit of background: I have a process pipeline which requires to do step A and then step B. Both steps consume some time so I tried to use `observeOn()` to connect the two steps, making them asynchronous and hence saving the time (below is a demo version of the code):
```
Flowable.range(0, 1000)
    .doOnNext(i -> {
        System.out.println(System.currentTimeMillis() + " doing step A for " + i);
        Thread.sleep(100);
    })
    .observeOn(Schedulers.io(), false, 5)
    .doOnNext(i -> {
        System.out.println(System.currentTimeMillis() + " doing step B for " + i);
        Thread.sleep(200);
    })
    .subscribe();
```
This solution works well, except that I found that after the `observeOn` buffer has been filled up once, the execution is no longer asynchronous. The following logs demonstrate what I mean:
```
1583054064105 doing step A for 0
1583054064305 doing step A for 1
1583054064305 doing step B for 0
1583054064410 doing step A for 2
1583054064506 doing step B for 1
1583054064513 doing step A for 3
1583054064615 doing step A for 4
1583054064708 doing step B for 2
1583054064912 doing step B for 3
1583054065112 doing step A for 5
1583054065214 doing step A for 6
1583054065317 doing step A for 7
1583054065420 doing step A for 8
1583054065525 doing step B for 4
1583054065726 doing step B for 5
1583054065927 doing step B for 6
1583054066131 doing step B for 7
1583054066335 doing step A for 9
1583054066438 doing step A for 10
...
```
So in the beginning, you can see that step A and step B is executed in parallel, and this is what I expected. But after the buffer has been filled up (step A for 4, because we have a buffer size of 5), the execution has become synchronous, in that it always execute step A to fill up the buffer, and then execute step B until the `limit` value has been reached, and execute step A to fill up the buffer again. In this phase, I lost the benefit of having these steps executed asynchronously. I have tested that if you never let the buffer fill up, then this change of behaviour would not happen.

IMHO this behaviour could really catch the user in surprise. Is this the expected behaviour and what is the reason behind it? If I want to keep the execution asynchronously all the time, is there any workaround for it?

Thank you guys in advance!

**Comment by akarnokd** [comment]
Due to backpressure, `range` responds to demand on whatever thread it gets the requests from. After some time, this will be the thread of `observeOn`. To make sure requests are fulfilled on the expected thread, use [`subscribeOn`](http://reactivex.io/RxJava/2.x/javadoc/io/reactivex/Flowable.html#subscribeOn-io.reactivex.Scheduler-).

**Comment by junhong-leanix** [comment]
Thank you very much for the quick response! Your suggested method works and also brought the concept of strong pipelining to my knowledge. Awesome!
