### ISSUE TITLE
Feature request: flow delimitring

### ISSUE THREAD

**Issue by Sammers21** [ReactiveX/RxJava#6925]
Let's say you have a stream of chars: 

```java
Flowable<Char> flow = "hello\r\nworld\r\nwhaterever"
```

and I want to split the stream into a stream of substreams and ignore a delimiter I'm splitting against. The delimiter can be a sequence of chars, '\r\n' in the example above.  Which is kind of similar to `Flowable#window`, but not exactly.

**Comment by akarnokd** [comment]
There are external operators, such as [`windowWhile`](https://github.com/akarnokd/RxJavaExtensions#flowabletransformerswindowwhile) and co to do it for items. If you have strings with arbitrarily placed separators, there is a complicated [`example`](https://github.com/akarnokd/RxJavaExtensions#flowabletransformerspartialcollect) for that.

These are, in general, datatype-specific operators which are not included in RxJava proper.
