### ISSUE TITLE
reactivex.github.io needs a new administrator

### ISSUE THREAD

**Issue by DavidMGross** [ReactiveX/RxJava#6932]
I'm no longer able to devote time to maintaining the reactivex.github.io site and its associated ReactiveX repo. There are some outstanding PRs that need review/merging, but in general there hasn't been a whole lot of activity there over the past months, so this is probably not a particularly demanding position.

**Comment by saeedntt** [comment]
Can you explain a bit more?

**Comment by r3h0** [comment]
See also https://github.com/ReactiveX/reactivex.github.io/issues/398

**Comment by MaratCrash** [comment]
@DavidMGross do you need help with that yet?

**Comment by t10-13rocket** [comment]
@DavidMGross Yes, I need help.

**Comment by meenbeese** [comment]
Would you still need a hand on maintaining the website? It hasn't received any care in about 3 years. @akarnokd

**Comment by akarnokd** [comment]
It would be great but the task is not for drive-by contributors. It needs knowledge of that build system, probably a Mac/Linux computer and dedication. 

Probably the best would be to recreate the site in plain HTML directly so no need for any special infrastructure.

**Comment by meenbeese** [comment]
> It would be great but the task is not for drive-by contributors. It needs knowledge of that build system, probably a Mac/Linux computer and dedication.

I built the site successfully on my Windows machine, and I have good experience with SSGs, primarily Zola, so I should be able to handle this task. I can try my best to keep it up to date, which should be better than it not being maintained for 3 years.
 
> Probably the best would be to recreate the site in plain HTML directly so no need for any special infrastructure.

This might be a more long-term task given the site's complexity that I can try, and I am open to further discussion on this.

**Comment by akarnokd** [comment]
Alright, let's see. I've merged a couple of trivial PRs. Could you build the site and post a PR against the master branch?

**Comment by akarnokd** [comment]
Okay, figured out most of the infrastructure so I'll be able to maintain reactivex.github.io 

Already merged and deployed most outstanding PRs.

**Comment by meenbeese** [comment]
Okay then, glad to help if anything pops up or if you change your mind on your willingness to maintain the website. I might also create some PRs if I see anything incomplete/wrong.
