### ISSUE TITLE
Merge delay error for multiple API calls.

### ISSUE THREAD

**Issue by pollux-** [ReactiveX/RxJava#6933]
```
launchJob {
            Observable.mergeDelayError(
                    getCareUseCase.getAllGetCareItems().toObservable(),
                    appointmentUseCase.getAllAppointment().toObservable()
                        .mergeWith(
                            prescriptionRefillsUseCase.getAllPrescriptionRefills())
                            .mergeWith(billUseCase.getAllPayBills())
                        .mergeWith(careTeamUseCase.getMyCareTeam())
                        .mergeWith(favoriteFacilitiesUseCase.getAllFavoriteFacilities())
                ).iOSubscribeMainThreadObserve()
                .subscribe({
                    mapSection(it)
                    flattenAndEmit()
                }, {
                   Log.e(TAG, "Failed to load dashboard contents")
                })
        }


```

If any of the API is failing entire stream is failing.  Any one knows why?

This is my requirement, I want to make all the API calls parallel,  I don't care about the order in which response arrives, I don't care if one fails, which one come fast, I just display in the order that receives.

**Comment by akarnokd** [comment]
`mergeWith` doesn't delay errors so if any of those fails, the subsequence will fail. Looks like you can simply use use `mergeArrayDelayError` with those 6 sources direclty:

```java
Observable.mergeArrayDelayError(
    getCareUseCase.getAllGetCareItems().toObservable(),
    appointmentUseCase.getAllAppointment().toObservable(),
    prescriptionRefillsUseCase.getAllPrescriptionRefills(),
    billUseCase.getAllPayBills(),
    careTeamUseCase.getMyCareTeam(),
    favoriteFacilitiesUseCase.getAllFavoriteFacilities()
)
.iOSubscribeMainThreadObserve()
```

**Comment by pollux-** [comment]
@akarnokd  

I ran into an issue.  Observable.mergeArrayDelayError() give me compilation error when I add more than 4 observable? I know this a super dumb question. As per signature it should work though?

**_mergeArrayDelayError(ObservableSource<? extends T>... sources)_**

   ```
Observable.mergeDelayError(
            getCareUseCase.getAllGetCareItems().toObservable(),
            getCareUseCase.getAllGetCareItems().toObservable(),
            getCareUseCase.getAllGetCareItems().toObservable(),
            getCareUseCase.getAllGetCareItems().toObservable(),
            getCareUseCase.getAllGetCareItems().toObservable()
        )
```

**Comment by akarnokd** [comment]
What is the error?

**Comment by pollux-** [comment]
_None of the following functions can be called with the arguments supplied: 
public final fun <T : Any!> mergeDelayError(p0: ((Observer<in (???..???)>) -> Unit)!, p1: ((Observer<in (???..???)>) -> Unit)!): Observable<(???..???)>! defined in io.reactivex.Observable
public final fun <T : Any!> mergeDelayError(p0: ((Observer<in (???..???)>) -> Unit)!, p1: ((Observer<in (???..???)>) -> Unit)!, p2: ((Observer<in (???..???)>) -> Unit)!): Observable<(???..???)>! defined in io.reactivex.Observable
public final fun <T : Any!> mergeDelayError(p0: ((Observer<in (???..???)>) -> Unit)!, p1: ((Observer<in (???..???)>) -> Unit)!, p2: ((Observer<in (???..???)>) -> Unit)!, p3: ((Observer<in (???..???)>) -> Unit)!): Observable<(???..???)>! defined in io.reactivex.Observable
public final fun <T : Any!> mergeDelayError(p0: ((Observer<in ObservableSource<out (???..???)>!>) -> Unit)!): Observable<(???..???)>! defined in io.reactivex.Observable
public final fun <T : Any!> mergeDelayError(p0: ((Observer<in ObservableSource<out (???..???)>!>) -> Unit)!, p1: Int): Observable<(???..???)>! defined in io.reactivex.Observable
public open fun <T : Any!> mergeDelayError(p0: ObservableSource<out ObservableSource<out (???..???)>!>!): Observable<(???..???)>! defined in io.reactivex.Observable
public open fun <T : Any!> mergeDelayError(p0: ObservableSource<out ObservableSource<out (???..???)>!>!, p1: Int): Observable<(???..???)>! defined in io.reactivex.Observable
public open fun <T : Any!> mergeDelayError(p0: ObservableSource<out Result<Pair<Section, List<HomeViewModel.HomeUiModel>>>!>!, p1: ObservableSource<out Result<Pair<Section, List<HomeViewModel.HomeUiModel>>>!>!): Observable<Result<Pair<Section, List<HomeViewModel.HomeUiModel>>>!>! defined in io.reactivex.Observable
public open fun <T : Any!> mergeDelayError(p0: ObservableSource<out Result<Pair<Section, List<HomeViewModel.HomeUiModel>>>!>!, p1: ObservableSource<out Result<Pair<Section, List<HomeViewModel.HomeUiModel>>>!>!, p2: ObservableSource<out Result<Pair<Section, List<HomeViewModel.HomeUiModel>>>!>!): Observable<Result<Pair<Section, List<HomeViewModel.HomeUiModel>>>!>! defined in io.reactivex.Observable
public open fun <T : Any!> mergeDelayError(p0: ObservableSource<out Result<Pair<Section, List<HomeViewModel.HomeUiModel>>>!>!, p1: ObservableSource<out Result<Pair<Section, List<HomeViewModel.HomeUiModel>>>!>!, p2: ObservableSource<out Result<Pair<Section, List<HomeViewModel.HomeUiModel>>>!>!, p3: ObservableSource<out Result<Pair<Section, List<HomeViewModel.HomeUiModel>>>!>!): Observable<Result<Pair<Section, List<HomeViewModel.HomeUiModel>>>!>! defined in io.reactivex.Observable
public open fun <T : Any!> mergeDelayError(p0: (Mutable)Iterable<ObservableSource<out (???..???)>!>!): Observable<(???..???)>! defined in io.reactivex.Observable
public open fun <T : Any!> mergeDelayError(p0: (Mutable)Iterable<ObservableSource<out (???..???)>!>!, p1: Int): Observable<(???..???)>! defined in io.reactivex.Observable
public open fun <T : Any!> mergeDelayError(p0: (Mutable)Iterable<ObservableSource<out (???..???)>!>!, p1: Int, p2: Int): Observable<(???..???)>! defined in io.reactivex.Observable

FAILURE: Build failed with an exception._

* What went wrong:
Execution failed for task ':kpflagshipapp:compileRefreshKotlin'.
> Compilation error. See log for more details

* Try:


```
val dashboardObservables = listOf(
            getCareUseCase.getAllGetCareItems().toObservable(),
            appointmentUseCase.getAllAppointment().toObservable(),
            prescriptionRefillsUseCase.getAllPrescriptionRefills(
                application.getString(R.string.prescription_refills_title),
                application.getString(R.string.prescription_refills_subtitle),
                R.drawable.ic_prescription_refill
            ),
            billUseCase.getAllPayBills().toObservable(),
            careTeamUseCase.getMyCareTeam().toObservable(),
            favoriteFacilitiesUseCase.getAllFavoriteFacilities().toObservable()
        )

        launchJob {
            Observable.mergeDelayError(dashboardObservables)
                .iOSubscribeMainThreadObserve()
                .subscribe({
                    mapSection(it)
                    flattenAndEmit()
                }, {
                   Log.e(TAG, "Failed to load dashboard contents")
                })
        }
```

@akarnokd  thank you so much for responding. 

The above should work,  or do you see any issue with that?

**Comment by akarnokd** [comment]
I wrote: `mergeArrayDelayError()`
You had: `mergeDelayError()`
See the difference?

**Comment by pollux-** [comment]
ya .. my bad .. thanks :)
