### ISSUE TITLE
doOnSubscribe don't work as expected.

### ISSUE THREAD

**Issue by VovaStelmashchuk** [ReactiveX/RxJava#6939]
RxJava 2.2.19
My code(sample):
```
class Foo {

	private val someCachedData = listOf(1, 2, 3)

	private val publisher = PublishProcessor.create<Int>()

	fun getPublisher(): Flowable<Int> = publisher.onBackpressureBuffer().publish().refCount()

	fun subscribe() {
		println("subscribe called")

		someCachedData.forEach(publisher::onNext)
	}
 }

 fun main() {

	val foo = Foo()

	foo.getPublisher()
		.subscribeOn(Schedulers.computation())
		.doOnSubscribe {
			println("doOnSubscribe called")
			foo.subscribe()
		}
		.subscribe { print(it) }

	Thread.sleep(10000)
}
```

Output:
```
doOnSubscribe called
subscribe called

Process finished with exit code 0
```
If i add some delay to call `foo.subscribe()`, App works fine.
The following code works fine:
```
foo.getPublisher()
		.subscribeOn(Schedulers.computation())
		.doOnSubscribe {
			println("doOnSubscribe called")
			Single.just(true)
				.subscribeOn(Schedulers.single())
				.delay(1, TimeUnit.SECONDS)
				.subscribe { _ ->
					foo.subscribe()
				}
		}
		.subscribe { print(it) }
```

**Comment by VovaStelmashchuk** [comment]
Maybe, I do something wrong. Can you provide some fix? Ad Hoc solution welcome.

**Comment by akarnokd** [comment]
In your setup, `doOnSubscribe` runs just before the `PublishProcessor` finishes the registration of the subscriber and thus when you try to signal the values then, the processor simply won't see the subscriber. Also such re-entrant use is not encouraged.

> Can you provide some fix?

What were you trying to achieve there? If you want a source to signal when a subscriber arrives, use a cold source.

**Comment by VovaStelmashchuk** [comment]
In my case, I connect to socket. Some data load from cache, another from the real socket. I want to emit cached data immediately after consumer subscribe.  How i can implement this?

**Comment by akarnokd** [comment]
Use `startWith` for example.

**Comment by VovaStelmashchuk** [comment]
Thx, I fix my problem.
