### ISSUE TITLE
Deadlock

### ISSUE THREAD

**Issue by adrian-linca** [ReactiveX/RxJava#6945]
RXJava 3.0.1.
I randomly got into a weird situation where my code entered a deadlock and I don't know why.
I simplified the code and got to the below part which will enter a deadlock and never return.
This seems like a bug, but maybe I'm missing something.
The code:
```java
Observable
    .range(1, 20)
    .flatMap(
            integer -> {
                if (integer % 5 != 0) {
                    return Observable
                            .just(integer);
                }

                return Observable
                        .just(-integer)
                        .observeOn(Schedulers.io());
            },
            false,
            1
    )
    .ignoreElements()
    .blockingAwait();
```

**Comment by akarnokd** [comment]
Thanks. It is a bug with the flatMap operator. Until the fix, you can workaround it by applying `hide()` to the plain `just`.

**Comment by adrian-linca** [comment]
OK, that works, thanks.
