### ISSUE TITLE
android exception out maybe problems from UI main thread and not UI threads

### ISSUE THREAD

**Issue by XiuyeXYE** [ReactiveX/RxJava#6950]
`Thanks` for using RxJava but before you post an issue, please consider the following points:

  - [ ] Please include the library version number, including the minor and patch version, in the issue text. In addition, if you'd include the major version in the title (such as `3.x`) that would be great.

  - [ ] If you think you found a bug, please include a code sample that reproduces the problem. Dumping a stacktrace is usually not enough for us.

  - [ ] RxJava has more than 150 operators, we recommend searching the [javadoc](http://reactivex.io/RxJava/3.x/javadoc/io/reactivex/Observable.html) for keywords of what you try to accomplish.

  - [ ] If you have a question/issue about a library/technology built on top of RxJava (such as Retrofit, RxNetty, etc.), please consider asking a question on StackOverflow first (then maybe on their issue list).

  - [ ] Questions like "how do I X with RxJava" are generally better suited for StackOverflow (where it may already have an answer).

  - [ ] Please avoid cross-posting questions on StackOverflow, this issue list, the Gitter room or the mailing list.

```
observable.subscribeOn(Schedulers.io())
                .map(new ResponseFunc1<T>())
               .map(new Func1<UserInfoResponse, UserInfo>() {
                    @Override
                    public UserInfo call(UserInfoResponse userInfoResponse) {
                        getUserInfoResponse(userInfoResponse);
                        XLog.log(mUserInfo,userInfoResponse);
                        return mUserInfo;
                    }
                })
                .map(new Func1<UserInfo, String>() {
                    @Override
                    public String call(UserInfo userInfo) {
//                        UIUtil.log(UserInfoRepository.class.toString(),userInfo.userName, userInfo.birthday);
                        XLog.log(UserInfoRepository.class,userInfo.userName,userInfo.birthday);
                        return "修改成功";
                    }
                })
                .observeOn(AndroidSchedulers.mainThread());
             .subscribe(new BaseSubscriber<String>(mView) {
                    @Override
                    public void onNext(String s) {
                        XLog.log(ModifyFieldPresent.class,"\nsuccess:",s);
                        activity.onSuccess(s);//inner call finish()
//                        this.onCompleted();
                    }
                });
```

this will cause the activity breakout and reboot.

rxjava             : '1.3.8',
rxandroid          : '1.2.1',

**Comment by akarnokd** [comment]
RxJava 1.x is no longer supported. Try asking this question on StackOverflow.
