### ISSUE TITLE
How transform ParallelFlowable?

### ISSUE THREAD

**Issue by deripas** [ReactiveX/RxJava#6966]
Hi!
I'm using version `rxjava:2.2.19`

Faced with the need to have its own context for each thread in parallel processing.
How to do this better?

Sintetic example on RxJava:
```java
        ThreadLocal<Context> context = .... // Thread load context

        Flowable.fromPublisher(...)
                .parallel()
                .runOn(Schedulers.computation())
                .map(item -> transformWithContext(context.get(), item)) // <- map item with current context
                ...
                .sequential()
```

For example, in Reactor you can use the [transformGroups](https://projectreactor.io/docs/core/release/api/reactor/core/publisher/ParallelFlux.html#transformGroups-java.util.function.Function-) method:
```java
        Flux.from(...)
                .parallel()
                .transformGroups(groupedFlux -> {
                    Context ctx = new ....
                    return groupedFlux
                            .map(item -> transformWithContext(context.get(), item);
                })
                .sequential()
```

This approach is similar to using [groupBy](http://reactivex.io/documentation/operators/groupby.html).
I couldn't find an analog to the `transformGroups`method, or does it exist?

With best regards,
Anton

**Comment by akarnokd** [comment]
This type of operation is not supported in RxJava or any of the support libraries and there are no plans to add it.

**Comment by akarnokd** [comment]
All I can say is that it may happen in the near future as part of RxJavaExtensions: https://github.com/akarnokd/RxJavaExtensions/issues/74
