### ISSUE TITLE
Request: allow to set `CLOCK_DRIFT_TOLERANCE_NANOS `in seconds/milliseconds

### ISSUE THREAD

**Issue by httpdispatch** [ReactiveX/RxJava#6968]
RxJava 2.2.18

https://github.com/ReactiveX/RxJava/blob/2cb20bd41efe70556ef7d346ee60f70e20548bae/src/main/java/io/reactivex/Scheduler.java#L97-L101

Would you please allow to set `CLOCK_DRIFT_TOLERANCE_NANOS` in seconds/milliseconds? 

I have a code which controls player position to play short pieces (few seconds) of media and pause them when the position is reached. Such as player may have various playback issues  (fast/slow playback, delay in initialization) i use `Flowable.interval`(50ms) to check its state/position periodically. However when system time synchronization occurs during playback flowable stops fire events until time become the same as it was before synchronization
Here how it looks in my log
```
14:21:43.273 z1 D PlaybackDurationControlCompletable.onTick: player position is unchanged, skipping check
14:21:37.727 z1 D some other event, time syncrhonization occurrs
// ... no onTick events for 6 seconds
14:21:43.372 z1 D PlaybackDurationControlCompletable: Initializing position 41769; elapsedTimerTime=5757 
```

**Comment by akarnokd** [comment]
This can be done for 3.x easily, but 2.x [no longer accepts changes like this](https://github.com/ReactiveX/RxJava#version-2x).

**Comment by httpdispatch** [comment]
@akarnokd thank you very much, will migrate to RxJava3
