### ISSUE TITLE
Add Duration alias to RxJava3's API

### ISSUE THREAD

**Issue by He-Pin** [ReactiveX/RxJava#6972]
Add `Duration` support to the RxJava3's API as a alias, like ,buffer etcs.

**Comment by JakeWharton** [comment]
Notably, where present, these need to coerce the type back into "primitive" versions like `long`+`TimeUnit` inside the method.

**Comment by He-Pin** [comment]
@JakeWharton Yes, that a kind of drawback.

**Comment by akarnokd** [comment]
No. This was already considered and decided not to be added to RxJava 3.
