### ISSUE TITLE
RxSchedule.io memory leak Tomcat server 8

### ISSUE THREAD

**Issue by 9030641913** [ReactiveX/RxJava#6973]
We are using tomcat 8 version and rx java 2.0.0 spring boot application.
We see the following memroy leak in the catalina out file

Tomcat catalina.out file
Error : appears to have started a thread named [RxSchedulerPurge-1] but has failed to stop it. This is very likely to create a memory leak.
Error : appears to have started a thread named [RxCachedWorkerPoolEvictor-1] but has failed to stop it. This is very likely to create a memory leak

We use subscribeOn(Schedulers.io()); . 

Is there any way we shutdown all the io operation when ever we restart the tomcat server.

<dependency>
			<groupId>io.jmnarloch</groupId>
			<artifactId>rxjava-spring-boot-starter</artifactId>
			<version>2.0.0</version>
</dependency

**Comment by akarnokd** [comment]
Make sure you call [Schedulers.shutdown](http://reactivex.io/RxJava/2.x/javadoc/io/reactivex/schedulers/Schedulers.html#shutdown--) for when the context gets unloaded.
