### ISSUE TITLE
3.x Feature request: backpressure-aware window(time) and buffer(count, time)

### ISSUE THREAD

**Issue by sobersanta** [ReactiveX/RxJava#6976]
Hi!

Currently usage of the time-based version of `.window` operator is fairly limited, as it does not support backpressure.
But I believe it would be possible to implement a limited-functionality, but backpressure-aware version which will be greatly useful in many scenarios.

For example, at the moment I use the following implementation:

```java
    public static <U, D> FlowableTransformer<U, D> sequentialWindow(Duration ttl, Function<Flowable<U>, Flowable<D>> mapper) {
        final Object singletonKey = new Object();
        return upstream -> upstream.groupBy(ignored -> singletonKey, Functions.identity(),
                                            false, 128,
                                            ttlEvictingMap(ttl))
                                   .concatMap(mapper, 2);
    }
```

where ttlEvictingMap is something like
```java
    public static <T> Function<Consumer<Object>, Map<T, Object>> ttlEvictingMap(Duration ttl) {
        return itemEvictConsumer -> CacheBuilder
            .newBuilder()
            .expireAfterWrite(ttl)
            .removalListener(notification -> {
                    try {
                        itemEvictConsumer.accept(notification.getValue());
                    } catch (Throwable throwable) {
                        throw new RuntimeException(throwable);
                    }
            })
            .<T, Object>build()
            .asMap();
    }
```

This does the job (except the bug with async group cancellation I reported yesterday),
but has quite significant unnecessary overhead and boilerplate code.

Maybe adding optimised version, something like:
```java
public <R> Flowable<R> sequentialWindow(long time, TimeUnit unit, Function<Flowable<T>, Flowable<R>> mapper)
```

to the RxJava would be possible?

And also similar applies to the `.buffer` operator.
What about something like:
```java
public <R> Flowable<R> buffer(long count, long maxTime, TimeUnit unit, int maxConcurrency, Function<Flowable<Collection<T>>, Flowable<R>> mapper)
```

Example usage of this is an infinite stream of events, which are being processed with some expensive to build resource, which must have a limited lifetime, and is non-trivially validated based on first items in the stream (see my another feature request regarding head-and-tail operator).
Like:

```java

stream
  .window(10, MINUTES)
  .headAndTail(first, rest -> {
    createExpensiveResource()
      .flatMap(resource -> 
        send(first)
          .onErrorResumeNext(e -> failStreamAtOnce(Flowable.just(first).concatWith(rest)))
          .flatMap(firstSuccess -> Flowable.just(firstSuccess).concatWith(rest.flatMapSingle(r->send(r))

```

Another example is buffering items in an infinite stream, based on maximum elements in the buffer, but also allowing buffer to be filled up only till maximum time window, like:

```java
stream
  .buffer(1000, 5, SECONDS)
  .flatMap(buffer->sendRequest(buffer)
  .flatMapPublisher(response->Flowable.fromIterable(merge(buffer,response)))
``` 

So the upstream items don't stay too long in the queue, having sane cap on the latency of the system.

WDYT?

**Comment by akarnokd** [comment]
This has been considered before and decided not to be added to RxJava proper. Timed windows, window abandonment and backpressure don't play well together and introduce a lot of corner cases.
