### ISSUE TITLE
3.x Feature request: headAndTail operator

### ISSUE THREAD

**Issue by sobersanta** [ReactiveX/RxJava#6977]
Hi!

Very useful operator available in some form both in Project Reactor and Akka Streams is prefix-and-tail or head-and-tail.

It's possible to implement it with `.publish`, e.g. like this:

```java
    public static <U, D> FlowableTransformer<U, D> headAndTail(
        BiFunction<U, Flowable<U>, Publisher<D>> mapper) {
        return source -> source.publish(shared ->
                                            shared
                                                .firstElement()
                                                .flatMapPublisher(firstElement ->
                                                                      mapper.apply(firstElement, shared)));
    }
```

Which obviously has an overhead both in terms of resources and code.

What about including an optimised implementation in the library?
Maybe more generalised version prefixAndTail which will select first N items, not just 1, as a prefix, like in Akka Streams?

**Comment by akarnokd** [comment]
It is an uncommon operator for RxJava and as such is better implemented in a 3rd party library, perhaps your own.
