### ISSUE TITLE
Single and Callable

### ISSUE THREAD

**Issue by derektom14** [ReactiveX/RxJava#6978]
I was trying to figure out why a benchmark I was running had `Observable`'s `flatMap` to an `Observable.just` with one element running faster than `flatMapSingle` to a `Single.just`, and concluded after adding some `hide`s that it's because of `Callable` optimizations. `MaybeJust`, `MaybeEmpty`, `MaybeFromAction`, and `MaybeFromCallable` all implement `Callable`, as do the equivalents for `Observable` and `Flowable`. Why don't the equivalent `Single` operators also implement `Callable` so that operators like `ObservableFlatMapSingle` can have similar optimizations to `ObservableFlatMap`?

(I've been looking at the 2.x library, 3.x has the same structure, but using `Supplier` instead of `Callable`.)

**Comment by akarnokd** [comment]
It was very common to use flatMap with just before, therefore, it received the optimizations. With such shortcuts, one has to beware not to worsen the more common non-shortcut path.

**Comment by derektom14** [comment]
Alright, but why is `Single` left out of these optimizations? Was it observed that `Single.just` was used in `flatMapSingle` significantly more rarely?

**Comment by derektom14** [comment]
This also leads to the strange scenario where, if one writes a `flatMapSingle` that has a very common `Single.just` path, it can be faster if rewritten as `flatMapMaybe`, despite the lack of an absent case.

**Comment by akarnokd** [comment]
What is your use case that involves `flatMapSingle` with `Single.just`?

**Comment by derektom14** [comment]
I don't have a specific one right now (just found this quirk while comparing `firstElement()` versus `take(1)`, but the scenario would be something where a key may be mapped to either a value that is already locally available (hence using `Single.just`) or a value that must be calculated by a separate process (hence using a different `Single`). Otherwise, it would be simpler as `map`.

**Comment by akarnokd** [comment]
`flatMapMaybe` was optimized because there were use cases that mixed scalar and async inner sources or used just/empty to perform mapping and filtering at the same time. Therefore, it was worth introducing the shortcuts. With `flatMapSingle`, mixed use was uncommon enough so no optimization is implemented.

**Comment by derektom14** [comment]
Ah, ok. From my benchmarking, on an `Observable`, using `flatMapMaybe` performs significantly worse than using `filter` followed by `map` (most likely due to the creation of new objects for every value as well as the greater complication of the `ObservableFlatMapMaybe`). I would need to switch to 3.x to see how `flatMapOptional` compares.

**Comment by derektom14** [comment]
With another benchmark, I've determined that on an `Observable`, using `flatMap` to a 0-or-1 `Observable` is significantly faster than using the equivalent `flatMapMaybe`. This is mostly explained by the fact that `ObservableFlatMap` tries the `Callable` optimization while `ObservableFlatMapMaybe` (but it's unclear why it doesn't), but even when I had `hide()` to bypass the `Callable` optimization, it still performs significantly worse, though not as significantly worse. By all appearances, `ObservableFlatMapMaybe` is a simpler operator than `ObservableFlatMap`, so why this performance difference, and why doesn't it apply the same `Callable` optimization? (I'm still looking at 2.x, perhaps this changed in 3.x.)

**Comment by akarnokd** [comment]
Not all possible optimizations have been applied to all the operators. If users are experiencing performance problems, their use case and the operators are investigated. Benchmarks showing such intended use help a lot in determining what actions to take.

**Comment by derektom14** [comment]
I'm surprised that `Observable.flatMap(Observable)` received this optimization while `Observable.flatMapMaybe(Maybe)` and `Maybe.flatMap(Maybe)` did not, then, and that it's more frequent for `flatMap` to involve an `Observable.just` or `Observable.empty` than for `flatMapMaybe` to involve `Maybe.just` or `Maybe.empty`, considering that `Observable` is usually used when multiple items are involved, and if it emits multiple items it can never be treated as a `Callable`.

And I'm still surprised that even when I remove optimizations with `hide()`, `flatMap` is still faster than `flatMapMaybe`, I'll need to turn to the debugger to see how it's taking fewer effective steps.

The benchmarks I'm running are just to directly compare `flatMapMaybe` versus `flatMap`, so they aren't directly reflecting intended use, although I do see many uses of `flatMapMaybe` that can only be `Maybe.just` and `Maybe.empty`, despite being an order of magnitude faster as `flatMapOptional`.
