### ISSUE TITLE
Re-connecting `replay(1)` sometimes works, sometimes doesn't - depends on the order of subscription vs connect().

### ISSUE THREAD

**Issue by valeriyo** [ReactiveX/RxJava#6981]
RxJava 2.2.19

The following test passes:

```kotlin
  @Test fun testReconnect() {
    val subject = BehaviorSubject.createDefault(5)
    val replayOne = subject.replay(1)

    val connect1 = replayOne.connect()
    val test1 = replayOne.test()
    subject.onNext(6)
    test1.assertValues(5, 6)
    connect1.dispose()
    test1.dispose()

    val connect2 = replayOne.connect() // <---- Swap this line with next to break the test!!!
    val test2 = replayOne.test()
    subject.onNext(7)
    test2.assertValues(6, 7)
  }
```

However if I swap the lines with `connect2` and `test2` -- the test fails on last line with `Value count differs; expected: 2 [6, 7] but was: 1 [6]`

NOTE: The order of `connect1` and `test1` doesn't matter.

I'm trying to understand the reason for this odd behavior - it caused many obscure bugs in our app, which I've spent a day on. It's hard to troubleshoot because it fails silently -- simply no new values are emitted. The interim solution I came up is to throw away the ConnectableObservable after it's been disconnected, and replace with a new one. That workaround is awkward to use because I can't use a regular `lazy` property, and is still error-prone, because it's too easy to "forget" to throw away the ConnectableObservable, and it will appear to work ... until, it doesn't.

Thanks.

**Comment by akarnokd** [comment]
This is a shortcoming in 2.x and should be fixed in 3.x. https://github.com/ReactiveX/RxJava/wiki/What's-different-in-3.0#connectable-source-reset

**Comment by valeriyo** [comment]
Oh, wow - that's exactly my situation - I need the `reset()` method. I'll be upgrading to 3.x soon. Thanks, David!
