### ISSUE TITLE
Nested blockingSubscribe() with .subscribeOn()

### ISSUE THREAD

**Issue by donlingliang** [ReactiveX/RxJava#6984]
**Version** `3.0.2`

Trying to achieve get parallel IO-thread work done then back to the caller thread with `blockingSubscribe()`, code below is what I have investigated according threads so far:
```
functionA() {               - Main Thread
   mainNetworkCall()        - RxCachedThreadScheduler-1
    .buffer(500, TimeUnit.MILLISECONDS, 200)
    .flatMap(functionB())   - RxComputationThreadPool-2
    // ... other operators
    .subscribeOn(Schedulers.io())
    .blockingSubscribe()
 
}

functionB() {               - RxComputationThreadPool-2
    subNetworkCall()        - RxCachedThreadScheduler-2
    // ... other operators
    .subscribeOn(Schedulers.io())
    .blockingSubscribe()
    logger.log("functionB finished.") - RxComputationThreadPool-2
}

Flowable mainNetworkCall() / subNetworkCall() {
   return Flowable.range()
               .concatMap()  - RxCachedThreadScheduler-1/2 (depends on functionA or B)
               .takeWhile()
               .flatMap()
}
```
Even `functionB()` is used with `blockingSubscribe()`, 
`functionB()` still possible propagates ("functionB finished.") on **RxComputationThreadPool-2** without waiting any response  triggered by first `subNetworkCall()` on **RxCachedThreadScheduler-2**.

which against that it should block the **RxComputationThreadPool-2** till upstream (RxCachedThreadScheduler-2) terminates, according to the document of `blockingSubscribe()`. 

Therefore, will `blockingSubscribe()` block the caller thread no matter its upstream emitted by IO or other thread?  if so, how did this case happen?

Otherwise, to achieve blocking a caller thread till all the parallel IO thread work done then back to caller thread, what is a suggested way?

Thanks in advance. 

_Side Note_:
`.subscribeOn(Schedulers.io())` in `functionA` seems could not control the flatMap operation, inner flatMap is till happening on **RxComputationThreadPool-2**.

**Comment by akarnokd** [comment]
`blockingSubscribe` blocks whatever thread is running on so if you nest it onto the IO thread, it will block a worker there too. Do not block in `functionB` but return the `Flowable` to be composed over via `flatMap` in `functionA`.

Also it is unclear what main thread are you using; are you trying to develop an Android application?

**Comment by donlingliang** [comment]
> `blockingSubscribe` blocks whatever thread is running on so if you nest it onto the IO thread, it will block a worker there too. Do not block in `functionB` but return the `Flowable` to be composed over via `flatMap` in `functionA`.

I see. And are you saying that `blockingSubscribe()` blocks the way like below?: 
```
networkcall()
      .operatorA()    - IO thread or whatever nested worker thread
      .operatorB()    - IO thread or whatever nested worker thread
      .subscribeOn(Schedulers.io())
      .blockingSubscribe(Observer);  - This unblock the caller thread until operatorA() and operatorB()
                                       both finished and let Observer handles the emitted items.              
```

Actually my whole `functionB` logic is like below, that `functionA` **buffer** a list of data from network call, then passes down to `functionB` to do an extra network call if type matched with certain types :
```
Flowable functionB(List<Data> dataList, String type) {   
  if (type.equals(certainType)) {
     List<Data> subDataList;
     DisposableSubscriber<DataObject> disposableSubscriber = new DisposableSubscriber<>() { 
               @Override
               public void onNext(Data subData) {
                   subDataList.add(subData);
               }
     ...
     };

     subNetworkCall()        
       // ... other operators
       .subscribeOn(Schedulers.io())
       .blockingSubscribe(disposableSubscriber)
     logger.log("functionB finished.") - RxComputationThreadPool-2

     // combine dataList with subDataList, then convert as combinedata
     return Flowable.fromIterable(combinedData);

  } else {
     // convert dataList to combinedata
     return Flowable.fromIterable(combinedData);
  }            
    
}
```
I think in this case, back to the original question, `logger.log("functionB finished.")` and ` // convert dataList with subDataList to combinedata` will happen in `functionB` **IF** block, before the subNetworkCall response and `DisposableSubscriber` onNext got triggered. 🤔, even using `blockingSubscribe()`.


> Also it is unclear what main thread are you using; are you trying to develop an Android application?

This is not an Android application, general server java application.

**Comment by akarnokd** [comment]
Methods with `blocking` in their name block the thread they are called on.

> subDataList.add(subData);

As I said, use composition and existing non-blocking operators, such as `toList`, `doOnNext` etc. for your example.
