### ISSUE TITLE
3.x: Alternative for assertValueSet

### ISSUE THREAD

**Issue by Steppschuh** [ReactiveX/RxJava#6991]
While upgrading a large codebase from RxJava2 to RxJava3, I stumbled upon the fact that `assertValueSet` has been removed from the test consumer. Unfortunately I missed the usage survey in #6153. 

Is there any recommended way to assert that a given stream emits expected items **in any order**?

Here's an example diff for my current workaround while migrating:
<img width="632" alt="Screenshot 2020-05-19 at 14 20 34" src="https://user-images.githubusercontent.com/1711417/82416392-3db23c00-9a7a-11ea-9ccb-a353baca95e4.png">

PS: I was happy that the migration was very smooth overall, especially because of the detailed documentation. Highly appreciate your efforts!

**Comment by akarnokd** [comment]
Those methods were turned into internal static methods on a helper class:

https://github.com/ReactiveX/RxJava/blob/3.x/src/test/java/io/reactivex/rxjava3/testsupport/TestHelper.java#L3457-L3477

You can do that or define your own `TestSubscriber` subclass with extra fluent assertions.
