### ISSUE TITLE
2.x using @NonNull for method parameters.

### ISSUE THREAD

**Issue by Laimiux** [ReactiveX/RxJava#6993]
Any reason that `T item` is not marked with `@NonNull`? There are multiple methods with parameters that could be marked with `@NonNull`.
```java
@CheckReturnValue
@NonNull
@SchedulerSupport(SchedulerSupport.NONE)
public static <T> Observable<T> just(T item) {
    ObjectHelper.requireNonNull(item, "item is null");
    return RxJavaPlugins.onAssembly(new ObservableJust<T>(item));
}
```

I'm trying to find the call-site of the following issue (stacktrace doesn't contain any of the code we maintain)
```io.reactivex.internal.functions.ObjectHelper.requireNonNull (ObjectHelper.java:39)```

I'm thinking that marking various return values and parameters with `@NonNull` would allow us to use lint to catch such issues before they make it into production (especially when using it with Kotlin data classes which are marked with `@Nullable` and `@NonNull` annotations).

Maybe also annotating `Function<T, R>` return value with `@NonNull`?

**Comment by akarnokd** [comment]
The nullability annotations have been fixed with [3.x](http://reactivex.io/RxJava/3.x/javadoc/io/reactivex/rxjava3/core/Observable.html#just-T-).
