### ISSUE TITLE
3.x Amb operator is not cancelling the other sources once one source completes

### ISSUE THREAD

**Issue by JurgenCruz** [ReactiveX/RxJava#6998]
Using library io.reactivex.rxjava3:rxjava:3.0.3

Depending on the order you declare the sources on the amb operator, the source gets cancelled or not. See code snippet below:
```Kotlin
@Test
fun ambTest() {
  var just = Maybe.just("test")
  val cancellable = object : Cancellable {
    var cancelled = false
    override fun cancel() {
      cancelled = true
    }
  }
  val never = Maybe.create<String> { it.setCancellable(cancellable) }
  var value: String? = null
  // This doesn't work
  Maybe.amb(listOf(just, never)).subscribe { value = it }
  // But this works
  // Maybe.amb(listOf(never, just)).subscribe { value = it }
  assertThat(value).isEqualTo("test")
  // The following line fails if you declare just first instead of never.
  assertThat(cancellable.cancelled).isTrue()
}
```
I would expect that regardless of the order in which you pass the MaybeSources to the `amb` operator, whenever one of them completes, the other are cancelled.

I found this bug by accident when writing another unit test which sometimes worked and sometimes didn't work. It seemed like a race condition but when I reduced it to the above example it is no longer random. In my case I think it was random because I was building the list from a HashSet so maybe the order was randomly changing each time.

If there is a workaround for this, that would be great. Maybe using some schedulers fixes it?

Thanks.

**Comment by akarnokd** [comment]
If a source completes while the subscriptions are still going on, those sources will not be subscribed and thus not get cancelled.

What is your use case that needs your sources to always start?

**Comment by JurgenCruz** [comment]
So you are saying that the sources that are not cancelled are also not subscribed and thus should not be active anyway? I had not considered that.

The use case in my program was that the sources might be hot sources that are waiting for a cancelation signal to cleanup. Also, even if it is not hot, if the method has side effects, even if it is not subscribed, the side effects will be called. This can be mitigated with a `defer` I guess.

Is there a way to test if `never` was actually never subscribed to? if I can do an `or` such that it was never subscribed or was cancelled, my unit test will pass.

**Comment by akarnokd** [comment]
There is the `doOnSubscribe` operator that gets called if a subscription is passing through.

**Comment by JurgenCruz** [comment]
Thanks, I'll give it a try and update with my findings.
Edit:

It works as expeted. new Unit Test:

```kotlin
  @Test
  fun ambTest() {
    val just = Maybe.just("test")
    var cancelled = false
    var subscribed = false
    val never = Maybe.create<String> {
      it.setCancellable { cancelled = true }
    }.doOnSubscribe { subscribed = true }
    var value: String? = null
    // This works
    Maybe.amb(listOf(just, never)).subscribe { value = it }
    // This also works
    // Maybe.amb(listOf(never, just)).subscribe { value = it }
    assertThat(value).isEqualTo("test")
    assertThat(cancelled || !subscribed).isTrue()
  }
```
