### ISSUE TITLE
3.x: Flaky GroupBy test

### ISSUE THREAD

**Issue by akarnokd** [ReactiveX/RxJava#7001]
https://github.com/ReactiveX/RxJava/blob/98acac218cdb04d279b5ac49bb1afc65bc6ec4fe/src/test/java/io/reactivex/rxjava3/internal/operators/flowable/FlowableGroupByTest.java#L2668

```
io.reactivex.rxjava3.internal.operators.flowable.FlowableGroupByTest > issue6974Part2Case1NoEvict FAILED
    java.lang.AssertionError: Error(s) present: [io.reactivex.rxjava3.exceptions.CompositeException: 1 exceptions occurred. ] (latch = 0, values = 15551, errors = 1, completions = 0)
        at io.reactivex.rxjava3.observers.BaseTestConsumer.fail(BaseTestConsumer.java:125)
        at io.reactivex.rxjava3.observers.BaseTestConsumer.assertNoErrors(BaseTestConsumer.java:212)
        at io.reactivex.rxjava3.internal.operators.flowable.FlowableGroupByTest.issue6974RunPart2NoEvict(FlowableGroupByTest.java:2681)
        at io.reactivex.rxjava3.internal.operators.flowable.FlowableGroupByTest.issue6974Part2Case1NoEvict(FlowableGroupByTest.java:2693)
        Caused by:
        io.reactivex.rxjava3.exceptions.CompositeException: 1 exceptions occurred. 
            Caused by:
            io.reactivex.rxjava3.exceptions.MissingBackpressureException: Unable to emit a new group (#71) due to lack of requests. Please make sure the downstream can always accept a new group as well as each group is consumed in order for the whole operator to be able to proceed.
```

Error is an allowed outcome here.

**Comment by ddunig2** [comment]
I would like to pick up this issue if no one is working on it yet.

**Comment by tmankita** [comment]
I would like to pick up this issue, @ddunig2  are you still working on it?

**Comment by ddunig2** [comment]
I had not realized I got the okay to work on this. @tmankita give me three days to work on it then it's all yours.

**Comment by ddunig2** [comment]
@akarnokd that test seems to be passing on my local machine, I'm not sure what the issue is.

**Comment by akarnokd** [comment]
It can probabilistically result in a `MissingBackpressureException`, which is an allowed outcome, but the test expects no errors: https://github.com/ReactiveX/RxJava/blob/98acac218cdb04d279b5ac49bb1afc65bc6ec4fe/src/test/java/io/reactivex/rxjava3/internal/operators/flowable/FlowableGroupByTest.java#L2681

Effectively, the only thing needed is a different assert such as in this test: https://github.com/ReactiveX/RxJava/blob/98acac218cdb04d279b5ac49bb1afc65bc6ec4fe/src/test/java/io/reactivex/rxjava3/internal/operators/flowable/FlowableGroupByTest.java#L2730

**Comment by ddunig2** [comment]
@akarnokd Okay, I got it. Would simply removing the assertNoErrors be valid? I would have to change the TestSubsriber to TestSubscriberEx to include the assertTerminate() and in this case, would we still need assertComplete()?
