### ISSUE TITLE
3.x: NoAnonymousInnerClassesTest fails

### ISSUE THREAD

**Issue by sh-abhi** [ReactiveX/RxJava#7005]
When attempting to build the project locally via `./gradlew build`, all of the tests pass except for the `NoAnonymousInnerClassesTest`:
```
io.reactivex.rxjava3.validators.NoAnonymousInnerClassesTest > verify FAILED
    java.lang.AssertionError: Anonymous inner classes found:
    test.io.reactivex.rxjava3.testsupport.SuppressUndeliverableRule$1.class
        at io.reactivex.rxjava3.validators.NoAnonymousInnerClassesTest.verify(NoAnonymousInnerClassesTest.java:125)
```

For context, here are some more details about what I'm running on my machine:
```
$ java --version
openjdk 11.0.2 2019-01-15
OpenJDK Runtime Environment 18.9 (build 11.0.2+9)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.2+9, mixed mode)
$ gradle --version
------------------------------------------------------------
Gradle 6.5
------------------------------------------------------------

Build time:   2020-06-02 20:46:21 UTC
Revision:     a27f41e4ae5e8a41ab9b19f8dd6d86d7b384dad4

Kotlin:       1.3.72
Groovy:       2.5.11
Ant:          Apache Ant(TM) version 1.10.7 compiled on September 1 2019
JVM:          13.0.2 (Oracle Corporation 13.0.2+8)
OS:           Mac OS X 10.15.5 x86_64
```

**Comment by akarnokd** [comment]
Apparently the verifier doesn't like the SuppressUndeliverableRule's inner class: https://github.com/ReactiveX/RxJava/blob/3.x/src/test/java/io/reactivex/rxjava3/testsupport/SuppressUndeliverableRule.java#L36

Could you turn that `new Statement` into a named inner class and see if it builds for you (it builds on CI so you are in a good position to verify a fix)?

**Comment by sh-abhi** [comment]
Sure, happy to. I'll fork and open up a new PR @akarnokd

**Comment by sh-abhi** [comment]
@akarnokd, I just opened a pull request: https://github.com/ReactiveX/RxJava/pull/7006
