### ISSUE TITLE
3.x: UndeliverableException when using mergeArray

### ISSUE THREAD

**Issue by Steppschuh** [ReactiveX/RxJava#7008]
I came across an issue in neXenio/RxAndroidBleServer#4 and I think it's a bug in RxJava and not an issue with how I use it. Please consider the following example:

```java
@Test
public void test() throws Exception {
    doMultipleFailingTasks()
            .test()
            .await(1, TimeUnit.SECONDS);
}

private Completable doMultipleFailingTasks() {
    return Completable.mergeArray(doFailingTask("A"), doFailingTask("B"))
            .doOnSubscribe(disposable -> System.out.println("Starting multiple tasks"))
            .doOnError(throwable -> System.out.println("Error: " + throwable))
            .doFinally(() -> System.out.println("Stopped multiple tasks"));
}

private Completable doFailingTask(String name) {
    return Completable.error(IllegalStateException::new)
            .subscribeOn(Schedulers.io())
            .doOnSubscribe(disposable -> System.out.println("Starting task " + name))
            .doFinally(() -> System.out.println("Stopped task " + name));
}
```

This would result in an unhandled `IllegalStateException` with the following output:

```
Starting multiple tasks
Starting task A
Starting task B
Error: java.lang.IllegalStateException
Stopped task A
Stopped multiple tasks
Stopped task B
java.lang.IllegalStateException  <-- unhandled
```

The same code however works as expected when removing the `.subscribeOn(Schedulers.io())` line from `doFailingTask` with the following output:

```
Starting multiple tasks
Starting task A
Stopped task A
Error: java.lang.IllegalStateException
Stopped multiple tasks
```

The problem seems to be a race condition when two or more errors are emitted at the same time in different threads. I do know about `Completable.mergeArrayDelayError`, however that does not work for my use case as the merged completables are ongoing tasks that never complete (if no error occurs).

**Comment by akarnokd** [comment]
This is not a bug in RxJava. When sources race with errors, `mergeArray` probabilistically picks one of them to emit and the other goes to the global error handler.

You have to decide what to do with the excess error that can't be delivered, for example:
- install a global error handler and log/suppress it,
- add an error handler operator to the `doFailingTask` that turns the error into a value or completion,
- create an union of (value, error) as the flow type and work with those.
