### ISSUE TITLE
Bug or Help Long running observable in background crashes app 

### ISSUE THREAD

**Issue by iplusMario** [ReactiveX/RxJava#7011]
Intended to write issue in RxAndroid :P

**Comment by akarnokd** [comment]
Looks like you have some memory issues with your Android app: `android.os.TransactionTooLargeException`.

I don't know what it means or how is it related to RxJava. Please ask such Android related questions on StackOverflow.

**Comment by iplusMario** [comment]
Ok. 
But it is wierd it only happens if i press home button when an observable is running.
An example i use observable for simple task to fetch some data from api 
if i press home button in the middle of execution so app goes into pause the callable thread interupts and throws error RxJavaPlugin.Error catches it but then after some seconds when app is stoped it crashes,

But If I wait so that the call finishes and press home button app goes into stop mode nothing happens it all works normal.

**Comment by iplusMario** [comment]
Observable.fromCallable(() -> {
                    try {
                        long currentTime = System.nanoTime();
                        long endTime = currentTime + 20000000000l;
                        while (currentTime < endTime) {
                            Thread.sleep(1);
                        }

                        // zapisiVBazoInPosljiBulk(iSTIT_ID, cSEVD_REF1, cSEVD_REF2, mList);
                    } catch (Exception e) {
                        Log.e("Test", "", e);
                    }

                    return true;
                }).subscribeOn(Schedulers.io())
                        .observeOn(AndroidSchedulers.mainThread())
                        .doOnError((e) -> {
                            Program.ShowDialogConfirm(requireActivity(), "Napaka", e.getMessage(), null);
                        })
                        .doOnNext((res) -> {
                            Program.ShowDialogConfirm(requireActivity(), "Title", "text", null);
                        })
                        .doFinally(() -> {
                            model.setShowProgress(false);
                        })
                        .subscribe((res) -> {}, (e) -> {}, () -> {});

not using any of my code still crashes I am going to try a new project so see if it works there

**Comment by iplusMario** [comment]
> Looks like you have some memory issues with your Android app: `android.os.TransactionTooLargeException`.
> 
> I don't know what it means or how is it related to RxJava. Please ask such Android related questions on StackOverflow.

Ok i tried it in new project it works so thany you i will check my code where it went wrong.

Edited
My bad saved array of 30000 to bundle thats why it crashed the app.
Sorry for the truble.
