### ISSUE TITLE
3.x: where did and/then/when go?

### ISSUE THREAD

**Issue by arcanefoam** [ReactiveX/RxJava#7014]
Why was the and/then/when flow removed in version 3?

**Comment by akarnokd** [comment]
As far as I remember, the join patterns weren't even part of RxJava 1.x and lived in [RxJavaJoins](https://github.com/ReactiveX/RxJavaJoins).

For 3.x, they are available in the [RxJavaExtensions](https://github.com/akarnokd/RxJavaExtensions) library ([docs](https://akarnokd.github.io/RxJavaExtensions/javadoc/hu/akarnokd/rxjava3/joins/package-summary.html)).

**Comment by arcanefoam** [comment]
Thanks!!

**Comment by arcanefoam** [comment]
Thanks!
