### ISSUE TITLE
Rxjava documents can be written in more detail. The hierarchical relationship is not very clear

### ISSUE THREAD

**Issue by pengzhengfa** [ReactiveX/RxJava#7015]
Rxjava documents can be written in more detail. The hierarchical relationship is not very clear

**Comment by akarnokd** [comment]
> Rxjava documents can be written in more detail.

There exist several books that do a great job of explaining RxJava. I suggest reading any of them.

> The hierarchical relationship is not very clear

What hierarchical relationships?

**Comment by pengzhengfa** [comment]
stay README.md The documents in the document are not written clearly, which can be optimized or an official document website can be opened

**Comment by akarnokd** [comment]
You are welcome to improve any of our documents or create a website that describes RxJava from your desired perspective.
