### ISSUE TITLE
3.0.4 groupBy operator seems broken after the first grouping

### ISSUE THREAD

**Issue by robphilipp-tiggee** [ReactiveX/RxJava#7016]
Using version 3.0.4, when running the groupBy example (https://github.com/ReactiveX/RxJava/wiki/Transforming-Observables#groupby) the grouping is not correct.
```java
Observable<String> animals = Observable
		.just("Tiger", "Elephant", "Cat", "Chameleon", "Frog", "Fish", "Turtle", "Flamingo", "Emu");

animals
		.groupBy(animal -> animal.charAt(0), String::toUpperCase)
		.concatMapSingle(Observable::toList)
		.subscribe(System.out::println);
```
gives output:
```text
[TIGER, TURTLE]
[ELEPHANT]
[CAT]
[CHAMELEON]
[FROG]
[FISH]
[FLAMINGO]
[EMU]
```
Note that Cat and Chameleon are not grouped, and Frog, Fish, Flamingo are not grouped, and Elephant and Emu are not grouped.

**Comment by akarnokd** [comment]
What you experience is the so-called [group abandonment](https://github.com/ReactiveX/RxJava/wiki/What's-different-in-3.0#group-abandonment-in-groupby) because `concatMapSingle` subscribes to one group at a time. Try with `flatMapSingle` instead.

**Comment by robphilipp-tiggee** [comment]
Awesome! Thanks that works.
