### ISSUE TITLE
RxJava3.X nullability annotations not supported by Kotlin compiler.

### ISSUE THREAD

**Issue by DougSig** [ReactiveX/RxJava#7017]
(As of 3.0.4)

`io.reactivex.rxjava3.annotations.NonNull` and `io.reactivex.rxjava3.annotations.Nullable` need to be added here as they were for RxJava2: https://github.com/JetBrains/kotlin/blob/master/core/descriptors.jvm/src/org/jetbrains/kotlin/load/java/JvmAnnotationNames.kt

For example, this compiles in Kotlin but it shouldn't:
```
    fun test(obs: io.reactivex.rxjava3.core.Observable<String>) = obs.map<String>(null)
    fun test2(obs: io.reactivex.rxjava3.core.Observable<String>) = obs.map { null }
```

-----
Thanks for using RxJava but before you post an issue, please consider the following points:

  - [x] Please include the library version number, including the minor and patch version, in the issue text. In addition, if you'd include the major version in the title (such as `3.x`) that would be great.

  - [x] If you think you found a bug, please include a code sample that reproduces the problem. Dumping a stacktrace is usually not enough for us.

  - [x] RxJava has more than 150 operators, we recommend searching the [javadoc](http://reactivex.io/RxJava/3.x/javadoc/io/reactivex/Observable.html) for keywords of what you try to accomplish.

  - [x] If you have a question/issue about a library/technology built on top of RxJava (such as Retrofit, RxNetty, etc.), please consider asking a question on StackOverflow first (then maybe on their issue list).

  - [x] Questions like "how do I X with RxJava" are generally better suited for StackOverflow (where it may already have an answer).

  - [x] Please avoid cross-posting questions on StackOverflow, this issue list, the Gitter room or the mailing list.

**Comment by akarnokd** [comment]
I suggest contacting the Kotlin project for such modifications.
