### ISSUE TITLE
coroutines Semaphore equivalent?

### ISSUE THREAD

**Issue by ursusursus** [ReactiveX/RxJava#7020]
Hi, is there a coroutines (not java - thread) Semaphore equivalent? Which would somehow enforce only 1 subscriber per multiple instances of the same stream?

**Comment by akarnokd** [comment]
> coroutines

Probably the wrong repo.
Also: https://stackoverflow.com/questions/62629606/how-to-enforce-only-1-subscriber-per-multiple-instances-of-a-same-single-observa
