### ISSUE TITLE
toList accepts an empty observable

### ISSUE THREAD

**Issue by anastr** [ReactiveX/RxJava#7026]
`V 3.0.4`

i have this situation where there is an empty Observable:

```kotlin
Observable.fromCallable {
    dataController.getImages() // empty array.
}
    .subscribeOn(Schedulers.io())
    .filter { it.isNotEmpty() }
    .doOnNext { images ->
        Log.i("RxText", images.toString()) // not passed 
        ...
    }
    .concatMap { Observable.fromIterable(it) }
    .map { image ->
        Log.i("RxText", image.toString()) // not passed 
        ...
    }
    .toList()
    .toObservable()
    .map {
        Log.i("RxText", it.toString()) // pass, Empty array !
        ...
    }
    ...
```

as you can see, transforming operation `toList` has accepted an empty observable as empty array, but that not what we expected.

here is a question for `toList` operation, should it accepts an empty Observable?
it's Ok to say that `toList` operation returned a `Single` that should have `onSuccess` or `onError` event so it must returned an empty list because `Single` does't have `Single.empty()` anyway, and that lead us to the second question:

why `filter` operation _(in the code above)_ dose't cut the sequence and stop the down stream?

is it a normal behavior for filtering and `to` operations!

**Comment by akarnokd** [comment]
`toList` always produces a list, an empty list if its upstream is empty. Thus even if you filtered out items before it, `toList` will still create an empty list. You have to filter this empty list out after if you don't need it:

```kotlin
.toList()
.toObservable()
.filter { it.isNotEmpty() }
.map {
}
```
