### ISSUE TITLE
Generalize Single/Observable zip() Method in rxJava2

### ISSUE THREAD

**Issue by damian-rafael-lattenero** [ReactiveX/RxJava#7029]
I create an example to achieve this goal, you can see it in:

https://stackoverflow.com/questions/62844759/how-can-i-generalize-the-arity-of-rxjava-zip-function-from-single-observable-t

I can try to achieve this in Java too

**Comment by akarnokd** [comment]
Why did you post this issue?

1. RxJava 2+ doesn't accept null values in the flows, thus a nullable element type is not going to work. You need Optional or similar structure to capture nullness while not having null references.
2. RxJava 2 is in maintenance mode so we wouldn't accept any changes to it anyway.
3. Having more than 9 argument is uncommon and would require even more function types and overloads. Luckily, you are in Kotlin so you can define your extension methods that hide the typecasting similar how RxJava does it for 2..9 sources.
4. Please do not cross post issues here and on StackOverflow.

2.
