### ISSUE TITLE
3.x Consider making .collect contravariant on T

### ISSUE THREAD

**Issue by cardamon** [ReactiveX/RxJava#7032]
Hi,

Currently, `collect` in Flowable, Observable accepts a `Collector<T, A, R> collector`. If that were to be `Collector<? super T, A, R> collector`, less casting would be needed in some instances. For example, when using `java.util.stream.Collectors.joining()`:

```java
Observable
        .just("foo", "bar", "baz")
        .cast(CharSequence.class)
        .collect(joining(", "));
```

The `.cast(CharSequence.class)` would then no longer be needed.

Should also be binary compatible?

**Comment by akarnokd** [comment]
Probably won't break anything. PR welcome.
