### ISSUE TITLE
3.x: Why merge(ObservableSource<ObservableSource>> sources) is different from merge(Iterable<ObservableSource>> sources) or mergeArray(ObservableSource... sources)?

### ISSUE THREAD

**Issue by suribada** [ReactiveX/RxJava#7037]
Hi.
merge(Iterable<ObservableSource>> sources) redicts to fromIterable(sources).flatMap(Functions.identity()) and
mergeArray(ObservableSource... sources) redicts to fromArray(sources).flatMap(Functions.identity()).

Similarly i think  that merge(ObservableSource<ObservableSource>> sources) can redirect to sources.flatMap(Functions.identity()).

Is there a reason that method use ObservableFlatMap directly?

Thanks.

**Comment by akarnokd** [comment]
It has already the right type and thus can be directly fed into the flatMap implementation.
