### ISSUE TITLE
Retrofit 2.1.0 as module, use RxJava 1.1.1 error

### ISSUE THREAD

**Issue by ByHSH** [ReactiveX/RxJava#7041]
there is a problem in my project, we use retrofit 2.1.0 as module, now I want use RxJava in project, so I implementation rxjava:1.1.1 and rxandroid:1.1.0 , even copy  retrofit-adapters and retrofit-converters  code in this editon (https://github.com/square/retrofit/tree/fd2f2e24a9e3aae3f7f6a832da3bb6fc22362577) ,also in my code setting Retrofit .addConverterFactory(GsonConverterFactory.create()).addCallAdapterFactory(RxJavaCallAdapterFactory.create()) ,but it stil has error (Caused by: java.lang.IllegalArgumentException: Could not locate call adapter for io.reactivex.Observable<java.lang.String>)

**Comment by akarnokd** [comment]
Please make sure you are using the right adapters with the right RxJava version:

- https://github.com/square/retrofit/tree/master/retrofit-adapters/rxjava#rxjava-adapter
- https://github.com/square/retrofit/tree/master/retrofit-adapters/rxjava2#rxjava2-adapter
- https://github.com/square/retrofit/tree/master/retrofit-adapters/rxjava3#rxjava3-adapter

**Comment by ByHSH** [comment]
in my project ,retrofit is a module , it can't change. I can't implementation 'com.squareup.retrofit2:adapter-rxjava:2.1.0' , it will cast
java.lang.NoSuchMethodError: No direct method <init>(Z)V in class Lokhttp3/OkHttpClient$Builder; or its super classes (declaration of 'okhttp3.OkHttpClient$Builder' appears in /data/app/com.xxx.xxx/base.apk)

**Comment by akarnokd** [comment]
I don't understand. For RxJava 2, you have to use `.addCallAdapterFactory(RxJava2CallAdapterFactory.create())`.

**Comment by ByHSH** [comment]
the editon in my project is Retrofit 2.1.0, it not support RxJava2 ,so I copy retrofit-adapters and retrofit-converters code in Retrofit 2.1.0 put in my project, but it doesn't work

**Comment by akarnokd** [comment]
Something is using RxJava 2 in your project and you have most likely defined your network type member with `io.reactivex.Observable`. Try specifying `rx.Observable` instead.

Note though that this is not an issue with RxJava itself but your project setup (which you haven't shared).

**Comment by ByHSH** [comment]
thanks, is my mistake, import the worry package
