### ISSUE TITLE
Is it possible to run a multistage pipeline in parallel?

### ISSUE THREAD

**Issue by Ohyoukillkenny** [ReactiveX/RxJava#7045]
Hi, suppose I have a query that entails a multi-stage pipeline of operations (e.g., `map(x -> intenseComputation(x)).map(...).map(...)...`)
Is it possible to implement such a query using multiple threads where each thread handles a stage of the computation (e.g., a single `map`)?

To illustrate,
input items -> map1 (assigned to thread1) -> map2 (thread2) -> map3 (thread3) ... -> Observer

I read the documentation of RxJava and checked many related materials, but now I only found codes and tutorials that taught me how to distribute the input items to multiple threads, where each thread runs the same query (e.g., using `flatMap(o -> ...subscribeOn(...))`).

Can someone help me to answer this question or refer me to some related materials? 
Thanks a lot!

BTW, I am using RxJava version 3.05.

**Comment by akarnokd** [comment]
Put `observeOn` between the stages.

**Comment by Ohyoukillkenny** [comment]
thanks a lot. I confuse the usage of observeOn with subscribeOn where `observeOn` acts only downstream.
