### ISSUE TITLE
onErrorResumeWith() javadoc has onErrorResumeNext() marble diagram

### ISSUE THREAD

**Issue by RobLewis** [ReactiveX/RxJava#7050]
documentation bug

**Comment by akarnokd** [comment]
Where exactly? There are hundreds of diagrams waiting to be redrawn...

**Comment by RobLewis** [comment]
Here: http://reactivex.io/RxJava/3.x/javadoc/ 
In the entry for `Observable<T>`, scroll down to `onErrorResumeWith()`. The marble diagram shows `onErrorResumeNext()`
