### ISSUE TITLE
3.0.5 : Previous inner observables are not unsubscribed when using flatMap

### ISSUE THREAD

**Issue by ProggerPete** [ReactiveX/RxJava#7052]
A subscription to a flatMap does not unsubscribe from the observable returned by flatMap until the resulting observable subscription is disposed.

In the code below I expect my testObserver to only receive on value "Outer 2 : Inner 1".

Instead it receives both "Outer 1 : Inner 1" and "Outer 2 : Inner 1".

It feels like we should be unsubscribed from the previous mapping when the mapping changes.  It's possible I'm misunderstanding how flatMap is supposed to work, but this feels like a bug to me.

```
	@Test
	public void shouldUnsubscribeToPreviousMappingWhenChanged() {
		PublishSubject<String> outerPublishSubject = PublishSubject.create();
		PublishSubject<String> innerPublishSubject = PublishSubject.create();

		Observable<String> flatMappedObservable = outerPublishSubject.flatMap(outer ->
				innerPublishSubject.map(inner -> outer + " : " + inner)
		);

		TestObserver<String> testObserver = flatMappedObservable.test();

		outerPublishSubject.onNext("Outer 1");
		outerPublishSubject.onNext("Outer 2");
		innerPublishSubject.onNext("Inner 1");
		
		assertThat(
				testObserver.values(),
				contains("Outer 2 : Inner 1")
		);
	}
```

**Comment by akarnokd** [comment]
> It feels like we should be unsubscribed from the previous mapping when the mapping changes.

You probably mixed it up with [`switchMap`](http://reactivex.io/RxJava/3.x/javadoc/io/reactivex/rxjava3/core/Observable.html#switchMap-io.reactivex.rxjava3.functions.Function-).

> I'm misunderstanding how flatMap is supposed to work, but this feels like a bug to me.

That is how `flatMap` has always been working and is supposed to work.

**Comment by ProggerPete** [comment]
Glad to be wrong on this.  SwitchMap does indeed fit my needs.
