### ISSUE TITLE
The worker thread failed to start work using subscribeOn(Schedulers.computation())

### ISSUE THREAD

**Issue by lancewoo** [ReactiveX/RxJava#7054]
**The libraries** that I included:

    implementation 'io.reactivex.rxjava3:rxandroid:3.0.0'
    implementation 'io.reactivex.rxjava3:rxjava:3.0.5'
    implementation 'com.trello.rxlifecycle4:rxlifecycle-components:4.0.0'

**My code** is just like this:

```Java
    private void doLogin() {
        Observable.create((ObservableOnSubscribe<Boolean>) emitter -> {
            Log.i("starting");
            while (true) {
                try {
                    boolean success = mLoginModule.login();
                    if (!success) {
                        KLog.d("login failed! No. " + mLoginTimes + ", " + ToolKits.getLastError());

                        mLoginTimes++;
                        emitter.onNext(false);
                    } else {
                        emitter.onNext(true);
                        emitter.onComplete();
                        break;
                    }

                    if (mLoginTimes > 100) {
                        emitter.onComplete();
                        break;
                    }

                    Thread.sleep(1000);
                } catch (Exception e) {
                }
            }
        }).subscribeOn(Schedulers.computation())
                .observeOn(AndroidSchedulers.mainThread())
                .compose(bindToLifecycle())
                .subscribe(new Observer<Boolean>() {
                    @Override
                    public void onSubscribe(@NonNull Disposable d) {
                    }

                    @Override
                    public void onNext(@NonNull Boolean result) {
                        onLoginResult(result);
                    }

                    @Override
                    public void onError(@NonNull Throwable e) {
                        Log.i("onError");
                    }

                    @Override
                    public void onComplete() {
                        Log.i("onComplete");
                    }
                });
    }

public class MyActivity extends RxAppCompatActivity {
    protected void onCreate(Bundle savedInstanceState) {
          ..........
                 doLogin();
          ..........

    }
}


```

**What I encountered** was sometimes the login work just failed to start, even the log output "starting" did not come out. But when the activity was destroyed, onComplete got printed out. So I guess there's something wrong with Schedulers.computation. Then I changed it to subscribeOn(Schedulers.newThread()) and it seemed just ok.

What's the problem? Did I misuse something or is there a bug in RxJava or RxAndroid?
Thanks!

**Comment by akarnokd** [comment]
`Schedulers.computation` is the wrong kind of scheduler to be used with blocking operations. It has a limited number of threads so when it is exhausted by blocking flows, you'll end up with hangs.

**Comment by lancewoo** [comment]
> 
> 
> `Schedulers.computation` is the wrong kind of scheduler to be used with blocking operations. It has a limited number of threads so when it is exhausted by blocking flows, you'll end up with hangs.

Yes, login() is a blocking method.
That's the only place where I used RxJava in the whole application, nowhere else. Does it concern with other threads created in other Android ways? Which scheduler would be suggested then in this situation, `Schedulers.newThread()` or `Schedulers.io()`?
Thanks!

**Comment by akarnokd** [comment]
The io scheduler.
