### ISSUE TITLE
2.x: Unsafe threading in TestObserver

### ISSUE THREAD

**Issue by JakeWharton** [ReactiveX/RxJava#7055]
With 2.2.19 I have the following helper function:
```java
private static CursorAssert assertCursor(TestObserver<Query> o) {
  Query query = o.awaitCount(1).assertValueCount(1).values().remove(0);
```
This will occasionally throw AIOOB:
```
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
at java.util.ArrayList.remove(ArrayList.java:503)
at io.reactivex.internal.util.VolatileSizeArrayList.remove(VolatileSizeArrayList.java:140)
at com.example.assertCursor(..)
```
This should be impossible since `awaitCount` waits for the list size to be non-zero. It seems like there's some unsafe publication of the list's state, presumably from the lack of synchronization primitives.

**Comment by JakeWharton** [comment]
And if it wasn't clear, I'm testing an observable that emits on a scheduler so it's running concurrently with my test thread.

**Comment by akarnokd** [comment]
The underlying list is not protected against concurrent modification. The `assertCount` only indicates how many items are safe to be read from any thread.

**Comment by JakeWharton** [comment]
Should the values getter wrap in unmodifiable then? Right now the test fails probabilistically which is probably the worst of both options.

**Comment by akarnokd** [comment]
There exist tests that do such manipulation as they know no concurrent modification can happen. Changing the underlying behavior in both 2.x and 3.x would be drastic. 

Based on your example, you may want to try `blockingIterable().iterator()` which will block until there is an item to dequeue. The returned iterator implements `Disposable` if needed.

Btw, you have another possible race: `awaitCount(1).assertValueCount(1)`.

**Comment by akarnokd** [comment]
The best I can offer is to make the internal list customizable on 3.x.

**Comment by JakeWharton** [comment]
I don't think it's supremely important. Is there a strong argument against using a synchronized list? I'd be surprised if it had a performance impact of any significance.

**Comment by akarnokd** [comment]
It introduces barriers that can hide concurrency bugs in the general case. (The volatile list uses a weaker [size](https://github.com/ReactiveX/RxJava/blob/2.x/src/main/java/io/reactivex/internal/util/VolatileSizeArrayList.java#L72) tracking, which is the minimum given the [use site](https://github.com/ReactiveX/RxJava/blob/2.x/src/main/java/io/reactivex/observers/BaseTestConsumer.java#L1015).)

**Comment by JakeWharton** [comment]
Ah thanks. I'm fine without any change then, especially if no one else has a use-case. In the past I've used an explicit `BlockingTestSubscriber`, I was just trying to migrate away from it. In general I try to avoid real schedulers in tests but sometimes it's needed.
