### ISSUE TITLE
Wrong signature in onErrorResumeWith

### ISSUE THREAD

**Issue by marcin-onegini** [ReactiveX/RxJava#7075]
RxJava 3.0.0

Please add Throwable to the method onErrorResumeWith(@NonNull CompletableSource fallback), if it's supposed to be a replacement for onErrorResumeNext(@NonNull Function<? super Throwable,? extends CompletableSource> fallbackSupplier) then the parameters should be the same.

**Comment by akarnokd** [comment]
Not sure what you mean. `onErrorResumeWith` is supposed to be unconditional while `onErrorResumeNext` unambiguously only accepting a function:

https://github.com/ReactiveX/RxJava/wiki/What's-different-in-3.0#onerrorresumenext-with-source
