### ISSUE TITLE
RxJava Branching/Conditional operators [question][feature]

### ISSUE THREAD

**Issue by saeedntt** [ReactiveX/RxJava#7078]
We had this problem a while ago that we wanted to have branches for our flow. To set an example:

```
upstream
    .filter{ condition }
    .map {...}
    .filter { !condition }
    .map {...}
    .subscribe(...) // both maps generate same type of output
```
Which obviously does not work. Because the conditions are simply contradictory to each other. But we needed to process all the items but in different ways.

I am aware of grouping and other operators that can help with this need but all of them come down to having if else statements somewhere in the code.

So I have one question and one suggestion.
1) Is there any operator that can help branch the item flows in a linear way? (Not having inner blocks with if statements)
2) Is it a good idea to create a branching (or conditional) operator (like `parallel()/sequential()` in Flowable) that creates branches of the flow and merges them in the end? I wanted to contribute by adding this feature but thought it might be a good idea to ask first. Something like the following for the above example:
```
upstream
    .branch()
    .if { condition }
    .then {...}
    .if { !condition }
    .then {...}
    .else {...}
    .merge()
    .subscribe(...) // both maps generate same type of output
```

**Comment by akarnokd** [comment]
You can use `publish` to split the flow and merge them back:

```java

source.publish(shared ->
   merge(shared.filter()..., shared.filter()...)
)
```

**Comment by saeedntt** [comment]
That's Great.
So you don't think adding a branch operator is a good idea? It keeps the stream creation linear.

**Comment by akarnokd** [comment]
Not a good idea, the usage pattern differs from the generic RxJava approach.

At least you seem to be on Kotlin so you can add any DSL you see fit via extension methods.
