### ISSUE TITLE
BehaviorSubject recursively emits values

### ISSUE THREAD

**Issue by arkivanov** [ReactiveX/RxJava#7079]
RxJava 3.0.6, Android

Hello! When I call `BehaviorSubject.onNext()` from subscribe `onNext` callback, it calls the latter `onNext` recursively.

Here is the sample code:
```kotlin
        val s = BehaviorSubject.create<Int>()
        s.subscribe {
            Log.v("MyTest", "Received $it")
            if (it == 0) {
                Log.v("MyTest", "Emitting 1")
                s.onNext(1)
                Log.v("MyTest", "Emitted 1")
            }
        }
        s.onNext(0)
```

The output is:
```
Received 0
Emitting 1
Received 1
Emitted 1
```

Is this behavior expected?

**Comment by akarnokd** [comment]
Subjects are not reentrant by design. Use toSerialized() .

**Comment by arkivanov** [comment]
You probably meant "are reentrant"? Because they do emit recursively. Also this won't happen if subject has default value. And also if you emit one more value recursively. In last two cases items won't be emitted recursively.

**Comment by arkivanov** [comment]
```
val s = BehaviorSubject.createDefault<Int>(0)
        s.subscribe {
            Log.v("MyTest", "Received $it")
            if (it == 0) {
                Log.v("MyTest", "Emitting 1")
                s.onNext(1)
                Log.v("MyTest", "Emitted 1")
            }
        }
```
This will print:
```
Received 0
Emitting 1
Emitted 1
Received 1
```

**Comment by akarnokd** [comment]
Such recursive calls are not supported.
See http://reactivex.io/RxJava/3.x/javadoc/io/reactivex/rxjava3/subjects/BehaviorSubject.html

**Comment by arkivanov** [comment]
Thanks for clarification!
