### ISSUE TITLE
2.x - Observable.toFlowable(ERROR) not releasing upstream on MissingBackPressure

### ISSUE THREAD

**Issue by feneuilflo** [ReactiveX/RxJava#7081]
Hi

Code sample :
```
Observable.interval(1, TimeUnit.MILLISECONDS)
				.doFinally(() -> System.err.println("finally obs"))
				.toFlowable(BackpressureStrategy.ERROR)
				.doFinally(() -> System.err.println("finally flow"))
				.observeOn(Schedulers.computation())
				.map(any -> {
					System.out.println("any = " + any);
					Thread.sleep(1000);
					return any;
				})
				.subscribe(any -> {
				}, err -> {
					System.err.println(err.getMessage());
				});
```
With this code, a MissingBackPressureException is quickly generated and propagated through the downstream of `.toFlowable(BackpressureStrategy.ERROR)`, but it looks like the upstream is never disposed. Am I missing something ?

Tested with rxjava 2.2.19

**Comment by akarnokd** [comment]
Thanks for reporting. This is a bug with the operator in both 2.x and 3.x. I'll post fixes shortly.

**Comment by feneuilflo** [comment]
The fix works for me. Thanks for the quick answer and correction !
