### ISSUE TITLE
Addition of new operator mapIf in Flowable/Observable Resource

### ISSUE THREAD

**Issue by Piyush-Nagar** [ReactiveX/RxJava#7105]
- In version 3.x . 

  - This ticket is for proposing a new operator that can be included in Flowable/Observable resource.
     **Description:** There are many time when we use if else condition in map to conditionally map Flowable or Observable resource.
     **One Such Example:**  
 ```
Flowable.fromIterable(ImmutableList.of(1,2,3,4,5,6))
            .map(x -> {
                if(Math.floorMod(x,2) == 1) {
                    return "ODD";
                }
                return "EVEN";
            });
```
**Problem with this type of code:**
1) It makes code unreadable and unstructured.
2) It doesn't show case Single responsibility for code block inside map inherently.

**Proposed Operator mapIf:**
I have this use case many time and started using customised version of Rx java. Where I created mapIf operator for Flowable class. 

 **Map If method Signature:**
```
public final <@NonNull R> Flowable<R> mapIf(Predicate<? super T> predicate,
        @NonNull Function<? super T, ? extends R> ifMapper,
        @NonNull Function<? super T, ? extends R> elseMapper)  {
   // Logic
}
```
**Client code for above operator: (Implementation using mapIf)**

  ```
   Flowable.fromIterable(ImmutableList.of(1,2,3,4,5,6))
          .mapIf(isOddNumber(), mapToOdd(), mapToEven());

   private Function<Integer, String> mapToEven() {
        return map -> "EVEN";
    }

    private Function<Integer, String> mapToOdd() {
        return map -> "ODD";
    }

    private Predicate<Integer> isOddNumber() {
        return item -> Math.floorMod(item, 2) == 1;
    }
```

**Note:**
Would like to know with community whether it will make sense to add it as part of Open Source version of code (RxJava3). If yes, I am very much eager to raise PR for the same.

**Comment by JakeWharton** [comment]
I don't agree with either point listed as problems. Conditionals are fundamental constructs of the language which should be easily recognizable by anyone with cursory familiarity whereas this library and its operators are learned over time and number too many to have them all memorized. Your solution doesn't scale to if/elseif/else conditionals nor switches meaning that you now need to use two different forms depending on how complex the conditional is.

**Comment by akarnokd** [comment]
Such conditional mappins have been considered a long time ago and we deemed them too verbose just to replace the straightforward use of the `map` operator.

If, for some reason, you want such operators in your code, you can define a `FlowableTransformer`:

```java
public static <T, R> FlowableTransformer<T, R> mapIf(
         Predicate<? super T> predicate, 
         Function<? super T, ? extends R> trueMapper,
         Function<? super T, ? extends R> falseMapper) {
    return upstream -> upstream.map(v -> predicate.test(v) ? trueMapper.apply(v) : falseMapper.apply(v));
}

source.compose(mapIf(p, tm, fm))
...
```

**Comment by Piyush-Nagar** [comment]
@JakeWharton @akarnokd Thanks for giving confirmation and clarity.
