### ISSUE TITLE
Jump to the next item on a collection upon click event

### ISSUE THREAD

**Issue by cloudshooterhuman** [ReactiveX/RxJava#7111]
I have a collection of items that I use with an interval like bellow :

```
Observable.just(1, 2, 3, 4)
.zipWith(Observable.interval(3500, TimeUnit.MILLISECONDS), (item, interval) -> item) 
.subscribe()

```
Current flow is that each item is displayed for 3500 ms. What I want to achieve is to jump to next item if the user click on a button before reaching 3500 ms.

I tried to achieve that through a Subject but it didn't work.

**Comment by akarnokd** [comment]
Please do not cross post questions.

https://stackoverflow.com/questions/64794367/jump-to-the-next-item-on-a-collection-upon-click-event
