### ISSUE TITLE
Android Desuagr and AutoClosable

### ISSUE THREAD

**Issue by anuchandy** [ReactiveX/RxJava#7112]
I was evaluating RxJava for the android libraries we are building. I see that RxJava is desugar friendly, but noticed that few places rxjava is using Autoclosable [reference](https://github.com/ReactiveX/RxJava/blob/78b29f7967cd7589c3e53a4a8a73ad2aadb30eff/src/main/java/io/reactivex/rxjava3/internal/jdk8/MaybeFlattenStreamAsObservable.java#L67); this is a type not yet available in [desugar core-library](https://github.com/google/desugar_jdk_libs). Do I need to worry about this? Any chance that this path can hit when running on android?

**Comment by akarnokd** [comment]
Afaik, AutoCloseable has been part of Android from early on and there were no issues reported regarding its use in RxJava.

**Comment by anuchandy** [comment]
thanks David!

The `AutoClosable` is introduced in API level 19 [reference](https://developer.android.com/reference/java/lang/AutoCloseable). If we set minSdkVersion 18 and run the android `newAPI` linter, the linter will report it as "Call require API level 19 (current min is 18)". 

If we run newAPI linter (with minSdkVersion 18) with desugaring enabled, still we get the same report, which is expected given the desugar core-lib don't have this type yet.

If we look at the byte-code, we can see that the byte code has a direct reference to this type:

```java
const-class v0, Ljava/lang/AutoCloseable;
```

I don't have a real device with L18 installed to validate this and the emulator seems to resolve to my local JDK type.

I'm not an expert in this space, but just thought of letting you know.

\\cc @JakeWharton, Jake do you have any thoughts on this?

**Comment by akarnokd** [comment]
I don't know. We isolated Java 8-related code such that if one doesn't use those operators, their classes should not end up in the code. Btw the desugar library does reference `AutoCloseable` in relation to [Stream](https://github.com/google/desugar_jdk_libs/blob/39251fe2a0f41f3bbaca81bb3619ac70dccb342d/src/share/classes/java/util/stream/BaseStream.java#L65).

**Comment by anuchandy** [comment]
I think I found it; though AutoCloseable is exposed only starting from L19, it does exist in the rt for L14; here is the java.lang package for L14: https://android.googlesource.com/platform/libcore/+/refs/tags/android-4.0.1_r1.2/luni/src/main/java/java/lang/

So I think though we get a compile error, it resolves correctly at runtime.

jfyi: 

for each version of Android, the source-code git-tag is here: https://source.android.com/setup/start/build-numbers#source-code-tags-and-builds

**Comment by anuchandy** [comment]
Here is a comment from Google dev: https://issuetracker.google.com/issues/36999599#comment4 , which I think implies that ICS (Ice-cream-sandwich L14) include `AutoClosable`.

**Comment by anuchandy** [comment]
Closing this issue, since we've got the answer now.
