### ISSUE TITLE
TestScheduler doesn't use RxJavaPlugins.onSchedule hook

### ISSUE THREAD

**Issue by Dimezis** [ReactiveX/RxJava#7119]
RxJava 2.2.20 and 3.0.7.
`TestScheduler` doesn't use `RxJavaPlugins.onSchedule` hook when scheduling tasks.
I believe this is an omission and it should respect the hooks just as other Schedulers do.

**Comment by akarnokd** [comment]
It was not meant to be hookable like the standard schedulers. What is your use case?

**Comment by Dimezis** [comment]
Long story short, to transfer the gRPC Context when scheduling the tasks with Rx Schedulers.
We replace the Schedulers with `TestScheduler` in some of our integration tests for timing control, but then the Context propagation breaks

**Comment by akarnokd** [comment]
I see. 

There are currently no plans to change the `TestScheduler` in this regard. You can instead create a delegating `Scheduler` implementation backed by a `TestScheduler` and intercept any `schedule*` method calls on it and its `Worker`.
