### ISSUE TITLE
TestObserver error messages should include more information about values where possible

### ISSUE THREAD

**Issue by derektom14** [ReactiveX/RxJava#7125]
This applies to both 2.x and 3.x, and while I'd like this to be fixed in 2.x, it's more of a frustration than a bug.

Suppose I'm trying to assert that a value from a `TestObserver` is equal to a particular value. I write this test:
```kotlin
Single.just("foo").test().assertValue("bar")
```
and get this helpful error message:
```
java.lang.AssertionError: expected: bar (class: String) but was: foo (class: String) (latch = 0, values = 1, errors = 0, completions = 1)
Expected :bar (class: String) 
Actual   :foo (class: String) (latch = 0, values = 1, errors = 0, completions = 1)
```
(Never mind that the "Actual" in this case includes extra information, it conveys what it needs to.)

Suppose that I instead use a predicate:
```kotlin
Single.just("foo").test().assertValue { it.equals("goodbye", ignoreCase = true) }
```
Now I get this error message instead:
```
java.lang.AssertionError: Value not present (latch = 0, values = 1, errors = 0, completions = 1)
```
I'm told that the value isn't present, which is slightly misleading as "not present" is different than "does not match predicate." But more importantly, I don't see what the "not present" value is, which is immensely helpful when debugging the test. My usual solution here is to use something like this instead:
```kotlin
Single.just("foo").test().assertValue {
    assert(it).isEqualTo("bar", ignoreCase = true)
    true
}
```
This code is more clunky, but gives me the actual value in the error message:
```
java.lang.AssertionError: 
Expected :"[bar]"
Actual   :"[foo]"
```
The cost is that I lose useful `(latch = 0, values = 1, errors = 0, completions = 1)` information.

Instead of having to make a choice between these two, it would be most helpful if the simplest solution was also just as informative:
```
java.lang.AssertionError: Value bar (class: String) did not match predicate (latch = 0, values = 1, errors = 0, completions = 1)
```

This extends to many other assertions as well. For example, if I called `assertNoValues()` but there was a value? I'd like to know what that value was.

**Comment by akarnokd** [comment]
> The cost is that I lose useful (latch = 0, values = 1, errors = 0, completions = 1) information

With `Single`, you have 3 states: not finished, success, failure. You can rule out the first two via `assertComplete` and `assertNoErrors`, then use your predicate that captures the value for you. Since you are on Kotlin, you can even make an extension method for it.

**Comment by derektom14** [comment]
If I change the order by checking `assertComplete` first:
```
BehaviorSubject.createDefault("foo").test().assertComplete().assertValue { it.equals("bar", ignoreCase = true)}
```
then if the chain is not completed, I will learn that first, without learning the value, even if knowing the value would be more useful for debugging:
```
java.lang.AssertionError: Not completed (latch = 1, values = 1, errors = 0, completions = 0)
```

Even then, with a more complicated workaround available, why shouldn't the library's provided assertion method provide information (the exact value that failedthe predicate) that any programmer would like to know when their test fails? The only drawback I can think of is if the value has an overly long and unhelpful `toString`, but that's a minor drawback compared to the usefulness of seeing the value in all cases.

**Comment by akarnokd** [comment]
The library provides a limited set of assertions based on community feedback and usage. For anything more complicated, the `TestObserver` can be extended and you'll have direct access to the [received events](https://github.com/ReactiveX/RxJava/blob/67c1a367397f1167f9ad5639dd5071b6608e4230/src/main/java/io/reactivex/rxjava3/observers/BaseTestConsumer.java#L35-L39) as well as add on-class methods. This will also let you call [fail()](https://github.com/ReactiveX/RxJava/blob/67c1a367397f1167f9ad5639dd5071b6608e4230/src/main/java/io/reactivex/rxjava3/observers/BaseTestConsumer.java#L96) to produce that particular formatted error message.

**Comment by derektom14** [comment]
I'm not asking for a new assertion to be added, but for the existing assertion to have a better error message. Is there a reason for the "value not present" error message to not contain the value that failed the predicate?

**Comment by akarnokd** [comment]
It didn't fit the pattern expected vs actual because with a predicate there is no way to tell the expected, hence the actual was not considered to be printed either.

After further considerations and looking at other methods, the error message across the tester class can be improved. I'll prepare a PR with the changes.

**Comment by derektom14** [comment]
Thanks!
