### ISSUE TITLE
Flaky Test 3x

### ISSUE THREAD

**Issue by shaker-project** [ReactiveX/RxJava#7136]
Hello, we are a group of researchers interested in understanding methods to reduce costs associated with Test Flakiness [1]. We developed an approach to detect flaky tests, dubbed Shaker [2]. Shaker spawns stressor tasks in the running environment (e.g., tasks that consume lots of cpu or memory) to identify if perturbations can make tests fail.

We ran Shaker on RxJava project and found the following likely flaky tests:

* synchronizationOfMultipleSequencesLoop -  failed 1 time in 12 reruns.
* blockingSourceAsnycCancel - failed 1 time in 12 reruns.

We sincerely hope that this can be useful information and look forward to hearing back.
 

[Denini](https://github.com/denini08), [Leopoldo](https://github.com/leopoldomt) and [Marcelo](https://github.com/damorim).

[1] https://hackernoon.com/flaky-tests-a-war-that-never-ends-9aa32fdef359

[2] D. Silva, L. Teixeira and M. d’Amorim, "Shake It! Detecting Flaky Tests Caused by Concurrency with Shaker," 2020 IEEE International Conference on Software Maintenance and Evolution (ICSME), Adelaide, Australia, 2020, pp. 301-311, https://ieeexplore.ieee.org/document/9240694/.

**Comment by akarnokd** [comment]
Thanks for the information.

We have a few tests that rely on `Thread.sleep` to provide real-time interleaving. If, for some reason, they sleep too little or too much, the tests fail. This is relatively rare thus not much of a problem, a suite restart usually makes the tests pass.

I'll read the linked material but don't plan on changing these tests for now.
