### ISSUE TITLE
2.x: Question about threading and doFinally()

### ISSUE THREAD

**Issue by BorisLaskov** [ReactiveX/RxJava#7137]
I am using RxJava 2 on Android. The modifyUi() function inside doFinally() should be called from main thread only.
```
task_1
    .subscribeOn(Schedulers.io())
    .doOnSuccess { ... }
    .flatMap { 
        task_2
            .subscribeOn(Schedulers.io()) 
    }
    .observeOn(AndroidSchedulers.mainThread())
    .doFinally { modifyUi() }
```
However, there are certain edge cases where observeOn() is ignored and doFinally() is fired in background.

Question 1: What these cases can be? So far, I've discovered only one of them - a very fast disposing of the chain. If I add
```
.doOnSubscribe { it.dispose() }
```
right after doFinally(), observeOn() becomes ignored, so doFinally() is fired from background. Why is that and what the other cases can be?

Question 2: Is there any reliable way to clean up the chain once it's done that can be set to a particular thread? As I see, doFinally() fails in some cases. Should I resort to duplicating the cleanup code in onSuccess() and onError() methods of the observer/consumer in subscribe()?

**Comment by akarnokd** [comment]
`doFinally` can run when the downstream disposes on whatever thread it is on, thus `observeOn` has likely no effect. You can apply `unsubscribeOn` after `doFinally` to make sure any dispose call is routed to the desired thread.

**Comment by BorisLaskov** [comment]
Thank you for the clarification :)
