### ISSUE TITLE
How to solve it

### ISSUE THREAD

**Issue by zhupengxiang** [ReactiveX/RxJava#7138]
No static method disposed()Lio/reactivex/rxjava3/disposables/Disposable; in class Lio/reactivex/rxjava3/disposables/Disposable; or its super classes (declaration of 'io.reactivex.rxjava3.disposables.Disposable' appears in /data/app/com.gctech.cloudcomputing-4s9INhkO3A0fdFgfsEU-Aw==/base.apk!classes2.dex)

**Comment by akarnokd** [comment]
Could be anything from old tool versions, mismatched tool versions to multidex shenanigans. Please ask this question on StackOverflow.

**Comment by fsbarata** [comment]
(Sorry for closed thread posting, had this problem myself)

Disposable.disposed() became a static method in an interface (Java 8 feature) since RxJava 3. It is likely that enabling desugar will solve this issue.

**Comment by AgiMaulana** [comment]
@fsbarata Enabling Java 8 desugar doesn't remove the issue on my code

```
compileOptions {
    coreLibraryDesugaringEnabled true
    sourceCompatibility JavaVersion.VERSION_1_8
    targetCompatibility JavaVersion.VERSION_1_8
}

kotlinOptions {
    jvmTarget = "1.8"
}

dependencies {
    coreLibraryDesugaring 'com.android.tools:desugar_jdk_libs:1.1.5'
}
```

**Comment by sahil2441** [comment]
Has anyone found a fix for this, yet ?
