### ISSUE TITLE
2.x, 3.x: Feature for detecting leaked subscriptions

### ISSUE THREAD

**Issue by andreyfomenkov** [ReactiveX/RxJava#7142]
Hi guys,

I was facing a problem in the project with RxJava onboard: some subscriptions were not disposed due to a bug. It's quite hard to find this kind of bugs and such situation can cause memory leak.
So, I decided to write a tool that generates HTML report with detailed info about all **not** disposed subscriptions in application. The output report includes:
- stack trace;
- number of calls;
- observable type.

Project on GitHub: [RxDisposableWatcher](https://github.com/andreyfomenkov/rx-disposable-watcher), compatible with 2.x and 3.x
Post on Medium: [Detect Leaked Subscriptions in RxJava code using RxDisposableWatcher](https://andrey-fomenkov.medium.com/find-leaked-subscriptions-in-rxjava-code-using-rxdisposablewatcher-8c2226dce01c)

I found it very useful. How do you think guys, does it make sense to create PR and integrate this kind of feature into RxJava?
Thank you!

**Comment by akarnokd** [comment]
Hi.

It is completely fine to have 3rd party offerings for certain features in their own respective libraries. For example, some [debug support](https://github.com/akarnokd/RxJavaExtensions#debug-support) lives separately.

Generally, unless there is a need for accessing RxJava internals, we don't include such extensions in RxJava proper. In some cases though ([example](https://github.com/ReactiveX/RxJava/pull/5590)), we may expanded the plugin surface to help with 3rd party tooling.
