### ISSUE TITLE
Can i execute more observables sequentially?

### ISSUE THREAD

**Issue by rensocontreras** [ReactiveX/RxJava#7146]
I'm using Firebase to get objects a real time, I would like to execute more observables sequentially (first in first out) because I have a concurrency problem, thanks you!
- void getDispatch(Dispatch dispatch) receive an object by Firebase.

public void getDispatch(Dispatch dispatch) {
                    Single<DispatchAction> observable =  Single.just(dispatch)
                    .map(order1 -> {
                        return convertDispatch(order1);
                    });
    
                   DisposableSingleObserver<DispatchAction> actionDisposableObserver = new  DisposableSingleObserver<DispatchAction>(){
                        @Override
                        public void onSuccess(DispatchAction action) {//Process result }
    
                        public void onError(Throwable e) {//Error }
     };
    
                        compositeDisposable.add(
                            observable
                                    .subscribeOn(Schedulers.single())
                                    .observeOn(AndroidSchedulers.mainThread())
                                    .subscribeWith(actionDisposableObserver)
                         );
    }

**Comment by akarnokd** [comment]
Please do not cross-post questions.
https://stackoverflow.com/questions/65631933/rxjava-execute-more-observables-sequentially
