### ISSUE TITLE
1.x  RxIoThread state is WAITING and task is null but won't be clearup

### ISSUE THREAD

**Issue by ShiminChen007** [ReactiveX/RxJava#7147]
![rxjava](https://user-images.githubusercontent.com/32054178/104536044-43d0da80-5652-11eb-9b01-4d2aa47f06ed.png)
i dont know what it  has happen

**Comment by akarnokd** [comment]
Afaik, Java's Executors tend to do timed sleep if they don't have work to do. The particular IO worker of RxJava should eventually get stopped by a cleanup routine.

**Comment by ShiminChen007** [comment]
> ![rxjava](https://user-images.githubusercontent.com/32054178/104536044-43d0da80-5652-11eb-9b01-4d2aa47f06ed.png)
> i dont know what it has happen

those  thread keep alive forever  but all of them state is WAITING, wont be clearup. so my project will group up  RxIoThread more and more

**Comment by ShiminChen007** [comment]
> Afaik, Java's Executors tend to do timed sleep if they don't have work to do. The particular IO worker of RxJava should eventually get stopped by a cleanup routine.

some of RxIoScheduler- thread wont be clearup forever ,  i dont know why. they are always state WAITING. but i have write a test      , but  all WAITING thread will be clearup  after 2min when those thread state is WAITING

**Comment by akarnokd** [comment]
Is this an Android App? Does it happen in the simulator? What versions? Have you tried doing a thread dump to see if it really waiting in the executor? Try `newThread` and see if those leak, indicating something in your code is not unsubscribing.

**Comment by ShiminChen007** [comment]
> Is this an Android App? Does it happen in the simulator? What versions? Have you tried doing a thread dump to see if it really waiting in the executor? Try `newThread` and see if those leak, indicating something in your code is not unsubscribing.

yes, is run an Android App, but i have write test  and will recycle those thread when they WAITING and  task is null, but my app wont be clearup, so sad , i try newThread and see it
