### ISSUE TITLE
2.x, 3.x RejectionExecutionException is not handled properly in FlowableObserveOn operator

### ISSUE THREAD

**Issue by ansip** [ReactiveX/RxJava#7149]
there is a bug: in case if RejectionExecutionException is thrown by Executor this exception is just swallowed and is not propagated to external code. As the result such subscription is stuck

TestSubscriber<Integer> s = new TestSubscriber<>();
Flowable.just(1,2,3,4,5).observerOn(scheduler).subscribe(s);
s <<< does not receive anything, neither values nor error nor completion
any subsequent values also will be ignored, the subscription is stuck

**Comment by akarnokd** [comment]
`RejectionExecutionException` would be thrown if the underlying `Executor` gets shut down or runs on a bounded pool.

For the first case (shutdown), don't just shut down the executor, but have all outstanding flows depending on that scheduler cancelled too.

For the second case (bounded pool), there is no reason to bound the pool underneath RxJava; just use `Flowable`s for backpressure and thus implicit limit the amount of work.

As I mentioned in the PR, this can't be handled reasonably within RxJava. In essence, threads are critical resources, similar to memory, thus unavailability is a fatal error that can't be handled or recovered from within RxJava.

**Comment by ansip** [comment]
but backpressure is about scope of one subscription.... what if I want to limit resources across the whole process and not to store all incoming tasks to my executor

it seems a big limitation of api (bounded pool) and critical bug, because consumer can't even understand what happened with subscription, it is very hard to investigate such issues

maybe fix could be copied from here?
https://github.com/reactor/reactor-core/blob/master/reactor-core/src/main/java/reactor/core/publisher/FluxPublishOn.java

**Comment by akarnokd** [comment]
What resources do you want to limit? Backpressure can limit the number of items, thus memory. Using `computation`, `single` or a fixed-parallelism Executor limits the task amount. Yes, you can still create an unlimited amount of Flowables, but in that case, make the creation of such Flowables itself a backpressured Flowable.

> it is very hard to investigate such issues

The global error handler is notified.

> maybe fix could be copied from here?

There was a discussion back then and I warned about the implications and consequences. You can see a [few](https://github.com/reactor/reactor-core/issues?q=is%3Aissue+RejectedExecutionException+is%3Aclosed) reported. So no, we won't adapt their way of dealing with the problem.

**Comment by ansip** [comment]
> Yes, you can still create an unlimited amount of Flowables, but in that case, make the creation of such Flowables itself a backpressured Flowable.

 Yes I meant this, that it is possible executor is limited and used to serve not only scheduler's tasks in the entire process

Ok I understood your position, does it make sense at least to mention this behavior and consequences of bounded pool usage in docs to `Schedulres.from` method?

**Comment by akarnokd** [comment]
> does it make sense at least to mention this behavior and consequences of bounded pool usage in docs to Schedulres.from method

Yes. I'll add the notes to the methods.
