### ISSUE TITLE
2.x Requesting 1 results in a request of 2

### ISSUE THREAD

**Issue by jameskleeh** [ReactiveX/RxJava#7155]
I've done my best to extract the code required to reproduce this error, however I haven't been able to do so. I have a test that can be executed to show the error.

The problem:

1 item is requested and 2 get delivered.

The context:

This test asserts that back pressure is respected and only requests one item where 2 could be delivered. This test works prior to my changes from using Flowable to Single.

See the test:
https://github.com/micronaut-projects/micronaut-core/blob/client-single/http-client/src/test/groovy/io/micronaut/http/client/JsonStreamSpec.groovy#L131

If you clone https://github.com/micronaut-projects/micronaut-core, checkout the `client-single` branch, and execute the [JsonStreamSpec](https://github.com/micronaut-projects/micronaut-core/blob/client-single/http-client/src/test/groovy/io/micronaut/http/client/JsonStreamSpec.groovy#L131) you will find that it fails. It fails because the second item is delivered when it should not be. Note that the [DataStreamSpec](https://github.com/micronaut-projects/micronaut-core/blob/client-single/http-client/src/test/groovy/io/micronaut/http/client/DataStreamSpec.groovy#L91) has a similar test and it works correctly. I suspect this is related to the usage of the [JacksonProcessor](https://github.com/micronaut-projects/micronaut-core/blob/client-single/http-client/src/main/java/io/micronaut/http/client/netty/DefaultHttpClient.java#L903). A breakpoint can be placed in the `receiveDemand` method of [HandlerPublisher](https://github.com/micronaut-projects/micronaut-core/blob/client-single/http-netty/src/main/java/io/micronaut/http/netty/reactive/HandlerPublisher.java#L525) to see the demand comes in as 2.

If you're unfamiliar with Gradle/Spock, the test can be executed with `./gradlew http-client:test --tests "io.micronaut.http.client.JsonStreamSpec.test read JSON stream demand one"`

The changes in [this PR](https://github.com/micronaut-projects/micronaut-core/pull/4808/files) are responsible for the failure, however they only consist of changing from Flowable to Single.

Any assistance or guidance is appreciated.

Thanks!

**Comment by akarnokd** [comment]
> A breakpoint can be placed in the receiveDemand method of HandlerPublisher to see the demand comes in as 2.

Try placing breakpoints along the way. Check if the test requests 2, do you get 3 or 4 in `receiveDemand`? Does the `JacksonProcessor` pass the TCK ([example](https://github.com/reactive-streams/reactive-streams-jvm/blob/master/tck/src/test/java/org/reactivestreams/tck/LockstepProcessorTest.java))?

**Comment by jameskleeh** [comment]
@akarnokd I have done some extensive debugging and it seems like there are 2 subscribers (StrictSubscriber class) that hold the request of 1, and when the downstream subscribe happens, they get added together.

**Comment by akarnokd** [comment]
As far as I can tell, the `upstreamDemand` gets incremented after the first json message is posted to the downstream and the next record is pushed irrespective of the actual downstream demand.

[SingleThreadedBufferingSubscriber.java#L91](https://github.com/micronaut-projects/micronaut-core/blob/client-single/core/src/main/java/io/micronaut/core/async/subscriber/SingleThreadedBufferingSubscriber.java#L91)
...
[JacksonProcessor.java#L187](https://github.com/micronaut-projects/micronaut-core/blob/client-single/runtime/src/main/java/io/micronaut/jackson/parser/JacksonProcessor.java#L187)
[JacksonProcessor.java#L218](https://github.com/micronaut-projects/micronaut-core/blob/client-single/runtime/src/main/java/io/micronaut/jackson/parser/JacksonProcessor.java#L218)
...
[SingleThreadedBufferingSubscriber.java#L96](https://github.com/micronaut-projects/micronaut-core/blob/client-single/core/src/main/java/io/micronaut/core/async/subscriber/SingleThreadedBufferingSubscriber.java#L96)

The unconditional call at [JacksonProcessor.java#L187](https://github.com/micronaut-projects/micronaut-core/blob/client-single/runtime/src/main/java/io/micronaut/jackson/parser/JacksonProcessor.java#L187) looks suspicious.

This quick test indicates `JacksonProcessor` does not behave correctly:

```groovy
    void "jacksonprocessor directly"() {
        given:
        Flowable<byte[]> source = Flowable.just(
                "{ \"value\": 0 }".getBytes(StandardCharsets.ISO_8859_1),
                "{ \"value\": 1 }".getBytes(StandardCharsets.ISO_8859_1)
        )
        JacksonProcessor jp = new JacksonProcessor()
        TestSubscriber<Object> ts = new TestSubscriber<>(0L)

        when:
        jp.subscribe(ts)

        source.subscribe(jp)

        ts.assertEmpty()

        ts.request(1)

        then:
        ts.assertValueCount(1)
    }
```

**Comment by akarnokd** [comment]
I'm closing this issue since it is not an error with RxJava but with the custom `JacksonProcessor` of Micronaut.

I suggest checking out the [partial collect](https://github.com/akarnokd/RxJavaExtensions/blob/3.x/src/main/java/hu/akarnokd/rxjava3/operators/FlowablePartialCollect.java) operator.
