### ISSUE TITLE
[question] Multiple doFinally and their order

### ISSUE THREAD

**Issue by dmandalidis** [ReactiveX/RxJava#7156]
Hi all,

Consider the following:
```
Observable.just(1,  2, 3)
	    	.map(s -> {
	    		if (s == 2) {
	    			throw new RuntimeException();
	    		}
	    		return s;
	    	})
    		.doFinally(() -> System.out.println("error 1"))
    		.doFinally(() -> System.out.println("error 2"))
    		.blockingSubscribe();
```

This prints:
```
error 2
error 1
```

If I move the `map` operator after the two `doFinally`, it prints:
```
error 1
error 2
```

I would expect that, no matter where the `map` operator is placed, I should have always get the second printout of errorX (error1 and error2 in that order). Can somebody explain this behavior?

I 'm using RxJava 2.2.16

**Comment by akarnokd** [comment]
When `map` is after `finally`, the crash will first cancel the upstream, and on the return angle, it invokes the finally actions top-down:

```
map.crash
    map.cancel
        doFinally.cancel // 2nd
            doFinally.cancel // 1st
                just.cancel
            doFinally.action -> print error 1
        doFinally.action -> print error 2
    map.onError
        observer.onError
```

When the `map` is before the finally's, the error is propagated to the end observer and the finally actions are invoked bottom-up.

```
map.crash
    map.cancel
        just.cancel
    map.onError
        doFinally.onError // 1st
            doFinally.onError // 2nd
                observer.onError
            doFinally.action -> print error 2
        doFinally.action -> print error 1
```
