### ISSUE TITLE
intervalRange behaviour

### ISSUE THREAD

**Issue by cloudshooterhuman** [ReactiveX/RxJava#7158]
As per documentation `intervalRange` : 
>The sequence completes immediately after the last value (start + count - 1) has been reached.

Which mean `doOnComplete` is called directly once the last interval is reached (and not _completed_)

```
private fun launchQuestionGame() {
        Flowable
            .fromIterable(mQuestions.asIterable()) // mQuestions contains 3 items

            .zipWith(
                startTimeIntervalAndCancelItUponUnUneButtonClick(mQuestions.size + 1)

                    .observeOn(AndroidSchedulers.mainThread())
                    .doOnEach {
                        onEachIntervalEmittion(it)
                    }

                    .repeat(mQuestions.size.toLong()), // repeat the interval mQuestions.size.toLong() times.

                BiFunction { t1: Question, _: Long ->
                    Timber.d(t1.toString())
                    doOnCompleteEachFile(t1)
                })

            .doOnComplete {
                Timber.d("doOnComplete")
                doOnCompleteAllFiles()
            }

            .subscribe()
    }
```

2021-01-23 18:38:49.526 17549-17549/ Item 1
2021-01-23 18:38:53.531 17549-17549/ Item 2
2021-01-23 18:38:57.527 17549-17549/ Item 3
2021-01-23 18:38:57.544 17549-17549/ doOnComplete

I tried to delay before `doOnComplete` but it doesn't work.

Is there anyway to have `doOnComplete` called after the last interval is finished ?

**Comment by akarnokd** [comment]
I don't understand your question. If you want to execute `doOnComplete` with a similar delay as between the items, append a timer:

```kotlin

     .zipWith ( ... )
     .concatWith(Completable.timer(4, TimeUnit.SECONDS))
     .doOnComplete {
           Timber.d("doOnComplete")
           doOnCompleteAllFiles()
      }
```

**Comment by cloudshooterhuman** [comment]
Thank you it did  work gracfully. just curious, why `delay` didn't have the same effect as ` .concatWith(Completable.timer(4, TimeUnit.SECONDS))` ?
