### ISSUE TITLE
Question: Opposite to throttleFirst operator: not throttle but collect.

### ISSUE THREAD

**Issue by tomomoto** [ReactiveX/RxJava#7185]
I need following operator which when element comes, starts the timer (creates window for elements) and collects them into `List` or `Observable/Flowable`. When time specified for the timer ends and no element comes, the operator doesn't send empty event. When next element comes, new timer is created and it starts to collect elements.

Rx java have Buffer and Window operator but this operators have disadvantages:

Buffer http://reactivex.io/documentation/operators/buffer.html with signature
`buffer(long timespan, TimeUnit unit)` almost fits but it produces empty events when no elements in timespan comes.

Window http://reactivex.io/documentation/operators/window.html with signature
`window(long timespan, TimeUnit unit)` almost fits but it produces empty Observables/Flowables when no elements in timespan comes.

It is possible to filter this empty elements but I would like to avoid polluting scheduler with empty events with `List/Observable-s/Flowable-s`.

I spend some time and found very similar formally, but functionally fulfilling the opposite role
`throttleFirst(long windowDuration, TimeUnit unit)` 
https://raw.githubusercontent.com/wiki/ReactiveX/RxJava/images/rx-operators/throttleFirst.png

But unfortunately it throttles, but not collect items.

**Comment by akarnokd** [comment]
Please do not cross post issues.

https://stackoverflow.com/questions/66151738/rxjava-opposite-for-throttlefirst-operator-not-throttling-but-collecting

**Comment by tomomoto** [comment]
@akarnokd Thanks for the reply on the stackoverflow. But probable this operator deserves to be native rx-java operator?
What do you think?

**Comment by akarnokd** [comment]
No. This is an uncommon pattern to be made an operator in RxJava proper.
