### ISSUE TITLE
2.x, 3.x: Unexpected behaviour when calling TestScheduler.advanceTimeBy() with >=Long.MAX_VALUE nanos

### ISSUE THREAD

**Issue by scorpeeon** [ReactiveX/RxJava#7187]
Tested this on 2.2.20, but looking at the codebase it should affect 3.x too.

I see 2 different problems when calling TestScheduler.advanceTimeBy() with >=Long.MAX_VALUE nanos (or equivalent other units):
 - Anything higher than Long.MAX_VALUE nanoseconds will be truncated
 - It will trigger all actions, even if some events should be scheduled later than this.

You might ask why would I use this with such large numbers, and while I agree the real-world impact is limited, I was writing a Unit test to check for handling a possible overflow scenario, and saw some unexpected behaviour.

Given
`private var testScheduler = TestScheduler()`

To demonstrate the issue, If I run
`testScheduler.advanceTimeBy(106751, TimeUnit.DAYS)`
Everything works as expected.

However if I run
`testScheduler.advanceTimeBy(106752, TimeUnit.DAYS)`
Suddenly it behaves differently, it will trigger all actions, even if some events should be scheduled later than this.

On this line within TestScheduler.advanceTimeBy(): https://github.com/ReactiveX/RxJava/blob/4e86963d9710d4f8fcbba0451e250237f4db15f8/src/main/java/io/reactivex/rxjava3/schedulers/TestScheduler.java#L139

This code:
`time + unit.toNanos(delayTime)`
Will truncate anything bigger than Long.MAX_VALUE, as documented by the method:
java.util.concurrent.TimeUnit.toNanos()

So basically anything higher will be the equivalent of calling it with Long.MAX_VALUE:
`testScheduler.advanceTimeBy(9223372036854775807L, TimeUnit.NANOSECONDS)`

Which is clear, however you wouldn't expect this conversion to nano and possible truncation issue as a consequence when just looking at advanceTimeBy()'s signature, as demonstrated by my previous example.

For demonstrating the issue, where all actions are triggered when calling it with Long.MAX_VALUE, even if some events should be scheduled later than that, this will fail (as it should):
```
val testObserver = Observable.timer(Long.MAX_VALUE, TimeUnit.DAYS).test()
testScheduler.advanceTimeBy(Long.MAX_VALUE - 1, TimeUnit.NANOSECONDS)

testObserver.assertComplete()
```

But this will succeed (even though it shouldn't):
```
val testObserver = Observable.timer(Long.MAX_VALUE, TimeUnit.DAYS).test()
testScheduler.advanceTimeBy(Long.MAX_VALUE, TimeUnit.NANOSECONDS)

testObserver.assertComplete()
```

I suppose it could be an implementation limitation where Long.MAX_VALUE nanos are just treated as infinity when advancing the time, however I also don't think you'd expect this just by looking at the method signature and documentation.

**Comment by akarnokd** [comment]
We are using `long` so it may simply overflow when using too big numbers. Any down to earth amount should be fine. 

Closing as wont fix.
