### ISSUE TITLE
GC friendly `Single.zip` operator

### ISSUE THREAD

**Issue by zireael-0** [ReactiveX/RxJava#7195]
Version 3.0.10

Hey there, 

My use case requires me to load huge datasets into memory. I need multiple of those datasets to cross compare them in their entirety. I decided to use the `Single.zip` operator to combine them.

Example:

```java
public static void main(String[] args)
{
  Single.zip(
      Single
          .defer(() -> Single.just(buildHumongousCollection()))
          .subscribeOn(Schedulers.computation()),

      Single
          .defer(() -> Single.just(buildHumongousCollection()))
          .subscribeOn(Schedulers.computation()),

      (z1, z2) -> new Collection[]{ z1, z2 }
  )
      .map(zip ->
      {
        // do anything with any operators, for example building new objects from the source set
        return new String[]{ "Foo", "Bar", "Baz" };
      })
      .blockingSubscribe(result ->
      {
        // just here to allow setting a breakpoint
        for ( final var msg : result ) { System.out.println(msg); }
      });
}

private static Collection<byte[]> buildHumongousCollection()
{
  final var rand = new Random();

  final var result = new LinkedList<byte[]>();
  for ( int i = 0; i < 50_000_000; i++ )
  {
    final var buff = new byte[32];
    rand.nextBytes(buff);
    result.add(buff);
  }

  return result;
}
```

I noticed that when I reach `onNext` of my Observer within `subscribe` in my execution chain, The memory is still allocated and will never be collected. So I started to investigate and found the cause of it.

The `ZipCoordinator` within `SingleZipArray` does not drop the local value collection after completion:

https://github.com/ReactiveX/RxJava/blob/09b2b1b4c9428616b2634a67bea0ee5a09201007/src/main/java/io/reactivex/rxjava3/internal/operators/single/SingleZipArray.java#L106-L121

Since the ZipCoordinator will always reside within the stack of one of the living threads, the garbage collector will never collect the it and therefore also the dataset even though it can never be used again. The only way to access it is through private fields.

I'd suggest to insert
```java
values = null;
```
at 118 - it should allow gc to free the memory.

**Comment by akarnokd** [comment]
A temporary workaround for you could be `onTerminateDetach`.

`Arrays.fill` would be better so that `values` can remain final. Also `dispose` could clean the values too. `Maybe` could be verified in this regard. Would you like to submit a PR?
