### ISSUE TITLE
3.x: Convert License from dangling Javadoc to block comment

### ISSUE THREAD

**Issue by benjamintboyle** [ReactiveX/RxJava#7204]
The License block at the beginning of all java files is a dangling Javadoc which results in a minorly annoying warning in Intellij. Convert all headers to regular Java block comment. Licenses are not all standardized across files. Use most common License as standard.

Update Checkstyle to validate all Java files have License header. Remove custom unit test FixLicenseHeaders currently used to validate License.

**Comment by akarnokd** [comment]
Closing via #7205
