### ISSUE TITLE
Apparent conflict in different overloads of Single .subscribe() method

### ISSUE THREAD

**Issue by RobLewis** [ReactiveX/RxJava#7215]
Trying to port some code to RxJava 3 and I'm very confused. 

I just checked again, and the consensus seems to be that _all overloads of a Java method *must* have the same return type._ 

However, in the Javadoc for the `Single<T>` class, it's stated that the version of `subscribe()` that is called with a `SingleObserver` returns `void`, while all other overloads return a `Disposable`. 

What am I missing? (I haven't checked this for the other types of emitter.)

**Comment by akarnokd** [comment]
With `subscribe(SingleObserver)`, there is no good way to return anything because the caller can't know when the actual `SingleObserver` implementation would receive a `Disposable` and if it is safe to call `dispose` on it with respect to what else might happen inside the `SingleObserver`.

With the lambda-subscribe method, the internal implementation makes sure it can be disposed at any time safely thus it can return a `Disposable`.

Consequently, existing users were familiar with the methods `subscribe` and the Reacive Streams specification requires a void subscribe method as well, hence no name distinction.

**Comment by RobLewis** [comment]
Sorry, I am struggling to understand your answer. You seem to be saying it is OK that one overload of `subscribe()` is `void`, while other overloads return `Disposable`. I have always understood that this violates the rules of Java. Any explanation would be much appreciated. 
For my purposes, I think I want to use a `DisposableSingleObserver`, and call its `onSubscribe()` method to send it a `Disposable`. Presumably this would get around the use of a `void subscribe()` method?

**Comment by akarnokd** [comment]
> consensus seems to be that all overloads of a Java method must have the same return type

Never heard of this consensus or mandate.

> I have always understood that this violates the rules of Java

Overloads have to be distinct in their arguments; the return type doesn't matter. Java does this too: [ByteBuffer.position()](https://docs.oracle.com/en/java/javase/13/docs/api/java.base/java/nio/Buffer.html#position()) and [ByteBuffer.position(int)](https://docs.oracle.com/en/java/javase/13/docs/api/java.base/java/nio/ByteBuffer.html#position(int)).

> For my purposes

What are you trying to implement? It is unlikely you would have to call `onSubscribe`. There is an example in the [Single](http://reactivex.io/RxJava/3.x/javadoc/io/reactivex/rxjava3/core/Single.html) class' Javadocs that may help you:

```java
Disposable d = Single.just("Hello World")
    .delay(10, TimeUnit.SECONDS, Schedulers.io())
    .subscribeWith(new DisposableSingleObserver<String>() {
        @Override
        public void onStart() {
            System.out.println("Started");
        }

        @Override
        public void onSuccess(String value) {
            System.out.println("Success: " + value);
        }

        @Override
        public void onError(Throwable error) {
            error.printStackTrace();
        }
    });
 
 Thread.sleep(5000);
 
 d.dispose();
```

**Comment by RobLewis** [comment]
That is very interesting, thank you. I am at this moment taking an online Java course from Oracle and I'm certain the instructor said return types had to be the same for all overloads. 
Also, though it may not matter, I note that the documentation you cited is for the abstract class `Buffer`. The docs for its concrete subclasses declare only one version of `position` and inherit the one that returns `int`. Frankly this seems kind of like a mistake, or at least a questionable choice. 
I want to create a `Single` reactive asynchronous file downloader using `OKhttp`. I want the client to be able to cancel the download by disposing the subscription.

**Comment by RobLewis** [comment]
After further study, I'm thinking I may in fact need to call `onSubscribe()` because when the client disposes, I have to call OKhttp's `call.cancel()` method. It seems I should create a `Disposable` that does this, no?

**Comment by akarnokd** [comment]
Check out [this blog post](https://medium.com/android-news/android-reactive-architecture-part-2-web-client-8c3099c48820) which has OkHttp with cancellation included.
