### ISSUE TITLE
(3.x) LambdaSubscriber violates the Reactive Streams spec

### ISSUE THREAD

**Issue by dkhalanskyjb** [ReactiveX/RxJava#7217]
The Reactive Streams spec for `Subscriber` (https://github.com/reactive-streams/reactive-streams-jvm/blob/v1.0.3/README.md#2-subscriber-code) says the following in 2.13:
> Calling `onSubscribe`, `onNext`, `onError` or `onComplete` MUST return normally except when any provided parameter is null in which case it MUST throw a `java.lang.NullPointerException` to the caller, for all other situations the only legal way for a `Subscriber` to signal failure is by cancelling its `Subscription`.

In cases when a fatal exception is encountered, `LambdaSubscriber` can throw them from each of the listed methods, which violates the spec. It seems that the thought behind this behavior was to quickly crash the whole runtime in case a fatal exception happens. However, we encountered a case where the actual effect was the opposite and the fatal exception that is supposed to surface immediately was stored in the emission queue for a `Flowable` instead: https://github.com/Kotlin/kotlinx.coroutines/issues/1297.

It seems that a more compliant solution would be to use `RxJavaPlugins.onError` to signal fatal exceptions.

**Comment by akarnokd** [comment]
There are a bunch of exceptions that RxJava considers unrecoverable, hence these don't go into the plugin error handler: running out of memory, running out of stack, thread dying, etc.

There is no good way of handling these without crashing further or even crashing the entire JVM, therefore, we simply rethrow them.

We can only suggest workarounds:
- Do not crash into RxJava. Use `try-catch` and wrap the fatal exception into something non-fatal and rethrow it. Those will land in the global error handler.
- Implement your own subscriber that doesn't rethrow fatal errors.

**Comment by dkhalanskyjb** [comment]
> There are a bunch of exceptions that RxJava considers unrecoverable

Sure, so it would make sense to make sure that some part of the system acknowledges that an exception happened. As is, however, some fatal exceptions can be swallowed, *silently* putting the system into an inconsistent state.

> We can only suggest workarounds

Both of your suggestions are inapplicable to us (the Kotlinx.coroutines library). I will link https://github.com/Kotlin/kotlinx.coroutines/issues/1297 again for an example: a user encountered a problem caused by RxJava being used inside a coroutine. Though it should be possible to make RxJava store an exception in an emission queue with a correct implementation of `Publisher` even without coroutines.

**Comment by akarnokd** [comment]
Again, the user should not crash into RxJava with a fatal exception. In this particular case, the user could wrap the `LinkageError` into `RuntimeException` subclass so it can travel through the usual error channel.
