### ISSUE TITLE
Dependabot runs on forks

### ISSUE THREAD

**Issue by benjamintboyle** [ReactiveX/RxJava#7233]
I noticed this morning that with the change to the native Dependabot, it is submitting pull requests on my personal fork. Obviously this isn't ideal. I found this [issue on the Dependabot repository](https://github.com/dependabot/dependabot-core/issues/2804) indicating that they are aware of it. But there doesn't seem to be any great workarounds.

Is there any opinion on if we should disable the native Dependabot? Or ignore it until the issue gets patched?

**Comment by akarnokd** [comment]
I'd say let's wait till they fix it.

If it gets worse, maybe [`target-branch`](https://docs.github.com/en/code-security/supply-chain-security/configuration-options-for-dependency-updates#target-branch) default behavior might be leveraged.

I usually pull 3.x fresh, create a branch, then push back to my fork, thus I haven't updated my 3.x branch in a long time. I guess you could just delete the yml in your fork's 3.x branch.

**Comment by benjamintboyle** [comment]
Sounds good. We'll do nothing and wait for the patch.
