### ISSUE TITLE
Copyright Information

### ISSUE THREAD

**Issue by stefan-hdt** [ReactiveX/RxJava#7236]
Short question about the copyright information: In the LICENSE dokument "Netflix" is stated as copyright holder. But the individual source code files show RXJava Contributors as copyright holders. I assume that the latter is correct. If so, it would be very kind of you to update the license file.

Cheers, Stefan

**Comment by akarnokd** [comment]
Which license are you refering to? https://github.com/ReactiveX/RxJava/blob/3.x/LICENSE has no mention of Netflix, nor does it appear in any copyright-related place: https://github.com/ReactiveX/RxJava/search?q=netflix

**Comment by stefan-hdt** [comment]
Thanks for your quick response. I was referrring to version 1.2.3 (https://raw.githubusercontent.com/ReactiveX/RxJava/v1.2.3/LICENSE). But I just figured out that Netflix was the copyright holder in older versions, now it's the RxJava Contributors.
