### ISSUE TITLE
3.x Consider adding a full Java module descriptor

### ISSUE THREAD

**Issue by aalmiray** [ReactiveX/RxJava#7240]
Full Java module descriptors (module-info.class) are a hard requirement for building custom Java Runtimes with Jlink.

It looks like the build must remain pre Java modules however given that the build is Gradle based there's the https://plugins.gradle.org/plugin/org.beryx.jar plugin that can be applied to keep the build in its current Java version while at the same time providing a full module descriptor. Caveat: the generated JAR will become a multi-release JAR.

If there's any interest I'll gladly provide a PR and help with maintenance.

Relates to: https://github.com/reactive-streams/reactive-streams-jvm/issues/531

**Comment by akarnokd** [comment]
Okay, as long as it doesn't break Android tooling.

It seems we'll need a couple of things:
- JDK 9+ GHA. A new GHA can be added with just "jar" task. The current JDK 11 build has to target 8.
- Use the [module info workaround](https://github.com/beryx/badass-jar-plugin/#module-infojava-location)

**Comment by aalmiray** [comment]
Correct. I must confess I know little of the Android ecosystem. It's my hope that additional entries found under `/META-INF/versions/x` would not cause any disruptions on Android.

**Comment by JakeWharton** [comment]
MR jars will have their content ignored by Android toolchain, yes

**Comment by akarnokd** [comment]
Great. @aalmiray you can post a PR for this.

**Comment by aalmiray** [comment]
This is great. However in order to have RxJava's module descriptor be fully modular we'll need an answer from the ReactiveStreams WG -> reactive-streams/reactive-streams-jvm#531

**Comment by aalmiray** [comment]
FYI encountered https://github.com/bndtools/bnd/issues/3514 -> https://github.com/bndtools/bnd/issues/2227 which has yet to be resolved.
