### ISSUE TITLE
[Android] NoSuchMethodError: No static method

### ISSUE THREAD

**Issue by valeriyo** [ReactiveX/RxJava#7243]
This is to make it easier to find the root cause issue https://issuetracker.google.com/issues/183632445 -- since RxJava3 uses interfaces with static methods, it's susceptible.

This is how the runtime error looks:
```
java.lang.NoSuchMethodError: No static method fromAction(Lio/reactivex/rxjava3/functions/Action;)Lio/reactivex/rxjava3/disposables/Disposable; in class Lio/reactivex/rxjava3/disposables/Disposable; or its super classes (declaration of 'io.reactivex.rxjava3.disposables.Disposable' appears in /data/app/..../base.apk!classes3.dex)
```

**Comment by AgiMaulana** [comment]
@valeriyo how did you solve this error? Enabling Java 8 desugar doesn't help me.
