### ISSUE TITLE
RxJava 2 support for Android 11

### ISSUE THREAD

**Issue by Flavind** [ReactiveX/RxJava#7244]
Hello!
My Application uses RxJava version 2.1.4 and supports Android version 5.1.
I want to update the application so that it can be compatible with Android 5.1 and Android 11. 
I am just making the app compatible as it is with Android 11 without changing any functionality/features.
Will this RxJava version support Android 11 and 5.1 or do I need to update to RxJava version 3?

**Comment by akarnokd** [comment]
If 2.1.4 worked for you in 5.1, it should keep working with Android 11. Note though that the entire 2.x line is end-of-life.

RxJava 3.x use requires [Android Desugaring](https://developer.android.com/studio/write/java8-support) which appears to be available for 5.1. You could try and create a minimalistic project for both 5.1 and 11 to see if it actually works for you.
