### ISSUE TITLE
`Observable.mapOptional` should not use `Optional<T>`

### ISSUE THREAD

**Issue by valeriyo** [ReactiveX/RxJava#7256]
in RxJava3, there is the following method:

```
public final <@NonNull R> Observable<R> mapOptional(@NonNull Function<? super T, @NonNull Optional<? extends R>> mapper)
```

I think, there are a few problems with it:
1) The mapper function should return `@Nullable R` instead of `Optional<R>`. Optional is needed to wrap nullable values that are emitted though Rx chains - not in regular functions.
2) Why is this method included into `Observable` when it can be implemented outside (as a transform or extension method)?

Kotlin has a standard `mapNotNull` collection/sequence operator which looks exactly what this should be -- https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.collections/map-not-null.html 

Thanks.

**Comment by akarnokd** [comment]
> Why is this method included

This method and others were added to allow interoperation with Java 8 constructs.

> The mapper function should return `@Nullable R`

We generally don't allow `null` returns because `null` can mean both no data or a bug in the logic.

> Kotlin has a standard `mapNotNull` collection/sequence operator which looks exactly what this should be
> [...] it can be implemented outside (as a transform or extension method)?

☝️

**Comment by valeriyo** [comment]
> We generally don't allow null returns because null can mean both no data or a bug in the logic.

By "generally" you mean regular methods? The `mapper` is a regular Java function, and returning a `null` value from a regular Java function is completely within the realm of reason.

**Comment by akarnokd** [comment]
In this library, we decided to disallow null returns.
