### ISSUE TITLE
Add java.time to public API

### ISSUE THREAD

**Issue by benjamintboyle** [ReactiveX/RxJava#7266]
I'd like to add the `java.time` classes to the public API of RxJava. Mostly replacing the `java.util.concurrent` classes (specifically `TimeUnit`). Obviously deprecating the previous APIs is undesirable, though it may be wise in the future. I know updating public API changes are a big deal which is why this issue was created.

One reason the change is valuable is that it reduces the number of method parameters, for example:

`public static Completable timer(long delay, @NonNull TimeUnit unit, @NonNull Scheduler scheduler)`

to:
`public static Completable timer(Duration delay, @NonNull Scheduler scheduler)`

There currently appears to be 62 classes in RxJava that have this pattern which would need updating.

**Comment by benjamintboyle** [comment]
62 classes are below:

src/main/java/io/reactivex/rxjava3/core/Completable.java
src/main/java/io/reactivex/rxjava3/core/Flowable.java
src/main/java/io/reactivex/rxjava3/core/Maybe.java
src/main/java/io/reactivex/rxjava3/core/Observable.java
src/main/java/io/reactivex/rxjava3/core/Scheduler.java
src/main/java/io/reactivex/rxjava3/core/Single.java
src/main/java/io/reactivex/rxjava3/flowables/ConnectableFlowable.java
src/main/java/io/reactivex/rxjava3/internal/functions/Functions.java
src/main/java/io/reactivex/rxjava3/internal/observers/BlockingMultiObserver.java
src/main/java/io/reactivex/rxjava3/internal/observers/FutureMultiObserver.java
src/main/java/io/reactivex/rxjava3/internal/observers/FutureObserver.java
src/main/java/io/reactivex/rxjava3/internal/operators/completable/CompletableDelay.java
src/main/java/io/reactivex/rxjava3/internal/operators/completable/CompletableTimer.java
src/main/java/io/reactivex/rxjava3/internal/operators/flowable/FlowableBufferTimed.java
src/main/java/io/reactivex/rxjava3/internal/operators/flowable/FlowableDebounceTimed.java
src/main/java/io/reactivex/rxjava3/internal/operators/flowable/FlowableDelay.java
src/main/java/io/reactivex/rxjava3/internal/operators/flowable/FlowableFromFuture.java
src/main/java/io/reactivex/rxjava3/internal/operators/flowable/FlowableInternalHelper.java
src/main/java/io/reactivex/rxjava3/internal/operators/flowable/FlowableInterval.java
src/main/java/io/reactivex/rxjava3/internal/operators/flowable/FlowableIntervalRange.java
src/main/java/io/reactivex/rxjava3/internal/operators/flowable/FlowableRefCount.java
src/main/java/io/reactivex/rxjava3/internal/operators/flowable/FlowableSampleTimed.java
src/main/java/io/reactivex/rxjava3/internal/operators/flowable/FlowableSkipLastTimed.java
src/main/java/io/reactivex/rxjava3/internal/operators/flowable/FlowableThrottleFirstTimed.java
src/main/java/io/reactivex/rxjava3/internal/operators/flowable/FlowableTimeInterval.java
src/main/java/io/reactivex/rxjava3/internal/operators/flowable/FlowableTimer.java
src/main/java/io/reactivex/rxjava3/internal/operators/maybe/MaybeDelay.java
src/main/java/io/reactivex/rxjava3/internal/operators/maybe/MaybeFromFuture.java
src/main/java/io/reactivex/rxjava3/internal/operators/maybe/MaybeTimeInterval.java
src/main/java/io/reactivex/rxjava3/internal/operators/maybe/MaybeTimer.java
src/main/java/io/reactivex/rxjava3/internal/operators/observable/ObservableBufferTimed.java
src/main/java/io/reactivex/rxjava3/internal/operators/observable/ObservableDebounceTimed.java
src/main/java/io/reactivex/rxjava3/internal/operators/observable/ObservableDelay.java
src/main/java/io/reactivex/rxjava3/internal/operators/observable/ObservableFromFuture.java
src/main/java/io/reactivex/rxjava3/internal/operators/observable/ObservableInternalHelper.java
src/main/java/io/reactivex/rxjava3/internal/operators/observable/ObservableInterval.java
src/main/java/io/reactivex/rxjava3/internal/operators/observable/ObservableIntervalRange.java
src/main/java/io/reactivex/rxjava3/internal/operators/observable/ObservableRefCount.java
src/main/java/io/reactivex/rxjava3/internal/operators/observable/ObservableSampleTimed.java
src/main/java/io/reactivex/rxjava3/internal/operators/observable/ObservableTimeInterval.java
src/main/java/io/reactivex/rxjava3/internal/operators/observable/ObservableTimer.java
src/main/java/io/reactivex/rxjava3/internal/operators/single/SingleDelay.java
src/main/java/io/reactivex/rxjava3/internal/operators/single/SingleTimeInterval.java
src/main/java/io/reactivex/rxjava3/internal/operators/single/SingleTimeout.java
src/main/java/io/reactivex/rxjava3/internal/operators/single/SingleTimer.java
src/main/java/io/reactivex/rxjava3/internal/schedulers/ComputationScheduler.java
src/main/java/io/reactivex/rxjava3/internal/schedulers/DisposeOnCancel.java
src/main/java/io/reactivex/rxjava3/internal/schedulers/ExecutorScheduler.java
src/main/java/io/reactivex/rxjava3/internal/schedulers/ImmediateThinScheduler.java
src/main/java/io/reactivex/rxjava3/internal/schedulers/IoScheduler.java
src/main/java/io/reactivex/rxjava3/internal/schedulers/NewThreadWorker.java
src/main/java/io/reactivex/rxjava3/internal/schedulers/SchedulerWhen.java
src/main/java/io/reactivex/rxjava3/internal/schedulers/SingleScheduler.java
src/main/java/io/reactivex/rxjava3/internal/schedulers/TrampolineScheduler.java
src/main/java/io/reactivex/rxjava3/internal/subscribers/FutureSubscriber.java
src/main/java/io/reactivex/rxjava3/internal/util/ExceptionHelper.java
src/main/java/io/reactivex/rxjava3/observables/ConnectableObservable.java
src/main/java/io/reactivex/rxjava3/observers/BaseTestConsumer.java
src/main/java/io/reactivex/rxjava3/processors/ReplayProcessor.java
src/main/java/io/reactivex/rxjava3/schedulers/TestScheduler.java
src/main/java/io/reactivex/rxjava3/schedulers/Timed.java
src/main/java/io/reactivex/rxjava3/subjects/ReplaySubject.java

**Comment by benjamintboyle** [comment]
Many are in the `internal` package which should not impact external API.

**Comment by akarnokd** [comment]
No. It was decided long ago to not support Duration for the following reasons:
- adds a lot of overloads,
- requires allocation,
- can be decomposed to time + unit with minimal effort.

Changing the existing signature would cascade out to all projects depending on RxJava and create massive inconvenience for no benefit.

**Comment by benjamintboyle** [comment]
Thanks for explaining the reasoning behind the decision.
