### ISSUE TITLE
2.x  Is this a typo in the Completable documentation ?

### ISSUE THREAD

**Issue by hehua2008** [ReactiveX/RxJava#7271]
https://github.com/ReactiveX/RxJava/blob/2.x/src/main/java/io/reactivex/Completable.java

In line 52, 53:
Like Observable, a running Completable can be stopped through the Disposable instance provided to consumers through SingleObserver.onSubscribe.

It seems that "CompletableObserver.onSubscribe" has been typed into "SingleObserver.onSubscribe" here.

**Comment by akarnokd** [comment]
Indeed there is a copy-paste error, including 3.x. I'll post a fix shortly.
