### ISSUE TITLE
2.x and 3.x: The reason behind scan() operator emitting the initialValue

### ISSUE THREAD

**Issue by vidhithakrar** [ReactiveX/RxJava#7275]
Though it is intended to emit the `initalValue` as first item from `scan` operator as shown below:

```
Observable.just(List.of(1, 10), List.of(50, 32), List.of(35, 70))
                .scan(emptyList(), (acc, item) ->
                        Stream.concat(acc.stream(), item.stream()).sorted().collect(toList()))
                .subscribe(System.out::println);
```

which outputs:
```
[]
[1, 10]
[1, 10, 32, 50]
[1, 10, 32, 35, 50, 70]
```

It is something which is different from other Rx implementation where `initialValue` is not emitted as the first item, So curious to know the intent behind it.

**Comment by akarnokd** [comment]
It is emitted in case the downstream needs it. If your use case doesn't require it, use `skip(1)`.

**Comment by vidhithakrar** [comment]
Thanks @akarnokd for the prompt response.

Yes, can definitely skip it. But I was more curious to understand is there any important reason behind this behaviour as other implementations are not behaving that way.

Also if downstream needs some `initialValue` then can always send it explicitly by using `startWith(emptyList())`.

**Comment by akarnokd** [comment]
Which other implementations? Each Rx implementation chose the best set of operators and parameterizations that fit their user base. For us, `scan` is often used on android with sequential state transitions where there needs to be an initial state. 

https://www.youtube.com/watch?v=0IKHxjkgop4

**Comment by vidhithakrar** [comment]
Other implementation like [RxJs](http://reactivex.io/rxjs/class/es6/Observable.js~Observable.html#instance-method-scan) also provides similar `scan` operator with `seed` but it is not emitted as the first item.

**Comment by akarnokd** [comment]
As far as I can remember and what [the issue list](https://github.com/ReactiveX/RxJava/issues/286#issuecomment-23983353) indicates, RxJava was doing it from the beginning. 

I can only speculate; back then the Rx.NET source was quite hazy so it wasn't that clear how operators worked there. In any case, it was decided to always emit the seed and let the consumer skip it. As far as I know, RxJS came later and were developed by people more familiar with Rx.NET thus they apparently kept that behavior.

**Comment by vidhithakrar** [comment]
Thank you again @akarnokd for the insight and appreciate the effort of finding out the reason from history.
