### ISSUE TITLE
com.android.tools.r8.errors.d: FORCE inlining on non-inlinable: void io.reactivex.rxjava3.disposables.RunnableDisposable

### ISSUE THREAD

**Issue by amirhossein320** [ReactiveX/RxJava#7292]
when i using  **minifyEnabled true** and generate signed apk i receive the above error

**Comment by akarnokd** [comment]
This is an android tools issue. I googled the error message and got this:

https://stackoverflow.com/a/64210074/61158

**Comment by amirhossein320** [comment]
> This is an android tools issue. I googled the error message and got this:
> 
> https://stackoverflow.com/a/64210074/61158

i use this but not work

**Comment by akarnokd** [comment]
Have you tried creating a few dummy disposables?

```java
composite.add(Disposable.fromRunnable(() -> { }));
composite.add(Disposable.fromRunnable(() -> { }));
```
