### ISSUE TITLE
3.x: Task distribution of ComputationScheduler

### ISSUE THREAD

**Issue by zireael-0** [ReactiveX/RxJava#7294]
Hi,

I was stuck with a problem on a 4-core V-Server that was supposed to run my application, which did not occur on my 16-core development computer.

In my application are several long running sequences that emit a huge number of elements very fast. Most of these originate from SQL queries that I implemented as Observable<SomeSqlRow> and call them like this:

```java
sqlResultObservable
  .subscribeOn(Schedulers.io())
  .observeOn(Schedulers.computation())
```

There are 5 to 10 queries that are invoked in parallel, which works perfectly fine. However, I also use `Schedulers.computation()` in a few other places where it makes sense to move work to a different thread for performance reasons. Until this point I never had a problem with doing so.

At the end of the Observable pipeline, I added an optional `.take(cliParam)` for debugging purposes. I noticed that this works without problems on my machine, but on the 4-core machine that is supposed to run the application later, the `cliParam` affected the result, but not the execution time. It was just as slow to take 100 elements as it was to take 5 Million elements - it's expected to be slow when it's done and is running in production for all elements, but for debugging this was more than annoying so I looked into it.

Turns out, the problem is, that of the 4 threads that are available to `Schedulers.computation()` only one was actually being used. The running task on that thread was an SQL query that emits about 5 Million elements, unless it's disposed. Unfortunately the thread that's processing the query result, has the task in it's queue that ultimately calls the `.take` observable and would dispose the query. 

Basically what happened is, that one of my fastest tasks was queued after one of my slowest every time, while 3 of the 4 available threads had an empty queue and were just waiting.

The culprit of this issue is here:

https://github.com/ReactiveX/RxJava/blob/c5883dcb390ebb17a484871038e37078e210052a/src/main/java/io/reactivex/rxjava3/internal/schedulers/ComputationScheduler.java#L84-L91

This just distributes the tasks evenly across the available threads which is kinda impractical if you ask me. In general the implementation of the `ComputationScheduler.FixedSchedulerPool` looks a little off to me.

Why do we create multiple single-thread executors, each with their own queue and distribute the tasks on our own? I'd suggest to just use the `java.util.concurrent.Executors.newFixedThreadPool(int maxNumThreads)` as it's already implemented and the threads share the same queue. That should avoid scenarios where threads are idling while others still have tasks left on their queue.

As a workaround, I replaced the computation thread pool via
```java
final var computationExecutor = Executors.newFixedThreadPool(Runtime.getRuntime().availableProcessors());
RxJavaPlugins.setInitComputationSchedulerHandler(_x -> Schedulers.from(computationExecutor));
```
which improved the overall performance with other multi-threaded workloads, too. Can someone look into it and tell me if it might be a good idea to replace the `FixedSchedulerPool` implementation?

**Comment by akarnokd** [comment]
> Why do we create multiple single-thread executors, each with their own queue and distribute the tasks on our own

Improves cache locality of computational tasks.

> As a workaround

For your case, that's the way to go. Override the scheduler(s) with your own backing pool.

> good idea to replace the FixedSchedulerPool implementation

No, the standard schedulers will not be changed.

**Comment by zireael-0** [comment]
You're correct. For Intel using multiple queues may have a better cache performance. I feel like the relatively high chance of threads being completely idle is worse than potentially having to copy the threads instructions again.

Maybe some time I'll try changing it and do a benchmark. I guess that's it for now. Thank you!
