### ISSUE TITLE
o.reactivex.rxjava3.exceptions.CompositeException$ExceptionOverview    3.X

### ISSUE THREAD

**Issue by MrEricChen** [ReactiveX/RxJava#7310]
Multiple exceptions (2) |-- java.util.NoSuchElementException: null at java.util.Vector.lastElement(Vector.java:503) |-- java.util.NoSuchElementException: null at java.util.Vector.lastElement(Vector.java:503)

io.reactivex.rxjava3.exceptions.CompositeException:2 exceptions occurred.
io.reactivex.rxjava3.internal.observers.LambdaObserver.onError(LambdaObserver.java:80)
......
Caused  
io.reactivex.rxjava3.exceptions.CompositeException$ExceptionOverview:Multiple exceptions (2)
java.util.NoSuchElementException: null
at java.util.Vector.lastElement(Vector.java:503)
java.util.NoSuchElementException: null
at java.util.Vector.lastElement(Vector.java:503)

**Comment by akarnokd** [comment]
This is not an issue with RxJava. You have Vector somewhere that is empty thus no last element.
