### ISSUE TITLE
3.x: Observable.never() and .firstElement() 

### ISSUE THREAD

**Issue by fmontesanto** [ReactiveX/RxJava#7311]
Hi there, 
I found myself testing a tricky situation after calling `.firstElement()` on a BehaviorSubject that was empty (with no default values) because either values were filtered or nothing was emitted. In that case it would be the same as doing `Observable.never().firstElement() ` where nothing would happen.   

After checking the https://github.com/ReactiveX/RxJava/blob/3.x/src/test/java/io/reactivex/rxjava3/internal/operators/observable/ObservableFirstTest.java  I saw that there is no test case on this although there are a lot with `Observable.empty()`  or `Observable.just()`.  
Should the spec have any test for this case? And furthermore should it be handled by this operator or `firstOrError`? 
The only work around I found to this so far is to wait for an arbitrary time with the `.take` operator were I was able to get a completion. 
Example : 
```
Observable.never<Boolean>()
        .take(1, TimeUnit.MILLISECONDS, Schedulers.newThread())
        .firstElement()
        .subscribe(
                { println("Value") },
                { println("Error") },
                { println("Complete") },
        )
```

Is there any other workaround to this? 

Thank you very much
Facundo Montesanto

**Comment by akarnokd** [comment]
You could somewhat test it via the Mockito `verify(observer, never()).onNext(any());` statements. However, it is usually uninformative with operators that wouldn't otherwise introduce signals from somewhere else or on their own.

In practice, you'd add `timeout` to cut off a possibly non-responding source, but then you'd have to decide on how much to wait.

**Comment by fmontesanto** [comment]
@akarnokd thank you for the quick response. 
I've might expressed my self wrong but with this : `Should the spec have any test for this case? And furthermore should it be handled by this operator or firstOrError?`. I meant the test of the lib `ObservableFirstTest` 
Yes indeed the timeout can do the trick but it forces you as you say to decide on how much to wait.. 
Another workaround I tested is wrap the object with an Optional and start the subject with an `empty` as default.. it forces you to check if it's empty or not but you can be certain if there's something or not..

**Comment by akarnokd** [comment]
I don't think a test is needed for this case for this operator.

**Comment by fmontesanto** [comment]
👍  thanks for the input
