### ISSUE TITLE
What‘s the reason that "relaying the upstream's Disposable directly is not allowed in RxJava"?

### ISSUE THREAD

**Issue by chxchen** [ReactiveX/RxJava#7317]
Thanks check my question.
When I implement `ObservableOperator`, find the comment "Note that relaying the upstream's Disposable directly is not allowed in RxJava" above observable operator `lift` sample.
I searched net, but found nobody explains the reason.  If i follow the sample for `lift`， the class seems complex a little bit, but relay the upstream's Disposable,  the class seems more clean.
```
public final class CustomObserver<T> implements Observer<T>, Disposable {

     final Observer<? super String> downstream;

     Disposable upstream;

     public CustomObserver(Observer<? super String> downstream) {
         this.downstream = downstream;
     }

     // In the subscription phase, the upstream sends a Disposable to this class
     // and subsequently this class has to send a Disposable to the downstream.
     // Note that relaying the upstream's Disposable directly is not allowed in RxJava
     @Override
     public void onSubscribe(Disposable d) {
         if (upstream != null) {
             d.dispose();
         } else {
             upstream = d;
             downstream.onSubscribe(this);
         }
     }

     @Override
     public void onNext(T item) {
         ... do something...
     }

     @Override
     public void onError(Throwable throwable) {
         downstream.onError(throwable);
     }

     @Override
     public void onComplete() {
         downstream.onComplete();
     }

     @Override
     public void dispose() {
         upstream.dispose();
     }

     @Override
     public boolean isDisposed() {
         return upstream.isDisposed();
     }
 }

```

```
public final class CustomObserver<T> implements Observer<T>, Disposable {

     final Observer<? super String> downstream;

     Disposable upstream;

     public CustomObserver(Observer<? super String> downstream) {
         this.downstream = downstream;
     }

     // Not follow sample says
     @Override
     public void onSubscribe(Disposable d) {
         downstream.onSubscribe(d);
     }

     @Override
     public void onNext(T item) {
         ... do something...
     }

     @Override
     public void onError(Throwable throwable) {
         downstream.onError(throwable);
     }

     @Override
     public void onComplete() {
         downstream.onComplete();
     }
}
```

**Comment by akarnokd** [comment]
It breaks operator fusion, which is detected by checking the `Disposable` sent via `onSubscribe`. If, for example, the upstream supports fusion and you relay that `Disposable` to the downstream, it will skip your operator and will talk to the upstream directly.

In general, it is rare not to intercept `dispose()` in an operator.

**Comment by chxchen** [comment]
> It breaks operator fusion, which is detected by checking the `Disposable` sent via `onSubscribe`. If, for example, the upstream supports fusion and you relay that `Disposable` to the downstream, it will skip your operator and will talk to the upstream directly.
> 
> In general, it is rare not to intercept `dispose()` in an operator.

Thank you!
Do you mean if an custom operator by `lift` is very simple, Relaying the upsteam's disposable does not make hidden error, but recommand to implement `Disposable` and delivery `this` to downstream?  (The simple operator just pass values to downstream.)

**Comment by akarnokd** [comment]
Yes.

**Comment by chxchen** [comment]
> Yes.
Thanks a lot
