### ISSUE TITLE
How can I check completion of saving which is processed  in async way?

### ISSUE THREAD

**Issue by YauheniZarembin** [ReactiveX/RxJava#7327]
Hi. could you please clarify how I can wait async execution of saving?
I Have the following methods in repository class.
```
public Completable save(Book book) {
        // logic to save book in DB
    }

public Single<Boolean> exist(Book book) {
        // logic to check if book exists in DB
    }
```
And there is method in service that uses _save_ method from repository
```
public Single<Book> saveBook(Book book) {
        bookRepo.save(book);
        return Sing.just(book);
    }
```

The problem is that after _saveBook_ method execution the book may not be in the database as saving is processed  in async way.
How can I change me _saveBook_ method using _exist_ method to be sure that after _saveBook_ method execution I will have the book in DB?

**Comment by akarnokd** [comment]
You can compose them via `flatMapCompletable`, for example:

```java
public Single<Book> saveBook(Book book) {
    return exist(book)
           .flatMapCompletable(exists -> exists ? Completable.complete() : bookRepo.save(book))
           .andThen(Single.just(book));
```

**Comment by YauheniZarembin** [comment]
No, maybe I should clarify my case.

At First I have nothing in DB. Then I save book by _saveBook_ method from service.
After that I want to update this book.
But when I try to receive book from DB for update I have nothing, as save is still executing very long in asycn way and DB is empty.

So in _saveBook_ method I want to wait to be sure that when I need to update book it will be in DB.

**Comment by akarnokd** [comment]
It depends on how you structured your save-update workflow.

One possibility is to cache the `saveBook` above; it will make sure the save runs at most once and there will be a value ready after, indicating the save completed.

```java
Single<Book> bookCached = saveBook(book).cache();
bookCached.subscribe(/* trigger the save */);

// later
bookCached
  .flatMap(book -> updateBook(book))
  .subscribe(/* trigger update */)
```

**Comment by YauheniZarembin** [comment]
Thanks!

**Comment by YauheniZarembin** [comment]
@akarnokd Maybe I foung what I want.
Could you please review is that a good way to check?

```
public Single<Book> saveBook(Book book) {
        bookRepo.save(book);
        
        boolean saved = Single.defer(() -> bookRepo.exist(book))
                .repeat()
                .takeUntil(b -> b)
                .ignoreElements()
                .blockingAwait(10000, TimeUnit.MILLISECONDS);
                
        if (saved) {
            return Single.just(book);
        } else {
            //error
        }
  
    }
```

Сan this code be simplified?

**Comment by akarnokd** [comment]
That repeat will be very eagle, perhaps waiting a second may be preferable: `repeatWhen(o -> o.delay(1, TimeUnit.SECONDS))`.

If you block, there is no value in returning a `Single`. Also depending on where this code runs, you may not be allowed to block.

**Comment by YauheniZarembin** [comment]
Thanks a lot!
