### ISSUE TITLE
Not predicate for fluent lambdas

### ISSUE THREAD

**Issue by vatevr** [ReactiveX/RxJava#7329]
This issue proposes to add introduce a new `Predicate` `Not` that will negate the given predicate.

This is useful to have more idiomatic chains such as 

```java
Observable.fromIterable(...)filter(not(Collection::isEmpty))
```

**Comment by akarnokd** [comment]
We don't implement fluent lambdas in RxJava. Since `not` you are suggesing is a static method, it can live in any 3rd party library, even in your own codebase.
