### ISSUE TITLE
Confusing nullability on `subscribe(BiConsumer)`

### ISSUE THREAD

**Issue by ZacSweers** [ReactiveX/RxJava#7330]
With RxJava 3.1.x's improve nullability annotations and Kotlin 1.5.30's improved recognition of them, I came across an interesting nullability mismatch with the `subscribe(BiConsumer)` case. In short - the generic `T` is always assumed non null now, but the nature of this method is that both parameters to the consumer are actually nullable (since only one is guaranteed to be present).

I'm not sure what the right solution is for this off-hand, but raising here for visibility.

<img width="568" alt="image" src="https://user-images.githubusercontent.com/1361086/132133476-13fa5b8b-1508-4860-87b1-67b0fd15c13f.png">

**Comment by ZacSweers** [comment]
For now, I'm explicitly typing these parameters as nullable rather than allowing type inference to assume otherwise

**Comment by akarnokd** [comment]
Probably the declaration-side override could work:

```java
Disposable subscribe(@NonNull BiConsumer<@Nullable ? super T, @Nullable ? super Throwable> onCallback)
```

Not sure how to verify it works with Kotlin. Could you create a mockup method with this kind of signature and see if the inference works for you?

**Comment by ZacSweers** [comment]
Yup I'll give that a try and report back

**Comment by ZacSweers** [comment]
Confirmed that works with this example

```java
public class Example<@NonNull T> {
  void subscribe(BiConsumer<@Nullable T, @Nullable Throwable> consumer) {

  }
}
```

![image](https://user-images.githubusercontent.com/1361086/132145184-fa7484ca-93ab-43bc-a805-3233c0393611.png)

**Comment by ZacSweers** [comment]
I'll make a PR
