### ISSUE TITLE
Observable.takeUntil wrong documentation

### ISSUE THREAD

**Issue by Maragues** [ReactiveX/RxJava#7339]
According to [Observable.takeUntil(ObservableSource<U> other)](http://reactivex.io/RxJava/3.x/javadoc/io/reactivex/rxjava3/core/Observable.html#takeUntil-io.reactivex.rxjava3.core.ObservableSource-)'s documentation

> Returns an Observable that emits the items emitted by the current Observable **until a second ObservableSource emits an item.**

Emphasis is mine

Looking at [ObservableTakeUntil](https://github.com/ReactiveX/RxJava/blob/5bb119b1489afe4fbc5bb51b828be95971ee8f1d/src/main/java/io/reactivex/rxjava3/internal/operators/observable/ObservableTakeUntil.java), it looks to me that `onNext` and `onComplete` are equivalent

I created this test, and the output is exactly the same

```kotlin
class TakeUntilTest {
    @Test
    fun `when Observable completes, then takeUntil completes`(){
        Observable.just(1, 2, 3)
            .takeUntil(Observable.empty<Unit>())
            .subscribe(
                {
                    println("Item: $it")
                },
                Timber::e,
                {
                    println("onComplete")
                }
            )
    }
    
    @Test
    fun `when Observable emits, then takeUntil completes`(){
        Observable.just(1, 2, 3)
            .takeUntil(Observable.just(Unit))
            .subscribe(
                {
                    println("Item: $it")
                },
                Timber::e,
                {
                    println("onComplete")
                }
            )
    }
}
```
![image](https://user-images.githubusercontent.com/655970/134490812-f1c94d82-7487-4d23-aad5-3a2f5ef8eab1.png)

According to documentation, the first test should emit 1, 2 and 3 values

Thus, I think the documentation should say something like

> Returns an Observable that emits the items emitted by the current Observable **until a second ObservableSource emits an item or completes successfully.**

Thanks!

**Comment by akarnokd** [comment]
Yes. PR welcome.

**Comment by Maragues** [comment]
What do you use to generate marble diagrams? This https://rx-marbles-online.herokuapp.com/ ?

It'd help to add whichever tool you use to contributing documentation https://github.com/ReactiveX/RxJava/blob/3.x/CONTRIBUTING.md, as well as wording guidelines for documentation

**Comment by akarnokd** [comment]
Don't worry about the diagram, I have an [Excel spreadsheet](https://docs.google.com/spreadsheets/d/0B4T7ZW3brESKQV9KaEF5YnpjM0k/edit?usp=sharing&ouid=113316559156085910174&resourcekey=0-VV8blrt9k9AebKUT69Rj7g&rtpof=true&sd=true) for them.

**Comment by akarnokd** [comment]
You can use these: 

Resize: 640 x 188
URL: https://raw.github.com/wiki/ReactiveX/RxJava/images/rx-operators/Flowable.takeUntil.p.png
 
![image](https://raw.github.com/wiki/ReactiveX/RxJava/images/rx-operators/Flowable.takeUntil.p.png)
-----------
Resize: 640 x 213
URL: https://raw.github.com/wiki/ReactiveX/RxJava/images/rx-operators/Observable.takeUntil.o.png

![image](https://raw.github.com/wiki/ReactiveX/RxJava/images/rx-operators/Observable.takeUntil.o.png)
