### ISSUE TITLE
Does the IoScheduler need to actively close expired threadworkers？

### ISSUE THREAD

**Issue by lianrenxingyu** [ReactiveX/RxJava#7342]
version: "io.reactivex.rxjava3:rxjava:3.1.1"

Do you need to call shutdown or dispose in IoScheduler.CachedWorkerPool#evictExpiredWorkers? The thread pool was not actively closed when removing the expired threadworker object. And one core thread will not be closed

**Comment by akarnokd** [comment]
I don't fully understand your question. The `remove` call in [IoScheduler.java#L133]( https://github.com/ReactiveX/RxJava/blob/3.x/src/main/java/io/reactivex/rxjava3/internal/schedulers/IoScheduler.java#L133) disposes as per [CompositeDisposable.remove()](https://github.com/ReactiveX/RxJava/blob/15ac5ad778503ffdd31ef17f61889c201d37ddb2/src/main/java/io/reactivex/rxjava3/disposables/CompositeDisposable.java#L148-L162).

**Comment by lianrenxingyu** [comment]
I got it . 
I made a mistake. Thank you !
