### ISSUE TITLE
Potential memory leak in flatMap(..subscribeOn) rxjava 3.1.1, major version (3.x)

### ISSUE THREAD

**Issue by yklymenko** [ReactiveX/RxJava#7353]
Hi,

I've used following construct to write some data into DB in parallel 

```
                        someData$.buffer(10000)
                        .flatMap(a -> Observable
                                        .just(a)
                                     //   .subscribeOn(scheduler)
                                        .map(b -> write(datasource, b)),
                                parallelCount
                        ),
```

In case if I activate "subscribeOn", the code produce memory leak (even with only one Thread). I do not see high memory consumption in "single thread" case without "subscribeOn". The complete example (maven project with H2DB) is attached. I've reproduced the same behaviors with other DBs also.  

[test-leak.zip](https://github.com/ReactiveX/RxJava/files/7374166/test-leak.zip)

**Comment by akarnokd** [comment]
In your example, you are generating values with maximum speed thus all flatMap can do is to queue up yet to be observed inner sources. The "leak" comes from the lack of backpressure towards the generator. Please consider using `Flowable` instead.
