### ISSUE TITLE
Observable.merge().Only the second observable in the result Observable one emits data. (3.x)

### ISSUE THREAD

**Issue by DzmitreyDanilau** [ReactiveX/RxJava#7368]
Hello, I am faced with a problem, not sure is it a bug or I just missed something.

Version: 3.x

```
fun example(observable: Observable<E>) : Observable<R>{
  return Observable.merge(
        Observable.merge(
               Observable.just(),
               observable.map(desiredMapping1)           
  ),
  observable.map(desiredMapping2)
}
```

**How we can solve the problem:**
This problem was fixed by using:

`Observable.publish { }`

What I want to understand:
1. Why it happens
2. Why tests work properly

Will be appreciated to receive the response or the idea of which way I should dig 

ty in advance

**Comment by akarnokd** [comment]
Depends on how `eventObservable` is set up. If it emits items upon subscription, subsequent subscriptions (such as coming from another merge) may not get the same initial items.

**Comment by DzmitreyDanilau** [comment]
@akarnokd thx for the response

```
eventObservable = Observable.merge(
   observable
   view.onTextChanges()
)
```

Also, the subscription happens once on the
```
fun example(observable: Observable).subscribeWith(Observer)

```

But how does the order of the merging observables impact this case?
Take a look at the option 1 and 2

ty in advance

**Comment by akarnokd** [comment]
In that case, the order should not matter.

Could you post a self-contained example that demonstrates your problem?

**Comment by DzmitreyDanilau** [comment]
Sure

**Comment by DzmitreyDanilau** [comment]
Hmm, a simple implementation that works on the one thread can't reproduce the issue. I think this is the case why tests work.
Not sure about the example, will it be suitable to see it as a simple android app?

**Comment by akarnokd** [comment]
Since only you have access to the original code with the problem, only you can compare what has become different with the simplification.

**Comment by DzmitreyDanilau** [comment]
@akarnokd anyway ty for the quick responses. Will try to figure out. If found the problem, will left the comment
ty once again

**Comment by DzmitreyDanilau** [comment]
Seems like multiple merging causes my problem. As ou said in your first comment.
As I understood, merged observable is a subscriber of ALL of its merged sources.
In my case nested observable - the second subscription for my **eventsObservable**. 
According to Jake Wharton proposal, if we want to share value with multiple subscribers we should call  `share()` on the observable. And it works =)
```
fun example(eventsObservable: Observable<E>) : Observable<R>{
  return Observable.merge(
        Observable.merge(
                Obsvable.just(), 
                eventObservable.map(::desiredMapping1)            
  ),
  eventObservable.map(::desiredMapping1)
}

```

But I wonder, why tests don't fail.
I provide to the `fun example(eventsObservable: Observable<E>) : Observable<R>` also observable:

`eventsObservable = Observable.merge(item1, item2)`

Maybe you have any suggestions?

ty in advance

cc @akarnokd

**Comment by akarnokd** [comment]
Can't suggest anything without seeing tests that reproduce the issue.

**Comment by DzmitreyDanilau** [comment]
@akarnokd 
My bad forgot to add the repository link. Added you to the repo also
https://github.com/DzmitreyDanilau/MergeQuestion/blob/master/app/src/test/java/com/musicianhelper/mergequestion/MergeTest.kt

**Comment by akarnokd** [comment]
Let's continue the discussion in your repo. https://github.com/DzmitreyDanilau/MergeQuestion/issues/1
