### ISSUE TITLE
Flowable.create and Flowable.subscribeOn without requestOn = false

### ISSUE THREAD

**Issue by wburns** [ReactiveX/RxJava#7375]
I am using the latest RxJava 3.1.3 and I am attempting to use `Flowable.create` to emit items from a recursive function that I can stop and resume in the middle of (binary tree navigation). The problem comes in that I must do this on a separate thread than the requesting thread (`Flowable.subscribeOn` with `requestOn = false`) which means the requestor sends requests asynchronously, which doesn't work with `Flowable.create`.

I have changes in my own branch to make `Flowable.create` only invoke the `FlowableOnSubscriber` when the upstream has requested elements. This way the `FlowableOnSubscribe` can be invoked multiple times, but still maintains the existing behavior where the `FlowableOnSubscribe`  is only invoked the one time per subscriber.

To isolate my code between publishers I just use `Flowable.defer` to hold the mutable reference per subscriber.

I was curious what you thought about this change and would allow for users to not have to use `requestOn = false` for `Flowable.subscribeOn` when using a downstream `Flowable.create`.

The branch with the changes are at https://github.com/ReactiveX/RxJava/compare/3.x...wburns:flowable.create_request?expand=1 . One thing I could not figure out was how to combine the sip (subscribe in process) variable I added with the existing wip variables on the `BackpressureStrategy.BUFFER` and `BackpressureStrategy.LATEST` back pressure modes.

With this change a user can use `Flowable.create` with multiple invocations in an ASYNC request manner.

The only other option I could think of was `Flowable.generate` which would work, but then I have to do my own buffering, which is unaware of the request amount, since restarting per element would be quite slow.

**Comment by akarnokd** [comment]
The body of the create callback is not meant to be invoked multiple times or in response to requests. There is no reason to conflate the operator with the suggested mode.

Indeed `generate` is a one per request callback but still synchronous so blocking is not recommended. 

You could look at [generateAsync](https://github.com/akarnokd/RxJavaExtensions#flowablesgenerateasync) to talk to some async background API.

Third, you could split up the computation into Flowable chunks and produce a single sequence with `concatMap`.

Last resort is to write your own custom operator and react to requests as you need.

**Comment by wburns** [comment]
> The body of the create callback is not meant to be invoked multiple times or in response to requests. There is no reason to conflate the operator with the suggested mode.

Alright, I had a feeling you may say that.

I was using `Flowable.create(..).repeatUntil()` instead, but this runs into a slightly different problem in that it will pass a new emitter (on repeat) with the request amount of 0, since more entries haven't been requested yet. If instead `Flowable.create` lazily subscribed once based on when the initial request came in it would allow this to work and only have a single invocation. I have updated my branch with that in mind to only allow the one subscription.

> You could look at generateAsync to talk to some async background API.

I was unaware of that. It looks like multiple `onNext` can be invoked for a single invocation correct? Unfortunately, this requires another dependency, but may be worthwhile.

> Third, you could split up the computation into Flowable chunks and produce a single sequence with concatMap.

I could do that, but it has a similar issue as `generate` that I need to use a chunk size. Unfortunately, I am hoping to have an implementation that directly obeys the request amount as the code can also be called without a `Flowable.subscribeOn` operator and thus may request Long.MAX_VALUE for some reduction operations which would not need any queueing and pass all elements down `onNext` immediately.

> Last resort is to write your own custom operator and react to requests as you need.

At this point I think I am going to do this as I "only" need to implement Publisher and just do the recursion call inside the subscription request (protected by a wip counter).

**Comment by akarnokd** [comment]
> It looks like multiple onNext can be invoked for a single invocation correct?

No. There is no good way to prevent the user from calling too many onNexts without taking control away from them in a way.
