### ISSUE TITLE
Maybe#fromSupplier expects not null value from callable

### ISSUE THREAD

**Issue by EugeneWalkers** [ReactiveX/RxJava#7376]
In documentation about Maybe::fromSupplier it's said it works different from other operators and don't throw `NullPointerException` in case we provide `null` like
```kotlin
Maybe.fromSupplier<Boolean> {
    null as? Boolean
}
``` 
The static code analyser marks it with warning as expected `Boolean but was Boolean?`
In case we change the code like
```kotlin
Maybe.fromSupplier<Boolean?> {
    null as? Boolean
}
``` 
We also got warning as T is marked as NonNull
```java
@CheckReturnValue
@NonNull
@SchedulerSupport(SchedulerSupport.NONE)
public static <@NonNull T> Maybe<T> fromSupplier(@NonNull Supplier<? extends T> supplier) {
     Objects.requireNonNull(supplier, "supplier is null");
     return RxJavaPlugins.onAssembly(new MaybeFromSupplier<>(supplier));
}
```
Also according documentation this method `@throws NullPointerException if {@code supplier} is {@code null}` that's wrong

**Comment by akarnokd** [comment]
Kotlin is more involved in null types so it is possible.

Could you check if changing the signature as follows (adding `@Nullable` to the argument of `Supplier`) resolves the warnings?

```java
@CheckReturnValue
@NonNull
@SchedulerSupport(SchedulerSupport.NONE)
public static <@NonNull T> Maybe<T> fromSupplier(@NonNull Supplier<@Nullable ? extends T> supplier) {
     Objects.requireNonNull(supplier, "supplier is null");
     return RxJavaPlugins.onAssembly(new MaybeFromSupplier<>(supplier));
}
```

> Also according documentation this method `@throws NullPointerException if {@code supplier} is {@code null}` that's wrong

Not sure what you mean by this. The documentation clearly states if **the argument is null**, it throws, and `requireNonNull` makes that happen. Also we have unit tests that verify the API in this regard.

**Comment by EugeneWalkers** [comment]
Actually this code don't fix warnings as not null variables extends nullable, not vice versa.
The following code works:
```java
@CheckReturnValue
@NonNull
@SchedulerSupport(SchedulerSupport.NONE)
public static <@Nullable T> Maybe<T> fromSupplier(@NonNull Supplier<? extends T> supplier) {
    Objects.requireNonNull(supplier, "supplier is null");
    return RxJavaPlugins.onAssembly(new MaybeFromSupplier<>(supplier));
}
```
In that case no problem with warnings
```kotlin
Maybe.fromSupplier<Boolean?> { 
    null
}
```
Oh, sorry, you're absolutely right about doc, i read this line wrong, so everything is correct here

**Comment by akarnokd** [comment]
For me, your suggestion still gives warnings. Besides, a nullable `T` is not a valid argument for a chain of `Maybe`s because it can never signal null.

I've tried a couple of signatures and this is what I get

```kotlin
    // No warning
    // static <T> Maybe<@NonNull T> fromSupplier1(Supplier<? extends @Nullable T> supplier)
    FromSupplier.fromSupplier1<Boolean> { null }
            .subscribe()

    // Warning
    // static <T> Maybe<@NonNull T> fromSupplier2(Supplier<@Nullable ? extends T> supplier)
    FromSupplier.fromSupplier2<Boolean> { null }
            .subscribe()

    // No Warning
    // static <@NonNull T> Maybe<T> fromSupplier3(Supplier<? extends @Nullable T> supplier)
    FromSupplier.fromSupplier3<Boolean> { null }
            .subscribe()

    // Warning
    // static <@NonNull T> Maybe<T> fromSupplier4(Supplier<@Nullable ? extends T> supplier)
    FromSupplier.fromSupplier4<Boolean> { null }
            .subscribe()

    // Warning
    // static <@NonNull T> Maybe<T> fromSupplier5(@NonNull Supplier<? extends @Nullable T> supplier)
    FromSupplier.fromSupplier5<Boolean> { null }
            .subscribe()

    // Warning
    // static <@NonNull T> Maybe<T> fromSupplier6(@NonNull Supplier<@Nullable ? extends T> supplier)
    FromSupplier.fromSupplier6<Boolean> { null }
            .subscribe()

```

So basically if I apply `@Nullable` to the supplier's `T` directly, no warning, except if the whole `Supplier` is annotated with `@NonNull` (case 5).

I'd say the Kotlin compiler has some odd behavior and might be worth asking them first about the situation.

**Comment by EugeneWalkers** [comment]
From my point of view, there is no mistake in Kotlin compiler, as now we declare only non-null values everywhere so we can't just return `null` in lambda.
The first approach looks great! Yeah, the only thing is that `Supplier` defined as interface with non-null value, so here it's a logical error. Anyway, all warnings have disappeared

**Comment by akarnokd** [comment]
Posted a bug report regarding case 5: https://youtrack.jetbrains.com/issue/KT-50734

**Comment by petukhovv** [comment]
Thanks for the report! See the answer in the corresponding issue ([KT-50734](https://youtrack.jetbrains.com/issue/KT-50734)).
