### ISSUE TITLE
Flowable.create() occurs error

### ISSUE THREAD

**Issue by mengzhiya** [ReactiveX/RxJava#7386]
static final int BUFFER_SIZE;
    static {
        BUFFER_SIZE = Math.max(1, Integer.getInteger("rx2.buffer-size", 128));
    }

occurs error when "rx2.buffer-size" propertity is null in system thows follow exception:
Fatal Exception: java.lang.NoSuchMethodError
No static method ,material_text_view_test_line_height_override(II)I in class Ljava/lang/Math; or its super classes (declaration of 'java.lang.Math' appears in /system/framework/core-oj.jar)
io.reactivex.Flowable.<clinit>

**Comment by akarnokd** [comment]
> No static method ,material_text_view_test_line_height_override(II)I in class Ljava/lang/Math; or its super classes (declaration of 'java.lang.Math' appears in /system/framework/core-oj.jar)

Sounds like some kind of corruption in your environment or binary that causes the issue and has nothing to do with RxJava.

**Comment by Akhenaton27** [comment]
>     static final int BUFFER_SIZE;
>     static {
>         BUFFER_SIZE = Math.max(1, Integer.getInteger("rx2.buffer-size", 128));
>     }
> 
> occurs error when "rx2.buffer-size" propertity is null in system thows follow exception:
> Fatal Exception: java.lang.NoSuchMethodError
> No static method ,material_text_view_test_line_height_override(II)I in class Ljava/lang/Math; or its super classes (declaration of 'java.lang.Math' appears in /system/framework/core-oj.jar)
> io.reactivex.Flowable.<clinit>
>
