### ISSUE TITLE
Is it possible to use backpressure with parallel?

### ISSUE THREAD

**Issue by ArsenyClean** [ReactiveX/RxJava#7394]
Flowable.fromIterable(items)
                .parallel()
                .runOn(Schedulers.io())
                .map(someFunction())
                .sequential()
                .subscribe(someSubscriber);

If i run this code, map function will process asynchronously in 12 threads (or in other count of threads, depends on pc), but subscription will be in one thread. The problem is that 12 threads wait for the subscription finished, and only then they will take other 12 items

I need someFunction not to wait subscriber, and at the same time, i need it to work asynchronously.

At the same time, i need subscriber to work in one thread

How to solve such a problem?

**Comment by akarnokd** [comment]
What you are seeing is the effect of backpressure on `sequential`. Apply `observeOn` after it with another scheduler to not bog down the parallel threads.
