### ISSUE TITLE
switchMap title different with document link,Please see attach

### ISSUE THREAD

**Issue by gucheng3116** [ReactiveX/RxJava#7395]
![switch_doc](https://user-images.githubusercontent.com/17681086/154845024-ade0add7-b63c-40ff-963c-b4d5f9ce0a90.png)

**Comment by gucheng3116** [comment]
title is switchMap, but document is flatMap, is it abnormal?

**Comment by akarnokd** [comment]
For some reason, reactivex.io has listed `switchMap` along with the `flatMap`s. I can't do anything about it.
