### ISSUE TITLE
3.x can RxJava support concatMapEagerSingle?

### ISSUE THREAD

**Issue by jiqimaogou** [ReactiveX/RxJava#7415]
Hello, Rxjava has`concatMapEager`

```
    public final <R> Observable<R> concatMapEager(@NonNull Function<? super T, ? extends ObservableSource<? extends R>> mapper) {
```

the mapper returns an ObservableSource.

in my case
mapper returns a Single.
```
    public final <R> Observable<R> concatMapEagerSingle(@NonNull Function<? super T, ? extends SingleSource<? extends R>> mapper) {
```

can RxJava support `concatMapEagerSingle`?

**Comment by akarnokd** [comment]
There are no plans to support this type of conversion. Use the `toObservable` to convert your `Single`.
