### ISSUE TITLE
issue with the reactive-stream License

### ISSUE THREAD

**Issue by dineshr93** [ReactiveX/RxJava#7418]
Hi Rxjava is dependent on reactive-stream which has CC-1.0 license that has the issue https://github.com/reactive-streams/reactive-streams-jvm/issues/536

That makes usage of RxJava problematic.

They plan to release new version with MIT license. Please consider upgrade to the new version of the reactive.-stream which will **not** be under CC-1.0 license

please check this comment https://github.com/reactive-streams/reactive-streams-jvm/issues/536#issuecomment-1124497560 for dependency relationship

Thanks

**Comment by akarnokd** [comment]
We are aware of the upcoming license change and will act once it is released.

Please stop spraying the projects with this issue, thanks.
