### ISSUE TITLE
Could not GET 'https://dl.bintray.com/samanjafaridotir/easyCountDownTimerTextview/com/google/maps/android/android-maps-utils/maven-metadata.xml'. Received status code 502 from server: Bad Gateway Disable Gradle 'offline mode' and sync project

### ISSUE THREAD

**Issue by elias-nasser** [ReactiveX/RxJava#7421]
Could not GET 'https://dl.bintray.com/samanjafaridotir/easyCountDownTimerTextview/com/google/maps/android/android-maps-utils/maven-metadata.xml'. Received status code 502 from server: Bad Gateway
Disable Gradle 'offline mode' and sync project

**Comment by akarnokd** [comment]
How is this an RxJava issue? Bintray has been dead for some time.
