### ISSUE TITLE
Rxjava 2.2.21 or 2.2.17 run in Android 13 always  crash, other version no try.

### ISSUE THREAD

**Issue by ZhangWuWei** [ReactiveX/RxJava#7423]
sample:

Observable.create(new ObservableOnSubscribe<String>() {
    @Override
    public void subscribe(ObservableEmitter<String> emitter) throws Exception {
        emitter.onNext("test");
        emitter.onComplete();
    }
})
.subscribeOn(Schedulers.io())
.observeOn(AndroidSchedulers.mainThread())
.subscribe(new Observer<String>() {
    @Override
    public void onSubscribe(Disposable d) {

    }

    @Override
    public void onNext(String s) {
        
    }

    @Override
    public void onError(Throwable e) {

    }

    @Override
    public void onComplete() {

    }
});

**Comment by akarnokd** [comment]
You haven't provided enough information to diagnose the problem. Also if you have problems while running in Android, please ask your question on StackOverflow as we only support RxJava version 3.x and platform-independent problems here.
