### ISSUE TITLE
3.x: Missing `NonNull` annotation on `Maybe<T>`

### ISSUE THREAD

**Issue by KarboniteKream** [ReactiveX/RxJava#7435]
In #6840, the `@NonNull` annotation was added to various class generic types, including [`MaybeSource`](https://github.com/ReactiveX/RxJava/blob/8e6bc11b141093af619a8f423dca01a32a80e2a7/src/main/java/io/reactivex/rxjava3/core/MaybeSource.java#L29).
However, the annotation was omitted from [`Maybe`](https://github.com/ReactiveX/RxJava/blob/8e6bc11b141093af619a8f423dca01a32a80e2a7/src/main/java/io/reactivex/rxjava3/core/Maybe.java#L113) itself. Was this intentional or was it just overlooked?

Apologies if this has been asked before, but I couldn't find any related issues/PRs.

**Comment by akarnokd** [comment]
Looks like a simple oversight. PR welcome.

**Comment by KarboniteKream** [comment]
Thanks for the clarification, let me submit it
