### ISSUE TITLE
[RxJava 3.1.5] Crash in Kotlin 1.7.0 due to contradictions between nullability of BiConsumer and Maybe.doOnEvent

### ISSUE THREAD

**Issue by dkuteynikov** [ReactiveX/RxJava#7444]
Code compiled with Kotlin 1.7.0 crashes with
`java.lang.NullPointerException: Parameter specified as non-null is null: method MainKt.rx$lambda-0, parameter <anonymous parameter 1>`

The reason of this issue is that `doOnEvent` method of `Maybe` passes `@Nullable` parameters to `BiConsumer` which was defined with `@NonNull` requirement for it's params:
```java
public final Maybe<T> doOnEvent(@NonNull BiConsumer<@Nullable ? super T, @Nullable ? super Throwable> onEvent) { ... }
```
```java
package io.reactivex.rxjava3.functions;
import io.reactivex.rxjava3.annotations.NonNull;

@FunctionalInterface
public interface BiConsumer<@NonNull T1, @NonNull T2> {
    void accept(T1 t1, T2 t2) throws Throwable;
}
```

Here is the example code which crashes:
```kotlin
import io.reactivex.rxjava3.core.Maybe

fun main(args: Array<String>) {
    println("Start")
    rx("abc").subscribe()
    println("Done")
}

fun rx(data: String): Maybe<String> {
    return Maybe.just(data).doOnEvent { d: String?, _ -> // Crashes in Kotlin 1.7.0
        println("got $d")
    }
}
```
The second anonymous parameter `_` is detected as `@NonNull` by Kotlin, and the corresponding check `Intrinsics.checkNotNullParameter` is automatically generated.
It's important to put the additional compiler arguments:
```kts
plugins {
    kotlin("jvm") version "1.7.0"
    application
}

group = "bug.example"
version = "1.0"

repositories {
    mavenCentral()
}

dependencies {
    implementation("io.reactivex.rxjava3:rxjava:3.1.5")
    implementation("io.reactivex.rxjava3:rxkotlin:3.0.1")
    testImplementation(kotlin("test"))
}

tasks.test {
    useJUnitPlatform()
}

application {
    mainClass.set("MainKt")
}

tasks.withType(org.jetbrains.kotlin.gradle.tasks.KotlinCompile::class.java).all {
    kotlinOptions {
        freeCompilerArgs += listOf(
            "-Xjvm-default=all",
            "-Xnullability-annotations=@io.reactivex.rxjava3.annotations:strict",
            "-Xnullability-annotations=@com.android.annotations:strict",
            "-Xnullability-annotations=@android.support.annotations:strict",
            "-Xnullability-annotations=@javax.annotation:strict",
            "-Xnullability-annotations=@org.jetbrains.annotations:strict"
        )
    }
}
```
For your convenience I attach the archived project.
[param-npe.zip](https://github.com/ReactiveX/RxJava/files/9028514/param-npe.zip)

**Comment by akarnokd** [comment]
> The second anonymous parameter `_` is detected as `@NonNull` by Kotlin, and the corresponding check `Intrinsics.checkNotNullParameter` is automatically generated.

Does it work if you explicitly specify `ex: Throwable?`? Does the `d: String?` also get a forced null check?

This sounds like a problem with the Kotlin compiler ignoring the override. I can only suggest to ask the Kotlin compiler writers if your scenario is indeed a compiler bug or not.

**Comment by dkuteynikov** [comment]
If I explicitly specify the type as `ex: Throwable?` it doesn't crash.

It means that Kotlin fails to automatically resolve the conflict between `@Nullable` and `@NonNull`. Indeed, how the same type argument can be simultaneously `@Nullable` and `@NonNull`? Maybe you should define `BiConsumer` with `@Nullable` arguments if you plan to pass `null` there?

**Comment by akarnokd** [comment]
No. `NonNull` is the default behavior. Plus changing nullability is always a risk with Kotlin users; someone else's code may break as a result.

**Comment by hoc081098** [comment]
Try adding `_: Throwable? ->`

**Comment by dkuteynikov** [comment]
`_: Throwable? ->` doesn't crash. Only if I don't explicitly specify the nullability, it crashes.

**Comment by akarnokd** [comment]
Please post your issue to https://youtrack.jetbrains.com/issues/KT so someone who understands what the compiler is supposed to do can have a look at it.

**Comment by hoc081098** [comment]
@akarnokd How about using `@NonNull`  on consumer side instead of declaration side

**Comment by dkuteynikov** [comment]
Reported to Kotlin: https://youtrack.jetbrains.com/issue/KT-53041

**Comment by dkuteynikov** [comment]
I was thinking about this issue during the weekend, and this is what came into my mind.

Java language specification in [the document about annotations](https://checkerframework.org/jsr308/java-annotation-design.html) says the following:

> This document specifies the syntax of extended Java annotations in Java source code and how those annotations are represented in classfiles. However, this document makes no commitment as to the **semantics** of any particular annotation type. As with Java’s existing annotations [[Blo04](https://checkerframework.org/jsr308/java-annotation-design.html#JSR175)], the semantics is dependent on annotation processors (**compiler plug-ins**), and not every annotation is necessarily sensible in every location where it is **syntactically** permitted to appear.

That means that only in our mind `@Nullable` and `@NonNull` have the opposite meaning. For the language itself they are completely independent annotations. `@interface Nullable` dosn't mention `@interface NonNull` in it's declaration and vice-versa. That's why I can write code like this in Java and it compiles:

```java
class JavaObj<T> {

    @NonNull
    @Nullable
    T data;

    ...
}
```

As a result, we get the same entity annotated simultaneously with both annotations. And one doesn't remove another. So the situation is ambiguous. How it will be treated - it depends on the compiler plug-ins, which may differ on different builds.

> A designer can define new type qualifiers using Java annotations, and can provide compiler plug-ins to check their semantics (for instance, by issuing lint-like warnings during compilation). A programmer can then use these type qualifiers throughout a program to obtain additional guarantees at compile time about the program. The type system defined by the type qualifiers does not change Java semantics, nor is it used by the Java compiler or run-time system. Rather, it is used by the checking tool

**Comment by akarnokd** [comment]
Fixed in Kotlin 1.8.0-Beta.

**Comment by filipatbnp** [comment]
@akarnokd are you sure? https://youtrack.jetbrains.com/issue/KT-53041 says it will be in 1.9.0-Beta

**Comment by akarnokd** [comment]
Or in 2.0.0 beta, or in 3.0. They keep pushing the fix out further and further.
