### ISSUE TITLE
Extend Scheduler#scheduleDirect with a Disposable container

### ISSUE THREAD

**Issue by sahil2441** [ReactiveX/RxJava#7445]
There's [recent API addition](https://github.com/ReactiveX/RxJava/pull/7298) in 3.1.0 that adds a composite in the `subscribe()` calls as a 4th parameter so that when the upstream terminates the disposable is also disposed.

In our application we use [Scheduler#scheduleDirect](http://reactivex.io/RxJava/3.x/javadoc/io/reactivex/rxjava3/core/Scheduler.html#scheduleDirect-java.lang.Runnable-) very often.
It'd be nice to extend Scheduler#scheduleDirect with a Composite so that returned the `Disposable` is automatically disposed when the upstream terminates.

**Comment by akarnokd** [comment]
You mean when the scheduled task completes?

We don't want to expand the `Scheduler` API into that direction so I suggest an utility method for you instead:

```java
public static Disposable schedule(Scheduler scheduler, Runnable run, 
        DisposableContainer container) {
    SerialDisposable d = new SerialDisposable();
    container.add(d);
    d.replace(scheduler.scheduleDirect(() -> {
        try {
             run.run();
        } finally {
             container.delete(d);
        }
    }));
    return Disposable.fromRunnable(() -> container.remove(d));
}
```
