### ISSUE TITLE
Rxjava3 reduce with Observable

### ISSUE THREAD

**Issue by jiqimaogou** [ReactiveX/RxJava#7446]
hello

reduce function only support synchronized value.
```
    public final <@NonNull R> Single<R> reduce(R seed, @NonNull BiFunction<R, ? super T, R> reducer) {
```

can you support async value?
```
    public final <@NonNull R> Single<R> reduce(R seed, @NonNull BiFunction<R, ? super T, ? extends ObservableSource<? extends R>> reducer) {
```

**Comment by akarnokd** [comment]
Not in the plans.

Can't you just use concatMap + the current reducer?

**Comment by akarnokd** [comment]
Here is a way to implement it on your end:

```java
public static <T, R> Single<R> reduceSingle(Observable<T> source, R seed, 
        BiFunction<R, ? super T, ? extends Single<? extends R>> reducer) {
    return Single.defer(() -> {
        AtomicReference<R> ref = new AtomicReference<R>(seed);

        return source.concatMapSingle(t -> {
             return reducer.apply(ref.get(), t)
                           .doOnSuccess(ref::set);
        })
        .ignoreElements()
        .andThen(Single.fromCallable(ref::get));
    });
}
```

**Comment by jiqimaogou** [comment]
is it suitable to call single.blockingget() in reduce?

**Comment by jiqimaogou** [comment]
> Here is a way to implement it on your end:
> 
> ```java
> public static <T, R> Single<R> reduceSingle(Observable<T> source, R seed, 
>         BiFunction<R, ? super T, ? extends Single<? extends R>> reducer) {
>     return Single.defer(() -> {
>         AtomicReference<R> ref = new AtomicReference<R>(seed);
> 
>         return source.concatMapSingle(t -> {
>              return reducer.apply(ref.get(), t)
>                            .doOnSuccess(ref::set);
>         })
>         .ignoreElements()
>         .andThen(Single.fromCallable(ref::get));
>     });
> }
> ```


is it suitable to call single.blockingget() in reduce?

**Comment by akarnokd** [comment]
It can lead to non responsiveness because `blockingGet` is disconnected from the reduce sequence. I don't recommend using it.

**Comment by jiqimaogou** [comment]
> It can lead to non responsiveness because `blockingGet` is disconnected from the reduce sequence. I don't recommend using it.

Can you please help with an example to describe the above bad practice?

I also feel that all Observables should be connected, it's bad practice to use `blockingGet` to convert async to sync. But I don't know why, can you help to explain it?

not only `reduce`, but `scan`, `combinelatest`, `zip`..., why we should not call `blockingGet` in these functions?

**Comment by akarnokd** [comment]
Sequences are connected if one sequence knows about the `Disposable` in another sequence(s), or vice versa, hence if one sequence gets disposed, it can notify the other sequence(s).

If you use `blockingGet`, you have to manage cancellations via other operators (`timeout`, `takeUntil`) or make sure the `blockingGet` runs on a scheduler that can be interrupted.
 
Also, most of the time the behavior of the secondary sequence can be joined up with the primary sequence via standard operators (e.g., `flatMap`) or combinations of standard operators.

Blocking can also cause deadlocks or memory leaks in certain `Scheduler`s. Reasoning about blocking is not that easy, reasoning about a mixture of blocking and non-blocking execution requires a lot of experience and thought. So simply avoid blocking with Rx as much as possible.

**Comment by jiqimaogou** [comment]
> Sequences are connected if one sequence knows about the `Disposable` in another sequence(s), or vice versa, hence if one sequence gets disposed, it can notify the other sequence(s).
> 
> If you use `blockingGet`, you have to manage cancellations via other operators (`timeout`, `takeUntil`) or make sure the `blockingGet` runs on a scheduler that can be interrupted.
> 
> Also, most of the time the behavior of the secondary sequence can be joined up with the primary sequence via standard operators (e.g., `flatMap`) or combinations of standard operators.
> 
> Blocking can also cause deadlocks or memory leaks in certain `Scheduler`s. Reasoning about blocking is not that easy, reasoning about a mixture of blocking and non-blocking execution requires a lot of experience and thought. So simply avoid blocking with Rx as much as possible.

very clear, thanks!

**Comment by jiqimaogou** [comment]
> > Here is a way to implement it on your end:
> > ```java
> > public static <T, R> Single<R> reduceSingle(Observable<T> source, R seed, 
> >         BiFunction<R, ? super T, ? extends Single<? extends R>> reducer) {
> >     return Single.defer(() -> {
> >         AtomicReference<R> ref = new AtomicReference<R>(seed);
> > 
> >         return source.concatMapSingle(t -> {
> >              return reducer.apply(ref.get(), t)
> >                            .doOnSuccess(ref::set);
> >         })
> >         .ignoreElements()
> >         .andThen(Single.fromCallable(ref::get));
> >     });
> > }
> > ```
> 
> is it suitable to call single.blockingget() in reduce?

Hello my last question?
why use defer here? what's the different with:

```java
public static <T, R> Single<R> reduceSingle(Observable<T> source, R seed, 
        BiFunction<R, ? super T, ? extends Single<? extends R>> reducer) {
        AtomicReference<R> ref = new AtomicReference<R>(seed);

        return source.concatMapSingle(t -> {
             return reducer.apply(ref.get(), t)
                           .doOnSuccess(ref::set);
        })
        .ignoreElements()
        .andThen(Single.fromCallable(ref::get));
}
```

**Comment by akarnokd** [comment]
It makes the use of `ref` limited to any particular subscription. I.e., if you subscribed to the resulting `Single` twice, my code would behave correctly. Without `defer`, the second subscription would use the very same `ref` and overwrite each other's intermediate values.
