### ISSUE TITLE
Firebase reporting crashes but when I try to reproduce it just logs System.err

### ISSUE THREAD

**Issue by jrowan3** [ReactiveX/RxJava#7447]
Hello, thank you for your time, I am having crashes reported to firebase that I cannot figure out how to solve.

  - [x] Please include the library version number, including the minor and patch version, in the issue text. In addition, if you'd include the major version in the title (such as `3.x`) that would be great.
  rxJavaVersion = "1.3.8"
    rxAndroidVersion = "1.2.1"

I started looking into this crash
```
Fatal Exception: java.lang.IllegalStateException
Exception thrown on Scheduler.Worker thread. Add `onError` handling.
```

But in our Application subclass we are doing this in onCreate()

```
RxJavaPlugins rxJavaPlugins = RxJavaPlugins.getInstance();
        rxJavaPlugins.reset();
        rxJavaPlugins.registerErrorHandler(new RxJavaErrorHandler() {
            @Override
            public void handleError(Throwable e) {
     
                e.printStackTrace();
              
            }
        });
```

The observable that is reporting this crash is

```
Observable.just(mSearchCriteria)
                        .map((Func1<AbstractSearchCriteria, Void>) abstractSearchCriteria -> {
                            mRecentSearchManager.save((FormSearchCriteria) abstractSearchCriteria);
                            return null;
                        })
                        .compose(RxTransformer.applyLowPriorityScheduler())
                        .subscribe();
```

I noticed that this crash is also in Firebase which could be related

Fatal Exception: java.lang.RuntimeException
Unable to create application com.mypackage.MainApplication: java.lang.IllegalStateException: Another strategy was already registered: rx.plugins.RxJavaPlugins$1@a86d388

Please if you can provide me with a way to figure out what is going on here, when I tried to reproduce the first crash with the same exception it is logged in Logcat as System.err and it seems that the onError is never even called. But the app never crashes and Firebase is reporting as a crash.  And I never get the onErrorNotImplemented part of the crash, the substacktrace of it is IllegalStateException which I can reproduce only logs, doesnt crash app.

I need to know if this is really a crash like Firebase says it is, or if RxJava is just reporting it to firebase as a crash when its really a log.

Thank you for your time

**Comment by akarnokd** [comment]
You have a crash which is then not observed, hence the "Add `onError` handling." message. Add an `onError` consumer to your `subscribe` methods.

"Another strategy was already registered" happens when you call `registerErrorHandler` without a preceding `reset` or call it twice.

**Comment by jrowan3** [comment]
So the registerErrorHandler doesnt catch all of the other onErrors for you @akarnokd ??

**Comment by jrowan3** [comment]
also, when I run the app with the same conditions that cause the exception in the subscribe method, the app doesnt crash and it just logs the exception

**Comment by akarnokd** [comment]
No. The handler receives only errors that would otherwise get lost.

I can't tell why you see or don't see the logs because Android sometimes ignores "chatty" log sources. If `mRecentSearchManager.save` crashes, put a try-catch around it and log the exception there.

Btw, RxJava 1.x is no longer supported and has all sorts of inconsistencies regarding the error handling. Please consider upgrading to RxJava 3.

**Comment by jrowan3** [comment]
Ok, thanks for the advice, one more thing, in the app we are only calling this once in Application onCreate, any ideas about that?
```
RxJavaPlugins rxJavaPlugins = 
RxJavaPlugins.getInstance();
        rxJavaPlugins.reset();
        rxJavaPlugins.registerErrorHandler(new RxJavaErrorHandler() {}

```

**Comment by jrowan3** [comment]
We are currently working on updating to RxJava 3, but our app is so big, the refactor is taking time.

**Comment by jrowan3** [comment]
Maybe i should replace it with RxJavaHooks? could you tell me the equivalent for registerErrorHandler?

**Comment by akarnokd** [comment]
> onCreate, any ideas about that?

No idea, maybe you call it concurrently with other Rx code? You'd probably need to put a breakpoint on the reset line and see why it doesn't stay null for the register call.

> could you tell me the equivalent for registerErrorHandler?

`setOnError`

**Comment by jrowan3** [comment]
@akarnokd One more question, do I have to call RxJavaHooks reset() or clear() before i setOnError for the replacement of registerErrorHandler, is it the same as RxJavaPlugins like will it still cause the "Another strategy was already registered" error?

**Comment by akarnokd** [comment]
`setOnError`  won't cause that error, you can set multiple times.

**Comment by jrowan3** [comment]
@akarnokd Thank you so much!!! Ill make these changes and hopefully that resolves these crashes in Firebase although they dont really crash the app.
