### ISSUE TITLE
3.x: Add onDropped callbacks to operators

### ISSUE THREAD

**Issue by akarnokd** [ReactiveX/RxJava#7458]
Add `onDropped` callback overloads to most operators that drop items that can't be recovered by other means.

- [x] `throttleLatest` [PR #7457](https://github.com/ReactiveX/RxJava/issues/7457)
- [x] `throttleFirst` [PR #7482](https://github.com/ReactiveX/RxJava/issues/7482)
- [x] `throttleLast` / `sample` [PR #7488](https://github.com/ReactiveX/RxJava/issues/7488)
- [x] `throttleWithTimeout` / `debounce` [PR #7510](https://github.com/ReactiveX/RxJava/issues/7510)
- [x] `onBackpressureLatest` ([PR #7458](https://github.com/ReactiveX/RxJava/pull/7542))
- [x] `onBackpressureBuffer` ([PR #7567](https://github.com/ReactiveX/RxJava/pull/7567))
  - 📓 The current overloads with `Action` are somewhat unhelpful, however, we'll have to add overloads in a way that avoids lambda ambiguity.

**Comment by Desislav-Petrov** [comment]
Hi - do you need any help with some of these?

**Comment by akarnokd** [comment]
@Desislav-Petrov you can have a stab at them. I won't have the time for weeks although there is no rush either.

**Comment by Desislav-Petrov** [comment]
Thanks, starting this week and will follow your PR per method strategy - I've started with throttleFirst

**Comment by Desislav-Petrov** [comment]
hi @akarnokd - i'm looking at throttleLast. From what I see, we should change the  public void onNext(T t) method in the *SampleTimed class. More precisely, when we do the lazySet() we should check if a value exists there - if so we need to call the onDropped with this value as this is what we're dropping. 
Does this make sense?

**Comment by akarnokd** [comment]
@Desislav-Petrov `lazySets` have to be made `getAndSet`: https://github.com/ReactiveX/RxJava/blob/3.x/src/main/java/io/reactivex/rxjava3/internal/operators/flowable/FlowableThrottleLatest.java#L130

**Comment by Desislav-Petrov** [comment]
Thx - leave this with me, will do a PR shortly.

**Comment by Desislav-Petrov** [comment]
taking a look at throttleWithTimeout / debounce next

**Comment by Desislav-Petrov** [comment]
Looking at onBackpressureLatest next
