### ISSUE TITLE
Test Smell: it is not a good practice to use nondeterministic random data in testing

### ISSUE THREAD

**Issue by TestSmell** [ReactiveX/RxJava#7467]
Hi!

We notice that the random number generator (RNG) is used to produce test data in your test code.
For example, ''asynchronousDrop'' method in DataSerializableJUnitTest.java 
<img width="612" alt="image" src="https://user-images.githubusercontent.com/110402847/187156056-c605a6d2-5182-45f5-9538-582bd991bfb5.png">
But generating random data in test code is not a good test practice. Since using randomized data may lead to unexpected unit test failure and once the test case fails, it is hard to trace what test data causes it.

Solution:
There are two solutions:

set a seed number for your random generator
using a hash method to generate random data
Thanks.

**Comment by akarnokd** [comment]
It's not a good practice to spam random repos with suggestions from a fresh account and no info on who or what you are.

Also the test is fine for us as is.
