### ISSUE TITLE
3.x: should observeOn be thread safe?

### ISSUE THREAD

**Issue by ThorJac** [ReactiveX/RxJava#7471]
Hi,
we are using the observeOn operator to ensure that values from different threads are dispatched to a target scheduler but we are running in the issue that values are getting lost.
We think that this is caused by the `io.reactivex.internal.operators.observable.ObservableObserveOn.ObserveOnObserver` which uses a `io.reactivex.internal.queue.SpscLinkedArrayQueue` for queuing the values.

However we are also not sure if this is expected behavior and if there are any alternatives which we should use?

Example:
```
val subject = BehaviorSubject.create<Int>()
  val counter = AtomicInteger()

  subject.observeOn(scheduler).subscribe { counter.incrementAndGet() }

  repeat(50) {
      Thread {
          repeat(1000) {
              subject.onNext(it)
              Thread.sleep(1)
          }
      }.start()
  }

  Observable.interval(5, TimeUnit.SECONDS)
      .subscribe { println("received ${counter.get()} values") }
```

If the operator would be thread safe an output of 50000 values would be expected however we often get less than that, e.g. 
`received 49970 values` or `received 49930 values`

Please can you clarify if this is expected behavior, a bug in rx java or maybe just a wrong usage by us? 
Thanks!

**Comment by akarnokd** [comment]
You are violating the contract of `onNext`: you can't invoke it concurrently and if you ever need to, use external means of synchronization. This is also explicitly mentioned in the Javadoc of [`BehaviorSubject`](http://reactivex.io/RxJava/3.x/javadoc/io/reactivex/rxjava3/subjects/BehaviorSubject.html).
