### ISSUE TITLE
3.x "Undeliverable" exceptions not always wrapped in UndeliverableException

### ISSUE THREAD

**Issue by jstaahl** [ReactiveX/RxJava#7480]
"Undeliverable" exceptions that match one of the types listed [here](https://github.com/ReactiveX/RxJava/blob/040ddcad1e0d0ac96969adf804e49758cb24833d/src/main/java/io/reactivex/rxjava3/plugins/RxJavaPlugins.java#L399) do not get wrapped in an UndeliverableException. It seems that this is because Throwables of these types are assumed to be library bugs originating from within library code. However, many of these Throwable types are just as likely to originate from within user-implemented functions as they are to arise from within library code. Undeliverable exceptions from user-implemented functions should always be wrapped in an UndeliverableException, regardless of their type.

**Comment by akarnokd** [comment]
This is by design to avoid unnecessary wrapping and thus verbosity in the global error handler. We don't plan to change this behavior.

**Comment by jstaahl** [comment]
Thanks. I just want to understand a bit better. Are you saying that the UndeliverableException wrapping is unnecessary in the first place? A common pattern for many is to simply catch and log UndeliverableExceptions in the global error handler. However, this leaves a nontrivial gap in the catchable errors when IllegalStateException, IllegalArgumentException, and NullPointerException don't get wrapped in an UndeliverableException.

edit: catch and *log

**Comment by akarnokd** [comment]
You can wrap them in your global error handler callback if you want.

**Comment by jstaahl** [comment]
Ah. I believe there is a common misunderstanding in the community about the thrown error type then. I think most developers assume that only UndeliverableExceptions are undeliverable exceptions arising from their code. As an example, this is the pattern I see often: https://github.com/instacart/truetime-android/issues/98#issuecomment-456730810. However, it sounds like it is actually safe to assume that _every_ exception bubbled up to the global error handler callback is an undeliverable exception arising from user code, regardless of its type. If this is the case, then I will do as you have suggested and just wrap them in my global error handler callback.
