### ISSUE TITLE
3.x: Add onDropped callback to throttleFirst operator

### ISSUE THREAD

**Issue by Desislav-Petrov** [ReactiveX/RxJava#7481]
This PR adds an overload to the throttleFirst operator which takes an onDropped consumer.

This consumer is called when we're still within the gated time window when any new item isn't passed to downstream.

If the onDropped crashes, the exception is either delivered to the downstream (if the sequence is still live at that point) or to the global error handler (sequence is stopped).

**Comment by akarnokd** [comment]
Not sure why you opened this issue. Just link to #7458 in your PRs.
