### ISSUE TITLE
Card activation

### ISSUE THREAD

**Issue by HENDERSON36** [ReactiveX/RxJava#7494]
Card activation

_Originally posted by @HENDERSON36 in https://github.com/ReactiveX/RxJava/issues/7491#issuecomment-1336498184_

**Comment by HENDERSON36** [comment]
> ```
>     Card activation
> ```
> 
> _Originally posted by @HENDERSON36 in [#7491 (comment)](https://github.com/ReactiveX/RxJava/issues/7491#issuecomment-1336498184)_

**Comment by HENDERSON36** [comment]
Help

**Comment by HENDERSON36** [comment]
Help to understand this account so I can move forward

**Comment by akarnokd** [comment]
You make no sense. Please quit spamming this repo.
