### ISSUE TITLE
rxandroid,io.reactivex.rxjava3  , get Android ID

### ISSUE THREAD

**Issue by githubczb** [ReactiveX/RxJava#7501]
io.reactivex.rxjava3:rxandroid:3.0.0
io.reactivex.rxjava3:rxjava:3.0.0

rxandroid,io.reactivex.rxjava3  , get Android ID, cause privacy non-compliance by Xiaomi App Store

**Comment by akarnokd** [comment]
I don't understand. Please explain your issue.
