### ISSUE TITLE
ExecutorScheduler.schedule(Runnable) cannot delivery RejectedExecutionException to consumer

### ISSUE THREAD

**Issue by wenhaozhao** [ReactiveX/RxJava#7509]
Why ExecutorScheduler.schedule(Runnable) cannot delivery RejectedExecutionException to consumer,
it is words well in Reactor, but we cannot do anything when it happen in RxJava.
especially when use blockGet(),the request thread will hang forever
![34FA19B5-94FC-45A0-B577-F4D2DF4031D4](https://user-images.githubusercontent.com/894671/210955311-d23324b8-d5d8-4f0b-a602-3c6b4a180a84.png)

**Comment by akarnokd** [comment]
It was designed as such. Most use sites wouldn't be able to handle such rejection or deliver the exception to the subscribers in any safe manner.

Do not shutdown the underlying executor while there are flows expected to use it and don't use executors that can reject some tasks as a form of throttling.

**Comment by wenhaozhao** [comment]
it's funny
