### ISSUE TITLE
[RxJava 2.2.21]: throttleFirst does not switch thread to the default computation thread while throttleLast does switch thread to the default computation thread

### ISSUE THREAD

**Issue by TonyTangAndroid** [ReactiveX/RxJava#7538]
**sample repo to reproduce the issue**: I have this pull request https://github.com/TonyTangAndroid/HelloRxJava/pull/8 here to demonstrate that  item through `throttleFirst` will remain to be the upstream thread `main` while item through `throttleLast` will be switched to the `RxComputationThreadPool-2`. This comes to me as a surprise. 

**Expectation** :  I had used `throttleLast` and learned that `throttleLast` will switch the thread to `Computation` thread pool. Hence, I made assumption that  `throttleFirst` will also do the same. 

**Actual** :   item through `throttleFirst` will remain to be the upstream thread `main`.

![throttle_first_vs_throttle_last_thread](https://user-images.githubusercontent.com/8612724/224441283-1b70660b-8ffb-4090-a86c-a2e2b707cce1.png)

**Comment by akarnokd** [comment]
The [Javadoc](http://reactivex.io/RxJava/3.x/javadoc/io/reactivex/rxjava3/core/Observable.html#throttleFirst-long-java.util.concurrent.TimeUnit-) clearly states.

> This differs from [throttleLast(long, java.util.concurrent.TimeUnit)](http://reactivex.io/RxJava/3.x/javadoc/io/reactivex/rxjava3/core/Observable.html#throttleLast-long-java.util.concurrent.TimeUnit-) in that this only tracks passage of time whereas throttleLast ticks at scheduled intervals.
