### ISSUE TITLE
Add minimum GitHub token permissions for workflows 

### ISSUE THREAD

**Issue by joycebrum** [ReactiveX/RxJava#7540]
@akarnokd can I bring up this topic (#7469) again and perhaps suggest a PR with the permission that were missing in this one? It is really a relevant topic on supply-chain security that prevents any threats and attacks. 

But before I would like to understand what didn't work on https://github.com/ReactiveX/RxJava/actions/runs/2343714818/jobs/3517587271 because for me it shows as success.

Looking into gradle_snapshot.yml and gradle_release.yml I've noticed that perhaps the permission that were missing was a `contents: write` to run this command https://github.com/ReactiveX/RxJava/blob/ed674be204210fe0804d64e28fdd356745915048/push_javadoc.sh#L118

Let me know if a PR is welcome and I'll try testing it before submit it, although I think it will be difficult considering sonatype access used.

**Comment by akarnokd** [comment]
The build doesn't fail if it can't push the javadoc back.

Alright, let's try your suggestion via PR.
