### ISSUE TITLE
3.x: Different behavior between blockingForEach and forEach

### ISSUE THREAD

**Issue by JaquierM** [ReactiveX/RxJava#7555]
Hello,

I'm surprise to see that the observable:
```java
Observable.just(0, 1, 2)
    .doOnSubscribe(ignored -> LOG.info("On subscribe"))
    .doOnTerminate(() -> LOG.info("On terminate"))
```

produce the following result with `.forEach(i -> LOG.info("Data: {}", i));`:
```
15:30:25.501 [main] INFO manual.NonBlockingTest - On subscribe
15:30:25.501 [main] INFO manual.NonBlockingTest - Data: 0
15:30:25.501 [main] INFO manual.NonBlockingTest - Data: 1
15:30:25.501 [main] INFO manual.NonBlockingTest - Data: 2
15:30:25.501 [main] INFO manual.NonBlockingTest - On terminate
```

and with `.blockingForEach(i -> LOG.info("Data: {}", i));`:
```
15:32:04.932 [main] INFO manual.BlockingTest - On subscribe
15:32:04.934 [main] INFO manual.BlockingTest - On terminate
15:32:04.935 [main] INFO manual.BlockingTest - Data: 0
15:32:04.936 [main] INFO manual.BlockingTest - Data: 1
15:32:04.936 [main] INFO manual.BlockingTest - Data: 2
```

I expected to have the same result (subscribe, datas, terminate) with `blockingForEach` as with `forEach` without using any scheduler. I have the same result with `subscribe`.

I tested with versions 3.1.3 and 3.1.6.

The documentation does not mention any difference between the two behaviors except that the blocking behavior blocks the current thread (which is what I want).

Did I not understand correctly the difference between the two or it is a bug?

Thanks for your time.

**Comment by akarnokd** [comment]
Not a bug. `blockingForEach` has an internal blocking buffer that can fill up before the control reaches its consumer callbacks.

In such synchronous cases, the upstream produces all items plus the terminal signal upon subscription, before `blockingForEach` switches to its consumer loop. With asynchronous sources, the production will usually happen on some other thread so the switch to the consumer loop pretty much immediately.

**Comment by JaquierM** [comment]
Ok, thanks for the answer.

I was not expecting that difference. I will just move my logic from `doOnTerminate` after the blocking call.
