### ISSUE TITLE
Kotlin multiplaform support

### ISSUE THREAD

**Issue by vladimirlisovskij** [ReactiveX/RxJava#7571]
Hi all!
I noticed that Reactivex has many implementations for different platforms. However, they are all separated into separate libraries. For the convenience of working in kotlin projects, I propose to combine them in a Kotlin Multiplatform project.
What do you think about it? Would it be useful?

I didn't know where to ask this question, so I wrote it here (sorry for this):
https://github.com/ReactiveX/RxKotlin
https://github.com/ReactiveX/RxAndroid
https://github.com/ReactiveX/RxJava

Thanks in advance!

**Comment by akarnokd** [comment]
We have separate projects so each platform can be unconstrained and Rx doesn't become the lowest common denominator.

For example, the RxAndroid main scheduler has no logical counterpart in server-backend RxJava. Kotlin has a lot of language features and conveniences that do not translate well (or at all) into RxJava for Java.
