### ISSUE TITLE
about 'ZIP'

### ISSUE THREAD

**Issue by sceneren** [ReactiveX/RxJava#7578]
version:'io.reactivex.rxjava3:rxjava:3.1.6'

the code will be crash,I don't known how to use zip?

        val single1 = Single.create<String> {
            throw Throwable("single1")
        }.subscribeOn(Schedulers.computation())

        val single2 = Single.create<String> {
            throw Throwable("single2")
        }.subscribeOn(Schedulers.io())

        Single.zip(single1, single2) { s1, s2 ->
            return@zip s1 + s2
        }.subscribeOn(Schedulers.io())
            .observeOn(AndroidSchedulers.mainThread())
            .subscribe({
                Log.e("MainActivity===>", "success===>${it}")
            }, {
                Log.e("MainActivity===>", "error===>${it.message.orEmpty()}")
            })

**Comment by akarnokd** [comment]
It crashes because the second exception has nowhere to go and is routed to the global error handler. You have to handle global errors or else it propagates to the Android system.

https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0#error-handling

**Comment by sceneren** [comment]
thx
