### ISSUE TITLE
Link http://reactivex.io/RxJava/ generated by github pages not working

### ISSUE THREAD

**Issue by md-abid-hussain** [ReactiveX/RxJava#7602]
version : 3.1.7
Link http://reactivex.io/RxJava/ generated by github pages not working

![image](https://github.com/ReactiveX/RxJava/assets/101964499/67fa100a-3ea6-4d89-bf3e-c86b021e5f8e)

**Comment by akarnokd** [comment]
Because there is nothing on that URL. We host the Javadoc at 

https://reactivex.io/RxJava/3.x/javadoc/
