### ISSUE TITLE
v3.1.4: race condition in DeferredScalarSubscription

### ISSUE THREAD

**Issue by nolaviz** [ReactiveX/RxJava#7604]
This issue was found by automated tooling (Thread Sanitizer). I have been unable to reduce the testcase from the production code (which is trade secret) to something more representative.

Library version: 3.1.4

Race is in `DeferredScalarSubscription`, between the `cancel` method and `complete` (lines 184 and 114 correspondingly).

My pipeline issues rpc's from the pipeline, aggregates the responses and will stop the pipeline once the aggregation satisfies some condition. From the stack trace of the race, it appears that `.takeUntil` decides to stop the pipeline just as some response is arriving - racing the cancellation and completion of the rpc result subscription.

```
  pipeline
    .flatMap(this::issueRpc(), MAX_CONCURRENCY)
    .scanWith(() -> Aggregator.create(), Aggregator::aggregate)
    .takeUntil(Aggregator::goodEnough)
```

**Comment by akarnokd** [comment]
Hi. Could you share more details on the race condition you are experiencing?

There is indeed a small race when a `cancel` happens while `poll()` is in progress, which can result in either a `null` or normal value. `null` will be treated by `flatMap` as being an empty source and bail out. Non null might be passed along and probably eventually stopped by some other operator's cancellation check.

**Comment by nolaviz** [comment]
The race condition is:

   - Thread 1 reaches DeferredScalarSubscription::complete() line 113, sees
   the state as FUSED_EMPTY, proceeds to line 114
   - Thread 1 sets value to the supplied "v"
   - Thread 2 reaches DeferredScalarSubscription::cancel() line 185, sets
   the state to CANCELLED
   - Thread 2 sets value to null
   - Thread 1 sets the state to FUSED_READY

The subscription is now in state FUSED_READY, but has a null value.

**Comment by akarnokd** [comment]
I see. Should have no practical effect because the `poll()` can return null indicating emptiness.

Do you have code that misbehaves due to this race?

**Comment by nolaviz** [comment]
Our automated race-detection tooling is triggering on this.
If this is a non-issue - I'll find a way to tell the automated tool to
ignore it.
