### ISSUE TITLE
3.x: Items dropped by observeOn without backpressure errors

### ISSUE THREAD

**Issue by m-radzikowski** [ReactiveX/RxJava#7613]
RxJava version: 3.1.8

I'm processing messages from `PublishProcessor` in parallel. On failure, items are put back to the processor for re-processing. I've noticed that events go missing randomly.

Reproduction:

```java
processor
    .doOnNext(s -> logger.trace("next: {}", s)) // item is here
    .onBackpressureDrop(s -> { // never called
        logger.error("!!!!!!! DROP {}", s);
        throw new RuntimeException("drop");
    })
    .observeOn(Schedulers.single()) // switch to single thread
    .doOnNext(s -> logger.trace("next single: {}", s)) // item is missing here
    .parallel()
    .runOn(Schedulers.io())
    .map(s -> { // run in parallel
        logger.info("Processing {}", s);
        Thread.sleep(50);
        logger.warn("Processing completed, reprocessing: {}", s);
        processor.onNext(s); // put item back
        return s;
    })
    .sequential()
    .subscribe();

processor.onNext("aaa");
processor.onNext("XXX");
```

Running it gives results in under a minute, often quicker - after some time, only one of the items is being processed, the other is lost.

I'm switching to `Schedulers.single()` for computation I've removed for brevity, and then process items in parallel. I found that items are lost on the `observeOn()` step - item is logged before it, and not logged after.

I've read the backpressure notice for the `observeOn()`, but as I understand, in case of the backpressure problem the `MissingBackpressureException` should be thrown. That's not happening.

Also the `onBackpressureDrop()` callback is never called.

Replacing `observeOn()` with `delay(0, TimeUnit.SECONDS, Schedulers.single())` seems to solve the problem, however I don't think quietly dropping items by `observeOn()` is expected here?

**Comment by akarnokd** [comment]
Did you serialize the `processor`? You are accessing it from possibly many threads.

**Comment by m-radzikowski** [comment]
No 🤦‍♂️

I did not notice that Publishers are not all methods are thread-safe by default. Serializing it solves the issue. Sorry.
