### ISSUE TITLE
DeferredScalarDisposable throws NullPointerException 

### ISSUE THREAD

**Issue by ritesh-singh** [ReactiveX/RxJava#7629]
Noticed  `DeferredScalarDisposable` throwing NPE when called from kotlin - basically i am a consumer of open-telemetry library, which also have support for RxJava2 [auto-instrumentation](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/instrumentation/rxjava/rxjava-2.0/library/src/main/java/io/opentelemetry/instrumentation/rxjava/v2_0/TracingObserver.java), my auto-instrumentation code is a direct replica of the open-tel source, but in kotlin.

In recent of kotlin - `1.9.20` it has a strict restriction when it comes to Generics and Java inter-op, they call it https://kotlinlang.org/docs/generics.html#definitely-non-nullable-types. Kotlin compiler fix is easy, intersect the Generic type with Any or just upper-bound with Any.

But, it makes it difficult with RxJava library, even-though the parameters are marked as `@NonNull` in java world for all `Observer<T>`(https://github.com/ReactiveX/RxJava/blob/24df131ecc012aa0591b9123b79a1f0f6a14a4f9/src/main/java/io/reactivex/Observer.java#L99) like `onNext`,  it's internal fusion code calls it will NULL - which will end up crashing my application.
Eg: - [https://github.com/ReactiveX/RxJava/blob/24df131ecc012aa0591b9123b79a1f0f6a14a4f9/[…]a/io/reactivex/internal/observers/DeferredScalarDisposable.java](https://github.com/ReactiveX/RxJava/blob/24df131ecc012aa0591b9123b79a1f0f6a14a4f9/src/main/java/io/reactivex/internal/observers/DeferredScalarDisposable.java#L79)

I came across this issue - https://github.com/ReactiveX/RxJava/issues/6702 which looks very related to this one, fusion code sending null value in the rx-stream  via onNext, which is required for the fusion queue poll implelemtation.

I am not sure, how should i handle this specific use-case in this case, i doubt any kind of delegation like [ObserverFix](https://github.com/ReactiveX/RxJava/issues/6702#issuecomment-550546466) is going to work with my use-case

Any leads/ideas?

**Comment by akarnokd** [comment]
Those nulls are internal affairs so unless you can exclude any class with that feature, no idea.

**Comment by ritesh-singh** [comment]
Sure, thank you. With limited understanding of how Rx2 deals with fusion internally. After give this [blog](https://akarnokd.blogspot.com/2016/03/operator-fusion-part-1.html?source=post_page-----dcd6612cffae--------------------------------) a read - my assumption is, Rx fusion library is adding `null` in the stream in case of  `Asynchronous-fusion`

Taking below para into consideration

`In asynchronous-fusion mode, downstream has to still issue request() calls, but instead of enqueueing the value twice, the value gets generated into the shared queue and the upstream calls onNext() indicating its availability. The value of this call is irrelevant, we use null as a type-neutral value, and can trigger the usual drain() call directly.`

I am wondering, if it's safe to assume not to call `onNext` on downstream observers when Rx fusion code calls onNext(null), getting invoked via upstream observer.

Below is the basic code snippet implementation of otel code in kotlin which deals with fusion.

```
// downstream  
internal class TracingObserver<T>( 
  private val wrappedObserver: Observer<in T>,
  private val context: Context,
) : BasicFuseableObserver<T, T>(
  wrappedObserver
) {
  override fun onNext(t: T & Any) { // it throws exception when it gets called via fusion
    context.makeCurrent().use { _ -> wrappedObserver.onNext(t) }
  }
......
}
```

```
// upstream 
internal class TracingSingleObserver<T>(
  private val actual: SingleObserver<T>,
  private val context: Context,
) : SingleObserver<T>, Disposable {
  private var disposable: Disposable? = null
  override fun onSubscribe(d: Disposable) {
    if (!DisposableHelper.validate(disposable, d)) {
      return
    }
    disposable = d
    actual.onSubscribe(this)
  }

  override fun onSuccess(t: T & Any) {
    context.makeCurrent().use { _ -> actual.onSuccess(t) } // upstream 
  }
....
}

```


I was wondering, if there are any implication, if i just handle the exception in `TracingSingleObserver#onSuccess` which will invoke `RxFusion with onNext(null)` but catches the exception thrown via `TracingObserver#onNext`.
Can there be any implications if `wrappedObserver.onNext(null)` isn't called in the RxStream.

Thanks, i need to dig in more!

**Comment by ritesh-singh** [comment]
👋  @akarnokd 

Last time, i had faced this issue, i avoided it by adding `ProhibitUsingNullableTypeParameterAgainstNotNullAnnotated` compiler flag, in kotlin 1.9.x, for that module. Looks like that flag is not valid anymore.


```
internal class TracingObserver<T>( // BasicFuseableObserver#actual has been renamed to downstream in newer versions, we can't use it
  // in this class
  private val wrappedObserver: Observer<in T>,
  private val context: Context,
) : BasicFuseableObserver<T, T>(
  wrappedObserver
) {
  override fun onNext(t: T) { // place where the code fails to compile in kotlin
    context.makeCurrent().use { _ -> wrappedObserver.onNext(t) }
  }
```

As stated, looks like null is emitted from Rx fusion - https://github.com/ReactiveX/RxJava/blob/24df131ecc012aa0591b9123b79a1f0f6a14a4f9/src/main/java/io/reactivex/internal/observers/DeferredScalarDisposable.java#L79 , which gets propagated in the chain, and ends up with NullPointer exception in kotlin world.

To fix the issue, i created a java class, overriding `onNext` with it's param marked as `@Nullable`

```
abstract class BasicFuseableObserverFix<T, R> extends BasicFuseableObserver<T,R> {

  /**
   * Construct a BasicFuseableObserver by wrapping the given subscriber.
   *
   * @param downstream the subscriber, not null (not verified)
   */
  public BasicFuseableObserverFix(Observer<? super R> downstream) {
    super(downstream);
  }

  @Override
  public void onNext(@Nullable T t) {
  }
}
```
and then 

```
internal class TracingObserver<T>( // BasicFuseableObserver#actual has been renamed to downstream in newer versions, we can't use it
  // in this class
  private val wrappedObserver: Observer<in T>,
  private val context: Context,
) : BasicFuseableObserverFix<T, T>(
  wrappedObserver
) {
  override fun onNext(t: T) { // place where the code fails to compile in kotlin
    context.makeCurrent().use { _ -> wrappedObserver.onNext(t) }
  }
```

Above, seems to fix the issue at my end.

Out of curiosity, wanted to confirm - if there aren't side-effect w.r.t Rx-fusion with above approach.

**Comment by akarnokd** [comment]
> Out of curiosity, wanted to confirm - if there aren't side-effect w.r.t Rx-fusion with above approach.

Can't think of any issues.

**Comment by ritesh-singh** [comment]
Thanks, since the `BasicFuseableObserverFix#onNext` is just a hack to satisfy compiler and for emitting the value
it's using `wrappedObserver.onNext(t)`, that should get the null emitted at required places, without interfering with any rx-chain.
