### ISSUE TITLE
`3.x` In README.md, add a link to the mentioned JavaFX Scheduler

### ISSUE THREAD

**Issue by pigelvy** [ReactiveX/RxJava#7630]
In [README.md](https://github.com/ReactiveX/RxJava#schedulers), there is a sentence about some specific Schedulers for other platforms.

> These are available on all JVM platforms but some specific platforms, such as Android, have their own typical Schedulers defined: AndroidSchedulers.mainThread(), SwingScheduler.instance() or JavaFXSchedulers.gui().

It's probably me but I can't find the `JavaFXSchedulers.gui()` you mention. Could you please update this section with links to those specific Schedulers?

**Comment by akarnokd** [comment]
https://github.com/torakiki/RxJavaFX/blob/2.11.x/src/main/java/org/pdfsam/rxjavafx/schedulers/JavaFxScheduler.java

Maybe they renamed it or never had such a name.

**Comment by pigelvy** [comment]
Okay, that is the one JavaFX Scheduler that I know about.
I still think that it would be clearer to newcomers if README.md had links to those specific Schedulers.

Feel free to close this ticket even if you don't alter README.md
Thx
