### ISSUE TITLE
Marble diagram for `Observable.concatMapMaybe` is wrong

### ISSUE THREAD

**Issue by boris-petrov** [ReactiveX/RxJava#7660]
https://reactivex.io/RxJava/3.x/javadoc/io/reactivex/rxjava3/core/Observable.html#concatMapMaybe-io.reactivex.rxjava3.functions.Function-

The diagram says `concatMap` instead of `concatMapMaybe` and also shows two items being emitted by the mapping function which is impossible in a `Maybe`. I guess the diagram was copied from `concatMap`. :)

**Comment by akarnokd** [comment]
Yes, we have still a lot of outdated and copy-paste diagrams.

No promises when they will be updated.

**Comment by dhrax21** [comment]
Hey can I work on this issue

**Comment by akarnokd** [comment]
Sure.

**Comment by dhrax21** [comment]
but what diagram should i replace with?

**Comment by akarnokd** [comment]
You have to draw it yourself, then post the png here.

If you have offline Excel, you could do it in our style:

- [Maybe marbles](https://docs.google.com/spreadsheets/d/1di67kFJEuiLPyq14JlnV3vFl-muaCMfH/edit?usp=drive_link&ouid=113316559156085910174&rtpof=true&sd=true)
- [Single marbles](https://docs.google.com/spreadsheets/d/1qlM9QSvXxAajFeW7LmuObrpuag1aKTFz/edit?usp=drive_link&ouid=113316559156085910174&rtpof=true&sd=true)
- [Completable marbles](https://docs.google.com/spreadsheets/d/1EkEucWJWxItTF_MyuFyFQj-5wGi7ZGAj/edit?usp=drive_link&ouid=113316559156085910174&rtpof=true&sd=true)
- [Mixed use marbles](https://docs.google.com/spreadsheets/d/0B4T7ZW3brESKQV9KaEF5YnpjM0k/edit?usp=drive_link&ouid=113316559156085910174&resourcekey=0-VV8blrt9k9AebKUT69Rj7g&rtpof=true&sd=true)

Or use [Draw.IO](draw.io) but it's a bit fiddly for this type of diagram work.

**Comment by dhrax21** [comment]
Sorry I don't wanna work on this 👍

**Comment by CHIRANTH-24** [comment]
![concatMapMayBe](https://github.com/ReactiveX/RxJava/assets/122692170/2e2dc2cc-685f-4e3e-8e7d-2cf7f0284971)
Hello @boris-petrov , I was able to understand the first part. Wanted help for the second.

**Comment by boris-petrov** [comment]
@CHIRANTH-24 - note that it's `Maybe`, not `MayBe`.

As for the second part - the diagram maps a single source item (the red circle) to multiple results (the white and red squares). It should be only a single white and a single red square. Same for the green and blue ones. Check the diagram for [flatMapMaybe](https://reactivex.io/RxJava/3.x/javadoc/io/reactivex/rxjava3/core/Observable.html#flatMapMaybe-io.reactivex.rxjava3.functions.Function-).
