### ISSUE TITLE
repeatWhen terminate

### ISSUE THREAD

**Issue by tonggang1308** [ReactiveX/RxJava#7664]
with 3.1.8

    fun test18() {
        var count = 0
        Completable.fromAction {
            println("Task 1")
        }.repeatWhen {
            it.flatMap {
                if (++count > 2) Flowable.empty()
                else Flowable.timer(100, TimeUnit.MILLISECONDS)
            }
        }.timeout(1000, TimeUnit.MILLISECONDS).doOnError {
            println("doOnError $it")
        }.doOnComplete {
            println("doOnComplete")
        }.onErrorComplete().blockingAwait()
    }
    

I just want to achieve an effect: if it meets the conditions, continue, if it does not meet the conditions, wait 100 milliseconds and repeat again.

My expected result is :
    Task 1
    Task 1
    Task 1
    doOnComplete
    
Although Flowable.empty() terminates the repeat,   but timeout is trigger.

**Comment by akarnokd** [comment]
Flatmapping an empty has no effect. You can't terminate that way. Use takeWhile for example.

**Comment by tonggang1308** [comment]
I just want to achieve an effect: if it meets the conditions, continue, if it does not meet the conditions, wait 100 milliseconds and repeat again.

**Comment by akarnokd** [comment]
Try this:

```kotlin
fun test18() {
    var count = 0
    Completable.fromAction {
        println("Task 1")
    }.repeatWhen {
        it
        .takeWhile { ++count < 3 }
        .flatMap {
            Flowable.timer(100, TimeUnit.MILLISECONDS)
        }
    }.timeout(1000, TimeUnit.MILLISECONDS).doOnError {
        println("doOnError $it")
    }.doOnComplete {
        println("doOnComplete")
    }.onErrorComplete().blockingAwait()
}
```

**Comment by tonggang1308** [comment]
thanks!
