### ISSUE TITLE
What does it mean due to lack of requests in MissingBackpressureException

### ISSUE THREAD

**Issue by nienienienie** [ReactiveX/RxJava#7683]
For http://reactivex.io/RxJava/3.x/javadoc/io/reactivex/rxjava3/exceptions/MissingBackpressureException.html there is

> Constructs a new MissingBackpressureException with the default message ["Could not emit value due to lack of requests"](http://reactivex.io/RxJava/3.x/javadoc/io/reactivex/rxjava3/exceptions/MissingBackpressureException.html#DEFAULT_MESSAGE).

And I'm trying to understand that message what exactly it means:
- what are requests in this context?
- what requests are lacking?
- and why RxJava even needs some requests?

**Comment by akarnokd** [comment]
-> https://github.com/ReactiveX/RxJava/wiki/Backpressure-(2.0)

**Comment by nienienienie** [comment]
thanks
