### ISSUE TITLE
FlowableObserveOn.BaseObserveOnSubscriber will ignore the next datas when cosumer throw exception 

### ISSUE THREAD

**Issue by laohuyuhai** [ReactiveX/RxJava#7687]
version: 2.2.19
![image](https://github.com/ReactiveX/RxJava/assets/10240823/95095620-fe25-4e12-a8c0-009ef4fb24b4)
![image](https://github.com/ReactiveX/RxJava/assets/10240823/bb3ff845-42e0-434d-b7c6-09a07ea138b3)
![image](https://github.com/ReactiveX/RxJava/assets/10240823/c6b6be52-3a81-44e6-9c22-7c631a25d1cf)

**Comment by laohuyuhai** [comment]
when a.tryOnNext(v) throw an exception, then addAndGet(-missed) will not execute,  then next flow run to tyrSchedule(), getAndIncrement != 0 will always be ture, then return,  the value is ignored。 Is this normal?

**Comment by akarnokd** [comment]
Why would the consumer throw? OnNext should not throw and RxJava honors this requirement. Are you implementing your own Subscriber? Do not throw or use a safeSubscribe.

Also 2.x is no longer suppoerted

**Comment by laohuyuhai** [comment]
Thank , I understand

**Comment by laohuyuhai** [comment]
> Why would the consumer throw? OnNext should not throw and RxJava honors this requirement. Are you implementing your own Subscriber? Do not throw or use a safeSubscribe.
> 
> Also 2.x is no longer suppoerted

Thank , I understand
