### ISSUE TITLE
Android: Subject alternative to using CursorLoader

### ISSUE THREAD

**Issue by imminent** [ReactiveX/RxJava#769]
I'm attempting to use RxJava to replace the `CursorLoader` approach in Android for retrieving and refreshing a `Cursor`. I have https://gist.github.com/imminent/8511925 so far. Curious if anyone else as tried this, or sees ways to improve what I'm doing.

**Comment by RahulRvR** [comment]
Is there a way now to use rxjava to replace cursor.

**Comment by iNoles** [comment]
There is SQLBrite. https://github.com/square/sqlbrite
