### ISSUE TITLE
Some Schedulers along with lockingGet will make the application hang

### ISSUE THREAD

**Issue by floodfill** [ReactiveX/RxJava#7713]
Verified hanging in both 2.x and 3.x versions.

This is the minimal code to reproduce the bug:
```
List<Integer> res = Observables
    .fromIterable(List.of(1, 2, 3, 4, 5))
    .subscribeOn(Schedulers.from(Executors.newFixedThreadPool(10))
    .map(x -> x * 2)
    .toList()
    .blockingGet();

res.foreach(x -> System.out.println("res" + x));
```

Running this code will still successfully print out everything in res, but it will hang the application and will not exit.

**Comment by akarnokd** [comment]
Not an RxJava issue. You have to shutdown the executor you created as it uses non-daemon threads that prevent the JVM from quitting.
