### ISSUE TITLE
shareReplay implementation help

### ISSUE THREAD

**Issue by fraune** [ReactiveX/RxJava#7803]
Hello, I'm looking for advice on implementing what I _think_ is called [`shareReplay`](https://rxjs.dev/api/operators/shareReplay) in RxJS. I've been digging through documentation and haven't found a suitable operator yet in RxJava (or RxKotlin).

Excuse the Kotlin sample code:

```kotlin
private val sharedObservable: Observable<T> =
    Observable.defer {
        executeInternal()
    }
        .replay(1)
        .refCount()
```

## Expected behavior

- If sharedObservable has multiple subscribers, I want results emitted from executeInternal to update each subscriber
- If sharedObservable has a subscription and executeInternal has emitted a value, new subscribers to sharedObservable will receive that last (cached) emission upon subscription
- If sharedObservable receives multiple subscribers before executeInternal has emitted a value, only a single subscription to executeInternal should be made (like if I used `.publish()` instead of `.replay(1)`, though I don't think both can be used simultaneously).
  - Small note on this requirement: executeInternal will establish a Bluetooth connection upstream, so I will cause errors by connecting to the same peripheral multiple times
- After all unsubscribe from sharedObservable, the subscription to executeInternal() is also disposed
  - This will allow me to disconnect from the Bluetooth peripheral
- After sharedObservable is unsubscribed from, future subscriptions to it will re-subscribe to executeInternal
  - This is important, since I can't restart a completed or errored Observable, but I will need to reconnect and transmit data again

## Libraries

I am using the [RxAndroidBle](https://github.com/dariuszseweryn/RxAndroidBle) library, though I think the scope of my question lies closer with the use of RxJava than with the particular operation of the BLE library.

I use [RxKotlin](https://github.com/ReactiveX/RxKotlin) in some places, though that library hasn't been updated in some time. That's why I usually prefer RxJava for the core Rx features, and why I'm posting here.

## Final thoughts

I know it's possible to write new operator implementations, but wanted to reach out to learn if anybody else had tackled a problem like this before. I would be surprised if I were the first, though I didn't see this operator in the RxJava library.

- Does this exist, but is called something else?
- Do you think the code I'm writing is an antipattern?
- How would the Rx experts here approach my problem if the operator doesn't exist?

Thanks for your time! :)

**Comment by akarnokd** [comment]
I think `replay(1).refCount()` should behave as you'd expect:

```java
PublishSubject<Integer> ps = PublishSubject.create();

var o1 = Observable.<Integer>defer(() -> {
    System.out.println("Subscribed");
    return ps;
})
.doOnDispose(() -> System.out.println("Unsubscribed"))
.replay(1).refCount();

o1.subscribe().dispose();
System.out.println(ps.hasObservers());
o1.subscribe().dispose();
```

Which prints two "Subscribed" so it does reconnect.

**Comment by fraune** [comment]
Thanks for the sanity check on this. That is also what I expected. I'm digging into it a little deeper, but I now suspect my problem lies elsewhere.

**Comment by fraune** [comment]
Okay, I found the issue. As they say, "the call was coming from inside my own house". Some silly lifecycle was retriggering a stream, and I misunderstood the symptoms, since I am less experienced with using a pattern like `.replay(1).refCount()`.

@akarnokd I appreciate your quick response, which helped me root out the problem! Cheers!
