### ISSUE TITLE
ObserveOnObserver violates Observer not-null contract on drainFuseable

### ISSUE THREAD

**Issue by fsbarata** [ReactiveX/RxJava#7805]
The Observer contract requires a NotNull value in the onNext, but there is at least one operator which pushes a null to it (ObserveOn).

Here's a simple test to reproduce this exception (in kotlin):

	class ObserverFuseErrorTest {
		class MyObservable<T: Any>(private val source: Observable<T>): Observable<T>() {
			override fun subscribeActual(observer: Observer<in T>) {
				source.subscribe(object : Observer<T> {
					var done = false
					override fun onSubscribe(d: Disposable) {
						observer.onSubscribe(d)
					}
					override fun onError(e: Throwable) {
						done = true
						observer.onError(e)
					}
					override fun onComplete() {
						done = true
						observer.onComplete()
					}
					override fun onNext(t: T) {
						if (done) return
						observer.onNext(t)
					}
				})
			}
		}
	
		@Test
		fun errors() {
			val subject = BehaviorSubject.createDefault(5)
			val observer = MyObservable(
				subject
					.observeOn(Schedulers.computation())
			)
				.observeOn(Schedulers.computation())
				.test()
	
			Thread.sleep(500)
			observer.assertValues(5)
		}
	}

Causes an exception with:
java.lang.NullPointerException: Parameter specified as non-null is null: method ObserverFuseErrorTest$MyObservable$subscribeActual$1.onNext, parameter t
	at ObserverFuseErrorTest$MyObservable$subscribeActual$1.onNext(ObserverFuseErrorTest.kt)
	at io.reactivex.rxjava3.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.drainFused(ObservableObserveOn.java:230)
	at io.reactivex.rxjava3.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.run(ObservableObserveOn.java:254)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:80)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:71)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1589)

The error happens because at some point there is a fusion in the ObserveOnObserver, and the drainFused calls onNext with null (line 230):

        void drainFused() {
            int missed = 1;

            for (;;) {
            ...

                downstream.onNext(null);

I'm not sure this was intentional but it leads to crashes on kotlin.

**Comment by akarnokd** [comment]
Pushing `null` is due to the so-called operator fusion in RxJava.

This should be rarely a problem but you implemented your operator incorrectly as one should never forward the upstream's `Subscription` to the downstream directly:

```kotlin
override fun onSubscribe(d: Disposable) {
	observer.onSubscribe(d)
}
```

Try with
```kotlin
override fun onSubscribe(d: Disposable) {
     val cd = CompositeDisposable()
     cd.add(d)
     observer.onSubscribe(cd)
}
```

**Comment by akarnokd** [comment]
From the [operator wiki](https://github.com/ReactiveX/RxJava/wiki/Writing-operators-for-2.0), applies to RxJava 3 too

> Important: when implementing operators for Flowable and Observable in RxJava 2.x, you are not allowed to pass along an upstream Subscription or Disposable to the child Subscriber/Observer when the operator logic itself doesn't require hooking the request/cancel/dispose calls. The reason for this is how operator-fusion is implemented on top of Subscription and Disposable passing through onSubscribe in RxJava 2.x (and in Reactor 3).

**Comment by fsbarata** [comment]
Thanks for the clarification of the restriction in delegation, that was indeed what caused the problem (as the downstream is fuseable).

Just curious:
Why did you decide not to extend the Observer, like FuseableObserver, to avoid calling the onNext with a meaningful "null"?

In any case, thanks for the great work.

**Comment by akarnokd** [comment]
Avoid many instanceof checks, avoid megamorphic method call sites. It looked like a nice internal optimization several years ago. As long as it remains internal affair, it should keep working.

**Comment by fsbarata** [comment]
Thanks for spending the time to respond and sharing that. I will close this now.
