### ISSUE TITLE
Generics Help Please?

### ISSUE THREAD

**Issue by benjchristensen** [ReactiveX/RxJava#858]
Generics have me stumped on the `merge` operator. The functionality is fine, but only if I leave it untyped.

All other operators I'm using `lift` with are okay, but I can't get this one.

``` java
// this doesn't compile
    public final static <T> Observable<T> merge(Observable<? extends Observable<? extends T>> source) {
        return source.lift(new OperatorMerge<T>()); 
    }

// this compiles with untyped warnings (no generic) and functions
    public final static <T> Observable<T> merge(Observable<? extends Observable<? extends T>> source) {
        return source.lift(new OperatorMerge()); 
    }

// this compiles (but is only merging itself so not very helpful)
    public Observable<T> mergeSelf() {
        return from(this).lift(new OperatorMerge<T>());
    }

// this doesn't compile
    public Observable<T> mergeSelfWithAnother(Observable<? extends T> other) {
        return from(this, other).lift(new OperatorMerge<T>());
    }
```

Here is the compilation error:

```
/Users/bechristensen/development/github/RxJavaFork/rxjava-core/src/main/java/rx/Observable.java:1780: error: method lift in class Observable<T#1> cannot be applied to given types;
        return source.lift(new OperatorMerge<T>());
                     ^
  required: Operator<R,CAP#1>
  found: OperatorMerge<T#2>
  reason: no instance(s) of type variable(s) R exist so that argument type OperatorMerge<T#2> conforms to formal parameter type Operator<R,CAP#1>
  where R,T#1,T#2 are type-variables:
    R extends Object declared in method <R>lift(Operator<R,T#1>)
    T#1 extends Object declared in class Observable
    T#2 extends Object declared in method <T#2>merge(Observable<? extends Observable<? extends T#2>>)
  where CAP#1 is a fresh type-variable:
    CAP#1 extends Observable<? extends T#2> from capture of ? extends Observable<? extends T#2>
```

**Comment by IgorGanapolsky** [comment]
I am getting the same compilation error now.  Using `io.reactivex:rxjava:1.0.10`.  What is the solution?

**Comment by akarnokd** [comment]
@IgorGanapolsky what is the code exactly that doesn't compile?

**Comment by IgorGanapolsky** [comment]
@akarnokd I have this code:
`return plugshareService.getLocationInfo(locationId).
                map(new PlugshareResponseToLocation()).
                subscribeOn(Schedulers.io()).
                observeOn(AndroidSchedulers.mainThread());`

And I get this error:
> Error:(28, 60) error: method map in class Observable<T> cannot be applied to given types;
required: Func1<? super EVgoLocation,? extends R>
found: PlugshareResponseToLocation
reason: cannot infer type-variable(s) R
(argument mismatch; PlugshareResponseToLocation cannot be converted to Func1<? super EVgoLocation,? extends R>)
where R,T are type-variables:
R extends Object declared in method <R>map(Func1<? super T,? extends R>)
T extends Object declared in class Observable

**Comment by IgorGanapolsky** [comment]
Nevermind, I solved it.  I have to use this in my Retrofit Observable interface:
`@POST("/locations/{id}")
    Observable<PlugshareResponse> getLocationInfo(@Path("id") String id);`

instead of 
`@POST("/locations/{id}")
    Observable<EVgoLocation> getLocationInfo(@Path("id") String id);`
