### ISSUE TITLE
Is there any way to get a Scheduler from OnSubscribe function?

### ISSUE THREAD

**Issue by nsk-mironov** [ReactiveX/RxJava#941]
Hello.

My `Observable` is very simple and looks like:

``` java
Observable.create(new Observable.OnSubscribe<Content>() {
    @Override
    public void call(final Subscriber<? super Content> subscriber) {
        final ContentObserver observer = new ContentObserver() {
            @Override
            public void onContentChanged() {
                subscriber.onNext(loadContent());
            }
        };

        subscriber.add(Subscriptions.create(new Action0() {
            @Override
            public void call() {
                unregisterContentObserver(observer);
            }
        }));

        registerContentObserver(observer);
        subscriber.onNext(loadContent());
    }
});
```

`loadContent` is a heavy operation and have to be executed on the background thread (which is provided by the `Scheduler` that I pass to `subscribeOn` method).

**PROBLEM**
`onContentChanged` is always invoked from the UI thread and this cannot be changed, so I need to reschedule `loadContent` call to the background thread, but I failed to find a way to get a current `Scheduler`. 

What is the right way to do it?

**Comment by weefbellington** [comment]
A bit of a necro but I would also find this to be a useful feature. I'd like to be able to do some work in an inner Observable (or an Operator) and return control flow to the original subscribeOn thread when the work is done. `Schedulers.tramploline()` seemed promising, but when I tested it it seemed to capture the current thread context too late -- at the time of `schedule` and not the time of `createWorker`.

**Comment by akarnokd** [comment]
You can wrap over a single threaded `ExecutorService` with `Schedulers.from()` and use it as many times as you wish to put tasks back to the same executor. If you have multiple independent instantiations of the same sequence, you can use `defer()` and create the single threaded Scheduler in there:

```java
Observable.defer(() -> {
    ExecutorService pool = Execturos.newFixedThreadPool(1);
    Scheduler s = Schedulers.from(pool);
    return Observable.just(1).subscribeOn(s)
              .map(v -> v + 1)
              .observeOn(Schedulers.io())
              .flatMap(v -> Observable.range(v, 2))
              .observeOn(s)
              .doOnNext(System.out::println)
              .doOnUnsubscribe(() -> pool.shutdown());
});
```

**Comment by Ghedeon** [comment]
I think @benjchristensen nailed it.
I believe `Schedulers.current()` could be very useful for wrapping some non-rx code that is switching threads for some reason. Happens on Android often, when callback is called on main thread. Consider this example:
```java
private static class MyOnSubscribe implements ObservableOnSubscribe<Foo> {
    @Override
    public void subscribe(ObservableEmitter<Foo> emitter) throws Exception {
        // worker thread
        callbackManager.registerCallback( //some sdk method that always delivers on main
                new Callback() {
                    @Override
                    public void onSuccess(@NonNull Foo result) {
                        // Main Thread. How to move onSuccess() back to worker?
                        emitter.onSuccess(result);
                    }
                }
         ...
        );
    }
}
```
Yes, I can just leave it as it is, let it deliver on `main` and fix it later with `observeOn`. But it just feels right to do it here, rather than outside.

EDIT: onSubscribe --> observeOn

**Comment by akarnokd** [comment]
@Ghedeon This is what `observeOn` stands for:

```java
Observable.create(new MyOnSubscribe())
.observeOn(Schedulers.computation())
.map(...)
.filter(...)
.observeOn(AndroidSchedulers.mainThread())
.subscribe(...);
```

**Comment by Ghedeon** [comment]
@akarnokd Right, no question it's gonna work. It just bothers me, that it's not clean, internal implementation introduced some mess and I'm exposing this crooked behavior of `MyOnSubscribe` and make consumers of this class deal with it. Adding comments like "Note: always on main", etc. Also, normally I would pass this Observable up, without having a single `observeOn/subscribeOn` and at the very end inject a Scheduler (using DI). But now I'm forced to inject it much earlier and in many places. It kinda changes the flow, it's subtle but definitely, makes a difference.

**Comment by lwasyl** [comment]
Sorry for digging up the thread, but we're facing the same issue as OP -- callback is called on a different thread than the subscription, and we'd like to emit value on the original `subscribeOn` scheduler anyway. Did anything change with RxJava2? I don't believe https://github.com/ReactiveX/RxJava/issues/941#issuecomment-125480042 is sufficient if we really care about going back to the same scheduler without having to inject it manually. I can also open a new issue if that's more appropriate
