### ISSUE TITLE
How to throw an exception from within an Observer

### ISSUE THREAD

**Issue by Dorvaryn** [ReactiveX/RxJava#969]
Hi,

I am trying to make the app fail fast when something is going wrong from the Observer.
I was surprised to see that the Exception was swallowed by RxJava.

Here is a sample I tried :

``` java

 Observable.error(new Exception()).subscribe(new Observer<Object>() {
                    @Override
                    public void onCompleted() {

                    }

                    @Override
                    public void onError(Throwable e) {
                        throw new IllegalStateException("This should crash the app");
                    }

                    @Override
                    public void onNext(Object o) {

                    }
                });

```

Do I need do do anything specific to fail from within an Observer ?

**Comment by tatini1** [comment]
Hi ,My use case is to propagate the error from Observable to subscriber,but the same error is not visible to onError() method of subscriber ,instead it always shows
onError Must subsriber is called --- com.netflix.hystrix.exception.HystrixRuntimeException: CommandSR timed-out and no fallback available.
Below goes my code from where i throw the real exception
```java
 @Override
    protected Observable<String> construct() {
    	System.out.println("I am in construct of "+name+"::thread name: "+Thread.currentThread().getName());
        return Observable.create(new Observable.OnSubscribe<String>() {
        	
            @Override
            public void call(Subscriber<? super String> observer) {
                try {
                    if (!observer.isUnsubscribed()) {
                    	String response = HTTPClientHelper.searchSR("https://stg-step.am.health.ge.com/service/v2/service-event11/search/SHOWROOM24", "gJc1Ts8PWBrCmi5PcTtZJTk6JmyS", "212469169");
                        // a real example would do work like a network call here
                      
                    	observer.onNext(response + "!");
                        observer.onCompleted();
                        
                    }
                } catch (Exception e) {
                	System.out.println("Exception+++++++++++++++"+e.getMessage());
                    observer.onError(new RuntimeException("graceful onError"));
                }
            }
         } );
```

**Comment by akarnokd** [comment]
Despite you are using 1.x `create`, the code signals the exception correctly. I'd assume there is something in Hystrix that suppresses your error and I suggest asking on their page or better yet on Stackoverflow.

**Comment by tatini1** [comment]
ok sure thanks

**Comment by bejibx** [comment]
Sorry for reviving an old discussion again, but can someone help me?
> If the user provided Subscriber.onError throws an exception, it will always be treated as fatal (since onError itself failed).

 Is this still viable for RxJava 2?
